[Beef liver] and [Liver] are good examples of [Meat]
[tomato], [passon_fruit] and [huckleberry] are [Fruit]
[Humidifier], [Forced-air] and [Microwave oven] are all types of [Appliance]
[Parsley] and [Celeriac] are both examples of [Vegetables]
[Beet], [Peas] and [Mushrooms] are [Vegetables]
remember that i have [thanksgiving]
there is a [supermarket] called [roche bros] that I shop in pretty often
what are the supermarkets?	'roche bros'	['question_type_global', 'question_single_statement']
[roche bros] has [Celeriac] on sale!
what's currently on sale at [roche bros]?	'Celeriac'	['question_type_local']
[Jacket], [Scarf] and [Suit] are all different types of [Clothing]
[Herbs and spices] is a kind of [Vegetables]
what stores are there that I taught you?	'roche bros'	['question_type_global', 'question_single_statement']
[Liver] is on sale at [roche bros]
what items are on sale at [this supermarket]?	'Liver', 'Celeriac'	['question_type_local']
[Beef liver] is on sale at [this store]
what is on sale at [that store]?	'Beef liver', 'Liver', 'Celeriac'	['question_type_local']
[Washing machine] is a [Appliance]
[stater brothers] is a [supermarket]
[stater brothers] has [Liver] on sale!
[Beef liver] is on sale at [stater brothers]
what is on sale at [that store]?	'Beef liver', 'Liver'	['question_type_local']
[this store] has [Parsley], [Mushrooms] and [Celeriac] on sale!
what is on sale at [stater brothers]?	'Beef liver', 'Liver', 'Parsley', 'Celeriac', 'Mushrooms'	['question_type_local']
[bowl] is a [Gift]
[tomato], [huckleberry] and [passon_fruit] are on sale at [roche bros]
[roche bros] no longer has [passon_fruit], [Beef liver] and [Celeriac] on sale
[Parsley], [Herbs and spices] and [Beet] are all on sale at [roche bros]
is there a sale on [Celeriac] anywhere?	'stater brothers'	['question_type_local']
what are the stores?	'roche bros', 'stater brothers'	['question_type_global', 'question_single_statement']
Where is [Mushrooms] on sale?	'stater brothers'	['question_type_local']
show me all supermarkets that i tought you	'roche bros', 'stater brothers'	['question_type_global', 'question_single_statement']
What stores is [Beef liver] on sale at	'stater brothers'	['question_type_local']
[Icebox] is a [Appliance]
what's currently on sale at [stater brothers]?	'Beef liver', 'Liver', 'Parsley', 'Celeriac', 'Mushrooms'	['question_type_local']
[Mushrooms] is no longer on sale at [stater brothers]
what is on sale at [that store]?	'Beef liver', 'Liver', 'Parsley', 'Celeriac'	['question_type_local']
What stores is [Celeriac] on sale at	'stater brothers'	['question_type_local']
[Peas] is on sale at [that supermarket]
[Beef liver] is on sale at [roche bros]
[Railroad Avenue] is located in the [Homewood South] neighborhood
i think this [roche bros] is somewhere on [this street]
what are the supermarkets?	'roche bros', 'stater brothers'	['question_type_global', 'question_single_statement']
what neighborhood is [that street] in?	'Homewood South'	['question_type_local']
What stores is [huckleberry] on sale at	'roche bros'	['question_type_local']
what stores on [Railroad Avenue] have a sale on [vegetables]?	'roche bros'	['question_type_global', 'question_three_hop_statement']
[flowers] and [mirror] are both examples of [Gift]
what is on sale at [stater brothers]?	'Beef liver', 'Liver', 'Parsley', 'Celeriac', 'Peas'	['question_type_local']
show me all supermarkets that i tought you	'roche bros', 'stater brothers'	['question_type_global', 'question_single_statement']
[Surrey Lane] is in [East Hills]
What stores is [Parsley] on sale at	'stater brothers', 'roche bros'	['question_type_local']
what supermarkets are there on [Railroad Avenue]?	'roche bros'	['question_type_global', 'question_single_statement']
[I] am on [Railroad Avenue]
what's currently on sale at [roche bros]?	'Beef liver', 'Liver', 'tomato', 'huckleberry', 'Parsley', 'Beet', 'Herbs and spices'	['question_type_local']
is there a store nearby with a sale on [fruit] going on right now?	'roche bros'	['question_type_global', 'question_four_hop_statement']
What stores is [Herbs and spices] on sale at	'roche bros'	['question_type_local']
show me all stores near [Railroad Avenue] that have a sale on [fruit]	'roche bros'	['question_type_global', 'question_three_hop_statement']
what stores near [Railroad Avenue] have an ongoing sale on [Parsley]?	'roche bros'	['question_type_global', 'question_two_hop_statement']
is there a store nearby with a sale on [huckleberry] going on right now?	'roche bros'	['question_type_global', 'question_three_hop_statement']
what neighborhood is [Surrey Lane] in?	'East Hills'	['question_type_local']
what do stores near me have on sale?	'Beef liver', 'Liver', 'tomato', 'huckleberry', 'Parsley', 'Beet', 'Herbs and spices'	['question_type_global', 'question_three_hop_statement']
[Duck Liver], [Tripe] and [Calf liver] are all types of [Meat]
What stores is [Liver] on sale at	'stater brothers', 'roche bros'	['question_type_local']
show me all stores near [Railroad Avenue] that have a sale on [Beet]	'roche bros'	['question_type_global', 'question_two_hop_statement']
show me all supermarkets on [Railroad Avenue] that currently have a sale	'roche bros'	['question_type_global', 'question_two_hop_statement']
what's currently on sale at [stater brothers]?	'Beef liver', 'Liver', 'Parsley', 'Celeriac', 'Peas'	['question_type_local']
remember that i have [grading dinner party]
add the following for [this event]: [huckleberry] and [tomato]
is there a sale on [Parsley] anywhere?	'stater brothers', 'roche bros'	['question_type_local']
what stores are there that I taught you?	'roche bros', 'stater brothers'	['question_type_global', 'question_single_statement']
what supermarkets are there on [Railroad Avenue]?	'roche bros'	['question_type_global', 'question_single_statement']
what are the supermarkets?	'roche bros', 'stater brothers'	['question_type_global', 'question_single_statement']
show me all of the supermarkets	'roche bros', 'stater brothers'	['question_type_global', 'question_single_statement']
is there a store nearby with a sale on [tomato] going on right now?	'roche bros'	['question_type_global', 'question_three_hop_statement']
show me all stores near [Railroad Avenue] that have a sale on [fruit]	'roche bros'	['question_type_global', 'question_three_hop_statement']
does any store nearby have [fruit] on sale?	'roche bros'	['question_type_global', 'question_four_hop_statement']
show me all supermarkets near [Railroad Avenue]	'roche bros'	['question_type_global', 'question_single_statement']
what items that I have to buy currently are on sale near me?	'tomato', 'huckleberry'	['question_type_global', 'question_four_hop_statement']
show me all stores on [Railroad Avenue] that currently have a sale on [vegetables]	'roche bros'	['question_type_global', 'question_three_hop_statement']
what stores near [Railroad Avenue] have an ongoing sale on [fruit]?	'roche bros'	['question_type_global', 'question_three_hop_statement']
show me all stores on [Railroad Avenue] that currently have a sale on [Liver]	'roche bros'	['question_type_global', 'question_two_hop_statement']
Where is [Liver] on sale?	'stater brothers', 'roche bros'	['question_type_local']
show me all of the supermarkets on [Railroad Avenue]	'roche bros'	['question_type_global', 'question_single_statement']
is there anything on sale at a store nearby?	'Beef liver', 'Liver', 'tomato', 'huckleberry', 'Parsley', 'Beet', 'Herbs and spices'	['question_type_global', 'question_three_hop_statement']
show me all supermarkets on [Railroad Avenue] that currently have a sale	'roche bros'	['question_type_global', 'question_two_hop_statement']
what neighborhood am I currently in?	'Homewood South'	['question_type_local']
what neighborhood is [Railroad Avenue] in?	'Homewood South'	['question_type_local']
is there a store near my location is having a sale on [fruit]?	'roche bros'	['question_type_global', 'question_four_hop_statement']
are there any stores nearby that have a sale on [fruit]?	'roche bros'	['question_type_global', 'question_four_hop_statement']
what are the supermarkets on [Railroad Avenue]?	'roche bros'	['question_type_global', 'question_single_statement']
this specific [stater brothers] is on [Surrey Lane]
[Beet] and [Mushrooms] are on sale at [that supermarket]
show me all stores on [Railroad Avenue] that currently have a sale on [meat]	'roche bros'	['question_type_global', 'question_three_hop_statement']
[Skirt] and [Lingerie] are types of [Clothing]
what supermarkets are there?	'roche bros', 'stater brothers'	['question_type_global', 'question_single_statement']
does any store nearby have any of the items i need on sale?	'roche bros'	['question_type_global', 'question_four_hop_statement']
is there any [fruit] that I have to buy currently are on sale?	'tomato', 'huckleberry'	['question_type_global', 'question_three_hop_statement']
i need to get [Jacket] and [Lingerie] for [thanksgiving]
what supermarkets are there on [Railroad Avenue]?	'roche bros'	['question_type_global', 'question_single_statement']
show me all stores near [Surrey Lane]	'stater brothers'	['question_type_global', 'question_single_statement']
Where is [Celeriac] on sale?	'stater brothers'	['question_type_local']
what are the supermarkets?	'roche bros', 'stater brothers'	['question_type_global', 'question_single_statement']
what are the supermarkets on [Railroad Avenue]?	'roche bros'	['question_type_global', 'question_single_statement']
[stater brothers] has [Duck Liver] on sale!
what do i have on shopping list for [grading dinner party]?	'tomato', 'huckleberry'	['question_type_local']
is there a store nearby with a sale on [meat] going on right now?	'roche bros'	['question_type_global', 'question_four_hop_statement']
is there a store near my location is having a sale on [meat]?	'roche bros'	['question_type_global', 'question_four_hop_statement']
what are the stores on [Surrey Lane]?	'stater brothers'	['question_type_local']
what stores near [Surrey Lane] have an ongoing sale on [Duck Liver]?	'stater brothers'	['question_type_global', 'question_two_hop_statement']
what stores near [Railroad Avenue] have an ongoing sale on [Beef liver]?	'roche bros'	['question_type_global', 'question_two_hop_statement']
what neighborhood am I in?	'Homewood South'	['question_type_local']
is there a store near my location is having a sale on [vegetables]?	'roche bros'	['question_type_global', 'question_four_hop_statement']
What stores is [that thing] on sale at	'stater brothers'	['question_type_local']
what stores near [Surrey Lane] have an ongoing sale on [vegetables]?	'stater brothers'	['question_type_global', 'question_three_hop_statement']
[passon_fruit] is on sale at [roche bros]
are there any [fruit] that i need to get?	'tomato', 'huckleberry'	['question_type_global', 'question_two_hop_statement']
show me all supermarkets on [Railroad Avenue] that currently have a sale	'roche bros'	['question_type_global', 'question_two_hop_statement']
is there a store nearby with a sale on [vegetables] going on right now?	'roche bros'	['question_type_global', 'question_four_hop_statement']
is there a sale on [Parsley] anywhere?	'stater brothers', 'roche bros'	['question_type_local']
show me all stores on [Surrey Lane] that currently have a sale on [meat]	'stater brothers'	['question_type_global', 'question_three_hop_statement']
What do I need to buy [tomato] for?	'grading dinner party'	['question_type_local']
Where is [Beet] on sale?	'stater brothers', 'roche bros'	['question_type_local']
does any store nearby have anything on sale?	'roche bros'	['question_type_global', 'question_three_hop_statement']
What stores is [passon_fruit] on sale at	'roche bros'	['question_type_local']
are there any items on my shopping list for [grading dinner party] that there is a sale on?	'tomato', 'huckleberry'	['question_type_global', 'question_two_hop_statement']
are there any items on my shopping list that there is a sale on?	'tomato', 'huckleberry'	['question_type_global', 'question_two_hop_statement']
is there any [fruit] on my list that's on sale somewhere?	'tomato', 'huckleberry'	['question_type_global', 'question_three_hop_statement']
show me all stores near [Surrey Lane] that have a sale on [vegetables]	'stater brothers'	['question_type_global', 'question_three_hop_statement']
are there any stores nearby that have a sale on [meat]?	'roche bros'	['question_type_global', 'question_four_hop_statement']
What stores is [huckleberry] on sale at	'roche bros'	['question_type_local']
show me all of the stores	'roche bros', 'stater brothers'	['question_type_global', 'question_single_statement']
is there a sale on any [fruit] on my shopping list?	'tomato', 'huckleberry'	['question_type_global', 'question_three_hop_statement']
what items that I have to buy currently are on sale?	'tomato', 'huckleberry'	['question_type_global', 'question_two_hop_statement']
what is on sale at [stater brothers]?	'Beef liver', 'Liver', 'Parsley', 'Celeriac', 'Beet', 'Peas', 'Mushrooms', 'Duck Liver'	['question_type_local']
what is my shopping list?	'tomato', 'huckleberry', 'Jacket', 'Lingerie'	['question_type_global', 'question_single_statement']
show me all of the stores on [Railroad Avenue]	'roche bros'	['question_type_global', 'question_single_statement']
are there any stores nearby that have a sale on [fruit]?	'roche bros'	['question_type_global', 'question_four_hop_statement']
what kind of [clothing] do I need to get?	'Jacket', 'Lingerie'	['question_type_global', 'question_two_hop_statement']
i think [Route 64] is in [Homewood South]
what items are on sale at [stater brothers]?	'Beef liver', 'Liver', 'Parsley', 'Celeriac', 'Beet', 'Peas', 'Mushrooms', 'Duck Liver'	['question_type_local']
what items that I have to buy currently are on sale?	'tomato', 'huckleberry'	['question_type_global', 'question_two_hop_statement']
is there anything on my list that's on sale somewhere near my current location?	'tomato', 'huckleberry'	['question_type_global', 'question_four_hop_statement']
are there any items on my shopping list for [grading dinner party] that there is a sale on?	'tomato', 'huckleberry'	['question_type_global', 'question_two_hop_statement']
[Duck Liver] and [Tripe] are all on sale at [roche bros]
is there a sale on any items on my shopping list where i am?	'tomato', 'huckleberry'	['question_type_global', 'question_four_hop_statement']
what are the supermarkets?	'roche bros', 'stater brothers'	['question_type_global', 'question_single_statement']
what items are on sale at [roche bros]?	'Beef liver', 'Liver', 'tomato', 'passon_fruit', 'huckleberry', 'Parsley', 'Beet', 'Herbs and spices', 'Duck Liver', 'Tripe'	['question_type_local']
is there a store nearby with a sale on [vegetables] going on right now?	'roche bros'	['question_type_global', 'question_four_hop_statement']
is there a sale on any items on my shopping list?	'tomato', 'huckleberry'	['question_type_global', 'question_two_hop_statement']
what items that I have to buy for [grading dinner party] currently are on sale?	'tomato', 'huckleberry'	['question_type_global', 'question_two_hop_statement']
[roche bros] doesn't have [Beef liver] on sale anymore
is there a store nearby with any of the items on my shopping list on sale?	'roche bros'	['question_type_global', 'question_four_hop_statement']
are there any items on my shopping list that there is a sale on at a store nearby?	'tomato', 'huckleberry'	['question_type_global', 'question_four_hop_statement']
what items are on sale at [stater brothers]?	'Beef liver', 'Liver', 'Parsley', 'Celeriac', 'Beet', 'Peas', 'Mushrooms', 'Duck Liver'	['question_type_local']
what stores on [Railroad Avenue] have a sale?	'roche bros'	['question_type_global', 'question_two_hop_statement']
show me all stores on [Surrey Lane] that currently have a sale on [vegetables]	'stater brothers'	['question_type_global', 'question_three_hop_statement']
is there a sale on any items on my shopping list where i am?	'tomato', 'huckleberry'	['question_type_global', 'question_four_hop_statement']
what stores are there that I taught you?	'roche bros', 'stater brothers'	['question_type_global', 'question_single_statement']
What stores is [Peas] on sale at	'stater brothers'	['question_type_local']
is there a store near my location that has what i need on sale?	'roche bros'	['question_type_global', 'question_four_hop_statement']
what items that I have to buy for [grading dinner party] currently are on sale?	'tomato', 'huckleberry'	['question_type_global', 'question_two_hop_statement']
[Beef heart], [Rabbit] and [Venison] are [Meat]
is there a store near my location is having a sale on [tomato]?	'roche bros'	['question_type_global', 'question_three_hop_statement']
is there a store near my location is having a sale on [vegetables]?	'roche bros'	['question_type_global', 'question_four_hop_statement']
[passon_fruit], [tomato] and [huckleberry] are on sale at [stater brothers]
[huckleberry], [Mushrooms] and [Beet] stopped being on sale at [stater brothers]
What stores is [Beef liver] on sale at	'stater brothers'	['question_type_local']
show me all stores on [Surrey Lane] that currently have a sale	'stater brothers'	['question_type_global', 'question_two_hop_statement']
what stores near [Surrey Lane] have an ongoing sale on [Beef liver]?	'stater brothers'	['question_type_global', 'question_two_hop_statement']
what is on sale at [stater brothers]?	'Beef liver', 'Liver', 'tomato', 'passon_fruit', 'Parsley', 'Celeriac', 'Peas', 'Duck Liver'	['question_type_local']
show me all stores on [Railroad Avenue] that currently have a sale on [passon_fruit]	'roche bros'	['question_type_global', 'question_two_hop_statement']
what kind of [clothing] do I need to get?	'Jacket', 'Lingerie'	['question_type_global', 'question_two_hop_statement']
what stores on [Railroad Avenue] have a sale?	'roche bros'	['question_type_global', 'question_two_hop_statement']
Where is [Beet] on sale?	'roche bros'	['question_type_local']
is there a store nearby with a sale on [vegetables] going on right now?	'roche bros'	['question_type_global', 'question_four_hop_statement']
show me all stores on [Surrey Lane] that currently have a sale on [meat]	'stater brothers'	['question_type_global', 'question_three_hop_statement']
what stores near [Surrey Lane] have an ongoing sale on [fruit]?	'stater brothers'	['question_type_global', 'question_three_hop_statement']
what are the supermarkets?	'roche bros', 'stater brothers'	['question_type_global', 'question_single_statement']
is there a store near my location is having a sale on [meat]?	'roche bros'	['question_type_global', 'question_four_hop_statement']
what stores near [Railroad Avenue] have an ongoing sale on [Liver]?	'roche bros'	['question_type_global', 'question_two_hop_statement']
show me all stores on [Surrey Lane] that currently have a sale on [vegetables]	'stater brothers'	['question_type_global', 'question_three_hop_statement']
What stores is [Herbs and spices] on sale at	'roche bros'	['question_type_local']
is there a sale on any items on my shopping list where i am?	'tomato', 'huckleberry'	['question_type_global', 'question_four_hop_statement']
show me all stores on [Surrey Lane] that currently have a sale on [fruit]	'stater brothers'	['question_type_global', 'question_three_hop_statement']
i often shop at [key food], which is my local [supermarket]
is there a store nearby with a sale on [fruit] going on right now?	'roche bros'	['question_type_global', 'question_four_hop_statement']
what do i need to buy?	'tomato', 'huckleberry', 'Jacket', 'Lingerie'	['question_type_global', 'question_single_statement']
what stores near [Surrey Lane] have an ongoing sale?	'stater brothers'	['question_type_global', 'question_two_hop_statement']
what are the stores?	'roche bros', 'stater brothers', 'key food'	['question_type_global', 'question_single_statement']
what stores near [Railroad Avenue] have an ongoing sale?	'roche bros'	['question_type_global', 'question_two_hop_statement']
show me all stores near [Surrey Lane]	'stater brothers'	['question_type_global', 'question_single_statement']
what items are on sale at [stater brothers]?	'Beef liver', 'Liver', 'tomato', 'passon_fruit', 'Parsley', 'Celeriac', 'Peas', 'Duck Liver'	['question_type_local']
are there any [clothing] that i need to get?	'Jacket', 'Lingerie'	['question_type_global', 'question_two_hop_statement']
are there any stores nearby that have a sale on [Liver]?	'roche bros'	['question_type_global', 'question_three_hop_statement']
is there anything on my list that's on sale somewhere near my current location?	'tomato', 'huckleberry'	['question_type_global', 'question_four_hop_statement']
[that store] has [Tripe] and [Venison] on sale!
i think this [key food] is somewhere on [Route 64]
what items are on sale at [this supermarket]?	'Tripe', 'Venison'	['question_type_local']
is there anything on my list that's on sale somewhere?	'tomato', 'huckleberry'	['question_type_global', 'question_two_hop_statement']
what's currently on sale at [stater brothers]?	'Beef liver', 'Liver', 'tomato', 'passon_fruit', 'Parsley', 'Celeriac', 'Peas', 'Duck Liver'	['question_type_local']
[key chain], [phone] and [piano] are all different types of [Gift]
what stores on [Surrey Lane] have a sale on [meat]?	'stater brothers'	['question_type_global', 'question_three_hop_statement']
what [fruit] do i need to buy?	'tomato', 'huckleberry'	['question_type_global', 'question_two_hop_statement']
does any store nearby have [meat] on sale?	'roche bros'	['question_type_global', 'question_four_hop_statement']
what is on sale near my current location?	'Liver', 'tomato', 'passon_fruit', 'huckleberry', 'Parsley', 'Beet', 'Herbs and spices', 'Duck Liver', 'Tripe'	['question_type_global', 'question_three_hop_statement']
what supermarkets near [Surrey Lane] have an ongoing sale?	'stater brothers'	['question_type_global', 'question_two_hop_statement']
[Celeriac] and [Peas] are on sale at [key food]
is there a sale on [Parsley] anywhere?	'stater brothers', 'roche bros'	['question_type_local']
[watch] and [greeting card] are types of [Gift]
Where is [passon_fruit] on sale?	'stater brothers', 'roche bros'	['question_type_local']
what stores on [Railroad Avenue] have a sale?	'roche bros'	['question_type_global', 'question_two_hop_statement']
show me all stores	'roche bros', 'stater brothers', 'key food'	['question_type_global', 'question_single_statement']
What do I need to buy [tomato] for?	'grading dinner party'	['question_type_local']
what kind of [fruit] do I need to get?	'tomato', 'huckleberry'	['question_type_global', 'question_two_hop_statement']
show me all stores near [Railroad Avenue] that have a sale on [huckleberry]	'roche bros'	['question_type_global', 'question_two_hop_statement']
does any store nearby have [fruit] on sale?	'roche bros'	['question_type_global', 'question_four_hop_statement']
what items that I have to buy currently are on sale?	'tomato', 'huckleberry'	['question_type_global', 'question_two_hop_statement']
what stores on [Railroad Avenue] have a sale?	'roche bros'	['question_type_global', 'question_two_hop_statement']
what kind of [clothing] do I need to get?	'Jacket', 'Lingerie'	['question_type_global', 'question_two_hop_statement']
there is a [supermarket] called [giant eagle] on [Railroad Avenue]
is there anything on my list that's on sale somewhere?	'tomato', 'huckleberry'	['question_type_global', 'question_two_hop_statement']
what items that I have to buy currently are on sale near me?	'tomato', 'huckleberry'	['question_type_global', 'question_four_hop_statement']
what stores near [Railroad Avenue] have an ongoing sale on [fruit]?	'roche bros'	['question_type_global', 'question_three_hop_statement']
show me all stores near [Route 64] that have a sale	'key food'	['question_type_global', 'question_two_hop_statement']
what event do I need to buy [huckleberry] for	'grading dinner party'	['question_type_local']
show me all stores on [Route 64] that currently have a sale on [meat]	'key food'	['question_type_global', 'question_three_hop_statement']
what supermarkets on [Surrey Lane] have a sale?	'stater brothers'	['question_type_global', 'question_two_hop_statement']
show me all of the supermarkets	'roche bros', 'stater brothers', 'key food', 'giant eagle'	['question_type_global', 'question_single_statement']
is there a sale on any items on my shopping list?	'tomato', 'huckleberry'	['question_type_global', 'question_two_hop_statement']
[Rabbit] and [Duck Liver] are all on sale at [this store]
what supermarkets near [Route 64] have an ongoing sale?	'key food'	['question_type_global', 'question_two_hop_statement']
show me all stores on [Railroad Avenue] that currently have a sale on [Duck Liver]	'roche bros', 'giant eagle'	['question_type_global', 'question_two_hop_statement']
show me all stores on [Railroad Avenue] that currently have a sale	'roche bros', 'giant eagle'	['question_type_global', 'question_two_hop_statement']
is there anything on my list that's on sale somewhere near my current location?	'tomato', 'huckleberry'	['question_type_global', 'question_four_hop_statement']
is there a store nearby with a sale going on right now?	'giant eagle', 'roche bros'	['question_type_global', 'question_three_hop_statement']
does any store nearby have [vegetables] on sale?	'roche bros'	['question_type_global', 'question_four_hop_statement']
is there a sale on [tomato] anywhere?	'stater brothers', 'roche bros'	['question_type_local']
show me all of the supermarkets on [Route 64]	'key food'	['question_type_global', 'question_single_statement']
what is on sale near my current location?	'Liver', 'tomato', 'passon_fruit', 'huckleberry', 'Parsley', 'Beet', 'Herbs and spices', 'Duck Liver', 'Tripe', 'Rabbit'	['question_type_global', 'question_three_hop_statement']
what stores on [Railroad Avenue] have a sale on [meat]?	'roche bros', 'giant eagle'	['question_type_global', 'question_three_hop_statement']
what do stores near me have on sale?	'Liver', 'tomato', 'passon_fruit', 'huckleberry', 'Parsley', 'Beet', 'Herbs and spices', 'Duck Liver', 'Tripe', 'Rabbit'	['question_type_global', 'question_three_hop_statement']
is there a store nearby with a sale on [fruit] going on right now?	'roche bros'	['question_type_global', 'question_four_hop_statement']
is there a store near my location is having a sale?	'giant eagle', 'roche bros'	['question_type_global', 'question_three_hop_statement']
show me all supermarkets that i tought you	'roche bros', 'stater brothers', 'key food', 'giant eagle'	['question_type_global', 'question_single_statement']
is there a store nearby with a sale going on right now?	'giant eagle', 'roche bros'	['question_type_global', 'question_three_hop_statement']
does any store nearby have [meat] on sale?	'giant eagle', 'roche bros'	['question_type_global', 'question_four_hop_statement']
show me all stores on [Railroad Avenue] that currently have a sale on [vegetables]	'roche bros'	['question_type_global', 'question_three_hop_statement']
what do i need [tomato] for?	'grading dinner party'	['question_type_local']
does any store nearby have [vegetables] on sale?	'roche bros'	['question_type_global', 'question_four_hop_statement']
show me all stores near [Surrey Lane] that have a sale on [fruit]	'stater brothers'	['question_type_global', 'question_three_hop_statement']
[Celeriac] and [Peas] are all on sale at [roche bros]
what is on sale at [roche bros]?	'Liver', 'tomato', 'passon_fruit', 'huckleberry', 'Parsley', 'Celeriac', 'Beet', 'Peas', 'Herbs and spices', 'Duck Liver', 'Tripe'	['question_type_local']
are there any items on my shopping list that there is a sale on?	'tomato', 'huckleberry'	['question_type_global', 'question_two_hop_statement']
show me all supermarkets near [Surrey Lane] that have a sale	'stater brothers'	['question_type_global', 'question_two_hop_statement']
what are the supermarkets?	'roche bros', 'stater brothers', 'key food', 'giant eagle'	['question_type_global', 'question_single_statement']
what are the supermarkets on [Surrey Lane]?	'stater brothers'	['question_type_global', 'question_single_statement']
does any store nearby have [fruit] on sale?	'roche bros'	['question_type_global', 'question_four_hop_statement']
Do i have any [clothing] on my shopping list?	'Jacket', 'Lingerie'	['question_type_global', 'question_two_hop_statement']
what stores on [Railroad Avenue] have a sale on [vegetables]?	'roche bros'	['question_type_global', 'question_three_hop_statement']
What stores is [Celeriac] on sale at	'stater brothers', 'roche bros', 'key food'	['question_type_local']
is there a store near my location is having a sale?	'giant eagle', 'roche bros'	['question_type_global', 'question_three_hop_statement']
is there a store near my location is having a sale on [Peas]?	'roche bros'	['question_type_global', 'question_three_hop_statement']
is there a store near my location that has what i need on sale?	'roche bros'	['question_type_global', 'question_four_hop_statement']
what stores near [Route 64] have an ongoing sale?	'key food'	['question_type_global', 'question_two_hop_statement']
what stores near [Surrey Lane] have an ongoing sale on [vegetables]?	'stater brothers'	['question_type_global', 'question_three_hop_statement']
what are the things that i need to get?	'tomato', 'huckleberry', 'Jacket', 'Lingerie'	['question_type_global', 'question_single_statement']
[key food] has [Duck Liver] and [Beef heart] on sale!
Where is [Beef heart] on sale?	'key food'	['question_type_local']
[balloon] and [socks] are [Gift]
what stores are located on [Railroad Avenue]?	'giant eagle', 'roche bros'	['question_type_local']
show me all stores on [Railroad Avenue] that currently have a sale on [meat]	'roche bros', 'giant eagle'	['question_type_global', 'question_three_hop_statement']
is there a store near my location is having a sale on [vegetables]?	'roche bros'	['question_type_global', 'question_four_hop_statement']
does any store nearby have [Duck Liver] on sale?	'giant eagle', 'roche bros'	['question_type_global', 'question_three_hop_statement']
there is a [department store] called [saks off 5th] that I shop in pretty often
i think this [this store] is somewhere on [Railroad Avenue]
[this store] has [Lingerie] on sale!
what are the things that I need to get?	'tomato', 'huckleberry', 'Jacket', 'Lingerie'	['question_type_global', 'question_single_statement']
is there a store near my location is having a sale on [clothing]?	'saks off 5th'	['question_type_global', 'question_four_hop_statement']
show me all stores near [Surrey Lane] that have a sale	'stater brothers'	['question_type_global', 'question_two_hop_statement']
show me all supermarkets near [Railroad Avenue]	'roche bros', 'giant eagle'	['question_type_global', 'question_single_statement']
what's currently on sale at [roche bros]?	'Liver', 'tomato', 'passon_fruit', 'huckleberry', 'Parsley', 'Celeriac', 'Beet', 'Peas', 'Herbs and spices', 'Duck Liver', 'Tripe'	['question_type_local']
show me all supermarkets that i tought you	'roche bros', 'stater brothers', 'key food', 'giant eagle'	['question_type_global', 'question_single_statement']
show me all department stores on [Railroad Avenue] that currently have a sale	'saks off 5th'	['question_type_global', 'question_two_hop_statement']
i am pretty sure that [Country Club Road] is in [Homewood South]
is there a sale on [Lingerie] anywhere?	'saks off 5th'	['question_type_local']
show me all stores on [Railroad Avenue] that currently have a sale	'roche bros', 'giant eagle', 'saks off 5th'	['question_type_global', 'question_two_hop_statement']
is there anything on my list that's on sale somewhere near my current location?	'tomato', 'huckleberry', 'Lingerie'	['question_type_global', 'question_four_hop_statement']
is there a sale on any [fruit] on my shopping list?	'tomato', 'huckleberry'	['question_type_global', 'question_three_hop_statement']
i need to make sure to get [Suit] for [thanksgiving]
what do i have on shopping list for [that event]?	'Jacket', 'Suit', 'Lingerie'	['question_type_local']
[roche bros] has [Mushrooms] on sale!
[Peas] and [Liver] are no longer on sale at [roche bros]
what is on sale at [roche bros]?	'tomato', 'passon_fruit', 'huckleberry', 'Parsley', 'Celeriac', 'Beet', 'Mushrooms', 'Herbs and spices', 'Duck Liver', 'Tripe'	['question_type_local']
what stores are there on [Railroad Avenue]?	'roche bros', 'giant eagle', 'saks off 5th'	['question_type_global', 'question_single_statement']
what supermarkets are there?	'roche bros', 'stater brothers', 'key food', 'giant eagle'	['question_type_global', 'question_single_statement']
what are the things that I need to get?	'tomato', 'huckleberry', 'Jacket', 'Suit', 'Lingerie'	['question_type_global', 'question_single_statement']
is there a sale on [that meat] anywhere?	'stater brothers'	['question_type_local']
show me all stores near [Surrey Lane]	'stater brothers'	['question_type_global', 'question_single_statement']
what are the supermarkets?	'roche bros', 'stater brothers', 'key food', 'giant eagle'	['question_type_global', 'question_single_statement']
what department stores are there on [Railroad Avenue]?	'saks off 5th'	['question_type_global', 'question_single_statement']
Where is [that veggie] on sale?	'stater brothers', 'key food'	['question_type_local']
is there anything on my list that's on sale somewhere near my current location?	'tomato', 'huckleberry', 'Lingerie'	['question_type_global', 'question_four_hop_statement']
are there any stores nearby that have a sale on items that i need?	'roche bros', 'saks off 5th'	['question_type_global', 'question_four_hop_statement']
show me all of the supermarkets	'roche bros', 'stater brothers', 'key food', 'giant eagle'	['question_type_global', 'question_single_statement']
Do i have any [fruit] on my shopping list?	'tomato', 'huckleberry'	['question_type_global', 'question_two_hop_statement']
does any store nearby have [meat] on sale?	'giant eagle', 'roche bros'	['question_type_global', 'question_four_hop_statement']
show me all of the stores on [Railroad Avenue]	'roche bros', 'giant eagle', 'saks off 5th'	['question_type_global', 'question_single_statement']
make sure to buy [socks] and [balloon] for [thanksgiving]
does any store nearby have anything on sale?	'giant eagle', 'roche bros', 'saks off 5th'	['question_type_global', 'question_three_hop_statement']
what stores on [Railroad Avenue] have a sale on [fruit]?	'roche bros'	['question_type_global', 'question_three_hop_statement']
[Beef heart] is no longer on sale at [key food]
what is on sale at [that store]?	'Celeriac', 'Peas', 'Duck Liver', 'Tripe', 'Venison'	['question_type_local']
does any store nearby have [huckleberry] on sale?	'roche bros'	['question_type_global', 'question_three_hop_statement']
is there a store near my location is having a sale on [Tripe]?	'roche bros'	['question_type_global', 'question_three_hop_statement']
what items are on sale at nearby stores?	'tomato', 'passon_fruit', 'huckleberry', 'Parsley', 'Celeriac', 'Beet', 'Mushrooms', 'Herbs and spices', 'Duck Liver', 'Tripe', 'Lingerie', 'Rabbit'	['question_type_global', 'question_three_hop_statement']
what do i need to buy?	'tomato', 'huckleberry', 'Jacket', 'Suit', 'Lingerie', 'balloon', 'socks'	['question_type_global', 'question_single_statement']
what stores near [Railroad Avenue] have an ongoing sale on [fruit]?	'roche bros'	['question_type_global', 'question_three_hop_statement']
[joseph magnin] is a [department store]
is there a store nearby with a sale on [meat] going on right now?	'giant eagle', 'roche bros'	['question_type_global', 'question_four_hop_statement']
i think [Sherwood Drive] is in [Homewood South]
[this store] has [key chain], [watch] and [greeting card] on sale!
i think this [joseph magnin] is somewhere on [Sherwood Drive]
what is on sale at [joseph magnin]?	'key chain', 'watch', 'greeting card'	['question_type_local']
what are the stores?	'roche bros', 'stater brothers', 'key food', 'giant eagle', 'saks off 5th', 'joseph magnin'	['question_type_global', 'question_single_statement']
show me all stores on [Sherwood Drive] that currently have a sale	'joseph magnin'	['question_type_global', 'question_two_hop_statement']
what kind of [fruit] do I need to get?	'tomato', 'huckleberry'	['question_type_global', 'question_two_hop_statement']
[Humidifier] and [Microwave oven] are on sale at [joseph magnin]
show me all of the supermarkets on [Route 64]	'key food'	['question_type_global', 'question_single_statement']
show me all supermarkets on [Route 64] that currently have a sale	'key food'	['question_type_global', 'question_two_hop_statement']
what supermarkets are there?	'roche bros', 'stater brothers', 'key food', 'giant eagle'	['question_type_global', 'question_single_statement']
what neighborhood is [Sherwood Drive] in?	'Homewood South'	['question_type_local']
what [fruit] do i need to buy?	'tomato', 'huckleberry'	['question_type_global', 'question_two_hop_statement']
[quality foods] is a [supermarket]
what are the stores on [Route 64]?	'key food'	['question_type_local']
what stores near [Route 64] have an ongoing sale?	'key food'	['question_type_global', 'question_two_hop_statement']
show me all department stores near [Railroad Avenue] that have a sale	'saks off 5th'	['question_type_global', 'question_two_hop_statement']
show me all of the department stores on [Sherwood Drive]	'joseph magnin'	['question_type_global', 'question_single_statement']
is there a store near my location is having a sale on [fruit]?	'roche bros'	['question_type_global', 'question_four_hop_statement']
is there anything on sale at a store nearby?	'tomato', 'passon_fruit', 'huckleberry', 'Parsley', 'Celeriac', 'Beet', 'Mushrooms', 'Herbs and spices', 'Duck Liver', 'Tripe', 'Lingerie', 'Rabbit'	['question_type_global', 'question_three_hop_statement']
what is my shopping list?	'tomato', 'huckleberry', 'Jacket', 'Suit', 'Lingerie', 'balloon', 'socks'	['question_type_global', 'question_single_statement']
is there anything on my list that's on sale somewhere near my current location?	'tomato', 'huckleberry', 'Lingerie'	['question_type_global', 'question_four_hop_statement']
[Beef heart] is on sale at [roche bros]
[roche bros] doesn't have [Celeriac] and [Tripe] on sale anymore!
what items are on sale at [roche bros]?	'tomato', 'passon_fruit', 'huckleberry', 'Parsley', 'Beet', 'Mushrooms', 'Herbs and spices', 'Duck Liver', 'Beef heart'	['question_type_local']
what stores on [Surrey Lane] have a sale?	'stater brothers'	['question_type_global', 'question_two_hop_statement']
is there a sale on any [clothing] on my shopping list?	'Lingerie'	['question_type_global', 'question_three_hop_statement']
are there any stores nearby that have a sale on [meat]?	'giant eagle', 'roche bros'	['question_type_global', 'question_four_hop_statement']
What stores is [Parsley] on sale at	'stater brothers', 'roche bros'	['question_type_local']
what do i need to buy?	'tomato', 'huckleberry', 'Jacket', 'Suit', 'Lingerie', 'balloon', 'socks'	['question_type_global', 'question_single_statement']
is there any [fruit] that I have to buy currently are on sale?	'tomato', 'huckleberry'	['question_type_global', 'question_three_hop_statement']
show me all stores near [Surrey Lane] that have a sale on [Duck Liver]	'stater brothers'	['question_type_global', 'question_two_hop_statement']
is there a sale on [watch] anywhere?	'joseph magnin'	['question_type_local']
what department stores are there	'saks off 5th', 'joseph magnin'	['question_type_global', 'question_single_statement']
what stores are there on [Sherwood Drive]?	'joseph magnin'	['question_type_global', 'question_single_statement']
what items are on sale at [key food]?	'Celeriac', 'Peas', 'Duck Liver', 'Tripe', 'Venison'	['question_type_local']
what [fruit] do i need to buy?	'tomato', 'huckleberry'	['question_type_global', 'question_two_hop_statement']
what stores on [Railroad Avenue] have a sale?	'roche bros', 'giant eagle', 'saks off 5th'	['question_type_global', 'question_two_hop_statement']
show me all department stores near [Sherwood Drive]	'joseph magnin'	['question_type_global', 'question_single_statement']
show me all stores on [Surrey Lane] that currently have a sale	'stater brothers'	['question_type_global', 'question_two_hop_statement']
[banana], [satsuma] and [cherry] are all examples of [Fruit]
show me all stores on [Route 64] that currently have a sale on [meat]	'key food'	['question_type_global', 'question_three_hop_statement']
show me all of the stores on [Surrey Lane]	'stater brothers'	['question_type_global', 'question_single_statement']
are there any stores nearby that have a sale on [meat]?	'giant eagle', 'roche bros'	['question_type_global', 'question_four_hop_statement']
does any store nearby have [meat] on sale?	'giant eagle', 'roche bros'	['question_type_global', 'question_four_hop_statement']
what stores on [Sherwood Drive] have a sale on [gifts]?	'joseph magnin'	['question_type_global', 'question_three_hop_statement']
are there any stores nearby that have a sale on [vegetables]?	'roche bros'	['question_type_global', 'question_four_hop_statement']
show me all stores on [Railroad Avenue] that currently have a sale	'roche bros', 'giant eagle', 'saks off 5th'	['question_type_global', 'question_two_hop_statement']
What stores is [Celeriac] on sale at	'stater brothers', 'key food'	['question_type_local']
what stores on [Sherwood Drive] have a sale on [watch]?	'joseph magnin'	['question_type_global', 'question_two_hop_statement']
what department stores near [Sherwood Drive] have an ongoing sale?	'joseph magnin'	['question_type_global', 'question_two_hop_statement']
what stores on [Route 64] have a sale on [vegetables]?	'key food'	['question_type_global', 'question_three_hop_statement']
does any store nearby have any of the items i need on sale?	'roche bros', 'saks off 5th'	['question_type_global', 'question_four_hop_statement']
what are the stores?	'roche bros', 'stater brothers', 'key food', 'giant eagle', 'saks off 5th', 'joseph magnin', 'quality foods'	['question_type_global', 'question_single_statement']
[stater brothers] has [Tripe] on sale!
are there any stores nearby that have a sale on [vegetables]?	'roche bros'	['question_type_global', 'question_four_hop_statement']
what items do I need to get?	'tomato', 'huckleberry', 'Jacket', 'Suit', 'Lingerie', 'balloon', 'socks'	['question_type_global', 'question_single_statement']
is there a store nearby with any of the items on my shopping list on sale?	'roche bros', 'saks off 5th'	['question_type_global', 'question_four_hop_statement']
is there a store near my location that has what i need on sale?	'roche bros', 'saks off 5th'	['question_type_global', 'question_four_hop_statement']
What stores is [Celeriac] on sale at	'stater brothers', 'key food'	['question_type_local']
[Venison] and [Beef heart] are on sale at [giant eagle]
what items are on sale at [joseph magnin]?	'Humidifier', 'Microwave oven', 'key chain', 'watch', 'greeting card'	['question_type_local']
show me all stores on [Sherwood Drive] that currently have a sale	'joseph magnin'	['question_type_global', 'question_two_hop_statement']
is there a sale on [Beef heart] anywhere?	'giant eagle', 'roche bros'	['question_type_local']
what stores on [Route 64] have a sale?	'key food'	['question_type_global', 'question_two_hop_statement']
is there a sale on [watch] anywhere?	'joseph magnin'	['question_type_local']
is there a sale on any items on my shopping list where i am?	'tomato', 'huckleberry', 'Lingerie'	['question_type_global', 'question_four_hop_statement']
is there any [fruit] on my list that's on sale somewhere?	'tomato', 'huckleberry'	['question_type_global', 'question_three_hop_statement']
show me all of the supermarkets on [Railroad Avenue]	'roche bros', 'giant eagle'	['question_type_global', 'question_single_statement']
what are the stores on [Sherwood Drive]?	'joseph magnin'	['question_type_local']
is there a store near my location is having a sale on [vegetables]?	'roche bros'	['question_type_global', 'question_four_hop_statement']
does any store nearby have [fruit] on sale?	'roche bros'	['question_type_global', 'question_four_hop_statement']
does any store nearby have [vegetables] on sale?	'roche bros'	['question_type_global', 'question_four_hop_statement']
what [gifts] do i need to buy?	'balloon', 'socks'	['question_type_global', 'question_two_hop_statement']
what stores on [Sherwood Drive] have a sale on [appliances]?	'joseph magnin'	['question_type_global', 'question_three_hop_statement']
what are the department stores?	'saks off 5th', 'joseph magnin'	['question_type_global', 'question_single_statement']
what items are on sale at [saks off 5th]?	'Lingerie'	['question_type_local']
i need to get [Skirt] for [thanksgiving]
what things do I need to buy for [that event]	'Jacket', 'Suit', 'Skirt', 'Lingerie', 'balloon', 'socks'	['question_type_local']
what [fruit] do i need to buy?	'tomato', 'huckleberry'	['question_type_global', 'question_two_hop_statement']
are there any stores nearby that have a sale on [clothing]?	'saks off 5th'	['question_type_global', 'question_four_hop_statement']
please remind me to buy [Scarf] for [thanksgiving]
what is on sale at [giant eagle]?	'Duck Liver', 'Beef heart', 'Rabbit', 'Venison'	['question_type_local']
what stores on [Route 64] have a sale?	'key food'	['question_type_global', 'question_two_hop_statement']
is there a sale on any items on my shopping list where i am?	'tomato', 'huckleberry', 'Lingerie'	['question_type_global', 'question_four_hop_statement']
what do i need to buy?	'tomato', 'huckleberry', 'Jacket', 'Scarf', 'Suit', 'Skirt', 'Lingerie', 'balloon', 'socks'	['question_type_global', 'question_single_statement']
is there a sale on [Beet] anywhere?	'roche bros'	['question_type_local']
what stores near [Route 64] have an ongoing sale on [vegetables]?	'key food'	['question_type_global', 'question_three_hop_statement']
are there any stores nearby that have a sale on [clothing]?	'saks off 5th'	['question_type_global', 'question_four_hop_statement']
show me all department stores near [Sherwood Drive]	'joseph magnin'	['question_type_global', 'question_single_statement']
remove [this item] and [socks] from my shopping list for [that event]
add [watch] and [bowl] to my shopping list for [thanksgiving]
what stores are located on [Railroad Avenue]?	'giant eagle', 'roche bros', 'saks off 5th'	['question_type_local']
what items that I have to buy for [thanksgiving] currently are on sale?	'Lingerie', 'watch'	['question_type_global', 'question_two_hop_statement']
is there a sale on any items on my shopping list where i am?	'tomato', 'huckleberry', 'Lingerie'	['question_type_global', 'question_four_hop_statement']
does any store nearby have [clothing] on sale?	'saks off 5th'	['question_type_global', 'question_four_hop_statement']
what event do I need to buy [bowl] for	'thanksgiving'	['question_type_local']
is there a store near my location is having a sale on [clothing]?	'saks off 5th'	['question_type_global', 'question_four_hop_statement']
show me all supermarkets that i tought you	'roche bros', 'stater brothers', 'key food', 'giant eagle', 'quality foods'	['question_type_global', 'question_single_statement']
what do stores near me are have a sale on?	'tomato', 'passon_fruit', 'huckleberry', 'Parsley', 'Beet', 'Mushrooms', 'Herbs and spices', 'Duck Liver', 'Lingerie', 'Beef heart', 'Rabbit', 'Venison'	['question_type_global', 'question_three_hop_statement']
show me all of the stores	'roche bros', 'stater brothers', 'key food', 'giant eagle', 'saks off 5th', 'joseph magnin', 'quality foods'	['question_type_global', 'question_single_statement']
what department stores near [Railroad Avenue] have an ongoing sale?	'saks off 5th'	['question_type_global', 'question_two_hop_statement']
are there any stores nearby that have a sale on [vegetables]?	'roche bros'	['question_type_global', 'question_four_hop_statement']
what's currently on sale at [stater brothers]?	'Beef liver', 'Liver', 'tomato', 'passon_fruit', 'Parsley', 'Celeriac', 'Peas', 'Duck Liver', 'Tripe'	['question_type_local']
is there a sale on any [clothing] on my shopping list?	'Lingerie'	['question_type_global', 'question_three_hop_statement']
is there a store near my location that has what i need on sale?	'roche bros', 'saks off 5th'	['question_type_global', 'question_four_hop_statement']
what items that I have to buy for [grading dinner party] currently are on sale?	'tomato', 'huckleberry'	['question_type_global', 'question_two_hop_statement']
Where is [Humidifier] on sale?	'joseph magnin'	['question_type_local']
is there any [gifts] on my list that's on sale somewhere?	'watch'	['question_type_global', 'question_three_hop_statement']
what items that I have to buy currently are on sale near me?	'tomato', 'huckleberry', 'Lingerie'	['question_type_global', 'question_four_hop_statement']
are there any stores nearby that have a sale?	'giant eagle', 'roche bros', 'saks off 5th'	['question_type_global', 'question_three_hop_statement']
does any store nearby have [clothing] on sale?	'saks off 5th'	['question_type_global', 'question_four_hop_statement']
i don't need [balloon] and [Skirt] for [thanksgiving] anymore
what did i remove from [thanksgiving]?	'Scarf', 'Skirt', 'balloon', 'socks'	['question_type_local']
what department stores are there	'saks off 5th', 'joseph magnin'	['question_type_global', 'question_single_statement']
Do I need to buy any [gifts]?	'bowl', 'watch'	['question_type_global', 'question_two_hop_statement']
show me all department stores near [Sherwood Drive] that have a sale	'joseph magnin'	['question_type_global', 'question_two_hop_statement']
what are the things that I need to get?	'tomato', 'huckleberry', 'Jacket', 'Suit', 'bowl', 'Lingerie', 'watch'	['question_type_global', 'question_single_statement']
show me all stores on [Sherwood Drive] that currently have a sale on [gifts]	'joseph magnin'	['question_type_global', 'question_three_hop_statement']
is there anything that I need for [thanksgiving] that's on sale somewhere?	'Lingerie', 'watch'	['question_type_global', 'question_two_hop_statement']
show me all stores near [Route 64] that have a sale on [meat]	'key food'	['question_type_global', 'question_three_hop_statement']
is there a sale on [passon_fruit] anywhere?	'stater brothers', 'roche bros'	['question_type_local']
are there any stores nearby that have a sale on [fruit]?	'roche bros'	['question_type_global', 'question_four_hop_statement']
what stores are located on [Sherwood Drive]?	'joseph magnin'	['question_type_local']
does any store nearby have [fruit] on sale?	'roche bros'	['question_type_global', 'question_four_hop_statement']
what do stores near me have on sale?	'tomato', 'passon_fruit', 'huckleberry', 'Parsley', 'Beet', 'Mushrooms', 'Herbs and spices', 'Duck Liver', 'Lingerie', 'Beef heart', 'Rabbit', 'Venison'	['question_type_global', 'question_three_hop_statement']
there is a [supermarket] called [roche bros] on [Country Club Road]
what are the department stores on [Sherwood Drive]?	'joseph magnin'	['question_type_global', 'question_single_statement']
show me all stores on [Railroad Avenue] that currently have a sale on [clothing]	'saks off 5th'	['question_type_global', 'question_three_hop_statement']
show me all of the department stores	'saks off 5th', 'joseph magnin'	['question_type_global', 'question_single_statement']
are there any [clothing] that i need to get?	'Jacket', 'Suit', 'Lingerie'	['question_type_global', 'question_two_hop_statement']
What stores is [Duck Liver] on sale at	'giant eagle', 'stater brothers', 'roche bros', 'key food'	['question_type_local']
is there anything on my list that's on sale somewhere near my current location?	'tomato', 'huckleberry', 'Lingerie'	['question_type_global', 'question_four_hop_statement']
does any store nearby have anything on sale?	'giant eagle', 'roche bros', 'saks off 5th'	['question_type_global', 'question_three_hop_statement']
Just got to [East Hills]
just arrived to [Country Club Road]
what neighborhood am I currently in?	'Homewood South'	['question_type_local']
what department stores are there	'saks off 5th', 'joseph magnin'	['question_type_global', 'question_single_statement']
what stores near [Railroad Avenue] have an ongoing sale on [clothing]?	'saks off 5th'	['question_type_global', 'question_three_hop_statement']
Do i have any [clothing] on my shopping list?	'Jacket', 'Suit', 'Lingerie'	['question_type_global', 'question_two_hop_statement']
what are the stores on [Route 64]?	'key food'	['question_type_local']
what stores are there that I taught you?	'roche bros', 'stater brothers', 'key food', 'giant eagle', 'saks off 5th', 'joseph magnin', 'quality foods'	['question_type_global', 'question_single_statement']
what are the things that I need to get?	'tomato', 'huckleberry', 'Jacket', 'Suit', 'bowl', 'Lingerie', 'watch'	['question_type_global', 'question_single_statement']
show me all of the stores on [Country Club Road]	'roche bros'	['question_type_global', 'question_single_statement']
[stater brothers] has [Herbs and spices] and [Mushrooms] on sale!
what items are on sale at [stater brothers]?	'Beef liver', 'Liver', 'tomato', 'passon_fruit', 'Parsley', 'Celeriac', 'Peas', 'Mushrooms', 'Herbs and spices', 'Duck Liver', 'Tripe'	['question_type_local']
what are the department stores?	'saks off 5th', 'joseph magnin'	['question_type_global', 'question_single_statement']
Do I need to buy any [gifts]?	'bowl', 'watch'	['question_type_global', 'question_two_hop_statement']
what's currently on sale at [roche bros on Railroad Avenue]?	'tomato', 'passon_fruit', 'huckleberry', 'Parsley', 'Beet', 'Mushrooms', 'Herbs and spices', 'Duck Liver', 'Beef heart'	['question_type_local']
what stores on [Route 64] have a sale on [meat]?	'key food'	['question_type_global', 'question_three_hop_statement']
what department stores near [Sherwood Drive] have an ongoing sale?	'joseph magnin'	['question_type_global', 'question_two_hop_statement']
Do i have any [fruit] on my shopping list?	'tomato', 'huckleberry'	['question_type_global', 'question_two_hop_statement']
Where is [Rabbit] on sale?	'giant eagle'	['question_type_local']
is there any [fruit] on my list that's on sale somewhere?	'tomato', 'huckleberry'	['question_type_global', 'question_three_hop_statement']
Do i have any [gifts] on my shopping list?	'bowl', 'watch'	['question_type_global', 'question_two_hop_statement']
show me all stores on [Surrey Lane] that currently have a sale	'stater brothers'	['question_type_global', 'question_two_hop_statement']
what stores on [Surrey Lane] have a sale on [fruit]?	'stater brothers'	['question_type_global', 'question_three_hop_statement']
what are the department stores?	'saks off 5th', 'joseph magnin'	['question_type_global', 'question_single_statement']
[roche bros on Country Club Road] has [Tripe] and [Liver] on sale!
what's currently on sale at [roche bros on Country Club Road]?	'Liver', 'Tripe'	['question_type_local']
show me all department stores near [Railroad Avenue]	'saks off 5th'	['question_type_global', 'question_single_statement']
is there any [gifts] on my list that's on sale somewhere?	'watch'	['question_type_global', 'question_three_hop_statement']
What stores is [Venison] on sale at	'giant eagle', 'key food'	['question_type_local']
show me all supermarkets that i tought you	'roche bros', 'stater brothers', 'key food', 'giant eagle', 'quality foods'	['question_type_global', 'question_single_statement']
show me all supermarkets near [Railroad Avenue]	'roche bros', 'giant eagle'	['question_type_global', 'question_single_statement']
just arrived to [Route 64]
I just got to [East Hills]
what neighborhood am I currently in?	'East Hills'	['question_type_local']
what department stores are there on [Sherwood Drive]?	'joseph magnin'	['question_type_global', 'question_single_statement']
does any store nearby have anything on sale?	'stater brothers'	['question_type_global', 'question_three_hop_statement']
what [gifts] do i need to buy?	'bowl', 'watch'	['question_type_global', 'question_two_hop_statement']
What stores is [greeting card] on sale at	'joseph magnin'	['question_type_local']
is there a store near my location that has what i need on sale?	'stater brothers'	['question_type_global', 'question_four_hop_statement']
what neighborhood is [that street] in?	'Homewood South'	['question_type_local']
does any store nearby have [vegetables] on sale?	'stater brothers'	['question_type_global', 'question_four_hop_statement']
what stores are located on [that street]?	'key food'	['question_type_local']
show me all department stores on [Sherwood Drive] that currently have a sale	'joseph magnin'	['question_type_global', 'question_two_hop_statement']
what stores on [Surrey Lane] have a sale on [meat]?	'stater brothers'	['question_type_global', 'question_three_hop_statement']
are there any stores nearby that have a sale on [meat]?	'stater brothers'	['question_type_global', 'question_four_hop_statement']
What stores is [passon_fruit] on sale at	'stater brothers', 'roche bros'	['question_type_local']
[date] and [dragonfruit] are good examples of [Fruit]
i have [ellen's graduation party] coming up
add [Forced-air] and [Microwave oven] to my shopping list for [that event]
what's currently on sale at [roche bros on Railroad Avenue]?	'tomato', 'passon_fruit', 'huckleberry', 'Parsley', 'Beet', 'Mushrooms', 'Herbs and spices', 'Duck Liver', 'Beef heart'	['question_type_local']
what stores on [Sherwood Drive] have a sale on [appliances]?	'joseph magnin'	['question_type_global', 'question_three_hop_statement']
is there a sale on any [gifts] on my shopping list?	'watch'	['question_type_global', 'question_three_hop_statement']
are there any items on my shopping list that there is a sale on?	'tomato', 'huckleberry', 'Microwave oven', 'Lingerie', 'watch'	['question_type_global', 'question_two_hop_statement']
what items are on sale at [roche bros on Railroad Avenue]?	'tomato', 'passon_fruit', 'huckleberry', 'Parsley', 'Beet', 'Mushrooms', 'Herbs and spices', 'Duck Liver', 'Beef heart'	['question_type_local']
what supermarkets on [Surrey Lane] have a sale?	'stater brothers'	['question_type_global', 'question_two_hop_statement']
is there a sale on [Beet] anywhere?	'roche bros'	['question_type_local']
are there any stores nearby that have a sale on [Herbs and spices]?	'stater brothers'	['question_type_global', 'question_three_hop_statement']
Do i have any [gifts] on my shopping list?	'bowl', 'watch'	['question_type_global', 'question_two_hop_statement']
[key food] has [dragonfruit], [date] and [satsuma] on sale!
what is on sale at [key food]?	'Celeriac', 'Peas', 'Duck Liver', 'Tripe', 'Venison', 'satsuma', 'date', 'dragonfruit'	['question_type_local']
is there any [gifts] on my list that's on sale somewhere?	'watch'	['question_type_global', 'question_three_hop_statement']
show me all stores near [Route 64] that have a sale	'key food'	['question_type_global', 'question_two_hop_statement']
are there any [appliances] on my shopping list that there is a sale on?	'Microwave oven'	['question_type_global', 'question_three_hop_statement']
is there anything that I need for [ellen's graduation party] that's on sale somewhere?	'Microwave oven'	['question_type_global', 'question_two_hop_statement']
what neighborhood is [Sherwood Drive] located in?	'Homewood South'	['question_type_local']
what do i need to buy?	'tomato', 'huckleberry', 'Forced-air', 'Microwave oven', 'Jacket', 'Suit', 'bowl', 'Lingerie', 'watch'	['question_type_global', 'question_single_statement']
are there any [clothing] on my shopping list that there is a sale on?	'Lingerie'	['question_type_global', 'question_three_hop_statement']
does any store nearby have [vegetables] on sale?	'stater brothers'	['question_type_global', 'question_four_hop_statement']
What did I already buy for [thanksgiving]?	'Scarf', 'Skirt', 'balloon', 'socks'	['question_type_local']
what department stores near [Sherwood Drive] have an ongoing sale?	'joseph magnin'	['question_type_global', 'question_two_hop_statement']
What stores is [satsuma] on sale at	'key food'	['question_type_local']
does any store nearby have [meat] on sale?	'stater brothers'	['question_type_global', 'question_four_hop_statement']
what do stores near me have on sale?	'Beef liver', 'Liver', 'tomato', 'passon_fruit', 'Parsley', 'Celeriac', 'Peas', 'Mushrooms', 'Herbs and spices', 'Duck Liver', 'Tripe'	['question_type_global', 'question_three_hop_statement']
is there a sale on [Rabbit] anywhere?	'giant eagle'	['question_type_local']
what is my shopping list?	'tomato', 'huckleberry', 'Forced-air', 'Microwave oven', 'Jacket', 'Suit', 'bowl', 'Lingerie', 'watch'	['question_type_global', 'question_single_statement']
what stores near [Route 64] have an ongoing sale on [fruit]?	'key food'	['question_type_global', 'question_three_hop_statement']
are there any stores nearby that have a sale on [meat]?	'stater brothers'	['question_type_global', 'question_four_hop_statement']
is there a store nearby with any of the items on my shopping list on sale?	'stater brothers'	['question_type_global', 'question_four_hop_statement']
is there any [appliances] on my list that's on sale somewhere?	'Microwave oven'	['question_type_global', 'question_three_hop_statement']
are there any stores nearby that have a sale on items that i need?	'stater brothers'	['question_type_global', 'question_four_hop_statement']
is there a sale on [date] anywhere?	'key food'	['question_type_local']
what stores on [Sherwood Drive] have a sale on [appliances]?	'joseph magnin'	['question_type_global', 'question_three_hop_statement']
is there a sale on [Celeriac] anywhere?	'stater brothers', 'key food'	['question_type_local']
what stores on [Surrey Lane] have a sale?	'stater brothers'	['question_type_global', 'question_two_hop_statement']
what do i need to buy?	'tomato', 'huckleberry', 'Forced-air', 'Microwave oven', 'Jacket', 'Suit', 'bowl', 'Lingerie', 'watch'	['question_type_global', 'question_single_statement']
is there any [gifts] on my list that's on sale somewhere?	'watch'	['question_type_global', 'question_three_hop_statement']
show me all of the department stores	'saks off 5th', 'joseph magnin'	['question_type_global', 'question_single_statement']
what stores on [Country Club Road] have a sale on [meat]?	'roche bros'	['question_type_global', 'question_three_hop_statement']
is there a store near my location is having a sale?	'stater brothers'	['question_type_global', 'question_three_hop_statement']
[cherry] is on sale at [key food]
[Venison], [Celeriac] and [Tripe] are no longer on sale at [that supermarket]
what items are on sale at [key food]?	'Peas', 'Duck Liver', 'satsuma', 'cherry', 'date', 'dragonfruit'	['question_type_local']
is there anything that I need for [ellen's graduation party] that's on sale somewhere?	'Microwave oven'	['question_type_global', 'question_two_hop_statement']
show me all of the stores	'roche bros', 'stater brothers', 'key food', 'giant eagle', 'saks off 5th', 'joseph magnin', 'quality foods'	['question_type_global', 'question_single_statement']
what supermarkets are there on [Country Club Road]?	'roche bros'	['question_type_global', 'question_single_statement']
is there a sale on any [fruit] on my shopping list?	'tomato', 'huckleberry'	['question_type_global', 'question_three_hop_statement']
Where is [this meat] on sale?	'stater brothers', 'roche bros'	['question_type_local']
what neighborhood is [Route 64] located in?	'Homewood South'	['question_type_local']
show me all stores near [Surrey Lane]	'stater brothers'	['question_type_global', 'question_single_statement']
what items that I have to buy currently are on sale?	'tomato', 'huckleberry', 'Microwave oven', 'Lingerie', 'watch'	['question_type_global', 'question_two_hop_statement']
is there any [gifts] that I have to buy currently are on sale?	'watch'	['question_type_global', 'question_three_hop_statement']
is there a sale on any [appliances] on my shopping list?	'Microwave oven'	['question_type_global', 'question_three_hop_statement']
what do stores near me are have a sale on?	'Beef liver', 'Liver', 'tomato', 'passon_fruit', 'Parsley', 'Celeriac', 'Peas', 'Mushrooms', 'Herbs and spices', 'Duck Liver', 'Tripe'	['question_type_global', 'question_three_hop_statement']
is there any [clothing] that I have to buy currently are on sale?	'Lingerie'	['question_type_global', 'question_three_hop_statement']
what items are on sale at [giant eagle]?	'Duck Liver', 'Beef heart', 'Rabbit', 'Venison'	['question_type_local']
is there any [clothing] on my list that's on sale somewhere?	'Lingerie'	['question_type_global', 'question_three_hop_statement']
is there any [fruit] on my list that's on sale somewhere?	'tomato', 'huckleberry'	['question_type_global', 'question_three_hop_statement']
is there a store near my location is having a sale on [vegetables]?	'stater brothers'	['question_type_global', 'question_four_hop_statement']
are there any [fruit] that i need to get?	'tomato', 'huckleberry'	['question_type_global', 'question_two_hop_statement']
show me all stores on [Sherwood Drive] that currently have a sale on [Microwave oven]	'joseph magnin'	['question_type_global', 'question_two_hop_statement']
what items that I have to buy currently are on sale?	'tomato', 'huckleberry', 'Microwave oven', 'Lingerie', 'watch'	['question_type_global', 'question_two_hop_statement']
what stores on [Surrey Lane] have a sale on [tomato]?	'stater brothers'	['question_type_global', 'question_two_hop_statement']
is there any [gifts] that I have to buy currently are on sale?	'watch'	['question_type_global', 'question_three_hop_statement']
is there a store near my location is having a sale?	'stater brothers'	['question_type_global', 'question_three_hop_statement']
is there a sale on [Tripe] anywhere?	'stater brothers', 'roche bros'	['question_type_local']
is there any [fruit] on my list that's on sale somewhere?	'tomato', 'huckleberry'	['question_type_global', 'question_three_hop_statement']
show me all supermarkets on [Country Club Road] that currently have a sale	'roche bros'	['question_type_global', 'question_two_hop_statement']
show me all department stores near [Railroad Avenue] that have a sale	'saks off 5th'	['question_type_global', 'question_two_hop_statement']
[Scarf] and [Lingerie] are all on sale at [joseph magnin]
[joseph magnin] no longer has [Lingerie], [watch] and [Humidifier] on sale
why do i need to buy [Jacket]?	'thanksgiving'	['question_type_local']
show me all of the department stores	'saks off 5th', 'joseph magnin'	['question_type_global', 'question_single_statement']
What stores is [passon_fruit] on sale at	'stater brothers', 'roche bros'	['question_type_local']
what stores on [Surrey Lane] have a sale on [vegetables]?	'stater brothers'	['question_type_global', 'question_three_hop_statement']
[Peas] is on sale at [roche bros on Railroad Avenue]
what is on sale at [this store]?	'tomato', 'passon_fruit', 'huckleberry', 'Parsley', 'Beet', 'Peas', 'Mushrooms', 'Herbs and spices', 'Duck Liver', 'Beef heart'	['question_type_local']
are there any stores nearby that have a sale?	'stater brothers'	['question_type_global', 'question_three_hop_statement']
is there a store nearby with any of the items on my shopping list on sale?	'stater brothers'	['question_type_global', 'question_four_hop_statement']
show me all supermarkets that i tought you	'roche bros', 'stater brothers', 'key food', 'giant eagle', 'quality foods'	['question_type_global', 'question_single_statement']
here are some examples of [Fruit]: [orange], [star fruit] and [lime]
what items are on sale at nearby stores?	'Beef liver', 'Liver', 'tomato', 'passon_fruit', 'Parsley', 'Celeriac', 'Peas', 'Mushrooms', 'Herbs and spices', 'Duck Liver', 'Tripe'	['question_type_global', 'question_three_hop_statement']
are there any items on my shopping list for [ellen's graduation party] that there is a sale on?	'Microwave oven'	['question_type_global', 'question_two_hop_statement']
are there any stores nearby that have a sale on [fruit]?	'stater brothers'	['question_type_global', 'question_four_hop_statement']
does any store nearby have any of the items i need on sale?	'stater brothers'	['question_type_global', 'question_four_hop_statement']
show me all stores on [Sherwood Drive] that currently have a sale on [gifts]	'joseph magnin'	['question_type_global', 'question_three_hop_statement']
why do i need to buy [Suit]?	'thanksgiving'	['question_type_local']
is there a store near my location is having a sale?	'stater brothers'	['question_type_global', 'question_three_hop_statement']
show me all stores on [Surrey Lane] that currently have a sale	'stater brothers'	['question_type_global', 'question_two_hop_statement']
does any store nearby have [vegetables] on sale?	'stater brothers'	['question_type_global', 'question_four_hop_statement']
what stores on [Route 64] have a sale on [meat]?	'key food'	['question_type_global', 'question_three_hop_statement']
what department stores near [Railroad Avenue] have an ongoing sale?	'saks off 5th'	['question_type_global', 'question_two_hop_statement']
what stores on [Sherwood Drive] have a sale?	'joseph magnin'	['question_type_global', 'question_two_hop_statement']
are there any [fruit] that i need to get?	'tomato', 'huckleberry'	['question_type_global', 'question_two_hop_statement']
is there anything that I need for [grading dinner party] that's on sale somewhere?	'tomato', 'huckleberry'	['question_type_global', 'question_two_hop_statement']
what are the supermarkets?	'roche bros', 'stater brothers', 'key food', 'giant eagle', 'quality foods'	['question_type_global', 'question_single_statement']
i think [Berkshire Drive] is in [Market East]
show me all stores near [Railroad Avenue] that have a sale on [vegetables]	'roche bros'	['question_type_global', 'question_three_hop_statement']
is there any [clothing] on my list that's on sale somewhere?	'Lingerie'	['question_type_global', 'question_three_hop_statement']
what [gifts] do i need to buy?	'bowl', 'watch'	['question_type_global', 'question_two_hop_statement']
what is on sale near my current location?	'Beef liver', 'Liver', 'tomato', 'passon_fruit', 'Parsley', 'Celeriac', 'Peas', 'Mushrooms', 'Herbs and spices', 'Duck Liver', 'Tripe'	['question_type_global', 'question_three_hop_statement']
Do I need to buy any [appliances]?	'Forced-air', 'Microwave oven'	['question_type_global', 'question_two_hop_statement']
are there any [fruit] on my shopping list that there is a sale on?	'tomato', 'huckleberry'	['question_type_global', 'question_three_hop_statement']
is there a store near my location is having a sale on [meat]?	'stater brothers'	['question_type_global', 'question_four_hop_statement']
is there a sale on [satsuma] anywhere?	'key food'	['question_type_local']
Do I need to buy any [gifts]?	'bowl', 'watch'	['question_type_global', 'question_two_hop_statement']
does any store nearby have [meat] on sale?	'stater brothers'	['question_type_global', 'question_four_hop_statement']
is there a store nearby with a sale on [meat] going on right now?	'stater brothers'	['question_type_global', 'question_four_hop_statement']
what are the things that I need to get?	'tomato', 'huckleberry', 'Forced-air', 'Microwave oven', 'Jacket', 'Suit', 'bowl', 'Lingerie', 'watch'	['question_type_global', 'question_single_statement']
show me all stores near [Country Club Road] that have a sale on [meat]	'roche bros'	['question_type_global', 'question_three_hop_statement']
is there a sale on [key chain] anywhere?	'joseph magnin'	['question_type_local']
does any store nearby have [vegetables] on sale?	'stater brothers'	['question_type_global', 'question_four_hop_statement']
what department stores on [Sherwood Drive] have a sale?	'joseph magnin'	['question_type_global', 'question_two_hop_statement']
show me all stores near [Sherwood Drive] that have a sale on [appliances]	'joseph magnin'	['question_type_global', 'question_three_hop_statement']
what [clothing] do i need to buy?	'Jacket', 'Suit', 'Lingerie'	['question_type_global', 'question_two_hop_statement']
what are the supermarkets on [Railroad Avenue]?	'roche bros', 'giant eagle'	['question_type_global', 'question_single_statement']
show me all of the department stores on [Railroad Avenue]	'saks off 5th'	['question_type_global', 'question_single_statement']
what [fruit] do i need to buy?	'tomato', 'huckleberry'	['question_type_global', 'question_two_hop_statement']
I am currently in [Homewood South]
Where is [dragonfruit] on sale?	'key food'	['question_type_local']
show me all of the supermarkets on [Surrey Lane]	'stater brothers'	['question_type_global', 'question_single_statement']
