for example [Fruit] are [blackberry] and [avocado]
here are some examples of [Clothing]: [Top], [Dress] and [Skirt]
[Lentils] and [Celery] are [Vegetables]
[Chicken] is a [Meat]
i have [dinner with my inlaws] coming up
i need to get [avocado] and [blackberry] for [dinner with my inlaws]
get rid of [blackberry] and [avocado] from my shopping for [dinner with my inlaws]
[Green beans] and [Skirret] are both examples of [Vegetables]
What did I already buy for [dinner with my inlaws]?	'blackberry', 'avocado'	['question_type_local']
what things did i get for [dinner with my inlaws]	'blackberry', 'avocado'	['question_type_local']
i think [Willow Lane] is in [Glen Hazel]
what neighborhood is [Willow Lane] located in?	'Glen Hazel'	['question_type_local']
[Cravat], [Lingerie] and [Briefs] are all good examples of [Clothing]
[blouse] is a [Gift]
what did i remove from [dinner with my inlaws]?	'blackberry', 'avocado'	['question_type_local']
there is a [supermarket] called [market of choice] on [Willow Lane]
[Chicken] is on sale at [market of choice]
please remind me to buy [Skirret] and [Celery] for [dinner with my inlaws]
what items do I need to get?	'Celery', 'Skirret'	['question_type_global', 'question_single_statement']
what are the stores?	'market of choice'	['question_type_global', 'question_single_statement']
there is an upcoming [thanksgiving dinner]
add [avocado] and [blackberry] to my shopping list for [this event]
what stores on [Willow Lane] have a sale on [Chicken]?	'market of choice'	['question_type_global', 'question_two_hop_statement']
Do i have any [vegetables] on my shopping list?	'Celery', 'Skirret'	['question_type_global', 'question_two_hop_statement']
what stores on [Willow Lane] have a sale?	'market of choice'	['question_type_global', 'question_two_hop_statement']
what event do I need to buy [Skirret] for	'dinner with my inlaws'	['question_type_local']
what supermarkets are there?	'market of choice'	['question_type_global', 'question_single_statement']
what stores near [Willow Lane] have an ongoing sale on [meat]?	'market of choice'	['question_type_global', 'question_three_hop_statement']
what supermarkets on [Willow Lane] have a sale?	'market of choice'	['question_type_global', 'question_two_hop_statement']
why do i need to buy [blackberry]?	'thanksgiving dinner'	['question_type_local']
What did I already buy for [dinner with my inlaws]?	'blackberry', 'avocado'	['question_type_local']
get rid of [Skirret] from my shopping list for [dinner with my inlaws]
what is on sale at [market of choice]?	'Chicken'	['question_type_local']
[date], [lime] and [grapefruit] are all different types of [Fruit]
Do I need to buy any [fruit]?	'blackberry', 'avocado'	['question_type_global', 'question_two_hop_statement']
what are the supermarkets?	'market of choice'	['question_type_global', 'question_single_statement']
what supermarkets near [Willow Lane] have an ongoing sale?	'market of choice'	['question_type_global', 'question_two_hop_statement']
Do I need to buy any [vegetables]?	'Celery'	['question_type_global', 'question_two_hop_statement']
show me all of the supermarkets on [Willow Lane]	'market of choice'	['question_type_global', 'question_single_statement']
there is a [supermarket] called [omni foods] on [Willow Lane]
why do i need to buy [avocado]?	'thanksgiving dinner'	['question_type_local']
what stores near [Willow Lane] have an ongoing sale on [meat]?	'market of choice'	['question_type_global', 'question_three_hop_statement']
what are the stores?	'market of choice', 'omni foods'	['question_type_global', 'question_single_statement']
what supermarkets are there on [Willow Lane]?	'market of choice', 'omni foods'	['question_type_global', 'question_single_statement']
show me all stores near [Willow Lane] that have a sale on [meat]	'market of choice'	['question_type_global', 'question_three_hop_statement']
Do I need to buy any [vegetables]?	'Celery'	['question_type_global', 'question_two_hop_statement']
[shoes] and [clay pot] are both examples of [Gift]
remove [avocado] and [blackberry] from my shopping list for [thanksgiving dinner]
add [date] and [grapefruit] for [thanksgiving dinner]
What did I already buy for [thanksgiving dinner]?	'blackberry', 'avocado'	['question_type_local']
Do i have any [vegetables] on my shopping list?	'Celery'	['question_type_global', 'question_two_hop_statement']
show me all of the stores on [Willow Lane]	'market of choice', 'omni foods'	['question_type_global', 'question_single_statement']
what is on sale at [market of choice]?	'Chicken'	['question_type_local']
what are the supermarkets on [Willow Lane]?	'market of choice', 'omni foods'	['question_type_global', 'question_single_statement']
show me all stores near [Willow Lane] that have a sale on [meat]	'market of choice'	['question_type_global', 'question_three_hop_statement']
what are the stores?	'market of choice', 'omni foods'	['question_type_global', 'question_single_statement']
show me all stores on [Willow Lane] that currently have a sale on [meat]	'market of choice'	['question_type_global', 'question_three_hop_statement']
[honeydew] is a [Fruit]
what supermarkets are there?	'market of choice', 'omni foods'	['question_type_global', 'question_single_statement']
[I] just got to [Willow Lane]
remember that i have [my son's graduation]
things i need to buy for [my son's graduation]: [Skirt] and [Dress]
i don't need [Dress] and [Skirt] for [my son's graduation] anymore
why do i need to buy [date]?	'thanksgiving dinner'	['question_type_local']
are there any stores nearby that have a sale on [meat]?	'market of choice'	['question_type_global', 'question_four_hop_statement']
show me all stores on [Willow Lane] that currently have a sale on [Chicken]	'market of choice'	['question_type_global', 'question_two_hop_statement']
show me all supermarkets near [Willow Lane] that have a sale	'market of choice'	['question_type_global', 'question_two_hop_statement']
[Waistcoat] and [Nightgown] are types of [Clothing]
what stores near [Willow Lane] have an ongoing sale on [Chicken]?	'market of choice'	['question_type_global', 'question_two_hop_statement']
what supermarkets are there on [Willow Lane]?	'market of choice', 'omni foods'	['question_type_global', 'question_single_statement']
what did i remove from [my son's graduation]?	'Dress', 'Skirt'	['question_type_local']
Do I need to buy any [vegetables]?	'Celery'	['question_type_global', 'question_two_hop_statement']
are there any stores nearby that have a sale?	'market of choice'	['question_type_global', 'question_three_hop_statement']
show me all of the stores	'market of choice', 'omni foods'	['question_type_global', 'question_single_statement']
[Fan heater], [Cold-pressed juicer] and [Air conditioner] are [Appliance]
show me all stores on [Willow Lane] that currently have a sale on [Chicken]	'market of choice'	['question_type_global', 'question_two_hop_statement']
what supermarkets are there?	'market of choice', 'omni foods'	['question_type_global', 'question_single_statement']
is there a store near my location is having a sale?	'market of choice'	['question_type_global', 'question_three_hop_statement']
what [fruit] do i need to buy?	'date', 'grapefruit'	['question_type_global', 'question_two_hop_statement']
show me all supermarkets that i tought you	'market of choice', 'omni foods'	['question_type_global', 'question_single_statement']
[rubber duck], [lamp shade] and [eye liner] are all good examples of [Gift]
what items do I need to get?	'Celery', 'date', 'grapefruit'	['question_type_global', 'question_single_statement']
i need to make sure to get [lime] for [thanksgiving dinner]
what is on sale at [market of choice]?	'Chicken'	['question_type_local']
[Lentils], [Celery] and [Skirret] are on sale at [market of choice]
what kind of [fruit] do I need to get?	'date', 'lime', 'grapefruit'	['question_type_global', 'question_two_hop_statement']
why do i need to buy [Celery]?	'dinner with my inlaws'	['question_type_local']
is there anything on sale at a store nearby?	'Lentils', 'Celery', 'Chicken', 'Skirret'	['question_type_global', 'question_three_hop_statement']
is there a store nearby with a sale on [vegetables] going on right now?	'market of choice'	['question_type_global', 'question_four_hop_statement']
show me all supermarkets near [Willow Lane]	'market of choice', 'omni foods'	['question_type_global', 'question_single_statement']
what stores near [Willow Lane] have an ongoing sale on [Chicken]?	'market of choice'	['question_type_global', 'question_two_hop_statement']
what items that I have to buy currently are on sale near me?	'Celery'	['question_type_global', 'question_four_hop_statement']
are there any items on my shopping list for [dinner with my inlaws] that there is a sale on?	'Celery'	['question_type_global', 'question_two_hop_statement']
what's currently on sale at [market of choice]?	'Lentils', 'Celery', 'Chicken', 'Skirret'	['question_type_local']
is there a store near my location is having a sale?	'market of choice'	['question_type_global', 'question_three_hop_statement']
what do i need to buy?	'Celery', 'date', 'lime', 'grapefruit'	['question_type_global', 'question_single_statement']
show me all of the supermarkets	'market of choice', 'omni foods'	['question_type_global', 'question_single_statement']
[tomato], [fig] and [dragonfruit] are all different types of [Fruit]
what neighborhood am I in?	'Glen Hazel'	['question_type_local']
is there anything on my list that's on sale somewhere near my current location?	'Celery'	['question_type_global', 'question_four_hop_statement']
what are the supermarkets?	'market of choice', 'omni foods'	['question_type_global', 'question_single_statement']
is there any [vegetables] that I have to buy currently are on sale?	'Celery'	['question_type_global', 'question_three_hop_statement']
add [clay pot] and [rubber duck] to my shopping list for [my son's graduation]
what things do I need to buy for [my son's graduation]	'clay pot', 'rubber duck'	['question_type_local']
Do i have any [fruit] on my shopping list?	'date', 'lime', 'grapefruit'	['question_type_global', 'question_two_hop_statement']
why do i need to buy [rubber duck]?	"my son's graduation"	['question_type_local']
are there any items on my shopping list that there is a sale on at a store nearby?	'Celery'	['question_type_global', 'question_four_hop_statement']
is there a store nearby with any of the items on my shopping list on sale?	'market of choice'	['question_type_global', 'question_four_hop_statement']
what items that I have to buy for [dinner with my inlaws] currently are on sale?	'Celery'	['question_type_global', 'question_two_hop_statement']
what are the supermarkets?	'market of choice', 'omni foods'	['question_type_global', 'question_single_statement']
what [fruit] do i need to buy?	'date', 'lime', 'grapefruit'	['question_type_global', 'question_two_hop_statement']
some example of [Appliance] are [Drawer dishwasher] and [Dehumidifier]
what stores on [Willow Lane] have a sale on [vegetables]?	'market of choice'	['question_type_global', 'question_three_hop_statement']
what supermarkets are there?	'market of choice', 'omni foods'	['question_type_global', 'question_single_statement']
show me all stores on [Willow Lane] that currently have a sale	'market of choice'	['question_type_global', 'question_two_hop_statement']
are there any stores nearby that have a sale on items that i need?	'market of choice'	['question_type_global', 'question_four_hop_statement']
please remind me to buy [Cravat] for [my son's graduation]
what [vegetables] do i need to buy?	'Celery'	['question_type_global', 'question_two_hop_statement']
does any store nearby have anything on sale?	'market of choice'	['question_type_global', 'question_three_hop_statement']
what stores on [Willow Lane] have a sale on [meat]?	'market of choice'	['question_type_global', 'question_three_hop_statement']
what do i have on shopping list for [thanksgiving dinner]?	'date', 'lime', 'grapefruit'	['question_type_local']
what supermarkets are there?	'market of choice', 'omni foods'	['question_type_global', 'question_single_statement']
what supermarkets near [Willow Lane] have an ongoing sale?	'market of choice'	['question_type_global', 'question_two_hop_statement']
is there anything that I need for [dinner with my inlaws] that's on sale somewhere?	'Celery'	['question_type_global', 'question_two_hop_statement']
[Patio heater] is a kind of [Appliance]
what stores near [Willow Lane] have an ongoing sale?	'market of choice'	['question_type_global', 'question_two_hop_statement']
things i need to buy for [thanksgiving dinner]: [dragonfruit] and [fig]
what are the things that I need to get?	'Celery', 'Cravat', 'date', 'lime', 'grapefruit', 'clay pot', 'rubber duck', 'fig', 'dragonfruit'	['question_type_global', 'question_single_statement']
show me all of the stores on [Willow Lane]	'market of choice', 'omni foods'	['question_type_global', 'question_single_statement']
there is a [department store] called [sage-allen] on [Willow Lane]
[sage-allen] has [eye liner], [lamp shade] and [blouse] on sale!
what is on sale at [sage-allen]?	'blouse', 'lamp shade', 'eye liner'	['question_type_local']
what are the supermarkets on [Willow Lane]?	'market of choice', 'omni foods'	['question_type_global', 'question_single_statement']
is there a store near my location is having a sale?	'market of choice', 'sage-allen'	['question_type_global', 'question_three_hop_statement']
are there any [gifts] that i need to get?	'clay pot', 'rubber duck'	['question_type_global', 'question_two_hop_statement']
what stores near [Willow Lane] have an ongoing sale on [lamp shade]?	'sage-allen'	['question_type_global', 'question_two_hop_statement']
just purchases [Celery] for [dinner with my inlaws]
is there a store nearby with a sale on [gifts] going on right now?	'sage-allen'	['question_type_global', 'question_four_hop_statement']
is there a store nearby with a sale on [meat] going on right now?	'market of choice'	['question_type_global', 'question_four_hop_statement']
show me all of the supermarkets	'market of choice', 'omni foods'	['question_type_global', 'question_single_statement']
add [Chicken] to my shopping list for [this event]
what do i have on shopping list for [this event]?	'Chicken'	['question_type_local']
show me all of the supermarkets on [Willow Lane]	'market of choice', 'omni foods'	['question_type_global', 'question_single_statement']
what is on sale at [market of choice]?	'Lentils', 'Celery', 'Chicken', 'Skirret'	['question_type_local']
is there a store near my location is having a sale on [gifts]?	'sage-allen'	['question_type_global', 'question_four_hop_statement']
is there a sale on [this thing] anywhere?	'market of choice'	['question_type_local']
are there any stores nearby that have a sale?	'market of choice', 'sage-allen'	['question_type_global', 'question_three_hop_statement']
are there any stores nearby that have a sale on [blouse]?	'sage-allen'	['question_type_global', 'question_three_hop_statement']
show me all stores near [Willow Lane] that have a sale on [meat]	'market of choice'	['question_type_global', 'question_three_hop_statement']
show me all supermarkets near [Willow Lane]	'market of choice', 'omni foods'	['question_type_global', 'question_single_statement']
Where is [Lentils] on sale?	'market of choice'	['question_type_local']
show me all department stores on [Willow Lane] that currently have a sale	'sage-allen'	['question_type_global', 'question_two_hop_statement']
what kind of [fruit] do I need to get?	'date', 'lime', 'grapefruit', 'fig', 'dragonfruit'	['question_type_global', 'question_two_hop_statement']
are there any [clothing] that i need to get?	'Cravat'	['question_type_global', 'question_two_hop_statement']
what stores on [Willow Lane] have a sale on [meat]?	'market of choice'	['question_type_global', 'question_three_hop_statement']
are there any [meat] on my shopping list that there is a sale on?	'Chicken'	['question_type_global', 'question_three_hop_statement']
what are the department stores on [Willow Lane]?	'sage-allen'	['question_type_global', 'question_single_statement']
is there any [meat] on my list that's on sale somewhere?	'Chicken'	['question_type_global', 'question_three_hop_statement']
[Chapel Street] is located in the [Glen Hazel] neighborhood
is there a sale on [this meat] anywhere?	'market of choice'	['question_type_local']
what are the supermarkets?	'market of choice', 'omni foods'	['question_type_global', 'question_single_statement']
show me all department stores near [Willow Lane]	'sage-allen'	['question_type_global', 'question_single_statement']
What stores is [lamp shade] on sale at	'sage-allen'	['question_type_local']
what kind of [meat] do I need to get?	'Chicken'	['question_type_global', 'question_two_hop_statement']
what are the stores on [Willow Lane]?	'market of choice', 'omni foods', 'sage-allen'	['question_type_global', 'question_single_statement']
is there a store nearby with a sale on [gifts] going on right now?	'sage-allen'	['question_type_global', 'question_four_hop_statement']
what stores near [Willow Lane] have an ongoing sale?	'market of choice', 'sage-allen'	['question_type_global', 'question_two_hop_statement']
what are the stores?	'market of choice', 'omni foods', 'sage-allen'	['question_type_global', 'question_single_statement']
make sure to buy [Lentils] and [Skirret] for [thanksgiving dinner]
what did i remove from [thanksgiving dinner]?	'blackberry', 'avocado'	['question_type_local']
show me all of the stores	'market of choice', 'omni foods', 'sage-allen'	['question_type_global', 'question_single_statement']
is there a store near my location is having a sale on [gifts]?	'sage-allen'	['question_type_global', 'question_four_hop_statement']
does any store nearby have anything on sale?	'market of choice', 'sage-allen'	['question_type_global', 'question_three_hop_statement']
is there a store nearby with any of the items on my shopping list on sale?	'market of choice'	['question_type_global', 'question_four_hop_statement']
what neighborhood is [Willow Lane] in?	'Glen Hazel'	['question_type_local']
is there anything on my list that's on sale somewhere?	'Lentils', 'Chicken', 'Skirret'	['question_type_global', 'question_two_hop_statement']
what kind of [fruit] do I need to get?	'date', 'lime', 'grapefruit', 'fig', 'dragonfruit'	['question_type_global', 'question_two_hop_statement']
i don't need [Chicken] for [dinner with my inlaws] anymore
i need to make sure to get [Lentils] and [Green beans] for [that event]
what do I need for [dinner with my inlaws]?	'Lentils', 'Green beans'	['question_type_local']
what department stores are there on [Willow Lane]?	'sage-allen'	['question_type_global', 'question_single_statement']
what supermarkets on [Willow Lane] have a sale?	'market of choice'	['question_type_global', 'question_two_hop_statement']
what are the stores?	'market of choice', 'omni foods', 'sage-allen'	['question_type_global', 'question_single_statement']
what supermarkets are there on [Willow Lane]?	'market of choice', 'omni foods'	['question_type_global', 'question_single_statement']
are there any stores nearby that have a sale on [gifts]?	'sage-allen'	['question_type_global', 'question_four_hop_statement']
does any store nearby have anything on sale?	'market of choice', 'sage-allen'	['question_type_global', 'question_three_hop_statement']
what department stores on [Willow Lane] have a sale?	'sage-allen'	['question_type_global', 'question_two_hop_statement']
for example [Gift] are [photo album] and [bookmark]
are there any [fruit] that i need to get?	'date', 'lime', 'grapefruit', 'fig', 'dragonfruit'	['question_type_global', 'question_two_hop_statement']
show me all department stores on [Willow Lane] that currently have a sale	'sage-allen'	['question_type_global', 'question_two_hop_statement']
what is on sale near my current location?	'Lentils', 'Celery', 'Chicken', 'Skirret', 'blouse', 'lamp shade', 'eye liner'	['question_type_global', 'question_three_hop_statement']
what items did i already get for [my son's graduation]?	'Dress', 'Skirt'	['question_type_local']
what stores on [Willow Lane] have a sale?	'market of choice', 'sage-allen'	['question_type_global', 'question_two_hop_statement']
show me all department stores near [Willow Lane] that have a sale	'sage-allen'	['question_type_global', 'question_two_hop_statement']
does any store nearby have [Chicken] on sale?	'market of choice'	['question_type_global', 'question_three_hop_statement']
show me all of the supermarkets	'market of choice', 'omni foods'	['question_type_global', 'question_single_statement']
[Broad Street West] is in [Glen Hazel]
what neighborhood is [that street] in?	'Glen Hazel'	['question_type_local']
what kind of [gifts] do I need to get?	'clay pot', 'rubber duck'	['question_type_global', 'question_two_hop_statement']
show me all supermarkets on [Willow Lane] that currently have a sale	'market of choice'	['question_type_global', 'question_two_hop_statement']
what are the department stores?	'sage-allen'	['question_type_global', 'question_single_statement']
show me all of the stores	'market of choice', 'omni foods', 'sage-allen'	['question_type_global', 'question_single_statement']
things i need to buy for [my son's graduation]: [Drawer dishwasher] and [Fan heater]
What do I need to buy [dragonfruit] for?	'thanksgiving dinner'	['question_type_local']
what stores on [Willow Lane] have a sale?	'market of choice', 'sage-allen'	['question_type_global', 'question_two_hop_statement']
what items that I have to buy currently are on sale?	'Lentils', 'Skirret'	['question_type_global', 'question_two_hop_statement']
show me all stores	'market of choice', 'omni foods', 'sage-allen'	['question_type_global', 'question_single_statement']
show me all stores near [Willow Lane] that have a sale on [Chicken]	'market of choice'	['question_type_global', 'question_two_hop_statement']
get rid of [fig] and [grapefruit] from my shopping for [thanksgiving dinner]
what do I need for [thanksgiving dinner]?	'Lentils', 'Skirret', 'date', 'lime', 'dragonfruit'	['question_type_local']
what kind of [fruit] do I need to get?	'date', 'lime', 'dragonfruit'	['question_type_global', 'question_two_hop_statement']
what [appliances] do i need to buy?	'Fan heater', 'Drawer dishwasher'	['question_type_global', 'question_two_hop_statement']
take off [Fan heater] and [Cravat] from my list for [my son's graduation]
i absolutely must not forget to get [Patio heater] for [my son's graduation]
is there a store near my location is having a sale?	'market of choice', 'sage-allen'	['question_type_global', 'question_three_hop_statement']
what stores near [Willow Lane] have an ongoing sale on [meat]?	'market of choice'	['question_type_global', 'question_three_hop_statement']
what stores near [Willow Lane] have an ongoing sale on [Chicken]?	'market of choice'	['question_type_global', 'question_two_hop_statement']
things i need to buy for [dinner with my inlaws]: [honeydew] and [fig]
What do I need to buy for [dinner with my inlaws]?	'Lentils', 'Green beans', 'honeydew', 'fig'	['question_type_local']
what stores near [Willow Lane] have an ongoing sale on [gifts]?	'sage-allen'	['question_type_global', 'question_three_hop_statement']
does any store nearby have [meat] on sale?	'market of choice'	['question_type_global', 'question_four_hop_statement']
are there any [fruit] that i need to get?	'date', 'lime', 'honeydew', 'fig', 'dragonfruit'	['question_type_global', 'question_two_hop_statement']
what stores near [Willow Lane] have an ongoing sale?	'market of choice', 'sage-allen'	['question_type_global', 'question_two_hop_statement']
what do stores near me are have a sale on?	'Lentils', 'Celery', 'Chicken', 'Skirret', 'blouse', 'lamp shade', 'eye liner'	['question_type_global', 'question_three_hop_statement']
what stores on [Willow Lane] have a sale on [vegetables]?	'market of choice'	['question_type_global', 'question_three_hop_statement']
are there any [appliances] that i need to get?	'Drawer dishwasher', 'Patio heater'	['question_type_global', 'question_two_hop_statement']
what do I need for [my son's graduation]?	'clay pot', 'rubber duck', 'Drawer dishwasher', 'Patio heater'	['question_type_local']
what stores are there on [Willow Lane]?	'market of choice', 'omni foods', 'sage-allen'	['question_type_global', 'question_single_statement']
what are the supermarkets on [Willow Lane]?	'market of choice', 'omni foods'	['question_type_global', 'question_single_statement']
show me all of the supermarkets	'market of choice', 'omni foods'	['question_type_global', 'question_single_statement']
what stores are there that I taught you?	'market of choice', 'omni foods', 'sage-allen'	['question_type_global', 'question_single_statement']
what do stores near me are have a sale on?	'Lentils', 'Celery', 'Chicken', 'Skirret', 'blouse', 'lamp shade', 'eye liner'	['question_type_global', 'question_three_hop_statement']
what are the things that i need to get?	'Lentils', 'Green beans', 'Skirret', 'date', 'lime', 'clay pot', 'honeydew', 'rubber duck', 'fig', 'dragonfruit', 'Drawer dishwasher', 'Patio heater'	['question_type_global', 'question_single_statement']
[8th Street South] is located in the [Glen Hazel] neighborhood
what are the department stores on [Willow Lane]?	'sage-allen'	['question_type_global', 'question_single_statement']
show me all stores near [Willow Lane] that have a sale on [vegetables]	'market of choice'	['question_type_global', 'question_three_hop_statement']
show me all stores on [Willow Lane] that currently have a sale on [Celery]	'market of choice'	['question_type_global', 'question_two_hop_statement']
show me all department stores	'sage-allen'	['question_type_global', 'question_single_statement']
add [Nightgown] and [Top] to my shopping list for [my son's graduation]
take off [Top] and [Nightgown] from my list for [my son's graduation]
is there a store near my location is having a sale on [gifts]?	'sage-allen'	['question_type_global', 'question_four_hop_statement']
what stores near [Willow Lane] have an ongoing sale on [meat]?	'market of choice'	['question_type_global', 'question_three_hop_statement']
is there a store nearby with a sale going on right now?	'market of choice', 'sage-allen'	['question_type_global', 'question_three_hop_statement']
what stores on [Willow Lane] have a sale on [vegetables]?	'market of choice'	['question_type_global', 'question_three_hop_statement']
[phone], [ice cube tray] and [socks] are all examples of [Gift]
is there a sale on [blouse] anywhere?	'sage-allen'	['question_type_local']
what are the department stores?	'sage-allen'	['question_type_global', 'question_single_statement']
is there any [vegetables] that I have to buy currently are on sale?	'Lentils', 'Skirret'	['question_type_global', 'question_three_hop_statement']
what event do I need to buy [honeydew] for	'dinner with my inlaws'	['question_type_local']
show me all stores on [Willow Lane] that currently have a sale on [meat]	'market of choice'	['question_type_global', 'question_three_hop_statement']
what supermarkets are there on [Willow Lane]?	'market of choice', 'omni foods'	['question_type_global', 'question_single_statement']
what stores on [Willow Lane] have a sale on [gifts]?	'sage-allen'	['question_type_global', 'question_three_hop_statement']
what stores on [Willow Lane] have a sale on [vegetables]?	'market of choice'	['question_type_global', 'question_three_hop_statement']
Do I need to buy any [appliances]?	'Drawer dishwasher', 'Patio heater'	['question_type_global', 'question_two_hop_statement']
what [vegetables] do i need to buy?	'Lentils', 'Green beans', 'Skirret'	['question_type_global', 'question_two_hop_statement']
show me all stores on [Willow Lane] that currently have a sale on [vegetables]	'market of choice'	['question_type_global', 'question_three_hop_statement']
what department stores on [Willow Lane] have a sale?	'sage-allen'	['question_type_global', 'question_two_hop_statement']
[apple] is a kind of [Fruit]
is there a store near my location is having a sale on [lamp shade]?	'sage-allen'	['question_type_global', 'question_three_hop_statement']
is there a sale on any items on my shopping list where i am?	'Lentils', 'Skirret'	['question_type_global', 'question_four_hop_statement']
what [gifts] do i need to buy?	'clay pot', 'rubber duck'	['question_type_global', 'question_two_hop_statement']
what are the stores?	'market of choice', 'omni foods', 'sage-allen'	['question_type_global', 'question_single_statement']
Where is [Chicken] on sale?	'market of choice'	['question_type_local']
show me all stores near [Willow Lane] that have a sale on [vegetables]	'market of choice'	['question_type_global', 'question_three_hop_statement']
here are some examples of [Appliance]: [Can opener], [Beverage opener] and [Window fan]
what items that I have to buy currently are on sale near me?	'Lentils', 'Skirret'	['question_type_global', 'question_four_hop_statement']
show me all of the supermarkets	'market of choice', 'omni foods'	['question_type_global', 'question_single_statement']
show me all stores on [Willow Lane] that currently have a sale	'market of choice', 'sage-allen'	['question_type_global', 'question_two_hop_statement']
what stores are there on [Willow Lane]?	'market of choice', 'omni foods', 'sage-allen'	['question_type_global', 'question_single_statement']
does any store nearby have [gifts] on sale?	'sage-allen'	['question_type_global', 'question_four_hop_statement']
is there a store nearby with a sale on [vegetables] going on right now?	'market of choice'	['question_type_global', 'question_four_hop_statement']
Do i have any [appliances] on my shopping list?	'Drawer dishwasher', 'Patio heater'	['question_type_global', 'question_two_hop_statement']
what are the things that I need to get?	'Lentils', 'Green beans', 'Skirret', 'date', 'lime', 'clay pot', 'honeydew', 'rubber duck', 'fig', 'dragonfruit', 'Drawer dishwasher', 'Patio heater'	['question_type_global', 'question_single_statement']
what do I need for [dinner with my inlaws]?	'Lentils', 'Green beans', 'honeydew', 'fig'	['question_type_local']
is there anything on sale at a store nearby?	'Lentils', 'Celery', 'Chicken', 'Skirret', 'blouse', 'lamp shade', 'eye liner'	['question_type_global', 'question_three_hop_statement']
what stores are there on [Willow Lane]?	'market of choice', 'omni foods', 'sage-allen'	['question_type_global', 'question_single_statement']
what are the stores?	'market of choice', 'omni foods', 'sage-allen'	['question_type_global', 'question_single_statement']
what do i need [date] for?	'thanksgiving dinner'	['question_type_local']
show me all stores on [Willow Lane] that currently have a sale on [vegetables]	'market of choice'	['question_type_global', 'question_three_hop_statement']
what kind of [gifts] do I need to get?	'clay pot', 'rubber duck'	['question_type_global', 'question_two_hop_statement']
does any store nearby have anything on sale?	'market of choice', 'sage-allen'	['question_type_global', 'question_three_hop_statement']
show me all of the stores on [Willow Lane]	'market of choice', 'omni foods', 'sage-allen'	['question_type_global', 'question_single_statement']
what are the department stores on [Willow Lane]?	'sage-allen'	['question_type_global', 'question_single_statement']
show me all of the supermarkets on [Willow Lane]	'market of choice', 'omni foods'	['question_type_global', 'question_single_statement']
are there any stores nearby that have a sale on [blouse]?	'sage-allen'	['question_type_global', 'question_three_hop_statement']
show me all department stores	'sage-allen'	['question_type_global', 'question_single_statement']
show me all stores on [Willow Lane] that currently have a sale on [gifts]	'sage-allen'	['question_type_global', 'question_three_hop_statement']
why do i need to buy [honeydew]?	'dinner with my inlaws'	['question_type_local']
what is my shopping list?	'Lentils', 'Green beans', 'Skirret', 'date', 'lime', 'clay pot', 'honeydew', 'rubber duck', 'fig', 'dragonfruit', 'Drawer dishwasher', 'Patio heater'	['question_type_global', 'question_single_statement']
show me all stores on [Willow Lane] that currently have a sale on [vegetables]	'market of choice'	['question_type_global', 'question_three_hop_statement']
what items that I have to buy currently are on sale near me?	'Lentils', 'Skirret'	['question_type_global', 'question_four_hop_statement']
what is on sale at [sage-allen]?	'blouse', 'lamp shade', 'eye liner'	['question_type_local']
what stores near [Willow Lane] have an ongoing sale on [vegetables]?	'market of choice'	['question_type_global', 'question_three_hop_statement']
what supermarkets are there on [Willow Lane]?	'market of choice', 'omni foods'	['question_type_global', 'question_single_statement']
what supermarkets on [Willow Lane] have a sale?	'market of choice'	['question_type_global', 'question_two_hop_statement']
what department stores are there on [Willow Lane]?	'sage-allen'	['question_type_global', 'question_single_statement']
[met foodmarkets] is a [supermarket]
[Grouse] and [Beef heart] are types of [Meat]
what neighborhood is [Chapel Street] in?	'Glen Hazel'	['question_type_local']
what stores on [Willow Lane] have a sale on [gifts]?	'sage-allen'	['question_type_global', 'question_three_hop_statement']
what supermarkets near [Willow Lane] have an ongoing sale?	'market of choice'	['question_type_global', 'question_two_hop_statement']
why do i need to buy [date]?	'thanksgiving dinner'	['question_type_local']
show me all supermarkets on [Willow Lane] that currently have a sale	'market of choice'	['question_type_global', 'question_two_hop_statement']
show me all stores on [Willow Lane] that currently have a sale on [vegetables]	'market of choice'	['question_type_global', 'question_three_hop_statement']
is there a sale on any items on my shopping list for [thanksgiving dinner]?	'Lentils', 'Skirret'	['question_type_global', 'question_two_hop_statement']
is there a store near my location is having a sale on [Chicken]?	'market of choice'	['question_type_global', 'question_three_hop_statement']
what do i need to buy?	'Lentils', 'Green beans', 'Skirret', 'date', 'lime', 'clay pot', 'honeydew', 'rubber duck', 'fig', 'dragonfruit', 'Drawer dishwasher', 'Patio heater'	['question_type_global', 'question_single_statement']
what are the department stores on [Willow Lane]?	'sage-allen'	['question_type_global', 'question_single_statement']
show me all of the stores	'market of choice', 'omni foods', 'sage-allen', 'met foodmarkets'	['question_type_global', 'question_single_statement']
Do I need to buy any [vegetables]?	'Lentils', 'Green beans', 'Skirret'	['question_type_global', 'question_two_hop_statement']
is there anything on my list that's on sale somewhere?	'Lentils', 'Skirret'	['question_type_global', 'question_two_hop_statement']
show me all supermarkets near [Willow Lane]	'market of choice', 'omni foods'	['question_type_global', 'question_single_statement']
don't forget about an upcoming [my honeymoon]
is there a store near my location is having a sale?	'market of choice', 'sage-allen'	['question_type_global', 'question_three_hop_statement']
what supermarkets near [Willow Lane] have an ongoing sale?	'market of choice'	['question_type_global', 'question_two_hop_statement']
show me all supermarkets on [Willow Lane] that currently have a sale	'market of choice'	['question_type_global', 'question_two_hop_statement']
show me all stores on [Willow Lane] that currently have a sale on [meat]	'market of choice'	['question_type_global', 'question_three_hop_statement']
is there a sale on any items on my shopping list where i am?	'Lentils', 'Skirret'	['question_type_global', 'question_four_hop_statement']
is there anything on my list that's on sale somewhere?	'Lentils', 'Skirret'	['question_type_global', 'question_two_hop_statement']
does any store nearby have anything on sale?	'market of choice', 'sage-allen'	['question_type_global', 'question_three_hop_statement']
[Overalls], [Bow Tie] and [T-Shirt] are all good examples of [Clothing]
what [gifts] do i need to buy?	'clay pot', 'rubber duck'	['question_type_global', 'question_two_hop_statement']
are there any items on my shopping list that there is a sale on at a store nearby?	'Lentils', 'Skirret'	['question_type_global', 'question_four_hop_statement']
are there any stores nearby that have a sale on [meat]?	'market of choice'	['question_type_global', 'question_four_hop_statement']
show me all stores on [Willow Lane] that currently have a sale on [lamp shade]	'sage-allen'	['question_type_global', 'question_two_hop_statement']
show me all of the stores on [Willow Lane]	'market of choice', 'omni foods', 'sage-allen'	['question_type_global', 'question_single_statement']
is there anything on my list that's on sale somewhere?	'Lentils', 'Skirret'	['question_type_global', 'question_two_hop_statement']
what department stores on [Willow Lane] have a sale?	'sage-allen'	['question_type_global', 'question_two_hop_statement']
i just bought [Patio heater] for [my son's graduation]
does any store nearby have anything on sale?	'market of choice', 'sage-allen'	['question_type_global', 'question_three_hop_statement']
show me all of the department stores on [Willow Lane]	'sage-allen'	['question_type_global', 'question_single_statement']
What did I already buy for [that event]?	'Top', 'Dress', 'Skirt', 'Cravat', 'Nightgown', 'Fan heater', 'Patio heater'	['question_type_local']
is there anything on sale at a store nearby?	'Lentils', 'Celery', 'Chicken', 'Skirret', 'blouse', 'lamp shade', 'eye liner'	['question_type_global', 'question_three_hop_statement']
show me all of the supermarkets on [Willow Lane]	'market of choice', 'omni foods'	['question_type_global', 'question_single_statement']
show me all stores near [Willow Lane] that have a sale on [vegetables]	'market of choice'	['question_type_global', 'question_three_hop_statement']
what [vegetables] do i need to buy?	'Lentils', 'Green beans', 'Skirret'	['question_type_global', 'question_two_hop_statement']
please remind me to buy [Briefs] for [my son's graduation]
i just bought [Briefs] for [my son's graduation]
show me all of the supermarkets	'market of choice', 'omni foods', 'met foodmarkets'	['question_type_global', 'question_single_statement']
get rid of [clay pot] from my shopping list for [this event]
what items that I have to buy for [thanksgiving dinner] currently are on sale?	'Lentils', 'Skirret'	['question_type_global', 'question_two_hop_statement']
show me all department stores near [Willow Lane]	'sage-allen'	['question_type_global', 'question_single_statement']
what stores on [Willow Lane] have a sale on [vegetables]?	'market of choice'	['question_type_global', 'question_three_hop_statement']
show me all supermarkets near [Willow Lane]	'market of choice', 'omni foods'	['question_type_global', 'question_single_statement']
what do i need [Skirret] for?	'thanksgiving dinner'	['question_type_local']
what do stores near me have on sale?	'Lentils', 'Celery', 'Chicken', 'Skirret', 'blouse', 'lamp shade', 'eye liner'	['question_type_global', 'question_three_hop_statement']
what supermarkets near [Willow Lane] have an ongoing sale?	'market of choice'	['question_type_global', 'question_two_hop_statement']
show me all stores on [Willow Lane] that currently have a sale on [Chicken]	'market of choice'	['question_type_global', 'question_two_hop_statement']
show me all stores near [Willow Lane]	'market of choice', 'omni foods', 'sage-allen'	['question_type_global', 'question_single_statement']
make sure to buy [Lingerie] for [this event]
what do i have on shopping list for [that event]?	'Lingerie', 'rubber duck', 'Drawer dishwasher'	['question_type_local']
are there any stores nearby that have a sale on [vegetables]?	'market of choice'	['question_type_global', 'question_four_hop_statement']
what stores on [Willow Lane] have a sale?	'market of choice', 'sage-allen'	['question_type_global', 'question_two_hop_statement']
what kind of [fruit] do I need to get?	'date', 'lime', 'honeydew', 'fig', 'dragonfruit'	['question_type_global', 'question_two_hop_statement']
are there any items on my shopping list that there is a sale on?	'Lentils', 'Skirret'	['question_type_global', 'question_two_hop_statement']
is there a store nearby with a sale on [eye liner] going on right now?	'sage-allen'	['question_type_global', 'question_three_hop_statement']
here are some examples of [Fruit]: [banana], [lemon] and [watermelon]
what department stores are there on [Willow Lane]?	'sage-allen'	['question_type_global', 'question_single_statement']
what do stores near me are have a sale on?	'Lentils', 'Celery', 'Chicken', 'Skirret', 'blouse', 'lamp shade', 'eye liner'	['question_type_global', 'question_three_hop_statement']
what [vegetables] do i need to buy?	'Lentils', 'Green beans', 'Skirret'	['question_type_global', 'question_two_hop_statement']
show me all supermarkets that i tought you	'market of choice', 'omni foods', 'met foodmarkets'	['question_type_global', 'question_single_statement']
Do I need to buy any [gifts]?	'rubber duck'	['question_type_global', 'question_two_hop_statement']
is there a sale on [Celery] anywhere?	'market of choice'	['question_type_local']
Do I need to buy any [appliances]?	'Drawer dishwasher'	['question_type_global', 'question_two_hop_statement']
are there any [vegetables] on my shopping list that there is a sale on?	'Lentils', 'Skirret'	['question_type_global', 'question_three_hop_statement']
show me all of the stores	'market of choice', 'omni foods', 'sage-allen', 'met foodmarkets'	['question_type_global', 'question_single_statement']
is there a sale on any [vegetables] on my shopping list?	'Lentils', 'Skirret'	['question_type_global', 'question_three_hop_statement']
what is on sale near my current location?	'Lentils', 'Celery', 'Chicken', 'Skirret', 'blouse', 'lamp shade', 'eye liner'	['question_type_global', 'question_three_hop_statement']
what [gifts] do i need to buy?	'rubber duck'	['question_type_global', 'question_two_hop_statement']
i don't need [rubber duck] for [my son's graduation] anymore
add [Waistcoat] and [Bow Tie] to my shopping list for [my son's graduation]
What do I need to buy for [my son's graduation]?	'Lingerie', 'Waistcoat', 'Drawer dishwasher', 'Bow Tie'	['question_type_local']
what stores on [Willow Lane] have a sale on [gifts]?	'sage-allen'	['question_type_global', 'question_three_hop_statement']
does any store nearby have [gifts] on sale?	'sage-allen'	['question_type_global', 'question_four_hop_statement']
[Green beans] is on sale at [market of choice]
what items are on sale at [this store]?	'Lentils', 'Celery', 'Chicken', 'Green beans', 'Skirret'	['question_type_local']
get rid of [this thing] and [Lentils] from my shopping for [dinner with my inlaws]
i need to get [watermelon] for [dinner with my inlaws]
what stores near [Willow Lane] have an ongoing sale on [lamp shade]?	'sage-allen'	['question_type_global', 'question_two_hop_statement']
show me all supermarkets on [Willow Lane] that currently have a sale	'market of choice'	['question_type_global', 'question_two_hop_statement']
please remind me to buy [Beef heart] for [that event]
take off [fig] and [watermelon] from my list for [this event]
what department stores near [Willow Lane] have an ongoing sale?	'sage-allen'	['question_type_global', 'question_two_hop_statement']
What do I need to buy [Drawer dishwasher] for?	"my son's graduation"	['question_type_local']
what kind of [meat] do I need to get?	'Beef heart'	['question_type_global', 'question_two_hop_statement']
is there a store near my location is having a sale on [eye liner]?	'sage-allen'	['question_type_global', 'question_three_hop_statement']
what supermarkets are there on [Willow Lane]?	'market of choice', 'omni foods'	['question_type_global', 'question_single_statement']
what event do I need to buy [date] for	'thanksgiving dinner'	['question_type_local']
what stores near [Willow Lane] have an ongoing sale on [lamp shade]?	'sage-allen'	['question_type_global', 'question_two_hop_statement']
show me all of the stores on [Willow Lane]	'market of choice', 'omni foods', 'sage-allen'	['question_type_global', 'question_single_statement']
show me all department stores near [Willow Lane]	'sage-allen'	['question_type_global', 'question_single_statement']
what items did i already get for [thanksgiving dinner]?	'blackberry', 'avocado', 'grapefruit', 'fig'	['question_type_local']
show me all department stores on [Willow Lane] that currently have a sale	'sage-allen'	['question_type_global', 'question_two_hop_statement']
what kind of [vegetables] do I need to get?	'Lentils', 'Skirret'	['question_type_global', 'question_two_hop_statement']
show me all supermarkets near [Willow Lane] that have a sale	'market of choice'	['question_type_global', 'question_two_hop_statement']
are there any [appliances] that i need to get?	'Drawer dishwasher'	['question_type_global', 'question_two_hop_statement']
is there any [vegetables] that I have to buy currently are on sale?	'Lentils', 'Skirret'	['question_type_global', 'question_three_hop_statement']
show me all stores near [Willow Lane]	'market of choice', 'omni foods', 'sage-allen'	['question_type_global', 'question_single_statement']
what stores near [Willow Lane] have an ongoing sale on [meat]?	'market of choice'	['question_type_global', 'question_three_hop_statement']
Do i have any [vegetables] on my shopping list?	'Lentils', 'Skirret'	['question_type_global', 'question_two_hop_statement']
i need to make sure to get [lemon] for [dinner with my inlaws]
i just bought both [lemon] and [honeydew] for [dinner with my inlaws]
is there a store nearby with a sale on [meat] going on right now?	'market of choice'	['question_type_global', 'question_four_hop_statement']
are there any stores nearby that have a sale on [vegetables]?	'market of choice'	['question_type_global', 'question_four_hop_statement']
what are the supermarkets?	'market of choice', 'omni foods', 'met foodmarkets'	['question_type_global', 'question_single_statement']
show me all stores on [Willow Lane] that currently have a sale on [meat]	'market of choice'	['question_type_global', 'question_three_hop_statement']
show me all stores near [Willow Lane] that have a sale on [vegetables]	'market of choice'	['question_type_global', 'question_three_hop_statement']
is there a store near my location that has what i need on sale?	'market of choice'	['question_type_global', 'question_four_hop_statement']
i absolutely must not forget to get both [lime] and [date] for [dinner with my inlaws]
take off [date] and [Beef heart] from my list for [dinner with my inlaws]
what do I need for [dinner with my inlaws]?	'lime'	['question_type_local']
is there a store nearby with a sale on [meat] going on right now?	'market of choice'	['question_type_global', 'question_four_hop_statement']
there is a [department store] called [kaufmann's] on [Willow Lane]
is there a store nearby with any of the items on my shopping list on sale?	'market of choice'	['question_type_global', 'question_four_hop_statement']
is there a store nearby with a sale on [gifts] going on right now?	'sage-allen'	['question_type_global', 'question_four_hop_statement']
what are the stores on [Willow Lane]?	'market of choice', 'omni foods', 'sage-allen', "kaufmann's"	['question_type_global', 'question_single_statement']
remove [lime] from the list for [dinner with my inlaws]
show me all of the department stores	'sage-allen', "kaufmann's"	['question_type_global', 'question_single_statement']
[sage-allen] is a [department store]
what supermarkets on [Willow Lane] have a sale?	'market of choice'	['question_type_global', 'question_two_hop_statement']
show me all supermarkets near [Willow Lane] that have a sale	'market of choice'	['question_type_global', 'question_two_hop_statement']
show me all department stores	'sage-allen', "kaufmann's"	['question_type_global', 'question_single_statement']
why do i need to buy [Waistcoat]?	"my son's graduation"	['question_type_local']
are there any [clothing] that i need to get?	'Lingerie', 'Waistcoat', 'Bow Tie'	['question_type_global', 'question_two_hop_statement']
Do i have any [vegetables] on my shopping list?	'Lentils', 'Skirret'	['question_type_global', 'question_two_hop_statement']
is there a store nearby with a sale on [gifts] going on right now?	'sage-allen'	['question_type_global', 'question_four_hop_statement']
add the following for [thanksgiving dinner]: [Beef heart] and [Chicken]
is there a sale on [blouse] anywhere?	'sage-allen'	['question_type_local']
show me all department stores near [Willow Lane]	'sage-allen', "kaufmann's"	['question_type_global', 'question_single_statement']
what stores on [Willow Lane] have a sale on [gifts]?	'sage-allen'	['question_type_global', 'question_three_hop_statement']
what are the department stores?	'sage-allen', "kaufmann's"	['question_type_global', 'question_single_statement']
are there any stores nearby that have a sale on [vegetables]?	'market of choice'	['question_type_global', 'question_four_hop_statement']
Where is [Chicken] on sale?	'market of choice'	['question_type_local']
what supermarkets are there on [Willow Lane]?	'market of choice', 'omni foods'	['question_type_global', 'question_single_statement']
are there any [appliances] that i need to get?	'Drawer dishwasher'	['question_type_global', 'question_two_hop_statement']
What do I need to buy [Chicken] for?	'thanksgiving dinner'	['question_type_local']
are there any stores nearby that have a sale?	'market of choice', 'sage-allen'	['question_type_global', 'question_three_hop_statement']
what [vegetables] do i need to buy?	'Lentils', 'Skirret'	['question_type_global', 'question_two_hop_statement']
are there any stores nearby that have a sale on items that i need?	'market of choice'	['question_type_global', 'question_four_hop_statement']
show me all supermarkets on [Willow Lane] that currently have a sale	'market of choice'	['question_type_global', 'question_two_hop_statement']
What did I already buy for [my son's graduation]?	'Top', 'Dress', 'Skirt', 'Cravat', 'Briefs', 'clay pot', 'Nightgown', 'Fan heater', 'rubber duck', 'Patio heater'	['question_type_local']
are there any [meat] that i need to get?	'Chicken', 'Beef heart'	['question_type_global', 'question_two_hop_statement']
what do i need to buy?	'Lentils', 'Chicken', 'Skirret', 'Lingerie', 'date', 'lime', 'Waistcoat', 'dragonfruit', 'Drawer dishwasher', 'Beef heart', 'Bow Tie'	['question_type_global', 'question_single_statement']
What do I need to buy [Chicken] for?	'thanksgiving dinner'	['question_type_local']
show me all of the department stores on [Willow Lane]	'sage-allen', "kaufmann's"	['question_type_global', 'question_single_statement']
what is on sale near my current location?	'Lentils', 'Celery', 'Chicken', 'Green beans', 'Skirret', 'blouse', 'lamp shade', 'eye liner'	['question_type_global', 'question_three_hop_statement']
Do i have any [fruit] on my shopping list?	'date', 'lime', 'dragonfruit'	['question_type_global', 'question_two_hop_statement']
is there a sale on any items on my shopping list where i am?	'Lentils', 'Chicken', 'Skirret'	['question_type_global', 'question_four_hop_statement']
Do I need to buy any [fruit]?	'date', 'lime', 'dragonfruit'	['question_type_global', 'question_two_hop_statement']
[date] and [lemon] are on sale at [market of choice]
what stores on [Willow Lane] have a sale on [meat]?	'market of choice'	['question_type_global', 'question_three_hop_statement']
are there any [clothing] that i need to get?	'Lingerie', 'Waistcoat', 'Bow Tie'	['question_type_global', 'question_two_hop_statement']
are there any [meat] that i need to get?	'Chicken', 'Beef heart'	['question_type_global', 'question_two_hop_statement']
what items did i already get for [dinner with my inlaws]?	'blackberry', 'avocado', 'Lentils', 'Celery', 'Chicken', 'Green beans', 'Skirret', 'date', 'lime', 'honeydew', 'fig', 'Beef heart', 'lemon', 'watermelon'	['question_type_local']
are there any stores nearby that have a sale on [vegetables]?	'market of choice'	['question_type_global', 'question_four_hop_statement']
what stores on [Willow Lane] have a sale on [vegetables]?	'market of choice'	['question_type_global', 'question_three_hop_statement']
please remind me to buy [watermelon] and [banana] for [thanksgiving dinner]
what event do I need to buy [Bow Tie] for	"my son's graduation"	['question_type_local']
Do I need to buy any [appliances]?	'Drawer dishwasher'	['question_type_global', 'question_two_hop_statement']
what's currently on sale at [sage-allen on Willow Lane]?	'blouse', 'lamp shade', 'eye liner'	['question_type_local']
what items do I need to get?	'Lentils', 'Chicken', 'Skirret', 'Lingerie', 'date', 'lime', 'Waistcoat', 'dragonfruit', 'Drawer dishwasher', 'Beef heart', 'Bow Tie', 'banana', 'watermelon'	['question_type_global', 'question_single_statement']
[Route 64] is in [Queen Village]
what stores near [Willow Lane] have an ongoing sale on [fruit]?	'market of choice'	['question_type_global', 'question_three_hop_statement']
show me all department stores near [Willow Lane] that have a sale	'sage-allen'	['question_type_global', 'question_two_hop_statement']
what kind of [appliances] do I need to get?	'Drawer dishwasher'	['question_type_global', 'question_two_hop_statement']
what are the stores?	'market of choice', 'omni foods', 'sage-allen', 'met foodmarkets', "kaufmann's"	['question_type_global', 'question_single_statement']
are there any [appliances] that i need to get?	'Drawer dishwasher'	['question_type_global', 'question_two_hop_statement']
what stores on [Willow Lane] have a sale?	'market of choice', 'sage-allen'	['question_type_global', 'question_two_hop_statement']
does any store nearby have [fruit] on sale?	'market of choice'	['question_type_global', 'question_four_hop_statement']
what do i need to buy?	'Lentils', 'Chicken', 'Skirret', 'Lingerie', 'date', 'lime', 'Waistcoat', 'dragonfruit', 'Drawer dishwasher', 'Beef heart', 'Bow Tie', 'banana', 'watermelon'	['question_type_global', 'question_single_statement']
what stores on [Willow Lane] have a sale on [meat]?	'market of choice'	['question_type_global', 'question_three_hop_statement']
i no longer need [Lentils] and [date] for [thanksgiving dinner]
Do I need to buy any [meat]?	'Chicken', 'Beef heart'	['question_type_global', 'question_two_hop_statement']
what are the supermarkets?	'market of choice', 'omni foods', 'met foodmarkets'	['question_type_global', 'question_single_statement']
[apple] and [tomato] are all on sale at [omni foods]
[Kangaroo], [Pork] and [Beef liver] are all different types of [Meat]
what neighborhood am I in?	'Glen Hazel'	['question_type_local']
is there anything on my list that's on sale somewhere near my current location?	'Chicken', 'Skirret'	['question_type_global', 'question_four_hop_statement']
please remind me to buy [tomato] for [thanksgiving dinner]
i just got [dragonfruit] for [thanksgiving dinner]
what do i have on shopping list for [that event]?	'Chicken', 'Skirret', 'lime', 'tomato', 'Beef heart', 'banana', 'watermelon'	['question_type_local']
what stores near [Willow Lane] have an ongoing sale on [vegetables]?	'market of choice'	['question_type_global', 'question_three_hop_statement']
are there any stores nearby that have a sale on [gifts]?	'sage-allen'	['question_type_global', 'question_four_hop_statement']
what are the stores on [Willow Lane]?	'market of choice', 'omni foods', 'sage-allen', "kaufmann's"	['question_type_global', 'question_single_statement']
i need to make sure to get [Kangaroo] for [dinner with my inlaws]
what items did i already get for [this event]?	'blackberry', 'avocado', 'Lentils', 'Celery', 'Chicken', 'Green beans', 'Skirret', 'date', 'lime', 'honeydew', 'fig', 'Beef heart', 'lemon', 'watermelon'	['question_type_local']
is there a sale on any [meat] on my shopping list?	'Chicken'	['question_type_global', 'question_three_hop_statement']
is there any [meat] on my list that's on sale somewhere?	'Chicken'	['question_type_global', 'question_three_hop_statement']
what supermarkets on [Willow Lane] have a sale?	'market of choice', 'omni foods'	['question_type_global', 'question_two_hop_statement']
is there a store nearby with any of the items on my shopping list on sale?	'market of choice', 'omni foods'	['question_type_global', 'question_four_hop_statement']
is there a store near my location that has what i need on sale?	'market of choice', 'omni foods'	['question_type_global', 'question_four_hop_statement']
what neighborhood is [Route 64] in?	'Queen Village'	['question_type_local']
Do i have any [appliances] on my shopping list?	'Drawer dishwasher'	['question_type_global', 'question_two_hop_statement']
show me all of the stores	'market of choice', 'omni foods', 'sage-allen', 'met foodmarkets', "kaufmann's"	['question_type_global', 'question_single_statement']
is there a sale on any items on my shopping list for [thanksgiving dinner]?	'Chicken', 'Skirret', 'tomato'	['question_type_global', 'question_two_hop_statement']
Do i have any [fruit] on my shopping list?	'lime', 'tomato', 'banana', 'watermelon'	['question_type_global', 'question_two_hop_statement']
show me all stores near [Willow Lane] that have a sale on [fruit]	'market of choice', 'omni foods'	['question_type_global', 'question_three_hop_statement']
show me all stores on [Willow Lane] that currently have a sale on [gifts]	'sage-allen'	['question_type_global', 'question_three_hop_statement']
does any store nearby have [blouse] on sale?	'sage-allen'	['question_type_global', 'question_three_hop_statement']
what stores on [Willow Lane] have a sale?	'market of choice', 'omni foods', 'sage-allen'	['question_type_global', 'question_two_hop_statement']
[Tie press] is a [Appliance]
what do stores near me have on sale?	'Lentils', 'Celery', 'Chicken', 'Green beans', 'Skirret', 'blouse', 'date', 'lamp shade', 'eye liner', 'tomato', 'apple', 'lemon'	['question_type_global', 'question_three_hop_statement']
what [vegetables] do i need to buy?	'Skirret'	['question_type_global', 'question_two_hop_statement']
what supermarkets are there?	'market of choice', 'omni foods', 'met foodmarkets'	['question_type_global', 'question_single_statement']
i need to get [grapefruit] for [dinner with my inlaws]
take off [that item] and [Kangaroo] from my list for [dinner with my inlaws]
what stores on [Willow Lane] have a sale on [vegetables]?	'market of choice'	['question_type_global', 'question_three_hop_statement']
what are the things that I need to get?	'Chicken', 'Skirret', 'Lingerie', 'lime', 'Waistcoat', 'tomato', 'Drawer dishwasher', 'Beef heart', 'Bow Tie', 'banana', 'watermelon'	['question_type_global', 'question_single_statement']
show me all of the supermarkets	'market of choice', 'omni foods', 'met foodmarkets'	['question_type_global', 'question_single_statement']
[Chicken Liver] is a type of [Meat]
what are the supermarkets on [Willow Lane]?	'market of choice', 'omni foods'	['question_type_global', 'question_single_statement']
show me all stores on [Willow Lane] that currently have a sale on [meat]	'market of choice'	['question_type_global', 'question_three_hop_statement']
what kind of [meat] do I need to get?	'Chicken', 'Beef heart'	['question_type_global', 'question_two_hop_statement']
are there any [vegetables] on my shopping list that there is a sale on?	'Skirret'	['question_type_global', 'question_three_hop_statement']
Do I need to buy any [clothing]?	'Lingerie', 'Waistcoat', 'Bow Tie'	['question_type_global', 'question_two_hop_statement']
what supermarkets near [Willow Lane] have an ongoing sale?	'market of choice', 'omni foods'	['question_type_global', 'question_two_hop_statement']
does any store nearby have [fruit] on sale?	'market of choice', 'omni foods'	['question_type_global', 'question_four_hop_statement']
are there any [meat] on my shopping list that there is a sale on?	'Chicken'	['question_type_global', 'question_three_hop_statement']
get rid of [Lingerie] from my shopping list for [my son's graduation]
make sure to buy [bookmark] and [socks] for [my son's graduation]
what neighborhood is [Broad Street West] in?	'Glen Hazel'	['question_type_local']
is there a store nearby with a sale on [vegetables] going on right now?	'market of choice'	['question_type_global', 'question_four_hop_statement']
are there any items on my shopping list that there is a sale on?	'Chicken', 'Skirret', 'tomato'	['question_type_global', 'question_two_hop_statement']
add [apple] to my shopping list for [dinner with my inlaws]
get rid of [apple] from my shopping list for [dinner with my inlaws]
what stores on [Willow Lane] have a sale on [vegetables]?	'market of choice'	['question_type_global', 'question_three_hop_statement']
show me all of the department stores	'sage-allen', "kaufmann's"	['question_type_global', 'question_single_statement']
