remember that i have [brown bag lunch at school]
[Cardigan], [Slippers] and [Poncho] are [Clothing]
[lamp], [rug] and [headphones] are all different types of [Gift]
don't forget about an upcoming [colin's birthday]
please remind me to buy [this thing] and [rug] for [that event]
there is a [supermarket] called [key food] that I shop in pretty often
What do I need to buy for [colin's birthday]?	'rug', 'headphones'	['question_type_local']
[papaya] is a type of [Fruit]
make sure to buy [that item] for [brown bag lunch at school]
what [gifts] do i need to buy?	'rug', 'headphones'	['question_type_global', 'question_two_hop_statement']
[Ham] is a kind of [Meat]
what do i need [this fruit] for?	'brown bag lunch at school'	['question_type_local']
show me all stores	'key food'	['question_type_global', 'question_single_statement']
what event do I need to buy [this fruit] for	'brown bag lunch at school'	['question_type_local']
what is my shopping list?	'rug', 'headphones', 'papaya'	['question_type_global', 'question_single_statement']
what stores are there that I taught you?	'key food'	['question_type_global', 'question_single_statement']
[tomato], [passon_fruit] and [pomegranate] are all different types of [Fruit]
show me all of the supermarkets	'key food'	['question_type_global', 'question_single_statement']
i am pretty sure that [West Avenue] is in [Four Mile Run]
what are the supermarkets?	'key food'	['question_type_global', 'question_single_statement']
i need to make sure to get [passon_fruit] for [brown bag lunch at school]
what are the things that I need to get?	'rug', 'headphones', 'papaya', 'passon_fruit'	['question_type_global', 'question_single_statement']
i just bought [papaya] and [this thing] for [that event]
what did i remove from [brown bag lunch at school]?	'papaya', 'passon_fruit'	['question_type_local']
show me all of the stores	'key food'	['question_type_global', 'question_single_statement']
what is my shopping list?	'rug', 'headphones'	['question_type_global', 'question_single_statement']
what are the stores?	'key food'	['question_type_global', 'question_single_statement']
[piano], [computer] and [mirror] are all different types of [Gift]
what do i need to buy?	'rug', 'headphones'	['question_type_global', 'question_single_statement']
please remind me to buy [Ham] for [brown bag lunch at school]
What do I need to buy for [that event]?	'Ham'	['question_type_local']
remember that i have [karen's potluck tonight]
what supermarkets are there?	'key food'	['question_type_global', 'question_single_statement']
add the following for [colin's birthday]: [Poncho] and [Slippers]
remove these for [colin's birthday]: [Poncho] and [headphones]
make sure to buy [lamp] for [colin's birthday]
what did i remove from [that event]?	'Poncho', 'headphones'	['question_type_local']
i don't need [Slippers] and [that item] for [colin's birthday] anymore
[guava], [jujube] and [satsuma] are all different types of [Fruit]
show me all supermarkets that i tought you	'key food'	['question_type_global', 'question_single_statement']
[Cornish Hen] is a kind of [Meat]
what stores are there that I taught you?	'key food'	['question_type_global', 'question_single_statement']
[pomegranate] and [satsuma] are on sale at [key food]
this particular [key food] is located on [West Avenue]
what things do I need to buy for [colin's birthday]	'rug'	['question_type_local']
[Turtle] is a type of [Meat]
what are the stores?	'key food'	['question_type_global', 'question_single_statement']
[chocolate] is a type of [Gift]
what supermarkets near [West Avenue] have an ongoing sale?	'key food'	['question_type_global', 'question_two_hop_statement']
what [gifts] do i need to buy?	'rug'	['question_type_global', 'question_two_hop_statement']
[Oven] and [Oil heater] are [Appliance]
just purchases [Ham] for [brown bag lunch at school]
add [pomegranate] and [satsuma] to my shopping list for [brown bag lunch at school]
what things did i get for [brown bag lunch at school]	'papaya', 'Ham', 'passon_fruit'	['question_type_local']
show me all supermarkets that i tought you	'key food'	['question_type_global', 'question_single_statement']
what supermarkets are there?	'key food'	['question_type_global', 'question_single_statement']
what is my shopping list?	'rug', 'pomegranate', 'satsuma'	['question_type_global', 'question_single_statement']
what are the supermarkets on [West Avenue]?	'key food'	['question_type_global', 'question_single_statement']
[Acorn squash], [White radish] and [Borlotti bean] are [Vegetables]
what stores near [West Avenue] have an ongoing sale?	'key food'	['question_type_global', 'question_two_hop_statement']
make sure to buy [Cardigan] for [colin's birthday]
remove these for [colin's birthday]: [rug] and [this clothing]
what did i remove from [colin's birthday]?	'Cardigan', 'Slippers', 'Poncho', 'lamp', 'rug', 'headphones'	['question_type_local']
is there a sale on any items on my shopping list?	'pomegranate', 'satsuma'	['question_type_global', 'question_two_hop_statement']
what stores near [West Avenue] have an ongoing sale on [fruit]?	'key food'	['question_type_global', 'question_three_hop_statement']
show me all stores on [West Avenue] that currently have a sale on [satsuma]	'key food'	['question_type_global', 'question_two_hop_statement']
what supermarkets are there on [West Avenue]?	'key food'	['question_type_global', 'question_single_statement']
what stores near [West Avenue] have an ongoing sale on [satsuma]?	'key food'	['question_type_global', 'question_two_hop_statement']
what stores on [West Avenue] have a sale on [fruit]?	'key food'	['question_type_global', 'question_three_hop_statement']
what supermarkets near [West Avenue] have an ongoing sale?	'key food'	['question_type_global', 'question_two_hop_statement']
what are the things that I need to get?	'pomegranate', 'satsuma'	['question_type_global', 'question_single_statement']
for example [Fruit] are [kiwi] and [raspberry]
are there any [fruit] on my shopping list that there is a sale on?	'pomegranate', 'satsuma'	['question_type_global', 'question_three_hop_statement']
are there any items on my shopping list that there is a sale on?	'pomegranate', 'satsuma'	['question_type_global', 'question_two_hop_statement']
what supermarkets are there on [West Avenue]?	'key food'	['question_type_global', 'question_single_statement']
there is a [supermarket] called [giant eagle] on [West Avenue]
what do i need to buy?	'pomegranate', 'satsuma'	['question_type_global', 'question_single_statement']
Do i have any [fruit] on my shopping list?	'pomegranate', 'satsuma'	['question_type_global', 'question_two_hop_statement']
what stores on [West Avenue] have a sale on [satsuma]?	'key food'	['question_type_global', 'question_two_hop_statement']
what [fruit] do i need to buy?	'pomegranate', 'satsuma'	['question_type_global', 'question_two_hop_statement']
are there any [fruit] on my shopping list that there is a sale on?	'pomegranate', 'satsuma'	['question_type_global', 'question_three_hop_statement']
what are the things that I need to get?	'pomegranate', 'satsuma'	['question_type_global', 'question_single_statement']
[satsuma], [tomato] and [that item] are on sale at [this store]
[giant eagle] no longer has [tomato], [satsuma] and [raspberry] on sale
don't forget about an upcoming [my daughter's graduation]
show me all of the stores	'key food', 'giant eagle'	['question_type_global', 'question_single_statement']
what stores on [West Avenue] have a sale on [fruit]?	'key food'	['question_type_global', 'question_three_hop_statement']
[huckleberry], [tangerine] and [pear] are all types of [Fruit]
what is on sale at [key food]?	'pomegranate', 'satsuma'	['question_type_local']
is there a sale on any items on my shopping list for [brown bag lunch at school]?	'pomegranate', 'satsuma'	['question_type_global', 'question_two_hop_statement']
[Mousetrap], [Steam mop] and [Ceiling fan] are all examples of [Appliance]
[ipod] is a type of [Gift]
show me all stores near [West Avenue] that have a sale	'key food'	['question_type_global', 'question_two_hop_statement']
what are the stores on [West Avenue]?	'key food', 'giant eagle'	['question_type_global', 'question_single_statement']
[Snake] and [Turkey] are both different kinds of [Meat]
is there a sale on any [fruit] on my shopping list?	'pomegranate', 'satsuma'	['question_type_global', 'question_three_hop_statement']
what items do I need to get?	'pomegranate', 'satsuma'	['question_type_global', 'question_single_statement']
are there any [fruit] that i need to get?	'pomegranate', 'satsuma'	['question_type_global', 'question_two_hop_statement']
[honeydew] is a [Fruit]
what stores are there that I taught you?	'key food', 'giant eagle'	['question_type_global', 'question_single_statement']
what things did i get for [brown bag lunch at school]	'papaya', 'Ham', 'passon_fruit'	['question_type_local']
what stores on [West Avenue] have a sale on [fruit]?	'key food'	['question_type_global', 'question_three_hop_statement']
what do i need to buy?	'pomegranate', 'satsuma'	['question_type_global', 'question_single_statement']
[key food] has [Cornish Hen], [Snake] and [Turkey] on sale!
what's currently on sale at [key food]?	'pomegranate', 'satsuma', 'Cornish Hen', 'Snake', 'Turkey'	['question_type_local']
show me all stores near [West Avenue] that have a sale on [fruit]	'key food'	['question_type_global', 'question_three_hop_statement']
[Paper shredder] is a type of [Appliance]
What stores is [pomegranate] on sale at	'key food'	['question_type_local']
what stores on [West Avenue] have a sale?	'key food'	['question_type_global', 'question_two_hop_statement']
Do i have any [fruit] on my shopping list?	'pomegranate', 'satsuma'	['question_type_global', 'question_two_hop_statement']
there is a [supermarket] called [hugo] on [West Avenue]
show me all stores on [West Avenue] that currently have a sale on [meat]	'key food'	['question_type_global', 'question_three_hop_statement']
what event do I need to buy [satsuma] for	'brown bag lunch at school'	['question_type_local']
what stores are there on [West Avenue]?	'key food', 'giant eagle', 'hugo'	['question_type_global', 'question_single_statement']
is there any [fruit] on my list that's on sale somewhere?	'pomegranate', 'satsuma'	['question_type_global', 'question_three_hop_statement']
what stores near [West Avenue] have an ongoing sale on [meat]?	'key food'	['question_type_global', 'question_three_hop_statement']
what supermarkets are there on [West Avenue]?	'key food', 'giant eagle', 'hugo'	['question_type_global', 'question_single_statement']
[passon_fruit] and [jujube] are on sale at [this supermarket]
what items do I need to get?	'pomegranate', 'satsuma'	['question_type_global', 'question_single_statement']
show me all stores near [West Avenue] that have a sale on [passon_fruit]	'hugo'	['question_type_global', 'question_two_hop_statement']
what items did i already get for [colin's birthday]?	'Cardigan', 'Slippers', 'Poncho', 'lamp', 'rug', 'headphones'	['question_type_local']
show me all stores	'key food', 'giant eagle', 'hugo'	['question_type_global', 'question_single_statement']
what supermarkets near [West Avenue] have an ongoing sale?	'key food', 'hugo'	['question_type_global', 'question_two_hop_statement']
are there any items on my shopping list that there is a sale on?	'pomegranate', 'satsuma'	['question_type_global', 'question_two_hop_statement']
what stores on [West Avenue] have a sale on [meat]?	'key food'	['question_type_global', 'question_three_hop_statement']
is there a sale on any items on my shopping list for [brown bag lunch at school]?	'pomegranate', 'satsuma'	['question_type_global', 'question_two_hop_statement']
show me all stores on [West Avenue] that currently have a sale on [pomegranate]	'key food'	['question_type_global', 'question_two_hop_statement']
what are the stores on [West Avenue]?	'key food', 'giant eagle', 'hugo'	['question_type_global', 'question_single_statement']
show me all stores on [West Avenue] that currently have a sale	'key food', 'hugo'	['question_type_global', 'question_two_hop_statement']
what are the things that I need to get?	'pomegranate', 'satsuma'	['question_type_global', 'question_single_statement']
what stores on [West Avenue] have a sale?	'key food', 'hugo'	['question_type_global', 'question_two_hop_statement']
is there a sale on [passon_fruit] anywhere?	'hugo'	['question_type_local']
what do i need [satsuma] for?	'brown bag lunch at school'	['question_type_local']
what stores are there that I taught you?	'key food', 'giant eagle', 'hugo'	['question_type_global', 'question_single_statement']
there is a [supermarket] called [hugo] that I shop in pretty often
[Cornish Hen] and [Turkey] are all on sale at [hugo]
what's currently on sale at [hugo that I last mentioned]?	'Cornish Hen', 'Turkey'	['question_type_local']
show me all stores	'key food', 'giant eagle', 'hugo'	['question_type_global', 'question_single_statement']
what stores on [West Avenue] have a sale on [meat]?	'key food'	['question_type_global', 'question_three_hop_statement']
What stores is [Cornish Hen] on sale at	'key food', 'hugo'	['question_type_local']
there is a [supermarket] called [market of choice] on [West Avenue]
show me all supermarkets near [West Avenue]	'key food', 'giant eagle', 'hugo', 'market of choice'	['question_type_global', 'question_single_statement']
are there any items on my shopping list that there is a sale on?	'pomegranate', 'satsuma'	['question_type_global', 'question_two_hop_statement']
what stores are located on [West Avenue]?	'key food', 'hugo', 'giant eagle', 'market of choice'	['question_type_local']
what are the things that I need to get?	'pomegranate', 'satsuma'	['question_type_global', 'question_single_statement']
there is a [department store] called [jordan marsch] on [West Avenue]
[Turtle], [Turkey] and [Snake] are all on sale at [market of choice]
show me all stores on [West Avenue] that currently have a sale on [fruit]	'key food', 'hugo'	['question_type_global', 'question_three_hop_statement']
why do i need to buy [pomegranate]?	'brown bag lunch at school'	['question_type_local']
what is my shopping list?	'pomegranate', 'satsuma'	['question_type_global', 'question_single_statement']
what stores on [West Avenue] have a sale on [fruit]?	'key food', 'hugo'	['question_type_global', 'question_three_hop_statement']
show me all stores on [West Avenue] that currently have a sale on [meat]	'key food', 'market of choice'	['question_type_global', 'question_three_hop_statement']
show me all supermarkets near [West Avenue]	'key food', 'giant eagle', 'hugo', 'market of choice'	['question_type_global', 'question_single_statement']
what are the department stores?	'jordan marsch'	['question_type_global', 'question_single_statement']
what stores near [West Avenue] have an ongoing sale on [Turkey]?	'key food', 'market of choice'	['question_type_global', 'question_two_hop_statement']
what supermarkets on [West Avenue] have a sale?	'key food', 'hugo', 'market of choice'	['question_type_global', 'question_two_hop_statement']
What stores is [pomegranate] on sale at	'key food'	['question_type_local']
show me all supermarkets near [West Avenue] that have a sale	'key food', 'hugo', 'market of choice'	['question_type_global', 'question_two_hop_statement']
Where is [satsuma] on sale?	'key food'	['question_type_local']
is there any [fruit] that I have to buy currently are on sale?	'pomegranate', 'satsuma'	['question_type_global', 'question_three_hop_statement']
show me all stores on [West Avenue] that currently have a sale on [fruit]	'key food', 'hugo'	['question_type_global', 'question_three_hop_statement']
Where is [Snake] on sale?	'key food', 'market of choice'	['question_type_local']
What stores is [Turkey] on sale at	'key food', 'hugo', 'market of choice'	['question_type_local']
show me all stores near [West Avenue]	'key food', 'giant eagle', 'hugo', 'market of choice', 'jordan marsch'	['question_type_global', 'question_single_statement']
show me all department stores near [West Avenue]	'jordan marsch'	['question_type_global', 'question_single_statement']
show me all of the stores on [West Avenue]	'key food', 'giant eagle', 'hugo', 'market of choice', 'jordan marsch'	['question_type_global', 'question_single_statement']
show me all stores on [West Avenue] that currently have a sale	'key food', 'hugo', 'market of choice'	['question_type_global', 'question_two_hop_statement']
show me all stores near [West Avenue] that have a sale on [fruit]	'key food', 'hugo'	['question_type_global', 'question_three_hop_statement']
what are the supermarkets on [West Avenue]?	'key food', 'giant eagle', 'hugo', 'market of choice'	['question_type_global', 'question_single_statement']
[I] am currently on [West Avenue]
is there a sale on [that item] anywhere?	'key food', 'market of choice'	['question_type_local']
show me all stores near [West Avenue]	'key food', 'giant eagle', 'hugo', 'market of choice', 'jordan marsch'	['question_type_global', 'question_single_statement']
are there any [fruit] on my shopping list that there is a sale on?	'pomegranate', 'satsuma'	['question_type_global', 'question_three_hop_statement']
does any store nearby have anything on sale?	'hugo', 'key food', 'market of choice'	['question_type_global', 'question_three_hop_statement']
i often shop at [jordan marsch], which is my local [department store]
[that department store] has [Mousetrap] and [Oil heater] on sale!
is there a store nearby with a sale on [fruit] going on right now?	'hugo', 'key food'	['question_type_global', 'question_four_hop_statement']
what neighborhood am I currently in?	'Four Mile Run'	['question_type_local']
show me all supermarkets that i tought you	'key food', 'giant eagle', 'hugo', 'market of choice'	['question_type_global', 'question_single_statement']
what supermarkets are there on [West Avenue]?	'key food', 'giant eagle', 'hugo', 'market of choice'	['question_type_global', 'question_single_statement']
Where is [passon_fruit] on sale?	'hugo'	['question_type_local']
[Kimchi refrigerator], [Solar water heater] and [Patio heater] are all different types of [Appliance]
are there any stores nearby that have a sale?	'hugo', 'key food', 'market of choice'	['question_type_global', 'question_three_hop_statement']
what is my shopping list?	'pomegranate', 'satsuma'	['question_type_global', 'question_single_statement']
show me all stores on [West Avenue] that currently have a sale	'key food', 'hugo', 'market of choice'	['question_type_global', 'question_two_hop_statement']
what are the stores?	'key food', 'giant eagle', 'hugo', 'market of choice', 'jordan marsch'	['question_type_global', 'question_single_statement']
show me all of the supermarkets on [West Avenue]	'key food', 'giant eagle', 'hugo', 'market of choice'	['question_type_global', 'question_single_statement']
what stores on [West Avenue] have a sale on [Cornish Hen]?	'key food'	['question_type_global', 'question_two_hop_statement']
What stores is [passon_fruit] on sale at	'hugo'	['question_type_local']
what supermarkets near [West Avenue] have an ongoing sale?	'key food', 'hugo', 'market of choice'	['question_type_global', 'question_two_hop_statement']
What do I need to buy [satsuma] for?	'brown bag lunch at school'	['question_type_local']
show me all supermarkets near [West Avenue]	'key food', 'giant eagle', 'hugo', 'market of choice'	['question_type_global', 'question_single_statement']
show me all supermarkets that i tought you	'key food', 'giant eagle', 'hugo', 'market of choice'	['question_type_global', 'question_single_statement']
what stores near [West Avenue] have an ongoing sale on [meat]?	'key food', 'market of choice'	['question_type_global', 'question_three_hop_statement']
does any store nearby have anything on sale?	'hugo', 'key food', 'market of choice'	['question_type_global', 'question_three_hop_statement']
is there a store near my location is having a sale on [fruit]?	'hugo', 'key food'	['question_type_global', 'question_four_hop_statement']
is there a sale on any items on my shopping list?	'pomegranate', 'satsuma'	['question_type_global', 'question_two_hop_statement']
What do I need to buy [pomegranate] for?	'brown bag lunch at school'	['question_type_local']
[Dill] is a kind of [Vegetables]
what do i need to buy?	'pomegranate', 'satsuma'	['question_type_global', 'question_single_statement']
what are the stores?	'key food', 'giant eagle', 'hugo', 'market of choice', 'jordan marsch'	['question_type_global', 'question_single_statement']
show me all stores near [West Avenue]	'key food', 'giant eagle', 'hugo', 'market of choice', 'jordan marsch'	['question_type_global', 'question_single_statement']
what stores near [West Avenue] have an ongoing sale on [fruit]?	'key food', 'hugo'	['question_type_global', 'question_three_hop_statement']
show me all of the supermarkets	'key food', 'giant eagle', 'hugo', 'market of choice'	['question_type_global', 'question_single_statement']
is there anything on my list that's on sale somewhere near my current location?	'pomegranate', 'satsuma'	['question_type_global', 'question_four_hop_statement']
show me all stores	'key food', 'giant eagle', 'hugo', 'market of choice', 'jordan marsch'	['question_type_global', 'question_single_statement']
Do i have any [fruit] on my shopping list?	'pomegranate', 'satsuma'	['question_type_global', 'question_two_hop_statement']
is there anything on my list that's on sale somewhere?	'pomegranate', 'satsuma'	['question_type_global', 'question_two_hop_statement']
does any store nearby have anything on sale?	'hugo', 'key food', 'market of choice'	['question_type_global', 'question_three_hop_statement']
[Sweet potato] and [Black-eyed peas] are both examples of [Vegetables]
what stores near [West Avenue] have an ongoing sale on [meat]?	'key food', 'market of choice'	['question_type_global', 'question_three_hop_statement']
is there a store near my location is having a sale?	'hugo', 'key food', 'market of choice'	['question_type_global', 'question_three_hop_statement']
are there any [fruit] that i need to get?	'pomegranate', 'satsuma'	['question_type_global', 'question_two_hop_statement']
what stores near [West Avenue] have an ongoing sale on [Turtle]?	'market of choice'	['question_type_global', 'question_two_hop_statement']
does any store nearby have any of the items i need on sale?	'key food'	['question_type_global', 'question_four_hop_statement']
show me all stores near [West Avenue] that have a sale on [satsuma]	'key food'	['question_type_global', 'question_two_hop_statement']
[honeydew] and [pear] are all on sale at [key food]
are there any stores nearby that have a sale on [meat]?	'key food', 'market of choice'	['question_type_global', 'question_four_hop_statement']
are there any stores nearby that have a sale on items that i need?	'key food'	['question_type_global', 'question_four_hop_statement']
i often shop at [sears], which is my local [department store]
what supermarkets are there?	'key food', 'giant eagle', 'hugo', 'market of choice'	['question_type_global', 'question_single_statement']
what items do I need to get?	'pomegranate', 'satsuma'	['question_type_global', 'question_single_statement']
[Slippers] is on sale at [that store]
this specific [that department store] is on [West Avenue]
what's currently on sale at [this store]?	'Slippers'	['question_type_local']
what are the supermarkets on [West Avenue]?	'key food', 'giant eagle', 'hugo', 'market of choice'	['question_type_global', 'question_single_statement']
what are the department stores on [West Avenue]?	'jordan marsch', 'sears'	['question_type_global', 'question_single_statement']
what stores are there on [West Avenue]?	'key food', 'giant eagle', 'hugo', 'market of choice', 'jordan marsch', 'sears'	['question_type_global', 'question_single_statement']
what stores on [West Avenue] have a sale on [Turtle]?	'market of choice'	['question_type_global', 'question_two_hop_statement']
what neighborhood is [this street] in?	'Four Mile Run'	['question_type_local']
[papaya] and [tomato] are on sale at [key food]
[Thong], [Shirt] and [Cufflinks] are all different types of [Clothing]
is there a sale on [tomato] anywhere?	'key food'	['question_type_local']
Where is [pear] on sale?	'key food'	['question_type_local']
show me all stores	'key food', 'giant eagle', 'hugo', 'market of choice', 'jordan marsch', 'sears'	['question_type_global', 'question_single_statement']
what stores near [West Avenue] have an ongoing sale on [clothing]?	'sears'	['question_type_global', 'question_three_hop_statement']
please remind me to buy [tomato] for [brown bag lunch at school]
what things do I need to buy for [this event]	'tomato', 'pomegranate', 'satsuma'	['question_type_local']
what do stores near me have on sale?	'Slippers', 'papaya', 'tomato', 'passon_fruit', 'pomegranate', 'jujube', 'satsuma', 'Cornish Hen', 'Turtle', 'pear', 'Snake', 'Turkey', 'honeydew'	['question_type_global', 'question_three_hop_statement']
does any store nearby have any of the items i need on sale?	'key food'	['question_type_global', 'question_four_hop_statement']
[giant eagle] has [White radish] on sale!
what items are on sale at [this store]?	'White radish'	['question_type_local']
what are the stores on [West Avenue]?	'key food', 'giant eagle', 'hugo', 'market of choice', 'jordan marsch', 'sears'	['question_type_global', 'question_single_statement']
[Acorn squash], [Sweet potato] and [White radish] are on sale at [hugo that I last mentioned]
what items are on sale at [hugo that I last mentioned]?	'Cornish Hen', 'Acorn squash', 'White radish', 'Turkey', 'Sweet potato'	['question_type_local']
is there a store near my location is having a sale on [passon_fruit]?	'hugo'	['question_type_global', 'question_three_hop_statement']
are there any stores nearby that have a sale on [vegetables]?	'giant eagle'	['question_type_global', 'question_four_hop_statement']
show me all department stores on [West Avenue] that currently have a sale	'sears'	['question_type_global', 'question_two_hop_statement']
what department stores are there	'jordan marsch', 'sears'	['question_type_global', 'question_single_statement']
[ring], [cell phone] and [purse] are kinds of [Gift]
are there any stores nearby that have a sale on items that i need?	'key food'	['question_type_global', 'question_four_hop_statement']
show me all stores near [West Avenue] that have a sale on [pomegranate]	'key food'	['question_type_global', 'question_two_hop_statement']
is there any [fruit] on my list that's on sale somewhere?	'tomato', 'pomegranate', 'satsuma'	['question_type_global', 'question_three_hop_statement']
is there a store near my location is having a sale?	'giant eagle', 'hugo', 'key food', 'market of choice', 'sears'	['question_type_global', 'question_three_hop_statement']
[Cornish Hen] is on sale at [market of choice]
does any store nearby have [vegetables] on sale?	'giant eagle'	['question_type_global', 'question_four_hop_statement']
what stores near [West Avenue] have an ongoing sale on [meat]?	'key food', 'market of choice'	['question_type_global', 'question_three_hop_statement']
what stores near [West Avenue] have an ongoing sale on [fruit]?	'key food', 'hugo'	['question_type_global', 'question_three_hop_statement']
show me all stores	'key food', 'giant eagle', 'hugo', 'market of choice', 'jordan marsch', 'sears'	['question_type_global', 'question_single_statement']
is there a store near my location is having a sale on [meat]?	'key food', 'market of choice'	['question_type_global', 'question_four_hop_statement']
are there any stores nearby that have a sale on [fruit]?	'hugo', 'key food'	['question_type_global', 'question_four_hop_statement']
are there any items on my shopping list that there is a sale on?	'tomato', 'pomegranate', 'satsuma'	['question_type_global', 'question_two_hop_statement']
what things did i get for [colin's birthday]	'Cardigan', 'Slippers', 'Poncho', 'lamp', 'rug', 'headphones'	['question_type_local']
show me all stores on [West Avenue] that currently have a sale on [vegetables]	'giant eagle'	['question_type_global', 'question_three_hop_statement']
what supermarkets near [West Avenue] have an ongoing sale?	'key food', 'giant eagle', 'hugo', 'market of choice'	['question_type_global', 'question_two_hop_statement']
show me all of the stores	'key food', 'giant eagle', 'hugo', 'market of choice', 'jordan marsch', 'sears'	['question_type_global', 'question_single_statement']
show me all supermarkets on [West Avenue] that currently have a sale	'key food', 'giant eagle', 'hugo', 'market of choice'	['question_type_global', 'question_two_hop_statement']
what are the supermarkets?	'key food', 'giant eagle', 'hugo', 'market of choice'	['question_type_global', 'question_single_statement']
what stores on [West Avenue] have a sale on [meat]?	'key food', 'market of choice'	['question_type_global', 'question_three_hop_statement']
is there a store nearby with a sale on [fruit] going on right now?	'hugo', 'key food'	['question_type_global', 'question_four_hop_statement']
what stores on [West Avenue] have a sale on [vegetables]?	'giant eagle'	['question_type_global', 'question_three_hop_statement']
does any store nearby have [meat] on sale?	'key food', 'market of choice'	['question_type_global', 'question_four_hop_statement']
[Borlotti bean] and [Dill] are all on sale at [market of choice]
[Borlotti bean] and [Turtle] are no longer on sale at [market of choice]
what's currently on sale at [market of choice]?	'Cornish Hen', 'Snake', 'Turkey', 'Dill'	['question_type_local']
[key food] has [raspberry] on sale!
[that store] no longer has [pear], [Cornish Hen] and [this thing] on sale
is there a sale on any items on my shopping list where i am?	'tomato', 'pomegranate', 'satsuma'	['question_type_global', 'question_four_hop_statement']
is there anything on my list that's on sale somewhere?	'tomato', 'pomegranate', 'satsuma'	['question_type_global', 'question_two_hop_statement']
show me all supermarkets near [West Avenue] that have a sale	'key food', 'giant eagle', 'hugo', 'market of choice'	['question_type_global', 'question_two_hop_statement']
what stores on [West Avenue] have a sale on [jujube]?	'hugo'	['question_type_global', 'question_two_hop_statement']
[Ham] is on sale at [market of choice]
what's currently on sale at [this supermarket]?	'Ham', 'Cornish Hen', 'Snake', 'Turkey', 'Dill'	['question_type_local']
what stores near [West Avenue] have an ongoing sale on [Snake]?	'key food', 'market of choice'	['question_type_global', 'question_two_hop_statement']
is there a store near my location is having a sale on [clothing]?	'sears'	['question_type_global', 'question_four_hop_statement']
[kiwi] and [pomegranate] are on sale at [this supermarket]
Where is [Oil heater] on sale?	'jordan marsch'	['question_type_local']
what stores on [West Avenue] have a sale on [vegetables]?	'giant eagle', 'market of choice'	['question_type_global', 'question_three_hop_statement']
what is on sale at [market of choice]?	'Ham', 'pomegranate', 'Cornish Hen', 'kiwi', 'Snake', 'Turkey', 'Dill'	['question_type_local']
show me all stores near [West Avenue] that have a sale	'key food', 'giant eagle', 'hugo', 'market of choice', 'sears'	['question_type_global', 'question_two_hop_statement']
what supermarkets on [West Avenue] have a sale?	'key food', 'giant eagle', 'hugo', 'market of choice'	['question_type_global', 'question_two_hop_statement']
what items are on sale at [hugo on West Avenue]?	'passon_fruit', 'jujube'	['question_type_local']
what items are on sale at [jordan marsch that I last mentioned]?	'Oil heater', 'Mousetrap'	['question_type_local']
show me all supermarkets that i tought you	'key food', 'giant eagle', 'hugo', 'market of choice'	['question_type_global', 'question_single_statement']
what department stores on [West Avenue] have a sale?	'sears'	['question_type_global', 'question_two_hop_statement']
show me all stores near [West Avenue] that have a sale on [vegetables]	'giant eagle', 'market of choice'	['question_type_global', 'question_three_hop_statement']
what stores near [West Avenue] have an ongoing sale on [clothing]?	'sears'	['question_type_global', 'question_three_hop_statement']
is there a store nearby with a sale on [meat] going on right now?	'key food', 'market of choice'	['question_type_global', 'question_four_hop_statement']
are there any items on my shopping list that there is a sale on at a store nearby?	'tomato', 'pomegranate', 'satsuma'	['question_type_global', 'question_four_hop_statement']
is there a store nearby with a sale going on right now?	'giant eagle', 'hugo', 'key food', 'market of choice', 'sears'	['question_type_global', 'question_three_hop_statement']
show me all stores near [West Avenue] that have a sale	'key food', 'giant eagle', 'hugo', 'market of choice', 'sears'	['question_type_global', 'question_two_hop_statement']
i often shop at [market of choice], which is my local [supermarket]
what are the supermarkets on [West Avenue]?	'key food', 'giant eagle', 'hugo', 'market of choice'	['question_type_global', 'question_single_statement']
show me all department stores near [West Avenue] that have a sale	'sears'	['question_type_global', 'question_two_hop_statement']
is there anything on sale at a store nearby?	'Slippers', 'papaya', 'Ham', 'tomato', 'passon_fruit', 'pomegranate', 'jujube', 'satsuma', 'Cornish Hen', 'White radish', 'kiwi', 'Snake', 'Turkey', 'honeydew', 'Dill'	['question_type_global', 'question_three_hop_statement']
[Sweet potato], [Borlotti bean] and [Acorn squash] are on sale at [that store]
What stores is [Borlotti bean] on sale at	'market of choice'	['question_type_local']
what department stores are there	'jordan marsch', 'sears'	['question_type_global', 'question_single_statement']
is there a store near my location is having a sale on [fruit]?	'hugo', 'key food', 'market of choice'	['question_type_global', 'question_four_hop_statement']
does any store nearby have [vegetables] on sale?	'giant eagle', 'market of choice'	['question_type_global', 'question_four_hop_statement']
what stores near [West Avenue] have an ongoing sale?	'key food', 'giant eagle', 'hugo', 'market of choice', 'sears'	['question_type_global', 'question_two_hop_statement']
show me all stores on [West Avenue] that currently have a sale on [vegetables]	'giant eagle', 'market of choice'	['question_type_global', 'question_three_hop_statement']
what department stores near [West Avenue] have an ongoing sale?	'sears'	['question_type_global', 'question_two_hop_statement']
is there any [fruit] that I have to buy currently are on sale?	'tomato', 'pomegranate', 'satsuma'	['question_type_global', 'question_three_hop_statement']
i think [Berkshire Drive] is in [Fishtown]
show me all supermarkets near [West Avenue]	'key food', 'giant eagle', 'hugo', 'market of choice'	['question_type_global', 'question_single_statement']
are there any stores nearby that have a sale on [clothing]?	'sears'	['question_type_global', 'question_four_hop_statement']
What stores is [tomato] on sale at	'key food'	['question_type_local']
is there anything that I need for [brown bag lunch at school] that's on sale somewhere?	'tomato', 'pomegranate', 'satsuma'	['question_type_global', 'question_two_hop_statement']
what stores on [West Avenue] have a sale on [fruit]?	'key food', 'hugo', 'market of choice'	['question_type_global', 'question_three_hop_statement']
What stores is [Turkey] on sale at	'key food', 'hugo', 'market of choice'	['question_type_local']
are there any stores nearby that have a sale on items that i need?	'key food', 'market of choice'	['question_type_global', 'question_four_hop_statement']
show me all stores near [West Avenue]	'key food', 'giant eagle', 'hugo', 'market of choice', 'jordan marsch', 'sears'	['question_type_global', 'question_single_statement']
is there a sale on any [fruit] on my shopping list?	'tomato', 'pomegranate', 'satsuma'	['question_type_global', 'question_three_hop_statement']
is there a store nearby with any of the items on my shopping list on sale?	'key food', 'market of choice'	['question_type_global', 'question_four_hop_statement']
what items are on sale at nearby stores?	'Slippers', 'papaya', 'Ham', 'tomato', 'passon_fruit', 'pomegranate', 'jujube', 'satsuma', 'Cornish Hen', 'White radish', 'kiwi', 'Snake', 'Turkey', 'honeydew', 'Dill'	['question_type_global', 'question_three_hop_statement']
is there a store near my location is having a sale on [vegetables]?	'giant eagle', 'market of choice'	['question_type_global', 'question_four_hop_statement']
show me all of the stores on [West Avenue]	'key food', 'giant eagle', 'hugo', 'market of choice', 'jordan marsch', 'sears'	['question_type_global', 'question_single_statement']
what do stores near me are have a sale on?	'Slippers', 'papaya', 'Ham', 'tomato', 'passon_fruit', 'pomegranate', 'jujube', 'satsuma', 'Cornish Hen', 'White radish', 'kiwi', 'Snake', 'Turkey', 'honeydew', 'Dill'	['question_type_global', 'question_three_hop_statement']
what department stores are there	'jordan marsch', 'sears'	['question_type_global', 'question_single_statement']
show me all supermarkets near [West Avenue]	'key food', 'giant eagle', 'hugo', 'market of choice'	['question_type_global', 'question_single_statement']
show me all department stores near [West Avenue] that have a sale	'sears'	['question_type_global', 'question_two_hop_statement']
are there any items on my shopping list that there is a sale on?	'tomato', 'pomegranate', 'satsuma'	['question_type_global', 'question_two_hop_statement']
is there a store nearby with a sale on [clothing] going on right now?	'sears'	['question_type_global', 'question_four_hop_statement']
is there a store nearby with a sale on [meat] going on right now?	'key food', 'market of choice'	['question_type_global', 'question_four_hop_statement']
why do i need to buy [pomegranate]?	'brown bag lunch at school'	['question_type_local']
what stores on [West Avenue] have a sale on [clothing]?	'sears'	['question_type_global', 'question_three_hop_statement']
is there anything on my list that's on sale somewhere near my current location?	'tomato', 'pomegranate', 'satsuma'	['question_type_global', 'question_four_hop_statement']
what items that I have to buy currently are on sale near me?	'tomato', 'pomegranate', 'satsuma'	['question_type_global', 'question_four_hop_statement']
what is on sale near my current location?	'Slippers', 'papaya', 'Ham', 'tomato', 'passon_fruit', 'pomegranate', 'jujube', 'satsuma', 'Cornish Hen', 'White radish', 'kiwi', 'Snake', 'Turkey', 'honeydew', 'Dill'	['question_type_global', 'question_three_hop_statement']
[key food] has [Turtle] and [Ham] on sale!
what's currently on sale at [key food]?	'papaya', 'Ham', 'tomato', 'pomegranate', 'satsuma', 'Turtle', 'Snake', 'Turkey', 'honeydew'	['question_type_local']
does any store nearby have [meat] on sale?	'key food', 'market of choice'	['question_type_global', 'question_four_hop_statement']
there is a [supermarket] called [hyvee] that I shop in pretty often
[this supermarket] has [Turkey] and [Turtle] on sale!
what is on sale at [hyvee]?	'Turtle', 'Turkey'	['question_type_local']
what are the department stores on [West Avenue]?	'jordan marsch', 'sears'	['question_type_global', 'question_single_statement']
is there a store near my location is having a sale on [fruit]?	'hugo', 'key food', 'market of choice'	['question_type_global', 'question_four_hop_statement']
show me all stores near [West Avenue] that have a sale	'key food', 'giant eagle', 'hugo', 'market of choice', 'sears'	['question_type_global', 'question_two_hop_statement']
show me all stores near [West Avenue] that have a sale on [vegetables]	'giant eagle', 'market of choice'	['question_type_global', 'question_three_hop_statement']
show me all stores near [West Avenue]	'key food', 'giant eagle', 'hugo', 'market of choice', 'jordan marsch', 'sears'	['question_type_global', 'question_single_statement']
is there a store nearby with a sale on [clothing] going on right now?	'sears'	['question_type_global', 'question_four_hop_statement']
what stores on [West Avenue] have a sale on [clothing]?	'sears'	['question_type_global', 'question_three_hop_statement']
what supermarkets are there on [West Avenue]?	'key food', 'giant eagle', 'hugo', 'market of choice'	['question_type_global', 'question_single_statement']
does any store nearby have [fruit] on sale?	'hugo', 'key food', 'market of choice'	['question_type_global', 'question_four_hop_statement']
is there anything on my list that's on sale somewhere?	'tomato', 'pomegranate', 'satsuma'	['question_type_global', 'question_two_hop_statement']
show me all of the supermarkets on [West Avenue]	'key food', 'giant eagle', 'hugo', 'market of choice'	['question_type_global', 'question_single_statement']
is there a sale on [Turtle] anywhere?	'key food', 'hyvee'	['question_type_local']
is there a store nearby with a sale on [Turkey] going on right now?	'key food', 'market of choice'	['question_type_global', 'question_three_hop_statement']
what stores on [West Avenue] have a sale?	'key food', 'giant eagle', 'hugo', 'market of choice', 'sears'	['question_type_global', 'question_two_hop_statement']
what's currently on sale at [market of choice on West Avenue]?	'Ham', 'pomegranate', 'Cornish Hen', 'kiwi', 'Snake', 'Turkey', 'Dill'	['question_type_local']
are there any stores nearby that have a sale on [meat]?	'key food', 'market of choice'	['question_type_global', 'question_four_hop_statement']
is there a store nearby with a sale on [vegetables] going on right now?	'giant eagle', 'market of choice'	['question_type_global', 'question_four_hop_statement']
show me all supermarkets on [West Avenue] that currently have a sale	'key food', 'giant eagle', 'hugo', 'market of choice'	['question_type_global', 'question_two_hop_statement']
what are the things that I need to get?	'tomato', 'pomegranate', 'satsuma'	['question_type_global', 'question_single_statement']
what items that I have to buy currently are on sale?	'tomato', 'pomegranate', 'satsuma'	['question_type_global', 'question_two_hop_statement']
what are the things that i need to get?	'tomato', 'pomegranate', 'satsuma'	['question_type_global', 'question_single_statement']
what stores near [West Avenue] have an ongoing sale on [fruit]?	'key food', 'hugo', 'market of choice'	['question_type_global', 'question_three_hop_statement']
what are the department stores on [West Avenue]?	'jordan marsch', 'sears'	['question_type_global', 'question_single_statement']
is there anything on my list that's on sale somewhere near my current location?	'tomato', 'pomegranate', 'satsuma'	['question_type_global', 'question_four_hop_statement']
What stores is [honeydew] on sale at	'key food'	['question_type_local']
[giant eagle] is a [supermarket]
[giant eagle] has [papaya] and [guava] on sale!
what is on sale at [giant eagle that I last mentioned]?	'papaya', 'guava'	['question_type_local']
does any store nearby have anything on sale?	'giant eagle', 'hugo', 'key food', 'market of choice', 'sears'	['question_type_global', 'question_three_hop_statement']
what department stores on [West Avenue] have a sale?	'sears'	['question_type_global', 'question_two_hop_statement']
what items that I have to buy currently are on sale?	'tomato', 'pomegranate', 'satsuma'	['question_type_global', 'question_two_hop_statement']
what stores on [West Avenue] have a sale on [meat]?	'key food', 'market of choice'	['question_type_global', 'question_three_hop_statement']
[Tie press] is a kind of [Appliance]
is there a sale on [guava] anywhere?	'giant eagle'	['question_type_local']
show me all of the supermarkets on [West Avenue]	'key food', 'giant eagle', 'hugo', 'market of choice'	['question_type_global', 'question_single_statement']
is there a sale on [that fruit] anywhere?	'giant eagle'	['question_type_local']
what are the department stores?	'jordan marsch', 'sears'	['question_type_global', 'question_single_statement']
show me all stores on [West Avenue] that currently have a sale on [vegetables]	'giant eagle', 'market of choice'	['question_type_global', 'question_three_hop_statement']
What stores is [Acorn squash] on sale at	'hugo', 'market of choice'	['question_type_local']
is there any [fruit] on my list that's on sale somewhere?	'tomato', 'pomegranate', 'satsuma'	['question_type_global', 'question_three_hop_statement']
show me all department stores near [West Avenue] that have a sale	'sears'	['question_type_global', 'question_two_hop_statement']
what do stores near me are have a sale on?	'Slippers', 'papaya', 'Ham', 'tomato', 'passon_fruit', 'pomegranate', 'jujube', 'satsuma', 'Cornish Hen', 'Turtle', 'White radish', 'kiwi', 'Snake', 'Turkey', 'honeydew', 'Dill'	['question_type_global', 'question_three_hop_statement']
is there a sale on [this fruit] anywhere?	'giant eagle'	['question_type_local']
is there a store nearby with a sale on [clothing] going on right now?	'sears'	['question_type_global', 'question_four_hop_statement']
What stores is [tomato] on sale at	'key food'	['question_type_local']
show me all stores on [West Avenue] that currently have a sale on [fruit]	'key food', 'hugo', 'market of choice'	['question_type_global', 'question_three_hop_statement']
what is on sale at [giant eagle on West Avenue]?	'White radish'	['question_type_local']
add [jujube] and [huckleberry] for [karen's potluck tonight]
what do I need for [karen's potluck tonight]?	'jujube', 'huckleberry'	['question_type_local']
show me all stores on [West Avenue] that currently have a sale on [meat]	'key food', 'market of choice'	['question_type_global', 'question_three_hop_statement']
show me all of the stores on [West Avenue]	'key food', 'giant eagle', 'hugo', 'market of choice', 'jordan marsch', 'sears'	['question_type_global', 'question_single_statement']
is there a store near my location that has what i need on sale?	'key food', 'hugo', 'market of choice'	['question_type_global', 'question_four_hop_statement']
does any store nearby have [vegetables] on sale?	'giant eagle', 'market of choice'	['question_type_global', 'question_four_hop_statement']
are there any stores nearby that have a sale on [clothing]?	'sears'	['question_type_global', 'question_four_hop_statement']
is there a store near my location is having a sale on [meat]?	'key food', 'market of choice'	['question_type_global', 'question_four_hop_statement']
i need to get [Shirt] and [Poncho] for [my daughter's graduation]
i don't need [Shirt] for [my daughter's graduation] anymore
what do I need for [my daughter's graduation]?	'Poncho'	['question_type_local']
is there a sale on [honeydew] anywhere?	'key food'	['question_type_local']
show me all of the department stores on [West Avenue]	'jordan marsch', 'sears'	['question_type_global', 'question_single_statement']
are there any stores nearby that have a sale on items that i need?	'key food', 'hugo', 'market of choice'	['question_type_global', 'question_four_hop_statement']
what [clothing] do i need to buy?	'Poncho'	['question_type_global', 'question_two_hop_statement']
show me all stores on [West Avenue] that currently have a sale	'key food', 'giant eagle', 'hugo', 'market of choice', 'sears'	['question_type_global', 'question_two_hop_statement']
what items that I have to buy for [brown bag lunch at school] currently are on sale?	'tomato', 'pomegranate', 'satsuma'	['question_type_global', 'question_two_hop_statement']
i don't need [Poncho] for [my daughter's graduation] anymore
what items did i already get for [that event]?	'Poncho', 'Shirt'	['question_type_local']
is there a store near my location is having a sale on [vegetables]?	'giant eagle', 'market of choice'	['question_type_global', 'question_four_hop_statement']
are there any stores nearby that have a sale?	'giant eagle', 'hugo', 'key food', 'market of choice', 'sears'	['question_type_global', 'question_three_hop_statement']
what department stores near [West Avenue] have an ongoing sale?	'sears'	['question_type_global', 'question_two_hop_statement']
Do I need to buy any [fruit]?	'tomato', 'pomegranate', 'jujube', 'satsuma', 'huckleberry'	['question_type_global', 'question_two_hop_statement']
i absolutely must not forget to get both [Kimchi refrigerator] and [Solar water heater] for [my daughter's graduation]
Where is [passon_fruit] on sale?	'hugo'	['question_type_local']
what are the stores on [West Avenue]?	'key food', 'giant eagle', 'hugo', 'market of choice', 'jordan marsch', 'sears'	['question_type_global', 'question_single_statement']
show me all stores on [West Avenue] that currently have a sale on [fruit]	'key food', 'hugo', 'market of choice'	['question_type_global', 'question_three_hop_statement']
is there a sale on any [fruit] on my shopping list?	'tomato', 'pomegranate', 'jujube', 'satsuma'	['question_type_global', 'question_three_hop_statement']
i absolutely must not forget to get both [Oven] and [Oil heater] for [colin's birthday]
there is a [supermarket] called [key food] that I shop in pretty often
[Turtle], [Ham] and [Snake] are all on sale at [that store]
what items are on sale at [key food that I last mentioned]?	'Ham', 'Turtle', 'Snake'	['question_type_local']
is there a store near my location is having a sale on [clothing]?	'sears'	['question_type_global', 'question_four_hop_statement']
are there any [appliances] that i need to get?	'Oven', 'Oil heater', 'Kimchi refrigerator', 'Solar water heater'	['question_type_global', 'question_two_hop_statement']
show me all stores on [West Avenue] that currently have a sale on [meat]	'key food', 'market of choice'	['question_type_global', 'question_three_hop_statement']
[Snake] and [Cornish Hen] are on sale at [hyvee]
this [hyvee] is on [Berkshire Drive]
what items are on sale at [hyvee]?	'Cornish Hen', 'Turtle', 'Snake', 'Turkey'	['question_type_local']
what's currently on sale at [giant eagle that I last mentioned]?	'papaya', 'guava'	['question_type_local']
is there a store nearby with a sale going on right now?	'giant eagle', 'hugo', 'key food', 'market of choice', 'sears'	['question_type_global', 'question_three_hop_statement']
[Cold-pressed juicer] is a [Appliance]
what is on sale at [key food that I last mentioned]?	'Ham', 'Turtle', 'Snake'	['question_type_local']
is there a store near my location is having a sale on [meat]?	'key food', 'market of choice'	['question_type_global', 'question_four_hop_statement']
does any store nearby have [fruit] on sale?	'hugo', 'key food', 'market of choice'	['question_type_global', 'question_four_hop_statement']
are there any [appliances] that i need to get?	'Oven', 'Oil heater', 'Kimchi refrigerator', 'Solar water heater'	['question_type_global', 'question_two_hop_statement']
What do I need to buy for [brown bag lunch at school]?	'tomato', 'pomegranate', 'satsuma'	['question_type_local']
show me all department stores	'jordan marsch', 'sears'	['question_type_global', 'question_single_statement']
is there a store nearby with a sale on [papaya] going on right now?	'key food'	['question_type_global', 'question_three_hop_statement']
what items are on sale at [giant eagle on West Avenue]?	'White radish'	['question_type_local']
are there any stores nearby that have a sale on [vegetables]?	'giant eagle', 'market of choice'	['question_type_global', 'question_four_hop_statement']
what are the supermarkets?	'key food', 'giant eagle', 'hugo', 'market of choice', 'hyvee'	['question_type_global', 'question_single_statement']
is there a sale on [papaya] anywhere?	'key food', 'giant eagle'	['question_type_local']
is there anything that I need for [brown bag lunch at school] that's on sale somewhere?	'tomato', 'pomegranate', 'satsuma'	['question_type_global', 'question_two_hop_statement']
does any store nearby have anything on sale?	'giant eagle', 'hugo', 'key food', 'market of choice', 'sears'	['question_type_global', 'question_three_hop_statement']
i am pretty sure that [Aspen Drive] is in [Fishtown]
is there a sale on any items on my shopping list?	'tomato', 'pomegranate', 'jujube', 'satsuma', 'Oil heater'	['question_type_global', 'question_two_hop_statement']
i often shop at [weis], which is my local [supermarket]
[Borlotti bean] is on sale at [this store]
this specific [this store] is on [Berkshire Drive]
what items are on sale at [this store]?	'Borlotti bean'	['question_type_local']
what do stores near me are have a sale on?	'Slippers', 'papaya', 'Ham', 'tomato', 'passon_fruit', 'pomegranate', 'jujube', 'satsuma', 'Cornish Hen', 'Turtle', 'White radish', 'kiwi', 'Snake', 'Turkey', 'honeydew', 'Dill'	['question_type_global', 'question_three_hop_statement']
is there a sale on [Ham] anywhere?	'key food', 'key food', 'market of choice'	['question_type_local']
what stores are there that I taught you?	'key food', 'giant eagle', 'hugo', 'market of choice', 'jordan marsch', 'sears', 'hyvee', 'weis'	['question_type_global', 'question_single_statement']
are there any stores nearby that have a sale on [meat]?	'key food', 'market of choice'	['question_type_global', 'question_four_hop_statement']
what supermarkets near [West Avenue] have an ongoing sale?	'key food', 'giant eagle', 'hugo', 'market of choice'	['question_type_global', 'question_two_hop_statement']
Do I need to buy any [fruit]?	'tomato', 'pomegranate', 'jujube', 'satsuma', 'huckleberry'	['question_type_global', 'question_two_hop_statement']
show me all stores near [West Avenue]	'key food', 'giant eagle', 'hugo', 'market of choice', 'jordan marsch', 'sears'	['question_type_global', 'question_single_statement']
[this supermarket] has [Sweet potato], [Dill] and [White radish] on sale!
[weis] no longer has [Borlotti bean], [White radish] and [Dill] on sale
what is on sale at [weis]?	'Sweet potato'	['question_type_local']
Do i have any [fruit] on my shopping list?	'tomato', 'pomegranate', 'jujube', 'satsuma', 'huckleberry'	['question_type_global', 'question_two_hop_statement']
