[Stockings], [Pajamas] and [Briefs] are kinds of [Clothing]
[lakeview grocery] is a [supermarket]
[Corset], [Sandals] and [Camisole] are [Clothing]
what stores are there that I taught you?	'lakeview grocery'	['question_type_global', 'question_single_statement']
what are the stores?	'lakeview grocery'	['question_type_global', 'question_single_statement']
show me all stores	'lakeview grocery'	['question_type_global', 'question_single_statement']
what are the supermarkets?	'lakeview grocery'	['question_type_global', 'question_single_statement']
[Water purifier], [Gas appliance] and [Automatic Rotimaker] are [Appliance]
remember that i have [my son's birthday]
[Goat], [Moose] and [Opossum] are all different types of [Meat]
[Beef liver] and [Beef tongue] are good examples of [Meat]
show me all supermarkets that i tought you	'lakeview grocery'	['question_type_global', 'question_single_statement']
what supermarkets are there?	'lakeview grocery'	['question_type_global', 'question_single_statement']
remember that i have [john's birthday party]
[Blouse] and [Shorts] are both examples of [Clothing]
[Route 5] is in [Elliott]
[dragonfruit] is a type of [Fruit]
i think this [lakeview grocery] is somewhere on [that street]
[dragonfruit] is on sale at [lakeview grocery]
[Marshall Street] is located in the [Elliott] neighborhood
what items are on sale at [lakeview grocery]?	'dragonfruit'	['question_type_local']
what stores on [Route 5] have a sale on [dragonfruit]?	'lakeview grocery'	['question_type_global', 'question_two_hop_statement']
[Shoes], [Gown] and [Dress] are all examples of [Clothing]
what stores on [Route 5] have a sale on [fruit]?	'lakeview grocery'	['question_type_global', 'question_three_hop_statement']
show me all stores on [Route 5] that currently have a sale	'lakeview grocery'	['question_type_global', 'question_two_hop_statement']
what neighborhood is [Marshall Street] in?	'Elliott'	['question_type_local']
[Radicchio] and [Wasabi] are [Vegetables]
what stores are on [Route 5]?	'lakeview grocery'	['question_type_local']
what stores near [Route 5] have an ongoing sale?	'lakeview grocery'	['question_type_global', 'question_two_hop_statement']
show me all stores	'lakeview grocery'	['question_type_global', 'question_single_statement']
show me all stores near [Route 5] that have a sale	'lakeview grocery'	['question_type_global', 'question_two_hop_statement']
[2nd Avenue] is located in the [Midtown] neighborhood
what are the supermarkets?	'lakeview grocery'	['question_type_global', 'question_single_statement']
[Cedar Street] is located in the [Midtown] neighborhood
show me all stores on [Route 5] that currently have a sale	'lakeview grocery'	['question_type_global', 'question_two_hop_statement']
what neighborhood is [Cedar Street] in?	'Midtown'	['question_type_local']
what stores on [Route 5] have a sale on [dragonfruit]?	'lakeview grocery'	['question_type_global', 'question_two_hop_statement']
what are the supermarkets on [Route 5]?	'lakeview grocery'	['question_type_global', 'question_single_statement']
[blackberry], [date] and [raspberry] are all good examples of [Fruit]
show me all stores near [Route 5] that have a sale on [dragonfruit]	'lakeview grocery'	['question_type_global', 'question_two_hop_statement']
show me all stores near [Route 5] that have a sale	'lakeview grocery'	['question_type_global', 'question_two_hop_statement']
what stores are located on [Route 5]?	'lakeview grocery'	['question_type_local']
what stores are there that I taught you?	'lakeview grocery'	['question_type_global', 'question_single_statement']
[Parsley], [Yam] and [Black-eyed peas] are kinds of [Vegetables]
what supermarkets near [Route 5] have an ongoing sale?	'lakeview grocery'	['question_type_global', 'question_two_hop_statement']
what stores are there on [Route 5]?	'lakeview grocery'	['question_type_global', 'question_single_statement']
show me all stores near [Route 5] that have a sale on [fruit]	'lakeview grocery'	['question_type_global', 'question_three_hop_statement']
show me all of the supermarkets on [Route 5]	'lakeview grocery'	['question_type_global', 'question_single_statement']
what stores near [Route 5] have an ongoing sale?	'lakeview grocery'	['question_type_global', 'question_two_hop_statement']
what are the supermarkets on [Route 5]?	'lakeview grocery'	['question_type_global', 'question_single_statement']
what are the stores on [Route 5]?	'lakeview grocery'	['question_type_local']
show me all stores on [Route 5] that currently have a sale	'lakeview grocery'	['question_type_global', 'question_two_hop_statement']
show me all stores	'lakeview grocery'	['question_type_global', 'question_single_statement']
[Cufflinks] is a kind of [Clothing]
some example of [Vegetables] are [Mushrooms] and [Sweetcorn]
what neighborhood is [Cedar Street] located in?	'Midtown'	['question_type_local']
[Snake] and [Duck Liver] are both different kinds of [Meat]
what neighborhood is [Marshall Street] located in?	'Elliott'	['question_type_local']
what stores near [Route 5] have an ongoing sale on [dragonfruit]?	'lakeview grocery'	['question_type_global', 'question_two_hop_statement']
[I] just got to [Route 5]
show me all stores near [Route 5] that have a sale on [fruit]	'lakeview grocery'	['question_type_global', 'question_three_hop_statement']
what stores are there that I taught you?	'lakeview grocery'	['question_type_global', 'question_single_statement']
what stores are there on [Route 5]?	'lakeview grocery'	['question_type_global', 'question_single_statement']
[Drawer dishwasher], [Washing machine] and [Air conditioner] are all good examples of [Appliance]
what is on sale near my current location?	'dragonfruit'	['question_type_global', 'question_three_hop_statement']
show me all stores near [Route 5] that have a sale on [dragonfruit]	'lakeview grocery'	['question_type_global', 'question_two_hop_statement']
show me all stores near [Route 5]	'lakeview grocery'	['question_type_global', 'question_single_statement']
what stores on [Route 5] have a sale on [fruit]?	'lakeview grocery'	['question_type_global', 'question_three_hop_statement']
show me all of the stores	'lakeview grocery'	['question_type_global', 'question_single_statement']
i am pretty sure that [Church Street South] is in [Fairywood]
is there anything on sale at a store nearby?	'dragonfruit'	['question_type_global', 'question_three_hop_statement']
show me all of the stores on [Route 5]	'lakeview grocery'	['question_type_global', 'question_single_statement']
what supermarkets are there on [Route 5]?	'lakeview grocery'	['question_type_global', 'question_single_statement']
what neighborhood is [Church Street South] in?	'Fairywood'	['question_type_local']
show me all stores near [Route 5]	'lakeview grocery'	['question_type_global', 'question_single_statement']
what stores near [Route 5] have an ongoing sale on [fruit]?	'lakeview grocery'	['question_type_global', 'question_three_hop_statement']
what stores near [Route 5] have an ongoing sale?	'lakeview grocery'	['question_type_global', 'question_two_hop_statement']
there is a [department store] called [armstrong's] on [this street]
does any store nearby have [dragonfruit] on sale?	'lakeview grocery'	['question_type_global', 'question_three_hop_statement']
show me all supermarkets near [Route 5] that have a sale	'lakeview grocery'	['question_type_global', 'question_two_hop_statement']
what are the stores on [this street]?	"armstrong's"	['question_type_local']
what do stores near me are have a sale on?	'dragonfruit'	['question_type_global', 'question_three_hop_statement']
show me all stores near [Church Street South]	"armstrong's"	['question_type_global', 'question_single_statement']
what stores are there that I taught you?	'lakeview grocery', "armstrong's"	['question_type_global', 'question_single_statement']
[Drawer dishwasher] is on sale at [that department store]
what items are on sale at [armstrong's]?	'Drawer dishwasher'	['question_type_local']
show me all supermarkets on [Route 5] that currently have a sale	'lakeview grocery'	['question_type_global', 'question_two_hop_statement']
what stores are there on [Church Street South]?	"armstrong's"	['question_type_global', 'question_single_statement']
show me all stores on [Route 5] that currently have a sale	'lakeview grocery'	['question_type_global', 'question_two_hop_statement']
what do stores near me have on sale?	'dragonfruit'	['question_type_global', 'question_three_hop_statement']
is there a store near my location is having a sale?	'lakeview grocery'	['question_type_global', 'question_three_hop_statement']
what stores on [Church Street South] have a sale on [appliances]?	"armstrong's"	['question_type_global', 'question_three_hop_statement']
[Radicchio] and [Wasabi] are all on sale at [lakeview grocery]
what items are on sale at [lakeview grocery]?	'dragonfruit', 'Radicchio', 'Wasabi'	['question_type_local']
show me all of the department stores	"armstrong's"	['question_type_global', 'question_single_statement']
show me all stores on [Church Street South] that currently have a sale on [Drawer dishwasher]	"armstrong's"	['question_type_global', 'question_two_hop_statement']
show me all of the stores	'lakeview grocery', "armstrong's"	['question_type_global', 'question_single_statement']
what stores near [Route 5] have an ongoing sale?	'lakeview grocery'	['question_type_global', 'question_two_hop_statement']
what's currently on sale at [lakeview grocery]?	'dragonfruit', 'Radicchio', 'Wasabi'	['question_type_local']
what is on sale near my current location?	'dragonfruit', 'Radicchio', 'Wasabi'	['question_type_global', 'question_three_hop_statement']
does any store nearby have [vegetables] on sale?	'lakeview grocery'	['question_type_global', 'question_four_hop_statement']
is there a store near my location is having a sale?	'lakeview grocery'	['question_type_global', 'question_three_hop_statement']
is there a sale on [Wasabi] anywhere?	'lakeview grocery'	['question_type_local']
show me all stores near [Route 5] that have a sale	'lakeview grocery'	['question_type_global', 'question_two_hop_statement']
show me all supermarkets that i tought you	'lakeview grocery'	['question_type_global', 'question_single_statement']
what stores on [Route 5] have a sale?	'lakeview grocery'	['question_type_global', 'question_two_hop_statement']
[armstrong's] doesn't have [Drawer dishwasher] on sale anymore
what are the department stores?	"armstrong's"	['question_type_global', 'question_single_statement']
is there a store near my location is having a sale on [vegetables]?	'lakeview grocery'	['question_type_global', 'question_four_hop_statement']
there is a [supermarket] called [albersons] on [2nd Avenue]
[Snake], [Beef liver] and [Goat] are on sale at [albersons]
what is on sale at [albersons]?	'Goat', 'Beef liver', 'Snake'	['question_type_local']
show me all of the department stores on [Church Street South]	"armstrong's"	['question_type_global', 'question_single_statement']
show me all of the supermarkets	'lakeview grocery', 'albersons'	['question_type_global', 'question_single_statement']
show me all supermarkets near [2nd Avenue]	'albersons'	['question_type_global', 'question_single_statement']
does any store nearby have anything on sale?	'lakeview grocery'	['question_type_global', 'question_three_hop_statement']
show me all stores near [Route 5] that have a sale on [fruit]	'lakeview grocery'	['question_type_global', 'question_three_hop_statement']
show me all stores on [Route 5] that currently have a sale on [fruit]	'lakeview grocery'	['question_type_global', 'question_three_hop_statement']
what stores near [Route 5] have an ongoing sale?	'lakeview grocery'	['question_type_global', 'question_two_hop_statement']
what stores are located on [Church Street South]?	"armstrong's"	['question_type_local']
are there any stores nearby that have a sale on [fruit]?	'lakeview grocery'	['question_type_global', 'question_four_hop_statement']
Just got to [Midtown]
what are the department stores?	"armstrong's"	['question_type_global', 'question_single_statement']
show me all stores	'lakeview grocery', "armstrong's", 'albersons'	['question_type_global', 'question_single_statement']
is there a sale on [Radicchio] anywhere?	'lakeview grocery'	['question_type_local']
what supermarkets near [Route 5] have an ongoing sale?	'lakeview grocery'	['question_type_global', 'question_two_hop_statement']
what supermarkets on [Route 5] have a sale?	'lakeview grocery'	['question_type_global', 'question_two_hop_statement']
are there any stores nearby that have a sale?	'albersons'	['question_type_global', 'question_three_hop_statement']
I am now on [Marshall Street]
show me all supermarkets that i tought you	'lakeview grocery', 'albersons'	['question_type_global', 'question_single_statement']
I think I am in [Fairywood]
I am now on [Church Street South]
what neighborhood am I currently in?	'Fairywood'	['question_type_local']
what stores near [2nd Avenue] have an ongoing sale?	'albersons'	['question_type_global', 'question_two_hop_statement']
[huckleberry] and [boysenberry] are both different kinds of [Fruit]
[Black-eyed peas] and [Mushrooms] are on sale at [albersons]
what department stores are there	"armstrong's"	['question_type_global', 'question_single_statement']
what are the department stores?	"armstrong's"	['question_type_global', 'question_single_statement']
what stores are there on [Church Street South]?	"armstrong's"	['question_type_global', 'question_single_statement']
show me all of the department stores	"armstrong's"	['question_type_global', 'question_single_statement']
show me all stores near [Route 5] that have a sale	'lakeview grocery'	['question_type_global', 'question_two_hop_statement']
make sure to buy [Shoes] and [Shorts] for [john's birthday party]
Where is [Mushrooms] on sale?	'albersons'	['question_type_local']
what's currently on sale at [albersons]?	'Goat', 'Beef liver', 'Black-eyed peas', 'Mushrooms', 'Snake'	['question_type_local']
show me all supermarkets near [2nd Avenue]	'albersons'	['question_type_global', 'question_single_statement']
[Shawl] and [Waistcoat] are types of [Clothing]
what stores on [2nd Avenue] have a sale?	'albersons'	['question_type_global', 'question_two_hop_statement']
what are the department stores on [Church Street South]?	"armstrong's"	['question_type_global', 'question_single_statement']
[Water cooker] is a [Appliance]
what supermarkets near [Route 5] have an ongoing sale?	'lakeview grocery'	['question_type_global', 'question_two_hop_statement']
what are the stores?	'lakeview grocery', "armstrong's", 'albersons'	['question_type_global', 'question_single_statement']
[Automatic Rotimaker], [Washing machine] and [Drawer dishwasher] are all on sale at [armstrong's]
what items are on sale at [armstrong's]?	'Automatic Rotimaker', 'Drawer dishwasher', 'Washing machine'	['question_type_local']
does any store nearby have [appliances] on sale?	"armstrong's"	['question_type_global', 'question_four_hop_statement']
show me all of the supermarkets	'lakeview grocery', 'albersons'	['question_type_global', 'question_single_statement']
what supermarkets are there?	'lakeview grocery', 'albersons'	['question_type_global', 'question_single_statement']
show me all stores near [2nd Avenue] that have a sale on [meat]	'albersons'	['question_type_global', 'question_three_hop_statement']
Where is [Drawer dishwasher] on sale?	"armstrong's"	['question_type_local']
Where is [Wasabi] on sale?	'lakeview grocery'	['question_type_local']
show me all department stores	"armstrong's"	['question_type_global', 'question_single_statement']
[Broccoli] is a [Vegetables]
what stores on [Church Street South] have a sale?	"armstrong's"	['question_type_global', 'question_two_hop_statement']
what is my shopping list?	'Shorts', 'Shoes'	['question_type_global', 'question_single_statement']
what are the supermarkets on [2nd Avenue]?	'albersons'	['question_type_global', 'question_single_statement']
What stores is [Snake] on sale at	'albersons'	['question_type_local']
what stores on [Church Street South] have a sale on [appliances]?	"armstrong's"	['question_type_global', 'question_three_hop_statement']
show me all of the supermarkets	'lakeview grocery', 'albersons'	['question_type_global', 'question_single_statement']
what are the supermarkets on [Route 5]?	'lakeview grocery'	['question_type_global', 'question_single_statement']
I am currently on [Cedar Street]
Where is [Wasabi] on sale?	'lakeview grocery'	['question_type_local']
I am now in [Elliott]
what neighborhood am I currently in?	'Elliott'	['question_type_local']
what [clothing] do i need to buy?	'Shorts', 'Shoes'	['question_type_global', 'question_two_hop_statement']
[Jicama], [Tomato] and [Garlic] are all different types of [Vegetables]
what stores near [2nd Avenue] have an ongoing sale on [vegetables]?	'albersons'	['question_type_global', 'question_three_hop_statement']
are there any stores nearby that have a sale?	'lakeview grocery'	['question_type_global', 'question_three_hop_statement']
show me all stores on [Route 5] that currently have a sale on [fruit]	'lakeview grocery'	['question_type_global', 'question_three_hop_statement']
show me all stores on [Route 5] that currently have a sale	'lakeview grocery'	['question_type_global', 'question_two_hop_statement']
is there a store nearby with a sale on [vegetables] going on right now?	'lakeview grocery'	['question_type_global', 'question_four_hop_statement']
are there any stores nearby that have a sale on [fruit]?	'lakeview grocery'	['question_type_global', 'question_four_hop_statement']
[Salsify] is a type of [Vegetables]
show me all of the department stores	"armstrong's"	['question_type_global', 'question_single_statement']
what department stores are there	"armstrong's"	['question_type_global', 'question_single_statement']
are there any [clothing] that i need to get?	'Shorts', 'Shoes'	['question_type_global', 'question_two_hop_statement']
Do I need to buy any [clothing]?	'Shorts', 'Shoes'	['question_type_global', 'question_two_hop_statement']
I just got to [Route 5]
what neighborhood am I in?	'Elliott'	['question_type_local']
show me all of the supermarkets	'lakeview grocery', 'albersons'	['question_type_global', 'question_single_statement']
show me all supermarkets that i tought you	'lakeview grocery', 'albersons'	['question_type_global', 'question_single_statement']
what supermarkets near [2nd Avenue] have an ongoing sale?	'albersons'	['question_type_global', 'question_two_hop_statement']
I am now on [Cedar Street]
Just arrived to [Elliott]
what supermarkets are there?	'lakeview grocery', 'albersons'	['question_type_global', 'question_single_statement']
[Black-eyed peas] is not on sale at [albersons]
what items are on sale at [that supermarket]?	'Goat', 'Beef liver', 'Mushrooms', 'Snake'	['question_type_local']
does any store nearby have [fruit] on sale?	'lakeview grocery'	['question_type_global', 'question_four_hop_statement']
what do i need [Shoes] for?	"john's birthday party"	['question_type_local']
show me all of the supermarkets	'lakeview grocery', 'albersons'	['question_type_global', 'question_single_statement']
there is a [supermarket] called [giant value] on [Route 5]
what is my shopping list?	'Shorts', 'Shoes'	['question_type_global', 'question_single_statement']
is there a store near my location is having a sale on [vegetables]?	'lakeview grocery'	['question_type_global', 'question_four_hop_statement']
what stores are there on [2nd Avenue]?	'albersons'	['question_type_global', 'question_single_statement']
what neighborhood is [Route 5] located in?	'Elliott'	['question_type_local']
what are the things that I need to get?	'Shorts', 'Shoes'	['question_type_global', 'question_single_statement']
what stores on [Church Street South] have a sale?	"armstrong's"	['question_type_global', 'question_two_hop_statement']
what stores near [Route 5] have an ongoing sale?	'lakeview grocery'	['question_type_global', 'question_two_hop_statement']
what is on sale at [albersons]?	'Goat', 'Beef liver', 'Mushrooms', 'Snake'	['question_type_local']
What do I need to buy for [john's birthday party]?	'Shorts', 'Shoes'	['question_type_local']
show me all stores near [Route 5] that have a sale on [fruit]	'lakeview grocery'	['question_type_global', 'question_three_hop_statement']
show me all stores on [2nd Avenue] that currently have a sale	'albersons'	['question_type_global', 'question_two_hop_statement']
[dragonfruit] and [huckleberry] are on sale at [giant value]
what items are on sale at [giant value]?	'dragonfruit', 'huckleberry'	['question_type_local']
is there a store nearby with a sale on [vegetables] going on right now?	'lakeview grocery'	['question_type_global', 'question_four_hop_statement']
what stores are located on [Route 5]?	'lakeview grocery', 'giant value'	['question_type_local']
what are the things that I need to get?	'Shorts', 'Shoes'	['question_type_global', 'question_single_statement']
what stores are there on [Route 5]?	'lakeview grocery', 'giant value'	['question_type_global', 'question_single_statement']
what department stores are there on [Church Street South]?	"armstrong's"	['question_type_global', 'question_single_statement']
[supremo supermarket] is a [supermarket]
this [this store] is on [Church Street South]
what stores on [Church Street South] have a sale on [appliances]?	"armstrong's"	['question_type_global', 'question_three_hop_statement']
is there a store near my location is having a sale?	'giant value', 'lakeview grocery'	['question_type_global', 'question_three_hop_statement']
what department stores are there	"armstrong's"	['question_type_global', 'question_single_statement']
[giant value] has [boysenberry] and [blackberry] on sale!
what do I need for [john's birthday party]?	'Shorts', 'Shoes'	['question_type_local']
what stores near [2nd Avenue] have an ongoing sale?	'albersons'	['question_type_global', 'question_two_hop_statement']
is there a store near my location is having a sale on [Radicchio]?	'lakeview grocery'	['question_type_global', 'question_three_hop_statement']
[tomato], [nectarine] and [plum] are all examples of [Fruit]
show me all supermarkets that i tought you	'lakeview grocery', 'albersons', 'giant value', 'supremo supermarket'	['question_type_global', 'question_single_statement']
just arrived to [Marshall Street]
show me all of the department stores on [Church Street South]	"armstrong's"	['question_type_global', 'question_single_statement']
[cherry] and [cantaloupe] are both different kinds of [Fruit]
show me all of the supermarkets	'lakeview grocery', 'albersons', 'giant value', 'supremo supermarket'	['question_type_global', 'question_single_statement']
there is an upcoming [grading dinner party]
show me all of the department stores	"armstrong's"	['question_type_global', 'question_single_statement']
Just arrived to [Fairywood]
what neighborhood am I currently in?	'Fairywood'	['question_type_local']
what items are on sale at nearby stores?	'Automatic Rotimaker', 'Drawer dishwasher', 'Washing machine'	['question_type_global', 'question_three_hop_statement']
show me all stores near [Church Street South] that have a sale on [appliances]	"armstrong's"	['question_type_global', 'question_three_hop_statement']
Do I need to buy any [clothing]?	'Shorts', 'Shoes'	['question_type_global', 'question_two_hop_statement']
i am pretty sure that [Brook Lane] is in [Fairywood]
what supermarkets are there on [Route 5]?	'lakeview grocery', 'giant value'	['question_type_global', 'question_single_statement']
there is a [supermarket] called [lakeview grocery] on [Marshall Street]
what neighborhood is [that street] in?	'Fairywood'	['question_type_local']
is there a sale on [Snake] anywhere?	'albersons'	['question_type_local']
what department stores are there on [Church Street South]?	"armstrong's"	['question_type_global', 'question_single_statement']
does any store nearby have [appliances] on sale?	"armstrong's"	['question_type_global', 'question_four_hop_statement']
what is on sale near my current location?	'Automatic Rotimaker', 'Drawer dishwasher', 'Washing machine'	['question_type_global', 'question_three_hop_statement']
what do i need to buy?	'Shorts', 'Shoes'	['question_type_global', 'question_single_statement']
[albersons] has [Beef tongue] on sale!
what items are on sale at [albersons]?	'Goat', 'Beef liver', 'Beef tongue', 'Mushrooms', 'Snake'	['question_type_local']
show me all supermarkets that i tought you	'lakeview grocery', 'albersons', 'giant value', 'supremo supermarket'	['question_type_global', 'question_single_statement']
show me all stores on [Church Street South] that currently have a sale on [appliances]	"armstrong's"	['question_type_global', 'question_three_hop_statement']
[this supermarket] no longer has [Mushrooms] and [Beef tongue] on sale!
What stores is [blackberry] on sale at	'giant value'	['question_type_local']
show me all department stores on [Church Street South] that currently have a sale	"armstrong's"	['question_type_global', 'question_two_hop_statement']
what are the supermarkets on [Marshall Street]?	'lakeview grocery'	['question_type_global', 'question_single_statement']
what department stores on [Church Street South] have a sale?	"armstrong's"	['question_type_global', 'question_two_hop_statement']
[blackberry] and [cherry] are on sale at [albersons]
what are the supermarkets?	'lakeview grocery', 'albersons', 'giant value', 'supremo supermarket'	['question_type_global', 'question_single_statement']
I am currently on [Brook Lane]
I am currently on [Church Street South]
Just got to [Elliott]
I am currently on [Church Street South]
I think I am in [Midtown]
what neighborhood am I currently in?	'Midtown'	['question_type_local']
what stores near [Church Street South] have an ongoing sale on [appliances]?	"armstrong's"	['question_type_global', 'question_three_hop_statement']
what department stores are there on [Church Street South]?	"armstrong's"	['question_type_global', 'question_single_statement']
show me all of the department stores on [Church Street South]	"armstrong's"	['question_type_global', 'question_single_statement']
I just got to [Elliott]
I just got to [Route 5]
what stores near [Route 5] have an ongoing sale on [Radicchio]?	'lakeview grocery'	['question_type_global', 'question_two_hop_statement']
what stores near [Route 5] have an ongoing sale?	'lakeview grocery', 'giant value'	['question_type_global', 'question_two_hop_statement']
show me all stores	'lakeview grocery', "armstrong's", 'albersons', 'giant value', 'supremo supermarket'	['question_type_global', 'question_single_statement']
is there a store nearby with a sale going on right now?	'giant value', 'lakeview grocery'	['question_type_global', 'question_three_hop_statement']
What stores is [Radicchio] on sale at	'lakeview grocery'	['question_type_local']
just arrived to [Marshall Street]
what neighborhood am I currently in?	'Elliott'	['question_type_local']
[albersons] no longer has [Snake], [blackberry] and [cherry] on sale
what supermarkets are there on [2nd Avenue]?	'albersons'	['question_type_global', 'question_single_statement']
what stores near [Route 5] have an ongoing sale on [fruit]?	'lakeview grocery', 'giant value'	['question_type_global', 'question_three_hop_statement']
what stores near [2nd Avenue] have an ongoing sale?	'albersons'	['question_type_global', 'question_two_hop_statement']
show me all department stores near [Church Street South] that have a sale	"armstrong's"	['question_type_global', 'question_two_hop_statement']
show me all department stores on [Church Street South] that currently have a sale	"armstrong's"	['question_type_global', 'question_two_hop_statement']
what neighborhood is [Cedar Street] located in?	'Midtown'	['question_type_local']
what stores near [Church Street South] have an ongoing sale?	"armstrong's"	['question_type_global', 'question_two_hop_statement']
Where is [Radicchio] on sale?	'lakeview grocery'	['question_type_local']
what are the supermarkets on [Marshall Street]?	'lakeview grocery'	['question_type_global', 'question_single_statement']
I just got to [Route 5]
what neighborhood am I currently in?	'Elliott'	['question_type_local']
show me all of the supermarkets	'lakeview grocery', 'albersons', 'giant value', 'supremo supermarket'	['question_type_global', 'question_single_statement']
I just got to [2nd Avenue]
I am currently in [Fairywood]
show me all stores on [Church Street South] that currently have a sale on [appliances]	"armstrong's"	['question_type_global', 'question_three_hop_statement']
I am currently on [Cedar Street]
what neighborhood is [Cedar Street] in?	'Midtown'	['question_type_local']
what items are on sale at [albersons]?	'Goat', 'Beef liver'	['question_type_local']
what department stores near [Church Street South] have an ongoing sale?	"armstrong's"	['question_type_global', 'question_two_hop_statement']
I am currently on [Route 5]
I just got to [Midtown]
what stores near [2nd Avenue] have an ongoing sale on [meat]?	'albersons'	['question_type_global', 'question_three_hop_statement']
[lakeview grocery on Route 5] has [Beef liver], [Duck Liver] and [Opossum] on sale!
what stores are on [2nd Avenue]?	'albersons'	['question_type_local']
what supermarkets are there on [Marshall Street]?	'lakeview grocery'	['question_type_global', 'question_single_statement']
what stores near [Church Street South] have an ongoing sale on [appliances]?	"armstrong's"	['question_type_global', 'question_three_hop_statement']
i need to make sure to get [nectarine] and [blackberry] for [grading dinner party]
remove these for [grading dinner party]: [blackberry] and [nectarine]
Just arrived to [Fairywood]
I am currently on [Marshall Street]
what neighborhood am I in?	'Elliott'	['question_type_local']
what items do I need to get?	'Shorts', 'Shoes'	['question_type_global', 'question_single_statement']
just arrived to [Cedar Street]
show me all of the supermarkets on [2nd Avenue]	'albersons'	['question_type_global', 'question_single_statement']
Do i have any [clothing] on my shopping list?	'Shorts', 'Shoes'	['question_type_global', 'question_two_hop_statement']
[supremo supermarket] has [Opossum], [Snake] and [Beef tongue] on sale!
[Snake] and [Beef tongue] are no longer on sale at [supremo supermarket]
what stores near [2nd Avenue] have an ongoing sale?	'albersons'	['question_type_global', 'question_two_hop_statement']
what are the stores on [Marshall Street]?	'lakeview grocery'	['question_type_global', 'question_single_statement']
what stores are there that I taught you?	'lakeview grocery', "armstrong's", 'albersons', 'giant value', 'supremo supermarket'	['question_type_global', 'question_single_statement']
show me all stores near [Church Street South] that have a sale	"armstrong's", 'supremo supermarket'	['question_type_global', 'question_two_hop_statement']
what stores on [Route 5] have a sale on [fruit]?	'lakeview grocery', 'giant value'	['question_type_global', 'question_three_hop_statement']
show me all of the stores	'lakeview grocery', "armstrong's", 'albersons', 'giant value', 'supremo supermarket'	['question_type_global', 'question_single_statement']
what are the supermarkets?	'lakeview grocery', 'albersons', 'giant value', 'supremo supermarket'	['question_type_global', 'question_single_statement']
what are the stores?	'lakeview grocery', "armstrong's", 'albersons', 'giant value', 'supremo supermarket'	['question_type_global', 'question_single_statement']
show me all department stores on [Church Street South] that currently have a sale	"armstrong's"	['question_type_global', 'question_two_hop_statement']
what neighborhood is [Cedar Street] located in?	'Midtown'	['question_type_local']
show me all supermarkets near [2nd Avenue] that have a sale	'albersons'	['question_type_global', 'question_two_hop_statement']
what neighborhood is [Cedar Street] in?	'Midtown'	['question_type_local']
what department stores near [Church Street South] have an ongoing sale?	"armstrong's"	['question_type_global', 'question_two_hop_statement']
what items are on sale at [giant value]?	'dragonfruit', 'blackberry', 'huckleberry', 'boysenberry'	['question_type_local']
Where is [Washing machine] on sale?	"armstrong's"	['question_type_local']
show me all stores near [Church Street South] that have a sale	"armstrong's", 'supremo supermarket'	['question_type_global', 'question_two_hop_statement']
just arrived to [Route 5]
what neighborhood am I in?	'Elliott'	['question_type_local']
does any store nearby have [fruit] on sale?	'giant value', 'lakeview grocery'	['question_type_global', 'question_four_hop_statement']
is there a store near my location is having a sale on [vegetables]?	'lakeview grocery'	['question_type_global', 'question_four_hop_statement']
does any store nearby have anything on sale?	'giant value', 'lakeview grocery'	['question_type_global', 'question_three_hop_statement']
just arrived to [2nd Avenue]
I just got to [Elliott]
what neighborhood am I currently in?	'Elliott'	['question_type_local']
just arrived to [Route 5]
what is my shopping list?	'Shorts', 'Shoes'	['question_type_global', 'question_single_statement']
show me all of the supermarkets on [2nd Avenue]	'albersons'	['question_type_global', 'question_single_statement']
what are the department stores?	"armstrong's"	['question_type_global', 'question_single_statement']
what are the stores on [this street]?	'lakeview grocery', 'giant value'	['question_type_local']
what are the stores on [it]?	'lakeview grocery', 'giant value'	['question_type_local']
are there any stores nearby that have a sale?	'giant value', 'lakeview grocery'	['question_type_global', 'question_three_hop_statement']
what stores are located on [Route 5]?	'lakeview grocery', 'giant value'	['question_type_local']
show me all of the stores on [Marshall Street]	'lakeview grocery'	['question_type_global', 'question_single_statement']
what do stores near me have on sale?	'Opossum', 'Beef liver', 'dragonfruit', 'Radicchio', 'Wasabi', 'blackberry', 'Duck Liver', 'huckleberry', 'boysenberry'	['question_type_global', 'question_three_hop_statement']
what neighborhood is [that street] in?	'Elliott'	['question_type_local']
show me all of the stores on [Route 5]	'lakeview grocery', 'giant value'	['question_type_global', 'question_single_statement']
Just arrived to [Midtown]
what neighborhood am I in?	'Midtown'	['question_type_local']
what are the supermarkets on [Marshall Street]?	'lakeview grocery'	['question_type_global', 'question_single_statement']
show me all department stores near [Church Street South]	"armstrong's"	['question_type_global', 'question_single_statement']
[albersons] no longer has [Beef liver] and [Goat] on sale!
show me all stores near [Church Street South] that have a sale on [meat]	'supremo supermarket'	['question_type_global', 'question_three_hop_statement']
what are the supermarkets on [Church Street South]?	'supremo supermarket'	['question_type_global', 'question_single_statement']
what neighborhood is [Marshall Street] in?	'Elliott'	['question_type_local']
what are the stores on [Church Street South]?	"armstrong's", 'supremo supermarket'	['question_type_global', 'question_single_statement']
show me all supermarkets that i tought you	'lakeview grocery', 'albersons', 'giant value', 'supremo supermarket'	['question_type_global', 'question_single_statement']
what is on sale at [lakeview grocery on Route 5]?	'Opossum', 'Beef liver', 'dragonfruit', 'Radicchio', 'Wasabi', 'Duck Liver'	['question_type_local']
show me all supermarkets near [2nd Avenue]	'albersons'	['question_type_global', 'question_single_statement']
just arrived to [2nd Avenue]
what neighborhood am I currently in?	'Midtown'	['question_type_local']
what department stores near [Church Street South] have an ongoing sale?	"armstrong's"	['question_type_global', 'question_two_hop_statement']
show me all stores on [Church Street South] that currently have a sale on [meat]	'supremo supermarket'	['question_type_global', 'question_three_hop_statement']
show me all department stores	"armstrong's"	['question_type_global', 'question_single_statement']
I am currently on [Church Street South]
I think I am in [Elliott]
what neighborhood am I in?	'Elliott'	['question_type_local']
show me all of the supermarkets on [2nd Avenue]	'albersons'	['question_type_global', 'question_single_statement']
is there a store nearby with a sale on [boysenberry] going on right now?	'giant value'	['question_type_global', 'question_three_hop_statement']
[lakeview grocery] is a [supermarket]
[Radicchio], [Tomato] and [Broccoli] are all on sale at [that store]
this particular [lakeview grocery that I last mentioned] is located on [Church Street South]
