[Slippers], [T-Shirt] and [Blouse] are [Clothing]
here are some examples of [Meat]: [Veal], [Rabbit] and [Pork]
[Microwave oven], [Ceiling fan] and [Water purifier] are all different types of [Appliance]
there is a [supermarket] called [safeway] that I shop in pretty often
don't forget about an upcoming [karen's wedding]
[gold circle] is a [department store]
make sure to buy [Blouse] and [Slippers] for [this event]
i just got [Blouse] for [karen's wedding]
show me all department stores	'gold circle'	['question_type_global', 'question_single_statement']
what do i need to buy?	'Slippers'	['question_type_global', 'question_single_statement']
i need to get [T-Shirt] for [karen's wedding]
What do I need to buy for [that event]?	'Slippers', 'T-Shirt'	['question_type_local']
show me all of the department stores	'gold circle'	['question_type_global', 'question_single_statement']
[burlington] is a [department store]
[9th Street West] is located in the [Friendship] neighborhood
[Slippers], [Blouse] and [T-Shirt] are on sale at [this store]
this [burlington] is on [9th Street West]
what is on sale at [that department store]?	'Slippers', 'T-Shirt', 'Blouse'	['question_type_local']
i have [bob and erin's dinner party today] coming up
[sage-allen] is a [department store]
this specific [sage-allen] is on [9th Street West]
what neighborhood is [9th Street West] located in?	'Friendship'	['question_type_local']
show me all department stores on [9th Street West] that currently have a sale	'burlington'	['question_type_global', 'question_two_hop_statement']
[Borlotti bean], [Mung beans] and [Thyme] are kinds of [Vegetables]
show me all supermarkets that i tought you	'safeway'	['question_type_global', 'question_single_statement']
[grapefruit], [orange] and [cherry] are all different types of [Fruit]
Do i have any [clothing] on my shopping list?	'Slippers', 'T-Shirt'	['question_type_global', 'question_two_hop_statement']
what are the department stores?	'gold circle', 'burlington', 'sage-allen'	['question_type_global', 'question_single_statement']
what stores on [9th Street West] have a sale?	'burlington'	['question_type_global', 'question_two_hop_statement']
[shawl] and [cell phone] are types of [Gift]
is there any [clothing] on my list that's on sale somewhere?	'Slippers', 'T-Shirt'	['question_type_global', 'question_three_hop_statement']
what kind of [clothing] do I need to get?	'Slippers', 'T-Shirt'	['question_type_global', 'question_two_hop_statement']
[Water cooker], [Heat pump] and [Box mangle] are all different types of [Appliance]
show me all department stores on [9th Street West] that currently have a sale	'burlington'	['question_type_global', 'question_two_hop_statement']
what department stores on [9th Street West] have a sale?	'burlington'	['question_type_global', 'question_two_hop_statement']
there is a [supermarket] called [foodtown] that I shop in pretty often
Do I need to buy any [clothing]?	'Slippers', 'T-Shirt'	['question_type_global', 'question_two_hop_statement']
[I] am on [9th Street West]
[foodtown] has [Pork], [Veal] and [Rabbit] on sale!
this particular [foodtown] is located on [9th Street West]
show me all stores near [9th Street West] that have a sale on [meat]	'foodtown'	['question_type_global', 'question_three_hop_statement']
are there any stores nearby that have a sale on items that i need?	'burlington'	['question_type_global', 'question_four_hop_statement']
show me all of the stores on [9th Street West]	'burlington', 'sage-allen', 'foodtown'	['question_type_global', 'question_single_statement']
what items that I have to buy currently are on sale near me?	'Slippers', 'T-Shirt'	['question_type_global', 'question_four_hop_statement']
does any store nearby have [meat] on sale?	'foodtown'	['question_type_global', 'question_four_hop_statement']
Where is [Blouse] on sale?	'burlington'	['question_type_local']
i don't need [T-Shirt] for [karen's wedding] anymore
what things did i get for [that event]	'T-Shirt', 'Blouse'	['question_type_local']
does any store nearby have anything on sale?	'burlington', 'foodtown'	['question_type_global', 'question_three_hop_statement']
[Beef tongue], [Duck Liver] and [Goose Liver] are all examples of [Meat]
is there anything on my list that's on sale somewhere near my current location?	'Slippers'	['question_type_global', 'question_four_hop_statement']
is there a sale on any items on my shopping list?	'Slippers'	['question_type_global', 'question_two_hop_statement']
[Gloves], [Sandals] and [Shawl] are kinds of [Clothing]
what items do I need to get?	'Slippers'	['question_type_global', 'question_single_statement']
what are the stores on [9th Street West]?	'burlington', 'sage-allen', 'foodtown'	['question_type_global', 'question_single_statement']
are there any items on my shopping list that there is a sale on at a store nearby?	'Slippers'	['question_type_global', 'question_four_hop_statement']
[Tankini], [Hat] and [Tights] are all good examples of [Clothing]
is there a sale on any [clothing] on my shopping list?	'Slippers'	['question_type_global', 'question_three_hop_statement']
show me all of the stores	'safeway', 'gold circle', 'burlington', 'sage-allen', 'foodtown'	['question_type_global', 'question_single_statement']
show me all supermarkets that i tought you	'safeway', 'foodtown'	['question_type_global', 'question_single_statement']
there is a [department store] called [saks fifth avenue] that I shop in pretty often
what are the stores?	'safeway', 'gold circle', 'burlington', 'sage-allen', 'foodtown', 'saks fifth avenue'	['question_type_global', 'question_single_statement']
what supermarkets near [9th Street West] have an ongoing sale?	'foodtown'	['question_type_global', 'question_two_hop_statement']
[speakers], [sun glasses] and [slippers] are all good examples of [Gift]
what do I need for [karen's wedding]?	'Slippers'	['question_type_local']
what stores on [9th Street West] have a sale on [clothing]?	'burlington'	['question_type_global', 'question_three_hop_statement']
what stores near [9th Street West] have an ongoing sale?	'burlington', 'foodtown'	['question_type_global', 'question_two_hop_statement']
is there a store near my location is having a sale on [meat]?	'foodtown'	['question_type_global', 'question_four_hop_statement']
show me all department stores	'gold circle', 'burlington', 'sage-allen', 'saks fifth avenue'	['question_type_global', 'question_single_statement']
what neighborhood is [9th Street West] located in?	'Friendship'	['question_type_local']
show me all department stores near [9th Street West] that have a sale	'burlington'	['question_type_global', 'question_two_hop_statement']
[Goat] is a type of [Meat]
what stores on [9th Street West] have a sale on [meat]?	'foodtown'	['question_type_global', 'question_three_hop_statement']
this particular [safeway] is located on [9th Street West]
show me all of the supermarkets on [9th Street West]	'safeway', 'foodtown'	['question_type_global', 'question_single_statement']
is there a store nearby with a sale going on right now?	'burlington', 'foodtown'	['question_type_global', 'question_three_hop_statement']
what stores are located on [9th Street West]?	'sage-allen', 'burlington', 'safeway', 'foodtown'	['question_type_local']
what is my shopping list?	'Slippers'	['question_type_global', 'question_single_statement']
what supermarkets are there?	'safeway', 'foodtown'	['question_type_global', 'question_single_statement']
show me all supermarkets near [9th Street West] that have a sale	'foodtown'	['question_type_global', 'question_two_hop_statement']
what neighborhood is [9th Street West] in?	'Friendship'	['question_type_local']
show me all supermarkets that i tought you	'safeway', 'foodtown'	['question_type_global', 'question_single_statement']
is there a sale on any items on my shopping list?	'Slippers'	['question_type_global', 'question_two_hop_statement']
is there a store near my location that has what i need on sale?	'burlington'	['question_type_global', 'question_four_hop_statement']
show me all department stores	'gold circle', 'burlington', 'sage-allen', 'saks fifth avenue'	['question_type_global', 'question_single_statement']
is there a store nearby with a sale on [Blouse] going on right now?	'burlington'	['question_type_global', 'question_three_hop_statement']
is there a store near my location is having a sale?	'burlington', 'foodtown'	['question_type_global', 'question_three_hop_statement']
Where is [Slippers] on sale?	'burlington'	['question_type_local']
show me all department stores near [9th Street West]	'burlington', 'sage-allen'	['question_type_global', 'question_single_statement']
what supermarkets are there on [9th Street West]?	'safeway', 'foodtown'	['question_type_global', 'question_single_statement']
what do i have on shopping list for [karen's wedding]?	'Slippers'	['question_type_local']
what stores on [9th Street West] have a sale on [Veal]?	'foodtown'	['question_type_global', 'question_two_hop_statement']
what department stores are there	'gold circle', 'burlington', 'sage-allen', 'saks fifth avenue'	['question_type_global', 'question_single_statement']
what stores on [9th Street West] have a sale?	'burlington', 'foodtown'	['question_type_global', 'question_two_hop_statement']
show me all department stores near [9th Street West] that have a sale	'burlington'	['question_type_global', 'question_two_hop_statement']
what stores on [9th Street West] have a sale on [clothing]?	'burlington'	['question_type_global', 'question_three_hop_statement']
is there a store nearby with a sale on [Blouse] going on right now?	'burlington'	['question_type_global', 'question_three_hop_statement']
what do stores near me have on sale?	'Slippers', 'T-Shirt', 'Blouse', 'Veal', 'Rabbit', 'Pork'	['question_type_global', 'question_three_hop_statement']
[Cedar Court] is located in the [Cedar Park] neighborhood
what neighborhood is [Cedar Court] in?	'Cedar Park'	['question_type_local']
show me all stores near [9th Street West] that have a sale on [clothing]	'burlington'	['question_type_global', 'question_three_hop_statement']
[safeway] has [orange], [cherry] and [grapefruit] on sale!
What stores is [orange] on sale at	'safeway'	['question_type_local']
what supermarkets near [9th Street West] have an ongoing sale?	'safeway', 'foodtown'	['question_type_global', 'question_two_hop_statement']
what stores are there on [9th Street West]?	'safeway', 'burlington', 'sage-allen', 'foodtown'	['question_type_global', 'question_single_statement']
what items are on sale at nearby stores?	'Slippers', 'T-Shirt', 'Blouse', 'Veal', 'Rabbit', 'Pork', 'grapefruit', 'orange', 'cherry'	['question_type_global', 'question_three_hop_statement']
[Fleece], [Cummerbund] and [Sarong] are all types of [Clothing]
is there a store nearby with a sale on [clothing] going on right now?	'burlington'	['question_type_global', 'question_four_hop_statement']
show me all of the department stores on [9th Street West]	'burlington', 'sage-allen'	['question_type_global', 'question_single_statement']
show me all stores near [9th Street West] that have a sale on [Blouse]	'burlington'	['question_type_global', 'question_two_hop_statement']
show me all stores near [9th Street West]	'safeway', 'burlington', 'sage-allen', 'foodtown'	['question_type_global', 'question_single_statement']
what stores are there that I taught you?	'safeway', 'gold circle', 'burlington', 'sage-allen', 'foodtown', 'saks fifth avenue'	['question_type_global', 'question_single_statement']
is there a store nearby with a sale on [meat] going on right now?	'foodtown'	['question_type_global', 'question_four_hop_statement']
what is on sale near my current location?	'Slippers', 'T-Shirt', 'Blouse', 'Veal', 'Rabbit', 'Pork', 'grapefruit', 'orange', 'cherry'	['question_type_global', 'question_three_hop_statement']
show me all stores on [9th Street West] that currently have a sale on [meat]	'foodtown'	['question_type_global', 'question_three_hop_statement']
show me all of the department stores on [9th Street West]	'burlington', 'sage-allen'	['question_type_global', 'question_single_statement']
i need to get [Hat] and [Sarong] for [karen's wedding]
what items did i already get for [karen's wedding]?	'T-Shirt', 'Blouse'	['question_type_local']
are there any stores nearby that have a sale on [clothing]?	'burlington'	['question_type_global', 'question_four_hop_statement']
What do I need to buy for [karen's wedding]?	'Slippers', 'Hat', 'Sarong'	['question_type_local']
is there a store near my location is having a sale on [fruit]?	'safeway'	['question_type_global', 'question_four_hop_statement']
is there a store near my location that has what i need on sale?	'burlington'	['question_type_global', 'question_four_hop_statement']
is there a sale on [Blouse] anywhere?	'burlington'	['question_type_local']
show me all stores near [9th Street West] that have a sale	'safeway', 'burlington', 'foodtown'	['question_type_global', 'question_two_hop_statement']
is there anything on my list that's on sale somewhere near my current location?	'Slippers'	['question_type_global', 'question_four_hop_statement']
show me all stores on [9th Street West] that currently have a sale on [clothing]	'burlington'	['question_type_global', 'question_three_hop_statement']
show me all stores on [9th Street West] that currently have a sale	'safeway', 'burlington', 'foodtown'	['question_type_global', 'question_two_hop_statement']
what are the department stores on [9th Street West]?	'burlington', 'sage-allen'	['question_type_global', 'question_single_statement']
Do i have any [clothing] on my shopping list?	'Slippers', 'Hat', 'Sarong'	['question_type_global', 'question_two_hop_statement']
[sage-allen] has [Water cooker] and [Ceiling fan] on sale!
are there any items on my shopping list that there is a sale on at a store nearby?	'Slippers'	['question_type_global', 'question_four_hop_statement']
what department stores near [9th Street West] have an ongoing sale?	'burlington', 'sage-allen'	['question_type_global', 'question_two_hop_statement']
does any store nearby have [clothing] on sale?	'burlington'	['question_type_global', 'question_four_hop_statement']
are there any [clothing] that i need to get?	'Slippers', 'Hat', 'Sarong'	['question_type_global', 'question_two_hop_statement']
what are the stores on [9th Street West]?	'safeway', 'burlington', 'sage-allen', 'foodtown'	['question_type_global', 'question_single_statement']
[Cufflinks], [Boots] and [Camisole] are all different types of [Clothing]
what stores near [9th Street West] have an ongoing sale on [clothing]?	'burlington'	['question_type_global', 'question_three_hop_statement']
does any store nearby have [fruit] on sale?	'safeway'	['question_type_global', 'question_four_hop_statement']
is there a store nearby with a sale on [Veal] going on right now?	'foodtown'	['question_type_global', 'question_three_hop_statement']
[Peas], [Horseradish] and [Zucchini] are all good examples of [Vegetables]
what items are on sale at [safeway]?	'grapefruit', 'orange', 'cherry'	['question_type_local']
is there a store nearby with a sale on [cherry] going on right now?	'safeway'	['question_type_global', 'question_three_hop_statement']
is there a sale on any [clothing] on my shopping list?	'Slippers'	['question_type_global', 'question_three_hop_statement']
what stores on [9th Street West] have a sale on [appliances]?	'sage-allen'	['question_type_global', 'question_three_hop_statement']
here are some examples of [Fruit]: [tangerine], [blackberry] and [nectarine]
are there any stores nearby that have a sale on [appliances]?	'sage-allen'	['question_type_global', 'question_four_hop_statement']
is there a store near my location that has what i need on sale?	'burlington'	['question_type_global', 'question_four_hop_statement']
is there a store nearby with a sale on [Slippers] going on right now?	'burlington'	['question_type_global', 'question_three_hop_statement']
what are the things that I need to get?	'Slippers', 'Hat', 'Sarong'	['question_type_global', 'question_single_statement']
what stores are there that I taught you?	'safeway', 'gold circle', 'burlington', 'sage-allen', 'foodtown', 'saks fifth avenue'	['question_type_global', 'question_single_statement']
show me all of the stores	'safeway', 'gold circle', 'burlington', 'sage-allen', 'foodtown', 'saks fifth avenue'	['question_type_global', 'question_single_statement']
is there a store nearby with a sale on [grapefruit] going on right now?	'safeway'	['question_type_global', 'question_three_hop_statement']
[slippers], [sun glasses] and [speakers] are on sale at [burlington]
show me all stores on [9th Street West] that currently have a sale on [gifts]	'burlington'	['question_type_global', 'question_three_hop_statement']
are there any stores nearby that have a sale on [orange]?	'safeway'	['question_type_global', 'question_three_hop_statement']
What stores is [speakers] on sale at	'burlington'	['question_type_local']
is there anything on my list that's on sale somewhere near my current location?	'Slippers'	['question_type_global', 'question_four_hop_statement']
why do i need to buy [Sarong]?	"karen's wedding"	['question_type_local']
is there a store nearby with a sale on [T-Shirt] going on right now?	'burlington'	['question_type_global', 'question_three_hop_statement']
what items that I have to buy currently are on sale?	'Slippers'	['question_type_global', 'question_two_hop_statement']
what are the department stores on [9th Street West]?	'burlington', 'sage-allen'	['question_type_global', 'question_single_statement']
show me all stores on [9th Street West] that currently have a sale	'safeway', 'burlington', 'sage-allen', 'foodtown'	['question_type_global', 'question_two_hop_statement']
show me all stores on [9th Street West] that currently have a sale on [gifts]	'burlington'	['question_type_global', 'question_three_hop_statement']
is there any [clothing] on my list that's on sale somewhere?	'Slippers'	['question_type_global', 'question_three_hop_statement']
does any store nearby have [meat] on sale?	'foodtown'	['question_type_global', 'question_four_hop_statement']
what stores on [9th Street West] have a sale on [clothing]?	'burlington'	['question_type_global', 'question_three_hop_statement']
What stores is [Rabbit] on sale at	'foodtown'	['question_type_local']
does any store nearby have [speakers] on sale?	'burlington'	['question_type_global', 'question_three_hop_statement']
what are the department stores?	'gold circle', 'burlington', 'sage-allen', 'saks fifth avenue'	['question_type_global', 'question_single_statement']
i think this [saks fifth avenue] is somewhere on [Cedar Court]
[shawl], [slippers] and [speakers] are on sale at [that store]
[saks fifth avenue] doesn't have [slippers] and [speakers] on sale anymore!
does any store nearby have [fruit] on sale?	'safeway'	['question_type_global', 'question_four_hop_statement']
show me all stores near [9th Street West] that have a sale on [meat]	'foodtown'	['question_type_global', 'question_three_hop_statement']
is there a sale on [Rabbit] anywhere?	'foodtown'	['question_type_local']
what items do I need to get?	'Slippers', 'Hat', 'Sarong'	['question_type_global', 'question_single_statement']
is there any [clothing] that I have to buy currently are on sale?	'Slippers'	['question_type_global', 'question_three_hop_statement']
what are the supermarkets?	'safeway', 'foodtown'	['question_type_global', 'question_single_statement']
what are the department stores?	'gold circle', 'burlington', 'sage-allen', 'saks fifth avenue'	['question_type_global', 'question_single_statement']
Where is [slippers] on sale?	'burlington'	['question_type_local']
show me all stores near [9th Street West] that have a sale on [gifts]	'burlington'	['question_type_global', 'question_three_hop_statement']
does any store nearby have [clothing] on sale?	'burlington'	['question_type_global', 'question_four_hop_statement']
show me all stores near [Cedar Court]	'saks fifth avenue'	['question_type_global', 'question_single_statement']
is there a store near my location is having a sale?	'burlington', 'foodtown', 'safeway', 'sage-allen'	['question_type_global', 'question_three_hop_statement']
just arrived to [Cedar Court]
what stores on [9th Street West] have a sale?	'safeway', 'burlington', 'sage-allen', 'foodtown'	['question_type_global', 'question_two_hop_statement']
what stores on [9th Street West] have a sale on [meat]?	'foodtown'	['question_type_global', 'question_three_hop_statement']
is there anything on my list that's on sale somewhere?	'Slippers'	['question_type_global', 'question_two_hop_statement']
what are the department stores?	'gold circle', 'burlington', 'sage-allen', 'saks fifth avenue'	['question_type_global', 'question_single_statement']
what items that I have to buy currently are on sale?	'Slippers'	['question_type_global', 'question_two_hop_statement']
is there a sale on any items on my shopping list?	'Slippers'	['question_type_global', 'question_two_hop_statement']
what is on sale near my current location?	'shawl'	['question_type_global', 'question_three_hop_statement']
is there a store nearby with a sale going on right now?	'saks fifth avenue'	['question_type_global', 'question_three_hop_statement']
show me all stores on [9th Street West] that currently have a sale	'safeway', 'burlington', 'sage-allen', 'foodtown'	['question_type_global', 'question_two_hop_statement']
is there a sale on any [clothing] on my shopping list?	'Slippers'	['question_type_global', 'question_three_hop_statement']
there is a [department store] called [five below] on [9th Street West]
show me all of the department stores on [9th Street West]	'burlington', 'sage-allen', 'five below'	['question_type_global', 'question_single_statement']
what are the supermarkets on [9th Street West]?	'safeway', 'foodtown'	['question_type_global', 'question_single_statement']
show me all supermarkets near [9th Street West]	'safeway', 'foodtown'	['question_type_global', 'question_single_statement']
what [clothing] do i need to buy?	'Slippers', 'Hat', 'Sarong'	['question_type_global', 'question_two_hop_statement']
what items that I have to buy for [karen's wedding] currently are on sale?	'Slippers'	['question_type_global', 'question_two_hop_statement']
does any store nearby have [gifts] on sale?	'saks fifth avenue'	['question_type_global', 'question_four_hop_statement']
Where is [T-Shirt] on sale?	'burlington'	['question_type_local']
is there any [clothing] that I have to buy currently are on sale?	'Slippers'	['question_type_global', 'question_three_hop_statement']
is there any [clothing] on my list that's on sale somewhere?	'Slippers'	['question_type_global', 'question_three_hop_statement']
what are the supermarkets on [9th Street West]?	'safeway', 'foodtown'	['question_type_global', 'question_single_statement']
what stores are there on [Cedar Court]?	'saks fifth avenue'	['question_type_global', 'question_single_statement']
what stores near [9th Street West] have an ongoing sale on [gifts]?	'burlington'	['question_type_global', 'question_three_hop_statement']
what do i need to buy?	'Slippers', 'Hat', 'Sarong'	['question_type_global', 'question_single_statement']
show me all of the department stores	'gold circle', 'burlington', 'sage-allen', 'saks fifth avenue', 'five below'	['question_type_global', 'question_single_statement']
what items that I have to buy currently are on sale?	'Slippers'	['question_type_global', 'question_two_hop_statement']
does any store nearby have [gifts] on sale?	'saks fifth avenue'	['question_type_global', 'question_four_hop_statement']
show me all of the stores	'safeway', 'gold circle', 'burlington', 'sage-allen', 'foodtown', 'saks fifth avenue', 'five below'	['question_type_global', 'question_single_statement']
show me all department stores near [9th Street West]	'burlington', 'sage-allen', 'five below'	['question_type_global', 'question_single_statement']
Where is [Blouse] on sale?	'burlington'	['question_type_local']
what stores are there that I taught you?	'safeway', 'gold circle', 'burlington', 'sage-allen', 'foodtown', 'saks fifth avenue', 'five below'	['question_type_global', 'question_single_statement']
what do i need to buy?	'Slippers', 'Hat', 'Sarong'	['question_type_global', 'question_single_statement']
[saks fifth avenue] has [Water cooker], [Microwave oven] and [Water purifier] on sale!
what's currently on sale at [saks fifth avenue]?	'Microwave oven', 'Water purifier', 'shawl', 'Water cooker'	['question_type_local']
what are the supermarkets on [9th Street West]?	'safeway', 'foodtown'	['question_type_global', 'question_single_statement']
show me all supermarkets on [9th Street West] that currently have a sale	'safeway', 'foodtown'	['question_type_global', 'question_two_hop_statement']
what are the supermarkets?	'safeway', 'foodtown'	['question_type_global', 'question_single_statement']
[foodtown] is a [supermarket]
[Goat], [Rabbit] and [Duck Liver] are all on sale at [that supermarket]
What stores is [grapefruit] on sale at	'safeway'	['question_type_local']
are there any [clothing] on my shopping list that there is a sale on?	'Slippers'	['question_type_global', 'question_three_hop_statement']
show me all department stores near [9th Street West]	'burlington', 'sage-allen', 'five below'	['question_type_global', 'question_single_statement']
what stores near [9th Street West] have an ongoing sale on [cherry]?	'safeway'	['question_type_global', 'question_two_hop_statement']
is there a sale on [Rabbit] anywhere?	'foodtown', 'foodtown'	['question_type_local']
[Aspen Drive] is located in the [Plaza District] neighborhood
does any store nearby have anything on sale?	'saks fifth avenue'	['question_type_global', 'question_three_hop_statement']
[Carrot] is a type of [Vegetables]
what are the department stores?	'gold circle', 'burlington', 'sage-allen', 'saks fifth avenue', 'five below'	['question_type_global', 'question_single_statement']
is there a store nearby with a sale on [gifts] going on right now?	'saks fifth avenue'	['question_type_global', 'question_four_hop_statement']
what are the things that i need to get?	'Slippers', 'Hat', 'Sarong'	['question_type_global', 'question_single_statement']
what do stores near me are have a sale on?	'Microwave oven', 'Water purifier', 'shawl', 'Water cooker'	['question_type_global', 'question_three_hop_statement']
what stores near [Cedar Court] have an ongoing sale on [gifts]?	'saks fifth avenue'	['question_type_global', 'question_three_hop_statement']
what stores on [9th Street West] have a sale on [meat]?	'foodtown'	['question_type_global', 'question_three_hop_statement']
show me all supermarkets on [9th Street West] that currently have a sale	'safeway', 'foodtown'	['question_type_global', 'question_two_hop_statement']
does any store nearby have [gifts] on sale?	'saks fifth avenue'	['question_type_global', 'question_four_hop_statement']
show me all of the supermarkets on [9th Street West]	'safeway', 'foodtown'	['question_type_global', 'question_single_statement']
i think [Surrey Lane] is in [Friendship]
what stores near [9th Street West] have an ongoing sale on [fruit]?	'safeway'	['question_type_global', 'question_three_hop_statement']
is there any [clothing] that I have to buy currently are on sale?	'Slippers'	['question_type_global', 'question_three_hop_statement']
show me all of the department stores on [Cedar Court]	'saks fifth avenue'	['question_type_global', 'question_single_statement']
is there a sale on [Slippers] anywhere?	'burlington'	['question_type_local']
is there a store nearby with a sale on [gifts] going on right now?	'saks fifth avenue'	['question_type_global', 'question_four_hop_statement']
are there any stores nearby that have a sale?	'saks fifth avenue'	['question_type_global', 'question_three_hop_statement']
what department stores are there on [9th Street West]?	'burlington', 'sage-allen', 'five below'	['question_type_global', 'question_single_statement']
i think this [gold circle] is somewhere on [Aspen Drive]
[Hat] and [Cummerbund] are on sale at [that department store]
[Cummerbund] and [Hat] are no longer on sale at [gold circle]
why do i need to buy [Hat]?	"karen's wedding"	['question_type_local']
show me all supermarkets on [9th Street West] that currently have a sale	'safeway', 'foodtown'	['question_type_global', 'question_two_hop_statement']
what supermarkets near [9th Street West] have an ongoing sale?	'safeway', 'foodtown'	['question_type_global', 'question_two_hop_statement']
what are the things that i need to get?	'Slippers', 'Hat', 'Sarong'	['question_type_global', 'question_single_statement']
what neighborhood is [Cedar Court] in?	'Cedar Park'	['question_type_local']
show me all of the department stores	'gold circle', 'burlington', 'sage-allen', 'saks fifth avenue', 'five below'	['question_type_global', 'question_single_statement']
what is on sale at [sage-allen]?	'Ceiling fan', 'Water cooker'	['question_type_local']
what are the supermarkets on [9th Street West]?	'safeway', 'foodtown'	['question_type_global', 'question_single_statement']
show me all stores on [9th Street West] that currently have a sale	'safeway', 'burlington', 'sage-allen', 'foodtown'	['question_type_global', 'question_two_hop_statement']
show me all stores on [9th Street West] that currently have a sale on [clothing]	'burlington'	['question_type_global', 'question_three_hop_statement']
show me all supermarkets near [9th Street West] that have a sale	'safeway', 'foodtown'	['question_type_global', 'question_two_hop_statement']
is there anything on my list that's on sale somewhere?	'Slippers'	['question_type_global', 'question_two_hop_statement']
show me all supermarkets on [9th Street West] that currently have a sale	'safeway', 'foodtown'	['question_type_global', 'question_two_hop_statement']
show me all supermarkets that i tought you	'safeway', 'foodtown'	['question_type_global', 'question_single_statement']
what stores are located on [9th Street West]?	'sage-allen', 'burlington', 'safeway', 'foodtown', 'five below'	['question_type_local']
does any store nearby have [appliances] on sale?	'saks fifth avenue'	['question_type_global', 'question_four_hop_statement']
is there a store near my location is having a sale?	'saks fifth avenue'	['question_type_global', 'question_three_hop_statement']
is there a store near my location is having a sale on [appliances]?	'saks fifth avenue'	['question_type_global', 'question_four_hop_statement']
show me all of the department stores	'gold circle', 'burlington', 'sage-allen', 'saks fifth avenue', 'five below'	['question_type_global', 'question_single_statement']
[Liver] and [Cornish Hen] are both different kinds of [Meat]
is there anything that I need for [karen's wedding] that's on sale somewhere?	'Slippers'	['question_type_global', 'question_two_hop_statement']
show me all stores near [9th Street West] that have a sale on [appliances]	'sage-allen'	['question_type_global', 'question_three_hop_statement']
is there a store nearby with a sale on [appliances] going on right now?	'saks fifth avenue'	['question_type_global', 'question_four_hop_statement']
what stores near [9th Street West] have an ongoing sale?	'safeway', 'burlington', 'sage-allen', 'foodtown'	['question_type_global', 'question_two_hop_statement']
Where is [orange] on sale?	'safeway'	['question_type_local']
what department stores are there	'gold circle', 'burlington', 'sage-allen', 'saks fifth avenue', 'five below'	['question_type_global', 'question_single_statement']
Where is [Blouse] on sale?	'burlington'	['question_type_local']
are there any stores nearby that have a sale on [appliances]?	'saks fifth avenue'	['question_type_global', 'question_four_hop_statement']
what is on sale at [foodtown on 9th Street West]?	'Veal', 'Rabbit', 'Pork'	['question_type_local']
what are the things that I need to get?	'Slippers', 'Hat', 'Sarong'	['question_type_global', 'question_single_statement']
what stores on [9th Street West] have a sale on [meat]?	'foodtown'	['question_type_global', 'question_three_hop_statement']
what do stores near me have on sale?	'Microwave oven', 'Water purifier', 'shawl', 'Water cooker'	['question_type_global', 'question_three_hop_statement']
what stores near [Cedar Court] have an ongoing sale?	'saks fifth avenue'	['question_type_global', 'question_two_hop_statement']
show me all stores on [9th Street West] that currently have a sale on [clothing]	'burlington'	['question_type_global', 'question_three_hop_statement']
[safeway] has [Goose Liver], [Liver] and [Duck Liver] on sale!
what items are on sale at [burlington]?	'Slippers', 'T-Shirt', 'Blouse', 'speakers', 'sun glasses', 'slippers'	['question_type_local']
what items are on sale at nearby stores?	'Microwave oven', 'Water purifier', 'shawl', 'Water cooker'	['question_type_global', 'question_three_hop_statement']
[safeway] is a [supermarket]
show me all stores	'safeway', 'gold circle', 'burlington', 'sage-allen', 'foodtown', 'saks fifth avenue', 'five below'	['question_type_global', 'question_single_statement']
show me all stores on [9th Street West] that currently have a sale	'safeway', 'burlington', 'sage-allen', 'foodtown'	['question_type_global', 'question_two_hop_statement']
are there any stores nearby that have a sale on [gifts]?	'saks fifth avenue'	['question_type_global', 'question_four_hop_statement']
what stores near [9th Street West] have an ongoing sale on [gifts]?	'burlington'	['question_type_global', 'question_three_hop_statement']
is there any [clothing] that I have to buy currently are on sale?	'Slippers'	['question_type_global', 'question_three_hop_statement']
what stores near [9th Street West] have an ongoing sale on [meat]?	'safeway', 'foodtown'	['question_type_global', 'question_three_hop_statement']
is there a sale on [Pork] anywhere?	'foodtown'	['question_type_local']
is there a store near my location is having a sale?	'saks fifth avenue'	['question_type_global', 'question_three_hop_statement']
is there a store near my location is having a sale on [gifts]?	'saks fifth avenue'	['question_type_global', 'question_four_hop_statement']
what stores near [Cedar Court] have an ongoing sale on [Water cooker]?	'saks fifth avenue'	['question_type_global', 'question_two_hop_statement']
What stores is [Blouse] on sale at	'burlington'	['question_type_local']
what stores near [9th Street West] have an ongoing sale on [fruit]?	'safeway'	['question_type_global', 'question_three_hop_statement']
what are the supermarkets?	'safeway', 'foodtown'	['question_type_global', 'question_single_statement']
show me all stores near [9th Street West] that have a sale	'safeway', 'burlington', 'sage-allen', 'foodtown'	['question_type_global', 'question_two_hop_statement']
is there anything on my list that's on sale somewhere?	'Slippers'	['question_type_global', 'question_two_hop_statement']
[tangerine] is on sale at [that store]
this [that store] is on [Surrey Lane]
what items are on sale at [this store]?	'tangerine'	['question_type_local']
[that supermarket] has [Peas] and [Borlotti bean] on sale!
[safeway on Surrey Lane] doesn't have [Borlotti bean] on sale anymore
what items are on sale at [sage-allen]?	'Ceiling fan', 'Water cooker'	['question_type_local']
show me all stores	'safeway', 'gold circle', 'burlington', 'sage-allen', 'foodtown', 'saks fifth avenue', 'five below'	['question_type_global', 'question_single_statement']
what kind of [clothing] do I need to get?	'Slippers', 'Hat', 'Sarong'	['question_type_global', 'question_two_hop_statement']
is there a store nearby with a sale on [gifts] going on right now?	'saks fifth avenue'	['question_type_global', 'question_four_hop_statement']
what neighborhood is [Cedar Court] in?	'Cedar Park'	['question_type_local']
what are the supermarkets?	'safeway', 'foodtown'	['question_type_global', 'question_single_statement']
is there anything that I need for [karen's wedding] that's on sale somewhere?	'Slippers'	['question_type_global', 'question_two_hop_statement']
What stores is [cherry] on sale at	'safeway'	['question_type_local']
is there a store nearby with a sale going on right now?	'saks fifth avenue'	['question_type_global', 'question_three_hop_statement']
what is on sale at [foodtown on 9th Street West]?	'Veal', 'Rabbit', 'Pork'	['question_type_local']
is there anything on my list that's on sale somewhere?	'Slippers'	['question_type_global', 'question_two_hop_statement']
[Red pepper], [Habanero] and [Quandong] are all different types of [Vegetables]
are there any stores nearby that have a sale on [appliances]?	'saks fifth avenue'	['question_type_global', 'question_four_hop_statement']
show me all stores near [Surrey Lane] that have a sale	'safeway'	['question_type_global', 'question_two_hop_statement']
what are the department stores on [9th Street West]?	'burlington', 'sage-allen', 'five below'	['question_type_global', 'question_single_statement']
show me all supermarkets near [Surrey Lane]	'safeway'	['question_type_global', 'question_single_statement']
what supermarkets are there on [9th Street West]?	'safeway', 'foodtown'	['question_type_global', 'question_single_statement']
what do i need to buy?	'Slippers', 'Hat', 'Sarong'	['question_type_global', 'question_single_statement']
what are the department stores on [Aspen Drive]?	'gold circle'	['question_type_global', 'question_single_statement']
show me all supermarkets on [9th Street West] that currently have a sale	'safeway', 'foodtown'	['question_type_global', 'question_two_hop_statement']
what stores near [Cedar Court] have an ongoing sale on [gifts]?	'saks fifth avenue'	['question_type_global', 'question_three_hop_statement']
what items are on sale at [safeway that I last mentioned]?	'Peas', 'tangerine'	['question_type_local']
what neighborhood is [Cedar Court] located in?	'Cedar Park'	['question_type_local']
[shawl], [sun glasses] and [slippers] are all on sale at [five below]
[sun glasses] is not on sale at [five below]
what's currently on sale at [this store]?	'shawl', 'slippers'	['question_type_local']
show me all supermarkets near [Surrey Lane]	'safeway'	['question_type_global', 'question_single_statement']
is there anything on sale at a store nearby?	'Microwave oven', 'Water purifier', 'shawl', 'Water cooker'	['question_type_global', 'question_three_hop_statement']
show me all department stores	'gold circle', 'burlington', 'sage-allen', 'saks fifth avenue', 'five below'	['question_type_global', 'question_single_statement']
what items are on sale at nearby stores?	'Microwave oven', 'Water purifier', 'shawl', 'Water cooker'	['question_type_global', 'question_three_hop_statement']
[slippers] is no longer on sale at [five below]
what is on sale at [five below]?	'shawl'	['question_type_local']
are there any stores nearby that have a sale on [gifts]?	'saks fifth avenue'	['question_type_global', 'question_four_hop_statement']
some example of [Fruit] are [guava] and [strawberry]
what neighborhood is [Cedar Court] in?	'Cedar Park'	['question_type_local']
is there a sale on [Duck Liver] anywhere?	'foodtown', 'safeway'	['question_type_local']
[foodtown that I last mentioned] has [Veal] and [Liver] on sale!
is there a store nearby with a sale on [shawl] going on right now?	'saks fifth avenue'	['question_type_global', 'question_three_hop_statement']
Where is [Water purifier] on sale?	'saks fifth avenue'	['question_type_local']
Where is [Goat] on sale?	'foodtown'	['question_type_local']
Do i have any [clothing] on my shopping list?	'Slippers', 'Hat', 'Sarong'	['question_type_global', 'question_two_hop_statement']
what department stores are there	'gold circle', 'burlington', 'sage-allen', 'saks fifth avenue', 'five below'	['question_type_global', 'question_single_statement']
what are the department stores?	'gold circle', 'burlington', 'sage-allen', 'saks fifth avenue', 'five below'	['question_type_global', 'question_single_statement']
are there any stores nearby that have a sale on [gifts]?	'saks fifth avenue'	['question_type_global', 'question_four_hop_statement']
what [clothing] do i need to buy?	'Slippers', 'Hat', 'Sarong'	['question_type_global', 'question_two_hop_statement']
is there a store near my location is having a sale?	'saks fifth avenue'	['question_type_global', 'question_three_hop_statement']
What stores is [Liver] on sale at	'foodtown', 'safeway'	['question_type_local']
is there a store nearby with a sale on [gifts] going on right now?	'saks fifth avenue'	['question_type_global', 'question_four_hop_statement']
[sage-allen] has [Sarong], [Cufflinks] and [Hat] on sale!
what are the department stores on [Aspen Drive]?	'gold circle'	['question_type_global', 'question_single_statement']
show me all stores on [9th Street West] that currently have a sale on [fruit]	'safeway'	['question_type_global', 'question_three_hop_statement']
is there a sale on [Ceiling fan] anywhere?	'sage-allen'	['question_type_local']
what are the stores?	'safeway', 'gold circle', 'burlington', 'sage-allen', 'foodtown', 'saks fifth avenue', 'five below'	['question_type_global', 'question_single_statement']
does any store nearby have [gifts] on sale?	'saks fifth avenue'	['question_type_global', 'question_four_hop_statement']
what are the department stores?	'gold circle', 'burlington', 'sage-allen', 'saks fifth avenue', 'five below'	['question_type_global', 'question_single_statement']
is there a sale on [Hat] anywhere?	'sage-allen'	['question_type_local']
Where is [Peas] on sale?	'safeway'	['question_type_local']
is there any [clothing] that I have to buy currently are on sale?	'Slippers', 'Hat', 'Sarong'	['question_type_global', 'question_three_hop_statement']
what items are on sale at nearby stores?	'Microwave oven', 'Water purifier', 'shawl', 'Water cooker'	['question_type_global', 'question_three_hop_statement']
is there a sale on [Water cooker] anywhere?	'sage-allen', 'saks fifth avenue'	['question_type_local']
there is a [department store] called [gold circle] on [Surrey Lane]
[Boots], [that item] and [Blouse] are all on sale at [this store]
what things did i get for [karen's wedding]	'T-Shirt', 'Blouse'	['question_type_local']
what are the things that I need to get?	'Slippers', 'Hat', 'Sarong'	['question_type_global', 'question_single_statement']
what are the stores?	'safeway', 'gold circle', 'burlington', 'sage-allen', 'foodtown', 'saks fifth avenue', 'five below'	['question_type_global', 'question_single_statement']
are there any items on my shopping list that there is a sale on?	'Slippers', 'Hat', 'Sarong'	['question_type_global', 'question_two_hop_statement']
[cell phone], [sun glasses] and [slippers] are on sale at [saks fifth avenue]
show me all of the department stores on [Cedar Court]	'saks fifth avenue'	['question_type_global', 'question_single_statement']
is there a sale on [Liver] anywhere?	'foodtown', 'safeway'	['question_type_local']
Where is [Ceiling fan] on sale?	'sage-allen'	['question_type_local']
what neighborhood am I currently in?	'Cedar Park'	['question_type_local']
show me all supermarkets that i tought you	'safeway', 'foodtown'	['question_type_global', 'question_single_statement']
what do stores near me have on sale?	'Microwave oven', 'Water purifier', 'shawl', 'cell phone', 'Water cooker', 'sun glasses', 'slippers'	['question_type_global', 'question_three_hop_statement']
What stores is [Peas] on sale at	'safeway'	['question_type_local']
show me all of the supermarkets on [9th Street West]	'safeway', 'foodtown'	['question_type_global', 'question_single_statement']
are there any items on my shopping list that there is a sale on?	'Slippers', 'Hat', 'Sarong'	['question_type_global', 'question_two_hop_statement']
is there a store near my location is having a sale?	'saks fifth avenue'	['question_type_global', 'question_three_hop_statement']
show me all stores near [9th Street West] that have a sale on [gifts]	'burlington', 'five below'	['question_type_global', 'question_three_hop_statement']
What stores is [Water cooker] on sale at	'sage-allen', 'saks fifth avenue'	['question_type_local']
show me all of the department stores on [Cedar Court]	'saks fifth avenue'	['question_type_global', 'question_single_statement']
are there any [clothing] on my shopping list that there is a sale on?	'Slippers', 'Hat', 'Sarong'	['question_type_global', 'question_three_hop_statement']
what stores are on [Cedar Court]?	'saks fifth avenue'	['question_type_local']
is there a sale on any [clothing] on my shopping list?	'Slippers', 'Hat', 'Sarong'	['question_type_global', 'question_three_hop_statement']
[cell phone], [speakers] and [shawl] are all on sale at [sage-allen]
[Ceiling fan], [shawl] and [Water cooker] are no longer on sale at [sage-allen]
Where is [Water purifier] on sale?	'saks fifth avenue'	['question_type_local']
what items are on sale at nearby stores?	'Microwave oven', 'Water purifier', 'shawl', 'cell phone', 'Water cooker', 'sun glasses', 'slippers'	['question_type_global', 'question_three_hop_statement']
what department stores near [Cedar Court] have an ongoing sale?	'saks fifth avenue'	['question_type_global', 'question_two_hop_statement']
what are the things that I need to get?	'Slippers', 'Hat', 'Sarong'	['question_type_global', 'question_single_statement']
what supermarkets are there on [9th Street West]?	'safeway', 'foodtown'	['question_type_global', 'question_single_statement']
[Borlotti bean] and [Habanero] are on sale at [safeway on 9th Street West]
what items that I have to buy currently are on sale?	'Slippers', 'Hat', 'Sarong'	['question_type_global', 'question_two_hop_statement']
show me all supermarkets that i tought you	'safeway', 'foodtown'	['question_type_global', 'question_single_statement']
[Water cooker], [Ceiling fan] and [Box mangle] are all on sale at [sage-allen]
what do stores near me have on sale?	'Microwave oven', 'Water purifier', 'shawl', 'cell phone', 'Water cooker', 'sun glasses', 'slippers'	['question_type_global', 'question_three_hop_statement']
show me all stores on [9th Street West] that currently have a sale on [meat]	'safeway', 'foodtown'	['question_type_global', 'question_three_hop_statement']
what stores near [9th Street West] have an ongoing sale?	'safeway', 'burlington', 'sage-allen', 'foodtown', 'five below'	['question_type_global', 'question_two_hop_statement']
what items are on sale at [burlington]?	'Slippers', 'T-Shirt', 'Blouse', 'speakers', 'sun glasses', 'slippers'	['question_type_local']
show me all of the supermarkets	'safeway', 'foodtown'	['question_type_global', 'question_single_statement']
are there any stores nearby that have a sale on [appliances]?	'saks fifth avenue'	['question_type_global', 'question_four_hop_statement']
is there a store near my location is having a sale?	'saks fifth avenue'	['question_type_global', 'question_three_hop_statement']
what stores are there that I taught you?	'safeway', 'gold circle', 'burlington', 'sage-allen', 'foodtown', 'saks fifth avenue', 'five below'	['question_type_global', 'question_single_statement']
please remind me to buy [Fleece] and [Camisole] for [karen's wedding]
i don't need [Hat] for [karen's wedding] anymore
What stores is [that item] on sale at	'sage-allen', 'gold circle'	['question_type_local']
show me all of the stores on [Aspen Drive]	'gold circle'	['question_type_global', 'question_single_statement']
what neighborhood am I currently in?	'Cedar Park'	['question_type_local']
show me all stores on [Cedar Court] that currently have a sale on [gifts]	'saks fifth avenue'	['question_type_global', 'question_three_hop_statement']
what is on sale at [safeway on Surrey Lane]?	'Peas', 'tangerine'	['question_type_local']
Where is [Borlotti bean] on sale?	'safeway'	['question_type_local']
show me all of the department stores on [Surrey Lane]	'gold circle'	['question_type_global', 'question_single_statement']
what are the things that I need to get?	'Slippers', 'Fleece', 'Sarong', 'Camisole'	['question_type_global', 'question_single_statement']
[Tights], [Shawl] and [Cufflinks] are on sale at [gold circle on Aspen Drive]
what's currently on sale at [gold circle on Aspen Drive]?	'Shawl', 'Tights', 'Cufflinks'	['question_type_local']
what are the supermarkets?	'safeway', 'foodtown'	['question_type_global', 'question_single_statement']
i often shop at [safeway], which is my local [supermarket]
this specific [that store] is on [Cedar Court]
what stores on [Surrey Lane] have a sale?	'safeway', 'gold circle'	['question_type_global', 'question_two_hop_statement']
what stores are there on [Surrey Lane]?	'safeway', 'gold circle'	['question_type_global', 'question_single_statement']
show me all stores	'safeway', 'gold circle', 'burlington', 'sage-allen', 'foodtown', 'saks fifth avenue', 'five below'	['question_type_global', 'question_single_statement']
What stores is [Water cooker] on sale at	'sage-allen', 'saks fifth avenue'	['question_type_local']
show me all of the stores on [Surrey Lane]	'safeway', 'gold circle'	['question_type_global', 'question_single_statement']
[Duck Liver], [Veal] and [Goat] are on sale at [safeway]
[Veal], [Duck Liver] and [Goat] are no longer on sale at [safeway on Cedar Court]
show me all of the department stores on [9th Street West]	'burlington', 'sage-allen', 'five below'	['question_type_global', 'question_single_statement']
what items that I have to buy currently are on sale?	'Slippers', 'Sarong'	['question_type_global', 'question_two_hop_statement']
show me all stores near [Surrey Lane] that have a sale on [vegetables]	'safeway'	['question_type_global', 'question_three_hop_statement']
are there any stores nearby that have a sale on [appliances]?	'saks fifth avenue'	['question_type_global', 'question_four_hop_statement']
is there a sale on any items on my shopping list?	'Slippers', 'Sarong'	['question_type_global', 'question_two_hop_statement']
show me all of the department stores on [Surrey Lane]	'gold circle'	['question_type_global', 'question_single_statement']
what items that I have to buy for [karen's wedding] currently are on sale?	'Slippers', 'Sarong'	['question_type_global', 'question_two_hop_statement']
what are the department stores on [9th Street West]?	'burlington', 'sage-allen', 'five below'	['question_type_global', 'question_single_statement']
i don't need [Fleece] for [karen's wedding] anymore
what things do I need to buy for [this event]	'Slippers', 'Sarong', 'Camisole'	['question_type_local']
[Hanover Court] is in [Plaza District]
is there a store near my location is having a sale on [appliances]?	'saks fifth avenue'	['question_type_global', 'question_four_hop_statement']
what stores near [9th Street West] have an ongoing sale on [fruit]?	'safeway'	['question_type_global', 'question_three_hop_statement']
is there a sale on [Sarong] anywhere?	'sage-allen'	['question_type_local']
show me all of the stores on [Cedar Court]	'saks fifth avenue', 'safeway'	['question_type_global', 'question_single_statement']
what kind of [clothing] do I need to get?	'Slippers', 'Sarong', 'Camisole'	['question_type_global', 'question_two_hop_statement']
is there a sale on [Duck Liver] anywhere?	'foodtown', 'safeway'	['question_type_local']
some example of [Fruit] are [papaya] and [peach]
what items that I have to buy currently are on sale?	'Slippers', 'Sarong'	['question_type_global', 'question_two_hop_statement']
What stores is [Goat] on sale at	'foodtown'	['question_type_local']
what stores on [9th Street West] have a sale on [clothing]?	'burlington', 'sage-allen'	['question_type_global', 'question_three_hop_statement']
what are the things that I need to get?	'Slippers', 'Sarong', 'Camisole'	['question_type_global', 'question_single_statement']
is there anything on sale at a store nearby?	'Microwave oven', 'Water purifier', 'shawl', 'cell phone', 'Water cooker', 'sun glasses', 'slippers'	['question_type_global', 'question_three_hop_statement']
what neighborhood am I currently in?	'Cedar Park'	['question_type_local']
what do stores near me are have a sale on?	'Microwave oven', 'Water purifier', 'shawl', 'cell phone', 'Water cooker', 'sun glasses', 'slippers'	['question_type_global', 'question_three_hop_statement']
show me all stores	'safeway', 'gold circle', 'burlington', 'sage-allen', 'foodtown', 'saks fifth avenue', 'five below'	['question_type_global', 'question_single_statement']
this [foodtown that I last mentioned] is on [Hanover Court]
[Zucchini] and [Habanero] are all on sale at [this supermarket]
[Liver], [Habanero] and [Rabbit] are no longer on sale at [foodtown on Hanover Court]
what is on sale at [foodtown that I last mentioned]?	'Veal', 'Duck Liver', 'Goat', 'Zucchini'	['question_type_local']
what is my shopping list?	'Slippers', 'Sarong', 'Camisole'	['question_type_global', 'question_single_statement']
are there any items on my shopping list that there is a sale on?	'Slippers', 'Sarong'	['question_type_global', 'question_two_hop_statement']
Where is [that meat] on sale?	'foodtown'	['question_type_local']
is there any [clothing] on my list that's on sale somewhere?	'Slippers', 'Sarong'	['question_type_global', 'question_three_hop_statement']
what do i need to buy?	'Slippers', 'Sarong', 'Camisole'	['question_type_global', 'question_single_statement']
Do I need to buy any [clothing]?	'Slippers', 'Sarong', 'Camisole'	['question_type_global', 'question_two_hop_statement']
Where is [tangerine] on sale?	'safeway'	['question_type_local']
What stores is [Goat] on sale at	'foodtown'	['question_type_local']
show me all of the supermarkets on [Hanover Court]	'foodtown'	['question_type_global', 'question_single_statement']
I am currently on [Hanover Court]
what stores near [Surrey Lane] have an ongoing sale on [fruit]?	'safeway'	['question_type_global', 'question_three_hop_statement']
what neighborhood is [Surrey Lane] in?	'Friendship'	['question_type_local']
show me all supermarkets that i tought you	'safeway', 'foodtown'	['question_type_global', 'question_single_statement']
I am currently on [Cedar Court]
what [clothing] do i need to buy?	'Slippers', 'Sarong', 'Camisole'	['question_type_global', 'question_two_hop_statement']
show me all department stores near [Aspen Drive] that have a sale	'gold circle'	['question_type_global', 'question_two_hop_statement']
are there any [clothing] on my shopping list that there is a sale on?	'Slippers', 'Sarong'	['question_type_global', 'question_three_hop_statement']
are there any stores nearby that have a sale on [appliances]?	'saks fifth avenue'	['question_type_global', 'question_four_hop_statement']
just arrived to [Hanover Court]
what neighborhood am I in?	'Plaza District'	['question_type_local']
Do i have any [clothing] on my shopping list?	'Slippers', 'Sarong', 'Camisole'	['question_type_global', 'question_two_hop_statement']
what are the department stores on [Cedar Court]?	'saks fifth avenue'	['question_type_global', 'question_single_statement']
what neighborhood is [Hanover Court] located in?	'Plaza District'	['question_type_local']
is there a store near my location is having a sale?	'foodtown'	['question_type_global', 'question_three_hop_statement']
are there any stores nearby that have a sale on [meat]?	'foodtown'	['question_type_global', 'question_four_hop_statement']
what stores are on [it]?	'foodtown'	['question_type_local']
I am currently on [Aspen Drive]
what kind of [clothing] do I need to get?	'Slippers', 'Sarong', 'Camisole'	['question_type_global', 'question_two_hop_statement']
are there any stores nearby that have a sale?	'gold circle'	['question_type_global', 'question_three_hop_statement']
show me all supermarkets near [Surrey Lane] that have a sale	'safeway'	['question_type_global', 'question_two_hop_statement']
what stores are located on [that street]?	'gold circle'	['question_type_local']
what department stores near [Surrey Lane] have an ongoing sale?	'gold circle'	['question_type_global', 'question_two_hop_statement']
is there a sale on any items on my shopping list for [karen's wedding]?	'Slippers', 'Sarong'	['question_type_global', 'question_two_hop_statement']
[gold circle on it] has [speakers] and [slippers] on sale!
What stores is [Shawl] on sale at	'gold circle'	['question_type_local']
what stores on [Cedar Court] have a sale on [gifts]?	'saks fifth avenue'	['question_type_global', 'question_three_hop_statement']
What stores is [T-Shirt] on sale at	'burlington'	['question_type_local']
show me all department stores on [Cedar Court] that currently have a sale	'saks fifth avenue'	['question_type_global', 'question_two_hop_statement']
are there any stores nearby that have a sale?	'gold circle'	['question_type_global', 'question_three_hop_statement']
what stores on [Surrey Lane] have a sale on [fruit]?	'safeway'	['question_type_global', 'question_three_hop_statement']
are there any stores nearby that have a sale on [gifts]?	'gold circle'	['question_type_global', 'question_four_hop_statement']
[Canterbury Road] is on the outskirts of [Plaza District]
What stores is [that thing] on sale at	'burlington', 'saks fifth avenue', 'gold circle'	['question_type_local']
what stores near [Surrey Lane] have an ongoing sale on [vegetables]?	'safeway'	['question_type_global', 'question_three_hop_statement']
what are the things that I need to get?	'Slippers', 'Sarong', 'Camisole'	['question_type_global', 'question_single_statement']
what neighborhood is [that street] located in?	'Plaza District'	['question_type_local']
does any store nearby have anything on sale?	'gold circle'	['question_type_global', 'question_three_hop_statement']
are there any [clothing] on my shopping list that there is a sale on?	'Slippers', 'Sarong'	['question_type_global', 'question_three_hop_statement']
show me all stores near [Aspen Drive] that have a sale	'gold circle'	['question_type_global', 'question_two_hop_statement']
what [clothing] do i need to buy?	'Slippers', 'Sarong', 'Camisole'	['question_type_global', 'question_two_hop_statement']
What stores is [this item] on sale at	'burlington', 'saks fifth avenue', 'gold circle'	['question_type_local']
show me all of the supermarkets on [9th Street West]	'safeway', 'foodtown'	['question_type_global', 'question_single_statement']
What stores is [T-Shirt] on sale at	'burlington'	['question_type_local']
what are the stores on [Surrey Lane]?	'safeway', 'gold circle'	['question_type_global', 'question_single_statement']
is there any [clothing] on my list that's on sale somewhere?	'Slippers', 'Sarong'	['question_type_global', 'question_three_hop_statement']
what stores on [Surrey Lane] have a sale on [vegetables]?	'safeway'	['question_type_global', 'question_three_hop_statement']
show me all stores near [Hanover Court]	'foodtown'	['question_type_global', 'question_single_statement']
is there a store near my location is having a sale on [gifts]?	'gold circle'	['question_type_global', 'question_four_hop_statement']
what do i need to buy?	'Slippers', 'Sarong', 'Camisole'	['question_type_global', 'question_single_statement']
does any store nearby have anything on sale?	'gold circle'	['question_type_global', 'question_three_hop_statement']
[Pork] is on sale at [foodtown that I last mentioned]
what items are on sale at [that store]?	'Veal', 'Pork', 'Duck Liver', 'Goat', 'Zucchini'	['question_type_local']
what supermarkets are there?	'safeway', 'foodtown'	['question_type_global', 'question_single_statement']
is there a store near my location is having a sale on [clothing]?	'gold circle'	['question_type_global', 'question_four_hop_statement']
What stores is [Habanero] on sale at	'safeway'	['question_type_local']
is there a sale on any [clothing] on my shopping list?	'Slippers', 'Sarong'	['question_type_global', 'question_three_hop_statement']
show me all department stores	'gold circle', 'burlington', 'sage-allen', 'saks fifth avenue', 'five below'	['question_type_global', 'question_single_statement']
what do stores near me are have a sale on?	'Shawl', 'Tights', 'speakers', 'slippers', 'Cufflinks'	['question_type_global', 'question_three_hop_statement']
[gold circle on Surrey Lane] has [Slippers] on sale!
what's currently on sale at [this store]?	'Slippers', 'Blouse', 'Hat', 'Boots'	['question_type_local']
what event do I need to buy [this item] for	"karen's wedding"	['question_type_local']
what department stores are there	'gold circle', 'burlington', 'sage-allen', 'saks fifth avenue', 'five below'	['question_type_global', 'question_single_statement']
what neighborhood am I currently in?	'Plaza District'	['question_type_local']
is there a sale on any items on my shopping list?	'Slippers', 'Sarong'	['question_type_global', 'question_two_hop_statement']
is there a sale on any items on my shopping list for [karen's wedding]?	'Slippers', 'Sarong'	['question_type_global', 'question_two_hop_statement']
What stores is [Tights] on sale at	'gold circle'	['question_type_local']
is there a sale on any [clothing] on my shopping list?	'Slippers', 'Sarong'	['question_type_global', 'question_three_hop_statement']
[sage-allen] has [Microwave oven] on sale!
what items are on sale at [that store]?	'Microwave oven', 'Ceiling fan', 'cell phone', 'Water cooker', 'Box mangle', 'Hat', 'speakers', 'Sarong', 'Cufflinks'	['question_type_local']
what [clothing] do i need to buy?	'Slippers', 'Sarong', 'Camisole'	['question_type_global', 'question_two_hop_statement']
show me all of the stores	'safeway', 'gold circle', 'burlington', 'sage-allen', 'foodtown', 'saks fifth avenue', 'five below'	['question_type_global', 'question_single_statement']
show me all of the supermarkets	'safeway', 'foodtown'	['question_type_global', 'question_single_statement']
[this store] has [sun glasses] on sale!
show me all of the stores on [Aspen Drive]	'gold circle'	['question_type_global', 'question_single_statement']
what are the department stores on [Cedar Court]?	'saks fifth avenue'	['question_type_global', 'question_single_statement']
what do stores near me are have a sale on?	'Shawl', 'Tights', 'speakers', 'slippers', 'Cufflinks'	['question_type_global', 'question_three_hop_statement']
[huckleberry] is a type of [Fruit]
what stores near [9th Street West] have an ongoing sale on [clothing]?	'burlington', 'sage-allen'	['question_type_global', 'question_three_hop_statement']
