i have [mandy's birthday] coming up
[socks], [monitor] and [mp3 player] are kinds of [Gift]
i need to make sure to get [mp3 player] and [socks] for [mandy's birthday]
i don't need [socks] and [mp3 player] for [mandy's birthday] anymore
[coasters], [phone] and [clay pot] are kinds of [Gift]
there is a [department store] called [miles market] that I shop in pretty often
show me all of the department stores	'miles market'	['question_type_global', 'question_single_statement']
[Turnip], [Black-eyed peas] and [Hubbard squash] are [Vegetables]
i need to make sure to get [clay pot] for [mandy's birthday]
[Box mangle] and [Oil heater] are [Appliance]
i need to make sure to get [Oil heater] and [Box mangle] for [mandy's birthday]
what do I need for [mandy's birthday]?	'clay pot', 'Box mangle', 'Oil heater'	['question_type_local']
[Gem squash] is a kind of [Vegetables]
i don't need [Box mangle] for [mandy's birthday] anymore
remove [clay pot] and [Oil heater] from my shopping list for [this event]
what are the stores?	'miles market'	['question_type_global', 'question_single_statement']
what stores are there that I taught you?	'miles market'	['question_type_global', 'question_single_statement']
i need to make sure to get [phone] for [mandy's birthday]
what are the department stores?	'miles market'	['question_type_global', 'question_single_statement']
[lamp shade] and [watch] are both different kinds of [Gift]
just purchases [phone] for [mandy's birthday]
[Turkey], [Moose] and [Kangaroo] are kinds of [Meat]
what things did i get for [mandy's birthday]	'socks', 'mp3 player', 'phone', 'clay pot', 'Box mangle', 'Oil heater'	['question_type_local']
i need to get [monitor] and [watch] for [mandy's birthday]
get rid of [watch] from my shopping list for [mandy's birthday]
what items did i already get for [that event]?	'socks', 'mp3 player', 'phone', 'clay pot', 'Box mangle', 'Oil heater', 'watch'	['question_type_local']
[Rabbit] is a type of [Meat]
what do i need [monitor] for?	"mandy's birthday"	['question_type_local']
show me all department stores	'miles market'	['question_type_global', 'question_single_statement']
what is my shopping list?	'monitor'	['question_type_global', 'question_single_statement']
[clay pot] and [monitor] are all on sale at [miles market]
[Sherwood Drive] is located in the [Downtown] neighborhood
what event do I need to buy [this item] for	"mandy's birthday"	['question_type_local']
Do i have any [gifts] on my shopping list?	'monitor'	['question_type_global', 'question_two_hop_statement']
what things do I need to buy for [mandy's birthday]	'monitor'	['question_type_local']
what do i need to buy?	'monitor'	['question_type_global', 'question_single_statement']
why do i need to buy [that thing]?	"mandy's birthday"	['question_type_local']
is there a sale on any [gifts] on my shopping list?	'monitor'	['question_type_global', 'question_three_hop_statement']
i don't need [this thing] for [mandy's birthday] anymore
What did I already buy for [that event]?	'socks', 'monitor', 'mp3 player', 'phone', 'clay pot', 'Box mangle', 'Oil heater', 'watch'	['question_type_local']
show me all of the department stores	'miles market'	['question_type_global', 'question_single_statement']
[television], [purse] and [blouse] are [Gift]
[Solar water heater] is a type of [Appliance]
[Turtle] and [Ham] are good examples of [Meat]
this [miles market] is on [Sherwood Drive]
[this department store] has [mp3 player] on sale!
[this department store] doesn't have [monitor] and [mp3 player] on sale anymore!
what did i remove from [mandy's birthday]?	'socks', 'monitor', 'mp3 player', 'phone', 'clay pot', 'Box mangle', 'Oil heater', 'watch'	['question_type_local']
i often shop at [giantway], which is my local [supermarket]
[that supermarket] has [Turtle] and [Ham] on sale!
i think this [giantway] is somewhere on [Sherwood Drive]
show me all stores near [Sherwood Drive] that have a sale on [meat]	'giantway'	['question_type_global', 'question_three_hop_statement']
show me all of the stores on [Sherwood Drive]	'miles market', 'giantway'	['question_type_global', 'question_single_statement']
what department stores are there on [Sherwood Drive]?	'miles market'	['question_type_global', 'question_single_statement']
[Pork], [Beef] and [Duck] are [Meat]
what supermarkets on [Sherwood Drive] have a sale?	'giantway'	['question_type_global', 'question_two_hop_statement']
what stores are there that I taught you?	'miles market', 'giantway'	['question_type_global', 'question_single_statement']
show me all stores near [Sherwood Drive] that have a sale	'miles market', 'giantway'	['question_type_global', 'question_two_hop_statement']
[model car] and [key chain] are both examples of [Gift]
show me all stores on [Sherwood Drive] that currently have a sale on [meat]	'giantway'	['question_type_global', 'question_three_hop_statement']
what stores on [Sherwood Drive] have a sale on [Ham]?	'giantway'	['question_type_global', 'question_two_hop_statement']
what stores on [Sherwood Drive] have a sale on [Turtle]?	'giantway'	['question_type_global', 'question_two_hop_statement']
what stores are there on [Sherwood Drive]?	'miles market', 'giantway'	['question_type_global', 'question_single_statement']
what are the stores?	'miles market', 'giantway'	['question_type_global', 'question_single_statement']
[Camisole] is a [Clothing]
what stores near [Sherwood Drive] have an ongoing sale on [meat]?	'giantway'	['question_type_global', 'question_three_hop_statement']
show me all of the stores on [Sherwood Drive]	'miles market', 'giantway'	['question_type_global', 'question_single_statement']
is there a sale on [Ham] anywhere?	'giantway'	['question_type_local']
[this clothing] is on sale at [miles market]
what items are on sale at [this store]?	'clay pot', 'Camisole'	['question_type_local']
what are the stores on [Sherwood Drive]?	'miles market', 'giantway'	['question_type_global', 'question_single_statement']
show me all department stores near [Sherwood Drive] that have a sale	'miles market'	['question_type_global', 'question_two_hop_statement']
show me all supermarkets on [Sherwood Drive] that currently have a sale	'giantway'	['question_type_global', 'question_two_hop_statement']
[Water chestnut] and [Carrot] are both different kinds of [Vegetables]
what are the department stores on [Sherwood Drive]?	'miles market'	['question_type_global', 'question_single_statement']
what stores on [Sherwood Drive] have a sale on [gifts]?	'miles market'	['question_type_global', 'question_three_hop_statement']
what are the supermarkets on [Sherwood Drive]?	'giantway'	['question_type_global', 'question_single_statement']
what stores are there on [Sherwood Drive]?	'miles market', 'giantway'	['question_type_global', 'question_single_statement']
what department stores near [Sherwood Drive] have an ongoing sale?	'miles market'	['question_type_global', 'question_two_hop_statement']
what is on sale at [miles market]?	'clay pot', 'Camisole'	['question_type_local']
what are the stores?	'miles market', 'giantway'	['question_type_global', 'question_single_statement']
show me all supermarkets near [Sherwood Drive] that have a sale	'giantway'	['question_type_global', 'question_two_hop_statement']
show me all of the supermarkets on [Sherwood Drive]	'giantway'	['question_type_global', 'question_single_statement']
show me all stores on [Sherwood Drive] that currently have a sale on [Camisole]	'miles market'	['question_type_global', 'question_two_hop_statement']
what stores near [Sherwood Drive] have an ongoing sale?	'miles market', 'giantway'	['question_type_global', 'question_two_hop_statement']
what stores are there on [Sherwood Drive]?	'miles market', 'giantway'	['question_type_global', 'question_single_statement']
what neighborhood is [Sherwood Drive] in?	'Downtown'	['question_type_local']
what department stores on [Sherwood Drive] have a sale?	'miles market'	['question_type_global', 'question_two_hop_statement']
show me all department stores on [Sherwood Drive] that currently have a sale	'miles market'	['question_type_global', 'question_two_hop_statement']
what stores near [Sherwood Drive] have an ongoing sale on [gifts]?	'miles market'	['question_type_global', 'question_three_hop_statement']
[I] just got to [Sherwood Drive]
show me all department stores	'miles market'	['question_type_global', 'question_single_statement']
what supermarkets are there on [Sherwood Drive]?	'giantway'	['question_type_global', 'question_single_statement']
what is on sale at [giantway]?	'Turtle', 'Ham'	['question_type_local']
what department stores are there on [Sherwood Drive]?	'miles market'	['question_type_global', 'question_single_statement']
show me all of the department stores	'miles market'	['question_type_global', 'question_single_statement']
is there a store near my location is having a sale on [Camisole]?	'miles market'	['question_type_global', 'question_three_hop_statement']
what neighborhood am I currently in?	'Downtown'	['question_type_local']
what stores on [Sherwood Drive] have a sale?	'miles market', 'giantway'	['question_type_global', 'question_two_hop_statement']
show me all stores	'miles market', 'giantway'	['question_type_global', 'question_single_statement']
[Goose] is a type of [Meat]
is there a store near my location is having a sale on [meat]?	'giantway'	['question_type_global', 'question_four_hop_statement']
[apricot] and [lemon] are types of [Fruit]
what stores near [Sherwood Drive] have an ongoing sale on [gifts]?	'miles market'	['question_type_global', 'question_three_hop_statement']
is there a store nearby with a sale on [clothing] going on right now?	'miles market'	['question_type_global', 'question_four_hop_statement']
what stores on [Sherwood Drive] have a sale on [clothing]?	'miles market'	['question_type_global', 'question_three_hop_statement']
i absolutely must not forget to get [Camisole] for [mandy's birthday]
what supermarkets are there on [Sherwood Drive]?	'giantway'	['question_type_global', 'question_single_statement']
show me all department stores	'miles market'	['question_type_global', 'question_single_statement']
is there anything on sale at a store nearby?	'clay pot', 'Turtle', 'Ham', 'Camisole'	['question_type_global', 'question_three_hop_statement']
is there any [clothing] that I have to buy currently are on sale?	'Camisole'	['question_type_global', 'question_three_hop_statement']
what department stores are there	'miles market'	['question_type_global', 'question_single_statement']
is there a store near my location is having a sale?	'giantway', 'miles market'	['question_type_global', 'question_three_hop_statement']
what department stores are there on [Sherwood Drive]?	'miles market'	['question_type_global', 'question_single_statement']
is there a store nearby with a sale on [gifts] going on right now?	'miles market'	['question_type_global', 'question_four_hop_statement']
please remind me to buy [coasters] for [mandy's birthday]
remove [Camisole] and [coasters] from my shopping list for [that event]
show me all of the supermarkets on [Sherwood Drive]	'giantway'	['question_type_global', 'question_single_statement']
does any store nearby have [meat] on sale?	'giantway'	['question_type_global', 'question_four_hop_statement']
what stores near [Sherwood Drive] have an ongoing sale?	'miles market', 'giantway'	['question_type_global', 'question_two_hop_statement']
what do stores near me are have a sale on?	'clay pot', 'Turtle', 'Ham', 'Camisole'	['question_type_global', 'question_three_hop_statement']
i often shop at [kohl's], which is my local [department store]
[mp3 player], [lamp shade] and [this gift] are on sale at [kohl's]
what is on sale at [kohl's]?	'mp3 player', 'coasters', 'lamp shade'	['question_type_local']
what items are on sale at nearby stores?	'clay pot', 'Turtle', 'Ham', 'Camisole'	['question_type_global', 'question_three_hop_statement']
what stores near [Sherwood Drive] have an ongoing sale on [Turtle]?	'giantway'	['question_type_global', 'question_two_hop_statement']
show me all stores near [Sherwood Drive] that have a sale	'miles market', 'giantway'	['question_type_global', 'question_two_hop_statement']
[giantway] has [Duck] and [Pork] on sale!
what neighborhood am I in?	'Downtown'	['question_type_local']
is there a store near my location is having a sale?	'giantway', 'miles market'	['question_type_global', 'question_three_hop_statement']
what stores near [Sherwood Drive] have an ongoing sale on [clothing]?	'miles market'	['question_type_global', 'question_three_hop_statement']
are there any stores nearby that have a sale on [gifts]?	'miles market'	['question_type_global', 'question_four_hop_statement']
Where is [coasters] on sale?	"kohl's"	['question_type_local']
is there a store near my location is having a sale on [clothing]?	'miles market'	['question_type_global', 'question_four_hop_statement']
does any store nearby have [Duck] on sale?	'giantway'	['question_type_global', 'question_three_hop_statement']
[Box mangle], [Oil heater] and [Solar water heater] are on sale at [kohl's]
i think this [kohl's] is somewhere on [Sherwood Drive]
what neighborhood am I in?	'Downtown'	['question_type_local']
show me all of the supermarkets	'giantway'	['question_type_global', 'question_single_statement']
what do stores near me are have a sale on?	'mp3 player', 'coasters', 'clay pot', 'Box mangle', 'Oil heater', 'lamp shade', 'Solar water heater', 'Turtle', 'Ham', 'Pork', 'Duck', 'Camisole'	['question_type_global', 'question_three_hop_statement']
what stores near [Sherwood Drive] have an ongoing sale on [Duck]?	'giantway'	['question_type_global', 'question_two_hop_statement']
does any store nearby have [Turtle] on sale?	'giantway'	['question_type_global', 'question_three_hop_statement']
show me all of the department stores	'miles market', "kohl's"	['question_type_global', 'question_single_statement']
what stores near [Sherwood Drive] have an ongoing sale on [meat]?	'giantway'	['question_type_global', 'question_three_hop_statement']
show me all department stores	'miles market', "kohl's"	['question_type_global', 'question_single_statement']
is there a store nearby with a sale on [gifts] going on right now?	"kohl's", 'miles market'	['question_type_global', 'question_four_hop_statement']
is there a store nearby with a sale on [meat] going on right now?	'giantway'	['question_type_global', 'question_four_hop_statement']
what are the stores on [that street]?	'miles market', 'giantway', "kohl's"	['question_type_local']
does any store nearby have [appliances] on sale?	"kohl's"	['question_type_global', 'question_four_hop_statement']
show me all stores near [Sherwood Drive] that have a sale on [meat]	'giantway'	['question_type_global', 'question_three_hop_statement']
what items are on sale at nearby stores?	'mp3 player', 'coasters', 'clay pot', 'Box mangle', 'Oil heater', 'lamp shade', 'Solar water heater', 'Turtle', 'Ham', 'Pork', 'Duck', 'Camisole'	['question_type_global', 'question_three_hop_statement']
what stores on [Sherwood Drive] have a sale on [clothing]?	'miles market'	['question_type_global', 'question_three_hop_statement']
what supermarkets on [Sherwood Drive] have a sale?	'giantway'	['question_type_global', 'question_two_hop_statement']
show me all stores on [Sherwood Drive] that currently have a sale on [appliances]	"kohl's"	['question_type_global', 'question_three_hop_statement']
show me all of the department stores	'miles market', "kohl's"	['question_type_global', 'question_single_statement']
show me all department stores near [Sherwood Drive] that have a sale	'miles market', "kohl's"	['question_type_global', 'question_two_hop_statement']
show me all stores near [Sherwood Drive] that have a sale on [clothing]	'miles market'	['question_type_global', 'question_three_hop_statement']
show me all stores near [Sherwood Drive] that have a sale on [appliances]	"kohl's"	['question_type_global', 'question_three_hop_statement']
[4th Street West] is on the outskirts of [Elliott]
what neighborhood is [Sherwood Drive] in?	'Downtown'	['question_type_local']
what stores near [Sherwood Drive] have an ongoing sale on [clothing]?	'miles market'	['question_type_global', 'question_three_hop_statement']
what items are on sale at [miles market]?	'clay pot', 'Camisole'	['question_type_local']
what stores on [Sherwood Drive] have a sale on [Duck]?	'giantway'	['question_type_global', 'question_two_hop_statement']
does any store nearby have anything on sale?	'giantway', "kohl's", 'miles market'	['question_type_global', 'question_three_hop_statement']
what stores on [Sherwood Drive] have a sale?	'miles market', 'giantway', "kohl's"	['question_type_global', 'question_two_hop_statement']
what are the stores on [Sherwood Drive]?	'miles market', 'giantway', "kohl's"	['question_type_local']
does any store nearby have [meat] on sale?	'giantway'	['question_type_global', 'question_four_hop_statement']
is there a store near my location is having a sale on [meat]?	'giantway'	['question_type_global', 'question_four_hop_statement']
is there a store near my location is having a sale on [clay pot]?	'miles market'	['question_type_global', 'question_three_hop_statement']
show me all department stores	'miles market', "kohl's"	['question_type_global', 'question_single_statement']
what stores are there on [Sherwood Drive]?	'miles market', 'giantway', "kohl's"	['question_type_global', 'question_single_statement']
[Shirt] and [Hat] are both examples of [Clothing]
Where is [clay pot] on sale?	'miles market'	['question_type_local']
what do stores near me have on sale?	'mp3 player', 'coasters', 'clay pot', 'Box mangle', 'Oil heater', 'lamp shade', 'Solar water heater', 'Turtle', 'Ham', 'Pork', 'Duck', 'Camisole'	['question_type_global', 'question_three_hop_statement']
what items are on sale at [kohl's]?	'mp3 player', 'coasters', 'Box mangle', 'Oil heater', 'lamp shade', 'Solar water heater'	['question_type_local']
what stores on [Sherwood Drive] have a sale on [meat]?	'giantway'	['question_type_global', 'question_three_hop_statement']
Where is [mp3 player] on sale?	"kohl's"	['question_type_local']
what stores on [Sherwood Drive] have a sale on [gifts]?	'miles market', "kohl's"	['question_type_global', 'question_three_hop_statement']
does any store nearby have [meat] on sale?	'giantway'	['question_type_global', 'question_four_hop_statement']
what stores are there on [Sherwood Drive]?	'miles market', 'giantway', "kohl's"	['question_type_global', 'question_single_statement']
what department stores are there	'miles market', "kohl's"	['question_type_global', 'question_single_statement']
what stores near [Sherwood Drive] have an ongoing sale on [meat]?	'giantway'	['question_type_global', 'question_three_hop_statement']
is there a store near my location is having a sale on [appliances]?	"kohl's"	['question_type_global', 'question_four_hop_statement']
show me all supermarkets near [Sherwood Drive]	'giantway'	['question_type_global', 'question_single_statement']
is there a store near my location is having a sale on [meat]?	'giantway'	['question_type_global', 'question_four_hop_statement']
what neighborhood is [Sherwood Drive] in?	'Downtown'	['question_type_local']
Where is [Box mangle] on sale?	"kohl's"	['question_type_local']
what stores on [Sherwood Drive] have a sale on [gifts]?	'miles market', "kohl's"	['question_type_global', 'question_three_hop_statement']
show me all of the supermarkets	'giantway'	['question_type_global', 'question_single_statement']
what stores on [Sherwood Drive] have a sale on [clothing]?	'miles market'	['question_type_global', 'question_three_hop_statement']
what stores near [Sherwood Drive] have an ongoing sale on [appliances]?	"kohl's"	['question_type_global', 'question_three_hop_statement']
show me all supermarkets on [Sherwood Drive] that currently have a sale	'giantway'	['question_type_global', 'question_two_hop_statement']
show me all stores near [Sherwood Drive]	'miles market', 'giantway', "kohl's"	['question_type_global', 'question_single_statement']
what's currently on sale at [giantway]?	'Turtle', 'Ham', 'Pork', 'Duck'	['question_type_local']
is there a store near my location is having a sale on [clothing]?	'miles market'	['question_type_global', 'question_four_hop_statement']
is there a store nearby with a sale on [clothing] going on right now?	'miles market'	['question_type_global', 'question_four_hop_statement']
does any store nearby have [gifts] on sale?	"kohl's", 'miles market'	['question_type_global', 'question_four_hop_statement']
what stores near [Sherwood Drive] have an ongoing sale on [meat]?	'giantway'	['question_type_global', 'question_three_hop_statement']
are there any stores nearby that have a sale on [meat]?	'giantway'	['question_type_global', 'question_four_hop_statement']
are there any stores nearby that have a sale on [clay pot]?	'miles market'	['question_type_global', 'question_three_hop_statement']
Where is [Oil heater] on sale?	"kohl's"	['question_type_local']
[Country Club Road] is located in the [Downtown] neighborhood
i often shop at [aldi], which is my local [supermarket]
show me all department stores near [Sherwood Drive] that have a sale	'miles market', "kohl's"	['question_type_global', 'question_two_hop_statement']
[Beef], [Pork] and [Ham] are on sale at [aldi]
this particular [aldi] is located on [Sherwood Drive]
what items are on sale at [that store]?	'Ham', 'Pork', 'Beef'	['question_type_local']
what supermarkets on [Sherwood Drive] have a sale?	'giantway', 'aldi'	['question_type_global', 'question_two_hop_statement']
does any store nearby have [clothing] on sale?	'miles market'	['question_type_global', 'question_four_hop_statement']
what are the stores on [Sherwood Drive]?	'miles market', 'giantway', "kohl's", 'aldi'	['question_type_global', 'question_single_statement']
what is on sale at [this store]?	'Ham', 'Pork', 'Beef'	['question_type_local']
[miles market] has [Oil heater], [Solar water heater] and [Box mangle] on sale!
what neighborhood is [Country Club Road] located in?	'Downtown'	['question_type_local']
show me all department stores near [Sherwood Drive]	'miles market', "kohl's"	['question_type_global', 'question_single_statement']
does any store nearby have anything on sale?	'aldi', 'giantway', "kohl's", 'miles market'	['question_type_global', 'question_three_hop_statement']
[apricot] and [lemon] are on sale at [aldi]
[aldi] doesn't have [lemon] and [Beef] on sale anymore!
what neighborhood is [4th Street West] located in?	'Elliott'	['question_type_local']
show me all stores on [Sherwood Drive] that currently have a sale on [meat]	'giantway', 'aldi'	['question_type_global', 'question_three_hop_statement']
is there a store near my location is having a sale on [gifts]?	"kohl's", 'miles market'	['question_type_global', 'question_four_hop_statement']
show me all of the supermarkets	'giantway', 'aldi'	['question_type_global', 'question_single_statement']
there is a [department store] called [hollister] on [Sherwood Drive]
what stores on [Sherwood Drive] have a sale on [fruit]?	'aldi'	['question_type_global', 'question_three_hop_statement']
does any store nearby have [gifts] on sale?	"kohl's", 'miles market'	['question_type_global', 'question_four_hop_statement']
show me all department stores near [Sherwood Drive] that have a sale	'miles market', "kohl's"	['question_type_global', 'question_two_hop_statement']
what are the department stores?	'miles market', "kohl's", 'hollister'	['question_type_global', 'question_single_statement']
what items are on sale at [kohl's]?	'mp3 player', 'coasters', 'Box mangle', 'Oil heater', 'lamp shade', 'Solar water heater'	['question_type_local']
show me all of the stores on [Sherwood Drive]	'miles market', 'giantway', "kohl's", 'aldi', 'hollister'	['question_type_global', 'question_single_statement']
what stores on [Sherwood Drive] have a sale on [meat]?	'giantway', 'aldi'	['question_type_global', 'question_three_hop_statement']
does any store nearby have [fruit] on sale?	'aldi'	['question_type_global', 'question_four_hop_statement']
what stores near [Sherwood Drive] have an ongoing sale on [apricot]?	'aldi'	['question_type_global', 'question_two_hop_statement']
is there a store nearby with a sale on [fruit] going on right now?	'aldi'	['question_type_global', 'question_four_hop_statement']
Where is [Solar water heater] on sale?	'miles market', "kohl's"	['question_type_local']
i often shop at [joseph magnin], which is my local [department store]
this specific [joseph magnin] is on [Country Club Road]
is there a store near my location is having a sale on [lamp shade]?	"kohl's"	['question_type_global', 'question_three_hop_statement']
show me all stores near [Sherwood Drive] that have a sale on [clothing]	'miles market'	['question_type_global', 'question_three_hop_statement']
is there anything on sale at a store nearby?	'mp3 player', 'coasters', 'clay pot', 'Box mangle', 'Oil heater', 'lamp shade', 'Solar water heater', 'Turtle', 'Ham', 'Pork', 'Duck', 'Camisole', 'apricot'	['question_type_global', 'question_three_hop_statement']
Where is [Camisole] on sale?	'miles market'	['question_type_local']
what are the stores on [that street]?	'joseph magnin'	['question_type_local']
is there a store nearby with a sale on [clothing] going on right now?	'miles market'	['question_type_global', 'question_four_hop_statement']
show me all of the supermarkets on [Sherwood Drive]	'giantway', 'aldi'	['question_type_global', 'question_single_statement']
what stores are there on [Sherwood Drive]?	'miles market', 'giantway', "kohl's", 'aldi', 'hollister'	['question_type_global', 'question_single_statement']
what is on sale near my current location?	'mp3 player', 'coasters', 'clay pot', 'Box mangle', 'Oil heater', 'lamp shade', 'Solar water heater', 'Turtle', 'Ham', 'Pork', 'Duck', 'Camisole', 'apricot'	['question_type_global', 'question_three_hop_statement']
are there any stores nearby that have a sale on [clay pot]?	'miles market'	['question_type_global', 'question_three_hop_statement']
show me all supermarkets near [Sherwood Drive] that have a sale	'giantway', 'aldi'	['question_type_global', 'question_two_hop_statement']
what is on sale at [miles market]?	'clay pot', 'Box mangle', 'Oil heater', 'Solar water heater', 'Camisole'	['question_type_local']
what supermarkets are there?	'giantway', 'aldi'	['question_type_global', 'question_single_statement']
what stores on [Sherwood Drive] have a sale on [gifts]?	'miles market', "kohl's"	['question_type_global', 'question_three_hop_statement']
[monitor], [clay pot] and [coasters] are all on sale at [this store]
show me all department stores on [Country Club Road] that currently have a sale	'joseph magnin'	['question_type_global', 'question_two_hop_statement']
what stores are there that I taught you?	'miles market', 'giantway', "kohl's", 'aldi', 'hollister', 'joseph magnin'	['question_type_global', 'question_single_statement']
Where is [mp3 player] on sale?	"kohl's"	['question_type_local']
[Tracksuit], [Belt] and [Briefs] are all types of [Clothing]
what is on sale at [aldi]?	'Ham', 'Pork', 'apricot'	['question_type_local']
what are the supermarkets?	'giantway', 'aldi'	['question_type_global', 'question_single_statement']
what are the stores?	'miles market', 'giantway', "kohl's", 'aldi', 'hollister', 'joseph magnin'	['question_type_global', 'question_single_statement']
show me all of the supermarkets	'giantway', 'aldi'	['question_type_global', 'question_single_statement']
is there a store nearby with a sale on [meat] going on right now?	'aldi', 'giantway'	['question_type_global', 'question_four_hop_statement']
what stores on [Sherwood Drive] have a sale on [appliances]?	'miles market', "kohl's"	['question_type_global', 'question_three_hop_statement']
what stores on [Sherwood Drive] have a sale on [meat]?	'giantway', 'aldi'	['question_type_global', 'question_three_hop_statement']
what stores near [Sherwood Drive] have an ongoing sale on [gifts]?	'miles market', "kohl's"	['question_type_global', 'question_three_hop_statement']
does any store nearby have [clay pot] on sale?	'miles market'	['question_type_global', 'question_three_hop_statement']
what stores are there on [Sherwood Drive]?	'miles market', 'giantway', "kohl's", 'aldi', 'hollister'	['question_type_global', 'question_single_statement']
show me all stores near [Sherwood Drive] that have a sale on [gifts]	'miles market', "kohl's"	['question_type_global', 'question_three_hop_statement']
what do stores near me have on sale?	'mp3 player', 'coasters', 'clay pot', 'Box mangle', 'Oil heater', 'lamp shade', 'Solar water heater', 'Turtle', 'Ham', 'Pork', 'Duck', 'Camisole', 'apricot'	['question_type_global', 'question_three_hop_statement']
[mp3 player], [television] and [watch] are on sale at [miles market]
what's currently on sale at [miles market]?	'mp3 player', 'clay pot', 'Box mangle', 'Oil heater', 'watch', 'television', 'Solar water heater', 'Camisole'	['question_type_local']
what supermarkets are there?	'giantway', 'aldi'	['question_type_global', 'question_single_statement']
what are the stores on [Country Club Road]?	'joseph magnin'	['question_type_global', 'question_single_statement']
show me all of the department stores	'miles market', "kohl's", 'hollister', 'joseph magnin'	['question_type_global', 'question_single_statement']
show me all stores near [Sherwood Drive] that have a sale	'miles market', 'giantway', "kohl's", 'aldi'	['question_type_global', 'question_two_hop_statement']
does any store nearby have [fruit] on sale?	'aldi'	['question_type_global', 'question_four_hop_statement']
what is on sale at [joseph magnin]?	'monitor', 'coasters', 'clay pot'	['question_type_local']
what are the stores on [Country Club Road]?	'joseph magnin'	['question_type_local']
show me all department stores	'miles market', "kohl's", 'hollister', 'joseph magnin'	['question_type_global', 'question_single_statement']
[jujube], [clementine] and [date] are [Fruit]
is there a store nearby with a sale on [appliances] going on right now?	"kohl's", 'miles market'	['question_type_global', 'question_four_hop_statement']
does any store nearby have [clothing] on sale?	'miles market'	['question_type_global', 'question_four_hop_statement']
show me all supermarkets near [Sherwood Drive] that have a sale	'giantway', 'aldi'	['question_type_global', 'question_two_hop_statement']
is there a store near my location is having a sale on [Duck]?	'giantway'	['question_type_global', 'question_three_hop_statement']
show me all of the department stores on [Sherwood Drive]	'miles market', "kohl's", 'hollister'	['question_type_global', 'question_single_statement']
[lamp] is a kind of [Gift]
does any store nearby have [meat] on sale?	'aldi', 'giantway'	['question_type_global', 'question_four_hop_statement']
show me all supermarkets that i tought you	'giantway', 'aldi'	['question_type_global', 'question_single_statement']
what stores are on [Sherwood Drive]?	'miles market', 'giantway', 'hollister', "kohl's", 'aldi'	['question_type_local']
does any store nearby have [appliances] on sale?	"kohl's", 'miles market'	['question_type_global', 'question_four_hop_statement']
does any store nearby have [watch] on sale?	'miles market'	['question_type_global', 'question_three_hop_statement']
what's currently on sale at [aldi]?	'Ham', 'Pork', 'apricot'	['question_type_local']
what stores near [Sherwood Drive] have an ongoing sale on [appliances]?	'miles market', "kohl's"	['question_type_global', 'question_three_hop_statement']
show me all department stores on [Sherwood Drive] that currently have a sale	'miles market', "kohl's"	['question_type_global', 'question_two_hop_statement']
what are the stores on [Sherwood Drive]?	'miles market', 'giantway', "kohl's", 'aldi', 'hollister'	['question_type_global', 'question_single_statement']
are there any stores nearby that have a sale on [lamp shade]?	"kohl's"	['question_type_global', 'question_three_hop_statement']
What stores is [monitor] on sale at	'joseph magnin'	['question_type_local']
does any store nearby have [lamp shade] on sale?	"kohl's"	['question_type_global', 'question_three_hop_statement']
show me all of the stores on [Sherwood Drive]	'miles market', 'giantway', "kohl's", 'aldi', 'hollister'	['question_type_global', 'question_single_statement']
is there a sale on [Pork] anywhere?	'giantway', 'aldi'	['question_type_local']
what stores near [Sherwood Drive] have an ongoing sale on [fruit]?	'aldi'	['question_type_global', 'question_three_hop_statement']
what stores on [Country Club Road] have a sale?	'joseph magnin'	['question_type_global', 'question_two_hop_statement']
what stores near [Sherwood Drive] have an ongoing sale on [clothing]?	'miles market'	['question_type_global', 'question_three_hop_statement']
what department stores on [Sherwood Drive] have a sale?	'miles market', "kohl's"	['question_type_global', 'question_two_hop_statement']
What stores is [Turtle] on sale at	'giantway'	['question_type_local']
show me all stores near [Country Club Road] that have a sale	'joseph magnin'	['question_type_global', 'question_two_hop_statement']
is there a store near my location is having a sale on [clothing]?	'miles market'	['question_type_global', 'question_four_hop_statement']
show me all supermarkets near [Sherwood Drive] that have a sale	'giantway', 'aldi'	['question_type_global', 'question_two_hop_statement']
show me all of the supermarkets on [Sherwood Drive]	'giantway', 'aldi'	['question_type_global', 'question_single_statement']
is there a store near my location is having a sale?	'aldi', 'giantway', "kohl's", 'miles market'	['question_type_global', 'question_three_hop_statement']
is there a sale on [Pork] anywhere?	'giantway', 'aldi'	['question_type_local']
What stores is [watch] on sale at	'miles market'	['question_type_local']
show me all of the stores on [Sherwood Drive]	'miles market', 'giantway', "kohl's", 'aldi', 'hollister'	['question_type_global', 'question_single_statement']
are there any stores nearby that have a sale on [meat]?	'aldi', 'giantway'	['question_type_global', 'question_four_hop_statement']
show me all department stores	'miles market', "kohl's", 'hollister', 'joseph magnin'	['question_type_global', 'question_single_statement']
what stores on [Sherwood Drive] have a sale on [Camisole]?	'miles market'	['question_type_global', 'question_two_hop_statement']
show me all stores on [Country Club Road] that currently have a sale	'joseph magnin'	['question_type_global', 'question_two_hop_statement']
show me all supermarkets that i tought you	'giantway', 'aldi'	['question_type_global', 'question_single_statement']
what is on sale at [joseph magnin]?	'monitor', 'coasters', 'clay pot'	['question_type_local']
what stores on [Sherwood Drive] have a sale on [gifts]?	'miles market', "kohl's"	['question_type_global', 'question_three_hop_statement']
please remind me to buy [Solar water heater] for [mandy's birthday]
just purchases [that item] for [this event]
what things did i get for [that event]	'socks', 'monitor', 'mp3 player', 'coasters', 'phone', 'clay pot', 'Box mangle', 'Oil heater', 'watch', 'Solar water heater', 'Camisole'	['question_type_local']
what do stores near me have on sale?	'mp3 player', 'coasters', 'clay pot', 'Box mangle', 'Oil heater', 'lamp shade', 'watch', 'television', 'Solar water heater', 'Turtle', 'Ham', 'Pork', 'Duck', 'Camisole', 'apricot'	['question_type_global', 'question_three_hop_statement']
is there a store near my location is having a sale on [gifts]?	"kohl's", 'miles market'	['question_type_global', 'question_four_hop_statement']
what stores are located on [Sherwood Drive]?	'miles market', 'giantway', 'hollister', "kohl's", 'aldi'	['question_type_local']
does any store nearby have anything on sale?	'aldi', 'giantway', "kohl's", 'miles market'	['question_type_global', 'question_three_hop_statement']
is there a sale on [this thing] anywhere?	'miles market', "kohl's"	['question_type_local']
there is a [department store] called [miles market] that I shop in pretty often
[Oil heater], [Solar water heater] and [Box mangle] are all on sale at [miles market]
this specific [miles market that I last mentioned] is on [4th Street West]
what is on sale at [that department store]?	'Box mangle', 'Oil heater', 'Solar water heater'	['question_type_local']
show me all stores near [Sherwood Drive] that have a sale on [gifts]	'miles market', "kohl's"	['question_type_global', 'question_three_hop_statement']
what are the stores on [4th Street West]?	'miles market'	['question_type_global', 'question_single_statement']
[14th Street] is located in the [East Hills] neighborhood
what neighborhood is [4th Street West] located in?	'Elliott'	['question_type_local']
what are the stores?	'miles market', 'giantway', "kohl's", 'aldi', 'hollister', 'joseph magnin'	['question_type_global', 'question_single_statement']
does any store nearby have [gifts] on sale?	"kohl's", 'miles market'	['question_type_global', 'question_four_hop_statement']
is there a store near my location is having a sale on [appliances]?	"kohl's", 'miles market'	['question_type_global', 'question_four_hop_statement']
[Blouse] is a type of [Clothing]
what is on sale at [miles market on 4th Street West]?	'Box mangle', 'Oil heater', 'Solar water heater'	['question_type_local']
what is on sale at [kohl's]?	'mp3 player', 'coasters', 'Box mangle', 'Oil heater', 'lamp shade', 'Solar water heater'	['question_type_local']
show me all department stores on [4th Street West] that currently have a sale	'miles market'	['question_type_global', 'question_two_hop_statement']
are there any stores nearby that have a sale on [clothing]?	'miles market'	['question_type_global', 'question_four_hop_statement']
are there any stores nearby that have a sale?	'aldi', 'giantway', "kohl's", 'miles market'	['question_type_global', 'question_three_hop_statement']
what supermarkets on [Sherwood Drive] have a sale?	'giantway', 'aldi'	['question_type_global', 'question_two_hop_statement']
what stores on [Sherwood Drive] have a sale on [meat]?	'giantway', 'aldi'	['question_type_global', 'question_three_hop_statement']
i absolutely must not forget to get both [Hat] and [Belt] for [mandy's birthday]
what do I need for [mandy's birthday]?	'Hat', 'Belt'	['question_type_local']
does any store nearby have [clothing] on sale?	'miles market'	['question_type_global', 'question_four_hop_statement']
is there a store near my location is having a sale on [fruit]?	'aldi'	['question_type_global', 'question_four_hop_statement']
i just got [Hat] for [mandy's birthday]
what did i remove from [mandy's birthday]?	'socks', 'monitor', 'mp3 player', 'coasters', 'phone', 'clay pot', 'Box mangle', 'Oil heater', 'watch', 'Solar water heater', 'Camisole', 'Hat'	['question_type_local']
is there a store nearby with a sale on [gifts] going on right now?	"kohl's", 'miles market'	['question_type_global', 'question_four_hop_statement']
[Window fan], [Automatic Rotimaker] and [Attic fan] are kinds of [Appliance]
what stores are located on [Country Club Road]?	'joseph magnin'	['question_type_local']
are there any stores nearby that have a sale on [meat]?	'aldi', 'giantway'	['question_type_global', 'question_four_hop_statement']
what items are on sale at nearby stores?	'mp3 player', 'coasters', 'clay pot', 'Box mangle', 'Oil heater', 'lamp shade', 'watch', 'television', 'Solar water heater', 'Turtle', 'Ham', 'Pork', 'Duck', 'Camisole', 'apricot'	['question_type_global', 'question_three_hop_statement']
what items are on sale at [joseph magnin]?	'monitor', 'coasters', 'clay pot'	['question_type_local']
show me all department stores near [Country Club Road]	'joseph magnin'	['question_type_global', 'question_single_statement']
Do I need to buy any [clothing]?	'Belt'	['question_type_global', 'question_two_hop_statement']
does any store nearby have [gifts] on sale?	"kohl's", 'miles market'	['question_type_global', 'question_four_hop_statement']
[lamp shade] is on sale at [joseph magnin]
show me all stores on [Sherwood Drive] that currently have a sale on [fruit]	'aldi'	['question_type_global', 'question_three_hop_statement']
show me all department stores near [Sherwood Drive]	'miles market', "kohl's", 'hollister'	['question_type_global', 'question_single_statement']
[aldi] has [Kangaroo], [Beef] and [Goose] on sale!
[Beef], [Ham] and [apricot] stopped being on sale at [aldi]
what items are on sale at [aldi]?	'Kangaroo', 'Pork', 'Goose'	['question_type_local']
show me all stores near [Country Club Road] that have a sale	'joseph magnin'	['question_type_global', 'question_two_hop_statement']
are there any stores nearby that have a sale?	'aldi', 'giantway', "kohl's", 'miles market'	['question_type_global', 'question_three_hop_statement']
is there a store near my location is having a sale?	'aldi', 'giantway', "kohl's", 'miles market'	['question_type_global', 'question_three_hop_statement']
is there a store nearby with a sale going on right now?	'aldi', 'giantway', "kohl's", 'miles market'	['question_type_global', 'question_three_hop_statement']
what stores are there that I taught you?	'miles market', 'giantway', "kohl's", 'aldi', 'hollister', 'joseph magnin'	['question_type_global', 'question_single_statement']
what stores near [4th Street West] have an ongoing sale on [appliances]?	'miles market'	['question_type_global', 'question_three_hop_statement']
what are the things that i need to get?	'Belt'	['question_type_global', 'question_single_statement']
does any store nearby have anything on sale?	'aldi', 'giantway', "kohl's", 'miles market'	['question_type_global', 'question_three_hop_statement']
is there a store nearby with a sale on [Solar water heater] going on right now?	"kohl's", 'miles market'	['question_type_global', 'question_three_hop_statement']
show me all supermarkets near [Sherwood Drive]	'giantway', 'aldi'	['question_type_global', 'question_single_statement']
what are the stores on [Sherwood Drive]?	'miles market', 'giantway', 'hollister', "kohl's", 'aldi'	['question_type_local']
does any store nearby have [clothing] on sale?	'miles market'	['question_type_global', 'question_four_hop_statement']
there is a [supermarket] called [giantway] that I shop in pretty often
show me all supermarkets that i tought you	'giantway', 'aldi'	['question_type_global', 'question_single_statement']
what supermarkets are there?	'giantway', 'aldi'	['question_type_global', 'question_single_statement']
Where is [watch] on sale?	'miles market'	['question_type_local']
show me all stores near [Country Club Road] that have a sale on [gifts]	'joseph magnin'	['question_type_global', 'question_three_hop_statement']
what stores near [Sherwood Drive] have an ongoing sale on [gifts]?	'miles market', "kohl's"	['question_type_global', 'question_three_hop_statement']
what event do I need to buy [Belt] for	"mandy's birthday"	['question_type_local']
is there a store near my location is having a sale on [meat]?	'aldi', 'giantway'	['question_type_global', 'question_four_hop_statement']
show me all of the supermarkets on [Sherwood Drive]	'giantway', 'aldi'	['question_type_global', 'question_single_statement']
what stores are there that I taught you?	'miles market', 'giantway', "kohl's", 'aldi', 'hollister', 'joseph magnin'	['question_type_global', 'question_single_statement']
are there any stores nearby that have a sale on [Box mangle]?	"kohl's", 'miles market'	['question_type_global', 'question_three_hop_statement']
show me all department stores near [Country Club Road]	'joseph magnin'	['question_type_global', 'question_single_statement']
is there a sale on [Oil heater] anywhere?	'miles market', "kohl's", 'miles market'	['question_type_local']
what stores near [Sherwood Drive] have an ongoing sale on [appliances]?	'miles market', "kohl's"	['question_type_global', 'question_three_hop_statement']
is there a sale on [mp3 player] anywhere?	'miles market', "kohl's"	['question_type_local']
does any store nearby have [lamp shade] on sale?	"kohl's"	['question_type_global', 'question_three_hop_statement']
what department stores are there	'miles market', "kohl's", 'hollister', 'joseph magnin'	['question_type_global', 'question_single_statement']
i think this [this store] is somewhere on [4th Street West]
are there any stores nearby that have a sale on [gifts]?	"kohl's", 'miles market'	['question_type_global', 'question_four_hop_statement']
what neighborhood am I currently in?	'Downtown'	['question_type_local']
what are the department stores on [Sherwood Drive]?	'miles market', "kohl's", 'hollister'	['question_type_global', 'question_single_statement']
what supermarkets near [Sherwood Drive] have an ongoing sale?	'giantway', 'aldi'	['question_type_global', 'question_two_hop_statement']
are there any stores nearby that have a sale on [coasters]?	"kohl's"	['question_type_global', 'question_three_hop_statement']
what supermarkets are there?	'giantway', 'aldi'	['question_type_global', 'question_single_statement']
show me all stores near [Country Club Road]	'joseph magnin'	['question_type_global', 'question_single_statement']
what are the stores?	'miles market', 'giantway', "kohl's", 'aldi', 'hollister', 'joseph magnin'	['question_type_global', 'question_single_statement']
show me all of the supermarkets on [4th Street West]	'giantway'	['question_type_global', 'question_single_statement']
what are the stores on [Country Club Road]?	'joseph magnin'	['question_type_global', 'question_single_statement']
what stores near [4th Street West] have an ongoing sale?	'miles market'	['question_type_global', 'question_two_hop_statement']
[kohl's] is a [department store]
[Window fan], [Automatic Rotimaker] and [Attic fan] are on sale at [this store]
does any store nearby have anything on sale?	'aldi', 'giantway', "kohl's", 'miles market'	['question_type_global', 'question_three_hop_statement']
what stores on [Sherwood Drive] have a sale on [gifts]?	'miles market', "kohl's"	['question_type_global', 'question_three_hop_statement']
what department stores near [4th Street West] have an ongoing sale?	'miles market'	['question_type_global', 'question_two_hop_statement']
there is a [department store] called [kohl's] that I shop in pretty often
Where is [Attic fan] on sale?	"kohl's"	['question_type_local']
what supermarkets are there?	'giantway', 'aldi'	['question_type_global', 'question_single_statement']
[boysenberry] is a [Fruit]
[that store] has [purse] and [lamp shade] on sale!
are there any stores nearby that have a sale on [meat]?	'aldi', 'giantway'	['question_type_global', 'question_four_hop_statement']
what stores near [Sherwood Drive] have an ongoing sale?	'miles market', 'giantway', "kohl's", 'aldi'	['question_type_global', 'question_two_hop_statement']
are there any stores nearby that have a sale on [gifts]?	"kohl's", 'miles market'	['question_type_global', 'question_four_hop_statement']
what stores are there that I taught you?	'miles market', 'giantway', "kohl's", 'aldi', 'hollister', 'joseph magnin'	['question_type_global', 'question_single_statement']
are there any stores nearby that have a sale on [appliances]?	"kohl's", 'miles market'	['question_type_global', 'question_four_hop_statement']
what is on sale at [kohl's that I last mentioned]?	'lamp shade', 'purse'	['question_type_local']
what supermarkets are there on [Sherwood Drive]?	'giantway', 'aldi'	['question_type_global', 'question_single_statement']
show me all department stores on [Country Club Road] that currently have a sale	'joseph magnin'	['question_type_global', 'question_two_hop_statement']
[kohl's that I last mentioned] has [phone] on sale!
this specific [this store] is on [14th Street]
show me all supermarkets near [4th Street West]	'giantway'	['question_type_global', 'question_single_statement']
what are the stores on [14th Street]?	"kohl's"	['question_type_global', 'question_single_statement']
i think [Old York Road] is in [Downtown]
what neighborhood is [14th Street] in?	'East Hills'	['question_type_local']
is there a store nearby with a sale going on right now?	'aldi', 'giantway', "kohl's", 'miles market'	['question_type_global', 'question_three_hop_statement']
what stores on [Country Club Road] have a sale?	'joseph magnin'	['question_type_global', 'question_two_hop_statement']
what is on sale at [miles market on Sherwood Drive]?	'mp3 player', 'clay pot', 'Box mangle', 'Oil heater', 'watch', 'television', 'Solar water heater', 'Camisole'	['question_type_local']
does any store nearby have [gifts] on sale?	"kohl's", 'miles market'	['question_type_global', 'question_four_hop_statement']
show me all of the department stores	'miles market', "kohl's", 'hollister', 'joseph magnin'	['question_type_global', 'question_single_statement']
is there a sale on [Camisole] anywhere?	'miles market'	['question_type_local']
are there any [clothing] that i need to get?	'Belt'	['question_type_global', 'question_two_hop_statement']
is there a store nearby with a sale going on right now?	'aldi', 'giantway', "kohl's", 'miles market'	['question_type_global', 'question_three_hop_statement']
Where is [Automatic Rotimaker] on sale?	"kohl's"	['question_type_local']
is there a store near my location is having a sale on [meat]?	'aldi', 'giantway'	['question_type_global', 'question_four_hop_statement']
is there a store near my location is having a sale?	'aldi', 'giantway', "kohl's", 'miles market'	['question_type_global', 'question_three_hop_statement']
show me all supermarkets that i tought you	'giantway', 'aldi'	['question_type_global', 'question_single_statement']
is there a store nearby with a sale on [appliances] going on right now?	"kohl's", 'miles market'	['question_type_global', 'question_four_hop_statement']
what stores are there on [Sherwood Drive]?	'miles market', 'giantway', "kohl's", 'aldi', 'hollister'	['question_type_global', 'question_single_statement']
are there any stores nearby that have a sale on [gifts]?	"kohl's", 'miles market'	['question_type_global', 'question_four_hop_statement']
[Space heater] is a [Appliance]
show me all of the stores	'miles market', 'giantway', "kohl's", 'aldi', 'hollister', 'joseph magnin'	['question_type_global', 'question_single_statement']
there is an upcoming [dinner with ben]
what department stores near [14th Street] have an ongoing sale?	"kohl's"	['question_type_global', 'question_two_hop_statement']
does any store nearby have anything on sale?	'aldi', 'giantway', "kohl's", 'miles market'	['question_type_global', 'question_three_hop_statement']
what stores on [Sherwood Drive] have a sale on [meat]?	'giantway', 'aldi'	['question_type_global', 'question_three_hop_statement']
what do i have on shopping list for [mandy's birthday]?	'Belt'	['question_type_local']
what do stores near me are have a sale on?	'mp3 player', 'coasters', 'clay pot', 'Box mangle', 'Oil heater', 'lamp shade', 'watch', 'Kangaroo', 'television', 'Solar water heater', 'Turtle', 'Ham', 'Pork', 'Duck', 'Camisole', 'Goose'	['question_type_global', 'question_three_hop_statement']
add the following for [that event]: [lemon] and [date]
Do i have any [clothing] on my shopping list?	'Belt'	['question_type_global', 'question_two_hop_statement']
is there a sale on [Attic fan] anywhere?	"kohl's"	['question_type_local']
show me all of the department stores	'miles market', "kohl's", 'hollister', 'joseph magnin'	['question_type_global', 'question_single_statement']
what stores are there on [14th Street]?	"kohl's"	['question_type_global', 'question_single_statement']
what stores on [Sherwood Drive] have a sale on [appliances]?	'miles market', "kohl's"	['question_type_global', 'question_three_hop_statement']
is there a store near my location is having a sale on [meat]?	'aldi', 'giantway'	['question_type_global', 'question_four_hop_statement']
show me all department stores on [4th Street West] that currently have a sale	'miles market'	['question_type_global', 'question_two_hop_statement']
what kind of [clothing] do I need to get?	'Belt'	['question_type_global', 'question_two_hop_statement']
[Black-eyed peas], [Turnip] and [Carrot] are all on sale at [giantway on Sherwood Drive]
what stores near [Sherwood Drive] have an ongoing sale on [vegetables]?	'giantway'	['question_type_global', 'question_three_hop_statement']
show me all stores near [Sherwood Drive] that have a sale on [clothing]	'miles market'	['question_type_global', 'question_three_hop_statement']
is there a store near my location is having a sale?	'aldi', 'giantway', "kohl's", 'miles market'	['question_type_global', 'question_three_hop_statement']
Where is [Oil heater] on sale?	'miles market', "kohl's", 'miles market'	['question_type_local']
what do i need to buy?	'lemon', 'Belt', 'date'	['question_type_global', 'question_single_statement']
what do stores near me have on sale?	'mp3 player', 'coasters', 'clay pot', 'Turnip', 'Black-eyed peas', 'Box mangle', 'Oil heater', 'lamp shade', 'watch', 'Kangaroo', 'television', 'Solar water heater', 'Turtle', 'Ham', 'Pork', 'Duck', 'Camisole', 'Carrot', 'Goose'	['question_type_global', 'question_three_hop_statement']
What stores is [Turnip] on sale at	'giantway'	['question_type_local']
what is my shopping list?	'lemon', 'Belt', 'date'	['question_type_global', 'question_single_statement']
is there a store near my location is having a sale on [vegetables]?	'giantway'	['question_type_global', 'question_four_hop_statement']
is there a store nearby with a sale going on right now?	'aldi', 'giantway', "kohl's", 'miles market'	['question_type_global', 'question_three_hop_statement']
Where is [Carrot] on sale?	'giantway'	['question_type_local']
what are the supermarkets?	'giantway', 'aldi'	['question_type_global', 'question_single_statement']
what do stores near me have on sale?	'mp3 player', 'coasters', 'clay pot', 'Turnip', 'Black-eyed peas', 'Box mangle', 'Oil heater', 'lamp shade', 'watch', 'Kangaroo', 'television', 'Solar water heater', 'Turtle', 'Ham', 'Pork', 'Duck', 'Camisole', 'Carrot', 'Goose'	['question_type_global', 'question_three_hop_statement']
is there a store nearby with a sale on [clothing] going on right now?	'miles market'	['question_type_global', 'question_four_hop_statement']
[miles market that I last mentioned] has [clay pot], [lamp shade] and [television] on sale!
what is on sale at [miles market that I last mentioned]?	'clay pot', 'Box mangle', 'Oil heater', 'lamp shade', 'television', 'Solar water heater'	['question_type_local']
does any store nearby have [appliances] on sale?	"kohl's", 'miles market'	['question_type_global', 'question_four_hop_statement']
what items are on sale at [miles market that I last mentioned]?	'clay pot', 'Box mangle', 'Oil heater', 'lamp shade', 'television', 'Solar water heater'	['question_type_local']
what supermarkets are there on [Sherwood Drive]?	'giantway', 'aldi'	['question_type_global', 'question_single_statement']
What stores is [watch] on sale at	'miles market'	['question_type_local']
show me all supermarkets near [4th Street West]	'giantway'	['question_type_global', 'question_single_statement']
what do i need to buy?	'lemon', 'Belt', 'date'	['question_type_global', 'question_single_statement']
show me all stores near [4th Street West] that have a sale on [gifts]	'miles market'	['question_type_global', 'question_three_hop_statement']
show me all supermarkets that i tought you	'giantway', 'aldi'	['question_type_global', 'question_single_statement']
what supermarkets are there on [4th Street West]?	'giantway'	['question_type_global', 'question_single_statement']
show me all of the supermarkets	'giantway', 'aldi'	['question_type_global', 'question_single_statement']
is there a store nearby with a sale on [meat] going on right now?	'aldi', 'giantway'	['question_type_global', 'question_four_hop_statement']
[Box mangle] is on sale at [kohl's on 14th Street]
i need to get [Shirt] for [mandy's birthday]
is there a store nearby with a sale going on right now?	'aldi', 'giantway', "kohl's", 'miles market'	['question_type_global', 'question_three_hop_statement']
[aldi] has [Beef] and [Turtle] on sale!
what items are on sale at [aldi]?	'Kangaroo', 'Turtle', 'Pork', 'Beef', 'Goose'	['question_type_local']
does any store nearby have [gifts] on sale?	"kohl's", 'miles market'	['question_type_global', 'question_four_hop_statement']
what do stores near me are have a sale on?	'mp3 player', 'coasters', 'clay pot', 'Turnip', 'Black-eyed peas', 'Box mangle', 'Oil heater', 'lamp shade', 'watch', 'Kangaroo', 'television', 'Solar water heater', 'Turtle', 'Ham', 'Pork', 'Beef', 'Duck', 'Camisole', 'Carrot', 'Goose'	['question_type_global', 'question_three_hop_statement']
What stores is [purse] on sale at	"kohl's"	['question_type_local']
what department stores are there on [14th Street]?	"kohl's"	['question_type_global', 'question_single_statement']
make sure to buy [Attic fan] for [mandy's birthday]
what did i remove from [this event]?	'socks', 'monitor', 'mp3 player', 'coasters', 'phone', 'clay pot', 'Box mangle', 'Oil heater', 'watch', 'Solar water heater', 'Camisole', 'Hat'	['question_type_local']
Do i have any [clothing] on my shopping list?	'Shirt', 'Belt'	['question_type_global', 'question_two_hop_statement']
[Cold-pressed juicer], [Steam mop] and [Combo washer dryer] are all good examples of [Appliance]
what is on sale at [joseph magnin]?	'monitor', 'coasters', 'clay pot', 'lamp shade'	['question_type_local']
what stores on [14th Street] have a sale on [appliances]?	"kohl's"	['question_type_global', 'question_three_hop_statement']
is there a store near my location is having a sale on [gifts]?	"kohl's", 'miles market'	['question_type_global', 'question_four_hop_statement']
Do i have any [appliances] on my shopping list?	'Attic fan'	['question_type_global', 'question_two_hop_statement']
what stores on [14th Street] have a sale?	"kohl's"	['question_type_global', 'question_two_hop_statement']
are there any [appliances] on my shopping list that there is a sale on?	'Attic fan'	['question_type_global', 'question_three_hop_statement']
what [clothing] do i need to buy?	'Shirt', 'Belt'	['question_type_global', 'question_two_hop_statement']
what neighborhood is [Sherwood Drive] located in?	'Downtown'	['question_type_local']
is there anything on my list that's on sale somewhere?	'Attic fan'	['question_type_global', 'question_two_hop_statement']
what stores on [Sherwood Drive] have a sale on [clothing]?	'miles market'	['question_type_global', 'question_three_hop_statement']
are there any stores nearby that have a sale on [appliances]?	"kohl's", 'miles market'	['question_type_global', 'question_four_hop_statement']
add the following for [mandy's birthday]: [Automatic Rotimaker] and [Steam mop]
What do I need to buy for [mandy's birthday]?	'Shirt', 'Belt', 'Automatic Rotimaker', 'Attic fan', 'Steam mop'	['question_type_local']
show me all stores near [Sherwood Drive]	'miles market', 'giantway', "kohl's", 'aldi', 'hollister'	['question_type_global', 'question_single_statement']
does any store nearby have [vegetables] on sale?	'giantway'	['question_type_global', 'question_four_hop_statement']
what stores are located on [Sherwood Drive]?	'miles market', 'giantway', 'hollister', "kohl's", 'aldi'	['question_type_local']
show me all of the department stores on [Sherwood Drive]	'miles market', "kohl's", 'hollister'	['question_type_global', 'question_single_statement']
show me all of the supermarkets	'giantway', 'aldi'	['question_type_global', 'question_single_statement']
what are the stores on [Sherwood Drive]?	'miles market', 'giantway', "kohl's", 'aldi', 'hollister'	['question_type_global', 'question_single_statement']
What do I need to buy [Automatic Rotimaker] for?	"mandy's birthday"	['question_type_local']
what stores near [Sherwood Drive] have an ongoing sale on [gifts]?	'miles market', "kohl's"	['question_type_global', 'question_three_hop_statement']
show me all supermarkets near [Sherwood Drive]	'giantway', 'aldi'	['question_type_global', 'question_single_statement']
is there a store near my location is having a sale on [appliances]?	"kohl's", 'miles market'	['question_type_global', 'question_four_hop_statement']
please remind me to buy [Tracksuit] for [mandy's birthday]
i don't need [Steam mop] and [Belt] for [mandy's birthday] anymore
What stores is [clay pot] on sale at	'miles market', 'joseph magnin', 'miles market'	['question_type_local']
what department stores near [Sherwood Drive] have an ongoing sale?	'miles market', "kohl's"	['question_type_global', 'question_two_hop_statement']
are there any stores nearby that have a sale on [Carrot]?	'giantway'	['question_type_global', 'question_three_hop_statement']
