i have [mandy's birthday] coming up
i often shop at [gold circle], which is my local [department store]
what are the stores?	'gold circle'	['question_type_global', 'question_single_statement']
[Beef heart] is a kind of [Meat]
show me all of the department stores	'gold circle'	['question_type_global', 'question_single_statement']
what department stores are there	'gold circle'	['question_type_global', 'question_single_statement']
there is a [supermarket] called [target] that I shop in pretty often
[this thing] is on sale at [this supermarket]
what is on sale at [that supermarket]?	'Beef heart'	['question_type_local']
what's currently on sale at [that supermarket]?	'Beef heart'	['question_type_local']
there is an upcoming [dinner with ben]
is there a sale on [Beef heart] anywhere?	'target'	['question_type_local']
show me all supermarkets that i tought you	'target'	['question_type_global', 'question_single_statement']
is there a sale on [it] anywhere?	'target'	['question_type_local']
what items are on sale at [target]?	'Beef heart'	['question_type_local']
[Beef], [Beef tongue] and [Lamb] are kinds of [Meat]
some example of [Gift] are [monitor] and [headphones]
things i need to buy for [dinner with ben]: [Beef heart] and [Beef tongue]
Do I need to buy any [meat]?	'Beef heart', 'Beef tongue'	['question_type_global', 'question_two_hop_statement']
what are the stores?	'gold circle', 'target'	['question_type_global', 'question_single_statement']
are there any [meat] on my shopping list that there is a sale on?	'Beef heart'	['question_type_global', 'question_three_hop_statement']
Do i have any [meat] on my shopping list?	'Beef heart', 'Beef tongue'	['question_type_global', 'question_two_hop_statement']
i often shop at [quality foods], which is my local [supermarket]
what event do I need to buy [that meat] for	'dinner with ben'	['question_type_local']
there is a [supermarket] called [target] that I shop in pretty often
[target that I last mentioned] has [Lamb], [Beef tongue] and [Beef heart] on sale!
[Cambridge Court] is in [Homewood South]
Where is [that meat] on sale?	'target', 'target'	['question_type_local']
what supermarkets are there?	'target', 'quality foods'	['question_type_global', 'question_single_statement']
i think this [target that I last mentioned] is somewhere on [Cambridge Court]
what is on sale at [that supermarket]?	'Beef heart', 'Beef tongue', 'Lamb'	['question_type_local']
what are the supermarkets?	'target', 'quality foods'	['question_type_global', 'question_single_statement']
what supermarkets are there on [Cambridge Court]?	'target'	['question_type_global', 'question_single_statement']
i absolutely must not forget to get [Lamb] for [dinner with ben]
what event do I need to buy [Beef heart] for	'dinner with ben'	['question_type_local']
what items do I need to get?	'Beef heart', 'Beef tongue', 'Lamb'	['question_type_global', 'question_single_statement']
show me all stores near [Cambridge Court] that have a sale on [Beef tongue]	'target'	['question_type_global', 'question_two_hop_statement']
show me all department stores	'gold circle'	['question_type_global', 'question_single_statement']
show me all stores on [Cambridge Court] that currently have a sale	'target'	['question_type_global', 'question_two_hop_statement']
Where is [Beef heart] on sale?	'target', 'target'	['question_type_local']
what are the things that i need to get?	'Beef heart', 'Beef tongue', 'Lamb'	['question_type_global', 'question_single_statement']
what neighborhood is [Cambridge Court] located in?	'Homewood South'	['question_type_local']
show me all stores near [Cambridge Court]	'target'	['question_type_global', 'question_single_statement']
what do I need for [dinner with ben]?	'Beef heart', 'Beef tongue', 'Lamb'	['question_type_local']
what items that I have to buy currently are on sale?	'Beef heart', 'Beef tongue', 'Lamb'	['question_type_global', 'question_two_hop_statement']
is there a sale on [this thing] anywhere?	'target'	['question_type_local']
what stores near [Cambridge Court] have an ongoing sale on [Beef tongue]?	'target'	['question_type_global', 'question_two_hop_statement']
is there a sale on any items on my shopping list?	'Beef heart', 'Beef tongue', 'Lamb'	['question_type_global', 'question_two_hop_statement']
i don't need [Beef tongue] and [Beef heart] for [this event] anymore
what do i have on shopping list for [dinner with ben]?	'Lamb'	['question_type_local']
what do i need [Lamb] for?	'dinner with ben'	['question_type_local']
what are the stores on [Cambridge Court]?	'target'	['question_type_global', 'question_single_statement']
this [gold circle] is on [Cambridge Court]
[radio], [blouse] and [lamp shade] are all different types of [Gift]
show me all stores near [Cambridge Court]	'gold circle', 'target'	['question_type_global', 'question_single_statement']
[Hoody] is a kind of [Clothing]
[Hanover Court] is in [East Liberty]
show me all stores near [Cambridge Court] that have a sale on [Beef heart]	'target'	['question_type_global', 'question_two_hop_statement']
what neighborhood is [this street] located in?	'East Liberty'	['question_type_local']
what are the supermarkets on [Cambridge Court]?	'target'	['question_type_global', 'question_single_statement']
i often shop at [wegmans], which is my local [supermarket]
show me all supermarkets on [Cambridge Court] that currently have a sale	'target'	['question_type_global', 'question_two_hop_statement']
show me all stores on [Cambridge Court] that currently have a sale on [meat]	'target'	['question_type_global', 'question_three_hop_statement']
this particular [that supermarket] is located on [Hanover Court]
what stores near [Cambridge Court] have an ongoing sale?	'target'	['question_type_global', 'question_two_hop_statement']
[Camisole] is a [Clothing]
What stores is [Beef heart] on sale at	'target', 'target'	['question_type_local']
are there any items on my shopping list that there is a sale on?	'Lamb'	['question_type_global', 'question_two_hop_statement']
[Pork] is a type of [Meat]
Where is [Beef tongue] on sale?	'target'	['question_type_local']
what is my shopping list?	'Lamb'	['question_type_global', 'question_single_statement']
[headphones] and [blouse] are on sale at [gold circle]
what is on sale at [gold circle]?	'headphones', 'blouse'	['question_type_local']
show me all supermarkets near [Hanover Court]	'wegmans'	['question_type_global', 'question_single_statement']
is there a sale on [blouse] anywhere?	'gold circle'	['question_type_local']
show me all of the department stores	'gold circle'	['question_type_global', 'question_single_statement']
what stores on [Cambridge Court] have a sale on [meat]?	'target'	['question_type_global', 'question_three_hop_statement']
Where is [Beef tongue] on sale?	'target'	['question_type_local']
show me all of the department stores on [Cambridge Court]	'gold circle'	['question_type_global', 'question_single_statement']
show me all of the stores on [Hanover Court]	'wegmans'	['question_type_global', 'question_single_statement']
Do i have any [meat] on my shopping list?	'Lamb'	['question_type_global', 'question_two_hop_statement']
what are the things that I need to get?	'Lamb'	['question_type_global', 'question_single_statement']
what stores are located on [Hanover Court]?	'wegmans'	['question_type_local']
is there a sale on any [meat] on my shopping list?	'Lamb'	['question_type_global', 'question_three_hop_statement']
show me all stores near [Cambridge Court] that have a sale on [meat]	'target'	['question_type_global', 'question_three_hop_statement']
what department stores on [Cambridge Court] have a sale?	'gold circle'	['question_type_global', 'question_two_hop_statement']
[Hoody] and [Camisole] are all on sale at [gold circle]
what is on sale at [gold circle]?	'headphones', 'blouse', 'Hoody', 'Camisole'	['question_type_local']
[Blouse], [Tie] and [Swimming Shorts] are all different types of [Clothing]
What stores is [Beef tongue] on sale at	'target'	['question_type_local']
what neighborhood is [Cambridge Court] in?	'Homewood South'	['question_type_local']
what are the stores on [Hanover Court]?	'wegmans'	['question_type_global', 'question_single_statement']
What stores is [Lamb] on sale at	'target'	['question_type_local']
show me all supermarkets that i tought you	'target', 'quality foods', 'wegmans'	['question_type_global', 'question_single_statement']
here are some examples of [Gift]: [camera], [book] and [watch]
show me all of the department stores on [Cambridge Court]	'gold circle'	['question_type_global', 'question_single_statement']
are there any items on my shopping list for [dinner with ben] that there is a sale on?	'Lamb'	['question_type_global', 'question_two_hop_statement']
show me all department stores on [Cambridge Court] that currently have a sale	'gold circle'	['question_type_global', 'question_two_hop_statement']
what stores are on [Cambridge Court]?	'target', 'gold circle'	['question_type_local']
i absolutely must not forget to get [Beef] for [dinner with ben]
What did I already buy for [that event]?	'Beef heart', 'Beef tongue'	['question_type_local']
what are the supermarkets?	'target', 'quality foods', 'wegmans'	['question_type_global', 'question_single_statement']
are there any [meat] on my shopping list that there is a sale on?	'Lamb'	['question_type_global', 'question_three_hop_statement']
is there any [meat] on my list that's on sale somewhere?	'Lamb'	['question_type_global', 'question_three_hop_statement']
[clay pot], [eye liner] and [video games] are all different types of [Gift]
show me all of the supermarkets	'target', 'quality foods', 'wegmans'	['question_type_global', 'question_single_statement']
What stores is [Beef heart] on sale at	'target', 'target'	['question_type_local']
[mirror] is a [Gift]
[picture frame], [flowers] and [balloon] are all good examples of [Gift]
[Cufflinks] is a kind of [Clothing]
show me all stores on [Cambridge Court] that currently have a sale on [gifts]	'gold circle'	['question_type_global', 'question_three_hop_statement']
what kind of [meat] do I need to get?	'Beef', 'Lamb'	['question_type_global', 'question_two_hop_statement']
what [meat] do i need to buy?	'Beef', 'Lamb'	['question_type_global', 'question_two_hop_statement']
what do i need [Lamb] for?	'dinner with ben'	['question_type_local']
show me all stores near [Cambridge Court]	'gold circle', 'target'	['question_type_global', 'question_single_statement']
what is my shopping list?	'Beef', 'Lamb'	['question_type_global', 'question_single_statement']
what are the supermarkets on [Cambridge Court]?	'target'	['question_type_global', 'question_single_statement']
what are the stores on [Hanover Court]?	'wegmans'	['question_type_global', 'question_single_statement']
show me all supermarkets near [Cambridge Court] that have a sale	'target'	['question_type_global', 'question_two_hop_statement']
what is on sale at [target that I last mentioned]?	'Beef heart', 'Beef tongue', 'Lamb'	['question_type_local']
Do I need to buy any [meat]?	'Beef', 'Lamb'	['question_type_global', 'question_two_hop_statement']
show me all of the supermarkets	'target', 'quality foods', 'wegmans'	['question_type_global', 'question_single_statement']
show me all department stores	'gold circle'	['question_type_global', 'question_single_statement']
is there a sale on [Hoody] anywhere?	'gold circle'	['question_type_local']
is there anything on my list that's on sale somewhere?	'Lamb'	['question_type_global', 'question_two_hop_statement']
is there any [meat] that I have to buy currently are on sale?	'Lamb'	['question_type_global', 'question_three_hop_statement']
Do i have any [meat] on my shopping list?	'Beef', 'Lamb'	['question_type_global', 'question_two_hop_statement']
are there any items on my shopping list that there is a sale on?	'Lamb'	['question_type_global', 'question_two_hop_statement']
Where is [Hoody] on sale?	'gold circle'	['question_type_local']
here are some examples of [Fruit]: [lemon], [jujube] and [pomegranate]
show me all of the department stores	'gold circle'	['question_type_global', 'question_single_statement']
show me all supermarkets on [Cambridge Court] that currently have a sale	'target'	['question_type_global', 'question_two_hop_statement']
i think [14th Street] is in [Homewood South]
add the following for [mandy's birthday]: [Tie] and [Hoody]
remove [Tie] from the list for [mandy's birthday]
what are the department stores?	'gold circle'	['question_type_global', 'question_single_statement']
what are the supermarkets?	'target', 'quality foods', 'wegmans'	['question_type_global', 'question_single_statement']
what items do I need to get?	'Beef', 'Lamb', 'Hoody'	['question_type_global', 'question_single_statement']
what items that I have to buy currently are on sale?	'Lamb', 'Hoody'	['question_type_global', 'question_two_hop_statement']
add the following for [that event]: [balloon] and [clay pot]
what did i remove from [mandy's birthday]?	'Tie'	['question_type_local']
show me all supermarkets near [Cambridge Court]	'target'	['question_type_global', 'question_single_statement']
show me all department stores on [Cambridge Court] that currently have a sale	'gold circle'	['question_type_global', 'question_two_hop_statement']
add [pomegranate] and [jujube] to my shopping list for [dinner with ben]
i just bought [Beef] for [dinner with ben]
what items did i already get for [this event]?	'Beef heart', 'Beef', 'Beef tongue'	['question_type_local']
what are the department stores on [Cambridge Court]?	'gold circle'	['question_type_global', 'question_single_statement']
what do i need to buy?	'Lamb', 'Hoody', 'clay pot', 'balloon', 'jujube', 'pomegranate'	['question_type_global', 'question_single_statement']
Do i have any [gifts] on my shopping list?	'clay pot', 'balloon'	['question_type_global', 'question_two_hop_statement']
show me all of the stores on [Hanover Court]	'wegmans'	['question_type_global', 'question_single_statement']
is there anything on my list that's on sale somewhere?	'Lamb', 'Hoody'	['question_type_global', 'question_two_hop_statement']
are there any items on my shopping list that there is a sale on?	'Lamb', 'Hoody'	['question_type_global', 'question_two_hop_statement']
show me all of the supermarkets on [Cambridge Court]	'target'	['question_type_global', 'question_single_statement']
what are the stores?	'gold circle', 'target', 'quality foods', 'wegmans'	['question_type_global', 'question_single_statement']
Do i have any [clothing] on my shopping list?	'Hoody'	['question_type_global', 'question_two_hop_statement']
there is a [department store] called [caldor] on [Hanover Court]
[that department store] has [balloon], [monitor] and [camera] on sale!
what items are on sale at [caldor]?	'monitor', 'camera', 'balloon'	['question_type_local']
[Jerusalem artichoke], [Parsley] and [Lemon Grass] are all examples of [Vegetables]
show me all stores near [Cambridge Court] that have a sale	'gold circle', 'target'	['question_type_global', 'question_two_hop_statement']
is there any [clothing] on my list that's on sale somewhere?	'Hoody'	['question_type_global', 'question_three_hop_statement']
[jujube], [lemon] and [pomegranate] are all on sale at [target on Cambridge Court]
what is on sale at [target on Cambridge Court]?	'Beef heart', 'Beef tongue', 'Lamb', 'lemon', 'jujube', 'pomegranate'	['question_type_local']
what are the department stores?	'gold circle', 'caldor'	['question_type_global', 'question_single_statement']
show me all department stores near [Cambridge Court] that have a sale	'gold circle'	['question_type_global', 'question_two_hop_statement']
are there any [meat] on my shopping list that there is a sale on?	'Lamb'	['question_type_global', 'question_three_hop_statement']
show me all stores near [Hanover Court] that have a sale on [gifts]	'caldor'	['question_type_global', 'question_three_hop_statement']
is there a sale on any [clothing] on my shopping list?	'Hoody'	['question_type_global', 'question_three_hop_statement']
[Turkey], [Goose Liver] and [Rabbit] are all different types of [Meat]
what stores near [Cambridge Court] have an ongoing sale on [fruit]?	'target'	['question_type_global', 'question_three_hop_statement']
is there any [fruit] on my list that's on sale somewhere?	'jujube', 'pomegranate'	['question_type_global', 'question_three_hop_statement']
show me all of the stores	'gold circle', 'target', 'quality foods', 'wegmans', 'caldor'	['question_type_global', 'question_single_statement']
what do i need [clay pot] for?	"mandy's birthday"	['question_type_local']
what event do I need to buy [clay pot] for	"mandy's birthday"	['question_type_local']
what stores are there that I taught you?	'gold circle', 'target', 'quality foods', 'wegmans', 'caldor'	['question_type_global', 'question_single_statement']
what are the supermarkets on [Cambridge Court]?	'target'	['question_type_global', 'question_single_statement']
show me all stores near [Hanover Court] that have a sale on [gifts]	'caldor'	['question_type_global', 'question_three_hop_statement']
Do I need to buy any [clothing]?	'Hoody'	['question_type_global', 'question_two_hop_statement']
for example [Meat] are [Goose] and [Venison]
Do i have any [gifts] on my shopping list?	'clay pot', 'balloon'	['question_type_global', 'question_two_hop_statement']
what kind of [gifts] do I need to get?	'clay pot', 'balloon'	['question_type_global', 'question_two_hop_statement']
what are the supermarkets?	'target', 'quality foods', 'wegmans'	['question_type_global', 'question_single_statement']
Where is [headphones] on sale?	'gold circle'	['question_type_local']
what items that I have to buy currently are on sale?	'Lamb', 'Hoody', 'balloon', 'jujube', 'pomegranate'	['question_type_global', 'question_two_hop_statement']
Do i have any [meat] on my shopping list?	'Lamb'	['question_type_global', 'question_two_hop_statement']
show me all supermarkets near [Hanover Court]	'wegmans'	['question_type_global', 'question_single_statement']
show me all stores on [Hanover Court] that currently have a sale	'caldor'	['question_type_global', 'question_two_hop_statement']
[Tripe] is a [Meat]
show me all supermarkets on [Cambridge Court] that currently have a sale	'target'	['question_type_global', 'question_two_hop_statement']
is there a sale on any items on my shopping list for [mandy's birthday]?	'Hoody', 'balloon'	['question_type_global', 'question_two_hop_statement']
show me all of the department stores on [Hanover Court]	'caldor'	['question_type_global', 'question_single_statement']
show me all stores on [Hanover Court] that currently have a sale on [gifts]	'caldor'	['question_type_global', 'question_three_hop_statement']
[Ceiling fan], [Solar water heater] and [Oil heater] are all types of [Appliance]
what stores on [Hanover Court] have a sale on [camera]?	'caldor'	['question_type_global', 'question_two_hop_statement']
show me all of the department stores	'gold circle', 'caldor'	['question_type_global', 'question_single_statement']
is there a sale on any [clothing] on my shopping list?	'Hoody'	['question_type_global', 'question_three_hop_statement']
what stores near [Cambridge Court] have an ongoing sale on [clothing]?	'gold circle'	['question_type_global', 'question_three_hop_statement']
[I] am on [Hanover Court]
show me all department stores near [Hanover Court]	'caldor'	['question_type_global', 'question_single_statement']
show me all stores near [Hanover Court] that have a sale on [balloon]	'caldor'	['question_type_global', 'question_two_hop_statement']
are there any stores nearby that have a sale on items that i need?	'caldor'	['question_type_global', 'question_four_hop_statement']
are there any [fruit] that i need to get?	'jujube', 'pomegranate'	['question_type_global', 'question_two_hop_statement']
What stores is [pomegranate] on sale at	'target'	['question_type_local']
is there a sale on any items on my shopping list where i am?	'balloon'	['question_type_global', 'question_four_hop_statement']
what items are on sale at [gold circle]?	'headphones', 'blouse', 'Hoody', 'Camisole'	['question_type_local']
is there any [fruit] on my list that's on sale somewhere?	'jujube', 'pomegranate'	['question_type_global', 'question_three_hop_statement']
show me all supermarkets that i tought you	'target', 'quality foods', 'wegmans'	['question_type_global', 'question_single_statement']
I just got to [14th Street]
what department stores are there	'gold circle', 'caldor'	['question_type_global', 'question_single_statement']
what stores on [Cambridge Court] have a sale on [Lamb]?	'target'	['question_type_global', 'question_two_hop_statement']
[Basil] is a kind of [Vegetables]
what neighborhood is [this street] in?	'Homewood South'	['question_type_local']
show me all stores near [Cambridge Court] that have a sale on [fruit]	'target'	['question_type_global', 'question_three_hop_statement']
what department stores are there on [Hanover Court]?	'caldor'	['question_type_global', 'question_single_statement']
show me all of the supermarkets	'target', 'quality foods', 'wegmans'	['question_type_global', 'question_single_statement']
is there a sale on any [clothing] on my shopping list?	'Hoody'	['question_type_global', 'question_three_hop_statement']
what department stores on [Cambridge Court] have a sale?	'gold circle'	['question_type_global', 'question_two_hop_statement']
are there any [meat] that i need to get?	'Lamb'	['question_type_global', 'question_two_hop_statement']
what stores near [Cambridge Court] have an ongoing sale on [Hoody]?	'gold circle'	['question_type_global', 'question_two_hop_statement']
are there any [clothing] that i need to get?	'Hoody'	['question_type_global', 'question_two_hop_statement']
What stores is [Hoody] on sale at	'gold circle'	['question_type_local']
is there any [clothing] that I have to buy currently are on sale?	'Hoody'	['question_type_global', 'question_three_hop_statement']
show me all of the stores	'gold circle', 'target', 'quality foods', 'wegmans', 'caldor'	['question_type_global', 'question_single_statement']
what supermarkets are there on [Hanover Court]?	'wegmans'	['question_type_global', 'question_single_statement']
Do I need to buy any [fruit]?	'jujube', 'pomegranate'	['question_type_global', 'question_two_hop_statement']
[jujube], [lemon] and [pomegranate] are on sale at [wegmans]
[jujube] is no longer on sale at [wegmans]
show me all department stores near [Hanover Court] that have a sale	'caldor'	['question_type_global', 'question_two_hop_statement']
[Blouse], [Cufflinks] and [Swimming Shorts] are on sale at [gold circle]
what is on sale at [gold circle]?	'headphones', 'blouse', 'Hoody', 'Camisole', 'Blouse', 'Swimming Shorts', 'Cufflinks'	['question_type_local']
what stores are there on [Cambridge Court]?	'gold circle', 'target'	['question_type_global', 'question_single_statement']
what department stores are there on [Cambridge Court]?	'gold circle'	['question_type_global', 'question_single_statement']
What stores is [balloon] on sale at	'caldor'	['question_type_local']
show me all stores near [Cambridge Court] that have a sale on [fruit]	'target'	['question_type_global', 'question_three_hop_statement']
show me all of the department stores on [Hanover Court]	'caldor'	['question_type_global', 'question_single_statement']
[lime], [cherry] and [plum] are all different types of [Fruit]
what items are on sale at [target on Cambridge Court]?	'Beef heart', 'Beef tongue', 'Lamb', 'lemon', 'jujube', 'pomegranate'	['question_type_local']
what department stores are there	'gold circle', 'caldor'	['question_type_global', 'question_single_statement']
what items that I have to buy currently are on sale?	'Lamb', 'Hoody', 'balloon', 'jujube', 'pomegranate'	['question_type_global', 'question_two_hop_statement']
[Home server], [Television] and [Hair iron] are all different types of [Appliance]
what supermarkets on [Hanover Court] have a sale?	'wegmans'	['question_type_global', 'question_two_hop_statement']
show me all of the stores	'gold circle', 'target', 'quality foods', 'wegmans', 'caldor'	['question_type_global', 'question_single_statement']
is there any [fruit] on my list that's on sale somewhere?	'jujube', 'pomegranate'	['question_type_global', 'question_three_hop_statement']
show me all supermarkets on [Cambridge Court] that currently have a sale	'target'	['question_type_global', 'question_two_hop_statement']
show me all stores on [Hanover Court] that currently have a sale	'wegmans', 'caldor'	['question_type_global', 'question_two_hop_statement']
is there any [clothing] on my list that's on sale somewhere?	'Hoody'	['question_type_global', 'question_three_hop_statement']
Where is [Swimming Shorts] on sale?	'gold circle'	['question_type_local']
is there any [fruit] that I have to buy currently are on sale?	'jujube', 'pomegranate'	['question_type_global', 'question_three_hop_statement']
is there a sale on any items on my shopping list for [dinner with ben]?	'Lamb', 'jujube', 'pomegranate'	['question_type_global', 'question_two_hop_statement']
are there any [fruit] that i need to get?	'jujube', 'pomegranate'	['question_type_global', 'question_two_hop_statement']
what kind of [meat] do I need to get?	'Lamb'	['question_type_global', 'question_two_hop_statement']
what items do I need to get?	'Lamb', 'Hoody', 'clay pot', 'balloon', 'jujube', 'pomegranate'	['question_type_global', 'question_single_statement']
what stores on [Hanover Court] have a sale on [gifts]?	'caldor'	['question_type_global', 'question_three_hop_statement']
[Tie] is on sale at [gold circle]
[this department store] doesn't have [Swimming Shorts] on sale anymore
what stores near [Hanover Court] have an ongoing sale?	'wegmans', 'caldor'	['question_type_global', 'question_two_hop_statement']
i often shop at [target], which is my local [supermarket]
is there any [gifts] on my list that's on sale somewhere?	'balloon'	['question_type_global', 'question_three_hop_statement']
what stores are there that I taught you?	'gold circle', 'target', 'quality foods', 'wegmans', 'caldor'	['question_type_global', 'question_single_statement']
[that store] has [Goose], [Turkey] and [Goose Liver] on sale!
this specific [target that I last mentioned] is on [14th Street]
what's currently on sale at [that store]?	'Turkey', 'Goose Liver', 'Goose'	['question_type_local']
is there a store nearby with a sale on [meat] going on right now?	'target'	['question_type_global', 'question_four_hop_statement']
[Swimming Shorts] is on sale at [gold circle]
what things did i get for [dinner with ben]	'Beef heart', 'Beef', 'Beef tongue'	['question_type_local']
what department stores are there	'gold circle', 'caldor'	['question_type_global', 'question_single_statement']
are there any [clothing] on my shopping list that there is a sale on?	'Hoody'	['question_type_global', 'question_three_hop_statement']
[gold circle] has [radio], [camera] and [picture frame] on sale!
what items are on sale at [gold circle]?	'headphones', 'radio', 'blouse', 'Hoody', 'Camisole', 'Blouse', 'Tie', 'Swimming Shorts', 'camera', 'picture frame', 'Cufflinks'	['question_type_local']
what do stores near me have on sale?	'Turkey', 'Goose Liver', 'Goose'	['question_type_global', 'question_three_hop_statement']
[caldor] has [eye liner] and [picture frame] on sale!
[monitor], [eye liner] and [balloon] stopped being on sale at [caldor]
show me all stores near [Cambridge Court] that have a sale	'gold circle', 'target'	['question_type_global', 'question_two_hop_statement']
what stores on [Hanover Court] have a sale on [fruit]?	'wegmans'	['question_type_global', 'question_three_hop_statement']
what are the stores?	'gold circle', 'target', 'quality foods', 'wegmans', 'caldor'	['question_type_global', 'question_single_statement']
what event do I need to buy [balloon] for	"mandy's birthday"	['question_type_local']
what supermarkets are there?	'target', 'quality foods', 'wegmans'	['question_type_global', 'question_single_statement']
what [gifts] do i need to buy?	'clay pot', 'balloon'	['question_type_global', 'question_two_hop_statement']
show me all stores near [Hanover Court] that have a sale	'wegmans', 'caldor'	['question_type_global', 'question_two_hop_statement']
is there a store nearby with a sale on [meat] going on right now?	'target'	['question_type_global', 'question_four_hop_statement']
what are the stores on [14th Street]?	'target'	['question_type_global', 'question_single_statement']
what stores on [Cambridge Court] have a sale on [radio]?	'gold circle'	['question_type_global', 'question_two_hop_statement']
is there any [meat] that I have to buy currently are on sale?	'Lamb'	['question_type_global', 'question_three_hop_statement']
[Belt], [Sunglasses] and [Shirt] are [Clothing]
what stores near [Hanover Court] have an ongoing sale?	'wegmans', 'caldor'	['question_type_global', 'question_two_hop_statement']
are there any [meat] on my shopping list that there is a sale on?	'Lamb'	['question_type_global', 'question_three_hop_statement']
show me all department stores	'gold circle', 'caldor'	['question_type_global', 'question_single_statement']
are there any [fruit] on my shopping list that there is a sale on?	'jujube', 'pomegranate'	['question_type_global', 'question_three_hop_statement']
what kind of [meat] do I need to get?	'Lamb'	['question_type_global', 'question_two_hop_statement']
what items are on sale at [target that I last mentioned]?	'Turkey', 'Goose Liver', 'Goose'	['question_type_local']
is there a sale on any [fruit] on my shopping list?	'jujube', 'pomegranate'	['question_type_global', 'question_three_hop_statement']
is there a sale on any [meat] on my shopping list?	'Lamb'	['question_type_global', 'question_three_hop_statement']
is there a sale on [Tie] anywhere?	'gold circle'	['question_type_local']
what are the department stores on [Cambridge Court]?	'gold circle'	['question_type_global', 'question_single_statement']
show me all department stores near [Cambridge Court]	'gold circle'	['question_type_global', 'question_single_statement']
add [Basil] and [Lemon Grass] to my shopping list for [dinner with ben]
are there any [fruit] on my shopping list that there is a sale on?	'jujube', 'pomegranate'	['question_type_global', 'question_three_hop_statement']
does any store nearby have [meat] on sale?	'target'	['question_type_global', 'question_four_hop_statement']
what are the department stores?	'gold circle', 'caldor'	['question_type_global', 'question_single_statement']
show me all stores on [Cambridge Court] that currently have a sale on [clothing]	'gold circle'	['question_type_global', 'question_three_hop_statement']
Do i have any [meat] on my shopping list?	'Lamb'	['question_type_global', 'question_two_hop_statement']
what is my shopping list?	'Lamb', 'Hoody', 'clay pot', 'balloon', 'jujube', 'pomegranate', 'Lemon Grass', 'Basil'	['question_type_global', 'question_single_statement']
what supermarkets on [Cambridge Court] have a sale?	'target'	['question_type_global', 'question_two_hop_statement']
show me all stores near [Cambridge Court] that have a sale on [meat]	'target'	['question_type_global', 'question_three_hop_statement']
What stores is [camera] on sale at	'gold circle', 'caldor'	['question_type_local']
[Chapel Street] is on the outskirts of [Homewood South]
what stores on [14th Street] have a sale?	'target'	['question_type_global', 'question_two_hop_statement']
there is a [supermarket] called [quality foods] on [14th Street]
what items are on sale at [caldor]?	'camera', 'picture frame'	['question_type_local']
are there any [clothing] that i need to get?	'Hoody'	['question_type_global', 'question_two_hop_statement']
show me all supermarkets near [14th Street]	'target', 'quality foods'	['question_type_global', 'question_single_statement']
Where is [headphones] on sale?	'gold circle'	['question_type_local']
what supermarkets on [Hanover Court] have a sale?	'wegmans'	['question_type_global', 'question_two_hop_statement']
what kind of [gifts] do I need to get?	'clay pot', 'balloon'	['question_type_global', 'question_two_hop_statement']
what neighborhood is [that street] in?	'Homewood South'	['question_type_local']
Do I need to buy any [gifts]?	'clay pot', 'balloon'	['question_type_global', 'question_two_hop_statement']
Do i have any [fruit] on my shopping list?	'jujube', 'pomegranate'	['question_type_global', 'question_two_hop_statement']
what is my shopping list?	'Lamb', 'Hoody', 'clay pot', 'balloon', 'jujube', 'pomegranate', 'Lemon Grass', 'Basil'	['question_type_global', 'question_single_statement']
what stores on [Hanover Court] have a sale?	'wegmans', 'caldor'	['question_type_global', 'question_two_hop_statement']
is there anything on my list that's on sale somewhere?	'Lamb', 'Hoody', 'jujube', 'pomegranate'	['question_type_global', 'question_two_hop_statement']
[that supermarket] has [lime], [lemon] and [plum] on sale!
are there any items on my shopping list that there is a sale on?	'Lamb', 'Hoody', 'jujube', 'pomegranate'	['question_type_global', 'question_two_hop_statement']
what supermarkets near [Cambridge Court] have an ongoing sale?	'target'	['question_type_global', 'question_two_hop_statement']
what stores on [Hanover Court] have a sale on [gifts]?	'caldor'	['question_type_global', 'question_three_hop_statement']
is there a store near my location is having a sale?	'quality foods', 'target'	['question_type_global', 'question_three_hop_statement']
what kind of [meat] do I need to get?	'Lamb'	['question_type_global', 'question_two_hop_statement']
does any store nearby have [meat] on sale?	'target'	['question_type_global', 'question_four_hop_statement']
is there a store near my location is having a sale on [fruit]?	'quality foods'	['question_type_global', 'question_four_hop_statement']
what items that I have to buy for [mandy's birthday] currently are on sale?	'Hoody'	['question_type_global', 'question_two_hop_statement']
is there a sale on any items on my shopping list for [dinner with ben]?	'Lamb', 'jujube', 'pomegranate'	['question_type_global', 'question_two_hop_statement']
[Oil heater], [Hair iron] and [Home server] are all on sale at [gold circle]
what's currently on sale at [gold circle]?	'headphones', 'radio', 'blouse', 'Hoody', 'Camisole', 'Blouse', 'Tie', 'Swimming Shorts', 'camera', 'picture frame', 'Cufflinks', 'Oil heater', 'Home server', 'Hair iron'	['question_type_local']
show me all supermarkets near [Hanover Court]	'wegmans'	['question_type_global', 'question_single_statement']
[Willow Lane] is located in the [East Liberty] neighborhood
show me all stores near [Cambridge Court] that have a sale on [jujube]	'target'	['question_type_global', 'question_two_hop_statement']
is there a sale on any items on my shopping list for [mandy's birthday]?	'Hoody'	['question_type_global', 'question_two_hop_statement']
what stores near [Cambridge Court] have an ongoing sale on [clothing]?	'gold circle'	['question_type_global', 'question_three_hop_statement']
show me all stores near [Cambridge Court] that have a sale on [gifts]	'gold circle'	['question_type_global', 'question_three_hop_statement']
why do i need to buy [Hoody]?	"mandy's birthday"	['question_type_local']
is there a sale on any [meat] on my shopping list?	'Lamb'	['question_type_global', 'question_three_hop_statement']
is there any [clothing] on my list that's on sale somewhere?	'Hoody'	['question_type_global', 'question_three_hop_statement']
What stores is [this appliance] on sale at	'gold circle'	['question_type_local']
what stores near [Hanover Court] have an ongoing sale on [gifts]?	'caldor'	['question_type_global', 'question_three_hop_statement']
show me all of the department stores	'gold circle', 'caldor'	['question_type_global', 'question_single_statement']
are there any [clothing] on my shopping list that there is a sale on?	'Hoody'	['question_type_global', 'question_three_hop_statement']
[target on 14th Street] has [Pork] on sale!
Where is [Turkey] on sale?	'target'	['question_type_local']
show me all stores near [Cambridge Court] that have a sale on [clothing]	'gold circle'	['question_type_global', 'question_three_hop_statement']
show me all of the supermarkets on [14th Street]	'target', 'quality foods'	['question_type_global', 'question_single_statement']
show me all of the supermarkets	'target', 'quality foods', 'wegmans'	['question_type_global', 'question_single_statement']
What stores is [this meat] on sale at	'target'	['question_type_local']
show me all stores on [Cambridge Court] that currently have a sale on [clothing]	'gold circle'	['question_type_global', 'question_three_hop_statement']
show me all supermarkets on [Hanover Court] that currently have a sale	'wegmans'	['question_type_global', 'question_two_hop_statement']
Do i have any [vegetables] on my shopping list?	'Lemon Grass', 'Basil'	['question_type_global', 'question_two_hop_statement']
[Parsley], [Lemon Grass] and [Basil] are on sale at [that supermarket]
what is on sale at [target on 14th Street]?	'Pork', 'Parsley', 'Lemon Grass', 'Turkey', 'Goose Liver', 'Goose', 'Basil'	['question_type_local']
is there a store nearby with a sale on [fruit] going on right now?	'quality foods'	['question_type_global', 'question_four_hop_statement']
what [clothing] do i need to buy?	'Hoody'	['question_type_global', 'question_two_hop_statement']
there is a [supermarket] called [homeland] on [Hanover Court]
what stores are on [Cambridge Court]?	'target', 'gold circle'	['question_type_local']
what stores are there that I taught you?	'gold circle', 'target', 'quality foods', 'wegmans', 'caldor', 'homeland'	['question_type_global', 'question_single_statement']
is there a store nearby with a sale on [vegetables] going on right now?	'target'	['question_type_global', 'question_four_hop_statement']
show me all stores on [Cambridge Court] that currently have a sale on [blouse]	'gold circle'	['question_type_global', 'question_two_hop_statement']
[Solar water heater], [Television] and [Oil heater] are on sale at [caldor]
what items are on sale at [gold circle]?	'headphones', 'radio', 'blouse', 'Hoody', 'Camisole', 'Blouse', 'Tie', 'Swimming Shorts', 'camera', 'picture frame', 'Cufflinks', 'Oil heater', 'Home server', 'Hair iron'	['question_type_local']
What stores is [Television] on sale at	'caldor'	['question_type_local']
what stores are there on [14th Street]?	'target', 'quality foods'	['question_type_global', 'question_single_statement']
are there any [vegetables] that i need to get?	'Lemon Grass', 'Basil'	['question_type_global', 'question_two_hop_statement']
for example [Appliance] are [Forced-air] and [Kimchi refrigerator]
Where is [Blouse] on sale?	'gold circle'	['question_type_local']
Do i have any [vegetables] on my shopping list?	'Lemon Grass', 'Basil'	['question_type_global', 'question_two_hop_statement']
show me all stores on [Cambridge Court] that currently have a sale on [gifts]	'gold circle'	['question_type_global', 'question_three_hop_statement']
what supermarkets are there on [Hanover Court]?	'wegmans', 'homeland'	['question_type_global', 'question_single_statement']
what stores are located on [Hanover Court]?	'wegmans', 'caldor', 'homeland'	['question_type_local']
is there any [fruit] that I have to buy currently are on sale?	'jujube', 'pomegranate'	['question_type_global', 'question_three_hop_statement']
are there any [gifts] that i need to get?	'clay pot', 'balloon'	['question_type_global', 'question_two_hop_statement']
what supermarkets are there?	'target', 'quality foods', 'wegmans', 'homeland'	['question_type_global', 'question_single_statement']
are there any stores nearby that have a sale on items that i need?	'target'	['question_type_global', 'question_four_hop_statement']
is there a sale on any items on my shopping list where i am?	'Lemon Grass', 'Basil'	['question_type_global', 'question_four_hop_statement']
are there any stores nearby that have a sale on [vegetables]?	'target'	['question_type_global', 'question_four_hop_statement']
are there any [vegetables] on my shopping list that there is a sale on?	'Lemon Grass', 'Basil'	['question_type_global', 'question_three_hop_statement']
is there a store near my location is having a sale on [vegetables]?	'target'	['question_type_global', 'question_four_hop_statement']
are there any stores nearby that have a sale on [fruit]?	'quality foods'	['question_type_global', 'question_four_hop_statement']
is there a sale on any [meat] on my shopping list?	'Lamb'	['question_type_global', 'question_three_hop_statement']
is there a sale on [Camisole] anywhere?	'gold circle'	['question_type_local']
what kind of [meat] do I need to get?	'Lamb'	['question_type_global', 'question_two_hop_statement']
is there a store near my location is having a sale on [meat]?	'target'	['question_type_global', 'question_four_hop_statement']
are there any [gifts] that i need to get?	'clay pot', 'balloon'	['question_type_global', 'question_two_hop_statement']
what stores are there that I taught you?	'gold circle', 'target', 'quality foods', 'wegmans', 'caldor', 'homeland'	['question_type_global', 'question_single_statement']
what is my shopping list?	'Lamb', 'Hoody', 'clay pot', 'balloon', 'jujube', 'pomegranate', 'Lemon Grass', 'Basil'	['question_type_global', 'question_single_statement']
is there any [meat] that I have to buy currently are on sale?	'Lamb'	['question_type_global', 'question_three_hop_statement']
is there a sale on any [clothing] on my shopping list?	'Hoody'	['question_type_global', 'question_three_hop_statement']
is there a store near my location is having a sale on [vegetables]?	'target'	['question_type_global', 'question_four_hop_statement']
what supermarkets are there on [Hanover Court]?	'wegmans', 'homeland'	['question_type_global', 'question_single_statement']
what items are on sale at nearby stores?	'Pork', 'lemon', 'Parsley', 'Lemon Grass', 'Turkey', 'Goose Liver', 'Goose', 'Basil', 'lime', 'plum'	['question_type_global', 'question_three_hop_statement']
what kind of [meat] do I need to get?	'Lamb'	['question_type_global', 'question_two_hop_statement']
what [meat] do i need to buy?	'Lamb'	['question_type_global', 'question_two_hop_statement']
is there any [fruit] on my list that's on sale somewhere?	'jujube', 'pomegranate'	['question_type_global', 'question_three_hop_statement']
is there a sale on [headphones] anywhere?	'gold circle'	['question_type_local']
is there a store near my location is having a sale on [meat]?	'target'	['question_type_global', 'question_four_hop_statement']
is there anything that I need for [dinner with ben] that's on sale somewhere?	'Lamb', 'jujube', 'pomegranate', 'Lemon Grass', 'Basil'	['question_type_global', 'question_two_hop_statement']
what department stores are there on [Hanover Court]?	'caldor'	['question_type_global', 'question_single_statement']
are there any [gifts] that i need to get?	'clay pot', 'balloon'	['question_type_global', 'question_two_hop_statement']
what stores on [Cambridge Court] have a sale on [clothing]?	'gold circle'	['question_type_global', 'question_three_hop_statement']
show me all stores on [14th Street] that currently have a sale	'target', 'quality foods'	['question_type_global', 'question_two_hop_statement']
is there a store near my location is having a sale?	'quality foods', 'target'	['question_type_global', 'question_three_hop_statement']
Do I need to buy any [gifts]?	'clay pot', 'balloon'	['question_type_global', 'question_two_hop_statement']
what are the department stores on [Hanover Court]?	'caldor'	['question_type_global', 'question_single_statement']
is there a store nearby with a sale on [fruit] going on right now?	'quality foods'	['question_type_global', 'question_four_hop_statement']
[wegmans] has [Pork], [Goose] and [Venison] on sale!
what's currently on sale at [wegmans]?	'Pork', 'lemon', 'pomegranate', 'Goose', 'Venison'	['question_type_local']
show me all stores near [14th Street] that have a sale	'target', 'quality foods'	['question_type_global', 'question_two_hop_statement']
show me all department stores	'gold circle', 'caldor'	['question_type_global', 'question_single_statement']
does any store nearby have anything on sale?	'quality foods', 'target'	['question_type_global', 'question_three_hop_statement']
what do i need [Basil] for?	'dinner with ben'	['question_type_local']
what are the stores?	'gold circle', 'target', 'quality foods', 'wegmans', 'caldor', 'homeland'	['question_type_global', 'question_single_statement']
what do i need to buy?	'Lamb', 'Hoody', 'clay pot', 'balloon', 'jujube', 'pomegranate', 'Lemon Grass', 'Basil'	['question_type_global', 'question_single_statement']
[Berkshire Drive] is in [Homewood South]
what are the things that I need to get?	'Lamb', 'Hoody', 'clay pot', 'balloon', 'jujube', 'pomegranate', 'Lemon Grass', 'Basil'	['question_type_global', 'question_single_statement']
show me all stores on [Cambridge Court] that currently have a sale on [meat]	'target'	['question_type_global', 'question_three_hop_statement']
Do I need to buy any [meat]?	'Lamb'	['question_type_global', 'question_two_hop_statement']
I am currently on [Hanover Court]
what neighborhood am I in?	'East Liberty'	['question_type_local']
what stores near [Hanover Court] have an ongoing sale on [meat]?	'wegmans'	['question_type_global', 'question_three_hop_statement']
show me all stores on [Hanover Court] that currently have a sale	'wegmans', 'caldor'	['question_type_global', 'question_two_hop_statement']
what do stores near me have on sale?	'Pork', 'camera', 'picture frame', 'lemon', 'pomegranate', 'Goose', 'Venison', 'Solar water heater', 'Oil heater', 'Television'	['question_type_global', 'question_three_hop_statement']
Do I need to buy any [clothing]?	'Hoody'	['question_type_global', 'question_two_hop_statement']
is there any [vegetables] on my list that's on sale somewhere?	'Lemon Grass', 'Basil'	['question_type_global', 'question_three_hop_statement']
what department stores are there on [Hanover Court]?	'caldor'	['question_type_global', 'question_single_statement']
show me all of the supermarkets on [Hanover Court]	'wegmans', 'homeland'	['question_type_global', 'question_single_statement']
are there any stores nearby that have a sale on items that i need?	'wegmans'	['question_type_global', 'question_four_hop_statement']
what neighborhood is [it] located in?	'East Liberty'	['question_type_local']
Do i have any [vegetables] on my shopping list?	'Lemon Grass', 'Basil'	['question_type_global', 'question_two_hop_statement']
what stores near [Hanover Court] have an ongoing sale on [gifts]?	'caldor'	['question_type_global', 'question_three_hop_statement']
what are the stores on [Hanover Court]?	'wegmans', 'caldor', 'homeland'	['question_type_global', 'question_single_statement']
what are the department stores on [Hanover Court]?	'caldor'	['question_type_global', 'question_single_statement']
show me all department stores near [Hanover Court]	'caldor'	['question_type_global', 'question_single_statement']
what is on sale at [gold circle]?	'headphones', 'radio', 'blouse', 'Hoody', 'Camisole', 'Blouse', 'Tie', 'Swimming Shorts', 'camera', 'picture frame', 'Cufflinks', 'Oil heater', 'Home server', 'Hair iron'	['question_type_local']
Do i have any [meat] on my shopping list?	'Lamb'	['question_type_global', 'question_two_hop_statement']
I think I am in [Homewood South]
I am currently on [this street]
what neighborhood am I in?	'East Liberty'	['question_type_local']
show me all supermarkets that i tought you	'target', 'quality foods', 'wegmans', 'homeland'	['question_type_global', 'question_single_statement']
i just bought [pomegranate] and [Lamb] for [dinner with ben]
is there any [clothing] that I have to buy currently are on sale?	'Hoody'	['question_type_global', 'question_three_hop_statement']
is there any [vegetables] that I have to buy currently are on sale?	'Lemon Grass', 'Basil'	['question_type_global', 'question_three_hop_statement']
Where is [pomegranate] on sale?	'target', 'wegmans'	['question_type_local']
Do i have any [clothing] on my shopping list?	'Hoody'	['question_type_global', 'question_two_hop_statement']
what stores near [Cambridge Court] have an ongoing sale on [meat]?	'target'	['question_type_global', 'question_three_hop_statement']
what stores on [Hanover Court] have a sale?	'wegmans', 'caldor'	['question_type_global', 'question_two_hop_statement']
show me all of the stores	'gold circle', 'target', 'quality foods', 'wegmans', 'caldor', 'homeland'	['question_type_global', 'question_single_statement']
show me all department stores near [Cambridge Court]	'gold circle'	['question_type_global', 'question_single_statement']
show me all stores near [Hanover Court] that have a sale on [meat]	'wegmans'	['question_type_global', 'question_three_hop_statement']
Where is [that meat] on sale?	'target'	['question_type_local']
what items that I have to buy for [dinner with ben] currently are on sale?	'jujube', 'Lemon Grass', 'Basil'	['question_type_global', 'question_two_hop_statement']
what stores near [14th Street] have an ongoing sale on [meat]?	'target'	['question_type_global', 'question_three_hop_statement']
is there a sale on [Lemon Grass] anywhere?	'target'	['question_type_local']
what are the things that i need to get?	'Hoody', 'clay pot', 'balloon', 'jujube', 'Lemon Grass', 'Basil'	['question_type_global', 'question_single_statement']
What stores is [that meat] on sale at	'target'	['question_type_local']
is there a sale on any items on my shopping list for [mandy's birthday]?	'Hoody'	['question_type_global', 'question_two_hop_statement']
what stores near [14th Street] have an ongoing sale on [fruit]?	'quality foods'	['question_type_global', 'question_three_hop_statement']
are there any [clothing] on my shopping list that there is a sale on?	'Hoody'	['question_type_global', 'question_three_hop_statement']
show me all stores near [14th Street] that have a sale	'target', 'quality foods'	['question_type_global', 'question_two_hop_statement']
what is my shopping list?	'Hoody', 'clay pot', 'balloon', 'jujube', 'Lemon Grass', 'Basil'	['question_type_global', 'question_single_statement']
is there anything on my list that's on sale somewhere?	'Hoody', 'jujube', 'Lemon Grass', 'Basil'	['question_type_global', 'question_two_hop_statement']
is there a sale on [Basil] anywhere?	'target'	['question_type_local']
what supermarkets are there on [Hanover Court]?	'wegmans', 'homeland'	['question_type_global', 'question_single_statement']
what stores near [14th Street] have an ongoing sale on [fruit]?	'quality foods'	['question_type_global', 'question_three_hop_statement']
Do i have any [gifts] on my shopping list?	'clay pot', 'balloon'	['question_type_global', 'question_two_hop_statement']
are there any stores nearby that have a sale?	'caldor', 'wegmans'	['question_type_global', 'question_three_hop_statement']
is there any [vegetables] on my list that's on sale somewhere?	'Lemon Grass', 'Basil'	['question_type_global', 'question_three_hop_statement']
is there a store nearby with a sale on [meat] going on right now?	'wegmans'	['question_type_global', 'question_four_hop_statement']
Do I need to buy any [clothing]?	'Hoody'	['question_type_global', 'question_two_hop_statement']
is there a sale on [Hair iron] anywhere?	'gold circle'	['question_type_local']
is there any [clothing] that I have to buy currently are on sale?	'Hoody'	['question_type_global', 'question_three_hop_statement']
is there a store near my location is having a sale?	'caldor', 'wegmans'	['question_type_global', 'question_three_hop_statement']
show me all department stores	'gold circle', 'caldor'	['question_type_global', 'question_single_statement']
what are the stores on [Hanover Court]?	'wegmans', 'caldor', 'homeland'	['question_type_global', 'question_single_statement']
are there any stores nearby that have a sale on [meat]?	'wegmans'	['question_type_global', 'question_four_hop_statement']
what [clothing] do i need to buy?	'Hoody'	['question_type_global', 'question_two_hop_statement']
show me all stores on [Hanover Court] that currently have a sale	'wegmans', 'caldor'	['question_type_global', 'question_two_hop_statement']
are there any stores nearby that have a sale on [fruit]?	'wegmans'	['question_type_global', 'question_four_hop_statement']
is there a sale on any [clothing] on my shopping list?	'Hoody'	['question_type_global', 'question_three_hop_statement']
what stores on [14th Street] have a sale on [meat]?	'target'	['question_type_global', 'question_three_hop_statement']
what things do I need to buy for [dinner with ben]	'jujube', 'Lemon Grass', 'Basil'	['question_type_local']
Where is [Pork] on sale?	'target', 'wegmans'	['question_type_local']
what event do I need to buy [balloon] for	"mandy's birthday"	['question_type_local']
is there a store near my location is having a sale on [meat]?	'wegmans'	['question_type_global', 'question_four_hop_statement']
what's currently on sale at [wegmans]?	'Pork', 'lemon', 'pomegranate', 'Goose', 'Venison'	['question_type_local']
what stores on [Hanover Court] have a sale on [gifts]?	'caldor'	['question_type_global', 'question_three_hop_statement']
Where is [Swimming Shorts] on sale?	'gold circle'	['question_type_local']
is there a sale on any [clothing] on my shopping list?	'Hoody'	['question_type_global', 'question_three_hop_statement']
what are the stores on [Cambridge Court]?	'gold circle', 'target'	['question_type_global', 'question_single_statement']
[Taro] and [Patty pans] are good examples of [Vegetables]
what stores near [14th Street] have an ongoing sale on [vegetables]?	'target'	['question_type_global', 'question_three_hop_statement']
is there a store nearby with a sale on [fruit] going on right now?	'wegmans'	['question_type_global', 'question_four_hop_statement']
show me all supermarkets on [14th Street] that currently have a sale	'target', 'quality foods'	['question_type_global', 'question_two_hop_statement']
What stores is [headphones] on sale at	'gold circle'	['question_type_local']
what stores on [Cambridge Court] have a sale on [fruit]?	'target'	['question_type_global', 'question_three_hop_statement']
is there anything that I need for [mandy's birthday] that's on sale somewhere?	'Hoody'	['question_type_global', 'question_two_hop_statement']
show me all stores near [Hanover Court] that have a sale on [meat]	'wegmans'	['question_type_global', 'question_three_hop_statement']
show me all stores on [Hanover Court] that currently have a sale	'wegmans', 'caldor'	['question_type_global', 'question_two_hop_statement']
show me all department stores on [Hanover Court] that currently have a sale	'caldor'	['question_type_global', 'question_two_hop_statement']
what items that I have to buy for [dinner with ben] currently are on sale?	'jujube', 'Lemon Grass', 'Basil'	['question_type_global', 'question_two_hop_statement']
what stores on [14th Street] have a sale on [Turkey]?	'target'	['question_type_global', 'question_two_hop_statement']
make sure to buy [plum] for [dinner with ben]
is there a sale on [Turkey] anywhere?	'target'	['question_type_local']
show me all of the department stores	'gold circle', 'caldor'	['question_type_global', 'question_single_statement']
show me all stores on [Cambridge Court] that currently have a sale on [appliances]	'gold circle'	['question_type_global', 'question_three_hop_statement']
is there a store nearby with a sale on [fruit] going on right now?	'wegmans'	['question_type_global', 'question_four_hop_statement']
Do I need to buy any [vegetables]?	'Lemon Grass', 'Basil'	['question_type_global', 'question_two_hop_statement']
remove [Basil] and [Lemon Grass] from my shopping list for [dinner with ben]
add [Goose] to my shopping list for [dinner with ben]
what are the things that I need to get?	'Hoody', 'clay pot', 'balloon', 'jujube', 'Goose', 'plum'	['question_type_global', 'question_single_statement']
show me all stores near [Hanover Court]	'wegmans', 'caldor', 'homeland'	['question_type_global', 'question_single_statement']
what department stores are there on [Hanover Court]?	'caldor'	['question_type_global', 'question_single_statement']
what stores on [14th Street] have a sale?	'target', 'quality foods'	['question_type_global', 'question_two_hop_statement']
what is on sale at [target on 14th Street]?	'Pork', 'Parsley', 'Lemon Grass', 'Turkey', 'Goose Liver', 'Goose', 'Basil'	['question_type_local']
are there any stores nearby that have a sale on [gifts]?	'caldor'	['question_type_global', 'question_four_hop_statement']
show me all stores near [Cambridge Court]	'gold circle', 'target'	['question_type_global', 'question_single_statement']
what is my shopping list?	'Hoody', 'clay pot', 'balloon', 'jujube', 'Goose', 'plum'	['question_type_global', 'question_single_statement']
what are the supermarkets?	'target', 'quality foods', 'wegmans', 'homeland'	['question_type_global', 'question_single_statement']
is there a sale on [Swimming Shorts] anywhere?	'gold circle'	['question_type_local']
is there any [clothing] that I have to buy currently are on sale?	'Hoody'	['question_type_global', 'question_three_hop_statement']
what stores near [Hanover Court] have an ongoing sale on [appliances]?	'caldor'	['question_type_global', 'question_three_hop_statement']
[jujube] is on sale at [quality foods on 14th Street]
what items are on sale at [that supermarket]?	'lemon', 'jujube', 'lime', 'plum'	['question_type_local']
what kind of [fruit] do I need to get?	'jujube', 'plum'	['question_type_global', 'question_two_hop_statement']
is there a sale on any [fruit] on my shopping list?	'jujube', 'plum'	['question_type_global', 'question_three_hop_statement']
are there any stores nearby that have a sale on [appliances]?	'caldor'	['question_type_global', 'question_four_hop_statement']
are there any [clothing] on my shopping list that there is a sale on?	'Hoody'	['question_type_global', 'question_three_hop_statement']
what [meat] do i need to buy?	'Goose'	['question_type_global', 'question_two_hop_statement']
what is on sale at [target on Cambridge Court]?	'Beef heart', 'Beef tongue', 'Lamb', 'lemon', 'jujube', 'pomegranate'	['question_type_local']
does any store nearby have [meat] on sale?	'wegmans'	['question_type_global', 'question_four_hop_statement']
what stores are there on [Cambridge Court]?	'gold circle', 'target'	['question_type_global', 'question_single_statement']
are there any stores nearby that have a sale on [gifts]?	'caldor'	['question_type_global', 'question_four_hop_statement']
what supermarkets on [Hanover Court] have a sale?	'wegmans'	['question_type_global', 'question_two_hop_statement']
is there a sale on [Camisole] anywhere?	'gold circle'	['question_type_local']
what kind of [gifts] do I need to get?	'clay pot', 'balloon'	['question_type_global', 'question_two_hop_statement']
are there any stores nearby that have a sale on [meat]?	'wegmans'	['question_type_global', 'question_four_hop_statement']
show me all stores on [14th Street] that currently have a sale on [fruit]	'quality foods'	['question_type_global', 'question_three_hop_statement']
Do i have any [gifts] on my shopping list?	'clay pot', 'balloon'	['question_type_global', 'question_two_hop_statement']
why do i need to buy [Hoody]?	"mandy's birthday"	['question_type_local']
what stores on [Cambridge Court] have a sale on [gifts]?	'gold circle'	['question_type_global', 'question_three_hop_statement']
is there a store nearby with a sale on [meat] going on right now?	'wegmans'	['question_type_global', 'question_four_hop_statement']
show me all stores on [Cambridge Court] that currently have a sale on [meat]	'target'	['question_type_global', 'question_three_hop_statement']
are there any stores nearby that have a sale on [Oil heater]?	'caldor'	['question_type_global', 'question_three_hop_statement']
What did I already buy for [dinner with ben]?	'Beef heart', 'Beef', 'Beef tongue', 'Lamb', 'pomegranate', 'Lemon Grass', 'Basil'	['question_type_local']
show me all of the supermarkets on [14th Street]	'target', 'quality foods'	['question_type_global', 'question_single_statement']
are there any stores nearby that have a sale on items that i need?	'wegmans'	['question_type_global', 'question_four_hop_statement']
what stores on [Hanover Court] have a sale on [gifts]?	'caldor'	['question_type_global', 'question_three_hop_statement']
is there a store near my location is having a sale on [gifts]?	'caldor'	['question_type_global', 'question_four_hop_statement']
is there a store nearby with a sale on [fruit] going on right now?	'wegmans'	['question_type_global', 'question_four_hop_statement']
what stores near [Cambridge Court] have an ongoing sale on [fruit]?	'target'	['question_type_global', 'question_three_hop_statement']
what stores on [14th Street] have a sale on [fruit]?	'quality foods'	['question_type_global', 'question_three_hop_statement']
are there any [meat] that i need to get?	'Goose'	['question_type_global', 'question_two_hop_statement']
what are the department stores on [Hanover Court]?	'caldor'	['question_type_global', 'question_single_statement']
what are the department stores on [Cambridge Court]?	'gold circle'	['question_type_global', 'question_single_statement']
is there a store near my location is having a sale?	'caldor', 'wegmans'	['question_type_global', 'question_three_hop_statement']
What stores is [this item] on sale at	'target', 'quality foods'	['question_type_local']
is there a store near my location is having a sale on [gifts]?	'caldor'	['question_type_global', 'question_four_hop_statement']
what are the stores on [14th Street]?	'target', 'quality foods'	['question_type_global', 'question_single_statement']
why do i need to buy [this item]?	'dinner with ben'	['question_type_local']
show me all stores on [Hanover Court] that currently have a sale on [appliances]	'caldor'	['question_type_global', 'question_three_hop_statement']
show me all stores near [Cambridge Court] that have a sale on [meat]	'target'	['question_type_global', 'question_three_hop_statement']
what items that I have to buy for [dinner with ben] currently are on sale?	'jujube', 'Goose', 'plum'	['question_type_global', 'question_two_hop_statement']
what stores near [14th Street] have an ongoing sale on [meat]?	'target'	['question_type_global', 'question_three_hop_statement']
show me all supermarkets that i tought you	'target', 'quality foods', 'wegmans', 'homeland'	['question_type_global', 'question_single_statement']
what is on sale at [target on 14th Street]?	'Pork', 'Parsley', 'Lemon Grass', 'Turkey', 'Goose Liver', 'Goose', 'Basil'	['question_type_local']
what department stores near [Hanover Court] have an ongoing sale?	'caldor'	['question_type_global', 'question_two_hop_statement']
show me all stores near [14th Street] that have a sale	'target', 'quality foods'	['question_type_global', 'question_two_hop_statement']
show me all department stores near [Hanover Court]	'caldor'	['question_type_global', 'question_single_statement']
what is on sale at [target on Cambridge Court]?	'Beef heart', 'Beef tongue', 'Lamb', 'lemon', 'jujube', 'pomegranate'	['question_type_local']
is there a store nearby with a sale on [appliances] going on right now?	'caldor'	['question_type_global', 'question_four_hop_statement']
are there any stores nearby that have a sale?	'caldor', 'wegmans'	['question_type_global', 'question_three_hop_statement']
what kind of [fruit] do I need to get?	'jujube', 'plum'	['question_type_global', 'question_two_hop_statement']
What do I need to buy [Goose] for?	'dinner with ben'	['question_type_local']
are there any [meat] on my shopping list that there is a sale on?	'Goose'	['question_type_global', 'question_three_hop_statement']
what items do I need to get?	'Hoody', 'clay pot', 'balloon', 'jujube', 'Goose', 'plum'	['question_type_global', 'question_single_statement']
show me all department stores	'gold circle', 'caldor'	['question_type_global', 'question_single_statement']
what do stores near me are have a sale on?	'Pork', 'camera', 'picture frame', 'lemon', 'pomegranate', 'Goose', 'Venison', 'Solar water heater', 'Oil heater', 'Television'	['question_type_global', 'question_three_hop_statement']
what department stores are there	'gold circle', 'caldor'	['question_type_global', 'question_single_statement']
is there any [fruit] on my list that's on sale somewhere?	'jujube', 'plum'	['question_type_global', 'question_three_hop_statement']
Do I need to buy any [fruit]?	'jujube', 'plum'	['question_type_global', 'question_two_hop_statement']
What stores is [that fruit] on sale at	'target', 'quality foods'	['question_type_local']
show me all department stores near [Cambridge Court] that have a sale	'gold circle'	['question_type_global', 'question_two_hop_statement']
does any store nearby have [appliances] on sale?	'caldor'	['question_type_global', 'question_four_hop_statement']
what stores near [Cambridge Court] have an ongoing sale?	'gold circle', 'target'	['question_type_global', 'question_two_hop_statement']
what items that I have to buy currently are on sale near me?	'Goose'	['question_type_global', 'question_four_hop_statement']
what stores are there on [Cambridge Court]?	'gold circle', 'target'	['question_type_global', 'question_single_statement']
Do I need to buy any [fruit]?	'jujube', 'plum'	['question_type_global', 'question_two_hop_statement']
show me all stores on [14th Street] that currently have a sale on [vegetables]	'target'	['question_type_global', 'question_three_hop_statement']
Do i have any [clothing] on my shopping list?	'Hoody'	['question_type_global', 'question_two_hop_statement']
what stores on [14th Street] have a sale on [meat]?	'target'	['question_type_global', 'question_three_hop_statement']
is there a store nearby with a sale on [gifts] going on right now?	'caldor'	['question_type_global', 'question_four_hop_statement']
what do stores near me are have a sale on?	'Pork', 'camera', 'picture frame', 'lemon', 'pomegranate', 'Goose', 'Venison', 'Solar water heater', 'Oil heater', 'Television'	['question_type_global', 'question_three_hop_statement']
show me all stores near [Cambridge Court] that have a sale on [appliances]	'gold circle'	['question_type_global', 'question_three_hop_statement']
[lemon], [Venison] and [Pork] are no longer on sale at [wegmans]
what is on sale at [gold circle]?	'headphones', 'radio', 'blouse', 'Hoody', 'Camisole', 'Blouse', 'Tie', 'Swimming Shorts', 'camera', 'picture frame', 'Cufflinks', 'Oil heater', 'Home server', 'Hair iron'	['question_type_local']
show me all stores near [Hanover Court] that have a sale	'wegmans', 'caldor'	['question_type_global', 'question_two_hop_statement']
what stores on [14th Street] have a sale?	'target', 'quality foods'	['question_type_global', 'question_two_hop_statement']
are there any [fruit] on my shopping list that there is a sale on?	'jujube', 'plum'	['question_type_global', 'question_three_hop_statement']
Where is [Pork] on sale?	'target'	['question_type_local']
is there a store near my location is having a sale on [fruit]?	'wegmans'	['question_type_global', 'question_four_hop_statement']
what department stores are there	'gold circle', 'caldor'	['question_type_global', 'question_single_statement']
What stores is [Turkey] on sale at	'target'	['question_type_local']
show me all supermarkets near [14th Street] that have a sale	'target', 'quality foods'	['question_type_global', 'question_two_hop_statement']
[Durham Court] is on the outskirts of [East Liberty]
is there a sale on [Solar water heater] anywhere?	'caldor'	['question_type_local']
is there a store nearby with any of the items on my shopping list on sale?	'wegmans'	['question_type_global', 'question_four_hop_statement']
show me all stores near [14th Street]	'target', 'quality foods'	['question_type_global', 'question_single_statement']
is there a store nearby with a sale on [appliances] going on right now?	'caldor'	['question_type_global', 'question_four_hop_statement']
show me all stores on [14th Street] that currently have a sale on [fruit]	'quality foods'	['question_type_global', 'question_three_hop_statement']
is there a sale on any items on my shopping list?	'Hoody', 'jujube', 'Goose', 'plum'	['question_type_global', 'question_two_hop_statement']
i just bought [Goose] and [plum] for [dinner with ben]
make sure to buy [Goose Liver] for [dinner with ben]
what items are on sale at [caldor]?	'camera', 'picture frame', 'Solar water heater', 'Oil heater', 'Television'	['question_type_local']
does any store nearby have [gifts] on sale?	'caldor'	['question_type_global', 'question_four_hop_statement']
what stores near [Cambridge Court] have an ongoing sale on [Beef tongue]?	'target'	['question_type_global', 'question_two_hop_statement']
show me all stores near [14th Street]	'target', 'quality foods'	['question_type_global', 'question_single_statement']
is there a sale on [radio] anywhere?	'gold circle'	['question_type_local']
is there anything that I need for [mandy's birthday] that's on sale somewhere?	'Hoody'	['question_type_global', 'question_two_hop_statement']
please remind me to buy [lemon] for [dinner with ben]
what things did i get for [this event]	'Beef heart', 'Beef', 'Beef tongue', 'Lamb', 'pomegranate', 'Lemon Grass', 'Goose', 'Basil', 'plum'	['question_type_local']
what stores are there on [Hanover Court]?	'wegmans', 'caldor', 'homeland'	['question_type_global', 'question_single_statement']
what kind of [gifts] do I need to get?	'clay pot', 'balloon'	['question_type_global', 'question_two_hop_statement']
Do i have any [gifts] on my shopping list?	'clay pot', 'balloon'	['question_type_global', 'question_two_hop_statement']
Do I need to buy any [fruit]?	'lemon', 'jujube'	['question_type_global', 'question_two_hop_statement']
[target on Cambridge Court] has [plum] on sale!
what's currently on sale at [this supermarket]?	'Beef heart', 'Beef tongue', 'Lamb', 'lemon', 'jujube', 'pomegranate', 'plum'	['question_type_local']
is there a sale on any items on my shopping list?	'Hoody', 'lemon', 'jujube', 'Goose Liver'	['question_type_global', 'question_two_hop_statement']
what are the stores?	'gold circle', 'target', 'quality foods', 'wegmans', 'caldor', 'homeland'	['question_type_global', 'question_single_statement']
make sure to buy [cherry] and [lime] for [dinner with ben]
get rid of [Goose Liver] and [cherry] from my shopping for [dinner with ben]
is there a sale on [Parsley] anywhere?	'target'	['question_type_local']
what do stores near me are have a sale on?	'camera', 'picture frame', 'pomegranate', 'Goose', 'Solar water heater', 'Oil heater', 'Television'	['question_type_global', 'question_three_hop_statement']
are there any stores nearby that have a sale on [meat]?	'wegmans'	['question_type_global', 'question_four_hop_statement']
is there a sale on [Goose Liver] anywhere?	'target'	['question_type_local']
does any store nearby have [fruit] on sale?	'wegmans'	['question_type_global', 'question_four_hop_statement']
i often shop at [gold circle], which is my local [department store]
show me all supermarkets near [Hanover Court]	'wegmans', 'homeland'	['question_type_global', 'question_single_statement']
what department stores are there	'gold circle', 'caldor'	['question_type_global', 'question_single_statement']
What stores is [lime] on sale at	'quality foods'	['question_type_local']
what stores on [14th Street] have a sale on [meat]?	'target'	['question_type_global', 'question_three_hop_statement']
[Hoody] and [Blouse] are all on sale at [gold circle]
what's currently on sale at [gold circle that I last mentioned]?	'Hoody', 'Blouse'	['question_type_local']
what stores near [Cambridge Court] have an ongoing sale on [meat]?	'target'	['question_type_global', 'question_three_hop_statement']
Do I need to buy any [clothing]?	'Hoody'	['question_type_global', 'question_two_hop_statement']
show me all of the stores on [14th Street]	'target', 'quality foods'	['question_type_global', 'question_single_statement']
Do I need to buy any [fruit]?	'lemon', 'jujube', 'lime'	['question_type_global', 'question_two_hop_statement']
what is on sale at [gold circle on Cambridge Court]?	'headphones', 'radio', 'blouse', 'Hoody', 'Camisole', 'Blouse', 'Tie', 'Swimming Shorts', 'camera', 'picture frame', 'Cufflinks', 'Oil heater', 'Home server', 'Hair iron'	['question_type_local']
what kind of [gifts] do I need to get?	'clay pot', 'balloon'	['question_type_global', 'question_two_hop_statement']
show me all stores near [Cambridge Court]	'gold circle', 'target'	['question_type_global', 'question_single_statement']
does any store nearby have [fruit] on sale?	'wegmans'	['question_type_global', 'question_four_hop_statement']
show me all supermarkets that i tought you	'target', 'quality foods', 'wegmans', 'homeland'	['question_type_global', 'question_single_statement']
does any store nearby have [appliances] on sale?	'caldor'	['question_type_global', 'question_four_hop_statement']
what stores are there on [Hanover Court]?	'wegmans', 'caldor', 'homeland'	['question_type_global', 'question_single_statement']
are there any items on my shopping list for [mandy's birthday] that there is a sale on?	'Hoody'	['question_type_global', 'question_two_hop_statement']
show me all of the supermarkets on [14th Street]	'target', 'quality foods'	['question_type_global', 'question_single_statement']
what [clothing] do i need to buy?	'Hoody'	['question_type_global', 'question_two_hop_statement']
what department stores near [Cambridge Court] have an ongoing sale?	'gold circle'	['question_type_global', 'question_two_hop_statement']
what stores near [Cambridge Court] have an ongoing sale on [clothing]?	'gold circle'	['question_type_global', 'question_three_hop_statement']
is there a sale on [Beef tongue] anywhere?	'target'	['question_type_local']
does any store nearby have [appliances] on sale?	'caldor'	['question_type_global', 'question_four_hop_statement']
does any store nearby have [fruit] on sale?	'wegmans'	['question_type_global', 'question_four_hop_statement']
show me all of the department stores on [Hanover Court]	'caldor'	['question_type_global', 'question_single_statement']
Do I need to buy any [gifts]?	'clay pot', 'balloon'	['question_type_global', 'question_two_hop_statement']
what do stores near me are have a sale on?	'camera', 'picture frame', 'pomegranate', 'Goose', 'Solar water heater', 'Oil heater', 'Television'	['question_type_global', 'question_three_hop_statement']
[cherry] and [jujube] are all on sale at [wegmans]
what neighborhood is [Durham Court] in?	'East Liberty'	['question_type_local']
show me all of the department stores on [Cambridge Court]	'gold circle'	['question_type_global', 'question_single_statement']
is there a sale on any items on my shopping list where i am?	'jujube'	['question_type_global', 'question_four_hop_statement']
what are the department stores?	'gold circle', 'caldor'	['question_type_global', 'question_single_statement']
show me all stores on [Cambridge Court] that currently have a sale on [fruit]	'target'	['question_type_global', 'question_three_hop_statement']
what items that I have to buy currently are on sale near me?	'jujube'	['question_type_global', 'question_four_hop_statement']
does any store nearby have anything on sale?	'caldor', 'wegmans'	['question_type_global', 'question_three_hop_statement']
are there any [gifts] that i need to get?	'clay pot', 'balloon'	['question_type_global', 'question_two_hop_statement']
what stores near [Hanover Court] have an ongoing sale on [appliances]?	'caldor'	['question_type_global', 'question_three_hop_statement']
what stores near [14th Street] have an ongoing sale on [fruit]?	'quality foods'	['question_type_global', 'question_three_hop_statement']
what items are on sale at [target on 14th Street]?	'Pork', 'Parsley', 'Lemon Grass', 'Turkey', 'Goose Liver', 'Goose', 'Basil'	['question_type_local']
show me all stores	'gold circle', 'target', 'quality foods', 'wegmans', 'caldor', 'homeland'	['question_type_global', 'question_single_statement']
show me all of the department stores on [Hanover Court]	'caldor'	['question_type_global', 'question_single_statement']
show me all supermarkets that i tought you	'target', 'quality foods', 'wegmans', 'homeland'	['question_type_global', 'question_single_statement']
is there a sale on [cherry] anywhere?	'wegmans'	['question_type_local']
show me all stores on [14th Street] that currently have a sale on [vegetables]	'target'	['question_type_global', 'question_three_hop_statement']
is there a sale on [radio] anywhere?	'gold circle'	['question_type_local']
does any store nearby have [meat] on sale?	'wegmans'	['question_type_global', 'question_four_hop_statement']
what supermarkets on [14th Street] have a sale?	'target', 'quality foods'	['question_type_global', 'question_two_hop_statement']
[wegmans] has [Tripe], [Rabbit] and [Beef] on sale!
what items are on sale at [wegmans]?	'Beef', 'jujube', 'pomegranate', 'Rabbit', 'Goose', 'Tripe', 'cherry'	['question_type_local']
is there a store nearby with a sale on [gifts] going on right now?	'caldor'	['question_type_global', 'question_four_hop_statement']
is there a store near my location is having a sale on [gifts]?	'caldor'	['question_type_global', 'question_four_hop_statement']
Do i have any [gifts] on my shopping list?	'clay pot', 'balloon'	['question_type_global', 'question_two_hop_statement']
what are the things that I need to get?	'Hoody', 'clay pot', 'balloon', 'lemon', 'jujube', 'lime'	['question_type_global', 'question_single_statement']
what supermarkets are there on [14th Street]?	'target', 'quality foods'	['question_type_global', 'question_single_statement']
