[shoes] is a type of [Gift]
[Quandong], [Radish] and [Celeriac] are [Vegetables]
remember that i have [wendy's visit tomorrow]
[Goose] is a type of [Meat]
i absolutely must not forget to get both [Quandong] and [Radish] for [that event]
add [Celeriac] to my shopping list for [wendy's visit tomorrow]
remove [Celeriac] and [Radish] from my shopping list for [wendy's visit tomorrow]
[tangerine] is a type of [Fruit]
i have [linda's wedding] coming up
[Beef liver] is a [Meat]
remember that i have [my honeymoon]
please remind me to buy [shoes] for [linda's wedding]
what items do I need to get?	'shoes', 'Quandong'	['question_type_global', 'question_single_statement']
[Pumpkin], [Skirret] and [Squashes] are all good examples of [Vegetables]
things i need to buy for [wendy's visit tomorrow]: [Goose] and [Beef liver]
i just got [Beef liver] for [wendy's visit tomorrow]
What do I need to buy for [wendy's visit tomorrow]?	'Quandong', 'Goose'	['question_type_local']
why do i need to buy [Quandong]?	"wendy's visit tomorrow"	['question_type_local']
i need to make sure to get [tangerine] for [wendy's visit tomorrow]
what things do I need to buy for [that event]	'Quandong', 'Goose', 'tangerine'	['question_type_local']
are there any [meat] that i need to get?	'Goose'	['question_type_global', 'question_two_hop_statement']
add [shoes] to my shopping list for [my honeymoon]
what do i have on shopping list for [that event]?	'shoes'	['question_type_local']
what [gifts] do i need to buy?	'shoes'	['question_type_global', 'question_two_hop_statement']
what [meat] do i need to buy?	'Goose'	['question_type_global', 'question_two_hop_statement']
what items did i already get for [wendy's visit tomorrow]?	'Radish', 'Celeriac', 'Beef liver'	['question_type_local']
Do i have any [fruit] on my shopping list?	'tangerine'	['question_type_global', 'question_two_hop_statement']
What do I need to buy for [that event]?	'shoes'	['question_type_local']
what [vegetables] do i need to buy?	'Quandong'	['question_type_global', 'question_two_hop_statement']
Do I need to buy any [fruit]?	'tangerine'	['question_type_global', 'question_two_hop_statement']
why do i need to buy [Quandong]?	"wendy's visit tomorrow"	['question_type_local']
[jujube] is a type of [Fruit]
Do I need to buy any [meat]?	'Goose'	['question_type_global', 'question_two_hop_statement']
Do i have any [gifts] on my shopping list?	'shoes'	['question_type_global', 'question_two_hop_statement']
what do i have on shopping list for [wendy's visit tomorrow]?	'Quandong', 'Goose', 'tangerine'	['question_type_local']
are there any [vegetables] that i need to get?	'Quandong'	['question_type_global', 'question_two_hop_statement']
Do I need to buy any [vegetables]?	'Quandong'	['question_type_global', 'question_two_hop_statement']
[Cornish Hen], [Beef tongue] and [Ham] are all different types of [Meat]
What do I need to buy [tangerine] for?	"wendy's visit tomorrow"	['question_type_local']
make sure to buy [jujube] for [wendy's visit tomorrow]
i just got [tangerine] for [wendy's visit tomorrow]
what things did i get for [that event]	'Radish', 'Celeriac', 'tangerine', 'Beef liver'	['question_type_local']
what are the things that I need to get?	'shoes', 'Quandong', 'Goose', 'jujube'	['question_type_global', 'question_single_statement']
i just bought [Quandong] for [wendy's visit tomorrow]
What do I need to buy for [wendy's visit tomorrow]?	'Goose', 'jujube'	['question_type_local']
[shawl], [key chain] and [lamp] are all good examples of [Gift]
Do I need to buy any [meat]?	'Goose'	['question_type_global', 'question_two_hop_statement']
what [gifts] do i need to buy?	'shoes'	['question_type_global', 'question_two_hop_statement']
what kind of [fruit] do I need to get?	'jujube'	['question_type_global', 'question_two_hop_statement']
some example of [Appliance] are [Box mangle] and [Mousetrap]
what do i have on shopping list for [wendy's visit tomorrow]?	'Goose', 'jujube'	['question_type_local']
remove these for [wendy's visit tomorrow]: [jujube] and [Goose]
[avocado], [guava] and [papaya] are all examples of [Fruit]
[2nd Avenue] is located in the [Homewood West] neighborhood
what do i have on shopping list for [linda's wedding]?	'shoes'	['question_type_local']
things i need to buy for [my honeymoon]: [Box mangle] and [Mousetrap]
what do I need for [my honeymoon]?	'shoes', 'Box mangle', 'Mousetrap'	['question_type_local']
i don't need [shoes] and [Box mangle] for [my honeymoon] anymore
[Shoes] and [Nightgown] are both examples of [Clothing]
what are the things that I need to get?	'shoes', 'Mousetrap'	['question_type_global', 'question_single_statement']
i need to get [Beef tongue] for [wendy's visit tomorrow]
What did I already buy for [that event]?	'Quandong', 'Radish', 'Celeriac', 'Goose', 'tangerine', 'Beef liver', 'jujube'	['question_type_local']
what are the things that i need to get?	'shoes', 'Beef tongue', 'Mousetrap'	['question_type_global', 'question_single_statement']
i need to make sure to get [avocado] for [wendy's visit tomorrow]
what items did i already get for [this event]?	'Quandong', 'Radish', 'Celeriac', 'Goose', 'tangerine', 'Beef liver', 'jujube'	['question_type_local']
i need to get [guava] for [wendy's visit tomorrow]
Do i have any [appliances] on my shopping list?	'Mousetrap'	['question_type_global', 'question_two_hop_statement']
make sure to buy [Shoes] and [Nightgown] for [linda's wedding]
i just bought [shoes] for [linda's wedding]
Do i have any [fruit] on my shopping list?	'avocado', 'guava'	['question_type_global', 'question_two_hop_statement']
Do i have any [meat] on my shopping list?	'Beef tongue'	['question_type_global', 'question_two_hop_statement']
Do I need to buy any [appliances]?	'Mousetrap'	['question_type_global', 'question_two_hop_statement']
[strawberry], [plum] and [blueberry] are all types of [Fruit]
Do I need to buy any [meat]?	'Beef tongue'	['question_type_global', 'question_two_hop_statement']
what kind of [appliances] do I need to get?	'Mousetrap'	['question_type_global', 'question_two_hop_statement']
why do i need to buy [Mousetrap]?	'my honeymoon'	['question_type_local']
What do I need to buy for [wendy's visit tomorrow]?	'Beef tongue', 'avocado', 'guava'	['question_type_local']
what [fruit] do i need to buy?	'avocado', 'guava'	['question_type_global', 'question_two_hop_statement']
Do I need to buy any [fruit]?	'avocado', 'guava'	['question_type_global', 'question_two_hop_statement']
what do i need to buy?	'Beef tongue', 'Mousetrap', 'avocado', 'guava', 'Shoes', 'Nightgown'	['question_type_global', 'question_single_statement']
Do I need to buy any [meat]?	'Beef tongue'	['question_type_global', 'question_two_hop_statement']
what kind of [clothing] do I need to get?	'Shoes', 'Nightgown'	['question_type_global', 'question_two_hop_statement']
please remind me to buy [papaya] for [wendy's visit tomorrow]
what things do I need to buy for [my honeymoon]	'Mousetrap'	['question_type_local']
i need to make sure to get [Shoes] and [Nightgown] for [my honeymoon]
please remind me to buy [Cornish Hen] for [wendy's visit tomorrow]
get rid of [guava] from my shopping list for [that event]
what do I need for [wendy's visit tomorrow]?	'Cornish Hen', 'Beef tongue', 'avocado', 'papaya'	['question_type_local']
are there any [meat] that i need to get?	'Cornish Hen', 'Beef tongue'	['question_type_global', 'question_two_hop_statement']
[I] am on [2nd Avenue]
are there any [appliances] that i need to get?	'Mousetrap'	['question_type_global', 'question_two_hop_statement']
what do i have on shopping list for [wendy's visit tomorrow]?	'Cornish Hen', 'Beef tongue', 'avocado', 'papaya'	['question_type_local']
i am pretty sure that [Augusta Drive] is in [Fairywood]
I think I am in [Fairywood]
please remind me to buy [Ham] for [wendy's visit tomorrow]
What do I need to buy [avocado] for?	"wendy's visit tomorrow"	['question_type_local']
what kind of [appliances] do I need to get?	'Mousetrap'	['question_type_global', 'question_two_hop_statement']
what neighborhood is [Augusta Drive] in?	'Fairywood'	['question_type_local']
i often shop at [marshalls], which is my local [department store]
this [marshalls] is on [2nd Avenue]
what is my shopping list?	'Cornish Hen', 'Beef tongue', 'Ham', 'Mousetrap', 'avocado', 'papaya', 'Shoes', 'Nightgown'	['question_type_global', 'question_single_statement']
what items do I need to get?	'Cornish Hen', 'Beef tongue', 'Ham', 'Mousetrap', 'avocado', 'papaya', 'Shoes', 'Nightgown'	['question_type_global', 'question_single_statement']
what department stores are there on [2nd Avenue]?	'marshalls'	['question_type_global', 'question_single_statement']
[Grouse] and [Beef] are both different kinds of [Meat]
are there any [clothing] that i need to get?	'Shoes', 'Nightgown'	['question_type_global', 'question_two_hop_statement']
what are the stores on [2nd Avenue]?	'marshalls'	['question_type_global', 'question_single_statement']
what kind of [meat] do I need to get?	'Cornish Hen', 'Beef tongue', 'Ham'	['question_type_global', 'question_two_hop_statement']
show me all stores	'marshalls'	['question_type_global', 'question_single_statement']
Do i have any [appliances] on my shopping list?	'Mousetrap'	['question_type_global', 'question_two_hop_statement']
what event do I need to buy [Cornish Hen] for	"wendy's visit tomorrow"	['question_type_local']
i need to get [Pumpkin] for [wendy's visit tomorrow]
what do i have on shopping list for [this event]?	'Pumpkin', 'Cornish Hen', 'Beef tongue', 'Ham', 'avocado', 'papaya'	['question_type_local']
what are the things that i need to get?	'Pumpkin', 'Cornish Hen', 'Beef tongue', 'Ham', 'Mousetrap', 'avocado', 'papaya', 'Shoes', 'Nightgown'	['question_type_global', 'question_single_statement']
make sure to buy [strawberry] for [wendy's visit tomorrow]
what stores are there on [2nd Avenue]?	'marshalls'	['question_type_global', 'question_single_statement']
why do i need to buy [that item]?	"wendy's visit tomorrow"	['question_type_local']
just purchases [Shoes] for [my honeymoon]
what department stores are there	'marshalls'	['question_type_global', 'question_single_statement']
what do i have on shopping list for [wendy's visit tomorrow]?	'Pumpkin', 'Cornish Hen', 'Beef tongue', 'Ham', 'avocado', 'papaya', 'strawberry'	['question_type_local']
show me all stores	'marshalls'	['question_type_global', 'question_single_statement']
[Vacuum cleaner], [Beverage opener] and [Air conditioner] are all types of [Appliance]
what kind of [fruit] do I need to get?	'avocado', 'papaya', 'strawberry'	['question_type_global', 'question_two_hop_statement']
what neighborhood am I currently in?	'Fairywood'	['question_type_local']
what are the stores?	'marshalls'	['question_type_global', 'question_single_statement']
show me all department stores near [2nd Avenue]	'marshalls'	['question_type_global', 'question_single_statement']
what are the stores on [2nd Avenue]?	'marshalls'	['question_type_local']
what event do I need to buy [papaya] for	"wendy's visit tomorrow"	['question_type_local']
what are the department stores on [2nd Avenue]?	'marshalls'	['question_type_global', 'question_single_statement']
i just bought both [Cornish Hen] and [papaya] for [wendy's visit tomorrow]
show me all department stores	'marshalls'	['question_type_global', 'question_single_statement']
Do I need to buy any [meat]?	'Beef tongue', 'Ham'	['question_type_global', 'question_two_hop_statement']
What do I need to buy [Shoes] for?	"linda's wedding"	['question_type_local']
what are the stores?	'marshalls'	['question_type_global', 'question_single_statement']
What do I need to buy for [wendy's visit tomorrow]?	'Pumpkin', 'Beef tongue', 'Ham', 'avocado', 'strawberry'	['question_type_local']
Do I need to buy any [clothing]?	'Shoes', 'Nightgown'	['question_type_global', 'question_two_hop_statement']
Do i have any [vegetables] on my shopping list?	'Pumpkin'	['question_type_global', 'question_two_hop_statement']
what [appliances] do i need to buy?	'Mousetrap'	['question_type_global', 'question_two_hop_statement']
[Grant Avenue] is located in the [Fairywood] neighborhood
Do i have any [appliances] on my shopping list?	'Mousetrap'	['question_type_global', 'question_two_hop_statement']
what kind of [fruit] do I need to get?	'avocado', 'strawberry'	['question_type_global', 'question_two_hop_statement']
what are the stores?	'marshalls'	['question_type_global', 'question_single_statement']
what neighborhood is [Augusta Drive] located in?	'Fairywood'	['question_type_local']
what stores are there that I taught you?	'marshalls'	['question_type_global', 'question_single_statement']
What do I need to buy for [wendy's visit tomorrow]?	'Pumpkin', 'Beef tongue', 'Ham', 'avocado', 'strawberry'	['question_type_local']
Do i have any [meat] on my shopping list?	'Beef tongue', 'Ham'	['question_type_global', 'question_two_hop_statement']
What do I need to buy [Beef tongue] for?	"wendy's visit tomorrow"	['question_type_local']
get rid of [avocado] and [Beef tongue] from my shopping for [wendy's visit tomorrow]
what do i need [Shoes] for?	"linda's wedding"	['question_type_local']
what are the things that I need to get?	'Pumpkin', 'Ham', 'Mousetrap', 'Shoes', 'Nightgown', 'strawberry'	['question_type_global', 'question_single_statement']
[Window fan] is a type of [Appliance]
show me all of the department stores	'marshalls'	['question_type_global', 'question_single_statement']
show me all department stores near [2nd Avenue]	'marshalls'	['question_type_global', 'question_single_statement']
remove these for [wendy's visit tomorrow]: [Ham] and [Pumpkin]
what do I need for [wendy's visit tomorrow]?	'strawberry'	['question_type_local']
things i need to buy for [linda's wedding]: [Window fan] and [Box mangle]
what neighborhood am I currently in?	'Fairywood'	['question_type_local']
[Overalls] is a kind of [Clothing]
what are the stores?	'marshalls'	['question_type_global', 'question_single_statement']
what [clothing] do i need to buy?	'Shoes', 'Nightgown'	['question_type_global', 'question_two_hop_statement']
[Space heater] and [Hair iron] are both examples of [Appliance]
what neighborhood is [Augusta Drive] located in?	'Fairywood'	['question_type_local']
show me all stores near [2nd Avenue]	'marshalls'	['question_type_global', 'question_single_statement']
what is my shopping list?	'Box mangle', 'Mousetrap', 'Shoes', 'Nightgown', 'strawberry', 'Window fan'	['question_type_global', 'question_single_statement']
what do i need [Nightgown] for?	"linda's wedding", 'my honeymoon'	['question_type_local']
what are the department stores?	'marshalls'	['question_type_global', 'question_single_statement']
what neighborhood is [2nd Avenue] in?	'Homewood West'	['question_type_local']
what are the stores on [2nd Avenue]?	'marshalls'	['question_type_global', 'question_single_statement']
[Brook Lane] is in [Elliott]
what event do I need to buy [strawberry] for	"wendy's visit tomorrow"	['question_type_local']
why do i need to buy [strawberry]?	"wendy's visit tomorrow"	['question_type_local']
add [lamp] and [key chain] to my shopping list for [linda's wedding]
what things did i get for [linda's wedding]	'shoes'	['question_type_local']
what [appliances] do i need to buy?	'Box mangle', 'Mousetrap', 'Window fan'	['question_type_global', 'question_two_hop_statement']
why do i need to buy [key chain]?	"linda's wedding"	['question_type_local']
show me all of the stores	'marshalls'	['question_type_global', 'question_single_statement']
what do i need [key chain] for?	"linda's wedding"	['question_type_local']
for example [Clothing] are [Swimming Shorts] and [Hoody]
what kind of [fruit] do I need to get?	'strawberry'	['question_type_global', 'question_two_hop_statement']
[kumquat] and [apricot] are both examples of [Fruit]
what kind of [gifts] do I need to get?	'key chain', 'lamp'	['question_type_global', 'question_two_hop_statement']
show me all of the stores on [2nd Avenue]	'marshalls'	['question_type_global', 'question_single_statement']
get rid of [Nightgown] from my shopping list for [my honeymoon]
i need to get [key chain] for [my honeymoon]
what items did i already get for [my honeymoon]?	'shoes', 'Box mangle', 'Shoes', 'Nightgown'	['question_type_local']
add [Hoody] and [Overalls] to my shopping list for [that event]
What did I already buy for [my honeymoon]?	'shoes', 'Box mangle', 'Shoes', 'Nightgown'	['question_type_local']
make sure to buy [Swimming Shorts] for [my honeymoon]
what items did i already get for [this event]?	'shoes', 'Box mangle', 'Shoes', 'Nightgown'	['question_type_local']
add [lamp] to my shopping list for [that event]
what kind of [appliances] do I need to get?	'Box mangle', 'Mousetrap', 'Window fan'	['question_type_global', 'question_two_hop_statement']
what are the stores?	'marshalls'	['question_type_global', 'question_single_statement']
Just arrived to [Elliott]
here are some examples of [Gift]: [mirror], [model car] and [balloon]
what stores are located on [2nd Avenue]?	'marshalls'	['question_type_local']
what department stores are there	'marshalls'	['question_type_global', 'question_single_statement']
what are the things that i need to get?	'key chain', 'lamp', 'Box mangle', 'Mousetrap', 'Shoes', 'Nightgown', 'strawberry', 'Window fan', 'Overalls', 'Swimming Shorts', 'Hoody'	['question_type_global', 'question_single_statement']
[Paprika] and [Spinach] are types of [Vegetables]
[Grove Avenue] is on the outskirts of [Homewood West]
what neighborhood is [this street] in?	'Homewood West'	['question_type_local']
show me all of the department stores	'marshalls'	['question_type_global', 'question_single_statement']
[Route 64] is in [Elliott]
show me all stores	'marshalls'	['question_type_global', 'question_single_statement']
show me all of the stores on [2nd Avenue]	'marshalls'	['question_type_global', 'question_single_statement']
what items do I need to get?	'key chain', 'lamp', 'Box mangle', 'Mousetrap', 'Shoes', 'Nightgown', 'strawberry', 'Window fan', 'Overalls', 'Swimming Shorts', 'Hoody'	['question_type_global', 'question_single_statement']
what [gifts] do i need to buy?	'key chain', 'lamp'	['question_type_global', 'question_two_hop_statement']
what do i need [Mousetrap] for?	'my honeymoon'	['question_type_local']
what stores are there on [2nd Avenue]?	'marshalls'	['question_type_global', 'question_single_statement']
are there any [appliances] that i need to get?	'Box mangle', 'Mousetrap', 'Window fan'	['question_type_global', 'question_two_hop_statement']
What do I need to buy [Nightgown] for?	"linda's wedding"	['question_type_local']
show me all stores	'marshalls'	['question_type_global', 'question_single_statement']
what are the department stores on [2nd Avenue]?	'marshalls'	['question_type_global', 'question_single_statement']
Do I need to buy any [appliances]?	'Box mangle', 'Mousetrap', 'Window fan'	['question_type_global', 'question_two_hop_statement']
what things did i get for [wendy's visit tomorrow]	'Quandong', 'Radish', 'Celeriac', 'Goose', 'tangerine', 'Beef liver', 'Pumpkin', 'jujube', 'Cornish Hen', 'Beef tongue', 'Ham', 'avocado', 'guava', 'papaya'	['question_type_local']
what neighborhood am I currently in?	'Elliott'	['question_type_local']
show me all department stores near [2nd Avenue]	'marshalls'	['question_type_global', 'question_single_statement']
[rubber duck] is a [Gift]
what neighborhood is [that street] located in?	'Elliott'	['question_type_local']
what are the stores?	'marshalls'	['question_type_global', 'question_single_statement']
here are some examples of [Vegetables]: [Butternut squash], [Bean sprouts] and [Thyme]
there is a [department store] called [marshalls] on [Grove Avenue]
[Beverage opener], [Air conditioner] and [Mousetrap] are all on sale at [that department store]
What stores is [Mousetrap] on sale at	'marshalls'	['question_type_local']
Do i have any [clothing] on my shopping list?	'Shoes', 'Nightgown', 'Overalls', 'Swimming Shorts', 'Hoody'	['question_type_global', 'question_two_hop_statement']
what are the department stores?	'marshalls'	['question_type_global', 'question_single_statement']
what do i need [Swimming Shorts] for?	'my honeymoon'	['question_type_local']
show me all department stores	'marshalls'	['question_type_global', 'question_single_statement']
what are the things that i need to get?	'key chain', 'lamp', 'Box mangle', 'Mousetrap', 'Shoes', 'Nightgown', 'strawberry', 'Window fan', 'Overalls', 'Swimming Shorts', 'Hoody'	['question_type_global', 'question_single_statement']
show me all stores near [Grove Avenue] that have a sale	'marshalls'	['question_type_global', 'question_two_hop_statement']
what [gifts] do i need to buy?	'key chain', 'lamp'	['question_type_global', 'question_two_hop_statement']
Do I need to buy any [gifts]?	'key chain', 'lamp'	['question_type_global', 'question_two_hop_statement']
what neighborhood am I in?	'Elliott'	['question_type_local']
what kind of [clothing] do I need to get?	'Shoes', 'Nightgown', 'Overalls', 'Swimming Shorts', 'Hoody'	['question_type_global', 'question_two_hop_statement']
what stores are there on [2nd Avenue]?	'marshalls'	['question_type_global', 'question_single_statement']
Do I need to buy any [fruit]?	'strawberry'	['question_type_global', 'question_two_hop_statement']
Do i have any [gifts] on my shopping list?	'key chain', 'lamp'	['question_type_global', 'question_two_hop_statement']
show me all of the stores	'marshalls'	['question_type_global', 'question_single_statement']
what kind of [gifts] do I need to get?	'key chain', 'lamp'	['question_type_global', 'question_two_hop_statement']
there is a [supermarket] called [food lion] on [Grant Avenue]
is there a sale on [Air conditioner] anywhere?	'marshalls'	['question_type_local']
show me all stores on [Grove Avenue] that currently have a sale	'marshalls'	['question_type_global', 'question_two_hop_statement']
remove [strawberry] from the list for [wendy's visit tomorrow]
i need to get [plum] for [wendy's visit tomorrow]
is there any [appliances] that I have to buy currently are on sale?	'Mousetrap'	['question_type_global', 'question_three_hop_statement']
is there a sale on any [appliances] on my shopping list?	'Mousetrap'	['question_type_global', 'question_three_hop_statement']
What do I need to buy [it] for?	"wendy's visit tomorrow"	['question_type_local']
what stores are there that I taught you?	'marshalls', 'food lion'	['question_type_global', 'question_single_statement']
what event do I need to buy [Box mangle] for	"linda's wedding"	['question_type_local']
get rid of [this fruit] from my shopping list for [this event]
what are the things that I need to get?	'key chain', 'lamp', 'Box mangle', 'Mousetrap', 'Shoes', 'Nightgown', 'Window fan', 'Overalls', 'Swimming Shorts', 'Hoody'	['question_type_global', 'question_single_statement']
what do i need to buy?	'key chain', 'lamp', 'Box mangle', 'Mousetrap', 'Shoes', 'Nightgown', 'Window fan', 'Overalls', 'Swimming Shorts', 'Hoody'	['question_type_global', 'question_single_statement']
what department stores on [Grove Avenue] have a sale?	'marshalls'	['question_type_global', 'question_two_hop_statement']
show me all of the stores on [Grove Avenue]	'marshalls'	['question_type_global', 'question_single_statement']
what neighborhood is [Brook Lane] located in?	'Elliott'	['question_type_local']
is there a sale on any [appliances] on my shopping list?	'Mousetrap'	['question_type_global', 'question_three_hop_statement']
is there a sale on any items on my shopping list?	'Mousetrap'	['question_type_global', 'question_two_hop_statement']
[Parsnip] is a kind of [Vegetables]
show me all of the department stores on [2nd Avenue]	'marshalls'	['question_type_global', 'question_single_statement']
what stores on [Grove Avenue] have a sale?	'marshalls'	['question_type_global', 'question_two_hop_statement']
what [clothing] do i need to buy?	'Shoes', 'Nightgown', 'Overalls', 'Swimming Shorts', 'Hoody'	['question_type_global', 'question_two_hop_statement']
what are the stores?	'marshalls', 'food lion'	['question_type_global', 'question_single_statement']
is there any [appliances] on my list that's on sale somewhere?	'Mousetrap'	['question_type_global', 'question_three_hop_statement']
what stores on [Grove Avenue] have a sale on [Air conditioner]?	'marshalls'	['question_type_global', 'question_two_hop_statement']
show me all of the department stores	'marshalls'	['question_type_global', 'question_single_statement']
show me all of the stores	'marshalls', 'food lion'	['question_type_global', 'question_single_statement']
what kind of [appliances] do I need to get?	'Box mangle', 'Mousetrap', 'Window fan'	['question_type_global', 'question_two_hop_statement']
i need to make sure to get [shawl] for [my honeymoon]
show me all of the supermarkets	'food lion'	['question_type_global', 'question_single_statement']
what neighborhood is [2nd Avenue] located in?	'Homewood West'	['question_type_local']
Do I need to buy any [clothing]?	'Shoes', 'Nightgown', 'Overalls', 'Swimming Shorts', 'Hoody'	['question_type_global', 'question_two_hop_statement']
what neighborhood am I in?	'Elliott'	['question_type_local']
Do i have any [clothing] on my shopping list?	'Shoes', 'Nightgown', 'Overalls', 'Swimming Shorts', 'Hoody'	['question_type_global', 'question_two_hop_statement']
show me all supermarkets that i tought you	'food lion'	['question_type_global', 'question_single_statement']
What did I already buy for [that event]?	'shoes', 'Box mangle', 'Shoes', 'Nightgown'	['question_type_local']
are there any items on my shopping list that there is a sale on?	'Mousetrap'	['question_type_global', 'question_two_hop_statement']
i am pretty sure that [Cedar Court] is in [Fairywood]
what do i need [this thing] for?	'my honeymoon'	['question_type_local']
what are the department stores on [Grove Avenue]?	'marshalls'	['question_type_global', 'question_single_statement']
what items that I have to buy currently are on sale?	'Mousetrap'	['question_type_global', 'question_two_hop_statement']
show me all department stores near [Grove Avenue]	'marshalls'	['question_type_global', 'question_single_statement']
are there any [appliances] that i need to get?	'Box mangle', 'Mousetrap', 'Window fan'	['question_type_global', 'question_two_hop_statement']
show me all department stores	'marshalls'	['question_type_global', 'question_single_statement']
show me all supermarkets near [Grant Avenue]	'food lion'	['question_type_global', 'question_single_statement']
is there any [appliances] that I have to buy currently are on sale?	'Mousetrap'	['question_type_global', 'question_three_hop_statement']
show me all stores	'marshalls', 'food lion'	['question_type_global', 'question_single_statement']
Do I need to buy any [clothing]?	'Shoes', 'Nightgown', 'Overalls', 'Swimming Shorts', 'Hoody'	['question_type_global', 'question_two_hop_statement']
what items do I need to get?	'shawl', 'key chain', 'lamp', 'Box mangle', 'Mousetrap', 'Shoes', 'Nightgown', 'Window fan', 'Overalls', 'Swimming Shorts', 'Hoody'	['question_type_global', 'question_single_statement']
what neighborhood is [Grant Avenue] in?	'Fairywood'	['question_type_local']
what stores on [Grove Avenue] have a sale on [appliances]?	'marshalls'	['question_type_global', 'question_three_hop_statement']
get rid of [key chain] and [Shoes] from my shopping for [linda's wedding]
what do I need for [linda's wedding]?	'lamp', 'Box mangle', 'Nightgown', 'Window fan'	['question_type_local']
what department stores are there	'marshalls'	['question_type_global', 'question_single_statement']
what are the things that I need to get?	'shawl', 'key chain', 'lamp', 'Box mangle', 'Mousetrap', 'Nightgown', 'Window fan', 'Overalls', 'Swimming Shorts', 'Hoody'	['question_type_global', 'question_single_statement']
show me all stores near [Grove Avenue] that have a sale on [appliances]	'marshalls'	['question_type_global', 'question_three_hop_statement']
why do i need to buy [Mousetrap]?	'my honeymoon'	['question_type_local']
what department stores are there on [2nd Avenue]?	'marshalls'	['question_type_global', 'question_single_statement']
show me all of the department stores	'marshalls'	['question_type_global', 'question_single_statement']
what event do I need to buy [lamp] for	"linda's wedding", 'my honeymoon'	['question_type_local']
What do I need to buy [lamp] for?	"linda's wedding", 'my honeymoon'	['question_type_local']
what are the department stores?	'marshalls'	['question_type_global', 'question_single_statement']
what are the stores on [Grant Avenue]?	'food lion'	['question_type_local']
show me all department stores near [Grove Avenue] that have a sale	'marshalls'	['question_type_global', 'question_two_hop_statement']
What stores is [Beverage opener] on sale at	'marshalls'	['question_type_local']
i absolutely must not forget to get [Air conditioner] for [my honeymoon]
is there a sale on any [appliances] on my shopping list?	'Mousetrap', 'Air conditioner'	['question_type_global', 'question_three_hop_statement']
What do I need to buy [Window fan] for?	"linda's wedding"	['question_type_local']
what is my shopping list?	'shawl', 'key chain', 'lamp', 'Box mangle', 'Mousetrap', 'Nightgown', 'Air conditioner', 'Window fan', 'Overalls', 'Swimming Shorts', 'Hoody'	['question_type_global', 'question_single_statement']
show me all supermarkets that i tought you	'food lion'	['question_type_global', 'question_single_statement']
i need to get [Grouse] and [Beef] for [wendy's visit tomorrow]
i just got [Grouse] for [wendy's visit tomorrow]
what things do I need to buy for [this event]	'Beef'	['question_type_local']
what neighborhood is [Grove Avenue] located in?	'Homewood West'	['question_type_local']
is there any [appliances] on my list that's on sale somewhere?	'Mousetrap', 'Air conditioner'	['question_type_global', 'question_three_hop_statement']
what kind of [appliances] do I need to get?	'Box mangle', 'Mousetrap', 'Air conditioner', 'Window fan'	['question_type_global', 'question_two_hop_statement']
add [apricot] and [kumquat] to my shopping list for [wendy's visit tomorrow]
what things do I need to buy for [wendy's visit tomorrow]	'Beef', 'kumquat', 'apricot'	['question_type_local']
Do I need to buy any [fruit]?	'kumquat', 'apricot'	['question_type_global', 'question_two_hop_statement']
what are the supermarkets on [Grant Avenue]?	'food lion'	['question_type_global', 'question_single_statement']
what are the stores on [Grant Avenue]?	'food lion'	['question_type_local']
what supermarkets are there?	'food lion'	['question_type_global', 'question_single_statement']
what event do I need to buy [Window fan] for	"linda's wedding"	['question_type_local']
is there anything that I need for [my honeymoon] that's on sale somewhere?	'Mousetrap', 'Air conditioner'	['question_type_global', 'question_two_hop_statement']
what are the things that i need to get?	'shawl', 'key chain', 'lamp', 'Box mangle', 'Mousetrap', 'Nightgown', 'Beef', 'Air conditioner', 'Window fan', 'Overalls', 'Swimming Shorts', 'Hoody', 'kumquat', 'apricot'	['question_type_global', 'question_single_statement']
why do i need to buy [apricot]?	"wendy's visit tomorrow"	['question_type_local']
what kind of [fruit] do I need to get?	'kumquat', 'apricot'	['question_type_global', 'question_two_hop_statement']
what items do I need to get?	'shawl', 'key chain', 'lamp', 'Box mangle', 'Mousetrap', 'Nightgown', 'Beef', 'Air conditioner', 'Window fan', 'Overalls', 'Swimming Shorts', 'Hoody', 'kumquat', 'apricot'	['question_type_global', 'question_single_statement']
Do I need to buy any [clothing]?	'Nightgown', 'Overalls', 'Swimming Shorts', 'Hoody'	['question_type_global', 'question_two_hop_statement']
what are the supermarkets?	'food lion'	['question_type_global', 'question_single_statement']
remove [apricot] from the list for [wendy's visit tomorrow]
Do i have any [gifts] on my shopping list?	'shawl', 'key chain', 'lamp'	['question_type_global', 'question_two_hop_statement']
show me all of the department stores on [Grove Avenue]	'marshalls'	['question_type_global', 'question_single_statement']
is there a sale on any items on my shopping list for [my honeymoon]?	'Mousetrap', 'Air conditioner'	['question_type_global', 'question_two_hop_statement']
add [blueberry] to my shopping list for [this event]
what things did i get for [this event]	'Quandong', 'Radish', 'Celeriac', 'Goose', 'tangerine', 'Beef liver', 'Pumpkin', 'jujube', 'Cornish Hen', 'Beef tongue', 'Ham', 'avocado', 'guava', 'papaya', 'strawberry', 'plum', 'Grouse', 'apricot'	['question_type_local']
are there any [appliances] on my shopping list that there is a sale on?	'Mousetrap', 'Air conditioner'	['question_type_global', 'question_three_hop_statement']
Where is [Air conditioner] on sale?	'marshalls'	['question_type_local']
what kind of [meat] do I need to get?	'Beef'	['question_type_global', 'question_two_hop_statement']
[apple] is a [Fruit]
i don't need [blueberry] and [kumquat] for [wendy's visit tomorrow] anymore
what items did i already get for [wendy's visit tomorrow]?	'Quandong', 'Radish', 'Celeriac', 'Goose', 'tangerine', 'Beef liver', 'Pumpkin', 'jujube', 'Cornish Hen', 'Beef tongue', 'Ham', 'avocado', 'guava', 'papaya', 'strawberry', 'plum', 'blueberry', 'Grouse', 'kumquat', 'apricot'	['question_type_local']
what stores near [Grove Avenue] have an ongoing sale on [appliances]?	'marshalls'	['question_type_global', 'question_three_hop_statement']
show me all stores near [Grove Avenue] that have a sale on [appliances]	'marshalls'	['question_type_global', 'question_three_hop_statement']
for example [Fruit] are [cantaloupe] and [coconut]
what items that I have to buy currently are on sale?	'Mousetrap', 'Air conditioner'	['question_type_global', 'question_two_hop_statement']
what are the department stores?	'marshalls'	['question_type_global', 'question_single_statement']
what do i need to buy?	'shawl', 'key chain', 'lamp', 'Box mangle', 'Mousetrap', 'Nightgown', 'Beef', 'Air conditioner', 'Window fan', 'Overalls', 'Swimming Shorts', 'Hoody'	['question_type_global', 'question_single_statement']
is there any [appliances] that I have to buy currently are on sale?	'Mousetrap', 'Air conditioner'	['question_type_global', 'question_three_hop_statement']
why do i need to buy [Hoody]?	'my honeymoon'	['question_type_local']
what event do I need to buy [Box mangle] for	"linda's wedding"	['question_type_local']
are there any [appliances] on my shopping list that there is a sale on?	'Mousetrap', 'Air conditioner'	['question_type_global', 'question_three_hop_statement']
what items that I have to buy for [my honeymoon] currently are on sale?	'Mousetrap', 'Air conditioner'	['question_type_global', 'question_two_hop_statement']
show me all of the stores on [2nd Avenue]	'marshalls'	['question_type_global', 'question_single_statement']
show me all stores	'marshalls', 'food lion'	['question_type_global', 'question_single_statement']
what items that I have to buy currently are on sale?	'Mousetrap', 'Air conditioner'	['question_type_global', 'question_two_hop_statement']
is there a sale on any items on my shopping list for [my honeymoon]?	'Mousetrap', 'Air conditioner'	['question_type_global', 'question_two_hop_statement']
what are the department stores?	'marshalls'	['question_type_global', 'question_single_statement']
show me all department stores near [Grove Avenue] that have a sale	'marshalls'	['question_type_global', 'question_two_hop_statement']
Do i have any [meat] on my shopping list?	'Beef'	['question_type_global', 'question_two_hop_statement']
are there any [appliances] that i need to get?	'Box mangle', 'Mousetrap', 'Air conditioner', 'Window fan'	['question_type_global', 'question_two_hop_statement']
there is a [supermarket] called [food lion] that I shop in pretty often
[strawberry] and [kumquat] are all on sale at [this store]
[strawberry] and [kumquat] are no longer on sale at [food lion that I last mentioned]
this particular [food lion that I last mentioned] is located on [Route 64]
is there anything that I need for [my honeymoon] that's on sale somewhere?	'Mousetrap', 'Air conditioner'	['question_type_global', 'question_two_hop_statement']
what are the supermarkets on [Grant Avenue]?	'food lion'	['question_type_global', 'question_single_statement']
show me all stores near [Grant Avenue]	'food lion'	['question_type_global', 'question_single_statement']
what neighborhood is [this street] located in?	'Elliott'	['question_type_local']
show me all of the supermarkets	'food lion'	['question_type_global', 'question_single_statement']
[this supermarket] has [papaya] and [coconut] on sale!
what is on sale at [food lion on Route 64]?	'papaya', 'coconut'	['question_type_local']
what supermarkets are there?	'food lion'	['question_type_global', 'question_single_statement']
is there a sale on [coconut] anywhere?	'food lion'	['question_type_local']
is there any [appliances] on my list that's on sale somewhere?	'Mousetrap', 'Air conditioner'	['question_type_global', 'question_three_hop_statement']
Do i have any [clothing] on my shopping list?	'Nightgown', 'Overalls', 'Swimming Shorts', 'Hoody'	['question_type_global', 'question_two_hop_statement']
What do I need to buy for [linda's wedding]?	'lamp', 'Box mangle', 'Nightgown', 'Window fan'	['question_type_local']
show me all of the department stores on [2nd Avenue]	'marshalls'	['question_type_global', 'question_single_statement']
is there a store near my location is having a sale on [fruit]?	'food lion'	['question_type_global', 'question_four_hop_statement']
what are the stores on [2nd Avenue]?	'marshalls'	['question_type_global', 'question_single_statement']
what supermarkets near [Route 64] have an ongoing sale?	'food lion'	['question_type_global', 'question_two_hop_statement']
what stores are there that I taught you?	'marshalls', 'food lion'	['question_type_global', 'question_single_statement']
what stores are located on [Grove Avenue]?	'marshalls'	['question_type_local']
is there any [appliances] that I have to buy currently are on sale?	'Mousetrap', 'Air conditioner'	['question_type_global', 'question_three_hop_statement']
is there anything on sale at a store nearby?	'papaya', 'coconut'	['question_type_global', 'question_three_hop_statement']
what are the stores on [Grant Avenue]?	'food lion'	['question_type_global', 'question_single_statement']
is there a sale on any items on my shopping list?	'Mousetrap', 'Air conditioner'	['question_type_global', 'question_two_hop_statement']
what supermarkets near [Route 64] have an ongoing sale?	'food lion'	['question_type_global', 'question_two_hop_statement']
What did I already buy for [wendy's visit tomorrow]?	'Quandong', 'Radish', 'Celeriac', 'Goose', 'tangerine', 'Beef liver', 'Pumpkin', 'jujube', 'Cornish Hen', 'Beef tongue', 'Ham', 'avocado', 'guava', 'papaya', 'strawberry', 'plum', 'blueberry', 'Grouse', 'kumquat', 'apricot'	['question_type_local']
are there any stores nearby that have a sale?	'food lion'	['question_type_global', 'question_three_hop_statement']
what are the stores?	'marshalls', 'food lion'	['question_type_global', 'question_single_statement']
what event do I need to buy [Window fan] for	"linda's wedding"	['question_type_local']
does any store nearby have [coconut] on sale?	'food lion'	['question_type_global', 'question_three_hop_statement']
what supermarkets are there on [Route 64]?	'food lion'	['question_type_global', 'question_single_statement']
what items are on sale at nearby stores?	'papaya', 'coconut'	['question_type_global', 'question_three_hop_statement']
what kind of [clothing] do I need to get?	'Nightgown', 'Overalls', 'Swimming Shorts', 'Hoody'	['question_type_global', 'question_two_hop_statement']
What stores is [papaya] on sale at	'food lion'	['question_type_local']
what items that I have to buy currently are on sale?	'Mousetrap', 'Air conditioner'	['question_type_global', 'question_two_hop_statement']
is there a store nearby with a sale going on right now?	'food lion'	['question_type_global', 'question_three_hop_statement']
What stores is [coconut] on sale at	'food lion'	['question_type_local']
what stores on [Grove Avenue] have a sale?	'marshalls'	['question_type_global', 'question_two_hop_statement']
what supermarkets are there?	'food lion'	['question_type_global', 'question_single_statement']
I think I am in [Homewood West]
what neighborhood am I currently in?	'Homewood West'	['question_type_local']
