don't forget about an upcoming [my engagement]
remember that i have [dinner with ben]
i often shop at [gemco], which is my local [department store]
[Suit] is a type of [Clothing]
show me all department stores	'gemco'	['question_type_global', 'question_single_statement']
what are the stores?	'gemco'	['question_type_global', 'question_single_statement']
[weistein's] is a [department store]
[that item] is on sale at [that store]
[this clothing] is not on sale at [this department store]
i think [York Road] is in [Fairmount]
[Electric water boiler], [Oven] and [Microwave oven] are kinds of [Appliance]
[Grand Avenue] is on the outskirts of [Fairmount]
[Oven], [Electric water boiler] and [Microwave oven] are on sale at [gemco]
[Microwave oven], [Oven] and [Electric water boiler] are no longer on sale at [gemco]
this particular [gemco] is located on [York Road]
[this store] has [Electric water boiler], [Microwave oven] and [Oven] on sale!
what is on sale at [gemco]?	'Electric water boiler', 'Oven', 'Microwave oven'	['question_type_local']
what department stores on [York Road] have a sale?	'gemco'	['question_type_global', 'question_two_hop_statement']
show me all stores on [York Road] that currently have a sale on [Microwave oven]	'gemco'	['question_type_global', 'question_two_hop_statement']
[Humidifier] is a kind of [Appliance]
what's currently on sale at [gemco]?	'Electric water boiler', 'Oven', 'Microwave oven'	['question_type_local']
what stores on [York Road] have a sale?	'gemco'	['question_type_global', 'question_two_hop_statement']
is there a sale on [Oven] anywhere?	'gemco'	['question_type_local']
show me all of the stores	'gemco', "weistein's"	['question_type_global', 'question_single_statement']
show me all stores on [York Road] that currently have a sale on [Electric water boiler]	'gemco'	['question_type_global', 'question_two_hop_statement']
what are the department stores?	'gemco', "weistein's"	['question_type_global', 'question_single_statement']
What stores is [Microwave oven] on sale at	'gemco'	['question_type_local']
what is on sale at [gemco]?	'Electric water boiler', 'Oven', 'Microwave oven'	['question_type_local']
show me all stores near [York Road] that have a sale on [Microwave oven]	'gemco'	['question_type_global', 'question_two_hop_statement']
[Skirt], [Socks] and [Sandals] are all different types of [Clothing]
what stores near [York Road] have an ongoing sale on [Oven]?	'gemco'	['question_type_global', 'question_two_hop_statement']
what stores are there that I taught you?	'gemco', "weistein's"	['question_type_global', 'question_single_statement']
[pomegranate], [lime] and [kiwi] are all good examples of [Fruit]
there is a [supermarket] called [trader joe's] on [York Road]
show me all stores near [York Road] that have a sale on [appliances]	'gemco'	['question_type_global', 'question_three_hop_statement']
this specific [weistein's] is on [Grand Avenue]
what stores are on [that street]?	"weistein's"	['question_type_local']
[Beef tongue] is a [Meat]
[Lentils], [Bitter Melon] and [Red pepper] are all types of [Vegetables]
show me all of the supermarkets	"trader joe's"	['question_type_global', 'question_single_statement']
what supermarkets are there on [York Road]?	"trader joe's"	['question_type_global', 'question_single_statement']
what stores are located on [York Road]?	'gemco', "trader joe's"	['question_type_local']
what stores near [York Road] have an ongoing sale on [Microwave oven]?	'gemco'	['question_type_global', 'question_two_hop_statement']
show me all of the supermarkets on [York Road]	"trader joe's"	['question_type_global', 'question_single_statement']
what neighborhood is [York Road] located in?	'Fairmount'	['question_type_local']
what are the supermarkets on [York Road]?	"trader joe's"	['question_type_global', 'question_single_statement']
[grape] is a kind of [Fruit]
what is on sale at [gemco]?	'Electric water boiler', 'Oven', 'Microwave oven'	['question_type_local']
what supermarkets are there?	"trader joe's"	['question_type_global', 'question_single_statement']
what stores are there that I taught you?	'gemco', "weistein's", "trader joe's"	['question_type_global', 'question_single_statement']
what department stores are there	'gemco', "weistein's"	['question_type_global', 'question_single_statement']
what are the stores?	'gemco', "weistein's", "trader joe's"	['question_type_global', 'question_single_statement']
show me all stores on [York Road] that currently have a sale on [Oven]	'gemco'	['question_type_global', 'question_two_hop_statement']
what neighborhood is [Grand Avenue] located in?	'Fairmount'	['question_type_local']
show me all supermarkets that i tought you	"trader joe's"	['question_type_global', 'question_single_statement']
is there a sale on [Microwave oven] anywhere?	'gemco'	['question_type_local']
[star fruit] is a type of [Fruit]
what stores are there that I taught you?	'gemco', "weistein's", "trader joe's"	['question_type_global', 'question_single_statement']
show me all of the department stores	'gemco', "weistein's"	['question_type_global', 'question_single_statement']
there is a [supermarket] called [walgreens] on [York Road]
[4th Street West] is located in the [Uptown] neighborhood
[Bitter Melon] and [Lentils] are all on sale at [walgreens]
[walgreens] doesn't have [Lentils] on sale anymore
show me all department stores near [York Road]	'gemco'	['question_type_global', 'question_single_statement']
show me all of the stores on [York Road]	'gemco', "trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
show me all of the stores	'gemco', "weistein's", "trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
show me all of the supermarkets	"trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
what are the stores?	'gemco', "weistein's", "trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
show me all stores on [York Road] that currently have a sale on [Oven]	'gemco'	['question_type_global', 'question_two_hop_statement']
what stores near [York Road] have an ongoing sale on [Microwave oven]?	'gemco'	['question_type_global', 'question_two_hop_statement']
what department stores are there on [Grand Avenue]?	"weistein's"	['question_type_global', 'question_single_statement']
[date], [kumquat] and [apple] are all types of [Fruit]
[Opossum] is a [Meat]
what are the department stores?	'gemco', "weistein's"	['question_type_global', 'question_single_statement']
what items are on sale at [gemco]?	'Electric water boiler', 'Oven', 'Microwave oven'	['question_type_local']
is there a sale on [Electric water boiler] anywhere?	'gemco'	['question_type_local']
show me all of the stores	'gemco', "weistein's", "trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
[Skirt] and [Socks] are on sale at [gemco]
show me all stores on [York Road] that currently have a sale	'gemco', 'walgreens'	['question_type_global', 'question_two_hop_statement']
show me all stores on [York Road] that currently have a sale on [vegetables]	'walgreens'	['question_type_global', 'question_three_hop_statement']
[Beef tongue] and [Opossum] are on sale at [walgreens]
show me all of the stores on [York Road]	'gemco', "trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
show me all of the stores on [Grand Avenue]	"weistein's"	['question_type_global', 'question_single_statement']
What stores is [Opossum] on sale at	'walgreens'	['question_type_local']
what neighborhood is [Grand Avenue] located in?	'Fairmount'	['question_type_local']
is there a sale on [Electric water boiler] anywhere?	'gemco'	['question_type_local']
what are the supermarkets?	"trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
what neighborhood is [Grand Avenue] in?	'Fairmount'	['question_type_local']
what stores near [York Road] have an ongoing sale on [meat]?	'walgreens'	['question_type_global', 'question_three_hop_statement']
What stores is [Skirt] on sale at	'gemco'	['question_type_local']
what department stores on [York Road] have a sale?	'gemco'	['question_type_global', 'question_two_hop_statement']
show me all supermarkets that i tought you	"trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
show me all of the supermarkets on [York Road]	"trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
[bookmark], [purse] and [ipod] are kinds of [Gift]
what stores near [York Road] have an ongoing sale on [vegetables]?	'walgreens'	['question_type_global', 'question_three_hop_statement']
show me all of the stores	'gemco', "weistein's", "trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
show me all department stores on [York Road] that currently have a sale	'gemco'	['question_type_global', 'question_two_hop_statement']
[ipod], [bookmark] and [purse] are on sale at [gemco]
[Marshall Street] is in [Asian District]
what neighborhood is [this street] located in?	'Asian District'	['question_type_local']
show me all supermarkets on [York Road] that currently have a sale	'walgreens'	['question_type_global', 'question_two_hop_statement']
What stores is [Oven] on sale at	'gemco'	['question_type_local']
[weistein's] has [ipod], [purse] and [bookmark] on sale!
[weistein's] no longer has [purse], [bookmark] and [ipod] on sale
show me all stores	'gemco', "weistein's", "trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
show me all stores near [York Road] that have a sale	'gemco', 'walgreens'	['question_type_global', 'question_two_hop_statement']
[Suit] and [Sandals] are on sale at [gemco]
what's currently on sale at [gemco]?	'Suit', 'Electric water boiler', 'Oven', 'Microwave oven', 'Skirt', 'Socks', 'Sandals', 'bookmark', 'purse', 'ipod'	['question_type_local']
show me all stores near [York Road] that have a sale on [vegetables]	'walgreens'	['question_type_global', 'question_three_hop_statement']
what neighborhood is [York Road] located in?	'Fairmount'	['question_type_local']
Where is [Skirt] on sale?	'gemco'	['question_type_local']
[coconut] and [avocado] are both examples of [Fruit]
i think [Surrey Lane] is in [Fairmount]
show me all stores on [York Road] that currently have a sale on [appliances]	'gemco'	['question_type_global', 'question_three_hop_statement']
what stores near [York Road] have an ongoing sale?	'gemco', 'walgreens'	['question_type_global', 'question_two_hop_statement']
what department stores near [York Road] have an ongoing sale?	'gemco'	['question_type_global', 'question_two_hop_statement']
is there a sale on [Microwave oven] anywhere?	'gemco'	['question_type_local']
what department stores are there on [Grand Avenue]?	"weistein's"	['question_type_global', 'question_single_statement']
show me all stores near [York Road] that have a sale on [meat]	'walgreens'	['question_type_global', 'question_three_hop_statement']
what stores on [York Road] have a sale on [ipod]?	'gemco'	['question_type_global', 'question_two_hop_statement']
show me all stores near [York Road] that have a sale on [ipod]	'gemco'	['question_type_global', 'question_two_hop_statement']
show me all stores on [York Road] that currently have a sale on [vegetables]	'walgreens'	['question_type_global', 'question_three_hop_statement']
what supermarkets on [York Road] have a sale?	'walgreens'	['question_type_global', 'question_two_hop_statement']
what stores near [York Road] have an ongoing sale on [clothing]?	'gemco'	['question_type_global', 'question_three_hop_statement']
show me all stores on [York Road] that currently have a sale on [gifts]	'gemco'	['question_type_global', 'question_three_hop_statement']
what is on sale at [gemco]?	'Suit', 'Electric water boiler', 'Oven', 'Microwave oven', 'Skirt', 'Socks', 'Sandals', 'bookmark', 'purse', 'ipod'	['question_type_local']
show me all supermarkets on [York Road] that currently have a sale	'walgreens'	['question_type_global', 'question_two_hop_statement']
show me all of the supermarkets	"trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
[orange] is a [Fruit]
what supermarkets near [York Road] have an ongoing sale?	'walgreens'	['question_type_global', 'question_two_hop_statement']
what are the supermarkets?	"trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
what department stores on [York Road] have a sale?	'gemco'	['question_type_global', 'question_two_hop_statement']
show me all of the supermarkets on [York Road]	"trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
show me all department stores near [Grand Avenue]	"weistein's"	['question_type_global', 'question_single_statement']
here are some examples of [Clothing]: [Sweatshirt], [Thong] and [Tie]
show me all supermarkets near [York Road]	"trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
What stores is [bookmark] on sale at	'gemco'	['question_type_local']
what stores are there that I taught you?	'gemco', "weistein's", "trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
there is a [department store] called [bloomingdale's] that I shop in pretty often
this specific [bloomingdale's] is on [York Road]
[bloomingdale's] has [Tie], [Socks] and [Suit] on sale!
[Socks], [Suit] and [Tie] are no longer on sale at [bloomingdale's]
[purse], [ipod] and [bookmark] are on sale at [weistein's]
[weistein's] no longer has [bookmark] and [ipod] on sale!
what items are on sale at [weistein's]?	'purse'	['question_type_local']
what are the department stores on [York Road]?	'gemco', "bloomingdale's"	['question_type_global', 'question_single_statement']
show me all stores on [Grand Avenue] that currently have a sale on [gifts]	"weistein's"	['question_type_global', 'question_three_hop_statement']
show me all of the department stores	'gemco', "weistein's", "bloomingdale's"	['question_type_global', 'question_single_statement']
show me all supermarkets that i tought you	"trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
[Microwave oven], [Oven] and [Humidifier] are all on sale at [bloomingdale's]
some example of [Gift] are [phone] and [blanket]
[peach], [grapefruit] and [pear] are all different types of [Fruit]
what stores on [York Road] have a sale on [meat]?	'walgreens'	['question_type_global', 'question_three_hop_statement']
show me all supermarkets near [York Road]	"trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
is there a sale on [Socks] anywhere?	'gemco'	['question_type_local']
show me all stores near [Grand Avenue] that have a sale	"weistein's"	['question_type_global', 'question_two_hop_statement']
[Blender] is a type of [Appliance]
what is on sale at [bloomingdale's]?	'Oven', 'Microwave oven', 'Humidifier'	['question_type_local']
what are the department stores?	'gemco', "weistein's", "bloomingdale's"	['question_type_global', 'question_single_statement']
show me all department stores near [Grand Avenue]	"weistein's"	['question_type_global', 'question_single_statement']
what department stores are there	'gemco', "weistein's", "bloomingdale's"	['question_type_global', 'question_single_statement']
What stores is [Beef tongue] on sale at	'walgreens'	['question_type_local']
[Bow Tie], [Shoes] and [Jeans] are all different types of [Clothing]
what are the department stores on [York Road]?	'gemco', "bloomingdale's"	['question_type_global', 'question_single_statement']
i am pretty sure that [Cambridge Court] is in [Fairmount]
what neighborhood is [that street] in?	'Fairmount'	['question_type_local']
show me all stores on [York Road] that currently have a sale on [vegetables]	'walgreens'	['question_type_global', 'question_three_hop_statement']
show me all supermarkets near [York Road]	"trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
show me all stores	'gemco', "weistein's", "trader joe's", 'walgreens', "bloomingdale's"	['question_type_global', 'question_single_statement']
show me all department stores near [Grand Avenue]	"weistein's"	['question_type_global', 'question_single_statement']
what neighborhood is [Cambridge Court] located in?	'Fairmount'	['question_type_local']
what supermarkets are there on [York Road]?	"trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
here are some examples of [Meat]: [Chicken], [Grouse] and [Veal]
[boom box] is a kind of [Gift]
what supermarkets are there?	"trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
what stores near [York Road] have an ongoing sale on [ipod]?	'gemco'	['question_type_global', 'question_two_hop_statement']
What stores is [ipod] on sale at	'gemco'	['question_type_local']
show me all of the stores	'gemco', "weistein's", "trader joe's", 'walgreens', "bloomingdale's"	['question_type_global', 'question_single_statement']
what department stores are there on [Grand Avenue]?	"weistein's"	['question_type_global', 'question_single_statement']
what are the department stores?	'gemco', "weistein's", "bloomingdale's"	['question_type_global', 'question_single_statement']
what is on sale at [walgreens]?	'Beef tongue', 'Bitter Melon', 'Opossum'	['question_type_local']
Where is [Sandals] on sale?	'gemco'	['question_type_local']
[Blender] is on sale at [gemco]
what items are on sale at [that department store]?	'Suit', 'Electric water boiler', 'Oven', 'Microwave oven', 'Skirt', 'Socks', 'Sandals', 'bookmark', 'purse', 'ipod', 'Blender'	['question_type_local']
show me all of the stores on [York Road]	'gemco', "trader joe's", 'walgreens', "bloomingdale's"	['question_type_global', 'question_single_statement']
Where is [that item] on sale?	'gemco'	['question_type_local']
what are the stores?	'gemco', "weistein's", "trader joe's", 'walgreens', "bloomingdale's"	['question_type_global', 'question_single_statement']
show me all supermarkets near [York Road]	"trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
what stores near [York Road] have an ongoing sale on [clothing]?	'gemco'	['question_type_global', 'question_three_hop_statement']
is there a sale on [Electric water boiler] anywhere?	'gemco'	['question_type_local']
what are the supermarkets on [York Road]?	"trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
what supermarkets are there?	"trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
[Thong] is on sale at [gemco]
what is on sale at [that department store]?	'Suit', 'Electric water boiler', 'Oven', 'Microwave oven', 'Skirt', 'Socks', 'Sandals', 'bookmark', 'purse', 'ipod', 'Thong', 'Blender'	['question_type_local']
what are the stores?	'gemco', "weistein's", "trader joe's", 'walgreens', "bloomingdale's"	['question_type_global', 'question_single_statement']
show me all stores near [Grand Avenue]	"weistein's"	['question_type_global', 'question_single_statement']
what supermarkets on [York Road] have a sale?	'walgreens'	['question_type_global', 'question_two_hop_statement']
[Socks], [Sweatshirt] and [that clothing] are on sale at [weistein's]
[Sweatshirt], [purse] and [Thong] stopped being on sale at [weistein's]
show me all department stores near [Grand Avenue]	"weistein's"	['question_type_global', 'question_single_statement']
what stores near [York Road] have an ongoing sale on [gifts]?	'gemco'	['question_type_global', 'question_three_hop_statement']
[Skirret] is a [Vegetables]
show me all of the supermarkets	"trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
what stores near [York Road] have an ongoing sale on [meat]?	'walgreens'	['question_type_global', 'question_three_hop_statement']
what supermarkets are there on [York Road]?	"trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
what's currently on sale at [walgreens]?	'Beef tongue', 'Bitter Melon', 'Opossum'	['question_type_local']
[Humidifier], [Microwave oven] and [Blender] are on sale at [weistein's]
what's currently on sale at [weistein's]?	'Microwave oven', 'Humidifier', 'Socks', 'Blender'	['question_type_local']
show me all of the department stores	'gemco', "weistein's", "bloomingdale's"	['question_type_global', 'question_single_statement']
What stores is [Bitter Melon] on sale at	'walgreens'	['question_type_local']
Where is [Microwave oven] on sale?	'gemco', "bloomingdale's", "weistein's"	['question_type_local']
what department stores are there	'gemco', "weistein's", "bloomingdale's"	['question_type_global', 'question_single_statement']
What stores is [Blender] on sale at	'gemco', "weistein's"	['question_type_local']
show me all stores near [Grand Avenue] that have a sale	"weistein's"	['question_type_global', 'question_two_hop_statement']
what are the department stores?	'gemco', "weistein's", "bloomingdale's"	['question_type_global', 'question_single_statement']
what neighborhood is [York Road] located in?	'Fairmount'	['question_type_local']
What stores is [Microwave oven] on sale at	'gemco', "bloomingdale's", "weistein's"	['question_type_local']
Where is [Microwave oven] on sale?	'gemco', "bloomingdale's", "weistein's"	['question_type_local']
[I] am currently on [4th Street West]
show me all department stores near [Grand Avenue] that have a sale	"weistein's"	['question_type_global', 'question_two_hop_statement']
show me all stores near [York Road] that have a sale on [meat]	'walgreens'	['question_type_global', 'question_three_hop_statement']
[Tie], [Skirt] and [Shoes] are all on sale at [weistein's]
what stores on [Grand Avenue] have a sale on [appliances]?	"weistein's"	['question_type_global', 'question_three_hop_statement']
[Back boiler], [Air purifier] and [Stove] are all types of [Appliance]
what are the supermarkets on [York Road]?	"trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
show me all department stores near [York Road]	'gemco', "bloomingdale's"	['question_type_global', 'question_single_statement']
what items are on sale at [walgreens]?	'Beef tongue', 'Bitter Melon', 'Opossum'	['question_type_local']
what supermarkets near [York Road] have an ongoing sale?	'walgreens'	['question_type_global', 'question_two_hop_statement']
show me all stores on [York Road] that currently have a sale	'gemco', 'walgreens', "bloomingdale's"	['question_type_global', 'question_two_hop_statement']
[phone] and [boom box] are on sale at [gemco]
is there a sale on [Skirt] anywhere?	'gemco', "weistein's"	['question_type_local']
show me all supermarkets on [York Road] that currently have a sale	'walgreens'	['question_type_global', 'question_two_hop_statement']
what supermarkets are there?	"trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
Where is [Opossum] on sale?	'walgreens'	['question_type_local']
what stores near [York Road] have an ongoing sale on [meat]?	'walgreens'	['question_type_global', 'question_three_hop_statement']
Where is [purse] on sale?	'gemco'	['question_type_local']
show me all department stores on [York Road] that currently have a sale	'gemco', "bloomingdale's"	['question_type_global', 'question_two_hop_statement']
[blanket] and [purse] are all on sale at [weistein's]
[Microwave oven] and [Tie] are no longer on sale at [weistein's]
what stores on [Grand Avenue] have a sale on [gifts]?	"weistein's"	['question_type_global', 'question_three_hop_statement']
what supermarkets are there on [York Road]?	"trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
show me all stores on [York Road] that currently have a sale on [appliances]	'gemco', "bloomingdale's"	['question_type_global', 'question_three_hop_statement']
show me all department stores near [Grand Avenue] that have a sale	"weistein's"	['question_type_global', 'question_two_hop_statement']
show me all of the stores	'gemco', "weistein's", "trader joe's", 'walgreens', "bloomingdale's"	['question_type_global', 'question_single_statement']
what neighborhood is [Cambridge Court] located in?	'Fairmount'	['question_type_local']
Where is [Beef tongue] on sale?	'walgreens'	['question_type_local']
show me all stores near [York Road] that have a sale on [Microwave oven]	'gemco', "bloomingdale's"	['question_type_global', 'question_two_hop_statement']
show me all stores	'gemco', "weistein's", "trader joe's", 'walgreens', "bloomingdale's"	['question_type_global', 'question_single_statement']
what stores on [Grand Avenue] have a sale on [clothing]?	"weistein's"	['question_type_global', 'question_three_hop_statement']
what are the supermarkets on [York Road]?	"trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
[Goose] is a type of [Meat]
what are the supermarkets?	"trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
show me all stores on [York Road] that currently have a sale on [meat]	'walgreens'	['question_type_global', 'question_three_hop_statement']
what supermarkets near [York Road] have an ongoing sale?	'walgreens'	['question_type_global', 'question_two_hop_statement']
what stores near [York Road] have an ongoing sale on [Skirt]?	'gemco'	['question_type_global', 'question_two_hop_statement']
[clay pot] is a type of [Gift]
show me all department stores near [York Road]	'gemco', "bloomingdale's"	['question_type_global', 'question_single_statement']
[weistein's] has [Suit], [Jeans] and [Bow Tie] on sale!
what's currently on sale at [weistein's]?	'Suit', 'Humidifier', 'Skirt', 'Socks', 'purse', 'blanket', 'Blender', 'Bow Tie', 'Shoes', 'Jeans'	['question_type_local']
what supermarkets are there on [York Road]?	"trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
[Pajamas] and [Shawl] are types of [Clothing]
show me all stores near [York Road] that have a sale on [gifts]	'gemco'	['question_type_global', 'question_three_hop_statement']
there is a [supermarket] called [trader joe's] on [Surrey Lane]
what department stores are there	'gemco', "weistein's", "bloomingdale's"	['question_type_global', 'question_single_statement']
what are the supermarkets on [York Road]?	"trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
show me all stores near [Surrey Lane]	"trader joe's"	['question_type_global', 'question_single_statement']
Where is [Thong] on sale?	'gemco'	['question_type_local']
what stores are there that I taught you?	'gemco', "weistein's", "trader joe's", 'walgreens', "bloomingdale's"	['question_type_global', 'question_single_statement']
[boom box] and [ipod] are all on sale at [weistein's]
[weistein's] no longer has [blanket], [Skirt] and [boom box] on sale
what items are on sale at [weistein's]?	'Suit', 'Humidifier', 'Socks', 'purse', 'ipod', 'Blender', 'Bow Tie', 'Shoes', 'Jeans'	['question_type_local']
what supermarkets are there?	"trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
what items are on sale at [walgreens]?	'Beef tongue', 'Bitter Melon', 'Opossum'	['question_type_local']
show me all stores near [Grand Avenue] that have a sale on [gifts]	"weistein's"	['question_type_global', 'question_three_hop_statement']
what are the department stores on [Grand Avenue]?	"weistein's"	['question_type_global', 'question_single_statement']
[trader joe's on York Road] has [Veal] on sale!
what are the stores?	'gemco', "weistein's", "trader joe's", 'walgreens', "bloomingdale's"	['question_type_global', 'question_single_statement']
Where is [that meat] on sale?	"trader joe's"	['question_type_local']
show me all stores	'gemco', "weistein's", "trader joe's", 'walgreens', "bloomingdale's"	['question_type_global', 'question_single_statement']
what stores are on [Grand Avenue]?	"weistein's"	['question_type_local']
what stores near [York Road] have an ongoing sale on [meat]?	"trader joe's", 'walgreens'	['question_type_global', 'question_three_hop_statement']
Where is [this item] on sale?	"trader joe's"	['question_type_local']
[Zucchini], [Green beans] and [Corn] are kinds of [Vegetables]
show me all department stores near [Grand Avenue] that have a sale	"weistein's"	['question_type_global', 'question_two_hop_statement']
what supermarkets are there?	"trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
what stores near [York Road] have an ongoing sale on [vegetables]?	'walgreens'	['question_type_global', 'question_three_hop_statement']
[Cedar Street] is in [Downtown]
what's currently on sale at [weistein's]?	'Suit', 'Humidifier', 'Socks', 'purse', 'ipod', 'Blender', 'Bow Tie', 'Shoes', 'Jeans'	['question_type_local']
What stores is [Skirt] on sale at	'gemco'	['question_type_local']
show me all supermarkets near [York Road] that have a sale	"trader joe's", 'walgreens'	['question_type_global', 'question_two_hop_statement']
what stores near [Grand Avenue] have an ongoing sale on [gifts]?	"weistein's"	['question_type_global', 'question_three_hop_statement']
show me all stores near [Grand Avenue] that have a sale on [clothing]	"weistein's"	['question_type_global', 'question_three_hop_statement']
show me all of the supermarkets on [York Road]	"trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
what department stores on [Grand Avenue] have a sale?	"weistein's"	['question_type_global', 'question_two_hop_statement']
show me all department stores near [York Road]	'gemco', "bloomingdale's"	['question_type_global', 'question_single_statement']
show me all stores on [York Road] that currently have a sale	'gemco', "trader joe's", 'walgreens', "bloomingdale's"	['question_type_global', 'question_two_hop_statement']
What stores is [purse] on sale at	'gemco', "weistein's"	['question_type_local']
show me all supermarkets that i tought you	"trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
what department stores near [Grand Avenue] have an ongoing sale?	"weistein's"	['question_type_global', 'question_two_hop_statement']
What stores is [ipod] on sale at	'gemco', "weistein's"	['question_type_local']
what stores near [Grand Avenue] have an ongoing sale on [clothing]?	"weistein's"	['question_type_global', 'question_three_hop_statement']
what department stores are there	'gemco', "weistein's", "bloomingdale's"	['question_type_global', 'question_single_statement']
show me all department stores	'gemco', "weistein's", "bloomingdale's"	['question_type_global', 'question_single_statement']
what stores near [Grand Avenue] have an ongoing sale?	"weistein's"	['question_type_global', 'question_two_hop_statement']
[Goose Liver] is a [Meat]
[boom box], [phone] and [purse] stopped being on sale at [gemco]
what items are on sale at [gemco]?	'Suit', 'Electric water boiler', 'Oven', 'Microwave oven', 'Skirt', 'Socks', 'Sandals', 'bookmark', 'ipod', 'Thong', 'Blender'	['question_type_local']
what are the department stores on [Grand Avenue]?	"weistein's"	['question_type_global', 'question_single_statement']
what supermarkets on [York Road] have a sale?	"trader joe's", 'walgreens'	['question_type_global', 'question_two_hop_statement']
i absolutely must not forget to get both [Goose] and [Goose Liver] for [dinner with ben]
what things do I need to buy for [dinner with ben]	'Goose', 'Goose Liver'	['question_type_local']
[Goose Liver] is on sale at [walgreens]
what is on sale at [that store]?	'Beef tongue', 'Bitter Melon', 'Opossum', 'Goose Liver'	['question_type_local']
what stores on [Grand Avenue] have a sale?	"weistein's"	['question_type_global', 'question_two_hop_statement']
show me all stores on [York Road] that currently have a sale on [vegetables]	'walgreens'	['question_type_global', 'question_three_hop_statement']
what department stores on [Grand Avenue] have a sale?	"weistein's"	['question_type_global', 'question_two_hop_statement']
what stores are there on [York Road]?	'gemco', "trader joe's", 'walgreens', "bloomingdale's"	['question_type_global', 'question_single_statement']
[kiwi] and [star fruit] are on sale at [this supermarket]
what is on sale at [walgreens]?	'kiwi', 'Beef tongue', 'Bitter Melon', 'star fruit', 'Opossum', 'Goose Liver'	['question_type_local']
i need to get [peach] and [kiwi] for [dinner with ben]
what things do I need to buy for [dinner with ben]	'kiwi', 'peach', 'Goose', 'Goose Liver'	['question_type_local']
what neighborhood is [York Road] located in?	'Fairmount'	['question_type_local']
[Dinner Jacket] is a [Clothing]
What stores is [kiwi] on sale at	'walgreens'	['question_type_local']
what are the supermarkets on [York Road]?	"trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
show me all supermarkets that i tought you	"trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
[weistein's] has [Electric water boiler] and [Microwave oven] on sale!
what items are on sale at [weistein's]?	'Suit', 'Electric water boiler', 'Microwave oven', 'Humidifier', 'Socks', 'purse', 'ipod', 'Blender', 'Bow Tie', 'Shoes', 'Jeans'	['question_type_local']
what [meat] do i need to buy?	'Goose', 'Goose Liver'	['question_type_global', 'question_two_hop_statement']
what stores near [York Road] have an ongoing sale on [meat]?	"trader joe's", 'walgreens'	['question_type_global', 'question_three_hop_statement']
show me all department stores near [York Road]	'gemco', "bloomingdale's"	['question_type_global', 'question_single_statement']
show me all of the department stores on [York Road]	'gemco', "bloomingdale's"	['question_type_global', 'question_single_statement']
show me all stores near [York Road] that have a sale on [vegetables]	'walgreens'	['question_type_global', 'question_three_hop_statement']
what items do I need to get?	'kiwi', 'peach', 'Goose', 'Goose Liver'	['question_type_global', 'question_single_statement']
what's currently on sale at [gemco]?	'Suit', 'Electric water boiler', 'Oven', 'Microwave oven', 'Skirt', 'Socks', 'Sandals', 'bookmark', 'ipod', 'Thong', 'Blender'	['question_type_local']
is there a sale on [Bitter Melon] anywhere?	'walgreens'	['question_type_local']
show me all department stores near [Grand Avenue] that have a sale	"weistein's"	['question_type_global', 'question_two_hop_statement']
show me all stores on [York Road] that currently have a sale on [clothing]	'gemco'	['question_type_global', 'question_three_hop_statement']
[purse] and [boom box] are on sale at [gemco]
[Green pepper] and [Turnip] are both different kinds of [Vegetables]
show me all of the stores	'gemco', "weistein's", "trader joe's", 'walgreens', "bloomingdale's"	['question_type_global', 'question_single_statement']
what items that I have to buy for [dinner with ben] currently are on sale?	'kiwi', 'Goose Liver'	['question_type_global', 'question_two_hop_statement']
there is a [department store] called [sage-allen] on [4th Street West]
[Shawl] and [Pajamas] are on sale at [sage-allen]
what's currently on sale at [sage-allen]?	'Pajamas', 'Shawl'	['question_type_local']
show me all stores on [York Road] that currently have a sale on [appliances]	'gemco', "bloomingdale's"	['question_type_global', 'question_three_hop_statement']
[gemco] has [Tie] on sale!
what items are on sale at [this store]?	'Suit', 'Electric water boiler', 'Oven', 'Microwave oven', 'Skirt', 'Socks', 'Sandals', 'bookmark', 'purse', 'ipod', 'Thong', 'Tie', 'Blender', 'boom box'	['question_type_local']
show me all of the department stores on [4th Street West]	'sage-allen'	['question_type_global', 'question_single_statement']
what stores near [York Road] have an ongoing sale on [vegetables]?	'walgreens'	['question_type_global', 'question_three_hop_statement']
show me all stores on [York Road] that currently have a sale	'gemco', "trader joe's", 'walgreens', "bloomingdale's"	['question_type_global', 'question_two_hop_statement']
i often shop at [trader joe's], which is my local [supermarket]
i think this [trader joe's] is somewhere on [Cedar Street]
[kumquat], [date] and [orange] are all on sale at [trader joe's]
[trader joe's that I last mentioned] no longer has [kumquat], [orange] and [date] on sale
show me all supermarkets near [Cedar Street]	"trader joe's"	['question_type_global', 'question_single_statement']
what stores on [York Road] have a sale on [clothing]?	'gemco'	['question_type_global', 'question_three_hop_statement']
What stores is [bookmark] on sale at	'gemco'	['question_type_local']
show me all of the supermarkets	"trader joe's", 'walgreens'	['question_type_global', 'question_single_statement']
show me all department stores near [4th Street West]	'sage-allen'	['question_type_global', 'question_single_statement']
what neighborhood is [Marshall Street] located in?	'Asian District'	['question_type_local']
What stores is [Beef tongue] on sale at	'walgreens'	['question_type_local']
show me all stores	'gemco', "weistein's", "trader joe's", 'walgreens', "bloomingdale's", 'sage-allen'	['question_type_global', 'question_single_statement']
what is on sale near my current location?	'Pajamas', 'Shawl'	['question_type_global', 'question_three_hop_statement']
Do i have any [fruit] on my shopping list?	'kiwi', 'peach'	['question_type_global', 'question_two_hop_statement']
[weistein's] has [Shawl] on sale!
show me all supermarkets near [Cedar Street]	"trader joe's"	['question_type_global', 'question_single_statement']
what are the department stores on [4th Street West]?	'sage-allen'	['question_type_global', 'question_single_statement']
what do stores near me have on sale?	'Pajamas', 'Shawl'	['question_type_global', 'question_three_hop_statement']
is there a sale on any [fruit] on my shopping list?	'kiwi'	['question_type_global', 'question_three_hop_statement']
what do stores near me are have a sale on?	'Pajamas', 'Shawl'	['question_type_global', 'question_three_hop_statement']
[bookmark] and [blanket] are on sale at [weistein's]
is there a sale on [Thong] anywhere?	'gemco'	['question_type_local']
is there a store nearby with a sale going on right now?	'sage-allen'	['question_type_global', 'question_three_hop_statement']
what [fruit] do i need to buy?	'kiwi', 'peach'	['question_type_global', 'question_two_hop_statement']
what is on sale near my current location?	'Pajamas', 'Shawl'	['question_type_global', 'question_three_hop_statement']
[blanket], [Jeans] and [Shoes] stopped being on sale at [weistein's]
what items are on sale at [weistein's]?	'Suit', 'Electric water boiler', 'Microwave oven', 'Humidifier', 'Socks', 'bookmark', 'purse', 'ipod', 'Blender', 'Bow Tie', 'Shawl'	['question_type_local']
[Duck], [Goat] and [Rabbit] are [Meat]
is there any [meat] on my list that's on sale somewhere?	'Goose Liver'	['question_type_global', 'question_three_hop_statement']
what items do I need to get?	'kiwi', 'peach', 'Goose', 'Goose Liver'	['question_type_global', 'question_single_statement']
Do i have any [fruit] on my shopping list?	'kiwi', 'peach'	['question_type_global', 'question_two_hop_statement']
are there any [meat] that i need to get?	'Goose', 'Goose Liver'	['question_type_global', 'question_two_hop_statement']
make sure to buy [Rabbit] and [Opossum] for [dinner with ben]
Do I need to buy any [fruit]?	'kiwi', 'peach'	['question_type_global', 'question_two_hop_statement']
[trader joe's on Cedar Street] has [Lentils] and [Green pepper] on sale!
what items are on sale at [sage-allen]?	'Pajamas', 'Shawl'	['question_type_local']
show me all of the department stores on [Grand Avenue]	"weistein's"	['question_type_global', 'question_single_statement']
