[flowers] is a type of [Gift]
[Tubers] and [Onion] are good examples of [Vegetables]
i have [thanksgiving dinner] coming up
add [Tubers] and [Onion] to my shopping list for [thanksgiving dinner]
What do I need to buy for [thanksgiving dinner]?	'Tubers', 'Onion'	['question_type_local']
Do i have any [vegetables] on my shopping list?	'Tubers', 'Onion'	['question_type_global', 'question_two_hop_statement']
get rid of [Tubers] and [Onion] from my shopping for [thanksgiving dinner]
what things did i get for [thanksgiving dinner]	'Tubers', 'Onion'	['question_type_local']
what items did i already get for [thanksgiving dinner]?	'Tubers', 'Onion'	['question_type_local']
what did i remove from [thanksgiving dinner]?	'Tubers', 'Onion'	['question_type_local']
[Combo washer dryer] and [Dishwasher] are types of [Appliance]
there is a [supermarket] called [holiday foods] that I shop in pretty often
show me all supermarkets that i tought you	'holiday foods'	['question_type_global', 'question_single_statement']
what are the supermarkets?	'holiday foods'	['question_type_global', 'question_single_statement']
what stores are there that I taught you?	'holiday foods'	['question_type_global', 'question_single_statement']
show me all of the stores	'holiday foods'	['question_type_global', 'question_single_statement']
[Clothes iron], [Automatic Rotimaker] and [Cold-pressed juicer] are all different types of [Appliance]
what are the stores?	'holiday foods'	['question_type_global', 'question_single_statement']
[Water cooker] is a [Appliance]
show me all of the supermarkets	'holiday foods'	['question_type_global', 'question_single_statement']
there is a [department store] called [joseph magnin] that I shop in pretty often
[Automatic Rotimaker], [Cold-pressed juicer] and [Dishwasher] are on sale at [joseph magnin]
what items are on sale at [joseph magnin]?	'Dishwasher', 'Automatic Rotimaker', 'Cold-pressed juicer'	['question_type_local']
Where is [Dishwasher] on sale?	'joseph magnin'	['question_type_local']
What stores is [Dishwasher] on sale at	'joseph magnin'	['question_type_local']
[Water cooker] is on sale at [joseph magnin]
what's currently on sale at [that department store]?	'Dishwasher', 'Automatic Rotimaker', 'Cold-pressed juicer', 'Water cooker'	['question_type_local']
What stores is [Automatic Rotimaker] on sale at	'joseph magnin'	['question_type_local']
there is a [department store] called [fashion bar] that I shop in pretty often
what supermarkets are there?	'holiday foods'	['question_type_global', 'question_single_statement']
what is on sale at [joseph magnin]?	'Dishwasher', 'Automatic Rotimaker', 'Cold-pressed juicer', 'Water cooker'	['question_type_local']
[Goat], [Mutton] and [Ham] are all types of [Meat]
what department stores are there	'joseph magnin', 'fashion bar'	['question_type_global', 'question_single_statement']
[Stockings], [Bow Tie] and [Boots] are all good examples of [Clothing]
[Clothes iron] is on sale at [joseph magnin]
what items are on sale at [this store]?	'Dishwasher', 'Clothes iron', 'Automatic Rotimaker', 'Cold-pressed juicer', 'Water cooker'	['question_type_local']
[Lingerie] and [Cufflinks] are both different kinds of [Clothing]
[2nd Avenue] is on the outskirts of [Hays]
[Boots], [Lingerie] and [Bow Tie] are on sale at [fashion bar]
what items are on sale at [fashion bar]?	'Bow Tie', 'Boots', 'Lingerie'	['question_type_local']
show me all department stores	'joseph magnin', 'fashion bar'	['question_type_global', 'question_single_statement']
is there a sale on [Water cooker] anywhere?	'joseph magnin'	['question_type_local']
[Kangaroo], [Duck] and [Tripe] are all examples of [Meat]
What stores is [Automatic Rotimaker] on sale at	'joseph magnin'	['question_type_local']
don't forget about an upcoming [linda's wedding]
this specific [fashion bar] is on [2nd Avenue]
what is on sale at [that department store]?	'Bow Tie', 'Boots', 'Lingerie'	['question_type_local']
what are the stores on [2nd Avenue]?	'fashion bar'	['question_type_global', 'question_single_statement']
show me all stores on [2nd Avenue] that currently have a sale	'fashion bar'	['question_type_global', 'question_two_hop_statement']
[Stockings] is on sale at [this department store]
what items are on sale at [fashion bar]?	'Stockings', 'Bow Tie', 'Boots', 'Lingerie'	['question_type_local']
show me all department stores	'joseph magnin', 'fashion bar'	['question_type_global', 'question_single_statement']
what stores near [2nd Avenue] have an ongoing sale on [clothing]?	'fashion bar'	['question_type_global', 'question_three_hop_statement']
what are the supermarkets?	'holiday foods'	['question_type_global', 'question_single_statement']
[Calf liver] is a kind of [Meat]
what are the department stores?	'joseph magnin', 'fashion bar'	['question_type_global', 'question_single_statement']
what stores are there on [2nd Avenue]?	'fashion bar'	['question_type_global', 'question_single_statement']
what department stores near [2nd Avenue] have an ongoing sale?	'fashion bar'	['question_type_global', 'question_two_hop_statement']
please remind me to buy [Boots] and [Cufflinks] for [linda's wedding]
Where is [Dishwasher] on sale?	'joseph magnin'	['question_type_local']
is there a sale on any items on my shopping list for [linda's wedding]?	'Boots'	['question_type_global', 'question_two_hop_statement']
What do I need to buy [Cufflinks] for?	"linda's wedding"	['question_type_local']
what are the department stores on [2nd Avenue]?	'fashion bar'	['question_type_global', 'question_single_statement']
i think this [holiday foods] is somewhere on [2nd Avenue]
[Onion] and [Tubers] are on sale at [holiday foods]
what is on sale at [holiday foods]?	'Tubers', 'Onion'	['question_type_local']
show me all of the stores	'holiday foods', 'joseph magnin', 'fashion bar'	['question_type_global', 'question_single_statement']
[book] is a type of [Gift]
[I] am currently on [2nd Avenue]
is there a sale on any items on my shopping list?	'Boots'	['question_type_global', 'question_two_hop_statement']
are there any stores nearby that have a sale on [Tubers]?	'holiday foods'	['question_type_global', 'question_three_hop_statement']
is there anything on my list that's on sale somewhere?	'Boots'	['question_type_global', 'question_two_hop_statement']
what event do I need to buy [Cufflinks] for	"linda's wedding"	['question_type_local']
what neighborhood am I currently in?	'Hays'	['question_type_local']
does any store nearby have [clothing] on sale?	'fashion bar'	['question_type_global', 'question_four_hop_statement']
show me all department stores on [2nd Avenue] that currently have a sale	'fashion bar'	['question_type_global', 'question_two_hop_statement']
what [clothing] do i need to buy?	'Boots', 'Cufflinks'	['question_type_global', 'question_two_hop_statement']
are there any [clothing] on my shopping list that there is a sale on?	'Boots'	['question_type_global', 'question_three_hop_statement']
is there a sale on [Dishwasher] anywhere?	'joseph magnin'	['question_type_local']
Do I need to buy any [clothing]?	'Boots', 'Cufflinks'	['question_type_global', 'question_two_hop_statement']
what are the things that I need to get?	'Boots', 'Cufflinks'	['question_type_global', 'question_single_statement']
what's currently on sale at [joseph magnin]?	'Dishwasher', 'Clothes iron', 'Automatic Rotimaker', 'Cold-pressed juicer', 'Water cooker'	['question_type_local']
what are the stores on [2nd Avenue]?	'holiday foods', 'fashion bar'	['question_type_global', 'question_single_statement']
what stores near [2nd Avenue] have an ongoing sale?	'holiday foods', 'fashion bar'	['question_type_global', 'question_two_hop_statement']
What do I need to buy for [linda's wedding]?	'Boots', 'Cufflinks'	['question_type_local']
what stores are there that I taught you?	'holiday foods', 'joseph magnin', 'fashion bar'	['question_type_global', 'question_single_statement']
show me all of the supermarkets	'holiday foods'	['question_type_global', 'question_single_statement']
show me all of the supermarkets on [2nd Avenue]	'holiday foods'	['question_type_global', 'question_single_statement']
[fashion bar] has [Combo washer dryer] and [Water cooker] on sale!
What stores is [Automatic Rotimaker] on sale at	'joseph magnin'	['question_type_local']
show me all supermarkets on [2nd Avenue] that currently have a sale	'holiday foods'	['question_type_global', 'question_two_hop_statement']
is there a sale on [Boots] anywhere?	'fashion bar'	['question_type_local']
is there a sale on any items on my shopping list?	'Boots'	['question_type_global', 'question_two_hop_statement']
what are the supermarkets?	'holiday foods'	['question_type_global', 'question_single_statement']
is there anything on my list that's on sale somewhere?	'Boots'	['question_type_global', 'question_two_hop_statement']
what supermarkets are there on [2nd Avenue]?	'holiday foods'	['question_type_global', 'question_single_statement']
What stores is [Stockings] on sale at	'fashion bar'	['question_type_local']
is there anything on sale at a store nearby?	'Tubers', 'Onion', 'Combo washer dryer', 'Water cooker', 'Stockings', 'Bow Tie', 'Boots', 'Lingerie'	['question_type_global', 'question_three_hop_statement']
is there a sale on [Combo washer dryer] anywhere?	'fashion bar'	['question_type_local']
what is my shopping list?	'Boots', 'Cufflinks'	['question_type_global', 'question_single_statement']
is there a store near my location that has what i need on sale?	'fashion bar'	['question_type_global', 'question_four_hop_statement']
what are the supermarkets?	'holiday foods'	['question_type_global', 'question_single_statement']
is there a sale on [Water cooker] anywhere?	'joseph magnin', 'fashion bar'	['question_type_local']
show me all stores on [2nd Avenue] that currently have a sale	'holiday foods', 'fashion bar'	['question_type_global', 'question_two_hop_statement']
is there a store nearby with a sale on [clothing] going on right now?	'fashion bar'	['question_type_global', 'question_four_hop_statement']
show me all stores on [2nd Avenue] that currently have a sale on [vegetables]	'holiday foods'	['question_type_global', 'question_three_hop_statement']
what department stores on [2nd Avenue] have a sale?	'fashion bar'	['question_type_global', 'question_two_hop_statement']
here are some examples of [Fruit]: [banana], [boysenberry] and [tangerine]
are there any stores nearby that have a sale on [clothing]?	'fashion bar'	['question_type_global', 'question_four_hop_statement']
why do i need to buy [Cufflinks]?	"linda's wedding"	['question_type_local']
[Orchard Street] is in [Uptown]
what neighborhood is [2nd Avenue] in?	'Hays'	['question_type_local']
is there anything on sale at a store nearby?	'Tubers', 'Onion', 'Combo washer dryer', 'Water cooker', 'Stockings', 'Bow Tie', 'Boots', 'Lingerie'	['question_type_global', 'question_three_hop_statement']
what neighborhood is [Orchard Street] located in?	'Uptown'	['question_type_local']
are there any items on my shopping list for [linda's wedding] that there is a sale on?	'Boots'	['question_type_global', 'question_two_hop_statement']
is there a sale on any items on my shopping list where i am?	'Boots'	['question_type_global', 'question_four_hop_statement']
show me all stores on [2nd Avenue] that currently have a sale on [clothing]	'fashion bar'	['question_type_global', 'question_three_hop_statement']
what items are on sale at [fashion bar]?	'Combo washer dryer', 'Water cooker', 'Stockings', 'Bow Tie', 'Boots', 'Lingerie'	['question_type_local']
what supermarkets on [2nd Avenue] have a sale?	'holiday foods'	['question_type_global', 'question_two_hop_statement']
does any store nearby have [Combo washer dryer] on sale?	'fashion bar'	['question_type_global', 'question_three_hop_statement']
show me all stores on [2nd Avenue] that currently have a sale on [vegetables]	'holiday foods'	['question_type_global', 'question_three_hop_statement']
What do I need to buy for [linda's wedding]?	'Boots', 'Cufflinks'	['question_type_local']
what is on sale at [fashion bar]?	'Combo washer dryer', 'Water cooker', 'Stockings', 'Bow Tie', 'Boots', 'Lingerie'	['question_type_local']
what stores near [2nd Avenue] have an ongoing sale on [appliances]?	'fashion bar'	['question_type_global', 'question_three_hop_statement']
what stores are there on [2nd Avenue]?	'holiday foods', 'fashion bar'	['question_type_global', 'question_single_statement']
what stores near [2nd Avenue] have an ongoing sale?	'holiday foods', 'fashion bar'	['question_type_global', 'question_two_hop_statement']
what are the things that i need to get?	'Boots', 'Cufflinks'	['question_type_global', 'question_single_statement']
what stores on [2nd Avenue] have a sale on [clothing]?	'fashion bar'	['question_type_global', 'question_three_hop_statement']
what neighborhood is [this street] in?	'Uptown'	['question_type_local']
what neighborhood is [this street] located in?	'Uptown'	['question_type_local']
are there any stores nearby that have a sale?	'fashion bar', 'holiday foods'	['question_type_global', 'question_three_hop_statement']
what neighborhood is [that street] located in?	'Uptown'	['question_type_local']
what is on sale near my current location?	'Tubers', 'Onion', 'Combo washer dryer', 'Water cooker', 'Stockings', 'Bow Tie', 'Boots', 'Lingerie'	['question_type_global', 'question_three_hop_statement']
show me all supermarkets near [2nd Avenue] that have a sale	'holiday foods'	['question_type_global', 'question_two_hop_statement']
is there any [clothing] on my list that's on sale somewhere?	'Boots'	['question_type_global', 'question_three_hop_statement']
is there anything that I need for [linda's wedding] that's on sale somewhere?	'Boots'	['question_type_global', 'question_two_hop_statement']
what items are on sale at [holiday foods]?	'Tubers', 'Onion'	['question_type_local']
is there any [clothing] that I have to buy currently are on sale?	'Boots'	['question_type_global', 'question_three_hop_statement']
show me all stores near [2nd Avenue] that have a sale on [vegetables]	'holiday foods'	['question_type_global', 'question_three_hop_statement']
are there any stores nearby that have a sale on [appliances]?	'fashion bar'	['question_type_global', 'question_four_hop_statement']
what are the supermarkets?	'holiday foods'	['question_type_global', 'question_single_statement']
[boom box] is a type of [Gift]
What stores is [Onion] on sale at	'holiday foods'	['question_type_local']
show me all of the stores on [2nd Avenue]	'holiday foods', 'fashion bar'	['question_type_global', 'question_single_statement']
what do stores near me have on sale?	'Tubers', 'Onion', 'Combo washer dryer', 'Water cooker', 'Stockings', 'Bow Tie', 'Boots', 'Lingerie'	['question_type_global', 'question_three_hop_statement']
are there any stores nearby that have a sale on [Water cooker]?	'fashion bar'	['question_type_global', 'question_three_hop_statement']
make sure to buy [boysenberry] and [banana] for [thanksgiving dinner]
what things do I need to buy for [thanksgiving dinner]	'banana', 'boysenberry'	['question_type_local']
there is a [department store] called [fashion bar] that I shop in pretty often
is there a sale on [Clothes iron] anywhere?	'joseph magnin'	['question_type_local']
is there a store near my location is having a sale?	'fashion bar', 'holiday foods'	['question_type_global', 'question_three_hop_statement']
what are the things that I need to get?	'Boots', 'Cufflinks', 'banana', 'boysenberry'	['question_type_global', 'question_single_statement']
what stores are there that I taught you?	'holiday foods', 'joseph magnin', 'fashion bar'	['question_type_global', 'question_single_statement']
here are some examples of [Gift]: [camera], [hair brush] and [tv]
what stores on [2nd Avenue] have a sale on [vegetables]?	'holiday foods'	['question_type_global', 'question_three_hop_statement']
show me all stores near [2nd Avenue]	'holiday foods', 'fashion bar'	['question_type_global', 'question_single_statement']
what do stores near me have on sale?	'Tubers', 'Onion', 'Combo washer dryer', 'Water cooker', 'Stockings', 'Bow Tie', 'Boots', 'Lingerie'	['question_type_global', 'question_three_hop_statement']
show me all stores near [2nd Avenue] that have a sale on [vegetables]	'holiday foods'	['question_type_global', 'question_three_hop_statement']
[Bridle Court] is located in the [Uptown] neighborhood
is there any [clothing] on my list that's on sale somewhere?	'Boots'	['question_type_global', 'question_three_hop_statement']
i just bought [banana] for [thanksgiving dinner]
i need to get [tangerine] for [this event]
what items that I have to buy currently are on sale?	'Boots'	['question_type_global', 'question_two_hop_statement']
What do I need to buy [boysenberry] for?	'thanksgiving dinner'	['question_type_local']
are there any stores nearby that have a sale on [vegetables]?	'holiday foods'	['question_type_global', 'question_four_hop_statement']
what stores near [2nd Avenue] have an ongoing sale on [clothing]?	'fashion bar'	['question_type_global', 'question_three_hop_statement']
what are the stores on [2nd Avenue]?	'holiday foods', 'fashion bar'	['question_type_global', 'question_single_statement']
[Tankini] is a [Clothing]
What stores is [Onion] on sale at	'holiday foods'	['question_type_local']
show me all stores on [2nd Avenue] that currently have a sale on [appliances]	'fashion bar'	['question_type_global', 'question_three_hop_statement']
what stores on [2nd Avenue] have a sale on [appliances]?	'fashion bar'	['question_type_global', 'question_three_hop_statement']
what is on sale near my current location?	'Tubers', 'Onion', 'Combo washer dryer', 'Water cooker', 'Stockings', 'Bow Tie', 'Boots', 'Lingerie'	['question_type_global', 'question_three_hop_statement']
What do I need to buy [boysenberry] for?	'thanksgiving dinner'	['question_type_local']
show me all stores near [2nd Avenue] that have a sale on [clothing]	'fashion bar'	['question_type_global', 'question_three_hop_statement']
what do stores near me are have a sale on?	'Tubers', 'Onion', 'Combo washer dryer', 'Water cooker', 'Stockings', 'Bow Tie', 'Boots', 'Lingerie'	['question_type_global', 'question_three_hop_statement']
what [fruit] do i need to buy?	'boysenberry', 'tangerine'	['question_type_global', 'question_two_hop_statement']
[boom box], [hair brush] and [flowers] are all on sale at [fashion bar on 2nd Avenue]
is there a sale on [flowers] anywhere?	'fashion bar'	['question_type_local']
show me all stores on [2nd Avenue] that currently have a sale on [gifts]	'fashion bar'	['question_type_global', 'question_three_hop_statement']
show me all stores on [2nd Avenue] that currently have a sale on [clothing]	'fashion bar'	['question_type_global', 'question_three_hop_statement']
[Hillside Drive] is located in the [Uptown] neighborhood
Do I need to buy any [clothing]?	'Boots', 'Cufflinks'	['question_type_global', 'question_two_hop_statement']
does any store nearby have [gifts] on sale?	'fashion bar'	['question_type_global', 'question_four_hop_statement']
i am pretty sure that [Grove Avenue] is in [Hays]
what is on sale near my current location?	'flowers', 'Tubers', 'Onion', 'Combo washer dryer', 'Water cooker', 'Stockings', 'Bow Tie', 'Boots', 'Lingerie', 'boom box', 'hair brush'	['question_type_global', 'question_three_hop_statement']
is there a store near my location that has what i need on sale?	'fashion bar'	['question_type_global', 'question_four_hop_statement']
what neighborhood is [Grove Avenue] located in?	'Hays'	['question_type_local']
what stores near [2nd Avenue] have an ongoing sale on [vegetables]?	'holiday foods'	['question_type_global', 'question_three_hop_statement']
are there any [clothing] on my shopping list that there is a sale on?	'Boots'	['question_type_global', 'question_three_hop_statement']
show me all stores on [2nd Avenue] that currently have a sale on [vegetables]	'holiday foods'	['question_type_global', 'question_three_hop_statement']
[coconut], [pomegranate] and [blueberry] are all examples of [Fruit]
what is on sale at [joseph magnin]?	'Dishwasher', 'Clothes iron', 'Automatic Rotimaker', 'Cold-pressed juicer', 'Water cooker'	['question_type_local']
what items are on sale at nearby stores?	'flowers', 'Tubers', 'Onion', 'Combo washer dryer', 'Water cooker', 'Stockings', 'Bow Tie', 'Boots', 'Lingerie', 'boom box', 'hair brush'	['question_type_global', 'question_three_hop_statement']
what are the department stores?	'joseph magnin', 'fashion bar'	['question_type_global', 'question_single_statement']
is there a store nearby with any of the items on my shopping list on sale?	'fashion bar'	['question_type_global', 'question_four_hop_statement']
is there a sale on [Clothes iron] anywhere?	'joseph magnin'	['question_type_local']
what stores on [2nd Avenue] have a sale on [clothing]?	'fashion bar'	['question_type_global', 'question_three_hop_statement']
is there any [clothing] that I have to buy currently are on sale?	'Boots'	['question_type_global', 'question_three_hop_statement']
is there a store nearby with a sale going on right now?	'fashion bar', 'holiday foods'	['question_type_global', 'question_three_hop_statement']
Do i have any [fruit] on my shopping list?	'boysenberry', 'tangerine'	['question_type_global', 'question_two_hop_statement']
i absolutely must not forget to get both [Calf liver] and [Goat] for [thanksgiving dinner]
what do I need for [thanksgiving dinner]?	'Goat', 'Calf liver', 'boysenberry', 'tangerine'	['question_type_local']
is there a store near my location is having a sale on [gifts]?	'fashion bar'	['question_type_global', 'question_four_hop_statement']
show me all of the stores	'holiday foods', 'joseph magnin', 'fashion bar'	['question_type_global', 'question_single_statement']
what stores near [2nd Avenue] have an ongoing sale?	'holiday foods', 'fashion bar'	['question_type_global', 'question_two_hop_statement']
what stores are on [2nd Avenue]?	'holiday foods', 'fashion bar'	['question_type_local']
show me all supermarkets on [2nd Avenue] that currently have a sale	'holiday foods'	['question_type_global', 'question_two_hop_statement']
is there anything on my list that's on sale somewhere?	'Boots'	['question_type_global', 'question_two_hop_statement']
show me all of the stores on [2nd Avenue]	'holiday foods', 'fashion bar'	['question_type_global', 'question_single_statement']
[burlington] is a [department store]
what event do I need to buy [this thing] for	'thanksgiving dinner'	['question_type_local']
is there a sale on any items on my shopping list for [linda's wedding]?	'Boots'	['question_type_global', 'question_two_hop_statement']
what stores on [2nd Avenue] have a sale on [vegetables]?	'holiday foods'	['question_type_global', 'question_three_hop_statement']
what do i need [boysenberry] for?	'thanksgiving dinner'	['question_type_local']
show me all stores on [2nd Avenue] that currently have a sale on [Stockings]	'fashion bar'	['question_type_global', 'question_two_hop_statement']
does any store nearby have [gifts] on sale?	'fashion bar'	['question_type_global', 'question_four_hop_statement']
i think [Center Street] is in [Hays]
this specific [that department store] is on [2nd Avenue]
[Dishwasher] is on sale at [burlington]
what's currently on sale at [that department store]?	'Dishwasher'	['question_type_local']
is there a store nearby with any of the items on my shopping list on sale?	'fashion bar'	['question_type_global', 'question_four_hop_statement']
is there a store nearby with a sale going on right now?	'burlington', 'fashion bar', 'holiday foods'	['question_type_global', 'question_three_hop_statement']
what department stores are there on [2nd Avenue]?	'fashion bar', 'burlington'	['question_type_global', 'question_single_statement']
show me all department stores on [2nd Avenue] that currently have a sale	'fashion bar', 'burlington'	['question_type_global', 'question_two_hop_statement']
[fashion bar on 2nd Avenue] has [Cufflinks] on sale!
what's currently on sale at [burlington]?	'Dishwasher'	['question_type_local']
are there any stores nearby that have a sale on [appliances]?	'burlington', 'fashion bar'	['question_type_global', 'question_four_hop_statement']
what event do I need to buy [that item] for	"linda's wedding"	['question_type_local']
show me all supermarkets on [2nd Avenue] that currently have a sale	'holiday foods'	['question_type_global', 'question_two_hop_statement']
show me all stores near [2nd Avenue] that have a sale on [appliances]	'fashion bar', 'burlington'	['question_type_global', 'question_three_hop_statement']
what stores near [2nd Avenue] have an ongoing sale on [gifts]?	'fashion bar'	['question_type_global', 'question_three_hop_statement']
are there any stores nearby that have a sale on items that i need?	'fashion bar'	['question_type_global', 'question_four_hop_statement']
Do I need to buy any [fruit]?	'boysenberry', 'tangerine'	['question_type_global', 'question_two_hop_statement']
are there any items on my shopping list that there is a sale on?	'Boots', 'Cufflinks'	['question_type_global', 'question_two_hop_statement']
why do i need to buy [Boots]?	"linda's wedding"	['question_type_local']
show me all stores on [2nd Avenue] that currently have a sale	'holiday foods', 'fashion bar', 'burlington'	['question_type_global', 'question_two_hop_statement']
is there any [clothing] on my list that's on sale somewhere?	'Boots', 'Cufflinks'	['question_type_global', 'question_three_hop_statement']
show me all stores near [2nd Avenue] that have a sale on [clothing]	'fashion bar'	['question_type_global', 'question_three_hop_statement']
what stores on [2nd Avenue] have a sale on [gifts]?	'fashion bar'	['question_type_global', 'question_three_hop_statement']
[Tripe] and [Goat] are on sale at [holiday foods]
what is on sale at [holiday foods]?	'Tubers', 'Onion', 'Goat', 'Tripe'	['question_type_local']
Do I need to buy any [clothing]?	'Boots', 'Cufflinks'	['question_type_global', 'question_two_hop_statement']
what are the things that i need to get?	'Goat', 'Boots', 'Cufflinks', 'Calf liver', 'boysenberry', 'tangerine'	['question_type_global', 'question_single_statement']
[mirror] is a kind of [Gift]
What stores is [Lingerie] on sale at	'fashion bar'	['question_type_local']
are there any stores nearby that have a sale?	'burlington', 'fashion bar', 'holiday foods'	['question_type_global', 'question_three_hop_statement']
what stores on [2nd Avenue] have a sale on [clothing]?	'fashion bar'	['question_type_global', 'question_three_hop_statement']
what are the stores on [2nd Avenue]?	'holiday foods', 'fashion bar', 'burlington'	['question_type_global', 'question_single_statement']
what stores are there that I taught you?	'holiday foods', 'joseph magnin', 'fashion bar', 'burlington'	['question_type_global', 'question_single_statement']
is there a sale on [Bow Tie] anywhere?	'fashion bar'	['question_type_local']
what stores on [2nd Avenue] have a sale on [hair brush]?	'fashion bar'	['question_type_global', 'question_two_hop_statement']
is there a store near my location is having a sale on [hair brush]?	'fashion bar'	['question_type_global', 'question_three_hop_statement']
does any store nearby have [clothing] on sale?	'fashion bar'	['question_type_global', 'question_four_hop_statement']
does any store nearby have [appliances] on sale?	'burlington', 'fashion bar'	['question_type_global', 'question_four_hop_statement']
what neighborhood is [Center Street] located in?	'Hays'	['question_type_local']
what stores are there that I taught you?	'holiday foods', 'joseph magnin', 'fashion bar', 'burlington'	['question_type_global', 'question_single_statement']
What stores is [this meat] on sale at	'holiday foods'	['question_type_local']
Do I need to buy any [fruit]?	'boysenberry', 'tangerine'	['question_type_global', 'question_two_hop_statement']
What stores is [flowers] on sale at	'fashion bar'	['question_type_local']
show me all department stores near [2nd Avenue] that have a sale	'fashion bar', 'burlington'	['question_type_global', 'question_two_hop_statement']
are there any items on my shopping list for [linda's wedding] that there is a sale on?	'Boots', 'Cufflinks'	['question_type_global', 'question_two_hop_statement']
is there a sale on [Goat] anywhere?	'holiday foods'	['question_type_local']
what is on sale at [fashion bar on 2nd Avenue]?	'flowers', 'Combo washer dryer', 'Water cooker', 'Stockings', 'Bow Tie', 'Boots', 'Lingerie', 'Cufflinks', 'boom box', 'hair brush'	['question_type_local']
does any store nearby have any of the items i need on sale?	'holiday foods', 'fashion bar'	['question_type_global', 'question_four_hop_statement']
are there any stores nearby that have a sale on items that i need?	'holiday foods', 'fashion bar'	['question_type_global', 'question_four_hop_statement']
take off [Calf liver] and [boysenberry] from my list for [thanksgiving dinner]
is there a store near my location is having a sale on [vegetables]?	'holiday foods'	['question_type_global', 'question_four_hop_statement']
Do i have any [clothing] on my shopping list?	'Boots', 'Cufflinks'	['question_type_global', 'question_two_hop_statement']
what stores near [2nd Avenue] have an ongoing sale on [gifts]?	'fashion bar'	['question_type_global', 'question_three_hop_statement']
show me all stores on [2nd Avenue] that currently have a sale on [clothing]	'fashion bar'	['question_type_global', 'question_three_hop_statement']
is there a store nearby with a sale on [Boots] going on right now?	'fashion bar'	['question_type_global', 'question_three_hop_statement']
is there anything on my list that's on sale somewhere?	'Goat', 'Boots', 'Cufflinks'	['question_type_global', 'question_two_hop_statement']
Do i have any [meat] on my shopping list?	'Goat'	['question_type_global', 'question_two_hop_statement']
does any store nearby have [vegetables] on sale?	'holiday foods'	['question_type_global', 'question_four_hop_statement']
show me all stores	'holiday foods', 'joseph magnin', 'fashion bar', 'burlington'	['question_type_global', 'question_single_statement']
is there any [clothing] that I have to buy currently are on sale?	'Boots', 'Cufflinks'	['question_type_global', 'question_three_hop_statement']
is there a sale on any items on my shopping list where i am?	'Goat', 'Boots', 'Cufflinks'	['question_type_global', 'question_four_hop_statement']
are there any stores nearby that have a sale on items that i need?	'holiday foods', 'fashion bar'	['question_type_global', 'question_four_hop_statement']
show me all department stores near [2nd Avenue] that have a sale	'fashion bar', 'burlington'	['question_type_global', 'question_two_hop_statement']
what stores on [2nd Avenue] have a sale on [vegetables]?	'holiday foods'	['question_type_global', 'question_three_hop_statement']
is there a store nearby with a sale on [gifts] going on right now?	'fashion bar'	['question_type_global', 'question_four_hop_statement']
show me all stores near [2nd Avenue] that have a sale on [clothing]	'fashion bar'	['question_type_global', 'question_three_hop_statement']
are there any [meat] that i need to get?	'Goat'	['question_type_global', 'question_two_hop_statement']
are there any stores nearby that have a sale on [meat]?	'holiday foods'	['question_type_global', 'question_four_hop_statement']
what is on sale at [fashion bar on 2nd Avenue]?	'flowers', 'Combo washer dryer', 'Water cooker', 'Stockings', 'Bow Tie', 'Boots', 'Lingerie', 'Cufflinks', 'boom box', 'hair brush'	['question_type_local']
what stores on [2nd Avenue] have a sale on [clothing]?	'fashion bar'	['question_type_global', 'question_three_hop_statement']
what do i need to buy?	'Goat', 'Boots', 'Cufflinks', 'tangerine'	['question_type_global', 'question_single_statement']
is there a sale on any [clothing] on my shopping list?	'Boots', 'Cufflinks'	['question_type_global', 'question_three_hop_statement']
what stores near [2nd Avenue] have an ongoing sale on [meat]?	'holiday foods'	['question_type_global', 'question_three_hop_statement']
show me all department stores near [2nd Avenue]	'fashion bar', 'burlington'	['question_type_global', 'question_single_statement']
what stores are there on [2nd Avenue]?	'holiday foods', 'fashion bar', 'burlington'	['question_type_global', 'question_single_statement']
is there a store near my location is having a sale on [gifts]?	'fashion bar'	['question_type_global', 'question_four_hop_statement']
what items do I need to get?	'Goat', 'Boots', 'Cufflinks', 'tangerine'	['question_type_global', 'question_single_statement']
show me all of the stores on [2nd Avenue]	'holiday foods', 'fashion bar', 'burlington'	['question_type_global', 'question_single_statement']
show me all department stores near [2nd Avenue] that have a sale	'fashion bar', 'burlington'	['question_type_global', 'question_two_hop_statement']
what department stores near [2nd Avenue] have an ongoing sale?	'fashion bar', 'burlington'	['question_type_global', 'question_two_hop_statement']
are there any [meat] on my shopping list that there is a sale on?	'Goat'	['question_type_global', 'question_three_hop_statement']
show me all stores on [2nd Avenue] that currently have a sale	'holiday foods', 'fashion bar', 'burlington'	['question_type_global', 'question_two_hop_statement']
is there any [clothing] that I have to buy currently are on sale?	'Boots', 'Cufflinks'	['question_type_global', 'question_three_hop_statement']
i think this [fashion bar that I last mentioned] is somewhere on [Bridle Court]
what is on sale at [joseph magnin]?	'Dishwasher', 'Clothes iron', 'Automatic Rotimaker', 'Cold-pressed juicer', 'Water cooker'	['question_type_local']
what supermarkets near [2nd Avenue] have an ongoing sale?	'holiday foods'	['question_type_global', 'question_two_hop_statement']
is there a sale on [Tripe] anywhere?	'holiday foods'	['question_type_local']
does any store nearby have [gifts] on sale?	'fashion bar'	['question_type_global', 'question_four_hop_statement']
is there a sale on any [clothing] on my shopping list?	'Boots', 'Cufflinks'	['question_type_global', 'question_three_hop_statement']
show me all of the stores on [2nd Avenue]	'holiday foods', 'fashion bar', 'burlington'	['question_type_global', 'question_single_statement']
what stores are located on [this street]?	'fashion bar'	['question_type_local']
what department stores on [2nd Avenue] have a sale?	'fashion bar', 'burlington'	['question_type_global', 'question_two_hop_statement']
is there anything on my list that's on sale somewhere near my current location?	'Goat', 'Boots', 'Cufflinks'	['question_type_global', 'question_four_hop_statement']
what do stores near me have on sale?	'flowers', 'Tubers', 'Onion', 'Combo washer dryer', 'Dishwasher', 'Water cooker', 'Goat', 'Stockings', 'Bow Tie', 'Boots', 'Lingerie', 'Cufflinks', 'Tripe', 'boom box', 'hair brush'	['question_type_global', 'question_three_hop_statement']
is there a store near my location is having a sale on [vegetables]?	'holiday foods'	['question_type_global', 'question_four_hop_statement']
i think this [joseph magnin] is somewhere on [Orchard Street]
[Clothes iron] and [Dishwasher] are no longer on sale at [that store]
Where is [Stockings] on sale?	'fashion bar'	['question_type_local']
show me all stores near [Orchard Street] that have a sale	'joseph magnin'	['question_type_global', 'question_two_hop_statement']
show me all stores near [Bridle Court]	'fashion bar'	['question_type_global', 'question_single_statement']
are there any [fruit] that i need to get?	'tangerine'	['question_type_global', 'question_two_hop_statement']
what are the supermarkets?	'holiday foods'	['question_type_global', 'question_single_statement']
what [clothing] do i need to buy?	'Boots', 'Cufflinks'	['question_type_global', 'question_two_hop_statement']
show me all department stores near [2nd Avenue]	'fashion bar', 'burlington'	['question_type_global', 'question_single_statement']
[Cufflinks], [Boots] and [Bow Tie] are on sale at [joseph magnin]
what are the supermarkets on [2nd Avenue]?	'holiday foods'	['question_type_global', 'question_single_statement']
show me all supermarkets near [2nd Avenue]	'holiday foods'	['question_type_global', 'question_single_statement']
is there a store nearby with a sale on [meat] going on right now?	'holiday foods'	['question_type_global', 'question_four_hop_statement']
what stores are there on [2nd Avenue]?	'holiday foods', 'fashion bar', 'burlington'	['question_type_global', 'question_single_statement']
[4th Street West] is in [Uptown]
is there a store nearby with a sale going on right now?	'burlington', 'fashion bar', 'holiday foods'	['question_type_global', 'question_three_hop_statement']
does any store nearby have anything on sale?	'burlington', 'fashion bar', 'holiday foods'	['question_type_global', 'question_three_hop_statement']
What stores is [this thing] on sale at	'joseph magnin', 'fashion bar'	['question_type_local']
does any store nearby have [Cufflinks] on sale?	'fashion bar'	['question_type_global', 'question_three_hop_statement']
show me all stores near [2nd Avenue] that have a sale on [gifts]	'fashion bar'	['question_type_global', 'question_three_hop_statement']
show me all stores on [2nd Avenue] that currently have a sale on [vegetables]	'holiday foods'	['question_type_global', 'question_three_hop_statement']
what neighborhood is [Bridle Court] in?	'Uptown'	['question_type_local']
is there a sale on any [meat] on my shopping list?	'Goat'	['question_type_global', 'question_three_hop_statement']
what stores on [2nd Avenue] have a sale on [clothing]?	'fashion bar'	['question_type_global', 'question_three_hop_statement']
what do i need to buy?	'Goat', 'Boots', 'Cufflinks', 'tangerine'	['question_type_global', 'question_single_statement']
[plum] and [pineapple] are both examples of [Fruit]
is there a store near my location is having a sale on [meat]?	'holiday foods'	['question_type_global', 'question_four_hop_statement']
are there any stores nearby that have a sale on items that i need?	'holiday foods', 'fashion bar'	['question_type_global', 'question_four_hop_statement']
does any store nearby have [meat] on sale?	'holiday foods'	['question_type_global', 'question_four_hop_statement']
show me all department stores near [Orchard Street]	'joseph magnin'	['question_type_global', 'question_single_statement']
what neighborhood am I in?	'Hays'	['question_type_local']
what stores on [2nd Avenue] have a sale on [vegetables]?	'holiday foods'	['question_type_global', 'question_three_hop_statement']
does any store nearby have [gifts] on sale?	'fashion bar'	['question_type_global', 'question_four_hop_statement']
i am pretty sure that [Old York Road] is in [Fishtown]
what neighborhood is [that street] located in?	'Fishtown'	['question_type_local']
what are the department stores?	'joseph magnin', 'fashion bar', 'burlington'	['question_type_global', 'question_single_statement']
are there any [fruit] that i need to get?	'tangerine'	['question_type_global', 'question_two_hop_statement']
is there a sale on any [clothing] on my shopping list?	'Boots', 'Cufflinks'	['question_type_global', 'question_three_hop_statement']
is there a sale on any items on my shopping list where i am?	'Goat', 'Boots', 'Cufflinks'	['question_type_global', 'question_four_hop_statement']
are there any [clothing] that i need to get?	'Boots', 'Cufflinks'	['question_type_global', 'question_two_hop_statement']
show me all stores on [Orchard Street] that currently have a sale	'joseph magnin'	['question_type_global', 'question_two_hop_statement']
is there a sale on [Onion] anywhere?	'holiday foods'	['question_type_local']
is there anything on my list that's on sale somewhere?	'Goat', 'Boots', 'Cufflinks'	['question_type_global', 'question_two_hop_statement']
Do i have any [fruit] on my shopping list?	'tangerine'	['question_type_global', 'question_two_hop_statement']
show me all stores on [Orchard Street] that currently have a sale on [appliances]	'joseph magnin'	['question_type_global', 'question_three_hop_statement']
Where is [boom box] on sale?	'fashion bar'	['question_type_local']
show me all stores on [2nd Avenue] that currently have a sale	'holiday foods', 'fashion bar', 'burlington'	['question_type_global', 'question_two_hop_statement']
is there a store nearby with any of the items on my shopping list on sale?	'holiday foods', 'fashion bar'	['question_type_global', 'question_four_hop_statement']
what department stores on [2nd Avenue] have a sale?	'fashion bar', 'burlington'	['question_type_global', 'question_two_hop_statement']
what neighborhood is [this street] in?	'Fishtown'	['question_type_local']
is there anything on my list that's on sale somewhere near my current location?	'Goat', 'Boots', 'Cufflinks'	['question_type_global', 'question_four_hop_statement']
show me all of the department stores on [Orchard Street]	'joseph magnin'	['question_type_global', 'question_single_statement']
[joseph magnin] has [Stockings] and [Tankini] on sale!
what items are on sale at [joseph magnin]?	'Automatic Rotimaker', 'Cold-pressed juicer', 'Water cooker', 'Stockings', 'Bow Tie', 'Boots', 'Cufflinks', 'Tankini'	['question_type_local']
what are the stores on [Orchard Street]?	'joseph magnin'	['question_type_global', 'question_single_statement']
show me all stores on [Orchard Street] that currently have a sale on [appliances]	'joseph magnin'	['question_type_global', 'question_three_hop_statement']
[nectarine] and [date] are both examples of [Fruit]
are there any stores nearby that have a sale on [appliances]?	'burlington', 'fashion bar'	['question_type_global', 'question_four_hop_statement']
is there anything on my list that's on sale somewhere?	'Goat', 'Boots', 'Cufflinks'	['question_type_global', 'question_two_hop_statement']
is there anything that I need for [linda's wedding] that's on sale somewhere?	'Boots', 'Cufflinks'	['question_type_global', 'question_two_hop_statement']
is there a store near my location is having a sale on [appliances]?	'burlington', 'fashion bar'	['question_type_global', 'question_four_hop_statement']
what is on sale near my current location?	'flowers', 'Tubers', 'Onion', 'Combo washer dryer', 'Dishwasher', 'Water cooker', 'Goat', 'Stockings', 'Bow Tie', 'Boots', 'Lingerie', 'Cufflinks', 'Tripe', 'boom box', 'hair brush'	['question_type_global', 'question_three_hop_statement']
is there a store nearby with a sale on [appliances] going on right now?	'burlington', 'fashion bar'	['question_type_global', 'question_four_hop_statement']
is there a sale on [Boots] anywhere?	'joseph magnin', 'fashion bar'	['question_type_local']
what stores near [2nd Avenue] have an ongoing sale on [clothing]?	'fashion bar'	['question_type_global', 'question_three_hop_statement']
Do i have any [clothing] on my shopping list?	'Boots', 'Cufflinks'	['question_type_global', 'question_two_hop_statement']
what stores on [Orchard Street] have a sale on [Bow Tie]?	'joseph magnin'	['question_type_global', 'question_two_hop_statement']
there is a [supermarket] called [hannaford] on [Hillside Drive]
what stores are there that I taught you?	'holiday foods', 'joseph magnin', 'fashion bar', 'burlington', 'hannaford'	['question_type_global', 'question_single_statement']
does any store nearby have [gifts] on sale?	'fashion bar'	['question_type_global', 'question_four_hop_statement']
is there anything on sale at a store nearby?	'flowers', 'Tubers', 'Onion', 'Combo washer dryer', 'Dishwasher', 'Water cooker', 'Goat', 'Stockings', 'Bow Tie', 'Boots', 'Lingerie', 'Cufflinks', 'Tripe', 'boom box', 'hair brush'	['question_type_global', 'question_three_hop_statement']
make sure to buy [camera] and [hair brush] for [linda's wedding]
What do I need to buy for [linda's wedding]?	'Boots', 'Cufflinks', 'camera', 'hair brush'	['question_type_local']
is there a store near my location is having a sale on [appliances]?	'burlington', 'fashion bar'	['question_type_global', 'question_four_hop_statement']
is there any [clothing] on my list that's on sale somewhere?	'Boots', 'Cufflinks'	['question_type_global', 'question_three_hop_statement']
what are the stores on [Orchard Street]?	'joseph magnin'	['question_type_global', 'question_single_statement']
Where is [Stockings] on sale?	'joseph magnin', 'fashion bar'	['question_type_local']
are there any [clothing] on my shopping list that there is a sale on?	'Boots', 'Cufflinks'	['question_type_global', 'question_three_hop_statement']
is there a sale on any [clothing] on my shopping list?	'Boots', 'Cufflinks'	['question_type_global', 'question_three_hop_statement']
what items that I have to buy for [linda's wedding] currently are on sale?	'Boots', 'Cufflinks', 'hair brush'	['question_type_global', 'question_two_hop_statement']
why do i need to buy [hair brush]?	"linda's wedding"	['question_type_local']
what department stores on [Orchard Street] have a sale?	'joseph magnin'	['question_type_global', 'question_two_hop_statement']
show me all stores	'holiday foods', 'joseph magnin', 'fashion bar', 'burlington', 'hannaford'	['question_type_global', 'question_single_statement']
are there any items on my shopping list that there is a sale on?	'Goat', 'Boots', 'Cufflinks', 'hair brush'	['question_type_global', 'question_two_hop_statement']
are there any items on my shopping list for [linda's wedding] that there is a sale on?	'Boots', 'Cufflinks', 'hair brush'	['question_type_global', 'question_two_hop_statement']
what is on sale at [joseph magnin]?	'Automatic Rotimaker', 'Cold-pressed juicer', 'Water cooker', 'Stockings', 'Bow Tie', 'Boots', 'Cufflinks', 'Tankini'	['question_type_local']
is there anything on sale at a store nearby?	'flowers', 'Tubers', 'Onion', 'Combo washer dryer', 'Dishwasher', 'Water cooker', 'Goat', 'Stockings', 'Bow Tie', 'Boots', 'Lingerie', 'Cufflinks', 'Tripe', 'boom box', 'hair brush'	['question_type_global', 'question_three_hop_statement']
what are the stores on [2nd Avenue]?	'burlington', 'holiday foods', 'fashion bar'	['question_type_local']
is there a store nearby with a sale on [hair brush] going on right now?	'fashion bar'	['question_type_global', 'question_three_hop_statement']
what is my shopping list?	'Goat', 'Boots', 'Cufflinks', 'tangerine', 'camera', 'hair brush'	['question_type_global', 'question_single_statement']
show me all department stores near [Bridle Court]	'fashion bar'	['question_type_global', 'question_single_statement']
what do i need [tangerine] for?	'thanksgiving dinner'	['question_type_local']
what do stores near me are have a sale on?	'flowers', 'Tubers', 'Onion', 'Combo washer dryer', 'Dishwasher', 'Water cooker', 'Goat', 'Stockings', 'Bow Tie', 'Boots', 'Lingerie', 'Cufflinks', 'Tripe', 'boom box', 'hair brush'	['question_type_global', 'question_three_hop_statement']
show me all stores on [2nd Avenue] that currently have a sale on [Combo washer dryer]	'fashion bar'	['question_type_global', 'question_two_hop_statement']
is there any [meat] on my list that's on sale somewhere?	'Goat'	['question_type_global', 'question_three_hop_statement']
are there any items on my shopping list that there is a sale on?	'Goat', 'Boots', 'Cufflinks', 'hair brush'	['question_type_global', 'question_two_hop_statement']
is there a sale on [Tubers] anywhere?	'holiday foods'	['question_type_local']
what stores are there that I taught you?	'holiday foods', 'joseph magnin', 'fashion bar', 'burlington', 'hannaford'	['question_type_global', 'question_single_statement']
[Horseradish], [Cucumber] and [Kale] are all types of [Vegetables]
is there a sale on any [meat] on my shopping list?	'Goat'	['question_type_global', 'question_three_hop_statement']
Do i have any [gifts] on my shopping list?	'camera', 'hair brush'	['question_type_global', 'question_two_hop_statement']
is there any [meat] that I have to buy currently are on sale?	'Goat'	['question_type_global', 'question_three_hop_statement']
[satsuma] is a [Fruit]
What stores is [Tubers] on sale at	'holiday foods'	['question_type_local']
what supermarkets are there?	'holiday foods', 'hannaford'	['question_type_global', 'question_single_statement']
are there any items on my shopping list for [linda's wedding] that there is a sale on?	'Boots', 'Cufflinks', 'hair brush'	['question_type_global', 'question_two_hop_statement']
what is on sale near my current location?	'flowers', 'Tubers', 'Onion', 'Combo washer dryer', 'Dishwasher', 'Water cooker', 'Goat', 'Stockings', 'Bow Tie', 'Boots', 'Lingerie', 'Cufflinks', 'Tripe', 'boom box', 'hair brush'	['question_type_global', 'question_three_hop_statement']
is there a store nearby with a sale on [appliances] going on right now?	'burlington', 'fashion bar'	['question_type_global', 'question_four_hop_statement']
What stores is [Cufflinks] on sale at	'joseph magnin', 'fashion bar'	['question_type_local']
is there a store near my location is having a sale on [Goat]?	'holiday foods'	['question_type_global', 'question_three_hop_statement']
what stores near [2nd Avenue] have an ongoing sale on [meat]?	'holiday foods'	['question_type_global', 'question_three_hop_statement']
show me all supermarkets that i tought you	'holiday foods', 'hannaford'	['question_type_global', 'question_single_statement']
is there a store nearby with a sale on [meat] going on right now?	'holiday foods'	['question_type_global', 'question_four_hop_statement']
what supermarkets are there?	'holiday foods', 'hannaford'	['question_type_global', 'question_single_statement']
is there a store near my location is having a sale on [gifts]?	'fashion bar'	['question_type_global', 'question_four_hop_statement']
are there any [meat] that i need to get?	'Goat'	['question_type_global', 'question_two_hop_statement']
are there any items on my shopping list that there is a sale on at a store nearby?	'Goat', 'Boots', 'Cufflinks', 'hair brush'	['question_type_global', 'question_four_hop_statement']
what are the supermarkets on [Hillside Drive]?	'hannaford'	['question_type_global', 'question_single_statement']
does any store nearby have [Combo washer dryer] on sale?	'fashion bar'	['question_type_global', 'question_three_hop_statement']
[Carrots], [Oregano] and [Mushrooms] are kinds of [Vegetables]
show me all of the supermarkets on [Hillside Drive]	'hannaford'	['question_type_global', 'question_single_statement']
is there anything that I need for [linda's wedding] that's on sale somewhere?	'Boots', 'Cufflinks', 'hair brush'	['question_type_global', 'question_two_hop_statement']
are there any stores nearby that have a sale on [appliances]?	'burlington', 'fashion bar'	['question_type_global', 'question_four_hop_statement']
What stores is [Boots] on sale at	'joseph magnin', 'fashion bar'	['question_type_local']
are there any stores nearby that have a sale on [gifts]?	'fashion bar'	['question_type_global', 'question_four_hop_statement']
What stores is [Onion] on sale at	'holiday foods'	['question_type_local']
is there a sale on any [clothing] on my shopping list?	'Boots', 'Cufflinks'	['question_type_global', 'question_three_hop_statement']
Do i have any [fruit] on my shopping list?	'tangerine'	['question_type_global', 'question_two_hop_statement']
Do i have any [meat] on my shopping list?	'Goat'	['question_type_global', 'question_two_hop_statement']
there is a [department store] called [fashion bar] on [Old York Road]
is there any [gifts] that I have to buy currently are on sale?	'hair brush'	['question_type_global', 'question_three_hop_statement']
are there any stores nearby that have a sale on [clothing]?	'fashion bar'	['question_type_global', 'question_four_hop_statement']
are there any stores nearby that have a sale on [meat]?	'holiday foods'	['question_type_global', 'question_four_hop_statement']
Do I need to buy any [meat]?	'Goat'	['question_type_global', 'question_two_hop_statement']
what department stores are there on [Bridle Court]?	'fashion bar'	['question_type_global', 'question_single_statement']
what is on sale at [fashion bar on 2nd Avenue]?	'flowers', 'Combo washer dryer', 'Water cooker', 'Stockings', 'Bow Tie', 'Boots', 'Lingerie', 'Cufflinks', 'boom box', 'hair brush'	['question_type_local']
what's currently on sale at [holiday foods]?	'Tubers', 'Onion', 'Goat', 'Tripe'	['question_type_local']
is there a store nearby with any of the items on my shopping list on sale?	'holiday foods', 'fashion bar'	['question_type_global', 'question_four_hop_statement']
[Lingerie] and [Stockings] are on sale at [fashion bar]
what stores on [Orchard Street] have a sale on [clothing]?	'joseph magnin'	['question_type_global', 'question_three_hop_statement']
are there any stores nearby that have a sale on [clothing]?	'fashion bar'	['question_type_global', 'question_four_hop_statement']
i absolutely must not forget to get [satsuma] for [thanksgiving dinner]
what do i need [that thing] for?	'thanksgiving dinner'	['question_type_local']
is there a store near my location is having a sale on [meat]?	'holiday foods'	['question_type_global', 'question_four_hop_statement']
what items do I need to get?	'Goat', 'Boots', 'Cufflinks', 'tangerine', 'camera', 'hair brush', 'satsuma'	['question_type_global', 'question_single_statement']
what [clothing] do i need to buy?	'Boots', 'Cufflinks'	['question_type_global', 'question_two_hop_statement']
does any store nearby have [Onion] on sale?	'holiday foods'	['question_type_global', 'question_three_hop_statement']
what are the things that i need to get?	'Goat', 'Boots', 'Cufflinks', 'tangerine', 'camera', 'hair brush', 'satsuma'	['question_type_global', 'question_single_statement']
does any store nearby have [clothing] on sale?	'fashion bar'	['question_type_global', 'question_four_hop_statement']
show me all stores on [2nd Avenue] that currently have a sale on [meat]	'holiday foods'	['question_type_global', 'question_three_hop_statement']
what items that I have to buy for [thanksgiving dinner] currently are on sale?	'Goat'	['question_type_global', 'question_two_hop_statement']
is there a sale on any [clothing] on my shopping list?	'Boots', 'Cufflinks'	['question_type_global', 'question_three_hop_statement']
Do i have any [clothing] on my shopping list?	'Boots', 'Cufflinks'	['question_type_global', 'question_two_hop_statement']
are there any [fruit] that i need to get?	'tangerine', 'satsuma'	['question_type_global', 'question_two_hop_statement']
[Boots], [Bow Tie] and [Tankini] are all on sale at [fashion bar on Bridle Court]
[fashion bar on Bridle Court] no longer has [Boots], [Tankini] and [Bow Tie] on sale
Do I need to buy any [fruit]?	'tangerine', 'satsuma'	['question_type_global', 'question_two_hop_statement']
i often shop at [armstrong's], which is my local [department store]
[Combo washer dryer], [Cold-pressed juicer] and [Automatic Rotimaker] are on sale at [that department store]
[armstrong's] no longer has [Combo washer dryer], [Automatic Rotimaker] and [Cold-pressed juicer] on sale
this [armstrong's] is on [Grove Avenue]
Do i have any [meat] on my shopping list?	'Goat'	['question_type_global', 'question_two_hop_statement']
what neighborhood is [2nd Avenue] located in?	'Hays'	['question_type_local']
what department stores are there	'joseph magnin', 'fashion bar', 'burlington', "armstrong's"	['question_type_global', 'question_single_statement']
[armstrong's] has [Boots] and [Tankini] on sale!
what's currently on sale at [armstrong's]?	'Boots', 'Tankini'	['question_type_local']
what items do I need to get?	'Goat', 'Boots', 'Cufflinks', 'tangerine', 'camera', 'hair brush', 'satsuma'	['question_type_global', 'question_single_statement']
is there a store near my location is having a sale on [vegetables]?	'holiday foods'	['question_type_global', 'question_four_hop_statement']
show me all stores near [Grove Avenue]	"armstrong's"	['question_type_global', 'question_single_statement']
What stores is [Tankini] on sale at	'joseph magnin', "armstrong's"	['question_type_local']
what stores near [Orchard Street] have an ongoing sale on [Cufflinks]?	'joseph magnin'	['question_type_global', 'question_two_hop_statement']
show me all department stores near [Orchard Street]	'joseph magnin'	['question_type_global', 'question_single_statement']
there is a [department store] called [armstrong's] that I shop in pretty often
[that store] has [Cufflinks] and [Boots] on sale!
[Boots] is no longer on sale at [armstrong's that I last mentioned]
this specific [this department store] is on [2nd Avenue]
is there a store nearby with a sale on [gifts] going on right now?	'fashion bar'	['question_type_global', 'question_four_hop_statement']
what stores are located on [2nd Avenue]?	'burlington', 'holiday foods', "armstrong's", 'fashion bar'	['question_type_local']
what event do I need to buy [Boots] for	"linda's wedding"	['question_type_local']
what supermarkets are there on [2nd Avenue]?	'holiday foods'	['question_type_global', 'question_single_statement']
i need to get [pineapple] for [thanksgiving dinner]
what items did i already get for [thanksgiving dinner]?	'Tubers', 'Onion', 'Calf liver', 'banana', 'boysenberry'	['question_type_local']
is there anything on my list that's on sale somewhere near my current location?	'Goat', 'Boots', 'Cufflinks', 'hair brush'	['question_type_global', 'question_four_hop_statement']
show me all department stores on [Grove Avenue] that currently have a sale	"armstrong's"	['question_type_global', 'question_two_hop_statement']
what department stores are there	'joseph magnin', 'fashion bar', 'burlington', "armstrong's"	['question_type_global', 'question_single_statement']
show me all stores on [Orchard Street] that currently have a sale on [appliances]	'joseph magnin'	['question_type_global', 'question_three_hop_statement']
show me all of the stores on [Bridle Court]	'fashion bar'	['question_type_global', 'question_single_statement']
Where is [Automatic Rotimaker] on sale?	'joseph magnin'	['question_type_local']
is there any [meat] on my list that's on sale somewhere?	'Goat'	['question_type_global', 'question_three_hop_statement']
[Boots], [Cufflinks] and [Stockings] are all on sale at [fashion bar on Bridle Court]
[fashion bar on Bridle Court] no longer has [Cufflinks], [Stockings] and [Boots] on sale
what items that I have to buy currently are on sale near me?	'Goat', 'Boots', 'Cufflinks', 'hair brush'	['question_type_global', 'question_four_hop_statement']
[Venison] is a [Meat]
what stores near [Grove Avenue] have an ongoing sale?	"armstrong's"	['question_type_global', 'question_two_hop_statement']
are there any stores nearby that have a sale on items that i need?	'holiday foods', 'fashion bar', "armstrong's"	['question_type_global', 'question_four_hop_statement']
show me all stores	'holiday foods', 'joseph magnin', 'fashion bar', 'burlington', 'hannaford', "armstrong's"	['question_type_global', 'question_single_statement']
Where is [flowers] on sale?	'fashion bar'	['question_type_local']
what department stores on [Orchard Street] have a sale?	'joseph magnin'	['question_type_global', 'question_two_hop_statement']
What do I need to buy [pineapple] for?	'thanksgiving dinner'	['question_type_local']
what department stores are there on [2nd Avenue]?	'fashion bar', 'burlington', "armstrong's"	['question_type_global', 'question_single_statement']
show me all stores near [Hillside Drive]	'hannaford'	['question_type_global', 'question_single_statement']
is there a store nearby with a sale on [clothing] going on right now?	"armstrong's", 'fashion bar'	['question_type_global', 'question_four_hop_statement']
what are the stores on [2nd Avenue]?	'burlington', 'holiday foods', "armstrong's", 'fashion bar'	['question_type_local']
is there any [clothing] that I have to buy currently are on sale?	'Boots', 'Cufflinks'	['question_type_global', 'question_three_hop_statement']
what are the department stores on [Bridle Court]?	'fashion bar'	['question_type_global', 'question_single_statement']
are there any [clothing] on my shopping list that there is a sale on?	'Boots', 'Cufflinks'	['question_type_global', 'question_three_hop_statement']
show me all of the supermarkets	'holiday foods', 'hannaford'	['question_type_global', 'question_single_statement']
Do I need to buy any [fruit]?	'tangerine', 'pineapple', 'satsuma'	['question_type_global', 'question_two_hop_statement']
what [gifts] do i need to buy?	'camera', 'hair brush'	['question_type_global', 'question_two_hop_statement']
show me all stores near [Orchard Street]	'joseph magnin'	['question_type_global', 'question_single_statement']
what stores are on [2nd Avenue]?	'burlington', 'holiday foods', "armstrong's", 'fashion bar'	['question_type_local']
does any store nearby have [gifts] on sale?	'fashion bar'	['question_type_global', 'question_four_hop_statement']
what kind of [fruit] do I need to get?	'tangerine', 'pineapple', 'satsuma'	['question_type_global', 'question_two_hop_statement']
does any store nearby have [Cufflinks] on sale?	"armstrong's", 'fashion bar'	['question_type_global', 'question_three_hop_statement']
does any store nearby have [Goat] on sale?	'holiday foods'	['question_type_global', 'question_three_hop_statement']
is there a store nearby with any of the items on my shopping list on sale?	'holiday foods', 'fashion bar', "armstrong's"	['question_type_global', 'question_four_hop_statement']
is there a store near my location is having a sale on [meat]?	'holiday foods'	['question_type_global', 'question_four_hop_statement']
what department stores on [Grove Avenue] have a sale?	"armstrong's"	['question_type_global', 'question_two_hop_statement']
are there any [gifts] on my shopping list that there is a sale on?	'hair brush'	['question_type_global', 'question_three_hop_statement']
what do i need [Goat] for?	'thanksgiving dinner'	['question_type_local']
are there any stores nearby that have a sale on [vegetables]?	'holiday foods'	['question_type_global', 'question_four_hop_statement']
is there anything that I need for [linda's wedding] that's on sale somewhere?	'Boots', 'Cufflinks', 'hair brush'	['question_type_global', 'question_two_hop_statement']
show me all supermarkets near [2nd Avenue]	'holiday foods'	['question_type_global', 'question_single_statement']
is there anything on my list that's on sale somewhere near my current location?	'Goat', 'Boots', 'Cufflinks', 'hair brush'	['question_type_global', 'question_four_hop_statement']
what stores are there on [Hillside Drive]?	'hannaford'	['question_type_global', 'question_single_statement']
what [gifts] do i need to buy?	'camera', 'hair brush'	['question_type_global', 'question_two_hop_statement']
are there any stores nearby that have a sale?	"armstrong's", 'burlington', 'fashion bar', 'holiday foods'	['question_type_global', 'question_three_hop_statement']
what kind of [fruit] do I need to get?	'tangerine', 'pineapple', 'satsuma'	['question_type_global', 'question_two_hop_statement']
what department stores are there on [Bridle Court]?	'fashion bar'	['question_type_global', 'question_single_statement']
is there a sale on [Tubers] anywhere?	'holiday foods'	['question_type_local']
Do I need to buy any [clothing]?	'Boots', 'Cufflinks'	['question_type_global', 'question_two_hop_statement']
does any store nearby have anything on sale?	"armstrong's", 'burlington', 'fashion bar', 'holiday foods'	['question_type_global', 'question_three_hop_statement']
show me all stores on [2nd Avenue] that currently have a sale on [flowers]	'fashion bar'	['question_type_global', 'question_two_hop_statement']
are there any [gifts] that i need to get?	'camera', 'hair brush'	['question_type_global', 'question_two_hop_statement']
[armstrong's] is a [department store]
Where is [flowers] on sale?	'fashion bar'	['question_type_local']
are there any [meat] on my shopping list that there is a sale on?	'Goat'	['question_type_global', 'question_three_hop_statement']
what items are on sale at [fashion bar on Old York Road]?	'Stockings', 'Lingerie'	['question_type_local']
what kind of [gifts] do I need to get?	'camera', 'hair brush'	['question_type_global', 'question_two_hop_statement']
show me all of the supermarkets	'holiday foods', 'hannaford'	['question_type_global', 'question_single_statement']
what stores are located on [Orchard Street]?	'joseph magnin'	['question_type_local']
what is my shopping list?	'Goat', 'Boots', 'Cufflinks', 'tangerine', 'camera', 'hair brush', 'pineapple', 'satsuma'	['question_type_global', 'question_single_statement']
[fashion bar on 2nd Avenue] has [camera] and [tv] on sale!
are there any [gifts] on my shopping list that there is a sale on?	'camera', 'hair brush'	['question_type_global', 'question_three_hop_statement']
Do I need to buy any [meat]?	'Goat'	['question_type_global', 'question_two_hop_statement']
what are the things that i need to get?	'Goat', 'Boots', 'Cufflinks', 'tangerine', 'camera', 'hair brush', 'pineapple', 'satsuma'	['question_type_global', 'question_single_statement']
What stores is [Cufflinks] on sale at	'joseph magnin', "armstrong's", 'fashion bar'	['question_type_local']
what [fruit] do i need to buy?	'tangerine', 'pineapple', 'satsuma'	['question_type_global', 'question_two_hop_statement']
is there any [clothing] on my list that's on sale somewhere?	'Boots', 'Cufflinks'	['question_type_global', 'question_three_hop_statement']
[Church Street South] is in [East Hills]
show me all supermarkets that i tought you	'holiday foods', 'hannaford'	['question_type_global', 'question_single_statement']
what stores are there on [Bridle Court]?	'fashion bar'	['question_type_global', 'question_single_statement']
are there any [meat] on my shopping list that there is a sale on?	'Goat'	['question_type_global', 'question_three_hop_statement']
is there a store nearby with a sale on [vegetables] going on right now?	'holiday foods'	['question_type_global', 'question_four_hop_statement']
Do i have any [meat] on my shopping list?	'Goat'	['question_type_global', 'question_two_hop_statement']
what items that I have to buy for [thanksgiving dinner] currently are on sale?	'Goat'	['question_type_global', 'question_two_hop_statement']
are there any stores nearby that have a sale on [clothing]?	"armstrong's", 'fashion bar'	['question_type_global', 'question_four_hop_statement']
does any store nearby have [vegetables] on sale?	'holiday foods'	['question_type_global', 'question_four_hop_statement']
what is on sale at [fashion bar that I last mentioned]?	'Stockings', 'Lingerie'	['question_type_local']
does any store nearby have [meat] on sale?	'holiday foods'	['question_type_global', 'question_four_hop_statement']
is there a sale on any [gifts] on my shopping list?	'camera', 'hair brush'	['question_type_global', 'question_three_hop_statement']
what supermarkets are there on [2nd Avenue]?	'holiday foods'	['question_type_global', 'question_single_statement']
what [gifts] do i need to buy?	'camera', 'hair brush'	['question_type_global', 'question_two_hop_statement']
what stores near [Grove Avenue] have an ongoing sale?	"armstrong's"	['question_type_global', 'question_two_hop_statement']
what stores near [Old York Road] have an ongoing sale on [clothing]?	'fashion bar'	['question_type_global', 'question_three_hop_statement']
is there a store near my location is having a sale on [appliances]?	'burlington', 'fashion bar'	['question_type_global', 'question_four_hop_statement']
does any store nearby have [Tripe] on sale?	'holiday foods'	['question_type_global', 'question_three_hop_statement']
is there a store nearby with a sale going on right now?	"armstrong's", 'burlington', 'fashion bar', 'holiday foods'	['question_type_global', 'question_three_hop_statement']
what neighborhood is [Orchard Street] located in?	'Uptown'	['question_type_local']
is there a store near my location is having a sale on [hair brush]?	'fashion bar'	['question_type_global', 'question_three_hop_statement']
is there any [gifts] on my list that's on sale somewhere?	'camera', 'hair brush'	['question_type_global', 'question_three_hop_statement']
is there a sale on any [clothing] on my shopping list?	'Boots', 'Cufflinks'	['question_type_global', 'question_three_hop_statement']
what supermarkets are there on [2nd Avenue]?	'holiday foods'	['question_type_global', 'question_single_statement']
[Lexington Drive] is located in the [Hays] neighborhood
what neighborhood is [Church Street South] in?	'East Hills'	['question_type_local']
is there a store nearby with a sale on [gifts] going on right now?	'fashion bar'	['question_type_global', 'question_four_hop_statement']
are there any stores nearby that have a sale on [vegetables]?	'holiday foods'	['question_type_global', 'question_four_hop_statement']
are there any [meat] on my shopping list that there is a sale on?	'Goat'	['question_type_global', 'question_three_hop_statement']
there is a [supermarket] called [hannaford] on [Old York Road]
what's currently on sale at [fashion bar on Old York Road]?	'Stockings', 'Lingerie'	['question_type_local']
what do stores near me have on sale?	'flowers', 'Tubers', 'Onion', 'Combo washer dryer', 'Dishwasher', 'Water cooker', 'Goat', 'Stockings', 'Bow Tie', 'Boots', 'Lingerie', 'Cufflinks', 'Tripe', 'boom box', 'camera', 'hair brush', 'tv'	['question_type_global', 'question_three_hop_statement']
is there a sale on any [clothing] on my shopping list?	'Boots', 'Cufflinks'	['question_type_global', 'question_three_hop_statement']
what kind of [gifts] do I need to get?	'camera', 'hair brush'	['question_type_global', 'question_two_hop_statement']
what event do I need to buy [camera] for	"linda's wedding"	['question_type_local']
Do I need to buy any [gifts]?	'camera', 'hair brush'	['question_type_global', 'question_two_hop_statement']
Do i have any [gifts] on my shopping list?	'camera', 'hair brush'	['question_type_global', 'question_two_hop_statement']
is there a store nearby with a sale on [clothing] going on right now?	"armstrong's", 'fashion bar'	['question_type_global', 'question_four_hop_statement']
are there any [clothing] that i need to get?	'Boots', 'Cufflinks'	['question_type_global', 'question_two_hop_statement']
here are some examples of [Gift]: [watch], [doll] and [television]
is there a sale on any items on my shopping list where i am?	'Goat', 'Boots', 'Cufflinks', 'camera', 'hair brush'	['question_type_global', 'question_four_hop_statement']
what items that I have to buy for [linda's wedding] currently are on sale?	'Boots', 'Cufflinks', 'camera', 'hair brush'	['question_type_global', 'question_two_hop_statement']
what neighborhood is [Lexington Drive] located in?	'Hays'	['question_type_local']
does any store nearby have anything on sale?	"armstrong's", 'burlington', 'fashion bar', 'holiday foods'	['question_type_global', 'question_three_hop_statement']
are there any items on my shopping list that there is a sale on?	'Goat', 'Boots', 'Cufflinks', 'camera', 'hair brush'	['question_type_global', 'question_two_hop_statement']
show me all stores near [Hillside Drive]	'hannaford'	['question_type_global', 'question_single_statement']
are there any items on my shopping list that there is a sale on at a store nearby?	'Goat', 'Boots', 'Cufflinks', 'camera', 'hair brush'	['question_type_global', 'question_four_hop_statement']
what stores are on [Grove Avenue]?	"armstrong's"	['question_type_local']
[Tankini] and [Boots] are on sale at [burlington]
what event do I need to buy [Cufflinks] for	"linda's wedding"	['question_type_local']
does any store nearby have [vegetables] on sale?	'holiday foods'	['question_type_global', 'question_four_hop_statement']
is there anything on my list that's on sale somewhere near my current location?	'Goat', 'Boots', 'Cufflinks', 'camera', 'hair brush'	['question_type_global', 'question_four_hop_statement']
is there a sale on any [meat] on my shopping list?	'Goat'	['question_type_global', 'question_three_hop_statement']
what is on sale at [holiday foods]?	'Tubers', 'Onion', 'Goat', 'Tripe'	['question_type_local']
show me all of the supermarkets	'holiday foods', 'hannaford'	['question_type_global', 'question_single_statement']
[perfume] and [balloon] are types of [Gift]
[huckleberry] is a kind of [Fruit]
Where is [flowers] on sale?	'fashion bar'	['question_type_local']
is there a store nearby with a sale on [meat] going on right now?	'holiday foods'	['question_type_global', 'question_four_hop_statement']
i think [9th Street West] is in [East Hills]
what is on sale near my current location?	'flowers', 'Tubers', 'Onion', 'Combo washer dryer', 'Dishwasher', 'Water cooker', 'Goat', 'Stockings', 'Bow Tie', 'Boots', 'Lingerie', 'Cufflinks', 'Tripe', 'boom box', 'camera', 'hair brush', 'tv', 'Tankini'	['question_type_global', 'question_three_hop_statement']
are there any stores nearby that have a sale?	"armstrong's", 'burlington', 'fashion bar', 'holiday foods'	['question_type_global', 'question_three_hop_statement']
what do stores near me are have a sale on?	'flowers', 'Tubers', 'Onion', 'Combo washer dryer', 'Dishwasher', 'Water cooker', 'Goat', 'Stockings', 'Bow Tie', 'Boots', 'Lingerie', 'Cufflinks', 'Tripe', 'boom box', 'camera', 'hair brush', 'tv', 'Tankini'	['question_type_global', 'question_three_hop_statement']
show me all supermarkets near [Hillside Drive]	'hannaford'	['question_type_global', 'question_single_statement']
show me all department stores	'joseph magnin', 'fashion bar', 'burlington', "armstrong's"	['question_type_global', 'question_single_statement']
show me all of the department stores	'joseph magnin', 'fashion bar', 'burlington', "armstrong's"	['question_type_global', 'question_single_statement']
what stores on [Grove Avenue] have a sale on [clothing]?	"armstrong's"	['question_type_global', 'question_three_hop_statement']
what are the stores?	'holiday foods', 'joseph magnin', 'fashion bar', 'burlington', 'hannaford', "armstrong's"	['question_type_global', 'question_single_statement']
show me all stores near [2nd Avenue] that have a sale on [meat]	'holiday foods'	['question_type_global', 'question_three_hop_statement']
does any store nearby have [Goat] on sale?	'holiday foods'	['question_type_global', 'question_three_hop_statement']
are there any [clothing] that i need to get?	'Boots', 'Cufflinks'	['question_type_global', 'question_two_hop_statement']
what are the department stores?	'joseph magnin', 'fashion bar', 'burlington', "armstrong's"	['question_type_global', 'question_single_statement']
is there a sale on [Boots] anywhere?	'joseph magnin', "armstrong's", 'fashion bar', 'burlington'	['question_type_local']
is there anything on my list that's on sale somewhere near my current location?	'Goat', 'Boots', 'Cufflinks', 'camera', 'hair brush'	['question_type_global', 'question_four_hop_statement']
what [gifts] do i need to buy?	'camera', 'hair brush'	['question_type_global', 'question_two_hop_statement']
is there a store near my location is having a sale on [vegetables]?	'holiday foods'	['question_type_global', 'question_four_hop_statement']
Do i have any [gifts] on my shopping list?	'camera', 'hair brush'	['question_type_global', 'question_two_hop_statement']
does any store nearby have [Bow Tie] on sale?	'fashion bar'	['question_type_global', 'question_three_hop_statement']
show me all stores near [2nd Avenue] that have a sale on [vegetables]	'holiday foods'	['question_type_global', 'question_three_hop_statement']
is there a sale on any [clothing] on my shopping list?	'Boots', 'Cufflinks'	['question_type_global', 'question_three_hop_statement']
[hannaford on Old York Road] has [Oregano], [Onion] and [Cucumber] on sale!
[Onion], [Oregano] and [Cucumber] stopped being on sale at [hannaford that I last mentioned]
show me all stores near [2nd Avenue] that have a sale on [meat]	'holiday foods'	['question_type_global', 'question_three_hop_statement']
what [fruit] do i need to buy?	'tangerine', 'pineapple', 'satsuma'	['question_type_global', 'question_two_hop_statement']
what is on sale at [joseph magnin]?	'Automatic Rotimaker', 'Cold-pressed juicer', 'Water cooker', 'Stockings', 'Bow Tie', 'Boots', 'Cufflinks', 'Tankini'	['question_type_local']
are there any stores nearby that have a sale on [meat]?	'holiday foods'	['question_type_global', 'question_four_hop_statement']
show me all of the department stores on [Bridle Court]	'fashion bar'	['question_type_global', 'question_single_statement']
does any store nearby have [hair brush] on sale?	'fashion bar'	['question_type_global', 'question_three_hop_statement']
is there a sale on any items on my shopping list where i am?	'Goat', 'Boots', 'Cufflinks', 'camera', 'hair brush'	['question_type_global', 'question_four_hop_statement']
is there a store nearby with any of the items on my shopping list on sale?	'holiday foods', 'fashion bar', 'burlington', "armstrong's"	['question_type_global', 'question_four_hop_statement']
What stores is [Cold-pressed juicer] on sale at	'joseph magnin'	['question_type_local']
is there a store near my location is having a sale on [Tubers]?	'holiday foods'	['question_type_global', 'question_three_hop_statement']
is there a store near my location is having a sale on [vegetables]?	'holiday foods'	['question_type_global', 'question_four_hop_statement']
does any store nearby have [meat] on sale?	'holiday foods'	['question_type_global', 'question_four_hop_statement']
is there a sale on any [gifts] on my shopping list?	'camera', 'hair brush'	['question_type_global', 'question_three_hop_statement']
are there any stores nearby that have a sale on items that i need?	'holiday foods', 'fashion bar', 'burlington', "armstrong's"	['question_type_global', 'question_four_hop_statement']
are there any stores nearby that have a sale?	"armstrong's", 'burlington', 'fashion bar', 'holiday foods'	['question_type_global', 'question_three_hop_statement']
what stores near [2nd Avenue] have an ongoing sale on [appliances]?	'fashion bar', 'burlington'	['question_type_global', 'question_three_hop_statement']
are there any [clothing] on my shopping list that there is a sale on?	'Boots', 'Cufflinks'	['question_type_global', 'question_three_hop_statement']
does any store nearby have [vegetables] on sale?	'holiday foods'	['question_type_global', 'question_four_hop_statement']
what event do I need to buy [Boots] for	"linda's wedding"	['question_type_local']
what are the department stores on [Orchard Street]?	'joseph magnin'	['question_type_global', 'question_single_statement']
show me all of the stores on [Orchard Street]	'joseph magnin'	['question_type_global', 'question_single_statement']
is there a store near my location is having a sale on [meat]?	'holiday foods'	['question_type_global', 'question_four_hop_statement']
does any store nearby have anything on sale?	"armstrong's", 'burlington', 'fashion bar', 'holiday foods'	['question_type_global', 'question_three_hop_statement']
is there a sale on any [meat] on my shopping list?	'Goat'	['question_type_global', 'question_three_hop_statement']
what are the department stores on [Old York Road]?	'fashion bar'	['question_type_global', 'question_single_statement']
what items are on sale at [joseph magnin]?	'Automatic Rotimaker', 'Cold-pressed juicer', 'Water cooker', 'Stockings', 'Bow Tie', 'Boots', 'Cufflinks', 'Tankini'	['question_type_local']
what are the stores?	'holiday foods', 'joseph magnin', 'fashion bar', 'burlington', 'hannaford', "armstrong's"	['question_type_global', 'question_single_statement']
Where is [tv] on sale?	'fashion bar'	['question_type_local']
are there any stores nearby that have a sale on [appliances]?	'burlington', 'fashion bar'	['question_type_global', 'question_four_hop_statement']
what supermarkets are there on [2nd Avenue]?	'holiday foods'	['question_type_global', 'question_single_statement']
what stores are there that I taught you?	'holiday foods', 'joseph magnin', 'fashion bar', 'burlington', 'hannaford', "armstrong's"	['question_type_global', 'question_single_statement']
what [gifts] do i need to buy?	'camera', 'hair brush'	['question_type_global', 'question_two_hop_statement']
show me all stores near [2nd Avenue] that have a sale on [Onion]	'holiday foods'	['question_type_global', 'question_two_hop_statement']
show me all stores near [Bridle Court]	'fashion bar'	['question_type_global', 'question_single_statement']
is there a sale on any [meat] on my shopping list?	'Goat'	['question_type_global', 'question_three_hop_statement']
what stores are located on [Bridle Court]?	'fashion bar'	['question_type_local']
is there a sale on any items on my shopping list?	'Goat', 'Boots', 'Cufflinks', 'camera', 'hair brush'	['question_type_global', 'question_two_hop_statement']
is there any [meat] that I have to buy currently are on sale?	'Goat'	['question_type_global', 'question_three_hop_statement']
what event do I need to buy [tangerine] for	'thanksgiving dinner'	['question_type_local']
show me all of the department stores on [2nd Avenue]	'fashion bar', 'burlington', "armstrong's"	['question_type_global', 'question_single_statement']
show me all of the department stores	'joseph magnin', 'fashion bar', 'burlington', "armstrong's"	['question_type_global', 'question_single_statement']
are there any [clothing] that i need to get?	'Boots', 'Cufflinks'	['question_type_global', 'question_two_hop_statement']
show me all stores near [Grove Avenue]	"armstrong's"	['question_type_global', 'question_single_statement']
what are the supermarkets?	'holiday foods', 'hannaford'	['question_type_global', 'question_single_statement']
Do I need to buy any [meat]?	'Goat'	['question_type_global', 'question_two_hop_statement']
is there a store nearby with a sale on [vegetables] going on right now?	'holiday foods'	['question_type_global', 'question_four_hop_statement']
what items are on sale at nearby stores?	'flowers', 'Tubers', 'Onion', 'Combo washer dryer', 'Dishwasher', 'Water cooker', 'Goat', 'Stockings', 'Bow Tie', 'Boots', 'Lingerie', 'Cufflinks', 'Tripe', 'boom box', 'camera', 'hair brush', 'tv', 'Tankini'	['question_type_global', 'question_three_hop_statement']
show me all stores near [Hillside Drive]	'hannaford'	['question_type_global', 'question_single_statement']
What stores is [Water cooker] on sale at	'joseph magnin', 'fashion bar'	['question_type_local']
is there a sale on any items on my shopping list?	'Goat', 'Boots', 'Cufflinks', 'camera', 'hair brush'	['question_type_global', 'question_two_hop_statement']
What stores is [Boots] on sale at	'joseph magnin', "armstrong's", 'fashion bar', 'burlington'	['question_type_local']
what items that I have to buy for [thanksgiving dinner] currently are on sale?	'Goat'	['question_type_global', 'question_two_hop_statement']
is there any [meat] on my list that's on sale somewhere?	'Goat'	['question_type_global', 'question_three_hop_statement']
there is a [supermarket] called [holiday foods] on [4th Street West]
[Duck] is on sale at [this store]
what's currently on sale at [this store]?	'Duck'	['question_type_local']
[plum] is on sale at [holiday foods]
what stores on [Grove Avenue] have a sale on [clothing]?	"armstrong's"	['question_type_global', 'question_three_hop_statement']
are there any stores nearby that have a sale on [appliances]?	'burlington', 'fashion bar'	['question_type_global', 'question_four_hop_statement']
