there is a new [early stage] [mobile] [project]
[mobile project] is in the [evaluation] stage
Which is the stage of [mobile project]?	'evaluation'	['question_type_local']
there is a new [early stage] [chatbot] [project]
[chatbot project] is currently in the [testing] stage
[this project] is now in the [evaluation] stage
there is a new [external] [knowledge base] [project]
[Isaiah] is a [tester] on [chatbot project]
[it] is in the [testing] stage
[Casey] is a [tester]
[this person] is working on [knowledge base project]
[he] is assigned to [mobile project] also
[this person] is working on [chatbot project] also
Who is working on [that project]?	'Isaiah', 'Casey'	['question_type_local']
[he] created a new issue for [this project]: [two consecutive dates identified as single date]
[that project] is now in the [testing] stage
[Vivienne] is a [developer] on [chatbot project]
[this developer] is working on [knowledge base project] also
[she] is assigned to [mobile project] also
[xml extractor exception] is a new [bug] created by [Casey] for [knowledge base project]
[this issue] is assigned to [Casey]
[this test engineer] resolved [that issue]
Who submitted [it]?	'Casey'	['question_type_local']
Are there any testers assigned to the [external] projects?	'Casey'	['question_type_global', 'question_three_hop_statement']
Are there any [bug]s that are not resolved?	'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
What stage is [knowledge base project] in?	'testing'	['question_type_local']
who are the developers?	'Vivienne'	['question_type_global', 'question_single_statement']
who are the testers?	'Isaiah', 'Casey'	['question_type_global', 'question_single_statement']
[the two consecutive dates identified as single date issue] is assigned to [Vivienne]
[Bob] is a [developer]
[Marisela] is a [developer] on [mobile project]
[she] is working on [knowledge base project] also
Are there any issues assigned to [Casey] that are resolved?	'xml extractor exception'	['question_type_local']
What are the non resolved issues for [early stage] projects?	'two consecutive dates identified as single date'	['question_type_global', 'question_two_hop_statement']
What projects is [Casey] working on?	'mobile', 'chatbot', 'knowledge base'	['question_type_local']
Are there any testers assigned to projects in the [testing] stage?	'Isaiah', 'Casey'	['question_type_global', 'question_three_hop_statement']
Are there any testers assigned to the [early stage] projects?	'Isaiah', 'Casey'	['question_type_global', 'question_three_hop_statement']
who are the developers?	'Vivienne', 'Bob', 'Marisela'	['question_type_global', 'question_single_statement']
[that person] is working on [chatbot project] also
Who has issues assigned to them that were not resolved?	'Vivienne'	['question_type_global', 'question_two_hop_statement']
[Willis] is a [tester] on [mobile project]
[chatbot project] is in the stage of [deployment]
Are there any developers assigned to projects in the [testing] stage?	'Vivienne', 'Marisela'	['question_type_global', 'question_three_hop_statement']
Are there any people assigned to the [external] projects?	'Casey', 'Vivienne', 'Marisela'	['question_type_global', 'question_two_hop_statement']
What are the [early stage] projects?	'mobile', 'chatbot'	['question_type_global', 'question_single_statement']
Which testers are working on [knowledge base project]?	'Casey'	['question_type_local']
Who are the developers currently working on the [early stage] projects?	'Vivienne', 'Marisela'	['question_type_global', 'question_three_hop_statement']
Are there any issues that are resolved?	'xml extractor exception'	['question_type_global', 'question_single_statement']
[this test engineer] is assigned to [chatbot project] also
[Yoshiko] is a [developer] on [mobile project]
[that developer] is assigned to [it] also
[that developer] is assigned to [knowledge base project] also
Are there any [early stage] projects?	'mobile', 'chatbot'	['question_type_global', 'question_single_statement']
who are the developers?	'Vivienne', 'Bob', 'Marisela', 'Yoshiko'	['question_type_global', 'question_single_statement']
[Vivienne] created a new issue for [mobile project]: [wrong pos tag on consecutive words]
[this issue] is assigned to [Casey]
[this person] resolved [that issue]
[that test engineer] is not working on [mobile project] anymore
[this project] has moved to the [testing] stage
[Casey] is assigned to [mobile project] also
[that test engineer] is not working on [that project] anymore
Who submitted [the xml extractor exception issue]?	'Casey'	['question_type_local']
Are there any issues that are resolved for [early stage] projects?	'wrong pos tag on consecutive words'	['question_type_global', 'question_two_hop_statement']
[Casey] is working on [this project] also
[Emma] is a [tester]
[Vivienne] submitted a new [task] for [chatbot project]: [svd is slow]
[the svd is slow issue] is assigned to [Willis]
[this person] resolved [the svd is slow task]
[Vivienne] resolved [the two consecutive dates identified as single date issue]
Who submitted [the wrong pos tag on consecutive words issue]?	'Vivienne'	['question_type_local']
Which developers have issues assigned to them that were all resolved?	'Vivienne'	['question_type_global', 'question_three_hop_statement']
Who are the testers currently working on the [external] projects?	'Casey'	['question_type_global', 'question_three_hop_statement']
Who is working on [knowledge base project]?	'Casey', 'Vivienne', 'Marisela', 'Yoshiko'	['question_type_local']
Who is assigned to projects in the [deployment] stage?	'Isaiah', 'Casey', 'Vivienne', 'Marisela', 'Willis', 'Yoshiko'	['question_type_global', 'question_two_hop_statement']
Who are the testers currently working on the [early stage] projects?	'Isaiah', 'Casey', 'Willis'	['question_type_global', 'question_three_hop_statement']
Are there any issues that are resolved?	'two consecutive dates identified as single date', 'xml extractor exception', 'wrong pos tag on consecutive words', 'svd is slow'	['question_type_global', 'question_single_statement']
Are there projects in the [testing] stage?	'mobile', 'knowledge base'	['question_type_global', 'question_single_statement']
Are there any [bug]s that are not resolved?	'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
Are there any projects that are [external]?	'knowledge base'	['question_type_global', 'question_single_statement']
Are there any developers assigned to the [early stage] projects?	'Vivienne', 'Marisela', 'Yoshiko'	['question_type_global', 'question_three_hop_statement']
Who is working on [mobile project]?	'Casey', 'Vivienne', 'Marisela', 'Willis', 'Yoshiko'	['question_type_local']
Are there any testers assigned to the [external] projects?	'Casey'	['question_type_global', 'question_three_hop_statement']
What are the issues that are resolved for projects in the [testing] stage?	'xml extractor exception', 'wrong pos tag on consecutive words'	['question_type_global', 'question_three_hop_statement']
Who is currently working on the [external] projects?	'Casey', 'Vivienne', 'Marisela', 'Yoshiko'	['question_type_global', 'question_two_hop_statement']
[Isaiah] is working on [knowledge base project] also
[Isaiah] is assigned to [mobile project] also
What are the issues created by [Vivienne] that were resolved?	'wrong pos tag on consecutive words', 'svd is slow'	['question_type_local']
Are there any [early stage] projects?	'mobile', 'chatbot'	['question_type_global', 'question_single_statement']
Which testers have issues assigned to them that were all resolved?	'Casey', 'Willis'	['question_type_global', 'question_three_hop_statement']
Are there any people assigned to the [early stage] projects?	'Isaiah', 'Casey', 'Vivienne', 'Marisela', 'Willis', 'Yoshiko'	['question_type_global', 'question_two_hop_statement']
[Casey] is no longer assigned to [chatbot project]
Who submitted [the svd is slow issue]?	'Vivienne'	['question_type_local']
Are there any issues that are resolved?	'two consecutive dates identified as single date', 'xml extractor exception', 'wrong pos tag on consecutive words', 'svd is slow'	['question_type_global', 'question_single_statement']
[that test engineer] is assigned to [that project] also
What are the issues that are resolved for projects in the [deployment] stage?	'two consecutive dates identified as single date', 'svd is slow'	['question_type_global', 'question_three_hop_statement']
What are the resolved issues for [external] projects?	'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
Who are the testers on [knowledge base project]	'Isaiah', 'Casey'	['question_type_local']
Who has issues assigned to them that were all resolved?	'Casey', 'Vivienne', 'Willis'	['question_type_global', 'question_two_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Vivienne'	['question_type_global', 'question_three_hop_statement']
[Yoshiko] created a new [bug] for [knowledge base project]: [fails with apache stack]
[this issue] is assigned to [Casey]
Who submitted [the xml extractor exception issue]?	'Casey'	['question_type_local']
Who are the testers currently working on projects in the [testing] stage?	'Isaiah', 'Casey', 'Willis'	['question_type_global', 'question_three_hop_statement']
Who has issues assigned to them that were not resolved?	'Casey'	['question_type_global', 'question_two_hop_statement']
[this tester] resolved [it]
[this test engineer] is no longer assigned to [mobile project]
[that test engineer] is working on [mobile project] also
[parse example terribly slow] is a new issue for the [knowledge base project]
[that issue] was assigned to [Marisela]
[she] resolved [the issue]
who are the developers?	'Vivienne', 'Bob', 'Marisela', 'Yoshiko'	['question_type_global', 'question_single_statement']
Are there any developers assigned to projects in the [testing] stage?	'Vivienne', 'Marisela', 'Yoshiko'	['question_type_global', 'question_three_hop_statement']
Are there any testers assigned to projects in the [deployment] stage?	'Isaiah', 'Casey', 'Willis'	['question_type_global', 'question_three_hop_statement']
Are there any testers assigned to the [external] projects?	'Isaiah', 'Casey'	['question_type_global', 'question_three_hop_statement']
What testers are assigned to projects in the [deployment] stage?	'Isaiah', 'Casey', 'Willis'	['question_type_global', 'question_three_hop_statement']
Who created [the task]?	'Vivienne'	['question_type_local']
What are the resolved issues?	'two consecutive dates identified as single date', 'xml extractor exception', 'wrong pos tag on consecutive words', 'svd is slow', 'fails with apache stack', 'parse example terribly slow'	['question_type_global', 'question_single_statement']
[that developer] is no longer assigned to [mobile project]
[this developer] is assigned to [it] also
[Willis] created a new issue for [mobile project]: [initialization broken]
[that issue] was assigned to [Willis]
[that test engineer] resolved [it]
[Willis] is assigned to [knowledge base project] also
What are the resolved issues for [chatbot project]?	'two consecutive dates identified as single date', 'svd is slow'	['question_type_global', 'question_two_hop_statement']
Who created [the two consecutive dates identified as single date issue]?	'Casey'	['question_type_local']
who are the developers?	'Vivienne', 'Bob', 'Marisela', 'Yoshiko'	['question_type_global', 'question_single_statement']
Are there any issues that are resolved?	'two consecutive dates identified as single date', 'xml extractor exception', 'wrong pos tag on consecutive words', 'svd is slow', 'fails with apache stack', 'parse example terribly slow', 'initialization broken'	['question_type_global', 'question_single_statement']
[Isaiah] created a new [proposal] for [knowledge base project]: [memory leak while reading tf records]
Who was [the parse example terribly slow issue] assigned to?	'Marisela'	['question_type_local']
What projects are currently in the [deployment] stage?	'chatbot'	['question_type_global', 'question_single_statement']
Who are the testers currently working on projects in the [testing] stage?	'Isaiah', 'Casey', 'Willis'	['question_type_global', 'question_three_hop_statement']
What testers are assigned to the [early stage] projects?	'Isaiah', 'Casey', 'Willis'	['question_type_global', 'question_three_hop_statement']
What are the non resolved [proposal]s?	'memory leak while reading tf records'	['question_type_global', 'question_two_hop_statement']
What are the resolved issues for [that project]?	'xml extractor exception', 'fails with apache stack', 'parse example terribly slow'	['question_type_global', 'question_two_hop_statement']
[chatbot project] has moved to the [testing] stage
[the memory leak while reading tf records issue] was assigned to [Isaiah]
Who submitted [the initialization broken issue]?	'Willis'	['question_type_local']
Who are the developers currently working on the [external] projects?	'Vivienne', 'Marisela', 'Yoshiko'	['question_type_global', 'question_three_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Vivienne', 'Marisela'	['question_type_global', 'question_three_hop_statement']
What are the non resolved issues?	'memory leak while reading tf records'	['question_type_global', 'question_single_statement']
What are the non resolved issues for [external] projects?	'memory leak while reading tf records'	['question_type_global', 'question_two_hop_statement']
[he] resolved [the memory leak while reading tf records issue]
[Vivienne] submitted a new [bug] for [chatbot project]: [parsing with parantheses fails]
[the issue] is assigned to [he]
Are there any issues created by [Vivienne] that are resolved?	'wrong pos tag on consecutive words', 'svd is slow'	['question_type_local']
who are the testers?	'Isaiah', 'Casey', 'Willis', 'Emma'	['question_type_global', 'question_single_statement']
Who has issues assigned to them that were not resolved?	'Isaiah'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are resolved?	'two consecutive dates identified as single date', 'xml extractor exception', 'wrong pos tag on consecutive words', 'svd is slow', 'fails with apache stack', 'parse example terribly slow', 'initialization broken', 'memory leak while reading tf records'	['question_type_global', 'question_single_statement']
Which developers have issues assigned to them that were all resolved?	'Vivienne', 'Marisela'	['question_type_global', 'question_three_hop_statement']
[that test engineer] resolved [that issue]
[knowledge base project] is not assigned to [that test engineer]
Are there any projects that are [external]?	'knowledge base'	['question_type_global', 'question_single_statement']
What are the resolved issues for [early stage] projects?	'two consecutive dates identified as single date', 'wrong pos tag on consecutive words', 'svd is slow', 'initialization broken', 'parsing with parantheses fails'	['question_type_global', 'question_two_hop_statement']
[Isaiah] is working on [knowledge base project] also
Are there any people assigned to the [external] projects?	'Isaiah', 'Casey', 'Vivienne', 'Marisela', 'Willis', 'Yoshiko'	['question_type_global', 'question_two_hop_statement']
Who are the testers currently working on the [external] projects?	'Isaiah', 'Casey', 'Willis'	['question_type_global', 'question_three_hop_statement']
What are the issues assigned to [that person]?	'memory leak while reading tf records', 'parsing with parantheses fails'	['question_type_local']
Are there any [proposal]s that are not resolved?	'memory leak while reading tf records'	['question_type_global', 'question_two_hop_statement']
Who is currently working on the [external] projects?	'Isaiah', 'Casey', 'Vivienne', 'Marisela', 'Willis', 'Yoshiko'	['question_type_global', 'question_two_hop_statement']
What are the resolved issues for [early stage] projects?	'two consecutive dates identified as single date', 'wrong pos tag on consecutive words', 'svd is slow', 'initialization broken', 'parsing with parantheses fails'	['question_type_global', 'question_two_hop_statement']
What are the issues created by [Yoshiko]?	'fails with apache stack'	['question_type_local']
Who are the developers currently working on projects in the [testing] stage?	'Vivienne', 'Marisela', 'Yoshiko'	['question_type_global', 'question_three_hop_statement']
What projects are currently in the [testing] stage?	'mobile', 'chatbot', 'knowledge base'	['question_type_global', 'question_single_statement']
What projects are in the [testing] stage?	'mobile', 'chatbot', 'knowledge base'	['question_type_global', 'question_single_statement']
What developers are assigned to projects in the [testing] stage?	'Vivienne', 'Marisela', 'Yoshiko'	['question_type_global', 'question_three_hop_statement']
[this project] is not assigned to [Casey]
Who is [the two consecutive dates identified as single date issue] assigned to?	'Vivienne'	['question_type_local']
Are there any projects that are [early stage]?	'mobile', 'chatbot'	['question_type_global', 'question_single_statement']
who are the developers?	'Vivienne', 'Bob', 'Marisela', 'Yoshiko'	['question_type_global', 'question_single_statement']
[that person] is working on [this project] also
Who submitted [the task]?	'Vivienne'	['question_type_local']
What are the resolved issues for projects in the [testing] stage?	'two consecutive dates identified as single date', 'xml extractor exception', 'wrong pos tag on consecutive words', 'svd is slow', 'fails with apache stack', 'parse example terribly slow', 'initialization broken', 'memory leak while reading tf records', 'parsing with parantheses fails'	['question_type_global', 'question_three_hop_statement']
Who are the developers currently working on projects in the [testing] stage?	'Vivienne', 'Marisela', 'Yoshiko'	['question_type_global', 'question_three_hop_statement']
Who are the testers currently working on projects in the [testing] stage?	'Isaiah', 'Casey', 'Willis'	['question_type_global', 'question_three_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Vivienne', 'Marisela'	['question_type_global', 'question_three_hop_statement']
[mobile project] is not assigned to [Casey]
[this person] is working on [it] also
What projects is [Willis] working on?	'mobile', 'chatbot', 'knowledge base'	['question_type_local']
Which testers have issues assigned to them that were all resolved?	'Isaiah', 'Casey', 'Willis'	['question_type_global', 'question_three_hop_statement']
Who are the developers currently working on the [early stage] projects?	'Vivienne', 'Marisela', 'Yoshiko'	['question_type_global', 'question_three_hop_statement']
Who is currently working on the [external] projects?	'Isaiah', 'Casey', 'Vivienne', 'Marisela', 'Willis', 'Yoshiko'	['question_type_global', 'question_two_hop_statement']
who are the developers?	'Vivienne', 'Bob', 'Marisela', 'Yoshiko'	['question_type_global', 'question_single_statement']
Are there any testers assigned to projects in the [testing] stage?	'Isaiah', 'Casey', 'Willis'	['question_type_global', 'question_three_hop_statement']
Who are the developers currently working on the [external] projects?	'Vivienne', 'Marisela', 'Yoshiko'	['question_type_global', 'question_three_hop_statement']
What are the resolved issues for [early stage] projects?	'two consecutive dates identified as single date', 'wrong pos tag on consecutive words', 'svd is slow', 'initialization broken', 'parsing with parantheses fails'	['question_type_global', 'question_two_hop_statement']
Which testers have issues assigned to them that were all resolved?	'Isaiah', 'Casey', 'Willis'	['question_type_global', 'question_three_hop_statement']
What are the issues that are resolved for [early stage] projects?	'two consecutive dates identified as single date', 'wrong pos tag on consecutive words', 'svd is slow', 'initialization broken', 'parsing with parantheses fails'	['question_type_global', 'question_two_hop_statement']
What projects is [Willis] working on?	'mobile', 'chatbot', 'knowledge base'	['question_type_local']
Are there any projects that are [early stage]?	'mobile', 'chatbot'	['question_type_global', 'question_single_statement']
Are there any developers assigned to projects in the [testing] stage?	'Vivienne', 'Marisela', 'Yoshiko'	['question_type_global', 'question_three_hop_statement']
Who are the testers on [this project]	'Isaiah', 'Casey', 'Willis'	['question_type_local']
Who are the developers currently working on projects in the [testing] stage?	'Vivienne', 'Marisela', 'Yoshiko'	['question_type_global', 'question_three_hop_statement']
who are the testers?	'Isaiah', 'Casey', 'Willis', 'Emma'	['question_type_global', 'question_single_statement']
[this tester] is not working on [knowledge base project] anymore
[that project] is now in the [development] stage
[mobile project] is now in the [development] stage
[knowledge base project] is in the stage of [testing]
Who submitted [the wrong pos tag on consecutive words issue]?	'Vivienne'	['question_type_local']
Are there any issues for [mobile project] that are resolved?	'wrong pos tag on consecutive words', 'initialization broken'	['question_type_global', 'question_two_hop_statement']
Are there any people assigned to projects in the [testing] stage?	'Isaiah', 'Casey', 'Vivienne', 'Marisela', 'Willis', 'Yoshiko'	['question_type_global', 'question_two_hop_statement']
[Casey] is assigned to [knowledge base project] also
[mobile project] has moved to the [deployment] stage
Who is [the svd is slow issue] assigned to?	'Willis'	['question_type_local']
Who is working on [knowledge base project]?	'Isaiah', 'Casey', 'Vivienne', 'Marisela', 'Willis', 'Yoshiko'	['question_type_local']
Are there any issues that are resolved for [early stage] projects?	'two consecutive dates identified as single date', 'wrong pos tag on consecutive words', 'svd is slow', 'initialization broken', 'parsing with parantheses fails'	['question_type_global', 'question_two_hop_statement']
Which testers have issues assigned to them that were all resolved?	'Isaiah', 'Casey', 'Willis'	['question_type_global', 'question_three_hop_statement']
Who created [the proposal]?	'Isaiah'	['question_type_local']
What developers are assigned to the [external] projects?	'Vivienne', 'Marisela', 'Yoshiko'	['question_type_global', 'question_three_hop_statement']
Who is currently working on projects in the [deployment] stage?	'Isaiah', 'Casey', 'Vivienne', 'Marisela', 'Willis', 'Yoshiko'	['question_type_global', 'question_two_hop_statement']
[mobile project] is not assigned to [Marisela]
[it] has moved to the [evaluation] stage
[chatbot project] is in the stage of [evaluation]
What projects is [Casey] working on?	'mobile', 'chatbot', 'knowledge base'	['question_type_local']
Who is working on [chatbot project]?	'Isaiah', 'Casey', 'Vivienne', 'Marisela', 'Willis', 'Yoshiko'	['question_type_local']
Are there projects in the [evaluation] stage?	'mobile', 'chatbot'	['question_type_global', 'question_single_statement']
Are there any developers assigned to the [external] projects?	'Vivienne', 'Marisela', 'Yoshiko'	['question_type_global', 'question_three_hop_statement']
What are the resolved issues for [chatbot project]?	'two consecutive dates identified as single date', 'svd is slow', 'parsing with parantheses fails'	['question_type_global', 'question_two_hop_statement']
[Casey] is not working on [chatbot project] anymore
[it] is assigned to [this test engineer] also
[that test engineer] is not working on [knowledge base project] anymore
[that test engineer] is assigned to [it] also
What are the issues created by [Vivienne] that were resolved?	'wrong pos tag on consecutive words', 'svd is slow', 'parsing with parantheses fails'	['question_type_local']
[Marisela] is working on [mobile project] also
[she] is no longer assigned to [chatbot project]
[that project] is assigned to [this developer] also
Which testers have issues assigned to them that were all resolved?	'Isaiah', 'Casey', 'Willis'	['question_type_global', 'question_three_hop_statement']
What projects is [Isaiah] working on?	'mobile', 'chatbot', 'knowledge base'	['question_type_local']
Were there any issues assigned to [Vivienne]?	'two consecutive dates identified as single date'	['question_type_local']
Are there any issues that are resolved?	'two consecutive dates identified as single date', 'xml extractor exception', 'wrong pos tag on consecutive words', 'svd is slow', 'fails with apache stack', 'parse example terribly slow', 'initialization broken', 'memory leak while reading tf records', 'parsing with parantheses fails'	['question_type_global', 'question_single_statement']
[that project] is now in the [testing] stage
[that project] is assigned to [Bob]
What projects are in the [evaluation] stage?	'mobile'	['question_type_global', 'question_single_statement']
[mobile project] is assigned to [that developer] also
Which developers have issues assigned to them that were all resolved?	'Vivienne', 'Marisela'	['question_type_global', 'question_three_hop_statement']
What are the resolved issues?	'two consecutive dates identified as single date', 'xml extractor exception', 'wrong pos tag on consecutive words', 'svd is slow', 'fails with apache stack', 'parse example terribly slow', 'initialization broken', 'memory leak while reading tf records', 'parsing with parantheses fails'	['question_type_global', 'question_single_statement']
[that developer] is assigned to [knowledge base project] also
Who submitted [the svd is slow task]?	'Vivienne'	['question_type_local']
What projects are [external]?	'knowledge base'	['question_type_global', 'question_single_statement']
What are the issues that are resolved for [external] projects?	'xml extractor exception', 'fails with apache stack', 'parse example terribly slow', 'memory leak while reading tf records'	['question_type_global', 'question_two_hop_statement']
Who has issues assigned to them that were all resolved?	'Isaiah', 'Casey', 'Vivienne', 'Marisela', 'Willis'	['question_type_global', 'question_two_hop_statement']
[Casey] is not working on [knowledge base project] anymore
[Casey] is working on [it] also
[knowledge base project] is not assigned to [Isaiah]
[this test engineer] is no longer assigned to [mobile project]
[he] is assigned to [that project] also
