there is a new [important] [chatbot] [project]
[that project] is currently in the [evaluation] stage
[parse example terribly slow] is a new [bug] for the [this project]
[Lucy] is a [tester]
[chatbot project] is assigned to [Lucy]
[the parse example terribly slow bug] is assigned to [Lucy]
[that person] resolved [the parse example terribly slow issue]
[this tester] created a new issue for [chatbot project]: [saving data throws exception]
[this issue] was assigned to [that person]
[Lucy] created a new issue for [chatbot project]: [wrong pos tag on consecutive words]
[Zenaida] is a [developer] on [chatbot project]
[it] was assigned to [this developer]
[Zenaida] resolved [the wrong pos tag on consecutive words issue]
[this developer] is not working on [chatbot project] anymore
Who submitted [the saving data throws exception issue]?	'Lucy'	['question_type_local']
Who is assigned to the [important] projects?	'Lucy'	['question_type_global', 'question_two_hop_statement']
[Zenaida] is assigned to [chatbot project]
[Lucy] resolved [the saving data throws exception issue]
What projects is [Zenaida] working on?	'chatbot'	['question_type_local']
[minified version fails] is a new issue for the [chatbot project]
[chatbot project] is not assigned to [this test engineer]
[Zenaida] submitted a new [proposal] for [that project]: [svd is slow]
[this project] is assigned to [Lucy]
[Zenaida] created a new issue for [it]: [versioning needs to be made consistent]
[this issue] is assigned to [Lucy]
[Lucy] resolved [the versioning needs to be made consistent issue]
who are the testers?	'Lucy'	['question_type_global', 'question_single_statement']
Which testers have issues assigned to them that were all resolved?	'Lucy'	['question_type_global', 'question_three_hop_statement']
Are there any [important] projects?	'chatbot'	['question_type_global', 'question_single_statement']
What are the issues for [chatbot project] that are not resolved?	'minified version fails', 'svd is slow'	['question_type_global', 'question_two_hop_statement']
[two consecutive dates identified as single date] is a new [enhancement] created by [Zenaida] for [chatbot project]
[this test engineer] created a new issue for [chatbot project]: [memory leak while reading tf records]
[the enhancement] is assigned to [Zenaida]
[Bob] is a [tester]
[chatbot project] is assigned to [this test engineer]
What developers are assigned to the [important] projects?	'Zenaida'	['question_type_global', 'question_three_hop_statement']
What are the resolved issues for [important] projects?	'parse example terribly slow', 'saving data throws exception', 'wrong pos tag on consecutive words', 'versioning needs to be made consistent'	['question_type_global', 'question_two_hop_statement']
Which developers are assigned to [that project]	'Zenaida'	['question_type_local']
Are there any issues that are resolved for projects in the [evaluation] stage?	'parse example terribly slow', 'saving data throws exception', 'wrong pos tag on consecutive words', 'versioning needs to be made consistent'	['question_type_global', 'question_three_hop_statement']
Are there any issues that are not resolved for projects in the [evaluation] stage?	'minified version fails', 'svd is slow', 'two consecutive dates identified as single date', 'memory leak while reading tf records'	['question_type_global', 'question_three_hop_statement']
Who are the developers currently working on the [important] projects?	'Zenaida'	['question_type_global', 'question_three_hop_statement']
What are the issues that are not resolved?	'minified version fails', 'svd is slow', 'two consecutive dates identified as single date', 'memory leak while reading tf records'	['question_type_global', 'question_single_statement']
What are the issues submitted by [Zenaida] that were resolved?	'versioning needs to be made consistent'	['question_type_local']
Are there any [important] projects?	'chatbot'	['question_type_global', 'question_single_statement']
Who are the testers currently working on projects in the [evaluation] stage?	'Lucy', 'Bob'	['question_type_global', 'question_three_hop_statement']
What are the [important] projects?	'chatbot'	['question_type_global', 'question_single_statement']
Who has issues assigned to them that were all resolved?	'Lucy', 'Zenaida'	['question_type_global', 'question_two_hop_statement']
There is a new [proposal] for the [that project]: [issue in using training data]
[the minified version fails issue] is assigned to [Lucy]
Who is [the two consecutive dates identified as single date enhancement] assigned to?	'Zenaida'	['question_type_local']
[that person] resolved [the minified version fails issue]
there is a new [internal] [mobile] [project]
[that project] is in the stage of [evaluation]
[Milagros] is a [developer]
[Milagros] is assigned to [chatbot project]
[she] is assigned to [mobile project] also
[Zenaida] is working on [mobile project] also
Who submitted [the versioning needs to be made consistent issue]?	'Zenaida'	['question_type_local']
What are the non resolved issues?	'svd is slow', 'two consecutive dates identified as single date', 'memory leak while reading tf records', 'issue in using training data'	['question_type_global', 'question_single_statement']
What are the issues that are not resolved for [important] projects?	'svd is slow', 'two consecutive dates identified as single date', 'memory leak while reading tf records', 'issue in using training data'	['question_type_global', 'question_two_hop_statement']
What projects are currently in the [evaluation] stage?	'chatbot', 'mobile'	['question_type_global', 'question_single_statement']
Which developers have issues assigned to them that were not resolved?	'Zenaida'	['question_type_global', 'question_three_hop_statement']
Are there any testers assigned to projects in the [evaluation] stage?	'Lucy', 'Bob'	['question_type_global', 'question_three_hop_statement']
Who is currently working on projects in the [evaluation] stage?	'Lucy', 'Zenaida', 'Bob', 'Milagros'	['question_type_global', 'question_two_hop_statement']
Which testers have issues assigned to them that were all resolved?	'Lucy'	['question_type_global', 'question_three_hop_statement']
who are the developers?	'Zenaida', 'Milagros'	['question_type_global', 'question_single_statement']
What projects is [Lucy] working on?	'chatbot'	['question_type_local']
What developers are assigned to projects in the [evaluation] stage?	'Zenaida', 'Milagros'	['question_type_global', 'question_three_hop_statement']
Are there any [enhancement]s that are not resolved?	'two consecutive dates identified as single date'	['question_type_global', 'question_two_hop_statement']
Who is working on [chatbot project]?	'Lucy', 'Zenaida', 'Bob', 'Milagros'	['question_type_local']
[Alverta] is a [tester]
[Alverta] is assigned to [this project]
Are there any [internal] projects?	'mobile'	['question_type_global', 'question_single_statement']
What projects are in the [evaluation] stage?	'chatbot', 'mobile'	['question_type_global', 'question_single_statement']
What are the resolved issues for projects in the [evaluation] stage?	'parse example terribly slow', 'saving data throws exception', 'wrong pos tag on consecutive words', 'minified version fails', 'versioning needs to be made consistent'	['question_type_global', 'question_three_hop_statement']
What are the issues that are resolved for projects in the [evaluation] stage?	'parse example terribly slow', 'saving data throws exception', 'wrong pos tag on consecutive words', 'minified version fails', 'versioning needs to be made consistent'	['question_type_global', 'question_three_hop_statement']
Are there any issues that are resolved?	'parse example terribly slow', 'saving data throws exception', 'wrong pos tag on consecutive words', 'minified version fails', 'versioning needs to be made consistent'	['question_type_global', 'question_single_statement']
Which developers have issues assigned to them that were all resolved?	'Zenaida'	['question_type_global', 'question_three_hop_statement']
Which developers have issues assigned to them that were not resolved?	'Zenaida'	['question_type_global', 'question_three_hop_statement']
who are the developers?	'Zenaida', 'Milagros'	['question_type_global', 'question_single_statement']
What are the issues assigned to [Zenaida] that were resolved?	'wrong pos tag on consecutive words'	['question_type_local']
Which testers have issues assigned to them that were all resolved?	'Lucy'	['question_type_global', 'question_three_hop_statement']
Who are the developers currently working on projects in the [evaluation] stage?	'Zenaida', 'Milagros'	['question_type_global', 'question_three_hop_statement']
What are the [proposal]s that are not resolved?	'svd is slow', 'issue in using training data'	['question_type_global', 'question_two_hop_statement']
[Bob] is assigned to [that project] also
What projects is [Milagros] working on?	'chatbot', 'mobile'	['question_type_local']
Are there any issues that are resolved for projects in the [evaluation] stage?	'parse example terribly slow', 'saving data throws exception', 'wrong pos tag on consecutive words', 'minified version fails', 'versioning needs to be made consistent'	['question_type_global', 'question_three_hop_statement']
Who has issues assigned to them that were not resolved?	'Zenaida'	['question_type_global', 'question_two_hop_statement']
Who are the testers currently working on projects in the [evaluation] stage?	'Lucy', 'Bob', 'Alverta'	['question_type_global', 'question_three_hop_statement']
Are there any issues assigned to [Zenaida] that are resolved?	'wrong pos tag on consecutive words'	['question_type_local']
Are there any testers assigned to projects in the [evaluation] stage?	'Lucy', 'Bob', 'Alverta'	['question_type_global', 'question_three_hop_statement']
Who is assigned to the [internal] projects?	'Zenaida', 'Bob', 'Milagros', 'Alverta'	['question_type_global', 'question_two_hop_statement']
who are the testers?	'Lucy', 'Bob', 'Alverta'	['question_type_global', 'question_single_statement']
there is a new [knowledge base] [project]
[knowledge base project] is a [internal] project
[Tom] is a [tester]
[this project] is currently in the [development] stage
[mobile project] is assigned to [Tom]
[this test engineer] is assigned to [knowledge base project] also
[that person] is assigned to [chatbot project] also
What are the issues for [it] that are not resolved?	'svd is slow', 'two consecutive dates identified as single date', 'memory leak while reading tf records', 'issue in using training data'	['question_type_global', 'question_two_hop_statement']
[it] is not assigned to [that test engineer]
[this tester] is assigned to [chatbot project] also
[this project] is now in the [design] stage
Which testers are working on [mobile project]?	'Bob', 'Alverta', 'Tom'	['question_type_local']
What are the issues that were resolved?	'parse example terribly slow', 'saving data throws exception', 'wrong pos tag on consecutive words', 'minified version fails', 'versioning needs to be made consistent'	['question_type_global', 'question_single_statement']
Which developers have issues assigned to them that were all resolved?	'Zenaida'	['question_type_global', 'question_three_hop_statement']
Who submitted [the memory leak while reading tf records issue]?	'Lucy'	['question_type_local']
Are there any developers assigned to the [important] projects?	'Zenaida', 'Milagros'	['question_type_global', 'question_three_hop_statement']
What are the non resolved [proposal]s?	'svd is slow', 'issue in using training data'	['question_type_global', 'question_two_hop_statement']
Are there projects in the [development] stage?	'knowledge base'	['question_type_global', 'question_single_statement']
[Michael] is a [developer] on [knowledge base project]
[mobile project] is assigned to [Michael] also
Who is currently working on projects in the [development] stage?	'Tom', 'Michael'	['question_type_global', 'question_two_hop_statement']
[that project] is in the stage of [development]
[Zenaida] resolved [the two consecutive dates identified as single date enhancement]
[that person] is assigned to [knowledge base project] also
What developers are assigned to the [internal] projects?	'Zenaida', 'Milagros', 'Michael'	['question_type_global', 'question_three_hop_statement']
Are there any developers assigned to the [internal] projects?	'Zenaida', 'Milagros', 'Michael'	['question_type_global', 'question_three_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Zenaida'	['question_type_global', 'question_three_hop_statement']
Who was [the parse example terribly slow issue] assigned to?	'Lucy'	['question_type_local']
who are the testers?	'Lucy', 'Bob', 'Alverta', 'Tom'	['question_type_global', 'question_single_statement']
Which testers have issues assigned to them that were all resolved?	'Lucy'	['question_type_global', 'question_three_hop_statement']
Are there any issues submitted by [Lucy] that are not resolved?	'memory leak while reading tf records'	['question_type_local']
[chatbot project] is assigned to [Michael] also
[chatbot project] is in the stage of [development]
[Tom] is no longer assigned to [knowledge base project]
Are there any people assigned to projects in the [development] stage?	'Lucy', 'Zenaida', 'Bob', 'Milagros', 'Alverta', 'Tom', 'Michael'	['question_type_global', 'question_two_hop_statement']
What are the non resolved issues?	'svd is slow', 'memory leak while reading tf records', 'issue in using training data'	['question_type_global', 'question_single_statement']
[that person] is working on [knowledge base project] also
Who is [the minified version fails issue] assigned to?	'Lucy'	['question_type_local']
What are the non resolved issues for projects in the [development] stage?	'svd is slow', 'memory leak while reading tf records', 'issue in using training data'	['question_type_global', 'question_three_hop_statement']
Who are the testers currently working on projects in the [development] stage?	'Lucy', 'Bob', 'Alverta', 'Tom'	['question_type_global', 'question_three_hop_statement']
Are there projects in the [development] stage?	'chatbot', 'mobile', 'knowledge base'	['question_type_global', 'question_single_statement']
What developers are assigned to projects in the [development] stage?	'Zenaida', 'Milagros', 'Michael'	['question_type_global', 'question_three_hop_statement']
What are the issues that are not resolved?	'svd is slow', 'memory leak while reading tf records', 'issue in using training data'	['question_type_global', 'question_single_statement']
Which testers have issues assigned to them that were all resolved?	'Lucy'	['question_type_global', 'question_three_hop_statement']
What are the issues submitted by [Lucy] that were not resolved?	'memory leak while reading tf records'	['question_type_local']
Which developers have issues assigned to them that were all resolved?	'Zenaida'	['question_type_global', 'question_three_hop_statement']
[knowledge base project] is in the [design] stage
[knowledge base project] is assigned to [Lucy] also
Which developers are assigned to [chatbot project]	'Zenaida', 'Milagros', 'Michael'	['question_type_local']
Are there projects in the [design] stage?	'knowledge base'	['question_type_global', 'question_single_statement']
[Lucy] is assigned to [mobile project] also
Are there any issues submitted by [that test engineer] that are resolved?	'saving data throws exception', 'wrong pos tag on consecutive words'	['question_type_local']
What testers are assigned to the [internal] projects?	'Lucy', 'Bob', 'Alverta', 'Tom'	['question_type_global', 'question_three_hop_statement']
Who is assigned to projects in the [design] stage?	'Lucy', 'Zenaida', 'Tom', 'Michael'	['question_type_global', 'question_two_hop_statement']
What developers are assigned to projects in the [design] stage?	'Zenaida', 'Michael'	['question_type_global', 'question_three_hop_statement']
Were there any issues created by [Zenaida]?	'svd is slow', 'versioning needs to be made consistent', 'two consecutive dates identified as single date'	['question_type_local']
Are there any testers assigned to the [important] projects?	'Lucy', 'Bob', 'Tom'	['question_type_global', 'question_three_hop_statement']
Who was [the bug] assigned to?	'Lucy'	['question_type_local']
What developers are assigned to projects in the [development] stage?	'Zenaida', 'Milagros', 'Michael'	['question_type_global', 'question_three_hop_statement']
What are the non resolved issues for [important] projects?	'svd is slow', 'memory leak while reading tf records', 'issue in using training data'	['question_type_global', 'question_two_hop_statement']
Who are the developers currently working on the [internal] projects?	'Zenaida', 'Milagros', 'Michael'	['question_type_global', 'question_three_hop_statement']
Are there projects in the [development] stage?	'chatbot', 'mobile'	['question_type_global', 'question_single_statement']
[this project] has moved to the [design] stage
[the memory leak while reading tf records issue] was assigned to [Zenaida]
[Zenaida] resolved [it]
Which is the stage of [mobile project]?	'design'	['question_type_local']
Which developers have issues assigned to them that were all resolved?	'Zenaida'	['question_type_global', 'question_three_hop_statement']
Who are the developers currently working on the [important] projects?	'Zenaida', 'Milagros', 'Michael'	['question_type_global', 'question_three_hop_statement']
Who has issues assigned to them that were all resolved?	'Lucy', 'Zenaida'	['question_type_global', 'question_two_hop_statement']
who are the testers?	'Lucy', 'Bob', 'Alverta', 'Tom'	['question_type_global', 'question_single_statement']
What developers are assigned to projects in the [development] stage?	'Zenaida', 'Milagros', 'Michael'	['question_type_global', 'question_three_hop_statement']
who are the developers?	'Zenaida', 'Milagros', 'Michael'	['question_type_global', 'question_single_statement']
What stage is [mobile project] in?	'design'	['question_type_local']
Which testers have issues assigned to them that were all resolved?	'Lucy'	['question_type_global', 'question_three_hop_statement']
Which developers are working on [knowledge base project]?	'Zenaida', 'Michael'	['question_type_local']
What testers are assigned to projects in the [design] stage?	'Lucy', 'Bob', 'Alverta', 'Tom'	['question_type_global', 'question_three_hop_statement']
[Zenaida] is not working on [mobile project] anymore
[she] is assigned to [mobile project] also
Who is [the enhancement] assigned to?	'Zenaida'	['question_type_local']
Are there any issues for [chatbot project] that are resolved?	'parse example terribly slow', 'saving data throws exception', 'wrong pos tag on consecutive words', 'minified version fails', 'versioning needs to be made consistent', 'two consecutive dates identified as single date', 'memory leak while reading tf records'	['question_type_global', 'question_two_hop_statement']
What are the non resolved [proposal]s?	'svd is slow', 'issue in using training data'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are not resolved for projects in the [development] stage?	'svd is slow', 'issue in using training data'	['question_type_global', 'question_three_hop_statement']
[mobile project] has moved to the [development] stage
Which testers have issues assigned to them that were all resolved?	'Lucy'	['question_type_global', 'question_three_hop_statement']
[this project] is now in the [design] stage
What are the issues that are resolved for [important] projects?	'parse example terribly slow', 'saving data throws exception', 'wrong pos tag on consecutive words', 'minified version fails', 'versioning needs to be made consistent', 'two consecutive dates identified as single date', 'memory leak while reading tf records'	['question_type_global', 'question_two_hop_statement']
Who are the developers currently working on the [internal] projects?	'Zenaida', 'Milagros', 'Michael'	['question_type_global', 'question_three_hop_statement']
What are the issues that are resolved for projects in the [development] stage?	'parse example terribly slow', 'saving data throws exception', 'wrong pos tag on consecutive words', 'minified version fails', 'versioning needs to be made consistent', 'two consecutive dates identified as single date', 'memory leak while reading tf records'	['question_type_global', 'question_three_hop_statement']
Who is assigned to projects in the [design] stage?	'Lucy', 'Zenaida', 'Bob', 'Milagros', 'Alverta', 'Tom', 'Michael'	['question_type_global', 'question_two_hop_statement']
What developers are assigned to the [important] projects?	'Zenaida', 'Milagros', 'Michael'	['question_type_global', 'question_three_hop_statement']
who are the testers?	'Lucy', 'Bob', 'Alverta', 'Tom'	['question_type_global', 'question_single_statement']
Are there any issues assigned to [Lucy] that are resolved?	'parse example terribly slow', 'saving data throws exception', 'minified version fails', 'versioning needs to be made consistent'	['question_type_local']
Who is currently working on the [important] projects?	'Lucy', 'Zenaida', 'Bob', 'Milagros', 'Tom', 'Michael'	['question_type_global', 'question_two_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Zenaida'	['question_type_global', 'question_three_hop_statement']
who are the developers?	'Zenaida', 'Milagros', 'Michael'	['question_type_global', 'question_single_statement']
What are the non resolved issues?	'svd is slow', 'issue in using training data'	['question_type_global', 'question_single_statement']
Are there any developers assigned to the [important] projects?	'Zenaida', 'Milagros', 'Michael'	['question_type_global', 'question_three_hop_statement']
What projects are in the [development] stage?	'chatbot'	['question_type_global', 'question_single_statement']
Who is assigned to the [internal] projects?	'Lucy', 'Zenaida', 'Bob', 'Milagros', 'Alverta', 'Tom', 'Michael'	['question_type_global', 'question_two_hop_statement']
Are there any people assigned to the [internal] projects?	'Lucy', 'Zenaida', 'Bob', 'Milagros', 'Alverta', 'Tom', 'Michael'	['question_type_global', 'question_two_hop_statement']
Which testers have issues assigned to them that were all resolved?	'Lucy'	['question_type_global', 'question_three_hop_statement']
Are there any issues for [chatbot project] that are not resolved?	'svd is slow', 'issue in using training data'	['question_type_global', 'question_two_hop_statement']
[knowledge base project] is assigned to [Milagros] also
What are the non resolved [enhancement]s?	'two consecutive dates identified as single date'	['question_type_global', 'question_two_hop_statement']
What testers are assigned to projects in the [development] stage?	'Lucy', 'Bob', 'Tom'	['question_type_global', 'question_three_hop_statement']
Are there any testers assigned to projects in the [design] stage?	'Lucy', 'Bob', 'Alverta', 'Tom'	['question_type_global', 'question_three_hop_statement']
Who was [the wrong pos tag on consecutive words issue] assigned to?	'Zenaida'	['question_type_local']
What are the issues for [chatbot project] that are resolved?	'parse example terribly slow', 'saving data throws exception', 'wrong pos tag on consecutive words', 'minified version fails', 'versioning needs to be made consistent', 'two consecutive dates identified as single date', 'memory leak while reading tf records'	['question_type_global', 'question_two_hop_statement']
What are the non resolved issues for projects in the [development] stage?	'svd is slow', 'issue in using training data'	['question_type_global', 'question_three_hop_statement']
Are there any developers assigned to the [internal] projects?	'Zenaida', 'Milagros', 'Michael'	['question_type_global', 'question_three_hop_statement']
Who is [the parse example terribly slow bug] assigned to?	'Lucy'	['question_type_local']
Which testers have issues assigned to them that were all resolved?	'Lucy'	['question_type_global', 'question_three_hop_statement']
Who has issues assigned to them that were all resolved?	'Lucy', 'Zenaida'	['question_type_global', 'question_two_hop_statement']
What projects are currently in the [development] stage?	'chatbot'	['question_type_global', 'question_single_statement']
[the svd is slow issue] was assigned to [Milagros]
[that person] resolved [the svd is slow issue]
What are the issues assigned to [Lucy] that were resolved?	'parse example terribly slow', 'saving data throws exception', 'minified version fails', 'versioning needs to be made consistent'	['question_type_local']
What are the issues that were resolved?	'parse example terribly slow', 'saving data throws exception', 'wrong pos tag on consecutive words', 'minified version fails', 'svd is slow', 'versioning needs to be made consistent', 'two consecutive dates identified as single date', 'memory leak while reading tf records'	['question_type_global', 'question_single_statement']
Which developers have issues assigned to them that were all resolved?	'Zenaida', 'Milagros'	['question_type_global', 'question_three_hop_statement']
Who are the testers currently working on projects in the [development] stage?	'Lucy', 'Bob', 'Tom'	['question_type_global', 'question_three_hop_statement']
Who is working on [chatbot project]?	'Lucy', 'Zenaida', 'Bob', 'Milagros', 'Tom', 'Michael'	['question_type_local']
Which testers have issues assigned to them that were all resolved?	'Lucy'	['question_type_global', 'question_three_hop_statement']
Who is working on [knowledge base project]?	'Lucy', 'Zenaida', 'Milagros', 'Tom', 'Michael'	['question_type_local']
Who has issues assigned to them that were all resolved?	'Lucy', 'Zenaida', 'Milagros'	['question_type_global', 'question_two_hop_statement']
What are the [enhancement]s that are not resolved?	'two consecutive dates identified as single date'	['question_type_global', 'question_two_hop_statement']
What are the resolved issues?	'parse example terribly slow', 'saving data throws exception', 'wrong pos tag on consecutive words', 'minified version fails', 'svd is slow', 'versioning needs to be made consistent', 'two consecutive dates identified as single date', 'memory leak while reading tf records'	['question_type_global', 'question_single_statement']
Who created [the versioning needs to be made consistent issue]?	'Zenaida'	['question_type_local']
What are the non resolved issues for projects in the [development] stage?	'issue in using training data'	['question_type_global', 'question_three_hop_statement']
Who created [the saving data throws exception issue]?	'Lucy'	['question_type_local']
Who are the testers currently working on projects in the [development] stage?	'Lucy', 'Bob', 'Tom'	['question_type_global', 'question_three_hop_statement']
Were there any issues assigned to [Lucy]?	'parse example terribly slow', 'saving data throws exception', 'minified version fails', 'versioning needs to be made consistent'	['question_type_local']
Are there any developers assigned to projects in the [development] stage?	'Zenaida', 'Milagros', 'Michael'	['question_type_global', 'question_three_hop_statement']
Who submitted [the wrong pos tag on consecutive words issue]?	'Lucy'	['question_type_local']
[Alverta] is working on [chatbot project] also
Are there any [internal] projects?	'mobile', 'knowledge base'	['question_type_global', 'question_single_statement']
[this test engineer] is assigned to [knowledge base project] also
Who was [the minified version fails issue] assigned to?	'Lucy'	['question_type_local']
Which testers have issues assigned to them that were all resolved?	'Lucy'	['question_type_global', 'question_three_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Zenaida', 'Milagros'	['question_type_global', 'question_three_hop_statement']
Who is [the wrong pos tag on consecutive words issue] assigned to?	'Zenaida'	['question_type_local']
What developers are assigned to projects in the [design] stage?	'Zenaida', 'Milagros', 'Michael'	['question_type_global', 'question_three_hop_statement']
Are there any developers assigned to the [internal] projects?	'Zenaida', 'Milagros', 'Michael'	['question_type_global', 'question_three_hop_statement']
What are the issues that were resolved?	'parse example terribly slow', 'saving data throws exception', 'wrong pos tag on consecutive words', 'minified version fails', 'svd is slow', 'versioning needs to be made consistent', 'two consecutive dates identified as single date', 'memory leak while reading tf records'	['question_type_global', 'question_single_statement']
Are there any people assigned to projects in the [design] stage?	'Lucy', 'Zenaida', 'Bob', 'Milagros', 'Alverta', 'Tom', 'Michael'	['question_type_global', 'question_two_hop_statement']
Who has issues assigned to them that were all resolved?	'Lucy', 'Zenaida', 'Milagros'	['question_type_global', 'question_two_hop_statement']
Which is the stage of [that project]?	'design'	['question_type_local']
[Bob] is no longer assigned to [chatbot project]
[that test engineer] is working on [knowledge base project] also
What projects are [important]?	'chatbot'	['question_type_global', 'question_single_statement']
Are there any issues that are not resolved for [important] projects?	'issue in using training data'	['question_type_global', 'question_two_hop_statement']
Are there any [bug]s that are not resolved?	'parse example terribly slow'	['question_type_global', 'question_two_hop_statement']
Are there any testers assigned to the [important] projects?	'Lucy', 'Alverta', 'Tom'	['question_type_global', 'question_three_hop_statement']
who are the developers?	'Zenaida', 'Milagros', 'Michael'	['question_type_global', 'question_single_statement']
What are the non resolved issues?	'issue in using training data'	['question_type_global', 'question_single_statement']
What developers are assigned to the [important] projects?	'Zenaida', 'Milagros', 'Michael'	['question_type_global', 'question_three_hop_statement']
Who are the developers currently working on projects in the [design] stage?	'Zenaida', 'Milagros', 'Michael'	['question_type_global', 'question_three_hop_statement']
[Michael] is not working on [mobile project] anymore
[he] is assigned to [mobile project] also
What stage is [chatbot project] in?	'development'	['question_type_local']
Are there any developers assigned to the [important] projects?	'Zenaida', 'Milagros', 'Michael'	['question_type_global', 'question_three_hop_statement']
Who is assigned to the [internal] projects?	'Lucy', 'Zenaida', 'Bob', 'Milagros', 'Alverta', 'Tom', 'Michael'	['question_type_global', 'question_two_hop_statement']
Who are the developers currently working on the [important] projects?	'Zenaida', 'Milagros', 'Michael'	['question_type_global', 'question_three_hop_statement']
[mobile project] is in the [evaluation] stage
Which developers are assigned to [knowledge base project]	'Zenaida', 'Milagros', 'Michael'	['question_type_local']
What are the issues that are resolved for [important] projects?	'parse example terribly slow', 'saving data throws exception', 'wrong pos tag on consecutive words', 'minified version fails', 'svd is slow', 'versioning needs to be made consistent', 'two consecutive dates identified as single date', 'memory leak while reading tf records'	['question_type_global', 'question_two_hop_statement']
who are the developers?	'Zenaida', 'Milagros', 'Michael'	['question_type_global', 'question_single_statement']
who are the testers?	'Lucy', 'Bob', 'Alverta', 'Tom'	['question_type_global', 'question_single_statement']
Who has issues assigned to them that were all resolved?	'Lucy', 'Zenaida', 'Milagros'	['question_type_global', 'question_two_hop_statement']
What are the issues that are not resolved?	'issue in using training data'	['question_type_global', 'question_single_statement']
Who are the testers currently working on projects in the [development] stage?	'Lucy', 'Alverta', 'Tom'	['question_type_global', 'question_three_hop_statement']
Who created [the wrong pos tag on consecutive words issue]?	'Lucy'	['question_type_local']
Are there any developers assigned to projects in the [design] stage?	'Zenaida', 'Milagros', 'Michael'	['question_type_global', 'question_three_hop_statement']
Are there any issues that are resolved for [important] projects?	'parse example terribly slow', 'saving data throws exception', 'wrong pos tag on consecutive words', 'minified version fails', 'svd is slow', 'versioning needs to be made consistent', 'two consecutive dates identified as single date', 'memory leak while reading tf records'	['question_type_global', 'question_two_hop_statement']
[chatbot project] is assigned to [Bob] also
What are the non resolved [bug]s?	'parse example terribly slow'	['question_type_global', 'question_two_hop_statement']
Are there any testers assigned to projects in the [evaluation] stage?	'Lucy', 'Bob', 'Alverta', 'Tom'	['question_type_global', 'question_three_hop_statement']
Are there any testers assigned to projects in the [development] stage?	'Lucy', 'Bob', 'Alverta', 'Tom'	['question_type_global', 'question_three_hop_statement']
Who is currently working on the [internal] projects?	'Lucy', 'Zenaida', 'Bob', 'Milagros', 'Alverta', 'Tom', 'Michael'	['question_type_global', 'question_two_hop_statement']
What are the non resolved issues for projects in the [development] stage?	'issue in using training data'	['question_type_global', 'question_three_hop_statement']
Who is currently working on the [important] projects?	'Lucy', 'Zenaida', 'Bob', 'Milagros', 'Alverta', 'Tom', 'Michael'	['question_type_global', 'question_two_hop_statement']
[Alverta] is no longer assigned to [chatbot project]
[this person] is working on [it] also
[chatbot project] is in the stage of [deployment]
[chatbot project] is now in the [evaluation] stage
[it] is in the stage of [deployment]
What are the issues that are not resolved for [important] projects?	'issue in using training data'	['question_type_global', 'question_two_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Zenaida', 'Milagros'	['question_type_global', 'question_three_hop_statement']
[it] is in the stage of [design]
Are there any [bug]s that are not resolved?	'parse example terribly slow'	['question_type_global', 'question_two_hop_statement']
Who are the developers currently working on the [important] projects?	'Zenaida', 'Milagros', 'Michael'	['question_type_global', 'question_three_hop_statement']
What projects are [important]?	'chatbot'	['question_type_global', 'question_single_statement']
Who are the testers currently working on projects in the [evaluation] stage?	'Lucy', 'Bob', 'Alverta', 'Tom'	['question_type_global', 'question_three_hop_statement']
[it] is now in the [deployment] stage
Are there any [proposal]s that are not resolved?	'issue in using training data'	['question_type_global', 'question_two_hop_statement']
Are there any people assigned to the [internal] projects?	'Lucy', 'Zenaida', 'Bob', 'Milagros', 'Alverta', 'Tom', 'Michael'	['question_type_global', 'question_two_hop_statement']
Who is currently working on projects in the [design] stage?	'Lucy', 'Zenaida', 'Bob', 'Milagros', 'Alverta', 'Tom', 'Michael'	['question_type_global', 'question_two_hop_statement']
Who has issues assigned to them that were all resolved?	'Lucy', 'Zenaida', 'Milagros'	['question_type_global', 'question_two_hop_statement']
who are the testers?	'Lucy', 'Bob', 'Alverta', 'Tom'	['question_type_global', 'question_single_statement']
Are there any issues for [this project] that are not resolved?	'issue in using training data'	['question_type_global', 'question_two_hop_statement']
Who is working on [it]?	'Lucy', 'Zenaida', 'Bob', 'Milagros', 'Alverta', 'Tom', 'Michael'	['question_type_local']
What are the issues that are not resolved for [important] projects?	'issue in using training data'	['question_type_global', 'question_two_hop_statement']
Are there any people assigned to projects in the [evaluation] stage?	'Lucy', 'Zenaida', 'Bob', 'Milagros', 'Alverta', 'Tom', 'Michael'	['question_type_global', 'question_two_hop_statement']
Who submitted [the svd is slow issue]?	'Zenaida'	['question_type_local']
Who has issues assigned to them that were all resolved?	'Lucy', 'Zenaida', 'Milagros'	['question_type_global', 'question_two_hop_statement']
Are there any people assigned to projects in the [deployment] stage?	'Lucy', 'Zenaida', 'Bob', 'Milagros', 'Alverta', 'Tom', 'Michael'	['question_type_global', 'question_two_hop_statement']
Who are the testers currently working on the [important] projects?	'Lucy', 'Bob', 'Alverta', 'Tom'	['question_type_global', 'question_three_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Zenaida', 'Milagros'	['question_type_global', 'question_three_hop_statement']
Who are the testers on [chatbot project]	'Lucy', 'Bob', 'Alverta', 'Tom'	['question_type_local']
What are the non resolved issues for [it]?	'issue in using training data'	['question_type_global', 'question_two_hop_statement']
Are there any [proposal]s that are not resolved?	'svd is slow'	['question_type_global', 'question_two_hop_statement']
Who was [the wrong pos tag on consecutive words issue] assigned to?	'Zenaida'	['question_type_local']
What are the [proposal]s that are not resolved?	'svd is slow'	['question_type_global', 'question_two_hop_statement']
Who are the developers currently working on the [internal] projects?	'Zenaida', 'Milagros', 'Michael'	['question_type_global', 'question_three_hop_statement']
who are the developers?	'Zenaida', 'Milagros', 'Michael'	['question_type_global', 'question_single_statement']
Are there any projects that are [internal]?	'mobile', 'knowledge base'	['question_type_global', 'question_single_statement']
Are there any people assigned to the [important] projects?	'Lucy', 'Zenaida', 'Bob', 'Milagros', 'Alverta', 'Tom', 'Michael'	['question_type_global', 'question_two_hop_statement']
Are there any [internal] projects?	'mobile', 'knowledge base'	['question_type_global', 'question_single_statement']
What are the resolved issues for [chatbot project]?	'parse example terribly slow', 'saving data throws exception', 'wrong pos tag on consecutive words', 'minified version fails', 'svd is slow', 'versioning needs to be made consistent', 'two consecutive dates identified as single date', 'memory leak while reading tf records'	['question_type_global', 'question_two_hop_statement']
[Lucy] is not working on [chatbot project] anymore
[this test engineer] is assigned to [this project] also
Which developers have issues assigned to them that were all resolved?	'Zenaida', 'Milagros'	['question_type_global', 'question_three_hop_statement']
What are the resolved issues for [important] projects?	'parse example terribly slow', 'saving data throws exception', 'wrong pos tag on consecutive words', 'minified version fails', 'svd is slow', 'versioning needs to be made consistent', 'two consecutive dates identified as single date', 'memory leak while reading tf records'	['question_type_global', 'question_two_hop_statement']
Who has issues assigned to them that were all resolved?	'Lucy', 'Zenaida', 'Milagros'	['question_type_global', 'question_two_hop_statement']
Are there any testers assigned to the [important] projects?	'Lucy', 'Bob', 'Alverta', 'Tom'	['question_type_global', 'question_three_hop_statement']
What are the [bug]s that are not resolved?	'parse example terribly slow'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are not resolved for [important] projects?	'issue in using training data'	['question_type_global', 'question_two_hop_statement']
[that person] is no longer assigned to [it]
Who is [the wrong pos tag on consecutive words issue] assigned to?	'Zenaida'	['question_type_local']
Which testers have issues assigned to them that were all resolved?	'Lucy'	['question_type_global', 'question_three_hop_statement']
Are there any testers assigned to projects in the [design] stage?	'Lucy', 'Bob', 'Alverta', 'Tom'	['question_type_global', 'question_three_hop_statement']
Who created [the wrong pos tag on consecutive words issue]?	'Lucy'	['question_type_local']
Which developers have issues assigned to them that were all resolved?	'Zenaida', 'Milagros'	['question_type_global', 'question_three_hop_statement']
who are the developers?	'Zenaida', 'Milagros', 'Michael'	['question_type_global', 'question_single_statement']
Are there any [proposal]s that are not resolved?	'issue in using training data'	['question_type_global', 'question_two_hop_statement']
Are there any developers assigned to the [important] projects?	'Zenaida', 'Milagros', 'Michael'	['question_type_global', 'question_three_hop_statement']
[Lucy] is working on [chatbot project] also
[chatbot project] is now in the [development] stage
Who is [the svd is slow issue] assigned to?	'Milagros'	['question_type_local']
who are the testers?	'Lucy', 'Bob', 'Alverta', 'Tom'	['question_type_global', 'question_single_statement']
who are the developers?	'Zenaida', 'Milagros', 'Michael'	['question_type_global', 'question_single_statement']
Who is [the wrong pos tag on consecutive words issue] assigned to?	'Zenaida'	['question_type_local']
Are there any issues for [chatbot project] that are resolved?	'parse example terribly slow', 'saving data throws exception', 'wrong pos tag on consecutive words', 'minified version fails', 'svd is slow', 'versioning needs to be made consistent', 'two consecutive dates identified as single date', 'memory leak while reading tf records'	['question_type_global', 'question_two_hop_statement']
What testers are assigned to the [important] projects?	'Lucy', 'Bob', 'Alverta', 'Tom'	['question_type_global', 'question_three_hop_statement']
Who was [the minified version fails issue] assigned to?	'Lucy'	['question_type_local']
What are the issues that are not resolved?	'issue in using training data'	['question_type_global', 'question_single_statement']
Are there any developers assigned to the [important] projects?	'Zenaida', 'Milagros', 'Michael'	['question_type_global', 'question_three_hop_statement']
What are the issues that are resolved for [important] projects?	'parse example terribly slow', 'saving data throws exception', 'wrong pos tag on consecutive words', 'minified version fails', 'svd is slow', 'versioning needs to be made consistent', 'two consecutive dates identified as single date', 'memory leak while reading tf records'	['question_type_global', 'question_two_hop_statement']
What are the non resolved issues?	'issue in using training data'	['question_type_global', 'question_single_statement']
Who is [the saving data throws exception issue] assigned to?	'Lucy'	['question_type_local']
Are there any issues that are resolved?	'parse example terribly slow', 'saving data throws exception', 'wrong pos tag on consecutive words', 'minified version fails', 'svd is slow', 'versioning needs to be made consistent', 'two consecutive dates identified as single date', 'memory leak while reading tf records'	['question_type_global', 'question_single_statement']
[chatbot project] is in the stage of [deployment]
What are the issues created by [Lucy] that were resolved?	'saving data throws exception', 'wrong pos tag on consecutive words', 'memory leak while reading tf records'	['question_type_local']
Are there any testers assigned to projects in the [evaluation] stage?	'Lucy', 'Bob', 'Alverta', 'Tom'	['question_type_global', 'question_three_hop_statement']
Who are the testers currently working on the [important] projects?	'Lucy', 'Bob', 'Alverta', 'Tom'	['question_type_global', 'question_three_hop_statement']
What projects is [Milagros] working on?	'chatbot', 'mobile', 'knowledge base'	['question_type_local']
What are the resolved issues?	'parse example terribly slow', 'saving data throws exception', 'wrong pos tag on consecutive words', 'minified version fails', 'svd is slow', 'versioning needs to be made consistent', 'two consecutive dates identified as single date', 'memory leak while reading tf records'	['question_type_global', 'question_single_statement']
What are the issues assigned to [Zenaida] that were resolved?	'wrong pos tag on consecutive words', 'two consecutive dates identified as single date', 'memory leak while reading tf records'	['question_type_local']
Are there projects in the [design] stage?	'knowledge base'	['question_type_global', 'question_single_statement']
Which developers have issues assigned to them that were all resolved?	'Zenaida', 'Milagros'	['question_type_global', 'question_three_hop_statement']
Who was [the two consecutive dates identified as single date enhancement] assigned to?	'Zenaida'	['question_type_local']
Are there any testers assigned to projects in the [evaluation] stage?	'Lucy', 'Bob', 'Alverta', 'Tom'	['question_type_global', 'question_three_hop_statement']
What testers are assigned to projects in the [evaluation] stage?	'Lucy', 'Bob', 'Alverta', 'Tom'	['question_type_global', 'question_three_hop_statement']
What are the non resolved issues?	'issue in using training data'	['question_type_global', 'question_single_statement']
[it] is in the [development] stage
Who submitted [the memory leak while reading tf records issue]?	'Lucy'	['question_type_local']
Are there any [bug]s that are not resolved?	'parse example terribly slow'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are resolved for projects in the [development] stage?	'parse example terribly slow', 'saving data throws exception', 'wrong pos tag on consecutive words', 'minified version fails', 'svd is slow', 'versioning needs to be made consistent', 'two consecutive dates identified as single date', 'memory leak while reading tf records'	['question_type_global', 'question_three_hop_statement']
What are the issues created by [Lucy]?	'saving data throws exception', 'wrong pos tag on consecutive words', 'memory leak while reading tf records'	['question_type_local']
Who is currently working on the [important] projects?	'Lucy', 'Zenaida', 'Bob', 'Milagros', 'Alverta', 'Tom', 'Michael'	['question_type_global', 'question_two_hop_statement']
which testers are assigned to [mobile project]	'Lucy', 'Bob', 'Alverta', 'Tom'	['question_type_local']
What are the non resolved [proposal]s?	'svd is slow'	['question_type_global', 'question_two_hop_statement']
Are there projects in the [design] stage?	'knowledge base'	['question_type_global', 'question_single_statement']
Who are the testers currently working on projects in the [design] stage?	'Lucy', 'Bob', 'Alverta', 'Tom'	['question_type_global', 'question_three_hop_statement']
Are there any [proposal]s that are not resolved?	'svd is slow'	['question_type_global', 'question_two_hop_statement']
who are the developers?	'Zenaida', 'Milagros', 'Michael'	['question_type_global', 'question_single_statement']
Who are the testers currently working on the [important] projects?	'Lucy', 'Bob', 'Alverta', 'Tom'	['question_type_global', 'question_three_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Zenaida', 'Milagros'	['question_type_global', 'question_three_hop_statement']
Who are the developers currently working on projects in the [development] stage?	'Zenaida', 'Milagros', 'Michael'	['question_type_global', 'question_three_hop_statement']
Which testers have issues assigned to them that were all resolved?	'Lucy'	['question_type_global', 'question_three_hop_statement']
[that project] is in the [evaluation] stage
[that project] is in the stage of [development]
What projects is [Zenaida] working on?	'chatbot', 'mobile', 'knowledge base'	['question_type_local']
Are there any developers assigned to projects in the [evaluation] stage?	'Zenaida', 'Milagros', 'Michael'	['question_type_global', 'question_three_hop_statement']
who are the developers?	'Zenaida', 'Milagros', 'Michael'	['question_type_global', 'question_single_statement']
What are the [bug]s that are not resolved?	'parse example terribly slow'	['question_type_global', 'question_two_hop_statement']
Who is [the enhancement] assigned to?	'Zenaida'	['question_type_local']
What developers are assigned to the [important] projects?	'Zenaida', 'Milagros', 'Michael'	['question_type_global', 'question_three_hop_statement']
who are the testers?	'Lucy', 'Bob', 'Alverta', 'Tom'	['question_type_global', 'question_single_statement']
What projects are [internal]?	'mobile', 'knowledge base'	['question_type_global', 'question_single_statement']
Who is assigned to the [important] projects?	'Lucy', 'Zenaida', 'Bob', 'Milagros', 'Alverta', 'Tom', 'Michael'	['question_type_global', 'question_two_hop_statement']
What projects is [Bob] working on?	'chatbot', 'mobile', 'knowledge base'	['question_type_local']
Are there any issues that are resolved?	'parse example terribly slow', 'saving data throws exception', 'wrong pos tag on consecutive words', 'minified version fails', 'svd is slow', 'versioning needs to be made consistent', 'two consecutive dates identified as single date', 'memory leak while reading tf records'	['question_type_global', 'question_single_statement']
Who has issues assigned to them that were all resolved?	'Lucy', 'Zenaida', 'Milagros'	['question_type_global', 'question_two_hop_statement']
who are the developers?	'Zenaida', 'Milagros', 'Michael'	['question_type_global', 'question_single_statement']
which testers are assigned to [knowledge base project]	'Lucy', 'Bob', 'Alverta', 'Tom'	['question_type_local']
Are there any issues that are not resolved?	'issue in using training data'	['question_type_global', 'question_single_statement']
What are the issues assigned to [Lucy] that were resolved?	'parse example terribly slow', 'saving data throws exception', 'minified version fails', 'versioning needs to be made consistent'	['question_type_local']
What testers are assigned to projects in the [design] stage?	'Lucy', 'Bob', 'Alverta', 'Tom'	['question_type_global', 'question_three_hop_statement']
What are the non resolved issues?	'issue in using training data'	['question_type_global', 'question_single_statement']
Who are the developers currently working on the [internal] projects?	'Zenaida', 'Milagros', 'Michael'	['question_type_global', 'question_three_hop_statement']
[it] is in the [design] stage
Which developers are working on [mobile project]?	'Zenaida', 'Milagros', 'Michael'	['question_type_local']
Who is currently working on the [internal] projects?	'Lucy', 'Zenaida', 'Bob', 'Milagros', 'Alverta', 'Tom', 'Michael'	['question_type_global', 'question_two_hop_statement']
[it] has moved to the [evaluation] stage
Who was [the memory leak while reading tf records issue] assigned to?	'Zenaida'	['question_type_local']
What are the resolved issues?	'parse example terribly slow', 'saving data throws exception', 'wrong pos tag on consecutive words', 'minified version fails', 'svd is slow', 'versioning needs to be made consistent', 'two consecutive dates identified as single date', 'memory leak while reading tf records'	['question_type_global', 'question_single_statement']
Are there any developers assigned to projects in the [design] stage?	'Zenaida', 'Milagros', 'Michael'	['question_type_global', 'question_three_hop_statement']
Are there any issues that are resolved for [important] projects?	'parse example terribly slow', 'saving data throws exception', 'wrong pos tag on consecutive words', 'minified version fails', 'svd is slow', 'versioning needs to be made consistent', 'two consecutive dates identified as single date', 'memory leak while reading tf records'	['question_type_global', 'question_two_hop_statement']
Are there any people assigned to the [important] projects?	'Lucy', 'Zenaida', 'Bob', 'Milagros', 'Alverta', 'Tom', 'Michael'	['question_type_global', 'question_two_hop_statement']
[that project] has moved to the [design] stage
Who are the developers on [mobile project]	'Zenaida', 'Milagros', 'Michael'	['question_type_local']
Which developers have issues assigned to them that were all resolved?	'Zenaida', 'Milagros'	['question_type_global', 'question_three_hop_statement']
Who created [the wrong pos tag on consecutive words issue]?	'Lucy'	['question_type_local']
Are there any issues that are resolved?	'parse example terribly slow', 'saving data throws exception', 'wrong pos tag on consecutive words', 'minified version fails', 'svd is slow', 'versioning needs to be made consistent', 'two consecutive dates identified as single date', 'memory leak while reading tf records'	['question_type_global', 'question_single_statement']
Who has issues assigned to them that were all resolved?	'Lucy', 'Zenaida', 'Milagros'	['question_type_global', 'question_two_hop_statement']
What are the issues that are resolved for projects in the [design] stage?	'parse example terribly slow', 'saving data throws exception', 'wrong pos tag on consecutive words', 'minified version fails', 'svd is slow', 'versioning needs to be made consistent', 'two consecutive dates identified as single date', 'memory leak while reading tf records'	['question_type_global', 'question_three_hop_statement']
[chatbot project] is now in the [evaluation] stage
