there is a new [experimental] [knowledge base] [project]
[it] is in the [implementation] stage
there is a new [personal] [chatbot] [project]
[chatbot project] is in the stage of [implementation]
Which is the stage of [it]?	'implementation'	['question_type_local']
There is a new [enhancement] for the [knowledge base project]: [saving data throws exception]
[xml extractor exception] is a new issue for the [that project]
What are the non resolved issues for [personal] projects?	'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
What are the non resolved [enhancement]s?	'saving data throws exception'	['question_type_global', 'question_two_hop_statement']
[chatbot project] is now in the [testing] stage
[dcoref always returns null] is a new [proposal] for the [this project]
[Alejandra] is a [developer] on [knowledge base project]
[this developer] is working on [chatbot project] also
[Stephine] is a [developer]
[knowledge base project] is assigned to [Stephine]
What are the non resolved issues for [experimental] projects?	'saving data throws exception'	['question_type_global', 'question_two_hop_statement']
Who are the developers currently working on projects in the [implementation] stage?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
[the xml extractor exception issue] was assigned to [Alejandra]
[she] resolved [it]
What are the [experimental] projects?	'knowledge base'	['question_type_global', 'question_single_statement']
What are the issues that are resolved for projects in the [testing] stage?	'xml extractor exception'	['question_type_global', 'question_three_hop_statement']
Are there any people assigned to projects in the [implementation] stage?	'Alejandra', 'Stephine'	['question_type_global', 'question_two_hop_statement']
What are the resolved issues for projects in the [testing] stage?	'xml extractor exception'	['question_type_global', 'question_three_hop_statement']
Who is currently working on projects in the [testing] stage?	'Alejandra'	['question_type_global', 'question_two_hop_statement']
Are there any issues for [knowledge base project] that are not resolved?	'saving data throws exception'	['question_type_global', 'question_two_hop_statement']
Who are the developers currently working on projects in the [implementation] stage?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
Are there any issues that are resolved for [personal] projects?	'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
What are the [experimental] projects?	'knowledge base'	['question_type_global', 'question_single_statement']
[knowledge base project] is now in the [maintenance] stage
Which developers are assigned to [chatbot project]	'Alejandra'	['question_type_local']
Are there any people assigned to projects in the [maintenance] stage?	'Alejandra', 'Stephine'	['question_type_global', 'question_two_hop_statement']
[Stephine] is assigned to [chatbot project] also
What developers are assigned to projects in the [testing] stage?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
Are there projects in the [testing] stage?	'chatbot'	['question_type_global', 'question_single_statement']
Who is assigned to projects in the [maintenance] stage?	'Alejandra', 'Stephine'	['question_type_global', 'question_two_hop_statement']
What projects is [that person] working on?	'knowledge base', 'chatbot'	['question_type_local']
Which developers have issues assigned to them that were all resolved?	'Alejandra'	['question_type_global', 'question_three_hop_statement']
Who are the developers currently working on the [experimental] projects?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
Who has issues assigned to them that were all resolved?	'Alejandra'	['question_type_global', 'question_two_hop_statement']
Are there any developers assigned to the [personal] projects?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
What projects are currently in the [testing] stage?	'chatbot'	['question_type_global', 'question_single_statement']
What are the [enhancement]s that are not resolved?	'saving data throws exception'	['question_type_global', 'question_two_hop_statement']
What are the issues that are resolved for [personal] projects?	'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
What are the non resolved issues for [personal] projects?	'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are resolved?	'xml extractor exception'	['question_type_global', 'question_single_statement']
Are there projects in the [maintenance] stage?	'knowledge base'	['question_type_global', 'question_single_statement']
What are the issues assigned to [Alejandra] that were resolved?	'xml extractor exception'	['question_type_local']
What developers are assigned to the [experimental] projects?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
there is a new [mobile] [project]
[fails with apache stack] is a new [proposal] for [knowledge base project] that [Alejandra] just created
[the issue] was assigned to [Alejandra]
Who created [the fails with apache stack issue]?	'Alejandra'	['question_type_local']
Who has issues assigned to them that were not resolved?	'Alejandra'	['question_type_global', 'question_two_hop_statement']
What are the non resolved issues?	'saving data throws exception', 'dcoref always returns null', 'fails with apache stack'	['question_type_global', 'question_single_statement']
Which developers have issues assigned to them that were all resolved?	'Alejandra'	['question_type_global', 'question_three_hop_statement']
Are there any [enhancement]s that are not resolved?	'saving data throws exception'	['question_type_global', 'question_two_hop_statement']
[Luanna] is a [tester] on [mobile project]
[Alejandra] is assigned to [mobile project] also
[Angelita] is a [tester] on [knowledge base project]
[Emmie] is a [developer]
[that developer] is assigned to [knowledge base project]
What are the issues assigned to [Alejandra] that were resolved?	'xml extractor exception'	['question_type_local']
What are the issues that are resolved for [personal] projects?	'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
What are the non resolved [proposal]s?	'dcoref always returns null', 'fails with apache stack'	['question_type_global', 'question_two_hop_statement']
[Britney] is a [tester] on [mobile project]
[this tester] is assigned to [chatbot project] also
Who are the developers currently working on the [experimental] projects?	'Alejandra', 'Stephine', 'Emmie'	['question_type_global', 'question_three_hop_statement']
Who are the developers currently working on the [personal] projects?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
[she] is assigned to [knowledge base project] also
[chatbot project] is assigned to [Angelita] also
[Alejandra] resolved [the fails with apache stack proposal]
[mobile project] is a [corporate] project
[mobile project] is currently in the [testing] stage
Are there any developers assigned to projects in the [testing] stage?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
[the enhancement] was assigned to [Angelita]
[this person] is assigned to [mobile project] also
[that project] is in the stage of [implementation]
Which developers have issues assigned to them that were all resolved?	'Alejandra'	['question_type_global', 'question_three_hop_statement']
Are there any issues that are not resolved for [experimental] projects?	'saving data throws exception'	['question_type_global', 'question_two_hop_statement']
Who has issues assigned to them that were all resolved?	'Alejandra'	['question_type_global', 'question_two_hop_statement']
Are there any testers assigned to the [corporate] projects?	'Luanna', 'Angelita', 'Britney'	['question_type_global', 'question_three_hop_statement']
[Angelita] resolved [the saving data throws exception enhancement]
[Britney] created a new issue for [chatbot project]: [changelong needs to be added]
Which testers have issues assigned to them that were all resolved?	'Angelita'	['question_type_global', 'question_three_hop_statement']
Who is assigned to projects in the [maintenance] stage?	'Alejandra', 'Stephine', 'Angelita', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
Who are the testers currently working on the [experimental] projects?	'Angelita', 'Britney'	['question_type_global', 'question_three_hop_statement']
Are there any people assigned to projects in the [implementation] stage?	'Alejandra', 'Luanna', 'Angelita', 'Britney'	['question_type_global', 'question_two_hop_statement']
[that issue] was assigned to [that person]
[she] resolved [the changelong needs to be added issue]
Who is currently working on the [corporate] projects?	'Alejandra', 'Luanna', 'Angelita', 'Britney'	['question_type_global', 'question_two_hop_statement']
What are the [proposal]s that are not resolved?	'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
Who are the testers currently working on projects in the [implementation] stage?	'Luanna', 'Angelita', 'Britney'	['question_type_global', 'question_three_hop_statement']
Who is working on [knowledge base project]?	'Alejandra', 'Stephine', 'Angelita', 'Emmie', 'Britney'	['question_type_local']
Which testers have issues assigned to them that were all resolved?	'Angelita'	['question_type_global', 'question_three_hop_statement']
Who are the testers currently working on projects in the [testing] stage?	'Angelita', 'Britney'	['question_type_global', 'question_three_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Alejandra'	['question_type_global', 'question_three_hop_statement']
What are the issues assigned to [Alejandra] that were resolved?	'xml extractor exception', 'fails with apache stack'	['question_type_local']
Are there any issues that are resolved for [experimental] projects?	'saving data throws exception', 'fails with apache stack'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are not resolved?	'dcoref always returns null'	['question_type_global', 'question_single_statement']
Are there any issues that are resolved?	'saving data throws exception', 'xml extractor exception', 'fails with apache stack', 'changelong needs to be added'	['question_type_global', 'question_single_statement']
[mobile project] has moved to the [testing] stage
Are there any testers assigned to the [personal] projects?	'Angelita', 'Britney'	['question_type_global', 'question_three_hop_statement']
Are there any issues that are not resolved for [personal] projects?	'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
Who submitted [the changelong needs to be added issue]?	'Britney'	['question_type_local']
[this tester] created a new issue for [chatbot project]: [versioning needs to be made consistent]
[the versioning needs to be made consistent issue] was assigned to [Britney]
What are the issues that are resolved for projects in the [maintenance] stage?	'saving data throws exception', 'fails with apache stack'	['question_type_global', 'question_three_hop_statement']
Who has issues assigned to them that were all resolved?	'Alejandra', 'Angelita'	['question_type_global', 'question_two_hop_statement']
[this person] resolved [the versioning needs to be made consistent issue]
who are the testers?	'Luanna', 'Angelita', 'Britney'	['question_type_global', 'question_single_statement']
Who is currently working on projects in the [maintenance] stage?	'Alejandra', 'Stephine', 'Angelita', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Alejandra'	['question_type_global', 'question_three_hop_statement']
What are the issues that are resolved for [personal] projects?	'xml extractor exception', 'changelong needs to be added', 'versioning needs to be made consistent'	['question_type_global', 'question_two_hop_statement']
[knowledge base project] is in the stage of [testing]
What are the issues assigned to [Alejandra] that were resolved?	'xml extractor exception', 'fails with apache stack'	['question_type_local']
Are there any issues that are not resolved for [personal] projects?	'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
[issue in using training data] is a new [task] for [chatbot project] that [Britney] just created
[that issue] is assigned to [Stephine]
[this developer] resolved [the issue in using training data task]
Who is currently working on the [experimental] projects?	'Alejandra', 'Stephine', 'Angelita', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
What are the non resolved issues for projects in the [testing] stage?	'dcoref always returns null'	['question_type_global', 'question_three_hop_statement']
[mobile project] is assigned to [she] also
Who is working on [chatbot project]?	'Alejandra', 'Stephine', 'Angelita', 'Britney'	['question_type_local']
Are there any people assigned to the [experimental] projects?	'Alejandra', 'Stephine', 'Angelita', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
What testers are assigned to the [experimental] projects?	'Angelita', 'Britney'	['question_type_global', 'question_three_hop_statement']
What are the issues that are not resolved for projects in the [testing] stage?	'dcoref always returns null'	['question_type_global', 'question_three_hop_statement']
[Britney] is not working on [knowledge base project] anymore
What are the [enhancement]s that are not resolved?	'saving data throws exception'	['question_type_global', 'question_two_hop_statement']
Who is currently working on projects in the [testing] stage?	'Alejandra', 'Stephine', 'Luanna', 'Angelita', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
[that project] is assigned to [that person] also
Are there any testers assigned to projects in the [testing] stage?	'Luanna', 'Angelita', 'Britney'	['question_type_global', 'question_three_hop_statement']
Who was [the xml extractor exception issue] assigned to?	'Alejandra'	['question_type_local']
who are the testers?	'Luanna', 'Angelita', 'Britney'	['question_type_global', 'question_single_statement']
Which developers have issues assigned to them that were all resolved?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
Are there any people assigned to projects in the [testing] stage?	'Alejandra', 'Stephine', 'Luanna', 'Angelita', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
[it] is in the [maintenance] stage
What testers are assigned to the [experimental] projects?	'Angelita', 'Britney'	['question_type_global', 'question_three_hop_statement']
Are there any issues assigned to [Stephine] that are resolved?	'issue in using training data'	['question_type_local']
Who is assigned to the [experimental] projects?	'Alejandra', 'Stephine', 'Angelita', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
[two consecutive dates identified as single date] is a new [task] for the [chatbot project]
[that issue] was assigned to [Alejandra]
[mobile project] is now in the [maintenance] stage
[mobile project] is in the [implementation] stage
[Luanna] created a new [enhancement] for [mobile project]: [minified version fails]
[the minified version fails enhancement] is assigned to [Stephine]
Are there any issues that are not resolved for projects in the [testing] stage?	'dcoref always returns null', 'two consecutive dates identified as single date'	['question_type_global', 'question_three_hop_statement']
Who is currently working on the [experimental] projects?	'Alejandra', 'Stephine', 'Angelita', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
Who is assigned to the [corporate] projects?	'Alejandra', 'Stephine', 'Luanna', 'Angelita', 'Britney'	['question_type_global', 'question_two_hop_statement']
Are there any [task]s that are not resolved?	'two consecutive dates identified as single date'	['question_type_global', 'question_two_hop_statement']
[this developer] resolved [it]
Who submitted [the issue in using training data task]?	'Britney'	['question_type_local']
Who are the testers currently working on the [experimental] projects?	'Angelita', 'Britney'	['question_type_global', 'question_three_hop_statement']
What are the [experimental] projects?	'knowledge base'	['question_type_global', 'question_single_statement']
Who are the testers currently working on the [corporate] projects?	'Luanna', 'Angelita', 'Britney'	['question_type_global', 'question_three_hop_statement']
Which testers are working on [mobile project]?	'Luanna', 'Angelita', 'Britney'	['question_type_local']
What testers are assigned to the [corporate] projects?	'Luanna', 'Angelita', 'Britney'	['question_type_global', 'question_three_hop_statement']
Are there any developers assigned to the [corporate] projects?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
Who created [that issue]?	'Luanna'	['question_type_local']
What are the issues that are not resolved for [personal] projects?	'dcoref always returns null', 'two consecutive dates identified as single date'	['question_type_global', 'question_two_hop_statement']
who are the developers?	'Alejandra', 'Stephine', 'Emmie'	['question_type_global', 'question_single_statement']
What are the issues that are resolved for projects in the [testing] stage?	'xml extractor exception', 'changelong needs to be added', 'versioning needs to be made consistent', 'issue in using training data'	['question_type_global', 'question_three_hop_statement']
Who created [the enhancement]?	'Luanna'	['question_type_local']
Which developers have issues assigned to them that were all resolved?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
What developers are assigned to the [corporate] projects?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
What are the non resolved issues for [personal] projects?	'dcoref always returns null', 'two consecutive dates identified as single date'	['question_type_global', 'question_two_hop_statement']
Who is [the xml extractor exception issue] assigned to?	'Alejandra'	['question_type_local']
Are there any people assigned to the [personal] projects?	'Alejandra', 'Stephine', 'Angelita', 'Britney'	['question_type_global', 'question_two_hop_statement']
Were there any issues created by [Alejandra]?	'fails with apache stack'	['question_type_local']
What developers are assigned to the [experimental] projects?	'Alejandra', 'Stephine', 'Emmie'	['question_type_global', 'question_three_hop_statement']
which testers are assigned to [knowledge base project]	'Angelita', 'Britney'	['question_type_local']
Who created [the issue in using training data task]?	'Britney'	['question_type_local']
Are there any issues that are resolved?	'saving data throws exception', 'xml extractor exception', 'fails with apache stack', 'changelong needs to be added', 'versioning needs to be made consistent', 'issue in using training data', 'minified version fails'	['question_type_global', 'question_single_statement']
What are the issues that are resolved for projects in the [maintenance] stage?	'saving data throws exception', 'fails with apache stack'	['question_type_global', 'question_three_hop_statement']
Who are the developers currently working on the [experimental] projects?	'Alejandra', 'Stephine', 'Emmie'	['question_type_global', 'question_three_hop_statement']
What are the issues created by [Alejandra] that were resolved?	'fails with apache stack'	['question_type_local']
Which developers have issues assigned to them that were all resolved?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
who are the testers?	'Luanna', 'Angelita', 'Britney'	['question_type_global', 'question_single_statement']
What are the issues that are resolved for projects in the [testing] stage?	'xml extractor exception', 'changelong needs to be added', 'versioning needs to be made consistent', 'issue in using training data'	['question_type_global', 'question_three_hop_statement']
Are there any issues that are resolved for [corporate] projects?	'minified version fails'	['question_type_global', 'question_two_hop_statement']
What are the issues that are resolved for projects in the [implementation] stage?	'minified version fails'	['question_type_global', 'question_three_hop_statement']
Which developers have issues assigned to them that were not resolved?	'Alejandra'	['question_type_global', 'question_three_hop_statement']
What developers are assigned to the [experimental] projects?	'Alejandra', 'Stephine', 'Emmie'	['question_type_global', 'question_three_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
What are the non resolved issues for [chatbot project]?	'dcoref always returns null', 'two consecutive dates identified as single date'	['question_type_global', 'question_two_hop_statement']
What projects are [personal]?	'chatbot'	['question_type_global', 'question_single_statement']
Which testers have issues assigned to them that were all resolved?	'Angelita', 'Britney'	['question_type_global', 'question_three_hop_statement']
Are there any [task]s that are not resolved?	'issue in using training data'	['question_type_global', 'question_two_hop_statement']
Are there any people assigned to projects in the [implementation] stage?	'Alejandra', 'Stephine', 'Luanna', 'Angelita', 'Britney'	['question_type_global', 'question_two_hop_statement']
Are there any projects that are [experimental]?	'knowledge base'	['question_type_global', 'question_single_statement']
What are the [proposal]s that are not resolved?	'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
[knowledge base project] is in the [testing] stage
What projects is [Emmie] working on?	'knowledge base'	['question_type_local']
What are the issues that are resolved for [experimental] projects?	'saving data throws exception', 'fails with apache stack'	['question_type_global', 'question_two_hop_statement']
who are the developers?	'Alejandra', 'Stephine', 'Emmie'	['question_type_global', 'question_single_statement']
Which developers have issues assigned to them that were all resolved?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
Are there any [task]s that are not resolved?	'two consecutive dates identified as single date'	['question_type_global', 'question_two_hop_statement']
Who is [the fails with apache stack issue] assigned to?	'Alejandra'	['question_type_local']
Are there any people assigned to the [experimental] projects?	'Alejandra', 'Stephine', 'Angelita', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
[Alejandra] resolved [the two consecutive dates identified as single date task]
Who is [the xml extractor exception issue] assigned to?	'Alejandra'	['question_type_local']
Are there any projects that are [corporate]?	'mobile'	['question_type_global', 'question_single_statement']
who are the testers?	'Luanna', 'Angelita', 'Britney'	['question_type_global', 'question_single_statement']
What are the resolved issues for projects in the [testing] stage?	'saving data throws exception', 'xml extractor exception', 'fails with apache stack', 'changelong needs to be added', 'versioning needs to be made consistent', 'issue in using training data', 'two consecutive dates identified as single date'	['question_type_global', 'question_three_hop_statement']
[she] is no longer assigned to [chatbot project]
[that person] is working on [this project] also
Who are the developers on [mobile project]	'Alejandra', 'Stephine'	['question_type_local']
What are the issues for [this project] that are resolved?	'xml extractor exception', 'changelong needs to be added', 'versioning needs to be made consistent', 'issue in using training data', 'two consecutive dates identified as single date'	['question_type_global', 'question_two_hop_statement']
What are the issues that are not resolved for [personal] projects?	'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
What projects is [Luanna] working on?	'mobile'	['question_type_local']
Are there any developers assigned to projects in the [implementation] stage?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
Who has issues assigned to them that were all resolved?	'Alejandra', 'Stephine', 'Angelita', 'Britney'	['question_type_global', 'question_two_hop_statement']
What projects are in the [testing] stage?	'knowledge base', 'chatbot'	['question_type_global', 'question_single_statement']
Are there any people assigned to the [personal] projects?	'Alejandra', 'Stephine', 'Angelita', 'Britney'	['question_type_global', 'question_two_hop_statement']
Are there any testers assigned to the [personal] projects?	'Angelita', 'Britney'	['question_type_global', 'question_three_hop_statement']
What are the resolved issues for [experimental] projects?	'saving data throws exception', 'fails with apache stack'	['question_type_global', 'question_two_hop_statement']
What are the issues that were resolved?	'saving data throws exception', 'xml extractor exception', 'fails with apache stack', 'changelong needs to be added', 'versioning needs to be made consistent', 'issue in using training data', 'two consecutive dates identified as single date', 'minified version fails'	['question_type_global', 'question_single_statement']
who are the testers?	'Luanna', 'Angelita', 'Britney'	['question_type_global', 'question_single_statement']
Who is assigned to the [personal] projects?	'Alejandra', 'Stephine', 'Angelita', 'Britney'	['question_type_global', 'question_two_hop_statement']
Are there any testers assigned to the [experimental] projects?	'Angelita', 'Britney'	['question_type_global', 'question_three_hop_statement']
Are there any developers assigned to projects in the [implementation] stage?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
Were there any issues created by [Britney]?	'changelong needs to be added', 'issue in using training data'	['question_type_local']
Who has issues assigned to them that were all resolved?	'Alejandra', 'Stephine', 'Angelita', 'Britney'	['question_type_global', 'question_two_hop_statement']
What are the resolved issues for projects in the [implementation] stage?	'minified version fails'	['question_type_global', 'question_three_hop_statement']
What are the [enhancement]s that are not resolved?	'saving data throws exception', 'minified version fails'	['question_type_global', 'question_two_hop_statement']
What are the issues that are not resolved for [personal] projects?	'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
[mobile project] is not assigned to [Alejandra]
[mobile project] is assigned to [this developer] also
Who submitted [the minified version fails issue]?	'Luanna'	['question_type_local']
What are the resolved issues?	'saving data throws exception', 'xml extractor exception', 'fails with apache stack', 'changelong needs to be added', 'versioning needs to be made consistent', 'issue in using training data', 'two consecutive dates identified as single date', 'minified version fails'	['question_type_global', 'question_single_statement']
Which testers have issues assigned to them that were all resolved?	'Angelita', 'Britney'	['question_type_global', 'question_three_hop_statement']
What testers are assigned to projects in the [implementation] stage?	'Luanna', 'Angelita', 'Britney'	['question_type_global', 'question_three_hop_statement']
What are the issues that are resolved for [corporate] projects?	'minified version fails'	['question_type_global', 'question_two_hop_statement']
Who is assigned to the [experimental] projects?	'Alejandra', 'Stephine', 'Angelita', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
Who is assigned to projects in the [implementation] stage?	'Alejandra', 'Stephine', 'Luanna', 'Angelita', 'Britney'	['question_type_global', 'question_two_hop_statement']
Who are the developers on [chatbot project]	'Alejandra', 'Stephine'	['question_type_local']
What are the issues that are not resolved?	'dcoref always returns null'	['question_type_global', 'question_single_statement']
What are the issues that are resolved for [personal] projects?	'xml extractor exception', 'changelong needs to be added', 'versioning needs to be made consistent', 'issue in using training data', 'two consecutive dates identified as single date'	['question_type_global', 'question_two_hop_statement']
What developers are assigned to the [personal] projects?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
What are the issues created by [Luanna]?	'minified version fails'	['question_type_local']
Are there any issues that are not resolved for [personal] projects?	'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
Are there projects in the [testing] stage?	'knowledge base', 'chatbot'	['question_type_global', 'question_single_statement']
Which developers have issues assigned to them that were all resolved?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
What are the resolved issues?	'saving data throws exception', 'xml extractor exception', 'fails with apache stack', 'changelong needs to be added', 'versioning needs to be made consistent', 'issue in using training data', 'two consecutive dates identified as single date', 'minified version fails'	['question_type_global', 'question_single_statement']
Who is assigned to the [experimental] projects?	'Alejandra', 'Stephine', 'Angelita', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
Who is working on [knowledge base project]?	'Alejandra', 'Stephine', 'Angelita', 'Emmie', 'Britney'	['question_type_local']
What are the [enhancement]s that are not resolved?	'saving data throws exception', 'minified version fails'	['question_type_global', 'question_two_hop_statement']
What testers are assigned to the [personal] projects?	'Angelita', 'Britney'	['question_type_global', 'question_three_hop_statement']
Are there any [enhancement]s that are not resolved?	'saving data throws exception', 'minified version fails'	['question_type_global', 'question_two_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
Who was [the xml extractor exception issue] assigned to?	'Alejandra'	['question_type_local']
What projects are currently in the [implementation] stage?	'mobile'	['question_type_global', 'question_single_statement']
Are there projects in the [implementation] stage?	'mobile'	['question_type_global', 'question_single_statement']
Who created [the minified version fails issue]?	'Luanna'	['question_type_local']
Who is [the fails with apache stack proposal] assigned to?	'Alejandra'	['question_type_local']
What are the issues for [chatbot project] that are not resolved?	'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
Who has issues assigned to them that were all resolved?	'Alejandra', 'Stephine', 'Angelita', 'Britney'	['question_type_global', 'question_two_hop_statement']
Who are the testers currently working on the [experimental] projects?	'Angelita', 'Britney'	['question_type_global', 'question_three_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
What are the issues that are not resolved?	'dcoref always returns null'	['question_type_global', 'question_single_statement']
What are the resolved issues?	'saving data throws exception', 'xml extractor exception', 'fails with apache stack', 'changelong needs to be added', 'versioning needs to be made consistent', 'issue in using training data', 'two consecutive dates identified as single date', 'minified version fails'	['question_type_global', 'question_single_statement']
What are the issues submitted by [Luanna]?	'minified version fails'	['question_type_local']
What are the non resolved issues?	'dcoref always returns null'	['question_type_global', 'question_single_statement']
What are the issues that were resolved?	'saving data throws exception', 'xml extractor exception', 'fails with apache stack', 'changelong needs to be added', 'versioning needs to be made consistent', 'issue in using training data', 'two consecutive dates identified as single date', 'minified version fails'	['question_type_global', 'question_single_statement']
What testers are assigned to projects in the [testing] stage?	'Angelita', 'Britney'	['question_type_global', 'question_three_hop_statement']
who are the testers?	'Luanna', 'Angelita', 'Britney'	['question_type_global', 'question_single_statement']
Are there any issues that are resolved?	'saving data throws exception', 'xml extractor exception', 'fails with apache stack', 'changelong needs to be added', 'versioning needs to be made consistent', 'issue in using training data', 'two consecutive dates identified as single date', 'minified version fails'	['question_type_global', 'question_single_statement']
What are the resolved issues for projects in the [testing] stage?	'saving data throws exception', 'xml extractor exception', 'fails with apache stack', 'changelong needs to be added', 'versioning needs to be made consistent', 'issue in using training data', 'two consecutive dates identified as single date'	['question_type_global', 'question_three_hop_statement']
[this person] is no longer assigned to [chatbot project]
[this person] is assigned to [this project] also
[it] has moved to the [maintenance] stage
Who was [the two consecutive dates identified as single date task] assigned to?	'Alejandra'	['question_type_local']
What are the non resolved issues for projects in the [maintenance] stage?	'dcoref always returns null'	['question_type_global', 'question_three_hop_statement']
What projects are currently in the [testing] stage?	'knowledge base'	['question_type_global', 'question_single_statement']
What developers are assigned to projects in the [maintenance] stage?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
[Alejandra] is not working on [that project] anymore
[this project] is assigned to [that developer] also
[knowledge base project] is now in the [implementation] stage
[the dcoref always returns null proposal] is assigned to [Alejandra]
What are the issues that are not resolved for projects in the [maintenance] stage?	'dcoref always returns null'	['question_type_global', 'question_three_hop_statement']
[this person] resolved [the proposal]
[that person] is no longer assigned to [knowledge base project]
[this person] is assigned to [knowledge base project] also
Which testers are working on [this project]?	'Angelita', 'Britney'	['question_type_local']
Who are the testers currently working on projects in the [implementation] stage?	'Luanna', 'Angelita', 'Britney'	['question_type_global', 'question_three_hop_statement']
What developers are assigned to the [corporate] projects?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
Who is currently working on projects in the [implementation] stage?	'Alejandra', 'Stephine', 'Luanna', 'Angelita', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
Who is [the versioning needs to be made consistent issue] assigned to?	'Britney'	['question_type_local']
Are there any people assigned to the [experimental] projects?	'Alejandra', 'Stephine', 'Angelita', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
Were there any issues submitted by [that person]?	'fails with apache stack'	['question_type_local']
Are there any issues that are resolved for projects in the [implementation] stage?	'saving data throws exception', 'fails with apache stack', 'minified version fails'	['question_type_global', 'question_three_hop_statement']
Who is assigned to the [experimental] projects?	'Alejandra', 'Stephine', 'Angelita', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
who are the testers?	'Luanna', 'Angelita', 'Britney'	['question_type_global', 'question_single_statement']
who are the developers?	'Alejandra', 'Stephine', 'Emmie'	['question_type_global', 'question_single_statement']
Who has issues assigned to them that were all resolved?	'Alejandra', 'Stephine', 'Angelita', 'Britney'	['question_type_global', 'question_two_hop_statement']
Who was [the xml extractor exception issue] assigned to?	'Alejandra'	['question_type_local']
What projects are currently in the [implementation] stage?	'knowledge base', 'mobile'	['question_type_global', 'question_single_statement']
Are there any people assigned to the [experimental] projects?	'Alejandra', 'Stephine', 'Angelita', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
What are the [proposal]s that are not resolved?	'dcoref always returns null', 'fails with apache stack'	['question_type_global', 'question_two_hop_statement']
Which testers have issues assigned to them that were all resolved?	'Angelita', 'Britney'	['question_type_global', 'question_three_hop_statement']
Who are the testers currently working on the [personal] projects?	'Angelita', 'Britney'	['question_type_global', 'question_three_hop_statement']
What are the issues created by [Luanna]?	'minified version fails'	['question_type_local']
Which developers have issues assigned to them that were all resolved?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
What are the issues that are resolved for projects in the [maintenance] stage?	'xml extractor exception', 'dcoref always returns null', 'changelong needs to be added', 'versioning needs to be made consistent', 'issue in using training data', 'two consecutive dates identified as single date'	['question_type_global', 'question_three_hop_statement']
Who is working on [chatbot project]?	'Alejandra', 'Stephine', 'Angelita', 'Britney'	['question_type_local']
Who are the testers currently working on the [experimental] projects?	'Angelita', 'Britney'	['question_type_global', 'question_three_hop_statement']
Are there any projects that are [personal]?	'chatbot'	['question_type_global', 'question_single_statement']
Who has issues assigned to them that were all resolved?	'Alejandra', 'Stephine', 'Angelita', 'Britney'	['question_type_global', 'question_two_hop_statement']
What testers are assigned to the [corporate] projects?	'Luanna', 'Angelita', 'Britney'	['question_type_global', 'question_three_hop_statement']
Are there any [corporate] projects?	'mobile'	['question_type_global', 'question_single_statement']
What testers are assigned to projects in the [implementation] stage?	'Luanna', 'Angelita', 'Britney'	['question_type_global', 'question_three_hop_statement']
What stage is [this project] in?	'implementation'	['question_type_local']
Are there any testers assigned to projects in the [maintenance] stage?	'Angelita', 'Britney'	['question_type_global', 'question_three_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
What are the [task]s that are not resolved?	'issue in using training data', 'two consecutive dates identified as single date'	['question_type_global', 'question_two_hop_statement']
[this project] is in the stage of [testing]
[it] is now in the [implementation] stage
[that project] is in the [testing] stage
Who was [the xml extractor exception issue] assigned to?	'Alejandra'	['question_type_local']
Who has issues assigned to them that were all resolved?	'Alejandra', 'Stephine', 'Angelita', 'Britney'	['question_type_global', 'question_two_hop_statement']
Who is [the issue in using training data issue] assigned to?	'Stephine'	['question_type_local']
Are there any people assigned to the [corporate] projects?	'Alejandra', 'Stephine', 'Luanna', 'Angelita', 'Britney'	['question_type_global', 'question_two_hop_statement']
What projects are currently in the [implementation] stage?	'mobile'	['question_type_global', 'question_single_statement']
Who is [the fails with apache stack proposal] assigned to?	'Alejandra'	['question_type_local']
Who is assigned to the [corporate] projects?	'Alejandra', 'Stephine', 'Luanna', 'Angelita', 'Britney'	['question_type_global', 'question_two_hop_statement']
[Stephine] is not working on [chatbot project] anymore
Are there any developers assigned to projects in the [testing] stage?	'Alejandra', 'Stephine', 'Emmie'	['question_type_global', 'question_three_hop_statement']
What are the non resolved [enhancement]s?	'saving data throws exception', 'minified version fails'	['question_type_global', 'question_two_hop_statement']
Which testers have issues assigned to them that were all resolved?	'Angelita', 'Britney'	['question_type_global', 'question_three_hop_statement']
Who are the developers currently working on projects in the [testing] stage?	'Alejandra', 'Stephine', 'Emmie'	['question_type_global', 'question_three_hop_statement']
What are the issues that were resolved?	'saving data throws exception', 'xml extractor exception', 'dcoref always returns null', 'fails with apache stack', 'changelong needs to be added', 'versioning needs to be made consistent', 'issue in using training data', 'two consecutive dates identified as single date', 'minified version fails'	['question_type_global', 'question_single_statement']
Who is assigned to the [personal] projects?	'Alejandra', 'Angelita', 'Britney'	['question_type_global', 'question_two_hop_statement']
[that person] is working on [it] also
Are there any issues for [mobile project] that are resolved?	'minified version fails'	['question_type_global', 'question_two_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
Who is [the issue in using training data task] assigned to?	'Stephine'	['question_type_local']
Are there any issues that are resolved for [experimental] projects?	'saving data throws exception', 'fails with apache stack'	['question_type_global', 'question_two_hop_statement']
who are the developers?	'Alejandra', 'Stephine', 'Emmie'	['question_type_global', 'question_single_statement']
What projects are [corporate]?	'mobile'	['question_type_global', 'question_single_statement']
Are there any [task]s that are not resolved?	'issue in using training data', 'two consecutive dates identified as single date'	['question_type_global', 'question_two_hop_statement']
Who is currently working on the [experimental] projects?	'Alejandra', 'Stephine', 'Angelita', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
Are there any people assigned to projects in the [testing] stage?	'Alejandra', 'Stephine', 'Angelita', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
Who is [the issue in using training data task] assigned to?	'Stephine'	['question_type_local']
What are the issues that were resolved?	'saving data throws exception', 'xml extractor exception', 'dcoref always returns null', 'fails with apache stack', 'changelong needs to be added', 'versioning needs to be made consistent', 'issue in using training data', 'two consecutive dates identified as single date', 'minified version fails'	['question_type_global', 'question_single_statement']
[Alejandra] is not working on [mobile project] anymore
[Alejandra] is working on [mobile project] also
[that developer] is no longer assigned to [knowledge base project]
[this developer] is working on [knowledge base project] also
[that project] is in the [implementation] stage
What projects is [Luanna] working on?	'mobile'	['question_type_local']
What are the issues that are resolved for [experimental] projects?	'saving data throws exception', 'fails with apache stack'	['question_type_global', 'question_two_hop_statement']
Are there any people assigned to the [experimental] projects?	'Alejandra', 'Stephine', 'Angelita', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
Who created [the changelong needs to be added issue]?	'Britney'	['question_type_local']
Are there any people assigned to projects in the [implementation] stage?	'Alejandra', 'Stephine', 'Luanna', 'Angelita', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
Who submitted [the enhancement that was last added]?	'Luanna'	['question_type_local']
who are the testers?	'Luanna', 'Angelita', 'Britney'	['question_type_global', 'question_single_statement']
Are there any issues that are resolved?	'saving data throws exception', 'xml extractor exception', 'dcoref always returns null', 'fails with apache stack', 'changelong needs to be added', 'versioning needs to be made consistent', 'issue in using training data', 'two consecutive dates identified as single date', 'minified version fails'	['question_type_global', 'question_single_statement']
[mobile project] is not assigned to [Stephine]
Who submitted [the versioning needs to be made consistent issue]?	'Angelita'	['question_type_local']
Which developers have issues assigned to them that were all resolved?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
[that developer] is not working on [chatbot project] anymore
[Stephine] is working on [this project] also
[mobile project] is assigned to [this person] also
Who has issues assigned to them that were all resolved?	'Alejandra', 'Stephine', 'Angelita', 'Britney'	['question_type_global', 'question_two_hop_statement']
What projects are [personal]?	'chatbot'	['question_type_global', 'question_single_statement']
Are there any developers assigned to the [personal] projects?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
What are the resolved issues for [experimental] projects?	'saving data throws exception', 'fails with apache stack'	['question_type_global', 'question_two_hop_statement']
Who are the developers currently working on the [experimental] projects?	'Alejandra', 'Stephine', 'Emmie'	['question_type_global', 'question_three_hop_statement']
Were there any issues submitted by [Angelita]?	'versioning needs to be made consistent'	['question_type_local']
What are the non resolved [proposal]s?	'dcoref always returns null', 'fails with apache stack'	['question_type_global', 'question_two_hop_statement']
Who are the testers currently working on the [personal] projects?	'Angelita', 'Britney'	['question_type_global', 'question_three_hop_statement']
What developers are assigned to the [personal] projects?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
Are there any developers assigned to the [corporate] projects?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
[this project] is in the [testing] stage
[knowledge base project] is now in the [maintenance] stage
What projects is [Britney] working on?	'knowledge base', 'chatbot', 'mobile'	['question_type_local']
Are there any testers assigned to projects in the [maintenance] stage?	'Angelita', 'Britney'	['question_type_global', 'question_three_hop_statement']
Are there projects in the [testing] stage?	'mobile'	['question_type_global', 'question_single_statement']
[knowledge base project] is now in the [implementation] stage
[this project] has moved to the [testing] stage
Which is the stage of [mobile project]?	'testing'	['question_type_local']
Which developers have issues assigned to them that were all resolved?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
Are there any issues that are resolved for [experimental] projects?	'saving data throws exception', 'fails with apache stack'	['question_type_global', 'question_two_hop_statement']
Who is [the versioning needs to be made consistent issue] assigned to?	'Britney'	['question_type_local']
What developers are assigned to the [personal] projects?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
who are the developers?	'Alejandra', 'Stephine', 'Emmie'	['question_type_global', 'question_single_statement']
[Luanna] is working on [knowledge base project] also
[chatbot project] is assigned to [this tester] also
What projects are in the [testing] stage?	'knowledge base', 'mobile'	['question_type_global', 'question_single_statement']
Who is assigned to the [corporate] projects?	'Alejandra', 'Stephine', 'Luanna', 'Angelita', 'Britney'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are resolved for [corporate] projects?	'minified version fails'	['question_type_global', 'question_two_hop_statement']
Were there any issues assigned to [Britney]?	'versioning needs to be made consistent'	['question_type_local']
What are the non resolved [task]s?	'issue in using training data', 'two consecutive dates identified as single date'	['question_type_global', 'question_two_hop_statement']
Who submitted [the changelong needs to be added issue]?	'Britney'	['question_type_local']
What developers are assigned to the [experimental] projects?	'Alejandra', 'Stephine', 'Emmie'	['question_type_global', 'question_three_hop_statement']
Who are the developers currently working on the [corporate] projects?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
who are the developers?	'Alejandra', 'Stephine', 'Emmie'	['question_type_global', 'question_single_statement']
What are the [corporate] projects?	'mobile'	['question_type_global', 'question_single_statement']
Who was [the proposal that was last added] assigned to?	'Alejandra'	['question_type_local']
Are there any issues for [mobile project] that are resolved?	'minified version fails'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are resolved?	'saving data throws exception', 'xml extractor exception', 'dcoref always returns null', 'fails with apache stack', 'changelong needs to be added', 'versioning needs to be made consistent', 'issue in using training data', 'two consecutive dates identified as single date', 'minified version fails'	['question_type_global', 'question_single_statement']
Are there any people assigned to projects in the [maintenance] stage?	'Alejandra', 'Stephine', 'Luanna', 'Angelita', 'Britney'	['question_type_global', 'question_two_hop_statement']
What are the issues assigned to [Angelita]?	'saving data throws exception', 'changelong needs to be added'	['question_type_local']
Are there any developers assigned to the [corporate] projects?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
Who has issues assigned to them that were all resolved?	'Alejandra', 'Stephine', 'Angelita', 'Britney'	['question_type_global', 'question_two_hop_statement']
[this tester] is no longer assigned to [chatbot project]
[chatbot project] is assigned to [Luanna] also
[that person] is no longer assigned to [mobile project]
Who are the developers on [chatbot project]	'Alejandra', 'Stephine'	['question_type_local']
Who is assigned to the [corporate] projects?	'Alejandra', 'Stephine', 'Angelita', 'Britney'	['question_type_global', 'question_two_hop_statement']
who are the developers?	'Alejandra', 'Stephine', 'Emmie'	['question_type_global', 'question_single_statement']
What are the issues that are resolved for projects in the [testing] stage?	'saving data throws exception', 'fails with apache stack', 'minified version fails'	['question_type_global', 'question_three_hop_statement']
What developers are assigned to the [experimental] projects?	'Alejandra', 'Stephine', 'Emmie'	['question_type_global', 'question_three_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
who are the testers?	'Luanna', 'Angelita', 'Britney'	['question_type_global', 'question_single_statement']
Who has issues assigned to them that were all resolved?	'Alejandra', 'Stephine', 'Angelita', 'Britney'	['question_type_global', 'question_two_hop_statement']
[that project] is in the stage of [implementation]
[this project] has moved to the [testing] stage
Are there any developers assigned to the [personal] projects?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
Who are the developers on [knowledge base project]	'Alejandra', 'Stephine', 'Emmie'	['question_type_local']
Were there any issues submitted by [Luanna]?	'minified version fails'	['question_type_local']
who are the developers?	'Alejandra', 'Stephine', 'Emmie'	['question_type_global', 'question_single_statement']
What projects are currently in the [testing] stage?	'knowledge base', 'mobile'	['question_type_global', 'question_single_statement']
Are there any issues that are resolved for projects in the [testing] stage?	'saving data throws exception', 'fails with apache stack', 'minified version fails'	['question_type_global', 'question_three_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
who are the testers?	'Luanna', 'Angelita', 'Britney'	['question_type_global', 'question_single_statement']
Which testers have issues assigned to them that were all resolved?	'Angelita', 'Britney'	['question_type_global', 'question_three_hop_statement']
[that project] is in the [maintenance] stage
Who submitted [the versioning needs to be made consistent issue]?	'Angelita'	['question_type_local']
What are the resolved issues for projects in the [maintenance] stage?	'xml extractor exception', 'dcoref always returns null', 'changelong needs to be added', 'versioning needs to be made consistent', 'issue in using training data', 'two consecutive dates identified as single date', 'minified version fails'	['question_type_global', 'question_three_hop_statement']
Who are the testers currently working on the [corporate] projects?	'Angelita', 'Britney'	['question_type_global', 'question_three_hop_statement']
Who has issues assigned to them that were all resolved?	'Alejandra', 'Stephine', 'Angelita', 'Britney'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are resolved?	'saving data throws exception', 'xml extractor exception', 'dcoref always returns null', 'fails with apache stack', 'changelong needs to be added', 'versioning needs to be made consistent', 'issue in using training data', 'two consecutive dates identified as single date', 'minified version fails'	['question_type_global', 'question_single_statement']
What developers are assigned to the [personal] projects?	'Alejandra', 'Stephine'	['question_type_global', 'question_three_hop_statement']
[Britney] is not working on [chatbot project] anymore
