there is a new [chatbot] [project]
[it] is in the [implementation] stage
[it] is a [important] project
[memory leak bug] is a new issue for the [this project]
[John] is a [developer] on [chatbot project]
[that issue] is assigned to [this person]
[chatbot project] is in the [design] stage
[that person] created a new issue for [that project]: [versioning needs to be made consistent]
[the issue] was assigned to [John]
[that person] resolved [that issue]
[Gabrielle] is a [tester] on [chatbot project]
[John] resolved [the memory leak bug issue]
[two consecutive dates identified as single date] is a new [enhancement] for [chatbot project] that [Gabrielle] just created
What are the issues that are not resolved for projects in the [design] stage?	'two consecutive dates identified as single date'	['question_type_global', 'question_three_hop_statement']
What projects are in the [design] stage?	'chatbot'	['question_type_global', 'question_single_statement']
Who are the developers currently working on the [important] projects?	'John'	['question_type_global', 'question_three_hop_statement']
Who submitted [the versioning needs to be made consistent issue]?	'John'	['question_type_local']
What are the issues that are not resolved for [important] projects?	'two consecutive dates identified as single date'	['question_type_global', 'question_two_hop_statement']
[chatbot project] is in the [implementation] stage
Which testers are working on [chatbot project]?	'Gabrielle'	['question_type_local']
who are the developers?	'John'	['question_type_global', 'question_single_statement']
who are the testers?	'Gabrielle'	['question_type_global', 'question_single_statement']
there is a new [mobile] [project]
[mobile project] is in the stage of [design]
[Jack] is a [tester]
[he] is working on [chatbot project]
What testers are assigned to projects in the [implementation] stage?	'Gabrielle', 'Jack'	['question_type_global', 'question_three_hop_statement']
[that test engineer] created a new issue for [it]: [parsing with parantheses fails]
[this issue] is assigned to [Jack]
[Angelita] is a [developer] on [chatbot project]
[she] is assigned to [mobile project] also
[this project] is a [external] project
[it] is in the [maintenance] stage
Are there any issues created by [Gabrielle] that are not resolved?	'two consecutive dates identified as single date'	['question_type_local']
Who are the developers currently working on the [external] projects?	'Angelita'	['question_type_global', 'question_three_hop_statement']
Are there any people assigned to projects in the [maintenance] stage?	'Angelita'	['question_type_global', 'question_two_hop_statement']
What projects are currently in the [implementation] stage?	'chatbot'	['question_type_global', 'question_single_statement']
[Danita] is a [developer] on [chatbot project]
[mobile project] is assigned to [Danita] also
Who is currently working on projects in the [maintenance] stage?	'Angelita', 'Danita'	['question_type_global', 'question_two_hop_statement']
Who has issues assigned to them that were all resolved?	'John'	['question_type_global', 'question_two_hop_statement']
there is a new [open source] [knowledge base] [project]
[knowledge base project] is in the stage of [design]
[Rachele] is a [tester] on [chatbot project]
[xml extractor exception] is a new issue for the [it]
[this tester] is working on [mobile project] also
[mobile project] has moved to the [design] stage
[Danita] is working on [knowledge base project] also
[Gabrielle] is assigned to [this project] also
[that project] has moved to the [implementation] stage
[Marisela] is a [tester] on [chatbot project]
[knowledge base project] is assigned to [this tester] also
There is a new issue for the [mobile project]: [issue in using training data]
[this issue] was assigned to [Angelita]
[she] resolved [this issue]
[John] is working on [knowledge base project] also
[that developer] is assigned to [mobile project] also
What are the issues created by [John]?	'versioning needs to be made consistent'	['question_type_local']
What are the non resolved issues for projects in the [implementation] stage?	'two consecutive dates identified as single date', 'parsing with parantheses fails', 'xml extractor exception'	['question_type_global', 'question_three_hop_statement']
What are the issues for [chatbot project] that are not resolved?	'two consecutive dates identified as single date', 'parsing with parantheses fails'	['question_type_global', 'question_two_hop_statement']
What developers are assigned to projects in the [design] stage?	'John', 'Angelita', 'Danita'	['question_type_global', 'question_three_hop_statement']
[this project] is assigned to [Jack] also
[knowledge base project] is assigned to [that person] also
Are there any [enhancement]s that are not resolved?	'two consecutive dates identified as single date'	['question_type_global', 'question_two_hop_statement']
who are the developers?	'John', 'Angelita', 'Danita'	['question_type_global', 'question_single_statement']
What testers are assigned to projects in the [design] stage?	'Jack', 'Rachele'	['question_type_global', 'question_three_hop_statement']
Who has issues assigned to them that were all resolved?	'John', 'Angelita'	['question_type_global', 'question_two_hop_statement']
What developers are assigned to the [external] projects?	'John', 'Angelita', 'Danita'	['question_type_global', 'question_three_hop_statement']
[that project] is assigned to [Angelita] also
[mobile project] is in the [maintenance] stage
[the enhancement] was assigned to [John]
Who is working on [mobile project]?	'John', 'Jack', 'Angelita', 'Danita', 'Rachele'	['question_type_local']
[the xml extractor exception issue] is assigned to [Jack]
[that test engineer] resolved [it]
Who created [the parsing with parantheses fails issue]?	'Jack'	['question_type_local']
Are there any developers assigned to the [important] projects?	'John', 'Angelita', 'Danita'	['question_type_global', 'question_three_hop_statement']
What testers are assigned to projects in the [implementation] stage?	'Gabrielle', 'Jack', 'Rachele', 'Marisela'	['question_type_global', 'question_three_hop_statement']
Who is [the issue in using training data issue] assigned to?	'Angelita'	['question_type_local']
who are the developers?	'John', 'Angelita', 'Danita'	['question_type_global', 'question_single_statement']
Which testers have issues assigned to them that were all resolved?	'Jack'	['question_type_global', 'question_three_hop_statement']
[knowledge base project] is assigned to [Rachele] also
Who are the testers on [chatbot project]	'Gabrielle', 'Jack', 'Rachele', 'Marisela'	['question_type_local']
Are there any issues that are resolved for projects in the [implementation] stage?	'memory leak bug', 'versioning needs to be made consistent', 'xml extractor exception'	['question_type_global', 'question_three_hop_statement']
Are there any developers assigned to the [open source] projects?	'John', 'Angelita', 'Danita'	['question_type_global', 'question_three_hop_statement']
What are the [important] projects?	'chatbot'	['question_type_global', 'question_single_statement']
Which developers have issues assigned to them that were all resolved?	'John', 'Angelita'	['question_type_global', 'question_three_hop_statement']
What testers are assigned to projects in the [implementation] stage?	'Gabrielle', 'Jack', 'Rachele', 'Marisela'	['question_type_global', 'question_three_hop_statement']
Who created [the two consecutive dates identified as single date enhancement]?	'Gabrielle'	['question_type_local']
Who are the testers currently working on the [important] projects?	'Gabrielle', 'Jack', 'Rachele', 'Marisela'	['question_type_global', 'question_three_hop_statement']
Who has issues assigned to them that were not resolved?	'John', 'Jack'	['question_type_global', 'question_two_hop_statement']
Who is [the xml extractor exception issue] assigned to?	'Jack'	['question_type_local']
What are the issues that are not resolved for [important] projects?	'two consecutive dates identified as single date', 'parsing with parantheses fails'	['question_type_global', 'question_two_hop_statement']
Were there any issues created by [John]?	'versioning needs to be made consistent'	['question_type_local']
who are the developers?	'John', 'Angelita', 'Danita'	['question_type_global', 'question_single_statement']
Which testers have issues assigned to them that were all resolved?	'Jack'	['question_type_global', 'question_three_hop_statement']
[mobile project] is not assigned to [this tester]
[knowledge base project] is in the [maintenance] stage
which testers are assigned to [chatbot project]	'Gabrielle', 'Jack', 'Rachele', 'Marisela'	['question_type_local']
who are the testers?	'Gabrielle', 'Jack', 'Rachele', 'Marisela'	['question_type_global', 'question_single_statement']
Are there any people assigned to the [external] projects?	'John', 'Jack', 'Angelita', 'Danita'	['question_type_global', 'question_two_hop_statement']
What are the issues that were resolved?	'memory leak bug', 'versioning needs to be made consistent', 'xml extractor exception', 'issue in using training data'	['question_type_global', 'question_single_statement']
[Marisela] created a new [task] for [chatbot project]: [minified version fails]
[the minified version fails issue] was assigned to [John]
[this person] resolved [the issue]
Who are the testers on [chatbot project]	'Gabrielle', 'Jack', 'Rachele', 'Marisela'	['question_type_local']
What projects are [important]?	'chatbot'	['question_type_global', 'question_single_statement']
Which testers have issues assigned to them that were not resolved?	'Jack'	['question_type_global', 'question_three_hop_statement']
Who has issues assigned to them that were not resolved?	'John', 'Jack'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are resolved for [open source] projects?	'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are resolved?	'memory leak bug', 'versioning needs to be made consistent', 'xml extractor exception', 'issue in using training data', 'minified version fails'	['question_type_global', 'question_single_statement']
What stage is [knowledge base project] in?	'maintenance'	['question_type_local']
who are the testers?	'Gabrielle', 'Jack', 'Rachele', 'Marisela'	['question_type_global', 'question_single_statement']
Are there any testers assigned to the [external] projects?	'Jack'	['question_type_global', 'question_three_hop_statement']
What are the issues that are not resolved?	'two consecutive dates identified as single date', 'parsing with parantheses fails'	['question_type_global', 'question_single_statement']
[Jack] created a new issue for [mobile project]: [parse example terribly slow]
[that issue] was assigned to [Angelita]
[this developer] resolved [it]
Who created [the two consecutive dates identified as single date issue]?	'Gabrielle'	['question_type_local']
What are the issues for [mobile project] that are resolved?	'issue in using training data', 'parse example terribly slow'	['question_type_global', 'question_two_hop_statement']
Which developers have issues assigned to them that were all resolved?	'John', 'Angelita'	['question_type_global', 'question_three_hop_statement']
Who has issues assigned to them that were not resolved?	'John', 'Jack'	['question_type_global', 'question_two_hop_statement']
Who has issues assigned to them that were all resolved?	'John', 'Jack', 'Angelita'	['question_type_global', 'question_two_hop_statement']
Which developers have issues assigned to them that were not resolved?	'John'	['question_type_global', 'question_three_hop_statement']
What projects are [open source]?	'knowledge base'	['question_type_global', 'question_single_statement']
[mobile project] is not assigned to [Angelita]
[knowledge base project] is in the [design] stage
Who is working on [chatbot project]?	'John', 'Gabrielle', 'Jack', 'Angelita', 'Danita', 'Rachele', 'Marisela'	['question_type_local']
What projects are [important]?	'chatbot'	['question_type_global', 'question_single_statement']
What projects are currently in the [design] stage?	'knowledge base'	['question_type_global', 'question_single_statement']
What testers are assigned to projects in the [implementation] stage?	'Gabrielle', 'Jack', 'Rachele', 'Marisela'	['question_type_global', 'question_three_hop_statement']
Who are the testers currently working on the [important] projects?	'Gabrielle', 'Jack', 'Rachele', 'Marisela'	['question_type_global', 'question_three_hop_statement']
[Gabrielle] created a new [enhancement] for [chatbot project]: [wrong pos tag on consecutive words]
[that issue] was assigned to [Jack]
[this person] resolved [the wrong pos tag on consecutive words enhancement]
Who was [the memory leak bug issue] assigned to?	'John'	['question_type_local']
Are there any [enhancement]s that are not resolved?	'wrong pos tag on consecutive words'	['question_type_global', 'question_two_hop_statement']
Which developers have issues assigned to them that were not resolved?	'John'	['question_type_global', 'question_three_hop_statement']
Are there any issues that are resolved for projects in the [design] stage?	'xml extractor exception'	['question_type_global', 'question_three_hop_statement']
What are the resolved issues for [chatbot project]?	'memory leak bug', 'versioning needs to be made consistent', 'minified version fails', 'wrong pos tag on consecutive words'	['question_type_global', 'question_two_hop_statement']
[knowledge base project] is not assigned to [he]
What projects is [Danita] working on?	'chatbot', 'mobile', 'knowledge base'	['question_type_local']
[knowledge base project] is assigned to [Jack] also
Who is working on [chatbot project]?	'John', 'Gabrielle', 'Jack', 'Angelita', 'Danita', 'Rachele', 'Marisela'	['question_type_local']
Who is currently working on projects in the [design] stage?	'John', 'Gabrielle', 'Jack', 'Angelita', 'Danita', 'Rachele', 'Marisela'	['question_type_global', 'question_two_hop_statement']
who are the testers?	'Gabrielle', 'Jack', 'Rachele', 'Marisela'	['question_type_global', 'question_single_statement']
What are the issues that were resolved?	'memory leak bug', 'versioning needs to be made consistent', 'xml extractor exception', 'issue in using training data', 'minified version fails', 'parse example terribly slow', 'wrong pos tag on consecutive words'	['question_type_global', 'question_single_statement']
Who is currently working on the [open source] projects?	'John', 'Gabrielle', 'Jack', 'Angelita', 'Danita', 'Rachele', 'Marisela'	['question_type_global', 'question_two_hop_statement']
[chatbot project] is not assigned to [this person]
[this tester] is assigned to [chatbot project] also
Which testers are working on [knowledge base project]?	'Gabrielle', 'Jack', 'Rachele', 'Marisela'	['question_type_local']
What are the [open source] projects?	'knowledge base'	['question_type_global', 'question_single_statement']
Which developers have issues assigned to them that were all resolved?	'John', 'Angelita'	['question_type_global', 'question_three_hop_statement']
What are the issues that are resolved for projects in the [design] stage?	'xml extractor exception'	['question_type_global', 'question_three_hop_statement']
What are the [external] projects?	'mobile'	['question_type_global', 'question_single_statement']
Are there any issues for [chatbot project] that are not resolved?	'two consecutive dates identified as single date', 'parsing with parantheses fails'	['question_type_global', 'question_two_hop_statement']
[memory leak while reading tf records] is a new [bug] for [chatbot project] that [Marisela] just created
[the issue] was assigned to [Gabrielle]
[mobile project] is assigned to [Angelita] also
What projects is [Rachele] working on?	'chatbot', 'knowledge base'	['question_type_local']
who are the developers?	'John', 'Angelita', 'Danita'	['question_type_global', 'question_single_statement']
[Gabrielle] resolved [the bug]
[she] is working on [mobile project] also
What stage is [this project] in?	'maintenance'	['question_type_local']
Are there any issues that are not resolved for projects in the [implementation] stage?	'two consecutive dates identified as single date', 'parsing with parantheses fails'	['question_type_global', 'question_three_hop_statement']
Are there any issues for [knowledge base project] that are resolved?	'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
Are there any [task]s that are not resolved?	'minified version fails'	['question_type_global', 'question_two_hop_statement']
What are the issues created by [John]?	'versioning needs to be made consistent'	['question_type_local']
What are the issues that are resolved for [important] projects?	'memory leak bug', 'versioning needs to be made consistent', 'minified version fails', 'wrong pos tag on consecutive words', 'memory leak while reading tf records'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are resolved?	'memory leak bug', 'versioning needs to be made consistent', 'xml extractor exception', 'issue in using training data', 'minified version fails', 'parse example terribly slow', 'wrong pos tag on consecutive words', 'memory leak while reading tf records'	['question_type_global', 'question_single_statement']
Are there any testers assigned to projects in the [design] stage?	'Gabrielle', 'Jack', 'Rachele', 'Marisela'	['question_type_global', 'question_three_hop_statement']
[mobile project] is in the stage of [design]
Who submitted [the two consecutive dates identified as single date issue]?	'Gabrielle'	['question_type_local']
Who has issues assigned to them that were not resolved?	'John', 'Jack'	['question_type_global', 'question_two_hop_statement']
Which testers have issues assigned to them that were not resolved?	'Jack'	['question_type_global', 'question_three_hop_statement']
Are there any people assigned to the [important] projects?	'John', 'Gabrielle', 'Jack', 'Angelita', 'Danita', 'Rachele', 'Marisela'	['question_type_global', 'question_two_hop_statement']
Which developers have issues assigned to them that were all resolved?	'John', 'Angelita'	['question_type_global', 'question_three_hop_statement']
[it] is now in the [implementation] stage
[chatbot project] is now in the [design] stage
What are the issues submitted by [Jack]?	'parsing with parantheses fails', 'parse example terribly slow'	['question_type_local']
What testers are assigned to projects in the [design] stage?	'Gabrielle', 'Jack', 'Rachele', 'Marisela'	['question_type_global', 'question_three_hop_statement']
Who are the testers currently working on the [open source] projects?	'Gabrielle', 'Jack', 'Rachele', 'Marisela'	['question_type_global', 'question_three_hop_statement']
What projects are [important]?	'chatbot'	['question_type_global', 'question_single_statement']
Who was [the wrong pos tag on consecutive words enhancement] assigned to?	'Jack'	['question_type_local']
What are the issues for [chatbot project] that are resolved?	'memory leak bug', 'versioning needs to be made consistent', 'minified version fails', 'wrong pos tag on consecutive words', 'memory leak while reading tf records'	['question_type_global', 'question_two_hop_statement']
What are the non resolved issues for projects in the [design] stage?	'two consecutive dates identified as single date', 'parsing with parantheses fails'	['question_type_global', 'question_three_hop_statement']
Who has issues assigned to them that were all resolved?	'John', 'Gabrielle', 'Jack', 'Angelita'	['question_type_global', 'question_two_hop_statement']
Who is assigned to the [external] projects?	'John', 'Gabrielle', 'Jack', 'Angelita', 'Danita'	['question_type_global', 'question_two_hop_statement']
[mobile project] is assigned to [Rachele] also
Who was [the parse example terribly slow issue] assigned to?	'Angelita'	['question_type_local']
What are the resolved issues for projects in the [implementation] stage?	'issue in using training data', 'parse example terribly slow'	['question_type_global', 'question_three_hop_statement']
who are the developers?	'John', 'Angelita', 'Danita'	['question_type_global', 'question_single_statement']
Which testers are working on [knowledge base project]?	'Gabrielle', 'Jack', 'Rachele', 'Marisela'	['question_type_local']
Are there any issues that are resolved for [open source] projects?	'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
Who was [the parsing with parantheses fails issue] assigned to?	'Jack'	['question_type_local']
Which testers have issues assigned to them that were all resolved?	'Gabrielle', 'Jack'	['question_type_global', 'question_three_hop_statement']
Are there any issues that are resolved for [external] projects?	'issue in using training data', 'parse example terribly slow'	['question_type_global', 'question_two_hop_statement']
What are the [external] projects?	'mobile'	['question_type_global', 'question_single_statement']
[she] is not working on [chatbot project] anymore
[that test engineer] is assigned to [it] also
Are there any issues that are resolved for projects in the [design] stage?	'memory leak bug', 'versioning needs to be made consistent', 'xml extractor exception', 'minified version fails', 'wrong pos tag on consecutive words', 'memory leak while reading tf records'	['question_type_global', 'question_three_hop_statement']
[mobile project] is not assigned to [John]
[it] is assigned to [he] also
[it] has moved to the [maintenance] stage
Who is [the memory leak bug issue] assigned to?	'John'	['question_type_local']
What are the resolved issues?	'memory leak bug', 'versioning needs to be made consistent', 'xml extractor exception', 'issue in using training data', 'minified version fails', 'parse example terribly slow', 'wrong pos tag on consecutive words', 'memory leak while reading tf records'	['question_type_global', 'question_single_statement']
What are the issues assigned to [John]?	'memory leak bug', 'versioning needs to be made consistent', 'two consecutive dates identified as single date', 'minified version fails'	['question_type_local']
What are the issues that were resolved?	'memory leak bug', 'versioning needs to be made consistent', 'xml extractor exception', 'issue in using training data', 'minified version fails', 'parse example terribly slow', 'wrong pos tag on consecutive words', 'memory leak while reading tf records'	['question_type_global', 'question_single_statement']
What projects are currently in the [design] stage?	'chatbot', 'knowledge base'	['question_type_global', 'question_single_statement']
Are there any issues that are not resolved for projects in the [design] stage?	'two consecutive dates identified as single date', 'parsing with parantheses fails'	['question_type_global', 'question_three_hop_statement']
[it] is in the stage of [implementation]
Which developers are working on [knowledge base project]?	'John', 'Angelita', 'Danita'	['question_type_local']
Who are the testers currently working on the [important] projects?	'Gabrielle', 'Jack', 'Rachele', 'Marisela'	['question_type_global', 'question_three_hop_statement']
Who has issues assigned to them that were not resolved?	'John', 'Jack'	['question_type_global', 'question_two_hop_statement']
Who is assigned to the [important] projects?	'John', 'Gabrielle', 'Jack', 'Angelita', 'Danita', 'Rachele', 'Marisela'	['question_type_global', 'question_two_hop_statement']
Who is currently working on the [external] projects?	'John', 'Gabrielle', 'Jack', 'Angelita', 'Danita', 'Rachele'	['question_type_global', 'question_two_hop_statement']
[chatbot project] is now in the [maintenance] stage
Are there any issues submitted by [Gabrielle] that are not resolved?	'two consecutive dates identified as single date'	['question_type_local']
What are the non resolved issues for [important] projects?	'two consecutive dates identified as single date', 'parsing with parantheses fails'	['question_type_global', 'question_two_hop_statement']
[knowledge base project] is in the stage of [maintenance]
What are the issues that were resolved?	'memory leak bug', 'versioning needs to be made consistent', 'xml extractor exception', 'issue in using training data', 'minified version fails', 'parse example terribly slow', 'wrong pos tag on consecutive words', 'memory leak while reading tf records'	['question_type_global', 'question_single_statement']
Which testers have issues assigned to them that were not resolved?	'Jack'	['question_type_global', 'question_three_hop_statement']
Which developers are assigned to [chatbot project]	'John', 'Angelita', 'Danita'	['question_type_local']
What testers are assigned to projects in the [implementation] stage?	'Gabrielle', 'Jack', 'Rachele'	['question_type_global', 'question_three_hop_statement']
What are the resolved issues for projects in the [maintenance] stage?	'memory leak bug', 'versioning needs to be made consistent', 'xml extractor exception', 'minified version fails', 'wrong pos tag on consecutive words', 'memory leak while reading tf records'	['question_type_global', 'question_three_hop_statement']
What are the non resolved issues?	'two consecutive dates identified as single date', 'parsing with parantheses fails'	['question_type_global', 'question_single_statement']
Who are the testers currently working on the [important] projects?	'Gabrielle', 'Jack', 'Rachele', 'Marisela'	['question_type_global', 'question_three_hop_statement']
Are there any issues that are not resolved?	'two consecutive dates identified as single date', 'parsing with parantheses fails'	['question_type_global', 'question_single_statement']
who are the developers?	'John', 'Angelita', 'Danita'	['question_type_global', 'question_single_statement']
[mobile project] is not assigned to [Gabrielle]
What are the issues assigned to [Jack] that were resolved?	'xml extractor exception', 'wrong pos tag on consecutive words'	['question_type_local']
Which testers have issues assigned to them that were not resolved?	'Jack'	['question_type_global', 'question_three_hop_statement']
[that person] is working on [this project] also
What are the issues assigned to [John] that were not resolved?	'two consecutive dates identified as single date'	['question_type_local']
Are there any testers assigned to projects in the [implementation] stage?	'Gabrielle', 'Jack', 'Rachele'	['question_type_global', 'question_three_hop_statement']
who are the testers?	'Gabrielle', 'Jack', 'Rachele', 'Marisela'	['question_type_global', 'question_single_statement']
[it] is not assigned to [Gabrielle]
[this tester] is working on [this project] also
Which testers have issues assigned to them that were all resolved?	'Gabrielle', 'Jack'	['question_type_global', 'question_three_hop_statement']
Who is [the xml extractor exception issue] assigned to?	'Jack'	['question_type_local']
Who are the developers currently working on projects in the [maintenance] stage?	'John', 'Angelita', 'Danita'	['question_type_global', 'question_three_hop_statement']
Who has issues assigned to them that were not resolved?	'John', 'Jack'	['question_type_global', 'question_two_hop_statement']
What developers are assigned to the [external] projects?	'John', 'Angelita', 'Danita'	['question_type_global', 'question_three_hop_statement']
Who is [the issue in using training data issue] assigned to?	'Angelita'	['question_type_local']
who are the testers?	'Gabrielle', 'Jack', 'Rachele', 'Marisela'	['question_type_global', 'question_single_statement']
Who has issues assigned to them that were all resolved?	'John', 'Gabrielle', 'Jack', 'Angelita'	['question_type_global', 'question_two_hop_statement']
[this test engineer] is not working on [knowledge base project] anymore
Which developers have issues assigned to them that were not resolved?	'John'	['question_type_global', 'question_three_hop_statement']
What testers are assigned to projects in the [maintenance] stage?	'Gabrielle', 'Jack', 'Rachele', 'Marisela'	['question_type_global', 'question_three_hop_statement']
[that person] is not working on [chatbot project] anymore
[knowledge base project] is assigned to [this person] also
What projects is [Marisela] working on?	'chatbot', 'knowledge base'	['question_type_local']
What are the [enhancement]s that are not resolved?	'two consecutive dates identified as single date'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are resolved for [external] projects?	'issue in using training data', 'parse example terribly slow'	['question_type_global', 'question_two_hop_statement']
[chatbot project] is assigned to [that person] also
What are the non resolved issues?	'two consecutive dates identified as single date', 'parsing with parantheses fails'	['question_type_global', 'question_single_statement']
What are the issues that are resolved for [open source] projects?	'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
What testers are assigned to the [open source] projects?	'Gabrielle', 'Jack', 'Rachele', 'Marisela'	['question_type_global', 'question_three_hop_statement']
Are there any issues assigned to [Jack] that are not resolved?	'parsing with parantheses fails'	['question_type_local']
What developers are assigned to projects in the [implementation] stage?	'John', 'Angelita', 'Danita'	['question_type_global', 'question_three_hop_statement']
who are the testers?	'Gabrielle', 'Jack', 'Rachele', 'Marisela'	['question_type_global', 'question_single_statement']
Are there any issues that are resolved for [open source] projects?	'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
who are the developers?	'John', 'Angelita', 'Danita'	['question_type_global', 'question_single_statement']
[chatbot project] is now in the [design] stage
Who is [the issue in using training data issue] assigned to?	'Angelita'	['question_type_local']
What testers are assigned to projects in the [implementation] stage?	'Gabrielle', 'Jack', 'Rachele'	['question_type_global', 'question_three_hop_statement']
What testers are assigned to the [external] projects?	'Gabrielle', 'Jack', 'Rachele'	['question_type_global', 'question_three_hop_statement']
What projects is [John] working on?	'chatbot', 'mobile', 'knowledge base'	['question_type_local']
Who has issues assigned to them that were not resolved?	'John', 'Jack'	['question_type_global', 'question_two_hop_statement']
Who are the testers currently working on the [external] projects?	'Gabrielle', 'Jack', 'Rachele'	['question_type_global', 'question_three_hop_statement']
[mobile project] is now in the [maintenance] stage
Who is [the wrong pos tag on consecutive words enhancement] assigned to?	'Jack'	['question_type_local']
Which testers have issues assigned to them that were not resolved?	'Jack'	['question_type_global', 'question_three_hop_statement']
What are the issues that were resolved?	'memory leak bug', 'versioning needs to be made consistent', 'xml extractor exception', 'issue in using training data', 'minified version fails', 'parse example terribly slow', 'wrong pos tag on consecutive words', 'memory leak while reading tf records'	['question_type_global', 'question_single_statement']
Who are the developers currently working on the [external] projects?	'John', 'Angelita', 'Danita'	['question_type_global', 'question_three_hop_statement']
What are the resolved issues?	'memory leak bug', 'versioning needs to be made consistent', 'xml extractor exception', 'issue in using training data', 'minified version fails', 'parse example terribly slow', 'wrong pos tag on consecutive words', 'memory leak while reading tf records'	['question_type_global', 'question_single_statement']
Who is currently working on projects in the [design] stage?	'John', 'Gabrielle', 'Jack', 'Angelita', 'Danita', 'Rachele', 'Marisela'	['question_type_global', 'question_two_hop_statement']
Who was [the issue in using training data issue] assigned to?	'Angelita'	['question_type_local']
Who has issues assigned to them that were all resolved?	'John', 'Gabrielle', 'Jack', 'Angelita'	['question_type_global', 'question_two_hop_statement']
What are the non resolved issues?	'two consecutive dates identified as single date', 'parsing with parantheses fails'	['question_type_global', 'question_single_statement']
Are there any issues for [chatbot project] that are not resolved?	'two consecutive dates identified as single date', 'parsing with parantheses fails'	['question_type_global', 'question_two_hop_statement']
who are the testers?	'Gabrielle', 'Jack', 'Rachele', 'Marisela'	['question_type_global', 'question_single_statement']
Who is [the xml extractor exception issue] assigned to?	'Jack'	['question_type_local']
Who has issues assigned to them that were not resolved?	'John', 'Jack'	['question_type_global', 'question_two_hop_statement']
What testers are assigned to the [external] projects?	'Gabrielle', 'Jack', 'Rachele'	['question_type_global', 'question_three_hop_statement']
Who are the testers currently working on the [open source] projects?	'Gabrielle', 'Jack', 'Rachele', 'Marisela'	['question_type_global', 'question_three_hop_statement']
Which developers have issues assigned to them that were not resolved?	'John'	['question_type_global', 'question_three_hop_statement']
[mobile project] is in the [design] stage
Who was [the xml extractor exception issue] assigned to?	'Jack'	['question_type_local']
What are the non resolved [bug]s?	'memory leak while reading tf records'	['question_type_global', 'question_two_hop_statement']
[that project] is now in the [implementation] stage
[that project] is in the stage of [maintenance]
[that project] is in the stage of [design]
who are the testers?	'Gabrielle', 'Jack', 'Rachele', 'Marisela'	['question_type_global', 'question_single_statement']
[John] resolved [the two consecutive dates identified as single date enhancement]
[knowledge base project] is not assigned to [John]
