there is a new [open source] [knowledge base] [project]
[that project] is in the [deployment] stage
[it] is in the [testing] stage
Which is the stage of [knowledge base project]?	'testing'	['question_type_local']
What stage is [that project] in?	'testing'	['question_type_local']
There is a new issue for the [this project]: [initialization broken]
[knowledge base project] is in the [evaluation] stage
[Francoise] is a [tester]
there is a new [mobile] [project]
[it] is currently in the [development] stage
[this project] is a [experimental] project
[Willis] is a [tester] on [that project]
Are there any issues that are not resolved?	'initialization broken'	['question_type_global', 'question_single_statement']
Who is assigned to projects in the [development] stage?	'Willis'	['question_type_global', 'question_two_hop_statement']
[Angelita] is a [developer] on [knowledge base project]
[that developer] is assigned to [mobile project] also
there is a new [open source] [chatbot] [project]
[chatbot project] is in the stage of [evaluation]
Which is the stage of [mobile project]?	'development'	['question_type_local']
Who are the testers currently working on the [experimental] projects?	'Willis'	['question_type_global', 'question_three_hop_statement']
[tokenization not consistent across platforms] is a new issue for the [it]
[Angelita] is assigned to [chatbot project] also
What are the issues that are not resolved?	'initialization broken', 'tokenization not consistent across platforms'	['question_type_global', 'question_single_statement']
What are the issues that are not resolved for [open source] projects?	'initialization broken', 'tokenization not consistent across platforms'	['question_type_global', 'question_two_hop_statement']
Are there any developers assigned to projects in the [evaluation] stage?	'Angelita'	['question_type_global', 'question_three_hop_statement']
What are the non resolved issues?	'initialization broken', 'tokenization not consistent across platforms'	['question_type_global', 'question_single_statement']
Who is working on [this project]?	'Angelita'	['question_type_local']
Are there any developers assigned to projects in the [development] stage?	'Angelita'	['question_type_global', 'question_three_hop_statement']
who are the testers?	'Francoise', 'Willis'	['question_type_global', 'question_single_statement']
[Emmie] is a [tester]
What testers are assigned to projects in the [development] stage?	'Willis'	['question_type_global', 'question_three_hop_statement']
Who is assigned to projects in the [development] stage?	'Willis', 'Angelita'	['question_type_global', 'question_two_hop_statement']
What projects are currently in the [development] stage?	'mobile'	['question_type_global', 'question_single_statement']
Are there any testers assigned to projects in the [development] stage?	'Willis'	['question_type_global', 'question_three_hop_statement']
Who is currently working on projects in the [evaluation] stage?	'Angelita'	['question_type_global', 'question_two_hop_statement']
[parsing with parantheses fails] is a new [proposal] submitted by [Angelita] for [knowledge base project]
[the parsing with parantheses fails proposal] was assigned to [Angelita]
Which developers are working on [mobile project]?	'Angelita'	['question_type_local']
What are the issues that are not resolved for [open source] projects?	'initialization broken', 'tokenization not consistent across platforms', 'parsing with parantheses fails'	['question_type_global', 'question_two_hop_statement']
Are there projects in the [evaluation] stage?	'knowledge base', 'chatbot'	['question_type_global', 'question_single_statement']
Are there projects in the [development] stage?	'mobile'	['question_type_global', 'question_single_statement']
[she] resolved [the issue]
[Ashly] is a [tester] on [chatbot project]
[Ashly] is working on [mobile project] also
Who are the developers currently working on the [open source] projects?	'Angelita'	['question_type_global', 'question_three_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Angelita'	['question_type_global', 'question_three_hop_statement']
[Alverta] is a [developer]
Are there any projects that are [open source]?	'knowledge base', 'chatbot'	['question_type_global', 'question_single_statement']
Are there any issues for [knowledge base project] that are resolved?	'parsing with parantheses fails'	['question_type_global', 'question_two_hop_statement']
What developers are assigned to the [open source] projects?	'Angelita'	['question_type_global', 'question_three_hop_statement']
Who has issues assigned to them that were all resolved?	'Angelita'	['question_type_global', 'question_two_hop_statement']
[Gabrielle] is a [developer]
[Alverta] is working on [chatbot project]
Which is the stage of [knowledge base project]?	'evaluation'	['question_type_local']
Are there any testers assigned to the [open source] projects?	'Ashly'	['question_type_global', 'question_three_hop_statement']
Are there any people assigned to projects in the [evaluation] stage?	'Angelita', 'Ashly', 'Alverta'	['question_type_global', 'question_two_hop_statement']
What developers are assigned to the [experimental] projects?	'Angelita'	['question_type_global', 'question_three_hop_statement']
Are there any issues that are not resolved for projects in the [evaluation] stage?	'initialization broken', 'tokenization not consistent across platforms'	['question_type_global', 'question_three_hop_statement']
What are the issues that are not resolved?	'initialization broken', 'tokenization not consistent across platforms'	['question_type_global', 'question_single_statement']
[Stephine] is a [developer]
[that person] is assigned to [mobile project]
[she] is no longer assigned to [this project]
[Stephine] is assigned to [chatbot project]
Who created [the parsing with parantheses fails proposal]?	'Angelita'	['question_type_local']
Who has issues assigned to them that were all resolved?	'Angelita'	['question_type_global', 'question_two_hop_statement']
who are the developers?	'Angelita', 'Alverta', 'Gabrielle', 'Stephine'	['question_type_global', 'question_single_statement']
What are the [proposal]s that are not resolved?	'parsing with parantheses fails'	['question_type_global', 'question_two_hop_statement']
[that developer] is assigned to [knowledge base project] also
[Stephine] is working on [mobile project] also
[it] is not assigned to [that person]
[Stephine] is assigned to [mobile project] also
Are there any testers assigned to the [open source] projects?	'Ashly'	['question_type_global', 'question_three_hop_statement']
who are the testers?	'Francoise', 'Willis', 'Emmie', 'Ashly'	['question_type_global', 'question_single_statement']
[this developer] created a new issue for [knowledge base project]: [null pointer exception during parsing]
[the issue] was assigned to [Stephine]
[that developer] resolved [it]
[Alverta] is working on [knowledge base project] also
[this project] is now in the [deployment] stage
Are there any people assigned to projects in the [development] stage?	'Willis', 'Angelita', 'Ashly', 'Stephine'	['question_type_global', 'question_two_hop_statement']
[Alverta] created a new issue for [knowledge base project]: [wrong pos tag on consecutive words]
[this issue] is assigned to [Stephine]
[Willis] is working on [chatbot project] also
Who is working on [it]?	'Willis', 'Angelita', 'Ashly', 'Alverta', 'Stephine'	['question_type_local']
Who are the testers currently working on the [open source] projects?	'Willis', 'Ashly'	['question_type_global', 'question_three_hop_statement']
Who is assigned to projects in the [deployment] stage?	'Angelita', 'Alverta', 'Stephine'	['question_type_global', 'question_two_hop_statement']
who are the developers?	'Angelita', 'Alverta', 'Gabrielle', 'Stephine'	['question_type_global', 'question_single_statement']
Which developers have issues assigned to them that were not resolved?	'Stephine'	['question_type_global', 'question_three_hop_statement']
[Alverta] is working on [mobile project] also
who are the testers?	'Francoise', 'Willis', 'Emmie', 'Ashly'	['question_type_global', 'question_single_statement']
Who created [the parsing with parantheses fails issue]?	'Angelita'	['question_type_local']
Are there any people assigned to the [experimental] projects?	'Willis', 'Angelita', 'Ashly', 'Alverta', 'Stephine'	['question_type_global', 'question_two_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Angelita', 'Stephine'	['question_type_global', 'question_three_hop_statement']
What are the issues that are not resolved for [open source] projects?	'initialization broken', 'tokenization not consistent across platforms', 'wrong pos tag on consecutive words'	['question_type_global', 'question_two_hop_statement']
What projects are currently in the [development] stage?	'mobile'	['question_type_global', 'question_single_statement']
Who has issues assigned to them that were not resolved?	'Stephine'	['question_type_global', 'question_two_hop_statement']
Who has issues assigned to them that were all resolved?	'Angelita', 'Stephine'	['question_type_global', 'question_two_hop_statement']
Are there any testers assigned to the [open source] projects?	'Willis', 'Ashly'	['question_type_global', 'question_three_hop_statement']
What are the non resolved issues for projects in the [deployment] stage?	'initialization broken', 'wrong pos tag on consecutive words'	['question_type_global', 'question_three_hop_statement']
What are the [proposal]s that are not resolved?	'parsing with parantheses fails'	['question_type_global', 'question_two_hop_statement']
[this project] has moved to the [deployment] stage
Are there any issues assigned to [Angelita] that are resolved?	'parsing with parantheses fails'	['question_type_local']
Are there any issues that are not resolved for projects in the [evaluation] stage?	'tokenization not consistent across platforms'	['question_type_global', 'question_three_hop_statement']
Are there any people assigned to projects in the [deployment] stage?	'Willis', 'Angelita', 'Ashly', 'Alverta', 'Stephine'	['question_type_global', 'question_two_hop_statement']
[Francoise] is assigned to [chatbot project]
[this person] is assigned to [mobile project] also
[knowledge base project] is assigned to [he] also
There is a new issue for the [mobile project]: [saving data throws exception]
Who has issues assigned to them that were all resolved?	'Angelita', 'Stephine'	['question_type_global', 'question_two_hop_statement']
Which developers have issues assigned to them that were not resolved?	'Stephine'	['question_type_global', 'question_three_hop_statement']
[fails with apache stack] is a new [bug] submitted by [Willis] for [mobile project]
[the fails with apache stack bug] was assigned to [Francoise]
[this tester] resolved [this issue]
[Ashly] created a new issue for [mobile project]: [issue in using training data]
[timeout problem] is a new issue for the [knowledge base project]
[the issue in using training data issue] was assigned to [Willis]
[Willis] resolved [that issue]
[Stephine] resolved [the wrong pos tag on consecutive words issue]
Were there any issues assigned to [that person]?	'null pointer exception during parsing', 'wrong pos tag on consecutive words'	['question_type_local']
What are the resolved issues for [experimental] projects?	'fails with apache stack', 'issue in using training data'	['question_type_global', 'question_two_hop_statement']
What projects are currently in the [deployment] stage?	'knowledge base', 'mobile'	['question_type_global', 'question_single_statement']
Who is working on [chatbot project]?	'Francoise', 'Willis', 'Angelita', 'Ashly', 'Alverta', 'Stephine'	['question_type_local']
Are there any projects that are [experimental]?	'mobile'	['question_type_global', 'question_single_statement']
Are there any issues for [mobile project] that are not resolved?	'saving data throws exception'	['question_type_global', 'question_two_hop_statement']
What testers are assigned to the [experimental] projects?	'Francoise', 'Willis', 'Ashly'	['question_type_global', 'question_three_hop_statement']
[the initialization broken issue] is assigned to [Francoise]
Who has issues assigned to them that were all resolved?	'Francoise', 'Willis', 'Angelita', 'Stephine'	['question_type_global', 'question_two_hop_statement']
Which testers have issues assigned to them that were all resolved?	'Francoise', 'Willis'	['question_type_global', 'question_three_hop_statement']
[that test engineer] resolved [that issue]
What developers are assigned to projects in the [deployment] stage?	'Angelita', 'Alverta', 'Stephine'	['question_type_global', 'question_three_hop_statement']
What are the issues for [chatbot project] that are not resolved?	'tokenization not consistent across platforms'	['question_type_global', 'question_two_hop_statement']
What projects is [Francoise] working on?	'knowledge base', 'mobile', 'chatbot'	['question_type_local']
Are there any issues for [mobile project] that are resolved?	'fails with apache stack', 'issue in using training data'	['question_type_global', 'question_two_hop_statement']
Are there any testers assigned to projects in the [deployment] stage?	'Francoise', 'Willis', 'Ashly'	['question_type_global', 'question_three_hop_statement']
who are the developers?	'Angelita', 'Alverta', 'Gabrielle', 'Stephine'	['question_type_global', 'question_single_statement']
Which developers have issues assigned to them that were all resolved?	'Angelita', 'Stephine'	['question_type_global', 'question_three_hop_statement']
[Stephine] created a new issue for [chatbot project]: [svd is slow]
[that issue] is assigned to [Alverta]
[that developer] resolved [it]
Who was [the initialization broken issue] assigned to?	'Francoise'	['question_type_local']
Are there any issues that are not resolved for [open source] projects?	'tokenization not consistent across platforms', 'timeout problem'	['question_type_global', 'question_two_hop_statement']
What are the issues that are not resolved?	'tokenization not consistent across platforms', 'saving data throws exception', 'timeout problem'	['question_type_global', 'question_single_statement']
Who is currently working on projects in the [deployment] stage?	'Francoise', 'Willis', 'Angelita', 'Ashly', 'Alverta', 'Stephine'	['question_type_global', 'question_two_hop_statement']
Are there any issues for [chatbot project] that are not resolved?	'tokenization not consistent across platforms'	['question_type_global', 'question_two_hop_statement']
What are the non resolved issues for [mobile project]?	'saving data throws exception'	['question_type_global', 'question_two_hop_statement']
What are the non resolved issues for [experimental] projects?	'saving data throws exception'	['question_type_global', 'question_two_hop_statement']
[Willis] is working on [knowledge base project] also
Are there any issues that are not resolved?	'tokenization not consistent across platforms', 'saving data throws exception', 'timeout problem'	['question_type_global', 'question_single_statement']
What are the non resolved issues for projects in the [deployment] stage?	'saving data throws exception', 'timeout problem'	['question_type_global', 'question_three_hop_statement']
Are there any developers assigned to the [open source] projects?	'Angelita', 'Alverta', 'Stephine'	['question_type_global', 'question_three_hop_statement']
Which developers are assigned to [knowledge base project]	'Angelita', 'Alverta', 'Stephine'	['question_type_local']
Are there any issues for [mobile project] that are not resolved?	'saving data throws exception'	['question_type_global', 'question_two_hop_statement']
who are the developers?	'Angelita', 'Alverta', 'Gabrielle', 'Stephine'	['question_type_global', 'question_single_statement']
Who are the testers currently working on the [open source] projects?	'Francoise', 'Willis', 'Ashly'	['question_type_global', 'question_three_hop_statement']
Are there any projects that are [open source]?	'knowledge base', 'chatbot'	['question_type_global', 'question_single_statement']
Who was [the wrong pos tag on consecutive words issue] assigned to?	'Stephine'	['question_type_local']
Are there any issues that are resolved for [experimental] projects?	'fails with apache stack', 'issue in using training data'	['question_type_global', 'question_two_hop_statement']
Which is the stage of [chatbot project]?	'evaluation'	['question_type_local']
What are the issues that are not resolved for projects in the [evaluation] stage?	'tokenization not consistent across platforms'	['question_type_global', 'question_three_hop_statement']
[it] is now in the [testing] stage
[that project] is now in the [deployment] stage
[Stephine] is not working on [chatbot project] anymore
Who created [the svd is slow issue]?	'Stephine'	['question_type_local']
who are the developers?	'Angelita', 'Alverta', 'Gabrielle', 'Stephine'	['question_type_global', 'question_single_statement']
What are the non resolved [proposal]s?	'parsing with parantheses fails'	['question_type_global', 'question_two_hop_statement']
What projects are [experimental]?	'mobile'	['question_type_global', 'question_single_statement']
Which testers have issues assigned to them that were all resolved?	'Francoise', 'Willis'	['question_type_global', 'question_three_hop_statement']
[Stephine] is assigned to [this project] also
[the timeout problem issue] was assigned to [Francoise]
Are there any issues that are not resolved?	'tokenization not consistent across platforms', 'saving data throws exception', 'timeout problem'	['question_type_global', 'question_single_statement']
Who is currently working on projects in the [evaluation] stage?	'Francoise', 'Willis', 'Angelita', 'Ashly', 'Alverta', 'Stephine'	['question_type_global', 'question_two_hop_statement']
What are the issues that are resolved for projects in the [evaluation] stage?	'svd is slow'	['question_type_global', 'question_three_hop_statement']
[Francoise] resolved [the issue]
[this person] is not working on [knowledge base project] anymore
[knowledge base project] is assigned to [this test engineer] also
Were there any issues assigned to [this person]?	'initialization broken', 'fails with apache stack', 'timeout problem'	['question_type_local']
What are the resolved issues for projects in the [evaluation] stage?	'svd is slow'	['question_type_global', 'question_three_hop_statement']
[knowledge base project] is assigned to [Ashly] also
[this project] is now in the [development] stage
Who created [the fails with apache stack bug]?	'Willis'	['question_type_local']
Who has issues assigned to them that were all resolved?	'Francoise', 'Willis', 'Angelita', 'Alverta', 'Stephine'	['question_type_global', 'question_two_hop_statement']
What are the issues that are resolved for projects in the [development] stage?	'initialization broken', 'parsing with parantheses fails', 'null pointer exception during parsing', 'wrong pos tag on consecutive words', 'timeout problem'	['question_type_global', 'question_three_hop_statement']
[it] is in the [evaluation] stage
Are there any issues created by [Alverta] that are resolved?	'wrong pos tag on consecutive words'	['question_type_local']
What are the resolved issues for projects in the [deployment] stage?	'fails with apache stack', 'issue in using training data'	['question_type_global', 'question_three_hop_statement']
Are there projects in the [evaluation] stage?	'knowledge base', 'chatbot'	['question_type_global', 'question_single_statement']
Who has issues assigned to them that were all resolved?	'Francoise', 'Willis', 'Angelita', 'Alverta', 'Stephine'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are resolved?	'initialization broken', 'parsing with parantheses fails', 'null pointer exception during parsing', 'wrong pos tag on consecutive words', 'fails with apache stack', 'issue in using training data', 'timeout problem', 'svd is slow'	['question_type_global', 'question_single_statement']
Are there any developers assigned to the [open source] projects?	'Angelita', 'Alverta', 'Stephine'	['question_type_global', 'question_three_hop_statement']
What are the resolved issues?	'initialization broken', 'parsing with parantheses fails', 'null pointer exception during parsing', 'wrong pos tag on consecutive words', 'fails with apache stack', 'issue in using training data', 'timeout problem', 'svd is slow'	['question_type_global', 'question_single_statement']
What are the [experimental] projects?	'mobile'	['question_type_global', 'question_single_statement']
Who is currently working on the [open source] projects?	'Francoise', 'Willis', 'Angelita', 'Ashly', 'Alverta', 'Stephine'	['question_type_global', 'question_two_hop_statement']
What developers are assigned to projects in the [deployment] stage?	'Angelita', 'Alverta', 'Stephine'	['question_type_global', 'question_three_hop_statement']
What are the issues that are not resolved?	'tokenization not consistent across platforms', 'saving data throws exception'	['question_type_global', 'question_single_statement']
Are there any issues submitted by [Alverta] that are resolved?	'wrong pos tag on consecutive words'	['question_type_local']
Are there any projects that are [experimental]?	'mobile'	['question_type_global', 'question_single_statement']
who are the testers?	'Francoise', 'Willis', 'Emmie', 'Ashly'	['question_type_global', 'question_single_statement']
Which developers have issues assigned to them that were all resolved?	'Angelita', 'Alverta', 'Stephine'	['question_type_global', 'question_three_hop_statement']
Are there any testers assigned to projects in the [evaluation] stage?	'Francoise', 'Willis', 'Ashly'	['question_type_global', 'question_three_hop_statement']
Who created [the null pointer exception during parsing issue]?	'Stephine'	['question_type_local']
Are there any issues that are not resolved for projects in the [deployment] stage?	'saving data throws exception'	['question_type_global', 'question_three_hop_statement']
Are there any [bug]s that are not resolved?	'fails with apache stack'	['question_type_global', 'question_two_hop_statement']
What are the non resolved issues for [experimental] projects?	'saving data throws exception'	['question_type_global', 'question_two_hop_statement']
[it] is in the [development] stage
Are there any developers assigned to projects in the [development] stage?	'Angelita', 'Alverta', 'Stephine'	['question_type_global', 'question_three_hop_statement']
What are the resolved issues for [open source] projects?	'initialization broken', 'parsing with parantheses fails', 'null pointer exception during parsing', 'wrong pos tag on consecutive words', 'timeout problem', 'svd is slow'	['question_type_global', 'question_two_hop_statement']
What are the issues submitted by [Stephine]?	'null pointer exception during parsing', 'svd is slow'	['question_type_local']
who are the developers?	'Angelita', 'Alverta', 'Gabrielle', 'Stephine'	['question_type_global', 'question_single_statement']
What are the resolved issues?	'initialization broken', 'parsing with parantheses fails', 'null pointer exception during parsing', 'wrong pos tag on consecutive words', 'fails with apache stack', 'issue in using training data', 'timeout problem', 'svd is slow'	['question_type_global', 'question_single_statement']
Are there any issues that are not resolved for projects in the [deployment] stage?	'saving data throws exception'	['question_type_global', 'question_three_hop_statement']
Who submitted [the null pointer exception during parsing issue]?	'Stephine'	['question_type_local']
Who is assigned to the [experimental] projects?	'Francoise', 'Willis', 'Angelita', 'Ashly', 'Alverta', 'Stephine'	['question_type_global', 'question_two_hop_statement']
What are the issues assigned to [Stephine]?	'null pointer exception during parsing', 'wrong pos tag on consecutive words'	['question_type_local']
What are the [experimental] projects?	'mobile'	['question_type_global', 'question_single_statement']
Are there any issues assigned to [Willis] that are resolved?	'issue in using training data'	['question_type_local']
who are the developers?	'Angelita', 'Alverta', 'Gabrielle', 'Stephine'	['question_type_global', 'question_single_statement']
Are there any issues that are resolved?	'initialization broken', 'parsing with parantheses fails', 'null pointer exception during parsing', 'wrong pos tag on consecutive words', 'fails with apache stack', 'issue in using training data', 'timeout problem', 'svd is slow'	['question_type_global', 'question_single_statement']
Which testers have issues assigned to them that were all resolved?	'Francoise', 'Willis'	['question_type_global', 'question_three_hop_statement']
What are the issues that are resolved for projects in the [deployment] stage?	'fails with apache stack', 'issue in using training data'	['question_type_global', 'question_three_hop_statement']
What are the non resolved issues for [mobile project]?	'saving data throws exception'	['question_type_global', 'question_two_hop_statement']
What are the issues for [mobile project] that are not resolved?	'saving data throws exception'	['question_type_global', 'question_two_hop_statement']
What are the issues for [chatbot project] that are not resolved?	'tokenization not consistent across platforms'	['question_type_global', 'question_two_hop_statement']
[that project] has moved to the [deployment] stage
Who is [the wrong pos tag on consecutive words issue] assigned to?	'Stephine'	['question_type_local']
Which developers have issues assigned to them that were all resolved?	'Angelita', 'Alverta', 'Stephine'	['question_type_global', 'question_three_hop_statement']
who are the testers?	'Francoise', 'Willis', 'Emmie', 'Ashly'	['question_type_global', 'question_single_statement']
Are there any issues that are not resolved?	'tokenization not consistent across platforms', 'saving data throws exception'	['question_type_global', 'question_single_statement']
Who are the developers currently working on the [open source] projects?	'Angelita', 'Alverta', 'Stephine'	['question_type_global', 'question_three_hop_statement']
What are the issues that are not resolved for [open source] projects?	'tokenization not consistent across platforms'	['question_type_global', 'question_two_hop_statement']
What stage is [chatbot project] in?	'evaluation'	['question_type_local']
What are the resolved issues for projects in the [deployment] stage?	'initialization broken', 'parsing with parantheses fails', 'null pointer exception during parsing', 'wrong pos tag on consecutive words', 'fails with apache stack', 'issue in using training data', 'timeout problem'	['question_type_global', 'question_three_hop_statement']
What are the issues that are not resolved for projects in the [evaluation] stage?	'tokenization not consistent across platforms'	['question_type_global', 'question_three_hop_statement']
[Francoise] is not working on [knowledge base project] anymore
[Francoise] is assigned to [that project] also
Who is [the svd is slow issue] assigned to?	'Alverta'	['question_type_local']
Are there any issues that are resolved for [open source] projects?	'initialization broken', 'parsing with parantheses fails', 'null pointer exception during parsing', 'wrong pos tag on consecutive words', 'timeout problem', 'svd is slow'	['question_type_global', 'question_two_hop_statement']
Were there any issues assigned to [Willis]?	'issue in using training data'	['question_type_local']
What are the issues that are not resolved for [experimental] projects?	'saving data throws exception'	['question_type_global', 'question_two_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Angelita', 'Alverta', 'Stephine'	['question_type_global', 'question_three_hop_statement']
Are there any testers assigned to the [open source] projects?	'Francoise', 'Willis', 'Ashly'	['question_type_global', 'question_three_hop_statement']
who are the developers?	'Angelita', 'Alverta', 'Gabrielle', 'Stephine'	['question_type_global', 'question_single_statement']
Which testers have issues assigned to them that were all resolved?	'Francoise', 'Willis'	['question_type_global', 'question_three_hop_statement']
Who was [the parsing with parantheses fails issue] assigned to?	'Angelita'	['question_type_local']
Are there any issues that are resolved for projects in the [deployment] stage?	'initialization broken', 'parsing with parantheses fails', 'null pointer exception during parsing', 'wrong pos tag on consecutive words', 'fails with apache stack', 'issue in using training data', 'timeout problem'	['question_type_global', 'question_three_hop_statement']
Are there any issues for [knowledge base project] that are resolved?	'initialization broken', 'parsing with parantheses fails', 'null pointer exception during parsing', 'wrong pos tag on consecutive words', 'timeout problem'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are not resolved for projects in the [deployment] stage?	'saving data throws exception'	['question_type_global', 'question_three_hop_statement']
What are the issues that are not resolved?	'tokenization not consistent across platforms', 'saving data throws exception'	['question_type_global', 'question_single_statement']
What are the resolved issues for projects in the [deployment] stage?	'initialization broken', 'parsing with parantheses fails', 'null pointer exception during parsing', 'wrong pos tag on consecutive words', 'fails with apache stack', 'issue in using training data', 'timeout problem'	['question_type_global', 'question_three_hop_statement']
Are there any testers assigned to projects in the [deployment] stage?	'Francoise', 'Willis', 'Ashly'	['question_type_global', 'question_three_hop_statement']
Who is assigned to the [open source] projects?	'Francoise', 'Willis', 'Angelita', 'Ashly', 'Alverta', 'Stephine'	['question_type_global', 'question_two_hop_statement']
Were there any issues assigned to [Stephine]?	'null pointer exception during parsing', 'wrong pos tag on consecutive words'	['question_type_local']
Who has issues assigned to them that were all resolved?	'Francoise', 'Willis', 'Angelita', 'Alverta', 'Stephine'	['question_type_global', 'question_two_hop_statement']
[Francoise] is no longer assigned to [knowledge base project]
[this person] is working on [it] also
[the saving data throws exception issue] is assigned to [Alverta]
[she] resolved [this issue]
[knowledge base project] is not assigned to [Stephine]
Are there any issues assigned to [Alverta] that are resolved?	'saving data throws exception', 'svd is slow'	['question_type_local']
Are there any people assigned to the [experimental] projects?	'Francoise', 'Willis', 'Angelita', 'Ashly', 'Alverta', 'Stephine'	['question_type_global', 'question_two_hop_statement']
Are there any projects that are [open source]?	'knowledge base', 'chatbot'	['question_type_global', 'question_single_statement']
[that project] is assigned to [that person] also
Who submitted [the proposal]?	'Angelita'	['question_type_local']
What testers are assigned to the [open source] projects?	'Francoise', 'Willis', 'Ashly'	['question_type_global', 'question_three_hop_statement']
Are there any testers assigned to the [experimental] projects?	'Francoise', 'Willis', 'Ashly'	['question_type_global', 'question_three_hop_statement']
What are the resolved issues for [open source] projects?	'initialization broken', 'parsing with parantheses fails', 'null pointer exception during parsing', 'wrong pos tag on consecutive words', 'timeout problem', 'svd is slow'	['question_type_global', 'question_two_hop_statement']
[that project] is now in the [testing] stage
who are the developers?	'Angelita', 'Alverta', 'Gabrielle', 'Stephine'	['question_type_global', 'question_single_statement']
Are there any issues that are resolved for projects in the [testing] stage?	'initialization broken', 'parsing with parantheses fails', 'null pointer exception during parsing', 'wrong pos tag on consecutive words', 'timeout problem'	['question_type_global', 'question_three_hop_statement']
Who is assigned to the [experimental] projects?	'Francoise', 'Willis', 'Angelita', 'Ashly', 'Alverta', 'Stephine'	['question_type_global', 'question_two_hop_statement']
What are the issues for [chatbot project] that are not resolved?	'tokenization not consistent across platforms'	['question_type_global', 'question_two_hop_statement']
What are the issues created by [Stephine]?	'null pointer exception during parsing', 'svd is slow'	['question_type_local']
Are there any testers assigned to projects in the [deployment] stage?	'Francoise', 'Willis', 'Ashly'	['question_type_global', 'question_three_hop_statement']
What are the resolved issues for [experimental] projects?	'saving data throws exception', 'fails with apache stack', 'issue in using training data'	['question_type_global', 'question_two_hop_statement']
Are there any projects that are [open source]?	'knowledge base', 'chatbot'	['question_type_global', 'question_single_statement']
who are the developers?	'Angelita', 'Alverta', 'Gabrielle', 'Stephine'	['question_type_global', 'question_single_statement']
[this project] is not assigned to [Angelita]
[that developer] is working on [that project] also
Were there any issues assigned to [Francoise]?	'initialization broken', 'fails with apache stack', 'timeout problem'	['question_type_local']
Are there any people assigned to the [open source] projects?	'Francoise', 'Willis', 'Angelita', 'Ashly', 'Alverta', 'Stephine'	['question_type_global', 'question_two_hop_statement']
What projects are currently in the [deployment] stage?	'mobile'	['question_type_global', 'question_single_statement']
Are there projects in the [testing] stage?	'knowledge base'	['question_type_global', 'question_single_statement']
[that project] is in the stage of [evaluation]
[Francoise] is no longer assigned to [chatbot project]
[Francoise] is assigned to [chatbot project] also
Who was [the issue in using training data issue] assigned to?	'Willis'	['question_type_local']
Who is currently working on the [experimental] projects?	'Francoise', 'Willis', 'Angelita', 'Ashly', 'Alverta', 'Stephine'	['question_type_global', 'question_two_hop_statement']
What are the non resolved issues for projects in the [evaluation] stage?	'tokenization not consistent across platforms'	['question_type_global', 'question_three_hop_statement']
Who are the developers currently working on projects in the [deployment] stage?	'Angelita', 'Alverta', 'Stephine'	['question_type_global', 'question_three_hop_statement']
What testers are assigned to the [experimental] projects?	'Francoise', 'Willis', 'Ashly'	['question_type_global', 'question_three_hop_statement']
Are there any issues created by [Alverta] that are resolved?	'wrong pos tag on consecutive words'	['question_type_local']
who are the testers?	'Francoise', 'Willis', 'Emmie', 'Ashly'	['question_type_global', 'question_single_statement']
Are there any issues that are resolved?	'initialization broken', 'parsing with parantheses fails', 'null pointer exception during parsing', 'wrong pos tag on consecutive words', 'saving data throws exception', 'fails with apache stack', 'issue in using training data', 'timeout problem', 'svd is slow'	['question_type_global', 'question_single_statement']
Are there any issues for [it] that are not resolved?	'tokenization not consistent across platforms'	['question_type_global', 'question_two_hop_statement']
Who was [the parsing with parantheses fails proposal] assigned to?	'Angelita'	['question_type_local']
Are there any people assigned to projects in the [deployment] stage?	'Francoise', 'Willis', 'Angelita', 'Ashly', 'Alverta', 'Stephine'	['question_type_global', 'question_two_hop_statement']
What are the non resolved issues?	'tokenization not consistent across platforms'	['question_type_global', 'question_single_statement']
What are the issues that are not resolved?	'tokenization not consistent across platforms'	['question_type_global', 'question_single_statement']
who are the developers?	'Angelita', 'Alverta', 'Gabrielle', 'Stephine'	['question_type_global', 'question_single_statement']
Are there projects in the [deployment] stage?	'mobile'	['question_type_global', 'question_single_statement']
What are the resolved issues for [this project]?	'svd is slow'	['question_type_global', 'question_two_hop_statement']
[that project] is in the [deployment] stage
What are the issues assigned to [Willis]?	'issue in using training data'	['question_type_local']
Are there any issues for [that project] that are not resolved?	'tokenization not consistent across platforms'	['question_type_global', 'question_two_hop_statement']
Which testers have issues assigned to them that were all resolved?	'Francoise', 'Willis'	['question_type_global', 'question_three_hop_statement']
Are there any people assigned to the [open source] projects?	'Francoise', 'Willis', 'Angelita', 'Ashly', 'Alverta', 'Stephine'	['question_type_global', 'question_two_hop_statement']
who are the developers?	'Angelita', 'Alverta', 'Gabrielle', 'Stephine'	['question_type_global', 'question_single_statement']
[it] has moved to the [development] stage
Who is currently working on projects in the [evaluation] stage?	'Francoise', 'Willis', 'Angelita', 'Ashly', 'Alverta', 'Stephine'	['question_type_global', 'question_two_hop_statement']
What are the resolved issues for [experimental] projects?	'saving data throws exception', 'fails with apache stack', 'issue in using training data'	['question_type_global', 'question_two_hop_statement']
What are the issues for [this project] that are resolved?	'svd is slow'	['question_type_global', 'question_two_hop_statement']
What are the issues that were resolved?	'initialization broken', 'parsing with parantheses fails', 'null pointer exception during parsing', 'wrong pos tag on consecutive words', 'saving data throws exception', 'fails with apache stack', 'issue in using training data', 'timeout problem', 'svd is slow'	['question_type_global', 'question_single_statement']
Which is the stage of [it]?	'development'	['question_type_local']
What are the non resolved issues?	'tokenization not consistent across platforms'	['question_type_global', 'question_single_statement']
What developers are assigned to the [experimental] projects?	'Angelita', 'Alverta', 'Stephine'	['question_type_global', 'question_three_hop_statement']
Which testers have issues assigned to them that were all resolved?	'Francoise', 'Willis'	['question_type_global', 'question_three_hop_statement']
Which is the stage of [mobile project]?	'deployment'	['question_type_local']
Are there any developers assigned to projects in the [evaluation] stage?	'Angelita', 'Alverta', 'Stephine'	['question_type_global', 'question_three_hop_statement']
who are the testers?	'Francoise', 'Willis', 'Emmie', 'Ashly'	['question_type_global', 'question_single_statement']
Are there any issues that are resolved?	'initialization broken', 'parsing with parantheses fails', 'null pointer exception during parsing', 'wrong pos tag on consecutive words', 'saving data throws exception', 'fails with apache stack', 'issue in using training data', 'timeout problem', 'svd is slow'	['question_type_global', 'question_single_statement']
What are the resolved issues for projects in the [deployment] stage?	'saving data throws exception', 'fails with apache stack', 'issue in using training data'	['question_type_global', 'question_three_hop_statement']
What projects is [Angelita] working on?	'knowledge base', 'mobile', 'chatbot'	['question_type_local']
Are there any testers assigned to the [experimental] projects?	'Francoise', 'Willis', 'Ashly'	['question_type_global', 'question_three_hop_statement']
[Angelita] is no longer assigned to [chatbot project]
[she] is assigned to [it] also
Who are the developers currently working on projects in the [evaluation] stage?	'Angelita', 'Alverta', 'Stephine'	['question_type_global', 'question_three_hop_statement']
Are there any people assigned to the [open source] projects?	'Francoise', 'Willis', 'Angelita', 'Ashly', 'Alverta', 'Stephine'	['question_type_global', 'question_two_hop_statement']
Which testers have issues assigned to them that were all resolved?	'Francoise', 'Willis'	['question_type_global', 'question_three_hop_statement']
What are the [bug]s that are not resolved?	'fails with apache stack'	['question_type_global', 'question_two_hop_statement']
[Willis] is no longer assigned to [mobile project]
[he] is working on [mobile project] also
[this test engineer] is no longer assigned to [chatbot project]
[that test engineer] is working on [chatbot project] also
[that test engineer] is no longer assigned to [knowledge base project]
[that test engineer] is working on [that project] also
Were there any issues submitted by [Angelita]?	'parsing with parantheses fails'	['question_type_local']
Who is assigned to projects in the [deployment] stage?	'Francoise', 'Willis', 'Angelita', 'Ashly', 'Alverta', 'Stephine'	['question_type_global', 'question_two_hop_statement']
Who has issues assigned to them that were all resolved?	'Francoise', 'Willis', 'Angelita', 'Alverta', 'Stephine'	['question_type_global', 'question_two_hop_statement']
who are the testers?	'Francoise', 'Willis', 'Emmie', 'Ashly'	['question_type_global', 'question_single_statement']
What testers are assigned to the [open source] projects?	'Francoise', 'Willis', 'Ashly'	['question_type_global', 'question_three_hop_statement']
[mobile project] is assigned to [Gabrielle]
What testers are assigned to projects in the [deployment] stage?	'Francoise', 'Willis', 'Ashly'	['question_type_global', 'question_three_hop_statement']
Are there any developers assigned to projects in the [development] stage?	'Angelita', 'Alverta', 'Stephine'	['question_type_global', 'question_three_hop_statement']
[this project] is now in the [development] stage
