there is a new [mobile] [project]
[this project] is a [internal] project
[that project] is in the stage of [implementation]
[mobile project] is in the [evaluation] stage
[mobile project] is in the [design] stage
[versioning needs to be made consistent] is a new issue for the [mobile project]
What projects are in the [design] stage?	'mobile'	['question_type_global', 'question_single_statement']
[mobile project] has moved to the [deployment] stage
What are the issues for [this project] that are not resolved?	'versioning needs to be made consistent'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are not resolved?	'versioning needs to be made consistent'	['question_type_global', 'question_single_statement']
What projects are currently in the [deployment] stage?	'mobile'	['question_type_global', 'question_single_statement']
there is a new [internal] [chatbot] [project]
there is a new [knowledge base] [project]
[knowledge base project] is in the [implementation] stage
[it] is a [platform] project
[Vivienne] is a [developer] on [that project]
[this project] is not assigned to [this developer]
[chatbot project] is assigned to [that person]
[that developer] is working on [knowledge base project] also
What stage is [knowledge base project] in?	'implementation'	['question_type_local']
who are the developers?	'Vivienne'	['question_type_global', 'question_single_statement']
[that person] is working on [mobile project] also
[mobile project] is now in the [implementation] stage
[Eun] is a [developer] on [knowledge base project]
[this person] is assigned to [mobile project] also
[she] created a new [bug] for [knowledge base project]: [memory leak bug]
[the memory leak bug issue] is assigned to [Eun]
Who is working on [knowledge base project]?	'Vivienne', 'Eun'	['question_type_local']
What projects are in the [implementation] stage?	'mobile', 'knowledge base'	['question_type_global', 'question_single_statement']
[wrong pos tag on consecutive words] is a new [proposal] for [knowledge base project] that [this person] just created
[the proposal] is assigned to [this developer]
[that developer] resolved [the wrong pos tag on consecutive words proposal]
[Vivienne] created a new issue for [chatbot project]: [two consecutive dates identified as single date]
[she] is no longer assigned to [knowledge base project]
[knowledge base project] is assigned to [Eun] also
[Alverta] is a [developer] on [knowledge base project]
Who is working on [chatbot project]?	'Vivienne'	['question_type_local']
What are the [bug]s that are not resolved?	'memory leak bug'	['question_type_global', 'question_two_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Eun'	['question_type_global', 'question_three_hop_statement']
Are there projects in the [implementation] stage?	'mobile', 'knowledge base'	['question_type_global', 'question_single_statement']
What are the resolved issues?	'wrong pos tag on consecutive words'	['question_type_global', 'question_single_statement']
Who has issues assigned to them that were all resolved?	'Eun'	['question_type_global', 'question_two_hop_statement']
[this person] is working on [chatbot project] also
Who is working on [it]?	'Vivienne', 'Alverta'	['question_type_local']
Are there any people assigned to projects in the [implementation] stage?	'Vivienne', 'Eun', 'Alverta'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are not resolved?	'versioning needs to be made consistent', 'memory leak bug', 'two consecutive dates identified as single date'	['question_type_global', 'question_single_statement']
What are the issues that are resolved for projects in the [implementation] stage?	'wrong pos tag on consecutive words'	['question_type_global', 'question_three_hop_statement']
What are the issues created by [Eun] that were not resolved?	'memory leak bug'	['question_type_local']
[Eun] is working on [this project] also
[this project] is in the [implementation] stage
[Michael] is a [developer]
[knowledge base project] is assigned to [this developer]
[John] is a [tester] on [mobile project]
[knowledge base project] is assigned to [this person] also
What are the issues for [mobile project] that are not resolved?	'versioning needs to be made consistent'	['question_type_global', 'question_two_hop_statement']
[the two consecutive dates identified as single date issue] is assigned to [Eun]
[this developer] resolved [this issue]
[this person] resolved [the bug]
Who submitted [the two consecutive dates identified as single date issue]?	'Vivienne'	['question_type_local']
Are there any testers assigned to projects in the [implementation] stage?	'John'	['question_type_global', 'question_three_hop_statement']
What are the non resolved issues?	'versioning needs to be made consistent'	['question_type_global', 'question_single_statement']
[Racquel] is a [tester]
[mobile project] is assigned to [Alverta] also
What are the issues that are not resolved for projects in the [implementation] stage?	'versioning needs to be made consistent'	['question_type_global', 'question_three_hop_statement']
Are there any people assigned to projects in the [implementation] stage?	'Vivienne', 'Eun', 'Alverta', 'Michael', 'John'	['question_type_global', 'question_two_hop_statement']
What are the non resolved issues for [this project]?	'versioning needs to be made consistent'	['question_type_global', 'question_two_hop_statement']
[chatbot project] is not assigned to [Vivienne]
[that person] is working on [it] also
[Alverta] submitted a new [enhancement] for [mobile project]: [saving data throws exception]
[this issue] was assigned to [Alverta]
[Alverta] resolved [the enhancement]
[Roslyn] is a [tester] on [chatbot project]
[that test engineer] is working on [mobile project] also
Who has issues assigned to them that were all resolved?	'Eun', 'Alverta'	['question_type_global', 'question_two_hop_statement']
What are the issues for [knowledge base project] that are resolved?	'memory leak bug', 'wrong pos tag on consecutive words'	['question_type_global', 'question_two_hop_statement']
Are there any people assigned to the [platform] projects?	'Vivienne', 'Eun', 'Alverta', 'Michael', 'John'	['question_type_global', 'question_two_hop_statement']
Who are the testers currently working on the [platform] projects?	'John'	['question_type_global', 'question_three_hop_statement']
who are the testers?	'John', 'Racquel', 'Roslyn'	['question_type_global', 'question_single_statement']
[that person] is working on [knowledge base project] also
Are there any people assigned to projects in the [implementation] stage?	'Vivienne', 'Eun', 'Alverta', 'Michael', 'John', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
[this person] created a new [proposal] for [chatbot project]: [timeout problem]
What developers are assigned to the [internal] projects?	'Vivienne', 'Eun', 'Alverta'	['question_type_global', 'question_three_hop_statement']
Are there any issues that are resolved?	'memory leak bug', 'wrong pos tag on consecutive words', 'two consecutive dates identified as single date', 'saving data throws exception'	['question_type_global', 'question_single_statement']
[the issue] is assigned to [Vivienne]
Who created [the enhancement]?	'Alverta'	['question_type_local']
who are the developers?	'Vivienne', 'Eun', 'Alverta', 'Michael'	['question_type_global', 'question_single_statement']
What developers are assigned to the [platform] projects?	'Vivienne', 'Eun', 'Alverta', 'Michael'	['question_type_global', 'question_three_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Eun', 'Alverta'	['question_type_global', 'question_three_hop_statement']
[that developer] resolved [that issue]
Which is the stage of [chatbot project]?	'implementation'	['question_type_local']
What are the issues for [chatbot project] that are resolved?	'two consecutive dates identified as single date', 'timeout problem'	['question_type_global', 'question_two_hop_statement']
What testers are assigned to projects in the [implementation] stage?	'John', 'Roslyn'	['question_type_global', 'question_three_hop_statement']
Who has issues assigned to them that were all resolved?	'Vivienne', 'Eun', 'Alverta'	['question_type_global', 'question_two_hop_statement']
[that person] is no longer assigned to [mobile project]
[svd is slow] is a new [bug] submitted by [Alverta] for [chatbot project]
[chatbot project] is not assigned to [Vivienne]
[that person] is assigned to [mobile project] also
[this person] is assigned to [chatbot project] also
[chatbot project] is in the [evaluation] stage
Who are the developers currently working on projects in the [evaluation] stage?	'Vivienne', 'Eun', 'Alverta'	['question_type_global', 'question_three_hop_statement']
[knowledge base project] is assigned to [Racquel]
[this test engineer] is working on [chatbot project] also
Which developers have issues assigned to them that were all resolved?	'Vivienne', 'Eun', 'Alverta'	['question_type_global', 'question_three_hop_statement']
who are the testers?	'John', 'Racquel', 'Roslyn'	['question_type_global', 'question_single_statement']
Are there any issues that are resolved for [internal] projects?	'two consecutive dates identified as single date', 'saving data throws exception', 'timeout problem'	['question_type_global', 'question_two_hop_statement']
What are the issues that are not resolved?	'versioning needs to be made consistent', 'svd is slow'	['question_type_global', 'question_single_statement']
What are the non resolved [bug]s?	'memory leak bug'	['question_type_global', 'question_two_hop_statement']
Are there any issues for [this project] that are not resolved?	'svd is slow'	['question_type_global', 'question_two_hop_statement']
who are the testers?	'John', 'Racquel', 'Roslyn'	['question_type_global', 'question_single_statement']
What are the issues for [mobile project] that are not resolved?	'versioning needs to be made consistent'	['question_type_global', 'question_two_hop_statement']
[that project] is assigned to [John] also
What projects is [Vivienne] working on?	'mobile', 'chatbot', 'knowledge base'	['question_type_local']
Are there any people assigned to the [platform] projects?	'Vivienne', 'Eun', 'Alverta', 'Michael', 'John', 'Racquel', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
What are the non resolved issues?	'versioning needs to be made consistent', 'svd is slow'	['question_type_global', 'question_single_statement']
What are the issues for [this project] that are not resolved?	'svd is slow'	['question_type_global', 'question_two_hop_statement']
Are there any [bug]s that are not resolved?	'memory leak bug'	['question_type_global', 'question_two_hop_statement']
Who is assigned to projects in the [implementation] stage?	'Vivienne', 'Eun', 'Alverta', 'Michael', 'John', 'Racquel', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
Were there any issues created by [Vivienne]?	'two consecutive dates identified as single date'	['question_type_local']
What projects are [internal]?	'mobile', 'chatbot'	['question_type_global', 'question_single_statement']
Are there any issues that are resolved?	'memory leak bug', 'wrong pos tag on consecutive words', 'two consecutive dates identified as single date', 'saving data throws exception', 'timeout problem'	['question_type_global', 'question_single_statement']
[this test engineer] is no longer assigned to [mobile project]
[that test engineer] is working on [this project] also
What are the [enhancement]s that are not resolved?	'saving data throws exception'	['question_type_global', 'question_two_hop_statement']
Who is assigned to projects in the [evaluation] stage?	'Vivienne', 'Eun', 'Alverta', 'John', 'Racquel', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Vivienne', 'Eun', 'Alverta'	['question_type_global', 'question_three_hop_statement']
Who is working on [this project]?	'Vivienne', 'Eun', 'Alverta', 'John', 'Roslyn'	['question_type_local']
Are there any testers assigned to projects in the [evaluation] stage?	'John', 'Racquel', 'Roslyn'	['question_type_global', 'question_three_hop_statement']
[it] is in the stage of [evaluation]
[the versioning needs to be made consistent issue] was assigned to [Vivienne]
[that developer] resolved [that issue]
What are the issues that are not resolved?	'svd is slow'	['question_type_global', 'question_single_statement']
Who is currently working on projects in the [implementation] stage?	'Vivienne', 'Eun', 'Alverta', 'Michael', 'John', 'Racquel', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
who are the developers?	'Vivienne', 'Eun', 'Alverta', 'Michael'	['question_type_global', 'question_single_statement']
Are there any [internal] projects?	'mobile', 'chatbot'	['question_type_global', 'question_single_statement']
What are the resolved issues for projects in the [evaluation] stage?	'versioning needs to be made consistent', 'two consecutive dates identified as single date', 'saving data throws exception', 'timeout problem'	['question_type_global', 'question_three_hop_statement']
[knowledge base project] is not assigned to [she]
[Vivienne] is assigned to [knowledge base project] also
[knowledge base project] is in the [deployment] stage
Who created [the saving data throws exception enhancement]?	'Alverta'	['question_type_local']
who are the testers?	'John', 'Racquel', 'Roslyn'	['question_type_global', 'question_single_statement']
Are there projects in the [evaluation] stage?	'mobile', 'chatbot'	['question_type_global', 'question_single_statement']
Who has issues assigned to them that were all resolved?	'Vivienne', 'Eun', 'Alverta'	['question_type_global', 'question_two_hop_statement']
Are there any projects that are [platform]?	'knowledge base'	['question_type_global', 'question_single_statement']
Who are the developers on [knowledge base project]	'Vivienne', 'Eun', 'Alverta', 'Michael'	['question_type_local']
What developers are assigned to projects in the [deployment] stage?	'Vivienne', 'Eun', 'Alverta', 'Michael'	['question_type_global', 'question_three_hop_statement']
Who is assigned to the [platform] projects?	'Vivienne', 'Eun', 'Alverta', 'Michael', 'John', 'Racquel', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
Who is [the wrong pos tag on consecutive words issue] assigned to?	'Eun'	['question_type_local']
Who is currently working on the [internal] projects?	'Vivienne', 'Eun', 'Alverta', 'John', 'Racquel', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
Who are the developers on [this project]	'Vivienne', 'Eun', 'Alverta', 'Michael'	['question_type_local']
Are there any people assigned to projects in the [deployment] stage?	'Vivienne', 'Eun', 'Alverta', 'Michael', 'John', 'Racquel', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
[chatbot project] is assigned to [Michael] also
[mobile project] is assigned to [this person] also
What are the resolved issues?	'versioning needs to be made consistent', 'memory leak bug', 'wrong pos tag on consecutive words', 'two consecutive dates identified as single date', 'saving data throws exception', 'timeout problem'	['question_type_global', 'question_single_statement']
Are there any issues for [knowledge base project] that are resolved?	'memory leak bug', 'wrong pos tag on consecutive words'	['question_type_global', 'question_two_hop_statement']
Were there any issues assigned to [Alverta]?	'saving data throws exception'	['question_type_local']
What developers are assigned to the [platform] projects?	'Vivienne', 'Eun', 'Alverta', 'Michael'	['question_type_global', 'question_three_hop_statement']
What are the non resolved issues?	'svd is slow'	['question_type_global', 'question_single_statement']
Are there any issues that are resolved for projects in the [evaluation] stage?	'versioning needs to be made consistent', 'two consecutive dates identified as single date', 'saving data throws exception', 'timeout problem'	['question_type_global', 'question_three_hop_statement']
What are the non resolved [enhancement]s?	'saving data throws exception'	['question_type_global', 'question_two_hop_statement']
Who submitted [the svd is slow issue]?	'Alverta'	['question_type_local']
Are there any issues that are not resolved?	'svd is slow'	['question_type_global', 'question_single_statement']
What are the issues for [mobile project] that are resolved?	'versioning needs to be made consistent', 'saving data throws exception'	['question_type_global', 'question_two_hop_statement']
Who has issues assigned to them that were all resolved?	'Vivienne', 'Eun', 'Alverta'	['question_type_global', 'question_two_hop_statement']
Who are the testers currently working on the [internal] projects?	'John', 'Racquel', 'Roslyn'	['question_type_global', 'question_three_hop_statement']
What stage is [knowledge base project] in?	'deployment'	['question_type_local']
Are there any issues that are resolved?	'versioning needs to be made consistent', 'memory leak bug', 'wrong pos tag on consecutive words', 'two consecutive dates identified as single date', 'saving data throws exception', 'timeout problem'	['question_type_global', 'question_single_statement']
who are the testers?	'John', 'Racquel', 'Roslyn'	['question_type_global', 'question_single_statement']
Are there any testers assigned to the [internal] projects?	'John', 'Racquel', 'Roslyn'	['question_type_global', 'question_three_hop_statement']
What projects are currently in the [deployment] stage?	'knowledge base'	['question_type_global', 'question_single_statement']
Who are the testers currently working on the [platform] projects?	'John', 'Racquel', 'Roslyn'	['question_type_global', 'question_three_hop_statement']
who are the developers?	'Vivienne', 'Eun', 'Alverta', 'Michael'	['question_type_global', 'question_single_statement']
Which is the stage of [knowledge base project]?	'deployment'	['question_type_local']
Are there any issues that are not resolved for [internal] projects?	'svd is slow'	['question_type_global', 'question_two_hop_statement']
What are the issues submitted by [Eun] that were resolved?	'memory leak bug', 'wrong pos tag on consecutive words'	['question_type_local']
What are the issues that are resolved for [platform] projects?	'memory leak bug', 'wrong pos tag on consecutive words'	['question_type_global', 'question_two_hop_statement']
Are there any issues created by [Roslyn] that are resolved?	'timeout problem'	['question_type_local']
Which developers have issues assigned to them that were all resolved?	'Vivienne', 'Eun', 'Alverta'	['question_type_global', 'question_three_hop_statement']
What projects are [platform]?	'knowledge base'	['question_type_global', 'question_single_statement']
What are the non resolved issues for [internal] projects?	'svd is slow'	['question_type_global', 'question_two_hop_statement']
[mobile project] is in the stage of [deployment]
What stage is [this project] in?	'deployment'	['question_type_local']
who are the testers?	'John', 'Racquel', 'Roslyn'	['question_type_global', 'question_single_statement']
Who has issues assigned to them that were all resolved?	'Vivienne', 'Eun', 'Alverta'	['question_type_global', 'question_two_hop_statement']
Were there any issues created by [Vivienne]?	'two consecutive dates identified as single date'	['question_type_local']
What are the non resolved issues for [chatbot project]?	'svd is slow'	['question_type_global', 'question_two_hop_statement']
Who is assigned to projects in the [evaluation] stage?	'Vivienne', 'Eun', 'Alverta', 'Michael', 'John', 'Racquel', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
What testers are assigned to projects in the [deployment] stage?	'John', 'Racquel', 'Roslyn'	['question_type_global', 'question_three_hop_statement']
What are the issues submitted by [Vivienne]?	'two consecutive dates identified as single date'	['question_type_local']
Which developers have issues assigned to them that were all resolved?	'Vivienne', 'Eun', 'Alverta'	['question_type_global', 'question_three_hop_statement']
What are the issues that are not resolved for [internal] projects?	'svd is slow'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are not resolved for projects in the [evaluation] stage?	'svd is slow'	['question_type_global', 'question_three_hop_statement']
What are the non resolved issues?	'svd is slow'	['question_type_global', 'question_single_statement']
Are there any people assigned to the [internal] projects?	'Vivienne', 'Eun', 'Alverta', 'Michael', 'John', 'Racquel', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
Were there any issues submitted by [Alverta]?	'saving data throws exception', 'svd is slow'	['question_type_local']
[that project] is now in the [implementation] stage
[that project] is in the stage of [design]
Who submitted [the memory leak bug bug]?	'Eun'	['question_type_local']
What projects are in the [deployment] stage?	'knowledge base'	['question_type_global', 'question_single_statement']
Are there any [internal] projects?	'mobile', 'chatbot'	['question_type_global', 'question_single_statement']
Which developers have issues assigned to them that were all resolved?	'Vivienne', 'Eun', 'Alverta'	['question_type_global', 'question_three_hop_statement']
Are there any issues that are resolved?	'versioning needs to be made consistent', 'memory leak bug', 'wrong pos tag on consecutive words', 'two consecutive dates identified as single date', 'saving data throws exception', 'timeout problem'	['question_type_global', 'question_single_statement']
What projects is [Roslyn] working on?	'mobile', 'chatbot', 'knowledge base'	['question_type_local']
What are the issues that are not resolved for projects in the [evaluation] stage?	'svd is slow'	['question_type_global', 'question_three_hop_statement']
What developers are assigned to projects in the [deployment] stage?	'Vivienne', 'Eun', 'Alverta', 'Michael'	['question_type_global', 'question_three_hop_statement']
Who are the developers currently working on the [platform] projects?	'Vivienne', 'Eun', 'Alverta', 'Michael'	['question_type_global', 'question_three_hop_statement']
What are the resolved issues for projects in the [design] stage?	'versioning needs to be made consistent', 'saving data throws exception'	['question_type_global', 'question_three_hop_statement']
Who is currently working on the [internal] projects?	'Vivienne', 'Eun', 'Alverta', 'Michael', 'John', 'Racquel', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
What are the [enhancement]s that are not resolved?	'saving data throws exception'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are not resolved?	'svd is slow'	['question_type_global', 'question_single_statement']
[mobile project] is now in the [implementation] stage
What projects is [Michael] working on?	'mobile', 'chatbot', 'knowledge base'	['question_type_local']
What projects are [platform]?	'knowledge base'	['question_type_global', 'question_single_statement']
Were there any issues assigned to [Alverta]?	'saving data throws exception'	['question_type_local']
Are there any projects that are [internal]?	'mobile', 'chatbot'	['question_type_global', 'question_single_statement']
Which developers have issues assigned to them that were all resolved?	'Vivienne', 'Eun', 'Alverta'	['question_type_global', 'question_three_hop_statement']
What are the issues that were resolved?	'versioning needs to be made consistent', 'memory leak bug', 'wrong pos tag on consecutive words', 'two consecutive dates identified as single date', 'saving data throws exception', 'timeout problem'	['question_type_global', 'question_single_statement']
[knowledge base project] is not assigned to [Eun]
[this developer] is working on [knowledge base project] also
Who is working on [this project]?	'Vivienne', 'Eun', 'Alverta', 'Michael', 'John', 'Racquel', 'Roslyn'	['question_type_local']
What developers are assigned to the [platform] projects?	'Vivienne', 'Eun', 'Alverta', 'Michael'	['question_type_global', 'question_three_hop_statement']
Are there any issues that are resolved for projects in the [evaluation] stage?	'two consecutive dates identified as single date', 'timeout problem'	['question_type_global', 'question_three_hop_statement']
Who is assigned to the [platform] projects?	'Vivienne', 'Eun', 'Alverta', 'Michael', 'John', 'Racquel', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
What are the issues that are resolved for [platform] projects?	'memory leak bug', 'wrong pos tag on consecutive words'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are resolved for [platform] projects?	'memory leak bug', 'wrong pos tag on consecutive words'	['question_type_global', 'question_two_hop_statement']
What are the resolved issues for [platform] projects?	'memory leak bug', 'wrong pos tag on consecutive words'	['question_type_global', 'question_two_hop_statement']
[that project] is not assigned to [Eun]
[it] is assigned to [that person] also
Are there any issues assigned to [Vivienne] that are resolved?	'versioning needs to be made consistent', 'timeout problem'	['question_type_local']
What are the issues that are not resolved for [internal] projects?	'svd is slow'	['question_type_global', 'question_two_hop_statement']
Who is assigned to projects in the [deployment] stage?	'Vivienne', 'Eun', 'Alverta', 'Michael', 'John', 'Racquel', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Vivienne', 'Eun', 'Alverta'	['question_type_global', 'question_three_hop_statement']
[this project] is in the [design] stage
[knowledge base project] has moved to the [evaluation] stage
What projects is [Alverta] working on?	'mobile', 'chatbot', 'knowledge base'	['question_type_local']
Who are the developers currently working on projects in the [implementation] stage?	'Vivienne', 'Eun', 'Alverta', 'Michael'	['question_type_global', 'question_three_hop_statement']
[mobile project] is in the [deployment] stage
Which developers are working on [knowledge base project]?	'Vivienne', 'Eun', 'Alverta', 'Michael'	['question_type_local']
who are the testers?	'John', 'Racquel', 'Roslyn'	['question_type_global', 'question_single_statement']
What are the non resolved [bug]s?	'svd is slow'	['question_type_global', 'question_two_hop_statement']
What developers are assigned to projects in the [deployment] stage?	'Vivienne', 'Eun', 'Alverta', 'Michael'	['question_type_global', 'question_three_hop_statement']
Who is assigned to projects in the [deployment] stage?	'Vivienne', 'Eun', 'Alverta', 'Michael', 'John', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
[mobile project] has moved to the [implementation] stage
Which testers are working on [mobile project]?	'John', 'Roslyn'	['question_type_local']
Who is assigned to projects in the [implementation] stage?	'Vivienne', 'Eun', 'Alverta', 'Michael', 'John', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
Are there projects in the [implementation] stage?	'mobile'	['question_type_global', 'question_single_statement']
What developers are assigned to the [internal] projects?	'Vivienne', 'Eun', 'Alverta', 'Michael'	['question_type_global', 'question_three_hop_statement']
Who created [the bug that was last added]?	'Alverta'	['question_type_local']
Who is assigned to the [platform] projects?	'Vivienne', 'Eun', 'Alverta', 'Michael', 'John', 'Racquel', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
What developers are assigned to projects in the [evaluation] stage?	'Vivienne', 'Eun', 'Alverta', 'Michael'	['question_type_global', 'question_three_hop_statement']
What testers are assigned to projects in the [implementation] stage?	'John', 'Roslyn'	['question_type_global', 'question_three_hop_statement']
who are the developers?	'Vivienne', 'Eun', 'Alverta', 'Michael'	['question_type_global', 'question_single_statement']
Are there any developers assigned to projects in the [evaluation] stage?	'Vivienne', 'Eun', 'Alverta', 'Michael'	['question_type_global', 'question_three_hop_statement']
What developers are assigned to the [internal] projects?	'Vivienne', 'Eun', 'Alverta', 'Michael'	['question_type_global', 'question_three_hop_statement']
Who has issues assigned to them that were all resolved?	'Vivienne', 'Eun', 'Alverta'	['question_type_global', 'question_two_hop_statement']
Are there any people assigned to the [platform] projects?	'Vivienne', 'Eun', 'Alverta', 'Michael', 'John', 'Racquel', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
[it] has moved to the [design] stage
Who is [the timeout problem proposal] assigned to?	'Vivienne'	['question_type_local']
What are the issues that are resolved for projects in the [design] stage?	'versioning needs to be made consistent', 'saving data throws exception'	['question_type_global', 'question_three_hop_statement']
What testers are assigned to projects in the [evaluation] stage?	'John', 'Racquel', 'Roslyn'	['question_type_global', 'question_three_hop_statement']
Are there any issues that are resolved for projects in the [design] stage?	'versioning needs to be made consistent', 'saving data throws exception'	['question_type_global', 'question_three_hop_statement']
[the bug that was last added] is assigned to [Michael]
[Michael] resolved [this issue]
Which testers are working on [mobile project]?	'John', 'Roslyn'	['question_type_local']
What are the resolved issues for projects in the [evaluation] stage?	'memory leak bug', 'wrong pos tag on consecutive words', 'two consecutive dates identified as single date', 'timeout problem', 'svd is slow'	['question_type_global', 'question_three_hop_statement']
who are the developers?	'Vivienne', 'Eun', 'Alverta', 'Michael'	['question_type_global', 'question_single_statement']
Who was [the versioning needs to be made consistent issue] assigned to?	'Vivienne'	['question_type_local']
Who has issues assigned to them that were all resolved?	'Vivienne', 'Eun', 'Alverta', 'Michael'	['question_type_global', 'question_two_hop_statement']
Which is the stage of [chatbot project]?	'evaluation'	['question_type_local']
What are the issues that are resolved for projects in the [design] stage?	'versioning needs to be made consistent', 'saving data throws exception'	['question_type_global', 'question_three_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Vivienne', 'Eun', 'Alverta', 'Michael'	['question_type_global', 'question_three_hop_statement']
Who was [the timeout problem proposal] assigned to?	'Vivienne'	['question_type_local']
What developers are assigned to projects in the [evaluation] stage?	'Vivienne', 'Eun', 'Alverta', 'Michael'	['question_type_global', 'question_three_hop_statement']
What projects are [internal]?	'mobile', 'chatbot'	['question_type_global', 'question_single_statement']
Are there any projects that are [platform]?	'knowledge base'	['question_type_global', 'question_single_statement']
What are the issues that are resolved for [platform] projects?	'memory leak bug', 'wrong pos tag on consecutive words'	['question_type_global', 'question_two_hop_statement']
[knowledge base project] is not assigned to [this developer]
What are the resolved issues for [mobile project]?	'versioning needs to be made consistent', 'saving data throws exception'	['question_type_global', 'question_two_hop_statement']
Who has issues assigned to them that were all resolved?	'Vivienne', 'Eun', 'Alverta', 'Michael'	['question_type_global', 'question_two_hop_statement']
[Michael] is working on [knowledge base project] also
[Racquel] is working on [mobile project] also
Who is [the enhancement] assigned to?	'Alverta'	['question_type_local']
[knowledge base project] is not assigned to [Eun]
[that person] is working on [it] also
[knowledge base project] is in the [deployment] stage
Are there any issues submitted by [Vivienne] that are resolved?	'two consecutive dates identified as single date'	['question_type_local']
Are there any people assigned to the [platform] projects?	'Vivienne', 'Eun', 'Alverta', 'Michael', 'John', 'Racquel', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
Are there any people assigned to the [internal] projects?	'Vivienne', 'Eun', 'Alverta', 'Michael', 'John', 'Racquel', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
[that project] is in the [evaluation] stage
[this project] is in the [design] stage
What stage is [chatbot project] in?	'evaluation'	['question_type_local']
Who is assigned to the [platform] projects?	'Vivienne', 'Eun', 'Alverta', 'Michael', 'John', 'Racquel', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
Who is currently working on projects in the [design] stage?	'Vivienne', 'Eun', 'Alverta', 'Michael', 'John', 'Racquel', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Vivienne', 'Eun', 'Alverta', 'Michael'	['question_type_global', 'question_three_hop_statement']
Are there any issues for [chatbot project] that are resolved?	'two consecutive dates identified as single date', 'timeout problem', 'svd is slow'	['question_type_global', 'question_two_hop_statement']
Who was [the bug that was last added] assigned to?	'Michael'	['question_type_local']
Who has issues assigned to them that were all resolved?	'Vivienne', 'Eun', 'Alverta', 'Michael'	['question_type_global', 'question_two_hop_statement']
[this project] is now in the [evaluation] stage
Who is currently working on projects in the [evaluation] stage?	'Vivienne', 'Eun', 'Alverta', 'Michael', 'John', 'Racquel', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
What testers are assigned to the [platform] projects?	'John', 'Racquel', 'Roslyn'	['question_type_global', 'question_three_hop_statement']
Are there any issues that are resolved for projects in the [design] stage?	'versioning needs to be made consistent', 'saving data throws exception'	['question_type_global', 'question_three_hop_statement']
What are the issues that were resolved?	'versioning needs to be made consistent', 'memory leak bug', 'wrong pos tag on consecutive words', 'two consecutive dates identified as single date', 'saving data throws exception', 'timeout problem', 'svd is slow'	['question_type_global', 'question_single_statement']
What are the issues for [it] that are resolved?	'memory leak bug', 'wrong pos tag on consecutive words'	['question_type_global', 'question_two_hop_statement']
What are the non resolved [bug]s?	'memory leak bug', 'svd is slow'	['question_type_global', 'question_two_hop_statement']
What are the issues for [chatbot project] that are resolved?	'two consecutive dates identified as single date', 'timeout problem', 'svd is slow'	['question_type_global', 'question_two_hop_statement']
Who created [the two consecutive dates identified as single date issue]?	'Vivienne'	['question_type_local']
Which developers have issues assigned to them that were all resolved?	'Vivienne', 'Eun', 'Alverta', 'Michael'	['question_type_global', 'question_three_hop_statement']
Who has issues assigned to them that were all resolved?	'Vivienne', 'Eun', 'Alverta', 'Michael'	['question_type_global', 'question_two_hop_statement']
Are there any [platform] projects?	'knowledge base'	['question_type_global', 'question_single_statement']
What are the resolved issues for [internal] projects?	'versioning needs to be made consistent', 'two consecutive dates identified as single date', 'saving data throws exception', 'timeout problem', 'svd is slow'	['question_type_global', 'question_two_hop_statement']
[chatbot project] is not assigned to [Vivienne]
Who is currently working on the [platform] projects?	'Vivienne', 'Eun', 'Alverta', 'Michael', 'John', 'Racquel', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
Who are the developers currently working on projects in the [design] stage?	'Vivienne', 'Eun', 'Alverta', 'Michael'	['question_type_global', 'question_three_hop_statement']
Are there any [internal] projects?	'mobile', 'chatbot'	['question_type_global', 'question_single_statement']
[chatbot project] is assigned to [this developer] also
Who created [the two consecutive dates identified as single date issue]?	'Vivienne'	['question_type_local']
Who submitted [the timeout problem issue]?	'Roslyn'	['question_type_local']
Who has issues assigned to them that were all resolved?	'Vivienne', 'Eun', 'Alverta', 'Michael'	['question_type_global', 'question_two_hop_statement']
What are the issues for [chatbot project] that are resolved?	'two consecutive dates identified as single date', 'timeout problem', 'svd is slow'	['question_type_global', 'question_two_hop_statement']
[that developer] is no longer assigned to [this project]
[this project] is assigned to [Vivienne] also
[Vivienne] is no longer assigned to [mobile project]
[Vivienne] is working on [it] also
