there is a new [internal] [mobile] [project]
[mobile project] is in the [design] stage
Which is the stage of [this project]?	'design'	['question_type_local']
What stage is [mobile project] in?	'design'	['question_type_local']
Which is the stage of [mobile project]?	'design'	['question_type_local']
there is a new [knowledge base] [project]
[knowledge base project] is in the [testing] stage
[this project] is a [platform] project
What projects are currently in the [design] stage?	'mobile'	['question_type_global', 'question_single_statement']
Are there any [internal] projects?	'mobile'	['question_type_global', 'question_single_statement']
[Angelita] is a [tester]
What stage is [that project] in?	'testing'	['question_type_local']
there is a new [chatbot] [project]
[this project] is a [personal] project
[that project] is currently in the [deployment] stage
[knowledge base project] is assigned to [Angelita]
[that person] is working on [chatbot project] also
[Stephine] is a [developer]
[Andrew] is a [developer]
[chatbot project] is assigned to [Andrew]
[Bob] is a [developer]
[Angelita] created a new [proposal] for [knowledge base project]: [memory leak bug]
[the issue] was assigned to [Angelita]
[that test engineer] resolved [the memory leak bug proposal]
What stage is [knowledge base project] in?	'testing'	['question_type_local']
What are the resolved issues?	'memory leak bug'	['question_type_global', 'question_single_statement']
who are the developers?	'Stephine', 'Andrew', 'Bob'	['question_type_global', 'question_single_statement']
Which is the stage of [mobile project]?	'design'	['question_type_local']
[mobile project] is assigned to [she] also
[Racquel] is a [tester]
Are there any [proposal]s that are not resolved?	'memory leak bug'	['question_type_global', 'question_two_hop_statement']
Are there projects in the [testing] stage?	'knowledge base'	['question_type_global', 'question_single_statement']
Who are the testers currently working on projects in the [testing] stage?	'Angelita'	['question_type_global', 'question_three_hop_statement']
[Racquel] is working on [chatbot project]
Who is working on [knowledge base project]?	'Angelita'	['question_type_local']
who are the testers?	'Angelita', 'Racquel'	['question_type_global', 'question_single_statement']
[chatbot project] has moved to the [design] stage
What projects are in the [testing] stage?	'knowledge base'	['question_type_global', 'question_single_statement']
Are there any testers assigned to the [internal] projects?	'Angelita'	['question_type_global', 'question_three_hop_statement']
[Angelita] created a new issue for [knowledge base project]: [initialization broken]
[the issue] is assigned to [Angelita]
Are there any testers assigned to the [platform] projects?	'Angelita'	['question_type_global', 'question_three_hop_statement']
[that test engineer] resolved [it]
[chatbot project] is not assigned to [this tester]
[that person] is assigned to [this project] also
which testers are assigned to [knowledge base project]	'Angelita'	['question_type_local']
Are there any people assigned to the [internal] projects?	'Angelita'	['question_type_global', 'question_two_hop_statement']
Who has issues assigned to them that were all resolved?	'Angelita'	['question_type_global', 'question_two_hop_statement']
Are there any [internal] projects?	'mobile'	['question_type_global', 'question_single_statement']
There is a new [bug] for the [mobile project]: [versioning needs to be made consistent]
[that issue] is assigned to [Angelita]
Who is currently working on the [personal] projects?	'Angelita', 'Andrew', 'Racquel'	['question_type_global', 'question_two_hop_statement']
Who are the testers currently working on projects in the [testing] stage?	'Angelita'	['question_type_global', 'question_three_hop_statement']
What are the non resolved [proposal]s?	'memory leak bug'	['question_type_global', 'question_two_hop_statement']
[Tereasa] is a [tester] on [mobile project]
[Tereasa] is no longer assigned to [mobile project]
[she] is working on [knowledge base project]
[mobile project] is assigned to [Racquel] also
[knowledge base project] is now in the [design] stage
[knowledge base project] is in the [development] stage
Who submitted [the memory leak bug proposal]?	'Angelita'	['question_type_local']
What projects are currently in the [development] stage?	'knowledge base'	['question_type_global', 'question_single_statement']
What are the [proposal]s that are not resolved?	'memory leak bug'	['question_type_global', 'question_two_hop_statement']
[Zenaida] is a [developer]
[this developer] is assigned to [chatbot project]
[this project] is not assigned to [this developer]
[Zenaida] is assigned to [knowledge base project]
What are the issues that are not resolved?	'versioning needs to be made consistent'	['question_type_global', 'question_single_statement']
[Tereasa] is working on [chatbot project] also
Who has issues assigned to them that were all resolved?	'Angelita'	['question_type_global', 'question_two_hop_statement']
What are the resolved issues?	'memory leak bug', 'initialization broken'	['question_type_global', 'question_single_statement']
who are the testers?	'Angelita', 'Racquel', 'Tereasa'	['question_type_global', 'question_single_statement']
What are the [personal] projects?	'chatbot'	['question_type_global', 'question_single_statement']
[that test engineer] is working on [mobile project] also
[it] has moved to the [testing] stage
[that project] is in the stage of [deployment]
Are there any developers assigned to projects in the [design] stage?	'Andrew'	['question_type_global', 'question_three_hop_statement']
What are the issues that were resolved?	'memory leak bug', 'initialization broken'	['question_type_global', 'question_single_statement']
Who is assigned to projects in the [deployment] stage?	'Angelita', 'Racquel', 'Tereasa'	['question_type_global', 'question_two_hop_statement']
Which testers have issues assigned to them that were not resolved?	'Angelita'	['question_type_global', 'question_three_hop_statement']
What are the resolved issues?	'memory leak bug', 'initialization broken'	['question_type_global', 'question_single_statement']
[that project] is now in the [testing] stage
[Zenaida] is not working on [knowledge base project] anymore
Who was [the initialization broken issue] assigned to?	'Angelita'	['question_type_local']
Are there any issues for [mobile project] that are not resolved?	'versioning needs to be made consistent'	['question_type_global', 'question_two_hop_statement']
What are the issues that are not resolved for projects in the [testing] stage?	'versioning needs to be made consistent'	['question_type_global', 'question_three_hop_statement']
[this developer] is working on [chatbot project]
Who has issues assigned to them that were not resolved?	'Angelita'	['question_type_global', 'question_two_hop_statement']
Who submitted [the initialization broken issue]?	'Angelita'	['question_type_local']
Who are the developers currently working on projects in the [design] stage?	'Andrew', 'Zenaida'	['question_type_global', 'question_three_hop_statement']
[mobile project] is assigned to [Zenaida] also
What stage is [chatbot project] in?	'design'	['question_type_local']
Which is the stage of [that project]?	'testing'	['question_type_local']
who are the testers?	'Angelita', 'Racquel', 'Tereasa'	['question_type_global', 'question_single_statement']
Which testers have issues assigned to them that were not resolved?	'Angelita'	['question_type_global', 'question_three_hop_statement']
[she] is assigned to [knowledge base project] also
who are the developers?	'Stephine', 'Andrew', 'Bob', 'Zenaida'	['question_type_global', 'question_single_statement']
Who has issues assigned to them that were all resolved?	'Angelita'	['question_type_global', 'question_two_hop_statement']
What are the non resolved [bug]s?	'versioning needs to be made consistent'	['question_type_global', 'question_two_hop_statement']
Are there any projects that are [internal]?	'mobile'	['question_type_global', 'question_single_statement']
What are the issues assigned to [Angelita]?	'memory leak bug', 'initialization broken', 'versioning needs to be made consistent'	['question_type_local']
Are there any issues that are not resolved?	'versioning needs to be made consistent'	['question_type_global', 'question_single_statement']
who are the testers?	'Angelita', 'Racquel', 'Tereasa'	['question_type_global', 'question_single_statement']
Which testers have issues assigned to them that were all resolved?	'Angelita'	['question_type_global', 'question_three_hop_statement']
What are the issues that are not resolved for projects in the [testing] stage?	'versioning needs to be made consistent'	['question_type_global', 'question_three_hop_statement']
What are the non resolved issues?	'versioning needs to be made consistent'	['question_type_global', 'question_single_statement']
There is a new issue for the [it]: [saving data throws exception]
[the issue] is assigned to [Tereasa]
What are the non resolved issues for projects in the [testing] stage?	'versioning needs to be made consistent'	['question_type_global', 'question_three_hop_statement']
Who has issues assigned to them that were all resolved?	'Angelita'	['question_type_global', 'question_two_hop_statement']
What are the issues that were resolved?	'memory leak bug', 'initialization broken'	['question_type_global', 'question_single_statement']
[Racquel] submitted a new [proposal] for [chatbot project]: [dcoref always returns null]
Are there any [personal] projects?	'chatbot'	['question_type_global', 'question_single_statement']
What are the issues for [chatbot project] that are not resolved?	'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
Are there any [proposal]s that are not resolved?	'memory leak bug'	['question_type_global', 'question_two_hop_statement']
What testers are assigned to the [platform] projects?	'Angelita', 'Tereasa'	['question_type_global', 'question_three_hop_statement']
Are there projects in the [design] stage?	'chatbot'	['question_type_global', 'question_single_statement']
[Roslyn] is a [developer] on [knowledge base project]
[the issue] was assigned to [Zenaida]
What projects is [Roslyn] working on?	'knowledge base'	['question_type_local']
What are the resolved issues?	'memory leak bug', 'initialization broken'	['question_type_global', 'question_single_statement']
Which developers have issues assigned to them that were not resolved?	'Zenaida'	['question_type_global', 'question_three_hop_statement']
What are the issues that are resolved for projects in the [development] stage?	'memory leak bug', 'initialization broken'	['question_type_global', 'question_three_hop_statement']
Who are the developers currently working on the [platform] projects?	'Zenaida', 'Roslyn'	['question_type_global', 'question_three_hop_statement']
What are the non resolved issues for [knowledge base project]?	'saving data throws exception'	['question_type_global', 'question_two_hop_statement']
[Lizeth] is a [tester] on [mobile project]
[Tereasa] created a new issue for [knowledge base project]: [tokenization not consistent across platforms]
[that person] is working on [knowledge base project] also
[this test engineer] is assigned to [chatbot project] also
Who is working on [this project]?	'Angelita', 'Andrew', 'Racquel', 'Tereasa', 'Zenaida', 'Lizeth'	['question_type_local']
Are there any issues that are not resolved for [platform] projects?	'saving data throws exception', 'tokenization not consistent across platforms'	['question_type_global', 'question_two_hop_statement']
Who is [the initialization broken issue] assigned to?	'Angelita'	['question_type_local']
What are the issues that are not resolved?	'versioning needs to be made consistent', 'saving data throws exception', 'dcoref always returns null', 'tokenization not consistent across platforms'	['question_type_global', 'question_single_statement']
What are the non resolved issues for [chatbot project]?	'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
What are the issues that are not resolved for [personal] projects?	'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
Who is assigned to projects in the [testing] stage?	'Angelita', 'Racquel', 'Tereasa', 'Zenaida', 'Lizeth'	['question_type_global', 'question_two_hop_statement']
[Francoise] is a [tester]
Who is working on [knowledge base project]?	'Angelita', 'Tereasa', 'Zenaida', 'Roslyn', 'Lizeth'	['question_type_local']
What projects are [internal]?	'mobile'	['question_type_global', 'question_single_statement']
who are the developers?	'Stephine', 'Andrew', 'Bob', 'Zenaida', 'Roslyn'	['question_type_global', 'question_single_statement']
Which developers have issues assigned to them that were not resolved?	'Zenaida'	['question_type_global', 'question_three_hop_statement']
What testers are assigned to projects in the [testing] stage?	'Angelita', 'Racquel', 'Tereasa', 'Lizeth'	['question_type_global', 'question_three_hop_statement']
who are the testers?	'Angelita', 'Racquel', 'Tereasa', 'Lizeth', 'Francoise'	['question_type_global', 'question_single_statement']
Who submitted [the initialization broken issue]?	'Angelita'	['question_type_local']
Are there any issues that are not resolved for projects in the [testing] stage?	'versioning needs to be made consistent'	['question_type_global', 'question_three_hop_statement']
Are there any [personal] projects?	'chatbot'	['question_type_global', 'question_single_statement']
What are the [proposal]s that are not resolved?	'memory leak bug'	['question_type_global', 'question_two_hop_statement']
[Tereasa] resolved [the saving data throws exception issue]
[knowledge base project] is not assigned to [Zenaida]
Which developers are working on [chatbot project]?	'Andrew', 'Zenaida'	['question_type_local']
Which developers have issues assigned to them that were not resolved?	'Zenaida'	['question_type_global', 'question_three_hop_statement']
Which testers have issues assigned to them that were not resolved?	'Angelita'	['question_type_global', 'question_three_hop_statement']
Who is assigned to the [internal] projects?	'Angelita', 'Racquel', 'Tereasa', 'Zenaida', 'Lizeth'	['question_type_global', 'question_two_hop_statement']
[knowledge base project] is assigned to [that developer] also
[Racquel] is working on [knowledge base project] also
What are the [platform] projects?	'knowledge base'	['question_type_global', 'question_single_statement']
[it] has moved to the [design] stage
[it] has moved to the [testing] stage
[changelong needs to be added] is a new [bug] for the [it]
Are there any issues for [knowledge base project] that are resolved?	'memory leak bug', 'initialization broken', 'saving data throws exception'	['question_type_global', 'question_two_hop_statement']
[this issue] is assigned to [Angelita]
[this tester] resolved [the bug]
What stage is [mobile project] in?	'testing'	['question_type_local']
Who is assigned to the [platform] projects?	'Angelita', 'Racquel', 'Tereasa', 'Zenaida', 'Roslyn', 'Lizeth'	['question_type_global', 'question_two_hop_statement']
What are the issues that were resolved?	'memory leak bug', 'initialization broken', 'saving data throws exception', 'changelong needs to be added'	['question_type_global', 'question_single_statement']
Are there any issues that are not resolved?	'versioning needs to be made consistent', 'dcoref always returns null', 'tokenization not consistent across platforms'	['question_type_global', 'question_single_statement']
[this tester] resolved [the versioning needs to be made consistent bug]
which testers are assigned to [knowledge base project]	'Angelita', 'Racquel', 'Tereasa', 'Lizeth'	['question_type_local']
Who has issues assigned to them that were not resolved?	'Zenaida'	['question_type_global', 'question_two_hop_statement']
What are the issues that are not resolved?	'dcoref always returns null', 'tokenization not consistent across platforms'	['question_type_global', 'question_single_statement']
Who is currently working on projects in the [testing] stage?	'Angelita', 'Racquel', 'Tereasa', 'Zenaida', 'Roslyn', 'Lizeth'	['question_type_global', 'question_two_hop_statement']
[mobile project] has moved to the [deployment] stage
[this project] is not assigned to [this tester]
[Tereasa] submitted a new [task] for [chatbot project]: [xml extractor exception]
Who submitted [the initialization broken issue]?	'Angelita'	['question_type_local']
who are the developers?	'Stephine', 'Andrew', 'Bob', 'Zenaida', 'Roslyn'	['question_type_global', 'question_single_statement']
What testers are assigned to the [platform] projects?	'Angelita', 'Racquel', 'Tereasa', 'Lizeth'	['question_type_global', 'question_three_hop_statement']
What are the issues that are not resolved for projects in the [design] stage?	'dcoref always returns null', 'xml extractor exception'	['question_type_global', 'question_three_hop_statement']
Are there any issues that are resolved for [internal] projects?	'versioning needs to be made consistent'	['question_type_global', 'question_two_hop_statement']
Are there any testers assigned to the [platform] projects?	'Angelita', 'Racquel', 'Tereasa', 'Lizeth'	['question_type_global', 'question_three_hop_statement']
[knowledge base project] has moved to the [development] stage
[Angelita] is working on [mobile project] also
What projects is [Lizeth] working on?	'mobile', 'knowledge base', 'chatbot'	['question_type_local']
What are the non resolved issues for [knowledge base project]?	'tokenization not consistent across platforms'	['question_type_global', 'question_two_hop_statement']
What testers are assigned to the [internal] projects?	'Angelita', 'Racquel', 'Tereasa', 'Lizeth'	['question_type_global', 'question_three_hop_statement']
What are the non resolved [proposal]s?	'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
Who has issues assigned to them that were not resolved?	'Zenaida'	['question_type_global', 'question_two_hop_statement']
[that project] is in the stage of [development]
What are the issues created by [Racquel] that were not resolved?	'dcoref always returns null'	['question_type_local']
Are there any issues that are not resolved?	'dcoref always returns null', 'tokenization not consistent across platforms', 'xml extractor exception'	['question_type_global', 'question_single_statement']
What are the issues that were resolved?	'memory leak bug', 'initialization broken', 'versioning needs to be made consistent', 'saving data throws exception', 'changelong needs to be added'	['question_type_global', 'question_single_statement']
Are there any developers assigned to the [personal] projects?	'Andrew', 'Zenaida'	['question_type_global', 'question_three_hop_statement']
who are the developers?	'Stephine', 'Andrew', 'Bob', 'Zenaida', 'Roslyn'	['question_type_global', 'question_single_statement']
[knowledge base project] is in the [design] stage
What are the issues that are not resolved for [personal] projects?	'dcoref always returns null', 'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are resolved?	'memory leak bug', 'initialization broken', 'versioning needs to be made consistent', 'saving data throws exception', 'changelong needs to be added'	['question_type_global', 'question_single_statement']
Are there any issues that are not resolved for projects in the [design] stage?	'dcoref always returns null', 'tokenization not consistent across platforms', 'xml extractor exception'	['question_type_global', 'question_three_hop_statement']
What are the issues for [knowledge base project] that are resolved?	'memory leak bug', 'initialization broken', 'saving data throws exception', 'changelong needs to be added'	['question_type_global', 'question_two_hop_statement']
[Angelita] is no longer assigned to [chatbot project]
[that test engineer] is assigned to [it] also
Are there any issues that are not resolved for [platform] projects?	'tokenization not consistent across platforms'	['question_type_global', 'question_two_hop_statement']
Which testers have issues assigned to them that were all resolved?	'Angelita', 'Tereasa'	['question_type_global', 'question_three_hop_statement']
What are the issues that were resolved?	'memory leak bug', 'initialization broken', 'versioning needs to be made consistent', 'saving data throws exception', 'changelong needs to be added'	['question_type_global', 'question_single_statement']
What testers are assigned to the [internal] projects?	'Angelita', 'Racquel', 'Tereasa', 'Lizeth'	['question_type_global', 'question_three_hop_statement']
What are the [proposal]s that are not resolved?	'memory leak bug'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are not resolved?	'dcoref always returns null', 'tokenization not consistent across platforms', 'xml extractor exception'	['question_type_global', 'question_single_statement']
What are the non resolved issues for [platform] projects?	'tokenization not consistent across platforms'	['question_type_global', 'question_two_hop_statement']
What are the non resolved [proposal]s?	'memory leak bug'	['question_type_global', 'question_two_hop_statement']
Which testers have issues assigned to them that were all resolved?	'Angelita', 'Tereasa'	['question_type_global', 'question_three_hop_statement']
[Roslyn] is assigned to [mobile project] also
[this developer] is assigned to [chatbot project] also
[knowledge base project] is not assigned to [she]
[this project] is assigned to [Roslyn] also
Are there any testers assigned to the [personal] projects?	'Angelita', 'Racquel', 'Tereasa', 'Lizeth'	['question_type_global', 'question_three_hop_statement']
Which developers have issues assigned to them that were not resolved?	'Zenaida'	['question_type_global', 'question_three_hop_statement']
What are the issues that were resolved?	'memory leak bug', 'initialization broken', 'versioning needs to be made consistent', 'saving data throws exception', 'changelong needs to be added'	['question_type_global', 'question_single_statement']
Are there any [internal] projects?	'mobile'	['question_type_global', 'question_single_statement']
Who submitted [the memory leak bug issue]?	'Angelita'	['question_type_local']
Are there any projects that are [platform]?	'knowledge base'	['question_type_global', 'question_single_statement']
Are there any testers assigned to the [internal] projects?	'Angelita', 'Racquel', 'Tereasa', 'Lizeth'	['question_type_global', 'question_three_hop_statement']
[Angelita] is not working on [knowledge base project] anymore
[it] is assigned to [that person] also
What are the issues that were resolved?	'memory leak bug', 'initialization broken', 'versioning needs to be made consistent', 'saving data throws exception', 'changelong needs to be added'	['question_type_global', 'question_single_statement']
Who is currently working on the [platform] projects?	'Angelita', 'Racquel', 'Tereasa', 'Zenaida', 'Roslyn', 'Lizeth'	['question_type_global', 'question_two_hop_statement']
Which testers have issues assigned to them that were all resolved?	'Angelita', 'Tereasa'	['question_type_global', 'question_three_hop_statement']
Who created [the task]?	'Tereasa'	['question_type_local']
What are the resolved issues for [platform] projects?	'memory leak bug', 'initialization broken', 'saving data throws exception', 'changelong needs to be added'	['question_type_global', 'question_two_hop_statement']
Who are the developers currently working on projects in the [development] stage?	'Zenaida', 'Roslyn'	['question_type_global', 'question_three_hop_statement']
Who are the developers currently working on the [internal] projects?	'Zenaida', 'Roslyn'	['question_type_global', 'question_three_hop_statement']
who are the developers?	'Stephine', 'Andrew', 'Bob', 'Zenaida', 'Roslyn'	['question_type_global', 'question_single_statement']
Who has issues assigned to them that were all resolved?	'Angelita', 'Tereasa'	['question_type_global', 'question_two_hop_statement']
[the tokenization not consistent across platforms issue] is assigned to [Zenaida]
[Zenaida] resolved [that issue]
Who is [the memory leak bug proposal] assigned to?	'Angelita'	['question_type_local']
Are there any developers assigned to projects in the [development] stage?	'Zenaida', 'Roslyn'	['question_type_global', 'question_three_hop_statement']
Who are the testers currently working on projects in the [development] stage?	'Angelita', 'Racquel', 'Tereasa', 'Lizeth'	['question_type_global', 'question_three_hop_statement']
Which developers have issues assigned to them that were not resolved?	'Zenaida'	['question_type_global', 'question_three_hop_statement']
Are there any [proposal]s that are not resolved?	'memory leak bug'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are resolved for projects in the [development] stage?	'versioning needs to be made consistent'	['question_type_global', 'question_three_hop_statement']
What are the issues assigned to [that person] that were resolved?	'tokenization not consistent across platforms'	['question_type_local']
What are the resolved issues?	'memory leak bug', 'initialization broken', 'versioning needs to be made consistent', 'saving data throws exception', 'tokenization not consistent across platforms', 'changelong needs to be added'	['question_type_global', 'question_single_statement']
What stage is [chatbot project] in?	'design'	['question_type_local']
Are there any developers assigned to projects in the [design] stage?	'Andrew', 'Zenaida', 'Roslyn'	['question_type_global', 'question_three_hop_statement']
Who is currently working on the [platform] projects?	'Angelita', 'Racquel', 'Tereasa', 'Zenaida', 'Roslyn', 'Lizeth'	['question_type_global', 'question_two_hop_statement']
Who has issues assigned to them that were all resolved?	'Angelita', 'Tereasa', 'Zenaida'	['question_type_global', 'question_two_hop_statement']
Who has issues assigned to them that were not resolved?	'Zenaida'	['question_type_global', 'question_two_hop_statement']
who are the testers?	'Angelita', 'Racquel', 'Tereasa', 'Lizeth', 'Francoise'	['question_type_global', 'question_single_statement']
Who are the testers on [knowledge base project]	'Angelita', 'Racquel', 'Tereasa', 'Lizeth'	['question_type_local']
Are there any projects that are [platform]?	'knowledge base'	['question_type_global', 'question_single_statement']
Who are the testers currently working on the [personal] projects?	'Angelita', 'Racquel', 'Tereasa', 'Lizeth'	['question_type_global', 'question_three_hop_statement']
What are the [personal] projects?	'chatbot'	['question_type_global', 'question_single_statement']
What are the issues assigned to [Angelita] that were resolved?	'memory leak bug', 'initialization broken', 'versioning needs to be made consistent', 'changelong needs to be added'	['question_type_local']
Who has issues assigned to them that were not resolved?	'Zenaida'	['question_type_global', 'question_two_hop_statement']
Who has issues assigned to them that were all resolved?	'Angelita', 'Tereasa', 'Zenaida'	['question_type_global', 'question_two_hop_statement']
Are there any issues for [chatbot project] that are not resolved?	'dcoref always returns null', 'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
Who was [the memory leak bug proposal] assigned to?	'Angelita'	['question_type_local']
What are the non resolved issues?	'dcoref always returns null', 'xml extractor exception'	['question_type_global', 'question_single_statement']
Are there any developers assigned to projects in the [design] stage?	'Andrew', 'Zenaida', 'Roslyn'	['question_type_global', 'question_three_hop_statement']
Which developers have issues assigned to them that were not resolved?	'Zenaida'	['question_type_global', 'question_three_hop_statement']
What projects is [Angelita] working on?	'mobile', 'knowledge base', 'chatbot'	['question_type_local']
What projects are in the [design] stage?	'knowledge base', 'chatbot'	['question_type_global', 'question_single_statement']
What are the resolved issues for projects in the [design] stage?	'memory leak bug', 'initialization broken', 'saving data throws exception', 'tokenization not consistent across platforms', 'changelong needs to be added'	['question_type_global', 'question_three_hop_statement']
Are there any issues that are not resolved for [personal] projects?	'dcoref always returns null', 'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
[that person] is not working on [knowledge base project] anymore
Are there any people assigned to the [platform] projects?	'Angelita', 'Racquel', 'Tereasa', 'Roslyn', 'Lizeth'	['question_type_global', 'question_two_hop_statement']
Who has issues assigned to them that were not resolved?	'Zenaida'	['question_type_global', 'question_two_hop_statement']
[this project] is assigned to [Zenaida] also
[mobile project] is assigned to [Andrew] also
[that developer] is working on [knowledge base project] also
Who is [the tokenization not consistent across platforms issue] assigned to?	'Zenaida'	['question_type_local']
Who has issues assigned to them that were all resolved?	'Angelita', 'Tereasa', 'Zenaida'	['question_type_global', 'question_two_hop_statement']
What are the non resolved issues?	'dcoref always returns null', 'xml extractor exception'	['question_type_global', 'question_single_statement']
which testers are assigned to [mobile project]	'Angelita', 'Racquel', 'Tereasa', 'Lizeth'	['question_type_local']
Which testers have issues assigned to them that were all resolved?	'Angelita', 'Tereasa'	['question_type_global', 'question_three_hop_statement']
What are the issues that are not resolved for [personal] projects?	'dcoref always returns null', 'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
What are the [proposal]s that are not resolved?	'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
What projects are in the [design] stage?	'knowledge base', 'chatbot'	['question_type_global', 'question_single_statement']
[mobile project] is in the [design] stage
What stage is [chatbot project] in?	'design'	['question_type_local']
What are the non resolved issues?	'dcoref always returns null', 'xml extractor exception'	['question_type_global', 'question_single_statement']
Which developers are assigned to [chatbot project]	'Andrew', 'Zenaida', 'Roslyn'	['question_type_local']
Are there any testers assigned to projects in the [design] stage?	'Angelita', 'Racquel', 'Tereasa', 'Lizeth'	['question_type_global', 'question_three_hop_statement']
Which testers have issues assigned to them that were all resolved?	'Angelita', 'Tereasa'	['question_type_global', 'question_three_hop_statement']
Who is assigned to projects in the [design] stage?	'Angelita', 'Andrew', 'Racquel', 'Tereasa', 'Zenaida', 'Roslyn', 'Lizeth'	['question_type_global', 'question_two_hop_statement']
What are the issues that are not resolved?	'dcoref always returns null', 'xml extractor exception'	['question_type_global', 'question_single_statement']
Are there any issues for [mobile project] that are resolved?	'versioning needs to be made consistent'	['question_type_global', 'question_two_hop_statement']
Are there any developers assigned to projects in the [design] stage?	'Andrew', 'Zenaida', 'Roslyn'	['question_type_global', 'question_three_hop_statement']
[knowledge base project] is in the stage of [testing]
Which testers are working on [chatbot project]?	'Angelita', 'Racquel', 'Tereasa', 'Lizeth'	['question_type_local']
who are the developers?	'Stephine', 'Andrew', 'Bob', 'Zenaida', 'Roslyn'	['question_type_global', 'question_single_statement']
Which testers have issues assigned to them that were all resolved?	'Angelita', 'Tereasa'	['question_type_global', 'question_three_hop_statement']
What are the [bug]s that are not resolved?	'versioning needs to be made consistent', 'changelong needs to be added'	['question_type_global', 'question_two_hop_statement']
Who is [the tokenization not consistent across platforms issue] assigned to?	'Zenaida'	['question_type_local']
Are there any projects that are [platform]?	'knowledge base'	['question_type_global', 'question_single_statement']
Who is working on [mobile project]?	'Angelita', 'Andrew', 'Racquel', 'Tereasa', 'Zenaida', 'Roslyn', 'Lizeth'	['question_type_local']
Who is assigned to the [platform] projects?	'Angelita', 'Andrew', 'Racquel', 'Tereasa', 'Zenaida', 'Roslyn', 'Lizeth'	['question_type_global', 'question_two_hop_statement']
What are the issues that are not resolved?	'dcoref always returns null', 'xml extractor exception'	['question_type_global', 'question_single_statement']
Are there any people assigned to the [personal] projects?	'Angelita', 'Andrew', 'Racquel', 'Tereasa', 'Zenaida', 'Roslyn', 'Lizeth'	['question_type_global', 'question_two_hop_statement']
[mobile project] has moved to the [development] stage
Which developers are assigned to [knowledge base project]	'Andrew', 'Zenaida', 'Roslyn'	['question_type_local']
What testers are assigned to projects in the [development] stage?	'Angelita', 'Racquel', 'Tereasa', 'Lizeth'	['question_type_global', 'question_three_hop_statement']
What are the [bug]s that are not resolved?	'versioning needs to be made consistent', 'changelong needs to be added'	['question_type_global', 'question_two_hop_statement']
Who has issues assigned to them that were all resolved?	'Angelita', 'Tereasa', 'Zenaida'	['question_type_global', 'question_two_hop_statement']
Which testers have issues assigned to them that were all resolved?	'Angelita', 'Tereasa'	['question_type_global', 'question_three_hop_statement']
Who is assigned to the [internal] projects?	'Angelita', 'Andrew', 'Racquel', 'Tereasa', 'Zenaida', 'Roslyn', 'Lizeth'	['question_type_global', 'question_two_hop_statement']
Who is working on [mobile project]?	'Angelita', 'Andrew', 'Racquel', 'Tereasa', 'Zenaida', 'Roslyn', 'Lizeth'	['question_type_local']
Who is currently working on the [personal] projects?	'Angelita', 'Andrew', 'Racquel', 'Tereasa', 'Zenaida', 'Roslyn', 'Lizeth'	['question_type_global', 'question_two_hop_statement']
[mobile project] has moved to the [deployment] stage
What are the non resolved issues?	'dcoref always returns null', 'xml extractor exception'	['question_type_global', 'question_single_statement']
What are the issues that are not resolved?	'dcoref always returns null', 'xml extractor exception'	['question_type_global', 'question_single_statement']
Who are the developers currently working on the [personal] projects?	'Andrew', 'Zenaida', 'Roslyn'	['question_type_global', 'question_three_hop_statement']
[it] is now in the [testing] stage
Who are the testers on [it]	'Angelita', 'Racquel', 'Tereasa', 'Lizeth'	['question_type_local']
Who has issues assigned to them that were all resolved?	'Angelita', 'Tereasa', 'Zenaida'	['question_type_global', 'question_two_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Zenaida'	['question_type_global', 'question_three_hop_statement']
[it] is in the [development] stage
Who was [the dcoref always returns null issue] assigned to?	'Zenaida'	['question_type_local']
Which developers have issues assigned to them that were not resolved?	'Zenaida'	['question_type_global', 'question_three_hop_statement']
What are the issues that were resolved?	'memory leak bug', 'initialization broken', 'versioning needs to be made consistent', 'saving data throws exception', 'tokenization not consistent across platforms', 'changelong needs to be added'	['question_type_global', 'question_single_statement']
What are the non resolved issues for projects in the [design] stage?	'dcoref always returns null', 'xml extractor exception'	['question_type_global', 'question_three_hop_statement']
Are there any developers assigned to the [personal] projects?	'Andrew', 'Zenaida', 'Roslyn'	['question_type_global', 'question_three_hop_statement']
What projects is [Tereasa] working on?	'mobile', 'knowledge base', 'chatbot'	['question_type_local']
Who are the developers currently working on the [personal] projects?	'Andrew', 'Zenaida', 'Roslyn'	['question_type_global', 'question_three_hop_statement']
Are there any people assigned to the [personal] projects?	'Angelita', 'Andrew', 'Racquel', 'Tereasa', 'Zenaida', 'Roslyn', 'Lizeth'	['question_type_global', 'question_two_hop_statement']
Who has issues assigned to them that were all resolved?	'Angelita', 'Tereasa', 'Zenaida'	['question_type_global', 'question_two_hop_statement']
[it] is in the stage of [testing]
Which developers have issues assigned to them that were all resolved?	'Zenaida'	['question_type_global', 'question_three_hop_statement']
[Angelita] is not working on [chatbot project] anymore
[chatbot project] is assigned to [Angelita] also
What are the issues that are not resolved?	'dcoref always returns null', 'xml extractor exception'	['question_type_global', 'question_single_statement']
What projects are currently in the [design] stage?	'chatbot'	['question_type_global', 'question_single_statement']
What are the issues for [mobile project] that are resolved?	'versioning needs to be made consistent'	['question_type_global', 'question_two_hop_statement']
[this project] is now in the [testing] stage
What projects is [Roslyn] working on?	'mobile', 'knowledge base', 'chatbot'	['question_type_local']
Which developers have issues assigned to them that were not resolved?	'Zenaida'	['question_type_global', 'question_three_hop_statement']
Who is assigned to projects in the [testing] stage?	'Angelita', 'Andrew', 'Racquel', 'Tereasa', 'Zenaida', 'Roslyn', 'Lizeth'	['question_type_global', 'question_two_hop_statement']
[chatbot project] has moved to the [development] stage
