there is a new [corporate] [knowledge base] [project]
[knowledge base project] is in the [testing] stage
What projects are in the [testing] stage?	'knowledge base'	['question_type_global', 'question_single_statement']
What projects are currently in the [testing] stage?	'knowledge base'	['question_type_global', 'question_single_statement']
[knowledge base project] is in the [development] stage
there is a new [corporate] [chatbot] [project]
[chatbot project] is in the stage of [development]
there is a new [personal] [mobile] [project]
[Roslyn] is a [developer] on [mobile project]
[mobile project] is currently in the [development] stage
[Michael] is a [tester] on [chatbot project]
[it] is assigned to [this tester] also
[that person] is working on [knowledge base project] also
What stage is [that project] in?	'development'	['question_type_local']
who are the testers?	'Michael'	['question_type_global', 'question_single_statement']
Who is working on [that project]?	'Michael'	['question_type_local']
Who are the developers currently working on projects in the [development] stage?	'Roslyn'	['question_type_global', 'question_three_hop_statement']
What testers are assigned to projects in the [development] stage?	'Michael'	['question_type_global', 'question_three_hop_statement']
What projects are in the [development] stage?	'knowledge base', 'chatbot', 'mobile'	['question_type_global', 'question_single_statement']
What are the [corporate] projects?	'knowledge base', 'chatbot'	['question_type_global', 'question_single_statement']
Who are the developers currently working on the [personal] projects?	'Roslyn'	['question_type_global', 'question_three_hop_statement']
[parsing with parantheses fails] is a new [enhancement] created by [that person] for [this project]
[that issue] was assigned to [Michael]
[this person] resolved [the enhancement]
Who is working on [chatbot project]?	'Michael'	['question_type_local']
[Genevive] is a [tester]
[chatbot project] is assigned to [she]
[timeout problem] is a new [proposal] created by [Michael] for [knowledge base project]
[this issue] is assigned to [Michael]
[this person] resolved [the issue]
Which is the stage of [mobile project]?	'development'	['question_type_local']
Who are the developers currently working on projects in the [development] stage?	'Roslyn'	['question_type_global', 'question_three_hop_statement']
Are there any testers assigned to the [corporate] projects?	'Michael', 'Genevive'	['question_type_global', 'question_three_hop_statement']
who are the developers?	'Roslyn'	['question_type_global', 'question_single_statement']
What are the non resolved [proposal]s?	'timeout problem'	['question_type_global', 'question_two_hop_statement']
What are the resolved issues for [knowledge base project]?	'parsing with parantheses fails', 'timeout problem'	['question_type_global', 'question_two_hop_statement']
Are there any people assigned to projects in the [development] stage?	'Roslyn', 'Michael', 'Genevive'	['question_type_global', 'question_two_hop_statement']
Are there any developers assigned to the [personal] projects?	'Roslyn'	['question_type_global', 'question_three_hop_statement']
Are there any developers assigned to projects in the [development] stage?	'Roslyn'	['question_type_global', 'question_three_hop_statement']
Are there any issues that are resolved?	'parsing with parantheses fails', 'timeout problem'	['question_type_global', 'question_single_statement']
[chatbot project] is assigned to [Roslyn] also
Which testers are working on [it]?	'Michael', 'Genevive'	['question_type_local']
What are the non resolved [proposal]s?	'timeout problem'	['question_type_global', 'question_two_hop_statement']
Who are the developers currently working on the [personal] projects?	'Roslyn'	['question_type_global', 'question_three_hop_statement']
There is a new issue for the [mobile project]: [initialization broken]
[Genevive] created a new issue for [that project]: [tokenization not consistent across platforms]
[the tokenization not consistent across platforms issue] is assigned to [Michael]
[Michael] resolved [this issue]
Who is [this issue] assigned to?	'Michael'	['question_type_local']
Who has issues assigned to them that were all resolved?	'Michael'	['question_type_global', 'question_two_hop_statement']
[Angelita] is a [tester] on [knowledge base project]
[mobile project] is assigned to [she] also
Which developers are working on [chatbot project]?	'Roslyn'	['question_type_local']
Who are the testers currently working on the [corporate] projects?	'Michael', 'Genevive', 'Angelita'	['question_type_global', 'question_three_hop_statement']
Who are the developers currently working on projects in the [development] stage?	'Roslyn'	['question_type_global', 'question_three_hop_statement']
Are there any people assigned to projects in the [development] stage?	'Roslyn', 'Michael', 'Genevive', 'Angelita'	['question_type_global', 'question_two_hop_statement']
[that test engineer] is working on [chatbot project] also
Who submitted [the tokenization not consistent across platforms issue]?	'Genevive'	['question_type_local']
Are there any developers assigned to projects in the [development] stage?	'Roslyn'	['question_type_global', 'question_three_hop_statement']
What are the resolved issues?	'parsing with parantheses fails', 'timeout problem', 'tokenization not consistent across platforms'	['question_type_global', 'question_single_statement']
who are the testers?	'Michael', 'Genevive', 'Angelita'	['question_type_global', 'question_single_statement']
Who are the testers currently working on projects in the [development] stage?	'Michael', 'Genevive', 'Angelita'	['question_type_global', 'question_three_hop_statement']
What developers are assigned to projects in the [development] stage?	'Roslyn'	['question_type_global', 'question_three_hop_statement']
Who has issues assigned to them that were all resolved?	'Michael'	['question_type_global', 'question_two_hop_statement']
[Genevive] is working on [mobile project] also
[Andrew] is a [developer]
What stage is [it] in?	'development'	['question_type_local']
What are the non resolved issues?	'initialization broken'	['question_type_global', 'question_single_statement']
Who is assigned to the [personal] projects?	'Roslyn', 'Michael', 'Genevive', 'Angelita'	['question_type_global', 'question_two_hop_statement']
Are there any developers assigned to the [personal] projects?	'Roslyn'	['question_type_global', 'question_three_hop_statement']
[Gia] is a [developer] on [mobile project]
[mobile project] is assigned to [Andrew]
Which is the stage of [chatbot project]?	'development'	['question_type_local']
who are the developers?	'Roslyn', 'Andrew', 'Gia'	['question_type_global', 'question_single_statement']
[versioning needs to be made consistent] is a new [proposal] for [mobile project] that [Roslyn] just created
Who has issues assigned to them that were all resolved?	'Michael'	['question_type_global', 'question_two_hop_statement']
Which testers have issues assigned to them that were all resolved?	'Michael'	['question_type_global', 'question_three_hop_statement']
[that issue] was assigned to [Genevive]
[Genevive] resolved [the versioning needs to be made consistent issue]
Who was [the tokenization not consistent across platforms issue] assigned to?	'Michael'	['question_type_local']
Are there any issues for [chatbot project] that are resolved?	'tokenization not consistent across platforms'	['question_type_global', 'question_two_hop_statement']
What testers are assigned to the [personal] projects?	'Michael', 'Genevive', 'Angelita'	['question_type_global', 'question_three_hop_statement']
What projects are in the [development] stage?	'knowledge base', 'chatbot', 'mobile'	['question_type_global', 'question_single_statement']
Are there any developers assigned to the [personal] projects?	'Roslyn', 'Andrew', 'Gia'	['question_type_global', 'question_three_hop_statement']
There is a new issue for the [mobile project]: [dcoref always returns null]
[that test engineer] is working on [knowledge base project] also
[Will] is a [developer] on [chatbot project]
[Gia] created a new issue for [mobile project]: [xml extractor exception]
[that issue] is assigned to [Andrew]
[this developer] is assigned to [knowledge base project] also
Who is working on [knowledge base project]?	'Michael', 'Genevive', 'Angelita', 'Andrew'	['question_type_local']
What are the issues that are not resolved?	'initialization broken', 'dcoref always returns null', 'xml extractor exception'	['question_type_global', 'question_single_statement']
[that developer] is assigned to [chatbot project] also
What projects is [Michael] working on?	'knowledge base', 'chatbot', 'mobile'	['question_type_local']
What are the issues submitted by [Michael] that were resolved?	'parsing with parantheses fails', 'timeout problem'	['question_type_local']
Are there any people assigned to the [corporate] projects?	'Roslyn', 'Michael', 'Genevive', 'Angelita', 'Andrew', 'Will'	['question_type_global', 'question_two_hop_statement']
Are there any developers assigned to projects in the [development] stage?	'Roslyn', 'Andrew', 'Gia', 'Will'	['question_type_global', 'question_three_hop_statement']
Who has issues assigned to them that were all resolved?	'Michael', 'Genevive'	['question_type_global', 'question_two_hop_statement']
[Bob] is a [tester]
[this tester] is working on [knowledge base project]
Who is working on [chatbot project]?	'Roslyn', 'Michael', 'Genevive', 'Angelita', 'Andrew', 'Will'	['question_type_local']
What are the resolved issues for [mobile project]?	'versioning needs to be made consistent'	['question_type_global', 'question_two_hop_statement']
Which developers have issues assigned to them that were not resolved?	'Andrew'	['question_type_global', 'question_three_hop_statement']
[it] is now in the [implementation] stage
Are there any issues that are not resolved?	'initialization broken', 'dcoref always returns null', 'xml extractor exception'	['question_type_global', 'question_single_statement']
What are the resolved issues for projects in the [development] stage?	'tokenization not consistent across platforms', 'versioning needs to be made consistent'	['question_type_global', 'question_three_hop_statement']
Who is currently working on projects in the [implementation] stage?	'Michael', 'Genevive', 'Angelita', 'Andrew', 'Bob'	['question_type_global', 'question_two_hop_statement']
who are the testers?	'Michael', 'Genevive', 'Angelita', 'Bob'	['question_type_global', 'question_single_statement']
Are there any issues assigned to [Michael] that are resolved?	'parsing with parantheses fails', 'timeout problem', 'tokenization not consistent across platforms'	['question_type_local']
What are the issues that are not resolved?	'initialization broken', 'dcoref always returns null', 'xml extractor exception'	['question_type_global', 'question_single_statement']
What are the [proposal]s that are not resolved?	'timeout problem', 'versioning needs to be made consistent'	['question_type_global', 'question_two_hop_statement']
What testers are assigned to the [personal] projects?	'Michael', 'Genevive', 'Angelita'	['question_type_global', 'question_three_hop_statement']
Which developers have issues assigned to them that were not resolved?	'Andrew'	['question_type_global', 'question_three_hop_statement']
Who is [the tokenization not consistent across platforms issue] assigned to?	'Michael'	['question_type_local']
Are there any issues for [mobile project] that are not resolved?	'initialization broken', 'dcoref always returns null', 'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
who are the testers?	'Michael', 'Genevive', 'Angelita', 'Bob'	['question_type_global', 'question_single_statement']
Are there any issues that are not resolved for projects in the [development] stage?	'initialization broken', 'dcoref always returns null', 'xml extractor exception'	['question_type_global', 'question_three_hop_statement']
[the initialization broken issue] was assigned to [Genevive]
[Roslyn] is working on [knowledge base project] also
[Andrew] resolved [the xml extractor exception issue]
What are the non resolved issues for projects in the [development] stage?	'initialization broken', 'dcoref always returns null'	['question_type_global', 'question_three_hop_statement']
[he] is no longer assigned to [knowledge base project]
[Andrew] is assigned to [that project] also
Who was [the timeout problem issue] assigned to?	'Michael'	['question_type_local']
who are the developers?	'Roslyn', 'Andrew', 'Gia', 'Will'	['question_type_global', 'question_single_statement']
Who are the developers currently working on the [personal] projects?	'Roslyn', 'Andrew', 'Gia'	['question_type_global', 'question_three_hop_statement']
Who has issues assigned to them that were not resolved?	'Genevive'	['question_type_global', 'question_two_hop_statement']
What are the issues that are resolved for projects in the [development] stage?	'tokenization not consistent across platforms', 'versioning needs to be made consistent', 'xml extractor exception'	['question_type_global', 'question_three_hop_statement']
What are the issues that are resolved for [personal] projects?	'versioning needs to be made consistent', 'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
[Michael] is no longer assigned to [mobile project]
[he] is working on [mobile project] also
Are there any testers assigned to projects in the [development] stage?	'Michael', 'Genevive', 'Angelita'	['question_type_global', 'question_three_hop_statement']
Who are the testers currently working on the [personal] projects?	'Michael', 'Genevive', 'Angelita'	['question_type_global', 'question_three_hop_statement']
Which testers have issues assigned to them that were not resolved?	'Genevive'	['question_type_global', 'question_three_hop_statement']
Which testers have issues assigned to them that were all resolved?	'Michael', 'Genevive'	['question_type_global', 'question_three_hop_statement']
What are the issues that are not resolved for [personal] projects?	'initialization broken', 'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
[Genevive] resolved [the initialization broken issue]
[Andrew] is no longer assigned to [knowledge base project]
Which developers have issues assigned to them that were all resolved?	'Andrew'	['question_type_global', 'question_three_hop_statement']
What are the issues for [mobile project] that are resolved?	'initialization broken', 'versioning needs to be made consistent', 'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
What projects are currently in the [development] stage?	'chatbot', 'mobile'	['question_type_global', 'question_single_statement']
Who submitted [the versioning needs to be made consistent proposal]?	'Roslyn'	['question_type_local']
Are there any issues for [mobile project] that are not resolved?	'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
[Andrew] is working on [knowledge base project] also
What projects is [Angelita] working on?	'knowledge base', 'chatbot', 'mobile'	['question_type_local']
What developers are assigned to the [corporate] projects?	'Roslyn', 'Andrew', 'Will'	['question_type_global', 'question_three_hop_statement']
[Bob] is working on [mobile project] also
What are the issues for [chatbot project] that are resolved?	'tokenization not consistent across platforms'	['question_type_global', 'question_two_hop_statement']
[that test engineer] is working on [chatbot project] also
[knowledge base project] is not assigned to [this test engineer]
Who submitted [the timeout problem issue]?	'Michael'	['question_type_local']
Who is currently working on the [personal] projects?	'Roslyn', 'Michael', 'Genevive', 'Angelita', 'Andrew', 'Gia', 'Bob'	['question_type_global', 'question_two_hop_statement']
What are the non resolved [proposal]s?	'timeout problem', 'versioning needs to be made consistent'	['question_type_global', 'question_two_hop_statement']
[Will] is assigned to [it] also
[mobile project] is assigned to [this person] also
What projects is [Andrew] working on?	'knowledge base', 'chatbot', 'mobile'	['question_type_local']
Who is currently working on projects in the [implementation] stage?	'Roslyn', 'Michael', 'Genevive', 'Angelita', 'Andrew', 'Will'	['question_type_global', 'question_two_hop_statement']
Who is assigned to the [corporate] projects?	'Roslyn', 'Michael', 'Genevive', 'Angelita', 'Andrew', 'Will', 'Bob'	['question_type_global', 'question_two_hop_statement']
What projects are currently in the [implementation] stage?	'knowledge base'	['question_type_global', 'question_single_statement']
Were there any issues submitted by [Gia]?	'xml extractor exception'	['question_type_local']
Who has issues assigned to them that were all resolved?	'Michael', 'Genevive', 'Andrew'	['question_type_global', 'question_two_hop_statement']
Who is currently working on the [corporate] projects?	'Roslyn', 'Michael', 'Genevive', 'Angelita', 'Andrew', 'Will', 'Bob'	['question_type_global', 'question_two_hop_statement']
Are there any people assigned to the [personal] projects?	'Roslyn', 'Michael', 'Genevive', 'Angelita', 'Andrew', 'Gia', 'Will', 'Bob'	['question_type_global', 'question_two_hop_statement']
Are there any issues for [this project] that are not resolved?	'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
who are the developers?	'Roslyn', 'Andrew', 'Gia', 'Will'	['question_type_global', 'question_single_statement']
who are the testers?	'Michael', 'Genevive', 'Angelita', 'Bob'	['question_type_global', 'question_single_statement']
Are there any developers assigned to the [corporate] projects?	'Roslyn', 'Andrew', 'Will'	['question_type_global', 'question_three_hop_statement']
Who was [the proposal that was last added] assigned to?	'Genevive'	['question_type_local']
Who has issues assigned to them that were all resolved?	'Michael', 'Genevive', 'Andrew'	['question_type_global', 'question_two_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Andrew'	['question_type_global', 'question_three_hop_statement']
Which testers have issues assigned to them that were all resolved?	'Michael', 'Genevive'	['question_type_global', 'question_three_hop_statement']
What projects is [Gia] working on?	'mobile'	['question_type_local']
What are the issues for [chatbot project] that are resolved?	'tokenization not consistent across platforms'	['question_type_global', 'question_two_hop_statement']
Are there any people assigned to projects in the [implementation] stage?	'Roslyn', 'Michael', 'Genevive', 'Angelita', 'Andrew', 'Will'	['question_type_global', 'question_two_hop_statement']
Who are the developers on [chatbot project]	'Roslyn', 'Andrew', 'Will'	['question_type_local']
Who are the testers currently working on projects in the [implementation] stage?	'Michael', 'Genevive', 'Angelita'	['question_type_global', 'question_three_hop_statement']
Are there any issues for [that project] that are not resolved?	'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
[Bob] is working on [knowledge base project] also
What are the resolved issues for [chatbot project]?	'tokenization not consistent across platforms'	['question_type_global', 'question_two_hop_statement']
What are the [personal] projects?	'mobile'	['question_type_global', 'question_single_statement']
What are the [enhancement]s that are not resolved?	'parsing with parantheses fails'	['question_type_global', 'question_two_hop_statement']
Who is [the parsing with parantheses fails issue] assigned to?	'Michael'	['question_type_local']
What are the issues for [chatbot project] that are resolved?	'tokenization not consistent across platforms'	['question_type_global', 'question_two_hop_statement']
Who is assigned to projects in the [development] stage?	'Roslyn', 'Michael', 'Genevive', 'Angelita', 'Andrew', 'Gia', 'Will', 'Bob'	['question_type_global', 'question_two_hop_statement']
Are there any testers assigned to the [personal] projects?	'Michael', 'Genevive', 'Angelita', 'Bob'	['question_type_global', 'question_three_hop_statement']
What are the issues submitted by [Michael] that were resolved?	'parsing with parantheses fails', 'timeout problem'	['question_type_local']
What are the resolved issues?	'parsing with parantheses fails', 'timeout problem', 'initialization broken', 'tokenization not consistent across platforms', 'versioning needs to be made consistent', 'xml extractor exception'	['question_type_global', 'question_single_statement']
Are there any developers assigned to projects in the [implementation] stage?	'Roslyn', 'Andrew', 'Will'	['question_type_global', 'question_three_hop_statement']
Are there any developers assigned to the [corporate] projects?	'Roslyn', 'Andrew', 'Will'	['question_type_global', 'question_three_hop_statement']
Are there any [corporate] projects?	'knowledge base', 'chatbot'	['question_type_global', 'question_single_statement']
who are the testers?	'Michael', 'Genevive', 'Angelita', 'Bob'	['question_type_global', 'question_single_statement']
Are there any issues for [chatbot project] that are resolved?	'tokenization not consistent across platforms'	['question_type_global', 'question_two_hop_statement']
What projects are [personal]?	'mobile'	['question_type_global', 'question_single_statement']
Are there any issues that are resolved for [personal] projects?	'initialization broken', 'versioning needs to be made consistent', 'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
Are there any people assigned to the [personal] projects?	'Roslyn', 'Michael', 'Genevive', 'Angelita', 'Andrew', 'Gia', 'Will', 'Bob'	['question_type_global', 'question_two_hop_statement']
What are the issues that are not resolved?	'dcoref always returns null'	['question_type_global', 'question_single_statement']
[it] is in the [testing] stage
Who is working on [this project]?	'Roslyn', 'Michael', 'Genevive', 'Angelita', 'Andrew', 'Will', 'Bob'	['question_type_local']
What are the resolved issues for [personal] projects?	'initialization broken', 'versioning needs to be made consistent', 'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
Are there any issues for [chatbot project] that are resolved?	'tokenization not consistent across platforms'	['question_type_global', 'question_two_hop_statement']
Who is assigned to the [corporate] projects?	'Roslyn', 'Michael', 'Genevive', 'Angelita', 'Andrew', 'Will', 'Bob'	['question_type_global', 'question_two_hop_statement']
What projects are in the [testing] stage?	'knowledge base'	['question_type_global', 'question_single_statement']
Which developers have issues assigned to them that were all resolved?	'Andrew'	['question_type_global', 'question_three_hop_statement']
Are there any testers assigned to the [personal] projects?	'Michael', 'Genevive', 'Angelita', 'Bob'	['question_type_global', 'question_three_hop_statement']
who are the developers?	'Roslyn', 'Andrew', 'Gia', 'Will'	['question_type_global', 'question_single_statement']
What are the issues that are resolved for projects in the [development] stage?	'initialization broken', 'tokenization not consistent across platforms', 'versioning needs to be made consistent', 'xml extractor exception'	['question_type_global', 'question_three_hop_statement']
Which testers have issues assigned to them that were all resolved?	'Michael', 'Genevive'	['question_type_global', 'question_three_hop_statement']
[that project] is now in the [implementation] stage
What are the resolved issues for [personal] projects?	'initialization broken', 'versioning needs to be made consistent', 'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
What projects are in the [implementation] stage?	'knowledge base'	['question_type_global', 'question_single_statement']
What are the issues that are resolved for [personal] projects?	'initialization broken', 'versioning needs to be made consistent', 'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
What testers are assigned to the [personal] projects?	'Michael', 'Genevive', 'Angelita', 'Bob'	['question_type_global', 'question_three_hop_statement']
Who created [the versioning needs to be made consistent proposal]?	'Roslyn'	['question_type_local']
Are there any issues that are resolved?	'parsing with parantheses fails', 'timeout problem', 'initialization broken', 'tokenization not consistent across platforms', 'versioning needs to be made consistent', 'xml extractor exception'	['question_type_global', 'question_single_statement']
What are the [personal] projects?	'mobile'	['question_type_global', 'question_single_statement']
Are there any issues for [mobile project] that are not resolved?	'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
What are the resolved issues for projects in the [development] stage?	'initialization broken', 'tokenization not consistent across platforms', 'versioning needs to be made consistent', 'xml extractor exception'	['question_type_global', 'question_three_hop_statement']
Who are the testers currently working on the [personal] projects?	'Michael', 'Genevive', 'Angelita', 'Bob'	['question_type_global', 'question_three_hop_statement']
Who are the developers currently working on the [corporate] projects?	'Roslyn', 'Andrew', 'Will'	['question_type_global', 'question_three_hop_statement']
who are the developers?	'Roslyn', 'Andrew', 'Gia', 'Will'	['question_type_global', 'question_single_statement']
What are the issues created by [Roslyn]?	'versioning needs to be made consistent'	['question_type_local']
who are the testers?	'Michael', 'Genevive', 'Angelita', 'Bob'	['question_type_global', 'question_single_statement']
Who are the developers currently working on projects in the [implementation] stage?	'Roslyn', 'Andrew', 'Will'	['question_type_global', 'question_three_hop_statement']
What are the [enhancement]s that are not resolved?	'parsing with parantheses fails'	['question_type_global', 'question_two_hop_statement']
[this project] has moved to the [testing] stage
What are the issues submitted by [Gia] that were resolved?	'xml extractor exception'	['question_type_local']
Who are the testers currently working on projects in the [development] stage?	'Michael', 'Genevive', 'Angelita', 'Bob'	['question_type_global', 'question_three_hop_statement']
[this project] is now in the [design] stage
[mobile project] is not assigned to [Bob]
[he] is working on [this project] also
What projects is [this test engineer] working on?	'knowledge base', 'chatbot', 'mobile'	['question_type_local']
What are the issues that are not resolved for [personal] projects?	'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
What are the non resolved issues?	'dcoref always returns null'	['question_type_global', 'question_single_statement']
who are the testers?	'Michael', 'Genevive', 'Angelita', 'Bob'	['question_type_global', 'question_single_statement']
What projects are currently in the [design] stage?	'knowledge base'	['question_type_global', 'question_single_statement']
[it] is in the stage of [testing]
Who submitted [the parsing with parantheses fails enhancement]?	'Michael'	['question_type_local']
Which testers have issues assigned to them that were all resolved?	'Michael', 'Genevive'	['question_type_global', 'question_three_hop_statement']
What testers are assigned to the [corporate] projects?	'Michael', 'Genevive', 'Angelita', 'Bob'	['question_type_global', 'question_three_hop_statement']
Are there any testers assigned to projects in the [testing] stage?	'Michael', 'Genevive', 'Angelita', 'Bob'	['question_type_global', 'question_three_hop_statement']
Were there any issues submitted by [Michael]?	'parsing with parantheses fails', 'timeout problem'	['question_type_local']
Are there any testers assigned to the [personal] projects?	'Michael', 'Genevive', 'Angelita', 'Bob'	['question_type_global', 'question_three_hop_statement']
Are there any issues for [mobile project] that are resolved?	'initialization broken', 'versioning needs to be made consistent', 'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
Are there any [personal] projects?	'mobile'	['question_type_global', 'question_single_statement']
What projects is [Michael] working on?	'knowledge base', 'chatbot', 'mobile'	['question_type_local']
Who is currently working on the [personal] projects?	'Roslyn', 'Michael', 'Genevive', 'Angelita', 'Andrew', 'Gia', 'Will', 'Bob'	['question_type_global', 'question_two_hop_statement']
Who are the testers currently working on the [corporate] projects?	'Michael', 'Genevive', 'Angelita', 'Bob'	['question_type_global', 'question_three_hop_statement']
[knowledge base project] has moved to the [implementation] stage
Who is [the tokenization not consistent across platforms issue] assigned to?	'Michael'	['question_type_local']
Are there any people assigned to projects in the [testing] stage?	'Roslyn', 'Michael', 'Genevive', 'Angelita', 'Andrew', 'Gia', 'Will', 'Bob'	['question_type_global', 'question_two_hop_statement']
Were there any issues submitted by [Genevive]?	'tokenization not consistent across platforms'	['question_type_local']
What are the resolved issues?	'parsing with parantheses fails', 'timeout problem', 'initialization broken', 'tokenization not consistent across platforms', 'versioning needs to be made consistent', 'xml extractor exception'	['question_type_global', 'question_single_statement']
Are there any issues that are not resolved for [personal] projects?	'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
What are the [personal] projects?	'mobile'	['question_type_global', 'question_single_statement']
What are the non resolved issues?	'dcoref always returns null'	['question_type_global', 'question_single_statement']
What projects are in the [testing] stage?	'mobile'	['question_type_global', 'question_single_statement']
who are the developers?	'Roslyn', 'Andrew', 'Gia', 'Will'	['question_type_global', 'question_single_statement']
What are the resolved issues for [mobile project]?	'initialization broken', 'versioning needs to be made consistent', 'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
Who submitted [the tokenization not consistent across platforms issue]?	'Genevive'	['question_type_local']
What are the issues for [mobile project] that are not resolved?	'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
Who are the developers currently working on the [personal] projects?	'Roslyn', 'Andrew', 'Gia', 'Will'	['question_type_global', 'question_three_hop_statement']
What are the non resolved issues?	'dcoref always returns null'	['question_type_global', 'question_single_statement']
Who has issues assigned to them that were all resolved?	'Michael', 'Genevive', 'Andrew'	['question_type_global', 'question_two_hop_statement']
Were there any issues created by [Gia]?	'xml extractor exception'	['question_type_local']
Which developers have issues assigned to them that were all resolved?	'Andrew'	['question_type_global', 'question_three_hop_statement']
Who are the developers currently working on projects in the [implementation] stage?	'Roslyn', 'Andrew', 'Will'	['question_type_global', 'question_three_hop_statement']
[mobile project] is in the stage of [design]
[Michael] is no longer assigned to [mobile project]
[this tester] is working on [mobile project] also
Which is the stage of [knowledge base project]?	'implementation'	['question_type_local']
Who is currently working on projects in the [design] stage?	'Roslyn', 'Michael', 'Genevive', 'Angelita', 'Andrew', 'Gia', 'Will', 'Bob'	['question_type_global', 'question_two_hop_statement']
Are there any people assigned to the [personal] projects?	'Roslyn', 'Michael', 'Genevive', 'Angelita', 'Andrew', 'Gia', 'Will', 'Bob'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are resolved for projects in the [development] stage?	'tokenization not consistent across platforms'	['question_type_global', 'question_three_hop_statement']
Are there any [proposal]s that are not resolved?	'timeout problem', 'versioning needs to be made consistent'	['question_type_global', 'question_two_hop_statement']
Who are the testers on [mobile project]	'Michael', 'Genevive', 'Angelita', 'Bob'	['question_type_local']
What are the issues for [chatbot project] that are resolved?	'tokenization not consistent across platforms'	['question_type_global', 'question_two_hop_statement']
Who are the developers currently working on the [corporate] projects?	'Roslyn', 'Andrew', 'Will'	['question_type_global', 'question_three_hop_statement']
Are there any issues that are resolved for [personal] projects?	'initialization broken', 'versioning needs to be made consistent', 'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
Who was [the xml extractor exception issue] assigned to?	'Andrew'	['question_type_local']
Who has issues assigned to them that were all resolved?	'Michael', 'Genevive', 'Andrew'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are resolved for projects in the [implementation] stage?	'parsing with parantheses fails', 'timeout problem'	['question_type_global', 'question_three_hop_statement']
What projects are currently in the [design] stage?	'mobile'	['question_type_global', 'question_single_statement']
which testers are assigned to [chatbot project]	'Michael', 'Genevive', 'Angelita', 'Bob'	['question_type_local']
What are the non resolved issues for [personal] projects?	'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
What are the issues for [knowledge base project] that are resolved?	'parsing with parantheses fails', 'timeout problem'	['question_type_global', 'question_two_hop_statement']
who are the developers?	'Roslyn', 'Andrew', 'Gia', 'Will'	['question_type_global', 'question_single_statement']
What are the issues for [mobile project] that are not resolved?	'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
Which testers are working on [chatbot project]?	'Michael', 'Genevive', 'Angelita', 'Bob'	['question_type_local']
Are there any issues that are not resolved?	'dcoref always returns null'	['question_type_global', 'question_single_statement']
What are the issues that were resolved?	'parsing with parantheses fails', 'timeout problem', 'initialization broken', 'tokenization not consistent across platforms', 'versioning needs to be made consistent', 'xml extractor exception'	['question_type_global', 'question_single_statement']
What developers are assigned to the [personal] projects?	'Roslyn', 'Andrew', 'Gia', 'Will'	['question_type_global', 'question_three_hop_statement']
Are there any issues created by [Genevive] that are resolved?	'tokenization not consistent across platforms'	['question_type_local']
What testers are assigned to the [personal] projects?	'Michael', 'Genevive', 'Angelita', 'Bob'	['question_type_global', 'question_three_hop_statement']
Who has issues assigned to them that were all resolved?	'Michael', 'Genevive', 'Andrew'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are not resolved for projects in the [design] stage?	'dcoref always returns null'	['question_type_global', 'question_three_hop_statement']
Were there any issues submitted by [Genevive]?	'tokenization not consistent across platforms'	['question_type_local']
What projects are currently in the [design] stage?	'mobile'	['question_type_global', 'question_single_statement']
Who is assigned to projects in the [implementation] stage?	'Roslyn', 'Michael', 'Genevive', 'Angelita', 'Andrew', 'Will', 'Bob'	['question_type_global', 'question_two_hop_statement']
What are the issues for [chatbot project] that are resolved?	'tokenization not consistent across platforms'	['question_type_global', 'question_two_hop_statement']
Are there any issues for [knowledge base project] that are resolved?	'parsing with parantheses fails', 'timeout problem'	['question_type_global', 'question_two_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Andrew'	['question_type_global', 'question_three_hop_statement']
Are there any issues that are resolved for [personal] projects?	'initialization broken', 'versioning needs to be made consistent', 'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
What developers are assigned to the [corporate] projects?	'Roslyn', 'Andrew', 'Will'	['question_type_global', 'question_three_hop_statement']
who are the developers?	'Roslyn', 'Andrew', 'Gia', 'Will'	['question_type_global', 'question_single_statement']
[this test engineer] is not working on [that project] anymore
[this tester] is working on [that project] also
Who created [the versioning needs to be made consistent issue]?	'Roslyn'	['question_type_local']
What are the resolved issues for [personal] projects?	'initialization broken', 'versioning needs to be made consistent', 'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
Who are the testers currently working on projects in the [implementation] stage?	'Michael', 'Genevive', 'Angelita', 'Bob'	['question_type_global', 'question_three_hop_statement']
Who is working on [knowledge base project]?	'Roslyn', 'Michael', 'Genevive', 'Angelita', 'Andrew', 'Will', 'Bob'	['question_type_local']
who are the testers?	'Michael', 'Genevive', 'Angelita', 'Bob'	['question_type_global', 'question_single_statement']
What are the non resolved issues for [personal] projects?	'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
Who is currently working on projects in the [implementation] stage?	'Roslyn', 'Michael', 'Genevive', 'Angelita', 'Andrew', 'Will', 'Bob'	['question_type_global', 'question_two_hop_statement']
who are the developers?	'Roslyn', 'Andrew', 'Gia', 'Will'	['question_type_global', 'question_single_statement']
[this project] has moved to the [testing] stage
What are the issues that are not resolved?	'dcoref always returns null'	['question_type_global', 'question_single_statement']
What projects are in the [implementation] stage?	'knowledge base'	['question_type_global', 'question_single_statement']
What are the resolved issues for projects in the [implementation] stage?	'parsing with parantheses fails', 'timeout problem'	['question_type_global', 'question_three_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Andrew'	['question_type_global', 'question_three_hop_statement']
What are the issues that were resolved?	'parsing with parantheses fails', 'timeout problem', 'initialization broken', 'tokenization not consistent across platforms', 'versioning needs to be made consistent', 'xml extractor exception'	['question_type_global', 'question_single_statement']
who are the testers?	'Michael', 'Genevive', 'Angelita', 'Bob'	['question_type_global', 'question_single_statement']
Who are the testers on [this project]	'Michael', 'Genevive', 'Angelita', 'Bob'	['question_type_local']
Are there any projects that are [personal]?	'mobile'	['question_type_global', 'question_single_statement']
What developers are assigned to the [corporate] projects?	'Roslyn', 'Andrew', 'Will'	['question_type_global', 'question_three_hop_statement']
What projects are currently in the [implementation] stage?	'knowledge base'	['question_type_global', 'question_single_statement']
Which is the stage of [it]?	'testing'	['question_type_local']
[Genevive] is no longer assigned to [mobile project]
[this person] is no longer assigned to [chatbot project]
[it] is assigned to [Genevive] also
[she] is working on [mobile project] also
What projects is [Gia] working on?	'mobile'	['question_type_local']
What are the issues created by [Michael]?	'parsing with parantheses fails', 'timeout problem'	['question_type_local']
What are the resolved issues for [mobile project]?	'initialization broken', 'versioning needs to be made consistent', 'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
who are the testers?	'Michael', 'Genevive', 'Angelita', 'Bob'	['question_type_global', 'question_single_statement']
What developers are assigned to the [personal] projects?	'Roslyn', 'Andrew', 'Gia', 'Will'	['question_type_global', 'question_three_hop_statement']
Who is currently working on the [personal] projects?	'Roslyn', 'Michael', 'Genevive', 'Angelita', 'Andrew', 'Gia', 'Will', 'Bob'	['question_type_global', 'question_two_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Andrew'	['question_type_global', 'question_three_hop_statement']
Which is the stage of [knowledge base project]?	'implementation'	['question_type_local']
What are the issues that are resolved for [personal] projects?	'initialization broken', 'versioning needs to be made consistent', 'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are resolved for projects in the [testing] stage?	'initialization broken', 'versioning needs to be made consistent', 'xml extractor exception'	['question_type_global', 'question_three_hop_statement']
Who is working on [knowledge base project]?	'Roslyn', 'Michael', 'Genevive', 'Angelita', 'Andrew', 'Will', 'Bob'	['question_type_local']
What are the issues for [knowledge base project] that are resolved?	'parsing with parantheses fails', 'timeout problem'	['question_type_global', 'question_two_hop_statement']
Are there any issues for [this project] that are resolved?	'initialization broken', 'versioning needs to be made consistent', 'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
What are the issues assigned to [Andrew]?	'xml extractor exception'	['question_type_local']
who are the testers?	'Michael', 'Genevive', 'Angelita', 'Bob'	['question_type_global', 'question_single_statement']
What projects are in the [testing] stage?	'mobile'	['question_type_global', 'question_single_statement']
What are the issues that are resolved for projects in the [implementation] stage?	'parsing with parantheses fails', 'timeout problem'	['question_type_global', 'question_three_hop_statement']
Are there any people assigned to the [personal] projects?	'Roslyn', 'Michael', 'Genevive', 'Angelita', 'Andrew', 'Gia', 'Will', 'Bob'	['question_type_global', 'question_two_hop_statement']
Who was [the versioning needs to be made consistent proposal] assigned to?	'Genevive'	['question_type_local']
Are there any issues that are resolved for [personal] projects?	'initialization broken', 'versioning needs to be made consistent', 'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
Are there any people assigned to the [corporate] projects?	'Roslyn', 'Michael', 'Genevive', 'Angelita', 'Andrew', 'Will', 'Bob'	['question_type_global', 'question_two_hop_statement']
What are the non resolved issues for [personal] projects?	'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
Who submitted [the enhancement]?	'Michael'	['question_type_local']
What are the issues for [that project] that are resolved?	'initialization broken', 'versioning needs to be made consistent', 'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
Are there any issues for [that project] that are resolved?	'initialization broken', 'versioning needs to be made consistent', 'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
[chatbot project] is not assigned to [that test engineer]
[Genevive] is working on [this project] also
Who is currently working on the [corporate] projects?	'Roslyn', 'Michael', 'Genevive', 'Angelita', 'Andrew', 'Will', 'Bob'	['question_type_global', 'question_two_hop_statement']
What are the issues that are not resolved for projects in the [testing] stage?	'dcoref always returns null'	['question_type_global', 'question_three_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Andrew'	['question_type_global', 'question_three_hop_statement']
who are the testers?	'Michael', 'Genevive', 'Angelita', 'Bob'	['question_type_global', 'question_single_statement']
What projects is [Andrew] working on?	'knowledge base', 'chatbot', 'mobile'	['question_type_local']
What are the issues that were resolved?	'parsing with parantheses fails', 'timeout problem', 'initialization broken', 'tokenization not consistent across platforms', 'versioning needs to be made consistent', 'xml extractor exception'	['question_type_global', 'question_single_statement']
Are there any testers assigned to the [corporate] projects?	'Michael', 'Genevive', 'Angelita', 'Bob'	['question_type_global', 'question_three_hop_statement']
Are there any issues that are resolved?	'parsing with parantheses fails', 'timeout problem', 'initialization broken', 'tokenization not consistent across platforms', 'versioning needs to be made consistent', 'xml extractor exception'	['question_type_global', 'question_single_statement']
Who has issues assigned to them that were all resolved?	'Michael', 'Genevive', 'Andrew'	['question_type_global', 'question_two_hop_statement']
What testers are assigned to projects in the [testing] stage?	'Michael', 'Genevive', 'Angelita', 'Bob'	['question_type_global', 'question_three_hop_statement']
[knowledge base project] is assigned to [Gia] also
[chatbot project] is assigned to [Gia] also
[that project] is in the stage of [design]
Are there any issues that are resolved for [personal] projects?	'initialization broken', 'versioning needs to be made consistent', 'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
Are there any testers assigned to projects in the [design] stage?	'Michael', 'Genevive', 'Angelita', 'Bob'	['question_type_global', 'question_three_hop_statement']
Who is assigned to projects in the [design] stage?	'Roslyn', 'Michael', 'Genevive', 'Angelita', 'Andrew', 'Gia', 'Will', 'Bob'	['question_type_global', 'question_two_hop_statement']
What are the resolved issues for [personal] projects?	'initialization broken', 'versioning needs to be made consistent', 'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
Who is working on [mobile project]?	'Roslyn', 'Michael', 'Genevive', 'Angelita', 'Andrew', 'Gia', 'Will', 'Bob'	['question_type_local']
Who are the developers currently working on projects in the [implementation] stage?	'Roslyn', 'Andrew', 'Gia', 'Will'	['question_type_global', 'question_three_hop_statement']
[mobile project] is not assigned to [Genevive]
[this project] is assigned to [this test engineer] also
Who was [the initialization broken issue] assigned to?	'Genevive'	['question_type_local']
What are the resolved issues for [knowledge base project]?	'parsing with parantheses fails', 'timeout problem'	['question_type_global', 'question_two_hop_statement']
Who is currently working on the [corporate] projects?	'Roslyn', 'Michael', 'Genevive', 'Angelita', 'Andrew', 'Gia', 'Will', 'Bob'	['question_type_global', 'question_two_hop_statement']
What are the non resolved issues?	'dcoref always returns null'	['question_type_global', 'question_single_statement']
What projects is [Gia] working on?	'knowledge base', 'chatbot', 'mobile'	['question_type_local']
Are there any testers assigned to projects in the [testing] stage?	'Michael', 'Genevive', 'Angelita', 'Bob'	['question_type_global', 'question_three_hop_statement']
What are the [corporate] projects?	'knowledge base', 'chatbot'	['question_type_global', 'question_single_statement']
Who is currently working on the [personal] projects?	'Roslyn', 'Michael', 'Genevive', 'Angelita', 'Andrew', 'Gia', 'Will', 'Bob'	['question_type_global', 'question_two_hop_statement']
What are the resolved issues for [corporate] projects?	'parsing with parantheses fails', 'timeout problem', 'tokenization not consistent across platforms'	['question_type_global', 'question_two_hop_statement']
Who submitted [the enhancement]?	'Michael'	['question_type_local']
What are the issues for [this project] that are not resolved?	'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
What are the issues that are resolved for [corporate] projects?	'parsing with parantheses fails', 'timeout problem', 'tokenization not consistent across platforms'	['question_type_global', 'question_two_hop_statement']
What projects are in the [testing] stage?	'mobile'	['question_type_global', 'question_single_statement']
who are the testers?	'Michael', 'Genevive', 'Angelita', 'Bob'	['question_type_global', 'question_single_statement']
Who submitted [the versioning needs to be made consistent proposal]?	'Roslyn'	['question_type_local']
What are the issues that are resolved for projects in the [testing] stage?	'initialization broken', 'versioning needs to be made consistent', 'xml extractor exception'	['question_type_global', 'question_three_hop_statement']
What testers are assigned to the [corporate] projects?	'Michael', 'Genevive', 'Angelita', 'Bob'	['question_type_global', 'question_three_hop_statement']
Who are the developers currently working on the [corporate] projects?	'Roslyn', 'Andrew', 'Gia', 'Will'	['question_type_global', 'question_three_hop_statement']
[chatbot project] is in the [development] stage
Were there any issues created by [Michael]?	'parsing with parantheses fails', 'timeout problem'	['question_type_local']
What projects are [personal]?	'mobile'	['question_type_global', 'question_single_statement']
Which testers have issues assigned to them that were all resolved?	'Michael', 'Genevive'	['question_type_global', 'question_three_hop_statement']
What projects are in the [implementation] stage?	'knowledge base'	['question_type_global', 'question_single_statement']
[chatbot project] is in the stage of [implementation]
Are there any [proposal]s that are not resolved?	'timeout problem', 'versioning needs to be made consistent'	['question_type_global', 'question_two_hop_statement']
What projects are currently in the [implementation] stage?	'knowledge base', 'chatbot'	['question_type_global', 'question_single_statement']
[Genevive] is no longer assigned to [chatbot project]
[that person] is working on [chatbot project] also
What projects is [Michael] working on?	'knowledge base', 'chatbot', 'mobile'	['question_type_local']
What projects are currently in the [testing] stage?	'mobile'	['question_type_global', 'question_single_statement']
Are there any testers assigned to the [corporate] projects?	'Michael', 'Genevive', 'Angelita', 'Bob'	['question_type_global', 'question_three_hop_statement']
[it] has moved to the [testing] stage
[it] is now in the [development] stage
Who are the testers on [chatbot project]	'Michael', 'Genevive', 'Angelita', 'Bob'	['question_type_local']
Are there any issues that are not resolved for [personal] projects?	'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
What developers are assigned to the [personal] projects?	'Roslyn', 'Andrew', 'Gia', 'Will'	['question_type_global', 'question_three_hop_statement']
[that project] is in the stage of [implementation]
[chatbot project] is in the stage of [design]
[this project] is in the [development] stage
What are the resolved issues for projects in the [implementation] stage?	'parsing with parantheses fails', 'timeout problem'	['question_type_global', 'question_three_hop_statement']
Are there any [proposal]s that are not resolved?	'timeout problem', 'versioning needs to be made consistent'	['question_type_global', 'question_two_hop_statement']
Who is [the xml extractor exception issue] assigned to?	'Andrew'	['question_type_local']
Who is assigned to the [personal] projects?	'Roslyn', 'Michael', 'Genevive', 'Angelita', 'Andrew', 'Gia', 'Will', 'Bob'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are resolved for projects in the [testing] stage?	'initialization broken', 'versioning needs to be made consistent', 'xml extractor exception'	['question_type_global', 'question_three_hop_statement']
What are the issues for [mobile project] that are not resolved?	'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
What are the [proposal]s that are not resolved?	'timeout problem', 'versioning needs to be made consistent'	['question_type_global', 'question_two_hop_statement']
What are the resolved issues?	'parsing with parantheses fails', 'timeout problem', 'initialization broken', 'tokenization not consistent across platforms', 'versioning needs to be made consistent', 'xml extractor exception'	['question_type_global', 'question_single_statement']
Are there any developers assigned to the [personal] projects?	'Roslyn', 'Andrew', 'Gia', 'Will'	['question_type_global', 'question_three_hop_statement']
Are there any testers assigned to the [personal] projects?	'Michael', 'Genevive', 'Angelita', 'Bob'	['question_type_global', 'question_three_hop_statement']
What are the resolved issues for [personal] projects?	'initialization broken', 'versioning needs to be made consistent', 'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
Are there any issues for [that project] that are resolved?	'tokenization not consistent across platforms'	['question_type_global', 'question_two_hop_statement']
Were there any issues submitted by [Gia]?	'xml extractor exception'	['question_type_local']
Which developers have issues assigned to them that were all resolved?	'Andrew'	['question_type_global', 'question_three_hop_statement']
[chatbot project] is in the stage of [implementation]
[chatbot project] is in the [design] stage
Are there any issues assigned to [Andrew] that are resolved?	'xml extractor exception'	['question_type_local']
What are the non resolved issues?	'dcoref always returns null'	['question_type_global', 'question_single_statement']
Who is [the versioning needs to be made consistent issue] assigned to?	'Genevive'	['question_type_local']
who are the developers?	'Roslyn', 'Andrew', 'Gia', 'Will'	['question_type_global', 'question_single_statement']
Are there any issues that are resolved?	'parsing with parantheses fails', 'timeout problem', 'initialization broken', 'tokenization not consistent across platforms', 'versioning needs to be made consistent', 'xml extractor exception'	['question_type_global', 'question_single_statement']
Who is assigned to the [corporate] projects?	'Roslyn', 'Michael', 'Genevive', 'Angelita', 'Andrew', 'Gia', 'Will', 'Bob'	['question_type_global', 'question_two_hop_statement']
What testers are assigned to the [corporate] projects?	'Michael', 'Genevive', 'Angelita', 'Bob'	['question_type_global', 'question_three_hop_statement']
who are the testers?	'Michael', 'Genevive', 'Angelita', 'Bob'	['question_type_global', 'question_single_statement']
[it] has moved to the [implementation] stage
Are there any projects that are [personal]?	'mobile'	['question_type_global', 'question_single_statement']
[it] is in the stage of [development]
[this project] has moved to the [testing] stage
Who has issues assigned to them that were all resolved?	'Michael', 'Genevive', 'Andrew'	['question_type_global', 'question_two_hop_statement']
Are there any issues for [knowledge base project] that are resolved?	'parsing with parantheses fails', 'timeout problem'	['question_type_global', 'question_two_hop_statement']
who are the developers?	'Roslyn', 'Andrew', 'Gia', 'Will'	['question_type_global', 'question_single_statement']
[mobile project] is not assigned to [Bob]
