there is a new [important] [mobile] [project]
[that project] is currently in the [implementation] stage
What stage is [mobile project] in?	'implementation'	['question_type_local']
There is a new [bug] for the [it]: [wrong pos tag on consecutive words]
There is a new issue for the [that project]: [initialization broken]
What are the issues that are not resolved for projects in the [implementation] stage?	'wrong pos tag on consecutive words', 'initialization broken'	['question_type_global', 'question_three_hop_statement']
There is a new issue for the [mobile project]: [saving data throws exception]
there is a new [important] [chatbot] [project]
[Cyndi] is a [tester] on [mobile project]
[this project] is in the [deployment] stage
[Emma] is a [tester]
[Emma] is assigned to [mobile project]
What are the non resolved issues?	'wrong pos tag on consecutive words', 'initialization broken', 'saving data throws exception'	['question_type_global', 'question_single_statement']
What are the issues for [mobile project] that are not resolved?	'wrong pos tag on consecutive words', 'initialization broken', 'saving data throws exception'	['question_type_global', 'question_two_hop_statement']
What projects are [important]?	'mobile', 'chatbot'	['question_type_global', 'question_single_statement']
Are there any issues for [that project] that are not resolved?	'wrong pos tag on consecutive words', 'initialization broken', 'saving data throws exception'	['question_type_global', 'question_two_hop_statement']
Are there any testers assigned to the [important] projects?	'Cyndi', 'Emma'	['question_type_global', 'question_three_hop_statement']
[Roslyn] is a [developer] on [this project]
[chatbot project] is assigned to [Roslyn] also
[Francoise] is a [tester]
[that project] is assigned to [Francoise]
[the wrong pos tag on consecutive words bug] is assigned to [Cyndi]
[this test engineer] resolved [the wrong pos tag on consecutive words issue]
[she] is not working on [mobile project] anymore
There is a new issue for the [chatbot project]: [tokenization not consistent across platforms]
[mobile project] has moved to the [testing] stage
[Tom] is a [developer]
What are the issues that were resolved?	'wrong pos tag on consecutive words'	['question_type_global', 'question_single_statement']
who are the developers?	'Roslyn', 'Tom'	['question_type_global', 'question_single_statement']
Which testers are working on [chatbot project]?	'Francoise'	['question_type_local']
Who is currently working on the [important] projects?	'Emma', 'Roslyn', 'Francoise'	['question_type_global', 'question_two_hop_statement']
Are there any developers assigned to projects in the [deployment] stage?	'Roslyn'	['question_type_global', 'question_three_hop_statement']
What are the issues that are resolved for [important] projects?	'wrong pos tag on consecutive words'	['question_type_global', 'question_two_hop_statement']
[this person] is working on [mobile project]
Who is working on [it]?	'Emma', 'Roslyn', 'Tom'	['question_type_local']
Are there any people assigned to the [important] projects?	'Emma', 'Roslyn', 'Francoise', 'Tom'	['question_type_global', 'question_two_hop_statement']
Who is assigned to the [important] projects?	'Emma', 'Roslyn', 'Francoise', 'Tom'	['question_type_global', 'question_two_hop_statement']
[that developer] is assigned to [chatbot project] also
Are there any testers assigned to the [important] projects?	'Emma', 'Francoise'	['question_type_global', 'question_three_hop_statement']
there is a new [knowledge base] [project]
[knowledge base project] is a [important] project
[it] is currently in the [development] stage
[this project] is assigned to [Cyndi]
[Cyndi] is assigned to [mobile project] also
What are the issues that are not resolved for [important] projects?	'initialization broken', 'saving data throws exception', 'tokenization not consistent across platforms'	['question_type_global', 'question_two_hop_statement']
[svd is slow] is a new [enhancement] submitted by [Tom] for [chatbot project]
[that issue] was assigned to [Tom]
[that person] resolved [that issue]
What projects are in the [development] stage?	'knowledge base'	['question_type_global', 'question_single_statement']
Are there any issues that are resolved for [important] projects?	'wrong pos tag on consecutive words', 'svd is slow'	['question_type_global', 'question_two_hop_statement']
[Emma] is working on [knowledge base project] also
Which is the stage of [chatbot project]?	'deployment'	['question_type_local']
Are there any issues that are resolved for projects in the [testing] stage?	'wrong pos tag on consecutive words'	['question_type_global', 'question_three_hop_statement']
[Emma] is assigned to [chatbot project] also
[chatbot project] is assigned to [Cyndi] also
What projects is [Tom] working on?	'mobile', 'chatbot'	['question_type_local']
Are there any people assigned to the [important] projects?	'Cyndi', 'Emma', 'Roslyn', 'Francoise', 'Tom'	['question_type_global', 'question_two_hop_statement']
Were there any issues assigned to [Tom]?	'svd is slow'	['question_type_local']
Who are the developers currently working on the [important] projects?	'Roslyn', 'Tom'	['question_type_global', 'question_three_hop_statement']
What developers are assigned to projects in the [deployment] stage?	'Roslyn', 'Tom'	['question_type_global', 'question_three_hop_statement']
who are the testers?	'Cyndi', 'Emma', 'Francoise'	['question_type_global', 'question_single_statement']
who are the developers?	'Roslyn', 'Tom'	['question_type_global', 'question_single_statement']
What are the issues that were resolved?	'wrong pos tag on consecutive words', 'svd is slow'	['question_type_global', 'question_single_statement']
What are the issues that are resolved for [important] projects?	'wrong pos tag on consecutive words', 'svd is slow'	['question_type_global', 'question_two_hop_statement']
[Tom] is assigned to [knowledge base project] also
[this project] is not assigned to [Tom]
[this developer] is assigned to [this project] also
[the tokenization not consistent across platforms issue] is assigned to [Emma]
[this tester] resolved [that issue]
Who was [that issue] assigned to?	'Emma'	['question_type_local']
What are the issues that are resolved for projects in the [deployment] stage?	'tokenization not consistent across platforms', 'svd is slow'	['question_type_global', 'question_three_hop_statement']
Who is assigned to the [important] projects?	'Cyndi', 'Emma', 'Roslyn', 'Francoise', 'Tom'	['question_type_global', 'question_two_hop_statement']
What are the issues that are not resolved?	'initialization broken', 'saving data throws exception'	['question_type_global', 'question_single_statement']
Who are the developers currently working on projects in the [testing] stage?	'Roslyn', 'Tom'	['question_type_global', 'question_three_hop_statement']
Who are the testers on [knowledge base project]	'Cyndi', 'Emma'	['question_type_local']
Are there any issues that are resolved for [important] projects?	'wrong pos tag on consecutive words', 'tokenization not consistent across platforms', 'svd is slow'	['question_type_global', 'question_two_hop_statement']
[the saving data throws exception issue] was assigned to [Tom]
[this person] resolved [this issue]
Who is working on [knowledge base project]?	'Cyndi', 'Emma', 'Tom'	['question_type_local']
Are there any testers assigned to the [important] projects?	'Cyndi', 'Emma', 'Francoise'	['question_type_global', 'question_three_hop_statement']
Are there projects in the [testing] stage?	'mobile'	['question_type_global', 'question_single_statement']
who are the testers?	'Cyndi', 'Emma', 'Francoise'	['question_type_global', 'question_single_statement']
Who is working on [chatbot project]?	'Cyndi', 'Emma', 'Roslyn', 'Francoise', 'Tom'	['question_type_local']
What are the issues that are resolved for [important] projects?	'wrong pos tag on consecutive words', 'saving data throws exception', 'tokenization not consistent across platforms', 'svd is slow'	['question_type_global', 'question_two_hop_statement']
Which testers have issues assigned to them that were all resolved?	'Cyndi', 'Emma'	['question_type_global', 'question_three_hop_statement']
Who are the developers currently working on projects in the [deployment] stage?	'Roslyn', 'Tom'	['question_type_global', 'question_three_hop_statement']
What testers are assigned to the [important] projects?	'Cyndi', 'Emma', 'Francoise'	['question_type_global', 'question_three_hop_statement']
Are there any testers assigned to projects in the [deployment] stage?	'Cyndi', 'Emma', 'Francoise'	['question_type_global', 'question_three_hop_statement']
[Emma] created a new issue for [knowledge base project]: [versioning needs to be made consistent]
[the versioning needs to be made consistent issue] was assigned to [Emma]
What projects is [Francoise] working on?	'chatbot'	['question_type_local']
Are there projects in the [testing] stage?	'mobile'	['question_type_global', 'question_single_statement']
Which testers have issues assigned to them that were all resolved?	'Cyndi', 'Emma'	['question_type_global', 'question_three_hop_statement']
What are the resolved issues?	'wrong pos tag on consecutive words', 'saving data throws exception', 'tokenization not consistent across platforms', 'svd is slow'	['question_type_global', 'question_single_statement']
What are the issues that are not resolved for projects in the [testing] stage?	'initialization broken'	['question_type_global', 'question_three_hop_statement']
Who has issues assigned to them that were all resolved?	'Cyndi', 'Emma', 'Tom'	['question_type_global', 'question_two_hop_statement']
[this test engineer] resolved [that issue]
Are there projects in the [development] stage?	'knowledge base'	['question_type_global', 'question_single_statement']
who are the developers?	'Roslyn', 'Tom'	['question_type_global', 'question_single_statement']
Who is assigned to the [important] projects?	'Cyndi', 'Emma', 'Roslyn', 'Francoise', 'Tom'	['question_type_global', 'question_two_hop_statement']
[Emma] is no longer assigned to [mobile project]
[that person] is assigned to [this project] also
[Emma] is no longer assigned to [knowledge base project]
[she] is working on [knowledge base project] also
Who are the developers on [chatbot project]	'Roslyn', 'Tom'	['question_type_local']
who are the testers?	'Cyndi', 'Emma', 'Francoise'	['question_type_global', 'question_single_statement']
What are the resolved issues?	'wrong pos tag on consecutive words', 'saving data throws exception', 'tokenization not consistent across platforms', 'svd is slow', 'versioning needs to be made consistent'	['question_type_global', 'question_single_statement']
[this project] is in the [testing] stage
Who is working on [chatbot project]?	'Cyndi', 'Emma', 'Roslyn', 'Francoise', 'Tom'	['question_type_local']
What are the issues that are not resolved?	'initialization broken'	['question_type_global', 'question_single_statement']
What projects are currently in the [deployment] stage?	'chatbot'	['question_type_global', 'question_single_statement']
[timeout problem] is a new [proposal] created by [Emma] for [it]
[that issue] is assigned to [Tom]
[this developer] resolved [that issue]
Which developers are working on [mobile project]?	'Roslyn', 'Tom'	['question_type_local']
Were there any issues assigned to [he]?	'saving data throws exception', 'svd is slow', 'timeout problem'	['question_type_local']
What are the resolved issues for [knowledge base project]?	'versioning needs to be made consistent', 'timeout problem'	['question_type_global', 'question_two_hop_statement']
Who was [the versioning needs to be made consistent issue] assigned to?	'Emma'	['question_type_local']
Which developers have issues assigned to them that were all resolved?	'Tom'	['question_type_global', 'question_three_hop_statement']
Who is assigned to the [important] projects?	'Cyndi', 'Emma', 'Roslyn', 'Francoise', 'Tom'	['question_type_global', 'question_two_hop_statement']
Who is [that issue] assigned to?	'Tom'	['question_type_local']
Who is currently working on projects in the [deployment] stage?	'Cyndi', 'Emma', 'Roslyn', 'Francoise', 'Tom'	['question_type_global', 'question_two_hop_statement']
What stage is [mobile project] in?	'testing'	['question_type_local']
What are the non resolved issues for projects in the [testing] stage?	'initialization broken'	['question_type_global', 'question_three_hop_statement']
What are the resolved issues for [important] projects?	'wrong pos tag on consecutive words', 'saving data throws exception', 'tokenization not consistent across platforms', 'svd is slow', 'versioning needs to be made consistent', 'timeout problem'	['question_type_global', 'question_two_hop_statement']
[parsing with parantheses fails] is a new [proposal] for [mobile project] that [Roslyn] just created
[that issue] was assigned to [Cyndi]
[this person] resolved [it]
What are the issues assigned to [Tom]?	'saving data throws exception', 'svd is slow', 'timeout problem'	['question_type_local']
What are the non resolved [enhancement]s?	'svd is slow'	['question_type_global', 'question_two_hop_statement']
What are the issues that are resolved for [important] projects?	'wrong pos tag on consecutive words', 'saving data throws exception', 'tokenization not consistent across platforms', 'svd is slow', 'versioning needs to be made consistent', 'timeout problem', 'parsing with parantheses fails'	['question_type_global', 'question_two_hop_statement']
Who is assigned to the [important] projects?	'Cyndi', 'Emma', 'Roslyn', 'Francoise', 'Tom'	['question_type_global', 'question_two_hop_statement']
[knowledge base project] is assigned to [Roslyn] also
Who is [the wrong pos tag on consecutive words bug] assigned to?	'Cyndi'	['question_type_local']
Who are the testers currently working on the [important] projects?	'Cyndi', 'Emma', 'Francoise'	['question_type_global', 'question_three_hop_statement']
Who are the testers on [that project]	'Cyndi', 'Emma'	['question_type_local']
Which testers have issues assigned to them that were all resolved?	'Cyndi', 'Emma'	['question_type_global', 'question_three_hop_statement']
What are the [bug]s that are not resolved?	'wrong pos tag on consecutive words'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are not resolved?	'initialization broken'	['question_type_global', 'question_single_statement']
Who are the developers currently working on projects in the [deployment] stage?	'Roslyn', 'Tom'	['question_type_global', 'question_three_hop_statement']
What are the non resolved issues for [important] projects?	'initialization broken'	['question_type_global', 'question_two_hop_statement']
What are the issues that are resolved for [important] projects?	'wrong pos tag on consecutive words', 'saving data throws exception', 'tokenization not consistent across platforms', 'svd is slow', 'versioning needs to be made consistent', 'timeout problem', 'parsing with parantheses fails'	['question_type_global', 'question_two_hop_statement']
What projects are in the [deployment] stage?	'chatbot'	['question_type_global', 'question_single_statement']
who are the developers?	'Roslyn', 'Tom'	['question_type_global', 'question_single_statement']
Which testers have issues assigned to them that were all resolved?	'Cyndi', 'Emma'	['question_type_global', 'question_three_hop_statement']
[Tom] created a new issue for [mobile project]: [memory leak bug]
[that project] is in the stage of [deployment]
[knowledge base project] is in the [development] stage
There is a new [enhancement] for the [knowledge base project]: [issue in using training data]
What projects is [Tom] working on?	'mobile', 'chatbot', 'knowledge base'	['question_type_local']
who are the testers?	'Cyndi', 'Emma', 'Francoise'	['question_type_global', 'question_single_statement']
Are there any [enhancement]s that are not resolved?	'svd is slow'	['question_type_global', 'question_two_hop_statement']
[the issue] is assigned to [Cyndi]
[she] resolved [the enhancement]
What are the issues for [mobile project] that are resolved?	'wrong pos tag on consecutive words', 'saving data throws exception', 'parsing with parantheses fails'	['question_type_global', 'question_two_hop_statement']
What are the issues that are resolved for projects in the [development] stage?	'versioning needs to be made consistent', 'timeout problem', 'issue in using training data'	['question_type_global', 'question_three_hop_statement']
[mobile project] is in the stage of [development]
[knowledge base project] has moved to the [testing] stage
[knowledge base project] is assigned to [Francoise] also
[that test engineer] is assigned to [mobile project] also
Who is working on [knowledge base project]?	'Cyndi', 'Emma', 'Roslyn', 'Francoise', 'Tom'	['question_type_local']
Which developers have issues assigned to them that were all resolved?	'Tom'	['question_type_global', 'question_three_hop_statement']
What developers are assigned to the [important] projects?	'Roslyn', 'Tom'	['question_type_global', 'question_three_hop_statement']
Who was [the versioning needs to be made consistent issue] assigned to?	'Emma'	['question_type_local']
What developers are assigned to projects in the [deployment] stage?	'Roslyn', 'Tom'	['question_type_global', 'question_three_hop_statement']
What projects are [important]?	'mobile', 'chatbot', 'knowledge base'	['question_type_global', 'question_single_statement']
What are the issues that are not resolved?	'initialization broken', 'memory leak bug'	['question_type_global', 'question_single_statement']
Are there any issues that are resolved?	'wrong pos tag on consecutive words', 'saving data throws exception', 'tokenization not consistent across platforms', 'svd is slow', 'versioning needs to be made consistent', 'timeout problem', 'parsing with parantheses fails', 'issue in using training data'	['question_type_global', 'question_single_statement']
Who are the testers on [knowledge base project]	'Cyndi', 'Emma', 'Francoise'	['question_type_local']
Which testers have issues assigned to them that were all resolved?	'Cyndi', 'Emma'	['question_type_global', 'question_three_hop_statement']
Are there any [proposal]s that are not resolved?	'timeout problem', 'parsing with parantheses fails'	['question_type_global', 'question_two_hop_statement']
What are the non resolved [enhancement]s?	'svd is slow', 'issue in using training data'	['question_type_global', 'question_two_hop_statement']
What projects are in the [development] stage?	'mobile'	['question_type_global', 'question_single_statement']
Are there any people assigned to the [important] projects?	'Cyndi', 'Emma', 'Roslyn', 'Francoise', 'Tom'	['question_type_global', 'question_two_hop_statement']
Which testers are working on [knowledge base project]?	'Cyndi', 'Emma', 'Francoise'	['question_type_local']
What projects are [important]?	'mobile', 'chatbot', 'knowledge base'	['question_type_global', 'question_single_statement']
Which is the stage of [knowledge base project]?	'testing'	['question_type_local']
Are there any projects that are [important]?	'mobile', 'chatbot', 'knowledge base'	['question_type_global', 'question_single_statement']
who are the testers?	'Cyndi', 'Emma', 'Francoise'	['question_type_global', 'question_single_statement']
[it] is not assigned to [this tester]
[this test engineer] is working on [it] also
Which is the stage of [this project]?	'development'	['question_type_local']
Who has issues assigned to them that were all resolved?	'Cyndi', 'Emma', 'Tom'	['question_type_global', 'question_two_hop_statement']
What developers are assigned to projects in the [testing] stage?	'Roslyn', 'Tom'	['question_type_global', 'question_three_hop_statement']
Who is assigned to projects in the [development] stage?	'Cyndi', 'Emma', 'Roslyn', 'Francoise', 'Tom'	['question_type_global', 'question_two_hop_statement']
Who is [the versioning needs to be made consistent issue] assigned to?	'Emma'	['question_type_local']
who are the developers?	'Roslyn', 'Tom'	['question_type_global', 'question_single_statement']
Which developers have issues assigned to them that were all resolved?	'Tom'	['question_type_global', 'question_three_hop_statement']
Are there any developers assigned to the [important] projects?	'Roslyn', 'Tom'	['question_type_global', 'question_three_hop_statement']
Are there any issues that are not resolved for [important] projects?	'initialization broken', 'memory leak bug'	['question_type_global', 'question_two_hop_statement']
Were there any issues submitted by [Emma]?	'versioning needs to be made consistent', 'timeout problem'	['question_type_local']
Who is assigned to projects in the [deployment] stage?	'Cyndi', 'Emma', 'Roslyn', 'Francoise', 'Tom'	['question_type_global', 'question_two_hop_statement']
Who is working on [chatbot project]?	'Cyndi', 'Emma', 'Roslyn', 'Francoise', 'Tom'	['question_type_local']
Who are the testers currently working on the [important] projects?	'Cyndi', 'Emma', 'Francoise'	['question_type_global', 'question_three_hop_statement']
[this project] is in the stage of [testing]
Are there any issues for [knowledge base project] that are resolved?	'versioning needs to be made consistent', 'timeout problem', 'issue in using training data'	['question_type_global', 'question_two_hop_statement']
Are there any people assigned to projects in the [deployment] stage?	'Cyndi', 'Emma', 'Roslyn', 'Francoise', 'Tom'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are not resolved for [important] projects?	'initialization broken', 'memory leak bug'	['question_type_global', 'question_two_hop_statement']
[Roslyn] is no longer assigned to [knowledge base project]
[that person] is assigned to [this project] also
Who are the testers currently working on projects in the [deployment] stage?	'Cyndi', 'Emma', 'Francoise'	['question_type_global', 'question_three_hop_statement']
[the memory leak bug issue] was assigned to [Cyndi]
who are the developers?	'Roslyn', 'Tom'	['question_type_global', 'question_single_statement']
Are there any testers assigned to projects in the [testing] stage?	'Cyndi', 'Emma', 'Francoise'	['question_type_global', 'question_three_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Tom'	['question_type_global', 'question_three_hop_statement']
Which testers are working on [mobile project]?	'Cyndi', 'Emma', 'Francoise'	['question_type_local']
Are there any people assigned to projects in the [deployment] stage?	'Cyndi', 'Emma', 'Roslyn', 'Francoise', 'Tom'	['question_type_global', 'question_two_hop_statement']
Are there any projects that are [important]?	'mobile', 'chatbot', 'knowledge base'	['question_type_global', 'question_single_statement']
Who is currently working on projects in the [deployment] stage?	'Cyndi', 'Emma', 'Roslyn', 'Francoise', 'Tom'	['question_type_global', 'question_two_hop_statement']
What are the [enhancement]s that are not resolved?	'svd is slow', 'issue in using training data'	['question_type_global', 'question_two_hop_statement']
[she] resolved [that issue]
Who is currently working on the [important] projects?	'Cyndi', 'Emma', 'Roslyn', 'Francoise', 'Tom'	['question_type_global', 'question_two_hop_statement']
Who was [the issue in using training data enhancement] assigned to?	'Cyndi'	['question_type_local']
Who has issues assigned to them that were all resolved?	'Cyndi', 'Emma', 'Tom'	['question_type_global', 'question_two_hop_statement']
Are there any developers assigned to the [important] projects?	'Roslyn', 'Tom'	['question_type_global', 'question_three_hop_statement']
What testers are assigned to the [important] projects?	'Cyndi', 'Emma', 'Francoise'	['question_type_global', 'question_three_hop_statement']
What are the non resolved issues for [important] projects?	'initialization broken'	['question_type_global', 'question_two_hop_statement']
who are the developers?	'Roslyn', 'Tom'	['question_type_global', 'question_single_statement']
Which developers are assigned to [mobile project]	'Roslyn', 'Tom'	['question_type_local']
Are there any issues that are resolved for projects in the [deployment] stage?	'tokenization not consistent across platforms', 'svd is slow'	['question_type_global', 'question_three_hop_statement']
What are the resolved issues?	'wrong pos tag on consecutive words', 'saving data throws exception', 'tokenization not consistent across platforms', 'svd is slow', 'versioning needs to be made consistent', 'timeout problem', 'parsing with parantheses fails', 'memory leak bug', 'issue in using training data'	['question_type_global', 'question_single_statement']
Who are the developers currently working on projects in the [deployment] stage?	'Roslyn', 'Tom'	['question_type_global', 'question_three_hop_statement']
What are the issues for [chatbot project] that are resolved?	'tokenization not consistent across platforms', 'svd is slow'	['question_type_global', 'question_two_hop_statement']
What are the non resolved issues for [important] projects?	'initialization broken'	['question_type_global', 'question_two_hop_statement']
What developers are assigned to the [important] projects?	'Roslyn', 'Tom'	['question_type_global', 'question_three_hop_statement']
Who is currently working on projects in the [deployment] stage?	'Cyndi', 'Emma', 'Roslyn', 'Francoise', 'Tom'	['question_type_global', 'question_two_hop_statement']
What are the issues for [knowledge base project] that are resolved?	'versioning needs to be made consistent', 'timeout problem', 'issue in using training data'	['question_type_global', 'question_two_hop_statement']
[Cyndi] is not working on [chatbot project] anymore
[this project] is assigned to [this person] also
What are the issues that are resolved for projects in the [deployment] stage?	'tokenization not consistent across platforms', 'svd is slow'	['question_type_global', 'question_three_hop_statement']
What are the issues assigned to [that test engineer] that were resolved?	'wrong pos tag on consecutive words', 'parsing with parantheses fails', 'memory leak bug', 'issue in using training data'	['question_type_local']
Are there any people assigned to the [important] projects?	'Cyndi', 'Emma', 'Roslyn', 'Francoise', 'Tom'	['question_type_global', 'question_two_hop_statement']
Are there any developers assigned to projects in the [testing] stage?	'Roslyn', 'Tom'	['question_type_global', 'question_three_hop_statement']
Who has issues assigned to them that were all resolved?	'Cyndi', 'Emma', 'Tom'	['question_type_global', 'question_two_hop_statement']
who are the testers?	'Cyndi', 'Emma', 'Francoise'	['question_type_global', 'question_single_statement']
Were there any issues submitted by [Emma]?	'versioning needs to be made consistent', 'timeout problem'	['question_type_local']
What are the issues for [knowledge base project] that are resolved?	'versioning needs to be made consistent', 'timeout problem', 'issue in using training data'	['question_type_global', 'question_two_hop_statement']
What are the non resolved [enhancement]s?	'svd is slow', 'issue in using training data'	['question_type_global', 'question_two_hop_statement']
[chatbot project] is in the stage of [development]
What are the non resolved issues?	'initialization broken'	['question_type_global', 'question_single_statement']
[this project] has moved to the [testing] stage
Who created [the svd is slow enhancement]?	'Tom'	['question_type_local']
What are the non resolved [bug]s?	'wrong pos tag on consecutive words'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are resolved for [important] projects?	'wrong pos tag on consecutive words', 'saving data throws exception', 'tokenization not consistent across platforms', 'svd is slow', 'versioning needs to be made consistent', 'timeout problem', 'parsing with parantheses fails', 'memory leak bug', 'issue in using training data'	['question_type_global', 'question_two_hop_statement']
Who created [the parsing with parantheses fails proposal]?	'Roslyn'	['question_type_local']
What projects are currently in the [testing] stage?	'mobile', 'chatbot', 'knowledge base'	['question_type_global', 'question_single_statement']
who are the developers?	'Roslyn', 'Tom'	['question_type_global', 'question_single_statement']
Which developers have issues assigned to them that were all resolved?	'Tom'	['question_type_global', 'question_three_hop_statement']
Who has issues assigned to them that were all resolved?	'Cyndi', 'Emma', 'Tom'	['question_type_global', 'question_two_hop_statement']
[that project] is in the stage of [deployment]
Who was [the tokenization not consistent across platforms issue] assigned to?	'Emma'	['question_type_local']
Who is assigned to the [important] projects?	'Cyndi', 'Emma', 'Roslyn', 'Francoise', 'Tom'	['question_type_global', 'question_two_hop_statement']
Which testers have issues assigned to them that were all resolved?	'Cyndi', 'Emma'	['question_type_global', 'question_three_hop_statement']
Who submitted [the parsing with parantheses fails proposal]?	'Roslyn'	['question_type_local']
Are there any [enhancement]s that are not resolved?	'svd is slow', 'issue in using training data'	['question_type_global', 'question_two_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Tom'	['question_type_global', 'question_three_hop_statement']
[this project] is in the stage of [implementation]
Who are the testers on [chatbot project]	'Cyndi', 'Emma', 'Francoise'	['question_type_local']
What testers are assigned to projects in the [implementation] stage?	'Cyndi', 'Emma', 'Francoise'	['question_type_global', 'question_three_hop_statement']
Are there any developers assigned to the [important] projects?	'Roslyn', 'Tom'	['question_type_global', 'question_three_hop_statement']
which testers are assigned to [mobile project]	'Cyndi', 'Emma', 'Francoise'	['question_type_local']
What projects are currently in the [implementation] stage?	'chatbot'	['question_type_global', 'question_single_statement']
Are there any developers assigned to projects in the [implementation] stage?	'Roslyn', 'Tom'	['question_type_global', 'question_three_hop_statement']
which testers are assigned to [this project]	'Cyndi', 'Emma', 'Francoise'	['question_type_local']
Who are the developers currently working on the [important] projects?	'Roslyn', 'Tom'	['question_type_global', 'question_three_hop_statement']
[chatbot project] is in the [development] stage
[it] is in the [implementation] stage
[it] is in the [deployment] stage
Which testers have issues assigned to them that were all resolved?	'Cyndi', 'Emma'	['question_type_global', 'question_three_hop_statement']
who are the developers?	'Roslyn', 'Tom'	['question_type_global', 'question_single_statement']
What are the [proposal]s that are not resolved?	'timeout problem', 'parsing with parantheses fails'	['question_type_global', 'question_two_hop_statement']
[it] is in the stage of [testing]
Are there projects in the [testing] stage?	'mobile', 'chatbot', 'knowledge base'	['question_type_global', 'question_single_statement']
Are there any issues created by [Emma] that are resolved?	'versioning needs to be made consistent', 'timeout problem'	['question_type_local']
What are the issues that are not resolved for [important] projects?	'initialization broken'	['question_type_global', 'question_two_hop_statement']
[this project] is now in the [development] stage
[knowledge base project] is now in the [deployment] stage
Who is working on [knowledge base project]?	'Cyndi', 'Emma', 'Roslyn', 'Francoise', 'Tom'	['question_type_local']
Who has issues assigned to them that were all resolved?	'Cyndi', 'Emma', 'Tom'	['question_type_global', 'question_two_hop_statement']
What developers are assigned to projects in the [testing] stage?	'Roslyn', 'Tom'	['question_type_global', 'question_three_hop_statement']
[knowledge base project] is now in the [implementation] stage
Who are the testers on [that project]	'Cyndi', 'Emma', 'Francoise'	['question_type_local']
What are the resolved issues for [important] projects?	'wrong pos tag on consecutive words', 'saving data throws exception', 'tokenization not consistent across platforms', 'svd is slow', 'versioning needs to be made consistent', 'timeout problem', 'parsing with parantheses fails', 'memory leak bug', 'issue in using training data'	['question_type_global', 'question_two_hop_statement']
[that project] is in the stage of [development]
What projects is [Emma] working on?	'mobile', 'chatbot', 'knowledge base'	['question_type_local']
who are the developers?	'Roslyn', 'Tom'	['question_type_global', 'question_single_statement']
What are the issues that are resolved for projects in the [testing] stage?	'wrong pos tag on consecutive words', 'saving data throws exception', 'parsing with parantheses fails', 'memory leak bug'	['question_type_global', 'question_three_hop_statement']
Who is currently working on projects in the [development] stage?	'Cyndi', 'Emma', 'Roslyn', 'Francoise', 'Tom'	['question_type_global', 'question_two_hop_statement']
What are the issues assigned to [Cyndi] that were resolved?	'wrong pos tag on consecutive words', 'parsing with parantheses fails', 'memory leak bug', 'issue in using training data'	['question_type_local']
Are there any [bug]s that are not resolved?	'wrong pos tag on consecutive words'	['question_type_global', 'question_two_hop_statement']
Are there any people assigned to the [important] projects?	'Cyndi', 'Emma', 'Roslyn', 'Francoise', 'Tom'	['question_type_global', 'question_two_hop_statement']
Are there any issues for [that project] that are resolved?	'versioning needs to be made consistent', 'timeout problem', 'issue in using training data'	['question_type_global', 'question_two_hop_statement']
[this project] is now in the [testing] stage
Are there any testers assigned to the [important] projects?	'Cyndi', 'Emma', 'Francoise'	['question_type_global', 'question_three_hop_statement']
Who is [the bug] assigned to?	'Cyndi'	['question_type_local']
who are the developers?	'Roslyn', 'Tom'	['question_type_global', 'question_single_statement']
What are the non resolved issues for projects in the [testing] stage?	'initialization broken'	['question_type_global', 'question_three_hop_statement']
[Tom] is not working on [mobile project] anymore
[that person] is working on [this project] also
What are the issues assigned to [Cyndi] that were resolved?	'wrong pos tag on consecutive words', 'parsing with parantheses fails', 'memory leak bug', 'issue in using training data'	['question_type_local']
What are the issues that are resolved for [important] projects?	'wrong pos tag on consecutive words', 'saving data throws exception', 'tokenization not consistent across platforms', 'svd is slow', 'versioning needs to be made consistent', 'timeout problem', 'parsing with parantheses fails', 'memory leak bug', 'issue in using training data'	['question_type_global', 'question_two_hop_statement']
What projects are in the [development] stage?	'chatbot'	['question_type_global', 'question_single_statement']
Are there any issues that are resolved for projects in the [testing] stage?	'wrong pos tag on consecutive words', 'saving data throws exception', 'versioning needs to be made consistent', 'timeout problem', 'parsing with parantheses fails', 'memory leak bug', 'issue in using training data'	['question_type_global', 'question_three_hop_statement']
who are the developers?	'Roslyn', 'Tom'	['question_type_global', 'question_single_statement']
What developers are assigned to the [important] projects?	'Roslyn', 'Tom'	['question_type_global', 'question_three_hop_statement']
Who has issues assigned to them that were all resolved?	'Cyndi', 'Emma', 'Tom'	['question_type_global', 'question_two_hop_statement']
Who is assigned to projects in the [development] stage?	'Cyndi', 'Emma', 'Roslyn', 'Francoise', 'Tom'	['question_type_global', 'question_two_hop_statement']
What projects are currently in the [testing] stage?	'mobile', 'knowledge base'	['question_type_global', 'question_single_statement']
Who is assigned to projects in the [testing] stage?	'Cyndi', 'Emma', 'Roslyn', 'Francoise', 'Tom'	['question_type_global', 'question_two_hop_statement']
Who is assigned to the [important] projects?	'Cyndi', 'Emma', 'Roslyn', 'Francoise', 'Tom'	['question_type_global', 'question_two_hop_statement']
What are the issues that are resolved for [important] projects?	'wrong pos tag on consecutive words', 'saving data throws exception', 'tokenization not consistent across platforms', 'svd is slow', 'versioning needs to be made consistent', 'timeout problem', 'parsing with parantheses fails', 'memory leak bug', 'issue in using training data'	['question_type_global', 'question_two_hop_statement']
[that developer] is not working on [chatbot project] anymore
[it] is assigned to [this developer] also
Who is [the svd is slow issue] assigned to?	'Tom'	['question_type_local']
Who is currently working on projects in the [testing] stage?	'Cyndi', 'Emma', 'Roslyn', 'Francoise', 'Tom'	['question_type_global', 'question_two_hop_statement']
[it] is in the stage of [deployment]
Who are the testers currently working on the [important] projects?	'Cyndi', 'Emma', 'Francoise'	['question_type_global', 'question_three_hop_statement']
who are the testers?	'Cyndi', 'Emma', 'Francoise'	['question_type_global', 'question_single_statement']
What projects are [important]?	'mobile', 'chatbot', 'knowledge base'	['question_type_global', 'question_single_statement']
What are the issues for [mobile project] that are resolved?	'wrong pos tag on consecutive words', 'saving data throws exception', 'parsing with parantheses fails', 'memory leak bug'	['question_type_global', 'question_two_hop_statement']
Are there any [proposal]s that are not resolved?	'timeout problem', 'parsing with parantheses fails'	['question_type_global', 'question_two_hop_statement']
Who is [the versioning needs to be made consistent issue] assigned to?	'Emma'	['question_type_local']
Are there any issues that are resolved for projects in the [testing] stage?	'wrong pos tag on consecutive words', 'saving data throws exception', 'versioning needs to be made consistent', 'timeout problem', 'parsing with parantheses fails', 'memory leak bug', 'issue in using training data'	['question_type_global', 'question_three_hop_statement']
Which testers have issues assigned to them that were all resolved?	'Cyndi', 'Emma'	['question_type_global', 'question_three_hop_statement']
What are the issues that are not resolved for projects in the [testing] stage?	'initialization broken'	['question_type_global', 'question_three_hop_statement']
Who was [the svd is slow issue] assigned to?	'Tom'	['question_type_local']
Who are the developers currently working on the [important] projects?	'Roslyn', 'Tom'	['question_type_global', 'question_three_hop_statement']
What projects are in the [deployment] stage?	'chatbot'	['question_type_global', 'question_single_statement']
[this project] has moved to the [development] stage
Which developers have issues assigned to them that were all resolved?	'Tom'	['question_type_global', 'question_three_hop_statement']
[that project] is in the [implementation] stage
Who is [the versioning needs to be made consistent issue] assigned to?	'Emma'	['question_type_local']
What developers are assigned to the [important] projects?	'Roslyn', 'Tom'	['question_type_global', 'question_three_hop_statement']
What developers are assigned to projects in the [testing] stage?	'Roslyn', 'Tom'	['question_type_global', 'question_three_hop_statement']
What are the non resolved [bug]s?	'wrong pos tag on consecutive words'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are resolved for projects in the [testing] stage?	'wrong pos tag on consecutive words', 'saving data throws exception', 'versioning needs to be made consistent', 'timeout problem', 'parsing with parantheses fails', 'memory leak bug', 'issue in using training data'	['question_type_global', 'question_three_hop_statement']
Who are the testers currently working on projects in the [implementation] stage?	'Cyndi', 'Emma', 'Francoise'	['question_type_global', 'question_three_hop_statement']
Are there any issues that are resolved for projects in the [implementation] stage?	'tokenization not consistent across platforms', 'svd is slow'	['question_type_global', 'question_three_hop_statement']
[this project] has moved to the [testing] stage
[knowledge base project] is now in the [deployment] stage
Who is working on [chatbot project]?	'Cyndi', 'Emma', 'Roslyn', 'Francoise', 'Tom'	['question_type_local']
Are there any issues that are resolved?	'wrong pos tag on consecutive words', 'saving data throws exception', 'tokenization not consistent across platforms', 'svd is slow', 'versioning needs to be made consistent', 'timeout problem', 'parsing with parantheses fails', 'memory leak bug', 'issue in using training data'	['question_type_global', 'question_single_statement']
who are the testers?	'Cyndi', 'Emma', 'Francoise'	['question_type_global', 'question_single_statement']
Are there any [important] projects?	'mobile', 'chatbot', 'knowledge base'	['question_type_global', 'question_single_statement']
What are the resolved issues?	'wrong pos tag on consecutive words', 'saving data throws exception', 'tokenization not consistent across platforms', 'svd is slow', 'versioning needs to be made consistent', 'timeout problem', 'parsing with parantheses fails', 'memory leak bug', 'issue in using training data'	['question_type_global', 'question_single_statement']
[knowledge base project] has moved to the [development] stage
Who is [the tokenization not consistent across platforms issue] assigned to?	'Emma'	['question_type_local']
Who has issues assigned to them that were all resolved?	'Cyndi', 'Emma', 'Tom'	['question_type_global', 'question_two_hop_statement']
Who was [the saving data throws exception issue] assigned to?	'Tom'	['question_type_local']
Which testers have issues assigned to them that were all resolved?	'Cyndi', 'Emma'	['question_type_global', 'question_three_hop_statement']
Are there any issues for [chatbot project] that are resolved?	'tokenization not consistent across platforms', 'svd is slow'	['question_type_global', 'question_two_hop_statement']
Are there any testers assigned to the [important] projects?	'Cyndi', 'Emma', 'Francoise'	['question_type_global', 'question_three_hop_statement']
Are there any developers assigned to the [important] projects?	'Roslyn', 'Tom'	['question_type_global', 'question_three_hop_statement']
Who is [the timeout problem proposal] assigned to?	'Tom'	['question_type_local']
What testers are assigned to projects in the [testing] stage?	'Cyndi', 'Emma', 'Francoise'	['question_type_global', 'question_three_hop_statement']
Who are the developers currently working on projects in the [development] stage?	'Roslyn', 'Tom'	['question_type_global', 'question_three_hop_statement']
Who is [the memory leak bug issue] assigned to?	'Cyndi'	['question_type_local']
What are the issues that are resolved for [important] projects?	'wrong pos tag on consecutive words', 'saving data throws exception', 'tokenization not consistent across platforms', 'svd is slow', 'versioning needs to be made consistent', 'timeout problem', 'parsing with parantheses fails', 'memory leak bug', 'issue in using training data'	['question_type_global', 'question_two_hop_statement']
Who is working on [mobile project]?	'Cyndi', 'Emma', 'Roslyn', 'Francoise', 'Tom'	['question_type_local']
Are there any issues that are not resolved for [important] projects?	'initialization broken'	['question_type_global', 'question_two_hop_statement']
What are the non resolved issues for [important] projects?	'initialization broken'	['question_type_global', 'question_two_hop_statement']
What are the [bug]s that are not resolved?	'wrong pos tag on consecutive words'	['question_type_global', 'question_two_hop_statement']
[chatbot project] is in the stage of [deployment]
Are there projects in the [deployment] stage?	'chatbot'	['question_type_global', 'question_single_statement']
who are the testers?	'Cyndi', 'Emma', 'Francoise'	['question_type_global', 'question_single_statement']
What developers are assigned to the [important] projects?	'Roslyn', 'Tom'	['question_type_global', 'question_three_hop_statement']
[the initialization broken issue] was assigned to [Roslyn]
[that developer] resolved [it]
