there is a new [internal] [chatbot] [project]
[chatbot project] is in the stage of [implementation]
Which is the stage of [this project]?	'implementation'	['question_type_local']
There is a new [proposal] for the [that project]: [memory leak bug]
[that project] is now in the [development] stage
There is a new [task] for the [this project]: [tokenization not consistent across platforms]
[Jack] is a [developer]
[chatbot project] is assigned to [Jack]
[the memory leak bug proposal] is assigned to [that developer]
[Jack] resolved [the memory leak bug issue]
[Francoise] is a [developer] on [chatbot project]
Who has issues assigned to them that were all resolved?	'Jack'	['question_type_global', 'question_two_hop_statement']
[svd is slow] is a new [proposal] for the [chatbot project]
What projects is [Jack] working on?	'chatbot'	['question_type_local']
Are there any issues that are not resolved for [internal] projects?	'tokenization not consistent across platforms', 'svd is slow'	['question_type_global', 'question_two_hop_statement']
[the svd is slow issue] was assigned to [Jack]
[he] resolved [the svd is slow issue]
[he] created a new [task] for [chatbot project]: [fails with apache stack]
[the issue] was assigned to [Jack]
[that developer] resolved [that issue]
What are the issues that are not resolved?	'tokenization not consistent across platforms'	['question_type_global', 'question_single_statement']
Are there any issues that are resolved?	'memory leak bug', 'svd is slow', 'fails with apache stack'	['question_type_global', 'question_single_statement']
there is a new [knowledge base] [project]
[Jack] is assigned to [this project] also
[that developer] submitted a new [enhancement] for [that project]: [changelong needs to be added]
[that project] is in the [implementation] stage
[knowledge base project] is a [open source] project
[parse example terribly slow] is a new issue for the [that project]
[this issue] is assigned to [Jack]
Which is the stage of [chatbot project]?	'development'	['question_type_local']
Who has issues assigned to them that were all resolved?	'Jack'	['question_type_global', 'question_two_hop_statement']
Which developers have issues assigned to them that were not resolved?	'Jack'	['question_type_global', 'question_three_hop_statement']
What projects are in the [development] stage?	'chatbot'	['question_type_global', 'question_single_statement']
Who are the developers currently working on the [open source] projects?	'Jack'	['question_type_global', 'question_three_hop_statement']
What projects are currently in the [implementation] stage?	'knowledge base'	['question_type_global', 'question_single_statement']
[chatbot project] is in the [evaluation] stage
[Eun] is a [tester]
[chatbot project] has moved to the [implementation] stage
[Danita] is a [tester] on [chatbot project]
[that project] is in the [evaluation] stage
[that person] is assigned to [knowledge base project] also
there is a new [mobile] [project]
What are the issues that were resolved?	'memory leak bug', 'svd is slow', 'fails with apache stack'	['question_type_global', 'question_single_statement']
[mobile project] is a [open source] project
[Jack] resolved [the parse example terribly slow issue]
[Jack] is assigned to [mobile project] also
[mobile project] is currently in the [implementation] stage
[this project] has moved to the [evaluation] stage
Are there any issues submitted by [Jack] that are resolved?	'fails with apache stack'	['question_type_local']
What testers are assigned to the [internal] projects?	'Danita'	['question_type_global', 'question_three_hop_statement']
What are the issues that are not resolved for projects in the [evaluation] stage?	'tokenization not consistent across platforms'	['question_type_global', 'question_three_hop_statement']
[that project] is in the [maintenance] stage
[knowledge base project] has moved to the [evaluation] stage
[Lucio] is a [developer] on [mobile project]
[Andy] is a [developer] on [it]
[chatbot project] is assigned to [Andy] also
[mobile project] is assigned to [Andy] also
[chatbot project] is not assigned to [Andy]
[chatbot project] is assigned to [this developer] also
Who is [the parse example terribly slow issue] assigned to?	'Jack'	['question_type_local']
Are there any issues for [it] that are not resolved?	'tokenization not consistent across platforms'	['question_type_global', 'question_two_hop_statement']
[Loyd] is a [developer] on [chatbot project]
[it] is in the stage of [implementation]
There is a new [task] for the [that project]: [wrong pos tag on consecutive words]
Are there any projects that are [open source]?	'knowledge base', 'mobile'	['question_type_global', 'question_single_statement']
[the issue] was assigned to [Danita]
[that test engineer] resolved [this issue]
[Charlott] is a [tester]
[mobile project] is assigned to [Danita] also
There is a new [enhancement] for the [chatbot project]: [two consecutive dates identified as single date]
Are there any testers assigned to the [open source] projects?	'Danita'	['question_type_global', 'question_three_hop_statement']
Who are the developers currently working on the [internal] projects?	'Jack', 'Francoise', 'Andy', 'Loyd'	['question_type_global', 'question_three_hop_statement']
What are the non resolved [enhancement]s?	'changelong needs to be added', 'two consecutive dates identified as single date'	['question_type_global', 'question_two_hop_statement']
[Emmie] is a [tester] on [chatbot project]
[this test engineer] is working on [mobile project] also
[Britney] is a [developer]
[chatbot project] is assigned to [Britney]
[mobile project] is assigned to [that person] also
Are there any testers assigned to projects in the [implementation] stage?	'Danita', 'Emmie'	['question_type_global', 'question_three_hop_statement']
What projects are [internal]?	'chatbot'	['question_type_global', 'question_single_statement']
Are there projects in the [implementation] stage?	'chatbot'	['question_type_global', 'question_single_statement']
What are the issues for [knowledge base project] that are not resolved?	'changelong needs to be added'	['question_type_global', 'question_two_hop_statement']
[knowledge base project] is assigned to [Britney] also
What are the issues submitted by [Jack] that were resolved?	'fails with apache stack'	['question_type_local']
What projects are currently in the [maintenance] stage?	'mobile'	['question_type_global', 'question_single_statement']
who are the testers?	'Eun', 'Danita', 'Charlott', 'Emmie'	['question_type_global', 'question_single_statement']
Who has issues assigned to them that were all resolved?	'Jack', 'Danita'	['question_type_global', 'question_two_hop_statement']
What are the issues that are resolved for projects in the [evaluation] stage?	'parse example terribly slow'	['question_type_global', 'question_three_hop_statement']
[Francoise] is assigned to [mobile project] also
[this person] is working on [knowledge base project] also
who are the developers?	'Jack', 'Francoise', 'Lucio', 'Andy', 'Loyd', 'Britney'	['question_type_global', 'question_single_statement']
What are the non resolved [task]s?	'fails with apache stack', 'wrong pos tag on consecutive words'	['question_type_global', 'question_two_hop_statement']
What are the issues that are not resolved for [internal] projects?	'tokenization not consistent across platforms', 'two consecutive dates identified as single date'	['question_type_global', 'question_two_hop_statement']
What are the issues that are resolved for [open source] projects?	'parse example terribly slow'	['question_type_global', 'question_two_hop_statement']
Who has issues assigned to them that were all resolved?	'Jack', 'Danita'	['question_type_global', 'question_two_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Jack'	['question_type_global', 'question_three_hop_statement']
What are the non resolved issues?	'tokenization not consistent across platforms', 'changelong needs to be added', 'two consecutive dates identified as single date'	['question_type_global', 'question_single_statement']
Are there any developers assigned to the [open source] projects?	'Jack', 'Francoise', 'Lucio', 'Andy', 'Britney'	['question_type_global', 'question_three_hop_statement']
[chatbot project] is not assigned to [Britney]
[Britney] is working on [chatbot project] also
which testers are assigned to [knowledge base project]	'Danita'	['question_type_local']
What are the issues for [knowledge base project] that are resolved?	'parse example terribly slow'	['question_type_global', 'question_two_hop_statement']
What are the non resolved [enhancement]s?	'changelong needs to be added', 'two consecutive dates identified as single date'	['question_type_global', 'question_two_hop_statement']
What are the [task]s that are not resolved?	'tokenization not consistent across platforms'	['question_type_global', 'question_two_hop_statement']
What are the issues that are resolved for [open source] projects?	'parse example terribly slow'	['question_type_global', 'question_two_hop_statement']
Who submitted [the changelong needs to be added enhancement]?	'Jack'	['question_type_local']
Which developers have issues assigned to them that were all resolved?	'Jack'	['question_type_global', 'question_three_hop_statement']
What are the issues for [this project] that are not resolved?	'tokenization not consistent across platforms', 'two consecutive dates identified as single date'	['question_type_global', 'question_two_hop_statement']
Which testers have issues assigned to them that were all resolved?	'Danita'	['question_type_global', 'question_three_hop_statement']
[knowledge base project] has moved to the [implementation] stage
[chatbot project] has moved to the [development] stage
who are the testers?	'Eun', 'Danita', 'Charlott', 'Emmie'	['question_type_global', 'question_single_statement']
Who is currently working on the [open source] projects?	'Jack', 'Francoise', 'Danita', 'Lucio', 'Andy', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
What testers are assigned to the [internal] projects?	'Danita', 'Emmie'	['question_type_global', 'question_three_hop_statement']
Who has issues assigned to them that were all resolved?	'Jack', 'Danita'	['question_type_global', 'question_two_hop_statement']
Are there any testers assigned to projects in the [maintenance] stage?	'Danita', 'Emmie'	['question_type_global', 'question_three_hop_statement']
What are the non resolved issues for [knowledge base project]?	'changelong needs to be added'	['question_type_global', 'question_two_hop_statement']
[knowledge base project] is in the stage of [maintenance]
What developers are assigned to projects in the [development] stage?	'Jack', 'Francoise', 'Andy', 'Loyd', 'Britney'	['question_type_global', 'question_three_hop_statement']
[chatbot project] has moved to the [maintenance] stage
[chatbot project] is in the stage of [implementation]
Are there any issues for [this project] that are not resolved?	'tokenization not consistent across platforms', 'two consecutive dates identified as single date'	['question_type_global', 'question_two_hop_statement']
who are the developers?	'Jack', 'Francoise', 'Lucio', 'Andy', 'Loyd', 'Britney'	['question_type_global', 'question_single_statement']
Are there any people assigned to projects in the [implementation] stage?	'Jack', 'Francoise', 'Danita', 'Andy', 'Loyd', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
Are there any [open source] projects?	'knowledge base', 'mobile'	['question_type_global', 'question_single_statement']
Who are the developers currently working on projects in the [maintenance] stage?	'Jack', 'Francoise', 'Lucio', 'Andy', 'Britney'	['question_type_global', 'question_three_hop_statement']
who are the testers?	'Eun', 'Danita', 'Charlott', 'Emmie'	['question_type_global', 'question_single_statement']
What are the [proposal]s that are not resolved?	'memory leak bug', 'svd is slow'	['question_type_global', 'question_two_hop_statement']
Who are the testers on [mobile project]	'Danita', 'Emmie'	['question_type_local']
What are the issues that are resolved for [internal] projects?	'memory leak bug', 'svd is slow', 'fails with apache stack', 'wrong pos tag on consecutive words'	['question_type_global', 'question_two_hop_statement']
What developers are assigned to projects in the [maintenance] stage?	'Jack', 'Francoise', 'Lucio', 'Andy', 'Britney'	['question_type_global', 'question_three_hop_statement']
What are the [enhancement]s that are not resolved?	'changelong needs to be added', 'two consecutive dates identified as single date'	['question_type_global', 'question_two_hop_statement']
[this project] is now in the [development] stage
Who is [the memory leak bug proposal] assigned to?	'Jack'	['question_type_local']
Are there any [proposal]s that are not resolved?	'memory leak bug', 'svd is slow'	['question_type_global', 'question_two_hop_statement']
What are the issues for [it] that are resolved?	'memory leak bug', 'svd is slow', 'fails with apache stack', 'wrong pos tag on consecutive words'	['question_type_global', 'question_two_hop_statement']
Who has issues assigned to them that were all resolved?	'Jack', 'Danita'	['question_type_global', 'question_two_hop_statement']
What projects is [Danita] working on?	'chatbot', 'knowledge base', 'mobile'	['question_type_local']
Who are the testers currently working on projects in the [development] stage?	'Danita', 'Emmie'	['question_type_global', 'question_three_hop_statement']
Who is working on [knowledge base project]?	'Jack', 'Francoise', 'Danita', 'Andy', 'Britney'	['question_type_local']
What are the non resolved issues for [open source] projects?	'changelong needs to be added'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are resolved?	'memory leak bug', 'svd is slow', 'fails with apache stack', 'parse example terribly slow', 'wrong pos tag on consecutive words'	['question_type_global', 'question_single_statement']
Which testers have issues assigned to them that were all resolved?	'Danita'	['question_type_global', 'question_three_hop_statement']
[the tokenization not consistent across platforms issue] was assigned to [Andy]
[he] resolved [the tokenization not consistent across platforms issue]
What are the issues assigned to [Danita]?	'wrong pos tag on consecutive words'	['question_type_local']
Are there any people assigned to the [internal] projects?	'Jack', 'Francoise', 'Danita', 'Andy', 'Loyd', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
What are the non resolved issues for [knowledge base project]?	'changelong needs to be added'	['question_type_global', 'question_two_hop_statement']
[Loyd] is working on [mobile project] also
Who was [the wrong pos tag on consecutive words task] assigned to?	'Danita'	['question_type_local']
What are the resolved issues for [knowledge base project]?	'parse example terribly slow'	['question_type_global', 'question_two_hop_statement']
Who has issues assigned to them that were all resolved?	'Jack', 'Danita', 'Andy'	['question_type_global', 'question_two_hop_statement']
What are the issues for [chatbot project] that are resolved?	'memory leak bug', 'tokenization not consistent across platforms', 'svd is slow', 'fails with apache stack', 'wrong pos tag on consecutive words'	['question_type_global', 'question_two_hop_statement']
Are there any developers assigned to projects in the [maintenance] stage?	'Jack', 'Francoise', 'Lucio', 'Andy', 'Loyd', 'Britney'	['question_type_global', 'question_three_hop_statement']
[the two consecutive dates identified as single date enhancement] was assigned to [Loyd]
[that developer] resolved [the two consecutive dates identified as single date issue]
[knowledge base project] is assigned to [Loyd] also
Who is [the task that was last added] assigned to?	'Danita'	['question_type_local']
What are the non resolved issues?	'changelong needs to be added'	['question_type_global', 'question_single_statement']
Who is currently working on the [internal] projects?	'Jack', 'Francoise', 'Danita', 'Andy', 'Loyd', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
What projects are [open source]?	'knowledge base', 'mobile'	['question_type_global', 'question_single_statement']
Who is currently working on projects in the [development] stage?	'Jack', 'Francoise', 'Danita', 'Andy', 'Loyd', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
What testers are assigned to projects in the [maintenance] stage?	'Danita', 'Emmie'	['question_type_global', 'question_three_hop_statement']
Who are the developers currently working on projects in the [development] stage?	'Jack', 'Francoise', 'Andy', 'Loyd', 'Britney'	['question_type_global', 'question_three_hop_statement']
Are there any projects that are [internal]?	'chatbot'	['question_type_global', 'question_single_statement']
[that project] is now in the [development] stage
Are there any developers assigned to the [internal] projects?	'Jack', 'Francoise', 'Andy', 'Loyd', 'Britney'	['question_type_global', 'question_three_hop_statement']
who are the developers?	'Jack', 'Francoise', 'Lucio', 'Andy', 'Loyd', 'Britney'	['question_type_global', 'question_single_statement']
What are the issues that are not resolved for projects in the [development] stage?	'changelong needs to be added'	['question_type_global', 'question_three_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Jack', 'Andy', 'Loyd'	['question_type_global', 'question_three_hop_statement']
What are the issues created by [Jack]?	'fails with apache stack', 'changelong needs to be added'	['question_type_local']
What are the [task]s that are not resolved?	'tokenization not consistent across platforms', 'fails with apache stack', 'wrong pos tag on consecutive words'	['question_type_global', 'question_two_hop_statement']
Are there any developers assigned to projects in the [maintenance] stage?	'Jack', 'Francoise', 'Lucio', 'Andy', 'Loyd', 'Britney'	['question_type_global', 'question_three_hop_statement']
[knowledge base project] is in the [implementation] stage
What testers are assigned to projects in the [development] stage?	'Danita', 'Emmie'	['question_type_global', 'question_three_hop_statement']
What are the issues that are resolved for [open source] projects?	'parse example terribly slow'	['question_type_global', 'question_two_hop_statement']
Are there any developers assigned to the [internal] projects?	'Jack', 'Francoise', 'Andy', 'Loyd', 'Britney'	['question_type_global', 'question_three_hop_statement']
who are the developers?	'Jack', 'Francoise', 'Lucio', 'Andy', 'Loyd', 'Britney'	['question_type_global', 'question_single_statement']
Who are the testers currently working on the [open source] projects?	'Danita', 'Emmie'	['question_type_global', 'question_three_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Jack', 'Andy', 'Loyd'	['question_type_global', 'question_three_hop_statement']
Are there any issues for [it] that are resolved?	'parse example terribly slow'	['question_type_global', 'question_two_hop_statement']
What projects are currently in the [maintenance] stage?	'mobile'	['question_type_global', 'question_single_statement']
Which testers are working on [chatbot project]?	'Danita', 'Emmie'	['question_type_local']
Are there any testers assigned to projects in the [maintenance] stage?	'Danita', 'Emmie'	['question_type_global', 'question_three_hop_statement']
who are the developers?	'Jack', 'Francoise', 'Lucio', 'Andy', 'Loyd', 'Britney'	['question_type_global', 'question_single_statement']
Who are the developers currently working on the [open source] projects?	'Jack', 'Francoise', 'Lucio', 'Andy', 'Loyd', 'Britney'	['question_type_global', 'question_three_hop_statement']
Are there any people assigned to projects in the [maintenance] stage?	'Jack', 'Francoise', 'Danita', 'Lucio', 'Andy', 'Loyd', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Jack', 'Andy', 'Loyd'	['question_type_global', 'question_three_hop_statement']
What projects is [Jack] working on?	'chatbot', 'knowledge base', 'mobile'	['question_type_local']
What developers are assigned to projects in the [maintenance] stage?	'Jack', 'Francoise', 'Lucio', 'Andy', 'Loyd', 'Britney'	['question_type_global', 'question_three_hop_statement']
What are the [internal] projects?	'chatbot'	['question_type_global', 'question_single_statement']
What are the issues for [this project] that are resolved?	'parse example terribly slow'	['question_type_global', 'question_two_hop_statement']
Who is assigned to the [open source] projects?	'Jack', 'Francoise', 'Danita', 'Lucio', 'Andy', 'Loyd', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
Are there any [enhancement]s that are not resolved?	'changelong needs to be added'	['question_type_global', 'question_two_hop_statement']
Are there projects in the [implementation] stage?	'knowledge base'	['question_type_global', 'question_single_statement']
Who is assigned to projects in the [implementation] stage?	'Jack', 'Francoise', 'Danita', 'Andy', 'Loyd', 'Britney'	['question_type_global', 'question_two_hop_statement']
Are there any people assigned to projects in the [development] stage?	'Jack', 'Francoise', 'Danita', 'Andy', 'Loyd', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
Who are the testers currently working on projects in the [maintenance] stage?	'Danita', 'Emmie'	['question_type_global', 'question_three_hop_statement']
Are there any issues for [knowledge base project] that are not resolved?	'changelong needs to be added'	['question_type_global', 'question_two_hop_statement']
What are the issues that are not resolved?	'changelong needs to be added'	['question_type_global', 'question_single_statement']
Are there any developers assigned to the [open source] projects?	'Jack', 'Francoise', 'Lucio', 'Andy', 'Loyd', 'Britney'	['question_type_global', 'question_three_hop_statement']
What are the issues assigned to [Danita] that were resolved?	'wrong pos tag on consecutive words'	['question_type_local']
What are the issues that are resolved for [open source] projects?	'parse example terribly slow'	['question_type_global', 'question_two_hop_statement']
[knowledge base project] is assigned to [Emmie] also
Who submitted [the changelong needs to be added enhancement]?	'Jack'	['question_type_local']
What are the resolved issues for [open source] projects?	'parse example terribly slow'	['question_type_global', 'question_two_hop_statement']
What are the non resolved issues?	'changelong needs to be added'	['question_type_global', 'question_single_statement']
Who is currently working on the [open source] projects?	'Jack', 'Francoise', 'Danita', 'Lucio', 'Andy', 'Loyd', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
What testers are assigned to the [internal] projects?	'Danita', 'Emmie'	['question_type_global', 'question_three_hop_statement']
What testers are assigned to projects in the [development] stage?	'Danita', 'Emmie'	['question_type_global', 'question_three_hop_statement']
Which testers have issues assigned to them that were all resolved?	'Danita'	['question_type_global', 'question_three_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Jack', 'Andy', 'Loyd'	['question_type_global', 'question_three_hop_statement']
Who are the developers currently working on projects in the [implementation] stage?	'Jack', 'Francoise', 'Andy', 'Loyd', 'Britney'	['question_type_global', 'question_three_hop_statement']
who are the testers?	'Eun', 'Danita', 'Charlott', 'Emmie'	['question_type_global', 'question_single_statement']
What stage is [chatbot project] in?	'development'	['question_type_local']
Were there any issues assigned to [Loyd]?	'two consecutive dates identified as single date'	['question_type_local']
Are there any people assigned to the [internal] projects?	'Jack', 'Francoise', 'Danita', 'Andy', 'Loyd', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
Are there any developers assigned to the [open source] projects?	'Jack', 'Francoise', 'Lucio', 'Andy', 'Loyd', 'Britney'	['question_type_global', 'question_three_hop_statement']
Who is assigned to projects in the [maintenance] stage?	'Jack', 'Francoise', 'Danita', 'Lucio', 'Andy', 'Loyd', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
Who are the developers on [chatbot project]	'Jack', 'Francoise', 'Andy', 'Loyd', 'Britney'	['question_type_local']
[chatbot project] has moved to the [evaluation] stage
Who are the testers currently working on projects in the [implementation] stage?	'Danita', 'Emmie'	['question_type_global', 'question_three_hop_statement']
who are the testers?	'Eun', 'Danita', 'Charlott', 'Emmie'	['question_type_global', 'question_single_statement']
Who are the developers on [mobile project]	'Jack', 'Francoise', 'Lucio', 'Andy', 'Loyd', 'Britney'	['question_type_local']
Who is currently working on projects in the [implementation] stage?	'Jack', 'Francoise', 'Danita', 'Andy', 'Loyd', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
Are there any testers assigned to projects in the [evaluation] stage?	'Danita', 'Emmie'	['question_type_global', 'question_three_hop_statement']
Are there any issues that are resolved for [open source] projects?	'parse example terribly slow'	['question_type_global', 'question_two_hop_statement']
Which testers have issues assigned to them that were all resolved?	'Danita'	['question_type_global', 'question_three_hop_statement']
Who has issues assigned to them that were all resolved?	'Jack', 'Danita', 'Andy', 'Loyd'	['question_type_global', 'question_two_hop_statement']
Who was [the fails with apache stack task] assigned to?	'Jack'	['question_type_local']
Are there any developers assigned to projects in the [maintenance] stage?	'Jack', 'Francoise', 'Lucio', 'Andy', 'Loyd', 'Britney'	['question_type_global', 'question_three_hop_statement']
What are the [internal] projects?	'chatbot'	['question_type_global', 'question_single_statement']
[knowledge base project] is in the stage of [evaluation]
What are the issues assigned to [Danita] that were resolved?	'wrong pos tag on consecutive words'	['question_type_local']
What are the issues that are not resolved for projects in the [evaluation] stage?	'changelong needs to be added'	['question_type_global', 'question_three_hop_statement']
[chatbot project] is in the stage of [maintenance]
Who was [the task that was last added] assigned to?	'Danita'	['question_type_local']
Who is assigned to the [open source] projects?	'Jack', 'Francoise', 'Danita', 'Lucio', 'Andy', 'Loyd', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
What are the issues that are not resolved?	'changelong needs to be added'	['question_type_global', 'question_single_statement']
[chatbot project] is now in the [development] stage
[that project] has moved to the [implementation] stage
[chatbot project] is now in the [evaluation] stage
[this project] is now in the [development] stage
[Charlott] is assigned to [mobile project]
Who was [the two consecutive dates identified as single date enhancement] assigned to?	'Loyd'	['question_type_local']
Are there any [internal] projects?	'chatbot'	['question_type_global', 'question_single_statement']
What are the non resolved [enhancement]s?	'two consecutive dates identified as single date'	['question_type_global', 'question_two_hop_statement']
Who is assigned to the [internal] projects?	'Jack', 'Francoise', 'Danita', 'Andy', 'Loyd', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
who are the developers?	'Jack', 'Francoise', 'Lucio', 'Andy', 'Loyd', 'Britney'	['question_type_global', 'question_single_statement']
Are there any testers assigned to the [open source] projects?	'Danita', 'Charlott', 'Emmie'	['question_type_global', 'question_three_hop_statement']
[chatbot project] is assigned to [that test engineer] also
[this person] is assigned to [knowledge base project] also
What are the non resolved issues?	'changelong needs to be added'	['question_type_global', 'question_single_statement']
What projects are [open source]?	'knowledge base', 'mobile'	['question_type_global', 'question_single_statement']
Who is currently working on projects in the [evaluation] stage?	'Jack', 'Francoise', 'Danita', 'Andy', 'Loyd', 'Charlott', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are not resolved for [open source] projects?	'changelong needs to be added'	['question_type_global', 'question_two_hop_statement']
[chatbot project] is not assigned to [Charlott]
[this tester] is assigned to [chatbot project] also
[mobile project] is in the stage of [development]
Who is assigned to the [open source] projects?	'Jack', 'Francoise', 'Danita', 'Lucio', 'Andy', 'Loyd', 'Charlott', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
Are there any [task]s that are not resolved?	'tokenization not consistent across platforms', 'fails with apache stack', 'wrong pos tag on consecutive words'	['question_type_global', 'question_two_hop_statement']
What are the non resolved issues for [open source] projects?	'changelong needs to be added'	['question_type_global', 'question_two_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Jack', 'Andy', 'Loyd'	['question_type_global', 'question_three_hop_statement']
Are there any developers assigned to projects in the [development] stage?	'Jack', 'Francoise', 'Lucio', 'Andy', 'Loyd', 'Britney'	['question_type_global', 'question_three_hop_statement']
What projects is [Britney] working on?	'chatbot', 'knowledge base', 'mobile'	['question_type_local']
What projects is [Lucio] working on?	'mobile'	['question_type_local']
What are the [enhancement]s that are not resolved?	'changelong needs to be added'	['question_type_global', 'question_two_hop_statement']
What are the issues that are not resolved?	'changelong needs to be added'	['question_type_global', 'question_single_statement']
Which developers are assigned to [chatbot project]	'Jack', 'Francoise', 'Andy', 'Loyd', 'Britney'	['question_type_local']
Are there any projects that are [internal]?	'chatbot'	['question_type_global', 'question_single_statement']
Are there any people assigned to projects in the [evaluation] stage?	'Jack', 'Francoise', 'Danita', 'Andy', 'Loyd', 'Charlott', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
What are the issues that are resolved for [open source] projects?	'parse example terribly slow'	['question_type_global', 'question_two_hop_statement']
Who is assigned to the [internal] projects?	'Jack', 'Francoise', 'Danita', 'Andy', 'Loyd', 'Charlott', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
[mobile project] is now in the [maintenance] stage
[that project] has moved to the [implementation] stage
Which testers are working on [this project]?	'Danita', 'Charlott', 'Emmie'	['question_type_local']
What are the resolved issues for [open source] projects?	'parse example terribly slow'	['question_type_global', 'question_two_hop_statement']
Who is [the tokenization not consistent across platforms issue] assigned to?	'Andy'	['question_type_local']
Are there any developers assigned to projects in the [development] stage?	'Jack', 'Francoise', 'Andy', 'Loyd', 'Britney'	['question_type_global', 'question_three_hop_statement']
who are the developers?	'Jack', 'Francoise', 'Lucio', 'Andy', 'Loyd', 'Britney'	['question_type_global', 'question_single_statement']
What are the issues that were resolved?	'memory leak bug', 'tokenization not consistent across platforms', 'svd is slow', 'fails with apache stack', 'parse example terribly slow', 'wrong pos tag on consecutive words', 'two consecutive dates identified as single date'	['question_type_global', 'question_single_statement']
What are the non resolved issues?	'changelong needs to be added'	['question_type_global', 'question_single_statement']
What are the [open source] projects?	'knowledge base', 'mobile'	['question_type_global', 'question_single_statement']
Who are the developers currently working on the [internal] projects?	'Jack', 'Francoise', 'Andy', 'Loyd', 'Britney'	['question_type_global', 'question_three_hop_statement']
What are the resolved issues for [internal] projects?	'memory leak bug', 'tokenization not consistent across platforms', 'svd is slow', 'fails with apache stack', 'wrong pos tag on consecutive words', 'two consecutive dates identified as single date'	['question_type_global', 'question_two_hop_statement']
What are the issues that are resolved for [internal] projects?	'memory leak bug', 'tokenization not consistent across platforms', 'svd is slow', 'fails with apache stack', 'wrong pos tag on consecutive words', 'two consecutive dates identified as single date'	['question_type_global', 'question_two_hop_statement']
What projects are [open source]?	'knowledge base', 'mobile'	['question_type_global', 'question_single_statement']
What projects is [Emmie] working on?	'chatbot', 'knowledge base', 'mobile'	['question_type_local']
Are there any developers assigned to projects in the [development] stage?	'Jack', 'Francoise', 'Andy', 'Loyd', 'Britney'	['question_type_global', 'question_three_hop_statement']
Are there any issues for [knowledge base project] that are not resolved?	'changelong needs to be added'	['question_type_global', 'question_two_hop_statement']
Who was [the fails with apache stack task] assigned to?	'Jack'	['question_type_local']
Are there any testers assigned to projects in the [development] stage?	'Danita', 'Charlott', 'Emmie'	['question_type_global', 'question_three_hop_statement']
who are the developers?	'Jack', 'Francoise', 'Lucio', 'Andy', 'Loyd', 'Britney'	['question_type_global', 'question_single_statement']
Who are the developers currently working on the [internal] projects?	'Jack', 'Francoise', 'Andy', 'Loyd', 'Britney'	['question_type_global', 'question_three_hop_statement']
[this project] is in the stage of [maintenance]
Are there any issues for [chatbot project] that are resolved?	'memory leak bug', 'tokenization not consistent across platforms', 'svd is slow', 'fails with apache stack', 'wrong pos tag on consecutive words', 'two consecutive dates identified as single date'	['question_type_global', 'question_two_hop_statement']
Who are the testers currently working on projects in the [development] stage?	'Danita', 'Charlott', 'Emmie'	['question_type_global', 'question_three_hop_statement']
What projects is [Loyd] working on?	'chatbot', 'knowledge base', 'mobile'	['question_type_local']
Are there projects in the [evaluation] stage?	'knowledge base'	['question_type_global', 'question_single_statement']
[it] is in the stage of [development]
[Charlott] is not working on [chatbot project] anymore
[Charlott] is assigned to [chatbot project] also
[this project] is now in the [evaluation] stage
who are the developers?	'Jack', 'Francoise', 'Lucio', 'Andy', 'Loyd', 'Britney'	['question_type_global', 'question_single_statement']
What are the issues that were resolved?	'memory leak bug', 'tokenization not consistent across platforms', 'svd is slow', 'fails with apache stack', 'parse example terribly slow', 'wrong pos tag on consecutive words', 'two consecutive dates identified as single date'	['question_type_global', 'question_single_statement']
Who is currently working on the [internal] projects?	'Jack', 'Francoise', 'Danita', 'Andy', 'Loyd', 'Charlott', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
Are there any people assigned to the [open source] projects?	'Jack', 'Francoise', 'Danita', 'Lucio', 'Andy', 'Loyd', 'Charlott', 'Emmie', 'Britney'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are resolved for [open source] projects?	'parse example terribly slow'	['question_type_global', 'question_two_hop_statement']
Which testers have issues assigned to them that were all resolved?	'Danita'	['question_type_global', 'question_three_hop_statement']
[that project] is in the [development] stage
Are there any [proposal]s that are not resolved?	'memory leak bug', 'svd is slow'	['question_type_global', 'question_two_hop_statement']
Are there any issues for [that project] that are resolved?	'memory leak bug', 'tokenization not consistent across platforms', 'svd is slow', 'fails with apache stack', 'wrong pos tag on consecutive words', 'two consecutive dates identified as single date'	['question_type_global', 'question_two_hop_statement']
[this project] is in the stage of [evaluation]
[chatbot project] has moved to the [implementation] stage
who are the testers?	'Eun', 'Danita', 'Charlott', 'Emmie'	['question_type_global', 'question_single_statement']
Who has issues assigned to them that were all resolved?	'Jack', 'Danita', 'Andy', 'Loyd'	['question_type_global', 'question_two_hop_statement']
[the changelong needs to be added issue] is assigned to [Loyd]
