there is a new [open source] [mobile] [project]
[mobile project] is in the [implementation] stage
[Francoise] is a [tester] on [it]
[it] is now in the [design] stage
there is a new [knowledge base] [project]
[knowledge base project] is in the stage of [maintenance]
[it] is a [external] project
[Igor] is a [tester]
[Gia] is a [tester] on [knowledge base project]
[Gia] is assigned to [mobile project] also
[Loyd] is a [developer]
[that person] is assigned to [that project]
Are there projects in the [maintenance] stage?	'knowledge base'	['question_type_global', 'question_single_statement']
Who are the developers currently working on projects in the [design] stage?	'Loyd'	['question_type_global', 'question_three_hop_statement']
[Peggy] is a [developer] on [knowledge base project]
What stage is [knowledge base project] in?	'maintenance'	['question_type_local']
[that project] is in the [maintenance] stage
there is a new [open source] [chatbot] [project]
Who are the testers currently working on the [external] projects?	'Gia'	['question_type_global', 'question_three_hop_statement']
[Alverta] is a [developer] on [mobile project]
[Alverta] is assigned to [knowledge base project] also
[that person] is not working on [mobile project] anymore
[chatbot project] is assigned to [Alverta] also
Who is working on [that project]?	'Alverta'	['question_type_local']
[this person] is working on [mobile project] also
[chatbot project] is currently in the [design] stage
Which developers are assigned to [mobile project]	'Loyd', 'Alverta'	['question_type_local']
Who is currently working on the [external] projects?	'Gia', 'Peggy', 'Alverta'	['question_type_global', 'question_two_hop_statement']
[Gabrielle] is a [tester]
There is a new issue for the [it]: [saving data throws exception]
[this tester] is working on [chatbot project]
[that test engineer] is working on [mobile project] also
[that project] is assigned to [Igor]
[this tester] is assigned to [knowledge base project] also
[Francoise] created a new issue for [mobile project]: [versioning needs to be made consistent]
Who are the developers on [chatbot project]	'Alverta'	['question_type_local']
What projects are in the [design] stage?	'chatbot'	['question_type_global', 'question_single_statement']
Which testers are working on [this project]?	'Igor', 'Gia'	['question_type_local']
Who are the developers currently working on the [external] projects?	'Peggy', 'Alverta'	['question_type_global', 'question_three_hop_statement']
[this issue] was assigned to [Gia]
[chatbot project] is assigned to [that person] also
Who is assigned to the [open source] projects?	'Francoise', 'Igor', 'Gia', 'Loyd', 'Alverta', 'Gabrielle'	['question_type_global', 'question_two_hop_statement']
[Gia] resolved [the versioning needs to be made consistent issue]
[this person] is not working on [chatbot project] anymore
[this project] is assigned to [that person] also
[Igor] is assigned to [that project] also
[mobile project] is in the stage of [design]
What projects is [Loyd] working on?	'mobile'	['question_type_local']
What are the non resolved issues?	'saving data throws exception'	['question_type_global', 'question_single_statement']
[chatbot project] is in the [implementation] stage
[Igor] created a new issue for [mobile project]: [timeout problem]
[the issue] is assigned to [Gia]
[she] resolved [that issue]
Who is assigned to projects in the [maintenance] stage?	'Igor', 'Gia', 'Peggy', 'Alverta'	['question_type_global', 'question_two_hop_statement']
Who is working on [chatbot project]?	'Igor', 'Gia', 'Alverta', 'Gabrielle'	['question_type_local']
What are the [open source] projects?	'mobile', 'chatbot'	['question_type_global', 'question_single_statement']
Who are the developers currently working on the [open source] projects?	'Loyd', 'Alverta'	['question_type_global', 'question_three_hop_statement']
who are the testers?	'Francoise', 'Igor', 'Gia', 'Gabrielle'	['question_type_global', 'question_single_statement']
Who is currently working on the [external] projects?	'Igor', 'Gia', 'Peggy', 'Alverta'	['question_type_global', 'question_two_hop_statement']
[minified version fails] is a new issue for the [chatbot project]
[that test engineer] is no longer assigned to [knowledge base project]
[she] is working on [knowledge base project] also
Which is the stage of [chatbot project]?	'implementation'	['question_type_local']
What are the issues that were resolved?	'versioning needs to be made consistent', 'timeout problem'	['question_type_global', 'question_single_statement']
[parsing with parantheses fails] is a new [bug] for [mobile project] that [Gabrielle] just created
[the issue] was assigned to [Gia]
[this test engineer] resolved [it]
What are the resolved issues for [open source] projects?	'versioning needs to be made consistent', 'timeout problem', 'parsing with parantheses fails'	['question_type_global', 'question_two_hop_statement']
[Peggy] created a new issue for [knowledge base project]: [dcoref always returns null]
who are the developers?	'Loyd', 'Peggy', 'Alverta'	['question_type_global', 'question_single_statement']
What are the issues that are not resolved?	'saving data throws exception', 'minified version fails', 'dcoref always returns null'	['question_type_global', 'question_single_statement']
Who has issues assigned to them that were all resolved?	'Gia'	['question_type_global', 'question_two_hop_statement']
[that issue] was assigned to [Peggy]
[chatbot project] is assigned to [Peggy] also
[Alverta] created a new [enhancement] for [chatbot project]: [changelong needs to be added]
Who submitted [the timeout problem issue]?	'Igor'	['question_type_local']
Who are the developers currently working on projects in the [maintenance] stage?	'Peggy', 'Alverta'	['question_type_global', 'question_three_hop_statement']
[this issue] is assigned to [Gia]
[she] is no longer assigned to [knowledge base project]
Who was [the parsing with parantheses fails bug] assigned to?	'Gia'	['question_type_local']
What are the non resolved issues for projects in the [implementation] stage?	'saving data throws exception', 'minified version fails', 'changelong needs to be added'	['question_type_global', 'question_three_hop_statement']
[this project] has moved to the [design] stage
[that project] is assigned to [Gia] also
Who are the developers on [mobile project]	'Loyd', 'Alverta'	['question_type_local']
Are there projects in the [implementation] stage?	'chatbot'	['question_type_global', 'question_single_statement']
who are the testers?	'Francoise', 'Igor', 'Gia', 'Gabrielle'	['question_type_global', 'question_single_statement']
What projects are currently in the [design] stage?	'mobile', 'knowledge base'	['question_type_global', 'question_single_statement']
[mobile project] has moved to the [implementation] stage
[mobile project] is assigned to [Peggy] also
[Gia] resolved [the changelong needs to be added enhancement]
What stage is [knowledge base project] in?	'design'	['question_type_local']
[Gabrielle] is assigned to [knowledge base project] also
Are there any issues submitted by [Francoise] that are resolved?	'versioning needs to be made consistent'	['question_type_local']
Who are the testers currently working on projects in the [implementation] stage?	'Francoise', 'Igor', 'Gia', 'Gabrielle'	['question_type_global', 'question_three_hop_statement']
Which developers have issues assigned to them that were not resolved?	'Peggy'	['question_type_global', 'question_three_hop_statement']
Are there projects in the [implementation] stage?	'mobile', 'chatbot'	['question_type_global', 'question_single_statement']
[chatbot project] is in the [maintenance] stage
Which is the stage of [chatbot project]?	'maintenance'	['question_type_local']
who are the testers?	'Francoise', 'Igor', 'Gia', 'Gabrielle'	['question_type_global', 'question_single_statement']
What testers are assigned to projects in the [design] stage?	'Igor', 'Gia', 'Gabrielle'	['question_type_global', 'question_three_hop_statement']
Are there any developers assigned to projects in the [implementation] stage?	'Loyd', 'Peggy', 'Alverta'	['question_type_global', 'question_three_hop_statement']
Who created [the parsing with parantheses fails bug]?	'Gabrielle'	['question_type_local']
Are there any issues that are not resolved for projects in the [design] stage?	'dcoref always returns null'	['question_type_global', 'question_three_hop_statement']
[knowledge base project] has moved to the [maintenance] stage
[chatbot project] is in the [design] stage
Who submitted [the enhancement]?	'Alverta'	['question_type_local']
Which testers have issues assigned to them that were all resolved?	'Gia'	['question_type_global', 'question_three_hop_statement']
Who is currently working on the [open source] projects?	'Francoise', 'Igor', 'Gia', 'Loyd', 'Peggy', 'Alverta', 'Gabrielle'	['question_type_global', 'question_two_hop_statement']
Which developers have issues assigned to them that were not resolved?	'Peggy'	['question_type_global', 'question_three_hop_statement']
[Gia] is no longer assigned to [knowledge base project]
[this test engineer] is assigned to [it] also
Which is the stage of [chatbot project]?	'design'	['question_type_local']
What are the [external] projects?	'knowledge base'	['question_type_global', 'question_single_statement']
Who has issues assigned to them that were all resolved?	'Gia'	['question_type_global', 'question_two_hop_statement']
What are the non resolved issues for [external] projects?	'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
which testers are assigned to [chatbot project]	'Igor', 'Gia', 'Gabrielle'	['question_type_local']
What projects are currently in the [implementation] stage?	'mobile'	['question_type_global', 'question_single_statement']
[Peggy] resolved [the dcoref always returns null issue]
Who is currently working on the [external] projects?	'Igor', 'Gia', 'Peggy', 'Alverta', 'Gabrielle'	['question_type_global', 'question_two_hop_statement']
What are the issues for [knowledge base project] that are resolved?	'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
Who created [the timeout problem issue]?	'Igor'	['question_type_local']
Are there any issues for [mobile project] that are resolved?	'versioning needs to be made consistent', 'timeout problem', 'parsing with parantheses fails'	['question_type_global', 'question_two_hop_statement']
What are the issues created by [Igor]?	'timeout problem'	['question_type_local']
who are the developers?	'Loyd', 'Peggy', 'Alverta'	['question_type_global', 'question_single_statement']
Who has issues assigned to them that were all resolved?	'Gia', 'Peggy'	['question_type_global', 'question_two_hop_statement']
Who was [this issue] assigned to?	'Peggy'	['question_type_local']
What are the resolved issues for [open source] projects?	'versioning needs to be made consistent', 'timeout problem', 'parsing with parantheses fails', 'changelong needs to be added'	['question_type_global', 'question_two_hop_statement']
What are the non resolved [enhancement]s?	'changelong needs to be added'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are resolved for projects in the [maintenance] stage?	'dcoref always returns null'	['question_type_global', 'question_three_hop_statement']
Which testers have issues assigned to them that were all resolved?	'Gia'	['question_type_global', 'question_three_hop_statement']
Are there any developers assigned to projects in the [implementation] stage?	'Loyd', 'Peggy', 'Alverta'	['question_type_global', 'question_three_hop_statement']
Are there any issues that are not resolved?	'saving data throws exception', 'minified version fails'	['question_type_global', 'question_single_statement']
who are the developers?	'Loyd', 'Peggy', 'Alverta'	['question_type_global', 'question_single_statement']
[knowledge base project] has moved to the [design] stage
Who was [the dcoref always returns null issue] assigned to?	'Peggy'	['question_type_local']
What are the non resolved issues for projects in the [design] stage?	'saving data throws exception', 'minified version fails'	['question_type_global', 'question_three_hop_statement']
What are the [open source] projects?	'mobile', 'chatbot'	['question_type_global', 'question_single_statement']
What are the issues for [mobile project] that are resolved?	'versioning needs to be made consistent', 'timeout problem', 'parsing with parantheses fails'	['question_type_global', 'question_two_hop_statement']
who are the testers?	'Francoise', 'Igor', 'Gia', 'Gabrielle'	['question_type_global', 'question_single_statement']
Who is assigned to the [open source] projects?	'Francoise', 'Igor', 'Gia', 'Loyd', 'Peggy', 'Alverta', 'Gabrielle'	['question_type_global', 'question_two_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Peggy'	['question_type_global', 'question_three_hop_statement']
What projects is [this developer] working on?	'mobile', 'knowledge base', 'chatbot'	['question_type_local']
Are there any issues for [mobile project] that are resolved?	'versioning needs to be made consistent', 'timeout problem', 'parsing with parantheses fails'	['question_type_global', 'question_two_hop_statement']
What are the non resolved issues for [open source] projects?	'saving data throws exception', 'minified version fails'	['question_type_global', 'question_two_hop_statement']
Are there any developers assigned to the [external] projects?	'Peggy', 'Alverta'	['question_type_global', 'question_three_hop_statement']
who are the developers?	'Loyd', 'Peggy', 'Alverta'	['question_type_global', 'question_single_statement']
What are the non resolved issues?	'saving data throws exception', 'minified version fails'	['question_type_global', 'question_single_statement']
[this person] is not working on [it] anymore
[this person] is working on [it] also
[this developer] is not working on [mobile project] anymore
[this person] is working on [mobile project] also
Who is working on [knowledge base project]?	'Igor', 'Gia', 'Peggy', 'Alverta', 'Gabrielle'	['question_type_local']
Which developers have issues assigned to them that were all resolved?	'Peggy'	['question_type_global', 'question_three_hop_statement']
Who is currently working on the [open source] projects?	'Francoise', 'Igor', 'Gia', 'Loyd', 'Peggy', 'Alverta', 'Gabrielle'	['question_type_global', 'question_two_hop_statement']
What are the resolved issues for [open source] projects?	'versioning needs to be made consistent', 'timeout problem', 'parsing with parantheses fails', 'changelong needs to be added'	['question_type_global', 'question_two_hop_statement']
who are the developers?	'Loyd', 'Peggy', 'Alverta'	['question_type_global', 'question_single_statement']
What are the [enhancement]s that are not resolved?	'changelong needs to be added'	['question_type_global', 'question_two_hop_statement']
What are the issues that are resolved for projects in the [implementation] stage?	'versioning needs to be made consistent', 'timeout problem', 'parsing with parantheses fails'	['question_type_global', 'question_three_hop_statement']
Which is the stage of [knowledge base project]?	'design'	['question_type_local']
Which developers have issues assigned to them that were all resolved?	'Peggy'	['question_type_global', 'question_three_hop_statement']
[chatbot project] is in the stage of [maintenance]
Are there any developers assigned to projects in the [implementation] stage?	'Loyd', 'Peggy', 'Alverta'	['question_type_global', 'question_three_hop_statement']
Who has issues assigned to them that were all resolved?	'Gia', 'Peggy'	['question_type_global', 'question_two_hop_statement']
Who is assigned to projects in the [maintenance] stage?	'Igor', 'Gia', 'Peggy', 'Alverta', 'Gabrielle'	['question_type_global', 'question_two_hop_statement']
Are there any developers assigned to projects in the [maintenance] stage?	'Peggy', 'Alverta'	['question_type_global', 'question_three_hop_statement']
Which is the stage of [mobile project]?	'implementation'	['question_type_local']
who are the developers?	'Loyd', 'Peggy', 'Alverta'	['question_type_global', 'question_single_statement']
What projects is [Alverta] working on?	'mobile', 'knowledge base', 'chatbot'	['question_type_local']
Are there any issues that are resolved?	'versioning needs to be made consistent', 'timeout problem', 'parsing with parantheses fails', 'dcoref always returns null', 'changelong needs to be added'	['question_type_global', 'question_single_statement']
What are the non resolved issues?	'saving data throws exception', 'minified version fails'	['question_type_global', 'question_single_statement']
Are there any [external] projects?	'knowledge base'	['question_type_global', 'question_single_statement']
Are there any people assigned to the [external] projects?	'Igor', 'Gia', 'Peggy', 'Alverta', 'Gabrielle'	['question_type_global', 'question_two_hop_statement']
What are the issues submitted by [Gabrielle] that were resolved?	'parsing with parantheses fails'	['question_type_local']
What projects are currently in the [implementation] stage?	'mobile'	['question_type_global', 'question_single_statement']
Are there any [open source] projects?	'mobile', 'chatbot'	['question_type_global', 'question_single_statement']
What are the issues that were resolved?	'versioning needs to be made consistent', 'timeout problem', 'parsing with parantheses fails', 'dcoref always returns null', 'changelong needs to be added'	['question_type_global', 'question_single_statement']
Who are the testers currently working on projects in the [implementation] stage?	'Francoise', 'Igor', 'Gia', 'Gabrielle'	['question_type_global', 'question_three_hop_statement']
What are the resolved issues for [open source] projects?	'versioning needs to be made consistent', 'timeout problem', 'parsing with parantheses fails', 'changelong needs to be added'	['question_type_global', 'question_two_hop_statement']
[mobile project] is in the [design] stage
who are the testers?	'Francoise', 'Igor', 'Gia', 'Gabrielle'	['question_type_global', 'question_single_statement']
Who is currently working on projects in the [maintenance] stage?	'Igor', 'Gia', 'Peggy', 'Alverta', 'Gabrielle'	['question_type_global', 'question_two_hop_statement']
What are the resolved issues for [knowledge base project]?	'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
Who are the developers currently working on projects in the [maintenance] stage?	'Peggy', 'Alverta'	['question_type_global', 'question_three_hop_statement']
Which developers are assigned to [chatbot project]	'Peggy', 'Alverta'	['question_type_local']
What are the issues that are resolved for [external] projects?	'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
Which developers are working on [mobile project]?	'Loyd', 'Peggy', 'Alverta'	['question_type_local']
Are there any issues for [chatbot project] that are not resolved?	'saving data throws exception', 'minified version fails'	['question_type_global', 'question_two_hop_statement']
[mobile project] is now in the [implementation] stage
What projects are [open source]?	'mobile', 'chatbot'	['question_type_global', 'question_single_statement']
Are there any testers assigned to projects in the [design] stage?	'Igor', 'Gia', 'Gabrielle'	['question_type_global', 'question_three_hop_statement']
What are the issues for [that project] that are resolved?	'versioning needs to be made consistent', 'timeout problem', 'parsing with parantheses fails'	['question_type_global', 'question_two_hop_statement']
who are the developers?	'Loyd', 'Peggy', 'Alverta'	['question_type_global', 'question_single_statement']
Were there any issues created by [Igor]?	'timeout problem'	['question_type_local']
What are the [external] projects?	'knowledge base'	['question_type_global', 'question_single_statement']
What are the resolved issues?	'versioning needs to be made consistent', 'timeout problem', 'parsing with parantheses fails', 'dcoref always returns null', 'changelong needs to be added'	['question_type_global', 'question_single_statement']
Which testers have issues assigned to them that were all resolved?	'Gia'	['question_type_global', 'question_three_hop_statement']
Are there projects in the [design] stage?	'knowledge base'	['question_type_global', 'question_single_statement']
What are the issues assigned to [Gia]?	'versioning needs to be made consistent', 'timeout problem', 'parsing with parantheses fails', 'changelong needs to be added'	['question_type_local']
What are the non resolved [enhancement]s?	'changelong needs to be added'	['question_type_global', 'question_two_hop_statement']
What are the [bug]s that are not resolved?	'parsing with parantheses fails'	['question_type_global', 'question_two_hop_statement']
who are the developers?	'Loyd', 'Peggy', 'Alverta'	['question_type_global', 'question_single_statement']
Are there any projects that are [open source]?	'mobile', 'chatbot'	['question_type_global', 'question_single_statement']
Who created [the dcoref always returns null issue]?	'Peggy'	['question_type_local']
Who are the developers currently working on the [external] projects?	'Peggy', 'Alverta'	['question_type_global', 'question_three_hop_statement']
What testers are assigned to the [open source] projects?	'Francoise', 'Igor', 'Gia', 'Gabrielle'	['question_type_global', 'question_three_hop_statement']
What are the resolved issues?	'versioning needs to be made consistent', 'timeout problem', 'parsing with parantheses fails', 'dcoref always returns null', 'changelong needs to be added'	['question_type_global', 'question_single_statement']
[knowledge base project] is not assigned to [Gia]
[Gia] is working on [that project] also
Which developers are assigned to [chatbot project]	'Peggy', 'Alverta'	['question_type_local']
Who are the testers currently working on the [external] projects?	'Igor', 'Gia', 'Gabrielle'	['question_type_global', 'question_three_hop_statement']
Who created [the bug]?	'Gabrielle'	['question_type_local']
Are there any issues that are not resolved?	'saving data throws exception', 'minified version fails'	['question_type_global', 'question_single_statement']
Who has issues assigned to them that were all resolved?	'Gia', 'Peggy'	['question_type_global', 'question_two_hop_statement']
[the minified version fails issue] was assigned to [Gia]
[she] resolved [it]
Are there any testers assigned to projects in the [implementation] stage?	'Francoise', 'Igor', 'Gia', 'Gabrielle'	['question_type_global', 'question_three_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Peggy'	['question_type_global', 'question_three_hop_statement']
Who are the testers currently working on projects in the [design] stage?	'Igor', 'Gia', 'Gabrielle'	['question_type_global', 'question_three_hop_statement']
Are there any issues that are resolved for projects in the [implementation] stage?	'versioning needs to be made consistent', 'timeout problem', 'parsing with parantheses fails'	['question_type_global', 'question_three_hop_statement']
who are the testers?	'Francoise', 'Igor', 'Gia', 'Gabrielle'	['question_type_global', 'question_single_statement']
[mobile project] is not assigned to [this tester]
[that project] is assigned to [this tester] also
What projects is [Alverta] working on?	'mobile', 'knowledge base', 'chatbot'	['question_type_local']
who are the developers?	'Loyd', 'Peggy', 'Alverta'	['question_type_global', 'question_single_statement']
Are there any developers assigned to projects in the [maintenance] stage?	'Peggy', 'Alverta'	['question_type_global', 'question_three_hop_statement']
What are the issues that are not resolved?	'saving data throws exception'	['question_type_global', 'question_single_statement']
What are the resolved issues for [knowledge base project]?	'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
[this person] is not working on [mobile project] anymore
Who are the developers on [chatbot project]	'Peggy', 'Alverta'	['question_type_local']
Are there any issues that are not resolved for [open source] projects?	'saving data throws exception'	['question_type_global', 'question_two_hop_statement']
Are there any testers assigned to projects in the [design] stage?	'Igor', 'Gia', 'Gabrielle'	['question_type_global', 'question_three_hop_statement']
Who is [the minified version fails issue] assigned to?	'Gia'	['question_type_local']
Are there any issues that are resolved for projects in the [maintenance] stage?	'minified version fails', 'changelong needs to be added'	['question_type_global', 'question_three_hop_statement']
Are there any issues for [chatbot project] that are not resolved?	'saving data throws exception'	['question_type_global', 'question_two_hop_statement']
[this tester] is working on [that project] also
[this project] is in the stage of [design]
[it] is in the stage of [maintenance]
Are there any issues that are not resolved?	'saving data throws exception'	['question_type_global', 'question_single_statement']
Who are the developers on [it]	'Loyd', 'Peggy', 'Alverta'	['question_type_local']
What are the issues that are resolved for projects in the [maintenance] stage?	'versioning needs to be made consistent', 'timeout problem', 'minified version fails', 'parsing with parantheses fails', 'changelong needs to be added'	['question_type_global', 'question_three_hop_statement']
Are there any issues assigned to [Gia] that are resolved?	'versioning needs to be made consistent', 'timeout problem', 'minified version fails', 'parsing with parantheses fails', 'changelong needs to be added'	['question_type_local']
Who is working on [it]?	'Francoise', 'Igor', 'Gia', 'Loyd', 'Peggy', 'Alverta', 'Gabrielle'	['question_type_local']
Are there any issues for [knowledge base project] that are resolved?	'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
Who is [the parsing with parantheses fails bug] assigned to?	'Gia'	['question_type_local']
What are the [external] projects?	'knowledge base'	['question_type_global', 'question_single_statement']
Which developers have issues assigned to them that were all resolved?	'Peggy'	['question_type_global', 'question_three_hop_statement']
Which testers have issues assigned to them that were all resolved?	'Gia'	['question_type_global', 'question_three_hop_statement']
who are the testers?	'Francoise', 'Igor', 'Gia', 'Gabrielle'	['question_type_global', 'question_single_statement']
Are there projects in the [design] stage?	'knowledge base'	['question_type_global', 'question_single_statement']
[this project] has moved to the [design] stage
[this project] has moved to the [maintenance] stage
[knowledge base project] is not assigned to [Gia]
[that person] is assigned to [that project] also
What projects is [this test engineer] working on?	'mobile', 'knowledge base', 'chatbot'	['question_type_local']
What projects are in the [maintenance] stage?	'mobile', 'chatbot'	['question_type_global', 'question_single_statement']
Are there any issues that are not resolved?	'saving data throws exception'	['question_type_global', 'question_single_statement']
Who is assigned to the [open source] projects?	'Francoise', 'Igor', 'Gia', 'Loyd', 'Peggy', 'Alverta', 'Gabrielle'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are not resolved for projects in the [maintenance] stage?	'saving data throws exception'	['question_type_global', 'question_three_hop_statement']
Which testers are working on [knowledge base project]?	'Igor', 'Gia', 'Gabrielle'	['question_type_local']
What projects are in the [design] stage?	'knowledge base'	['question_type_global', 'question_single_statement']
Are there any people assigned to projects in the [design] stage?	'Igor', 'Gia', 'Peggy', 'Alverta', 'Gabrielle'	['question_type_global', 'question_two_hop_statement']
Are there any testers assigned to projects in the [maintenance] stage?	'Francoise', 'Igor', 'Gia', 'Gabrielle'	['question_type_global', 'question_three_hop_statement']
[it] is in the [implementation] stage
Are there any issues that are not resolved?	'saving data throws exception'	['question_type_global', 'question_single_statement']
who are the developers?	'Loyd', 'Peggy', 'Alverta'	['question_type_global', 'question_single_statement']
Are there any issues that are resolved?	'versioning needs to be made consistent', 'timeout problem', 'minified version fails', 'parsing with parantheses fails', 'dcoref always returns null', 'changelong needs to be added'	['question_type_global', 'question_single_statement']
What testers are assigned to the [open source] projects?	'Francoise', 'Igor', 'Gia', 'Gabrielle'	['question_type_global', 'question_three_hop_statement']
What are the resolved issues for projects in the [maintenance] stage?	'versioning needs to be made consistent', 'timeout problem', 'minified version fails', 'parsing with parantheses fails', 'changelong needs to be added'	['question_type_global', 'question_three_hop_statement']
Which is the stage of [it]?	'implementation'	['question_type_local']
What are the issues that are resolved for projects in the [maintenance] stage?	'versioning needs to be made consistent', 'timeout problem', 'minified version fails', 'parsing with parantheses fails', 'changelong needs to be added'	['question_type_global', 'question_three_hop_statement']
Who are the testers currently working on the [external] projects?	'Igor', 'Gia', 'Gabrielle'	['question_type_global', 'question_three_hop_statement']
Who is currently working on projects in the [implementation] stage?	'Igor', 'Gia', 'Peggy', 'Alverta', 'Gabrielle'	['question_type_global', 'question_two_hop_statement']
Who is working on [mobile project]?	'Francoise', 'Igor', 'Gia', 'Loyd', 'Peggy', 'Alverta', 'Gabrielle'	['question_type_local']
who are the developers?	'Loyd', 'Peggy', 'Alverta'	['question_type_global', 'question_single_statement']
What are the resolved issues for [knowledge base project]?	'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
Who is currently working on projects in the [maintenance] stage?	'Francoise', 'Igor', 'Gia', 'Loyd', 'Peggy', 'Alverta', 'Gabrielle'	['question_type_global', 'question_two_hop_statement']
[that project] is now in the [maintenance] stage
[that project] is in the [implementation] stage
What are the issues submitted by [Gabrielle] that were resolved?	'parsing with parantheses fails'	['question_type_local']
Are there any developers assigned to the [external] projects?	'Peggy', 'Alverta'	['question_type_global', 'question_three_hop_statement']
What testers are assigned to projects in the [implementation] stage?	'Igor', 'Gia', 'Gabrielle'	['question_type_global', 'question_three_hop_statement']
What are the issues that are resolved for projects in the [implementation] stage?	'dcoref always returns null'	['question_type_global', 'question_three_hop_statement']
What are the issues that are not resolved?	'saving data throws exception'	['question_type_global', 'question_single_statement']
Which developers have issues assigned to them that were all resolved?	'Peggy'	['question_type_global', 'question_three_hop_statement']
Who has issues assigned to them that were all resolved?	'Gia', 'Peggy'	['question_type_global', 'question_two_hop_statement']
What are the issues for [mobile project] that are resolved?	'versioning needs to be made consistent', 'timeout problem', 'parsing with parantheses fails'	['question_type_global', 'question_two_hop_statement']
What are the resolved issues for [mobile project]?	'versioning needs to be made consistent', 'timeout problem', 'parsing with parantheses fails'	['question_type_global', 'question_two_hop_statement']
[mobile project] is not assigned to [Gia]
[knowledge base project] is in the stage of [design]
[Gia] is assigned to [mobile project] also
Who submitted [the enhancement]?	'Alverta'	['question_type_local']
Who are the developers currently working on the [external] projects?	'Peggy', 'Alverta'	['question_type_global', 'question_three_hop_statement']
Are there any issues that are resolved for projects in the [maintenance] stage?	'versioning needs to be made consistent', 'timeout problem', 'minified version fails', 'parsing with parantheses fails', 'changelong needs to be added'	['question_type_global', 'question_three_hop_statement']
What stage is [chatbot project] in?	'maintenance'	['question_type_local']
What are the non resolved [bug]s?	'parsing with parantheses fails'	['question_type_global', 'question_two_hop_statement']
Are there any [open source] projects?	'mobile', 'chatbot'	['question_type_global', 'question_single_statement']
Which testers have issues assigned to them that were all resolved?	'Gia'	['question_type_global', 'question_three_hop_statement']
Who are the developers on [chatbot project]	'Peggy', 'Alverta'	['question_type_local']
Are there any people assigned to the [external] projects?	'Igor', 'Gia', 'Peggy', 'Alverta', 'Gabrielle'	['question_type_global', 'question_two_hop_statement']
[Gia] is not working on [this project] anymore
[that test engineer] is assigned to [that project] also
Who is currently working on the [open source] projects?	'Francoise', 'Igor', 'Gia', 'Loyd', 'Peggy', 'Alverta', 'Gabrielle'	['question_type_global', 'question_two_hop_statement']
[Peggy] is not working on [it] anymore
[that project] is assigned to [this developer] also
Which is the stage of [mobile project]?	'maintenance'	['question_type_local']
Which developers have issues assigned to them that were all resolved?	'Peggy'	['question_type_global', 'question_three_hop_statement']
What are the issues that are not resolved?	'saving data throws exception'	['question_type_global', 'question_single_statement']
which testers are assigned to [knowledge base project]	'Igor', 'Gia', 'Gabrielle'	['question_type_local']
Which testers have issues assigned to them that were all resolved?	'Gia'	['question_type_global', 'question_three_hop_statement']
Who is currently working on projects in the [maintenance] stage?	'Francoise', 'Igor', 'Gia', 'Loyd', 'Peggy', 'Alverta', 'Gabrielle'	['question_type_global', 'question_two_hop_statement']
What are the resolved issues for [chatbot project]?	'minified version fails', 'changelong needs to be added'	['question_type_global', 'question_two_hop_statement']
What are the resolved issues for projects in the [maintenance] stage?	'versioning needs to be made consistent', 'timeout problem', 'minified version fails', 'parsing with parantheses fails', 'changelong needs to be added'	['question_type_global', 'question_three_hop_statement']
Who was [the dcoref always returns null issue] assigned to?	'Peggy'	['question_type_local']
Are there any testers assigned to the [open source] projects?	'Francoise', 'Igor', 'Gia', 'Gabrielle'	['question_type_global', 'question_three_hop_statement']
Are there any issues that are resolved for projects in the [design] stage?	'dcoref always returns null'	['question_type_global', 'question_three_hop_statement']
What are the issues for [it] that are resolved?	'versioning needs to be made consistent', 'timeout problem', 'parsing with parantheses fails'	['question_type_global', 'question_two_hop_statement']
[Peggy] is no longer assigned to [mobile project]
[mobile project] is assigned to [Peggy] also
[it] is in the [implementation] stage
[it] is in the [design] stage
What are the [external] projects?	'knowledge base'	['question_type_global', 'question_single_statement']
Who has issues assigned to them that were all resolved?	'Gia', 'Peggy'	['question_type_global', 'question_two_hop_statement']
Who is [the timeout problem issue] assigned to?	'Gia'	['question_type_local']
What are the issues that are resolved for [external] projects?	'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
[mobile project] is in the stage of [implementation]
What are the non resolved issues?	'saving data throws exception'	['question_type_global', 'question_single_statement']
