there is a new [chatbot] [project]
[that project] is in the [evaluation] stage
[it] is a [pilot] project
What are the [pilot] projects?	'chatbot'	['question_type_global', 'question_single_statement']
[Roslyn] is a [developer] on [chatbot project]
Who are the developers on [that project]	'Roslyn'	['question_type_local']
Are there any developers assigned to the [pilot] projects?	'Roslyn'	['question_type_global', 'question_three_hop_statement']
Are there any people assigned to projects in the [evaluation] stage?	'Roslyn'	['question_type_global', 'question_two_hop_statement']
[parse example terribly slow] is a new [bug] for the [this project]
there is a new [knowledge base] [project]
[that project] is a [pilot] project
[that project] is in the stage of [implementation]
[Albertha] is a [developer] on [that project]
Are there any people assigned to the [pilot] projects?	'Roslyn', 'Albertha'	['question_type_global', 'question_two_hop_statement']
[that developer] is working on [chatbot project] also
there is a new [pilot] [mobile] [project]
[mobile project] is in the stage of [implementation]
[Albertha] is working on [mobile project] also
[knowledge base project] has moved to the [evaluation] stage
[Francoise] is a [tester]
[mobile project] is in the stage of [deployment]
[he] is working on [knowledge base project]
What projects is [that person] working on?	'knowledge base'	['question_type_local']
Who are the developers currently working on projects in the [evaluation] stage?	'Roslyn', 'Albertha'	['question_type_global', 'question_three_hop_statement']
[he] is working on [mobile project] also
Which developers are working on [knowledge base project]?	'Albertha'	['question_type_local']
[that test engineer] created a new issue for [knowledge base project]: [fails with apache stack]
What developers are assigned to projects in the [evaluation] stage?	'Roslyn', 'Albertha'	['question_type_global', 'question_three_hop_statement']
Are there any testers assigned to projects in the [deployment] stage?	'Francoise'	['question_type_global', 'question_three_hop_statement']
[the issue] is assigned to [Albertha]
Who is working on [mobile project]?	'Albertha', 'Francoise'	['question_type_local']
who are the developers?	'Roslyn', 'Albertha'	['question_type_global', 'question_single_statement']
What are the issues that are not resolved for projects in the [evaluation] stage?	'parse example terribly slow', 'fails with apache stack'	['question_type_global', 'question_three_hop_statement']
[Albertha] resolved [it]
What are the issues that are resolved for [pilot] projects?	'fails with apache stack'	['question_type_global', 'question_two_hop_statement']
What are the resolved issues for projects in the [evaluation] stage?	'fails with apache stack'	['question_type_global', 'question_three_hop_statement']
Who has issues assigned to them that were all resolved?	'Albertha'	['question_type_global', 'question_two_hop_statement']
who are the testers?	'Francoise'	['question_type_global', 'question_single_statement']
Who is working on [chatbot project]?	'Roslyn', 'Albertha'	['question_type_local']
What are the issues that are not resolved for [pilot] projects?	'parse example terribly slow'	['question_type_global', 'question_two_hop_statement']
[Lucy] is a [developer] on [chatbot project]
[Lucy] is not working on [chatbot project] anymore
[she] is working on [knowledge base project]
[this project] is not assigned to [she]
Who was [the fails with apache stack issue] assigned to?	'Albertha'	['question_type_local']
Which developers have issues assigned to them that were all resolved?	'Albertha'	['question_type_global', 'question_three_hop_statement']
What are the resolved issues for projects in the [evaluation] stage?	'fails with apache stack'	['question_type_global', 'question_three_hop_statement']
What are the non resolved issues for [pilot] projects?	'parse example terribly slow'	['question_type_global', 'question_two_hop_statement']
Are there any testers assigned to projects in the [evaluation] stage?	'Francoise'	['question_type_global', 'question_three_hop_statement']
[chatbot project] is assigned to [Francoise] also
[mobile project] is now in the [evaluation] stage
Which is the stage of [chatbot project]?	'evaluation'	['question_type_local']
Are there any testers assigned to the [pilot] projects?	'Francoise'	['question_type_global', 'question_three_hop_statement']
Who has issues assigned to them that were all resolved?	'Albertha'	['question_type_global', 'question_two_hop_statement']
What are the issues that were resolved?	'fails with apache stack'	['question_type_global', 'question_single_statement']
[mobile project] has moved to the [deployment] stage
[Jack] is a [developer] on [mobile project]
[chatbot project] is assigned to [that person] also
[Tawnya] is a [developer] on [that project]
[this developer] is working on [mobile project] also
[Tom] is a [developer]
What stage is [chatbot project] in?	'evaluation'	['question_type_local']
Who is currently working on projects in the [deployment] stage?	'Albertha', 'Francoise', 'Jack', 'Tawnya'	['question_type_global', 'question_two_hop_statement']
Who are the testers currently working on projects in the [evaluation] stage?	'Francoise'	['question_type_global', 'question_three_hop_statement']
[xml extractor exception] is a new [task] submitted by [Roslyn] for [chatbot project]
[mobile project] is assigned to [Tom]
[he] is assigned to [knowledge base project] also
[that developer] is assigned to [chatbot project] also
Which developers are assigned to [it]	'Roslyn', 'Albertha', 'Jack', 'Tawnya', 'Tom'	['question_type_local']
What developers are assigned to the [pilot] projects?	'Roslyn', 'Albertha', 'Jack', 'Tawnya', 'Tom'	['question_type_global', 'question_three_hop_statement']
Who has issues assigned to them that were all resolved?	'Albertha'	['question_type_global', 'question_two_hop_statement']
What are the non resolved [bug]s?	'parse example terribly slow'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are resolved?	'fails with apache stack'	['question_type_global', 'question_single_statement']
Are there any developers assigned to projects in the [deployment] stage?	'Albertha', 'Jack', 'Tawnya', 'Tom'	['question_type_global', 'question_three_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Albertha'	['question_type_global', 'question_three_hop_statement']
Who are the developers currently working on the [pilot] projects?	'Roslyn', 'Albertha', 'Jack', 'Tawnya', 'Tom'	['question_type_global', 'question_three_hop_statement']
Which developers are working on [mobile project]?	'Albertha', 'Jack', 'Tawnya', 'Tom'	['question_type_local']
What are the issues that are resolved for [pilot] projects?	'fails with apache stack'	['question_type_global', 'question_two_hop_statement']
What are the issues that are not resolved for [pilot] projects?	'parse example terribly slow', 'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
What are the non resolved [bug]s?	'parse example terribly slow'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are not resolved for [pilot] projects?	'parse example terribly slow', 'xml extractor exception'	['question_type_global', 'question_two_hop_statement']
[null pointer exception during parsing] is a new issue for the [mobile project]
[that issue] was assigned to [Albertha]
What projects is [Tawnya] working on?	'chatbot', 'mobile'	['question_type_local']
Which developers have issues assigned to them that were not resolved?	'Albertha'	['question_type_global', 'question_three_hop_statement']
What are the issues that were resolved?	'fails with apache stack'	['question_type_global', 'question_single_statement']
Who has issues assigned to them that were not resolved?	'Albertha'	['question_type_global', 'question_two_hop_statement']
Who is currently working on projects in the [evaluation] stage?	'Roslyn', 'Albertha', 'Francoise', 'Jack', 'Tawnya', 'Tom'	['question_type_global', 'question_two_hop_statement']
[that person] resolved [that issue]
[Tawnya] is working on [knowledge base project] also
Who has issues assigned to them that were all resolved?	'Albertha'	['question_type_global', 'question_two_hop_statement']
What are the resolved issues for [pilot] projects?	'fails with apache stack', 'null pointer exception during parsing'	['question_type_global', 'question_two_hop_statement']
What are the issues that are not resolved?	'parse example terribly slow', 'xml extractor exception'	['question_type_global', 'question_single_statement']
[the parse example terribly slow bug] was assigned to [Roslyn]
[Albertha] is no longer assigned to [chatbot project]
[this project] is assigned to [that developer] also
[dcoref always returns null] is a new [task] for [that project] that [Roslyn] just created
[mobile project] is assigned to [Lucy]
[Tawnya] created a new [task] for [knowledge base project]: [parsing with parantheses fails]
[that project] is now in the [implementation] stage
[that issue] is assigned to [Tom]
[this developer] resolved [that issue]
What are the issues that are resolved for projects in the [implementation] stage?	'null pointer exception during parsing'	['question_type_global', 'question_three_hop_statement']
What developers are assigned to the [pilot] projects?	'Roslyn', 'Albertha', 'Lucy', 'Jack', 'Tawnya', 'Tom'	['question_type_global', 'question_three_hop_statement']
[knowledge base project] is not assigned to [this person]
[Tom] is assigned to [knowledge base project] also
Who was [the null pointer exception during parsing issue] assigned to?	'Albertha'	['question_type_local']
Are there any issues that are resolved for [pilot] projects?	'fails with apache stack', 'null pointer exception during parsing', 'parsing with parantheses fails'	['question_type_global', 'question_two_hop_statement']
Who are the testers currently working on the [pilot] projects?	'Francoise'	['question_type_global', 'question_three_hop_statement']
What are the resolved issues for projects in the [evaluation] stage?	'fails with apache stack', 'parsing with parantheses fails'	['question_type_global', 'question_three_hop_statement']
Who are the developers currently working on projects in the [evaluation] stage?	'Roslyn', 'Albertha', 'Jack', 'Tawnya', 'Tom'	['question_type_global', 'question_three_hop_statement']
Which developers have issues assigned to them that were not resolved?	'Roslyn'	['question_type_global', 'question_three_hop_statement']
Who was [the fails with apache stack issue] assigned to?	'Albertha'	['question_type_local']
Are there any developers assigned to projects in the [evaluation] stage?	'Roslyn', 'Albertha', 'Jack', 'Tawnya', 'Tom'	['question_type_global', 'question_three_hop_statement']
Who is assigned to the [pilot] projects?	'Roslyn', 'Albertha', 'Francoise', 'Lucy', 'Jack', 'Tawnya', 'Tom'	['question_type_global', 'question_two_hop_statement']
[knowledge base project] is in the [deployment] stage
[Lucy] is working on [knowledge base project] also
[this person] is working on [chatbot project] also
[knowledge base project] is not assigned to [Lucy]
[Albertha] created a new issue for [mobile project]: [wrong pos tag on consecutive words]
Who has issues assigned to them that were not resolved?	'Roslyn'	['question_type_global', 'question_two_hop_statement']
What are the non resolved issues?	'parse example terribly slow', 'xml extractor exception', 'dcoref always returns null', 'wrong pos tag on consecutive words'	['question_type_global', 'question_single_statement']
Which developers have issues assigned to them that were not resolved?	'Roslyn'	['question_type_global', 'question_three_hop_statement']
What are the non resolved [bug]s?	'parse example terribly slow'	['question_type_global', 'question_two_hop_statement']
who are the developers?	'Roslyn', 'Albertha', 'Lucy', 'Jack', 'Tawnya', 'Tom'	['question_type_global', 'question_single_statement']
Which developers have issues assigned to them that were all resolved?	'Albertha', 'Tom'	['question_type_global', 'question_three_hop_statement']
[the issue] was assigned to [Lucy]
[this developer] resolved [it]
[knowledge base project] is assigned to [that person] also
Are there any issues that are resolved?	'fails with apache stack', 'null pointer exception during parsing', 'parsing with parantheses fails', 'wrong pos tag on consecutive words'	['question_type_global', 'question_single_statement']
What projects are [pilot]?	'chatbot', 'knowledge base', 'mobile'	['question_type_global', 'question_single_statement']
Are there projects in the [implementation] stage?	'mobile'	['question_type_global', 'question_single_statement']
[mobile project] is not assigned to [Lucy]
[this developer] is assigned to [it] also
Who was [the parsing with parantheses fails issue] assigned to?	'Tom'	['question_type_local']
What are the non resolved issues?	'parse example terribly slow', 'xml extractor exception', 'dcoref always returns null'	['question_type_global', 'question_single_statement']
Are there any issues for [mobile project] that are resolved?	'null pointer exception during parsing', 'wrong pos tag on consecutive words'	['question_type_global', 'question_two_hop_statement']
[chatbot project] is not assigned to [this developer]
Who submitted [the dcoref always returns null task]?	'Roslyn'	['question_type_local']
What are the issues that are resolved for [pilot] projects?	'fails with apache stack', 'null pointer exception during parsing', 'parsing with parantheses fails', 'wrong pos tag on consecutive words'	['question_type_global', 'question_two_hop_statement']
Who has issues assigned to them that were not resolved?	'Roslyn'	['question_type_global', 'question_two_hop_statement']
Are there any developers assigned to the [pilot] projects?	'Roslyn', 'Albertha', 'Lucy', 'Jack', 'Tawnya', 'Tom'	['question_type_global', 'question_three_hop_statement']
Who is assigned to projects in the [evaluation] stage?	'Roslyn', 'Albertha', 'Francoise', 'Jack', 'Tawnya', 'Tom'	['question_type_global', 'question_two_hop_statement']
who are the developers?	'Roslyn', 'Albertha', 'Lucy', 'Jack', 'Tawnya', 'Tom'	['question_type_global', 'question_single_statement']
Who was [the wrong pos tag on consecutive words issue] assigned to?	'Lucy'	['question_type_local']
What are the issues for [that project] that are not resolved?	'parse example terribly slow', 'xml extractor exception', 'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
[this person] is assigned to [this project] also
Who is [the wrong pos tag on consecutive words issue] assigned to?	'Lucy'	['question_type_local']
Are there any issues that are resolved?	'fails with apache stack', 'null pointer exception during parsing', 'parsing with parantheses fails', 'wrong pos tag on consecutive words'	['question_type_global', 'question_single_statement']
Who are the testers currently working on the [pilot] projects?	'Francoise'	['question_type_global', 'question_three_hop_statement']
Are there any testers assigned to projects in the [deployment] stage?	'Francoise'	['question_type_global', 'question_three_hop_statement']
Are there any issues for [it] that are not resolved?	'parse example terribly slow', 'xml extractor exception', 'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are resolved for [pilot] projects?	'fails with apache stack', 'null pointer exception during parsing', 'parsing with parantheses fails', 'wrong pos tag on consecutive words'	['question_type_global', 'question_two_hop_statement']
What developers are assigned to the [pilot] projects?	'Roslyn', 'Albertha', 'Lucy', 'Jack', 'Tawnya', 'Tom'	['question_type_global', 'question_three_hop_statement']
Which is the stage of [mobile project]?	'implementation'	['question_type_local']
Which developers have issues assigned to them that were all resolved?	'Albertha', 'Lucy', 'Tom'	['question_type_global', 'question_three_hop_statement']
Are there any projects that are [pilot]?	'chatbot', 'knowledge base', 'mobile'	['question_type_global', 'question_single_statement']
[mobile project] has moved to the [deployment] stage
[chatbot project] is in the stage of [implementation]
Who has issues assigned to them that were all resolved?	'Albertha', 'Lucy', 'Tom'	['question_type_global', 'question_two_hop_statement']
What projects are in the [implementation] stage?	'chatbot'	['question_type_global', 'question_single_statement']
Who is working on [chatbot project]?	'Roslyn', 'Albertha', 'Francoise', 'Lucy', 'Jack', 'Tawnya', 'Tom'	['question_type_local']
Who are the developers currently working on projects in the [deployment] stage?	'Albertha', 'Lucy', 'Jack', 'Tawnya', 'Tom'	['question_type_global', 'question_three_hop_statement']
who are the testers?	'Francoise'	['question_type_global', 'question_single_statement']
Who are the developers currently working on projects in the [implementation] stage?	'Roslyn', 'Albertha', 'Lucy', 'Jack', 'Tawnya', 'Tom'	['question_type_global', 'question_three_hop_statement']
Are there projects in the [implementation] stage?	'chatbot'	['question_type_global', 'question_single_statement']
What are the non resolved [task]s?	'xml extractor exception', 'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
Who is currently working on the [pilot] projects?	'Roslyn', 'Albertha', 'Francoise', 'Lucy', 'Jack', 'Tawnya', 'Tom'	['question_type_global', 'question_two_hop_statement']
What are the issues that are not resolved?	'parse example terribly slow', 'xml extractor exception', 'dcoref always returns null'	['question_type_global', 'question_single_statement']
What are the non resolved issues for projects in the [implementation] stage?	'parse example terribly slow', 'xml extractor exception', 'dcoref always returns null'	['question_type_global', 'question_three_hop_statement']
What projects is [Lucy] working on?	'chatbot', 'knowledge base', 'mobile'	['question_type_local']
Which developers have issues assigned to them that were not resolved?	'Roslyn'	['question_type_global', 'question_three_hop_statement']
What are the issues that were resolved?	'fails with apache stack', 'null pointer exception during parsing', 'parsing with parantheses fails', 'wrong pos tag on consecutive words'	['question_type_global', 'question_single_statement']
What are the [pilot] projects?	'chatbot', 'knowledge base', 'mobile'	['question_type_global', 'question_single_statement']
What projects are currently in the [deployment] stage?	'knowledge base', 'mobile'	['question_type_global', 'question_single_statement']
[chatbot project] is not assigned to [Tawnya]
[this person] is assigned to [chatbot project] also
Who are the testers on [knowledge base project]	'Francoise'	['question_type_local']
Are there any issues for [knowledge base project] that are resolved?	'fails with apache stack', 'parsing with parantheses fails'	['question_type_global', 'question_two_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Albertha', 'Lucy', 'Tom'	['question_type_global', 'question_three_hop_statement']
Are there any [task]s that are not resolved?	'parsing with parantheses fails'	['question_type_global', 'question_two_hop_statement']
[Tom] is no longer assigned to [that project]
[Jack] is working on [knowledge base project] also
Who is [the wrong pos tag on consecutive words issue] assigned to?	'Lucy'	['question_type_local']
who are the developers?	'Roslyn', 'Albertha', 'Lucy', 'Jack', 'Tawnya', 'Tom'	['question_type_global', 'question_single_statement']
[this developer] created a new issue for [chatbot project]: [saving data throws exception]
[this issue] is assigned to [Jack]
Who was [the bug] assigned to?	'Roslyn'	['question_type_local']
Are there any testers assigned to the [pilot] projects?	'Francoise'	['question_type_global', 'question_three_hop_statement']
Who has issues assigned to them that were all resolved?	'Albertha', 'Lucy', 'Tom'	['question_type_global', 'question_two_hop_statement']
Who is assigned to the [pilot] projects?	'Roslyn', 'Albertha', 'Francoise', 'Lucy', 'Jack', 'Tawnya', 'Tom'	['question_type_global', 'question_two_hop_statement']
Who has issues assigned to them that were not resolved?	'Roslyn', 'Jack'	['question_type_global', 'question_two_hop_statement']
[that person] resolved [that issue]
[Tom] is working on [chatbot project] also
Who created [the xml extractor exception issue]?	'Roslyn'	['question_type_local']
Who are the testers currently working on projects in the [implementation] stage?	'Francoise'	['question_type_global', 'question_three_hop_statement']
What developers are assigned to the [pilot] projects?	'Roslyn', 'Albertha', 'Lucy', 'Jack', 'Tawnya', 'Tom'	['question_type_global', 'question_three_hop_statement']
Are there any issues that are resolved for [pilot] projects?	'fails with apache stack', 'null pointer exception during parsing', 'parsing with parantheses fails', 'wrong pos tag on consecutive words', 'saving data throws exception'	['question_type_global', 'question_two_hop_statement']
who are the developers?	'Roslyn', 'Albertha', 'Lucy', 'Jack', 'Tawnya', 'Tom'	['question_type_global', 'question_single_statement']
Who are the developers on [that project]	'Roslyn', 'Albertha', 'Lucy', 'Jack', 'Tawnya', 'Tom'	['question_type_local']
who are the testers?	'Francoise'	['question_type_global', 'question_single_statement']
Are there any testers assigned to the [pilot] projects?	'Francoise'	['question_type_global', 'question_three_hop_statement']
Who was [the fails with apache stack issue] assigned to?	'Albertha'	['question_type_local']
Who has issues assigned to them that were not resolved?	'Roslyn'	['question_type_global', 'question_two_hop_statement']
What testers are assigned to the [pilot] projects?	'Francoise'	['question_type_global', 'question_three_hop_statement']
What are the issues that are resolved for [pilot] projects?	'fails with apache stack', 'null pointer exception during parsing', 'parsing with parantheses fails', 'wrong pos tag on consecutive words', 'saving data throws exception'	['question_type_global', 'question_two_hop_statement']
Who are the testers on [knowledge base project]	'Francoise'	['question_type_local']
Which developers have issues assigned to them that were all resolved?	'Albertha', 'Lucy', 'Jack', 'Tom'	['question_type_global', 'question_three_hop_statement']
What are the non resolved issues?	'parse example terribly slow', 'xml extractor exception', 'dcoref always returns null'	['question_type_global', 'question_single_statement']
What are the resolved issues for [this project]?	'saving data throws exception'	['question_type_global', 'question_two_hop_statement']
Are there any developers assigned to the [pilot] projects?	'Roslyn', 'Albertha', 'Lucy', 'Jack', 'Tawnya', 'Tom'	['question_type_global', 'question_three_hop_statement']
[this project] is in the stage of [deployment]
[this project] is in the [implementation] stage
[Lucy] created a new issue for [chatbot project]: [memory leak bug]
[the issue] was assigned to [Francoise]
[that test engineer] resolved [the issue]
[knowledge base project] is now in the [implementation] stage
What are the issues that are resolved for projects in the [implementation] stage?	'fails with apache stack', 'parsing with parantheses fails', 'saving data throws exception', 'memory leak bug'	['question_type_global', 'question_three_hop_statement']
Are there any issues that are resolved?	'fails with apache stack', 'null pointer exception during parsing', 'parsing with parantheses fails', 'wrong pos tag on consecutive words', 'saving data throws exception', 'memory leak bug'	['question_type_global', 'question_single_statement']
Are there any issues that are not resolved for [pilot] projects?	'parse example terribly slow', 'xml extractor exception', 'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
[Roslyn] resolved [the parse example terribly slow bug]
What projects is [that developer] working on?	'chatbot'	['question_type_local']
Are there any [pilot] projects?	'chatbot', 'knowledge base', 'mobile'	['question_type_global', 'question_single_statement']
who are the testers?	'Francoise'	['question_type_global', 'question_single_statement']
What testers are assigned to projects in the [implementation] stage?	'Francoise'	['question_type_global', 'question_three_hop_statement']
[Roslyn] is assigned to [knowledge base project] also
What projects are [pilot]?	'chatbot', 'knowledge base', 'mobile'	['question_type_global', 'question_single_statement']
Who has issues assigned to them that were all resolved?	'Roslyn', 'Albertha', 'Francoise', 'Lucy', 'Jack', 'Tom'	['question_type_global', 'question_two_hop_statement']
Are there any issues that are resolved for [pilot] projects?	'parse example terribly slow', 'fails with apache stack', 'null pointer exception during parsing', 'parsing with parantheses fails', 'wrong pos tag on consecutive words', 'saving data throws exception', 'memory leak bug'	['question_type_global', 'question_two_hop_statement']
Who are the developers currently working on projects in the [implementation] stage?	'Roslyn', 'Albertha', 'Lucy', 'Jack', 'Tawnya', 'Tom'	['question_type_global', 'question_three_hop_statement']
[Albertha] is no longer assigned to [knowledge base project]
[she] is working on [that project] also
Who submitted [the xml extractor exception task]?	'Roslyn'	['question_type_local']
Are there any people assigned to projects in the [deployment] stage?	'Albertha', 'Francoise', 'Lucy', 'Jack', 'Tawnya', 'Tom'	['question_type_global', 'question_two_hop_statement']
Which developers have issues assigned to them that were all resolved?	'Roslyn', 'Albertha', 'Lucy', 'Jack', 'Tom'	['question_type_global', 'question_three_hop_statement']
Who is working on [mobile project]?	'Albertha', 'Francoise', 'Lucy', 'Jack', 'Tawnya', 'Tom'	['question_type_local']
Who are the developers currently working on the [pilot] projects?	'Roslyn', 'Albertha', 'Lucy', 'Jack', 'Tawnya', 'Tom'	['question_type_global', 'question_three_hop_statement']
What are the non resolved [task]s?	'xml extractor exception', 'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
[Albertha] is no longer assigned to [mobile project]
[Albertha] is assigned to [mobile project] also
[she] is no longer assigned to [that project]
who are the developers?	'Roslyn', 'Albertha', 'Lucy', 'Jack', 'Tawnya', 'Tom'	['question_type_global', 'question_single_statement']
Which testers have issues assigned to them that were all resolved?	'Francoise'	['question_type_global', 'question_three_hop_statement']
[this project] is assigned to [Albertha] also
Who created [the wrong pos tag on consecutive words issue]?	'Albertha'	['question_type_local']
Are there any issues that are resolved for projects in the [implementation] stage?	'parse example terribly slow', 'fails with apache stack', 'parsing with parantheses fails', 'saving data throws exception', 'memory leak bug'	['question_type_global', 'question_three_hop_statement']
What testers are assigned to projects in the [implementation] stage?	'Francoise'	['question_type_global', 'question_three_hop_statement']
What are the issues that are resolved for [pilot] projects?	'parse example terribly slow', 'fails with apache stack', 'null pointer exception during parsing', 'parsing with parantheses fails', 'wrong pos tag on consecutive words', 'saving data throws exception', 'memory leak bug'	['question_type_global', 'question_two_hop_statement']
[mobile project] is now in the [evaluation] stage
[that project] is in the [deployment] stage
[this project] is now in the [evaluation] stage
Are there any developers assigned to the [pilot] projects?	'Roslyn', 'Albertha', 'Lucy', 'Jack', 'Tawnya', 'Tom'	['question_type_global', 'question_three_hop_statement']
What developers are assigned to the [pilot] projects?	'Roslyn', 'Albertha', 'Lucy', 'Jack', 'Tawnya', 'Tom'	['question_type_global', 'question_three_hop_statement']
Who are the testers currently working on the [pilot] projects?	'Francoise'	['question_type_global', 'question_three_hop_statement']
What are the issues submitted by [Tawnya] that were resolved?	'parsing with parantheses fails'	['question_type_local']
Who is assigned to the [pilot] projects?	'Roslyn', 'Albertha', 'Francoise', 'Lucy', 'Jack', 'Tawnya', 'Tom'	['question_type_global', 'question_two_hop_statement']
What projects is [Francoise] working on?	'chatbot', 'knowledge base', 'mobile'	['question_type_local']
What testers are assigned to projects in the [implementation] stage?	'Francoise'	['question_type_global', 'question_three_hop_statement']
who are the testers?	'Francoise'	['question_type_global', 'question_single_statement']
What are the [task]s that are not resolved?	'xml extractor exception', 'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
Who is assigned to projects in the [evaluation] stage?	'Albertha', 'Francoise', 'Lucy', 'Jack', 'Tawnya', 'Tom'	['question_type_global', 'question_two_hop_statement']
Who created [the xml extractor exception issue]?	'Roslyn'	['question_type_local']
What are the resolved issues for [chatbot project]?	'parse example terribly slow', 'saving data throws exception', 'memory leak bug'	['question_type_global', 'question_two_hop_statement']
Who is assigned to projects in the [implementation] stage?	'Roslyn', 'Albertha', 'Francoise', 'Lucy', 'Jack', 'Tawnya', 'Tom'	['question_type_global', 'question_two_hop_statement']
What projects are currently in the [evaluation] stage?	'mobile'	['question_type_global', 'question_single_statement']
What are the non resolved [bug]s?	'parse example terribly slow'	['question_type_global', 'question_two_hop_statement']
What are the issues assigned to [Lucy] that were resolved?	'wrong pos tag on consecutive words'	['question_type_local']
What are the [pilot] projects?	'chatbot', 'knowledge base', 'mobile'	['question_type_global', 'question_single_statement']
What are the issues that were resolved?	'parse example terribly slow', 'fails with apache stack', 'null pointer exception during parsing', 'parsing with parantheses fails', 'wrong pos tag on consecutive words', 'saving data throws exception', 'memory leak bug'	['question_type_global', 'question_single_statement']
Are there any people assigned to the [pilot] projects?	'Roslyn', 'Albertha', 'Francoise', 'Lucy', 'Jack', 'Tawnya', 'Tom'	['question_type_global', 'question_two_hop_statement']
who are the testers?	'Francoise'	['question_type_global', 'question_single_statement']
[knowledge base project] is not assigned to [Tom]
[knowledge base project] is assigned to [Tom] also
[Albertha] is not working on [knowledge base project] anymore
[that developer] is assigned to [this project] also
[it] is in the stage of [deployment]
[knowledge base project] is in the [implementation] stage
Who created [the dcoref always returns null issue]?	'Roslyn'	['question_type_local']
What projects are [pilot]?	'chatbot', 'knowledge base', 'mobile'	['question_type_global', 'question_single_statement']
Are there any testers assigned to projects in the [implementation] stage?	'Francoise'	['question_type_global', 'question_three_hop_statement']
Who are the developers on [mobile project]	'Albertha', 'Lucy', 'Jack', 'Tawnya', 'Tom'	['question_type_local']
Are there any issues that are resolved?	'parse example terribly slow', 'fails with apache stack', 'null pointer exception during parsing', 'parsing with parantheses fails', 'wrong pos tag on consecutive words', 'saving data throws exception', 'memory leak bug'	['question_type_global', 'question_single_statement']
What are the [bug]s that are not resolved?	'parse example terribly slow'	['question_type_global', 'question_two_hop_statement']
[Lucy] is no longer assigned to [mobile project]
[Lucy] is working on [mobile project] also
What are the issues assigned to [that developer]?	'wrong pos tag on consecutive words'	['question_type_local']
What are the issues that are not resolved?	'xml extractor exception', 'dcoref always returns null'	['question_type_global', 'question_single_statement']
Are there any issues assigned to [Albertha] that are resolved?	'fails with apache stack', 'null pointer exception during parsing'	['question_type_local']
Who are the developers currently working on the [pilot] projects?	'Roslyn', 'Albertha', 'Lucy', 'Jack', 'Tawnya', 'Tom'	['question_type_global', 'question_three_hop_statement']
Are there any [bug]s that are not resolved?	'parse example terribly slow'	['question_type_global', 'question_two_hop_statement']
What are the non resolved issues for [pilot] projects?	'xml extractor exception', 'dcoref always returns null'	['question_type_global', 'question_two_hop_statement']
who are the testers?	'Francoise'	['question_type_global', 'question_single_statement']
[that project] is now in the [implementation] stage
