there is a [student] named [Angelita]
[she]'s email is [Angelita@chk.ru]
[she] is not a friend
[that person]'s major is [computer science]
actually [she] is my friend
What is [that person]'s email	'Angelita@chk.ru'	['question_type_local']
What is [that person]'s major	'computer science'	['question_type_local']
What is [Angelita]'s email	'Angelita@chk.ru'	['question_type_local']
[Peggy] is a [student]
[Peggy]'s major is [computer science]
[she] is a friend
[this person]'s email is [Peggy@yandex.com]
What is [this student]'s major	'computer science'	['question_type_local']
create a new [meeting]
[this person]'s affiliation is [Adams College]
[this person] is not my friend
[Angelita] will attend [the event]
[this meeting] is [to grade papers]
Who is attending [this meeting]	'Angelita'	['question_type_local']
who are my friends?	'Angelita'	['question_type_global', 'question_single_statement']
[Tawnya] is a [professor]
[Gabrielle] is a [student]
who attended [to grade papers]	'Angelita'	['question_type_global', 'question_single_statement']
there is a [professor] named [Milagros]
[that student]'s major is [food science]
[that student]'s affiliation is [Hudson University]
[that person]'s email is [Gabrielle@yahoo.com]
[that person] is not a friend
create a new [meeting]
Which university is [this student] affiliated with?	'Hudson University'	['question_type_local']
there is a [meeting] [to prepare for exams]
[Milagros] will attend [the event that was last added]
[that professor] attended [this meeting] on time
[Angelita]'s affiliation is [Hudson University]
What is [this student]'s affiliation?	'Hudson University'	['question_type_local']
create a new [meeting]
[that meeting] is [to practice presentations]
[Gabrielle] will attend [this meeting]
which students are majoring in [computer science]	'Angelita', 'Peggy'	['question_type_global', 'question_single_statement']
[this person] attended [the event] on time
[Angelita] will attend [that meeting]
What is [that person]'s email	'Angelita@chk.ru'	['question_type_local']
who attended [to grade papers]	'Angelita'	['question_type_global', 'question_single_statement']
who are my friends?	'Angelita'	['question_type_global', 'question_single_statement']
there is a [meeting] [to grade papers]
What is [Gabrielle]'s major	'food science'	['question_type_local']
which students are my friends?	'Angelita'	['question_type_global', 'question_two_hop_statement']
What is [Angelita]'s email	'Angelita@chk.ru'	['question_type_local']
which students are majoring in [food science]	'Gabrielle'	['question_type_global', 'question_single_statement']
was anyone affiliated with [Hudson University] attended [to practice presentations]	'Gabrielle'	['question_type_global', 'question_two_hop_statement']
Change major of [that person] to [biology]
[Peggy] will attend [the event with Angelita and Gabrielle]
[Tawnya] will attend [that meeting]
[this professor] attended [the event] late
[Tawnya] is not a friend
[Tawnya]'s affiliation is [Adams College]
What is [this person]'s affiliation?	'Adams College'	['question_type_local']
were any students affiliated with [Hudson University] in attendance to [to practice presentations]	'Gabrielle'	['question_type_global', 'question_three_hop_statement']
[that professor]'s email is [Tawnya@nh.edu]
What is [that person]'s email	'Tawnya@nh.edu'	['question_type_local']
which people attended meetings late	'Tawnya'	['question_type_global', 'question_single_statement']
[Tawnya]'s department is [asian studies]
was anyone affiliated with [asian studies] attending any meetings late?	'Tawnya'	['question_type_global', 'question_two_hop_statement']
which students are majoring in [food science]	'Gabrielle'	['question_type_global', 'question_single_statement']
who is affiliated with [Adams College]	'Peggy', 'Tawnya'	['question_type_global', 'question_single_statement']
who is in the [asian studies] department	'Tawnya'	['question_type_global', 'question_single_statement']
which people are affiliated with [Adams College]	'Peggy', 'Tawnya'	['question_type_global', 'question_single_statement']
which people are affiliated with [Hudson University]	'Angelita', 'Gabrielle'	['question_type_global', 'question_single_statement']
which people attended meetings late	'Tawnya'	['question_type_global', 'question_single_statement']
which professors affiliated with [Adams College] attended [to practice presentations]	'Tawnya'	['question_type_global', 'question_three_hop_statement']
create a new [meeting]
Who is attending [the event with Angelita and Gabrielle to practice presentations]	'Angelita', 'Peggy', 'Tawnya', 'Gabrielle'	['question_type_local']
which people affiliated with [Adams College] were late	'Tawnya'	['question_type_global', 'question_two_hop_statement']
was anyone affiliated with [asian studies] attending any meetings late?	'Tawnya'	['question_type_global', 'question_two_hop_statement']
What is [Peggy]'s major	'computer science'	['question_type_local']
[that meeting] is [to grade papers]
[Gabrielle] will attend [this meeting]
Change major of [Angelita] to [history]
create a new [meeting]
What is [Angelita]'s major	'history'	['question_type_local']
[Milagros]'s email is [Milagros@yandex.com]
[she] is not a friend
[that professor]'s department is [mechanical engineering]
[she]'s affiliation is [Medfield College]
Which university is [this person] affiliated with?	'Medfield College'	['question_type_local']
Which university is [this professor] affiliated with?	'Medfield College'	['question_type_local']
which students are majoring in [computer science]	'Peggy'	['question_type_global', 'question_single_statement']
What department is [she] affiliated with?	'mechanical engineering'	['question_type_local']
actually [this professor] is my friend
who is affiliated with [Adams College]	'Peggy', 'Tawnya'	['question_type_global', 'question_single_statement']
which professors are my friends?	'Milagros'	['question_type_global', 'question_two_hop_statement']
were any people affiliated with [Adams College] late	'Tawnya'	['question_type_global', 'question_two_hop_statement']
which people are affiliated with [Hudson University]	'Angelita', 'Gabrielle'	['question_type_global', 'question_single_statement']
create a new [meeting]
[this person] will attend [the meeting to grade papers with Gabrielle]
Who is attending [the meeting]	'Gabrielle', 'Milagros'	['question_type_local']
who are my friends?	'Angelita', 'Milagros'	['question_type_global', 'question_single_statement']
there is a [meeting] [to practice presentations]
[Peggy] will attend [that meeting]
What is [Angelita]'s email	'Angelita@chk.ru'	['question_type_local']
was anyone from the [mechanical engineering] department in attendance?	'Milagros'	['question_type_global', 'question_two_hop_statement']
which students are my friends?	'Angelita'	['question_type_global', 'question_two_hop_statement']
which people affiliated with [Hudson University] attended [to practice presentations]	'Gabrielle'	['question_type_global', 'question_two_hop_statement']
who is affiliated with [Adams College]	'Peggy', 'Tawnya'	['question_type_global', 'question_single_statement']
[Tawnya] will attend [this meeting]
[Peggy] attended [this meeting] late
[Gabrielle] will attend [the event]
Who was late to [that meeting]	'Peggy'	['question_type_local']
create a new [meeting]
which professors are affiliated with the [mechanical engineering] department	'Milagros'	['question_type_global', 'question_single_statement']
What is [this student]'s major	'food science'	['question_type_local']
[Peggy] will attend [the meeting with Milagros that was last added]
[Peggy] attended [that meeting] on time
[the event that was last added] is [to grade papers]
which students attended meetings late	'Peggy'	['question_type_global', 'question_two_hop_statement']
which people affiliated with [Adams College] were late	'Peggy', 'Tawnya'	['question_type_global', 'question_two_hop_statement']
[Angelita] attended [the event to grade papers with Angelita] late
Who was late to [that meeting]	'Angelita'	['question_type_local']
which people attended meetings late	'Angelita', 'Peggy', 'Tawnya'	['question_type_global', 'question_single_statement']
has anyone from the [asian studies] department attending meetings	'Tawnya'	['question_type_global', 'question_two_hop_statement']
there is a [meeting] [to grade papers]
What is [that student]'s major	'history'	['question_type_local']
which people affiliated with [Medfield College] attended [to prepare for exams]	'Milagros'	['question_type_global', 'question_two_hop_statement']
which students are my friends?	'Angelita'	['question_type_global', 'question_two_hop_statement']
was anyone from the [mechanical engineering] department in attendance?	'Milagros'	['question_type_global', 'question_two_hop_statement']
were any [food science] majors attending the meetings?	'Gabrielle'	['question_type_global', 'question_two_hop_statement']
[this student] is not my friend
What is [that student]'s email	'Angelita@chk.ru'	['question_type_local']
who is in the [asian studies] department	'Tawnya'	['question_type_global', 'question_single_statement']
has anyone from the [asian studies] department attending meetings late	'Tawnya'	['question_type_global', 'question_two_hop_statement']
create a new [meeting]
What is [that person]'s major	'history'	['question_type_local']
who attended [to prepare for exams]	'Milagros'	['question_type_global', 'question_single_statement']
What is [this person]'s major	'history'	['question_type_local']
which students attended meetings late	'Angelita', 'Peggy'	['question_type_global', 'question_two_hop_statement']
Which university is [that person] affiliated with?	'Hudson University'	['question_type_local']
[that meeting] is [to practice presentations]
[Tawnya] will attend [the event]
Who is attending [this meeting]	'Tawnya'	['question_type_local']
was anyone affiliated with [asian studies] attending any meetings late?	'Tawnya'	['question_type_global', 'question_two_hop_statement']
who are my friends?	'Milagros'	['question_type_global', 'question_single_statement']
which students are majoring in [computer science]	'Peggy'	['question_type_global', 'question_single_statement']
were any [food science] majors attending the meetings?	'Gabrielle'	['question_type_global', 'question_two_hop_statement']
What is [Peggy]'s major	'computer science'	['question_type_local']
who are my professor friends?	'Milagros'	['question_type_global', 'question_two_hop_statement']
who is majoring in [history]	'Angelita'	['question_type_global', 'question_single_statement']
which people affiliated with [Hudson University] were late	'Angelita'	['question_type_global', 'question_two_hop_statement']
who was late to [to practice presentations]	'Peggy', 'Tawnya'	['question_type_global', 'question_two_hop_statement']
What is [that professor]'s email	'Tawnya@nh.edu'	['question_type_local']
which students attended meetings late	'Angelita', 'Peggy'	['question_type_global', 'question_two_hop_statement']
who are my friends?	'Milagros'	['question_type_global', 'question_single_statement']
were any people affiliated with [Adams College] late to [to practice presentations]	'Peggy', 'Tawnya'	['question_type_global', 'question_three_hop_statement']
[Tawnya] attended [that meeting] on time
[Peggy] will attend [the event]
[Angelita] will attend [that meeting]
What is [this student]'s major	'history'	['question_type_local']
[Milagros] will attend [this meeting]
[Milagros] attended [the event] on time
[Peggy] attended [this meeting] on time
who is majoring in [computer science]	'Peggy'	['question_type_global', 'question_single_statement']
was anyone affiliated with [Adams College] attended [to practice presentations]	'Peggy', 'Tawnya'	['question_type_global', 'question_two_hop_statement']
What is [Gabrielle]'s email	'Gabrielle@yahoo.com'	['question_type_local']
who is majoring in [history]	'Angelita'	['question_type_global', 'question_single_statement']
who are my friends?	'Milagros'	['question_type_global', 'question_single_statement']
What is [Milagros]'s affiliation?	'Medfield College'	['question_type_local']
who are my professor friends?	'Milagros'	['question_type_global', 'question_two_hop_statement']
[Gabrielle] attended [the meeting to practice presentations with Gabrielle and Tawnya that was last added] late
[Milagros] will attend [this meeting]
What is [she]'s email	'Milagros@yandex.com'	['question_type_local']
[Milagros] attended [this meeting] late
Who was late to [this meeting]	'Peggy', 'Gabrielle', 'Milagros'	['question_type_local']
who is majoring in [computer science]	'Peggy'	['question_type_global', 'question_single_statement']
Change major of [Angelita] to [food science]
What is [that student]'s email	'Angelita@chk.ru'	['question_type_local']
[Tawnya] attended [the meeting to practice presentations with Gabrielle that was last added] on time
create a new [meeting]
who attended [to practice presentations] late	'Peggy', 'Tawnya', 'Gabrielle', 'Milagros'	['question_type_global', 'question_two_hop_statement']
who attended [to prepare for exams]	'Milagros'	['question_type_global', 'question_single_statement']
[this meeting] is [to prepare for exams]
[Peggy] will attend [this meeting]
What department is [Tawnya] with?	'asian studies'	['question_type_local']
which people are in the [asian studies] department	'Tawnya'	['question_type_global', 'question_single_statement']
who are my professor friends?	'Milagros'	['question_type_global', 'question_two_hop_statement']
which professors are affiliated with the [asian studies] department	'Tawnya'	['question_type_global', 'question_single_statement']
What is [that student]'s major	'computer science'	['question_type_local']
were any professors affiliated with [Medfield College] late to any meetings	'Milagros'	['question_type_global', 'question_three_hop_statement']
who is affiliated with [Adams College]	'Peggy', 'Tawnya'	['question_type_global', 'question_single_statement']
[this person] attended [that meeting] on time
[Milagros] will attend [this meeting]
Who is attending [that meeting]	'Peggy', 'Milagros'	['question_type_local']
What is [Angelita]'s email	'Angelita@chk.ru'	['question_type_local']
who are my friends?	'Milagros'	['question_type_global', 'question_single_statement']
who is affiliated with [Hudson University]	'Angelita', 'Gabrielle'	['question_type_global', 'question_single_statement']
who is in the [mechanical engineering] department	'Milagros'	['question_type_global', 'question_single_statement']
What is [Gabrielle]'s email	'Gabrielle@yahoo.com'	['question_type_local']
was anyone from the [asian studies] department late to meetings?	'Tawnya'	['question_type_global', 'question_two_hop_statement']
which people are affiliated with [Adams College]	'Peggy', 'Tawnya'	['question_type_global', 'question_single_statement']
who attended [to grade papers]	'Angelita', 'Peggy', 'Gabrielle', 'Milagros'	['question_type_global', 'question_single_statement']
was anyone who majored in [food science] in attendance?	'Angelita', 'Gabrielle'	['question_type_global', 'question_two_hop_statement']
[this professor] will attend [the event with Angelita to grade papers]
Who was late to [the meeting]	'Angelita'	['question_type_local']
who are my friends?	'Milagros'	['question_type_global', 'question_single_statement']
were any people affiliated with [Hudson University] late	'Angelita', 'Gabrielle'	['question_type_global', 'question_two_hop_statement']
which professors are my friends?	'Milagros'	['question_type_global', 'question_two_hop_statement']
Which university is [this person] affiliated with?	'Medfield College'	['question_type_local']
who is affiliated with [Medfield College]	'Milagros'	['question_type_global', 'question_single_statement']
What department is [Tawnya] with?	'asian studies'	['question_type_local']
was anyone affiliated with [Hudson University] late to any meetings	'Angelita', 'Gabrielle'	['question_type_global', 'question_two_hop_statement']
was anyone who majored in [food science] ever late to any meetings?	'Angelita', 'Gabrielle'	['question_type_global', 'question_two_hop_statement']
which professors affiliated with [Adams College] were late	'Tawnya'	['question_type_global', 'question_three_hop_statement']
[Peggy] will attend [that meeting]
[Milagros] attended [that meeting] on time
[Gabrielle] will attend [that meeting]
Who is attending [the event]	'Angelita', 'Peggy', 'Gabrielle', 'Milagros'	['question_type_local']
which professors are my friends?	'Milagros'	['question_type_global', 'question_two_hop_statement']
[the event to practice presentations with Gabrielle that was last added] now is [to prepare for exams]
Who was late to [this meeting]	'Peggy', 'Gabrielle', 'Milagros'	['question_type_local']
which students attended meetings late	'Angelita', 'Peggy', 'Gabrielle'	['question_type_global', 'question_two_hop_statement']
which professors are affiliated with the [mechanical engineering] department	'Milagros'	['question_type_global', 'question_single_statement']
What is [that person]'s email	'Gabrielle@yahoo.com'	['question_type_local']
who is affiliated with [Hudson University]	'Angelita', 'Gabrielle'	['question_type_global', 'question_single_statement']
who attended [to grade papers]	'Angelita', 'Peggy', 'Gabrielle', 'Milagros'	['question_type_global', 'question_single_statement']
Who is attending [this meeting]	'Peggy', 'Tawnya', 'Gabrielle', 'Milagros'	['question_type_local']
which students are majoring in [computer science]	'Peggy'	['question_type_global', 'question_single_statement']
which professors affiliated with [Medfield College] were late	'Milagros'	['question_type_global', 'question_three_hop_statement']
which professors are my friends?	'Milagros'	['question_type_global', 'question_two_hop_statement']
Who was late to [this meeting]	'Peggy', 'Gabrielle', 'Milagros'	['question_type_local']
which students attended meetings late	'Angelita', 'Peggy', 'Gabrielle'	['question_type_global', 'question_two_hop_statement']
were any students affiliated with [Adams College] late to any meetings	'Peggy'	['question_type_global', 'question_three_hop_statement']
[Peggy] will attend [the event to grade papers that was last added]
[Gabrielle] attended [the event with Milagros to grade papers that was last added] on time
[Angelita] attended [the event to practice presentations with Gabrielle] on time
What is [Tawnya]'s affiliation?	'Adams College'	['question_type_local']
who is in the [mechanical engineering] department	'Milagros'	['question_type_global', 'question_single_statement']
were any professors affiliated with [Medfield College] in attendance to [to grade papers]	'Milagros'	['question_type_global', 'question_three_hop_statement']
were any [computer science] majors ever late?	'Peggy'	['question_type_global', 'question_two_hop_statement']
which people are affiliated with [Hudson University]	'Angelita', 'Gabrielle'	['question_type_global', 'question_single_statement']
create a new [meeting]
[Gabrielle] will attend [this meeting]
Who is attending [the meeting]	'Gabrielle'	['question_type_local']
were any students affiliated with [Adams College] in attendance to [to practice presentations]	'Peggy'	['question_type_global', 'question_three_hop_statement']
were any [food science] majors attending the meetings?	'Angelita', 'Gabrielle'	['question_type_global', 'question_two_hop_statement']
create a new [meeting]
Change major of [that person] to [biology]
What is [that student]'s affiliation?	'Hudson University'	['question_type_local']
which professors are my friends?	'Milagros'	['question_type_global', 'question_two_hop_statement']
actually [she] is my friend
there is a [meeting] [to practice presentations]
[the event with Gabrielle to grade papers that was last added] now is [to prepare for exams]
[Gabrielle] will attend [the meeting to practice presentations that was last added]
[this student] attended [the event] late
