create a [person] named [Cyndi]
[that person] is not a friend
[Cyndi]'s affiliation is [Adams College]
What is [this person]'s affiliation?	'Adams College'	['question_type_local']
[Stephine] is a [professor]
Which university is [Cyndi] affiliated with?	'Adams College'	['question_type_local']
there is a [meeting] [to practice presentations]
[Stephine]'s affiliation is [Hudson University]
[she] is a friend
there is a [person] named [William]
[he] is a friend
[this person]'s affiliation is [Adams College]
there is a [professor] named [Vivienne]
[Vivienne]'s affiliation is [Hudson University]
there is a [person] named [Lucy]
[that professor] is a friend
Which university is [William] affiliated with?	'Adams College'	['question_type_local']
who are my professor friends?	'Stephine', 'Vivienne'	['question_type_global', 'question_two_hop_statement']
[Lucy]'s affiliation is [Pennbrook University]
[Lucy] is not a friend
Which university is [Lucy] affiliated with?	'Pennbrook University'	['question_type_local']
who is affiliated with [Hudson University]	'Stephine', 'Vivienne'	['question_type_global', 'question_single_statement']
which professors are my friends?	'Stephine', 'Vivienne'	['question_type_global', 'question_two_hop_statement']
there is a [meeting] [to grade papers]
[William] will attend [this meeting]
there is a [meeting] [to discuss future plans]
[Cyndi] will attend [this meeting]
[this person] attended [that meeting] on time
Who is attending [this meeting]	'Cyndi'	['question_type_local']
Which university is [she] affiliated with?	'Adams College'	['question_type_local']
who attended [to discuss future plans]	'Cyndi'	['question_type_global', 'question_single_statement']
actually [that person] is my friend
Which university is [Cyndi] affiliated with?	'Adams College'	['question_type_local']
who attended [to grade papers]	'William'	['question_type_global', 'question_single_statement']
[this person] is not my friend
actually [this person] is my friend
who are my professor friends?	'Stephine', 'Vivienne'	['question_type_global', 'question_two_hop_statement']
who is affiliated with [Adams College]	'Cyndi', 'William'	['question_type_global', 'question_single_statement']
which professors are my friends?	'Stephine', 'Vivienne'	['question_type_global', 'question_two_hop_statement']
[that person] is not my friend
[Stephine] will attend [the meeting that was last added]
Who is attending [the event]	'Cyndi', 'Stephine'	['question_type_local']
who attended [to discuss future plans]	'Cyndi', 'Stephine'	['question_type_global', 'question_single_statement']
create a new [meeting]
Who is attending [the meeting to discuss future plans with Cyndi]	'Cyndi', 'Stephine'	['question_type_local']
which people are affiliated with [Pennbrook University]	'Lucy'	['question_type_global', 'question_single_statement']
create a new [meeting]
[the event that was last added] is [to grade papers]
[William] will attend [this meeting]
Who is attending [that meeting]	'William'	['question_type_local']
What is [that person]'s affiliation?	'Adams College'	['question_type_local']
there is a [meeting] [about homework grading]
actually [Cyndi] is my friend
[Lucy] will attend [the meeting to grade papers that was last added]
[William] attended [this meeting] on time
who are my professor friends?	'Stephine', 'Vivienne'	['question_type_global', 'question_two_hop_statement']
which professors are my friends?	'Stephine', 'Vivienne'	['question_type_global', 'question_two_hop_statement']
Which university is [this person] affiliated with?	'Adams College'	['question_type_local']
there is a [meeting] [to discuss future plans]
who are my friends?	'Cyndi', 'Stephine', 'William', 'Vivienne'	['question_type_global', 'question_single_statement']
Which university is [that person] affiliated with?	'Adams College'	['question_type_local']
What is [Vivienne]'s affiliation?	'Hudson University'	['question_type_local']
there is a [meeting] [to grade papers]
[Stephine] will attend [the event to grade papers that was last added]
[this meeting] now is [to prepare for exams]
Who is attending [the meeting]	'Stephine'	['question_type_local']
who is affiliated with [Hudson University]	'Stephine', 'Vivienne'	['question_type_global', 'question_single_statement']
create a new [meeting]
[Stephine] attended [the event with Stephine to prepare for exams] on time
which professors affiliated with [Hudson University] attended [to prepare for exams]	'Stephine'	['question_type_global', 'question_three_hop_statement']
What is [Cyndi]'s affiliation?	'Adams College'	['question_type_local']
was anyone affiliated with [Adams College] attended [to grade papers]	'William'	['question_type_global', 'question_two_hop_statement']
[Lucy] will attend [the meeting]
[that meeting] now is [to discuss future plans]
there is a [meeting] [about homework grading]
create a new [meeting]
What is [Lucy]'s affiliation?	'Pennbrook University'	['question_type_local']
[the meeting that was last added] is [to discuss future plans]
[Stephine] will attend [the event with Lucy and William to grade papers]
[Lucy] attended [this meeting] on time
Who is attending [this meeting]	'Stephine', 'William', 'Lucy'	['question_type_local']
[Vivienne] will attend [this meeting]
[Stephine] attended [the event] on time
[Stephine] is not my friend
Which university is [this person] affiliated with?	'Hudson University'	['question_type_local']
which people are affiliated with [Pennbrook University]	'Lucy'	['question_type_global', 'question_single_statement']
Which university is [Cyndi] affiliated with?	'Adams College'	['question_type_local']
create a new [meeting]
Who is attending [the event to grade papers with Vivienne and Stephine]	'Stephine', 'William', 'Vivienne', 'Lucy'	['question_type_local']
who is affiliated with [Adams College]	'Cyndi', 'William'	['question_type_global', 'question_single_statement']
who are my professor friends?	'Vivienne'	['question_type_global', 'question_two_hop_statement']
which professors affiliated with [Hudson University] attended [to discuss future plans]	'Stephine'	['question_type_global', 'question_three_hop_statement']
which professors are my friends?	'Vivienne'	['question_type_global', 'question_two_hop_statement']
there is a [meeting] [to grade papers]
[Cyndi] will attend [the event with Lucy to discuss future plans]
[this person] will attend [the event to discuss future plans that was last added]
[the event] now is [to prepare for exams]
[Lucy] will attend [that meeting]
[this person] attended [that meeting] on time
there is a [meeting] [to practice presentations]
What is [she]'s affiliation?	'Pennbrook University'	['question_type_local']
who are my friends?	'Cyndi', 'William', 'Vivienne'	['question_type_global', 'question_single_statement']
Which university is [Lucy] affiliated with?	'Pennbrook University'	['question_type_local']
Which university is [this person] affiliated with?	'Pennbrook University'	['question_type_local']
[Lucy] will attend [that meeting]
Who is attending [this meeting]	'Lucy'	['question_type_local']
Which university is [Cyndi] affiliated with?	'Adams College'	['question_type_local']
actually [Lucy] is my friend
What is [she]'s affiliation?	'Pennbrook University'	['question_type_local']
who attended [to discuss future plans]	'Cyndi', 'Stephine', 'Lucy'	['question_type_global', 'question_single_statement']
Who is attending [the meeting to practice presentations with Lucy]	'Lucy'	['question_type_local']
which professors are my friends?	'Vivienne'	['question_type_global', 'question_two_hop_statement']
Which university is [she] affiliated with?	'Pennbrook University'	['question_type_local']
who are my friends?	'Cyndi', 'William', 'Vivienne', 'Lucy'	['question_type_global', 'question_single_statement']
which people are affiliated with [Hudson University]	'Stephine', 'Vivienne'	['question_type_global', 'question_single_statement']
Who is attending [the meeting to prepare for exams]	'Cyndi', 'Lucy'	['question_type_local']
which professors affiliated with [Hudson University] attended [to grade papers]	'Stephine'	['question_type_global', 'question_three_hop_statement']
create a new [meeting]
there is a [meeting] [about homework grading]
there is a [meeting] [to grade papers]
[Cyndi] will attend [the meeting about homework grading that was last added]
who attended [to discuss future plans]	'Cyndi', 'Stephine', 'Lucy'	['question_type_global', 'question_single_statement']
[Vivienne] will attend [this meeting]
[Vivienne] attended [that meeting] late
Who was late to [this meeting]	'Vivienne'	['question_type_local']
which professors are my friends?	'Vivienne'	['question_type_global', 'question_two_hop_statement']
create a new [meeting]
[that meeting] is [to practice presentations]
[William] will attend [the event to discuss future plans that was last added]
[Cyndi] attended [the event] late
Who is attending [the event to grade papers with William and Stephine]	'Stephine', 'William', 'Vivienne', 'Lucy'	['question_type_local']
was anyone affiliated with [Hudson University] late to any meetings	'Vivienne'	['question_type_global', 'question_two_hop_statement']
who attended [to grade papers]	'Stephine', 'William', 'Vivienne', 'Lucy'	['question_type_global', 'question_single_statement']
What is [Cyndi]'s affiliation?	'Adams College'	['question_type_local']
who are my friends?	'Cyndi', 'William', 'Vivienne', 'Lucy'	['question_type_global', 'question_single_statement']
Who was late to [this meeting]	'Cyndi'	['question_type_local']
[Cyndi] attended [the meeting with Cyndi and Vivienne] late
[William] will attend [that meeting]
Who was late to [that meeting]	'Cyndi', 'Vivienne'	['question_type_local']
What is [he]'s affiliation?	'Adams College'	['question_type_local']
who are my professor friends?	'Vivienne'	['question_type_global', 'question_two_hop_statement']
there is a [meeting] [to prepare for exams]
was anyone affiliated with [Adams College] late to any meetings	'Cyndi'	['question_type_global', 'question_two_hop_statement']
was anyone affiliated with [Hudson University] attended [to grade papers]	'Stephine'	['question_type_global', 'question_two_hop_statement']
[Cyndi] attended [the meeting with Lucy and Cyndi to prepare for exams] on time
[Vivienne] will attend [this meeting]
What is [that professor]'s affiliation?	'Hudson University'	['question_type_local']
who attended [to grade papers]	'Stephine', 'William', 'Vivienne', 'Lucy'	['question_type_global', 'question_single_statement']
[Vivienne] attended [this meeting] on time
which people are affiliated with [Hudson University]	'Stephine', 'Vivienne'	['question_type_global', 'question_single_statement']
create a new [meeting]
[that meeting] is [to practice presentations]
What is [Vivienne]'s affiliation?	'Hudson University'	['question_type_local']
which people affiliated with [Hudson University] were late	'Vivienne'	['question_type_global', 'question_two_hop_statement']
who are my friends?	'Cyndi', 'William', 'Vivienne', 'Lucy'	['question_type_global', 'question_single_statement']
[Vivienne] will attend [that meeting]
create a new [meeting]
[this person] will attend [the event]
which people attended meetings late	'Cyndi', 'Vivienne'	['question_type_global', 'question_single_statement']
was anyone affiliated with [Adams College] attended [to discuss future plans]	'Cyndi'	['question_type_global', 'question_two_hop_statement']
who attended [to discuss future plans]	'Cyndi', 'Stephine', 'William', 'Lucy'	['question_type_global', 'question_single_statement']
[Stephine] will attend [that meeting]
[that meeting] is [about homework grading]
Which university is [Cyndi] affiliated with?	'Adams College'	['question_type_local']
was anyone affiliated with [Adams College] late to [about homework grading]	'Cyndi'	['question_type_global', 'question_three_hop_statement']
which people affiliated with [Hudson University] attended [to grade papers]	'Stephine'	['question_type_global', 'question_two_hop_statement']
[William] will attend [the event with Cyndi to prepare for exams]
What is [he]'s affiliation?	'Adams College'	['question_type_local']
was anyone affiliated with [Adams College] attended [to grade papers]	'William'	['question_type_global', 'question_two_hop_statement']
who was late to [about homework grading]	'Cyndi', 'Vivienne'	['question_type_global', 'question_two_hop_statement']
Which university is [Lucy] affiliated with?	'Pennbrook University'	['question_type_local']
which people attended meetings late	'Cyndi', 'Vivienne'	['question_type_global', 'question_single_statement']
who attended [to practice presentations]	'Vivienne', 'Lucy'	['question_type_global', 'question_single_statement']
[that meeting] now is [to practice presentations]
who are my professor friends?	'Vivienne'	['question_type_global', 'question_two_hop_statement']
Who is attending [the meeting to discuss future plans with Stephine that was last added]	'Cyndi', 'Stephine', 'William', 'Lucy'	['question_type_local']
which professors are my friends?	'Vivienne'	['question_type_global', 'question_two_hop_statement']
Which university is [that person] affiliated with?	'Adams College'	['question_type_local']
were any professors affiliated with [Hudson University] late	'Vivienne'	['question_type_global', 'question_three_hop_statement']
[Vivienne] attended [the meeting to grade papers with Lucy and Stephine] on time
Who is attending [the meeting with William and Cyndi that was last added]	'Cyndi', 'William', 'Vivienne'	['question_type_local']
were any people affiliated with [Pennbrook University] in attendance to [to grade papers]	'Lucy'	['question_type_global', 'question_two_hop_statement']
What is [that professor]'s affiliation?	'Hudson University'	['question_type_local']
who is affiliated with [Adams College]	'Cyndi', 'William'	['question_type_global', 'question_single_statement']
which professors are my friends?	'Vivienne'	['question_type_global', 'question_two_hop_statement']
which people attended meetings late	'Cyndi', 'Vivienne'	['question_type_global', 'question_single_statement']
there is a [meeting] [to practice presentations]
[Lucy] will attend [that meeting]
there is a [meeting] [about homework grading]
which people affiliated with [Pennbrook University] attended [to grade papers]	'Lucy'	['question_type_global', 'question_two_hop_statement']
Who is attending [the meeting to practice presentations with Lucy and William]	'Cyndi', 'William', 'Vivienne', 'Lucy'	['question_type_local']
[that meeting] now is [to practice presentations]
[that meeting] now is [to discuss future plans]
create a new [meeting]
[Vivienne] will attend [the meeting that was last added]
[that professor] attended [that meeting] on time
[that meeting] is [about homework grading]
Who is attending [the event to practice presentations with Lucy and Vivienne]	'Cyndi', 'William', 'Vivienne', 'Lucy'	['question_type_local']
which professors affiliated with [Hudson University] were late	'Vivienne'	['question_type_global', 'question_three_hop_statement']
there is a [meeting] [to practice presentations]
who attended [to discuss future plans] late	'Cyndi'	['question_type_global', 'question_two_hop_statement']
were any people affiliated with [Adams College] late to [about homework grading]	'Cyndi'	['question_type_global', 'question_three_hop_statement']
which people attended meetings late	'Cyndi', 'Vivienne'	['question_type_global', 'question_single_statement']
Who is attending [the meeting about homework grading that was last added]	'Vivienne'	['question_type_local']
who attended [about homework grading]	'Cyndi', 'Stephine', 'William', 'Vivienne'	['question_type_global', 'question_single_statement']
[William] will attend [the meeting to practice presentations that was last added]
[this person] attended [this meeting] late
[Lucy] will attend [the event]
[Stephine] will attend [the meeting with Vivienne that was last added]
