there is a [professor] named [Lucy]
[she] is a friend
[Lucy]'s affiliation is [Hillman College]
create a [student] named [Alverta]
create a new [meeting]
there is a [meeting] [about homework grading]
who are my professor friends?	'Lucy'	['question_type_global', 'question_two_hop_statement']
there is a [person] named [Gabrielle]
there is a [professor] named [Hanna]
[Hanna]'s affiliation is [Hearst College]
who is affiliated with [Hillman College]	'Lucy'	['question_type_global', 'question_single_statement']
[she] is a friend
[that person] is not my friend
What is [that professor]'s affiliation?	'Hearst College'	['question_type_local']
[Emma] is a [professor]
there is a [student] named [Alejandra]
[Alejandra]'s affiliation is [Hudson University]
[this student]'s major is [history]
which professors are my friends?	'Lucy'	['question_type_global', 'question_two_hop_statement']
create a new [meeting]
[this student] is a friend
What is [Alejandra]'s major	'history'	['question_type_local']
who are my friends?	'Lucy', 'Alejandra'	['question_type_global', 'question_single_statement']
which people are affiliated with [Hearst College]	'Hanna'	['question_type_global', 'question_single_statement']
[Lucy] will attend [this meeting]
[Alverta]'s affiliation is [Groff Community College]
[this student] is a friend
What is [that student]'s affiliation?	'Groff Community College'	['question_type_local']
there is a [meeting] [about homework grading]
[this student]'s major is [history]
What is [this person]'s major	'history'	['question_type_local']
which students are majoring in [history]	'Alverta', 'Alejandra'	['question_type_global', 'question_single_statement']
[Lucy] will attend [the meeting]
[that person] attended [this meeting] on time
which students are my friends?	'Alverta', 'Alejandra'	['question_type_global', 'question_two_hop_statement']
[Alverta] will attend [this meeting]
What is [that person]'s major	'history'	['question_type_local']
Which university is [Alejandra] affiliated with?	'Hudson University'	['question_type_local']
which professors affiliated with [Hillman College] attended [about homework grading]	'Lucy'	['question_type_global', 'question_three_hop_statement']
who are my professor friends?	'Lucy'	['question_type_global', 'question_two_hop_statement']
there is a [meeting] [about homework grading]
[Alverta] will attend [that meeting]
[Alverta] attended [the meeting] on time
[Gabrielle] will attend [this meeting]
which people affiliated with [Hillman College] attended [about homework grading]	'Lucy'	['question_type_global', 'question_two_hop_statement']
[that person] is a friend
[this person]'s affiliation is [Hillman College]
Which university is [Gabrielle] affiliated with?	'Hillman College'	['question_type_local']
who is affiliated with [Hillman College]	'Lucy', 'Gabrielle'	['question_type_global', 'question_single_statement']
there is a [meeting] [to practice presentations]
[the event with Lucy that was last added] now is [to prepare for exams]
[Alejandra] will attend [the meeting with Lucy that was last added]
[Alverta] attended [that meeting] late
What is [Alejandra]'s affiliation?	'Hudson University'	['question_type_local']
[Hanna] will attend [that meeting]
who attended [to prepare for exams]	'Lucy', 'Alverta', 'Hanna', 'Alejandra'	['question_type_global', 'question_single_statement']
which people are affiliated with [Hillman College]	'Lucy', 'Gabrielle'	['question_type_global', 'question_single_statement']
who are my professor friends?	'Lucy'	['question_type_global', 'question_two_hop_statement']
create a new [meeting]
[Alverta] is not my friend
which students are my friends?	'Alejandra'	['question_type_global', 'question_two_hop_statement']
which people attended meetings late	'Alverta'	['question_type_global', 'question_single_statement']
was anyone who majored in [history] in attendance?	'Alverta'	['question_type_global', 'question_two_hop_statement']
[Alejandra] attended [the event to prepare for exams with Alverta and Hanna] late
Who is attending [that meeting]	'Lucy', 'Alverta', 'Hanna', 'Alejandra'	['question_type_local']
which students are majoring in [history]	'Alverta', 'Alejandra'	['question_type_global', 'question_single_statement']
Who was late to [that meeting]	'Alverta', 'Alejandra'	['question_type_local']
who are my professor friends?	'Lucy'	['question_type_global', 'question_two_hop_statement']
who is affiliated with [Hearst College]	'Hanna'	['question_type_global', 'question_single_statement']
were any students affiliated with [Hudson University] late to any meetings	'Alejandra'	['question_type_global', 'question_three_hop_statement']
What is [this person]'s major	'history'	['question_type_local']
were any students affiliated with [Hudson University] late	'Alejandra'	['question_type_global', 'question_three_hop_statement']
which students are my friends?	'Alejandra'	['question_type_global', 'question_two_hop_statement']
What is [that student]'s major	'history'	['question_type_local']
were any students affiliated with [Groff Community College] late	'Alverta'	['question_type_global', 'question_three_hop_statement']
which students are majoring in [history]	'Alverta', 'Alejandra'	['question_type_global', 'question_single_statement']
create a new [meeting]
which people attended meetings late	'Alverta', 'Alejandra'	['question_type_global', 'question_single_statement']
[Gabrielle] will attend [the event]
[that meeting] is [about homework grading]
[Alverta] will attend [the event]
Who is attending [the meeting]	'Alverta', 'Gabrielle'	['question_type_local']
which professors are my friends?	'Lucy'	['question_type_global', 'question_two_hop_statement']
[that student] attended [the event] on time
[Alejandra] will attend [the meeting]
Which university is [Alejandra] affiliated with?	'Hudson University'	['question_type_local']
who attended [to prepare for exams]	'Lucy', 'Alverta', 'Hanna', 'Alejandra'	['question_type_global', 'question_single_statement']
were any people affiliated with [Groff Community College] in attendance to [to prepare for exams]	'Alverta'	['question_type_global', 'question_two_hop_statement']
Who was late to [the meeting to prepare for exams]	'Alverta', 'Alejandra'	['question_type_local']
were any students affiliated with [Groff Community College] attended [to prepare for exams]	'Alverta'	['question_type_global', 'question_three_hop_statement']
which students majoring in [history] were late	'Alverta', 'Alejandra'	['question_type_global', 'question_two_hop_statement']
Who is attending [that meeting]	'Alverta', 'Gabrielle', 'Alejandra'	['question_type_local']
which professors are my friends?	'Lucy'	['question_type_global', 'question_two_hop_statement']
which students majoring in [history] attended meetings	'Alverta', 'Alejandra'	['question_type_global', 'question_two_hop_statement']
create a new [meeting]
[that meeting] is [to practice presentations]
[Alverta] will attend [that meeting]
create a new [meeting]
[Gabrielle] attended [the event about homework grading that was last added] on time
Which university is [Alverta] affiliated with?	'Groff Community College'	['question_type_local']
who are my friends?	'Lucy', 'Gabrielle', 'Alejandra'	['question_type_global', 'question_single_statement']
which people affiliated with [Hillman College] attended [to prepare for exams]	'Lucy'	['question_type_global', 'question_two_hop_statement']
[Lucy] is not my friend
What is [Gabrielle]'s affiliation?	'Hillman College'	['question_type_local']
which students are my friends?	'Alejandra'	['question_type_global', 'question_two_hop_statement']
create a new [meeting]
[Hanna] will attend [the meeting]
Who is attending [that meeting]	'Hanna'	['question_type_local']
which students attended meetings late	'Alverta', 'Alejandra'	['question_type_global', 'question_two_hop_statement']
[she] attended [the event] late
create a new [meeting]
actually [she] is my friend
[this professor] will attend [the meeting with Alverta to practice presentations]
create a new [meeting]
there is a [meeting] [to practice presentations]
which students majoring in [history] attended meetings	'Alverta', 'Alejandra'	['question_type_global', 'question_two_hop_statement']
create a new [meeting]
create a new [meeting]
there is a [meeting] [about homework grading]
were any students affiliated with [Hudson University] late to any meetings	'Alejandra'	['question_type_global', 'question_three_hop_statement']
who are my friends?	'Gabrielle', 'Hanna', 'Alejandra'	['question_type_global', 'question_single_statement']
which people attended meetings late	'Alverta', 'Hanna', 'Alejandra'	['question_type_global', 'question_single_statement']
was anyone affiliated with [Groff Community College] late to any meetings	'Alverta'	['question_type_global', 'question_two_hop_statement']
[Emma] will attend [the meeting that was last added]
Who is attending [that meeting]	'Emma'	['question_type_local']
which students are majoring in [history]	'Alverta', 'Alejandra'	['question_type_global', 'question_single_statement']
[Hanna] will attend [this meeting]
who attended [about homework grading]	'Alverta', 'Gabrielle', 'Hanna', 'Emma', 'Alejandra'	['question_type_global', 'question_single_statement']
What is [Gabrielle]'s email	"I don't know"	['question_type_local']
which people are affiliated with [Hearst College]	'Hanna'	['question_type_global', 'question_single_statement']
which people attended meetings late	'Alverta', 'Hanna', 'Alejandra'	['question_type_global', 'question_single_statement']
there is a [meeting] [to practice presentations]
[she] will attend [this meeting]
[that person] attended [this meeting] on time
What is [that professor]'s affiliation?	'Hearst College'	['question_type_local']
Who is attending [the event to prepare for exams]	'Lucy', 'Alverta', 'Hanna', 'Alejandra'	['question_type_local']
were any [history] majors attending the meetings?	'Alverta', 'Alejandra'	['question_type_global', 'question_two_hop_statement']
[Alverta] will attend [that meeting]
Who is attending [this meeting]	'Alverta', 'Hanna'	['question_type_local']
were any professors affiliated with [Hearst College] in attendance to [to practice presentations]	'Hanna'	['question_type_global', 'question_three_hop_statement']
create a new [meeting]
was anyone who majored in [history] in attendance?	'Alverta', 'Alejandra'	['question_type_global', 'question_two_hop_statement']
were any people affiliated with [Hudson University] late	'Alejandra'	['question_type_global', 'question_two_hop_statement']
[Lucy] will attend [the meeting with Gabrielle that was last added]
[Alejandra] attended [that meeting] late
Who is attending [that meeting]	'Lucy', 'Alverta', 'Gabrielle', 'Alejandra'	['question_type_local']
who was late to [about homework grading]	'Alejandra'	['question_type_global', 'question_two_hop_statement']
was anyone affiliated with [Hudson University] attended [about homework grading]	'Alejandra'	['question_type_global', 'question_two_hop_statement']
who are my friends?	'Gabrielle', 'Hanna', 'Alejandra'	['question_type_global', 'question_single_statement']
What is [Alejandra]'s major	'history'	['question_type_local']
there is a [meeting] [about homework grading]
Change major of [that person] to [communication]
[Gabrielle] will attend [the meeting]
[Gabrielle] attended [this meeting] on time
Who is attending [that meeting]	'Gabrielle'	['question_type_local']
which students are my friends?	'Alejandra'	['question_type_global', 'question_two_hop_statement']
[Alejandra] will attend [this meeting]
Who is attending [the event]	'Gabrielle', 'Alejandra'	['question_type_local']
who attended [to prepare for exams]	'Lucy', 'Alverta', 'Hanna', 'Alejandra'	['question_type_global', 'question_single_statement']
which people attended meetings late	'Alverta', 'Hanna', 'Alejandra'	['question_type_global', 'question_single_statement']
Who is attending [the event to prepare for exams with Alverta]	'Lucy', 'Alverta', 'Hanna', 'Alejandra'	['question_type_local']
[Alverta] will attend [the event]
who attended [about homework grading]	'Lucy', 'Alverta', 'Gabrielle', 'Hanna', 'Emma', 'Alejandra'	['question_type_global', 'question_single_statement']
which people are affiliated with [Groff Community College]	'Alverta'	['question_type_global', 'question_single_statement']
which students are my friends?	'Alejandra'	['question_type_global', 'question_two_hop_statement']
Who is attending [the meeting to prepare for exams with Hanna]	'Lucy', 'Alverta', 'Hanna', 'Alejandra'	['question_type_local']
which students are majoring in [history]	'Alverta'	['question_type_global', 'question_single_statement']
[Emma] will attend [the event to practice presentations that was last added]
[Alejandra] is not my friend
Which university is [this student] affiliated with?	'Hudson University'	['question_type_local']
who attended [to prepare for exams]	'Lucy', 'Alverta', 'Hanna', 'Alejandra'	['question_type_global', 'question_single_statement']
which students majoring in [history] were late	'Alverta'	['question_type_global', 'question_two_hop_statement']
who is affiliated with [Hearst College]	'Hanna'	['question_type_global', 'question_single_statement']
who are my friends?	'Gabrielle', 'Hanna'	['question_type_global', 'question_single_statement']
which people affiliated with [Hearst College] were late	'Hanna'	['question_type_global', 'question_two_hop_statement']
which professors are my friends?	'Hanna'	['question_type_global', 'question_two_hop_statement']
What is [this student]'s major	'communication'	['question_type_local']
create a new [meeting]
Who is attending [the meeting to prepare for exams with Hanna]	'Lucy', 'Alverta', 'Hanna', 'Alejandra'	['question_type_local']
which students attended meetings late	'Alverta', 'Alejandra'	['question_type_global', 'question_two_hop_statement']
were any people affiliated with [Hudson University] late to [to prepare for exams]	'Alejandra'	['question_type_global', 'question_three_hop_statement']
What is [Alejandra]'s major	'communication'	['question_type_local']
actually [she] is my friend
[Gabrielle] will attend [the event]
who attended [to prepare for exams]	'Lucy', 'Alverta', 'Hanna', 'Alejandra'	['question_type_global', 'question_single_statement']
create a new [meeting]
which people attended meetings late	'Alverta', 'Hanna', 'Alejandra'	['question_type_global', 'question_single_statement']
Which university is [Gabrielle] affiliated with?	'Hillman College'	['question_type_local']
was anyone affiliated with [Hudson University] attended [about homework grading]	'Alejandra'	['question_type_global', 'question_two_hop_statement']
was anyone who majored in [communication] ever late to any meetings?	'Alejandra'	['question_type_global', 'question_two_hop_statement']
What is [Gabrielle]'s affiliation?	'Hillman College'	['question_type_local']
were any professors affiliated with [Hillman College] attended [to prepare for exams]	'Lucy'	['question_type_global', 'question_three_hop_statement']
who was late to [to prepare for exams]	'Alverta', 'Alejandra'	['question_type_global', 'question_two_hop_statement']
which people are affiliated with [Hillman College]	'Lucy', 'Gabrielle'	['question_type_global', 'question_single_statement']
were any [communication] majors attending the meetings?	'Alejandra'	['question_type_global', 'question_two_hop_statement']
who is majoring in [communication]	'Alejandra'	['question_type_global', 'question_single_statement']
which students are my friends?	'Alejandra'	['question_type_global', 'question_two_hop_statement']
[this meeting] is [about homework grading]
who attended [about homework grading]	'Lucy', 'Alverta', 'Gabrielle', 'Hanna', 'Emma', 'Alejandra'	['question_type_global', 'question_single_statement']
were any [history] majors ever late?	'Alverta'	['question_type_global', 'question_two_hop_statement']
who are my friends?	'Gabrielle', 'Hanna', 'Alejandra'	['question_type_global', 'question_single_statement']
was anyone who majored in [communication] ever late to any meetings?	'Alejandra'	['question_type_global', 'question_two_hop_statement']
were any students affiliated with [Groff Community College] late to any meetings	'Alverta'	['question_type_global', 'question_three_hop_statement']
which students attended meetings late	'Alverta', 'Alejandra'	['question_type_global', 'question_two_hop_statement']
[Hanna] will attend [that meeting]
[Hanna] attended [the event] on time
[Alejandra] is not my friend
who is affiliated with [Groff Community College]	'Alverta'	['question_type_global', 'question_single_statement']
who attended [to practice presentations]	'Alverta', 'Hanna', 'Emma'	['question_type_global', 'question_single_statement']
actually [Lucy] is my friend
What is [this professor]'s affiliation?	'Hillman College'	['question_type_local']
who are my friends?	'Lucy', 'Gabrielle', 'Hanna'	['question_type_global', 'question_single_statement']
Which university is [that student] affiliated with?	'Hudson University'	['question_type_local']
who attended [to prepare for exams]	'Lucy', 'Alverta', 'Hanna', 'Alejandra'	['question_type_global', 'question_single_statement']
which people affiliated with [Hillman College] attended [to prepare for exams]	'Lucy'	['question_type_global', 'question_two_hop_statement']
which professors are my friends?	'Lucy', 'Hanna'	['question_type_global', 'question_two_hop_statement']
What is [Alverta]'s major	'history'	['question_type_local']
who is affiliated with [Hearst College]	'Hanna'	['question_type_global', 'question_single_statement']
was anyone affiliated with [Groff Community College] late to any meetings	'Alverta'	['question_type_global', 'question_two_hop_statement']
[this professor] will attend [the meeting to practice presentations that was last added]
Who is attending [that meeting]	'Lucy', 'Alverta', 'Hanna', 'Emma'	['question_type_local']
which students attended meetings late	'Alverta', 'Alejandra'	['question_type_global', 'question_two_hop_statement']
who attended [to practice presentations]	'Lucy', 'Alverta', 'Hanna', 'Emma'	['question_type_global', 'question_single_statement']
who is majoring in [communication]	'Alejandra'	['question_type_global', 'question_single_statement']
[Emma] attended [the event about homework grading with Emma and Hanna] late
[Alverta] will attend [the event]
Who was late to [that meeting]	'Emma'	['question_type_local']
which students affiliated with [Hudson University] were late	'Alejandra'	['question_type_global', 'question_three_hop_statement']
were any [communication] majors ever late?	'Alejandra'	['question_type_global', 'question_two_hop_statement']
Who is attending [that meeting]	'Alverta', 'Hanna', 'Emma'	['question_type_local']
which professors are my friends?	'Lucy', 'Hanna'	['question_type_global', 'question_two_hop_statement']
who is affiliated with [Groff Community College]	'Alverta'	['question_type_global', 'question_single_statement']
who attended [to practice presentations]	'Lucy', 'Alverta', 'Hanna', 'Emma'	['question_type_global', 'question_single_statement']
which students attended meetings late	'Alverta', 'Alejandra'	['question_type_global', 'question_two_hop_statement']
which students affiliated with [Hudson University] were late	'Alejandra'	['question_type_global', 'question_three_hop_statement']
[that student] attended [the meeting] late
[Gabrielle] will attend [that meeting]
Who was late to [that meeting]	'Alverta', 'Emma'	['question_type_local']
which professors are my friends?	'Lucy', 'Hanna'	['question_type_global', 'question_two_hop_statement']
there is a [meeting] [to practice presentations]
who are my professor friends?	'Lucy', 'Hanna'	['question_type_global', 'question_two_hop_statement']
were any students affiliated with [Groff Community College] in attendance to [to prepare for exams]	'Alverta'	['question_type_global', 'question_three_hop_statement']
was anyone affiliated with [Groff Community College] attended [to prepare for exams]	'Alverta'	['question_type_global', 'question_two_hop_statement']
who attended [to practice presentations]	'Lucy', 'Alverta', 'Hanna', 'Emma'	['question_type_global', 'question_single_statement']
were any people affiliated with [Groff Community College] late to [about homework grading]	'Alverta'	['question_type_global', 'question_three_hop_statement']
who is majoring in [communication]	'Alejandra'	['question_type_global', 'question_single_statement']
which students majoring in [history] were late	'Alverta'	['question_type_global', 'question_two_hop_statement']
[Hanna] attended [the event about homework grading with Hanna and Emma] on time
Who is attending [the meeting to practice presentations with Hanna that was last added]	'Lucy', 'Alverta', 'Hanna', 'Emma'	['question_type_local']
which students affiliated with [Groff Community College] attended [to prepare for exams]	'Alverta'	['question_type_global', 'question_three_hop_statement']
was anyone who majored in [history] ever late to any meetings?	'Alverta'	['question_type_global', 'question_two_hop_statement']
who are my friends?	'Lucy', 'Gabrielle', 'Hanna'	['question_type_global', 'question_single_statement']
was anyone who majored in [communication] ever late to any meetings?	'Alejandra'	['question_type_global', 'question_two_hop_statement']
there is a [meeting] [to practice presentations]
[Alverta] will attend [that meeting]
[Alverta] attended [that meeting] late
Who was late to [the meeting]	'Alverta'	['question_type_local']
which students attended meetings late	'Alverta', 'Alejandra'	['question_type_global', 'question_two_hop_statement']
[Emma] will attend [this meeting]
[this professor] attended [the event] late
