[Roslyn] is a [person]
[Michael] is a [professor]
there is a [student] named [Racquel]
[that professor]'s email is [Michael@yahoo.com]
[she] is not a friend
[that student]'s affiliation is [Hillman College]
[this person]'s email is [Racquel@yahoo.com]
[Roslyn]'s email is [Roslyn@yahoo.com]
[Roslyn] is not a friend
there is a [person] named [Lucio]
[Lucio]'s email is [Lucio@yahoo.com]
[Lucio]'s affiliation is [Huxley University]
[this person] is not a friend
Which university is [Lucio] affiliated with?	'Huxley University'	['question_type_local']
create a new [meeting]
What is [that person]'s email	'Lucio@yahoo.com'	['question_type_local']
What is [this person]'s affiliation?	'Huxley University'	['question_type_local']
What is [Lucio]'s affiliation?	'Huxley University'	['question_type_local']
[Racquel] will attend [the event]
What is [that person]'s email	'Racquel@yahoo.com'	['question_type_local']
who is affiliated with [Hillman College]	'Racquel'	['question_type_global', 'question_single_statement']
What is [this person]'s affiliation?	'Hillman College'	['question_type_local']
[Michael]'s affiliation is [Hillman College]
[he] is not a friend
What is [Michael]'s email	'Michael@yahoo.com'	['question_type_local']
[Roslyn]'s affiliation is [Hillman College]
Which university is [she] affiliated with?	'Hillman College'	['question_type_local']
[Luanna] is a [person]
[Luanna]'s email is [Luanna@nh.edu]
[that person]'s affiliation is [Hearst College]
[that person] is a friend
What is [that person]'s email	'Luanna@nh.edu'	['question_type_local']
What is [Lucio]'s affiliation?	'Huxley University'	['question_type_local']
[Alejandra] is a [person]
What is [Luanna]'s email	'Luanna@nh.edu'	['question_type_local']
which people are affiliated with [Hillman College]	'Roslyn', 'Michael', 'Racquel'	['question_type_global', 'question_single_statement']
[Michael] will attend [the meeting]
who are my friends?	'Luanna'	['question_type_global', 'question_single_statement']
who is affiliated with [Hearst College]	'Luanna'	['question_type_global', 'question_single_statement']
[this professor]'s department is [english]
What is [that professor]'s email	'Michael@yahoo.com'	['question_type_local']
change [Michael]'s department to [mechanical engineering]
there is a [person] named [William]
[William] is a friend
who is in the [mechanical engineering] department	'Michael'	['question_type_global', 'question_single_statement']
[this person]'s email is [William@yale.edu]
[this person]'s affiliation is [Hudson University]
Which university is [he] affiliated with?	'Hudson University'	['question_type_local']
there is a [student] named [Danita]
What is [he]'s email	'William@yale.edu'	['question_type_local']
[this student] is not a friend
[Danita]'s email is [Danita@msn.com]
[this person]'s major is [communication]
actually [that person] is my friend
[this person]'s affiliation is [Hillman College]
What is [Danita]'s affiliation?	'Hillman College'	['question_type_local']
create a new [meeting]
[Racquel]'s major is [electrical engineering]
Which university is [that person] affiliated with?	'Hillman College'	['question_type_local']
What is [this person]'s email	'Racquel@yahoo.com'	['question_type_local']
who is majoring in [communication]	'Danita'	['question_type_global', 'question_single_statement']
What is [Roslyn]'s email	'Roslyn@yahoo.com'	['question_type_local']
which students are my friends?	'Danita'	['question_type_global', 'question_two_hop_statement']
there is a [meeting] [about homework grading]
[Roslyn] will attend [this meeting]
[this person] attended [that meeting] on time
What is [Luanna]'s email	'Luanna@nh.edu'	['question_type_local']
who are my friends?	'Luanna', 'William', 'Danita'	['question_type_global', 'question_single_statement']
[Luanna] will attend [this meeting]
Which university is [Lucio] affiliated with?	'Huxley University'	['question_type_local']
What is [Racquel]'s email	'Racquel@yahoo.com'	['question_type_local']
which students are majoring in [communication]	'Danita'	['question_type_global', 'question_single_statement']
[Lucio] will attend [this meeting]
who is majoring in [communication]	'Danita'	['question_type_global', 'question_single_statement']
Which university is [he] affiliated with?	'Huxley University'	['question_type_local']
which students are my friends?	'Danita'	['question_type_global', 'question_two_hop_statement']
What is [this person]'s affiliation?	'Huxley University'	['question_type_local']
What is [Racquel]'s affiliation?	'Hillman College'	['question_type_local']
What is [Racquel]'s major	'electrical engineering'	['question_type_local']
[Alejandra] is not a friend
[she]'s email is [Alejandra@gmail.com]
who is majoring in [electrical engineering]	'Racquel'	['question_type_global', 'question_single_statement']
What is [that person]'s email	'Alejandra@gmail.com'	['question_type_local']
who is affiliated with [Hillman College]	'Roslyn', 'Michael', 'Racquel', 'Danita'	['question_type_global', 'question_single_statement']
there is a [meeting] [to practice presentations]
What is [this person]'s email	'Alejandra@gmail.com'	['question_type_local']
which people are in the [mechanical engineering] department	'Michael'	['question_type_global', 'question_single_statement']
[that person]'s affiliation is [Hearst College]
What is [Lucio]'s email	'Lucio@yahoo.com'	['question_type_local']
What is [Michael]'s email	'Michael@yahoo.com'	['question_type_local']
who is affiliated with [Hudson University]	'William'	['question_type_global', 'question_single_statement']
Which university is [this person] affiliated with?	'Hearst College'	['question_type_local']
which students are my friends?	'Danita'	['question_type_global', 'question_two_hop_statement']
[William] will attend [the meeting]
[the meeting] now is [about homework grading]
[that person] attended [the meeting] late
[Roslyn] will attend [the meeting]
Who is attending [that meeting]	'Roslyn', 'William'	['question_type_local']
which people are affiliated with [Hudson University]	'William'	['question_type_global', 'question_single_statement']
Which university is [Racquel] affiliated with?	'Hillman College'	['question_type_local']
which people attended meetings late	'William'	['question_type_global', 'question_single_statement']
create a new [meeting]
create a new [meeting]
What is [Alejandra]'s affiliation?	'Hearst College'	['question_type_local']
What is [Danita]'s affiliation?	'Hillman College'	['question_type_local']
there is a [meeting] [about homework grading]
[Danita] will attend [the event about homework grading that was last added]
Who is attending [that meeting]	'Danita'	['question_type_local']
which students are my friends?	'Danita'	['question_type_global', 'question_two_hop_statement']
What is [that person]'s email	'Danita@msn.com'	['question_type_local']
What is [that student]'s major	'communication'	['question_type_local']
[Danita] attended [this meeting] on time
[Lucio] will attend [this meeting]
[this person] attended [that meeting] on time
were any [communication] majors attending the meetings?	'Danita'	['question_type_global', 'question_two_hop_statement']
[Michael] will attend [the meeting]
What is [that professor]'s email	'Michael@yahoo.com'	['question_type_local']
which people attended meetings late	'William'	['question_type_global', 'question_single_statement']
who is in the [mechanical engineering] department	'Michael'	['question_type_global', 'question_single_statement']
which students are my friends?	'Danita'	['question_type_global', 'question_two_hop_statement']
[Alejandra] will attend [that meeting]
Who is attending [this meeting]	'Michael', 'Lucio', 'Alejandra', 'Danita'	['question_type_local']
which people are in the [mechanical engineering] department	'Michael'	['question_type_global', 'question_single_statement']
Which university is [Alejandra] affiliated with?	'Hearst College'	['question_type_local']
What is [William]'s email	'William@yale.edu'	['question_type_local']
who is affiliated with [Hearst College]	'Luanna', 'Alejandra'	['question_type_global', 'question_single_statement']
which people attended meetings late	'William'	['question_type_global', 'question_single_statement']
What is [Lucio]'s affiliation?	'Huxley University'	['question_type_local']
which students majoring in [communication] attended meetings	'Danita'	['question_type_global', 'question_two_hop_statement']
What is [Danita]'s major	'communication'	['question_type_local']
was anyone who majored in [communication] in attendance?	'Danita'	['question_type_global', 'question_two_hop_statement']
who are my friends?	'Luanna', 'William', 'Danita'	['question_type_global', 'question_single_statement']
which students are my friends?	'Danita'	['question_type_global', 'question_two_hop_statement']
there is a [meeting] [to practice presentations]
which students are majoring in [communication]	'Danita'	['question_type_global', 'question_single_statement']
What is [Alejandra]'s affiliation?	'Hearst College'	['question_type_local']
What is [Alejandra]'s email	'Alejandra@gmail.com'	['question_type_local']
who attended [about homework grading] late	'William'	['question_type_global', 'question_two_hop_statement']
who is affiliated with [Hillman College]	'Roslyn', 'Michael', 'Racquel', 'Danita'	['question_type_global', 'question_single_statement']
What is [that person]'s affiliation?	'Hearst College'	['question_type_local']
[Racquel] will attend [the event]
which students majoring in [communication] attended meetings	'Danita'	['question_type_global', 'question_two_hop_statement']
which students are my friends?	'Danita'	['question_type_global', 'question_two_hop_statement']
which people attended meetings late	'William'	['question_type_global', 'question_single_statement']
[William] will attend [that meeting]
Who is attending [that meeting]	'Racquel', 'William'	['question_type_local']
Which university is [William] affiliated with?	'Hudson University'	['question_type_local']
who are my friends?	'Luanna', 'William', 'Danita'	['question_type_global', 'question_single_statement']
who is majoring in [communication]	'Danita'	['question_type_global', 'question_single_statement']
who attended [to practice presentations]	'Racquel', 'William'	['question_type_global', 'question_single_statement']
[this person] attended [this meeting] late
[Michael] will attend [this meeting]
[Racquel] attended [that meeting] late
there is a [meeting] [about homework grading]
What is [she]'s major	'electrical engineering'	['question_type_local']
which people attended meetings late	'Racquel', 'William'	['question_type_global', 'question_single_statement']
which students are my friends?	'Danita'	['question_type_global', 'question_two_hop_statement']
[Lucio] will attend [that meeting]
[he] attended [that meeting] late
create a new [meeting]
[Roslyn] will attend [that meeting]
[Roslyn] attended [the event] late
Who is attending [the meeting]	'Roslyn'	['question_type_local']
who are my friends?	'Luanna', 'William', 'Danita'	['question_type_global', 'question_single_statement']
[that meeting] is [to practice presentations]
[William] will attend [the event]
there is a [meeting] [to practice presentations]
What is [Lucio]'s email	'Lucio@yahoo.com'	['question_type_local']
which people affiliated with [Hudson University] were late	'William'	['question_type_global', 'question_two_hop_statement']
which students are majoring in [communication]	'Danita'	['question_type_global', 'question_single_statement']
were any [electrical engineering] majors attending the meetings?	'Racquel'	['question_type_global', 'question_two_hop_statement']
What is [that person]'s email	'William@yale.edu'	['question_type_local']
which professors are affiliated with the [mechanical engineering] department	'Michael'	['question_type_global', 'question_single_statement']
who are my friends?	'Luanna', 'William', 'Danita'	['question_type_global', 'question_single_statement']
What is [Racquel]'s major	'electrical engineering'	['question_type_local']
which students attended meetings late	'Racquel'	['question_type_global', 'question_two_hop_statement']
who was late to [about homework grading]	'Lucio', 'William'	['question_type_global', 'question_two_hop_statement']
which people are affiliated with [Hillman College]	'Roslyn', 'Michael', 'Racquel', 'Danita'	['question_type_global', 'question_single_statement']
were any people affiliated with [Hudson University] in attendance to [about homework grading]	'William'	['question_type_global', 'question_two_hop_statement']
What is [William]'s affiliation?	'Hudson University'	['question_type_local']
[Danita] will attend [the meeting]
[that student] attended [that meeting] on time
which students affiliated with [Hillman College] attended [to practice presentations]	'Racquel', 'Danita'	['question_type_global', 'question_three_hop_statement']
were any people affiliated with [Hillman College] in attendance to [about homework grading]	'Roslyn', 'Danita'	['question_type_global', 'question_two_hop_statement']
was anyone affiliated with [Huxley University] attended [about homework grading]	'Lucio'	['question_type_global', 'question_two_hop_statement']
create a new [meeting]
there is a [meeting] [to prepare for exams]
[Racquel] will attend [the meeting to prepare for exams]
What is [that student]'s email	'Racquel@yahoo.com'	['question_type_local']
who are my friends?	'Luanna', 'William', 'Danita'	['question_type_global', 'question_single_statement']
[Alejandra] will attend [this meeting]
[Luanna] will attend [that meeting]
[Alejandra] attended [that meeting] late
[Roslyn] will attend [the meeting]
[this person] attended [that meeting] late
Who was late to [the event]	'Roslyn', 'Alejandra'	['question_type_local']
create a new [meeting]
[that person] will attend [the meeting]
which professors are affiliated with the [mechanical engineering] department	'Michael'	['question_type_global', 'question_single_statement']
[she] attended [that meeting] late
[Luanna] will attend [that meeting]
[the meeting] is [about homework grading]
create a new [meeting]
Who was late to [the meeting about homework grading with Roslyn that was last added]	'Roslyn'	['question_type_local']
What is [Luanna]'s email	'Luanna@nh.edu'	['question_type_local']
which students are majoring in [electrical engineering]	'Racquel'	['question_type_global', 'question_single_statement']
who is affiliated with [Hillman College]	'Roslyn', 'Michael', 'Racquel', 'Danita'	['question_type_global', 'question_single_statement']
were any people affiliated with [Hudson University] late to [to practice presentations]	'William'	['question_type_global', 'question_three_hop_statement']
was anyone affiliated with [Hillman College] late to [about homework grading]	'Roslyn'	['question_type_global', 'question_three_hop_statement']
which students are my friends?	'Danita'	['question_type_global', 'question_two_hop_statement']
[Racquel] will attend [the meeting about homework grading with Roslyn that was last added]
[Alejandra] will attend [the event with William and Roslyn about homework grading]
[Roslyn] attended [this meeting] late
Which university is [Roslyn] affiliated with?	'Hillman College'	['question_type_local']
which people are affiliated with [Hillman College]	'Roslyn', 'Michael', 'Racquel', 'Danita'	['question_type_global', 'question_single_statement']
[William] will attend [the event about homework grading with Luanna and Roslyn that was last added]
Who is attending [this meeting]	'Roslyn', 'Racquel', 'Luanna', 'William'	['question_type_local']
which professors are affiliated with the [mechanical engineering] department	'Michael'	['question_type_global', 'question_single_statement']
who attended [to prepare for exams]	'Roslyn', 'Racquel', 'Luanna', 'Alejandra'	['question_type_global', 'question_single_statement']
were any people affiliated with [Hillman College] late to [to practice presentations]	'Roslyn', 'Racquel'	['question_type_global', 'question_three_hop_statement']
[Racquel] attended [that meeting] on time
which people attended meetings late	'Roslyn', 'Racquel', 'Lucio', 'Alejandra', 'William'	['question_type_global', 'question_single_statement']
Who was late to [that meeting]	'Roslyn'	['question_type_local']
which students are my friends?	'Danita'	['question_type_global', 'question_two_hop_statement']
were any people affiliated with [Hudson University] late to [about homework grading]	'William'	['question_type_global', 'question_three_hop_statement']
create a new [meeting]
What is [this person]'s email	'Racquel@yahoo.com'	['question_type_local']
which students attended meetings late	'Racquel'	['question_type_global', 'question_two_hop_statement']
who attended [about homework grading]	'Roslyn', 'Michael', 'Racquel', 'Lucio', 'Luanna', 'Alejandra', 'William', 'Danita'	['question_type_global', 'question_single_statement']
which people affiliated with [Hillman College] attended [to prepare for exams]	'Roslyn'	['question_type_global', 'question_two_hop_statement']
What is [Alejandra]'s email	'Alejandra@gmail.com'	['question_type_local']
who is majoring in [electrical engineering]	'Racquel'	['question_type_global', 'question_single_statement']
which people affiliated with [Hudson University] attended [to practice presentations]	'William'	['question_type_global', 'question_two_hop_statement']
there is a [meeting] [to prepare for exams]
[the event about homework grading that was last added] now is [to practice presentations]
[Luanna] attended [the meeting with Luanna that was last added] late
