there is a [meeting] [to practice presentations]
[the event] now is [to prepare for exams]
[Igor] is a [student]
[Igor]'s affiliation is [Hudson University]
What is [that person]'s affiliation?	'Hudson University'	['question_type_local']
Which university is [this student] affiliated with?	'Hudson University'	['question_type_local']
[Lucy] is a [person]
[that student]'s email is [Igor@yahoo.com]
[Luanna] is a [professor]
[he] is a friend
[Igor]'s major is [computer science]
What is [this person]'s email	'Igor@yahoo.com'	['question_type_local']
create a [professor] named [Kristeen]
which students are my friends?	'Igor'	['question_type_global', 'question_two_hop_statement']
[Kristeen] is a friend
there is a [meeting] [to discuss future plans]
[this professor] will attend [the event]
[Lucy] will attend [the meeting]
create a [professor] named [Emma]
create a [person] named [Gabrielle]
[Gabrielle]'s email is [Gabrielle@harvard.edu]
[Gabrielle] is not a friend
[Kristeen] will attend [the meeting to prepare for exams]
there is a [meeting] [to discuss future plans]
[the meeting to prepare for exams with Kristeen] now is [to practice presentations]
who are my professor friends?	'Kristeen'	['question_type_global', 'question_two_hop_statement']
[Luanna] will attend [the event with Kristeen to practice presentations]
who is majoring in [computer science]	'Igor'	['question_type_global', 'question_single_statement']
[this person]'s email is [Luanna@yandex.com]
[that professor]'s affiliation is [Blue Mountain State]
[Luanna] is not a friend
[Igor] will attend [the event to practice presentations]
who is affiliated with [Blue Mountain State]	'Luanna'	['question_type_global', 'question_single_statement']
[Lucy] will attend [the event]
Who is attending [this meeting]	'Igor', 'Lucy', 'Luanna', 'Kristeen'	['question_type_local']
[she]'s email is [Lucy@yale.edu]
[this person]'s affiliation is [Hudson University]
[that person] is not a friend
What is [Lucy]'s email	'Lucy@yale.edu'	['question_type_local']
which students are majoring in [computer science]	'Igor'	['question_type_global', 'question_single_statement']
Who is attending [the event to practice presentations]	'Igor', 'Lucy', 'Luanna', 'Kristeen'	['question_type_local']
which students are my friends?	'Igor'	['question_type_global', 'question_two_hop_statement']
actually [that person] is my friend
Which university is [Lucy] affiliated with?	'Hudson University'	['question_type_local']
which professors are my friends?	'Kristeen'	['question_type_global', 'question_two_hop_statement']
create a new [meeting]
there is a [meeting] [to discuss future plans]
[Luanna] will attend [the event to discuss future plans that was last added]
Who is attending [the event]	'Luanna'	['question_type_local']
What is [Lucy]'s email	'Lucy@yale.edu'	['question_type_local']
who is affiliated with [Blue Mountain State]	'Luanna'	['question_type_global', 'question_single_statement']
[Lucy] will attend [that meeting]
who is affiliated with [Hudson University]	'Igor', 'Lucy'	['question_type_global', 'question_single_statement']
who are my professor friends?	'Kristeen'	['question_type_global', 'question_two_hop_statement']
who are my friends?	'Igor', 'Lucy', 'Kristeen'	['question_type_global', 'question_single_statement']
create a new [meeting]
Who is attending [the meeting with Luanna and Lucy to practice presentations]	'Igor', 'Lucy', 'Luanna', 'Kristeen'	['question_type_local']
which people are affiliated with [Blue Mountain State]	'Luanna'	['question_type_global', 'question_single_statement']
What is [Lucy]'s email	'Lucy@yale.edu'	['question_type_local']
there is a [meeting] [to practice presentations]
Which university is [Igor] affiliated with?	'Hudson University'	['question_type_local']
which professors are my friends?	'Kristeen'	['question_type_global', 'question_two_hop_statement']
there is a [meeting] [to practice presentations]
[Lucy] will attend [the event that was last added]
Who is attending [this meeting]	'Lucy'	['question_type_local']
who are my professor friends?	'Kristeen'	['question_type_global', 'question_two_hop_statement']
Which university is [that person] affiliated with?	'Hudson University'	['question_type_local']
[Luanna] will attend [that meeting]
[this meeting] now is [to discuss future plans]
Who is attending [the event]	'Lucy', 'Luanna'	['question_type_local']
[Igor] will attend [this meeting]
there is a [meeting] [to prepare for exams]
Change major of [this person] to [english]
What is [that person]'s email	'Igor@yahoo.com'	['question_type_local']
[Kristeen] will attend [this meeting]
[Emma] will attend [this meeting]
[Igor] is not my friend
What is [he]'s email	'Igor@yahoo.com'	['question_type_local']
who attended [to prepare for exams]	'Kristeen', 'Emma'	['question_type_global', 'question_single_statement']
[this professor]'s email is [Emma@cornell.edu]
[this professor]'s affiliation is [Hudson University]
[Emma] is not a friend
who is majoring in [english]	'Igor'	['question_type_global', 'question_single_statement']
there is a [meeting] [to discuss future plans]
What is [Lucy]'s affiliation?	'Hudson University'	['question_type_local']
[this professor] will attend [the meeting]
which students are majoring in [english]	'Igor'	['question_type_global', 'question_single_statement']
create a new [meeting]
[Lucy] will attend [that meeting]
[that meeting] is [to prepare for exams]
Who is attending [that meeting]	'Lucy'	['question_type_local']
Who is attending [this meeting]	'Lucy'	['question_type_local']
What is [Lucy]'s email	'Lucy@yale.edu'	['question_type_local']
[Kristeen] will attend [that meeting]
[Kristeen]'s affiliation is [Hearst College]
[she]'s email is [Kristeen@yandex.com]
[Kristeen] is not my friend
who is majoring in [english]	'Igor'	['question_type_global', 'question_single_statement']
who are my friends?	'Lucy'	['question_type_global', 'question_single_statement']
who attended [to practice presentations]	'Igor', 'Lucy', 'Luanna', 'Kristeen'	['question_type_global', 'question_single_statement']
actually [this professor] is my friend
What is [Kristeen]'s affiliation?	'Hearst College'	['question_type_local']
who is affiliated with [Hearst College]	'Kristeen'	['question_type_global', 'question_single_statement']
create a new [meeting]
[Igor] will attend [that meeting]
who attended [to discuss future plans]	'Igor', 'Lucy', 'Luanna', 'Kristeen', 'Emma'	['question_type_global', 'question_single_statement']
[that meeting] is [to practice presentations]
Who is attending [the meeting]	'Igor'	['question_type_local']
who is majoring in [english]	'Igor'	['question_type_global', 'question_single_statement']
[Lucy] is not my friend
[she] will attend [the meeting with Kristeen and Emma]
[this meeting] now is [to practice presentations]
Who is attending [the meeting]	'Lucy', 'Kristeen', 'Emma'	['question_type_local']
which professors are my friends?	'Kristeen'	['question_type_global', 'question_two_hop_statement']
What is [that person]'s affiliation?	'Hudson University'	['question_type_local']
who are my friends?	'Kristeen'	['question_type_global', 'question_single_statement']
[Luanna] will attend [that meeting]
Who is attending [the event]	'Lucy', 'Luanna', 'Kristeen', 'Emma'	['question_type_local']
which students are majoring in [english]	'Igor'	['question_type_global', 'question_single_statement']
which people are affiliated with [Hearst College]	'Kristeen'	['question_type_global', 'question_single_statement']
who attended [to prepare for exams]	'Lucy', 'Kristeen'	['question_type_global', 'question_single_statement']
create a new [meeting]
who is affiliated with [Hudson University]	'Igor', 'Lucy', 'Emma'	['question_type_global', 'question_single_statement']
[Gabrielle] will attend [this meeting]
create a new [meeting]
[Gabrielle] will attend [the event to discuss future plans with Igor and Lucy]
which professors are my friends?	'Kristeen'	['question_type_global', 'question_two_hop_statement']
Which university is [Igor] affiliated with?	'Hudson University'	['question_type_local']
[this person] will attend [the event to prepare for exams]
What is [Luanna]'s email	'Luanna@yandex.com'	['question_type_local']
which people are affiliated with [Blue Mountain State]	'Luanna'	['question_type_global', 'question_single_statement']
[this meeting] now is [to practice presentations]
who are my friends?	'Kristeen'	['question_type_global', 'question_single_statement']
Who is attending [that meeting]	'Lucy', 'Kristeen', 'Gabrielle'	['question_type_local']
who are my professor friends?	'Kristeen'	['question_type_global', 'question_two_hop_statement']
[Luanna] will attend [that meeting]
[the meeting] now is [to discuss future plans]
create a new [meeting]
there is a [meeting] [to prepare for exams]
who is affiliated with [Hearst College]	'Kristeen'	['question_type_global', 'question_single_statement']
who is majoring in [english]	'Igor'	['question_type_global', 'question_single_statement']
[Gabrielle] will attend [the event with Emma that was last added]
[Kristeen] will attend [this meeting]
there is a [meeting] [to practice presentations]
Who is attending [the event to practice presentations with Lucy that was last added]	'Lucy', 'Luanna', 'Kristeen', 'Emma'	['question_type_local']
which students are majoring in [english]	'Igor'	['question_type_global', 'question_single_statement']
which professors are my friends?	'Kristeen'	['question_type_global', 'question_two_hop_statement']
Who is attending [the event to discuss future plans with Igor]	'Igor', 'Lucy', 'Luanna', 'Gabrielle'	['question_type_local']
What is [that person]'s email	'Kristeen@yandex.com'	['question_type_local']
there is a [meeting] [to prepare for exams]
create a new [meeting]
who are my friends?	'Kristeen'	['question_type_global', 'question_single_statement']
there is a [meeting] [to discuss future plans]
create a new [meeting]
[the event that was last added] is [to practice presentations]
which people are affiliated with [Hudson University]	'Igor', 'Lucy', 'Emma'	['question_type_global', 'question_single_statement']
who is majoring in [english]	'Igor'	['question_type_global', 'question_single_statement']
[Kristeen] will attend [that meeting]
Who is attending [the event]	'Kristeen'	['question_type_local']
create a new [meeting]
Who is attending [the event to practice presentations with Igor and Luanna]	'Igor', 'Lucy', 'Luanna', 'Kristeen'	['question_type_local']
which people are affiliated with [Hearst College]	'Kristeen'	['question_type_global', 'question_single_statement']
[Emma] will attend [the event]
[that meeting] is [to prepare for exams]
Who is attending [that meeting]	'Emma'	['question_type_local']
who are my professor friends?	'Kristeen'	['question_type_global', 'question_two_hop_statement']
which professors are my friends?	'Kristeen'	['question_type_global', 'question_two_hop_statement']
who attended [to prepare for exams]	'Emma'	['question_type_global', 'question_single_statement']
Who is attending [the meeting]	'Emma'	['question_type_local']
which people are affiliated with [Blue Mountain State]	'Luanna'	['question_type_global', 'question_single_statement']
who are my friends?	'Kristeen'	['question_type_global', 'question_single_statement']
Who is attending [the meeting with Luanna and Kristeen that was last added]	'Lucy', 'Luanna', 'Kristeen', 'Gabrielle'	['question_type_local']
which students are majoring in [english]	'Igor'	['question_type_global', 'question_single_statement']
Who is attending [that meeting]	'Emma'	['question_type_local']
who attended [to prepare for exams]	'Emma'	['question_type_global', 'question_single_statement']
[Kristeen] will attend [the meeting to practice presentations with Igor that was last added]
[this meeting] now is [to prepare for exams]
Who is attending [the event with Igor and Lucy to discuss future plans]	'Igor', 'Lucy', 'Luanna', 'Gabrielle'	['question_type_local']
Who is attending [the meeting with Igor to practice presentations]	'Igor', 'Lucy', 'Luanna', 'Kristeen'	['question_type_local']
who is affiliated with [Blue Mountain State]	'Luanna'	['question_type_global', 'question_single_statement']
there is a [meeting] [to practice presentations]
Who is attending [the meeting with Lucy that was last added]	'Lucy', 'Luanna', 'Kristeen', 'Gabrielle'	['question_type_local']
who are my professor friends?	'Kristeen'	['question_type_global', 'question_two_hop_statement']
[Luanna] will attend [the meeting to practice presentations that was last added]
[this meeting] now is [to discuss future plans]
[Kristeen] will attend [the meeting]
What is [that person]'s affiliation?	'Hearst College'	['question_type_local']
[Luanna] will attend [the meeting to prepare for exams that was last added]
[Gabrielle] will attend [the meeting with Igor that was last added]
[she]'s affiliation is [Harrison University]
What is [that person]'s affiliation?	'Harrison University'	['question_type_local']
there is a [meeting] [to practice presentations]
Which university is [she] affiliated with?	'Harrison University'	['question_type_local']
What is [Gabrielle]'s email	'Gabrielle@harvard.edu'	['question_type_local']
which professors are my friends?	'Kristeen'	['question_type_global', 'question_two_hop_statement']
[Kristeen] will attend [the event]
Who is attending [the meeting]	'Kristeen'	['question_type_local']
who is affiliated with [Harrison University]	'Gabrielle'	['question_type_global', 'question_single_statement']
who attended [to prepare for exams]	'Igor', 'Luanna', 'Kristeen', 'Emma', 'Gabrielle'	['question_type_global', 'question_single_statement']
