there is a [professor] named [Zenaida]
[this person]'s department is [electrical engineering]
[that person] is a friend
[Zenaida]'s affiliation is [Harrison University]
Which university is [that person] affiliated with?	'Harrison University'	['question_type_local']
[John] is a [person]
[he]'s affiliation is [Harrison University]
[he] is not a friend
What is [this person]'s affiliation?	'Harrison University'	['question_type_local']
who are my professor friends?	'Zenaida'	['question_type_global', 'question_two_hop_statement']
[Tawnya] is a [student]
there is a [professor] named [Isaiah]
[she] is a friend
[she]'s affiliation is [Harrison University]
[this student]'s major is [engineering]
Which university is [she] affiliated with?	'Harrison University'	['question_type_local']
who is affiliated with [Harrison University]	'Zenaida', 'John', 'Tawnya'	['question_type_global', 'question_single_statement']
What is [Tawnya]'s major	'engineering'	['question_type_local']
Which university is [John] affiliated with?	'Harrison University'	['question_type_local']
which students are majoring in [engineering]	'Tawnya'	['question_type_global', 'question_single_statement']
Which university is [this person] affiliated with?	'Harrison University'	['question_type_local']
[Roslyn] is a [student]
[Zenaida] is not my friend
Which university is [this professor] affiliated with?	'Harrison University'	['question_type_local']
What is [Zenaida]'s affiliation?	'Harrison University'	['question_type_local']
who are my friends?	'Tawnya'	['question_type_global', 'question_single_statement']
[Roslyn]'s major is [economics]
[that student]'s affiliation is [Springfield University]
[this student] is a friend
which students are my friends?	'Tawnya', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
What is [this student]'s major	'economics'	['question_type_local']
which students are majoring in [engineering]	'Tawnya'	['question_type_global', 'question_single_statement']
Change major of [that student] to [computer science]
What is [this person]'s affiliation?	'Springfield University'	['question_type_local']
[that student] is not my friend
create a new [meeting]
Which university is [that person] affiliated with?	'Springfield University'	['question_type_local']
who is affiliated with [Springfield University]	'Roslyn'	['question_type_global', 'question_single_statement']
which professors are affiliated with the [electrical engineering] department	'Zenaida'	['question_type_global', 'question_single_statement']
which students are my friends?	'Tawnya'	['question_type_global', 'question_two_hop_statement']
What is [Zenaida]'s affiliation?	'Harrison University'	['question_type_local']
who are my friends?	'Tawnya'	['question_type_global', 'question_single_statement']
which people are affiliated with [Harrison University]	'Zenaida', 'John', 'Tawnya'	['question_type_global', 'question_single_statement']
create a new [meeting]
What is [Tawnya]'s major	'engineering'	['question_type_local']
who is in the [electrical engineering] department	'Zenaida'	['question_type_global', 'question_single_statement']
[the event that was last added] is [about homework grading]
[Zenaida] will attend [that meeting]
create a new [meeting]
[John] will attend [the meeting]
[this meeting] is [to practice presentations]
Who is attending [this meeting]	'John'	['question_type_local']
Which university is [this person] affiliated with?	'Harrison University'	['question_type_local']
which students are my friends?	'Tawnya'	['question_type_global', 'question_two_hop_statement']
What is [that person]'s affiliation?	'Harrison University'	['question_type_local']
who are my friends?	'Tawnya'	['question_type_global', 'question_single_statement']
there is a [meeting] [to grade papers]
actually [Zenaida] is my friend
What is [that person]'s affiliation?	'Harrison University'	['question_type_local']
[that professor] will attend [this meeting]
[Isaiah] will attend [that meeting]
[Zenaida] attended [this meeting] late
Who was late to [that meeting]	'Zenaida'	['question_type_local']
which people are in the [electrical engineering] department	'Zenaida'	['question_type_global', 'question_single_statement']
[John] will attend [the event]
Who is attending [that meeting]	'Zenaida', 'John', 'Isaiah'	['question_type_local']
were any professors affiliated with [Harrison University] in attendance to [to grade papers]	'Zenaida'	['question_type_global', 'question_three_hop_statement']
which students are majoring in [engineering]	'Tawnya'	['question_type_global', 'question_single_statement']
who attended [about homework grading]	'Zenaida'	['question_type_global', 'question_single_statement']
who attended [to grade papers] late	'Zenaida'	['question_type_global', 'question_two_hop_statement']
there is a [meeting] [to prepare for exams]
who are my friends?	'Zenaida', 'Tawnya'	['question_type_global', 'question_single_statement']
which people are affiliated with [Springfield University]	'Roslyn'	['question_type_global', 'question_single_statement']
who is in the [electrical engineering] department	'Zenaida'	['question_type_global', 'question_single_statement']
Which university is [Zenaida] affiliated with?	'Harrison University'	['question_type_local']
Which university is [John] affiliated with?	'Harrison University'	['question_type_local']
there is a [meeting] [to prepare for exams]
there is a [meeting] [about homework grading]
[Roslyn] will attend [the meeting about homework grading that was last added]
What is [Roslyn]'s affiliation?	'Springfield University'	['question_type_local']
What is [Tawnya]'s major	'engineering'	['question_type_local']
was anyone affiliated with [Harrison University] late to any meetings	'Zenaida'	['question_type_global', 'question_two_hop_statement']
who attended [to practice presentations]	'John'	['question_type_global', 'question_single_statement']
has anyone from the [electrical engineering] department attending meetings late	'Zenaida'	['question_type_global', 'question_two_hop_statement']
which students are majoring in [engineering]	'Tawnya'	['question_type_global', 'question_single_statement']
there is a [meeting] [to practice presentations]
Which university is [that person] affiliated with?	'Springfield University'	['question_type_local']
who is majoring in [engineering]	'Tawnya'	['question_type_global', 'question_single_statement']
What is [that student]'s affiliation?	'Springfield University'	['question_type_local']
who is in the [electrical engineering] department	'Zenaida'	['question_type_global', 'question_single_statement']
[Isaiah]'s department is [electrical engineering]
[this person] is not a friend
[this person]'s affiliation is [Hudson University]
Which university is [he] affiliated with?	'Hudson University'	['question_type_local']
who is affiliated with [Harrison University]	'Zenaida', 'John', 'Tawnya'	['question_type_global', 'question_single_statement']
which people are in the [electrical engineering] department	'Zenaida', 'Isaiah'	['question_type_global', 'question_single_statement']
change [this professor]'s department to [applied physics]
was anyone from the [electrical engineering] department in attendance?	'Zenaida'	['question_type_global', 'question_two_hop_statement']
Which university is [Isaiah] affiliated with?	'Hudson University'	['question_type_local']
which students are my friends?	'Tawnya'	['question_type_global', 'question_two_hop_statement']
Who is attending [the meeting to grade papers]	'Zenaida', 'John', 'Isaiah'	['question_type_local']
[Roslyn] will attend [the meeting to grade papers]
[Roslyn] attended [this meeting] on time
Who was late to [this meeting]	'Zenaida'	['question_type_local']
who is affiliated with [Harrison University]	'Zenaida', 'John', 'Tawnya'	['question_type_global', 'question_single_statement']
which people attended meetings late	'Zenaida'	['question_type_global', 'question_single_statement']
[Tawnya] will attend [the event with Zenaida about homework grading]
[Zenaida] attended [that meeting] on time
Who is attending [the meeting]	'Zenaida', 'Tawnya'	['question_type_local']
there is a [meeting] [to grade papers]
What is [that person]'s affiliation?	'Harrison University'	['question_type_local']
was anyone from the [electrical engineering] department in attendance?	'Zenaida'	['question_type_global', 'question_two_hop_statement']
there is a [meeting] [to practice presentations]
who attended [about homework grading]	'Zenaida', 'Tawnya', 'Roslyn'	['question_type_global', 'question_single_statement']
which students are my friends?	'Tawnya'	['question_type_global', 'question_two_hop_statement']
What is [Roslyn]'s major	'computer science'	['question_type_local']
was anyone who majored in [computer science] in attendance?	'Roslyn'	['question_type_global', 'question_two_hop_statement']
has anyone from the [electrical engineering] department attending meetings late	'Zenaida'	['question_type_global', 'question_two_hop_statement']
[Tawnya] will attend [the event that was last added]
create a new [meeting]
[Roslyn] will attend [the event with Tawnya and Zenaida]
Who is attending [the meeting]	'Zenaida', 'Tawnya', 'Roslyn'	['question_type_local']
who are my professor friends?	'Zenaida'	['question_type_global', 'question_two_hop_statement']
Who is attending [the meeting with Zenaida to grade papers]	'Zenaida', 'John', 'Isaiah', 'Roslyn'	['question_type_local']
[Isaiah] will attend [that meeting]
[he] attended [the meeting] late
who are my friends?	'Zenaida', 'Tawnya'	['question_type_global', 'question_single_statement']
was anyone affiliated with [electrical engineering] attending any meetings late?	'Zenaida'	['question_type_global', 'question_two_hop_statement']
What is [he]'s affiliation?	'Hudson University'	['question_type_local']
who is affiliated with [Hudson University]	'Isaiah'	['question_type_global', 'question_single_statement']
which professors affiliated with [Harrison University] were late	'Zenaida'	['question_type_global', 'question_three_hop_statement']
was anyone affiliated with [electrical engineering] attending the meetings?	'Zenaida'	['question_type_global', 'question_two_hop_statement']
change [Zenaida]'s department to [applied physics]
What department is [he] with?	'applied physics'	['question_type_local']
which people are affiliated with [Springfield University]	'Roslyn'	['question_type_global', 'question_single_statement']
which people [about homework grading] late	'Isaiah'	['question_type_global', 'question_two_hop_statement']
change [she]'s department to [electrical engineering]
Which university is [this professor] affiliated with?	'Harrison University'	['question_type_local']
who is majoring in [computer science]	'Roslyn'	['question_type_global', 'question_single_statement']
who are my friends?	'Zenaida', 'Tawnya'	['question_type_global', 'question_single_statement']
who are my professor friends?	'Zenaida'	['question_type_global', 'question_two_hop_statement']
What is [Isaiah]'s affiliation?	'Hudson University'	['question_type_local']
What department is [Zenaida] affiliated with?	'electrical engineering'	['question_type_local']
who is in the [electrical engineering] department	'Zenaida'	['question_type_global', 'question_single_statement']
which people affiliated with [Harrison University] were late	'Zenaida'	['question_type_global', 'question_two_hop_statement']
who attended [to grade papers] late	'Zenaida'	['question_type_global', 'question_two_hop_statement']
What is [that professor]'s affiliation?	'Harrison University'	['question_type_local']
which people affiliated with [Hudson University] attended [about homework grading]	'Isaiah'	['question_type_global', 'question_two_hop_statement']
who are my friends?	'Zenaida', 'Tawnya'	['question_type_global', 'question_single_statement']
which people are affiliated with [Harrison University]	'Zenaida', 'John', 'Tawnya'	['question_type_global', 'question_single_statement']
What department is [Zenaida] in?	'electrical engineering'	['question_type_local']
who attended [to practice presentations]	'John', 'Tawnya'	['question_type_global', 'question_single_statement']
[this person] is not my friend
What is [Zenaida]'s affiliation?	'Harrison University'	['question_type_local']
What is [that professor]'s affiliation?	'Harrison University'	['question_type_local']
[Tawnya] attended [the meeting with Isaiah and Tawnya about homework grading] on time
which people attended meetings late	'Zenaida', 'Isaiah'	['question_type_global', 'question_single_statement']
[the event with Roslyn and John to grade papers] now is [to practice presentations]
Who is attending [that meeting]	'Zenaida', 'John', 'Isaiah', 'Roslyn'	['question_type_local']
was anyone affiliated with [electrical engineering] attending any meetings late?	'Zenaida'	['question_type_global', 'question_two_hop_statement']
was anyone affiliated with [Hudson University] late to any meetings	'Isaiah'	['question_type_global', 'question_two_hop_statement']
who is in the [applied physics] department	'Isaiah'	['question_type_global', 'question_single_statement']
[Isaiah] attended [this meeting] late
Which university is [that professor] affiliated with?	'Hudson University'	['question_type_local']
who attended [about homework grading]	'Zenaida', 'Tawnya', 'Isaiah', 'Roslyn'	['question_type_global', 'question_single_statement']
was anyone affiliated with [applied physics] attending the meetings?	'Isaiah'	['question_type_global', 'question_two_hop_statement']
[that meeting] now is [to grade papers]
Who was late to [that meeting]	'Zenaida', 'Isaiah'	['question_type_local']
Who is attending [this meeting]	'Zenaida', 'John', 'Isaiah', 'Roslyn'	['question_type_local']
Who is attending [that meeting]	'Zenaida', 'John', 'Isaiah', 'Roslyn'	['question_type_local']
which people are affiliated with [Springfield University]	'Roslyn'	['question_type_global', 'question_single_statement']
Who is attending [the meeting with John to practice presentations]	'John'	['question_type_local']
were any professors affiliated with [Harrison University] late	'Zenaida'	['question_type_global', 'question_three_hop_statement']
who are my friends?	'Tawnya'	['question_type_global', 'question_single_statement']
which people attended meetings late	'Zenaida', 'Isaiah'	['question_type_global', 'question_single_statement']
What is [Zenaida]'s affiliation?	'Harrison University'	['question_type_local']
who is majoring in [computer science]	'Roslyn'	['question_type_global', 'question_single_statement']
Who is attending [that meeting]	'Zenaida', 'John', 'Isaiah', 'Roslyn'	['question_type_local']
Who is attending [this meeting]	'Zenaida', 'John', 'Isaiah', 'Roslyn'	['question_type_local']
which students are my friends?	'Tawnya'	['question_type_global', 'question_two_hop_statement']
[John] attended [the meeting with John to practice presentations] late
has anyone from the [applied physics] department attending meetings	'Isaiah'	['question_type_global', 'question_two_hop_statement']
was anyone from the [applied physics] department in attendance?	'Isaiah'	['question_type_global', 'question_two_hop_statement']
were any students affiliated with [Springfield University] attended [to grade papers]	'Roslyn'	['question_type_global', 'question_three_hop_statement']
Who was late to [the meeting]	'John'	['question_type_local']
who is majoring in [engineering]	'Tawnya'	['question_type_global', 'question_single_statement']
[Isaiah] will attend [that meeting]
Who is attending [this meeting]	'John', 'Isaiah'	['question_type_local']
were any people affiliated with [Hudson University] late	'Isaiah'	['question_type_global', 'question_two_hop_statement']
which people [about homework grading] late	'Isaiah'	['question_type_global', 'question_two_hop_statement']
What is [that person]'s affiliation?	'Hudson University'	['question_type_local']
has anyone from the [electrical engineering] department attending meetings late	'Zenaida'	['question_type_global', 'question_two_hop_statement']
What is [Roslyn]'s major	'computer science'	['question_type_local']
Which university is [he] affiliated with?	'Hudson University'	['question_type_local']
there is a [meeting] [to practice presentations]
which students are my friends?	'Tawnya'	['question_type_global', 'question_two_hop_statement']
create a new [meeting]
which people affiliated with [Hudson University] attended [to grade papers]	'Isaiah'	['question_type_global', 'question_two_hop_statement']
were any professors affiliated with [Hudson University] attended [about homework grading]	'Isaiah'	['question_type_global', 'question_three_hop_statement']
which people attended meetings late	'Zenaida', 'John', 'Isaiah'	['question_type_global', 'question_single_statement']
has anyone from the [electrical engineering] department attending meetings late	'Zenaida'	['question_type_global', 'question_two_hop_statement']
was anyone from the [electrical engineering] department late to meetings?	'Zenaida'	['question_type_global', 'question_two_hop_statement']
which people are affiliated with [Harrison University]	'Zenaida', 'John', 'Tawnya'	['question_type_global', 'question_single_statement']
which people are in the [electrical engineering] department	'Zenaida'	['question_type_global', 'question_single_statement']
was anyone who majored in [computer science] in attendance?	'Roslyn'	['question_type_global', 'question_two_hop_statement']
there is a [meeting] [to practice presentations]
there is a [meeting] [to prepare for exams]
create a new [meeting]
were any professors affiliated with [Harrison University] late to any meetings	'Zenaida'	['question_type_global', 'question_three_hop_statement']
there is a [meeting] [to practice presentations]
actually [Isaiah] is my friend
there is a [meeting] [about homework grading]
Who was late to [the meeting with Tawnya about homework grading]	'Isaiah'	['question_type_local']
which students are my friends?	'Tawnya'	['question_type_global', 'question_two_hop_statement']
was anyone affiliated with [electrical engineering] attending the meetings?	'Zenaida'	['question_type_global', 'question_two_hop_statement']
who attended [to grade papers]	'Zenaida', 'John', 'Isaiah', 'Roslyn'	['question_type_global', 'question_single_statement']
Who is attending [the meeting with Tawnya about homework grading]	'Zenaida', 'Tawnya', 'Isaiah', 'Roslyn'	['question_type_local']
which people affiliated with [Hudson University] were late	'Isaiah'	['question_type_global', 'question_two_hop_statement']
who are my friends?	'Tawnya', 'Isaiah'	['question_type_global', 'question_single_statement']
[Roslyn] will attend [the event]
[she] attended [the meeting] late
Who is attending [that meeting]	'Roslyn'	['question_type_local']
which people affiliated with [Harrison University] were late	'Zenaida', 'John'	['question_type_global', 'question_two_hop_statement']
was anyone from the [electrical engineering] department in attendance?	'Zenaida'	['question_type_global', 'question_two_hop_statement']
were any [computer science] majors attending the meetings?	'Roslyn'	['question_type_global', 'question_two_hop_statement']
was anyone affiliated with [electrical engineering] attending any meetings late?	'Zenaida'	['question_type_global', 'question_two_hop_statement']
which people are in the [applied physics] department	'Isaiah'	['question_type_global', 'question_single_statement']
What department is [Isaiah] affiliated with?	'applied physics'	['question_type_local']
who is affiliated with [Hudson University]	'Isaiah'	['question_type_global', 'question_single_statement']
Which university is [Isaiah] affiliated with?	'Hudson University'	['question_type_local']
who is affiliated with [Harrison University]	'Zenaida', 'John', 'Tawnya'	['question_type_global', 'question_single_statement']
there is a [meeting] [to grade papers]
which students attended meetings late	'Roslyn'	['question_type_global', 'question_two_hop_statement']
[Isaiah] will attend [that meeting]
were any professors affiliated with [Hudson University] in attendance to [to grade papers]	'Isaiah'	['question_type_global', 'question_three_hop_statement']
[Tawnya] will attend [the meeting]
[this person] attended [that meeting] late
Who is attending [that meeting]	'Tawnya', 'Isaiah'	['question_type_local']
who is in the [electrical engineering] department	'Zenaida'	['question_type_global', 'question_single_statement']
who attended [about homework grading]	'Zenaida', 'Tawnya', 'Isaiah', 'Roslyn'	['question_type_global', 'question_single_statement']
[Isaiah] attended [this meeting] on time
Who was late to [that meeting]	'Tawnya'	['question_type_local']
which people are affiliated with [Harrison University]	'Zenaida', 'John', 'Tawnya'	['question_type_global', 'question_single_statement']
which students attended meetings late	'Tawnya', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
What is [Roslyn]'s major	'computer science'	['question_type_local']
which people attended meetings late	'Zenaida', 'John', 'Tawnya', 'Isaiah', 'Roslyn'	['question_type_global', 'question_single_statement']
actually [Zenaida] is my friend
Which university is [she] affiliated with?	'Harrison University'	['question_type_local']
were any people affiliated with [Harrison University] in attendance to [to practice presentations]	'John'	['question_type_global', 'question_two_hop_statement']
were any people affiliated with [Hudson University] late	'Isaiah'	['question_type_global', 'question_two_hop_statement']
Which university is [he] affiliated with?	'Hudson University'	['question_type_local']
which people affiliated with [Hudson University] attended [to grade papers]	'Isaiah'	['question_type_global', 'question_two_hop_statement']
which students attended meetings late	'Tawnya', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
which people attended meetings late	'Zenaida', 'John', 'Tawnya', 'Isaiah', 'Roslyn'	['question_type_global', 'question_single_statement']
was anyone from the [applied physics] department in attendance?	'Isaiah'	['question_type_global', 'question_two_hop_statement']
[Roslyn] will attend [the event with Isaiah to practice presentations]
create a new [meeting]
Change major of [this student] to [electrical engineering]
Which university is [that student] affiliated with?	'Springfield University'	['question_type_local']
which students are my friends?	'Tawnya'	['question_type_global', 'question_two_hop_statement']
were any professors affiliated with [Hudson University] late to any meetings	'Isaiah'	['question_type_global', 'question_three_hop_statement']
which professors affiliated with [Harrison University] attended [to grade papers]	'Zenaida'	['question_type_global', 'question_three_hop_statement']
which people are affiliated with [Hudson University]	'Isaiah'	['question_type_global', 'question_single_statement']
which professors affiliated with [Harrison University] were late	'Zenaida'	['question_type_global', 'question_three_hop_statement']
who are my friends?	'Zenaida', 'Tawnya', 'Isaiah'	['question_type_global', 'question_single_statement']
Who is attending [the event with Tawnya about homework grading]	'Zenaida', 'Tawnya', 'Isaiah', 'Roslyn'	['question_type_local']
which students majoring in [electrical engineering] were late	'Roslyn'	['question_type_global', 'question_two_hop_statement']
who is majoring in [engineering]	'Tawnya'	['question_type_global', 'question_single_statement']
[Zenaida] will attend [the event with Roslyn that was last added]
was anyone who majored in [electrical engineering] ever late to any meetings?	'Roslyn'	['question_type_global', 'question_two_hop_statement']
which people attended meetings late	'Zenaida', 'John', 'Tawnya', 'Isaiah', 'Roslyn'	['question_type_global', 'question_single_statement']
change [Zenaida]'s department to [computer science]
create a new [meeting]
which students majoring in [engineering] were late	'Tawnya'	['question_type_global', 'question_two_hop_statement']
which people are affiliated with [Hudson University]	'Isaiah'	['question_type_global', 'question_single_statement']
were any people affiliated with [Springfield University] in attendance to [about homework grading]	'Roslyn'	['question_type_global', 'question_two_hop_statement']
What is [John]'s affiliation?	'Harrison University'	['question_type_local']
which students are my friends?	'Tawnya'	['question_type_global', 'question_two_hop_statement']
was anyone from the [applied physics] department in attendance?	'Isaiah'	['question_type_global', 'question_two_hop_statement']
was anyone affiliated with [applied physics] attending the meetings?	'Isaiah'	['question_type_global', 'question_two_hop_statement']
[she] is not my friend
What department is [Zenaida] with?	'computer science'	['question_type_local']
which students attended meetings late	'Tawnya', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
[Roslyn] will attend [this meeting]
[Roslyn] attended [that meeting] late
[this meeting] is [about homework grading]
Change major of [that person] to [computer science]
which people are in the [applied physics] department	'Isaiah'	['question_type_global', 'question_single_statement']
which people affiliated with [Hudson University] attended [to grade papers]	'Isaiah'	['question_type_global', 'question_two_hop_statement']
Who is attending [the event with Tawnya about homework grading]	'Zenaida', 'Tawnya', 'Isaiah', 'Roslyn'	['question_type_local']
which professors are my friends?	'Isaiah'	['question_type_global', 'question_two_hop_statement']
was anyone who majored in [computer science] ever late to any meetings?	'Roslyn'	['question_type_global', 'question_two_hop_statement']
create a new [meeting]
[that meeting] is [to practice presentations]
[Zenaida] will attend [the event]
[she] attended [the event] on time
[this meeting] now is [to grade papers]
What department is [she] in?	'computer science'	['question_type_local']
which students attended meetings late	'Tawnya', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
who attended [to practice presentations]	'John', 'Tawnya', 'Isaiah', 'Roslyn'	['question_type_global', 'question_single_statement']
which people are affiliated with [Harrison University]	'Zenaida', 'John', 'Tawnya'	['question_type_global', 'question_single_statement']
who attended [about homework grading] late	'Isaiah', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
who are my friends?	'Tawnya', 'Isaiah'	['question_type_global', 'question_single_statement']
What is [Roslyn]'s major	'computer science'	['question_type_local']
who attended [about homework grading]	'Zenaida', 'Tawnya', 'Isaiah', 'Roslyn'	['question_type_global', 'question_single_statement']
which people attended meetings late	'Zenaida', 'John', 'Tawnya', 'Isaiah', 'Roslyn'	['question_type_global', 'question_single_statement']
which people are in the [applied physics] department	'Isaiah'	['question_type_global', 'question_single_statement']
was anyone affiliated with [Harrison University] late to [to practice presentations]	'John'	['question_type_global', 'question_three_hop_statement']
[Isaiah] will attend [this meeting]
who are my professor friends?	'Isaiah'	['question_type_global', 'question_two_hop_statement']
which professors are my friends?	'Isaiah'	['question_type_global', 'question_two_hop_statement']
What is [that person]'s affiliation?	'Hudson University'	['question_type_local']
[Tawnya] will attend [the meeting]
What is [Roslyn]'s major	'computer science'	['question_type_local']
which students affiliated with [Springfield University] attended [to grade papers]	'Roslyn'	['question_type_global', 'question_three_hop_statement']
which students affiliated with [Harrison University] were late	'Tawnya'	['question_type_global', 'question_three_hop_statement']
which students are my friends?	'Tawnya'	['question_type_global', 'question_two_hop_statement']
[Isaiah] attended [that meeting] late
[the event] now is [to practice presentations]
Which university is [this professor] affiliated with?	'Hudson University'	['question_type_local']
who is affiliated with [Springfield University]	'Roslyn'	['question_type_global', 'question_single_statement']
who are my professor friends?	'Isaiah'	['question_type_global', 'question_two_hop_statement']
What department is [he] affiliated with?	'applied physics'	['question_type_local']
What is [that professor]'s affiliation?	'Hudson University'	['question_type_local']
who are my friends?	'Tawnya', 'Isaiah'	['question_type_global', 'question_single_statement']
was anyone affiliated with [applied physics] attending the meetings?	'Isaiah'	['question_type_global', 'question_two_hop_statement']
were any [computer science] majors attending the meetings?	'Roslyn'	['question_type_global', 'question_two_hop_statement']
Who is attending [that meeting]	'Zenaida', 'Tawnya', 'Isaiah'	['question_type_local']
which people attended meetings late	'Zenaida', 'John', 'Tawnya', 'Isaiah', 'Roslyn'	['question_type_global', 'question_single_statement']
was anyone affiliated with [computer science] attending the meetings?	'Zenaida'	['question_type_global', 'question_two_hop_statement']
which people are in the [computer science] department	'Zenaida'	['question_type_global', 'question_single_statement']
who are my friends?	'Tawnya', 'Isaiah'	['question_type_global', 'question_single_statement']
was anyone from the [applied physics] department late to meetings?	'Isaiah'	['question_type_global', 'question_two_hop_statement']
which people are affiliated with [Harrison University]	'Zenaida', 'John', 'Tawnya'	['question_type_global', 'question_single_statement']
[Roslyn] will attend [the event]
Who was late to [this meeting]	'Isaiah'	['question_type_local']
What department is [Zenaida] affiliated with?	'computer science'	['question_type_local']
has anyone from the [applied physics] department attending meetings late	'Isaiah'	['question_type_global', 'question_two_hop_statement']
which students majoring in [engineering] attended meetings	'Tawnya'	['question_type_global', 'question_two_hop_statement']
which professors are my friends?	'Isaiah'	['question_type_global', 'question_two_hop_statement']
were any [engineering] majors ever late?	'Tawnya'	['question_type_global', 'question_two_hop_statement']
were any people affiliated with [Hudson University] late to [about homework grading]	'Isaiah'	['question_type_global', 'question_three_hop_statement']
who is majoring in [computer science]	'Roslyn'	['question_type_global', 'question_single_statement']
which professors are affiliated with the [applied physics] department	'Isaiah'	['question_type_global', 'question_single_statement']
[Tawnya] attended [this meeting] on time
Who is attending [this meeting]	'Zenaida', 'Tawnya', 'Isaiah', 'Roslyn'	['question_type_local']
which people attended meetings late	'Zenaida', 'John', 'Tawnya', 'Isaiah', 'Roslyn'	['question_type_global', 'question_single_statement']
[she] is not my friend
