[Casey] is a [professor]
there is a [professor] named [Igor]
[Casey]'s affiliation is [Faber College]
[Casey] is a friend
[that professor]'s email is [Casey@nh.edu]
who are my friends?	'Casey'	['question_type_global', 'question_single_statement']
create a new [meeting]
[Lorilee] is a [person]
create a [person] named [Danita]
[Danita] is not a friend
[that person]'s affiliation is [Faber College]
[this person]'s email is [Danita@harvard.edu]
What is [this person]'s affiliation?	'Faber College'	['question_type_local']
What is [that person]'s email	'Danita@harvard.edu'	['question_type_local']
Which university is [Danita] affiliated with?	'Faber College'	['question_type_local']
there is a [meeting] [to practice presentations]
[Lorilee] will attend [this meeting]
[that person]'s affiliation is [Barnett College]
[this person] is not a friend
Which university is [she] affiliated with?	'Barnett College'	['question_type_local']
[this person]'s email is [Lorilee@yandex.com]
What is [that person]'s affiliation?	'Barnett College'	['question_type_local']
who are my professor friends?	'Casey'	['question_type_global', 'question_two_hop_statement']
[Casey] is not my friend
What is [Danita]'s affiliation?	'Faber College'	['question_type_local']
[this professor] will attend [the event that was last added]
Who is attending [the event]	'Casey', 'Lorilee'	['question_type_local']
which people are affiliated with [Faber College]	'Casey', 'Danita'	['question_type_global', 'question_single_statement']
[Danita] will attend [the meeting]
create a new [meeting]
What is [that person]'s email	'Danita@harvard.edu'	['question_type_local']
[that meeting] is [to grade papers]
[Casey] will attend [this meeting]
[Igor] will attend [the event to practice presentations]
[this person]'s affiliation is [Blue Mountain State]
[that person]'s email is [Igor@msn.com]
[Igor] is a friend
Which university is [Igor] affiliated with?	'Blue Mountain State'	['question_type_local']
Which university is [this professor] affiliated with?	'Blue Mountain State'	['question_type_local']
there is a [meeting] [to discuss future plans]
create a new [meeting]
who attended [to practice presentations]	'Casey', 'Igor', 'Lorilee', 'Danita'	['question_type_global', 'question_single_statement']
who are my friends?	'Igor'	['question_type_global', 'question_single_statement']
which people are affiliated with [Blue Mountain State]	'Igor'	['question_type_global', 'question_single_statement']
[Lorilee] will attend [the event that was last added]
[the event] is [to discuss future plans]
Which university is [she] affiliated with?	'Barnett College'	['question_type_local']
[Danita] will attend [that meeting]
[Casey] will attend [that meeting]
[Igor] will attend [that meeting]
actually [Casey] is my friend
which people are affiliated with [Barnett College]	'Lorilee'	['question_type_global', 'question_single_statement']
create a new [meeting]
[that professor] will attend [that meeting]
[this meeting] is [to grade papers]
Who is attending [this meeting]	'Casey'	['question_type_local']
which people are affiliated with [Faber College]	'Casey', 'Danita'	['question_type_global', 'question_single_statement']
What is [Igor]'s affiliation?	'Blue Mountain State'	['question_type_local']
who are my friends?	'Casey', 'Igor'	['question_type_global', 'question_single_statement']
[Danita] will attend [the event]
there is a [meeting] [to discuss future plans]
What is [this person]'s email	'Danita@harvard.edu'	['question_type_local']
which professors are my friends?	'Casey', 'Igor'	['question_type_global', 'question_two_hop_statement']
create a new [meeting]
[Igor] will attend [the meeting to discuss future plans that was last added]
[that meeting] now is [about homework grading]
Who is attending [the event]	'Igor'	['question_type_local']
[Lorilee] will attend [that meeting]
[Casey] will attend [that meeting]
[Danita] will attend [this meeting]
Who is attending [the meeting]	'Casey', 'Igor', 'Lorilee', 'Danita'	['question_type_local']
who are my professor friends?	'Casey', 'Igor'	['question_type_global', 'question_two_hop_statement']
which people are affiliated with [Blue Mountain State]	'Igor'	['question_type_global', 'question_single_statement']
[Igor] will attend [the meeting to grade papers with Casey and Danita]
Who is attending [that meeting]	'Casey', 'Igor', 'Danita'	['question_type_local']
actually [Danita] is my friend
What is [she]'s affiliation?	'Faber College'	['question_type_local']
What is [she]'s email	'Danita@harvard.edu'	['question_type_local']
Which university is [she] affiliated with?	'Faber College'	['question_type_local']
who is affiliated with [Blue Mountain State]	'Igor'	['question_type_global', 'question_single_statement']
What is [Danita]'s email	'Danita@harvard.edu'	['question_type_local']
there is a [meeting] [about homework grading]
create a new [meeting]
[Lorilee] will attend [the meeting about homework grading that was last added]
[Danita] will attend [that meeting]
Who is attending [that meeting]	'Lorilee', 'Danita'	['question_type_local']
who attended [about homework grading]	'Casey', 'Igor', 'Lorilee', 'Danita'	['question_type_global', 'question_single_statement']
who attended [to discuss future plans]	'Casey', 'Igor', 'Lorilee', 'Danita'	['question_type_global', 'question_single_statement']
[Casey] will attend [the meeting]
which professors are my friends?	'Casey', 'Igor'	['question_type_global', 'question_two_hop_statement']
Who is attending [this meeting]	'Casey', 'Lorilee', 'Danita'	['question_type_local']
which people are affiliated with [Blue Mountain State]	'Igor'	['question_type_global', 'question_single_statement']
[this person] is not my friend
What is [Danita]'s email	'Danita@harvard.edu'	['question_type_local']
who are my friends?	'Igor', 'Danita'	['question_type_global', 'question_single_statement']
create a new [meeting]
[the meeting] is [about homework grading]
[Lorilee] will attend [this meeting]
Who is attending [that meeting]	'Lorilee'	['question_type_local']
who attended [to discuss future plans]	'Casey', 'Igor', 'Lorilee', 'Danita'	['question_type_global', 'question_single_statement']
[Casey] will attend [that meeting]
[Danita] will attend [the event]
[Igor] is not my friend
who is affiliated with [Blue Mountain State]	'Igor'	['question_type_global', 'question_single_statement']
who is affiliated with [Barnett College]	'Lorilee'	['question_type_global', 'question_single_statement']
Who is attending [the event about homework grading with Casey and Igor]	'Casey', 'Igor', 'Lorilee', 'Danita'	['question_type_local']
there is a [meeting] [to grade papers]
[Lorilee] will attend [the meeting]
[Danita] will attend [this meeting]
create a new [meeting]
there is a [meeting] [about homework grading]
[Casey] will attend [the meeting that was last added]
create a new [meeting]
[Danita] will attend [this meeting]
[this meeting] is [to practice presentations]
Who is attending [this meeting]	'Danita'	['question_type_local']
who is affiliated with [Faber College]	'Casey', 'Danita'	['question_type_global', 'question_single_statement']
[Lorilee] will attend [the meeting with Igor and Danita to grade papers]
[Igor] will attend [the event about homework grading with Casey and Danita that was last added]
Who is attending [that meeting]	'Casey', 'Igor', 'Lorilee', 'Danita'	['question_type_local']
Who is attending [the event]	'Casey', 'Igor', 'Lorilee', 'Danita'	['question_type_local']
What is [Danita]'s email	'Danita@harvard.edu'	['question_type_local']
create a new [meeting]
who are my friends?	'Danita'	['question_type_global', 'question_single_statement']
create a new [meeting]
[Lorilee] will attend [the event that was last added]
[this meeting] is [to discuss future plans]
Who is attending [the event]	'Lorilee'	['question_type_local']
Who is attending [the event to discuss future plans with Igor and Casey]	'Casey', 'Igor', 'Lorilee', 'Danita'	['question_type_local']
Which university is [she] affiliated with?	'Barnett College'	['question_type_local']
Which university is [that person] affiliated with?	'Barnett College'	['question_type_local']
there is a [meeting] [to grade papers]
Who is attending [the event with Igor and Casey to grade papers]	'Casey', 'Igor', 'Lorilee', 'Danita'	['question_type_local']
[Lorilee] will attend [the event that was last added]
What is [Igor]'s email	'Igor@msn.com'	['question_type_local']
Who is attending [the meeting to grade papers with Igor]	'Casey', 'Igor', 'Lorilee', 'Danita'	['question_type_local']
who attended [to grade papers]	'Casey', 'Igor', 'Lorilee', 'Danita'	['question_type_global', 'question_single_statement']
there is a [meeting] [to discuss future plans]
What is [Lorilee]'s email	'Lorilee@yandex.com'	['question_type_local']
who attended [to discuss future plans]	'Casey', 'Igor', 'Lorilee', 'Danita'	['question_type_global', 'question_single_statement']
[Casey] will attend [that meeting]
create a new [meeting]
create a new [meeting]
[Casey] will attend [the event that was last added]
[the meeting] is [to practice presentations]
who are my friends?	'Danita'	['question_type_global', 'question_single_statement']
actually [this person] is my friend
What is [this person]'s affiliation?	'Faber College'	['question_type_local']
who are my professor friends?	'Casey'	['question_type_global', 'question_two_hop_statement']
[this person] will attend [the event with Danita to grade papers that was last added]
there is a [meeting] [to practice presentations]
[Casey] is not my friend
Which university is [Casey] affiliated with?	'Faber College'	['question_type_local']
there is a [meeting] [to grade papers]
[Lorilee] will attend [that meeting]
What is [Igor]'s affiliation?	'Blue Mountain State'	['question_type_local']
create a new [meeting]
What is [she]'s email	'Lorilee@yandex.com'	['question_type_local']
which people are affiliated with [Barnett College]	'Lorilee'	['question_type_global', 'question_single_statement']
What is [that person]'s email	'Lorilee@yandex.com'	['question_type_local']
[Casey] will attend [the meeting]
[the event] is [to grade papers]
[Danita] will attend [this meeting]
Who is attending [that meeting]	'Casey', 'Danita'	['question_type_local']
which people are affiliated with [Blue Mountain State]	'Igor'	['question_type_global', 'question_single_statement']
[Igor] will attend [this meeting]
there is a [meeting] [about homework grading]
create a new [meeting]
What is [Casey]'s email	'Casey@nh.edu'	['question_type_local']
[the event to discuss future plans with Casey and Igor] now is [about homework grading]
[Danita] will attend [the meeting that was last added]
[that meeting] is [about homework grading]
Who is attending [that meeting]	'Danita'	['question_type_local']
Who is attending [the event with Danita and Casey to practice presentations]	'Casey', 'Igor', 'Lorilee', 'Danita'	['question_type_local']
[Casey] will attend [that meeting]
there is a [meeting] [to grade papers]
