there is a [student] named [Britney]
[Britney]'s major is [communication]
[that student]'s affiliation is [Medfield College]
[this person] is not a friend
What is [Britney]'s major	'communication'	['question_type_local']
What is [this person]'s major	'communication'	['question_type_local']
create a [person] named [Cecil]
[he] is a friend
who are my friends?	'Cecil'	['question_type_global', 'question_single_statement']
there is a [student] named [Willis]
[Cecil]'s affiliation is [Greendale Community College]
there is a [meeting] [to grade papers]
there is a [person] named [Angelita]
[John] is a [person]
[Angelita] will attend [the meeting]
Who is attending [this meeting]	'Angelita'	['question_type_local']
[Cecil] will attend [this meeting]
who is affiliated with [Medfield College]	'Britney'	['question_type_global', 'question_single_statement']
[Willis] will attend [this meeting]
[John] will attend [this meeting]
[he]'s affiliation is [Greendale Community College]
[that person] is a friend
Change major of [Britney] to [accounting]
create a new [meeting]
there is a [student] named [Genevive]
[John] will attend [the meeting]
[the meeting] is [about homework grading]
there is a [meeting] [to grade papers]
Who is attending [the meeting about homework grading with John]	'John'	['question_type_local']
who is affiliated with [Greendale Community College]	'Cecil', 'John'	['question_type_global', 'question_single_statement']
create a new [meeting]
[the event to grade papers that was last added] now is [to discuss future plans]
[John] will attend [the event to discuss future plans]
which students are majoring in [accounting]	'Britney'	['question_type_global', 'question_single_statement']
[Britney] will attend [the event that was last added]
there is a [meeting] [to discuss future plans]
who are my friends?	'Cecil', 'John'	['question_type_global', 'question_single_statement']
[Angelita] will attend [that meeting]
who attended [to discuss future plans]	'Angelita', 'John'	['question_type_global', 'question_single_statement']
[Genevive] will attend [the meeting with Britney]
[this meeting] is [about homework grading]
[the event that was last added] now is [about homework grading]
[John] will attend [the event with Angelita that was last added]
Who is attending [the meeting]	'Angelita', 'John'	['question_type_local']
[Britney] will attend [that meeting]
[Willis] is a friend
[he]'s affiliation is [Harrison University]
Which university is [this student] affiliated with?	'Harrison University'	['question_type_local']
[he]'s major is [math]
create a new [meeting]
which students are my friends?	'Willis'	['question_type_global', 'question_two_hop_statement']
[that meeting] is [to discuss future plans]
[Cecil] will attend [that meeting]
[John] will attend [the meeting]
Who is attending [this meeting]	'Cecil', 'John'	['question_type_local']
who is affiliated with [Medfield College]	'Britney'	['question_type_global', 'question_single_statement']
[Willis] will attend [the event about homework grading that was last added]
Change major of [Britney] to [math]
What is [Britney]'s major	'math'	['question_type_local']
Which university is [he] affiliated with?	'Harrison University'	['question_type_local']
who is majoring in [math]	'Britney', 'Willis'	['question_type_global', 'question_single_statement']
What is [he]'s major	'math'	['question_type_local']
[Genevive]'s major is [math]
[Genevive]'s affiliation is [Greendale Community College]
[that student] is a friend
What is [Genevive]'s major	'math'	['question_type_local']
who are my friends?	'Cecil', 'Willis', 'John', 'Genevive'	['question_type_global', 'question_single_statement']
Which university is [Genevive] affiliated with?	'Greendale Community College'	['question_type_local']
which students are my friends?	'Willis', 'Genevive'	['question_type_global', 'question_two_hop_statement']
What is [Genevive]'s affiliation?	'Greendale Community College'	['question_type_local']
create a new [meeting]
Who is attending [the meeting with Angelita that was last added]	'Britney', 'Willis', 'Angelita', 'John'	['question_type_local']
Who is attending [the event to grade papers]	'Cecil', 'Willis', 'Angelita', 'John'	['question_type_local']
which people are affiliated with [Medfield College]	'Britney'	['question_type_global', 'question_single_statement']
who are my friends?	'Cecil', 'Willis', 'John', 'Genevive'	['question_type_global', 'question_single_statement']
there is a [meeting] [to discuss future plans]
create a new [meeting]
[the event that was last added] is [about homework grading]
[Willis] will attend [this meeting]
What is [Britney]'s major	'math'	['question_type_local']
[this meeting] now is [to prepare for exams]
[Cecil] will attend [that meeting]
which students are my friends?	'Willis', 'Genevive'	['question_type_global', 'question_two_hop_statement']
[John] will attend [the meeting]
who is affiliated with [Harrison University]	'Willis'	['question_type_global', 'question_single_statement']
[Cecil] is not my friend
which students are majoring in [math]	'Britney', 'Willis', 'Genevive'	['question_type_global', 'question_single_statement']
Change major of [Britney] to [accounting]
actually [this student] is my friend
What is [this student]'s affiliation?	'Medfield College'	['question_type_local']
[John] is not my friend
What is [she]'s major	'accounting'	['question_type_local']
What is [that student]'s affiliation?	'Medfield College'	['question_type_local']
Which university is [this student] affiliated with?	'Medfield College'	['question_type_local']
who attended [to grade papers]	'Cecil', 'Willis', 'Angelita', 'John'	['question_type_global', 'question_single_statement']
What is [he]'s affiliation?	'Greendale Community College'	['question_type_local']
which students are my friends?	'Britney', 'Willis', 'Genevive'	['question_type_global', 'question_two_hop_statement']
Change major of [Willis] to [communication]
What is [Willis]'s major	'communication'	['question_type_local']
create a new [meeting]
there is a [meeting] [to grade papers]
[Cecil] will attend [the meeting to grade papers that was last added]
Change major of [Britney] to [communication]
What is [this student]'s affiliation?	'Medfield College'	['question_type_local']
[Angelita]'s affiliation is [Medfield College]
[Angelita] is not a friend
What is [she]'s affiliation?	'Medfield College'	['question_type_local']
actually [Angelita] is my friend
Which university is [she] affiliated with?	'Medfield College'	['question_type_local']
which students are majoring in [math]	'Genevive'	['question_type_global', 'question_single_statement']
who are my friends?	'Britney', 'Willis', 'Angelita', 'Genevive'	['question_type_global', 'question_single_statement']
Which university is [this person] affiliated with?	'Medfield College'	['question_type_local']
which students are my friends?	'Britney', 'Willis', 'Genevive'	['question_type_global', 'question_two_hop_statement']
What is [Willis]'s affiliation?	'Harrison University'	['question_type_local']
who is affiliated with [Medfield College]	'Britney', 'Angelita'	['question_type_global', 'question_single_statement']
who attended [to discuss future plans]	'Cecil', 'John'	['question_type_global', 'question_single_statement']
Which university is [she] affiliated with?	'Medfield College'	['question_type_local']
who are my friends?	'Britney', 'Willis', 'Angelita', 'Genevive'	['question_type_global', 'question_single_statement']
Which university is [this person] affiliated with?	'Medfield College'	['question_type_local']
create a new [meeting]
there is a [meeting] [about homework grading]
[Britney] will attend [the event about homework grading that was last added]
Who is attending [that meeting]	'Britney'	['question_type_local']
create a new [meeting]
Change major of [that person] to [math]
[Cecil] will attend [that meeting]
[that meeting] is [to prepare for exams]
create a new [meeting]
What is [Britney]'s major	'math'	['question_type_local']
who attended [about homework grading]	'Britney', 'Willis', 'Angelita', 'John', 'Genevive'	['question_type_global', 'question_single_statement']
[John] will attend [the event that was last added]
[this meeting] is [to prepare for exams]
[Angelita] will attend [this meeting]
[Genevive] will attend [the event with Willis that was last added]
What is [this person]'s major	'math'	['question_type_local']
create a new [meeting]
[Willis] will attend [the meeting about homework grading with Britney and Genevive]
which students are majoring in [math]	'Britney', 'Genevive'	['question_type_global', 'question_single_statement']
What is [that person]'s affiliation?	'Harrison University'	['question_type_local']
[Cecil] will attend [the meeting]
[that meeting] now is [to grade papers]
[Angelita] will attend [the event with Cecil to grade papers that was last added]
create a new [meeting]
who attended [to discuss future plans]	'Cecil', 'John'	['question_type_global', 'question_single_statement']
[the event to prepare for exams with Cecil and John] now is [about homework grading]
Who is attending [the meeting with Cecil and Britney to grade papers]	'Britney', 'Cecil', 'Willis', 'Genevive'	['question_type_local']
Who is attending [the event with Britney and Willis about homework grading]	'Britney', 'Willis', 'Angelita', 'John'	['question_type_local']
who is affiliated with [Medfield College]	'Britney', 'Angelita'	['question_type_global', 'question_single_statement']
[Britney] will attend [the event with John to discuss future plans that was last added]
create a new [meeting]
who attended [to grade papers]	'Britney', 'Cecil', 'Willis', 'Angelita', 'John', 'Genevive'	['question_type_global', 'question_single_statement']
What is [Cecil]'s affiliation?	'Greendale Community College'	['question_type_local']
who is affiliated with [Harrison University]	'Willis'	['question_type_global', 'question_single_statement']
[this meeting] is [to grade papers]
who are my friends?	'Britney', 'Willis', 'Angelita', 'Genevive'	['question_type_global', 'question_single_statement']
[Cecil] will attend [this meeting]
Change major of [Britney] to [accounting]
What is [this student]'s affiliation?	'Medfield College'	['question_type_local']
which students are majoring in [communication]	'Willis'	['question_type_global', 'question_single_statement']
there is a [meeting] [about homework grading]
[Britney] is not my friend
who attended [to prepare for exams]	'Cecil', 'Angelita', 'John'	['question_type_global', 'question_single_statement']
[this meeting] now is [to prepare for exams]
[John] will attend [the event]
Who is attending [the event]	'John'	['question_type_local']
who are my friends?	'Willis', 'Angelita', 'Genevive'	['question_type_global', 'question_single_statement']
What is [this person]'s affiliation?	'Greendale Community College'	['question_type_local']
who attended [about homework grading]	'Britney', 'Cecil', 'Willis', 'Angelita', 'John', 'Genevive'	['question_type_global', 'question_single_statement']
[Angelita] will attend [this meeting]
who is affiliated with [Harrison University]	'Willis'	['question_type_global', 'question_single_statement']
Which university is [that person] affiliated with?	'Medfield College'	['question_type_local']
[Cecil] will attend [this meeting]
Who is attending [that meeting]	'Cecil', 'Angelita', 'John'	['question_type_local']
who attended [to prepare for exams]	'Cecil', 'Angelita', 'John'	['question_type_global', 'question_single_statement']
Which university is [he] affiliated with?	'Greendale Community College'	['question_type_local']
create a new [meeting]
[Cecil] will attend [the meeting]
Who is attending [the meeting]	'Cecil'	['question_type_local']
which students are majoring in [communication]	'Willis'	['question_type_global', 'question_single_statement']
[that meeting] is [to grade papers]
[Angelita] will attend [that meeting]
