there is a [student] named [Gabrielle]
there is a [meeting] [to prepare for exams]
[Gabrielle]'s major is [food science]
[this student]'s affiliation is [Barnett College]
What is [this student]'s affiliation?	'Barnett College'	['question_type_local']
[this person] is a friend
[Tom] is a [student]
[Andy] is a [professor]
[Gabrielle] will attend [the meeting]
which students are my friends?	'Gabrielle'	['question_type_global', 'question_two_hop_statement']
who is majoring in [food science]	'Gabrielle'	['question_type_global', 'question_single_statement']
create a [person] named [Luanna]
Change major of [Gabrielle] to [biology]
What is [this student]'s major	'biology'	['question_type_local']
[that student] is not my friend
which people are affiliated with [Barnett College]	'Gabrielle'	['question_type_global', 'question_single_statement']
who is affiliated with [Barnett College]	'Gabrielle'	['question_type_global', 'question_single_statement']
[Eun] is a [student]
[Luanna]'s affiliation is [Barnett College]
[Luanna] is a friend
What is [that person]'s affiliation?	'Barnett College'	['question_type_local']
What is [she]'s affiliation?	'Barnett College'	['question_type_local']
who is majoring in [biology]	'Gabrielle'	['question_type_global', 'question_single_statement']
Which university is [that person] affiliated with?	'Barnett College'	['question_type_local']
[Luanna] is not my friend
What is [Luanna]'s affiliation?	'Barnett College'	['question_type_local']
Which university is [Luanna] affiliated with?	'Barnett College'	['question_type_local']
which people are affiliated with [Barnett College]	'Gabrielle', 'Luanna'	['question_type_global', 'question_single_statement']
create a new [meeting]
Which university is [Gabrielle] affiliated with?	'Barnett College'	['question_type_local']
[Gabrielle] will attend [this meeting]
[this meeting] is [to discuss future plans]
which students are majoring in [biology]	'Gabrielle'	['question_type_global', 'question_single_statement']
[Andy] will attend [that meeting]
[Eun] will attend [this meeting]
[she]'s major is [food science]
[Eun]'s affiliation is [Hudson University]
[that student] is not a friend
Who is attending [the meeting that was last added]	'Gabrielle', 'Andy', 'Eun'	['question_type_local']
What is [Eun]'s major	'food science'	['question_type_local']
[Andy]'s department is [biomedical engineering]
What department is [he] in?	'biomedical engineering'	['question_type_local']
who is majoring in [food science]	'Eun'	['question_type_global', 'question_single_statement']
What is [this student]'s major	'food science'	['question_type_local']
What is [she]'s major	'food science'	['question_type_local']
there is a [meeting] [to practice presentations]
[that professor]'s affiliation is [South Harmon Institute of Technology]
[that person]'s office is [NSH387]
What department is [that person] in?	'biomedical engineering'	['question_type_local']
[Tom] will attend [the event to discuss future plans with Eun and Gabrielle]
Who is attending [the event]	'Gabrielle', 'Tom', 'Andy', 'Eun'	['question_type_local']
who attended [to prepare for exams]	'Gabrielle'	['question_type_global', 'question_single_statement']
[Tom]'s major is [biology]
[this student] is a friend
[he]'s affiliation is [Adams College]
there is a [meeting] [to grade papers]
Which university is [Eun] affiliated with?	'Hudson University'	['question_type_local']
who are my friends?	'Tom'	['question_type_global', 'question_single_statement']
[Eun] will attend [that meeting]
[Andy] is not a friend
who is majoring in [food science]	'Eun'	['question_type_global', 'question_single_statement']
which students are my friends?	'Tom'	['question_type_global', 'question_two_hop_statement']
there is a [meeting] [to discuss future plans]
[Gabrielle] will attend [this meeting]
Who is attending [the event]	'Gabrielle'	['question_type_local']
[Andy] will attend [the meeting to practice presentations]
Who is attending [the event with Eun that was last added]	'Eun'	['question_type_local']
What is [Eun]'s major	'food science'	['question_type_local']
which professors are affiliated with the [biomedical engineering] department	'Andy'	['question_type_global', 'question_single_statement']
which people are affiliated with [Hudson University]	'Eun'	['question_type_global', 'question_single_statement']
[Luanna] will attend [this meeting]
Who is attending [this meeting]	'Andy', 'Luanna'	['question_type_local']
[this meeting] now is [to grade papers]
[Eun] will attend [the meeting]
who is affiliated with [South Harmon Institute of Technology]	'Andy'	['question_type_global', 'question_single_statement']
[Gabrielle] will attend [that meeting]
who are my friends?	'Tom'	['question_type_global', 'question_single_statement']
there is a [meeting] [to grade papers]
Who is attending [the meeting with Tom]	'Gabrielle', 'Tom', 'Andy', 'Eun'	['question_type_local']
who is in the [biomedical engineering] department	'Andy'	['question_type_global', 'question_single_statement']
[Luanna] will attend [this meeting]
who attended [to prepare for exams]	'Gabrielle'	['question_type_global', 'question_single_statement']
What is [Gabrielle]'s affiliation?	'Barnett College'	['question_type_local']
who is majoring in [biology]	'Gabrielle', 'Tom'	['question_type_global', 'question_single_statement']
actually [Gabrielle] is my friend
create a new [meeting]
What is [Eun]'s major	'food science'	['question_type_local']
who are my friends?	'Gabrielle', 'Tom'	['question_type_global', 'question_single_statement']
who attended [to grade papers]	'Gabrielle', 'Andy', 'Luanna', 'Eun'	['question_type_global', 'question_single_statement']
create a new [meeting]
[the meeting that was last added] is [about homework grading]
[Tom] will attend [the event]
Who is attending [that meeting]	'Tom'	['question_type_local']
which students are my friends?	'Gabrielle', 'Tom'	['question_type_global', 'question_two_hop_statement']
which students are majoring in [biology]	'Gabrielle', 'Tom'	['question_type_global', 'question_single_statement']
which people are affiliated with [Barnett College]	'Gabrielle', 'Luanna'	['question_type_global', 'question_single_statement']
who is majoring in [biology]	'Gabrielle', 'Tom'	['question_type_global', 'question_single_statement']
[this student] is not my friend
Change major of [Tom] to [food science]
What is [Tom]'s affiliation?	'Adams College'	['question_type_local']
who are my friends?	'Gabrielle'	['question_type_global', 'question_single_statement']
Change major of [that person] to [english]
Which university is [this person] affiliated with?	'Adams College'	['question_type_local']
Who is attending [the meeting with Eun and Gabrielle that was last added]	'Gabrielle', 'Andy', 'Luanna', 'Eun'	['question_type_local']
[he] will attend [the meeting with Gabrielle to prepare for exams]
Who is attending [this meeting]	'Gabrielle', 'Tom'	['question_type_local']
who is in the [biomedical engineering] department	'Andy'	['question_type_global', 'question_single_statement']
which students are my friends?	'Gabrielle'	['question_type_global', 'question_two_hop_statement']
[Luanna] will attend [that meeting]
[Eun] will attend [that meeting]
Who is attending [the event]	'Gabrielle', 'Tom', 'Luanna', 'Eun'	['question_type_local']
Which university is [that student] affiliated with?	'Hudson University'	['question_type_local']
which people are in the [biomedical engineering] department	'Andy'	['question_type_global', 'question_single_statement']
who attended [to prepare for exams]	'Gabrielle', 'Tom', 'Luanna', 'Eun'	['question_type_global', 'question_single_statement']
[Gabrielle] is not my friend
Change major of [Gabrielle] to [food science]
What is [this person]'s major	'food science'	['question_type_local']
there is a [meeting] [to practice presentations]
which students are majoring in [food science]	'Gabrielle', 'Eun'	['question_type_global', 'question_single_statement']
who is majoring in [english]	'Tom'	['question_type_global', 'question_single_statement']
there is a [meeting] [about homework grading]
What is [Luanna]'s affiliation?	'Barnett College'	['question_type_local']
who is in the [biomedical engineering] department	'Andy'	['question_type_global', 'question_single_statement']
[Gabrielle] will attend [the meeting about homework grading that was last added]
Who is attending [the meeting]	'Gabrielle'	['question_type_local']
who is affiliated with [Hudson University]	'Eun'	['question_type_global', 'question_single_statement']
create a new [meeting]
[the event] is [to prepare for exams]
[Gabrielle] will attend [this meeting]
What is [this student]'s major	'food science'	['question_type_local']
who attended [to grade papers]	'Gabrielle', 'Andy', 'Luanna', 'Eun'	['question_type_global', 'question_single_statement']
which people are in the [biomedical engineering] department	'Andy'	['question_type_global', 'question_single_statement']
who attended [to prepare for exams]	'Gabrielle', 'Tom', 'Luanna', 'Eun'	['question_type_global', 'question_single_statement']
[Andy] will attend [this meeting]
which students are majoring in [food science]	'Gabrielle', 'Eun'	['question_type_global', 'question_single_statement']
[Luanna] will attend [that meeting]
[Tom] will attend [the meeting]
Who is attending [that meeting]	'Gabrielle', 'Tom', 'Andy', 'Luanna'	['question_type_local']
Who is attending [the meeting]	'Gabrielle', 'Tom', 'Andy', 'Luanna'	['question_type_local']
who is in the [biomedical engineering] department	'Andy'	['question_type_global', 'question_single_statement']
there is a [meeting] [to practice presentations]
[Eun] will attend [the meeting]
Which university is [Andy] affiliated with?	'South Harmon Institute of Technology'	['question_type_local']
[Tom] will attend [the event about homework grading with Gabrielle]
who is affiliated with [South Harmon Institute of Technology]	'Andy'	['question_type_global', 'question_single_statement']
which students are majoring in [food science]	'Gabrielle', 'Eun'	['question_type_global', 'question_single_statement']
[Luanna] will attend [that meeting]
create a new [meeting]
Who is attending [the event to grade papers with Eun that was last added]	'Eun'	['question_type_local']
Which university is [this person] affiliated with?	'Barnett College'	['question_type_local']
which professors are affiliated with the [biomedical engineering] department	'Andy'	['question_type_global', 'question_single_statement']
Which university is [that person] affiliated with?	'Barnett College'	['question_type_local']
there is a [meeting] [to practice presentations]
Who is attending [the event with Andy and Gabrielle to grade papers]	'Gabrielle', 'Andy', 'Luanna', 'Eun'	['question_type_local']
there is a [meeting] [about homework grading]
who is affiliated with [Hudson University]	'Eun'	['question_type_global', 'question_single_statement']
[Gabrielle] will attend [the event that was last added]
[Andy] will attend [the event]
Who is attending [that meeting]	'Gabrielle', 'Andy'	['question_type_local']
[Eun] will attend [that meeting]
which students are majoring in [english]	'Tom'	['question_type_global', 'question_single_statement']
create a new [meeting]
[the meeting] is [about homework grading]
[Gabrielle] will attend [this meeting]
who is affiliated with [Adams College]	'Tom'	['question_type_global', 'question_single_statement']
there is a [meeting] [to practice presentations]
[Tom] will attend [that meeting]
which people are in the [biomedical engineering] department	'Andy'	['question_type_global', 'question_single_statement']
What is [that person]'s affiliation?	'Adams College'	['question_type_local']
[Andy] will attend [that meeting]
which professors are affiliated with the [biomedical engineering] department	'Andy'	['question_type_global', 'question_single_statement']
who attended [to discuss future plans]	'Gabrielle', 'Tom', 'Andy', 'Eun'	['question_type_global', 'question_single_statement']
[this person] will attend [the meeting with Eun to grade papers that was last added]
What is [Tom]'s affiliation?	'Adams College'	['question_type_local']
who is affiliated with [South Harmon Institute of Technology]	'Andy'	['question_type_global', 'question_single_statement']
who attended [to grade papers]	'Gabrielle', 'Andy', 'Luanna', 'Eun'	['question_type_global', 'question_single_statement']
[Gabrielle] will attend [that meeting]
actually [that student] is my friend
What is [Tom]'s major	'english'	['question_type_local']
which students are majoring in [food science]	'Gabrielle', 'Eun'	['question_type_global', 'question_single_statement']
there is a [meeting] [to prepare for exams]
which students are my friends?	'Gabrielle'	['question_type_global', 'question_two_hop_statement']
Change major of [that student] to [biology]
[Andy] will attend [the event with Luanna to grade papers that was last added]
Who is attending [that meeting]	'Andy', 'Luanna'	['question_type_local']
who attended [about homework grading]	'Gabrielle', 'Tom', 'Andy', 'Luanna', 'Eun'	['question_type_global', 'question_single_statement']
actually [Andy] is my friend
What department is [this person] with?	'biomedical engineering'	['question_type_local']
What department is [this person] in?	'biomedical engineering'	['question_type_local']
which professors are my friends?	'Andy'	['question_type_global', 'question_two_hop_statement']
who is affiliated with [Hudson University]	'Eun'	['question_type_global', 'question_single_statement']
What is [this professor]'s affiliation?	'South Harmon Institute of Technology'	['question_type_local']
who attended [to prepare for exams]	'Gabrielle', 'Tom', 'Andy', 'Luanna', 'Eun'	['question_type_global', 'question_single_statement']
which students are majoring in [biology]	'Gabrielle'	['question_type_global', 'question_single_statement']
create a new [meeting]
What department is [this person] with?	'biomedical engineering'	['question_type_local']
who attended [to grade papers]	'Gabrielle', 'Andy', 'Luanna', 'Eun'	['question_type_global', 'question_single_statement']
which students are my friends?	'Gabrielle'	['question_type_global', 'question_two_hop_statement']
Which university is [he] affiliated with?	'South Harmon Institute of Technology'	['question_type_local']
who are my professor friends?	'Andy'	['question_type_global', 'question_two_hop_statement']
[Gabrielle] will attend [that meeting]
[this meeting] is [to discuss future plans]
[that person] is not my friend
there is a [meeting] [to grade papers]
[Andy] will attend [the meeting with Eun to practice presentations]
[Luanna] will attend [this meeting]
which professors are affiliated with the [biomedical engineering] department	'Andy'	['question_type_global', 'question_single_statement']
Who is attending [the event to grade papers with Gabrielle and Eun that was last added]	'Gabrielle', 'Andy', 'Eun'	['question_type_local']
who is in the [biomedical engineering] department	'Andy'	['question_type_global', 'question_single_statement']
who are my friends?	'Andy'	['question_type_global', 'question_single_statement']
[Gabrielle] will attend [that meeting]
Who is attending [the event]	'Gabrielle', 'Andy', 'Luanna', 'Eun'	['question_type_local']
who attended [about homework grading]	'Gabrielle', 'Tom', 'Andy', 'Luanna', 'Eun'	['question_type_global', 'question_single_statement']
which people are affiliated with [Hudson University]	'Eun'	['question_type_global', 'question_single_statement']
What is [Tom]'s major	'english'	['question_type_local']
Which university is [this person] affiliated with?	'Barnett College'	['question_type_local']
which professors are my friends?	'Andy'	['question_type_global', 'question_two_hop_statement']
What is [that student]'s major	'biology'	['question_type_local']
which students are majoring in [food science]	'Eun'	['question_type_global', 'question_single_statement']
change [Andy]'s department to [animal science]
[Eun] will attend [the event with Tom and Andy that was last added]
Who is attending [that meeting]	'Tom', 'Andy', 'Eun'	['question_type_local']
which professors are affiliated with the [animal science] department	'Andy'	['question_type_global', 'question_single_statement']
[Luanna] will attend [that meeting]
[Eun] will attend [the meeting with Luanna about homework grading]
Who is attending [that meeting]	'Gabrielle', 'Tom', 'Luanna', 'Eun'	['question_type_local']
