create a new [meeting]
[this meeting] is [to prepare for exams]
create a [professor] named [Racquel]
[that professor] will attend [this meeting]
[Racquel] is not a friend
[this professor]'s affiliation is [Barnett College]
create a [professor] named [Albertha]
[Albertha]'s affiliation is [Barnett College]
[this person] is not a friend
[Emmie] is a [student]
[Isaiah] is a [person]
create a new [meeting]
[Emmie] will attend [this meeting]
[that meeting] is [to prepare for exams]
[this student]'s affiliation is [Harrison University]
[Emmie] is not a friend
[Racquel] will attend [the event with Emmie]
Who is attending [this meeting]	'Racquel', 'Emmie'	['question_type_local']
actually [this professor] is my friend
who are my friends?	'Racquel'	['question_type_global', 'question_single_statement']
What is [Racquel]'s affiliation?	'Barnett College'	['question_type_local']
there is a [meeting] [to prepare for exams]
[this professor] will attend [that meeting]
create a new [meeting]
there is a [meeting] [to grade papers]
[Racquel] will attend [the meeting to grade papers]
[Albertha] will attend [that meeting]
Who is attending [the meeting]	'Racquel', 'Albertha'	['question_type_local']
[Emmie] will attend [the meeting with Racquel to prepare for exams that was last added]
Who is attending [the meeting]	'Racquel', 'Emmie'	['question_type_local']
create a new [meeting]
who are my professor friends?	'Racquel'	['question_type_global', 'question_two_hop_statement']
[this student]'s major is [english]
What is [that student]'s affiliation?	'Harrison University'	['question_type_local']
create a new [meeting]
What is [she]'s major	'english'	['question_type_local']
Change major of [this student] to [accounting]
Which university is [that person] affiliated with?	'Harrison University'	['question_type_local']
who is majoring in [accounting]	'Emmie'	['question_type_global', 'question_single_statement']
there is a [meeting] [to prepare for exams]
[Isaiah] will attend [this meeting]
which students are majoring in [accounting]	'Emmie'	['question_type_global', 'question_single_statement']
[he] is a friend
[this person]'s affiliation is [Coolidge College]
there is a [meeting] [to prepare for exams]
What is [Emmie]'s major	'accounting'	['question_type_local']
who are my friends?	'Racquel', 'Isaiah'	['question_type_global', 'question_single_statement']
which people are affiliated with [Barnett College]	'Racquel', 'Albertha'	['question_type_global', 'question_single_statement']
[Emmie] will attend [this meeting]
[Isaiah] will attend [the event to grade papers]
actually [Emmie] is my friend
What is [that student]'s major	'accounting'	['question_type_local']
there is a [meeting] [to practice presentations]
create a new [meeting]
[Isaiah] will attend [the meeting to prepare for exams that was last added]
Who is attending [this meeting]	'Emmie', 'Isaiah'	['question_type_local']
who are my professor friends?	'Racquel'	['question_type_global', 'question_two_hop_statement']
which students are my friends?	'Emmie'	['question_type_global', 'question_two_hop_statement']
who are my friends?	'Racquel', 'Emmie', 'Isaiah'	['question_type_global', 'question_single_statement']
What is [that person]'s affiliation?	'Coolidge College'	['question_type_local']
there is a [meeting] [to grade papers]
Which university is [this person] affiliated with?	'Coolidge College'	['question_type_local']
who is affiliated with [Barnett College]	'Racquel', 'Albertha'	['question_type_global', 'question_single_statement']
[Albertha] will attend [the meeting]
Who is attending [the event with Racquel and Emmie to prepare for exams that was last added]	'Racquel', 'Emmie'	['question_type_local']
who are my professor friends?	'Racquel'	['question_type_global', 'question_two_hop_statement']
[Emmie] will attend [the meeting with Isaiah and Racquel]
which students are my friends?	'Emmie'	['question_type_global', 'question_two_hop_statement']
[that meeting] now is [to prepare for exams]
[Emmie] is not my friend
[that meeting] now is [about homework grading]
What is [Emmie]'s affiliation?	'Harrison University'	['question_type_local']
who is affiliated with [Coolidge College]	'Isaiah'	['question_type_global', 'question_single_statement']
who are my friends?	'Racquel', 'Isaiah'	['question_type_global', 'question_single_statement']
[Racquel] is not my friend
[the meeting] now is [to discuss future plans]
create a new [meeting]
[Isaiah] will attend [the event that was last added]
[that meeting] is [to prepare for exams]
who is affiliated with [Harrison University]	'Emmie'	['question_type_global', 'question_single_statement']
Who is attending [the event with Albertha to discuss future plans]	'Racquel', 'Albertha', 'Emmie', 'Isaiah'	['question_type_local']
who attended [to prepare for exams]	'Racquel', 'Emmie', 'Isaiah'	['question_type_global', 'question_single_statement']
there is a [meeting] [to grade papers]
[Racquel] will attend [the meeting with Isaiah to prepare for exams that was last added]
create a new [meeting]
[Albertha] will attend [that meeting]
who is affiliated with [Coolidge College]	'Isaiah'	['question_type_global', 'question_single_statement']
What is [Emmie]'s affiliation?	'Harrison University'	['question_type_local']
[Isaiah] will attend [the event]
[Emmie] will attend [the event]
[this meeting] is [to grade papers]
who are my friends?	'Isaiah'	['question_type_global', 'question_single_statement']
[Racquel] will attend [that meeting]
Who is attending [that meeting]	'Racquel', 'Albertha', 'Emmie', 'Isaiah'	['question_type_local']
there is a [meeting] [to discuss future plans]
create a new [meeting]
[the meeting that was last added] is [to grade papers]
who attended [to discuss future plans]	'Racquel', 'Albertha', 'Emmie', 'Isaiah'	['question_type_global', 'question_single_statement']
[Racquel] will attend [this meeting]
Who is attending [that meeting]	'Racquel'	['question_type_local']
What is [Racquel]'s affiliation?	'Barnett College'	['question_type_local']
which people are affiliated with [Barnett College]	'Racquel', 'Albertha'	['question_type_global', 'question_single_statement']
which students are majoring in [accounting]	'Emmie'	['question_type_global', 'question_single_statement']
who is affiliated with [Barnett College]	'Racquel', 'Albertha'	['question_type_global', 'question_single_statement']
who is majoring in [accounting]	'Emmie'	['question_type_global', 'question_single_statement']
What is [Isaiah]'s affiliation?	'Coolidge College'	['question_type_local']
who are my friends?	'Isaiah'	['question_type_global', 'question_single_statement']
[Emmie] will attend [that meeting]
What is [Emmie]'s major	'accounting'	['question_type_local']
which people are affiliated with [Barnett College]	'Racquel', 'Albertha'	['question_type_global', 'question_single_statement']
create a new [meeting]
[the meeting] is [to prepare for exams]
[Albertha] will attend [that meeting]
which people are affiliated with [Coolidge College]	'Isaiah'	['question_type_global', 'question_single_statement']
Who is attending [that meeting]	'Albertha'	['question_type_local']
Who is attending [this meeting]	'Albertha'	['question_type_local']
who attended [to discuss future plans]	'Racquel', 'Albertha', 'Emmie', 'Isaiah'	['question_type_global', 'question_single_statement']
[Emmie] will attend [that meeting]
[Racquel] will attend [the meeting]
who is majoring in [accounting]	'Emmie'	['question_type_global', 'question_single_statement']
who are my friends?	'Isaiah'	['question_type_global', 'question_single_statement']
[Isaiah] will attend [that meeting]
there is a [meeting] [about homework grading]
[Albertha] will attend [this meeting]
[Emmie] will attend [this meeting]
who attended [about homework grading]	'Albertha', 'Emmie'	['question_type_global', 'question_single_statement']
[Racquel] will attend [this meeting]
which people are affiliated with [Barnett College]	'Racquel', 'Albertha'	['question_type_global', 'question_single_statement']
Who is attending [the event]	'Racquel', 'Albertha', 'Emmie'	['question_type_local']
What is [Emmie]'s major	'accounting'	['question_type_local']
[Isaiah] will attend [this meeting]
there is a [meeting] [to grade papers]
What is [Emmie]'s affiliation?	'Harrison University'	['question_type_local']
who attended [to discuss future plans]	'Racquel', 'Albertha', 'Emmie', 'Isaiah'	['question_type_global', 'question_single_statement']
who is affiliated with [Barnett College]	'Racquel', 'Albertha'	['question_type_global', 'question_single_statement']
which students are majoring in [accounting]	'Emmie'	['question_type_global', 'question_single_statement']
there is a [meeting] [to discuss future plans]
[Isaiah] will attend [the event to grade papers that was last added]
Who is attending [this meeting]	'Isaiah'	['question_type_local']
who attended [to grade papers]	'Racquel', 'Albertha', 'Emmie', 'Isaiah'	['question_type_global', 'question_single_statement']
[Emmie] will attend [that meeting]
Which university is [Isaiah] affiliated with?	'Coolidge College'	['question_type_local']
who are my friends?	'Isaiah'	['question_type_global', 'question_single_statement']
[Racquel] will attend [this meeting]
Who is attending [that meeting]	'Racquel', 'Emmie', 'Isaiah'	['question_type_local']
actually [Emmie] is my friend
Which university is [this student] affiliated with?	'Harrison University'	['question_type_local']
which students are majoring in [accounting]	'Emmie'	['question_type_global', 'question_single_statement']
who attended [to prepare for exams]	'Racquel', 'Albertha', 'Emmie', 'Isaiah'	['question_type_global', 'question_single_statement']
there is a [meeting] [about homework grading]
[Albertha] will attend [the meeting]
create a new [meeting]
What is [she]'s affiliation?	'Barnett College'	['question_type_local']
What is [this person]'s affiliation?	'Barnett College'	['question_type_local']
[that meeting] is [to grade papers]
which students are my friends?	'Emmie'	['question_type_global', 'question_two_hop_statement']
create a new [meeting]
[the meeting that was last added] is [to prepare for exams]
[Isaiah] will attend [that meeting]
who are my friends?	'Emmie', 'Isaiah'	['question_type_global', 'question_single_statement']
[Albertha] will attend [that meeting]
Who is attending [this meeting]	'Albertha', 'Isaiah'	['question_type_local']
create a new [meeting]
who is majoring in [accounting]	'Emmie'	['question_type_global', 'question_single_statement']
Change major of [Emmie] to [english]
create a new [meeting]
create a new [meeting]
there is a [meeting] [to grade papers]
[Isaiah] will attend [the meeting with Albertha about homework grading that was last added]
Who is attending [this meeting]	'Albertha', 'Isaiah'	['question_type_local']
which people are affiliated with [Barnett College]	'Racquel', 'Albertha'	['question_type_global', 'question_single_statement']
[Emmie] will attend [this meeting]
there is a [meeting] [about homework grading]
who is majoring in [english]	'Emmie'	['question_type_global', 'question_single_statement']
there is a [meeting] [to practice presentations]
[Racquel] will attend [the event to practice presentations that was last added]
actually [she] is my friend
What is [that person]'s affiliation?	'Barnett College'	['question_type_local']
who is affiliated with [Coolidge College]	'Isaiah'	['question_type_global', 'question_single_statement']
