create a [person] named [Michael]
[that person] is a friend
who are my friends?	'Michael'	['question_type_global', 'question_single_statement']
create a new [meeting]
[that person]'s affiliation is [Greendale Community College]
What is [this person]'s affiliation?	'Greendale Community College'	['question_type_local']
[that meeting] is [to grade papers]
[he] will attend [that meeting]
Which university is [that person] affiliated with?	'Greendale Community College'	['question_type_local']
who attended [to grade papers]	'Michael'	['question_type_global', 'question_single_statement']
there is a [student] named [Francoise]
[Michael] attended [the event] late
[Francoise] will attend [this meeting]
[this person] attended [this meeting] on time
Who is attending [this meeting]	'Michael', 'Francoise'	['question_type_local']
who was late to [to grade papers]	'Michael'	['question_type_global', 'question_two_hop_statement']
there is a [professor] named [Danita]
[Danita] is not a friend
[she]'s affiliation is [Greendale Community College]
which people affiliated with [Greendale Community College] were late to [to grade papers]	'Michael'	['question_type_global', 'question_three_hop_statement']
there is a [professor] named [Gia]
Which university is [Danita] affiliated with?	'Greendale Community College'	['question_type_local']
[Gia] is a friend
[this person]'s affiliation is [Hillman College]
[Gia] will attend [the meeting]
[Luanna] is a [student]
create a [professor] named [Eun]
[this student] is a friend
[this student]'s major is [economics]
What is [that person]'s major	'economics'	['question_type_local']
who is affiliated with [Hillman College]	'Gia'	['question_type_global', 'question_single_statement']
there is a [student] named [William]
[Francoise] is not a friend
[Francoise]'s major is [computer science]
[this student]'s affiliation is [Medfield College]
What is [Francoise]'s major	'computer science'	['question_type_local']
Which university is [he] affiliated with?	'Medfield College'	['question_type_local']
which people attended meetings late	'Michael'	['question_type_global', 'question_single_statement']
who attended [to grade papers] late	'Michael'	['question_type_global', 'question_two_hop_statement']
What is [Gia]'s affiliation?	'Hillman College'	['question_type_local']
[Gia] attended [the meeting] on time
[Luanna] will attend [this meeting]
there is a [meeting] [to grade papers]
[that person] attended [the meeting with Gia to grade papers] on time
Who is attending [this meeting]	'Michael', 'Francoise', 'Gia', 'Luanna'	['question_type_local']
which students are my friends?	'Luanna'	['question_type_global', 'question_two_hop_statement']
Who was late to [that meeting]	'Michael'	['question_type_local']
Who was late to [the event]	'Michael'	['question_type_local']
which people attended meetings late	'Michael'	['question_type_global', 'question_single_statement']
actually [Francoise] is my friend
Who was late to [the event to grade papers with Francoise]	'Michael'	['question_type_local']
which people affiliated with [Greendale Community College] were late to [to grade papers]	'Michael'	['question_type_global', 'question_three_hop_statement']
was anyone who majored in [economics] in attendance?	'Luanna'	['question_type_global', 'question_two_hop_statement']
which students are my friends?	'Francoise', 'Luanna'	['question_type_global', 'question_two_hop_statement']
were any [economics] majors attending the meetings?	'Luanna'	['question_type_global', 'question_two_hop_statement']
which people affiliated with [Greendale Community College] were late	'Michael'	['question_type_global', 'question_two_hop_statement']
[she]'s affiliation is [Hillman College]
What is [he]'s affiliation?	'Medfield College'	['question_type_local']
who are my friends?	'Michael', 'Francoise', 'Gia', 'Luanna'	['question_type_global', 'question_single_statement']
who is majoring in [economics]	'Luanna'	['question_type_global', 'question_single_statement']
create a new [meeting]
[the event] is [to prepare for exams]
which people are affiliated with [Greendale Community College]	'Michael', 'Danita'	['question_type_global', 'question_single_statement']
which professors are my friends?	'Gia'	['question_type_global', 'question_two_hop_statement']
[Francoise] will attend [this meeting]
Who is attending [this meeting]	'Francoise'	['question_type_local']
which students are my friends?	'Francoise', 'Luanna'	['question_type_global', 'question_two_hop_statement']
What is [Francoise]'s affiliation?	'Medfield College'	['question_type_local']
which people attended meetings late	'Michael'	['question_type_global', 'question_single_statement']
was anyone who majored in [computer science] in attendance?	'Francoise'	['question_type_global', 'question_two_hop_statement']
What is [this student]'s major	'computer science'	['question_type_local']
was anyone affiliated with [Greendale Community College] late to [to grade papers]	'Michael'	['question_type_global', 'question_three_hop_statement']
[Francoise] attended [this meeting] late
Which university is [Francoise] affiliated with?	'Medfield College'	['question_type_local']
which students are my friends?	'Francoise', 'Luanna'	['question_type_global', 'question_two_hop_statement']
were any students affiliated with [Medfield College] in attendance to [to grade papers]	'Francoise'	['question_type_global', 'question_three_hop_statement']
[Luanna] will attend [the meeting]
which people are affiliated with [Medfield College]	'Francoise'	['question_type_global', 'question_single_statement']
were any students affiliated with [Medfield College] late to any meetings	'Francoise'	['question_type_global', 'question_three_hop_statement']
Who is attending [the meeting with Gia and Luanna]	'Michael', 'Francoise', 'Gia', 'Luanna'	['question_type_local']
which students majoring in [computer science] were late	'Francoise'	['question_type_global', 'question_two_hop_statement']
[that person] attended [this meeting] on time
[this meeting] now is [to discuss future plans]
Who was late to [this meeting]	'Francoise'	['question_type_local']
who are my professor friends?	'Gia'	['question_type_global', 'question_two_hop_statement']
which students are my friends?	'Francoise', 'Luanna'	['question_type_global', 'question_two_hop_statement']
was anyone who majored in [computer science] ever late to any meetings?	'Francoise'	['question_type_global', 'question_two_hop_statement']
which students attended meetings late	'Francoise'	['question_type_global', 'question_two_hop_statement']
What is [this student]'s major	'economics'	['question_type_local']
were any people affiliated with [Medfield College] late to [to discuss future plans]	'Francoise'	['question_type_global', 'question_three_hop_statement']
Who is attending [that meeting]	'Francoise', 'Luanna'	['question_type_local']
was anyone who majored in [economics] in attendance?	'Luanna'	['question_type_global', 'question_two_hop_statement']
there is a [meeting] [to prepare for exams]
there is a [meeting] [to grade papers]
there is a [meeting] [to discuss future plans]
[Eun] will attend [the meeting to grade papers that was last added]
[Michael] will attend [the event]
[Eun] attended [that meeting] late
[William] will attend [the event]
Who is attending [that meeting]	'Michael', 'Eun', 'William'	['question_type_local']
who are my friends?	'Michael', 'Francoise', 'Gia', 'Luanna'	['question_type_global', 'question_single_statement']
which students are my friends?	'Francoise', 'Luanna'	['question_type_global', 'question_two_hop_statement']
was anyone who majored in [computer science] in attendance?	'Francoise'	['question_type_global', 'question_two_hop_statement']
[he] is a friend
create a new [meeting]
[Michael] attended [the event with Eun] late
[Luanna] will attend [the event]
who are my professor friends?	'Gia'	['question_type_global', 'question_two_hop_statement']
who is majoring in [computer science]	'Francoise'	['question_type_global', 'question_single_statement']
were any students affiliated with [Hillman College] in attendance to [to discuss future plans]	'Luanna'	['question_type_global', 'question_three_hop_statement']
were any students affiliated with [Medfield College] late	'Francoise'	['question_type_global', 'question_three_hop_statement']
who attended [to discuss future plans]	'Francoise', 'Luanna'	['question_type_global', 'question_single_statement']
Who is attending [that meeting]	'Michael', 'Luanna', 'Eun', 'William'	['question_type_local']
Who is attending [this meeting]	'Michael', 'Luanna', 'Eun', 'William'	['question_type_local']
which students attended meetings late	'Francoise'	['question_type_global', 'question_two_hop_statement']
who is majoring in [economics]	'Luanna'	['question_type_global', 'question_single_statement']
which people attended meetings late	'Michael', 'Francoise', 'Eun'	['question_type_global', 'question_single_statement']
which students affiliated with [Medfield College] attended [to grade papers]	'Francoise'	['question_type_global', 'question_three_hop_statement']
Who is attending [the meeting with Gia]	'Michael', 'Francoise', 'Gia', 'Luanna'	['question_type_local']
Who was late to [the meeting with Gia]	'Michael'	['question_type_local']
there is a [meeting] [to grade papers]
create a new [meeting]
Which university is [Michael] affiliated with?	'Greendale Community College'	['question_type_local']
which people affiliated with [Medfield College] attended [to discuss future plans]	'Francoise'	['question_type_global', 'question_two_hop_statement']
which people affiliated with [Greendale Community College] were late	'Michael'	['question_type_global', 'question_two_hop_statement']
which students are majoring in [economics]	'Luanna'	['question_type_global', 'question_single_statement']
create a new [meeting]
[Gia] will attend [the meeting to grade papers that was last added]
[that person] attended [the event] late
[Luanna] will attend [this meeting]
[that person] attended [this meeting] late
Who was late to [this meeting]	'Gia', 'Luanna'	['question_type_local']
were any people affiliated with [Medfield College] in attendance to [to discuss future plans]	'Francoise'	['question_type_global', 'question_two_hop_statement']
which students are my friends?	'Francoise', 'Luanna', 'William'	['question_type_global', 'question_two_hop_statement']
there is a [meeting] [to discuss future plans]
was anyone who majored in [computer science] ever late to any meetings?	'Francoise'	['question_type_global', 'question_two_hop_statement']
which students majoring in [economics] were late	'Luanna'	['question_type_global', 'question_two_hop_statement']
were any students affiliated with [Hillman College] late	'Luanna'	['question_type_global', 'question_three_hop_statement']
which professors are my friends?	'Gia'	['question_type_global', 'question_two_hop_statement']
who are my friends?	'Michael', 'Francoise', 'Gia', 'Luanna', 'William'	['question_type_global', 'question_single_statement']
[this student] is not my friend
which students attended meetings late	'Francoise', 'Luanna'	['question_type_global', 'question_two_hop_statement']
which people attended meetings late	'Michael', 'Francoise', 'Gia', 'Luanna', 'Eun'	['question_type_global', 'question_single_statement']
were any [computer science] majors ever late?	'Francoise'	['question_type_global', 'question_two_hop_statement']
which people affiliated with [Greendale Community College] were late	'Michael'	['question_type_global', 'question_two_hop_statement']
who was late to [to grade papers]	'Michael', 'Gia', 'Luanna', 'Eun'	['question_type_global', 'question_two_hop_statement']
who is affiliated with [Greendale Community College]	'Michael', 'Danita'	['question_type_global', 'question_single_statement']
were any [economics] majors attending the meetings?	'Luanna'	['question_type_global', 'question_two_hop_statement']
which people [to grade papers] late	'Michael', 'Gia', 'Luanna', 'Eun'	['question_type_global', 'question_two_hop_statement']
which students attended meetings late	'Francoise', 'Luanna'	['question_type_global', 'question_two_hop_statement']
which students majoring in [computer science] were late	'Francoise'	['question_type_global', 'question_two_hop_statement']
there is a [meeting] [to grade papers]
[Eun] will attend [the meeting]
which students are majoring in [computer science]	'Francoise'	['question_type_global', 'question_single_statement']
were any [computer science] majors ever late?	'Francoise'	['question_type_global', 'question_two_hop_statement']
who are my friends?	'Michael', 'Francoise', 'Gia', 'William'	['question_type_global', 'question_single_statement']
[Luanna] will attend [that meeting]
Change major of [that student] to [computer science]
who attended [to grade papers]	'Michael', 'Francoise', 'Gia', 'Luanna', 'Eun', 'William'	['question_type_global', 'question_single_statement']
What is [Luanna]'s major	'computer science'	['question_type_local']
which students affiliated with [Hillman College] were late	'Luanna'	['question_type_global', 'question_three_hop_statement']
was anyone affiliated with [Medfield College] attended [to grade papers]	'Francoise'	['question_type_global', 'question_two_hop_statement']
who is majoring in [computer science]	'Francoise', 'Luanna'	['question_type_global', 'question_single_statement']
there is a [meeting] [to prepare for exams]
there is a [meeting] [to discuss future plans]
there is a [meeting] [to prepare for exams]
there is a [meeting] [to discuss future plans]
[Danita] will attend [the meeting with Luanna and Eun that was last added]
Who is attending [the event]	'Danita', 'Luanna', 'Eun'	['question_type_local']
which people attended meetings late	'Michael', 'Francoise', 'Gia', 'Luanna', 'Eun'	['question_type_global', 'question_single_statement']
were any people affiliated with [Greendale Community College] late to [to grade papers]	'Michael'	['question_type_global', 'question_three_hop_statement']
which students attended meetings late	'Francoise', 'Luanna'	['question_type_global', 'question_two_hop_statement']
which students are my friends?	'Francoise', 'William'	['question_type_global', 'question_two_hop_statement']
[William] will attend [that meeting]
[this student] attended [that meeting] late
[that student]'s major is [english]
[William] is not my friend
[this student]'s affiliation is [Pendleton State University]
which students majoring in [computer science] attended meetings	'Francoise', 'Luanna'	['question_type_global', 'question_two_hop_statement']
Who is attending [the meeting with Eun and Michael]	'Michael', 'Luanna', 'Eun', 'William'	['question_type_local']
who are my professor friends?	'Gia'	['question_type_global', 'question_two_hop_statement']
which students affiliated with [Hillman College] were late	'Luanna'	['question_type_global', 'question_three_hop_statement']
actually [that student] is my friend
Who is attending [the event with Francoise that was last added]	'Francoise', 'Luanna'	['question_type_local']
who is majoring in [computer science]	'Francoise', 'Luanna'	['question_type_global', 'question_single_statement']
was anyone who majored in [english] ever late to any meetings?	'William'	['question_type_global', 'question_two_hop_statement']
was anyone who majored in [english] in attendance?	'William'	['question_type_global', 'question_two_hop_statement']
Which university is [he] affiliated with?	'Pendleton State University'	['question_type_local']
there is a [meeting] [to prepare for exams]
Which university is [this student] affiliated with?	'Pendleton State University'	['question_type_local']
who is affiliated with [Medfield College]	'Francoise'	['question_type_global', 'question_single_statement']
was anyone affiliated with [Greendale Community College] attended [to grade papers]	'Michael'	['question_type_global', 'question_two_hop_statement']
was anyone affiliated with [Pendleton State University] attended [to grade papers]	'William'	['question_type_global', 'question_two_hop_statement']
who attended [to discuss future plans] late	'Francoise'	['question_type_global', 'question_two_hop_statement']
[Luanna] will attend [this meeting]
What is [Francoise]'s major	'computer science'	['question_type_local']
which students are majoring in [computer science]	'Francoise', 'Luanna'	['question_type_global', 'question_single_statement']
were any [computer science] majors attending the meetings?	'Francoise', 'Luanna'	['question_type_global', 'question_two_hop_statement']
which people attended meetings late	'Michael', 'Francoise', 'Gia', 'Luanna', 'Eun', 'William'	['question_type_global', 'question_single_statement']
there is a [meeting] [to grade papers]
which professors are my friends?	'Gia'	['question_type_global', 'question_two_hop_statement']
which people are affiliated with [Greendale Community College]	'Michael', 'Danita'	['question_type_global', 'question_single_statement']
which people [to discuss future plans] late	'Francoise'	['question_type_global', 'question_two_hop_statement']
which students are my friends?	'Francoise', 'William'	['question_type_global', 'question_two_hop_statement']
[Michael] will attend [the meeting to discuss future plans with Luanna]
[this meeting] now is [to grade papers]
[Gia] will attend [the event]
Who is attending [the event]	'Michael', 'Francoise', 'Gia', 'Luanna'	['question_type_local']
which students attended meetings late	'Francoise', 'Luanna', 'William'	['question_type_global', 'question_two_hop_statement']
Who is attending [that meeting]	'Michael', 'Francoise', 'Gia', 'Luanna'	['question_type_local']
was anyone who majored in [computer science] ever late to any meetings?	'Francoise', 'Luanna'	['question_type_global', 'question_two_hop_statement']
Who is attending [this meeting]	'Michael', 'Francoise', 'Gia', 'Luanna'	['question_type_local']
were any students affiliated with [Hillman College] late to any meetings	'Luanna'	['question_type_global', 'question_three_hop_statement']
who are my friends?	'Michael', 'Francoise', 'Gia', 'William'	['question_type_global', 'question_single_statement']
there is a [meeting] [to prepare for exams]
create a new [meeting]
[Michael] will attend [the event to prepare for exams that was last added]
[Eun] is not a friend
[that professor]'s affiliation is [Greendale Community College]
were any people affiliated with [Medfield College] late	'Francoise'	['question_type_global', 'question_two_hop_statement']
who are my professor friends?	'Gia'	['question_type_global', 'question_two_hop_statement']
which students affiliated with [Pendleton State University] were late	'William'	['question_type_global', 'question_three_hop_statement']
which students majoring in [english] were late	'William'	['question_type_global', 'question_two_hop_statement']
were any [english] majors ever late?	'William'	['question_type_global', 'question_two_hop_statement']
was anyone who majored in [english] ever late to any meetings?	'William'	['question_type_global', 'question_two_hop_statement']
were any [computer science] majors ever late?	'Francoise', 'Luanna'	['question_type_global', 'question_two_hop_statement']
who is majoring in [computer science]	'Francoise', 'Luanna'	['question_type_global', 'question_single_statement']
create a new [meeting]
there is a [meeting] [to discuss future plans]
there is a [meeting] [to discuss future plans]
[Eun] will attend [the meeting that was last added]
Who is attending [the event to prepare for exams that was last added]	'Michael'	['question_type_local']
which people [to grade papers] late	'Michael', 'Francoise', 'Gia', 'Luanna', 'Eun', 'William'	['question_type_global', 'question_two_hop_statement']
was anyone who majored in [computer science] ever late to any meetings?	'Francoise', 'Luanna'	['question_type_global', 'question_two_hop_statement']
[William] attended [the event to grade papers with Michael and Luanna that was last added] late
Who is attending [that meeting]	'Michael', 'Luanna', 'Eun', 'William'	['question_type_local']
who is majoring in [english]	'William'	['question_type_global', 'question_single_statement']
which students attended meetings late	'Francoise', 'Luanna', 'William'	['question_type_global', 'question_two_hop_statement']
Who was late to [the event]	'Michael', 'Eun', 'William'	['question_type_local']
[that student] is not my friend
there is a [meeting] [to discuss future plans]
What is [he]'s major	'english'	['question_type_local']
which students are my friends?	'Francoise'	['question_type_global', 'question_two_hop_statement']
[Michael] will attend [the event with Luanna that was last added]
there is a [meeting] [to discuss future plans]
[that meeting] now is [to grade papers]
[Gia] will attend [this meeting]
[this person] attended [that meeting] late
[Danita] will attend [that meeting]
create a new [meeting]
which people attended meetings late	'Michael', 'Francoise', 'Gia', 'Luanna', 'Eun', 'William'	['question_type_global', 'question_single_statement']
[that meeting] is [to discuss future plans]
[Francoise] will attend [this meeting]
