[Yoshiko] is a [student]
[this student]'s affiliation is [Blue Mountain State]
[Yoshiko] is a friend
[Yoshiko]'s major is [engineering]
What is [that person]'s major	'engineering'	['question_type_local']
who are my friends?	'Yoshiko'	['question_type_global', 'question_single_statement']
[Alejandra] is a [student]
What is [Yoshiko]'s affiliation?	'Blue Mountain State'	['question_type_local']
[Yoshiko] is not my friend
create a [student] named [Tom]
create a new [meeting]
there is a [meeting] [about homework grading]
[Zenaida] is a [student]
[Yoshiko] will attend [this meeting]
[Yoshiko] attended [that meeting] late
there is a [student] named [Marisela]
create a new [meeting]
[that meeting] is [to grade papers]
[Yoshiko] will attend [this meeting]
Who is attending [that meeting]	'Yoshiko'	['question_type_local']
which people affiliated with [Blue Mountain State] were late	'Yoshiko'	['question_type_global', 'question_two_hop_statement']
[Zenaida] will attend [that meeting]
[Yoshiko] attended [the event] on time
[Tom] will attend [this meeting]
there is a [meeting] [about homework grading]
[this person]'s major is [math]
[Yoshiko] will attend [that meeting]
What is [Yoshiko]'s major	'engineering'	['question_type_local']
were any people affiliated with [Blue Mountain State] in attendance to [to grade papers]	'Yoshiko'	['question_type_global', 'question_two_hop_statement']
were any students affiliated with [Blue Mountain State] in attendance to [to grade papers]	'Yoshiko'	['question_type_global', 'question_three_hop_statement']
was anyone affiliated with [Blue Mountain State] attended [about homework grading]	'Yoshiko'	['question_type_global', 'question_two_hop_statement']
were any people affiliated with [Blue Mountain State] late to [about homework grading]	'Yoshiko'	['question_type_global', 'question_three_hop_statement']
[Albertha] is a [student]
who attended [about homework grading]	'Yoshiko'	['question_type_global', 'question_single_statement']
were any students affiliated with [Blue Mountain State] attended [about homework grading]	'Yoshiko'	['question_type_global', 'question_three_hop_statement']
which people affiliated with [Blue Mountain State] attended [about homework grading]	'Yoshiko'	['question_type_global', 'question_two_hop_statement']
[Albertha]'s major is [electrical engineering]
[that person]'s affiliation is [Greendale Community College]
What is [she]'s major	'electrical engineering'	['question_type_local']
which people affiliated with [Blue Mountain State] were late	'Yoshiko'	['question_type_global', 'question_two_hop_statement']
who is majoring in [engineering]	'Yoshiko'	['question_type_global', 'question_single_statement']
which students affiliated with [Blue Mountain State] attended [to grade papers]	'Yoshiko'	['question_type_global', 'question_three_hop_statement']
were any [engineering] majors attending the meetings?	'Yoshiko'	['question_type_global', 'question_two_hop_statement']
create a new [meeting]
[Albertha] is not a friend
which people attended meetings late	'Yoshiko'	['question_type_global', 'question_single_statement']
[that meeting] is [to grade papers]
which students attended meetings late	'Yoshiko'	['question_type_global', 'question_two_hop_statement']
[Tom]'s affiliation is [Coolidge College]
[this person] is not a friend
[that student] attended [the event with Yoshiko and Tom] late
Who is attending [this meeting]	'Yoshiko', 'Tom', 'Zenaida'	['question_type_local']
were any students affiliated with [Coolidge College] in attendance to [to grade papers]	'Tom'	['question_type_global', 'question_three_hop_statement']
which students majoring in [math] were late	'Tom'	['question_type_global', 'question_two_hop_statement']
[Marisela] will attend [that meeting]
[Marisela] is not a friend
[that student]'s affiliation is [Springfield University]
[Marisela]'s major is [engineering]
which students majoring in [engineering] were late	'Yoshiko'	['question_type_global', 'question_two_hop_statement']
which people [to grade papers] late	'Tom'	['question_type_global', 'question_two_hop_statement']
create a new [meeting]
[Zenaida] will attend [that meeting]
[the meeting] is [about homework grading]
[this person] attended [the event] on time
[Tom] will attend [that meeting]
were any students affiliated with [Blue Mountain State] late	'Yoshiko'	['question_type_global', 'question_three_hop_statement']
who is majoring in [electrical engineering]	'Albertha'	['question_type_global', 'question_single_statement']
actually [that student] is my friend
who attended [about homework grading]	'Yoshiko', 'Tom', 'Zenaida'	['question_type_global', 'question_single_statement']
which people are affiliated with [Springfield University]	'Marisela'	['question_type_global', 'question_single_statement']
Which university is [he] affiliated with?	'Coolidge College'	['question_type_local']
Change major of [Tom] to [electrical engineering]
What is [he]'s major	'electrical engineering'	['question_type_local']
were any [engineering] majors ever late?	'Yoshiko'	['question_type_global', 'question_two_hop_statement']
What is [that student]'s major	'electrical engineering'	['question_type_local']
which people attended meetings late	'Yoshiko', 'Tom'	['question_type_global', 'question_single_statement']
[Yoshiko] will attend [the meeting to grade papers that was last added]
What is [this student]'s major	'engineering'	['question_type_local']
were any students affiliated with [Coolidge College] in attendance to [to grade papers]	'Tom'	['question_type_global', 'question_three_hop_statement']
which students are my friends?	'Tom'	['question_type_global', 'question_two_hop_statement']
create a new [meeting]
were any [electrical engineering] majors ever late?	'Tom'	['question_type_global', 'question_two_hop_statement']
who is majoring in [electrical engineering]	'Tom', 'Albertha'	['question_type_global', 'question_single_statement']
who attended [to grade papers]	'Yoshiko', 'Tom', 'Zenaida', 'Marisela'	['question_type_global', 'question_single_statement']
[Zenaida] will attend [that meeting]
[Tom] attended [the meeting about homework grading that was last added] on time
Who is attending [this meeting]	'Tom', 'Zenaida'	['question_type_local']
were any [engineering] majors ever late?	'Yoshiko'	['question_type_global', 'question_two_hop_statement']
which students are majoring in [engineering]	'Yoshiko', 'Marisela'	['question_type_global', 'question_single_statement']
[this meeting] now is [to prepare for exams]
which people attended meetings late	'Yoshiko', 'Tom'	['question_type_global', 'question_single_statement']
which students attended meetings late	'Yoshiko', 'Tom'	['question_type_global', 'question_two_hop_statement']
Who was late to [the meeting with Yoshiko and Marisela]	'Tom'	['question_type_local']
was anyone affiliated with [Coolidge College] attended [to grade papers]	'Tom'	['question_type_global', 'question_two_hop_statement']
which students are my friends?	'Tom'	['question_type_global', 'question_two_hop_statement']
were any [electrical engineering] majors ever late?	'Tom'	['question_type_global', 'question_two_hop_statement']
[Alejandra] will attend [that meeting]
[Alejandra] is not a friend
[Alejandra]'s major is [engineering]
[she]'s affiliation is [Blue Mountain State]
What is [Alejandra]'s major	'engineering'	['question_type_local']
there is a [meeting] [to discuss future plans]
[Albertha] will attend [that meeting]
Who is attending [the meeting to prepare for exams]	'Alejandra', 'Tom', 'Zenaida'	['question_type_local']
who attended [about homework grading]	'Yoshiko'	['question_type_global', 'question_single_statement']
which people attended meetings late	'Yoshiko', 'Tom'	['question_type_global', 'question_single_statement']
who are my friends?	'Tom'	['question_type_global', 'question_single_statement']
Change major of [she] to [math]
What is [Albertha]'s major	'math'	['question_type_local']
were any [engineering] majors attending the meetings?	'Yoshiko'	['question_type_global', 'question_two_hop_statement']
were any [electrical engineering] majors ever late?	'Tom'	['question_type_global', 'question_two_hop_statement']
which students are majoring in [electrical engineering]	'Tom'	['question_type_global', 'question_single_statement']
[Marisela] will attend [the meeting with Alejandra and Zenaida to prepare for exams]
[Marisela] attended [that meeting] late
there is a [meeting] [to discuss future plans]
What is [that person]'s affiliation?	'Springfield University'	['question_type_local']
was anyone affiliated with [Springfield University] late to any meetings	'Marisela'	['question_type_global', 'question_two_hop_statement']
which students are my friends?	'Tom'	['question_type_global', 'question_two_hop_statement']
[Zenaida] will attend [that meeting]
[she] attended [the meeting] on time
Who is attending [this meeting]	'Zenaida'	['question_type_local']
was anyone who majored in [electrical engineering] ever late to any meetings?	'Tom'	['question_type_global', 'question_two_hop_statement']
which students attended meetings late	'Yoshiko', 'Tom', 'Marisela'	['question_type_global', 'question_two_hop_statement']
were any people affiliated with [Springfield University] late	'Marisela'	['question_type_global', 'question_two_hop_statement']
[Zenaida]'s major is [math]
[this student] is not a friend
What is [Zenaida]'s major	'math'	['question_type_local']
were any students affiliated with [Blue Mountain State] in attendance to [to grade papers]	'Yoshiko'	['question_type_global', 'question_three_hop_statement']
[that person]'s affiliation is [Faber College]
who are my friends?	'Tom'	['question_type_global', 'question_single_statement']
which people attended meetings late	'Yoshiko', 'Tom', 'Marisela'	['question_type_global', 'question_single_statement']
Which university is [that student] affiliated with?	'Faber College'	['question_type_local']
[Marisela] will attend [the event with Yoshiko that was last added]
[Marisela] attended [this meeting] on time
there is a [meeting] [to discuss future plans]
who attended [to grade papers]	'Yoshiko', 'Tom', 'Zenaida', 'Marisela'	['question_type_global', 'question_single_statement']
were any students affiliated with [Springfield University] late to any meetings	'Marisela'	['question_type_global', 'question_three_hop_statement']
create a new [meeting]
[Marisela] will attend [the event to discuss future plans that was last added]
who is affiliated with [Springfield University]	'Marisela'	['question_type_global', 'question_single_statement']
which students attended meetings late	'Yoshiko', 'Tom', 'Marisela'	['question_type_global', 'question_two_hop_statement']
who attended [about homework grading] late	'Yoshiko'	['question_type_global', 'question_two_hop_statement']
Change major of [this person] to [electrical engineering]
Which university is [Marisela] affiliated with?	'Springfield University'	['question_type_local']
who attended [about homework grading]	'Yoshiko'	['question_type_global', 'question_single_statement']
which students affiliated with [Blue Mountain State] attended [to grade papers]	'Yoshiko'	['question_type_global', 'question_three_hop_statement']
who is affiliated with [Coolidge College]	'Tom'	['question_type_global', 'question_single_statement']
which people are affiliated with [Greendale Community College]	'Albertha'	['question_type_global', 'question_single_statement']
What is [Marisela]'s affiliation?	'Springfield University'	['question_type_local']
What is [she]'s major	'electrical engineering'	['question_type_local']
were any people affiliated with [Blue Mountain State] late	'Yoshiko'	['question_type_global', 'question_two_hop_statement']
What is [that student]'s major	'electrical engineering'	['question_type_local']
Which university is [she] affiliated with?	'Springfield University'	['question_type_local']
which students are majoring in [electrical engineering]	'Tom', 'Marisela'	['question_type_global', 'question_single_statement']
who was late to [about homework grading]	'Yoshiko'	['question_type_global', 'question_two_hop_statement']
which students attended meetings late	'Yoshiko', 'Tom', 'Marisela'	['question_type_global', 'question_two_hop_statement']
Change major of [Zenaida] to [engineering]
create a new [meeting]
[Albertha] will attend [the event with Yoshiko and Marisela to grade papers that was last added]
[that meeting] now is [about homework grading]
[Tom] will attend [this meeting]
create a new [meeting]
was anyone affiliated with [Faber College] attended [to prepare for exams]	'Zenaida'	['question_type_global', 'question_two_hop_statement']
were any students affiliated with [Faber College] attended [to discuss future plans]	'Zenaida'	['question_type_global', 'question_three_hop_statement']
which people attended meetings late	'Yoshiko', 'Tom', 'Marisela'	['question_type_global', 'question_single_statement']
create a new [meeting]
What is [Alejandra]'s affiliation?	'Blue Mountain State'	['question_type_local']
[Yoshiko] will attend [the meeting that was last added]
[this meeting] is [about homework grading]
[this student] attended [this meeting] late
What is [that person]'s major	'engineering'	['question_type_local']
who are my friends?	'Tom'	['question_type_global', 'question_single_statement']
Which university is [that student] affiliated with?	'Blue Mountain State'	['question_type_local']
were any students affiliated with [Springfield University] late to any meetings	'Marisela'	['question_type_global', 'question_three_hop_statement']
who attended [to discuss future plans]	'Zenaida', 'Marisela', 'Albertha'	['question_type_global', 'question_single_statement']
who attended [about homework grading] late	'Yoshiko'	['question_type_global', 'question_two_hop_statement']
were any [engineering] majors attending the meetings?	'Yoshiko', 'Zenaida'	['question_type_global', 'question_two_hop_statement']
What is [that person]'s affiliation?	'Blue Mountain State'	['question_type_local']
which people are affiliated with [Blue Mountain State]	'Yoshiko', 'Alejandra'	['question_type_global', 'question_single_statement']
who is affiliated with [Greendale Community College]	'Albertha'	['question_type_global', 'question_single_statement']
who are my friends?	'Tom'	['question_type_global', 'question_single_statement']
which students are my friends?	'Tom'	['question_type_global', 'question_two_hop_statement']
who is affiliated with [Faber College]	'Zenaida'	['question_type_global', 'question_single_statement']
which people [about homework grading] late	'Yoshiko'	['question_type_global', 'question_two_hop_statement']
What is [that student]'s affiliation?	'Blue Mountain State'	['question_type_local']
who attended [to grade papers]	'Yoshiko', 'Tom', 'Zenaida', 'Marisela'	['question_type_global', 'question_single_statement']
Which university is [Marisela] affiliated with?	'Springfield University'	['question_type_local']
which people affiliated with [Coolidge College] attended [to prepare for exams]	'Tom'	['question_type_global', 'question_two_hop_statement']
which students are my friends?	'Tom'	['question_type_global', 'question_two_hop_statement']
were any people affiliated with [Coolidge College] in attendance to [to grade papers]	'Tom'	['question_type_global', 'question_two_hop_statement']
Which university is [Yoshiko] affiliated with?	'Blue Mountain State'	['question_type_local']
who attended [about homework grading]	'Yoshiko', 'Tom', 'Marisela', 'Albertha'	['question_type_global', 'question_single_statement']
create a new [meeting]
What is [that student]'s major	'engineering'	['question_type_local']
which people [to prepare for exams] late	'Marisela'	['question_type_global', 'question_two_hop_statement']
[Marisela] will attend [the event with Yoshiko that was last added]
Who was late to [the event]	'Yoshiko'	['question_type_local']
who is majoring in [engineering]	'Yoshiko', 'Alejandra', 'Zenaida'	['question_type_global', 'question_single_statement']
which people are affiliated with [Springfield University]	'Marisela'	['question_type_global', 'question_single_statement']
who is majoring in [math]	'Albertha'	['question_type_global', 'question_single_statement']
which students attended meetings late	'Yoshiko', 'Tom', 'Marisela'	['question_type_global', 'question_two_hop_statement']
which students are majoring in [engineering]	'Yoshiko', 'Alejandra', 'Zenaida'	['question_type_global', 'question_single_statement']
[that meeting] now is [to grade papers]
who are my friends?	'Tom'	['question_type_global', 'question_single_statement']
who is affiliated with [Faber College]	'Zenaida'	['question_type_global', 'question_single_statement']
What is [Marisela]'s affiliation?	'Springfield University'	['question_type_local']
were any people affiliated with [Springfield University] in attendance to [to prepare for exams]	'Marisela'	['question_type_global', 'question_two_hop_statement']
Which university is [this student] affiliated with?	'Springfield University'	['question_type_local']
who is affiliated with [Springfield University]	'Marisela'	['question_type_global', 'question_single_statement']
Who was late to [the meeting with Tom and Yoshiko to grade papers]	'Tom'	['question_type_local']
which students are my friends?	'Tom'	['question_type_global', 'question_two_hop_statement']
were any people affiliated with [Coolidge College] late	'Tom'	['question_type_global', 'question_two_hop_statement']
Who is attending [the meeting with Tom and Yoshiko to grade papers]	'Yoshiko', 'Tom', 'Zenaida', 'Marisela'	['question_type_local']
create a new [meeting]
[Zenaida] will attend [the event that was last added]
Who is attending [that meeting]	'Zenaida'	['question_type_local']
which people attended meetings late	'Yoshiko', 'Tom', 'Marisela'	['question_type_global', 'question_single_statement']
was anyone who majored in [engineering] ever late to any meetings?	'Yoshiko'	['question_type_global', 'question_two_hop_statement']
which people affiliated with [Springfield University] were late	'Marisela'	['question_type_global', 'question_two_hop_statement']
[the meeting] is [to grade papers]
[Albertha] attended [the event with Marisela about homework grading] late
Which university is [she] affiliated with?	'Greendale Community College'	['question_type_local']
were any [engineering] majors ever late?	'Yoshiko'	['question_type_global', 'question_two_hop_statement']
[this student] will attend [the event with Marisela that was last added]
[Alejandra] will attend [that meeting]
Who was late to [the meeting about homework grading that was last added]	'Albertha'	['question_type_local']
which students affiliated with [Blue Mountain State] were late	'Yoshiko'	['question_type_global', 'question_three_hop_statement']
which people affiliated with [Greendale Community College] were late	'Albertha'	['question_type_global', 'question_two_hop_statement']
who attended [to grade papers]	'Yoshiko', 'Alejandra', 'Tom', 'Zenaida', 'Marisela', 'Albertha'	['question_type_global', 'question_single_statement']
were any students affiliated with [Greendale Community College] attended [about homework grading]	'Albertha'	['question_type_global', 'question_three_hop_statement']
What is [Yoshiko]'s major	'engineering'	['question_type_local']
was anyone who majored in [electrical engineering] in attendance?	'Tom', 'Marisela'	['question_type_global', 'question_two_hop_statement']
who is affiliated with [Coolidge College]	'Tom'	['question_type_global', 'question_single_statement']
was anyone who majored in [electrical engineering] ever late to any meetings?	'Tom', 'Marisela'	['question_type_global', 'question_two_hop_statement']
who is majoring in [electrical engineering]	'Tom', 'Marisela'	['question_type_global', 'question_single_statement']
Who was late to [that meeting]	'Yoshiko'	['question_type_local']
create a new [meeting]
who are my friends?	'Tom'	['question_type_global', 'question_single_statement']
which students are my friends?	'Tom'	['question_type_global', 'question_two_hop_statement']
which people affiliated with [Coolidge College] were late	'Tom'	['question_type_global', 'question_two_hop_statement']
[this meeting] is [to prepare for exams]
[Tom] will attend [that meeting]
[this person] attended [the event with Tom and Albertha about homework grading] on time
Who was late to [that meeting]	'Albertha'	['question_type_local']
were any [electrical engineering] majors ever late?	'Tom', 'Marisela'	['question_type_global', 'question_two_hop_statement']
[Yoshiko] attended [that meeting] on time
Who was late to [this meeting]	'Albertha'	['question_type_local']
were any students affiliated with [Greendale Community College] attended [about homework grading]	'Albertha'	['question_type_global', 'question_three_hop_statement']
were any students affiliated with [Springfield University] in attendance to [about homework grading]	'Marisela'	['question_type_global', 'question_three_hop_statement']
create a new [meeting]
Which university is [that person] affiliated with?	'Blue Mountain State'	['question_type_local']
who are my friends?	'Tom'	['question_type_global', 'question_single_statement']
was anyone who majored in [math] in attendance?	'Albertha'	['question_type_global', 'question_two_hop_statement']
[Albertha] will attend [this meeting]
there is a [meeting] [to discuss future plans]
What is [Alejandra]'s affiliation?	'Blue Mountain State'	['question_type_local']
which students are my friends?	'Tom'	['question_type_global', 'question_two_hop_statement']
which people affiliated with [Faber College] attended [to discuss future plans]	'Zenaida'	['question_type_global', 'question_two_hop_statement']
which students majoring in [engineering] attended meetings	'Yoshiko', 'Zenaida'	['question_type_global', 'question_two_hop_statement']
create a new [meeting]
which people attended meetings late	'Yoshiko', 'Tom', 'Marisela', 'Albertha'	['question_type_global', 'question_single_statement']
which people affiliated with [Springfield University] were late	'Marisela'	['question_type_global', 'question_two_hop_statement']
there is a [meeting] [to grade papers]
[Marisela] will attend [the event that was last added]
who attended [about homework grading]	'Yoshiko', 'Tom', 'Marisela', 'Albertha'	['question_type_global', 'question_single_statement']
[Zenaida] will attend [that meeting]
there is a [meeting] [about homework grading]
