[Ashly] is a [student]
[Ashly] is a friend
[this person]'s major is [economics]
[Vivienne] is a [student]
[Francoise] is a [student]
create a [person] named [Zenaida]
there is a [student] named [Bob]
[Vivienne]'s major is [philosophy]
[Vivienne]'s affiliation is [Harrison University]
[Zenaida]'s email is [Zenaida@msn.com]
[Zenaida] is a friend
[Zenaida]'s affiliation is [Coolidge College]
Which university is [that person] affiliated with?	'Coolidge College'	['question_type_local']
who are my friends?	'Ashly', 'Zenaida'	['question_type_global', 'question_single_statement']
there is a [meeting] [to discuss future plans]
[Ashly]'s email is [Ashly@yale.edu]
[that student]'s affiliation is [Coolidge College]
What is [that person]'s email	'Ashly@yale.edu'	['question_type_local']
who is affiliated with [Coolidge College]	'Ashly', 'Zenaida'	['question_type_global', 'question_single_statement']
What is [this person]'s major	'economics'	['question_type_local']
which people are affiliated with [Coolidge College]	'Ashly', 'Zenaida'	['question_type_global', 'question_single_statement']
there is a [meeting] [to grade papers]
[Ashly] will attend [that meeting]
Who is attending [that meeting]	'Ashly'	['question_type_local']
who is majoring in [economics]	'Ashly'	['question_type_global', 'question_single_statement']
which people are affiliated with [Harrison University]	'Vivienne'	['question_type_global', 'question_single_statement']
[Tereasa] is a [professor]
[that student] attended [the meeting with Ashly] on time
[Vivienne] will attend [that meeting]
Who is attending [this meeting]	'Ashly', 'Vivienne'	['question_type_local']
[that student] attended [that meeting] late
[Tereasa] will attend [this meeting]
who are my friends?	'Ashly', 'Zenaida'	['question_type_global', 'question_single_statement']
who is affiliated with [Coolidge College]	'Ashly', 'Zenaida'	['question_type_global', 'question_single_statement']
[Rey] is a [person]
were any students affiliated with [Coolidge College] in attendance to [to grade papers]	'Ashly'	['question_type_global', 'question_three_hop_statement']
were any people affiliated with [Harrison University] in attendance to [to grade papers]	'Vivienne'	['question_type_global', 'question_two_hop_statement']
[Bob] will attend [the event that was last added]
[Tereasa] attended [the event] late
[that professor]'s office is [026]
were any [philosophy] majors ever late?	'Vivienne'	['question_type_global', 'question_two_hop_statement']
[Bob] will attend [the event to discuss future plans]
which students are majoring in [philosophy]	'Vivienne'	['question_type_global', 'question_single_statement']
there is a [meeting] [to prepare for exams]
[that person] attended [the event to grade papers with Vivienne and Tereasa] late
Who is attending [this meeting]	'Ashly', 'Vivienne', 'Bob', 'Tereasa'	['question_type_local']
create a new [meeting]
create a new [meeting]
[Tereasa]'s affiliation is [Medfield College]
which people affiliated with [Medfield College] were late	'Tereasa'	['question_type_global', 'question_two_hop_statement']
who are my friends?	'Ashly', 'Zenaida'	['question_type_global', 'question_single_statement']
which students are majoring in [economics]	'Ashly'	['question_type_global', 'question_single_statement']
What is [Zenaida]'s email	'Zenaida@msn.com'	['question_type_local']
[Tereasa]'s department is [english]
What is [this person]'s affiliation?	'Medfield College'	['question_type_local']
which students majoring in [philosophy] attended meetings	'Vivienne'	['question_type_global', 'question_two_hop_statement']
which students attended meetings late	'Vivienne', 'Bob'	['question_type_global', 'question_two_hop_statement']
Where is [that person]?	'026'	['question_type_local']
who are my friends?	'Ashly', 'Zenaida'	['question_type_global', 'question_single_statement']
which professors are affiliated with the [english] department	'Tereasa'	['question_type_global', 'question_single_statement']
[Francoise] will attend [the meeting to discuss future plans]
Who is attending [that meeting]	'Francoise', 'Bob'	['question_type_local']
was anyone who majored in [economics] in attendance?	'Ashly'	['question_type_global', 'question_two_hop_statement']
who is in the [english] department	'Tereasa'	['question_type_global', 'question_single_statement']
Who was late to [the meeting to grade papers]	'Vivienne', 'Bob', 'Tereasa'	['question_type_local']
which people affiliated with [Harrison University] were late to [to grade papers]	'Vivienne'	['question_type_global', 'question_three_hop_statement']
which students are my friends?	'Ashly'	['question_type_global', 'question_two_hop_statement']
which people attended meetings late	'Vivienne', 'Bob', 'Tereasa'	['question_type_global', 'question_single_statement']
was anyone who majored in [philosophy] in attendance?	'Vivienne'	['question_type_global', 'question_two_hop_statement']
[Tereasa] is a friend
Where is [Tereasa]'s office located?	'026'	['question_type_local']
was anyone who majored in [philosophy] ever late to any meetings?	'Vivienne'	['question_type_global', 'question_two_hop_statement']
What department is [this professor] with?	'english'	['question_type_local']
who attended [to discuss future plans]	'Francoise', 'Bob'	['question_type_global', 'question_single_statement']
who are my friends?	'Ashly', 'Zenaida', 'Tereasa'	['question_type_global', 'question_single_statement']
[he] is not a friend
[he]'s affiliation is [Medfield College]
[this person]'s email is [Francoise@cornell.edu]
What department is [Tereasa] in?	'english'	['question_type_local']
were any [economics] majors attending the meetings?	'Ashly'	['question_type_global', 'question_two_hop_statement']
which people attended meetings late	'Vivienne', 'Bob', 'Tereasa'	['question_type_global', 'question_single_statement']
has anyone from the [english] department attending meetings late	'Tereasa'	['question_type_global', 'question_two_hop_statement']
[Tereasa] is not my friend
which people are affiliated with [Coolidge College]	'Ashly', 'Zenaida'	['question_type_global', 'question_single_statement']
who is affiliated with [Coolidge College]	'Ashly', 'Zenaida'	['question_type_global', 'question_single_statement']
which students are my friends?	'Ashly'	['question_type_global', 'question_two_hop_statement']
What is [she]'s affiliation?	'Medfield College'	['question_type_local']
What is [Francoise]'s affiliation?	'Medfield College'	['question_type_local']
who are my friends?	'Ashly', 'Zenaida'	['question_type_global', 'question_single_statement']
was anyone who majored in [philosophy] in attendance?	'Vivienne'	['question_type_global', 'question_two_hop_statement']
was anyone from the [english] department late to meetings?	'Tereasa'	['question_type_global', 'question_two_hop_statement']
which students majoring in [philosophy] were late	'Vivienne'	['question_type_global', 'question_two_hop_statement']
What is [Ashly]'s major	'economics'	['question_type_local']
which students attended meetings late	'Vivienne', 'Bob'	['question_type_global', 'question_two_hop_statement']
[this professor]'s email is [Tereasa@harvard.edu]
Who is attending [the meeting with Bob that was last added]	'Ashly', 'Vivienne', 'Bob', 'Tereasa'	['question_type_local']
which people attended meetings late	'Vivienne', 'Bob', 'Tereasa'	['question_type_global', 'question_single_statement']
who are my friends?	'Ashly', 'Zenaida'	['question_type_global', 'question_single_statement']
create a new [meeting]
[Tereasa] will attend [the event]
[that professor] attended [that meeting] on time
Who is attending [this meeting]	'Tereasa'	['question_type_local']
there is a [meeting] [to grade papers]
[Ashly] will attend [that meeting]
Who is attending [that meeting]	'Ashly'	['question_type_local']
Which university is [Francoise] affiliated with?	'Medfield College'	['question_type_local']
which students majoring in [economics] attended meetings	'Ashly'	['question_type_global', 'question_two_hop_statement']
were any professors affiliated with [Medfield College] attended [to grade papers]	'Tereasa'	['question_type_global', 'question_three_hop_statement']
which people are in the [english] department	'Tereasa'	['question_type_global', 'question_single_statement']
was anyone from the [english] department in attendance?	'Tereasa'	['question_type_global', 'question_two_hop_statement']
Which university is [Tereasa] affiliated with?	'Medfield College'	['question_type_local']
which people are affiliated with [Harrison University]	'Vivienne'	['question_type_global', 'question_single_statement']
which students majoring in [economics] attended meetings	'Ashly'	['question_type_global', 'question_two_hop_statement']
[Bob] will attend [this meeting]
[this person] attended [this meeting] late
[this student] attended [the event with Bob and Francoise] on time
Who is attending [that meeting]	'Francoise', 'Bob'	['question_type_local']
which students are my friends?	'Ashly'	['question_type_global', 'question_two_hop_statement']
Who is attending [this meeting]	'Francoise', 'Bob'	['question_type_local']
[Tereasa] will attend [the event with Ashly and Bob that was last added]
[Bob]'s major is [communication]
[he]'s affiliation is [Medfield College]
What is [Bob]'s major	'communication'	['question_type_local']
was anyone affiliated with [Medfield College] late to [to grade papers]	'Bob', 'Tereasa'	['question_type_global', 'question_three_hop_statement']
who attended [to discuss future plans]	'Francoise', 'Bob'	['question_type_global', 'question_single_statement']
[Bob]'s email is [Bob@yandex.com]
Change major of [he] to [accounting]
What is [that student]'s major	'accounting'	['question_type_local']
who is affiliated with [Medfield College]	'Francoise', 'Bob', 'Tereasa'	['question_type_global', 'question_single_statement']
were any students affiliated with [Harrison University] attended [to grade papers]	'Vivienne'	['question_type_global', 'question_three_hop_statement']
which people attended meetings late	'Vivienne', 'Bob', 'Tereasa'	['question_type_global', 'question_single_statement']
who are my friends?	'Ashly', 'Zenaida'	['question_type_global', 'question_single_statement']
What is [this student]'s email	'Bob@yandex.com'	['question_type_local']
which students are my friends?	'Ashly'	['question_type_global', 'question_two_hop_statement']
[Bob] is a friend
[Francoise]'s major is [accounting]
Which university is [Bob] affiliated with?	'Medfield College'	['question_type_local']
which students majoring in [philosophy] were late	'Vivienne'	['question_type_global', 'question_two_hop_statement']
which students attended meetings late	'Vivienne', 'Bob'	['question_type_global', 'question_two_hop_statement']
which people are affiliated with [Coolidge College]	'Ashly', 'Zenaida'	['question_type_global', 'question_single_statement']
What is [Francoise]'s major	'accounting'	['question_type_local']
which students majoring in [economics] attended meetings	'Ashly'	['question_type_global', 'question_two_hop_statement']
was anyone who majored in [philosophy] in attendance?	'Vivienne'	['question_type_global', 'question_two_hop_statement']
which people are affiliated with [Harrison University]	'Vivienne'	['question_type_global', 'question_single_statement']
What is [Ashly]'s email	'Ashly@yale.edu'	['question_type_local']
which students are my friends?	'Ashly', 'Bob'	['question_type_global', 'question_two_hop_statement']
has anyone from the [english] department attending meetings late	'Tereasa'	['question_type_global', 'question_two_hop_statement']
What is [Bob]'s major	'accounting'	['question_type_local']
which people are in the [english] department	'Tereasa'	['question_type_global', 'question_single_statement']
Which university is [Bob] affiliated with?	'Medfield College'	['question_type_local']
were any students affiliated with [Harrison University] in attendance to [to grade papers]	'Vivienne'	['question_type_global', 'question_three_hop_statement']
who are my friends?	'Ashly', 'Zenaida', 'Bob'	['question_type_global', 'question_single_statement']
What is [Bob]'s email	'Bob@yandex.com'	['question_type_local']
were any professors affiliated with [Medfield College] late	'Tereasa'	['question_type_global', 'question_three_hop_statement']
was anyone affiliated with [english] attending the meetings?	'Tereasa'	['question_type_global', 'question_two_hop_statement']
which students are my friends?	'Ashly', 'Bob'	['question_type_global', 'question_two_hop_statement']
which people attended meetings late	'Vivienne', 'Bob', 'Tereasa'	['question_type_global', 'question_single_statement']
Which university is [Bob] affiliated with?	'Medfield College'	['question_type_local']
who is affiliated with [Coolidge College]	'Ashly', 'Zenaida'	['question_type_global', 'question_single_statement']
What is [Tereasa]'s email	'Tereasa@harvard.edu'	['question_type_local']
was anyone who majored in [philosophy] in attendance?	'Vivienne'	['question_type_global', 'question_two_hop_statement']
was anyone who majored in [accounting] ever late to any meetings?	'Bob'	['question_type_global', 'question_two_hop_statement']
there is a [meeting] [to discuss future plans]
Which university is [he] affiliated with?	'Medfield College'	['question_type_local']
which people are in the [english] department	'Tereasa'	['question_type_global', 'question_single_statement']
[Zenaida] will attend [the event to grade papers with Tereasa that was last added]
Which university is [that person] affiliated with?	'Coolidge College'	['question_type_local']
which people affiliated with [Medfield College] were late	'Bob', 'Tereasa'	['question_type_global', 'question_two_hop_statement']
which students attended meetings late	'Vivienne', 'Bob'	['question_type_global', 'question_two_hop_statement']
which people are affiliated with [Medfield College]	'Francoise', 'Bob', 'Tereasa'	['question_type_global', 'question_single_statement']
which people attended meetings late	'Vivienne', 'Bob', 'Tereasa'	['question_type_global', 'question_single_statement']
[Tereasa] attended [this meeting] late
Who was late to [that meeting]	'Bob', 'Tereasa'	['question_type_local']
Who is attending [the event with Francoise and Bob]	'Francoise', 'Bob'	['question_type_local']
was anyone affiliated with [Medfield College] attended [to discuss future plans]	'Bob'	['question_type_global', 'question_two_hop_statement']
was anyone who majored in [philosophy] ever late to any meetings?	'Vivienne'	['question_type_global', 'question_two_hop_statement']
[Rey]'s affiliation is [Harrison University]
create a new [meeting]
[he]'s email is [Rey@yale.edu]
[that person] is a friend
What is [Rey]'s affiliation?	'Harrison University'	['question_type_local']
which students are my friends?	'Ashly', 'Bob'	['question_type_global', 'question_two_hop_statement']
who is majoring in [accounting]	'Francoise', 'Bob'	['question_type_global', 'question_single_statement']
Which university is [Rey] affiliated with?	'Harrison University'	['question_type_local']
has anyone from the [english] department attending meetings	'Tereasa'	['question_type_global', 'question_two_hop_statement']
create a new [meeting]
What is [this person]'s affiliation?	'Harrison University'	['question_type_local']
was anyone who majored in [economics] in attendance?	'Ashly'	['question_type_global', 'question_two_hop_statement']
which people are in the [english] department	'Tereasa'	['question_type_global', 'question_single_statement']
who is majoring in [philosophy]	'Vivienne'	['question_type_global', 'question_single_statement']
which students are my friends?	'Ashly', 'Bob'	['question_type_global', 'question_two_hop_statement']
What is [that person]'s email	'Rey@yale.edu'	['question_type_local']
which students attended meetings late	'Vivienne', 'Bob'	['question_type_global', 'question_two_hop_statement']
What is [that person]'s affiliation?	'Harrison University'	['question_type_local']
which people attended meetings late	'Vivienne', 'Bob', 'Tereasa'	['question_type_global', 'question_single_statement']
Who is attending [the event with Vivienne and Ashly]	'Ashly', 'Vivienne', 'Bob', 'Tereasa'	['question_type_local']
was anyone from the [english] department late to meetings?	'Tereasa'	['question_type_global', 'question_two_hop_statement']
was anyone who majored in [accounting] in attendance?	'Bob'	['question_type_global', 'question_two_hop_statement']
[Vivienne] will attend [that meeting]
[that student] attended [the event] on time
there is a [meeting] [to discuss future plans]
[this student]'s email is [Vivienne@yale.edu]
[this person] is a friend
What is [that student]'s major	'philosophy'	['question_type_local']
has anyone from the [english] department attending meetings	'Tereasa'	['question_type_global', 'question_two_hop_statement']
create a new [meeting]
Who is attending [the meeting with Tereasa and Zenaida to grade papers]	'Ashly', 'Zenaida', 'Bob', 'Tereasa'	['question_type_local']
has anyone from the [english] department attending meetings late	'Tereasa'	['question_type_global', 'question_two_hop_statement']
[that meeting] is [to practice presentations]
[Ashly] will attend [this meeting]
What is [Francoise]'s affiliation?	'Medfield College'	['question_type_local']
who is majoring in [philosophy]	'Vivienne'	['question_type_global', 'question_single_statement']
Change major of [Vivienne] to [accounting]
Who is attending [the meeting to grade papers with Vivienne]	'Ashly', 'Vivienne', 'Bob', 'Tereasa'	['question_type_local']
which people affiliated with [Harrison University] were late	'Vivienne'	['question_type_global', 'question_two_hop_statement']
who attended [to practice presentations]	'Ashly'	['question_type_global', 'question_single_statement']
were any people affiliated with [Medfield College] late	'Bob', 'Tereasa'	['question_type_global', 'question_two_hop_statement']
who is affiliated with [Harrison University]	'Vivienne', 'Rey'	['question_type_global', 'question_single_statement']
Change major of [Ashly] to [accounting]
What is [Vivienne]'s email	'Vivienne@yale.edu'	['question_type_local']
What is [Ashly]'s major	'accounting'	['question_type_local']
was anyone from the [english] department in attendance?	'Tereasa'	['question_type_global', 'question_two_hop_statement']
who attended [to discuss future plans]	'Francoise', 'Bob'	['question_type_global', 'question_single_statement']
who are my friends?	'Ashly', 'Vivienne', 'Zenaida', 'Bob', 'Rey'	['question_type_global', 'question_single_statement']
which people are affiliated with [Harrison University]	'Vivienne', 'Rey'	['question_type_global', 'question_single_statement']
What is [Zenaida]'s email	'Zenaida@msn.com'	['question_type_local']
which students majoring in [accounting] attended meetings	'Ashly', 'Vivienne', 'Bob'	['question_type_global', 'question_two_hop_statement']
which students attended meetings late	'Vivienne', 'Bob'	['question_type_global', 'question_two_hop_statement']
Change major of [Vivienne] to [communication]
Which university is [Ashly] affiliated with?	'Coolidge College'	['question_type_local']
was anyone who majored in [accounting] ever late to any meetings?	'Bob'	['question_type_global', 'question_two_hop_statement']
What is [Ashly]'s affiliation?	'Coolidge College'	['question_type_local']
which students affiliated with [Medfield College] attended [to discuss future plans]	'Bob'	['question_type_global', 'question_three_hop_statement']
which students are my friends?	'Ashly', 'Vivienne', 'Bob'	['question_type_global', 'question_two_hop_statement']
has anyone from the [english] department attending meetings late	'Tereasa'	['question_type_global', 'question_two_hop_statement']
was anyone affiliated with [english] attending the meetings?	'Tereasa'	['question_type_global', 'question_two_hop_statement']
which people attended meetings late	'Vivienne', 'Bob', 'Tereasa'	['question_type_global', 'question_single_statement']
Who was late to [the meeting with Bob and Tereasa to grade papers that was last added]	'Bob', 'Tereasa'	['question_type_local']
who are my friends?	'Ashly', 'Vivienne', 'Zenaida', 'Bob', 'Rey'	['question_type_global', 'question_single_statement']
which students majoring in [communication] were late	'Vivienne'	['question_type_global', 'question_two_hop_statement']
What is [Ashly]'s affiliation?	'Coolidge College'	['question_type_local']
which students are my friends?	'Ashly', 'Vivienne', 'Bob'	['question_type_global', 'question_two_hop_statement']
which people are in the [english] department	'Tereasa'	['question_type_global', 'question_single_statement']
there is a [meeting] [to discuss future plans]
there is a [meeting] [to discuss future plans]
there is a [meeting] [to grade papers]
Change major of [Ashly] to [electrical engineering]
create a new [meeting]
[Bob] will attend [the event to grade papers that was last added]
What is [that person]'s major	'accounting'	['question_type_local']
Which university is [he] affiliated with?	'Medfield College'	['question_type_local']
was anyone affiliated with [english] attending the meetings?	'Tereasa'	['question_type_global', 'question_two_hop_statement']
which people attended meetings late	'Vivienne', 'Bob', 'Tereasa'	['question_type_global', 'question_single_statement']
which professors are affiliated with the [english] department	'Tereasa'	['question_type_global', 'question_single_statement']
What is [this student]'s email	'Bob@yandex.com'	['question_type_local']
were any [accounting] majors attending the meetings?	'Bob'	['question_type_global', 'question_two_hop_statement']
What is [this person]'s major	'accounting'	['question_type_local']
which students are majoring in [accounting]	'Francoise', 'Bob'	['question_type_global', 'question_single_statement']
was anyone affiliated with [english] attending any meetings late?	'Tereasa'	['question_type_global', 'question_two_hop_statement']
who are my friends?	'Ashly', 'Vivienne', 'Zenaida', 'Bob', 'Rey'	['question_type_global', 'question_single_statement']
[Tereasa] will attend [the meeting]
[Bob] attended [this meeting] on time
which students attended meetings late	'Vivienne', 'Bob'	['question_type_global', 'question_two_hop_statement']
What is [this student]'s email	'Bob@yandex.com'	['question_type_local']
which students are my friends?	'Ashly', 'Vivienne', 'Bob'	['question_type_global', 'question_two_hop_statement']
[Tereasa] attended [the meeting] on time
Who is attending [this meeting]	'Bob', 'Tereasa'	['question_type_local']
were any people affiliated with [Harrison University] late	'Vivienne'	['question_type_global', 'question_two_hop_statement']
[Francoise] attended [the meeting to discuss future plans with Francoise and Bob] late
[Vivienne] will attend [the event]
Which university is [this student] affiliated with?	'Harrison University'	['question_type_local']
which students majoring in [electrical engineering] attended meetings	'Ashly'	['question_type_global', 'question_two_hop_statement']
was anyone affiliated with [english] attending the meetings?	'Tereasa'	['question_type_global', 'question_two_hop_statement']
Change major of [that student] to [electrical engineering]
there is a [meeting] [about homework grading]
[Ashly] will attend [that meeting]
[Ashly] attended [this meeting] on time
Who is attending [that meeting]	'Ashly'	['question_type_local']
who attended [about homework grading]	'Ashly'	['question_type_global', 'question_single_statement']
which students attended meetings late	'Vivienne', 'Francoise', 'Bob'	['question_type_global', 'question_two_hop_statement']
was anyone from the [english] department late to meetings?	'Tereasa'	['question_type_global', 'question_two_hop_statement']
What is [Zenaida]'s affiliation?	'Coolidge College'	['question_type_local']
which people affiliated with [Harrison University] were late to [to grade papers]	'Vivienne'	['question_type_global', 'question_three_hop_statement']
has anyone from the [english] department attending meetings	'Tereasa'	['question_type_global', 'question_two_hop_statement']
Who is attending [the meeting with Ashly and Vivienne to grade papers]	'Ashly', 'Vivienne', 'Bob', 'Tereasa'	['question_type_local']
who are my friends?	'Ashly', 'Vivienne', 'Zenaida', 'Bob', 'Rey'	['question_type_global', 'question_single_statement']
Which university is [that student] affiliated with?	'Coolidge College'	['question_type_local']
which students attended meetings late	'Vivienne', 'Francoise', 'Bob'	['question_type_global', 'question_two_hop_statement']
who is affiliated with [Medfield College]	'Francoise', 'Bob', 'Tereasa'	['question_type_global', 'question_single_statement']
which people affiliated with [Medfield College] were late to [to grade papers]	'Bob', 'Tereasa'	['question_type_global', 'question_three_hop_statement']
was anyone affiliated with [english] attending any meetings late?	'Tereasa'	['question_type_global', 'question_two_hop_statement']
[Bob] will attend [that meeting]
[Tereasa] will attend [that meeting]
[Rey] will attend [this meeting]
[Bob] attended [the meeting] on time
actually [Tereasa] is my friend
What department is [that professor] with?	'english'	['question_type_local']
which people attended meetings late	'Vivienne', 'Francoise', 'Bob', 'Tereasa'	['question_type_global', 'question_single_statement']
who is majoring in [electrical engineering]	'Ashly', 'Vivienne'	['question_type_global', 'question_single_statement']
which students are my friends?	'Ashly', 'Vivienne', 'Bob'	['question_type_global', 'question_two_hop_statement']
who is affiliated with [Medfield College]	'Francoise', 'Bob', 'Tereasa'	['question_type_global', 'question_single_statement']
create a new [meeting]
What is [Bob]'s email	'Bob@yandex.com'	['question_type_local']
was anyone who majored in [accounting] ever late to any meetings?	'Francoise', 'Bob'	['question_type_global', 'question_two_hop_statement']
were any people affiliated with [Harrison University] late	'Vivienne'	['question_type_global', 'question_two_hop_statement']
has anyone from the [english] department attending meetings	'Tereasa'	['question_type_global', 'question_two_hop_statement']
Who is attending [the meeting about homework grading with Bob]	'Ashly', 'Bob', 'Tereasa', 'Rey'	['question_type_local']
who is affiliated with [Harrison University]	'Vivienne', 'Rey'	['question_type_global', 'question_single_statement']
which students are my friends?	'Ashly', 'Vivienne', 'Bob'	['question_type_global', 'question_two_hop_statement']
were any people affiliated with [Medfield College] in attendance to [to discuss future plans]	'Francoise', 'Bob'	['question_type_global', 'question_two_hop_statement']
who are my friends?	'Ashly', 'Vivienne', 'Zenaida', 'Bob', 'Tereasa', 'Rey'	['question_type_global', 'question_single_statement']
who are my professor friends?	'Tereasa'	['question_type_global', 'question_two_hop_statement']
was anyone who majored in [electrical engineering] in attendance?	'Ashly', 'Vivienne'	['question_type_global', 'question_two_hop_statement']
create a new [meeting]
Who was late to [the meeting with Bob and Zenaida to grade papers]	'Bob', 'Tereasa'	['question_type_local']
which students attended meetings late	'Vivienne', 'Francoise', 'Bob'	['question_type_global', 'question_two_hop_statement']
[the event that was last added] is [to discuss future plans]
were any students affiliated with [Medfield College] attended [to discuss future plans]	'Francoise', 'Bob'	['question_type_global', 'question_three_hop_statement']
What is [Tereasa]'s email	'Tereasa@harvard.edu'	['question_type_local']
were any students affiliated with [Harrison University] late to any meetings	'Vivienne'	['question_type_global', 'question_three_hop_statement']
has anyone from the [english] department attending meetings	'Tereasa'	['question_type_global', 'question_two_hop_statement']
were any students affiliated with [Medfield College] attended [to grade papers]	'Bob'	['question_type_global', 'question_three_hop_statement']
[Francoise] will attend [that meeting]
What is [this person]'s email	'Francoise@cornell.edu'	['question_type_local']
which students are my friends?	'Ashly', 'Vivienne', 'Bob'	['question_type_global', 'question_two_hop_statement']
were any people affiliated with [Medfield College] in attendance to [to grade papers]	'Bob', 'Tereasa'	['question_type_global', 'question_two_hop_statement']
who is in the [english] department	'Tereasa'	['question_type_global', 'question_single_statement']
[Zenaida] will attend [this meeting]
Who is attending [this meeting]	'Francoise', 'Zenaida'	['question_type_local']
who are my friends?	'Ashly', 'Vivienne', 'Zenaida', 'Bob', 'Tereasa', 'Rey'	['question_type_global', 'question_single_statement']
[Vivienne] is not my friend
What is [Vivienne]'s major	'electrical engineering'	['question_type_local']
were any students affiliated with [Harrison University] late	'Vivienne'	['question_type_global', 'question_three_hop_statement']
