[Rey] is a masters student
the affiliation of [that student] is [asian studies]
[Milagros] is a masters student
the affiliation of [she] is [physics]
There is a course called [U302]
[this person] and [Rey] are both enrolled in [that class]
Who is taking the U302 course	'Rey', 'Milagros'	['question_type_global', 'question_single_statement']
who are the students?	'Rey', 'Milagros'	['question_type_global', 'question_single_statement']
Which courses did [she] enroll in?	'U302'	['question_type_local']
Who are the students in the [physics] department	'Milagros'	['question_type_global', 'question_two_hop_statement']
who are the masters students?	'Rey', 'Milagros'	['question_type_global', 'question_single_statement']
there is a masters student named [Hiram]
[Hiram]'s department is [animal science]
What courses is [Milagros] taking?	'U302'	['question_type_local']
[Gia] is a [full] [professor]
What students are in the [animal science] department?	'Hiram'	['question_type_global', 'question_two_hop_statement']
There is a [undergraduate] [mini course] called [G203]
[Hiram] and [Rey] are taking [that class]
[Gia] is the instructor for [G203]
Who is teaching [that course]?	'Gia'	['question_type_local']
Who is part of the [physics] department	'Milagros'	['question_type_global', 'question_single_statement']
[Hiram] is attending [that course]
What courses is [he] taking?	'G203'	['question_type_local']
The TA for [that course] is [Rey]
Which professors are teaching [undergraduate] courses?	'Gia'	['question_type_global', 'question_two_hop_statement']
[Hiram] is attending [G203]
What students are going to TA [G203]?	'Rey'	['question_type_local']
[that course] is a 2 unit course
[Milagros] and [Hiram] are TAing [G203]
Who is teaching [G203]?	'Gia'	['question_type_local']
Who is part of the [animal science] department	'Hiram'	['question_type_global', 'question_single_statement']
[Willis] is a [professor]
What are the courses that [Milagros] is enrolled in?	'U302'	['question_type_local']
Which are some [undergraduate] courses that masters students take?	'G203'	['question_type_global', 'question_three_hop_statement']
Which courses are TAed by [Rey]?	'G203'	['question_type_local']
What are the 2 unit courses?	'G203'	['question_type_global', 'question_single_statement']
Which courses have masters student TAs?	'G203'	['question_type_global', 'question_two_hop_statement']
What are the courses that [Hiram] is enrolled in?	'G203'	['question_type_local']
Which courses are TAed by masters students?	'G203'	['question_type_global', 'question_two_hop_statement']
there is a [first year] PhD student named [Alverta]
[Alverta] is in [Clare Building]
[Willis] is on [this student]'s committee
What professors are on [Alverta]'s committee	'Willis'	['question_type_local']
Which are some courses that no phd student is taking?	'U302', 'G203'	['question_type_global', 'question_two_hop_statement']
create a [professor] named [Igor]
[Igor] advises [Alverta]
[Igor] research interest is in [evolution]
What is [this professor] research area?	'evolution'	['question_type_local']
[second year] is a [Will] PhD student
[this student] passed the qualifiers
Who has [Willis] on their phd committee?	'Alverta'	['question_type_local']
who are the masters students?	'Rey', 'Milagros', 'Hiram'	['question_type_global', 'question_single_statement']
[Willis] advises [Will]
[that professor] received funding
[that professor] conducts research in [evolution]
Which phd students does [Igor] advise?	'Alverta'	['question_type_local']
What are the courses TAed by [Hiram]?	'G203'	['question_type_local']
Which courses are offered this semester?	'U302', 'G203'	['question_type_global', 'question_single_statement']
Which students are in their [first year]	'Alverta'	['question_type_global', 'question_single_statement']
who are the phd students?	'Alverta', 'Will'	['question_type_global', 'question_single_statement']
[Cecil] is a masters student
[Alverta] has failed the qualifying exam
[she] successfully defended their thesis
What professors are on [she]'s committee	'Willis'	['question_type_local']
Who are the [full] professors?	'Gia'	['question_type_global', 'question_single_statement']
Which professors advise students who passed their defense?	'Igor'	['question_type_global', 'question_two_hop_statement']
[this student] is in [second year]
[this student] has passed the thesis proposal exam
Which courses are TAed by [Hiram]?	'G203'	['question_type_local']
Which professors have an [full] status?	'Gia'	['question_type_global', 'question_single_statement']
[Will] has passed the thesis proposal exam
What are the [undergraduate] courses?	'G203'	['question_type_global', 'question_single_statement']
who are the students?	'Rey', 'Milagros', 'Hiram', 'Alverta', 'Will', 'Cecil'	['question_type_global', 'question_single_statement']
Which professors are teaching [undergraduate] courses?	'Gia'	['question_type_global', 'question_two_hop_statement']
there is a new PhD student named [Lorilee]
[he] is now a [third year] student
what courses have masters students taking them?	'U302', 'G203'	['question_type_global', 'question_two_hop_statement']
Who are the professors working on [evolution]?	'Willis', 'Igor'	['question_type_global', 'question_single_statement']
there is a new [fifth year] PhD student named [Zenaida]
What students are enrolled in [U302]?	'Rey', 'Milagros'	['question_type_local']
which students passed the defense?	'Alverta'	['question_type_global', 'question_single_statement']
[he] is in [Hallems Building]
What students are advised by a professor with funding?	'Will'	['question_type_global', 'question_two_hop_statement']
[she] currently has funding
[Zenaida] did not pass the qualifiers
What masters students are taking G203	'Rey', 'Hiram'	['question_type_global', 'question_two_hop_statement']
What students are in the [animal science] department?	'Hiram'	['question_type_global', 'question_two_hop_statement']
what [undergraduate] courses have no phd students taking them?	'G203'	['question_type_global', 'question_three_hop_statement']
There is a [undergraduate] course called [U201]
[that student] is now a [sixth year] student
Which students are advised by professors working on [evolution]?	'Alverta', 'Will'	['question_type_global', 'question_two_hop_statement']
[she] has passed the thesis proposal exam
[this person] successfully defended their thesis
What professors are on [Alverta]'s committee	'Willis'	['question_type_local']
What courses is [Gia] teaching?	'G203'	['question_type_local']
which courses have no masters students enrolled?	'U201'	['question_type_global', 'question_two_hop_statement']
Who is teaching [undergraduate] courses?	'Gia'	['question_type_global', 'question_two_hop_statement']
there is a PhD student named [Albertha]
who are the phd students?	'Alverta', 'Will', 'Lorilee', 'Zenaida', 'Albertha'	['question_type_global', 'question_single_statement']
create a [teaching] [professor] named [Tereasa]
[that student] has [Willis] and [Igor] on the committee
Which people are in the [animal science] department?	'Hiram'	['question_type_global', 'question_single_statement']
which students passed the defense?	'Alverta', 'Zenaida'	['question_type_global', 'question_single_statement']
Which students have offices in Clare Building	'Alverta'	['question_type_global', 'question_two_hop_statement']
Which students are funded?	'Zenaida'	['question_type_global', 'question_single_statement']
[Stephine] is a [professor]
[Stephine]'s research interest is [evolution]
[this person] currently has funding
Who has an advisor with funding?	'Will'	['question_type_global', 'question_two_hop_statement']
What students are taking U302	'Rey', 'Milagros'	['question_type_global', 'question_single_statement']
[Britney] is a PhD student
[Stephine] advises [Britney]
What is [that professor] research area?	'evolution'	['question_type_local']
Who are the professors working on [evolution]?	'Willis', 'Igor', 'Stephine'	['question_type_global', 'question_single_statement']
Which [third year] students are advised by professors working on [evolution]?	'Will'	['question_type_global', 'question_three_hop_statement']
Which courses are [undergraduate] level courses?	'G203', 'U201'	['question_type_global', 'question_single_statement']
What students are going to TA [G203]?	'Rey', 'Milagros', 'Hiram'	['question_type_local']
which [undergraduate] courses have no phd students enrolled?	'G203', 'U201'	['question_type_global', 'question_three_hop_statement']
[Alverta] is enrolled in [G203]
Who is currently TAing [this course]?	'Rey', 'Milagros', 'Hiram'	['question_type_local']
which [undergraduate] courses have some phd students enrolled?	'G203'	['question_type_global', 'question_three_hop_statement']
The TA for [this course] is [Britney]
Who is enrolled in [this course]?	'Rey', 'Hiram', 'Alverta'	['question_type_local']
which courses have some phd students enrolled?	'G203'	['question_type_global', 'question_two_hop_statement']
Who is taking the G203 course	'Rey', 'Hiram', 'Alverta'	['question_type_global', 'question_single_statement']
Which professors are teaching [mini course]?	'Gia'	['question_type_global', 'question_two_hop_statement']
[Zenaida] has [Gia] and [Igor] on the committee
Which professors advise students who passed their defense?	'Igor'	['question_type_global', 'question_two_hop_statement']
there is a [professor] named [Andrew]
What is [Willis]'s research focus?	'evolution'	['question_type_local']
What students are taking U302	'Rey', 'Milagros'	['question_type_global', 'question_single_statement']
Which courses are offered this semester?	'U302', 'G203', 'U201'	['question_type_global', 'question_single_statement']
[Willis] advises [Zenaida] and [Lorilee]
Who is [Zenaida]'s advisor?	'Willis'	['question_type_local']
which students passed the qualifying exam?	'Will'	['question_type_global', 'question_single_statement']
Which are some courses that phd students take?	'G203'	['question_type_global', 'question_two_hop_statement']
What professors advise students who passed their thesis proposal?	'Willis', 'Igor'	['question_type_global', 'question_two_hop_statement']
Which are some [undergraduate] courses that masters students take?	'G203'	['question_type_global', 'question_three_hop_statement']
Who are the [full] professors?	'Gia'	['question_type_global', 'question_single_statement']
Which courses are TAed by masters students?	'G203'	['question_type_global', 'question_two_hop_statement']
There is a [phd] level course called [G601]
[that course] will be a mini course
Who is on [Albertha]'s committee?	'Willis', 'Igor'	['question_type_local']
who are the students?	'Rey', 'Milagros', 'Hiram', 'Alverta', 'Will', 'Cecil', 'Lorilee', 'Zenaida', 'Albertha', 'Britney'	['question_type_global', 'question_single_statement']
Who is in [Hallems Building]	'Will'	['question_type_global', 'question_two_hop_statement']
there is a PhD student named [Tawnya]
[this person] passed thesis defense
[that person] has failed the thesis proposal exam
[this student] passed the qualifiers
[this person] has failed the thesis proposal exam
Which courses have masters student TAs?	'G203'	['question_type_global', 'question_two_hop_statement']
[fifth year] is a [Casey] PhD student
[she] has failed the thesis proposal exam
Which students's advisors are conducting research in [evolution]	'Alverta', 'Will', 'Lorilee', 'Zenaida', 'Britney'	['question_type_global', 'question_two_hop_statement']
What professors advise students who passed their thesis qualifiers?	'Willis'	['question_type_global', 'question_two_hop_statement']
What are the [phd] courses?	'G601'	['question_type_global', 'question_single_statement']
[he] successfully defended their thesis
[he] is in [Hallems Building]
Which courses are TAed by [Hiram]?	'G203'	['question_type_local']
Who are the professors working on [evolution]?	'Willis', 'Igor', 'Stephine'	['question_type_global', 'question_single_statement']
[Charlott] is a PhD student
[he] currently has funding
[he] passed the qualifiers
Which professors advise students who passed their defense?	'Willis', 'Igor'	['question_type_global', 'question_two_hop_statement']
Who in third year has an advisor with funding?	'Will'	['question_type_global', 'question_three_hop_statement']
who are the masters students?	'Rey', 'Milagros', 'Hiram', 'Cecil'	['question_type_global', 'question_single_statement']
Which masters students taking the U302 course	'Rey', 'Milagros'	['question_type_global', 'question_two_hop_statement']
[Alverta] did not pass the qualifiers
which [undergraduate] courses have some masters students enrolled?	'G203'	['question_type_global', 'question_three_hop_statement']
Which professors advise students who passed their proposal?	'Willis', 'Igor'	['question_type_global', 'question_two_hop_statement']
Who is teaching [mini course]?	'Gia'	['question_type_global', 'question_two_hop_statement']
which students passed the defense?	'Alverta', 'Zenaida', 'Tawnya', 'Casey'	['question_type_global', 'question_single_statement']
[Willis] advises [Casey]
Which phd students does [Willis] advise?	'Will', 'Lorilee', 'Zenaida', 'Casey'	['question_type_local']
Which courses have phd student TAs?	'G203'	['question_type_global', 'question_two_hop_statement']
[Charlott] and [Tawnya] are [this professor]'s student
which courses have some masters students enrolled?	'U302', 'G203'	['question_type_global', 'question_two_hop_statement']
Which professors advise students who passed their defense?	'Willis', 'Igor'	['question_type_global', 'question_two_hop_statement']
Which [third year] students are advised by professors working on [evolution]?	'Will'	['question_type_global', 'question_three_hop_statement']
Which courses are TAed by masters students?	'G203'	['question_type_global', 'question_two_hop_statement']
[Charlott] passed thesis proposal
[Charlott] is funded
Who is on [Alverta]'s committee?	'Willis'	['question_type_local']
which students passed the proposal exam?	'Alverta', 'Will', 'Zenaida', 'Charlott'	['question_type_global', 'question_single_statement']
Who has an advisor with funding?	'Will', 'Lorilee', 'Zenaida', 'Britney', 'Tawnya', 'Casey', 'Charlott'	['question_type_global', 'question_two_hop_statement']
Who advises [Zenaida]?	'Willis'	['question_type_local']
Which [third year] students's advisors are conducting research in [evolution]	'Will'	['question_type_global', 'question_three_hop_statement']
who are the phd students?	'Alverta', 'Will', 'Lorilee', 'Zenaida', 'Albertha', 'Britney', 'Tawnya', 'Casey', 'Charlott'	['question_type_global', 'question_single_statement']
There is a [undergraduate] level [mini course] called [U610]
[this course] has 2 units
Who does [Willis] advise?	'Will', 'Lorilee', 'Zenaida', 'Tawnya', 'Casey', 'Charlott'	['question_type_local']
Who is in [Clare Building]	'Alverta'	['question_type_global', 'question_two_hop_statement']
which courses have some masters students enrolled?	'U302', 'G203'	['question_type_global', 'question_two_hop_statement']
Which students have offices in Hallems Building	'Will', 'Casey'	['question_type_global', 'question_two_hop_statement']
Create a new course called [G303]
[G303] is a 8 unit course
Who is part of the [physics] department	'Milagros'	['question_type_global', 'question_single_statement']
Which courses are offered this semester?	'U302', 'G203', 'U201', 'G601', 'U610', 'G303'	['question_type_global', 'question_single_statement']
there is a [professor] named [Peggy]
[Lorilee] and [Zenaida] are TAs for [G303]
[G303] is full semester
Which courses are [mini course]	'G203', 'G601', 'U610'	['question_type_global', 'question_single_statement']
Which [fifth year] students's advisors are conducting research in [evolution]	'Casey'	['question_type_global', 'question_three_hop_statement']
[Tawnya] and [Cecil] are TAs for [that class]
[Igor] teaches [G303]
[Andrew] and [Gia] are on [Alverta]'s committee
What students are taking courses and TAing?	'Rey', 'Milagros', 'Hiram'	['question_type_global', 'question_two_hop_statement']
[Andrew] advises [Albertha]
[that professor]'s research interest is [programming languages]
Which courses are TAed by [Rey]?	'G203'	['question_type_local']
which [undergraduate] courses have no phd students enrolled?	'U201', 'U610'	['question_type_global', 'question_three_hop_statement']
Which professors advise students who passed their qualifying exam?	'Willis'	['question_type_global', 'question_two_hop_statement']
Who is taking the G203 course	'Rey', 'Hiram', 'Alverta'	['question_type_global', 'question_single_statement']
What students are in the [animal science] department?	'Hiram'	['question_type_global', 'question_two_hop_statement']
[Tawnya] is current in [third year]
[that student] passed thesis proposal
[that student] is funded
What students are in Clare Building	'Alverta'	['question_type_global', 'question_two_hop_statement']
Which courses are 8 unit courses?	'G303'	['question_type_global', 'question_single_statement']
who are the professors?	'Gia', 'Willis', 'Igor', 'Tereasa', 'Stephine', 'Andrew', 'Peggy'	['question_type_global', 'question_single_statement']
What courses is [this person] TAing?	'G303'	['question_type_local']
Who are the [fifth year] students?	'Casey'	['question_type_global', 'question_single_statement']
Which phd students does [Andrew] advise?	'Albertha'	['question_type_local']
which students passed the defense?	'Alverta', 'Zenaida', 'Tawnya', 'Casey'	['question_type_global', 'question_single_statement']
What students in fifth year are advised by a professor with funding?	'Casey'	['question_type_global', 'question_three_hop_statement']
Which professors have an [full] status?	'Gia'	['question_type_global', 'question_single_statement']
[Casey] passed thesis proposal
What courses is [Zenaida] TAing?	'G303'	['question_type_local']
Which courses are TAed by phd students that passed their qualifier exam?	'G303'	['question_type_global', 'question_three_hop_statement']
What students are advised by a professor with funding?	'Will', 'Lorilee', 'Zenaida', 'Britney', 'Tawnya', 'Casey', 'Charlott'	['question_type_global', 'question_two_hop_statement']
There is a course called [U203]
[Casey] is now a [sixth year] student
Who advises [this student]?	'Willis'	['question_type_local']
Who is [Charlott]'s advisor?	'Willis'	['question_type_local']
What are all the courses?	'U302', 'G203', 'U201', 'G601', 'U610', 'G303', 'U203'	['question_type_global', 'question_single_statement']
Which courses are TAed by phd students that passed their qualifier exam or have some funding?	'G303'	['question_type_global', 'question_four_hop_statement']
[Lorilee] is in their [sixth year]
[she] is in [Health Building]
[she] passed thesis defense
Who has an advisor with funding?	'Will', 'Lorilee', 'Zenaida', 'Britney', 'Tawnya', 'Casey', 'Charlott'	['question_type_global', 'question_two_hop_statement']
Which students are in their [second year]	'Alverta'	['question_type_global', 'question_single_statement']
[this person] has [Andrew] and [Peggy] on the committee
[Lorilee] has passed the thesis proposal exam
What are the courses TAed by [that student]?	'G303'	['question_type_local']
what [undergraduate] courses have masters students taking them?	'G203'	['question_type_global', 'question_three_hop_statement']
Who are the [full] professors?	'Gia'	['question_type_global', 'question_single_statement']
