there is a new masters student named [Tawnya]
[this student]'s department is [biomedical engineering]
There is a course called [U9000]
what courses have no phd students taking them?	'U9000'	['question_type_global', 'question_two_hop_statement']
there is a PhD student named [Lizeth]
[this person] has failed the qualifying exam
[Lizeth] is in their [third year]
Which students are part of the [biomedical engineering] department	'Tawnya'	['question_type_global', 'question_two_hop_statement']
There is a course called [U301]
[Lizeth] has passed the thesis defense
[Albertha] is a [professor]
[that professor] conducts research in [reinforcement learning]
[this professor] is an [full] professor
[this person]'s department is [mechanical engineering]
[fifth year] is a [Tom] PhD student
[he] has passed the thesis defense
Who are the [full] professors?	'Albertha'	['question_type_global', 'question_single_statement']
[this person] has [Albertha] on the committee
[he] is now in [sixth year]
Who are the professors in the [mechanical engineering] department?	'Albertha'	['question_type_global', 'question_two_hop_statement']
[Lizeth] has failed the thesis proposal exam
[she] passed the qualifiers
Which professors have an [full] status?	'Albertha'	['question_type_global', 'question_single_statement']
[Loyd] is a [professor]
[she] and [Tom] are [Albertha]'s student
For which phd students does [Albertha] serve on a committee?	'Tom'	['question_type_local']
Which students are in their [sixth year]	'Tom'	['question_type_global', 'question_single_statement']
[she] is now a [fourth year] student
[Lizeth] has failed the thesis proposal exam
Who are the [fourth year] students?	'Lizeth'	['question_type_global', 'question_single_statement']
Which professors are part of the [mechanical engineering] department?	'Albertha'	['question_type_global', 'question_two_hop_statement']
which students passed the qualifying exam?	'Lizeth'	['question_type_global', 'question_single_statement']
create a [professor] named [Emma]
[Lizeth] has passed the thesis proposal exam
What [full] professors advise students who passed their thesis proposal?	'Albertha'	['question_type_global', 'question_three_hop_statement']
Which phd students have [Albertha] on their committee	'Tom'	['question_type_local']
Which professors are conducting research in [reinforcement learning]	'Albertha'	['question_type_global', 'question_single_statement']
[Tom] passed thesis proposal
[he] failed the qualifiers
There is a course called [U201]
[Loyd] and [Emma] are on [this person]'s committee
Who are the [full] professors?	'Albertha'	['question_type_global', 'question_single_statement']
Which [fourth year] students's advisors are conducting research in [reinforcement learning]	'Lizeth'	['question_type_global', 'question_three_hop_statement']
[Gia] is a [professor]
[Emma]'s department is [history]
there is a new PhD student named [John]
What professors are in the [mechanical engineering] department?	'Albertha'	['question_type_global', 'question_two_hop_statement']
create a [professor] named [Yoshiko]
[he] successfully defended their thesis
Create a new course called [U102]
[that person] has [Emma] on the committee
[this student] has passed the thesis proposal exam
What professors advise students who passed their thesis qualifiers?	'Albertha'	['question_type_global', 'question_two_hop_statement']
there is a new [second year] PhD student named [Rey]
[Rey] failed their thesis defense
who are the students?	'Tawnya', 'Lizeth', 'Tom', 'John', 'Rey'	['question_type_global', 'question_single_statement']
Create a new [undergraduate] course called [G301]
[this student] and [Tom] are TAing [that class]
which courses have no masters students enrolled?	'U9000', 'U301', 'U201', 'U102', 'G301'	['question_type_global', 'question_two_hop_statement']
Which undergraduate courses have phd student TAs?	'G301'	['question_type_global', 'question_three_hop_statement']
[G301] is set up as a full semester course
[Tawnya] and [Lizeth] are TAing [that course]
[Tom] is attending [G301]
What students are enrolled in [that class]?	'Tom'	['question_type_local']
which courses have some phd students enrolled?	'G301'	['question_type_global', 'question_two_hop_statement']
There is a [phd] level course called [U8001]
Which courses are TAed by phd students that passed their qualifier exam?	'G301'	['question_type_global', 'question_three_hop_statement']
which students passed the qualifying exam?	'Lizeth'	['question_type_global', 'question_single_statement']
[Vivienne] is a [associate] [professor]
[Vivienne] conducts research in [reinforcement learning]
[this person] advises [John] and [Rey]
what courses have no phd students taking them?	'U9000', 'U301', 'U201', 'U102', 'U8001'	['question_type_global', 'question_two_hop_statement']
Which are some [undergraduate] courses that phd students take?	'G301'	['question_type_global', 'question_three_hop_statement']
Which courses are [phd] level courses?	'U8001'	['question_type_global', 'question_single_statement']
Which courses did [Tom] enroll in?	'G301'	['question_type_local']
Which are some [undergraduate] courses that no masters student is taking?	'G301'	['question_type_global', 'question_three_hop_statement']
[John] is in their [second year]
Who are the [associate] professors?	'Vivienne'	['question_type_global', 'question_single_statement']
who are the students?	'Tawnya', 'Lizeth', 'Tom', 'John', 'Rey'	['question_type_global', 'question_single_statement']
Who is in the [biomedical engineering] department	'Tawnya'	['question_type_global', 'question_single_statement']
[John] passed the qualifiers
[that person] has [Yoshiko] on the committee
Which phd students are both taking a course and a TA?	'Tom'	['question_type_global', 'question_three_hop_statement']
Who is [John]'s advisor?	'Vivienne'	['question_type_local']
Which courses are TAed by phd students in their fourth year?	'G301'	['question_type_global', 'question_three_hop_statement']
Which undergraduate courses are TAed by phd students?	'G301'	['question_type_global', 'question_three_hop_statement']
Who advises [Tom]?	'Albertha'	['question_type_local']
[Yoshiko] research interest is in [unsupervised machine learning]
[she] is an [assistant] professor
which students passed the defense?	'Lizeth', 'Tom', 'John'	['question_type_global', 'question_single_statement']
Which professors are conducting research in [reinforcement learning]	'Albertha', 'Vivienne'	['question_type_global', 'question_single_statement']
which students passed the qualifying exam?	'Lizeth', 'John'	['question_type_global', 'question_single_statement']
Which students are in their [fourth year]	'Lizeth'	['question_type_global', 'question_single_statement']
Which phd students does [Albertha] advise?	'Lizeth', 'Tom'	['question_type_local']
Who are the professors in the [mechanical engineering] department?	'Albertha'	['question_type_global', 'question_two_hop_statement']
[Rey] is now in [third year]
[he] has passed the qualifying exam
[Rey] has [Gia] and [Loyd] on the committee
Which courses are TAed by phd students that passed their qualifier exam or have some funding?	'G301'	['question_type_global', 'question_four_hop_statement']
Who are the [associate] professors?	'Vivienne'	['question_type_global', 'question_single_statement']
Which are some [phd] courses that no masters student is taking?	'U8001'	['question_type_global', 'question_three_hop_statement']
who are the phd students?	'Lizeth', 'Tom', 'John', 'Rey'	['question_type_global', 'question_single_statement']
There is a course called [G203]
[this person] is an [full] professor
which students passed the defense?	'Lizeth', 'Tom', 'John'	['question_type_global', 'question_single_statement']
what [undergraduate] courses have no masters students taking them?	'G301'	['question_type_global', 'question_three_hop_statement']
Which courses have phd student TAs?	'G301'	['question_type_global', 'question_two_hop_statement']
Which phd students are both taking a course and a TA?	'Tom'	['question_type_global', 'question_three_hop_statement']
[Tom] passed the qualifiers
What are the courses TAed by [that student]?	'G301'	['question_type_local']
Which professors are part of the [history] department?	'Emma'	['question_type_global', 'question_two_hop_statement']
what courses have phd students taking them?	'G301'	['question_type_global', 'question_two_hop_statement']
Create a new course called [U304]
[that class] is a pass-fail course
Who are the [associate] professors?	'Vivienne'	['question_type_global', 'question_single_statement']
Who is [John]'s advisor?	'Vivienne'	['question_type_local']
what [phd] courses have no masters students taking them?	'U8001'	['question_type_global', 'question_three_hop_statement']
[this course] is taught by [Gia]
The TA for [U304] is [John]
which courses have no phd students enrolled?	'U9000', 'U301', 'U201', 'U102', 'U8001', 'G203', 'U304'	['question_type_global', 'question_two_hop_statement']
[Tawnya] and [Tom] are taking [U304]
What phd students are taking G301	'Tom'	['question_type_global', 'question_two_hop_statement']
Which courses are offered this semester?	'U9000', 'U301', 'U201', 'U102', 'G301', 'U8001', 'G203', 'U304'	['question_type_global', 'question_single_statement']
[Gia] and [Yoshiko] are on [Tom]'s committee
Create a new course called [G610]
[Lizeth] and [John] are both taking [that course]
who are the masters students?	'Tawnya'	['question_type_global', 'question_single_statement']
Which professors advise students who passed their defense?	'Albertha', 'Vivienne'	['question_type_global', 'question_two_hop_statement']
What are all the courses?	'U9000', 'U301', 'U201', 'U102', 'G301', 'U8001', 'G203', 'U304', 'G610'	['question_type_global', 'question_single_statement']
[he] has [Albertha] and [Gia] on the committee
Who advises [John]?	'Vivienne'	['question_type_local']
Which professors are conducting research in [unsupervised machine learning]	'Yoshiko'	['question_type_global', 'question_single_statement']
Which courses are TAed by phd students that passed their qualifier exam?	'G301', 'U304'	['question_type_global', 'question_three_hop_statement']
[Gia] conducts research in [reinforcement learning]
who are the phd students?	'Lizeth', 'Tom', 'John', 'Rey'	['question_type_global', 'question_single_statement']
the affiliation of [she] is [biomedical engineering]
[this person] is an [assistant] professor
What is [Gia] research area?	'reinforcement learning'	['question_type_local']
Which courses have phd student TAs?	'G301', 'U304'	['question_type_global', 'question_two_hop_statement']
What [associate] professors advise students who passed their thesis qualifiers?	'Vivienne'	['question_type_global', 'question_three_hop_statement']
Which [associate] professors advise students who passed their defense?	'Vivienne'	['question_type_global', 'question_three_hop_statement']
Which courses are offered this semester?	'U9000', 'U301', 'U201', 'U102', 'G301', 'U8001', 'G203', 'U304', 'G610'	['question_type_global', 'question_single_statement']
What is [that professor] research area?	'reinforcement learning'	['question_type_local']
What are the [second year] phd students	'John'	['question_type_global', 'question_single_statement']
[Vivienne] is on [Tom]'s committee
which students passed the proposal exam?	'Lizeth', 'Tom', 'John'	['question_type_global', 'question_single_statement']
Which courses have masters student TAs?	'G301'	['question_type_global', 'question_two_hop_statement']
Who is [Rey]'s advisor?	'Vivienne'	['question_type_local']
Which courses are TAed by phd students that passed their qualifier exam or have some funding?	'G301', 'U304'	['question_type_global', 'question_four_hop_statement']
Who is on [Tom]'s committee?	'Albertha', 'Loyd', 'Emma', 'Gia', 'Yoshiko', 'Vivienne'	['question_type_local']
What [associate] professors advise students who passed their thesis proposal?	'Vivienne'	['question_type_global', 'question_three_hop_statement']
which courses have some masters students enrolled?	'U304'	['question_type_global', 'question_two_hop_statement']
Who does [she] advise?	'John', 'Rey'	['question_type_local']
What students are taking courses and TAing?	'Tawnya', 'Lizeth', 'Tom', 'John'	['question_type_global', 'question_two_hop_statement']
[Rey] passed thesis proposal
[Rey] has [Emma] on the committee
Which are some courses that masters students take?	'U304'	['question_type_global', 'question_two_hop_statement']
What professors are in the [biomedical engineering] department?	'Gia'	['question_type_global', 'question_two_hop_statement']
Who is [John]'s advisor?	'Vivienne'	['question_type_local']
For which phd students does [Gia] serve on a committee?	'Tom', 'John', 'Rey'	['question_type_local']
Which courses have masters student TAs?	'G301'	['question_type_global', 'question_two_hop_statement']
Create a new [phd] level course called [G103]
Which department is [that person] in?	'history'	['question_type_local']
[U301] is a [masters] level course
Which students are part of the [biomedical engineering] department	'Tawnya'	['question_type_global', 'question_two_hop_statement']
What courses is [Tom] TAing?	'G301'	['question_type_local']
What [associate] professors advise students who defended successfully?	'Vivienne'	['question_type_global', 'question_three_hop_statement']
What courses are taught by those in the [biomedical engineering] department?	'U304'	['question_type_global', 'question_two_hop_statement']
what courses have masters students taking them?	'U304'	['question_type_global', 'question_two_hop_statement']
Which courses have phd student TAs that passed the qualifying exam?	'G301', 'U304'	['question_type_global', 'question_three_hop_statement']
[Tom] is attending [U301]
[that course] is a full semester course
Who is taking [that class]?	'Tom'	['question_type_local']
What are all the courses?	'U9000', 'U301', 'U201', 'U102', 'G301', 'U8001', 'G203', 'U304', 'G610', 'G103'	['question_type_global', 'question_single_statement']
[Lizeth] and [Tawnya] are attending [U304]
Who is taking [G610]?	'Lizeth', 'John'	['question_type_local']
which [undergraduate] courses have some phd students enrolled?	'G301'	['question_type_global', 'question_three_hop_statement']
Which courses are [phd] level courses?	'U8001', 'G103'	['question_type_global', 'question_single_statement']
who are the phd students?	'Lizeth', 'Tom', 'John', 'Rey'	['question_type_global', 'question_single_statement']
[Gia] is on [Lizeth]'s committee
Which courses are TAed by phd students that passed their qualifier exam or have some funding?	'G301', 'U304'	['question_type_global', 'question_four_hop_statement']
who are the masters students?	'Tawnya'	['question_type_global', 'question_single_statement']
[Loyd] is on [Lizeth]'s committee
Which students's advisors are conducting research in [reinforcement learning]	'Lizeth', 'Tom', 'John', 'Rey'	['question_type_global', 'question_two_hop_statement']
which courses have some masters students enrolled?	'U304'	['question_type_global', 'question_two_hop_statement']
[that student] is now a [fifth year] student
What courses is [this student] TAing?	'G301'	['question_type_local']
Which courses have phd student TAs?	'G301', 'U304'	['question_type_global', 'question_two_hop_statement']
which students passed the proposal exam?	'Lizeth', 'Tom', 'John', 'Rey'	['question_type_global', 'question_single_statement']
Which courses did [that student] enroll in?	'U304', 'G610'	['question_type_local']
[Rey] passed thesis defense
What courses is [Gia] teaching?	'U304'	['question_type_local']
Who is part of the [mechanical engineering] department	'Albertha'	['question_type_global', 'question_single_statement']
who are the phd students?	'Lizeth', 'Tom', 'John', 'Rey'	['question_type_global', 'question_single_statement']
What students are taking courses and TAing?	'Tawnya', 'Lizeth', 'Tom', 'John'	['question_type_global', 'question_two_hop_statement']
Which professors are conducting research in [reinforcement learning]	'Albertha', 'Gia', 'Vivienne'	['question_type_global', 'question_single_statement']
[Albertha] and [Yoshiko] are on [he]'s committee
What phd students are taking courses and TAing?	'Lizeth', 'Tom', 'John'	['question_type_global', 'question_three_hop_statement']
Which courses are TAed by [Tawnya]?	'G301'	['question_type_local']
[Yoshiko] teaches [U8001]
What professors advise students who passed their thesis proposal?	'Albertha', 'Vivienne'	['question_type_global', 'question_two_hop_statement']
which [undergraduate] courses have some phd students enrolled?	'G301'	['question_type_global', 'question_three_hop_statement']
who are the masters students?	'Tawnya'	['question_type_global', 'question_single_statement']
Which courses are offered this semester?	'U9000', 'U301', 'U201', 'U102', 'G301', 'U8001', 'G203', 'U304', 'G610', 'G103'	['question_type_global', 'question_single_statement']
[Emma] is an [assistant] professor
[Emma] conducts research in [reinforcement learning]
What courses are taught by those in the [biomedical engineering] department?	'U304'	['question_type_global', 'question_two_hop_statement']
what [phd] courses have no masters students taking them?	'U8001', 'G103'	['question_type_global', 'question_three_hop_statement']
Which courses have phd student TAs?	'G301', 'U304'	['question_type_global', 'question_two_hop_statement']
Which courses did [John] enroll in?	'G610'	['question_type_local']
Which professors advise students who passed their proposal?	'Albertha', 'Vivienne'	['question_type_global', 'question_two_hop_statement']
What are all the courses?	'U9000', 'U301', 'U201', 'U102', 'G301', 'U8001', 'G203', 'U304', 'G610', 'G103'	['question_type_global', 'question_single_statement']
which [undergraduate] courses have no masters students enrolled?	'G301'	['question_type_global', 'question_three_hop_statement']
What professors are on [John]'s committee	'Albertha', 'Emma', 'Gia', 'Yoshiko'	['question_type_local']
Which [associate] professors advise students who passed their proposal?	'Vivienne'	['question_type_global', 'question_three_hop_statement']
What courses is [Tawnya] taking?	'U304'	['question_type_local']
Which courses have phd student TAs that either have some funding or passed the qualifying exam?	'G301', 'U304'	['question_type_global', 'question_four_hop_statement']
Which professors are part of the [mechanical engineering] department?	'Albertha'	['question_type_global', 'question_two_hop_statement']
who are the professors?	'Albertha', 'Loyd', 'Emma', 'Gia', 'Yoshiko', 'Vivienne'	['question_type_global', 'question_single_statement']
What professors advise students who passed their thesis qualifiers?	'Albertha', 'Vivienne'	['question_type_global', 'question_two_hop_statement']
Which courses are TAed by masters students?	'G301'	['question_type_global', 'question_two_hop_statement']
[Loyd] is on [John]'s committee
Who is part of the [mechanical engineering] department	'Albertha'	['question_type_global', 'question_single_statement']
the affiliation of [this professor] is [mechanical engineering]
Who has [Vivienne] on their phd committee?	'Tom'	['question_type_local']
which students passed the proposal exam?	'Lizeth', 'Tom', 'John', 'Rey'	['question_type_global', 'question_single_statement']
What courses is [Gia] teaching?	'U304'	['question_type_local']
who are the professors?	'Albertha', 'Loyd', 'Emma', 'Gia', 'Yoshiko', 'Vivienne'	['question_type_global', 'question_single_statement']
Which courses are offered this semester?	'U9000', 'U301', 'U201', 'U102', 'G301', 'U8001', 'G203', 'U304', 'G610', 'G103'	['question_type_global', 'question_single_statement']
[Loyd] research interest is in [programming languages]
Which department is [this professor] in?	'mechanical engineering'	['question_type_local']
Which professors advise students who passed their defense?	'Albertha', 'Vivienne'	['question_type_global', 'question_two_hop_statement']
[Rey] is in [fourth year]
Who is [that student]'s advisor?	'Vivienne'	['question_type_local']
Which people are in the [history] department?	'Emma'	['question_type_global', 'question_single_statement']
Which phd students have [Loyd] on their committee	'Lizeth', 'Tom', 'John', 'Rey'	['question_type_local']
[U304] is a [undergraduate] level course
What students are enrolled in [that class]?	'Tawnya', 'Lizeth', 'Tom'	['question_type_local']
What professors advise students who defended successfully?	'Albertha', 'Vivienne'	['question_type_global', 'question_two_hop_statement']
Which professors advise students who passed their qualifying exam?	'Albertha', 'Vivienne'	['question_type_global', 'question_two_hop_statement']
which courses have no phd students enrolled?	'U9000', 'U201', 'U102', 'U8001', 'G203', 'G103'	['question_type_global', 'question_two_hop_statement']
Which phd students are both taking a course and a TA?	'Lizeth', 'Tom', 'John'	['question_type_global', 'question_three_hop_statement']
Which courses have phd student TAs that passed the qualifying exam?	'G301', 'U304'	['question_type_global', 'question_three_hop_statement']
Which courses have phd student TAs that either have some funding or passed the qualifying exam?	'G301', 'U304'	['question_type_global', 'question_four_hop_statement']
[Lizeth] is a student in [that course]
[this course] is set up as a mini course
Which courses have masters student TAs?	'G301'	['question_type_global', 'question_two_hop_statement']
[this student] has [Vivienne] on the committee
Who advises [that student]?	'Albertha'	['question_type_local']
who are the students?	'Tawnya', 'Lizeth', 'Tom', 'John', 'Rey'	['question_type_global', 'question_single_statement']
What [full] professors advise students who passed their thesis qualifiers?	'Albertha'	['question_type_global', 'question_three_hop_statement']
Who is teaching [phd] courses?	'Yoshiko'	['question_type_global', 'question_two_hop_statement']
Who are the [second year] students?	'John'	['question_type_global', 'question_single_statement']
what courses have masters students taking them?	'U304'	['question_type_global', 'question_two_hop_statement']
What students are taking courses and TAing?	'Tawnya', 'Lizeth', 'Tom', 'John'	['question_type_global', 'question_two_hop_statement']
Create a new course called [U101]
What professors advise students who passed their thesis qualifiers?	'Albertha', 'Vivienne'	['question_type_global', 'question_two_hop_statement']
who are the professors?	'Albertha', 'Loyd', 'Emma', 'Gia', 'Yoshiko', 'Vivienne'	['question_type_global', 'question_single_statement']
the affiliation of [this professor] is [biomedical engineering]
which students passed the proposal exam?	'Lizeth', 'Tom', 'John', 'Rey'	['question_type_global', 'question_single_statement']
Who are the students in the [biomedical engineering] department	'Tawnya'	['question_type_global', 'question_two_hop_statement']
What [associate] professors advise students who passed their thesis qualifiers?	'Vivienne'	['question_type_global', 'question_three_hop_statement']
What is [this professor]'s research focus?	'reinforcement learning'	['question_type_local']
Which courses are [mini course]	'U304'	['question_type_global', 'question_single_statement']
Which courses have phd student TAs?	'G301', 'U304'	['question_type_global', 'question_two_hop_statement']
which students passed the qualifying exam?	'Lizeth', 'Tom', 'John', 'Rey'	['question_type_global', 'question_single_statement']
What professors advise students who defended successfully?	'Albertha', 'Vivienne'	['question_type_global', 'question_two_hop_statement']
[that course] is a pass-fail course
What 4 unit courses are taught by those in the [biomedical engineering] department?	'U304'	['question_type_global', 'question_three_hop_statement']
[Vivienne] has been promoted to [full] professor
What is [Vivienne] research area?	'reinforcement learning'	['question_type_local']
Who is taking [G610]?	'Lizeth', 'John'	['question_type_local']
Which professors are teaching [phd] courses?	'Yoshiko'	['question_type_global', 'question_two_hop_statement']
[that class] is taught by [Albertha]
[U101] is a [undergraduate] level course
Which people are in the [mechanical engineering] department?	'Albertha', 'Loyd'	['question_type_global', 'question_single_statement']
