[Tereasa] is a masters student
[Tereasa] is affiliated with the [applied physics] department
[third year] is a [Tawnya] PhD student
[Casey] is a [professor]
Who is part of the [applied physics] department	'Tereasa'	['question_type_global', 'question_single_statement']
[this student] is [he]'s student
[this professor] research interest is in [applications of machine learning]
there is a [fourth year] PhD student named [Francoise]
[that student] is [Casey]'s student
[Tawnya] has passed the thesis defense
[she] has passed the qualifying exam
[this person] is in [fourth year]
[she] passed thesis proposal
Who is [Francoise]'s advisor?	'Casey'	['question_type_local']
which students passed the proposal exam?	'Tawnya'	['question_type_global', 'question_single_statement']
Who advises [that person]?	'Casey'	['question_type_local']
There is a course called [G8001]
[Francoise] and [Tawnya] are TAs for [that class]
there is a new [second year] PhD student named [Hanna]
[Tawnya] is in [fifth year]
What courses is [Tawnya] TAing?	'G8001'	['question_type_local']
who are the professors?	'Casey'	['question_type_global', 'question_single_statement']
there is a PhD student named [Igor]
[he] has passed the thesis proposal exam
[Casey] is on [this student]'s committee
which courses have no phd students enrolled?	'G8001'	['question_type_global', 'question_two_hop_statement']
Which students's advisors are conducting research in [applications of machine learning]	'Tawnya', 'Francoise'	['question_type_global', 'question_two_hop_statement']
Who is on [that student]'s committee?	'Casey'	['question_type_local']
create a [assistant] [professor] named [Andrew]
What are the [fifth year] phd students	'Tawnya'	['question_type_global', 'question_single_statement']
Create a new course called [U104]
[that class] is a [undergraduate] course
[Casey] is the instructor for [that course]
[Tawnya]'s office is [Community Building]
Who is [Tawnya]'s advisor?	'Casey'	['question_type_local']
who are the phd students?	'Tawnya', 'Francoise', 'Hanna', 'Igor'	['question_type_global', 'question_single_statement']
which [undergraduate] courses have no phd students enrolled?	'U104'	['question_type_global', 'question_three_hop_statement']
Who is currently TAing [G8001]?	'Tawnya', 'Francoise'	['question_type_local']
Who has an office in [Community Building]	'Tawnya'	['question_type_global', 'question_two_hop_statement']
create a [assistant] [professor] named [Yoshiko]
who are the masters students?	'Tereasa'	['question_type_global', 'question_single_statement']
Which courses are TAed by phd students that passed their qualifier exam?	'G8001'	['question_type_global', 'question_three_hop_statement']
[Stephine] is a masters student
[Igor] and [Hanna] are [Yoshiko]'s student
[Yoshiko] research interest is in [applications of machine learning]
Who is teaching [U104]?	'Casey'	['question_type_local']
which students passed the qualifying exam?	'Tawnya'	['question_type_global', 'question_single_statement']
create a [professor] named [Eun]
What are all the courses?	'G8001', 'U104'	['question_type_global', 'question_single_statement']
who are the students?	'Tereasa', 'Tawnya', 'Francoise', 'Hanna', 'Igor', 'Stephine'	['question_type_global', 'question_single_statement']
What courses is [Casey] teaching?	'U104'	['question_type_local']
Which professors advise students who passed their defense?	'Casey'	['question_type_global', 'question_two_hop_statement']
Which people are in the [applied physics] department?	'Tereasa'	['question_type_global', 'question_single_statement']
Which courses are TAed by phd students that passed their qualifier exam?	'G8001'	['question_type_global', 'question_three_hop_statement']
Which are some [undergraduate] courses that no phd student is taking?	'U104'	['question_type_global', 'question_three_hop_statement']
there is a new masters student named [Bob]
Which professors advise students who passed their qualifying exam?	'Casey'	['question_type_global', 'question_two_hop_statement']
Which students are in their [second year]	'Hanna'	['question_type_global', 'question_single_statement']
which students passed the qualifying exam?	'Tawnya'	['question_type_global', 'question_single_statement']
[this student] is affiliated with the [electrical engineering] department
Which courses are offered this semester?	'G8001', 'U104'	['question_type_global', 'question_single_statement']
There is a [masters] level 8 unit course called [G201]
[Andrew] teaches [that class]
[Stephine] and [Hanna] are TAing [this course]
[G201] is part of the [english] department
What are the [undergraduate] courses?	'U104'	['question_type_global', 'question_single_statement']
[she] is now in [third year]
Who are the [fourth year] students?	'Francoise'	['question_type_global', 'question_single_statement']
[she] has failed the thesis proposal exam
[Hanna] failed the qualifiers
[that person] passed thesis defense
Who is teaching [U104]?	'Casey'	['question_type_local']
Which courses are TAed by phd students that passed their qualifier exam?	'G8001'	['question_type_global', 'question_three_hop_statement']
who are the students?	'Tereasa', 'Tawnya', 'Francoise', 'Hanna', 'Igor', 'Stephine', 'Bob'	['question_type_global', 'question_single_statement']
What [assistant] professors advise students who defended successfully?	'Yoshiko'	['question_type_global', 'question_three_hop_statement']
[Andrew] and [Eun] are on [Tawnya]'s committee
[she] research interest is in [theoretical cosmology]
Who advises [Hanna]?	'Yoshiko'	['question_type_local']
What professors advise students who passed their thesis proposal?	'Casey', 'Yoshiko'	['question_type_global', 'question_two_hop_statement']
Which courses have masters student TAs?	'G201'	['question_type_global', 'question_two_hop_statement']
What professors advise students who defended successfully?	'Casey', 'Yoshiko'	['question_type_global', 'question_two_hop_statement']
What courses is [Stephine] TAing?	'G201'	['question_type_local']
Which courses are TAed by phd students in their fourth year?	'G8001'	['question_type_global', 'question_three_hop_statement']
what [undergraduate] courses have no phd students taking them?	'U104'	['question_type_global', 'question_three_hop_statement']
What [assistant] professors advise students who defended successfully?	'Yoshiko'	['question_type_global', 'question_three_hop_statement']
what courses have no masters students taking them?	'G8001', 'U104', 'G201'	['question_type_global', 'question_two_hop_statement']
which students passed the qualifying exam?	'Tawnya'	['question_type_global', 'question_single_statement']
What students are in the [electrical engineering] department?	'Bob'	['question_type_global', 'question_two_hop_statement']
which [masters] courses have no phd students enrolled?	'G201'	['question_type_global', 'question_three_hop_statement']
[Tawnya] is a student in [G201]
What is [Eun] research area?	'theoretical cosmology'	['question_type_local']
What are the [third year] phd students	'Hanna'	['question_type_global', 'question_single_statement']
Who is in the [electrical engineering] department	'Bob'	['question_type_global', 'question_single_statement']
Who is part of the [electrical engineering] department	'Bob'	['question_type_global', 'question_single_statement']
What students are taking courses and TAing?	'Tawnya'	['question_type_global', 'question_two_hop_statement']
Who are the professors working on [applications of machine learning]?	'Casey', 'Yoshiko'	['question_type_global', 'question_single_statement']
[G201] is set up as a full semester course
Who is taking [that class]?	'Tawnya'	['question_type_local']
Which courses have phd student TAs?	'G8001', 'G201'	['question_type_global', 'question_two_hop_statement']
Which [assistant] professors advise students who passed their defense?	'Yoshiko'	['question_type_global', 'question_three_hop_statement']
What are the courses TAed by [Francoise]?	'G8001'	['question_type_local']
Which are some courses that no masters student is taking?	'G8001', 'U104', 'G201'	['question_type_global', 'question_two_hop_statement']
Which professors are teaching [full_semester_course]?	'Andrew'	['question_type_global', 'question_two_hop_statement']
which courses have no phd students enrolled?	'G8001', 'U104'	['question_type_global', 'question_two_hop_statement']
Which [third year] students's advisors are conducting research in [applications of machine learning]	'Hanna'	['question_type_global', 'question_three_hop_statement']
Which courses are TAed by phd students that passed their qualifier exam or have some funding?	'G8001'	['question_type_global', 'question_four_hop_statement']
[this person] has [Yoshiko] on the committee
Who advises [this student]?	'Casey'	['question_type_local']
Which professors advise students who passed their proposal?	'Casey', 'Yoshiko'	['question_type_global', 'question_two_hop_statement']
[Igor] passed the qualifiers
[this student] is a [sixth year] student
Who is in the [electrical engineering] department	'Bob'	['question_type_global', 'question_single_statement']
[that student] passed thesis defense
Which courses are TAed by phd students?	'G8001', 'G201'	['question_type_global', 'question_two_hop_statement']
[Eun] is on [that person]'s committee
Which courses are TAed by masters students?	'G201'	['question_type_global', 'question_two_hop_statement']
Which phd students are both taking a course and a TA?	'Tawnya'	['question_type_global', 'question_three_hop_statement']
which students passed the defense?	'Tawnya', 'Hanna', 'Igor'	['question_type_global', 'question_single_statement']
which courses have no phd students enrolled?	'G8001', 'U104'	['question_type_global', 'question_two_hop_statement']
Which professors are conducting research in [theoretical cosmology]	'Eun'	['question_type_global', 'question_single_statement']
What are the [undergraduate] courses?	'U104'	['question_type_global', 'question_single_statement']
Which courses are 8 unit courses?	'G201'	['question_type_global', 'question_single_statement']
What students are in Community Building	'Tawnya'	['question_type_global', 'question_two_hop_statement']
which [undergraduate] courses have no phd students enrolled?	'U104'	['question_type_global', 'question_three_hop_statement']
who are the phd students?	'Tawnya', 'Francoise', 'Hanna', 'Igor'	['question_type_global', 'question_single_statement']
[this student]'s office is [Irey Theatre]
Which department is [G201] in?	'english'	['question_type_local']
Who is in [Irey Theatre]	'Igor'	['question_type_global', 'question_two_hop_statement']
Which students are taking [G201]?	'Tawnya'	['question_type_local']
What [assistant] professors advise students who defended successfully?	'Yoshiko'	['question_type_global', 'question_three_hop_statement']
Who has [Casey] on their phd committee?	'Igor'	['question_type_local']
which students passed the defense?	'Tawnya', 'Hanna', 'Igor'	['question_type_global', 'question_single_statement']
What are all the courses?	'G8001', 'U104', 'G201'	['question_type_global', 'question_single_statement']
Who is taking [G201]?	'Tawnya'	['question_type_local']
who are the students?	'Tereasa', 'Tawnya', 'Francoise', 'Hanna', 'Igor', 'Stephine', 'Bob'	['question_type_global', 'question_single_statement']
Which are some [undergraduate] courses that no masters student is taking?	'U104'	['question_type_global', 'question_three_hop_statement']
Which professors are teaching [undergraduate] courses?	'Casey'	['question_type_global', 'question_two_hop_statement']
Which courses are TAed by phd students that passed their qualifier exam?	'G8001'	['question_type_global', 'question_three_hop_statement']
[Andrew] conducts research in [computational biology]
What courses is [Andrew] teaching?	'G201'	['question_type_local']
Which students have offices in Irey Theatre	'Igor'	['question_type_global', 'question_two_hop_statement']
Which students are in their [third year]	'Hanna'	['question_type_global', 'question_single_statement']
Which masters courses have phd student TAs?	'G201'	['question_type_global', 'question_three_hop_statement']
What phd students are taking courses and TAing?	'Tawnya'	['question_type_global', 'question_three_hop_statement']
Which professors advise students who passed their defense?	'Casey', 'Yoshiko'	['question_type_global', 'question_two_hop_statement']
[G8001] will be a full semester course
which courses have some phd students enrolled?	'G201'	['question_type_global', 'question_two_hop_statement']
Which are some courses that phd students take?	'G201'	['question_type_global', 'question_two_hop_statement']
[Hanna] failed the qualifiers
Which courses have masters student TAs?	'G201'	['question_type_global', 'question_two_hop_statement']
which [undergraduate] courses have no masters students enrolled?	'U104'	['question_type_global', 'question_three_hop_statement']
[she] has passed the qualifying exam
[she] has [Eun] on the committee
Who is teaching [undergraduate] courses?	'Casey'	['question_type_global', 'question_two_hop_statement']
Which department is [that professor] in?	"I don't know"	['question_type_local']
which students passed the qualifying exam?	'Tawnya', 'Hanna', 'Igor'	['question_type_global', 'question_single_statement']
What [assistant] professors advise students who passed their thesis proposal?	'Yoshiko'	['question_type_global', 'question_three_hop_statement']
who are the professors?	'Casey', 'Andrew', 'Yoshiko', 'Eun'	['question_type_global', 'question_single_statement']
What are the 8 unit courses?	'G201'	['question_type_global', 'question_single_statement']
Which professors are teaching [full_semester_course]?	'Andrew'	['question_type_global', 'question_two_hop_statement']
Which students are TAing [G201]?	'Hanna', 'Stephine'	['question_type_local']
which students passed the proposal exam?	'Tawnya', 'Igor'	['question_type_global', 'question_single_statement']
Which courses are offered this semester in the english department?	'G201'	['question_type_global', 'question_two_hop_statement']
Which courses are 8 unit courses?	'G201'	['question_type_global', 'question_single_statement']
Which courses are TAed by phd students that passed their qualifier exam or have some funding?	'G8001', 'G201'	['question_type_global', 'question_four_hop_statement']
[this student] has [Andrew] on the committee
[this student]'s office is [Ekeley Building]
Which courses have phd student TAs that either have some funding or passed the qualifying exam?	'G8001', 'G201'	['question_type_global', 'question_four_hop_statement']
Create a new [undergraduate] level course called [U601]
For which phd students does [Andrew] serve on a committee?	'Tawnya', 'Hanna'	['question_type_local']
What students are taking G201	'Tawnya'	['question_type_global', 'question_single_statement']
[that person] is in [fourth year]
Who is on [this student]'s committee?	'Andrew', 'Eun'	['question_type_local']
what [masters] courses have no masters students taking them?	'G201'	['question_type_global', 'question_three_hop_statement']
Which are some courses that phd students take?	'G201'	['question_type_global', 'question_two_hop_statement']
[Yoshiko] teaches [U601]
[U601] is offered in the [electrical engineering] department
What is [Yoshiko] working on?	'applications of machine learning'	['question_type_local']
Which students are in their [fifth year]	'Tawnya'	['question_type_global', 'question_single_statement']
Which courses are TAed by masters students?	'G201'	['question_type_global', 'question_two_hop_statement']
Which courses are TAed by phd students?	'G8001', 'G201'	['question_type_global', 'question_two_hop_statement']
Who is teaching [that class]?	'Yoshiko'	['question_type_local']
What students are in the [applied physics] department?	'Tereasa'	['question_type_global', 'question_two_hop_statement']
What [assistant] professors advise students who passed their thesis proposal?	'Yoshiko'	['question_type_global', 'question_three_hop_statement']
Which courses are 8 unit courses?	'G201'	['question_type_global', 'question_single_statement']
What are all the courses?	'G8001', 'U104', 'G201', 'U601'	['question_type_global', 'question_single_statement']
What students are in Irey Theatre	'Igor'	['question_type_global', 'question_two_hop_statement']
What are the courses TAed by [Francoise]?	'G8001'	['question_type_local']
Which professors advise students who passed their qualifying exam?	'Casey', 'Yoshiko'	['question_type_global', 'question_two_hop_statement']
what courses have no masters students taking them?	'G8001', 'U104', 'G201', 'U601'	['question_type_global', 'question_two_hop_statement']
Which professors are conducting research in [computational biology]	'Andrew'	['question_type_global', 'question_single_statement']
which students passed the qualifying exam?	'Tawnya', 'Hanna', 'Igor'	['question_type_global', 'question_single_statement']
Which are some courses that no phd student is taking?	'G8001', 'U104', 'U601'	['question_type_global', 'question_two_hop_statement']
Who is teaching [masters] courses?	'Andrew'	['question_type_global', 'question_two_hop_statement']
[Francoise] is enrolled in [that course]
[that class] is a full semester course
Who is currently TAing [G8001]?	'Tawnya', 'Francoise'	['question_type_local']
Which courses are TAed by phd students?	'G8001', 'G201'	['question_type_global', 'question_two_hop_statement']
[Andrew] is on [Francoise]'s committee
Who is on [this student]'s committee?	'Andrew'	['question_type_local']
which courses have some phd students enrolled?	'G201', 'U601'	['question_type_global', 'question_two_hop_statement']
[Francoise] passed the qualifiers
[that student] is in [Duane Building]
Which courses have phd student TAs that passed the qualifying exam?	'G8001', 'G201'	['question_type_global', 'question_three_hop_statement']
which students passed the proposal exam?	'Tawnya', 'Igor'	['question_type_global', 'question_single_statement']
which courses have no masters students enrolled?	'G8001', 'U104', 'G201', 'U601'	['question_type_global', 'question_two_hop_statement']
[Francoise] has passed the thesis defense
[Francoise] is now a [fifth year] student
Which professors advise students who passed their qualifying exam?	'Casey', 'Yoshiko'	['question_type_global', 'question_two_hop_statement']
What are the courses TAed by [that student]?	'G8001'	['question_type_local']
Which courses in the english department are TAed by phd students?	'G201'	['question_type_global', 'question_three_hop_statement']
[that student] has passed the thesis proposal exam
What are the courses TAed by [that person]?	'G8001'	['question_type_local']
who are the phd students?	'Tawnya', 'Francoise', 'Hanna', 'Igor'	['question_type_global', 'question_single_statement']
What phd students are taking courses and TAing?	'Tawnya', 'Francoise'	['question_type_global', 'question_three_hop_statement']
what courses have no phd students taking them?	'G8001', 'U104'	['question_type_global', 'question_two_hop_statement']
[Yoshiko] and [Eun] are on [Francoise]'s committee
Who is teaching [G201]?	'Andrew'	['question_type_local']
Which phd students are both taking a course and a TA?	'Tawnya', 'Francoise'	['question_type_global', 'question_three_hop_statement']
Which [sixth year] students's advisors are conducting research in [applications of machine learning]	'Igor'	['question_type_global', 'question_three_hop_statement']
who are the students?	'Tereasa', 'Tawnya', 'Francoise', 'Hanna', 'Igor', 'Stephine', 'Bob'	['question_type_global', 'question_single_statement']
What professors advise students who passed their thesis proposal?	'Casey', 'Yoshiko'	['question_type_global', 'question_two_hop_statement']
Which masters courses have phd student TAs?	'G201'	['question_type_global', 'question_three_hop_statement']
Who are the [fourth year] students?	'Hanna'	['question_type_global', 'question_single_statement']
Which courses have phd student TAs?	'G8001', 'G201'	['question_type_global', 'question_two_hop_statement']
Which are some [undergraduate] courses that no phd student is taking?	'U104'	['question_type_global', 'question_three_hop_statement']
which students passed the qualifying exam?	'Tawnya', 'Francoise', 'Hanna', 'Igor'	['question_type_global', 'question_single_statement']
What are the [full_semester_course]?	'G8001', 'G201', 'U601'	['question_type_global', 'question_single_statement']
Which courses have phd student TAs that are in the fourth year?	'G201'	['question_type_global', 'question_three_hop_statement']
[Francoise] and [Tawnya] are both taking [G201]
Who is teaching [G201]?	'Andrew'	['question_type_local']
What phd students are taking U601	'Francoise'	['question_type_global', 'question_two_hop_statement']
Which courses are offered this semester in the electrical engineering department?	'U601'	['question_type_global', 'question_two_hop_statement']
Which phd students are both taking a course and a TA?	'Tawnya', 'Francoise'	['question_type_global', 'question_three_hop_statement']
Which department is [G201] in?	'english'	['question_type_local']
Which courses are TAed by masters students?	'G201'	['question_type_global', 'question_two_hop_statement']
What are the [masters] courses?	'G201'	['question_type_global', 'question_single_statement']
Which courses are TAed by [she]?	'G8001'	['question_type_local']
What is [Andrew] research area?	'computational biology'	['question_type_local']
Which courses have phd student TAs?	'G8001', 'G201'	['question_type_global', 'question_two_hop_statement']
[she] is now in [sixth year]
Which courses did [this person] enroll in?	'G201'	['question_type_local']
What are the 8 unit courses?	'G201'	['question_type_global', 'question_single_statement']
Which courses have phd student TAs that passed the qualifying exam?	'G8001', 'G201'	['question_type_global', 'question_three_hop_statement']
What courses is [Andrew] teaching?	'G201'	['question_type_local']
Which courses are [undergraduate] level courses?	'U104', 'U601'	['question_type_global', 'question_single_statement']
[Bob] is a TA for [U601]
[Stephine] and [Hanna] are taking [U601]
Who is taking [U601]?	'Francoise', 'Hanna', 'Stephine'	['question_type_local']
which students passed the proposal exam?	'Tawnya', 'Francoise', 'Igor'	['question_type_global', 'question_single_statement']
Who advises [Tawnya]?	'Casey'	['question_type_local']
what courses have no phd students taking them?	'G8001', 'U104'	['question_type_global', 'question_two_hop_statement']
what courses have masters students taking them?	'U601'	['question_type_global', 'question_two_hop_statement']
Which courses are in the [electrical engineering] department?	'U601'	['question_type_global', 'question_single_statement']
[Stephine]'s department is [english]
What are the courses TAed by [Stephine]?	'G201'	['question_type_local']
what courses have no masters students taking them?	'G8001', 'U104', 'G201'	['question_type_global', 'question_two_hop_statement']
What courses is [Stephine] TAing?	'G201'	['question_type_local']
Which courses have masters student TAs?	'G201', 'U601'	['question_type_global', 'question_two_hop_statement']
Who are the [assistant] professors?	'Andrew', 'Yoshiko'	['question_type_global', 'question_single_statement']
[Hanna] is now a [fifth year] student
Who is teaching [G201]?	'Andrew'	['question_type_local']
Who are the students in the [electrical engineering] department	'Bob'	['question_type_global', 'question_two_hop_statement']
which courses have some phd students enrolled?	'G201', 'U601'	['question_type_global', 'question_two_hop_statement']
Who has an office in [Ekeley Building]	'Hanna'	['question_type_global', 'question_two_hop_statement']
[Igor] has [Andrew] on the committee
Which courses are 8 unit courses?	'G201'	['question_type_global', 'question_single_statement']
What are the courses that [Francoise] is enrolled in?	'G201', 'U601'	['question_type_local']
Which courses have masters student TAs?	'G201', 'U601'	['question_type_global', 'question_two_hop_statement']
Which phd students does [Yoshiko] advise?	'Hanna', 'Igor'	['question_type_local']
who are the professors?	'Casey', 'Andrew', 'Yoshiko', 'Eun'	['question_type_global', 'question_single_statement']
Create a new [phd] [mini course] called [U101]
[Tereasa] and [Igor] are TAs for [that course]
[he] and [Hanna] are both taking [U101]
Which courses in the english department are TAed by phd students?	'G201'	['question_type_global', 'question_three_hop_statement']
who are the masters students?	'Tereasa', 'Stephine', 'Bob'	['question_type_global', 'question_single_statement']
Who does [Casey] advise?	'Tawnya', 'Francoise'	['question_type_local']
who are the phd students?	'Tawnya', 'Francoise', 'Hanna', 'Igor'	['question_type_global', 'question_single_statement']
[she] has failed the thesis proposal exam
Who is on [that student]'s committee?	'Andrew', 'Eun'	['question_type_local']
What professors advise students who defended successfully?	'Casey', 'Yoshiko'	['question_type_global', 'question_two_hop_statement']
which students passed the qualifying exam?	'Tawnya', 'Francoise', 'Hanna', 'Igor'	['question_type_global', 'question_single_statement']
[that student] failed thesis proposal
What courses is [this person] taking?	'U601', 'U101'	['question_type_local']
Which students are part of the [applied physics] department	'Tereasa'	['question_type_global', 'question_two_hop_statement']
Which professors advise students who passed their proposal?	'Casey', 'Yoshiko'	['question_type_global', 'question_two_hop_statement']
Which phd students have [Eun] on their committee	'Tawnya', 'Francoise', 'Hanna', 'Igor'	['question_type_local']
Which are some courses that phd students take?	'G201', 'U601', 'U101'	['question_type_global', 'question_two_hop_statement']
which students passed the proposal exam?	'Tawnya', 'Francoise', 'Igor'	['question_type_global', 'question_single_statement']
which courses have some masters students enrolled?	'U601'	['question_type_global', 'question_two_hop_statement']
What professors advise students who defended successfully?	'Casey', 'Yoshiko'	['question_type_global', 'question_two_hop_statement']
What courses is [Casey] teaching?	'U104'	['question_type_local']
Which professors are conducting research in [applications of machine learning]	'Casey', 'Yoshiko'	['question_type_global', 'question_single_statement']
Which courses in the english department are TAed by phd students?	'G201'	['question_type_global', 'question_three_hop_statement']
What courses is [Stephine] TAing?	'G201'	['question_type_local']
What are the courses TAed by [that person]?	'G201'	['question_type_local']
Which courses are TAed by masters students?	'G201', 'U601', 'U101'	['question_type_global', 'question_two_hop_statement']
Which courses are offered this semester?	'G8001', 'U104', 'G201', 'U601', 'U101'	['question_type_global', 'question_single_statement']
What are all the courses?	'G8001', 'U104', 'G201', 'U601', 'U101'	['question_type_global', 'question_single_statement']
[that student] has failed the thesis proposal exam
What are the courses TAed by [this student]?	'G201'	['question_type_local']
Who are the professors working on [computational biology]?	'Andrew'	['question_type_global', 'question_single_statement']
Which [assistant] professors advise students who passed their defense?	'Yoshiko'	['question_type_global', 'question_three_hop_statement']
Who are the professors working on [theoretical cosmology]?	'Eun'	['question_type_global', 'question_single_statement']
What are the [full_semester_course]?	'G8001', 'G201', 'U601'	['question_type_global', 'question_single_statement']
Which students are taking [U601]?	'Francoise', 'Hanna', 'Stephine'	['question_type_local']
which students passed the qualifying exam?	'Tawnya', 'Francoise', 'Hanna', 'Igor'	['question_type_global', 'question_single_statement']
Which department is [G201] part of?	'english'	['question_type_local']
Which students are part of the [applied physics] department	'Tereasa'	['question_type_global', 'question_two_hop_statement']
What [assistant] professors advise students who defended successfully?	'Yoshiko'	['question_type_global', 'question_three_hop_statement']
[that person] has failed the thesis proposal exam
Who is taking [U601]?	'Francoise', 'Hanna', 'Stephine'	['question_type_local']
[she] has failed the thesis proposal exam
What courses is [Bob] TAing?	'U601'	['question_type_local']
Which courses are offered this semester in the english department?	'G201'	['question_type_global', 'question_two_hop_statement']
[she] failed thesis proposal
Which courses did [that student] enroll in?	'U601', 'U101'	['question_type_local']
which students passed the qualifying exam?	'Tawnya', 'Francoise', 'Hanna', 'Igor'	['question_type_global', 'question_single_statement']
which courses have some phd students enrolled?	'G201', 'U601', 'U101'	['question_type_global', 'question_two_hop_statement']
Which students are in their [sixth year]	'Tawnya', 'Igor'	['question_type_global', 'question_single_statement']
Which masters courses are TAed by phd students?	'G201'	['question_type_global', 'question_three_hop_statement']
Who has an office in [Duane Building]	'Francoise'	['question_type_global', 'question_two_hop_statement']
Who has [Yoshiko] on their phd committee?	'Tawnya', 'Francoise'	['question_type_local']
Which courses are [full_semester_course]	'G8001', 'G201', 'U601'	['question_type_global', 'question_single_statement']
who are the masters students?	'Tereasa', 'Stephine', 'Bob'	['question_type_global', 'question_single_statement']
Which courses in the english department have masters TAs?	'G201'	['question_type_global', 'question_three_hop_statement']
[she] passed thesis proposal
What professors are on [this person]'s committee	'Andrew', 'Eun'	['question_type_local']
Which courses have masters student TAs?	'G201', 'U601', 'U101'	['question_type_global', 'question_two_hop_statement']
which students passed the qualifying exam?	'Tawnya', 'Francoise', 'Hanna', 'Igor'	['question_type_global', 'question_single_statement']
which [undergraduate] courses have some masters students enrolled?	'U601'	['question_type_global', 'question_three_hop_statement']
[Francoise] is now in [sixth year]
What are the courses that [he] is enrolled in?	'G201', 'U601'	['question_type_local']
Which courses are offered this semester?	'G8001', 'U104', 'G201', 'U601', 'U101'	['question_type_global', 'question_single_statement']
what [undergraduate] courses have phd students taking them?	'U601'	['question_type_global', 'question_three_hop_statement']
who are the professors?	'Casey', 'Andrew', 'Yoshiko', 'Eun'	['question_type_global', 'question_single_statement']
Who is [he]'s advisor?	'Casey'	['question_type_local']
What are the 8 unit courses?	'G201'	['question_type_global', 'question_single_statement']
What are the courses TAed by [Bob]?	'U601'	['question_type_local']
What [assistant] professors advise students who defended successfully?	'Yoshiko'	['question_type_global', 'question_three_hop_statement']
Which students have offices in Community Building	'Tawnya'	['question_type_global', 'question_two_hop_statement']
Who is in the [electrical engineering] department	'Bob'	['question_type_global', 'question_single_statement']
Which professors are conducting research in [computational biology]	'Andrew'	['question_type_global', 'question_single_statement']
What masters students are taking U601	'Stephine'	['question_type_global', 'question_two_hop_statement']
Who has an office in [Ekeley Building]	'Hanna'	['question_type_global', 'question_two_hop_statement']
Which courses have masters student TAs?	'G201', 'U601', 'U101'	['question_type_global', 'question_two_hop_statement']
[Casey] is on [Hanna]'s committee
Which courses are TAed by phd students in their sixth year?	'G8001', 'U101'	['question_type_global', 'question_three_hop_statement']
Who are the [fifth year] students?	'Hanna'	['question_type_global', 'question_single_statement']
Who is in the [applied physics] department	'Tereasa'	['question_type_global', 'question_single_statement']
who are the phd students?	'Tawnya', 'Francoise', 'Hanna', 'Igor'	['question_type_global', 'question_single_statement']
Create a new [phd] level course called [G203]
[Stephine] and [Francoise] are both taking [G203]
[G203] is a course in the [applied physics] department
What professors advise students who passed their thesis proposal?	'Casey', 'Yoshiko'	['question_type_global', 'question_two_hop_statement']
Which courses are [full_semester_course]	'G8001', 'G201', 'U601'	['question_type_global', 'question_single_statement']
[Stephine] is a student in [G203]
[that course] is taught by [Eun]
Who is TAing [G201]?	'Hanna', 'Stephine'	['question_type_local']
Which students's advisors are conducting research in [applications of machine learning]	'Tawnya', 'Francoise', 'Hanna', 'Igor'	['question_type_global', 'question_two_hop_statement']
Who are the professors working on [applications of machine learning]?	'Casey', 'Yoshiko'	['question_type_global', 'question_single_statement']
Which students are in their [sixth year]	'Tawnya', 'Francoise', 'Igor'	['question_type_global', 'question_single_statement']
Who is teaching [U601]?	'Yoshiko'	['question_type_local']
Who is on [Hanna]'s committee?	'Casey', 'Andrew', 'Eun'	['question_type_local']
who are the students?	'Tereasa', 'Tawnya', 'Francoise', 'Hanna', 'Igor', 'Stephine', 'Bob'	['question_type_global', 'question_single_statement']
What are all the courses?	'G8001', 'U104', 'G201', 'U601', 'U101', 'G203'	['question_type_global', 'question_single_statement']
What are all the courses in the electrical engineering department?	'U601'	['question_type_global', 'question_two_hop_statement']
Which courses are TAed by phd students that passed their qualifier exam or have some funding?	'G8001', 'G201', 'U101'	['question_type_global', 'question_four_hop_statement']
Which courses are offered this semester?	'G8001', 'U104', 'G201', 'U601', 'U101', 'G203'	['question_type_global', 'question_single_statement']
Which department is [G203] part of?	'applied physics'	['question_type_local']
Which phd students are both taking a course and a TA?	'Tawnya', 'Francoise', 'Hanna', 'Igor'	['question_type_global', 'question_three_hop_statement']
Which phd students taking the G201 course	'Tawnya', 'Francoise'	['question_type_global', 'question_two_hop_statement']
[that course] is a mini course
[Francoise] is attending [G203]
Which courses have phd student TAs?	'G8001', 'G201', 'U101'	['question_type_global', 'question_two_hop_statement']
Who are the [fifth year] students?	'Hanna'	['question_type_global', 'question_single_statement']
Which students are in their [sixth year]	'Tawnya', 'Francoise', 'Igor'	['question_type_global', 'question_single_statement']
Which courses are TAed by masters students?	'G201', 'U601', 'U101'	['question_type_global', 'question_two_hop_statement']
Which students are taking [U601]?	'Francoise', 'Hanna', 'Stephine'	['question_type_local']
Who is enrolled in [that class]?	'Francoise', 'Stephine'	['question_type_local']
Which professors are conducting research in [computational biology]	'Andrew'	['question_type_global', 'question_single_statement']
which [undergraduate] courses have no masters students enrolled?	'U104'	['question_type_global', 'question_three_hop_statement']
what courses have no masters students taking them?	'G8001', 'U104', 'G201', 'U101'	['question_type_global', 'question_two_hop_statement']
What professors are on [Hanna]'s committee	'Casey', 'Andrew', 'Eun'	['question_type_local']
Which phd courses have phd student TAs?	'U101'	['question_type_global', 'question_three_hop_statement']
Which [sixth year] students's advisors are conducting research in [applications of machine learning]	'Tawnya', 'Francoise', 'Igor'	['question_type_global', 'question_three_hop_statement']
What are all the courses in the electrical engineering department?	'U601'	['question_type_global', 'question_two_hop_statement']
There is a [phd] 2 unit class called [G101]
[Tereasa] and [Igor] are both enrolled in [that course]
Which courses are TAed by masters students?	'G201', 'U601', 'U101'	['question_type_global', 'question_two_hop_statement']
which students passed the qualifying exam?	'Tawnya', 'Francoise', 'Hanna', 'Igor'	['question_type_global', 'question_single_statement']
Create a new course called [G310]
[Tereasa] and [Hanna] are taking [that class]
what courses have phd students taking them?	'G201', 'U601', 'U101', 'G203', 'G101', 'G310'	['question_type_global', 'question_two_hop_statement']
Which courses are [phd] level courses?	'U101', 'G203', 'G101'	['question_type_global', 'question_single_statement']
Which courses in the electrical engineering department are TAed by masters students?	'U601'	['question_type_global', 'question_three_hop_statement']
What courses is [Francoise] taking?	'G201', 'U601', 'G203'	['question_type_local']
Which courses have phd student TAs that passed the qualifying exam?	'G8001', 'G201', 'U101'	['question_type_global', 'question_three_hop_statement']
There is a course called [G610]
[that class] is a course in the [english] department
Who are the [assistant] professors?	'Andrew', 'Yoshiko'	['question_type_global', 'question_single_statement']
which students passed the proposal exam?	'Tawnya', 'Francoise', 'Hanna', 'Igor'	['question_type_global', 'question_single_statement']
