there is a [professor] named [Loyd]
[this person] is in [Balch Building]
Who is in [Balch Building]	'Loyd'	['question_type_global', 'question_two_hop_statement']
[that person] is on sabbatical
What is [that professor]'s office?	'Balch Building'	['question_type_local']
Which professors are currently on sabbatical?	'Loyd'	['question_type_global', 'question_single_statement']
there is a [distinguished] [professor] named [Francoise]
[Francoise] went on sabbatical
[that professor]'s research interest is [cold fusion]
[this person] is not on sabbatical anymore
What is [that person]'s department?	"I don't know"	['question_type_local']
Which professors have offices in Balch Building	'Loyd'	['question_type_global', 'question_two_hop_statement']
create a [assistant] [professor] named [Casey]
[Francoise] is in [Imig Building]
Who are the professors working on [cold fusion]?	'Francoise'	['question_type_global', 'question_single_statement']
[Andrew] is a [professor]
What is [Francoise]'s office?	'Imig Building'	['question_type_local']
Who has an office in [Balch Building]	'Loyd'	['question_type_global', 'question_two_hop_statement']
What office is [Loyd] in?	'Balch Building'	['question_type_local']
What is [Francoise]'s research focus?	'cold fusion'	['question_type_local']
There is a course called [U201]
There is a course called [U103]
[U103] is set up as a full semester course
[this course] is a pass-fail course
there is a new masters student named [Vivienne]
the affiliation of [that person] is [electrical engineering]
there is a [fifth year] PhD student named [Bob]
[Bob] has passed the thesis proposal exam
[Bob] passed the qualifiers
which courses have no masters students enrolled?	'U201', 'U103'	['question_type_global', 'question_two_hop_statement']
[he] has [Francoise] on the committee
Which courses are [full_semester_course]	'U103'	['question_type_global', 'question_single_statement']
[Andrew] research interest is in [supervised learning]
Which professors are currently on sabbatical?	'Loyd'	['question_type_global', 'question_single_statement']
Who are the professors working on [supervised learning]?	'Andrew'	['question_type_global', 'question_single_statement']
Who has an office in [Imig Building]	'Francoise'	['question_type_global', 'question_two_hop_statement']
there is a new PhD student named [Cecil]
[this professor] advises [that student]
[that professor] is now on sabbatical
Who is part of the [electrical engineering] department	'Vivienne'	['question_type_global', 'question_single_statement']
Create a new course called [G301]
[physics] offers [this course]
[Bob] is [Loyd]'s student
What professors advise students who passed their thesis qualifiers?	'Loyd'	['question_type_global', 'question_two_hop_statement']
What are all the courses?	'U201', 'U103', 'G301'	['question_type_global', 'question_single_statement']
[Casey] is on sabbatical
[this professor]'s office is [Imig Building]
who are the students?	'Vivienne', 'Bob', 'Cecil'	['question_type_global', 'question_single_statement']
[Andrew] is in [Fleming Building]
what courses have no phd students taking them?	'U201', 'U103', 'G301'	['question_type_global', 'question_two_hop_statement']
What professors are in Fleming Building	'Andrew'	['question_type_global', 'question_two_hop_statement']
there is a new masters student named [Tawnya]
who are the masters students?	'Vivienne', 'Tawnya'	['question_type_global', 'question_single_statement']
Which professors are on sabbatical and are also advising students?	'Loyd', 'Andrew'	['question_type_global', 'question_two_hop_statement']
What professors that currently advise students are going on sabbatical?	'Loyd', 'Andrew'	['question_type_global', 'question_two_hop_statement']
there is a [assistant] [professor] named [Gabrielle]
[this student] is affiliated with the [physics] department
What are the [physics] courses?	'G301'	['question_type_global', 'question_single_statement']
there is a [first year] PhD student named [Peggy]
there is a [professor] named [Marisela]
[this student] passed thesis defense
[Marisela]'s office is [Gamow Building]
What is [this professor]'s office?	'Gamow Building'	['question_type_local']
Who are the students in the [electrical engineering] department	'Vivienne'	['question_type_global', 'question_two_hop_statement']
who are the professors?	'Loyd', 'Francoise', 'Casey', 'Andrew', 'Gabrielle', 'Marisela'	['question_type_global', 'question_single_statement']
there is a new masters student named [Tom]
[this professor] conducts research in [supervised learning]
who are the students?	'Vivienne', 'Bob', 'Cecil', 'Tawnya', 'Peggy', 'Tom'	['question_type_global', 'question_single_statement']
[Peggy] is [Gabrielle]'s student
[this professor] is in [Ward Building]
What office is [Andrew] in?	'Fleming Building'	['question_type_local']
Which courses are [full_semester_course]	'U103'	['question_type_global', 'question_single_statement']
which students passed the proposal exam?	'Bob'	['question_type_global', 'question_single_statement']
Create a new course called [G8001]
What professors advise students who defended successfully?	'Gabrielle'	['question_type_global', 'question_two_hop_statement']
[Casey]'s research interest is [reinforcement learning]
Who is in the [physics] department	'Tawnya'	['question_type_global', 'question_single_statement']
What professors are in Imig Building	'Francoise', 'Casey'	['question_type_global', 'question_two_hop_statement']
Create a new [undergraduate] level [mini course] called [G203]
What is [that professor] research area?	'reinforcement learning'	['question_type_local']
Which courses are offered this semester in the physics department?	'G301'	['question_type_global', 'question_two_hop_statement']
[Lizeth] is a masters student
[that class] is offered in the [physics] department
Which department is [this course] part of?	'physics'	['question_type_local']
there is a masters student named [Roslyn]
Who advises [Cecil]?	'Andrew'	['question_type_local']
Which courses are [undergraduate] level courses?	'G203'	['question_type_global', 'question_single_statement']
[Lucy] is a PhD student
[Roslyn]'s department is [applied physics]
Which students are in their [fifth year]	'Bob'	['question_type_global', 'question_single_statement']
What office is [Casey] in?	'Imig Building'	['question_type_local']
Who are [Gabrielle]'s students?	'Peggy'	['question_type_local']
create a [professor] named [Alverta]
what courses have no masters students taking them?	'U201', 'U103', 'G301', 'G8001', 'G203'	['question_type_global', 'question_two_hop_statement']
[G8001] is a [undergraduate] level course
[that course] is a course in the [computer science] department
[that course] is not a pass-fail course
what [undergraduate] courses have no masters students taking them?	'G8001', 'G203'	['question_type_global', 'question_three_hop_statement']
[Tom] is taking [this course]
there is a [assistant] [professor] named [Milagros]
[this student] is affiliated with the [physics] department
which courses have some masters students enrolled?	'G8001'	['question_type_global', 'question_two_hop_statement']
There is a course called [G610]
What are the courses that [this student] is enrolled in?	'G8001'	['question_type_local']
[Lucy] is [Francoise]'s student
What is [he]'s office?	'Imig Building'	['question_type_local']
[Bob] is enrolled in [G301]
What department is [that course] offered in?	'physics'	['question_type_local']
Which professors are on sabbatical and are also advising students?	'Loyd', 'Andrew'	['question_type_global', 'question_two_hop_statement']
[G203] is a pass-fail course
which courses have some phd students enrolled?	'G301'	['question_type_global', 'question_two_hop_statement']
what courses have phd students taking them?	'G301'	['question_type_global', 'question_two_hop_statement']
which students passed the qualifying exam?	'Bob'	['question_type_global', 'question_single_statement']
Which department is [G203] part of?	'physics'	['question_type_local']
[Tom] and [Cecil] are TAs for [that class]
[Casey] teaches [G203]
Which department is [G8001] in?	'computer science'	['question_type_local']
Which courses are [undergraduate] level courses?	'G8001', 'G203'	['question_type_global', 'question_single_statement']
[Bob] is attending [G203]
Who is teaching [that course]?	'Casey'	['question_type_local']
which students passed the defense?	'Peggy'	['question_type_global', 'question_single_statement']
[G8001] is taught by [Loyd]
[Lizeth] and [Tom] are both taking [G8001]
Who is teaching [G8001]?	'Loyd'	['question_type_local']
Who is in the [physics] department	'Tawnya', 'Tom'	['question_type_global', 'question_single_statement']
[G8001] will be set up as a mini course
[Peggy] and [Lizeth] are TAing [this course]
Which department is [G301] part of?	'physics'	['question_type_local']
Which courses have masters student TAs?	'G8001', 'G203'	['question_type_global', 'question_two_hop_statement']
[Lizeth] is affiliated with the [mechanical engineering] department
Which courses did [she] enroll in?	'G8001'	['question_type_local']
Which professors advise students who passed their defense?	'Gabrielle'	['question_type_global', 'question_two_hop_statement']
Which students are advised by professors working on [cold fusion]?	'Lucy'	['question_type_global', 'question_two_hop_statement']
What courses is [this person] taking?	'G8001'	['question_type_local']
Which courses in the physics department are TAed by masters students?	'G203'	['question_type_global', 'question_three_hop_statement']
which students passed the proposal exam?	'Bob'	['question_type_global', 'question_single_statement']
What are the courses that [she] is enrolled in?	'G8001'	['question_type_local']
What students currently have their advisor on sabbatical	'Bob', 'Cecil'	['question_type_global', 'question_two_hop_statement']
What [assistant] professors advise students who defended successfully?	'Gabrielle'	['question_type_global', 'question_three_hop_statement']
[Bob] currently has funding
which courses have some phd students enrolled?	'G301', 'G203'	['question_type_global', 'question_two_hop_statement']
Who is part of the [applied physics] department	'Roslyn'	['question_type_global', 'question_single_statement']
Which professors advise students who passed their qualifying exam?	'Loyd'	['question_type_global', 'question_two_hop_statement']
[he] passed thesis defense
[Peggy] passed thesis proposal
[she]'s office is [Balch Building]
Who is [Peggy]'s advisor?	'Gabrielle'	['question_type_local']
Which professors are conducting research in [supervised learning]	'Andrew', 'Marisela'	['question_type_global', 'question_single_statement']
what [undergraduate] courses have masters students taking them?	'G8001'	['question_type_global', 'question_three_hop_statement']
[Peggy] did not pass the qualifiers
Which courses have masters student TAs?	'G8001', 'G203'	['question_type_global', 'question_two_hop_statement']
who are the masters students?	'Vivienne', 'Tawnya', 'Tom', 'Lizeth', 'Roslyn'	['question_type_global', 'question_single_statement']
Create a new course called [U310]
[that class] is a pass-fail course
[that class] will be a mini course
which courses have some phd students enrolled?	'G301', 'G203'	['question_type_global', 'question_two_hop_statement']
what courses have no phd students taking them?	'U201', 'U103', 'G8001', 'G610', 'U310'	['question_type_global', 'question_two_hop_statement']
[Tawnya] and [Roslyn] are TAing [U310]
[Lucy] and [Vivienne] are taking [U310]
What students are enrolled in [U310]?	'Vivienne', 'Lucy'	['question_type_local']
Which professors are on sabbatical and are also advising students?	'Loyd', 'Andrew'	['question_type_global', 'question_two_hop_statement']
which courses have no phd students enrolled?	'U201', 'U103', 'G8001', 'G610'	['question_type_global', 'question_two_hop_statement']
Which courses have masters student TAs?	'G8001', 'G203', 'U310'	['question_type_global', 'question_two_hop_statement']
[Bob] is a TA for [G301]
[Gabrielle] teaches [that course]
Who is teaching [this course]?	'Gabrielle'	['question_type_local']
who are the professors?	'Loyd', 'Francoise', 'Casey', 'Andrew', 'Gabrielle', 'Marisela', 'Alverta', 'Milagros'	['question_type_global', 'question_single_statement']
Who are [Andrew]'s students?	'Cecil'	['question_type_local']
Which students are funded?	'Bob'	['question_type_global', 'question_single_statement']
Which courses are TAed by phd students that passed their qualifier exam and have some funding?	'G301'	['question_type_global', 'question_four_hop_statement']
Which courses are TAed by phd students that passed their qualifier exam or have some funding?	'G301'	['question_type_global', 'question_four_hop_statement']
who are the phd students?	'Bob', 'Cecil', 'Peggy', 'Lucy'	['question_type_global', 'question_single_statement']
who are the masters students?	'Vivienne', 'Tawnya', 'Tom', 'Lizeth', 'Roslyn'	['question_type_global', 'question_single_statement']
[that course] is a full semester course
[that class] is not a pass-fail course
Who is enrolled in [G301]?	'Bob'	['question_type_local']
Which courses are offered this semester?	'U201', 'U103', 'G301', 'G8001', 'G203', 'G610', 'U310'	['question_type_global', 'question_single_statement']
which courses have some phd students enrolled?	'G301', 'G203', 'U310'	['question_type_global', 'question_two_hop_statement']
Create a new [masters] level 12 unit course called [G201]
[G301] is a [masters] level course
which students passed the proposal exam?	'Bob', 'Peggy'	['question_type_global', 'question_single_statement']
Which professors are teaching [undergraduate] courses?	'Loyd', 'Casey'	['question_type_global', 'question_two_hop_statement']
[Vivienne] is taking [G301]
Who is taking [this course]?	'Vivienne', 'Bob'	['question_type_local']
Which courses are TAed by phd students?	'G301', 'G8001', 'G203'	['question_type_global', 'question_two_hop_statement']
What are the [physics] courses?	'G301', 'G203'	['question_type_global', 'question_single_statement']
[Tom] is attending [G301]
[Lucy] and [Vivienne] are TAing [G301]
Who is taking [G301]?	'Vivienne', 'Bob', 'Tom'	['question_type_local']
Which courses are TAed by masters students?	'G301', 'G8001', 'G203', 'U310'	['question_type_global', 'question_two_hop_statement']
Which courses are part of the [physics] department	'G301', 'G203'	['question_type_global', 'question_single_statement']
What courses is [Vivienne] TAing?	'G301'	['question_type_local']
What professors are in Fleming Building	'Andrew'	['question_type_global', 'question_two_hop_statement']
Which courses have phd student TAs?	'G301', 'G8001', 'G203'	['question_type_global', 'question_two_hop_statement']
[Vivienne] and [Bob] are both enrolled in [G201]
[G201] will be a full semester course
What courses is [Vivienne] taking?	'G301', 'U310', 'G201'	['question_type_local']
Which courses have phd student TAs that either have some funding or passed the qualifying exam?	'G301'	['question_type_global', 'question_four_hop_statement']
What are the 12 unit courses?	'G201'	['question_type_global', 'question_single_statement']
[Marisela] is the instructor for [G201]
Which courses have masters student TAs?	'G301', 'G8001', 'G203', 'U310'	['question_type_global', 'question_two_hop_statement']
Which courses are TAed by masters students?	'G301', 'G8001', 'G203', 'U310'	['question_type_global', 'question_two_hop_statement']
Which [assistant] professors advise students who passed their defense?	'Gabrielle'	['question_type_global', 'question_three_hop_statement']
which [undergraduate] courses have some phd students enrolled?	'G203'	['question_type_global', 'question_three_hop_statement']
[Cecil] has [Francoise] on the committee
[Cecil] successfully defended their thesis
What courses is [that student] TAing?	'G203'	['question_type_local']
Which masters courses are TAed by phd students?	'G301'	['question_type_global', 'question_three_hop_statement']
[Bob] and [Lizeth] are both enrolled in [G201]
Which professors are currently on sabbatical?	'Loyd', 'Casey', 'Andrew'	['question_type_global', 'question_single_statement']
Which professors have offices in Gamow Building	'Marisela'	['question_type_global', 'question_two_hop_statement']
What courses is [Tawnya] TAing?	'U310'	['question_type_local']
which students passed the qualifying exam?	'Bob'	['question_type_global', 'question_single_statement']
Which courses are TAed by phd students that passed their qualifier exam or have some funding?	'G301'	['question_type_global', 'question_four_hop_statement']
[he]'s office is [Koelbel Building]
which students passed the proposal exam?	'Bob', 'Peggy'	['question_type_global', 'question_single_statement']
Who is teaching [G8001]?	'Loyd'	['question_type_local']
Which are some courses that no phd student is taking?	'U201', 'U103', 'G8001', 'G610'	['question_type_global', 'question_two_hop_statement']
Which professors are on sabbatical and are also advising students?	'Loyd', 'Andrew'	['question_type_global', 'question_two_hop_statement']
Which courses are TAed by [Vivienne]?	'G301'	['question_type_local']
Who is advised by a professor who is now on a sabbatical?	'Bob', 'Cecil'	['question_type_global', 'question_two_hop_statement']
which [undergraduate] courses have some masters students enrolled?	'G8001'	['question_type_global', 'question_three_hop_statement']
Which department is [G301] in?	'physics'	['question_type_local']
What masters students are taking G8001	'Tom', 'Lizeth'	['question_type_global', 'question_two_hop_statement']
There is a course called [U204]
[this person] is now a [sixth year] student
[this person] has [Casey] and [Alverta] on the committee
What students are in the [physics] department?	'Tawnya', 'Tom'	['question_type_global', 'question_two_hop_statement']
What are all the courses in the physics department?	'G301', 'G203'	['question_type_global', 'question_two_hop_statement']
Who has [he] on their phd committee?	'Bob'	['question_type_local']
Which are some [undergraduate] courses that phd students take?	'G203'	['question_type_global', 'question_three_hop_statement']
What are all the courses?	'U201', 'U103', 'G301', 'G8001', 'G203', 'G610', 'U310', 'G201', 'U204'	['question_type_global', 'question_single_statement']
Who is supposed to be teaching [mini course] and is currently on sabbatical?	'Loyd', 'Casey'	['question_type_global', 'question_three_hop_statement']
Who is currently TAing [G8001]?	'Peggy', 'Lizeth'	['question_type_local']
Who has an office in [Imig Building]	'Francoise', 'Casey'	['question_type_global', 'question_two_hop_statement']
Create a new [undergraduate] level course called [U104]
[she] is now on sabbatical
Which are some courses that masters students take?	'G301', 'G8001', 'U310', 'G201'	['question_type_global', 'question_two_hop_statement']
who are the professors?	'Loyd', 'Francoise', 'Casey', 'Andrew', 'Gabrielle', 'Marisela', 'Alverta', 'Milagros'	['question_type_global', 'question_single_statement']
Which courses are TAed by phd students that passed their qualifier exam and have some funding?	'G301'	['question_type_global', 'question_four_hop_statement']
There is a course called [G104]
[Bob] and [Cecil] are attending [this course]
[G104] is a mini course
Which [assistant] professors advise students who passed their proposal?	'Gabrielle'	['question_type_global', 'question_three_hop_statement']
Which courses are TAed by phd students that passed their qualifier exam or have some funding?	'G301'	['question_type_global', 'question_four_hop_statement']
