[fifth year] is a [Andy] PhD student
[Andy] has passed the thesis proposal exam
[he]'s office is [Community Building]
Who is in [Community Building]	'Andy'	['question_type_global', 'question_two_hop_statement']
create a [distinguished] [professor] named [Yoshiko]
[that professor] advises [Andy]
[that professor] has funding
Who does [that professor] advise?	'Andy'	['question_type_local']
there is a new masters student named [Britney]
Create a new course called [U104]
[that person] and [Andy] are both enrolled in [U104]
[U104] is set up as a full semester course
[applied physics] offers [that course]
[Andy] has passed the thesis defense
Who are the [fifth year] students?	'Andy'	['question_type_global', 'question_single_statement']
[Yoshiko]'s research interest is [molecular biology]
What are the courses that [Britney] is enrolled in?	'U104'	['question_type_local']
Who has an advisor with funding?	'Andy'	['question_type_global', 'question_two_hop_statement']
[Ashly] is a PhD student
[that student]'s office is [Education Building]
Which professors are conducting research in [molecular biology]	'Yoshiko'	['question_type_global', 'question_single_statement']
[Gabrielle] is a [teaching] [professor]
[that student] passed the qualifiers
there is a new PhD student named [Igor]
[he] has [Gabrielle] on the committee
what courses have masters students taking them?	'U104'	['question_type_global', 'question_two_hop_statement']
Who are the professors working on [molecular biology]?	'Yoshiko'	['question_type_global', 'question_single_statement']
there is a masters student named [Lizeth]
[Ashly] is [this professor]'s student
[this professor] currently has funding
[Gabrielle] conducts research in [programming languages]
Which phd students does [this professor] advise?	'Ashly'	['question_type_local']
What professors advise students who passed their thesis qualifiers?	'Gabrielle'	['question_type_global', 'question_two_hop_statement']
there is a new PhD student named [Albertha]
[Igor] is [Gabrielle]'s student
What are the courses that [Britney] is enrolled in?	'U104'	['question_type_local']
Which professors advise students who passed their proposal?	'Yoshiko'	['question_type_global', 'question_two_hop_statement']
There is a [masters] 8 unit class called [G203]
[this course] will be set up as a mini course
[Igor] is a student in [G203]
Who has an office in [Community Building]	'Andy'	['question_type_global', 'question_two_hop_statement']
which students passed the defense?	'Andy'	['question_type_global', 'question_single_statement']
who are the phd students?	'Andy', 'Ashly', 'Igor', 'Albertha'	['question_type_global', 'question_single_statement']
there is a [second year] PhD student named [Alejandra]
[Alejandra] has failed the qualifying exam
[this student] has passed the thesis defense
[that student] is in [CIRES Building]
Who advises [Andy]?	'Yoshiko'	['question_type_local']
Which courses are 8 unit courses?	'G203'	['question_type_global', 'question_single_statement']
Create a new course called [U201]
[Alejandra] failed thesis proposal
What courses is [Britney] taking?	'U104'	['question_type_local']
[that student] has passed the qualifying exam
[that student] passed thesis proposal
Which are some [masters] courses that phd students take?	'G203'	['question_type_global', 'question_three_hop_statement']
Which phd students does [Gabrielle] advise?	'Ashly', 'Igor'	['question_type_local']
who are the professors?	'Yoshiko', 'Gabrielle'	['question_type_global', 'question_single_statement']
Who in fifth year has an advisor with funding?	'Andy'	['question_type_global', 'question_three_hop_statement']
there is a [associate] [professor] named [Roslyn]
[Roslyn] conducts research in [evolution]
Who has an advisor with funding?	'Andy', 'Ashly', 'Igor'	['question_type_global', 'question_two_hop_statement']
which courses have no phd students enrolled?	'U201'	['question_type_global', 'question_two_hop_statement']
What are all the courses?	'U104', 'G203', 'U201'	['question_type_global', 'question_single_statement']
create a [assistant] [professor] named [Will]
[she] received funding
Who advises [Ashly]?	'Gabrielle'	['question_type_local']
Which professors advise students who passed their qualifying exam?	'Gabrielle'	['question_type_global', 'question_two_hop_statement']
create a [assistant] [professor] named [Marisela]
there is a new [sixth year] PhD student named [Andrew]
who are the professors?	'Yoshiko', 'Gabrielle', 'Roslyn', 'Will', 'Marisela'	['question_type_global', 'question_single_statement']
What students are taking G203	'Igor'	['question_type_global', 'question_single_statement']
Which students's advisors are conducting research in [molecular biology]	'Andy'	['question_type_global', 'question_two_hop_statement']
[Yoshiko] is the instructor for [G203]
[Andy] and [Lizeth] are attending [G203]
[Gabrielle] advises [Albertha]
who are the students?	'Andy', 'Britney', 'Ashly', 'Igor', 'Lizeth', 'Albertha', 'Alejandra', 'Andrew'	['question_type_global', 'question_single_statement']
What are the 8 unit courses?	'G203'	['question_type_global', 'question_single_statement']
there is a new [third year] PhD student named [Jack]
[he] is in [CIRES Building]
[Alejandra] and [that person] are [Will]'s student
Which professors are teaching [masters] courses?	'Yoshiko'	['question_type_global', 'question_two_hop_statement']
Who advises [Igor]?	'Gabrielle'	['question_type_local']
Who has an office in [Education Building]	'Ashly'	['question_type_global', 'question_two_hop_statement']
[Alejandra] is now in [third year]
Which [assistant] professors advise students who passed their defense?	'Will'	['question_type_global', 'question_three_hop_statement']
which courses have some phd students enrolled?	'U104', 'G203'	['question_type_global', 'question_two_hop_statement']
who are the phd students?	'Andy', 'Ashly', 'Igor', 'Albertha', 'Alejandra', 'Andrew', 'Jack'	['question_type_global', 'question_single_statement']
Who is [Andy]'s advisor?	'Yoshiko'	['question_type_local']
Which students are in a course that is instructed by their advisor?	'Andy'	['question_type_global', 'question_three_hop_statement']
[Andy] has failed the qualifying exam
[he] has [Roslyn] on the committee
Who is on [Igor]'s committee?	'Gabrielle'	['question_type_local']
What phd students are taking U104	'Andy'	['question_type_global', 'question_two_hop_statement']
which students passed the qualifying exam?	'Ashly', 'Alejandra'	['question_type_global', 'question_single_statement']
[G203] is not a pass-fail course
What is [Gabrielle]'s research focus?	'programming languages'	['question_type_local']
What are the courses that [Lizeth] is enrolled in?	'G203'	['question_type_local']
[Will] research interest is in [molecular biology]
Who is [Andy]'s advisor?	'Yoshiko'	['question_type_local']
Which are some courses that phd students take?	'U104', 'G203'	['question_type_global', 'question_two_hop_statement']
What professors advise students who passed their thesis qualifiers?	'Gabrielle', 'Will'	['question_type_global', 'question_two_hop_statement']
Which professors advise students who passed their qualifying exam?	'Gabrielle', 'Will'	['question_type_global', 'question_two_hop_statement']
what courses have masters students taking them?	'U104', 'G203'	['question_type_global', 'question_two_hop_statement']
[Vivienne] is a masters student
[Jack] passed thesis defense
there is a masters student named [Genevive]
[Jack] has passed the thesis proposal exam
Who is [he]'s advisor?	'Will'	['question_type_local']
which students passed the defense?	'Andy', 'Alejandra', 'Jack'	['question_type_global', 'question_single_statement']
there is a masters student named [Emmie]
[Jack] is now a [fourth year] student
[Gabrielle] is on [Jack]'s committee
Which phd students does [this professor] advise?	'Ashly', 'Igor', 'Albertha'	['question_type_local']
Which students are advised by professors working on [molecular biology]?	'Andy', 'Alejandra', 'Jack'	['question_type_global', 'question_two_hop_statement']
Which courses are offered this semester in the applied physics department?	'U104'	['question_type_global', 'question_two_hop_statement']
there is a [teaching] [professor] named [Zenaida]
[Gabrielle] advises [Andrew]
What courses is [Lizeth] taking?	'G203'	['question_type_local']
what courses have phd students taking them?	'U104', 'G203'	['question_type_global', 'question_two_hop_statement']
there is a [third year] PhD student named [Cecil]
[Cecil]'s office is [CIRES Building]
[Cecil] successfully defended their thesis
What are all the courses?	'U104', 'G203', 'U201'	['question_type_global', 'question_single_statement']
What are the 8 unit courses?	'G203'	['question_type_global', 'question_single_statement']
What professors advise students who passed their thesis proposal?	'Yoshiko', 'Will'	['question_type_global', 'question_two_hop_statement']
Which courses are [full_semester_course]	'U104'	['question_type_global', 'question_single_statement']
Which [teaching] professors advise students who passed their qualifying exam?	'Gabrielle'	['question_type_global', 'question_three_hop_statement']
What are the [masters] courses?	'G203'	['question_type_global', 'question_single_statement']
[Cecil] has passed the qualifying exam
Which masters students taking the U104 course	'Britney'	['question_type_global', 'question_two_hop_statement']
[this student] is now a [fourth year] student
Which professors advise students who passed their qualifying exam?	'Gabrielle', 'Will'	['question_type_global', 'question_two_hop_statement']
Which are some courses that no masters student is taking?	'U201'	['question_type_global', 'question_two_hop_statement']
[this student] is [Yoshiko]'s student
Which department is [U104] part of?	'applied physics'	['question_type_local']
What are the [applied physics] courses?	'U104'	['question_type_global', 'question_single_statement']
which students passed the qualifying exam?	'Ashly', 'Alejandra', 'Cecil'	['question_type_global', 'question_single_statement']
who are the phd students?	'Andy', 'Ashly', 'Igor', 'Albertha', 'Alejandra', 'Andrew', 'Jack', 'Cecil'	['question_type_global', 'question_single_statement']
What students in fifth year are advised by a professor with funding?	'Andy'	['question_type_global', 'question_three_hop_statement']
Who advises [this student]?	'Yoshiko'	['question_type_local']
who are the professors?	'Yoshiko', 'Gabrielle', 'Roslyn', 'Will', 'Marisela', 'Zenaida'	['question_type_global', 'question_single_statement']
Which professors are teaching [masters] courses?	'Yoshiko'	['question_type_global', 'question_two_hop_statement']
Who are the [distinguished] professors?	'Yoshiko'	['question_type_global', 'question_single_statement']
Create a new course called [U202]
[this person] is now in [fifth year]
Which students's advisors are conducting research in [molecular biology]	'Andy', 'Alejandra', 'Jack', 'Cecil'	['question_type_global', 'question_two_hop_statement']
Which courses are offered this semester in the applied physics department?	'U104'	['question_type_global', 'question_two_hop_statement']
[he] has [Gabrielle] on the committee
[this student] is now in [sixth year]
Who is on [he]'s committee?	'Gabrielle'	['question_type_local']
What professors advise students who defended successfully?	'Yoshiko', 'Will'	['question_type_global', 'question_two_hop_statement']
What students are advised by a professor with funding?	'Andy', 'Ashly', 'Igor', 'Albertha', 'Andrew', 'Cecil'	['question_type_global', 'question_two_hop_statement']
[Marisela] and [Roslyn] are on [that student]'s committee
who are the students?	'Andy', 'Britney', 'Ashly', 'Igor', 'Lizeth', 'Albertha', 'Alejandra', 'Andrew', 'Jack', 'Vivienne', 'Genevive', 'Emmie', 'Cecil'	['question_type_global', 'question_single_statement']
Which professors advise students who passed their proposal?	'Yoshiko', 'Will'	['question_type_global', 'question_two_hop_statement']
[Marisela] received funding
which [masters] courses have some phd students enrolled?	'G203'	['question_type_global', 'question_three_hop_statement']
which students passed the defense?	'Andy', 'Alejandra', 'Jack', 'Cecil'	['question_type_global', 'question_single_statement']
What are the 8 unit courses?	'G203'	['question_type_global', 'question_single_statement']
Which professors advise students who passed their qualifying exam?	'Yoshiko', 'Gabrielle', 'Will'	['question_type_global', 'question_two_hop_statement']
[Marisela] and [Yoshiko] are on [Alejandra]'s committee
Who is on [Alejandra]'s committee?	'Yoshiko', 'Marisela'	['question_type_local']
Which [assistant] professors advise students who passed their qualifying exam?	'Will'	['question_type_global', 'question_three_hop_statement']
[Marisela] research interest is in [molecular biology]
Who is teaching [G203]?	'Yoshiko'	['question_type_local']
Who are the professors working on [programming languages]?	'Gabrielle'	['question_type_global', 'question_single_statement']
Which courses are [masters] level courses?	'G203'	['question_type_global', 'question_single_statement']
What is [Roslyn] research area?	'evolution'	['question_type_local']
who are the masters students?	'Britney', 'Lizeth', 'Vivienne', 'Genevive', 'Emmie'	['question_type_global', 'question_single_statement']
What are the [applied physics] courses?	'U104'	['question_type_global', 'question_single_statement']
What [distinguished] professors advise students who defended successfully?	'Yoshiko'	['question_type_global', 'question_three_hop_statement']
What students are advised by a professor with funding?	'Andy', 'Ashly', 'Igor', 'Albertha', 'Andrew', 'Cecil'	['question_type_global', 'question_two_hop_statement']
who are the phd students?	'Andy', 'Ashly', 'Igor', 'Albertha', 'Alejandra', 'Andrew', 'Jack', 'Cecil'	['question_type_global', 'question_single_statement']
Which phd students does [Yoshiko] advise?	'Andy', 'Cecil'	['question_type_local']
which courses have some masters students enrolled?	'U104', 'G203'	['question_type_global', 'question_two_hop_statement']
Who advises [Alejandra]?	'Will'	['question_type_local']
what courses have masters students taking them?	'U104', 'G203'	['question_type_global', 'question_two_hop_statement']
Which [assistant] professors advise students who passed their defense?	'Will'	['question_type_global', 'question_three_hop_statement']
What are the [applied physics] courses?	'U104'	['question_type_global', 'question_single_statement']
Who is [Albertha]'s advisor?	'Gabrielle'	['question_type_local']
what [masters] courses have phd students taking them?	'G203'	['question_type_global', 'question_three_hop_statement']
[U201] is part of the [applied physics] department
[U201] is a [phd] course
[U201] is taught by [Roslyn]
Who is [Ashly]'s advisor?	'Gabrielle'	['question_type_local']
who are the phd students?	'Andy', 'Ashly', 'Igor', 'Albertha', 'Alejandra', 'Andrew', 'Jack', 'Cecil'	['question_type_global', 'question_single_statement']
Which students are in a course that is instructed by their advisor?	'Andy'	['question_type_global', 'question_three_hop_statement']
Which professors have an [associate] status?	'Roslyn'	['question_type_global', 'question_single_statement']
[U104] is a [undergraduate] level course
Which courses did [Andy] enroll in?	'U104', 'G203'	['question_type_local']
Which [assistant] professors advise students who passed their proposal?	'Will'	['question_type_global', 'question_three_hop_statement']
[that class] is taught by [Zenaida]
[that course] is a pass-fail course
What students are advised by a professor with funding?	'Andy', 'Ashly', 'Igor', 'Albertha', 'Andrew', 'Cecil'	['question_type_global', 'question_two_hop_statement']
What courses is [she] teaching?	'U104'	['question_type_local']
who are the phd students?	'Andy', 'Ashly', 'Igor', 'Albertha', 'Alejandra', 'Andrew', 'Jack', 'Cecil'	['question_type_global', 'question_single_statement']
Who are the professors working on [programming languages]?	'Gabrielle'	['question_type_global', 'question_single_statement']
[Andy] is a TA for [U104]
[Jack] is taking [this course]
Who is enrolled in [this course]?	'Andy', 'Britney', 'Jack'	['question_type_local']
which students passed the defense?	'Andy', 'Alejandra', 'Jack', 'Cecil'	['question_type_global', 'question_single_statement']
What professors advise students who defended successfully?	'Yoshiko', 'Will'	['question_type_global', 'question_two_hop_statement']
What courses is [Roslyn] teaching?	'U201'	['question_type_local']
Which courses are TAed by phd students in their fifth year?	'U104'	['question_type_global', 'question_three_hop_statement']
What are the courses that [he] is enrolled in?	'U104'	['question_type_local']
What students are advised by a professor with funding?	'Andy', 'Ashly', 'Igor', 'Albertha', 'Andrew', 'Cecil'	['question_type_global', 'question_two_hop_statement']
Which students have offices in Community Building	'Andy'	['question_type_global', 'question_two_hop_statement']
Which students are taking [U104]?	'Andy', 'Britney', 'Jack'	['question_type_local']
What professors advise students who passed their thesis qualifiers?	'Yoshiko', 'Gabrielle', 'Will'	['question_type_global', 'question_two_hop_statement']
What is [Gabrielle] working on?	'programming languages'	['question_type_local']
What are all the courses?	'U104', 'G203', 'U201', 'U202'	['question_type_global', 'question_single_statement']
Which professors are teaching [undergraduate] courses?	'Zenaida'	['question_type_global', 'question_two_hop_statement']
Which courses are in the [applied physics] department?	'U104', 'U201'	['question_type_global', 'question_single_statement']
who are the students?	'Andy', 'Britney', 'Ashly', 'Igor', 'Lizeth', 'Albertha', 'Alejandra', 'Andrew', 'Jack', 'Vivienne', 'Genevive', 'Emmie', 'Cecil'	['question_type_global', 'question_single_statement']
[Cecil] has passed the thesis proposal exam
Who advises [Alejandra]?	'Will'	['question_type_local']
Who are the [assistant] professors?	'Will', 'Marisela'	['question_type_global', 'question_single_statement']
Who advises [Cecil]?	'Yoshiko'	['question_type_local']
who are the phd students?	'Andy', 'Ashly', 'Igor', 'Albertha', 'Alejandra', 'Andrew', 'Jack', 'Cecil'	['question_type_global', 'question_single_statement']
[Zenaida] and [Will] are on [Cecil]'s committee
[she] research interest is in [programming languages]
Who has [she] on their phd committee?	'Cecil'	['question_type_local']
which students passed the defense?	'Andy', 'Alejandra', 'Jack', 'Cecil'	['question_type_global', 'question_single_statement']
[he] currently has funding
Which courses are offered this semester?	'U104', 'G203', 'U201', 'U202'	['question_type_global', 'question_single_statement']
Which students have offices in Community Building	'Andy'	['question_type_global', 'question_two_hop_statement']
who are the students?	'Andy', 'Britney', 'Ashly', 'Igor', 'Lizeth', 'Albertha', 'Alejandra', 'Andrew', 'Jack', 'Vivienne', 'Genevive', 'Emmie', 'Cecil'	['question_type_global', 'question_single_statement']
Who is [Alejandra]'s advisor?	'Will'	['question_type_local']
which students passed the proposal exam?	'Andy', 'Alejandra', 'Jack', 'Cecil'	['question_type_global', 'question_single_statement']
Which courses are offered this semester in the applied physics department?	'U104', 'U201'	['question_type_global', 'question_two_hop_statement']
Which students are in their [fifth year]	'Andy'	['question_type_global', 'question_single_statement']
Which courses have phd student TAs?	'U104'	['question_type_global', 'question_two_hop_statement']
Which phd students does [he] advise?	'Alejandra', 'Jack'	['question_type_local']
who are the phd students?	'Andy', 'Ashly', 'Igor', 'Albertha', 'Alejandra', 'Andrew', 'Jack', 'Cecil'	['question_type_global', 'question_single_statement']
[Ashly] and [Andrew] are taking [U201]
[U201] is set up as a full semester course
[this course] is not a pass-fail course
[Ashly] is attending [this course]
which [phd] courses have no masters students enrolled?	'U201'	['question_type_global', 'question_three_hop_statement']
[Britney] is a student in [that course]
Which department is [U201] part of?	'applied physics'	['question_type_local']
Which courses are [masters] level courses?	'G203'	['question_type_global', 'question_single_statement']
Create a new [undergraduate] course called [G104]
Which courses are offered this semester in the applied physics department?	'U104', 'U201'	['question_type_global', 'question_two_hop_statement']
Which courses are TAed by phd students?	'U104'	['question_type_global', 'question_two_hop_statement']
What are the 8 unit courses?	'G203'	['question_type_global', 'question_single_statement']
what [undergraduate] courses have no masters students taking them?	'G104'	['question_type_global', 'question_three_hop_statement']
[this course] is a pass-fail course
What department is [U104] offered in?	'applied physics'	['question_type_local']
What phd students are taking G203	'Andy', 'Igor'	['question_type_global', 'question_two_hop_statement']
What students are advised by a professor with funding?	'Andy', 'Ashly', 'Igor', 'Albertha', 'Alejandra', 'Andrew', 'Jack', 'Cecil'	['question_type_global', 'question_two_hop_statement']
Which professors are conducting research in [evolution]	'Roslyn'	['question_type_global', 'question_single_statement']
[Will] has been promoted to [associate] professor
Which undergraduate courses are TAed by phd students?	'U104'	['question_type_global', 'question_three_hop_statement']
Which phd students are both taking a course and a TA?	'Andy'	['question_type_global', 'question_three_hop_statement']
Which undergraduate courses have phd student TAs?	'U104'	['question_type_global', 'question_three_hop_statement']
What professors advise students who passed their thesis proposal?	'Yoshiko', 'Will'	['question_type_global', 'question_two_hop_statement']
[Ashly] has passed the thesis defense
[Ashly] passed thesis proposal
[that student] is in their [first year]
[Vivienne] and [Jack] are both enrolled in [G104]
[G104] will be a full semester course
What masters students are taking G104	'Vivienne'	['question_type_global', 'question_two_hop_statement']
Which [fourth year] students are advised by professors working on [molecular biology]?	'Jack'	['question_type_global', 'question_three_hop_statement']
