there is a new masters student named [Gia]
the affiliation of [she] is [history]
there is a masters student named [Rachele]
[Rachele]'s department is [history]
[Emma] is a masters student
there is a new masters student named [Isaiah]
the affiliation of [he] is [asian studies]
Which students are part of the [asian studies] department	'Isaiah'	['question_type_global', 'question_two_hop_statement']
[Emmie] is a masters student
the affiliation of [she] is [electrical engineering]
there is a new masters student named [Loyd]
there is a [distinguished] [professor] named [Casey]
the affiliation of [this student] is [history]
Create a new course called [U601]
[this course] will be a full semester course
[that class] is a pass-fail course
[Casey] teaches [that course]
[Rachele] and [Isaiah] are TAs for [U601]
What courses is [she] TAing?	'U601'	['question_type_local']
Which courses have masters student TAs?	'U601'	['question_type_global', 'question_two_hop_statement']
[U601] is a [masters] course
[Rachele] is taking [U601]
Who is TAing [that class]?	'Rachele', 'Isaiah'	['question_type_local']
what courses have masters students taking them?	'U601'	['question_type_global', 'question_two_hop_statement']
there is a [assistant] [professor] named [Lucy]
[Lucy] research interest is in [conservation biology]
Who is teaching [U601]?	'Casey'	['question_type_local']
which courses have some masters students enrolled?	'U601'	['question_type_global', 'question_two_hop_statement']
[Lucy] is affiliated with the [history] department
[this professor]'s office is [Advising Center]
Who has an office in [Advising Center]	'Lucy'	['question_type_global', 'question_two_hop_statement']
What are the courses TAed by [Rachele]?	'U601'	['question_type_local']
What professors are in the [history] department?	'Lucy'	['question_type_global', 'question_two_hop_statement']
Which courses are offered this semester?	'U601'	['question_type_global', 'question_single_statement']
Which people are in the [electrical engineering] department?	'Emmie'	['question_type_global', 'question_single_statement']
which courses have no phd students enrolled?	'U601'	['question_type_global', 'question_two_hop_statement']
What courses is [Casey] teaching?	'U601'	['question_type_local']
Which people are in the [history] department?	'Gia', 'Rachele', 'Loyd', 'Lucy'	['question_type_global', 'question_single_statement']
Which students are both taking a course and a TA?	'Rachele'	['question_type_global', 'question_two_hop_statement']
[Yoshiko] is a masters student
Which are some [masters] courses that no phd student is taking?	'U601'	['question_type_global', 'question_three_hop_statement']
Who is taking the U601 course	'Rachele'	['question_type_global', 'question_single_statement']
What professors are in Advising Center	'Lucy'	['question_type_global', 'question_two_hop_statement']
[Loyd] and [Yoshiko] are taking [U601]
Who is teaching [U601]?	'Casey'	['question_type_local']
There is a course called [U103]
[Yoshiko] is affiliated with the [animal science] department
What courses is [Rachele] taking?	'U601'	['question_type_local']
Who is part of the [electrical engineering] department	'Emmie'	['question_type_global', 'question_single_statement']
Which professors are conducting research in [conservation biology]	'Lucy'	['question_type_global', 'question_single_statement']
Which courses are TAed by masters students?	'U601'	['question_type_global', 'question_two_hop_statement']
there is a [third year] PhD student named [Tawnya]
the affiliation of [Emma] is [history]
what courses have masters students taking them?	'U601'	['question_type_global', 'question_two_hop_statement']
who are the professors?	'Casey', 'Lucy'	['question_type_global', 'question_single_statement']
Create a new [masters] [mini course] called [G601]
The TA for [this course] is [Tawnya]
Which courses did [Rachele] enroll in?	'U601'	['question_type_local']
[Lizeth] is a [professor]
[that professor]'s office is [Lesser House]
the affiliation of [this person] is [animal science]
[Tawnya] is [she]'s student
What courses is [Isaiah] TAing?	'U601'	['question_type_local']
who are the students?	'Gia', 'Rachele', 'Emma', 'Isaiah', 'Emmie', 'Loyd', 'Yoshiko', 'Tawnya'	['question_type_global', 'question_single_statement']
the [animal science] department is headed by [Lizeth]
[Lizeth] research interest is in [experimental cosmology]
[Racquel] is a [distinguished] [professor]
What is [Lizeth] research area?	'experimental cosmology'	['question_type_local']
Which students are advised by professors working on [experimental cosmology]?	'Tawnya'	['question_type_global', 'question_two_hop_statement']
[Racquel]'s office is [Lesser House]
[this person] research interest is in [experimental cosmology]
Who are the professors in the [history] department?	'Lucy'	['question_type_global', 'question_two_hop_statement']
Which courses are TAed by masters students?	'U601'	['question_type_global', 'question_two_hop_statement']
Which [third year] students's advisors are conducting research in [experimental cosmology]	'Tawnya'	['question_type_global', 'question_three_hop_statement']
What is [Lizeth]'s office?	'Lesser House'	['question_type_local']
Who is teaching [masters] courses?	'Casey'	['question_type_global', 'question_two_hop_statement']
There is a [undergraduate] course called [U203]
[she]'s department is [history]
What is [Lucy]'s office?	'Advising Center'	['question_type_local']
which courses have some masters students enrolled?	'U601'	['question_type_global', 'question_two_hop_statement']
What students are advised by the head of the department?	'Tawnya'	['question_type_global', 'question_two_hop_statement']
what courses have no phd students taking them?	'U601', 'U103', 'G601', 'U203'	['question_type_global', 'question_two_hop_statement']
Who is teaching [full_semester_course]?	'Casey'	['question_type_global', 'question_two_hop_statement']
create a [professor] named [Francoise]
[Francoise] is affiliated with the [electrical engineering] department
[Francoise] is in [Balch Building]
Which are some [masters] courses that no phd student is taking?	'U601', 'G601'	['question_type_global', 'question_three_hop_statement']
What is [Racquel]'s department?	'history'	['question_type_local']
Who are the professors working on [experimental cosmology]?	'Lizeth', 'Racquel'	['question_type_global', 'question_single_statement']
What are the [full_semester_course]?	'U601'	['question_type_global', 'question_single_statement']
There is a [masters] level [mini course] called [U102]
who are the students?	'Gia', 'Rachele', 'Emma', 'Isaiah', 'Emmie', 'Loyd', 'Yoshiko', 'Tawnya'	['question_type_global', 'question_single_statement']
[Emmie] is attending [U102]
[Francoise] teaches [that class]
Who is taking [U102]?	'Emmie'	['question_type_local']
Which are some courses that masters students take?	'U601', 'U102'	['question_type_global', 'question_two_hop_statement']
Which students have an advisor who heads the department?	'Tawnya'	['question_type_global', 'question_two_hop_statement']
[Racquel] is the [history] department head
What masters students are taking U102	'Emmie'	['question_type_global', 'question_two_hop_statement']
Which people are in the [electrical engineering] department?	'Emmie', 'Francoise'	['question_type_global', 'question_single_statement']
What is [he]'s department?	'electrical engineering'	['question_type_local']
[William] is a [professor]
[William] is affiliated with the [electrical engineering] department
[that professor]'s office is [Benson Building]
What is [this person]'s office?	'Benson Building'	['question_type_local']
[William] heads the [electrical engineering] department
Which professors are conducting research in [conservation biology]	'Lucy'	['question_type_global', 'question_single_statement']
Which masters students taking the U601 course	'Rachele', 'Loyd', 'Yoshiko'	['question_type_global', 'question_two_hop_statement']
Create a new course called [G310]
[this person]'s research interest is [molecular biology]
What is [this person]'s department?	'electrical engineering'	['question_type_local']
Which students have an advisor who heads the department?	'Tawnya'	['question_type_global', 'question_two_hop_statement']
Which professors have an [distinguished] status?	'Casey', 'Racquel'	['question_type_global', 'question_single_statement']
[Tawnya] has passed the thesis defense
[she] has [Casey] on the committee
Who is [she]'s advisor?	'Lizeth'	['question_type_local']
What students are taking courses and TAing?	'Rachele'	['question_type_global', 'question_two_hop_statement']
[this student] has [Racquel] on the committee
Which professors have offices in Balch Building	'Francoise'	['question_type_global', 'question_two_hop_statement']
there is a new [second year] PhD student named [Alverta]
Which phd students have [Racquel] on their committee	'Tawnya'	['question_type_local']
What [masters] courses are taught by professors in the [electrical engineering] department?	'U102'	['question_type_global', 'question_three_hop_statement']
Who is in the [animal science] department	'Yoshiko', 'Lizeth'	['question_type_global', 'question_single_statement']
there is a new masters student named [Alejandra]
the affiliation of [Alejandra] is [animal science]
Who is enrolled in [U102]?	'Emmie'	['question_type_local']
Which courses have masters student TAs?	'U601'	['question_type_global', 'question_two_hop_statement']
which students passed the defense?	'Tawnya'	['question_type_global', 'question_single_statement']
[William] advises [Alverta]
Which courses are TAed by phd students?	'G601'	['question_type_global', 'question_two_hop_statement']
Which professors have offices in Balch Building	'Francoise'	['question_type_global', 'question_two_hop_statement']
[U103] is a [undergraduate] level course
Which professors are teaching [mini course]?	'Francoise'	['question_type_global', 'question_two_hop_statement']
Who is teaching [full_semester_course]?	'Casey'	['question_type_global', 'question_two_hop_statement']
There is a course called [G102]
[Alejandra] and [Yoshiko] are TAs for [G102]
Which courses are offered this semester?	'U601', 'U103', 'G601', 'U203', 'U102', 'G310', 'G102'	['question_type_global', 'question_single_statement']
who are the professors?	'Casey', 'Lucy', 'Lizeth', 'Racquel', 'Francoise', 'William'	['question_type_global', 'question_single_statement']
What are the [third year] phd students	'Tawnya'	['question_type_global', 'question_single_statement']
who are the phd students?	'Tawnya', 'Alverta'	['question_type_global', 'question_single_statement']
Create a new [undergraduate] level 4 unit course called [U201]
[Emma] is a student in [U201]
[this course] is a pass-fail course
[Lizeth] is the instructor for [that class]
What students are taking courses and TAing?	'Rachele', 'Yoshiko'	['question_type_global', 'question_two_hop_statement']
What departments are people in [Advising Center] affiliated with?	'history'	['question_type_global', 'question_two_hop_statement']
Who is teaching [this course]?	'Lizeth'	['question_type_local']
What are the [mini course]?	'G601', 'U102'	['question_type_global', 'question_single_statement']
What professors advise students who defended successfully?	'Lizeth'	['question_type_global', 'question_two_hop_statement']
What 4 unit courses are taught by those in the [animal science] department?	'U201'	['question_type_global', 'question_three_hop_statement']
Who has [Racquel] on their phd committee?	'Tawnya'	['question_type_local']
Which courses are TAed by masters students?	'U601', 'G102'	['question_type_global', 'question_two_hop_statement']
What courses is [Alejandra] TAing?	'G102'	['question_type_local']
There is a [masters] course called [G304]
[Emma] and [Alverta] are both taking [G304]
[G304] is a pass-fail course
What are the courses TAed by [Alejandra]?	'G102'	['question_type_local']
What are the [mini course]?	'G601', 'U102'	['question_type_global', 'question_single_statement']
There is a [phd] course called [U610]
[G304] is taught by [Racquel]
which students passed the defense?	'Tawnya'	['question_type_global', 'question_single_statement']
Create a new course called [G305]
What students are in the [asian studies] department?	'Isaiah'	['question_type_global', 'question_two_hop_statement']
[Lucy] is the instructor for [G310]
[Yoshiko] is taking [G310]
Which students have an advisor who heads the department?	'Tawnya', 'Alverta'	['question_type_global', 'question_two_hop_statement']
Which courses are TAed by masters students?	'U601', 'G102'	['question_type_global', 'question_two_hop_statement']
Who does [Lizeth] advise?	'Tawnya'	['question_type_local']
What courses is [this student] taking?	'U601', 'G310'	['question_type_local']
what courses have phd students taking them?	'G304'	['question_type_global', 'question_two_hop_statement']
[G310] is full semester
Who is teaching [G310]?	'Lucy'	['question_type_local']
Which professors have offices in Advising Center	'Lucy'	['question_type_global', 'question_two_hop_statement']
What are the courses TAed by [Isaiah]?	'U601'	['question_type_local']
Which courses are TAed by [she]?	'G102'	['question_type_local']
who are the phd students?	'Tawnya', 'Alverta'	['question_type_global', 'question_single_statement']
[G310] is a pass-fail course
[Emmie] is TAing [that class]
Who is teaching [that course]?	'Lucy'	['question_type_local']
who are the students?	'Gia', 'Rachele', 'Emma', 'Isaiah', 'Emmie', 'Loyd', 'Yoshiko', 'Tawnya', 'Alverta', 'Alejandra'	['question_type_global', 'question_single_statement']
Which phd students does [William] advise?	'Alverta'	['question_type_local']
Which courses have masters student TAs?	'U601', 'G310', 'G102'	['question_type_global', 'question_two_hop_statement']
Which courses did [Emmie] enroll in?	'U102'	['question_type_local']
Which professors are conducting research in [conservation biology]	'Lucy'	['question_type_global', 'question_single_statement']
What offices do people in the [history] department have?	'Advising Center', 'Lesser House'	['question_type_global', 'question_two_hop_statement']
[Isaiah] and [Yoshiko] are attending [that class]
The TA for [G310] is [Emma]
Who is taking the G304 course	'Emma', 'Alverta'	['question_type_global', 'question_single_statement']
[Rachele] and [Loyd] are both enrolled in [this course]
What courses is [Emma] TAing?	'G310'	['question_type_local']
Which masters students taking the U201 course	'Emma'	['question_type_global', 'question_two_hop_statement']
What are all the courses?	'U601', 'U103', 'G601', 'U203', 'U102', 'G310', 'G102', 'U201', 'G304', 'U610', 'G305'	['question_type_global', 'question_single_statement']
who are the students?	'Gia', 'Rachele', 'Emma', 'Isaiah', 'Emmie', 'Loyd', 'Yoshiko', 'Tawnya', 'Alverta', 'Alejandra'	['question_type_global', 'question_single_statement']
What courses is [Yoshiko] TAing?	'G102'	['question_type_local']
Which professors are conducting research in [experimental cosmology]	'Lizeth', 'Racquel'	['question_type_global', 'question_single_statement']
which students passed the defense?	'Tawnya'	['question_type_global', 'question_single_statement']
What courses is [she] TAing?	'U601'	['question_type_local']
Who is taking the G304 course	'Emma', 'Alverta'	['question_type_global', 'question_single_statement']
[Casey] research interest is in [neurocomputing]
who are the masters students?	'Gia', 'Rachele', 'Emma', 'Isaiah', 'Emmie', 'Loyd', 'Yoshiko', 'Alejandra'	['question_type_global', 'question_single_statement']
Which masters courses have phd student TAs?	'G601'	['question_type_global', 'question_three_hop_statement']
What courses are taught by professors in the [animal science] department?	'U201'	['question_type_global', 'question_two_hop_statement']
what [undergraduate] courses have no phd students taking them?	'U103', 'U203', 'U201'	['question_type_global', 'question_three_hop_statement']
What students are in the [history] department?	'Gia', 'Rachele', 'Emma', 'Loyd'	['question_type_global', 'question_two_hop_statement']
Who is enrolled in [G310]?	'Rachele', 'Isaiah', 'Loyd', 'Yoshiko'	['question_type_local']
What office is [Francoise] in?	'Balch Building'	['question_type_local']
What courses are taught by professors in the [history] department?	'G310', 'G304'	['question_type_global', 'question_two_hop_statement']
Which phd students have [this professor] on their committee	'Tawnya'	['question_type_local']
Who is part of the [asian studies] department	'Isaiah'	['question_type_global', 'question_single_statement']
What [full_semester_course] are taught by those in the [history] department?	'G310', 'G304'	['question_type_global', 'question_three_hop_statement']
[Tawnya] is now a [fourth year] student
[Tawnya] has [William] and [Francoise] on the committee
Which students are taking [G310]?	'Rachele', 'Isaiah', 'Loyd', 'Yoshiko'	['question_type_local']
Which courses are offered this semester?	'U601', 'U103', 'G601', 'U203', 'U102', 'G310', 'G102', 'U201', 'G304', 'U610', 'G305'	['question_type_global', 'question_single_statement']
What courses are taught by those in the [history] department?	'G310', 'G304'	['question_type_global', 'question_two_hop_statement']
Which students are both taking a course and a TA?	'Rachele', 'Emma', 'Isaiah', 'Emmie', 'Yoshiko'	['question_type_global', 'question_two_hop_statement']
What professors advise students who defended successfully?	'Lizeth'	['question_type_global', 'question_two_hop_statement']
What courses is [Emmie] TAing?	'G310'	['question_type_local']
[U103] is set up as a full semester course
Which courses are [full_semester_course]	'U601', 'U103', 'G310'	['question_type_global', 'question_single_statement']
[Gia] and [Alverta] are TAing [G304]
What students are going to TA [G102]?	'Yoshiko', 'Alejandra'	['question_type_local']
Which professors are conducting research in [experimental cosmology]	'Lizeth', 'Racquel'	['question_type_global', 'question_single_statement']
What are the courses TAed by [Rachele]?	'U601'	['question_type_local']
What [full_semester_course] are taught by professors in the [electrical engineering] department?	'U102'	['question_type_global', 'question_three_hop_statement']
Which students are taking [U201]?	'Emma'	['question_type_local']
Which are some courses that masters students take?	'U601', 'U102', 'G310', 'U201', 'G304'	['question_type_global', 'question_two_hop_statement']
What students are taking courses and TAing?	'Rachele', 'Emma', 'Isaiah', 'Emmie', 'Yoshiko', 'Alverta'	['question_type_global', 'question_two_hop_statement']
Which phd students are both taking a course and a TA?	'Alverta'	['question_type_global', 'question_three_hop_statement']
[Francoise] is on [Alverta]'s committee
[Alverta] currently has funding
[that student] is now a [third year] student
Who is teaching [U601]?	'Casey'	['question_type_local']
Which courses are 4 unit courses?	'U201'	['question_type_global', 'question_single_statement']
What phd students are taking courses and TAing?	'Alverta'	['question_type_global', 'question_three_hop_statement']
[Lucy] is on [Alverta]'s committee
[that student] successfully defended their thesis
who are the students?	'Gia', 'Rachele', 'Emma', 'Isaiah', 'Emmie', 'Loyd', 'Yoshiko', 'Tawnya', 'Alverta', 'Alejandra'	['question_type_global', 'question_single_statement']
who are the professors?	'Casey', 'Lucy', 'Lizeth', 'Racquel', 'Francoise', 'William'	['question_type_global', 'question_single_statement']
Who advises [Alverta]?	'William'	['question_type_local']
[this professor] is the head of the [history] department
Which courses did [Alverta] enroll in?	'G304'	['question_type_local']
Which courses are TAed by masters students?	'U601', 'G310', 'G102', 'G304'	['question_type_global', 'question_two_hop_statement']
[that student] passed thesis proposal
Who advises [that student]?	'William'	['question_type_local']
What students TA a course taught by the head of the department?	'Gia', 'Emma', 'Emmie', 'Alverta'	['question_type_global', 'question_three_hop_statement']
What masters students are taking G304	'Emma'	['question_type_global', 'question_two_hop_statement']
What is [Racquel]'s department?	'history'	['question_type_local']
What courses is [Emmie] taking?	'U102'	['question_type_local']
Where are the offices of those in the [animal science] department?	'Lesser House'	['question_type_global', 'question_two_hop_statement']
Who is [Tawnya]'s advisor?	'Lizeth'	['question_type_local']
Which professors are part of the [animal science] department?	'Lizeth'	['question_type_global', 'question_two_hop_statement']
What students TA a course taught by the head of the department?	'Gia', 'Emma', 'Emmie', 'Alverta'	['question_type_global', 'question_three_hop_statement']
Which courses did [Loyd] enroll in?	'U601', 'G310'	['question_type_local']
Which courses are TAed by phd students?	'G601', 'G304'	['question_type_global', 'question_two_hop_statement']
[this student]'s office is [Environmental Building]
[she] has [Casey] and [Lizeth] on the committee
What professors are in Benson Building	'William'	['question_type_global', 'question_two_hop_statement']
Who does [Lizeth] advise?	'Tawnya'	['question_type_local']
Which students are part of the [history] department	'Gia', 'Rachele', 'Emma', 'Loyd'	['question_type_global', 'question_two_hop_statement']
[he] is in [Gamow Building]
what courses have masters students taking them?	'U601', 'U102', 'G310', 'U201', 'G304'	['question_type_global', 'question_two_hop_statement']
What office is [she] in?	'Lesser House'	['question_type_local']
Which are some [phd] courses that no phd student is taking?	'U610'	['question_type_global', 'question_three_hop_statement']
Which courses have masters student TAs?	'U601', 'G310', 'G102', 'G304'	['question_type_global', 'question_two_hop_statement']
what courses have no phd students taking them?	'U601', 'U103', 'G601', 'U203', 'U102', 'G310', 'G102', 'U201', 'U610', 'G305'	['question_type_global', 'question_two_hop_statement']
Create a new course called [U304]
the affiliation of [this professor] is [animal science]
What are the courses TAed by [Emma]?	'G310'	['question_type_local']
who are the masters students?	'Gia', 'Rachele', 'Emma', 'Isaiah', 'Emmie', 'Loyd', 'Yoshiko', 'Alejandra'	['question_type_global', 'question_single_statement']
who are the professors?	'Casey', 'Lucy', 'Lizeth', 'Racquel', 'Francoise', 'William'	['question_type_global', 'question_single_statement']
