there is a [associate] [professor] named [Alejandra]
[that person] is affiliated with the [animal science] department
[this professor] is now on sabbatical
Which department is [Alejandra] in?	'animal science'	['question_type_local']
Which professors are currently on sabbatical?	'Alejandra'	['question_type_global', 'question_single_statement']
there is a PhD student named [Cecil]
[that professor]'s research interest is [computational biology]
Who are the professors in the [animal science] department?	'Alejandra'	['question_type_global', 'question_two_hop_statement']
there is a [professor] named [Jack]
[she] advises [Cecil]
Who is [Cecil]'s advisor?	'Alejandra'	['question_type_local']
who are the students?	'Cecil'	['question_type_global', 'question_single_statement']
Who is in the [animal science] department	'Alejandra'	['question_type_global', 'question_single_statement']
[this student] is a [sixth year] student
[that person] has passed the thesis proposal exam
[Jack] is on [he]'s committee
there is a new masters student named [Tawnya]
[this professor]'s research interest is [evolutionary biology]
Who is part of the [animal science] department	'Alejandra'	['question_type_global', 'question_single_statement']
there is a new PhD student named [Willis]
[this professor] and [Alejandra] are on [that student]'s committee
[Willis] passed thesis proposal
who are the phd students?	'Cecil', 'Willis'	['question_type_global', 'question_single_statement']
who are the professors?	'Alejandra', 'Jack'	['question_type_global', 'question_single_statement']
there is a new [sixth year] PhD student named [Gia]
What professors are on [Cecil]'s committee	'Jack'	['question_type_local']
What professors advise students who passed their thesis proposal?	'Alejandra'	['question_type_global', 'question_two_hop_statement']
[Tom] is a masters student
[he]'s department is [neuroscience]
What students are in the [neuroscience] department?	'Tom'	['question_type_global', 'question_two_hop_statement']
Which professors have an [associate] status?	'Alejandra'	['question_type_global', 'question_single_statement']
there is a masters student named [Bob]
Which professors are part of the [animal science] department?	'Alejandra'	['question_type_global', 'question_two_hop_statement']
Which professors are on sabbatical and are also advising students?	'Alejandra'	['question_type_global', 'question_two_hop_statement']
Who is on sabbatical?	'Alejandra'	['question_type_global', 'question_single_statement']
[Jack] is affiliated with the [asian studies] department
[Jack] is on sabbatical
[Bob] is affiliated with the [physics] department
What students currently have their advisor on sabbatical	'Cecil'	['question_type_global', 'question_two_hop_statement']
[Willis] successfully defended their thesis
[Willis] passed the qualifiers
[this student] is in their [third year]
Who are the professors working on [computational biology]?	'Alejandra'	['question_type_global', 'question_single_statement']
For which phd students does [Jack] serve on a committee?	'Cecil', 'Willis'	['question_type_local']
there is a new masters student named [Tereasa]
the affiliation of [Tereasa] is [physics]
[third year] is a [Emma] PhD student
Which students are part of the [physics] department	'Bob', 'Tereasa'	['question_type_global', 'question_two_hop_statement']
Who has [Jack] on their phd committee?	'Cecil', 'Willis'	['question_type_local']
There is a course called [U102]
[Emma] has passed the qualifying exam
[Jack] is an [teaching] professor
What professors advise students who passed their thesis proposal?	'Alejandra'	['question_type_global', 'question_two_hop_statement']
What are the [third year] phd students	'Willis', 'Emma'	['question_type_global', 'question_single_statement']
Who is on sabbatical this semester?	'Alejandra', 'Jack'	['question_type_global', 'question_single_statement']
Who are the students in the [neuroscience] department	'Tom'	['question_type_global', 'question_two_hop_statement']
[Alejandra] and [that professor] are on [she]'s committee
What are all the courses?	'U102'	['question_type_global', 'question_single_statement']
create a [distinguished] [professor] named [Roslyn]
What department is [Jack] affiliated with?	'asian studies'	['question_type_local']
[Roslyn] went on sabbatical
[Roslyn] is affiliated with the [asian studies] department
Which professors are conducting research in [evolutionary biology]	'Jack'	['question_type_global', 'question_single_statement']
which students passed the qualifying exam?	'Willis', 'Emma'	['question_type_global', 'question_single_statement']
[that person] conducts research in [computational biology]
which courses have no masters students enrolled?	'U102'	['question_type_global', 'question_two_hop_statement']
[Emma] and [Gia] are [Roslyn]'s student
What professors advise students who passed their thesis qualifiers?	'Roslyn'	['question_type_global', 'question_two_hop_statement']
[Emma] successfully defended their thesis
What is [Roslyn]'s department?	'asian studies'	['question_type_local']
which students passed the proposal exam?	'Cecil', 'Willis'	['question_type_global', 'question_single_statement']
[Willis] is in [fourth year]
Who is on [Willis]'s committee?	'Alejandra', 'Jack'	['question_type_local']
What are all the courses?	'U102'	['question_type_global', 'question_single_statement']
Who is advised by a professor who is now on a sabbatical?	'Cecil', 'Gia', 'Emma'	['question_type_global', 'question_two_hop_statement']
Which [distinguished] professors advise students who passed their defense?	'Roslyn'	['question_type_global', 'question_three_hop_statement']
[Emma] has failed the thesis proposal exam
Who is [Emma]'s advisor?	'Roslyn'	['question_type_local']
who are the phd students?	'Cecil', 'Willis', 'Gia', 'Emma'	['question_type_global', 'question_single_statement']
which students passed the qualifying exam?	'Willis', 'Emma'	['question_type_global', 'question_single_statement']
[Gia] has passed the thesis proposal exam
Who advises [Gia]?	'Roslyn'	['question_type_local']
Which professors have an [teaching] status?	'Jack'	['question_type_global', 'question_single_statement']
[Alejandra] advises [Willis]
What professors are on [Cecil]'s committee	'Jack'	['question_type_local']
Which professors are part of the [animal science] department?	'Alejandra'	['question_type_global', 'question_two_hop_statement']
[Roslyn] is on [Willis]'s committee
Who advises [he]?	'Alejandra'	['question_type_local']
[he] is now in [fifth year]
Who are the students in the [physics] department	'Bob', 'Tereasa'	['question_type_global', 'question_two_hop_statement']
who are the students?	'Cecil', 'Tawnya', 'Willis', 'Gia', 'Tom', 'Bob', 'Tereasa', 'Emma'	['question_type_global', 'question_single_statement']
Who are the professors working on [computational biology]?	'Alejandra', 'Roslyn'	['question_type_global', 'question_single_statement']
[he] is now in [sixth year]
Who is advised by a professor who is now on a sabbatical?	'Cecil', 'Willis', 'Gia', 'Emma'	['question_type_global', 'question_two_hop_statement']
[Emma] has failed the thesis proposal exam
Who is in the [neuroscience] department	'Tom'	['question_type_global', 'question_single_statement']
[she] is in [fourth year]
Which professors are conducting research in [evolutionary biology]	'Jack'	['question_type_global', 'question_single_statement']
Which professors advise students who passed their defense?	'Alejandra', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
who are the professors?	'Alejandra', 'Jack', 'Roslyn'	['question_type_global', 'question_single_statement']
Which [distinguished] professors advise students who passed their qualifying exam?	'Roslyn'	['question_type_global', 'question_three_hop_statement']
Who are the professors working on [computational biology]?	'Alejandra', 'Roslyn'	['question_type_global', 'question_single_statement']
What [distinguished] professors advise students who passed their thesis qualifiers?	'Roslyn'	['question_type_global', 'question_three_hop_statement']
What professors advise students who passed their thesis qualifiers?	'Alejandra', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
[Cecil] passed thesis defense
Who is [Willis]'s advisor?	'Alejandra'	['question_type_local']
Which students are in their [fourth year]	'Emma'	['question_type_global', 'question_single_statement']
[she] failed thesis proposal
What professors are on [she]'s committee	'Alejandra', 'Jack'	['question_type_local']
who are the masters students?	'Tawnya', 'Tom', 'Bob', 'Tereasa'	['question_type_global', 'question_single_statement']
What is [Alejandra] research area?	'computational biology'	['question_type_local']
Which professors are part of the [asian studies] department?	'Jack', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
There is a [undergraduate] course called [U302]
[Gia] and [Bob] are taking [this course]
What courses is [she] taking?	'U302'	['question_type_local']
which students passed the proposal exam?	'Cecil', 'Willis', 'Gia'	['question_type_global', 'question_single_statement']
[she] passed the qualifiers
[she] failed their thesis defense
[Gia] has [Alejandra] and [Jack] on the committee
Which courses are [undergraduate] level courses?	'U302'	['question_type_global', 'question_single_statement']
Which professors advise students who passed their defense?	'Alejandra', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
Who advises [Emma]?	'Roslyn'	['question_type_local']
Which professors are on sabbatical and are also advising students?	'Alejandra', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
Which phd students does [she] advise?	'Cecil', 'Willis'	['question_type_local']
Create a new [masters] level [mini course] called [G301]
What [associate] professors advise students who passed their thesis proposal?	'Alejandra'	['question_type_global', 'question_three_hop_statement']
Who is advised by a professor who is now on a sabbatical?	'Cecil', 'Willis', 'Gia', 'Emma'	['question_type_global', 'question_two_hop_statement']
What is [Alejandra] working on?	'computational biology'	['question_type_local']
which students passed the defense?	'Cecil', 'Willis', 'Emma'	['question_type_global', 'question_single_statement']
Which are some [undergraduate] courses that phd students take?	'U302'	['question_type_global', 'question_three_hop_statement']
[Willis] is attending [G301]
[G301] is offered in the [asian studies] department
Which courses are [undergraduate] level courses?	'U302'	['question_type_global', 'question_single_statement']
Which [associate] professors advise students who passed their qualifying exam?	'Alejandra'	['question_type_global', 'question_three_hop_statement']
Who is on [Gia]'s committee?	'Alejandra', 'Jack'	['question_type_local']
what [masters] courses have phd students taking them?	'G301'	['question_type_global', 'question_three_hop_statement']
[Alejandra] teaches [that class]
[Emma] and [Tereasa] are both taking [this course]
Which courses did [Tereasa] enroll in?	'G301'	['question_type_local']
For which phd students does [Roslyn] serve on a committee?	'Willis'	['question_type_local']
[Emma] has passed the thesis proposal exam
Who advises [Cecil]?	'Alejandra'	['question_type_local']
who are the students?	'Cecil', 'Tawnya', 'Willis', 'Gia', 'Tom', 'Bob', 'Tereasa', 'Emma'	['question_type_global', 'question_single_statement']
Which people are in the [asian studies] department?	'Jack', 'Roslyn'	['question_type_global', 'question_single_statement']
Which masters students taking the G301 course	'Tereasa'	['question_type_global', 'question_two_hop_statement']
Which professors are currently on sabbatical?	'Alejandra', 'Jack', 'Roslyn'	['question_type_global', 'question_single_statement']
Which courses are in the [asian studies] department?	'G301'	['question_type_global', 'question_single_statement']
What students are taking G301	'Willis', 'Tereasa', 'Emma'	['question_type_global', 'question_single_statement']
[Cecil] has passed the qualifying exam
which students passed the defense?	'Cecil', 'Willis', 'Emma'	['question_type_global', 'question_single_statement']
Which department is [G301] part of?	'asian studies'	['question_type_local']
What students are taking a course taught by their advisor?	'Willis'	['question_type_global', 'question_three_hop_statement']
which [masters] courses have some phd students enrolled?	'G301'	['question_type_global', 'question_three_hop_statement']
What courses is [she] taking?	'G301'	['question_type_local']
Which people are in the [asian studies] department?	'Jack', 'Roslyn'	['question_type_global', 'question_single_statement']
Create a new [phd] course called [G302]
Which professors are teaching [mini course]?	'Alejandra'	['question_type_global', 'question_two_hop_statement']
[Roslyn] is on [Cecil]'s committee
Which are some courses that phd students take?	'U302', 'G301'	['question_type_global', 'question_two_hop_statement']
What students are in the [neuroscience] department?	'Tom'	['question_type_global', 'question_two_hop_statement']
There is a course called [U104]
What students are taking a course taught by their advisor?	'Willis'	['question_type_global', 'question_three_hop_statement']
Which professors are conducting research in [evolutionary biology]	'Jack'	['question_type_global', 'question_single_statement']
Which [distinguished] professors advise students who passed their proposal?	'Roslyn'	['question_type_global', 'question_three_hop_statement']
[Jack] is the instructor for [this course]
[physics] offers [that class]
[U104] is a [phd] level course
What department is [U104] offered in?	'physics'	['question_type_local']
who are the phd students?	'Cecil', 'Willis', 'Gia', 'Emma'	['question_type_global', 'question_single_statement']
Which professors are on sabbatical and are also advising students?	'Alejandra', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
Who are the professors in the [animal science] department?	'Alejandra'	['question_type_global', 'question_two_hop_statement']
[this course] will be a full semester course
what courses have masters students taking them?	'U302', 'G301'	['question_type_global', 'question_two_hop_statement']
What professors that currently advise students are going on sabbatical?	'Alejandra', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
Which professors advise students who passed their defense?	'Alejandra', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
which students passed the proposal exam?	'Cecil', 'Willis', 'Gia', 'Emma'	['question_type_global', 'question_single_statement']
Who is on sabbatical this semester?	'Alejandra', 'Jack', 'Roslyn'	['question_type_global', 'question_single_statement']
[Emma] and [Cecil] are TAing [that class]
Who is teaching [U104]?	'Jack'	['question_type_local']
What students currently have their advisor on sabbatical	'Cecil', 'Willis', 'Gia', 'Emma'	['question_type_global', 'question_two_hop_statement']
Which courses are TAed by [she]?	'U104'	['question_type_local']
What courses are taught by those in the [animal science] department?	'G301'	['question_type_global', 'question_two_hop_statement']
Which professors have an [associate] status?	'Alejandra'	['question_type_global', 'question_single_statement']
Which professors are teaching [masters] courses?	'Alejandra'	['question_type_global', 'question_two_hop_statement']
What students are taking courses and TAing?	'Emma'	['question_type_global', 'question_two_hop_statement']
[Roslyn] is the instructor for [U302]
[that class] will be set up as a mini course
[that course] is under the [asian studies] department
What courses is [Bob] taking?	'U302'	['question_type_local']
who are the professors?	'Alejandra', 'Jack', 'Roslyn'	['question_type_global', 'question_single_statement']
Which courses are TAed by phd students that passed their qualifier exam?	'U104'	['question_type_global', 'question_three_hop_statement']
Who are the students in the [physics] department	'Bob', 'Tereasa'	['question_type_global', 'question_two_hop_statement']
Which courses are offered this semester?	'U102', 'U302', 'G301', 'G302', 'U104'	['question_type_global', 'question_single_statement']
[Tereasa] is enrolled in [that course]
Create a new [phd] [mini course] called [G601]
[Tawnya] is a student in [this course]
[G601] is a course in the [animal science] department
Which courses are part of the [animal science] department	'G601'	['question_type_global', 'question_single_statement']
What [distinguished] professors advise students who defended successfully?	'Roslyn'	['question_type_global', 'question_three_hop_statement']
[Cecil] is a student in [that course]
Which courses are offered this semester in the asian studies department?	'U302', 'G301'	['question_type_global', 'question_two_hop_statement']
who are the professors?	'Alejandra', 'Jack', 'Roslyn'	['question_type_global', 'question_single_statement']
Create a new course called [G104]
[that class] is a mini course
[this course] is under the [physics] department
[that class] is a [masters] level course
Which students are taking [U302]?	'Gia', 'Bob', 'Tereasa'	['question_type_local']
What are the [fourth year] phd students	'Emma'	['question_type_global', 'question_single_statement']
Which [fourth year] students are advised by professors working on [computational biology]?	'Emma'	['question_type_global', 'question_three_hop_statement']
Which [distinguished] professors advise students who passed their proposal?	'Roslyn'	['question_type_global', 'question_three_hop_statement']
Which courses are TAed by phd students?	'U104'	['question_type_global', 'question_two_hop_statement']
which students passed the defense?	'Cecil', 'Willis', 'Emma'	['question_type_global', 'question_single_statement']
Who is [Emma]'s advisor?	'Roslyn'	['question_type_local']
who are the professors?	'Alejandra', 'Jack', 'Roslyn'	['question_type_global', 'question_single_statement']
Which students are part of the [physics] department	'Bob', 'Tereasa'	['question_type_global', 'question_two_hop_statement']
who are the students?	'Cecil', 'Tawnya', 'Willis', 'Gia', 'Tom', 'Bob', 'Tereasa', 'Emma'	['question_type_global', 'question_single_statement']
Which courses have phd student TAs that passed the qualifying exam?	'U104'	['question_type_global', 'question_three_hop_statement']
What courses is [Alejandra] teaching?	'G301'	['question_type_local']
Who is teaching [undergraduate] courses?	'Roslyn'	['question_type_global', 'question_two_hop_statement']
Which professors advise students who passed their proposal?	'Alejandra', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
Who is [Willis]'s advisor?	'Alejandra'	['question_type_local']
which students passed the defense?	'Cecil', 'Willis', 'Emma'	['question_type_global', 'question_single_statement']
Which people are in the [asian studies] department?	'Jack', 'Roslyn'	['question_type_global', 'question_single_statement']
Which students are advised by professors working on [computational biology]?	'Cecil', 'Willis', 'Gia', 'Emma'	['question_type_global', 'question_two_hop_statement']
Which courses are [undergraduate] level courses?	'U302'	['question_type_global', 'question_single_statement']
Which phd students does [Roslyn] advise?	'Gia', 'Emma'	['question_type_local']
who are the phd students?	'Cecil', 'Willis', 'Gia', 'Emma'	['question_type_global', 'question_single_statement']
Who are the professors working on [computational biology]?	'Alejandra', 'Roslyn'	['question_type_global', 'question_single_statement']
which students passed the defense?	'Cecil', 'Willis', 'Emma'	['question_type_global', 'question_single_statement']
which students passed the qualifying exam?	'Cecil', 'Willis', 'Gia', 'Emma'	['question_type_global', 'question_single_statement']
[Bob] is TAing [that course]
Which professors advise students who passed their defense?	'Alejandra', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
Which courses are TAed by masters students?	'G104'	['question_type_global', 'question_two_hop_statement']
What are the courses TAed by [this person]?	'G104'	['question_type_local']
Which students are in a course that is instructed by their advisor?	'Willis', 'Gia'	['question_type_global', 'question_three_hop_statement']
Which courses are offered this semester?	'U102', 'U302', 'G301', 'G302', 'U104', 'G601', 'G104'	['question_type_global', 'question_single_statement']
What is [Roslyn]'s department?	'asian studies'	['question_type_local']
Which professors are on sabbatical and are also advising students?	'Alejandra', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
Which courses have phd student TAs that passed the qualifying exam?	'U104'	['question_type_global', 'question_three_hop_statement']
What are the courses that [Tereasa] is enrolled in?	'U302', 'G301'	['question_type_local']
Who is supposed to be teaching [mini course] and is currently on sabbatical?	'Alejandra', 'Roslyn'	['question_type_global', 'question_three_hop_statement']
What are all the courses in the physics department?	'U104', 'G104'	['question_type_global', 'question_two_hop_statement']
What professors advise students who defended successfully?	'Alejandra', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
Create a new [masters] level course called [U8001]
which students passed the proposal exam?	'Cecil', 'Willis', 'Gia', 'Emma'	['question_type_global', 'question_single_statement']
what courses have phd students taking them?	'U302', 'G301', 'G601'	['question_type_global', 'question_two_hop_statement']
Which courses have phd student TAs that either have some funding or passed the qualifying exam?	'U104'	['question_type_global', 'question_four_hop_statement']
Which are some [phd] courses that no phd student is taking?	'G302', 'U104'	['question_type_global', 'question_three_hop_statement']
Create a new course called [G304]
[G304] is offered in the [asian studies] department
[that course] is a full semester course
Who is enrolled in [G301]?	'Willis', 'Tereasa', 'Emma'	['question_type_local']
Who is on sabbatical?	'Alejandra', 'Jack', 'Roslyn'	['question_type_global', 'question_single_statement']
What 8 unit courses are taught by professors in the [asian studies] department?	'U302', 'U104'	['question_type_global', 'question_three_hop_statement']
[Tereasa] and [Tawnya] are TAs for [G304]
What department is [G304] offered in?	'asian studies'	['question_type_local']
which students passed the proposal exam?	'Cecil', 'Willis', 'Gia', 'Emma'	['question_type_global', 'question_single_statement']
Which courses are TAed by phd students that passed their qualifier exam?	'U104'	['question_type_global', 'question_three_hop_statement']
Who is advised by a professor who is now on a sabbatical?	'Cecil', 'Willis', 'Gia', 'Emma'	['question_type_global', 'question_two_hop_statement']
Which courses are TAed by [Cecil]?	'U104'	['question_type_local']
Which professors have an [teaching] status?	'Jack'	['question_type_global', 'question_single_statement']
Which phd courses are TAed by phd students?	'U104'	['question_type_global', 'question_three_hop_statement']
Who are the professors in the [animal science] department?	'Alejandra'	['question_type_global', 'question_two_hop_statement']
Which courses have phd student TAs?	'U104'	['question_type_global', 'question_two_hop_statement']
[Tawnya]'s department is [neuroscience]
Which courses are TAed by [Tawnya]?	'G304'	['question_type_local']
Which are some courses that no masters student is taking?	'U102', 'G302', 'U104', 'G104', 'U8001', 'G304'	['question_type_global', 'question_two_hop_statement']
Who is supposed to be teaching [full_semester_course] and is currently on sabbatical?	'Jack'	['question_type_global', 'question_three_hop_statement']
Which courses are TAed by phd students that passed their qualifier exam?	'U104'	['question_type_global', 'question_three_hop_statement']
What professors that currently advise students are going on sabbatical?	'Alejandra', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
What are the courses that [this student] is enrolled in?	'G601'	['question_type_local']
Which are some courses that phd students take?	'U302', 'G301', 'G601'	['question_type_global', 'question_two_hop_statement']
Which professors are teaching [phd] courses?	'Jack'	['question_type_global', 'question_two_hop_statement']
Who is supposed to be teaching [phd] courses but is currently on sabbatical?	'Jack'	['question_type_global', 'question_three_hop_statement']
What [associate] professors advise students who passed their thesis proposal?	'Alejandra'	['question_type_global', 'question_three_hop_statement']
Who is advised by a professor who is now on a sabbatical?	'Cecil', 'Willis', 'Gia', 'Emma'	['question_type_global', 'question_two_hop_statement']
Which professors are currently on sabbatical?	'Alejandra', 'Jack', 'Roslyn'	['question_type_global', 'question_single_statement']
Which courses have masters student TAs?	'G104', 'G304'	['question_type_global', 'question_two_hop_statement']
[U102] is a course in the [neuroscience] department
Which are some [phd] courses that no phd student is taking?	'G302', 'U104'	['question_type_global', 'question_three_hop_statement']
What students are taking a course taught by their advisor?	'Willis', 'Gia'	['question_type_global', 'question_three_hop_statement']
Which courses have phd student TAs?	'U104'	['question_type_global', 'question_two_hop_statement']
who are the phd students?	'Cecil', 'Willis', 'Gia', 'Emma'	['question_type_global', 'question_single_statement']
What are the courses TAed by [Tawnya]?	'G304'	['question_type_local']
What students currently have their advisor on sabbatical	'Cecil', 'Willis', 'Gia', 'Emma'	['question_type_global', 'question_two_hop_statement']
Which people are in the [animal science] department?	'Alejandra'	['question_type_global', 'question_single_statement']
Which are some [undergraduate] courses that masters students take?	'U302'	['question_type_global', 'question_three_hop_statement']
What courses is [Tawnya] taking?	'G601'	['question_type_local']
Who is on sabbatical?	'Alejandra', 'Jack', 'Roslyn'	['question_type_global', 'question_single_statement']
What professors that currently advise students are going on sabbatical?	'Alejandra', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
Which phd students are both taking a course and a TA?	'Cecil', 'Emma'	['question_type_global', 'question_three_hop_statement']
[Willis] and [Emma] are attending [U102]
What department is [U102] offered in?	'neuroscience'	['question_type_local']
who are the professors?	'Alejandra', 'Jack', 'Roslyn'	['question_type_global', 'question_single_statement']
Who are the [sixth year] students?	'Cecil', 'Willis', 'Gia'	['question_type_global', 'question_single_statement']
What 8 unit courses are taught by those in the [animal science] department?	'G301'	['question_type_global', 'question_three_hop_statement']
Who advises [Gia]?	'Roslyn'	['question_type_local']
which [phd] courses have some phd students enrolled?	'G601'	['question_type_global', 'question_three_hop_statement']
What [distinguished] professors advise students who defended successfully?	'Roslyn'	['question_type_global', 'question_three_hop_statement']
What students are taking courses and TAing?	'Cecil', 'Tawnya', 'Bob', 'Tereasa', 'Emma'	['question_type_global', 'question_two_hop_statement']
Who are [Alejandra]'s students?	'Cecil', 'Willis'	['question_type_local']
Which courses are offered this semester in the asian studies department?	'U302', 'G301', 'G304'	['question_type_global', 'question_two_hop_statement']
[Gia] passed thesis defense
Who is on [Gia]'s committee?	'Alejandra', 'Jack'	['question_type_local']
Which students's advisors are conducting research in [computational biology]	'Cecil', 'Willis', 'Gia', 'Emma'	['question_type_global', 'question_two_hop_statement']
[Willis] and [Gia] are TAs for [G301]
Which [sixth year] students's advisors are conducting research in [computational biology]	'Cecil', 'Willis', 'Gia'	['question_type_global', 'question_three_hop_statement']
Which phd students are both taking a course and a TA?	'Cecil', 'Willis', 'Gia', 'Emma'	['question_type_global', 'question_three_hop_statement']
Which department is [U102] in?	'neuroscience'	['question_type_local']
Which students TA a course that is instructed by their advisor?	'Willis'	['question_type_global', 'question_three_hop_statement']
which students passed the qualifying exam?	'Cecil', 'Willis', 'Gia', 'Emma'	['question_type_global', 'question_single_statement']
What courses is [Roslyn] teaching?	'U302'	['question_type_local']
Which phd students taking the G301 course	'Willis', 'Emma'	['question_type_global', 'question_two_hop_statement']
Which courses are offered this semester in the animal science department?	'G601'	['question_type_global', 'question_two_hop_statement']
[Tom] is a TA for [U104]
What 12 unit courses are taught by professors in the [asian studies] department?	'U302', 'U104'	['question_type_global', 'question_three_hop_statement']
Which students are advised by professors working on [computational biology]?	'Cecil', 'Willis', 'Gia', 'Emma'	['question_type_global', 'question_two_hop_statement']
who are the masters students?	'Tawnya', 'Tom', 'Bob', 'Tereasa'	['question_type_global', 'question_single_statement']
Who is in the [physics] department	'Bob', 'Tereasa'	['question_type_global', 'question_single_statement']
What are the [animal science] courses?	'G601'	['question_type_global', 'question_single_statement']
Which [sixth year] students's advisors are conducting research in [computational biology]	'Cecil', 'Willis', 'Gia'	['question_type_global', 'question_three_hop_statement']
What [full_semester_course] are taught by professors in the [asian studies] department?	'U302', 'U104'	['question_type_global', 'question_three_hop_statement']
Who is teaching [U302]?	'Roslyn'	['question_type_local']
Who is advised by a professor who is now on a sabbatical?	'Cecil', 'Willis', 'Gia', 'Emma'	['question_type_global', 'question_two_hop_statement']
which courses have no masters students enrolled?	'U102', 'G302', 'U104', 'G104', 'U8001', 'G304'	['question_type_global', 'question_two_hop_statement']
Which are some courses that no phd student is taking?	'G302', 'U104', 'G104', 'U8001', 'G304'	['question_type_global', 'question_two_hop_statement']
who are the professors?	'Alejandra', 'Jack', 'Roslyn'	['question_type_global', 'question_single_statement']
Which courses did [Bob] enroll in?	'U302'	['question_type_local']
What students are TAing a course taught by their advisor?	'Willis'	['question_type_global', 'question_three_hop_statement']
which students passed the proposal exam?	'Cecil', 'Willis', 'Gia', 'Emma'	['question_type_global', 'question_single_statement']
Who is part of the [neuroscience] department	'Tawnya', 'Tom'	['question_type_global', 'question_single_statement']
Which department is [that class] part of?	'physics'	['question_type_local']
Which courses are TAed by phd students?	'G301', 'U104'	['question_type_global', 'question_two_hop_statement']
[Gia] and [Emma] are attending [that class]
Which [distinguished] professors advise students who passed their qualifying exam?	'Roslyn'	['question_type_global', 'question_three_hop_statement']
Which professors that are currently on sabbatical need to be teaching [full_semester_course]?	'Jack'	['question_type_global', 'question_three_hop_statement']
Who is on [Gia]'s committee?	'Alejandra', 'Jack'	['question_type_local']
Who is supposed to be teaching [masters] courses but is currently on sabbatical?	'Alejandra'	['question_type_global', 'question_three_hop_statement']
Who is teaching [U104]?	'Jack'	['question_type_local']
Who is supposed to be teaching [mini course] and is currently on sabbatical?	'Alejandra', 'Roslyn'	['question_type_global', 'question_three_hop_statement']
What are the courses that [Emma] is enrolled in?	'U102', 'G301', 'U104'	['question_type_local']
which courses have some masters students enrolled?	'U302', 'G301', 'G601'	['question_type_global', 'question_two_hop_statement']
who are the masters students?	'Tawnya', 'Tom', 'Bob', 'Tereasa'	['question_type_global', 'question_single_statement']
Which are some [masters] courses that no phd student is taking?	'G104', 'U8001'	['question_type_global', 'question_three_hop_statement']
What students currently have their advisor on sabbatical	'Cecil', 'Willis', 'Gia', 'Emma'	['question_type_global', 'question_two_hop_statement']
What courses is [Tereasa] TAing?	'G304'	['question_type_local']
what courses have no phd students taking them?	'G302', 'G104', 'U8001', 'G304'	['question_type_global', 'question_two_hop_statement']
Which courses have phd student TAs?	'G301', 'U104'	['question_type_global', 'question_two_hop_statement']
Create a new course called [U610]
What are the courses TAed by [she]?	'U104'	['question_type_local']
Which professors currently on sabbatical are supposed to be teaching [undergraduate] courses?	'Roslyn'	['question_type_global', 'question_three_hop_statement']
Which professors have an [teaching] status?	'Jack'	['question_type_global', 'question_single_statement']
What professors advise students who passed their thesis qualifiers?	'Alejandra', 'Roslyn'	['question_type_global', 'question_two_hop_statement']
Which courses are TAed by [this person]?	'U104'	['question_type_local']
Which courses have masters student TAs?	'U104', 'G104', 'G304'	['question_type_global', 'question_two_hop_statement']
Who is part of the [asian studies] department	'Jack', 'Roslyn'	['question_type_global', 'question_single_statement']
Which phd students are both taking a course and a TA?	'Cecil', 'Willis', 'Gia', 'Emma'	['question_type_global', 'question_three_hop_statement']
Who are the [sixth year] students?	'Cecil', 'Willis', 'Gia'	['question_type_global', 'question_single_statement']
Which courses have phd student TAs that either have some funding or passed the qualifying exam?	'G301', 'U104'	['question_type_global', 'question_four_hop_statement']
Create a new course called [U9000]
[Tawnya] is attending [U610]
[that class] is full semester
Who are the professors in the [animal science] department?	'Alejandra'	['question_type_global', 'question_two_hop_statement']
Which courses have phd student TAs?	'G301', 'U104'	['question_type_global', 'question_two_hop_statement']
[Emma] and [Willis] are taking [U610]
[animal science] offers [U610]
who are the masters students?	'Tawnya', 'Tom', 'Bob', 'Tereasa'	['question_type_global', 'question_single_statement']
What professors are in the [animal science] department?	'Alejandra'	['question_type_global', 'question_two_hop_statement']
Which phd students are both taking a course and a TA?	'Cecil', 'Willis', 'Gia', 'Emma'	['question_type_global', 'question_three_hop_statement']
