Create a new [undergraduate] level 12 unit course called [U610]
[that course] is a course in the [electrical engineering] department
What department is [that class] offered in?	'electrical engineering'	['question_type_local']
[this course] is set up as a mini course
Which department is [U610] part of?	'electrical engineering'	['question_type_local']
[that class] is a pass-fail course
What are all the courses in the electrical engineering department?	'U610'	['question_type_global', 'question_two_hop_statement']
Create a new [undergraduate] level 12 unit course called [U101]
[Bob] is a masters student
the affiliation of [this person] is [history]
there is a new masters student named [Hanna]
Create a new course called [U303]
[she] is taking [this course]
[U303] is a full semester course
[that class] part of the [biomedical engineering] department
[second year] is a [Ashly] PhD student
[that student] passed thesis proposal
create a [professor] named [Lucio]
who are the masters students?	'Bob', 'Hanna'	['question_type_global', 'question_single_statement']
Which courses are 12 unit courses?	'U610', 'U101'	['question_type_global', 'question_single_statement']
create a [teaching] [professor] named [Britney]
[she] is on sabbatical
which students passed the proposal exam?	'Ashly'	['question_type_global', 'question_single_statement']
[Britney] is affiliated with the [biomedical engineering] department
[Ashly] is a student in [U610]
The TA for [U610] is [Hanna]
Which department is [this course] in?	'electrical engineering'	['question_type_local']
there is a new masters student named [Yoshiko]
the affiliation of [Yoshiko] is [english]
What department is [U610] offered in?	'electrical engineering'	['question_type_local']
Who is on sabbatical this semester?	'Britney'	['question_type_global', 'question_single_statement']
Who are the [teaching] professors?	'Britney'	['question_type_global', 'question_single_statement']
which [undergraduate] courses have no masters students enrolled?	'U610', 'U101'	['question_type_global', 'question_three_hop_statement']
Which courses are offered this semester?	'U610', 'U101', 'U303'	['question_type_global', 'question_single_statement']
[Lucy] is a [professor]
There is a course called [G201]
[this person] is on sabbatical
[she] research interest is in [applications of machine learning]
What are the courses TAed by [Hanna]?	'U610'	['question_type_local']
which [undergraduate] courses have no phd students enrolled?	'U101'	['question_type_global', 'question_three_hop_statement']
Create a new course called [U601]
[this course] is taught by [that professor]
[U601] is a [phd] level course
[U601] is under the [history] department
What are all the courses in the electrical engineering department?	'U610'	['question_type_global', 'question_two_hop_statement']
there is a new masters student named [Alejandra]
[that person] is affiliated with the [electrical engineering] department
[U303] is a pass-fail course
[that class] is 4 units
Who is taking [that course]?	'Hanna'	['question_type_local']
what [undergraduate] courses have phd students taking them?	'U610'	['question_type_global', 'question_three_hop_statement']
what courses have phd students taking them?	'U610'	['question_type_global', 'question_two_hop_statement']
who are the students?	'Bob', 'Hanna', 'Ashly', 'Yoshiko', 'Alejandra'	['question_type_global', 'question_single_statement']
there is a [teaching] [professor] named [Luanna]
[she] conducts research in [reinforcement learning]
the affiliation of [this person] is [english]
create a [distinguished] [professor] named [Marisela]
Which courses are offered this semester?	'U610', 'U101', 'U303', 'G201', 'U601'	['question_type_global', 'question_single_statement']
which students passed the proposal exam?	'Ashly'	['question_type_global', 'question_single_statement']
there is a [professor] named [Igor]
[she] research interest is in [reinforcement learning]
What are the [history] courses?	'U601'	['question_type_global', 'question_single_statement']
[John] is a masters student
[that professor] advises [Ashly]
Which students are both taking a course and a TA?	'Hanna'	['question_type_global', 'question_two_hop_statement']
What professors are in the [english] department?	'Luanna'	['question_type_global', 'question_two_hop_statement']
Who is part of the [history] department	'Bob'	['question_type_global', 'question_single_statement']
What professors advise students who passed their thesis proposal?	'Marisela'	['question_type_global', 'question_two_hop_statement']
there is a new [fifth year] PhD student named [Racquel]
there is a new PhD student named [Tom]
[he] passed thesis defense
What students are in the [electrical engineering] department?	'Alejandra'	['question_type_global', 'question_two_hop_statement']
[John]'s department is [history]
What are all the courses in the biomedical engineering department?	'U303'	['question_type_global', 'question_two_hop_statement']
which students passed the defense?	'Tom'	['question_type_global', 'question_single_statement']
there is a new masters student named [Jack]
What are the [mini course]?	'U610'	['question_type_global', 'question_single_statement']
Which courses have masters student TAs?	'U610'	['question_type_global', 'question_two_hop_statement']
[Jack]'s department is [biomedical engineering]
which students passed the proposal exam?	'Ashly'	['question_type_global', 'question_single_statement']
which [phd] courses have no masters students enrolled?	'U601'	['question_type_global', 'question_three_hop_statement']
What are the 4 unit courses?	'U303'	['question_type_global', 'question_single_statement']
Which are some courses that no phd student is taking?	'U101', 'U303', 'G201', 'U601'	['question_type_global', 'question_two_hop_statement']
[Britney] is the instructor for [U610]
Which professors advise students who passed their proposal?	'Marisela'	['question_type_global', 'question_two_hop_statement']
[John] and [Alejandra] are TAing [U610]
What [distinguished] professors advise students who passed their thesis proposal?	'Marisela'	['question_type_global', 'question_three_hop_statement']
Who is supposed to be teaching [phd] courses but is currently on sabbatical?	'Lucy'	['question_type_global', 'question_three_hop_statement']
which [undergraduate] courses have no masters students enrolled?	'U610', 'U101'	['question_type_global', 'question_three_hop_statement']
What courses is [he] TAing?	'U610'	['question_type_local']
which courses have no phd students enrolled?	'U101', 'U303', 'G201', 'U601'	['question_type_global', 'question_two_hop_statement']
What professors are in the [english] department?	'Luanna'	['question_type_global', 'question_two_hop_statement']
who are the masters students?	'Bob', 'Hanna', 'Yoshiko', 'Alejandra', 'John', 'Jack'	['question_type_global', 'question_single_statement']
which students passed the proposal exam?	'Ashly'	['question_type_global', 'question_single_statement']
What courses is [John] TAing?	'U610'	['question_type_local']
Which courses are part of the [electrical engineering] department	'U610'	['question_type_global', 'question_single_statement']
Which courses have masters student TAs?	'U610'	['question_type_global', 'question_two_hop_statement']
Which professors are conducting research in [applications of machine learning]	'Lucy'	['question_type_global', 'question_single_statement']
What 4 unit courses are taught by professors in the [biomedical engineering] department?	'U610'	['question_type_global', 'question_three_hop_statement']
which courses have no masters students enrolled?	'U610', 'U101', 'G201', 'U601'	['question_type_global', 'question_two_hop_statement']
who are the phd students?	'Ashly', 'Racquel', 'Tom'	['question_type_global', 'question_single_statement']
[Lucy] is an [associate] professor
What courses is [that professor] teaching?	'U601'	['question_type_local']
[Ashly] successfully defended their thesis
[Ashly] has passed the qualifying exam
which students passed the defense?	'Ashly', 'Tom'	['question_type_global', 'question_single_statement']
What [distinguished] professors advise students who passed their thesis proposal?	'Marisela'	['question_type_global', 'question_three_hop_statement']
Which people are in the [biomedical engineering] department?	'Britney', 'Jack'	['question_type_global', 'question_single_statement']
[Hanna] is affiliated with the [electrical engineering] department
Which courses did [Hanna] enroll in?	'U303'	['question_type_local']
What professors are in the [biomedical engineering] department?	'Britney'	['question_type_global', 'question_two_hop_statement']
What students are taking courses and TAing?	'Hanna'	['question_type_global', 'question_two_hop_statement']
What are the 12 unit courses?	'U610', 'U101'	['question_type_global', 'question_single_statement']
Which courses are offered this semester?	'U610', 'U101', 'U303', 'G201', 'U601'	['question_type_global', 'question_single_statement']
[Ashly] has [Lucy] and [Igor] on the committee
Who is [Ashly]'s advisor?	'Marisela'	['question_type_local']
Which professors are part of the [biomedical engineering] department?	'Britney'	['question_type_global', 'question_two_hop_statement']
Which professors advise students who passed their defense?	'Marisela'	['question_type_global', 'question_two_hop_statement']
[Tom] and [Racquel] are [he]'s student
the affiliation of [Igor] is [electrical engineering]
What department is [Igor] affiliated with?	'electrical engineering'	['question_type_local']
[Marisela] is on sabbatical
Which are some [undergraduate] courses that no phd student is taking?	'U101'	['question_type_global', 'question_three_hop_statement']
who are the students?	'Bob', 'Hanna', 'Ashly', 'Yoshiko', 'Alejandra', 'John', 'Racquel', 'Tom', 'Jack'	['question_type_global', 'question_single_statement']
[Igor] research interest is in [reinforcement learning]
Who has [he] on their phd committee?	'Ashly'	['question_type_local']
Which are some [undergraduate] courses that no masters student is taking?	'U610', 'U101'	['question_type_global', 'question_three_hop_statement']
what courses have no phd students taking them?	'U101', 'U303', 'G201', 'U601'	['question_type_global', 'question_two_hop_statement']
Create a new [phd] level 4 unit course called [G204]
[Jack] is TAing [this course]
What students are going to TA [that course]?	'Jack'	['question_type_local']
Which professors are currently on sabbatical?	'Britney', 'Lucy', 'Marisela'	['question_type_global', 'question_single_statement']
[Racquel] is taking [U610]
Which students are TAing [this course]?	'Hanna', 'Alejandra', 'John'	['question_type_local']
Which [distinguished] professors advise students who passed their qualifying exam?	'Marisela'	['question_type_global', 'question_three_hop_statement']
Which professors are part of the [english] department?	'Luanna'	['question_type_global', 'question_two_hop_statement']
Who is [Tom]'s advisor?	'Igor'	['question_type_local']
Which professors have an [associate] status?	'Lucy'	['question_type_global', 'question_single_statement']
what [undergraduate] courses have phd students taking them?	'U610'	['question_type_global', 'question_three_hop_statement']
Which professors are part of the [biomedical engineering] department?	'Britney'	['question_type_global', 'question_two_hop_statement']
[this student] has failed the thesis proposal exam
[Lucy] is on [Racquel]'s committee
Create a new [masters] level [mini course] called [G301]
[that class] is 12 units
[G301] is a pass-fail course
Who are the [teaching] professors?	'Britney', 'Luanna'	['question_type_global', 'question_single_statement']
which students passed the defense?	'Ashly', 'Tom'	['question_type_global', 'question_single_statement']
Which courses are 4 unit courses?	'U303', 'G204'	['question_type_global', 'question_single_statement']
Which are some [phd] courses that no masters student is taking?	'U601', 'G204'	['question_type_global', 'question_three_hop_statement']
[Ashly] has [Britney] on the committee
Which professors are teaching [mini course]?	'Britney'	['question_type_global', 'question_two_hop_statement']
What professors that currently advise students are going on sabbatical?	'Marisela'	['question_type_global', 'question_two_hop_statement']
which courses have no phd students enrolled?	'U101', 'U303', 'G201', 'U601', 'G204', 'G301'	['question_type_global', 'question_two_hop_statement']
[Luanna] currently has funding
What professors advise students who defended successfully?	'Marisela', 'Igor'	['question_type_global', 'question_two_hop_statement']
What are all the courses?	'U610', 'U101', 'U303', 'G201', 'U601', 'G204', 'G301'	['question_type_global', 'question_single_statement']
What are the [masters] courses?	'G301'	['question_type_global', 'question_single_statement']
what courses have masters students taking them?	'U303'	['question_type_global', 'question_two_hop_statement']
Which courses are part of the [biomedical engineering] department	'U303'	['question_type_global', 'question_single_statement']
What are the [full_semester_course]?	'U303'	['question_type_global', 'question_single_statement']
What is [Lucy]'s research focus?	'applications of machine learning'	['question_type_local']
[Luanna] is now on sabbatical
What is [Luanna] working on?	'reinforcement learning'	['question_type_local']
Which professors advise students who passed their defense?	'Marisela', 'Igor'	['question_type_global', 'question_two_hop_statement']
Which people are in the [history] department?	'Bob', 'John'	['question_type_global', 'question_single_statement']
What is [Luanna] research area?	'reinforcement learning'	['question_type_local']
which students passed the proposal exam?	'Ashly'	['question_type_global', 'question_single_statement']
Who is taking the U610 course	'Ashly', 'Racquel'	['question_type_global', 'question_single_statement']
Who is enrolled in [U610]?	'Ashly', 'Racquel'	['question_type_local']
Who is in the [electrical engineering] department	'Hanna', 'Alejandra', 'Igor'	['question_type_global', 'question_single_statement']
Who are the [associate] professors?	'Lucy'	['question_type_global', 'question_single_statement']
Which phd students taking the U610 course	'Ashly', 'Racquel'	['question_type_global', 'question_two_hop_statement']
What [distinguished] professors advise students who defended successfully?	'Marisela'	['question_type_global', 'question_three_hop_statement']
What are all the courses in the biomedical engineering department?	'U303'	['question_type_global', 'question_two_hop_statement']
Who are the students in the [biomedical engineering] department	'Jack'	['question_type_global', 'question_two_hop_statement']
Which masters students taking the U303 course	'Hanna'	['question_type_global', 'question_two_hop_statement']
What is [she] working on?	'reinforcement learning'	['question_type_local']
Which students are both taking a course and a TA?	'Hanna'	['question_type_global', 'question_two_hop_statement']
What is [this professor]'s research focus?	'reinforcement learning'	['question_type_local']
Which professors advise students who passed their proposal?	'Marisela'	['question_type_global', 'question_two_hop_statement']
Which professors are part of the [english] department?	'Luanna'	['question_type_global', 'question_two_hop_statement']
There is a course called [G202]
What is [Luanna] working on?	'reinforcement learning'	['question_type_local']
Which professors are conducting research in [reinforcement learning]	'Luanna', 'Marisela', 'Igor'	['question_type_global', 'question_single_statement']
Which courses are [phd] level courses?	'U601', 'G204'	['question_type_global', 'question_single_statement']
which students passed the proposal exam?	'Ashly'	['question_type_global', 'question_single_statement']
Which courses have masters student TAs?	'U610', 'G204'	['question_type_global', 'question_two_hop_statement']
What courses are taught by professors in the [biomedical engineering] department?	'U610'	['question_type_global', 'question_two_hop_statement']
[John] and [Hanna] are taking [G202]
[G202] is taught by [Marisela]
[that class] part of the [electrical engineering] department
What courses is [Britney] teaching?	'U610'	['question_type_local']
Who is teaching [mini course]?	'Britney'	['question_type_global', 'question_two_hop_statement']
What students are taking courses and TAing?	'Hanna', 'John'	['question_type_global', 'question_two_hop_statement']
What courses is [John] taking?	'G202'	['question_type_local']
which courses have some phd students enrolled?	'U610'	['question_type_global', 'question_two_hop_statement']
[Ashly] is now in [third year]
What professors advise students who passed their thesis qualifiers?	'Marisela'	['question_type_global', 'question_two_hop_statement']
Who advises [that person]?	'Marisela'	['question_type_local']
who are the phd students?	'Ashly', 'Racquel', 'Tom'	['question_type_global', 'question_single_statement']
What courses is [that person] taking?	'U610'	['question_type_local']
What 12 unit courses are taught by those in the [biomedical engineering] department?	'U610'	['question_type_global', 'question_three_hop_statement']
Which professors are currently on sabbatical?	'Britney', 'Lucy', 'Luanna', 'Marisela'	['question_type_global', 'question_single_statement']
Which are some courses that masters students take?	'U303', 'G202'	['question_type_global', 'question_two_hop_statement']
[Luanna] and [Lucio] are on [Ashly]'s committee
Who is on sabbatical?	'Britney', 'Lucy', 'Luanna', 'Marisela'	['question_type_global', 'question_single_statement']
[he]'s department is [english]
Who has [this professor] on their phd committee?	'Ashly'	['question_type_local']
who are the professors?	'Lucio', 'Britney', 'Lucy', 'Luanna', 'Marisela', 'Igor'	['question_type_global', 'question_single_statement']
Which courses did [John] enroll in?	'G202'	['question_type_local']
Which professors are funded?,	'Luanna'	['question_type_global', 'question_two_hop_statement']
Which courses are TAed by masters students?	'U610', 'G204'	['question_type_global', 'question_two_hop_statement']
Which courses are in the [electrical engineering] department?	'U610', 'G202'	['question_type_global', 'question_single_statement']
[this professor] went on sabbatical
What are all the courses in the electrical engineering department?	'U610', 'G202'	['question_type_global', 'question_two_hop_statement']
Who is supposed to be teaching [mini course] and is currently on sabbatical?	'Britney'	['question_type_global', 'question_three_hop_statement']
What are the 12 unit courses?	'U610', 'U101', 'G301'	['question_type_global', 'question_single_statement']
Which are some [phd] courses that no masters student is taking?	'U601', 'G204'	['question_type_global', 'question_three_hop_statement']
Which courses are offered this semester in the biomedical engineering department?	'U303'	['question_type_global', 'question_two_hop_statement']
[Lucio] currently has funding
Which professors that are currently on sabbatical need to be teaching [mini course]?	'Britney'	['question_type_global', 'question_three_hop_statement']
Create a new [phd] course called [G305]
[Luanna] teaches [that course]
[Lucy] is affiliated with the [electrical engineering] department
Which phd students have [Britney] on their committee	'Ashly'	['question_type_local']
[Lucio]'s research interest is [conservation biology]
For which phd students does [Lucio] serve on a committee?	'Ashly'	['question_type_local']
What is [she]'s department?	'electrical engineering'	['question_type_local']
Which professors are currently on sabbatical?	'Lucio', 'Britney', 'Lucy', 'Luanna', 'Marisela'	['question_type_global', 'question_single_statement']
What courses is [John] TAing?	'U610'	['question_type_local']
Who are the [fifth year] students?	'Racquel'	['question_type_global', 'question_single_statement']
Which are some [undergraduate] courses that no phd student is taking?	'U101'	['question_type_global', 'question_three_hop_statement']
What [mini course] are taught by those in the [biomedical engineering] department?	'U610'	['question_type_global', 'question_three_hop_statement']
[she] is now an [full] professor
There is a course called [G203]
[G203] is a [phd] course
What courses is [Ashly] taking?	'U610'	['question_type_local']
What department is [Igor] affiliated with?	'electrical engineering'	['question_type_local']
What professors that currently advise students are going on sabbatical?	'Marisela'	['question_type_global', 'question_two_hop_statement']
[Yoshiko] is a student in [G301]
Which students are taking [that course]?	'Yoshiko'	['question_type_local']
What [undergraduate] courses are taught by professors in the [english] department?	'G305'	['question_type_global', 'question_three_hop_statement']
Which are some courses that phd students take?	'U610'	['question_type_global', 'question_two_hop_statement']
Which professors that are currently on sabbatical need to be teaching [mini course]?	'Britney'	['question_type_global', 'question_three_hop_statement']
What are the courses that [she] is enrolled in?	'G301'	['question_type_local']
which courses have some phd students enrolled?	'U610'	['question_type_global', 'question_two_hop_statement']
which [masters] courses have some masters students enrolled?	'G301'	['question_type_global', 'question_three_hop_statement']
[Britney] has funding
What is [this professor]'s department?	'biomedical engineering'	['question_type_local']
Which courses are 12 unit courses?	'U610', 'U101', 'G301'	['question_type_global', 'question_single_statement']
Which professors have an [distinguished] status?	'Marisela'	['question_type_global', 'question_single_statement']
What department is [this professor] affiliated with?	'biomedical engineering'	['question_type_local']
[that professor] conducts research in [reinforcement learning]
Who is teaching [G305]?	'Luanna'	['question_type_local']
Which professors have an [teaching] status?	'Britney', 'Luanna'	['question_type_global', 'question_single_statement']
which students passed the proposal exam?	'Ashly'	['question_type_global', 'question_single_statement']
Which courses are [phd] level courses?	'U601', 'G204', 'G305', 'G203'	['question_type_global', 'question_single_statement']
[Lucy] currently has funding
which courses have no phd students enrolled?	'U101', 'U303', 'G201', 'U601', 'G204', 'G301', 'G202', 'G305', 'G203'	['question_type_global', 'question_two_hop_statement']
Who is on sabbatical?	'Lucio', 'Britney', 'Lucy', 'Luanna', 'Marisela'	['question_type_global', 'question_single_statement']
Which courses are TAed by [Hanna]?	'U610'	['question_type_local']
who are the masters students?	'Bob', 'Hanna', 'Yoshiko', 'Alejandra', 'John', 'Jack'	['question_type_global', 'question_single_statement']
[Igor] currently has funding
Who has [she] on their phd committee?	'Ashly', 'Racquel'	['question_type_local']
Who is part of the [biomedical engineering] department	'Britney', 'Jack'	['question_type_global', 'question_single_statement']
Which students are both taking a course and a TA?	'Hanna', 'John'	['question_type_global', 'question_two_hop_statement']
What department is [Lucy] affiliated with?	'electrical engineering'	['question_type_local']
Which courses are [mini course]	'U610', 'G301'	['question_type_global', 'question_single_statement']
[she] heads the [electrical engineering] department
who are the phd students?	'Ashly', 'Racquel', 'Tom'	['question_type_global', 'question_single_statement']
which students passed the proposal exam?	'Ashly'	['question_type_global', 'question_single_statement']
[Igor] is an [teaching] professor
What is [he]'s research focus?	'reinforcement learning'	['question_type_local']
which students passed the qualifying exam?	'Ashly'	['question_type_global', 'question_single_statement']
who are the students?	'Bob', 'Hanna', 'Ashly', 'Yoshiko', 'Alejandra', 'John', 'Racquel', 'Tom', 'Jack'	['question_type_global', 'question_single_statement']
Which professors that are currently on sabbatical need to be teaching [mini course]?	'Britney'	['question_type_global', 'question_three_hop_statement']
Create a new [undergraduate] course called [U102]
[U102] is a course in the [electrical engineering] department
[Racquel] is TAing [U102]
Which department is [that class] in?	'electrical engineering'	['question_type_local']
Which courses have phd student TAs that are in the fifth year?	'U102'	['question_type_global', 'question_three_hop_statement']
What [distinguished] professors advise students who passed their thesis qualifiers?	'Marisela'	['question_type_global', 'question_three_hop_statement']
What are the courses that [John] is enrolled in?	'G202'	['question_type_local']
Who is teaching [phd] courses?	'Lucy', 'Luanna'	['question_type_global', 'question_two_hop_statement']
[Yoshiko] is a TA for [G305]
what courses have phd students taking them?	'U610'	['question_type_global', 'question_two_hop_statement']
What 4 unit courses are taught by those in the [electrical engineering] department?	'U601'	['question_type_global', 'question_three_hop_statement']
who are the students?	'Bob', 'Hanna', 'Ashly', 'Yoshiko', 'Alejandra', 'John', 'Racquel', 'Tom', 'Jack'	['question_type_global', 'question_single_statement']
[G305] is under the [english] department
[G305] has 2 units
Which professors are funded?,	'Lucio', 'Britney', 'Lucy', 'Luanna'	['question_type_global', 'question_two_hop_statement']
which [masters] courses have some masters students enrolled?	'G301'	['question_type_global', 'question_three_hop_statement']
Who are [Igor]'s students?	'Racquel', 'Tom'	['question_type_local']
Which department is [G305] in?	'english'	['question_type_local']
Which courses in the electrical engineering department have masters TAs?	'U610'	['question_type_global', 'question_three_hop_statement']
What students are advised by a professor with funding?	'Racquel', 'Tom'	['question_type_global', 'question_two_hop_statement']
What is [Igor] research area?	'reinforcement learning'	['question_type_local']
which students passed the proposal exam?	'Ashly'	['question_type_global', 'question_single_statement']
Which professors are currently on sabbatical?	'Lucio', 'Britney', 'Lucy', 'Luanna', 'Marisela'	['question_type_global', 'question_single_statement']
the [english] department is headed by [Luanna]
What are the [third year] phd students	'Ashly'	['question_type_global', 'question_single_statement']
