[Vivienne] is a [professor]
[Vivienne] is an [distinguished] professor
[Vivienne] research interest is in [reinforcement learning]
[this professor] has funding
Who are the [distinguished] professors?	'Vivienne'	['question_type_global', 'question_single_statement']
there is a masters student named [Tom]
[that student]'s department is [neuroscience]
Which professors are conducting research in [reinforcement learning]	'Vivienne'	['question_type_global', 'question_single_statement']
there is a new masters student named [Albertha]
[Peggy] is a [professor]
[this student]'s department is [english]
there is a new PhD student named [Andy]
[he] has [Vivienne] on the committee
[this student] is current in [third year]
[Peggy] currently has funding
[that student] is [Peggy]'s student
[this professor] conducts research in [conservation biology]
Which students are in their [third year]	'Andy'	['question_type_global', 'question_single_statement']
there is a [full] [professor] named [Will]
What students are advised by a professor with funding?	'Andy'	['question_type_global', 'question_two_hop_statement']
Who has an advisor with funding?	'Andy'	['question_type_global', 'question_two_hop_statement']
[Andy] successfully defended their thesis
[this student] is now a [fourth year] student
[he] has passed the thesis proposal exam
Who advises [this person]?	'Peggy'	['question_type_local']
there is a [fourth year] PhD student named [Eun]
[Andy] has [Will] on the committee
[Will]'s research interest is [theoretical cosmology]
[Eun] is [that professor]'s student
Who has [he] on their phd committee?	'Andy'	['question_type_local']
Who is part of the [neuroscience] department	'Tom'	['question_type_global', 'question_single_statement']
Which students are in their [fourth year]	'Andy', 'Eun'	['question_type_global', 'question_single_statement']
What is [that professor]'s research focus?	'theoretical cosmology'	['question_type_local']
What students are advised by a professor with funding?	'Andy'	['question_type_global', 'question_two_hop_statement']
there is a [second year] PhD student named [Isaiah]
[he] is funded
[that student] is now in [third year]
What professors advise students who defended successfully?	'Peggy'	['question_type_global', 'question_two_hop_statement']
What professors are on [Andy]'s committee	'Vivienne', 'Will'	['question_type_local']
there is a [professor] named [Francoise]
[this student] has passed the thesis defense
What is [Vivienne] research area?	'reinforcement learning'	['question_type_local']
[that student] is [Peggy]'s student
who are the phd students?	'Andy', 'Eun', 'Isaiah'	['question_type_global', 'question_single_statement']
What is [Peggy] research area?	'conservation biology'	['question_type_local']
There is a course called [G304]
[that course] is set up as a full semester course
[Andy] and [Eun] are taking [G304]
[G304] is not a pass-fail course
[that student] has [Peggy] and [Vivienne] on the committee
Which phd students have [Vivienne] on their committee	'Andy', 'Eun'	['question_type_local']
Who are the students in the [english] department	'Albertha'	['question_type_global', 'question_two_hop_statement']
Which are some courses that no masters student is taking?	'G304'	['question_type_global', 'question_two_hop_statement']
Who are the professors working on [conservation biology]?	'Peggy'	['question_type_global', 'question_single_statement']
Which professors have an [distinguished] status?	'Vivienne'	['question_type_global', 'question_single_statement']
there is a [assistant] [professor] named [Genevive]
Who is [Andy]'s advisor?	'Peggy'	['question_type_local']
Which phd students taking the G304 course	'Andy', 'Eun'	['question_type_global', 'question_two_hop_statement']
there is a PhD student named [Tawnya]
[Tawnya] is [this professor]'s student
Who does [that professor] advise?	'Tawnya'	['question_type_local']
[that student] has passed the qualifying exam
[that person] passed thesis defense
What professors are on [Andy]'s committee	'Vivienne', 'Will'	['question_type_local']
who are the masters students?	'Tom', 'Albertha'	['question_type_global', 'question_single_statement']
there is a new masters student named [Milagros]
[Tawnya] passed thesis proposal
[Tawnya] is a [third year] student
Who advises [that person]?	'Genevive'	['question_type_local']
Which professors advise students who passed their defense?	'Peggy', 'Genevive'	['question_type_global', 'question_two_hop_statement']
Create a new [masters] course called [U302]
[this course] is not a pass-fail course
which students passed the proposal exam?	'Andy', 'Tawnya'	['question_type_global', 'question_single_statement']
who are the phd students?	'Andy', 'Eun', 'Isaiah', 'Tawnya'	['question_type_global', 'question_single_statement']
[Eun] and [Albertha] are TAing [that course]
[computer science] offers [U302]
Which courses are TAed by masters students?	'U302'	['question_type_global', 'question_two_hop_statement']
What professors advise students who defended successfully?	'Peggy', 'Genevive'	['question_type_global', 'question_two_hop_statement']
Which courses are offered this semester in the computer science department?	'U302'	['question_type_global', 'question_two_hop_statement']
which courses have some phd students enrolled?	'G304'	['question_type_global', 'question_two_hop_statement']
[Andy] currently has funding
What students are enrolled in [G304]?	'Andy', 'Eun'	['question_type_local']
[this course] will be a 12 unit course
Which courses in the computer science department have phd TAs?	'U302'	['question_type_global', 'question_three_hop_statement']
which students passed the qualifying exam?	'Tawnya'	['question_type_global', 'question_single_statement']
Which professors advise students who passed their qualifying exam?	'Genevive'	['question_type_global', 'question_two_hop_statement']
What students in third year are advised by a professor with funding?	'Isaiah'	['question_type_global', 'question_three_hop_statement']
There is a course called [G601]
[english] offers [G601]
[this course] is a [masters] level course
[this course] is a pass-fail course
[Isaiah] and [Albertha] are taking [G601]
who are the phd students?	'Andy', 'Eun', 'Isaiah', 'Tawnya'	['question_type_global', 'question_single_statement']
who are the masters students?	'Tom', 'Albertha', 'Milagros'	['question_type_global', 'question_single_statement']
[Will] teaches [G304]
What [assistant] professors advise students who passed their thesis proposal?	'Genevive'	['question_type_global', 'question_three_hop_statement']
Which students are advised by professors working on [conservation biology]?	'Andy', 'Isaiah'	['question_type_global', 'question_two_hop_statement']
who are the students?	'Tom', 'Albertha', 'Andy', 'Eun', 'Isaiah', 'Tawnya', 'Milagros'	['question_type_global', 'question_single_statement']
what courses have no masters students taking them?	'G304', 'U302'	['question_type_global', 'question_two_hop_statement']
[Andy] has [Genevive] and [Francoise] on the committee
What professors advise students who passed their thesis proposal?	'Peggy', 'Genevive'	['question_type_global', 'question_two_hop_statement']
Which courses have phd student TAs?	'U302'	['question_type_global', 'question_two_hop_statement']
[Eun] is funded
Which students are both taking a course and a TA?	'Albertha', 'Eun'	['question_type_global', 'question_two_hop_statement']
which students passed the qualifying exam?	'Tawnya'	['question_type_global', 'question_single_statement']
create a [professor] named [Emma]
[that professor] is an [assistant] professor
Which [fourth year] students are advised by professors working on [conservation biology]?	'Andy'	['question_type_global', 'question_three_hop_statement']
Which professors advise students who passed their qualifying exam?	'Genevive'	['question_type_global', 'question_two_hop_statement']
What students are in the [english] department?	'Albertha'	['question_type_global', 'question_two_hop_statement']
which students passed the proposal exam?	'Andy', 'Tawnya'	['question_type_global', 'question_single_statement']
There is a [undergraduate] course called [U9000]
[that class] is a course in the [neuroscience] department
[that class] is taught by [Genevive]
Which phd students have [Peggy] on their committee	'Eun'	['question_type_local']
which courses have some phd students enrolled?	'G304', 'G601'	['question_type_global', 'question_two_hop_statement']
[U9000] is not a pass-fail course
[Tom] is a TA for [U9000]
[Eun] and [Milagros] are taking [that course]
[U9000] is 12 units
Which department is [that course] part of?	'neuroscience'	['question_type_local']
Which are some [undergraduate] courses that phd students take?	'U9000'	['question_type_global', 'question_three_hop_statement']
which [masters] courses have no masters students enrolled?	'U302'	['question_type_global', 'question_three_hop_statement']
there is a [associate] [professor] named [William]
Who has [Peggy] on their phd committee?	'Eun'	['question_type_local']
Who is taking the G304 course	'Andy', 'Eun'	['question_type_global', 'question_single_statement']
there is a new masters student named [Roslyn]
the affiliation of [that student] is [neuroscience]
who are the students?	'Tom', 'Albertha', 'Andy', 'Eun', 'Isaiah', 'Tawnya', 'Milagros', 'Roslyn'	['question_type_global', 'question_single_statement']
[Peggy] is an [teaching] professor
What is [Will] research area?	'theoretical cosmology'	['question_type_local']
Which courses have masters student TAs?	'U302', 'U9000'	['question_type_global', 'question_two_hop_statement']
what courses have phd students taking them?	'G304', 'G601', 'U9000'	['question_type_global', 'question_two_hop_statement']
Which courses have phd student TAs that either have some funding or passed the qualifying exam?	'U302'	['question_type_global', 'question_four_hop_statement']
What professors advise students who defended successfully?	'Peggy', 'Genevive'	['question_type_global', 'question_two_hop_statement']
What students are in the [english] department?	'Albertha'	['question_type_global', 'question_two_hop_statement']
[Andy] has [Emma] and [William] on the committee
Who is on [Andy]'s committee?	'Vivienne', 'Will', 'Francoise', 'Genevive', 'Emma', 'William'	['question_type_local']
Which are some courses that masters students take?	'G601', 'U9000'	['question_type_global', 'question_two_hop_statement']
[U9000] will be a mini course
Which professors are teaching [undergraduate] courses?	'Genevive'	['question_type_global', 'question_two_hop_statement']
Which courses are part of the [english] department	'G601'	['question_type_global', 'question_single_statement']
what [masters] courses have phd students taking them?	'G601'	['question_type_global', 'question_three_hop_statement']
What courses is [Albertha] TAing?	'U302'	['question_type_local']
Which courses have phd student TAs?	'U302'	['question_type_global', 'question_two_hop_statement']
Which courses are [masters] level courses?	'U302', 'G601'	['question_type_global', 'question_single_statement']
[William] received funding
Who is teaching [G304]?	'Will'	['question_type_local']
Which people are in the [neuroscience] department?	'Tom', 'Roslyn'	['question_type_global', 'question_single_statement']
which courses have some phd students enrolled?	'G304', 'G601', 'U9000'	['question_type_global', 'question_two_hop_statement']
which [undergraduate] courses have some masters students enrolled?	'U9000'	['question_type_global', 'question_three_hop_statement']
[he]'s research interest is [molecular biology]
Which courses have masters student TAs?	'U302', 'U9000'	['question_type_global', 'question_two_hop_statement']
What students in third year are advised by a professor with funding?	'Isaiah'	['question_type_global', 'question_three_hop_statement']
What is [that person] working on?	'molecular biology'	['question_type_local']
Which professors advise students who passed their proposal?	'Peggy', 'Genevive'	['question_type_global', 'question_two_hop_statement']
What courses is [Isaiah] taking?	'G601'	['question_type_local']
Which [assistant] professors advise students who passed their qualifying exam?	'Genevive'	['question_type_global', 'question_three_hop_statement']
what courses have no phd students taking them?	'U302'	['question_type_global', 'question_two_hop_statement']
Which people are in the [neuroscience] department?	'Tom', 'Roslyn'	['question_type_global', 'question_single_statement']
What masters students are taking G601	'Albertha'	['question_type_global', 'question_two_hop_statement']
Which courses are in the [english] department?	'G601'	['question_type_global', 'question_single_statement']
which [undergraduate] courses have some phd students enrolled?	'U9000'	['question_type_global', 'question_three_hop_statement']
[Andy] is in [fifth year]
Who does [Peggy] advise?	'Andy', 'Isaiah'	['question_type_local']
Which courses in the computer science department are TAed by phd students?	'U302'	['question_type_global', 'question_three_hop_statement']
which [masters] courses have some phd students enrolled?	'G601'	['question_type_global', 'question_three_hop_statement']
who are the masters students?	'Tom', 'Albertha', 'Milagros', 'Roslyn'	['question_type_global', 'question_single_statement']
which students passed the defense?	'Andy', 'Isaiah', 'Tawnya'	['question_type_global', 'question_single_statement']
which courses have some phd students enrolled?	'G304', 'G601', 'U9000'	['question_type_global', 'question_two_hop_statement']
which courses have no phd students enrolled?	'U302'	['question_type_global', 'question_two_hop_statement']
Who is [Isaiah]'s advisor?	'Peggy'	['question_type_local']
which courses have no masters students enrolled?	'G304', 'U302'	['question_type_global', 'question_two_hop_statement']
Which phd students are both taking a course and a TA?	'Eun'	['question_type_global', 'question_three_hop_statement']
Which professors are teaching [mini course]?	'Genevive'	['question_type_global', 'question_two_hop_statement']
[Roslyn] is a TA for [U9000]
Who is teaching [that course]?	'Genevive'	['question_type_local']
Which courses are offered this semester in the computer science department?	'U302'	['question_type_global', 'question_two_hop_statement']
Which courses are [full_semester_course]	'G304'	['question_type_global', 'question_single_statement']
[Albertha] and [Tawnya] are both taking [U302]
What department is [U302] offered in?	'computer science'	['question_type_local']
Who has an advisor with funding?	'Andy', 'Isaiah'	['question_type_global', 'question_two_hop_statement']
Who is teaching [full_semester_course]?	'Will'	['question_type_global', 'question_two_hop_statement']
Which courses did [Albertha] enroll in?	'U302', 'G601'	['question_type_local']
What students are taking U302	'Albertha', 'Tawnya'	['question_type_global', 'question_single_statement']
What are the courses that [Albertha] is enrolled in?	'U302', 'G601'	['question_type_local']
which [masters] courses have some masters students enrolled?	'U302', 'G601'	['question_type_global', 'question_three_hop_statement']
[Andy] passed the qualifiers
Who has [Genevive] on their phd committee?	'Andy'	['question_type_local']
which courses have some phd students enrolled?	'G304', 'U302', 'G601', 'U9000'	['question_type_global', 'question_two_hop_statement']
[Peggy] is on [she]'s committee
Which phd students taking the U302 course	'Tawnya'	['question_type_global', 'question_two_hop_statement']
which students passed the qualifying exam?	'Andy', 'Tawnya'	['question_type_global', 'question_single_statement']
What students are going to TA [U9000]?	'Tom', 'Roslyn'	['question_type_local']
Which courses are [undergraduate] level courses?	'U9000'	['question_type_global', 'question_single_statement']
[this professor] is now an [assistant] professor
What courses is [Albertha] taking?	'U302', 'G601'	['question_type_local']
What masters students are taking U302	'Albertha'	['question_type_global', 'question_two_hop_statement']
Who are the [third year] students?	'Isaiah', 'Tawnya'	['question_type_global', 'question_single_statement']
What are all the courses?	'G304', 'U302', 'G601', 'U9000'	['question_type_global', 'question_single_statement']
What students are taking U302	'Albertha', 'Tawnya'	['question_type_global', 'question_single_statement']
Which students are taking [U302]?	'Albertha', 'Tawnya'	['question_type_local']
Which courses in the computer science department are TAed by phd students?	'U302'	['question_type_global', 'question_three_hop_statement']
What are the [computer science] courses?	'U302'	['question_type_global', 'question_single_statement']
What is [she]'s research focus?	'conservation biology'	['question_type_local']
which courses have some masters students enrolled?	'U302', 'G601', 'U9000'	['question_type_global', 'question_two_hop_statement']
Which courses have masters student TAs?	'U302', 'U9000'	['question_type_global', 'question_two_hop_statement']
For which phd students does [Will] serve on a committee?	'Andy'	['question_type_local']
What students have funding?	'Andy', 'Eun', 'Isaiah'	['question_type_global', 'question_single_statement']
What is [Will]'s research focus?	'theoretical cosmology'	['question_type_local']
Which courses are 12 unit courses?	'U302', 'U9000'	['question_type_global', 'question_single_statement']
[Emma] research interest is in [supervised learning]
For which phd students does [Emma] serve on a committee?	'Andy'	['question_type_local']
Create a new course called [U610]
[U610] is a course in the [computer science] department
What students are taking a course taught by their advisor?	'Eun'	['question_type_global', 'question_three_hop_statement']
Which professors have an [associate] status?	'William'	['question_type_global', 'question_single_statement']
[this course] will be a 4 unit course
Who is taking the G304 course	'Andy', 'Eun'	['question_type_global', 'question_single_statement']
Who is teaching [mini course]?	'Genevive'	['question_type_global', 'question_two_hop_statement']
Which professors are teaching [full_semester_course]?	'Will'	['question_type_global', 'question_two_hop_statement']
Which courses are TAed by phd students?	'U302'	['question_type_global', 'question_two_hop_statement']
There is a [phd] level 12 unit course called [U601]
[U610] is set up as a full semester course
What students have funding?	'Andy', 'Eun', 'Isaiah'	['question_type_global', 'question_single_statement']
[U302] is taught by [Francoise]
Which professors have an [distinguished] status?	'Vivienne'	['question_type_global', 'question_single_statement']
What professors advise students who passed their thesis qualifiers?	'Peggy', 'Genevive'	['question_type_global', 'question_two_hop_statement']
Which courses are TAed by masters students?	'U302', 'U9000'	['question_type_global', 'question_two_hop_statement']
[Tawnya] and [Milagros] are both enrolled in [U9000]
Which students are TAing [U9000]?	'Tom', 'Roslyn'	['question_type_local']
[Milagros] is affiliated with the [english] department
[William] teaches [U601]
which students passed the defense?	'Andy', 'Isaiah', 'Tawnya'	['question_type_global', 'question_single_statement']
Who is on [Tawnya]'s committee?	'Peggy'	['question_type_local']
Which are some courses that masters students take?	'U302', 'G601', 'U9000'	['question_type_global', 'question_two_hop_statement']
What students are enrolled in [G304]?	'Andy', 'Eun'	['question_type_local']
What students are advised by a professor with funding?	'Andy', 'Isaiah'	['question_type_global', 'question_two_hop_statement']
[that class] will be a mini course
Who is teaching [G304]?	'Will'	['question_type_local']
[that course] is a pass-fail course
Who is teaching [that course]?	'William'	['question_type_local']
what [phd] courses have no masters students taking them?	'U601'	['question_type_global', 'question_three_hop_statement']
What professors advise students who defended successfully?	'Peggy', 'Genevive'	['question_type_global', 'question_two_hop_statement']
[Isaiah] and [Roslyn] are both taking [U610]
What students are enrolled in [U610]?	'Isaiah', 'Roslyn'	['question_type_local']
who are the professors?	'Vivienne', 'Peggy', 'Will', 'Francoise', 'Genevive', 'Emma', 'William'	['question_type_global', 'question_single_statement']
Which courses in the computer science department are TAed by masters students?	'U302'	['question_type_global', 'question_three_hop_statement']
Which masters students taking the G601 course	'Albertha'	['question_type_global', 'question_two_hop_statement']
[Emma] currently has funding
Which courses are [undergraduate] level courses?	'U9000'	['question_type_global', 'question_single_statement']
What courses is [William] teaching?	'U601'	['question_type_local']
which students passed the proposal exam?	'Andy', 'Tawnya'	['question_type_global', 'question_single_statement']
what courses have phd students taking them?	'G304', 'U302', 'G601', 'U9000', 'U610'	['question_type_global', 'question_two_hop_statement']
Which courses did [Tawnya] enroll in?	'U302', 'U9000'	['question_type_local']
who are the phd students?	'Andy', 'Eun', 'Isaiah', 'Tawnya'	['question_type_global', 'question_single_statement']
Who are the [fifth year] students?	'Andy'	['question_type_global', 'question_single_statement']
which courses have some phd students enrolled?	'G304', 'U302', 'G601', 'U9000', 'U610'	['question_type_global', 'question_two_hop_statement']
Create a new [undergraduate] level 8 unit course called [U7000]
[U7000] is TAed by [Andy] and [Isaiah]
Which people are in the [neuroscience] department?	'Tom', 'Roslyn'	['question_type_global', 'question_single_statement']
Who is teaching [U9000]?	'Genevive'	['question_type_local']
Which are some courses that phd students take?	'G304', 'U302', 'G601', 'U9000', 'U610'	['question_type_global', 'question_two_hop_statement']
Who is taking the U610 course	'Isaiah', 'Roslyn'	['question_type_global', 'question_single_statement']
[Isaiah] passed thesis proposal
Which courses in the computer science department have fourth year phd TAs?	'U302'	['question_type_global', 'question_three_hop_statement']
[he] is now in [fourth year]
Which courses are 4 unit courses?	'U610'	['question_type_global', 'question_single_statement']
What are the [undergraduate] courses?	'U9000', 'U7000'	['question_type_global', 'question_single_statement']
Which are some [phd] courses that no masters student is taking?	'U601'	['question_type_global', 'question_three_hop_statement']
Which department is [U9000] part of?	'neuroscience'	['question_type_local']
[this student] is in [fifth year]
What courses is [this student] taking?	'G601', 'U610'	['question_type_local']
[that student] is now a [sixth year] student
Who is taking [U610]?	'Isaiah', 'Roslyn'	['question_type_local']
Which courses are TAed by masters students?	'U302', 'U9000'	['question_type_global', 'question_two_hop_statement']
what courses have phd students taking them?	'G304', 'U302', 'G601', 'U9000', 'U610'	['question_type_global', 'question_two_hop_statement']
What are the courses that [Isaiah] is enrolled in?	'G601', 'U610'	['question_type_local']
Which professors are conducting research in [theoretical cosmology]	'Will'	['question_type_global', 'question_single_statement']
Who are the [fourth year] students?	'Eun'	['question_type_global', 'question_single_statement']
Who are the [sixth year] students?	'Isaiah'	['question_type_global', 'question_single_statement']
What [assistant] professors advise students who defended successfully?	'Peggy', 'Genevive'	['question_type_global', 'question_three_hop_statement']
who are the professors?	'Vivienne', 'Peggy', 'Will', 'Francoise', 'Genevive', 'Emma', 'William'	['question_type_global', 'question_single_statement']
[Eun] failed their thesis defense
[she] passed the qualifiers
Who are [Genevive]'s students?	'Tawnya'	['question_type_local']
What are all the courses?	'G304', 'U302', 'G601', 'U9000', 'U610', 'U601', 'U7000'	['question_type_global', 'question_single_statement']
Which are some courses that phd students take?	'G304', 'U302', 'G601', 'U9000', 'U610'	['question_type_global', 'question_two_hop_statement']
