there is a new masters student named [Francoise]
the affiliation of [this student] is [english]
there is a masters student named [Emma]
create a [professor] named [Casey]
[that professor] is an [distinguished] professor
There is a course called [G103]
[that course] is not a pass-fail course
[that course] is set up as a full semester course
[that course] is a [phd] level course
create a [full] [professor] named [Will]
[that professor] research interest is in [neurocomputing]
[Racquel] is a masters student
[he] is the instructor for [G103]
[G103] is under the [english] department
[Emma] is taking [G103]
Who is taking [that class]?	'Emma'	['question_type_local']
what courses have masters students taking them?	'G103'	['question_type_global', 'question_two_hop_statement']
Who is teaching [that class]?	'Will'	['question_type_local']
who are the masters students?	'Francoise', 'Emma', 'Racquel'	['question_type_global', 'question_single_statement']
[Emma] and [Francoise] are both enrolled in [this course]
Who is teaching [G103]?	'Will'	['question_type_local']
Who are the students in the [english] department	'Francoise'	['question_type_global', 'question_two_hop_statement']
What is [Will]'s research focus?	'neurocomputing'	['question_type_local']
Which professors have an [full] status?	'Will'	['question_type_global', 'question_single_statement']
Which masters students taking the G103 course	'Francoise', 'Emma'	['question_type_global', 'question_two_hop_statement']
[she] is affiliated with the [biomedical engineering] department
Which courses did [he] enroll in?	'G103'	['question_type_local']
Which professors are teaching [full_semester_course]?	'Will'	['question_type_global', 'question_two_hop_statement']
which courses have some masters students enrolled?	'G103'	['question_type_global', 'question_two_hop_statement']
Who is teaching [G103]?	'Will'	['question_type_local']
What are the [phd] courses?	'G103'	['question_type_global', 'question_single_statement']
who are the professors?	'Casey', 'Will'	['question_type_global', 'question_single_statement']
[Albertha] is a masters student
the affiliation of [Albertha] is [biomedical engineering]
create a [distinguished] [professor] named [Isaiah]
What are all the courses?	'G103'	['question_type_global', 'question_single_statement']
[she] is enrolled in [G103]
What department is [this course] offered in?	'english'	['question_type_local']
What students are taking G103	'Francoise', 'Emma', 'Albertha'	['question_type_global', 'question_single_statement']
Create a new course called [U203]
[this course] is under the [psychology] department
[Casey] is the instructor for [U203]
The TA for [this course] is [Racquel]
who are the masters students?	'Francoise', 'Emma', 'Racquel', 'Albertha'	['question_type_global', 'question_single_statement']
Who is teaching [full_semester_course]?	'Will'	['question_type_global', 'question_two_hop_statement']
[that student] is affiliated with the [psychology] department
who are the students?	'Francoise', 'Emma', 'Racquel', 'Albertha'	['question_type_global', 'question_single_statement']
[Hanna] is a masters student
the affiliation of [Hanna] is [psychology]
Which department is [G103] in?	'english'	['question_type_local']
Which are some courses that no masters student is taking?	'U203'	['question_type_global', 'question_two_hop_statement']
there is a [professor] named [Andrew]
Which courses have masters student TAs?	'U203'	['question_type_global', 'question_two_hop_statement']
Create a new [phd] course called [G304]
[G304] is full semester
[that class] part of the [psychology] department
Who is part of the [biomedical engineering] department	'Emma', 'Albertha'	['question_type_global', 'question_single_statement']
Create a new [undergraduate] course called [U7000]
[Racquel] and [Hanna] are attending [U7000]
What are the courses that [Hanna] is enrolled in?	'U7000'	['question_type_local']
Who is teaching [G103]?	'Will'	['question_type_local']
there is a PhD student named [Yoshiko]
Which courses did [Hanna] enroll in?	'U7000'	['question_type_local']
who are the students?	'Francoise', 'Emma', 'Racquel', 'Albertha', 'Hanna', 'Yoshiko'	['question_type_global', 'question_single_statement']
Which courses are offered this semester?	'G103', 'U203', 'G304', 'U7000'	['question_type_global', 'question_single_statement']
[Yoshiko] is a [sixth year] student
create a [professor] named [Genevive]
[that professor] advises [that student]
What are all the courses?	'G103', 'U203', 'G304', 'U7000'	['question_type_global', 'question_single_statement']
Who is teaching [full_semester_course]?	'Will'	['question_type_global', 'question_two_hop_statement']
[Vivienne] is a PhD student
[Yoshiko] passed thesis proposal
Which are some courses that no masters student is taking?	'U203', 'G304'	['question_type_global', 'question_two_hop_statement']
Which students are in their [sixth year]	'Yoshiko'	['question_type_global', 'question_single_statement']
there is a [fifth year] PhD student named [Tawnya]
[Yoshiko] successfully defended their thesis
[Isaiah] and [Andrew] are on [Yoshiko]'s committee
What masters students are taking U7000	'Racquel', 'Hanna'	['question_type_global', 'question_two_hop_statement']
Which courses are part of the [psychology] department	'U203', 'G304'	['question_type_global', 'question_single_statement']
create a [associate] [professor] named [Luanna]
[Andrew] is an [assistant] professor
[Andrew] advises [Tawnya]
who are the students?	'Francoise', 'Emma', 'Racquel', 'Albertha', 'Hanna', 'Yoshiko', 'Vivienne', 'Tawnya'	['question_type_global', 'question_single_statement']
Which courses in the psychology department are TAed by masters students?	'U203'	['question_type_global', 'question_three_hop_statement']
[Vivienne] is [Andrew]'s student
Which courses are TAed by masters students?	'U203'	['question_type_global', 'question_two_hop_statement']
Who is part of the [psychology] department	'Racquel', 'Hanna'	['question_type_global', 'question_single_statement']
there is a [sixth year] PhD student named [Tom]
[Will] and [Isaiah] are on [she]'s committee
which students passed the defense?	'Yoshiko'	['question_type_global', 'question_single_statement']
there is a masters student named [Marisela]
[this professor]'s research interest is [reinforcement learning]
there is a [professor] named [Cecil]
[Cecil] advises [Tom]
who are the professors?	'Casey', 'Will', 'Isaiah', 'Andrew', 'Genevive', 'Luanna', 'Cecil'	['question_type_global', 'question_single_statement']
there is a masters student named [Lucio]
[Tom] has passed the qualifying exam
[Tom] has [Luanna] and [Genevive] on the committee
[Luanna] and [Will] are on [Yoshiko]'s committee
Who is [Yoshiko]'s advisor?	'Genevive'	['question_type_local']
the affiliation of [Lucio] is [english]
Which courses did [Emma] enroll in?	'G103'	['question_type_local']
which students passed the qualifying exam?	'Tom'	['question_type_global', 'question_single_statement']
create a [associate] [professor] named [Kristeen]
Which courses did [Francoise] enroll in?	'G103'	['question_type_local']
Who is part of the [biomedical engineering] department	'Emma', 'Albertha'	['question_type_global', 'question_single_statement']
what courses have no phd students taking them?	'G103', 'U203', 'G304', 'U7000'	['question_type_global', 'question_two_hop_statement']
[Kristeen] research interest is in [reinforcement learning]
What is [Kristeen] working on?	'reinforcement learning'	['question_type_local']
What are the [sixth year] phd students	'Yoshiko', 'Tom'	['question_type_global', 'question_single_statement']
Which professors are teaching [full_semester_course]?	'Will'	['question_type_global', 'question_two_hop_statement']
Who are the students in the [psychology] department	'Racquel', 'Hanna'	['question_type_global', 'question_two_hop_statement']
which students passed the defense?	'Yoshiko'	['question_type_global', 'question_single_statement']
what courses have no masters students taking them?	'U203', 'G304'	['question_type_global', 'question_two_hop_statement']
[Tawnya]'s office is [Koelbel Building]
Which students are both taking a course and a TA?	'Racquel'	['question_type_global', 'question_two_hop_statement']
Which professors advise students who passed their qualifying exam?	'Cecil'	['question_type_global', 'question_two_hop_statement']
What students are taking U7000	'Racquel', 'Hanna'	['question_type_global', 'question_single_statement']
What is [that professor]'s research focus?	'reinforcement learning'	['question_type_local']
which courses have no phd students enrolled?	'G103', 'U203', 'G304', 'U7000'	['question_type_global', 'question_two_hop_statement']
[Tom] is funded
[Tom] passed thesis proposal
who are the phd students?	'Yoshiko', 'Vivienne', 'Tawnya', 'Tom'	['question_type_global', 'question_single_statement']
Which are some courses that masters students take?	'G103', 'U7000'	['question_type_global', 'question_two_hop_statement']
[this student] has passed the thesis defense
Who is [he]'s advisor?	'Cecil'	['question_type_local']
Which professors are teaching [phd] courses?	'Will'	['question_type_global', 'question_two_hop_statement']
Which professors have an [full] status?	'Will'	['question_type_global', 'question_single_statement']
Who are the students in the [psychology] department	'Racquel', 'Hanna'	['question_type_global', 'question_two_hop_statement']
[that person]'s office is [Main Building]
which [undergraduate] courses have no phd students enrolled?	'U7000'	['question_type_global', 'question_three_hop_statement']
which students passed the defense?	'Yoshiko', 'Tom'	['question_type_global', 'question_single_statement']
Which courses are TAed by masters students?	'U203'	['question_type_global', 'question_two_hop_statement']
[Kristeen] is on [this student]'s committee
Who is teaching [full_semester_course]?	'Will'	['question_type_global', 'question_two_hop_statement']
What students are taking courses and TAing?	'Racquel'	['question_type_global', 'question_two_hop_statement']
[Genevive] is an [assistant] professor
For which phd students does [Genevive] serve on a committee?	'Tom'	['question_type_local']
Which students are in their [fifth year]	'Tawnya'	['question_type_global', 'question_single_statement']
Who is taking the U7000 course	'Racquel', 'Hanna'	['question_type_global', 'question_single_statement']
what [phd] courses have no masters students taking them?	'G304'	['question_type_global', 'question_three_hop_statement']
What students are in Main Building	'Tom'	['question_type_global', 'question_two_hop_statement']
Which masters students taking the G103 course	'Francoise', 'Emma', 'Albertha'	['question_type_global', 'question_two_hop_statement']
who are the professors?	'Casey', 'Will', 'Isaiah', 'Andrew', 'Genevive', 'Luanna', 'Cecil', 'Kristeen'	['question_type_global', 'question_single_statement']
who are the students?	'Francoise', 'Emma', 'Racquel', 'Albertha', 'Hanna', 'Yoshiko', 'Vivienne', 'Tawnya', 'Tom', 'Marisela', 'Lucio'	['question_type_global', 'question_single_statement']
[Kristeen] has been promoted to [full] professor
Which department is [G103] in?	'english'	['question_type_local']
[Kristeen] has been promoted to [distinguished] professor
What is [that professor] research area?	'reinforcement learning'	['question_type_local']
[G103] is TAed by [Albertha] and [Hanna]
What are the courses that [Hanna] is enrolled in?	'U7000'	['question_type_local']
which students passed the defense?	'Yoshiko', 'Tom'	['question_type_global', 'question_single_statement']
Which courses in the psychology department have masters TAs?	'U203'	['question_type_global', 'question_three_hop_statement']
which [phd] courses have no masters students enrolled?	'G304'	['question_type_global', 'question_three_hop_statement']
Who is teaching [full_semester_course]?	'Will'	['question_type_global', 'question_two_hop_statement']
Which courses did [Hanna] enroll in?	'U7000'	['question_type_local']
Which students have offices in Koelbel Building	'Tawnya'	['question_type_global', 'question_two_hop_statement']
which students passed the qualifying exam?	'Tom'	['question_type_global', 'question_single_statement']
who are the professors?	'Casey', 'Will', 'Isaiah', 'Andrew', 'Genevive', 'Luanna', 'Cecil', 'Kristeen'	['question_type_global', 'question_single_statement']
Who are the students in the [english] department	'Francoise', 'Lucio'	['question_type_global', 'question_two_hop_statement']
Which courses are TAed by [Albertha]?	'G103'	['question_type_local']
What are the courses TAed by [Albertha]?	'G103'	['question_type_local']
Who has an office in [Main Building]	'Tom'	['question_type_global', 'question_two_hop_statement']
[Cecil] conducts research in [reinforcement learning]
What is [Cecil]'s research focus?	'reinforcement learning'	['question_type_local']
Who is in the [psychology] department	'Racquel', 'Hanna'	['question_type_global', 'question_single_statement']
What courses is [Will] teaching?	'G103'	['question_type_local']
Which professors advise students who passed their defense?	'Genevive', 'Cecil'	['question_type_global', 'question_two_hop_statement']
What are the courses that [Emma] is enrolled in?	'G103'	['question_type_local']
which students passed the qualifying exam?	'Tom'	['question_type_global', 'question_single_statement']
who are the students?	'Francoise', 'Emma', 'Racquel', 'Albertha', 'Hanna', 'Yoshiko', 'Vivienne', 'Tawnya', 'Tom', 'Marisela', 'Lucio'	['question_type_global', 'question_single_statement']
who are the professors?	'Casey', 'Will', 'Isaiah', 'Andrew', 'Genevive', 'Luanna', 'Cecil', 'Kristeen'	['question_type_global', 'question_single_statement']
which students passed the proposal exam?	'Yoshiko', 'Tom'	['question_type_global', 'question_single_statement']
Who is teaching [full_semester_course]?	'Will'	['question_type_global', 'question_two_hop_statement']
[Tawnya] is a TA for [G304]
What masters students are taking U7000	'Racquel', 'Hanna'	['question_type_global', 'question_two_hop_statement']
Which courses are TAed by masters students?	'G103', 'U203'	['question_type_global', 'question_two_hop_statement']
which courses have no phd students enrolled?	'G103', 'U203', 'G304', 'U7000'	['question_type_global', 'question_two_hop_statement']
[that person] passed the qualifiers
Which students are both taking a course and a TA?	'Racquel', 'Albertha', 'Hanna'	['question_type_global', 'question_two_hop_statement']
[this person] failed their thesis defense
who are the professors?	'Casey', 'Will', 'Isaiah', 'Andrew', 'Genevive', 'Luanna', 'Cecil', 'Kristeen'	['question_type_global', 'question_single_statement']
[she] failed thesis proposal
Which are some [phd] courses that no phd student is taking?	'G103', 'G304'	['question_type_global', 'question_three_hop_statement']
[Genevive]'s research interest is [reinforcement learning]
Who are [this professor]'s students?	'Yoshiko'	['question_type_local']
Who is teaching [full_semester_course]?	'Will'	['question_type_global', 'question_two_hop_statement']
There is a [undergraduate] level course called [U610]
Which courses are TAed by phd students that passed their qualifier exam or have some funding?	'G304'	['question_type_global', 'question_four_hop_statement']
What professors advise students who passed their thesis proposal?	'Genevive', 'Cecil'	['question_type_global', 'question_two_hop_statement']
What is [that professor]'s research focus?	'reinforcement learning'	['question_type_local']
Who is part of the [biomedical engineering] department	'Emma', 'Albertha'	['question_type_global', 'question_single_statement']
Which masters students taking the G103 course	'Francoise', 'Emma', 'Albertha'	['question_type_global', 'question_two_hop_statement']
Which courses have masters student TAs?	'G103', 'U203'	['question_type_global', 'question_two_hop_statement']
Which students are funded?	'Tom'	['question_type_global', 'question_single_statement']
Create a new [phd] [full_semester_course] called [G9000]
[G9000] part of the [psychology] department
[Emma] is attending [G9000]
What department is [that course] offered in?	'psychology'	['question_type_local']
who are the students?	'Francoise', 'Emma', 'Racquel', 'Albertha', 'Hanna', 'Yoshiko', 'Vivienne', 'Tawnya', 'Tom', 'Marisela', 'Lucio'	['question_type_global', 'question_single_statement']
What are the courses that [she] is enrolled in?	'G103', 'G9000'	['question_type_local']
Which courses in the psychology department are TAed by phd students?	'G304'	['question_type_global', 'question_three_hop_statement']
Which [sixth year] students's advisors are conducting research in [reinforcement learning]	'Yoshiko', 'Tom'	['question_type_global', 'question_three_hop_statement']
Which courses are part of the [psychology] department	'U203', 'G304', 'G9000'	['question_type_global', 'question_single_statement']
There is a [masters] 4 unit class called [U310]
What courses is [this person] taking?	'G103', 'G9000'	['question_type_local']
Which courses are TAed by masters students?	'G103', 'U203'	['question_type_global', 'question_two_hop_statement']
Which professors are conducting research in [reinforcement learning]	'Isaiah', 'Genevive', 'Cecil', 'Kristeen'	['question_type_global', 'question_single_statement']
which students passed the proposal exam?	'Yoshiko', 'Tom'	['question_type_global', 'question_single_statement']
What are all the courses in the english department?	'G103'	['question_type_global', 'question_two_hop_statement']
[U310] is not a pass-fail course
[Marisela] and [Yoshiko] are taking [that course]
Which students are both taking a course and a TA?	'Racquel', 'Albertha', 'Hanna'	['question_type_global', 'question_two_hop_statement']
which students passed the qualifying exam?	'Tawnya', 'Tom'	['question_type_global', 'question_single_statement']
Which courses are [full_semester_course]	'G103', 'G304', 'G9000'	['question_type_global', 'question_single_statement']
the affiliation of [Marisela] is [english]
Which professors advise students who passed their qualifying exam?	'Andrew', 'Cecil'	['question_type_global', 'question_two_hop_statement']
What are the 4 unit courses?	'U310'	['question_type_global', 'question_single_statement']
who are the students?	'Francoise', 'Emma', 'Racquel', 'Albertha', 'Hanna', 'Yoshiko', 'Vivienne', 'Tawnya', 'Tom', 'Marisela', 'Lucio'	['question_type_global', 'question_single_statement']
[G304] is a pass-fail course
[that class] is TAed by [Yoshiko] and [Marisela]
Which courses are 4 unit courses?	'U310'	['question_type_global', 'question_single_statement']
What is [Genevive] research area?	'reinforcement learning'	['question_type_local']
What are the courses TAed by [Marisela]?	'G304'	['question_type_local']
Which courses are part of the [psychology] department	'U203', 'G304', 'G9000'	['question_type_global', 'question_single_statement']
What students are taking G103	'Francoise', 'Emma', 'Albertha'	['question_type_global', 'question_single_statement']
What students are taking courses and TAing?	'Racquel', 'Albertha', 'Hanna', 'Yoshiko', 'Marisela'	['question_type_global', 'question_two_hop_statement']
[U203] is a [masters] level course
[Racquel] and [Marisela] are taking [U203]
Which department is [U203] part of?	'psychology'	['question_type_local']
Who is in [Koelbel Building]	'Tawnya'	['question_type_global', 'question_two_hop_statement']
What masters students are taking U7000	'Racquel', 'Hanna'	['question_type_global', 'question_two_hop_statement']
What professors advise students who defended successfully?	'Genevive', 'Cecil'	['question_type_global', 'question_two_hop_statement']
[Andrew]'s research interest is [theory]
Which phd students have [Luanna] on their committee	'Yoshiko', 'Tom'	['question_type_local']
who are the masters students?	'Francoise', 'Emma', 'Racquel', 'Albertha', 'Hanna', 'Marisela', 'Lucio'	['question_type_global', 'question_single_statement']
Which professors are teaching [full_semester_course]?	'Will'	['question_type_global', 'question_two_hop_statement']
Which courses are TAed by [Albertha]?	'G103'	['question_type_local']
Which students are funded?	'Tom'	['question_type_global', 'question_single_statement']
What courses is [Francoise] taking?	'G103'	['question_type_local']
who are the professors?	'Casey', 'Will', 'Isaiah', 'Andrew', 'Genevive', 'Luanna', 'Cecil', 'Kristeen'	['question_type_global', 'question_single_statement']
What courses is [she] TAing?	'G304'	['question_type_local']
Who is in [Koelbel Building]	'Tawnya'	['question_type_global', 'question_two_hop_statement']
Which professors advise students who passed their defense?	'Genevive', 'Cecil'	['question_type_global', 'question_two_hop_statement']
Which courses have phd student TAs?	'G304'	['question_type_global', 'question_two_hop_statement']
Which professors advise students who passed their qualifying exam?	'Andrew', 'Cecil'	['question_type_global', 'question_two_hop_statement']
Create a new course called [G204]
[G204] is a pass-fail course
[that class] is a full semester course
what [masters] courses have no phd students taking them?	'U203'	['question_type_global', 'question_three_hop_statement']
What phd students are taking courses and TAing?	'Yoshiko'	['question_type_global', 'question_three_hop_statement']
[Kristeen] teaches [G204]
What courses is [Albertha] TAing?	'G103'	['question_type_local']
What professors advise students who defended successfully?	'Genevive', 'Cecil'	['question_type_global', 'question_two_hop_statement']
[this course] is a [undergraduate] course
[Racquel] is taking [that class]
which students passed the defense?	'Yoshiko', 'Tom'	['question_type_global', 'question_single_statement']
Which courses are offered this semester in the english department?	'G103'	['question_type_global', 'question_two_hop_statement']
who are the phd students?	'Yoshiko', 'Vivienne', 'Tawnya', 'Tom'	['question_type_global', 'question_single_statement']
Which professors advise students who passed their proposal?	'Genevive', 'Cecil'	['question_type_global', 'question_two_hop_statement']
what courses have phd students taking them?	'U310'	['question_type_global', 'question_two_hop_statement']
There is a [undergraduate] level course called [U303]
[Francoise] and [Tom] are taking [that class]
[Luanna] is the instructor for [U303]
[U303] is not a pass-fail course
Who is taking [this course]?	'Francoise', 'Tom'	['question_type_local']
who are the students?	'Francoise', 'Emma', 'Racquel', 'Albertha', 'Hanna', 'Yoshiko', 'Vivienne', 'Tawnya', 'Tom', 'Marisela', 'Lucio'	['question_type_global', 'question_single_statement']
Which professors are teaching [full_semester_course]?	'Will', 'Kristeen'	['question_type_global', 'question_two_hop_statement']
who are the masters students?	'Francoise', 'Emma', 'Racquel', 'Albertha', 'Hanna', 'Marisela', 'Lucio'	['question_type_global', 'question_single_statement']
There is a course called [G310]
[G310] is not a pass-fail course
[G310] is set up as a full semester course
[psychology] offers [this course]
what [phd] courses have no masters students taking them?	'G304'	['question_type_global', 'question_three_hop_statement']
