There is a course called [G102]
[this course] is set up as a full semester course
what courses have no phd students taking them?	'G102'	['question_type_global', 'question_two_hop_statement']
there is a [fifth year] PhD student named [Tom]
[this student] is funded
[Tom] has passed the thesis proposal exam
[this student] is now in [sixth year]
[he] has failed the qualifying exam
[this student] is taking [G102]
there is a new masters student named [Britney]
Who is taking the G102 course	'Tom'	['question_type_global', 'question_single_statement']
there is a masters student named [Cyndi]
which courses have some phd students enrolled?	'G102'	['question_type_global', 'question_two_hop_statement']
there is a PhD student named [Danita]
[Danita] successfully defended their thesis
[Danita] did not pass the qualifiers
who are the masters students?	'Britney', 'Cyndi'	['question_type_global', 'question_single_statement']
[Andrew] is a masters student
[she] has passed the thesis proposal exam
[Britney] is TAing [G102]
What are the [sixth year] phd students	'Tom'	['question_type_global', 'question_single_statement']
[G102] is a [masters] level course
[Danita] and [Tom] are both taking [that class]
[G102] is TAed by [Tom] and [Andrew]
Who is TAing [G102]?	'Tom', 'Britney', 'Andrew'	['question_type_local']
Which courses are TAed by phd students?	'G102'	['question_type_global', 'question_two_hop_statement']
[Michael] is a masters student
[G102] is a 2 unit course
Who is taking [G102]?	'Tom', 'Danita'	['question_type_local']
which students passed the proposal exam?	'Tom', 'Danita'	['question_type_global', 'question_single_statement']
[Michael] is a TA for [G102]
Which are some courses that no masters student is taking?	'G102'	['question_type_global', 'question_two_hop_statement']
Which courses are TAed by phd students that passed their qualifier exam or have some funding?	'G102'	['question_type_global', 'question_four_hop_statement']
there is a PhD student named [Stephine]
[she] passed thesis proposal
which [masters] courses have no masters students enrolled?	'G102'	['question_type_global', 'question_three_hop_statement']
there is a masters student named [Andy]
Which courses are TAed by [Michael]?	'G102'	['question_type_local']
What phd students are taking G102	'Tom', 'Danita'	['question_type_global', 'question_two_hop_statement']
who are the students?	'Tom', 'Britney', 'Cyndi', 'Danita', 'Andrew', 'Michael', 'Stephine', 'Andy'	['question_type_global', 'question_single_statement']
Which courses are TAed by masters students?	'G102'	['question_type_global', 'question_two_hop_statement']
[she] is current in [second year]
Which are some courses that phd students take?	'G102'	['question_type_global', 'question_two_hop_statement']
Create a new course called [G301]
[G301] is a [masters] course
[Andy] and [Danita] are TAs for [G301]
What are the [sixth year] phd students	'Tom'	['question_type_global', 'question_single_statement']
[Britney] and [Cyndi] are taking [G102]
who are the masters students?	'Britney', 'Cyndi', 'Andrew', 'Michael', 'Andy'	['question_type_global', 'question_single_statement']
Which phd students taking the G102 course	'Tom', 'Danita'	['question_type_global', 'question_two_hop_statement']
who are the phd students?	'Tom', 'Danita', 'Stephine'	['question_type_global', 'question_single_statement']
which [masters] courses have no masters students enrolled?	'G301'	['question_type_global', 'question_three_hop_statement']
Create a new course called [G310]
Which courses have phd student TAs?	'G102', 'G301'	['question_type_global', 'question_two_hop_statement']
[Zenaida] is a PhD student
Which courses are TAed by [Andrew]?	'G102'	['question_type_local']
There is a course called [U304]
[this student] passed thesis proposal
[she] currently has funding
what [masters] courses have no masters students taking them?	'G301'	['question_type_global', 'question_three_hop_statement']
Which courses are TAed by masters students?	'G102', 'G301'	['question_type_global', 'question_two_hop_statement']
there is a new masters student named [Alejandra]
there is a masters student named [Loyd]
who are the students?	'Tom', 'Britney', 'Cyndi', 'Danita', 'Andrew', 'Michael', 'Stephine', 'Andy', 'Zenaida', 'Alejandra', 'Loyd'	['question_type_global', 'question_single_statement']
There is a [masters] level 4 unit course called [U303]
[Cyndi] and [Britney] are taking [that course]
What phd students are taking courses and TAing?	'Tom', 'Danita'	['question_type_global', 'question_three_hop_statement']
what courses have masters students taking them?	'G102', 'U303'	['question_type_global', 'question_two_hop_statement']
which students passed the defense?	'Danita'	['question_type_global', 'question_single_statement']
Which courses are offered this semester?	'G102', 'G301', 'G310', 'U304', 'U303'	['question_type_global', 'question_single_statement']
[Tom] did not pass the qualifiers
What students are enrolled in [G102]?	'Tom', 'Britney', 'Cyndi', 'Danita'	['question_type_local']
[Andy] is a student in [G102]
[Zenaida] and [Loyd] are TAs for [G102]
What are the 2 unit courses?	'G102'	['question_type_global', 'question_single_statement']
Which courses are TAed by masters students?	'G102', 'G301'	['question_type_global', 'question_two_hop_statement']
who are the masters students?	'Britney', 'Cyndi', 'Andrew', 'Michael', 'Andy', 'Alejandra', 'Loyd'	['question_type_global', 'question_single_statement']
[Zenaida] has passed the qualifying exam
[she] is taking [G102]
What students have funding?	'Tom', 'Zenaida'	['question_type_global', 'question_single_statement']
[Tom] successfully defended their thesis
[he] failed the qualifiers
Which students are both taking a course and a TA?	'Tom', 'Britney', 'Danita', 'Andy', 'Zenaida'	['question_type_global', 'question_two_hop_statement']
Which courses are TAed by [Tom]?	'G102'	['question_type_local']
what [masters] courses have no masters students taking them?	'G301'	['question_type_global', 'question_three_hop_statement']
create a [distinguished] [professor] named [Charlott]
[she] is affiliated with the [english] department
Which courses are TAed by phd students that passed their qualifier exam or have some funding?	'G102'	['question_type_global', 'question_four_hop_statement']
[Danita] passed the qualifiers
[this student] is in their [fifth year]
[Charlott] is on [Zenaida]'s committee
Which courses have phd student TAs that are in the fifth year?	'G301'	['question_type_global', 'question_three_hop_statement']
Which courses are TAed by phd students?	'G102', 'G301'	['question_type_global', 'question_two_hop_statement']
What courses is [Andrew] TAing?	'G102'	['question_type_local']
Which courses have masters student TAs?	'G102', 'G301'	['question_type_global', 'question_two_hop_statement']
there is a [third year] PhD student named [Vivienne]
[this professor] advises [Danita]
[Charlott] conducts research in [applications of machine learning]
What is [that professor] working on?	'applications of machine learning'	['question_type_local']
Which courses have phd student TAs that passed the qualifying exam?	'G102', 'G301'	['question_type_global', 'question_three_hop_statement']
[Michael] is enrolled in [G102]
Who is taking [G102]?	'Tom', 'Britney', 'Cyndi', 'Danita', 'Michael', 'Andy', 'Zenaida'	['question_type_local']
which courses have no phd students enrolled?	'G301', 'G310', 'U304', 'U303'	['question_type_global', 'question_two_hop_statement']
which students passed the defense?	'Tom', 'Danita'	['question_type_global', 'question_single_statement']
Which are some [masters] courses that masters students take?	'G102', 'U303'	['question_type_global', 'question_three_hop_statement']
Which courses have masters student TAs?	'G102', 'G301'	['question_type_global', 'question_two_hop_statement']
Which courses have funded phd student TAs that passed the qualifying exam?	'G102'	['question_type_global', 'question_four_hop_statement']
Create a new course called [G8001]
[Vivienne] and [Stephine] are TAing [G8001]
[G8001] has 4 units
[Charlott] is the instructor for [this course]
Who is teaching [that course]?	'Charlott'	['question_type_local']
Create a new [phd] level course called [U601]
[Cyndi] is TAing [U601]
What students are going to TA [this course]?	'Cyndi'	['question_type_local']
What [distinguished] professors advise students who passed their thesis qualifiers?	'Charlott'	['question_type_global', 'question_three_hop_statement']
Which courses did [Michael] enroll in?	'G102'	['question_type_local']
What courses are taught by professors in the [english] department?	'G8001'	['question_type_global', 'question_two_hop_statement']
which students passed the proposal exam?	'Tom', 'Danita', 'Stephine', 'Zenaida'	['question_type_global', 'question_single_statement']
there is a new masters student named [Milagros]
What are the courses TAed by [Cyndi]?	'U601'	['question_type_local']
Which students's advisors are conducting research in [applications of machine learning]	'Danita'	['question_type_global', 'question_two_hop_statement']
there is a PhD student named [Lucy]
[Lucy] successfully defended their thesis
[this student] is a [first year] student
Which department is [this student] in?	"I don't know"	['question_type_local']
Which courses are TAed by masters students?	'G102', 'G301', 'U601'	['question_type_global', 'question_two_hop_statement']
which students passed the qualifying exam?	'Danita', 'Zenaida'	['question_type_global', 'question_single_statement']
[Hanna] is a PhD student
[Hanna] is funded
Which are some [phd] courses that no masters student is taking?	'U601'	['question_type_global', 'question_three_hop_statement']
[that student] is attending [G102]
What courses are taught by those in the [english] department?	'G8001'	['question_type_global', 'question_two_hop_statement']
who are the phd students?	'Tom', 'Danita', 'Stephine', 'Zenaida', 'Vivienne', 'Lucy', 'Hanna'	['question_type_global', 'question_single_statement']
who are the students?	'Tom', 'Britney', 'Cyndi', 'Danita', 'Andrew', 'Michael', 'Stephine', 'Andy', 'Zenaida', 'Alejandra', 'Loyd', 'Vivienne', 'Milagros', 'Lucy', 'Hanna'	['question_type_global', 'question_single_statement']
Which courses are TAed by phd students that passed their qualifier exam and have some funding?	'G102'	['question_type_global', 'question_four_hop_statement']
[that person] is a TA for [this course]
What students are going to TA [that course]?	'Tom', 'Britney', 'Andrew', 'Michael', 'Zenaida', 'Loyd', 'Hanna'	['question_type_local']
Who are the [sixth year] students?	'Tom'	['question_type_global', 'question_single_statement']
What courses are taught by professors in the [english] department?	'G8001'	['question_type_global', 'question_two_hop_statement']
Which courses have phd student TAs?	'G102', 'G301', 'G8001'	['question_type_global', 'question_two_hop_statement']
which [phd] courses have no phd students enrolled?	'U601'	['question_type_global', 'question_three_hop_statement']
[Loyd] and [Michael] are taking [G102]
What students are enrolled in [G102]?	'Tom', 'Britney', 'Cyndi', 'Danita', 'Michael', 'Andy', 'Zenaida', 'Loyd', 'Hanna'	['question_type_local']
Which courses have masters student TAs?	'G102', 'G301', 'U601'	['question_type_global', 'question_two_hop_statement']
[Danita] is now a [sixth year] student
What are the courses TAed by [Andy]?	'G301'	['question_type_local']
Which courses are TAed by [he]?	'G102'	['question_type_local']
Which professors advise students who passed their proposal?	'Charlott'	['question_type_global', 'question_two_hop_statement']
Create a new course called [G610]
[G610] has 4 units
[Milagros] and [Alejandra] are TAing [G610]
What courses is [Michael] taking?	'G102'	['question_type_local']
What [distinguished] professors advise students who defended successfully?	'Charlott'	['question_type_global', 'question_three_hop_statement']
which students passed the qualifying exam?	'Danita', 'Zenaida'	['question_type_global', 'question_single_statement']
Which professors advise students who passed their defense?	'Charlott'	['question_type_global', 'question_two_hop_statement']
who are the phd students?	'Tom', 'Danita', 'Stephine', 'Zenaida', 'Vivienne', 'Lucy', 'Hanna'	['question_type_global', 'question_single_statement']
which [phd] courses have no phd students enrolled?	'U601'	['question_type_global', 'question_three_hop_statement']
which students passed the proposal exam?	'Tom', 'Danita', 'Stephine', 'Zenaida'	['question_type_global', 'question_single_statement']
which students passed the defense?	'Tom', 'Danita', 'Lucy'	['question_type_global', 'question_single_statement']
Which phd students are both taking a course and a TA?	'Tom', 'Danita', 'Zenaida', 'Hanna'	['question_type_global', 'question_three_hop_statement']
what [masters] courses have masters students taking them?	'G102', 'U303'	['question_type_global', 'question_three_hop_statement']
What are the courses that [Britney] is enrolled in?	'G102', 'U303'	['question_type_local']
Which are some courses that no phd student is taking?	'G301', 'G310', 'U304', 'U303', 'G8001', 'U601', 'G610'	['question_type_global', 'question_two_hop_statement']
What students have funding?	'Tom', 'Zenaida', 'Hanna'	['question_type_global', 'question_single_statement']
What students are taking courses and TAing?	'Tom', 'Britney', 'Cyndi', 'Danita', 'Michael', 'Andy', 'Zenaida', 'Loyd', 'Hanna'	['question_type_global', 'question_two_hop_statement']
who are the students?	'Tom', 'Britney', 'Cyndi', 'Danita', 'Andrew', 'Michael', 'Stephine', 'Andy', 'Zenaida', 'Alejandra', 'Loyd', 'Vivienne', 'Milagros', 'Lucy', 'Hanna'	['question_type_global', 'question_single_statement']
[Stephine] failed their thesis defense
[Stephine] is in [third year]
which students passed the defense?	'Tom', 'Danita', 'Lucy'	['question_type_global', 'question_single_statement']
What are the courses TAed by [Loyd]?	'G102'	['question_type_local']
which [masters] courses have no phd students enrolled?	'G301', 'U303'	['question_type_global', 'question_three_hop_statement']
[U601] is 12 units
who are the professors?	'Charlott'	['question_type_global', 'question_single_statement']
Who are the professors in the [english] department?	'Charlott'	['question_type_global', 'question_two_hop_statement']
who are the phd students?	'Tom', 'Danita', 'Stephine', 'Zenaida', 'Vivienne', 'Lucy', 'Hanna'	['question_type_global', 'question_single_statement']
Which [distinguished] professors advise students who passed their qualifying exam?	'Charlott'	['question_type_global', 'question_three_hop_statement']
Which courses did [Michael] enroll in?	'G102'	['question_type_local']
Which professors have an [distinguished] status?	'Charlott'	['question_type_global', 'question_single_statement']
Which courses are TAed by phd students that passed their qualifier exam and have some funding?	'G102'	['question_type_global', 'question_four_hop_statement']
Which courses did [Andy] enroll in?	'G102'	['question_type_local']
Which students are advised by professors working on [applications of machine learning]?	'Danita'	['question_type_global', 'question_two_hop_statement']
[this person] failed the qualifiers
Which courses have phd student TAs?	'G102', 'G301', 'G8001'	['question_type_global', 'question_two_hop_statement']
Who are the professors working on [applications of machine learning]?	'Charlott'	['question_type_global', 'question_single_statement']
[U601] is set up as a full semester course
[Lucy] and [Danita] are attending [U601]
Which courses have phd student TAs that passed the qualifying exam?	'G102', 'G301'	['question_type_global', 'question_three_hop_statement']
which students passed the proposal exam?	'Tom', 'Danita', 'Stephine', 'Zenaida'	['question_type_global', 'question_single_statement']
Who is part of the [english] department	'Charlott'	['question_type_global', 'question_single_statement']
Create a new course called [U7000]
[that course] is a [undergraduate] course
What courses is [Hanna] TAing?	'G102'	['question_type_local']
who are the masters students?	'Britney', 'Cyndi', 'Andrew', 'Michael', 'Andy', 'Alejandra', 'Loyd', 'Milagros'	['question_type_global', 'question_single_statement']
Which phd students are both taking a course and a TA?	'Tom', 'Danita', 'Zenaida', 'Hanna'	['question_type_global', 'question_three_hop_statement']
The TA for [that course] is [Lucy]
Who is taking the U303 course	'Britney', 'Cyndi'	['question_type_global', 'question_single_statement']
Which courses are TAed by phd students?	'G102', 'G301', 'G8001', 'U7000'	['question_type_global', 'question_two_hop_statement']
What courses is [Cyndi] TAing?	'U601'	['question_type_local']
who are the phd students?	'Tom', 'Danita', 'Stephine', 'Zenaida', 'Vivienne', 'Lucy', 'Hanna'	['question_type_global', 'question_single_statement']
What phd students are taking courses and TAing?	'Tom', 'Danita', 'Zenaida', 'Lucy', 'Hanna'	['question_type_global', 'question_three_hop_statement']
[she] is funded
what courses have masters students taking them?	'G102', 'U303'	['question_type_global', 'question_two_hop_statement']
[Tom] is taking [G102]
Which courses did [Tom] enroll in?	'G102'	['question_type_local']
who are the professors?	'Charlott'	['question_type_global', 'question_single_statement']
[this student] has [Charlott] on the committee
Which courses have phd student TAs that are in the first year?	'U7000'	['question_type_global', 'question_three_hop_statement']
What 4 unit courses are taught by professors in the [english] department?	'G8001'	['question_type_global', 'question_three_hop_statement']
What [full_semester_course] are taught by those in the [english] department?	'G8001'	['question_type_global', 'question_three_hop_statement']
what courses have phd students taking them?	'G102', 'U601'	['question_type_global', 'question_two_hop_statement']
What are the courses that [Lucy] is enrolled in?	'U601'	['question_type_local']
[that professor] advises [Hanna]
What is [that professor] research area?	'applications of machine learning'	['question_type_local']
Who are the professors working on [applications of machine learning]?	'Charlott'	['question_type_global', 'question_single_statement']
Which courses have phd student TAs that are in the first year?	'U7000'	['question_type_global', 'question_three_hop_statement']
Create a new course called [G601]
[Milagros] is attending [G601]
What students are enrolled in [that course]?	'Milagros'	['question_type_local']
Which courses have phd student TAs that passed the qualifying exam?	'G102', 'G301'	['question_type_global', 'question_three_hop_statement']
what courses have phd students taking them?	'G102', 'U601'	['question_type_global', 'question_two_hop_statement']
who are the masters students?	'Britney', 'Cyndi', 'Andrew', 'Michael', 'Andy', 'Alejandra', 'Loyd', 'Milagros'	['question_type_global', 'question_single_statement']
what [masters] courses have no masters students taking them?	'G301'	['question_type_global', 'question_three_hop_statement']
What courses is [that person] taking?	'G601'	['question_type_local']
What students are taking courses and TAing?	'Tom', 'Britney', 'Cyndi', 'Danita', 'Michael', 'Andy', 'Zenaida', 'Loyd', 'Milagros', 'Lucy', 'Hanna'	['question_type_global', 'question_two_hop_statement']
[that course] is a full semester course
[G601] is a [phd] level course
[Milagros] and [Cyndi] are both enrolled in [that class]
Which courses have masters student TAs?	'G102', 'G301', 'U601', 'G610'	['question_type_global', 'question_two_hop_statement']
What [distinguished] professors advise students who passed their thesis proposal?	'Charlott'	['question_type_global', 'question_three_hop_statement']
What students are taking G102	'Tom', 'Britney', 'Cyndi', 'Danita', 'Michael', 'Andy', 'Zenaida', 'Loyd', 'Hanna'	['question_type_global', 'question_single_statement']
Which are some courses that no masters student is taking?	'G301', 'G310', 'U304', 'G8001', 'U601', 'G610', 'U7000'	['question_type_global', 'question_two_hop_statement']
Which courses are TAed by [Milagros]?	'G610'	['question_type_local']
What courses are taught by those in the [english] department?	'G8001'	['question_type_global', 'question_two_hop_statement']
Which professors advise students who passed their qualifying exam?	'Charlott'	['question_type_global', 'question_two_hop_statement']
Which people are in the [english] department?	'Charlott'	['question_type_global', 'question_single_statement']
What are the courses that [Cyndi] is enrolled in?	'G102', 'U303', 'G601'	['question_type_local']
What 2 unit courses are taught by professors in the [english] department?	'G8001'	['question_type_global', 'question_three_hop_statement']
What are the courses TAed by [Loyd]?	'G102'	['question_type_local']
What courses is [Cyndi] TAing?	'U601'	['question_type_local']
Which courses are TAed by phd students that passed their qualifier exam and have some funding?	'G102'	['question_type_global', 'question_four_hop_statement']
Create a new [phd] course called [U203]
Which [distinguished] professors advise students who passed their defense?	'Charlott'	['question_type_global', 'question_three_hop_statement']
which students passed the defense?	'Tom', 'Danita', 'Lucy'	['question_type_global', 'question_single_statement']
Who is TAing [G102]?	'Tom', 'Britney', 'Andrew', 'Michael', 'Zenaida', 'Loyd', 'Hanna'	['question_type_local']
Who are the [distinguished] professors?	'Charlott'	['question_type_global', 'question_single_statement']
What students are taking courses and TAing?	'Tom', 'Britney', 'Cyndi', 'Danita', 'Michael', 'Andy', 'Zenaida', 'Loyd', 'Milagros', 'Lucy', 'Hanna'	['question_type_global', 'question_two_hop_statement']
Which courses are offered this semester?	'G102', 'G301', 'G310', 'U304', 'U303', 'G8001', 'U601', 'G610', 'U7000', 'G601', 'U203'	['question_type_global', 'question_single_statement']
which courses have no masters students enrolled?	'G301', 'G310', 'U304', 'G8001', 'U601', 'G610', 'U7000', 'U203'	['question_type_global', 'question_two_hop_statement']
What are all the courses?	'G102', 'G301', 'G310', 'U304', 'U303', 'G8001', 'U601', 'G610', 'U7000', 'G601', 'U203'	['question_type_global', 'question_single_statement']
Which courses did [that student] enroll in?	'G102', 'U303', 'G601'	['question_type_local']
Which courses have phd student TAs that either have some funding or passed the qualifying exam?	'G102', 'G301', 'U7000'	['question_type_global', 'question_four_hop_statement']
Which courses are 4 unit courses?	'U303', 'G8001', 'G610'	['question_type_global', 'question_single_statement']
[U203] is a 12 unit course
Who is teaching [G8001]?	'Charlott'	['question_type_local']
who are the professors?	'Charlott'	['question_type_global', 'question_single_statement']
who are the phd students?	'Tom', 'Danita', 'Stephine', 'Zenaida', 'Vivienne', 'Lucy', 'Hanna'	['question_type_global', 'question_single_statement']
Which students are advised by professors working on [applications of machine learning]?	'Danita', 'Hanna'	['question_type_global', 'question_two_hop_statement']
Which [distinguished] professors advise students who passed their proposal?	'Charlott'	['question_type_global', 'question_three_hop_statement']
What professors advise students who defended successfully?	'Charlott'	['question_type_global', 'question_two_hop_statement']
There is a course called [U202]
[U202] is set up as a full semester course
What are the 4 unit courses?	'U303', 'G8001', 'G610'	['question_type_global', 'question_single_statement']
[that course] is 2 units
Who is enrolled in [U303]?	'Britney', 'Cyndi'	['question_type_local']
Which professors are conducting research in [applications of machine learning]	'Charlott'	['question_type_global', 'question_single_statement']
Which courses are 2 unit courses?	'G102', 'U202'	['question_type_global', 'question_single_statement']
Which professors advise students who passed their qualifying exam?	'Charlott'	['question_type_global', 'question_two_hop_statement']
Which students are advised by professors working on [applications of machine learning]?	'Danita', 'Hanna'	['question_type_global', 'question_two_hop_statement']
which students passed the defense?	'Tom', 'Danita', 'Lucy'	['question_type_global', 'question_single_statement']
[that class] is a [phd] level course
Which masters courses are TAed by phd students?	'G102', 'G301'	['question_type_global', 'question_three_hop_statement']
Which are some courses that masters students take?	'G102', 'U303', 'G601'	['question_type_global', 'question_two_hop_statement']
What are the courses that [Cyndi] is enrolled in?	'G102', 'U303', 'G601'	['question_type_local']
Which courses are TAed by phd students that passed their qualifier exam and have some funding?	'G102'	['question_type_global', 'question_four_hop_statement']
What courses are taught by those in the [english] department?	'G8001'	['question_type_global', 'question_two_hop_statement']
who are the masters students?	'Britney', 'Cyndi', 'Andrew', 'Michael', 'Andy', 'Alejandra', 'Loyd', 'Milagros'	['question_type_global', 'question_single_statement']
which courses have no masters students enrolled?	'G301', 'G310', 'U304', 'G8001', 'U601', 'G610', 'U7000', 'U203', 'U202'	['question_type_global', 'question_two_hop_statement']
Create a new course called [G305]
[G305] is set up as a full semester course
