There is a [masters] level course called [U202]
[that class] is full semester
which courses have no masters students enrolled?	'U202'	['question_type_global', 'question_two_hop_statement']
What are the [masters] courses?	'U202'	['question_type_global', 'question_single_statement']
there is a [fifth year] PhD student named [Zenaida]
[this person] has passed the thesis proposal exam
[this person] has passed the qualifying exam
[that student] passed thesis defense
there is a new [third year] PhD student named [Tereasa]
There is a [undergraduate] level [mini course] called [G305]
[this course] is a course in the [english] department
What are all the courses?	'U202', 'G305'	['question_type_global', 'question_single_statement']
[Tereasa] and [Zenaida] are both taking [that course]
Which courses are [mini course]	'G305'	['question_type_global', 'question_single_statement']
[Genevive] is a masters student
What courses is [Zenaida] taking?	'G305'	['question_type_local']
who are the masters students?	'Genevive'	['question_type_global', 'question_single_statement']
[Tereasa] is funded
[Tereasa] passed thesis defense
Who is taking the G305 course	'Zenaida', 'Tereasa'	['question_type_global', 'question_single_statement']
Create a new course called [U201]
[this course] is offered in the [english] department
there is a PhD student named [Stephine]
[Stephine] has failed the qualifying exam
[Tereasa] has passed the qualifying exam
There is a [phd] [mini course] called [U9000]
[this student] passed thesis proposal
[U201] is a full semester course
[Genevive] is taking [U201]
Which masters students taking the U201 course	'Genevive'	['question_type_global', 'question_two_hop_statement']
which students passed the qualifying exam?	'Zenaida', 'Tereasa'	['question_type_global', 'question_single_statement']
[Racquel] is a [teaching] [professor]
[this professor] advises [Zenaida]
the affiliation of [that professor] is [english]
Which department is [that professor] in?	'english'	['question_type_local']
What are the [fifth year] phd students	'Zenaida'	['question_type_global', 'question_single_statement']
[Lucio] is a [assistant] [professor]
[he] is in [Eaton Building]
[Lucio]'s department is [english]
which students passed the proposal exam?	'Zenaida', 'Tereasa'	['question_type_global', 'question_single_statement']
[this professor] advises [Tereasa] and [Stephine]
[Stephine] passed the qualifiers
[that student] has passed the thesis defense
[she] is funded
Which [assistant] professors advise students who passed their qualifying exam?	'Lucio'	['question_type_global', 'question_three_hop_statement']
What offices do people in the [english] department have?	'Eaton Building'	['question_type_global', 'question_two_hop_statement']
who are the professors?	'Racquel', 'Lucio'	['question_type_global', 'question_single_statement']
[that student] has [Racquel] on the committee
[this student] is a [third year] student
Which professors advise students who passed their defense?	'Racquel', 'Lucio'	['question_type_global', 'question_two_hop_statement']
Which students are taking [G305]?	'Zenaida', 'Tereasa'	['question_type_local']
Which courses are offered this semester?	'U202', 'G305', 'U201', 'U9000'	['question_type_global', 'question_single_statement']
Which [teaching] professors advise students who passed their qualifying exam?	'Racquel'	['question_type_global', 'question_three_hop_statement']
Who are the [assistant] professors?	'Lucio'	['question_type_global', 'question_single_statement']
[Lucio] is on [Zenaida]'s committee
there is a masters student named [Peggy]
there is a PhD student named [Cecil]
What phd students are taking G305	'Zenaida', 'Tereasa'	['question_type_global', 'question_two_hop_statement']
[second year] is a [Cyndi] PhD student
[she] has passed the qualifying exam
[Cyndi] is now a [third year] student
[that person] currently has funding
Which are some courses that phd students take?	'G305'	['question_type_global', 'question_two_hop_statement']
Create a new [undergraduate] level course called [U8001]
[Racquel] teaches [this course]
[Cecil] is taking [U8001]
Who has an office in [Eaton Building]	'Lucio'	['question_type_global', 'question_two_hop_statement']
who are the phd students?	'Zenaida', 'Tereasa', 'Stephine', 'Cecil', 'Cyndi'	['question_type_global', 'question_single_statement']
What are the [full_semester_course]?	'U202', 'U201'	['question_type_global', 'question_single_statement']
[that course] is a full semester course
The TA for [that class] is [Peggy]
[this course] is under the [asian studies] department
Which department is [this course] in?	'asian studies'	['question_type_local']
[Racquel] advises [Cecil]
[she]'s office is [Denison Building]
Which department is [U201] in?	'english'	['question_type_local']
What masters students are taking U201	'Genevive'	['question_type_global', 'question_two_hop_statement']
What departments are people in [Denison Building] affiliated with?	'english'	['question_type_global', 'question_two_hop_statement']
there is a [first year] PhD student named [Hiram]
Which phd students does [this professor] advise?	'Zenaida', 'Cecil'	['question_type_local']
who are the professors?	'Racquel', 'Lucio'	['question_type_global', 'question_single_statement']
[Eun] is a PhD student
[she] is current in [fourth year]
[Eun] has passed the thesis proposal exam
What professors are on [Zenaida]'s committee	'Lucio'	['question_type_local']
[Racquel] is on [Tereasa]'s committee
which students passed the proposal exam?	'Zenaida', 'Tereasa', 'Eun'	['question_type_global', 'question_single_statement']
who are the students?	'Zenaida', 'Tereasa', 'Genevive', 'Stephine', 'Peggy', 'Cecil', 'Cyndi', 'Hiram', 'Eun'	['question_type_global', 'question_single_statement']
which students passed the qualifying exam?	'Zenaida', 'Tereasa', 'Stephine', 'Cyndi'	['question_type_global', 'question_single_statement']
What professors are in the [english] department?	'Racquel', 'Lucio'	['question_type_global', 'question_two_hop_statement']
[this professor]'s research interest is [applications of machine learning]
What are all the courses?	'U202', 'G305', 'U201', 'U9000', 'U8001'	['question_type_global', 'question_single_statement']
Who are the professors working on [applications of machine learning]?	'Racquel'	['question_type_global', 'question_single_statement']
[this professor] advises [Hiram] and [Eun]
Who is [Tereasa]'s advisor?	'Lucio'	['question_type_local']
which students passed the defense?	'Zenaida', 'Tereasa', 'Stephine'	['question_type_global', 'question_single_statement']
Where are the offices of those in the [english] department?	'Denison Building', 'Eaton Building'	['question_type_global', 'question_two_hop_statement']
[Kristeen] is a masters student
Which students are in a course that is instructed by their advisor?	'Cecil'	['question_type_global', 'question_three_hop_statement']
[Eun] has passed the thesis defense
[Lucio] is on [Eun]'s committee
Who is [Stephine]'s advisor?	'Lucio'	['question_type_local']
who are the masters students?	'Genevive', 'Peggy', 'Kristeen'	['question_type_global', 'question_single_statement']
Which courses are TAed by masters students?	'U8001'	['question_type_global', 'question_two_hop_statement']
Which courses are offered this semester in the asian studies department?	'U8001'	['question_type_global', 'question_two_hop_statement']
What [assistant] professors advise students who passed their thesis proposal?	'Lucio'	['question_type_global', 'question_three_hop_statement']
[she] is funded
What is [Racquel]'s department?	'english'	['question_type_local']
Which [assistant] professors advise students who passed their proposal?	'Lucio'	['question_type_global', 'question_three_hop_statement']
What are all the courses?	'U202', 'G305', 'U201', 'U9000', 'U8001'	['question_type_global', 'question_single_statement']
What professors advise students who passed their thesis proposal?	'Racquel', 'Lucio'	['question_type_global', 'question_two_hop_statement']
[this professor] conducts research in [applications of machine learning]
[Cyndi] is [this professor]'s student
there is a [professor] named [Gia]
[that professor] research interest is in [computational biology]
which courses have some masters students enrolled?	'U201'	['question_type_global', 'question_two_hop_statement']
Which courses in the asian studies department are TAed by masters students?	'U8001'	['question_type_global', 'question_three_hop_statement']
who are the phd students?	'Zenaida', 'Tereasa', 'Stephine', 'Cecil', 'Cyndi', 'Hiram', 'Eun'	['question_type_global', 'question_single_statement']
[that person] is an [assistant] professor
What are the courses that [Genevive] is enrolled in?	'U201'	['question_type_local']
Which courses are in the [asian studies] department?	'U8001'	['question_type_global', 'question_single_statement']
Which students are in their [first year]	'Hiram'	['question_type_global', 'question_single_statement']
Which courses are part of the [asian studies] department	'U8001'	['question_type_global', 'question_single_statement']
which students passed the defense?	'Zenaida', 'Tereasa', 'Stephine', 'Eun'	['question_type_global', 'question_single_statement']
Which phd students taking the U8001 course	'Cecil'	['question_type_global', 'question_two_hop_statement']
[Britney] is a masters student
[that professor]'s office is [Eaton Building]
Which students's advisors are conducting research in [applications of machine learning]	'Zenaida', 'Tereasa', 'Stephine', 'Cecil', 'Cyndi', 'Hiram', 'Eun'	['question_type_global', 'question_two_hop_statement']
What are the [full_semester_course]?	'U202', 'U201', 'U8001'	['question_type_global', 'question_single_statement']
there is a masters student named [Loyd]
Which professors advise students who passed their proposal?	'Racquel', 'Lucio'	['question_type_global', 'question_two_hop_statement']
Which courses have masters student TAs?	'U8001'	['question_type_global', 'question_two_hop_statement']
[Angelita] is a [assistant] [professor]
Which phd students have [Racquel] on their committee	'Tereasa', 'Stephine'	['question_type_local']
What [phd] courses are taught by those in the [english] department?	'U8001'	['question_type_global', 'question_three_hop_statement']
What 12 unit courses are taught by those in the [english] department?	'U8001'	['question_type_global', 'question_three_hop_statement']
Which students are in a course that is instructed by their advisor?	'Cecil'	['question_type_global', 'question_three_hop_statement']
[Hiram] has failed the thesis proposal exam
who are the professors?	'Racquel', 'Lucio', 'Gia', 'Angelita'	['question_type_global', 'question_single_statement']
What department is [U8001] offered in?	'asian studies'	['question_type_local']
Which [first year] students are advised by professors working on [applications of machine learning]?	'Hiram'	['question_type_global', 'question_three_hop_statement']
[Stephine] has [she] on the committee
What professors are on [Zenaida]'s committee	'Lucio'	['question_type_local']
Which professors are teaching [full_semester_course]?	'Racquel'	['question_type_global', 'question_two_hop_statement']
Which [teaching] professors advise students who passed their qualifying exam?	'Racquel'	['question_type_global', 'question_three_hop_statement']
Which courses did [Tereasa] enroll in?	'G305'	['question_type_local']
Which students are in a course that is instructed by their advisor?	'Cecil'	['question_type_global', 'question_three_hop_statement']
[Genevive] and [Cecil] are both enrolled in [U8001]
[he] is TAing [U8001]
Who is TAing [U8001]?	'Peggy', 'Cecil'	['question_type_local']
Which courses are [phd] level courses?	'U9000'	['question_type_global', 'question_single_statement']
which students passed the proposal exam?	'Zenaida', 'Tereasa', 'Eun'	['question_type_global', 'question_single_statement']
What are all the courses in the asian studies department?	'U8001'	['question_type_global', 'question_two_hop_statement']
Which are some courses that phd students take?	'G305', 'U8001'	['question_type_global', 'question_two_hop_statement']
Which courses are TAed by [Cecil]?	'U8001'	['question_type_local']
who are the students?	'Zenaida', 'Tereasa', 'Genevive', 'Stephine', 'Peggy', 'Cecil', 'Cyndi', 'Hiram', 'Eun', 'Kristeen', 'Britney', 'Loyd'	['question_type_global', 'question_single_statement']
who are the professors?	'Racquel', 'Lucio', 'Gia', 'Angelita'	['question_type_global', 'question_single_statement']
Who are the professors working on [applications of machine learning]?	'Racquel', 'Lucio'	['question_type_global', 'question_single_statement']
Which phd students are both taking a course and a TA?	'Cecil'	['question_type_global', 'question_three_hop_statement']
Which department is [U8001] part of?	'asian studies'	['question_type_local']
Which courses are offered this semester in the asian studies department?	'U8001'	['question_type_global', 'question_two_hop_statement']
Who is [Stephine]'s advisor?	'Lucio'	['question_type_local']
Which professors advise students who passed their defense?	'Racquel', 'Lucio'	['question_type_global', 'question_two_hop_statement']
[Angelita] teaches [U201]
[this course] is a [phd] level course
Who is teaching [U201]?	'Angelita'	['question_type_local']
what courses have no phd students taking them?	'U202', 'U201', 'U9000'	['question_type_global', 'question_two_hop_statement']
[Gia] and [Angelita] are on [Eun]'s committee
[Eun] is in [fifth year]
What are the [first year] phd students	'Hiram'	['question_type_global', 'question_single_statement']
Which students are both taking a course and a TA?	'Cecil'	['question_type_global', 'question_two_hop_statement']
What are all the courses?	'U202', 'G305', 'U201', 'U9000', 'U8001'	['question_type_global', 'question_single_statement']
[this professor] conducts research in [computational biology]
What is [this professor] working on?	'computational biology'	['question_type_local']
which courses have no phd students enrolled?	'U202', 'U201', 'U9000'	['question_type_global', 'question_two_hop_statement']
Which courses are offered this semester?	'U202', 'G305', 'U201', 'U9000', 'U8001'	['question_type_global', 'question_single_statement']
[Angelita]'s office is [Gamow Building]
[she] is affiliated with the [asian studies] department
Who are [Lucio]'s students?	'Tereasa', 'Stephine', 'Cyndi'	['question_type_local']
Which professors are conducting research in [applications of machine learning]	'Racquel', 'Lucio'	['question_type_global', 'question_single_statement']
What professors advise students who passed their thesis qualifiers?	'Racquel', 'Lucio'	['question_type_global', 'question_two_hop_statement']
What 4 unit courses are taught by professors in the [asian studies] department?	'U201'	['question_type_global', 'question_three_hop_statement']
Which professors are teaching [undergraduate] courses?	'Racquel'	['question_type_global', 'question_two_hop_statement']
What professors advise students who defended successfully?	'Racquel', 'Lucio'	['question_type_global', 'question_two_hop_statement']
Who has [this professor] on their phd committee?	'Stephine', 'Eun'	['question_type_local']
which courses have no phd students enrolled?	'U202', 'U201', 'U9000'	['question_type_global', 'question_two_hop_statement']
What [full_semester_course] are taught by professors in the [asian studies] department?	'U201'	['question_type_global', 'question_three_hop_statement']
[Eun] is in [sixth year]
which students passed the qualifying exam?	'Zenaida', 'Tereasa', 'Stephine', 'Cyndi'	['question_type_global', 'question_single_statement']
Which courses are [mini course]	'G305', 'U9000'	['question_type_global', 'question_single_statement']
What office is [Lucio] in?	'Eaton Building'	['question_type_local']
which courses have no masters students enrolled?	'U202', 'G305', 'U9000'	['question_type_global', 'question_two_hop_statement']
What 4 unit courses are taught by professors in the [asian studies] department?	'U201'	['question_type_global', 'question_three_hop_statement']
Who is teaching [full_semester_course]?	'Racquel', 'Angelita'	['question_type_global', 'question_two_hop_statement']
Where are the offices of those in the [english] department?	'Denison Building', 'Eaton Building'	['question_type_global', 'question_two_hop_statement']
What students have funding?	'Tereasa', 'Stephine', 'Cyndi', 'Eun'	['question_type_global', 'question_single_statement']
Which professors have offices in Denison Building	'Racquel'	['question_type_global', 'question_two_hop_statement']
who are the students?	'Zenaida', 'Tereasa', 'Genevive', 'Stephine', 'Peggy', 'Cecil', 'Cyndi', 'Hiram', 'Eun', 'Kristeen', 'Britney', 'Loyd'	['question_type_global', 'question_single_statement']
[Eun] passed the qualifiers
What [assistant] professors advise students who passed their thesis proposal?	'Lucio'	['question_type_global', 'question_three_hop_statement']
Which are some courses that masters students take?	'U201', 'U8001'	['question_type_global', 'question_two_hop_statement']
What students are taking a course taught by their advisor?	'Cecil'	['question_type_global', 'question_three_hop_statement']
Which people are in the [english] department?	'Racquel', 'Lucio'	['question_type_global', 'question_single_statement']
[Tereasa] is a TA for [G305]
Which students are TAing [G305]?	'Tereasa'	['question_type_local']
Who are the professors working on [computational biology]?	'Gia', 'Angelita'	['question_type_global', 'question_single_statement']
What professors advise students who defended successfully?	'Racquel', 'Lucio'	['question_type_global', 'question_two_hop_statement']
[Gia] is on [that student]'s committee
Which courses are TAed by masters students?	'U8001'	['question_type_global', 'question_two_hop_statement']
What 8 unit courses are taught by professors in the [english] department?	'U8001'	['question_type_global', 'question_three_hop_statement']
Who has an office in [Eaton Building]	'Lucio', 'Gia'	['question_type_global', 'question_two_hop_statement']
What students have funding?	'Tereasa', 'Stephine', 'Cyndi', 'Eun'	['question_type_global', 'question_single_statement']
Which undergraduate courses have phd student TAs?	'G305', 'U8001'	['question_type_global', 'question_three_hop_statement']
who are the masters students?	'Genevive', 'Peggy', 'Kristeen', 'Britney', 'Loyd'	['question_type_global', 'question_single_statement']
which students passed the proposal exam?	'Zenaida', 'Tereasa', 'Eun'	['question_type_global', 'question_single_statement']
the affiliation of [Gia] is [animal science]
Which professors have an [teaching] status?	'Racquel'	['question_type_global', 'question_single_statement']
Who has an office in [Gamow Building]	'Angelita'	['question_type_global', 'question_two_hop_statement']
What is [Angelita]'s research focus?	'computational biology'	['question_type_local']
which courses have no masters students enrolled?	'U202', 'G305', 'U9000'	['question_type_global', 'question_two_hop_statement']
[Kristeen] and [Stephine] are taking [U201]
[U201] is a 8 unit course
[that course] is TAed by [Loyd] and [Zenaida]
Who is TAing [U201]?	'Zenaida', 'Loyd'	['question_type_local']
Which courses are TAed by masters students?	'U201', 'U8001'	['question_type_global', 'question_two_hop_statement']
Which courses are TAed by [Loyd]?	'U201'	['question_type_local']
Which courses are offered this semester in the english department?	'G305', 'U201'	['question_type_global', 'question_two_hop_statement']
Which courses did [Genevive] enroll in?	'U201', 'U8001'	['question_type_local']
Which courses are [undergraduate] level courses?	'G305', 'U8001'	['question_type_global', 'question_single_statement']
Which [fifth year] students's advisors are conducting research in [applications of machine learning]	'Zenaida'	['question_type_global', 'question_three_hop_statement']
Who are the [teaching] professors?	'Racquel'	['question_type_global', 'question_single_statement']
[Gia] and [Angelita] are on [Zenaida]'s committee
What professors are on [Zenaida]'s committee	'Lucio', 'Gia', 'Angelita'	['question_type_local']
Which courses are TAed by masters students?	'U201', 'U8001'	['question_type_global', 'question_two_hop_statement']
which students passed the qualifying exam?	'Zenaida', 'Tereasa', 'Stephine', 'Cyndi', 'Eun'	['question_type_global', 'question_single_statement']
Which undergraduate courses are TAed by phd students?	'G305', 'U8001'	['question_type_global', 'question_three_hop_statement']
What are the [mini course]?	'G305', 'U9000'	['question_type_global', 'question_single_statement']
Create a new [phd] level [full_semester_course] called [G101]
[Gia] teaches [that course]
[physics] offers [this course]
Who is enrolled in [U8001]?	'Genevive', 'Cecil'	['question_type_local']
What students have funding?	'Tereasa', 'Stephine', 'Cyndi', 'Eun'	['question_type_global', 'question_single_statement']
Who are the professors in the [animal science] department?	'Gia'	['question_type_global', 'question_two_hop_statement']
What professors are on [Stephine]'s committee	'Racquel', 'Angelita'	['question_type_local']
What [teaching] professors advise students who defended successfully?	'Racquel'	['question_type_global', 'question_three_hop_statement']
What [assistant] professors advise students who defended successfully?	'Lucio'	['question_type_global', 'question_three_hop_statement']
The TA for [G101] is [Britney]
Which students are funded?	'Tereasa', 'Stephine', 'Cyndi', 'Eun'	['question_type_global', 'question_single_statement']
which courses have no masters students enrolled?	'U202', 'G305', 'U9000', 'G101'	['question_type_global', 'question_two_hop_statement']
[Zenaida] is enrolled in [U201]
What students are going to TA [this course]?	'Zenaida', 'Loyd'	['question_type_local']
What professors advise students who defended successfully?	'Racquel', 'Lucio'	['question_type_global', 'question_two_hop_statement']
Who are the [assistant] professors?	'Lucio', 'Gia', 'Angelita'	['question_type_global', 'question_single_statement']
Which courses are TAed by phd students?	'G305', 'U201', 'U8001'	['question_type_global', 'question_two_hop_statement']
what [phd] courses have no masters students taking them?	'U9000', 'G101'	['question_type_global', 'question_three_hop_statement']
What phd students are taking courses and TAing?	'Zenaida', 'Tereasa', 'Cecil'	['question_type_global', 'question_three_hop_statement']
What courses is [Peggy] TAing?	'U8001'	['question_type_local']
Where are the offices of those in the [asian studies] department?	'Gamow Building'	['question_type_global', 'question_two_hop_statement']
Which professors are conducting research in [applications of machine learning]	'Racquel', 'Lucio'	['question_type_global', 'question_single_statement']
What [undergraduate] courses are taught by those in the [asian studies] department?	'U201'	['question_type_global', 'question_three_hop_statement']
what courses have no phd students taking them?	'U202', 'U9000', 'G101'	['question_type_global', 'question_two_hop_statement']
Which courses in the asian studies department have phd TAs?	'U8001'	['question_type_global', 'question_three_hop_statement']
which courses have no masters students enrolled?	'U202', 'G305', 'U9000', 'G101'	['question_type_global', 'question_two_hop_statement']
What professors are in the [english] department?	'Racquel', 'Lucio'	['question_type_global', 'question_two_hop_statement']
which [undergraduate] courses have no masters students enrolled?	'G305'	['question_type_global', 'question_three_hop_statement']
Which department is [G305] part of?	'english'	['question_type_local']
who are the phd students?	'Zenaida', 'Tereasa', 'Stephine', 'Cecil', 'Cyndi', 'Hiram', 'Eun'	['question_type_global', 'question_single_statement']
Which phd students taking the U201 course	'Zenaida', 'Stephine'	['question_type_global', 'question_two_hop_statement']
What courses is [that student] taking?	'G305', 'U201'	['question_type_local']
which [phd] courses have some masters students enrolled?	'U201'	['question_type_global', 'question_three_hop_statement']
Which undergraduate courses have phd student TAs?	'G305', 'U8001'	['question_type_global', 'question_three_hop_statement']
[Cecil] has [Angelita] on the committee
What department is [G101] offered in?	'physics'	['question_type_local']
Which courses are part of the [english] department	'G305', 'U201'	['question_type_global', 'question_single_statement']
Who is in the [asian studies] department	'Angelita'	['question_type_global', 'question_single_statement']
There is a course called [U304]
The TA for [U304] is [Hiram]
Which courses are TAed by masters students?	'U201', 'U8001', 'G101'	['question_type_global', 'question_two_hop_statement']
[Lucio] is on [he]'s committee
[that student] passed thesis defense
What phd students are taking G305	'Zenaida', 'Tereasa'	['question_type_global', 'question_two_hop_statement']
What professors are on [Cecil]'s committee	'Angelita'	['question_type_local']
Which courses in the physics department have masters TAs?	'G101'	['question_type_global', 'question_three_hop_statement']
which students passed the qualifying exam?	'Zenaida', 'Tereasa', 'Stephine', 'Cyndi', 'Eun'	['question_type_global', 'question_single_statement']
which courses have no phd students enrolled?	'U202', 'U9000', 'G101', 'U304'	['question_type_global', 'question_two_hop_statement']
Which professors are teaching [phd] courses?	'Gia', 'Angelita'	['question_type_global', 'question_two_hop_statement']
Who is [Tereasa]'s advisor?	'Lucio'	['question_type_local']
What [undergraduate] courses are taught by professors in the [animal science] department?	'G101'	['question_type_global', 'question_three_hop_statement']
What [mini course] are taught by professors in the [animal science] department?	'G101'	['question_type_global', 'question_three_hop_statement']
Create a new [phd] level 4 unit course called [U101]
[he] has passed the qualifying exam
What 4 unit courses are taught by those in the [asian studies] department?	'U201'	['question_type_global', 'question_three_hop_statement']
Who has an office in [Eaton Building]	'Lucio', 'Gia'	['question_type_global', 'question_two_hop_statement']
who are the students?	'Zenaida', 'Tereasa', 'Genevive', 'Stephine', 'Peggy', 'Cecil', 'Cyndi', 'Hiram', 'Eun', 'Kristeen', 'Britney', 'Loyd'	['question_type_global', 'question_single_statement']
