[first year] is a [Francoise] PhD student
[Francoise] passed thesis proposal
there is a masters student named [Willis]
[Francoise] has failed thesis defense
[Francoise] is now a [second year] student
there is a new masters student named [John]
there is a [assistant] [professor] named [Hanna]
create a [teaching] [professor] named [Vivienne]
[Francoise] is [Vivienne]'s student
Which phd students does [this professor] advise?	'Francoise'	['question_type_local']
Create a new course called [U7000]
[this course] is part of the [mechanical engineering] department
[that course] is taught by [Vivienne]
[Francoise] and [Willis] are both taking [U7000]
Which students are taking [U7000]?	'Francoise', 'Willis'	['question_type_local']
there is a new PhD student named [Cecil]
[Hanna] and [Vivienne] are on [Cecil]'s committee
Who is on [Cecil]'s committee?	'Hanna', 'Vivienne'	['question_type_local']
who are the professors?	'Hanna', 'Vivienne'	['question_type_global', 'question_single_statement']
[Zenaida] is a [professor]
[Zenaida] research interest is in [optical physics]
[this person] is an [teaching] professor
[fifth year] is a [Will] PhD student
[Hanna] is on [Will]'s committee
[that student] has passed the thesis proposal exam
Which courses are offered this semester?	'U7000'	['question_type_global', 'question_single_statement']
[this professor] went on sabbatical
[that professor] research interest is in [optical physics]
[Francoise] successfully defended their thesis
Who advises [Francoise]?	'Vivienne'	['question_type_local']
there is a new masters student named [Gia]
There is a [undergraduate] course called [G304]
there is a new masters student named [Angelita]
Which courses did [Willis] enroll in?	'U7000'	['question_type_local']
What [teaching] professors advise students who passed their thesis proposal?	'Vivienne'	['question_type_global', 'question_three_hop_statement']
[Francoise] has [Zenaida] on the committee
Who is on [he]'s committee?	'Zenaida'	['question_type_local']
What are the [undergraduate] courses?	'G304'	['question_type_global', 'question_single_statement']
what courses have no masters students taking them?	'G304'	['question_type_global', 'question_two_hop_statement']
[Will] has [Zenaida] and [Vivienne] on the committee
Who is on [Will]'s committee?	'Hanna', 'Vivienne', 'Zenaida'	['question_type_local']
Which professors have an [teaching] status?	'Vivienne', 'Zenaida'	['question_type_global', 'question_single_statement']
Who are the professors working on [optical physics]?	'Hanna', 'Zenaida'	['question_type_global', 'question_single_statement']
there is a [professor] named [Bob]
[Vivienne] is on sabbatical
Which are some [undergraduate] courses that no masters student is taking?	'G304'	['question_type_global', 'question_three_hop_statement']
[she] advises [Cecil] and [Will]
[Vivienne]'s research interest is [supervised learning]
Who are [she]'s students?	'Francoise', 'Cecil', 'Will'	['question_type_local']
What are all the courses?	'U7000', 'G304'	['question_type_global', 'question_single_statement']
Who is on sabbatical?	'Hanna', 'Vivienne'	['question_type_global', 'question_single_statement']
who are the phd students?	'Francoise', 'Cecil', 'Will'	['question_type_global', 'question_single_statement']
[Bob] research interest is in [evolutionary biology]
[he] is an [teaching] professor
[that professor] is on sabbatical
which courses have some masters students enrolled?	'U7000'	['question_type_global', 'question_two_hop_statement']
Which courses are offered this semester in the mechanical engineering department?	'U7000'	['question_type_global', 'question_two_hop_statement']
Who has [Vivienne] on their phd committee?	'Cecil', 'Will'	['question_type_local']
what [undergraduate] courses have no masters students taking them?	'G304'	['question_type_global', 'question_three_hop_statement']
Who are [Vivienne]'s students?	'Francoise', 'Cecil', 'Will'	['question_type_local']
Which professors are on sabbatical and are also advising students?	'Vivienne'	['question_type_global', 'question_two_hop_statement']
Which are some [undergraduate] courses that no masters student is taking?	'G304'	['question_type_global', 'question_three_hop_statement']
Create a new [phd] level 2 unit course called [U203]
[Gia] and [Will] are attending [U203]
[U203] will be a mini course
[Vivienne] is now an [assistant] professor
[Angelita] and [Francoise] are both taking [that course]
[U203] is a course in the [mechanical engineering] department
Who advises [Will]?	'Vivienne'	['question_type_local']
What professors advise students who passed their thesis proposal?	'Vivienne'	['question_type_global', 'question_two_hop_statement']
which students passed the defense?	'Francoise'	['question_type_global', 'question_single_statement']
Which courses are [phd] level courses?	'U203'	['question_type_global', 'question_single_statement']
[Cecil] and [Gia] are both taking [this course]
The TA for [U203] is [she]
who are the professors?	'Hanna', 'Vivienne', 'Zenaida', 'Bob'	['question_type_global', 'question_single_statement']
Create a new course called [U304]
[U304] is full semester
[that course] is taught by [Zenaida]
Which courses are [mini course]	'U203'	['question_type_global', 'question_single_statement']
Which students are in a course that is instructed by their advisor?	'Francoise'	['question_type_global', 'question_three_hop_statement']
[that class] is offered in the [mechanical engineering] department
[Francoise] and [Angelita] are TAs for [U304]
[U304] is a [masters] course
There is a [phd] level course called [U610]
[U610] is offered in the [mechanical engineering] department
[that course] will be a full semester course
[Hanna] teaches [U610]
What department is [this course] offered in?	'mechanical engineering'	['question_type_local']
Who are the [fifth year] students?	'Will'	['question_type_global', 'question_single_statement']
[Gia] is taking [U304]
Which are some courses that masters students take?	'U7000', 'U203', 'U304'	['question_type_global', 'question_two_hop_statement']
What are the courses that [Will] is enrolled in?	'U203'	['question_type_local']
Which courses are [full_semester_course]	'U304', 'U610'	['question_type_global', 'question_single_statement']
Who is on sabbatical?	'Hanna', 'Vivienne', 'Bob'	['question_type_global', 'question_single_statement']
Who is teaching [full_semester_course]?	'Hanna', 'Zenaida'	['question_type_global', 'question_two_hop_statement']
Which courses did [Gia] enroll in?	'U203', 'U304'	['question_type_local']
[Will] is a TA for [U304]
Which department is [that class] in?	'mechanical engineering'	['question_type_local']
who are the students?	'Francoise', 'Willis', 'John', 'Cecil', 'Will', 'Gia', 'Angelita'	['question_type_global', 'question_single_statement']
Which are some [masters] courses that no phd student is taking?	'U304'	['question_type_global', 'question_three_hop_statement']
Who is supposed to be teaching [full_semester_course] and is currently on sabbatical?	'Hanna'	['question_type_global', 'question_three_hop_statement']
[U7000] is TAed by [John] and [Willis]
What are the courses TAed by [Will]?	'U304'	['question_type_local']
Who is taking the U304 course	'Gia'	['question_type_global', 'question_single_statement']
There is a [phd] 12 unit class called [G101]
What courses is [this person] taking?	'U7000'	['question_type_local']
Which students are in a course that is instructed by their advisor?	'Francoise'	['question_type_global', 'question_three_hop_statement']
what courses have masters students taking them?	'U7000', 'U203', 'U304'	['question_type_global', 'question_two_hop_statement']
Which professors advise students who passed their proposal?	'Vivienne'	['question_type_global', 'question_two_hop_statement']
What students are taking courses and TAing?	'Francoise', 'Willis', 'Will', 'Gia', 'Angelita'	['question_type_global', 'question_two_hop_statement']
Which courses are offered this semester?	'U7000', 'G304', 'U203', 'U304', 'U610', 'G101'	['question_type_global', 'question_single_statement']
Which courses are TAed by [he]?	'U7000'	['question_type_local']
What department is [U7000] offered in?	'mechanical engineering'	['question_type_local']
who are the students?	'Francoise', 'Willis', 'John', 'Cecil', 'Will', 'Gia', 'Angelita'	['question_type_global', 'question_single_statement']
which courses have some phd students enrolled?	'U7000', 'U203'	['question_type_global', 'question_two_hop_statement']
Which courses are offered this semester in the mechanical engineering department?	'U7000', 'U203', 'U304', 'U610'	['question_type_global', 'question_two_hop_statement']
What are the [mechanical engineering] courses?	'U7000', 'U203', 'U304', 'U610'	['question_type_global', 'question_single_statement']
Which courses are [masters] level courses?	'U304'	['question_type_global', 'question_single_statement']
What students currently have their advisor on sabbatical	'Francoise', 'Cecil', 'Will'	['question_type_global', 'question_two_hop_statement']
Which professors advise students who passed their defense?	'Vivienne'	['question_type_global', 'question_two_hop_statement']
Who is taking the U7000 course	'Francoise', 'Willis'	['question_type_global', 'question_single_statement']
What professors that currently advise students are going on sabbatical?	'Vivienne'	['question_type_global', 'question_two_hop_statement']
[Cecil] and [Will] are both enrolled in [G101]
Who does [Vivienne] advise?	'Francoise', 'Cecil', 'Will'	['question_type_local']
who are the phd students?	'Francoise', 'Cecil', 'Will'	['question_type_global', 'question_single_statement']
[Cecil] has passed the thesis proposal exam
What professors are on [Cecil]'s committee	'Hanna', 'Vivienne'	['question_type_local']
Which are some courses that no phd student is taking?	'G304', 'U304', 'U610'	['question_type_global', 'question_two_hop_statement']
which courses have no masters students enrolled?	'G304', 'U610', 'G101'	['question_type_global', 'question_two_hop_statement']
What is [Zenaida] working on?	'optical physics'	['question_type_local']
Who is supposed to be teaching [full_semester_course] and is currently on sabbatical?	'Hanna'	['question_type_global', 'question_three_hop_statement']
Which courses are offered this semester in the mechanical engineering department?	'U7000', 'U203', 'U304', 'U610'	['question_type_global', 'question_two_hop_statement']
What courses is [Vivienne] teaching?	'U7000'	['question_type_local']
Which courses are TAed by masters students?	'U7000', 'U203', 'U304'	['question_type_global', 'question_two_hop_statement']
What department is [U304] offered in?	'mechanical engineering'	['question_type_local']
Which courses have masters student TAs?	'U7000', 'U203', 'U304'	['question_type_global', 'question_two_hop_statement']
What students are going to TA [U7000]?	'Willis', 'John'	['question_type_local']
[Cecil] passed the qualifiers
which students passed the proposal exam?	'Francoise', 'Cecil', 'Will'	['question_type_global', 'question_single_statement']
Which professors advise students who passed their defense?	'Vivienne'	['question_type_global', 'question_two_hop_statement']
[Bob] is on [Francoise]'s committee
Who is [Cecil]'s advisor?	'Vivienne'	['question_type_local']
who are the masters students?	'Willis', 'John', 'Gia', 'Angelita'	['question_type_global', 'question_single_statement']
[Hanna] is on [that student]'s committee
Who is [he]'s advisor?	'Vivienne'	['question_type_local']
Which courses are TAed by masters students?	'U7000', 'U203', 'U304'	['question_type_global', 'question_two_hop_statement']
who are the students?	'Francoise', 'Willis', 'John', 'Cecil', 'Will', 'Gia', 'Angelita'	['question_type_global', 'question_single_statement']
Who is on [this student]'s committee?	'Hanna', 'Zenaida', 'Bob'	['question_type_local']
There is a course called [G202]
Which department is [U203] part of?	'mechanical engineering'	['question_type_local']
What [assistant] professors advise students who defended successfully?	'Vivienne'	['question_type_global', 'question_three_hop_statement']
Create a new [phd] level 8 unit course called [U301]
[U301] is a course in the [math] department
[Cecil] is TAing [U301]
What courses is [John] TAing?	'U7000'	['question_type_local']
[this course] is a full semester course
who are the masters students?	'Willis', 'John', 'Gia', 'Angelita'	['question_type_global', 'question_single_statement']
Which courses are [undergraduate] level courses?	'G304'	['question_type_global', 'question_single_statement']
[Zenaida] and [Bob] are on [this person]'s committee
What courses is [Cecil] taking?	'U203', 'G101'	['question_type_local']
What students are taking a course taught by their advisor?	'Francoise'	['question_type_global', 'question_three_hop_statement']
[he] has been promoted to [assistant] professor
who are the phd students?	'Francoise', 'Cecil', 'Will'	['question_type_global', 'question_single_statement']
[Will] is enrolled in [U301]
[Bob] teaches [U301]
What department is [U304] offered in?	'mechanical engineering'	['question_type_local']
What masters students are taking U7000	'Willis'	['question_type_global', 'question_two_hop_statement']
There is a [masters] course called [G204]
Which courses have phd student TAs that are in the second year?	'U304'	['question_type_global', 'question_three_hop_statement']
Which phd students have [Bob] on their committee	'Francoise', 'Cecil'	['question_type_local']
which students passed the qualifying exam?	'Cecil'	['question_type_global', 'question_single_statement']
Which courses are TAed by masters students?	'U7000', 'U203', 'U304'	['question_type_global', 'question_two_hop_statement']
Which professors advise students who passed their defense?	'Vivienne'	['question_type_global', 'question_two_hop_statement']
Which students are advised by professors working on [supervised learning]?	'Francoise', 'Cecil', 'Will'	['question_type_global', 'question_two_hop_statement']
Who is [Cecil]'s advisor?	'Vivienne'	['question_type_local']
What are the [mechanical engineering] courses?	'U7000', 'U203', 'U304', 'U610'	['question_type_global', 'question_single_statement']
Which professors are conducting research in [supervised learning]	'Vivienne'	['question_type_global', 'question_single_statement']
Which phd students have [that person] on their committee	'Francoise', 'Cecil'	['question_type_local']
Which department is [U203] part of?	'mechanical engineering'	['question_type_local']
What professors advise students who passed their thesis proposal?	'Vivienne'	['question_type_global', 'question_two_hop_statement']
which students passed the proposal exam?	'Francoise', 'Cecil', 'Will'	['question_type_global', 'question_single_statement']
[G204] is a course in the [psychology] department
[that class] is a full semester course
What professors are on [Will]'s committee	'Hanna', 'Vivienne', 'Zenaida'	['question_type_local']
What phd students are taking G101	'Cecil', 'Will'	['question_type_global', 'question_two_hop_statement']
which courses have some phd students enrolled?	'U7000', 'U203', 'G101', 'U301'	['question_type_global', 'question_two_hop_statement']
What courses is [Bob] teaching?	'U301'	['question_type_local']
Which professors are currently on sabbatical?	'Hanna', 'Vivienne', 'Bob'	['question_type_global', 'question_single_statement']
Which courses have phd student TAs that passed the qualifying exam?	'U301'	['question_type_global', 'question_three_hop_statement']
Which are some [phd] courses that no masters student is taking?	'U610', 'G101', 'U301'	['question_type_global', 'question_three_hop_statement']
[John] and [Cecil] are attending [G204]
Which courses are TAed by [Willis]?	'U7000'	['question_type_local']
Which masters students taking the G204 course	'John'	['question_type_global', 'question_two_hop_statement']
Which courses are TAed by masters students?	'U7000', 'U203', 'U304'	['question_type_global', 'question_two_hop_statement']
who are the students?	'Francoise', 'Willis', 'John', 'Cecil', 'Will', 'Gia', 'Angelita'	['question_type_global', 'question_single_statement']
Which are some courses that phd students take?	'U7000', 'U203', 'G101', 'U301', 'G204'	['question_type_global', 'question_two_hop_statement']
[Bob] is on [Will]'s committee
What professors advise students who defended successfully?	'Vivienne'	['question_type_global', 'question_two_hop_statement']
[that student] is in [sixth year]
What is [Zenaida] research area?	'optical physics'	['question_type_local']
Which professors are on sabbatical and are also advising students?	'Vivienne'	['question_type_global', 'question_two_hop_statement']
Which courses are TAed by phd students?	'U304', 'U301'	['question_type_global', 'question_two_hop_statement']
Which masters students taking the G204 course	'John'	['question_type_global', 'question_two_hop_statement']
What phd students are taking U301	'Will'	['question_type_global', 'question_two_hop_statement']
What professors are on [Cecil]'s committee	'Hanna', 'Vivienne', 'Zenaida', 'Bob'	['question_type_local']
What professors advise students who passed their thesis proposal?	'Vivienne'	['question_type_global', 'question_two_hop_statement']
which students passed the defense?	'Francoise'	['question_type_global', 'question_single_statement']
Who is teaching [U304]?	'Zenaida'	['question_type_local']
Which courses are TAed by phd students?	'U304', 'U301'	['question_type_global', 'question_two_hop_statement']
Who is taking the U7000 course	'Francoise', 'Willis'	['question_type_global', 'question_single_statement']
[that student] did not pass the qualifiers
Who is on [that person]'s committee?	'Hanna', 'Vivienne', 'Zenaida', 'Bob'	['question_type_local']
Which phd courses are TAed by phd students?	'U301'	['question_type_global', 'question_three_hop_statement']
[Francoise] is taking [U304]
Which are some courses that no masters student is taking?	'G304', 'U610', 'G101', 'G202', 'U301'	['question_type_global', 'question_two_hop_statement']
What courses is [Zenaida] teaching?	'U304'	['question_type_local']
Which courses are offered this semester?	'U7000', 'G304', 'U203', 'U304', 'U610', 'G101', 'G202', 'U301', 'G204'	['question_type_global', 'question_single_statement']
There is a course called [G601]
Which department is [G204] part of?	'psychology'	['question_type_local']
Who is supposed to be teaching [full_semester_course] and is currently on sabbatical?	'Hanna', 'Bob'	['question_type_global', 'question_three_hop_statement']
[this course] is a [masters] level course
which [masters] courses have some masters students enrolled?	'U304', 'G204'	['question_type_global', 'question_three_hop_statement']
What are the courses TAed by [Cecil]?	'U301'	['question_type_local']
Which professors are on sabbatical and are also advising students?	'Vivienne'	['question_type_global', 'question_two_hop_statement']
Which courses are TAed by phd students that passed their qualifier exam?	'U301'	['question_type_global', 'question_three_hop_statement']
Which masters courses have phd student TAs?	'U304'	['question_type_global', 'question_three_hop_statement']
Which professors have an [assistant] status?	'Hanna', 'Vivienne', 'Bob'	['question_type_global', 'question_single_statement']
[Willis] and [Gia] are both taking [U304]
What department is [U304] offered in?	'mechanical engineering'	['question_type_local']
What are the courses that [she] is enrolled in?	'U203', 'U304'	['question_type_local']
Which courses have masters student TAs?	'U7000', 'U203', 'U304'	['question_type_global', 'question_two_hop_statement']
What courses is [he] TAing?	'U7000'	['question_type_local']
What are the courses that [Angelita] is enrolled in?	'U203'	['question_type_local']
Which professors are on sabbatical and are also advising students?	'Vivienne'	['question_type_global', 'question_two_hop_statement']
What students are taking U7000	'Francoise', 'Willis'	['question_type_global', 'question_single_statement']
[Francoise] has passed the qualifying exam
What are the [full_semester_course]?	'U304', 'U610', 'U301', 'G204'	['question_type_global', 'question_single_statement']
What is [Bob] research area?	'evolutionary biology'	['question_type_local']
What masters students are taking U203	'Gia', 'Angelita'	['question_type_global', 'question_two_hop_statement']
What are the courses TAed by [she]?	'U203'	['question_type_local']
what courses have masters students taking them?	'U7000', 'U203', 'U304', 'G204'	['question_type_global', 'question_two_hop_statement']
which [masters] courses have some masters students enrolled?	'U304', 'G204'	['question_type_global', 'question_three_hop_statement']
who are the professors?	'Hanna', 'Vivienne', 'Zenaida', 'Bob'	['question_type_global', 'question_single_statement']
which courses have no masters students enrolled?	'G304', 'U610', 'G101', 'G202', 'U301', 'G601'	['question_type_global', 'question_two_hop_statement']
Who is TAing [U301]?	'Cecil'	['question_type_local']
What professors advise students who passed their thesis proposal?	'Vivienne'	['question_type_global', 'question_two_hop_statement']
Which are some [masters] courses that no masters student is taking?	'G601'	['question_type_global', 'question_three_hop_statement']
What students are taking U301	'Will'	['question_type_global', 'question_single_statement']
What courses is [Zenaida] teaching?	'U304'	['question_type_local']
[Will] has failed thesis defense
which students passed the proposal exam?	'Francoise', 'Cecil', 'Will'	['question_type_global', 'question_single_statement']
Which courses in the mechanical engineering department are TAed by second year phd students?	'U304'	['question_type_global', 'question_three_hop_statement']
Which are some [phd] courses that no phd student is taking?	'U610'	['question_type_global', 'question_three_hop_statement']
Who is supposed to be teaching [phd] courses but is currently on sabbatical?	'Hanna', 'Bob'	['question_type_global', 'question_three_hop_statement']
Who are [Vivienne]'s students?	'Francoise', 'Cecil', 'Will'	['question_type_local']
which students passed the defense?	'Francoise'	['question_type_global', 'question_single_statement']
[Francoise] is now a [third year] student
Which department is [U610] part of?	'mechanical engineering'	['question_type_local']
Which masters courses are TAed by phd students?	'U304'	['question_type_global', 'question_three_hop_statement']
Which courses did [Will] enroll in?	'U203', 'G101', 'U301'	['question_type_local']
Which courses have masters student TAs?	'U7000', 'U203', 'U304'	['question_type_global', 'question_two_hop_statement']
who are the phd students?	'Francoise', 'Cecil', 'Will'	['question_type_global', 'question_single_statement']
Create a new course called [U202]
what courses have no masters students taking them?	'G304', 'U610', 'G101', 'G202', 'U301', 'G601', 'U202'	['question_type_global', 'question_two_hop_statement']
which courses have no masters students enrolled?	'G304', 'U610', 'G101', 'G202', 'U301', 'G601', 'U202'	['question_type_global', 'question_two_hop_statement']
Create a new [phd] level course called [U601]
[John] is enrolled in [U601]
[that class] is a course in the [psychology] department
What are the 8 unit courses?	'U301'	['question_type_global', 'question_single_statement']
Which students are in a course that is instructed by their advisor?	'Francoise'	['question_type_global', 'question_three_hop_statement']
For which phd students does [Hanna] serve on a committee?	'Francoise', 'Cecil', 'Will'	['question_type_local']
What [assistant] professors advise students who defended successfully?	'Vivienne'	['question_type_global', 'question_three_hop_statement']
What are the courses TAed by [this person]?	'U7000'	['question_type_local']
Who is on sabbatical?	'Hanna', 'Vivienne', 'Bob'	['question_type_global', 'question_single_statement']
what courses have no masters students taking them?	'G304', 'U610', 'G101', 'G202', 'U301', 'G601', 'U202'	['question_type_global', 'question_two_hop_statement']
There is a [undergraduate] level course called [U8001]
Which courses are TAed by phd students?	'U304', 'U301'	['question_type_global', 'question_two_hop_statement']
What are the 12 unit courses?	'G101'	['question_type_global', 'question_single_statement']
What [assistant] professors advise students who passed their thesis proposal?	'Vivienne'	['question_type_global', 'question_three_hop_statement']
What professors are on [Cecil]'s committee	'Hanna', 'Vivienne', 'Zenaida', 'Bob'	['question_type_local']
Which courses have masters student TAs?	'U7000', 'U203', 'U304'	['question_type_global', 'question_two_hop_statement']
Which department is [U601] in?	'psychology'	['question_type_local']
Which students are both taking a course and a TA?	'Francoise', 'Willis', 'John', 'Cecil', 'Will', 'Gia', 'Angelita'	['question_type_global', 'question_two_hop_statement']
[Zenaida] is now on sabbatical
What courses is [Zenaida] teaching?	'U304'	['question_type_local']
Which professors have an [teaching] status?	'Zenaida'	['question_type_global', 'question_single_statement']
Which are some [phd] courses that masters students take?	'U203', 'U601'	['question_type_global', 'question_three_hop_statement']
[Gia] and [Cecil] are attending [that course]
Which phd students are both taking a course and a TA?	'Francoise', 'Cecil', 'Will'	['question_type_global', 'question_three_hop_statement']
What are the 2 unit courses?	'U203'	['question_type_global', 'question_single_statement']
[Willis] and [Angelita] are both enrolled in [U301]
Which department is [U203] in?	'mechanical engineering'	['question_type_local']
What are the [masters] courses?	'U304', 'G204', 'G601'	['question_type_global', 'question_single_statement']
What courses is [Zenaida] teaching?	'U304'	['question_type_local']
Which courses have phd student TAs that passed the qualifying exam?	'U304', 'U301'	['question_type_global', 'question_three_hop_statement']
Who is teaching [masters] courses?	'Zenaida'	['question_type_global', 'question_two_hop_statement']
Which students are TAing [U203]?	'Gia'	['question_type_local']
Which courses are TAed by phd students in their sixth year?	'U304'	['question_type_global', 'question_three_hop_statement']
Which courses in the mechanical engineering department have phd TAs?	'U304'	['question_type_global', 'question_three_hop_statement']
What department is [U610] offered in?	'mechanical engineering'	['question_type_local']
who are the professors?	'Hanna', 'Vivienne', 'Zenaida', 'Bob'	['question_type_global', 'question_single_statement']
What professors are on [Francoise]'s committee	'Hanna', 'Zenaida', 'Bob'	['question_type_local']
Which courses are TAed by [John]?	'U7000'	['question_type_local']
What are all the courses?	'U7000', 'G304', 'U203', 'U304', 'U610', 'G101', 'G202', 'U301', 'G204', 'G601', 'U202', 'U601', 'U8001'	['question_type_global', 'question_single_statement']
which students passed the defense?	'Francoise'	['question_type_global', 'question_single_statement']
Which courses are [full_semester_course]	'U304', 'U610', 'U301', 'G204'	['question_type_global', 'question_single_statement']
Which courses are [mini course]	'U203'	['question_type_global', 'question_single_statement']
Which students are TAing [U301]?	'Cecil'	['question_type_local']
who are the students?	'Francoise', 'Willis', 'John', 'Cecil', 'Will', 'Gia', 'Angelita'	['question_type_global', 'question_single_statement']
Which are some [undergraduate] courses that phd students take?	'U8001'	['question_type_global', 'question_three_hop_statement']
Which courses are TAed by masters students?	'U7000', 'U203', 'U304'	['question_type_global', 'question_two_hop_statement']
Which courses are TAed by [he]?	'U7000'	['question_type_local']
Which courses are offered this semester in the math department?	'U301'	['question_type_global', 'question_two_hop_statement']
Which courses are TAed by phd students that passed their qualifier exam?	'U304', 'U301'	['question_type_global', 'question_three_hop_statement']
What phd students are taking U301	'Will'	['question_type_global', 'question_two_hop_statement']
who are the masters students?	'Willis', 'John', 'Gia', 'Angelita'	['question_type_global', 'question_single_statement']
Who is enrolled in [U301]?	'Willis', 'Will', 'Angelita'	['question_type_local']
Which courses have phd student TAs that passed the qualifying exam?	'U304', 'U301'	['question_type_global', 'question_three_hop_statement']
Which students's advisors are conducting research in [supervised learning]	'Francoise', 'Cecil', 'Will'	['question_type_global', 'question_two_hop_statement']
Which professors advise students who passed their proposal?	'Vivienne'	['question_type_global', 'question_two_hop_statement']
Which professors are on sabbatical and are also advising students?	'Vivienne'	['question_type_global', 'question_two_hop_statement']
There is a [masters] course called [G103]
What are the courses that [this student] is enrolled in?	'U203', 'U301'	['question_type_local']
Which students are both taking a course and a TA?	'Francoise', 'Willis', 'John', 'Cecil', 'Will', 'Gia', 'Angelita'	['question_type_global', 'question_two_hop_statement']
Which courses in the math department are TAed by phd students?	'U301'	['question_type_global', 'question_three_hop_statement']
what [undergraduate] courses have no phd students taking them?	'G304'	['question_type_global', 'question_three_hop_statement']
What are the courses that [that person] is enrolled in?	'U203', 'U301'	['question_type_local']
Which are some [masters] courses that no phd student is taking?	'G601', 'G103'	['question_type_global', 'question_three_hop_statement']
Which professors advise students who passed their proposal?	'Vivienne'	['question_type_global', 'question_two_hop_statement']
What are all the courses in the psychology department?	'G204', 'U601'	['question_type_global', 'question_two_hop_statement']
Create a new course called [G610]
Which students are both taking a course and a TA?	'Francoise', 'Willis', 'John', 'Cecil', 'Will', 'Gia', 'Angelita'	['question_type_global', 'question_two_hop_statement']
Which courses in the mechanical engineering department are TAed by phd students?	'U304'	['question_type_global', 'question_three_hop_statement']
[G610] is set up as a full semester course
Which professors currently on sabbatical are supposed to be teaching [phd] courses?	'Hanna', 'Bob'	['question_type_global', 'question_three_hop_statement']
Which courses are offered this semester?	'U7000', 'G304', 'U203', 'U304', 'U610', 'G101', 'G202', 'U301', 'G204', 'G601', 'U202', 'U601', 'U8001', 'G103', 'G610'	['question_type_global', 'question_single_statement']
Which are some [phd] courses that phd students take?	'U203', 'G101', 'U301'	['question_type_global', 'question_three_hop_statement']
Which professors advise students who passed their qualifying exam?	'Vivienne'	['question_type_global', 'question_two_hop_statement']
[Francoise] is taking [G610]
Which are some [undergraduate] courses that phd students take?	'U8001'	['question_type_global', 'question_three_hop_statement']
What students currently have their advisor on sabbatical	'Francoise', 'Cecil', 'Will'	['question_type_global', 'question_two_hop_statement']
what [masters] courses have phd students taking them?	'U304', 'G204'	['question_type_global', 'question_three_hop_statement']
Which phd students taking the U301 course	'Will'	['question_type_global', 'question_two_hop_statement']
What courses is [Bob] teaching?	'U301'	['question_type_local']
Which professors are teaching [full_semester_course]?	'Hanna', 'Zenaida', 'Bob'	['question_type_global', 'question_two_hop_statement']
[Gia] and [Willis] are both enrolled in [G610]
Who is taking [G610]?	'Francoise', 'Willis', 'Gia'	['question_type_local']
what courses have phd students taking them?	'U7000', 'U203', 'U304', 'G101', 'U301', 'G204', 'U8001', 'G610'	['question_type_global', 'question_two_hop_statement']
Which courses are TAed by [he]?	'U7000'	['question_type_local']
What are the 12 unit courses?	'G101'	['question_type_global', 'question_single_statement']
What students are going to TA [U304]?	'Francoise', 'Will', 'Angelita'	['question_type_local']
What courses is [she] TAing?	'U203'	['question_type_local']
Who advises [Will]?	'Vivienne'	['question_type_local']
Which professors have an [teaching] status?	'Zenaida'	['question_type_global', 'question_single_statement']
[G202] is under the [math] department
[that class] will be set up as a mini course
Which courses have phd student TAs that are in the third year?	'U304'	['question_type_global', 'question_three_hop_statement']
who are the professors?	'Hanna', 'Vivienne', 'Zenaida', 'Bob'	['question_type_global', 'question_single_statement']
