there is a new masters student named [Cyndi]
[that person] is affiliated with the [physics] department
there is a new [fifth year] PhD student named [Zenaida]
there is a new PhD student named [Angelita]
[Zenaida] has passed the qualifying exam
[Zenaida] failed thesis proposal
What students are in the [physics] department?	'Cyndi'	['question_type_global', 'question_two_hop_statement']
Create a new course called [G9000]
[this course] will be a mini course
What are all the courses?	'G9000'	['question_type_global', 'question_single_statement']
which students passed the qualifying exam?	'Zenaida'	['question_type_global', 'question_single_statement']
there is a PhD student named [Hiram]
[that class] is a [masters] course
[Angelita] is a TA for [that class]
[Hiram] and [Angelita] are taking [G9000]
Who is enrolled in [G9000]?	'Angelita', 'Hiram'	['question_type_local']
Which courses are offered this semester?	'G9000'	['question_type_global', 'question_single_statement']
[he] is in their [third year]
Which courses are TAed by phd students?	'G9000'	['question_type_global', 'question_two_hop_statement']
What are the [mini course]?	'G9000'	['question_type_global', 'question_single_statement']
[Hiram] passed thesis proposal
Which masters courses have phd student TAs?	'G9000'	['question_type_global', 'question_three_hop_statement']
Which students are in their [fifth year]	'Zenaida'	['question_type_global', 'question_single_statement']
there is a masters student named [William]
the affiliation of [William] is [english]
Who is taking [G9000]?	'Angelita', 'Hiram'	['question_type_local']
there is a new masters student named [Gia]
the affiliation of [she] is [applied physics]
Which students are taking [G9000]?	'Angelita', 'Hiram'	['question_type_local']
Who are the [fifth year] students?	'Zenaida'	['question_type_global', 'question_single_statement']
Which courses have phd student TAs?	'G9000'	['question_type_global', 'question_two_hop_statement']
who are the students?	'Cyndi', 'Zenaida', 'Angelita', 'Hiram', 'William', 'Gia'	['question_type_global', 'question_single_statement']
[Zenaida] passed thesis defense
Which are some courses that phd students take?	'G9000'	['question_type_global', 'question_two_hop_statement']
which students passed the defense?	'Zenaida'	['question_type_global', 'question_single_statement']
who are the phd students?	'Zenaida', 'Angelita', 'Hiram'	['question_type_global', 'question_single_statement']
who are the masters students?	'Cyndi', 'William', 'Gia'	['question_type_global', 'question_single_statement']
there is a masters student named [Alejandra]
the affiliation of [Alejandra] is [applied physics]
Which are some [masters] courses that phd students take?	'G9000'	['question_type_global', 'question_three_hop_statement']
[Lorilee] is a [professor]
[Angelita] is [that professor]'s student
[Lorilee] is now on sabbatical
What are the [masters] courses?	'G9000'	['question_type_global', 'question_single_statement']
[this professor]'s office is [Environmental Building]
what [masters] courses have phd students taking them?	'G9000'	['question_type_global', 'question_three_hop_statement']
there is a [professor] named [Lizeth]
[Lizeth] advises [Hiram]
[she] is now on sabbatical
[Hiram] has [Lorilee] on the committee
what courses have no masters students taking them?	'G9000'	['question_type_global', 'question_two_hop_statement']
what [masters] courses have no masters students taking them?	'G9000'	['question_type_global', 'question_three_hop_statement']
What professors are in Environmental Building	'Lorilee'	['question_type_global', 'question_two_hop_statement']
[this professor]'s research interest is [molecular biology]
What students are taking G9000	'Angelita', 'Hiram'	['question_type_global', 'question_single_statement']
Create a new course called [U101]
[this professor] advises [Zenaida]
Which phd students does [this professor] advise?	'Zenaida', 'Angelita'	['question_type_local']
there is a [professor] named [Igor]
[that student] is in [sixth year]
[this student] has [that professor] on the committee
[that student] has passed the thesis proposal exam
Which [sixth year] students are advised by professors working on [molecular biology]?	'Zenaida'	['question_type_global', 'question_three_hop_statement']
[Igor]'s research interest is [computational biology]
who are the masters students?	'Cyndi', 'William', 'Gia', 'Alejandra'	['question_type_global', 'question_single_statement']
Which are some [masters] courses that phd students take?	'G9000'	['question_type_global', 'question_three_hop_statement']
What phd students are taking G9000	'Angelita', 'Hiram'	['question_type_global', 'question_two_hop_statement']
Which phd students does [Lorilee] advise?	'Zenaida', 'Angelita'	['question_type_local']
Which courses are offered this semester?	'G9000', 'U101'	['question_type_global', 'question_single_statement']
What professors advise students who defended successfully?	'Lorilee'	['question_type_global', 'question_two_hop_statement']
Who are the students in the [physics] department	'Cyndi'	['question_type_global', 'question_two_hop_statement']
[Kristeen] is a [full] [professor]
[she]'s office is [Center Building]
Which phd students are both taking a course and a TA?	'Angelita'	['question_type_global', 'question_three_hop_statement']
Which professors have an [full] status?	'Kristeen'	['question_type_global', 'question_single_statement']
Which courses are TAed by phd students?	'G9000'	['question_type_global', 'question_two_hop_statement']
which students passed the defense?	'Zenaida'	['question_type_global', 'question_single_statement']
[she] research interest is in [molecular biology]
What is [this person]'s office?	'Center Building'	['question_type_local']
What is [this person] research area?	'molecular biology'	['question_type_local']
who are the students?	'Cyndi', 'Zenaida', 'Angelita', 'Hiram', 'William', 'Gia', 'Alejandra'	['question_type_global', 'question_single_statement']
Which phd students does [Lorilee] advise?	'Zenaida', 'Angelita'	['question_type_local']
Which courses are [masters] level courses?	'G9000'	['question_type_global', 'question_single_statement']
[Kristeen] is now on sabbatical
What students are enrolled in [G9000]?	'Angelita', 'Hiram'	['question_type_local']
who are the professors?	'Lorilee', 'Lizeth', 'Igor', 'Kristeen'	['question_type_global', 'question_single_statement']
Which students's advisors are conducting research in [molecular biology]	'Zenaida', 'Angelita'	['question_type_global', 'question_two_hop_statement']
[Gia] is TAing [U101]
Which phd students are both taking a course and a TA?	'Angelita'	['question_type_global', 'question_three_hop_statement']
What professors advise students who defended successfully?	'Lorilee'	['question_type_global', 'question_two_hop_statement']
Which professors have an [full] status?	'Kristeen'	['question_type_global', 'question_single_statement']
Who is advised by a professor who is now on a sabbatical?	'Zenaida', 'Angelita', 'Hiram'	['question_type_global', 'question_two_hop_statement']
What courses is [she] TAing?	'U101'	['question_type_local']
Who is in the [applied physics] department	'Gia', 'Alejandra'	['question_type_global', 'question_single_statement']
Which courses are TAed by phd students?	'G9000'	['question_type_global', 'question_two_hop_statement']
Which phd students taking the G9000 course	'Angelita', 'Hiram'	['question_type_global', 'question_two_hop_statement']
There is a course called [G303]
What are the courses TAed by [this person]?	'U101'	['question_type_local']
What students currently have their advisor on sabbatical	'Zenaida', 'Angelita', 'Hiram'	['question_type_global', 'question_two_hop_statement']
There is a [masters] level [full_semester_course] called [G7000]
[G7000] is taught by [Lorilee]
who are the professors?	'Lorilee', 'Lizeth', 'Igor', 'Kristeen'	['question_type_global', 'question_single_statement']
What professors that currently advise students are going on sabbatical?	'Lorilee', 'Lizeth'	['question_type_global', 'question_two_hop_statement']
What are the [masters] courses?	'G9000', 'G7000'	['question_type_global', 'question_single_statement']
What is [that professor]'s research focus?	'molecular biology'	['question_type_local']
Which professors advise students who passed their proposal?	'Lorilee', 'Lizeth'	['question_type_global', 'question_two_hop_statement']
Which professors are conducting research in [molecular biology]	'Lorilee', 'Kristeen'	['question_type_global', 'question_single_statement']
There is a course called [U301]
who are the phd students?	'Zenaida', 'Angelita', 'Hiram'	['question_type_global', 'question_single_statement']
which students passed the defense?	'Zenaida'	['question_type_global', 'question_single_statement']
Which professors advise students who passed their defense?	'Lorilee'	['question_type_global', 'question_two_hop_statement']
What is [Kristeen]'s office?	'Center Building'	['question_type_local']
What professors advise students who passed their thesis proposal?	'Lorilee', 'Lizeth'	['question_type_global', 'question_two_hop_statement']
Which courses have phd student TAs?	'G9000'	['question_type_global', 'question_two_hop_statement']
which students passed the qualifying exam?	'Zenaida'	['question_type_global', 'question_single_statement']
Which courses are TAed by masters students?	'U101'	['question_type_global', 'question_two_hop_statement']
Who has [Igor] on their phd committee?	'Zenaida'	['question_type_local']
Who are the students in the [english] department	'William'	['question_type_global', 'question_two_hop_statement']
which students passed the proposal exam?	'Zenaida', 'Hiram'	['question_type_global', 'question_single_statement']
What is [that professor]'s office?	'Environmental Building'	['question_type_local']
Which courses have masters student TAs?	'U101'	['question_type_global', 'question_two_hop_statement']
Who is on sabbatical?	'Lorilee', 'Lizeth', 'Kristeen'	['question_type_global', 'question_single_statement']
What professors advise students who defended successfully?	'Lorilee'	['question_type_global', 'question_two_hop_statement']
Create a new course called [G310]
[U301] is a [undergraduate] level course
Which are some [masters] courses that no phd student is taking?	'G7000'	['question_type_global', 'question_three_hop_statement']
Which courses are TAed by phd students?	'G9000'	['question_type_global', 'question_two_hop_statement']
[Igor] is the instructor for [U301]
What courses is [this professor] teaching?	'U301'	['question_type_local']
Which professors that are currently on sabbatical need to be teaching [full_semester_course]?	'Lorilee'	['question_type_global', 'question_three_hop_statement']
Who has an office in [Center Building]	'Kristeen'	['question_type_global', 'question_two_hop_statement']
Which are some courses that no phd student is taking?	'U101', 'G303', 'G7000', 'U301', 'G310'	['question_type_global', 'question_two_hop_statement']
who are the professors?	'Lorilee', 'Lizeth', 'Igor', 'Kristeen'	['question_type_global', 'question_single_statement']
Which courses have phd student TAs?	'G9000'	['question_type_global', 'question_two_hop_statement']
Who has [Lorilee] on their phd committee?	'Hiram'	['question_type_local']
Who is on sabbatical this semester?	'Lorilee', 'Lizeth', 'Kristeen'	['question_type_global', 'question_single_statement']
which students passed the defense?	'Zenaida'	['question_type_global', 'question_single_statement']
Which are some courses that phd students take?	'G9000'	['question_type_global', 'question_two_hop_statement']
[he] went on sabbatical
Which professors that are currently on sabbatical need to be teaching [full_semester_course]?	'Lorilee'	['question_type_global', 'question_three_hop_statement']
Which professors advise students who passed their defense?	'Lorilee'	['question_type_global', 'question_two_hop_statement']
Which professors currently on sabbatical are supposed to be teaching [undergraduate] courses?	'Igor'	['question_type_global', 'question_three_hop_statement']
Which phd students are both taking a course and a TA?	'Angelita'	['question_type_global', 'question_three_hop_statement']
what [masters] courses have no masters students taking them?	'G9000', 'G7000'	['question_type_global', 'question_three_hop_statement']
What students are taking courses and TAing?	'Angelita'	['question_type_global', 'question_two_hop_statement']
There is a course called [U304]
[Angelita] is attending [this course]
[U304] is a [phd] course
[that course] is TAed by [William] and [Hiram]
What students are going to TA [U304]?	'Hiram', 'William'	['question_type_local']
Which are some courses that phd students take?	'G9000', 'U304'	['question_type_global', 'question_two_hop_statement']
Create a new course called [G104]
[that class] is TAed by [Cyndi] and [Zenaida]
[G104] is a [masters] level course
[Hiram] is taking [G104]
what courses have no phd students taking them?	'U101', 'G303', 'G7000', 'U301', 'G310'	['question_type_global', 'question_two_hop_statement']
Who is teaching [masters] courses?	'Lorilee'	['question_type_global', 'question_two_hop_statement']
[G310] is a [undergraduate] level course
[Angelita] and [Cyndi] are attending [that class]
Which courses did [Cyndi] enroll in?	'G310'	['question_type_local']
Which courses are offered this semester?	'G9000', 'U101', 'G303', 'G7000', 'U301', 'G310', 'U304', 'G104'	['question_type_global', 'question_single_statement']
What courses is [Cyndi] taking?	'G310'	['question_type_local']
What professors advise students who defended successfully?	'Lorilee'	['question_type_global', 'question_two_hop_statement']
[Angelita] successfully defended their thesis
[Angelita] is a [first year] student
What are the [full_semester_course]?	'G7000'	['question_type_global', 'question_single_statement']
What professors advise students who passed their thesis proposal?	'Lorilee', 'Lizeth'	['question_type_global', 'question_two_hop_statement']
[Angelita] did not pass the qualifiers
[this person] has [Lizeth] on the committee
[Alejandra] is a TA for [G310]
Who is on [Zenaida]'s committee?	'Igor'	['question_type_local']
What professors are in Environmental Building	'Lorilee'	['question_type_global', 'question_two_hop_statement']
Create a new [undergraduate] level course called [U104]
[U104] is full semester
Create a new [undergraduate] course called [G305]
What is [Lorilee] research area?	'molecular biology'	['question_type_local']
[Zenaida] and [William] are taking [U104]
Who is taking [G9000]?	'Angelita', 'Hiram'	['question_type_local']
Which professors advise students who passed their proposal?	'Lorilee', 'Lizeth'	['question_type_global', 'question_two_hop_statement']
[Kristeen] is on [Zenaida]'s committee
Who advises [this student]?	'Lorilee'	['question_type_local']
What professors advise students who passed their thesis proposal?	'Lorilee', 'Lizeth'	['question_type_global', 'question_two_hop_statement']
What is [Kristeen] research area?	'molecular biology'	['question_type_local']
Which are some courses that masters students take?	'G310', 'U104'	['question_type_global', 'question_two_hop_statement']
Which courses are TAed by phd students?	'G9000', 'U304', 'G104'	['question_type_global', 'question_two_hop_statement']
which students passed the qualifying exam?	'Zenaida'	['question_type_global', 'question_single_statement']
[Lizeth] is on [Zenaida]'s committee
What courses is [this student] TAing?	'G104'	['question_type_local']
What professors are in Environmental Building	'Lorilee'	['question_type_global', 'question_two_hop_statement']
which students passed the defense?	'Zenaida', 'Angelita'	['question_type_global', 'question_single_statement']
[Hiram] has [Kristeen] on the committee
[this student] is now in [fourth year]
who are the masters students?	'Cyndi', 'William', 'Gia', 'Alejandra'	['question_type_global', 'question_single_statement']
Which courses have phd student TAs that passed the qualifying exam?	'G104'	['question_type_global', 'question_three_hop_statement']
[Lizeth] conducts research in [programming languages]
Who advises [Angelita]?	'Lorilee'	['question_type_local']
Who has [she] on their phd committee?	'Zenaida', 'Angelita'	['question_type_local']
Which phd students taking the U104 course	'Zenaida'	['question_type_global', 'question_two_hop_statement']
what courses have masters students taking them?	'G310', 'U104'	['question_type_global', 'question_two_hop_statement']
[Angelita] passed thesis proposal
[this student] has [Kristeen] and [Igor] on the committee
Who is on [Angelita]'s committee?	'Lizeth', 'Igor', 'Kristeen'	['question_type_local']
who are the phd students?	'Zenaida', 'Angelita', 'Hiram'	['question_type_global', 'question_single_statement']
What professors are on [Angelita]'s committee	'Lizeth', 'Igor', 'Kristeen'	['question_type_local']
Which are some [masters] courses that no masters student is taking?	'G9000', 'G7000', 'G104'	['question_type_global', 'question_three_hop_statement']
Who has an office in [Environmental Building]	'Lorilee'	['question_type_global', 'question_two_hop_statement']
Which professors advise students who passed their proposal?	'Lorilee', 'Lizeth'	['question_type_global', 'question_two_hop_statement']
what courses have no masters students taking them?	'G9000', 'U101', 'G303', 'G7000', 'U301', 'U304', 'G104', 'G305'	['question_type_global', 'question_two_hop_statement']
Which courses did [Cyndi] enroll in?	'G310'	['question_type_local']
Who is on sabbatical this semester?	'Lorilee', 'Lizeth', 'Igor', 'Kristeen'	['question_type_global', 'question_single_statement']
Which are some courses that phd students take?	'G9000', 'G310', 'U304', 'G104', 'U104'	['question_type_global', 'question_two_hop_statement']
Which courses are TAed by phd students in their first year?	'G9000'	['question_type_global', 'question_three_hop_statement']
which students passed the defense?	'Zenaida', 'Angelita'	['question_type_global', 'question_single_statement']
For which phd students does [Lizeth] serve on a committee?	'Zenaida', 'Angelita'	['question_type_local']
Which courses are TAed by masters students?	'U101', 'G310', 'U304', 'G104'	['question_type_global', 'question_two_hop_statement']
For which phd students does [he] serve on a committee?	'Zenaida', 'Angelita'	['question_type_local']
Which students are taking [G9000]?	'Angelita', 'Hiram'	['question_type_local']
which courses have some phd students enrolled?	'G9000', 'G310', 'U304', 'G104', 'U104'	['question_type_global', 'question_two_hop_statement']
What professors advise students who passed their thesis proposal?	'Lorilee', 'Lizeth'	['question_type_global', 'question_two_hop_statement']
Which are some [undergraduate] courses that no phd student is taking?	'U301', 'G305'	['question_type_global', 'question_three_hop_statement']
[he]'s office is [Environmental Building]
What is [Igor]'s office?	'Environmental Building'	['question_type_local']
What are the [mini course]?	'G9000'	['question_type_global', 'question_single_statement']
who are the professors?	'Lorilee', 'Lizeth', 'Igor', 'Kristeen'	['question_type_global', 'question_single_statement']
[Hiram] did not pass the qualifiers
[this student] passed thesis defense
What are the courses TAed by [he]?	'U304'	['question_type_local']
Which students are TAing [G310]?	'Alejandra'	['question_type_local']
Which professors are conducting research in [computational biology]	'Igor'	['question_type_global', 'question_single_statement']
What students are taking G9000	'Angelita', 'Hiram'	['question_type_global', 'question_single_statement']
[G104] is taught by [Lizeth]
Which courses have phd student TAs?	'G9000', 'U304', 'G104'	['question_type_global', 'question_two_hop_statement']
What professors are on [Zenaida]'s committee	'Lizeth', 'Igor', 'Kristeen'	['question_type_local']
What students are taking a course taught by their advisor?	'Hiram'	['question_type_global', 'question_three_hop_statement']
Which students are both taking a course and a TA?	'Cyndi', 'Zenaida', 'Angelita', 'Hiram', 'William'	['question_type_global', 'question_two_hop_statement']
[this person] is back from the sabbatical
which students passed the proposal exam?	'Zenaida', 'Angelita', 'Hiram'	['question_type_global', 'question_single_statement']
What phd students are taking courses and TAing?	'Zenaida', 'Angelita', 'Hiram'	['question_type_global', 'question_three_hop_statement']
Which courses have phd student TAs that either have some funding or passed the qualifying exam?	'G104'	['question_type_global', 'question_four_hop_statement']
[this person] is in [Hale Building]
Which professors are teaching [full_semester_course]?	'Lorilee'	['question_type_global', 'question_two_hop_statement']
Who are [that person]'s students?	'Hiram'	['question_type_local']
What are all the courses?	'G9000', 'U101', 'G303', 'G7000', 'U301', 'G310', 'U304', 'G104', 'U104', 'G305'	['question_type_global', 'question_single_statement']
Who is on [Hiram]'s committee?	'Lorilee', 'Kristeen'	['question_type_local']
who are the students?	'Cyndi', 'Zenaida', 'Angelita', 'Hiram', 'William', 'Gia', 'Alejandra'	['question_type_global', 'question_single_statement']
Which professors have an [full] status?	'Kristeen'	['question_type_global', 'question_single_statement']
There is a course called [G610]
Who is teaching [U301]?	'Igor'	['question_type_local']
Which are some [undergraduate] courses that no masters student is taking?	'U301', 'G305'	['question_type_global', 'question_three_hop_statement']
Which courses are TAed by masters students?	'U101', 'G310', 'U304', 'G104'	['question_type_global', 'question_two_hop_statement']
which students passed the proposal exam?	'Zenaida', 'Angelita', 'Hiram'	['question_type_global', 'question_single_statement']
Which students's advisors are conducting research in [programming languages]	'Hiram'	['question_type_global', 'question_two_hop_statement']
Which people are in the [physics] department?	'Cyndi'	['question_type_global', 'question_single_statement']
[that course] is a [masters] level course
[Gia] and [Cyndi] are both taking [G610]
Which students are in their [first year]	'Angelita'	['question_type_global', 'question_single_statement']
Who is taking the U104 course	'Zenaida', 'William'	['question_type_global', 'question_single_statement']
who are the phd students?	'Zenaida', 'Angelita', 'Hiram'	['question_type_global', 'question_single_statement']
What courses is [Gia] TAing?	'U101'	['question_type_local']
Who is [Hiram]'s advisor?	'Lizeth'	['question_type_local']
Which courses are TAed by masters students?	'U101', 'G310', 'U304', 'G104'	['question_type_global', 'question_two_hop_statement']
What is [Kristeen] working on?	'molecular biology'	['question_type_local']
What professors that currently advise students are going on sabbatical?	'Lorilee'	['question_type_global', 'question_two_hop_statement']
who are the masters students?	'Cyndi', 'William', 'Gia', 'Alejandra'	['question_type_global', 'question_single_statement']
What are the courses TAed by [Cyndi]?	'G104'	['question_type_local']
What professors advise students who passed their thesis proposal?	'Lorilee', 'Lizeth'	['question_type_global', 'question_two_hop_statement']
What are the [undergraduate] courses?	'U301', 'G310', 'U104', 'G305'	['question_type_global', 'question_single_statement']
who are the professors?	'Lorilee', 'Lizeth', 'Igor', 'Kristeen'	['question_type_global', 'question_single_statement']
Which professors currently on sabbatical are supposed to be teaching [undergraduate] courses?	'Igor'	['question_type_global', 'question_three_hop_statement']
Who is TAing [U101]?	'Gia'	['question_type_local']
Which courses have phd student TAs?	'G9000', 'U304', 'G104'	['question_type_global', 'question_two_hop_statement']
Who is taking the G104 course	'Hiram'	['question_type_global', 'question_single_statement']
which [undergraduate] courses have no masters students enrolled?	'U301', 'G305'	['question_type_global', 'question_three_hop_statement']
What masters students are taking G610	'Cyndi', 'Gia'	['question_type_global', 'question_two_hop_statement']
What phd students are taking G9000	'Angelita', 'Hiram'	['question_type_global', 'question_two_hop_statement']
What office is [Lizeth] in?	'Hale Building'	['question_type_local']
who are the phd students?	'Zenaida', 'Angelita', 'Hiram'	['question_type_global', 'question_single_statement']
What professors advise students who passed their thesis proposal?	'Lorilee', 'Lizeth'	['question_type_global', 'question_two_hop_statement']
Which professors advise students who passed their defense?	'Lorilee', 'Lizeth'	['question_type_global', 'question_two_hop_statement']
Who is teaching [full_semester_course]?	'Lorilee'	['question_type_global', 'question_two_hop_statement']
Which courses are offered this semester?	'G9000', 'U101', 'G303', 'G7000', 'U301', 'G310', 'U304', 'G104', 'U104', 'G305', 'G610'	['question_type_global', 'question_single_statement']
which students passed the qualifying exam?	'Zenaida'	['question_type_global', 'question_single_statement']
What courses is [Gia] taking?	'G610'	['question_type_local']
Which courses are TAed by phd students that passed their qualifier exam?	'G104'	['question_type_global', 'question_three_hop_statement']
Which courses are TAed by [Cyndi]?	'G104'	['question_type_local']
Which professors advise students who passed their defense?	'Lorilee', 'Lizeth'	['question_type_global', 'question_two_hop_statement']
What are the [undergraduate] courses?	'U301', 'G310', 'U104', 'G305'	['question_type_global', 'question_single_statement']
Who is teaching [full_semester_course]?	'Lorilee'	['question_type_global', 'question_two_hop_statement']
who are the masters students?	'Cyndi', 'William', 'Gia', 'Alejandra'	['question_type_global', 'question_single_statement']
Which professors have offices in Hale Building	'Lizeth'	['question_type_global', 'question_two_hop_statement']
Which people are in the [english] department?	'William'	['question_type_global', 'question_single_statement']
Which are some courses that masters students take?	'G310', 'U104', 'G610'	['question_type_global', 'question_two_hop_statement']
[Igor] is on [Hiram]'s committee
Which courses did [Zenaida] enroll in?	'U104'	['question_type_local']
Which courses are [full_semester_course]	'G7000', 'U104'	['question_type_global', 'question_single_statement']
who are the phd students?	'Zenaida', 'Angelita', 'Hiram'	['question_type_global', 'question_single_statement']
[G104] is set up as a full semester course
[Hiram] and [Alejandra] are attending [G104]
Who advises [Zenaida]?	'Lorilee'	['question_type_local']
which students passed the defense?	'Zenaida', 'Angelita', 'Hiram'	['question_type_global', 'question_single_statement']
[Angelita] and [he] are attending [G104]
Who is teaching [G104]?	'Lizeth'	['question_type_local']
Who is on sabbatical?	'Lorilee', 'Igor', 'Kristeen'	['question_type_global', 'question_single_statement']
Which courses are TAed by masters students?	'U101', 'G310', 'U304', 'G104'	['question_type_global', 'question_two_hop_statement']
What courses is [Hiram] taking?	'G9000', 'G104'	['question_type_local']
What students currently have their advisor on sabbatical	'Zenaida', 'Angelita'	['question_type_global', 'question_two_hop_statement']
What is [Lizeth] working on?	'programming languages'	['question_type_local']
Which students are advised by professors working on [molecular biology]?	'Zenaida', 'Angelita'	['question_type_global', 'question_two_hop_statement']
What are the [mini course]?	'G9000'	['question_type_global', 'question_single_statement']
Which courses are TAed by phd students in their sixth year?	'G104'	['question_type_global', 'question_three_hop_statement']
Who is in [Center Building]	'Kristeen'	['question_type_global', 'question_two_hop_statement']
What courses is [he] taking?	'G9000', 'G104'	['question_type_local']
For which phd students does [Lizeth] serve on a committee?	'Zenaida', 'Angelita'	['question_type_local']
Who are the professors working on [computational biology]?	'Igor'	['question_type_global', 'question_single_statement']
What are the courses TAed by [he]?	'U304'	['question_type_local']
who are the professors?	'Lorilee', 'Lizeth', 'Igor', 'Kristeen'	['question_type_global', 'question_single_statement']
What are all the courses?	'G9000', 'U101', 'G303', 'G7000', 'U301', 'G310', 'U304', 'G104', 'U104', 'G305', 'G610'	['question_type_global', 'question_single_statement']
what courses have masters students taking them?	'G310', 'G104', 'U104', 'G610'	['question_type_global', 'question_two_hop_statement']
What courses is [Angelita] taking?	'G9000', 'G310', 'U304', 'G104'	['question_type_local']
What is [Lizeth] working on?	'programming languages'	['question_type_local']
Which [fourth year] students's advisors are conducting research in [programming languages]	'Hiram'	['question_type_global', 'question_three_hop_statement']
Which courses are TAed by masters students?	'U101', 'G310', 'U304', 'G104'	['question_type_global', 'question_two_hop_statement']
[Kristeen] is the instructor for [G9000]
What students are enrolled in [that course]?	'Angelita', 'Hiram'	['question_type_local']
[Cyndi] is attending [G9000]
What is [Kristeen]'s office?	'Center Building'	['question_type_local']
What are the [undergraduate] courses?	'U301', 'G310', 'U104', 'G305'	['question_type_global', 'question_single_statement']
Which courses are TAed by phd students?	'G9000', 'U304', 'G104'	['question_type_global', 'question_two_hop_statement']
Which masters students taking the G104 course	'Alejandra'	['question_type_global', 'question_two_hop_statement']
Who does [Lizeth] advise?	'Hiram'	['question_type_local']
Which professors currently on sabbatical are supposed to be teaching [undergraduate] courses?	'Igor'	['question_type_global', 'question_three_hop_statement']
What courses is [this person] TAing?	'G104'	['question_type_local']
which [undergraduate] courses have some phd students enrolled?	'G310', 'U104'	['question_type_global', 'question_three_hop_statement']
What students are enrolled in [U104]?	'Zenaida', 'William'	['question_type_local']
Which professors advise students who passed their proposal?	'Lorilee', 'Lizeth'	['question_type_global', 'question_two_hop_statement']
who are the masters students?	'Cyndi', 'William', 'Gia', 'Alejandra'	['question_type_global', 'question_single_statement']
Which phd courses have phd student TAs?	'U304'	['question_type_global', 'question_three_hop_statement']
What students are going to TA [that course]?	'Angelita'	['question_type_local']
What professors advise students who passed their thesis qualifiers?	'Lorilee'	['question_type_global', 'question_two_hop_statement']
Who has [Kristeen] on their phd committee?	'Zenaida', 'Angelita', 'Hiram'	['question_type_local']
Which professors that are currently not on sabbatical need to be teaching [full_semester_course]?	'Lizeth'	['question_type_global', 'question_three_hop_statement']
Which courses did [Gia] enroll in?	'G610'	['question_type_local']
which courses have some masters students enrolled?	'G9000', 'G310', 'G104', 'U104', 'G610'	['question_type_global', 'question_two_hop_statement']
Who is in the [physics] department	'Cyndi'	['question_type_global', 'question_single_statement']
Which courses have phd student TAs?	'G9000', 'U304', 'G104'	['question_type_global', 'question_two_hop_statement']
[Alejandra] and [Cyndi] are taking [U304]
Who are the professors working on [molecular biology]?	'Lorilee', 'Kristeen'	['question_type_global', 'question_single_statement']
who are the students?	'Cyndi', 'Zenaida', 'Angelita', 'Hiram', 'William', 'Gia', 'Alejandra'	['question_type_global', 'question_single_statement']
What courses is [Alejandra] TAing?	'G310'	['question_type_local']
Which students are in a course that is instructed by their advisor?	'Hiram'	['question_type_global', 'question_three_hop_statement']
What are the courses TAed by [Alejandra]?	'G310'	['question_type_local']
Which masters students taking the U304 course	'Cyndi', 'Alejandra'	['question_type_global', 'question_two_hop_statement']
What courses is [Lizeth] teaching?	'G104'	['question_type_local']
What professors advise students who defended successfully?	'Lorilee', 'Lizeth'	['question_type_global', 'question_two_hop_statement']
Who is on sabbatical?	'Lorilee', 'Igor', 'Kristeen'	['question_type_global', 'question_single_statement']
who are the masters students?	'Cyndi', 'William', 'Gia', 'Alejandra'	['question_type_global', 'question_single_statement']
Which courses did [Cyndi] enroll in?	'G9000', 'G310', 'U304', 'G610'	['question_type_local']
What are the [masters] courses?	'G9000', 'G7000', 'G104', 'G610'	['question_type_global', 'question_single_statement']
which [undergraduate] courses have some masters students enrolled?	'G310', 'U104'	['question_type_global', 'question_three_hop_statement']
What courses is [Cyndi] TAing?	'G104'	['question_type_local']
which students passed the qualifying exam?	'Zenaida'	['question_type_global', 'question_single_statement']
Which courses did [Alejandra] enroll in?	'U304', 'G104'	['question_type_local']
Which courses are [mini course]	'G9000'	['question_type_global', 'question_single_statement']
What are the courses TAed by [Cyndi]?	'G104'	['question_type_local']
What is [Igor]'s research focus?	'computational biology'	['question_type_local']
Which courses are TAed by phd students that passed their qualifier exam or have some funding?	'G104'	['question_type_global', 'question_four_hop_statement']
What are the [sixth year] phd students	'Zenaida'	['question_type_global', 'question_single_statement']
which students passed the proposal exam?	'Zenaida', 'Angelita', 'Hiram'	['question_type_global', 'question_single_statement']
what [masters] courses have phd students taking them?	'G9000', 'G104'	['question_type_global', 'question_three_hop_statement']
What are the courses TAed by [Alejandra]?	'G310'	['question_type_local']
who are the professors?	'Lorilee', 'Lizeth', 'Igor', 'Kristeen'	['question_type_global', 'question_single_statement']
which courses have no masters students enrolled?	'U101', 'G303', 'G7000', 'U301', 'G305'	['question_type_global', 'question_two_hop_statement']
Which courses have phd student TAs?	'G9000', 'U304', 'G104'	['question_type_global', 'question_two_hop_statement']
[Cyndi] is attending [U304]
What is [Kristeen]'s research focus?	'molecular biology'	['question_type_local']
Which courses are [phd] level courses?	'U304'	['question_type_global', 'question_single_statement']
Which students are in a course that is instructed by their advisor?	'Hiram'	['question_type_global', 'question_three_hop_statement']
[U304] is set up as a full semester course
What are the [full_semester_course]?	'G7000', 'U304', 'G104', 'U104'	['question_type_global', 'question_single_statement']
Which professors have offices in Environmental Building	'Lorilee', 'Igor'	['question_type_global', 'question_two_hop_statement']
which students passed the defense?	'Zenaida', 'Angelita', 'Hiram'	['question_type_global', 'question_single_statement']
Who is enrolled in [G104]?	'Angelita', 'Hiram', 'Alejandra'	['question_type_local']
[William] and [Angelita] are both enrolled in [U304]
Who is TAing [U304]?	'Hiram', 'William'	['question_type_local']
Which professors are teaching [undergraduate] courses?	'Igor'	['question_type_global', 'question_two_hop_statement']
Which professors are teaching [masters] courses?	'Lorilee', 'Lizeth', 'Kristeen'	['question_type_global', 'question_two_hop_statement']
Which courses are TAed by [William]?	'U304'	['question_type_local']
Which courses are TAed by phd students that passed their qualifier exam?	'G104'	['question_type_global', 'question_three_hop_statement']
What are the courses TAed by [he]?	'U304'	['question_type_local']
what courses have masters students taking them?	'G9000', 'G310', 'U304', 'G104', 'U104', 'G610'	['question_type_global', 'question_two_hop_statement']
Which courses are offered this semester?	'G9000', 'U101', 'G303', 'G7000', 'U301', 'G310', 'U304', 'G104', 'U104', 'G305', 'G610'	['question_type_global', 'question_single_statement']
Which professors advise students who passed their proposal?	'Lorilee', 'Lizeth'	['question_type_global', 'question_two_hop_statement']
What courses is [he] TAing?	'U304'	['question_type_local']
Who is supposed to be teaching [masters] courses but is currently on sabbatical?	'Lorilee', 'Kristeen'	['question_type_global', 'question_three_hop_statement']
Which students are taking [U304]?	'Cyndi', 'Angelita', 'William', 'Alejandra'	['question_type_local']
Which students are in their [fourth year]	'Hiram'	['question_type_global', 'question_single_statement']
Who are the students in the [english] department	'William'	['question_type_global', 'question_two_hop_statement']
Which courses are offered this semester?	'G9000', 'U101', 'G303', 'G7000', 'U301', 'G310', 'U304', 'G104', 'U104', 'G305', 'G610'	['question_type_global', 'question_single_statement']
What are the courses TAed by [he]?	'U304'	['question_type_local']
Who is in [Center Building]	'Kristeen'	['question_type_global', 'question_two_hop_statement']
who are the students?	'Cyndi', 'Zenaida', 'Angelita', 'Hiram', 'William', 'Gia', 'Alejandra'	['question_type_global', 'question_single_statement']
Which courses are TAed by phd students?	'G9000', 'U304', 'G104'	['question_type_global', 'question_two_hop_statement']
Who is [she]'s advisor?	'Lorilee'	['question_type_local']
which courses have no phd students enrolled?	'U101', 'G303', 'G7000', 'U301', 'G305', 'G610'	['question_type_global', 'question_two_hop_statement']
Who is on sabbatical this semester?	'Lorilee', 'Igor', 'Kristeen'	['question_type_global', 'question_single_statement']
Which courses are TAed by [he]?	'U304'	['question_type_local']
which [masters] courses have no phd students enrolled?	'G7000', 'G610'	['question_type_global', 'question_three_hop_statement']
Which courses have masters student TAs?	'U101', 'G310', 'U304', 'G104'	['question_type_global', 'question_two_hop_statement']
What courses is [William] taking?	'U304', 'U104'	['question_type_local']
Which students are both taking a course and a TA?	'Cyndi', 'Zenaida', 'Angelita', 'Hiram', 'William', 'Gia', 'Alejandra'	['question_type_global', 'question_two_hop_statement']
Which courses are offered this semester?	'G9000', 'U101', 'G303', 'G7000', 'U301', 'G310', 'U304', 'G104', 'U104', 'G305', 'G610'	['question_type_global', 'question_single_statement']
Who is supposed to be teaching [mini course] and is currently on sabbatical?	'Kristeen'	['question_type_global', 'question_three_hop_statement']
Who is on sabbatical this semester?	'Lorilee', 'Igor', 'Kristeen'	['question_type_global', 'question_single_statement']
which students passed the defense?	'Zenaida', 'Angelita', 'Hiram'	['question_type_global', 'question_single_statement']
Who are the [first year] students?	'Angelita'	['question_type_global', 'question_single_statement']
Which courses did [he] enroll in?	'U304', 'U104'	['question_type_local']
Which professors have offices in Center Building	'Kristeen'	['question_type_global', 'question_two_hop_statement']
[she] is in [second year]
Which courses did [she] enroll in?	'G9000', 'G310', 'U304', 'G104'	['question_type_local']
What courses is [Lizeth] teaching?	'G104'	['question_type_local']
Who is in the [english] department	'William'	['question_type_global', 'question_single_statement']
who are the masters students?	'Cyndi', 'William', 'Gia', 'Alejandra'	['question_type_global', 'question_single_statement']
Which courses are TAed by [Hiram]?	'U304'	['question_type_local']
What are the [undergraduate] courses?	'U301', 'G310', 'U104', 'G305'	['question_type_global', 'question_single_statement']
Which courses are TAed by phd students?	'G9000', 'U304', 'G104'	['question_type_global', 'question_two_hop_statement']
Which professors have offices in Environmental Building	'Lorilee', 'Igor'	['question_type_global', 'question_two_hop_statement']
What professors advise students who passed their thesis proposal?	'Lorilee', 'Lizeth'	['question_type_global', 'question_two_hop_statement']
What office is [Igor] in?	'Environmental Building'	['question_type_local']
Which masters students taking the U104 course	'William'	['question_type_global', 'question_two_hop_statement']
Which professors are teaching [mini course]?	'Kristeen'	['question_type_global', 'question_two_hop_statement']
Which courses have masters student TAs?	'U101', 'G310', 'U304', 'G104'	['question_type_global', 'question_two_hop_statement']
What courses is [this student] taking?	'G9000', 'G310', 'U304', 'G104'	['question_type_local']
who are the professors?	'Lorilee', 'Lizeth', 'Igor', 'Kristeen'	['question_type_global', 'question_single_statement']
Who is in [Center Building]	'Kristeen'	['question_type_global', 'question_two_hop_statement']
Which courses are offered this semester?	'G9000', 'U101', 'G303', 'G7000', 'U301', 'G310', 'U304', 'G104', 'U104', 'G305', 'G610'	['question_type_global', 'question_single_statement']
[Angelita] has passed the qualifying exam
What are the courses TAed by [Angelita]?	'G9000'	['question_type_local']
Which are some courses that phd students take?	'G9000', 'G310', 'U304', 'G104', 'U104'	['question_type_global', 'question_two_hop_statement']
Which courses did [Alejandra] enroll in?	'U304', 'G104'	['question_type_local']
Which professors advise students who passed their qualifying exam?	'Lorilee'	['question_type_global', 'question_two_hop_statement']
What are the courses TAed by [William]?	'U304'	['question_type_local']
Who is on [she]'s committee?	'Lizeth', 'Igor', 'Kristeen'	['question_type_local']
[that person] is now in [third year]
What are the courses that [this student] is enrolled in?	'G9000', 'G310', 'U304', 'G104'	['question_type_local']
Which courses are [masters] level courses?	'G9000', 'G7000', 'G104', 'G610'	['question_type_global', 'question_single_statement']
Which professors are conducting research in [programming languages]	'Lizeth'	['question_type_global', 'question_single_statement']
What courses is [that person] TAing?	'G9000'	['question_type_local']
Who is teaching [U101]?	"I don't know"	['question_type_local']
[she] and [Gia] are both enrolled in [G305]
What are the [third year] phd students	'Angelita'	['question_type_global', 'question_single_statement']
What phd students are taking G104	'Angelita', 'Hiram'	['question_type_global', 'question_two_hop_statement']
[Angelita] is now in [fourth year]
