there is a [professor] named [Vivienne]
the affiliation of [that professor] is [math]
[that professor]'s office is [1976]
[Vivienne]'s email is [Vivienne@yahoo.com]
Which department is [that professor] in?	'math'	['question_type_local']
list the professors in the [math] department	'Vivienne'	['question_type_global', 'question_two_hop_statement']
which professors are in the [math] department?	'Vivienne'	['question_type_global', 'question_two_hop_statement']
What is [this person]'s email	'Vivienne@yahoo.com'	['question_type_local']
What is [this professor]'s office?	'1976'	['question_type_local']
What is [this professor]'s department?	'math'	['question_type_local']
I am taking a [business communication] course
[Vivienne] teaches [this course]
[Lucio] is a [professor]
the affiliation of [he] is [english]
[Lucio] is in [1976]
[this professor]'s email is [Lucio@chk.ru]
What courses is [Vivienne] teaching?	'business communication'	['question_type_local']
[business communication] has a new [business communication project 1] released
What is [Vivienne]'s email	'Vivienne@yahoo.com'	['question_type_local']
what assignments do I have to do for [Vivienne]?	'business communication project 1'	['question_type_global', 'question_three_hop_statement']
what are all the assignments due?	'business communication project 1'	['question_type_global', 'question_single_statement']
what assignments do I have to do for [business communication]?	'business communication project 1'	['question_type_global', 'question_two_hop_statement']
I submitted [that project] late
The topic of [this project] is [cold war]
The deadline of [that project] is [May 11]
[business communication project 1] is [20] points
there is a [professor] named [Emmie]
The deadline of [this project] moved to [May 11]
What is [Lucio]'s email	'Lucio@chk.ru'	['question_type_local']
show me all the late projects that i submitted	'business communication project 1'	['question_type_global', 'question_two_hop_statement']
what are all the assignments due for [business communication]?	'business communication project 1'	['question_type_global', 'question_two_hop_statement']
When is [this project] due?	'May 11'	['question_type_local']
list all projects for [Vivienne]	'business communication project 1'	['question_type_global', 'question_three_hop_statement']
who did I submit assignments late to	'Vivienne'	['question_type_global', 'question_three_hop_statement']
there is a new [homework] for [business communication]
What department is [Lucio] affiliated with?	'english'	['question_type_local']
create a [professor] named [Milagros]
[business communication homework 1] is [34] points
[this assignment] is due on [May 16]
I submitted [this homework] late and received 34 points
What is [Lucio]'s email	'Lucio@chk.ru'	['question_type_local']
list all homeworks	'business communication homework 1'	['question_type_global', 'question_single_statement']
show me all the late assignments that i submitted	'business communication project 1', 'business communication homework 1'	['question_type_global', 'question_two_hop_statement']
what homeworks did i submit?	'business communication homework 1'	['question_type_global', 'question_two_hop_statement']
which homeworks did I submit?	'business communication homework 1'	['question_type_global', 'question_two_hop_statement']
list all assignments that i submitted late for [Vivienne]	'business communication project 1', 'business communication homework 1'	['question_type_global', 'question_three_hop_statement']
I am taking a course called [us history]
[Emmie] is the instructor for [that course]
[business communication homework 1] is about [The Senses]
What is the topic of [business communication project 1]?	'cold war'	['question_type_local']
which projects are due before [May 13]?	'business communication project 1'	['question_type_global', 'question_two_hop_statement']
[this person]'s department is [math]
[this professor]'s email is [Emmie@cornell.edu]
What is [Lucio]'s department?	'english'	['question_type_local']
which homeworks are due after [May 13]?	'business communication homework 1'	['question_type_global', 'question_two_hop_statement']
I am taking a [spanish] course
[that professor] is in [1812]
[that class] is taught by [Milagros]
what are all the projects due for [business communication]?	'business communication project 1'	['question_type_global', 'question_two_hop_statement']
[this person]'s email is [Milagros@yahoo.com]
what did I get on [business communication homework 1]?	34	['question_type_local']
list all projects	'business communication project 1'	['question_type_global', 'question_single_statement']
show me all projects i submitted for [Vivienne]	'business communication project 1'	['question_type_global', 'question_three_hop_statement']
there is a [professor] named [Britney]
[Milagros]'s department is [english]
What office is [Vivienne] in?	'1976'	['question_type_local']
show me all homeworks i submitted	'business communication homework 1'	['question_type_global', 'question_two_hop_statement']
what are the late projects that i submitted?	'business communication project 1'	['question_type_global', 'question_two_hop_statement']
which professors did I submit late projects for?	'Vivienne'	['question_type_global', 'question_three_hop_statement']
[Britney]'s email is [Britney@yahoo.com]
[Britney]'s office is [3387]
[this professor]'s department is [english]
what instructors did i have late projects for?	'Vivienne'	['question_type_global', 'question_three_hop_statement']
who did I submit projects late to	'Vivienne'	['question_type_global', 'question_three_hop_statement']
list all homeworks for [business communication]	'business communication homework 1'	['question_type_global', 'question_two_hop_statement']
what are the late homeworks that i submitted?	'business communication homework 1'	['question_type_global', 'question_two_hop_statement']
how much did I get on [business communication homework 1]?	34	['question_type_local']
which professors are in the [english] department?	'Lucio', 'Milagros', 'Britney'	['question_type_global', 'question_two_hop_statement']
what homeworks do I have to do for [Vivienne]?	'business communication homework 1'	['question_type_global', 'question_three_hop_statement']
What office is [Lucio] in?	'1976'	['question_type_local']
list homeworks that are due on [May 16]	'business communication homework 1'	['question_type_global', 'question_two_hop_statement']
[us history project 1] is out for [us history]
I submitted [that assignment]
[that project] is worth [13] points
[this project] is on [introduction]
[that assignment] is due on [May 10]
Who is the instructor for [business communication]?	'Vivienne'	['question_type_local']
which homeworks are due before [May 17]?	'business communication homework 1'	['question_type_global', 'question_two_hop_statement']
which homeworks did I submit late?	'business communication homework 1'	['question_type_global', 'question_two_hop_statement']
who are the professors?	'Vivienne', 'Lucio', 'Emmie', 'Milagros', 'Britney'	['question_type_global', 'question_single_statement']
what assignments did i submit late?	'business communication project 1', 'business communication homework 1'	['question_type_global', 'question_two_hop_statement']
which professors are in the [math] department?	'Vivienne', 'Emmie'	['question_type_global', 'question_two_hop_statement']
which projects are due before [May 15]?	'business communication project 1', 'us history project 1'	['question_type_global', 'question_two_hop_statement']
what are the homeworks that i submitted for [Vivienne]	'business communication homework 1'	['question_type_global', 'question_three_hop_statement']
list all projects that i submitted for [us history]	'us history project 1'	['question_type_global', 'question_two_hop_statement']
what instructors did i have late assignments for?	'Vivienne'	['question_type_global', 'question_three_hop_statement']
What are the homeworks for [business communication]?	'business communication homework 1'	['question_type_local']
which projects are due before [May 13]?	'business communication project 1', 'us history project 1'	['question_type_global', 'question_two_hop_statement']
which projects are due before [May 19]?	'business communication project 1', 'us history project 1'	['question_type_global', 'question_two_hop_statement']
[business communication] has a new [business communication project 2] out
[business communication project 2] is on [Molds & Fungi]
I submitted [this project] late
What courses is [Milagros] teaching?	'spanish'	['question_type_local']
which homeworks are due after [May 13]?	'business communication homework 1'	['question_type_global', 'question_two_hop_statement']
list all assignments for [business communication]	'business communication project 1', 'business communication project 2'	['question_type_global', 'question_two_hop_statement']
list all projects	'business communication project 1', 'us history project 1', 'business communication project 2'	['question_type_global', 'question_single_statement']
[that project] is [84] points
[Milagros]'s office is [1812]
who are the instructors to whom i submitted late homeworks?	'Vivienne'	['question_type_global', 'question_three_hop_statement']
which assignments are due before [May 12]?	'business communication project 1', 'us history project 1'	['question_type_global', 'question_two_hop_statement']
list all assignments that i submitted late	'business communication project 1', 'business communication homework 1', 'business communication project 2'	['question_type_global', 'question_two_hop_statement']
which assignments are due after [May 09]?	'business communication project 1', 'business communication homework 1', 'us history project 1'	['question_type_global', 'question_two_hop_statement']
what are the courses for which I submitted projects late	'business communication'	['question_type_global', 'question_two_hop_statement']
there is a new [project] for [business communication]
Who is teaching [business communication]?	'Vivienne'	['question_type_local']
show me all the late assignments that i submitted	'business communication project 1', 'business communication homework 1', 'business communication project 2'	['question_type_global', 'question_two_hop_statement']
I submitted [that project]
The deadline of [this assignment] is [June 02]
what are all the projects due for [Emmie]?	'us history project 1'	['question_type_global', 'question_three_hop_statement']
[business communication] has a new [business communication homework 2] out
[business communication project 3] is about [grammar induction]
[that project] is [95] points
[spanish homework 1] is out for [spanish]
[this homework] is [54] points
Show me all assignments due for [spanish]	'spanish homework 1'	['question_type_local']
what projects do I have to do for [us history]?	'us history project 1'	['question_type_global', 'question_two_hop_statement']
[that homework] is due on [May 17]
What is [Lucio]'s email	'Lucio@chk.ru'	['question_type_local']
which homeworks are due after [May 10]?	'business communication homework 1', 'spanish homework 1'	['question_type_global', 'question_two_hop_statement']
which assignments are due after [May 14]?	'business communication homework 1', 'business communication project 3', 'spanish homework 1'	['question_type_global', 'question_two_hop_statement']
which assignments did I submit?	'business communication project 1', 'business communication homework 1', 'us history project 1', 'business communication project 2', 'business communication project 3'	['question_type_global', 'question_two_hop_statement']
[spanish homework 1] is about [kernels]
I submitted [this assignment] and received 54 points
list assignments that are due on [May 11]	'business communication project 1'	['question_type_global', 'question_two_hop_statement']
what instructors did i have late homeworks for?	'Vivienne'	['question_type_global', 'question_three_hop_statement']
Show me all homeworks due for [business communication]	'business communication homework 1', 'business communication homework 2'	['question_type_local']
which projects are due after [May 18]?	'business communication project 3'	['question_type_global', 'question_two_hop_statement']
which projects did I submit late?	'business communication project 1', 'business communication project 2'	['question_type_global', 'question_two_hop_statement']
what are all the homeworks due?	'business communication homework 1', 'business communication homework 2', 'spanish homework 1'	['question_type_global', 'question_single_statement']
What is [business communication project 2] on?	'Molds & Fungi'	['question_type_local']
what are the courses for which I submitted homeworks late	'business communication'	['question_type_global', 'question_two_hop_statement']
show me all late homeworks i submitted	'business communication homework 1'	['question_type_global', 'question_two_hop_statement']
which assignments did I submit late for [Vivienne]?	'business communication project 1', 'business communication homework 1', 'business communication project 2'	['question_type_global', 'question_three_hop_statement']
When is [business communication project 3] due?	'June 02'	['question_type_local']
what are all the projects due?	'business communication project 1', 'us history project 1', 'business communication project 2', 'business communication project 3'	['question_type_global', 'question_single_statement']
show me the homeworks due on [May 17]	'spanish homework 1'	['question_type_global', 'question_two_hop_statement']
what are all the homeworks due?	'business communication homework 1', 'business communication homework 2', 'spanish homework 1'	['question_type_global', 'question_single_statement']
list all assignments	'business communication project 1', 'business communication homework 1', 'us history project 1', 'business communication project 2', 'business communication project 3', 'business communication homework 2', 'spanish homework 1'	['question_type_global', 'question_single_statement']
What is [this homework] on?	'kernels'	['question_type_local']
which homeworks did I submit late?	'business communication homework 1'	['question_type_global', 'question_two_hop_statement']
which projects are due before [May 12]?	'business communication project 1', 'us history project 1'	['question_type_global', 'question_two_hop_statement']
[spanish homework 2] is out for [spanish]
[us history] has a new [us history project 2] released
I submitted [that project] late
[that assignment] is due on [May 27]
[that assignment] is [16] points
which courses did I submit late homeworks for?	'business communication'	['question_type_global', 'question_two_hop_statement']
what are the late assignments that i submitted for [Vivienne]	'business communication project 1', 'business communication homework 1', 'business communication project 2'	['question_type_global', 'question_three_hop_statement']
list all projects that i submitted late	'business communication project 1', 'business communication project 2', 'us history project 2'	['question_type_global', 'question_two_hop_statement']
[spanish project 1] is released for [spanish]
What courses is [Milagros] teaching?	'spanish'	['question_type_local']
which homeworks are due before [May 24]?	'business communication homework 1', 'spanish homework 1'	['question_type_global', 'question_two_hop_statement']
What is [Emmie]'s email	'Emmie@cornell.edu'	['question_type_local']
what homeworks did i submit late for [Vivienne]?	'business communication homework 1'	['question_type_global', 'question_three_hop_statement']
which projects are due before [May 19]?	'business communication project 1', 'us history project 1'	['question_type_global', 'question_two_hop_statement']
[spanish project 1] is [93] points
I submitted [spanish project 1] and received 93 points
What are the homeworks for [business communication]?	'business communication homework 1', 'business communication homework 2'	['question_type_local']
what assignments did i submit late?	'business communication project 1', 'business communication homework 1', 'business communication project 2', 'us history project 2'	['question_type_global', 'question_two_hop_statement']
what are all the assignments due for [us history]?	'us history project 1', 'us history project 2'	['question_type_global', 'question_two_hop_statement']
what assignments do I have to do for [Vivienne]?	'business communication project 1', 'business communication homework 1', 'business communication project 2', 'business communication project 3', 'business communication homework 2'	['question_type_global', 'question_three_hop_statement']
[this project] is due on [May 13]
[us history] has a new [us history homework 1] released
When is [us history project 2] due?	'May 27'	['question_type_local']
which homeworks did I submit late for [business communication]?	'business communication homework 1'	['question_type_global', 'question_two_hop_statement']
which assignments are due on [May 16]?	'business communication homework 1'	['question_type_global', 'question_two_hop_statement']
which projects did I submit for [Milagros]?	'spanish project 1'	['question_type_global', 'question_three_hop_statement']
[this homework] is [46] points
[business communication project 4] is released for [business communication]
there is new [business communication homework 3] for [business communication]
[business communication project 4] is [40] points
The deadline of [business communication project 4] is [June 16]
I submitted [that project] and received 40 points
list all projects for [Vivienne]	'business communication project 1', 'business communication project 2', 'business communication project 3', 'business communication project 4'	['question_type_global', 'question_three_hop_statement']
list all homeworks	'business communication homework 1', 'business communication homework 2', 'spanish homework 1', 'spanish homework 2', 'us history homework 1', 'business communication homework 3'	['question_type_global', 'question_single_statement']
what are the projects that i submitted for [business communication]	'business communication project 1', 'business communication project 2', 'business communication project 3', 'business communication project 4'	['question_type_global', 'question_two_hop_statement']
what are all the assignments due for [us history]?	'us history project 1', 'us history project 2'	['question_type_global', 'question_two_hop_statement']
list assignments that are due on [May 16]	'business communication homework 1'	['question_type_global', 'question_two_hop_statement']
what are the homeworks that i submitted for [business communication]	'business communication homework 1'	['question_type_global', 'question_two_hop_statement']
what are the late projects that i submitted?	'business communication project 1', 'business communication project 2', 'us history project 2'	['question_type_global', 'question_two_hop_statement']
what homeworks do I have to do for [Milagros]?	'spanish homework 1', 'spanish homework 2'	['question_type_global', 'question_three_hop_statement']
When is the deadline of [business communication project 1]?	'May 11'	['question_type_local']
which projects did I submit late for [Vivienne]?	'business communication project 1', 'business communication project 2'	['question_type_global', 'question_three_hop_statement']
what are the courses for which I submitted assignments late	'business communication', 'us history'	['question_type_global', 'question_two_hop_statement']
show me all late assignments i submitted for [Emmie]	'us history project 2'	['question_type_global', 'question_three_hop_statement']
list all projects for [spanish]	'spanish project 1'	['question_type_global', 'question_two_hop_statement']
show me the projects due on [June 02]	'business communication project 3'	['question_type_global', 'question_two_hop_statement']
How many points did I get on [business communication project 4]	40	['question_type_local']
show all professors	'Vivienne', 'Lucio', 'Emmie', 'Milagros', 'Britney'	['question_type_global', 'question_single_statement']
who did I submit projects late to	'Vivienne', 'Emmie'	['question_type_global', 'question_three_hop_statement']
what homeworks do I have to do?	'business communication homework 1', 'business communication homework 2', 'spanish homework 1', 'spanish homework 2', 'us history homework 1', 'business communication homework 3'	['question_type_global', 'question_single_statement']
list all assignments that i submitted late	'business communication project 1', 'business communication homework 1', 'business communication project 2', 'us history project 2'	['question_type_global', 'question_two_hop_statement']
how many points is [business communication project 1]?	20	['question_type_local']
which projects did I submit?	'business communication project 1', 'us history project 1', 'business communication project 2', 'business communication project 3', 'us history project 2', 'spanish project 1', 'business communication project 4'	['question_type_global', 'question_two_hop_statement']
on which assignments did I get full credit?	'business communication homework 1', 'spanish homework 1', 'spanish project 1', 'business communication project 4'	['question_type_global', 'question_three_hop_statement']
what are all the homeworks due for [Vivienne]?	'business communication homework 1', 'business communication homework 2', 'business communication homework 3'	['question_type_global', 'question_three_hop_statement']
what are the courses for which i submitted late homeworks?	'business communication'	['question_type_global', 'question_two_hop_statement']
there is a new [homework] for [business communication]
[this project] is now due on [June 13]
The deadline of [this homework] is [June 16]
I submitted [business communication homework 4]
what are all the projects due?	'business communication project 1', 'us history project 1', 'business communication project 2', 'business communication project 3', 'us history project 2', 'spanish project 1', 'business communication project 4'	['question_type_global', 'question_single_statement']
which assignments did I submit for [us history]?	'us history project 1', 'us history project 2'	['question_type_global', 'question_two_hop_statement']
which assignments are due after [May 07]?	'business communication project 1', 'business communication homework 1', 'us history project 1', 'business communication project 3', 'spanish homework 1', 'us history project 2', 'spanish project 1', 'business communication project 4', 'business communication homework 4'	['question_type_global', 'question_two_hop_statement']
list all projects that i submitted late	'business communication project 1', 'business communication project 2', 'us history project 2'	['question_type_global', 'question_two_hop_statement']
[business communication] has a new [business communication homework 5] out
[business communication homework 5] is [44] points
[this assignment] is due on [June 17]
which homeworks did I submit for [Milagros]?	'spanish homework 1'	['question_type_global', 'question_three_hop_statement']
which professors did I submit late assignments for?	'Vivienne', 'Emmie'	['question_type_global', 'question_three_hop_statement']
which projects are due after [May 18]?	'business communication project 3', 'us history project 2', 'business communication project 4'	['question_type_global', 'question_two_hop_statement']
I submitted [this assignment] late and received 44 points
which homeworks are due before [June 15]?	'business communication homework 1', 'spanish homework 1'	['question_type_global', 'question_two_hop_statement']
[business communication project 5] is out for [business communication]
[business communication project 5] is [41] points
[this project] is due on [June 27]
How much is [business communication homework 5] worth?	44	['question_type_local']
which courses did I submit late projects for?	'business communication', 'us history'	['question_type_global', 'question_two_hop_statement']
what are all the assignments due?	'business communication project 1', 'business communication homework 1', 'us history project 1', 'business communication project 2', 'business communication project 3', 'business communication homework 2', 'spanish homework 1', 'spanish homework 2', 'us history project 2', 'spanish project 1', 'us history homework 1', 'business communication project 4', 'business communication homework 3', 'business communication homework 4', 'business communication homework 5', 'business communication project 5'	['question_type_global', 'question_single_statement']
which assignments are due after [May 30]?	'business communication project 3', 'business communication project 4', 'business communication homework 4', 'business communication homework 5', 'business communication project 5'	['question_type_global', 'question_two_hop_statement']
which homeworks did I submit late?	'business communication homework 1', 'business communication homework 5'	['question_type_global', 'question_two_hop_statement']
I submitted [us history homework 1] on time and received 46 points
which homeworks did I submit late for [business communication]?	'business communication homework 1', 'business communication homework 5'	['question_type_global', 'question_two_hop_statement']
[spanish homework 3] is released for [spanish]
I submitted [spanish homework 3]
which professors are in the [english] department?	'Lucio', 'Milagros', 'Britney'	['question_type_global', 'question_two_hop_statement']
show me all late homeworks i submitted	'business communication homework 1', 'business communication homework 5'	['question_type_global', 'question_two_hop_statement']
who did I submit projects late to	'Vivienne', 'Emmie'	['question_type_global', 'question_three_hop_statement']
what projects do I have to do for [Milagros]?	'spanish project 1'	['question_type_global', 'question_three_hop_statement']
[business communication homework 6] is released for [business communication]
[business communication homework 6] is worth [12] points
The deadline of [that homework] is [July 26]
I submitted [this assignment] on time and received 12 points
When is the deadline of [business communication homework 1]?	'May 16'	['question_type_local']
show me the assignments due on [May 11]	'business communication project 1'	['question_type_global', 'question_two_hop_statement']
list all homeworks that i submitted for [business communication]	'business communication homework 1', 'business communication homework 4', 'business communication homework 5', 'business communication homework 6'	['question_type_global', 'question_two_hop_statement']
which projects are due after [June 16]?	'business communication project 5'	['question_type_global', 'question_two_hop_statement']
which assignments are due before [June 27]?	'business communication project 1', 'business communication homework 1', 'us history project 1', 'business communication project 3', 'spanish homework 1', 'us history project 2', 'spanish project 1', 'business communication project 4', 'business communication homework 4', 'business communication homework 5'	['question_type_global', 'question_two_hop_statement']
there is a new [homework] for [us history]
I submitted [us history homework 2]
The deadline of [this assignment] is [May 23]
[us history homework 2] is worth [85] points
When is [business communication homework 6] due?	'July 26'	['question_type_local']
which homeworks are due before [May 30]?	'business communication homework 1', 'spanish homework 1', 'us history homework 2'	['question_type_global', 'question_two_hop_statement']
list all homeworks	'business communication homework 1', 'business communication homework 2', 'spanish homework 1', 'spanish homework 2', 'us history homework 1', 'business communication homework 3', 'business communication homework 4', 'business communication homework 5', 'spanish homework 3', 'business communication homework 6', 'us history homework 2'	['question_type_global', 'question_single_statement']
show me all projects i submitted for [business communication]	'business communication project 1', 'business communication project 2', 'business communication project 3', 'business communication project 4'	['question_type_global', 'question_two_hop_statement']
what are the homeworks that i submitted?	'business communication homework 1', 'spanish homework 1', 'us history homework 1', 'business communication homework 4', 'business communication homework 5', 'spanish homework 3', 'business communication homework 6', 'us history homework 2'	['question_type_global', 'question_two_hop_statement']
list all homeworks that i submitted late	'business communication homework 1', 'business communication homework 5'	['question_type_global', 'question_two_hop_statement']
which assignments are due after [June 25]?	'business communication project 5', 'business communication homework 6'	['question_type_global', 'question_two_hop_statement']
what did I get on [business communication homework 6]?	12	['question_type_local']
list all assignments that i submitted for [spanish]	'spanish homework 1', 'spanish project 1', 'spanish homework 3'	['question_type_global', 'question_two_hop_statement']
which homeworks did I submit?	'business communication homework 1', 'spanish homework 1', 'us history homework 1', 'business communication homework 4', 'business communication homework 5', 'spanish homework 3', 'business communication homework 6', 'us history homework 2'	['question_type_global', 'question_two_hop_statement']
show all professors	'Vivienne', 'Lucio', 'Emmie', 'Milagros', 'Britney'	['question_type_global', 'question_single_statement']
show me all late projects i submitted for [Emmie]	'us history project 2'	['question_type_global', 'question_three_hop_statement']
What is [Lucio]'s email	'Lucio@chk.ru'	['question_type_local']
which assignments are due after [June 25]?	'business communication project 5', 'business communication homework 6'	['question_type_global', 'question_two_hop_statement']
what projects did i submit late for [business communication]?	'business communication project 1', 'business communication project 2'	['question_type_global', 'question_two_hop_statement']
which professors did I submit late homeworks for?	'Vivienne'	['question_type_global', 'question_three_hop_statement']
list all assignments	'business communication project 1', 'business communication homework 1', 'us history project 1', 'business communication project 2', 'business communication project 3', 'business communication homework 2', 'spanish homework 1', 'spanish homework 2', 'us history project 2', 'spanish project 1', 'us history homework 1', 'business communication project 4', 'business communication homework 3', 'business communication homework 4', 'business communication homework 5', 'business communication project 5', 'spanish homework 3', 'business communication homework 6', 'us history homework 2'	['question_type_global', 'question_single_statement']
[business communication homework 7] is released for [business communication]
on which assignments did I get full credit?	'business communication homework 1', 'spanish homework 1', 'spanish project 1', 'us history homework 1', 'business communication project 4', 'business communication homework 5', 'business communication homework 6'	['question_type_global', 'question_three_hop_statement']
How many points is [us history project 1] worth?	13	['question_type_local']
what are all the projects due for [Milagros]?	'spanish project 1'	['question_type_global', 'question_three_hop_statement']
what assignments did i submit late for [Vivienne]?	'business communication project 1', 'business communication homework 1', 'business communication project 2', 'business communication homework 5'	['question_type_global', 'question_three_hop_statement']
show me all homeworks i submitted for [Vivienne]	'business communication homework 1', 'business communication homework 4', 'business communication homework 5', 'business communication homework 6'	['question_type_global', 'question_three_hop_statement']
which assignments did I submit?	'business communication project 1', 'business communication homework 1', 'us history project 1', 'business communication project 2', 'business communication project 3', 'spanish homework 1', 'us history project 2', 'spanish project 1', 'us history homework 1', 'business communication project 4', 'business communication homework 4', 'business communication homework 5', 'spanish homework 3', 'business communication homework 6', 'us history homework 2'	['question_type_global', 'question_two_hop_statement']
what are the late projects that i submitted?	'business communication project 1', 'business communication project 2', 'us history project 2'	['question_type_global', 'question_two_hop_statement']
which assignments are due before [May 15]?	'business communication project 1', 'us history project 1', 'spanish project 1'	['question_type_global', 'question_two_hop_statement']
which projects are due after [May 28]?	'business communication project 3', 'business communication project 4', 'business communication project 5'	['question_type_global', 'question_two_hop_statement']
The deadline of [us history homework 2] moved to [May 21]
how many points is [business communication project 3]?	95	['question_type_local']
show all professors	'Vivienne', 'Lucio', 'Emmie', 'Milagros', 'Britney'	['question_type_global', 'question_single_statement']
How many points is [business communication homework 6] worth?	12	['question_type_local']
show me all courses for which i submitted at least one late assignment	'business communication', 'us history'	['question_type_global', 'question_two_hop_statement']
who did I submit homeworks late to	'Vivienne'	['question_type_global', 'question_three_hop_statement']
which assignments are due after [June 14]?	'business communication homework 4', 'business communication homework 5', 'business communication project 5', 'business communication homework 6'	['question_type_global', 'question_two_hop_statement']
which assignments are due after [May 15]?	'business communication homework 1', 'business communication project 3', 'spanish homework 1', 'us history project 2', 'business communication project 4', 'business communication homework 4', 'business communication homework 5', 'business communication project 5', 'business communication homework 6', 'us history homework 2'	['question_type_global', 'question_two_hop_statement']
list the professors in the [english] department	'Lucio', 'Milagros', 'Britney'	['question_type_global', 'question_two_hop_statement']
What is [business communication homework 1] on?	'The Senses'	['question_type_local']
list all assignments for [business communication]	'business communication project 1', 'business communication project 2', 'business communication project 3', 'business communication project 4', 'business communication project 5'	['question_type_global', 'question_two_hop_statement']
which projects are due after [June 02]?	'business communication project 4', 'business communication project 5'	['question_type_global', 'question_two_hop_statement']
what are all the assignments due for [business communication]?	'business communication project 1', 'business communication project 2', 'business communication project 3', 'business communication project 4', 'business communication project 5'	['question_type_global', 'question_two_hop_statement']
The deadline of [business communication project 3] moved to [June 03]
How much is [spanish homework 1] worth?	54	['question_type_local']
what are the projects that i submitted for [us history]	'us history project 1', 'us history project 2'	['question_type_global', 'question_two_hop_statement']
what projects did i submit late for [business communication]?	'business communication project 1', 'business communication project 2'	['question_type_global', 'question_two_hop_statement']
show me all late projects i submitted for [us history]	'us history project 2'	['question_type_global', 'question_two_hop_statement']
list all homeworks for [business communication]	'business communication homework 1', 'business communication homework 2', 'business communication homework 3', 'business communication homework 4', 'business communication homework 5', 'business communication homework 6', 'business communication homework 7'	['question_type_global', 'question_two_hop_statement']
what instructors did i have late homeworks for?	'Vivienne'	['question_type_global', 'question_three_hop_statement']
The deadline of [business communication project 2] is [May 17]
When is the deadline of [business communication project 5]?	'June 27'	['question_type_local']
list all homeworks	'business communication homework 1', 'business communication homework 2', 'spanish homework 1', 'spanish homework 2', 'us history homework 1', 'business communication homework 3', 'business communication homework 4', 'business communication homework 5', 'spanish homework 3', 'business communication homework 6', 'us history homework 2', 'business communication homework 7'	['question_type_global', 'question_single_statement']
list all the professors	'Vivienne', 'Lucio', 'Emmie', 'Milagros', 'Britney'	['question_type_global', 'question_single_statement']
how many points did I receive on [business communication project 4]?	40	['question_type_local']
what are the courses for which I submitted homeworks late	'business communication'	['question_type_global', 'question_two_hop_statement']
who did I submit homeworks late to	'Vivienne'	['question_type_global', 'question_three_hop_statement']
which homeworks are due after [May 14]?	'business communication homework 1', 'spanish homework 1', 'business communication homework 4', 'business communication homework 5', 'business communication homework 6', 'us history homework 2'	['question_type_global', 'question_two_hop_statement']
show me all assignments that i submitted for [Vivienne]	'business communication project 1', 'business communication homework 1', 'business communication project 2', 'business communication project 3', 'business communication project 4', 'business communication homework 4', 'business communication homework 5', 'business communication homework 6'	['question_type_global', 'question_three_hop_statement']
What is [us history project 1] on?	'introduction'	['question_type_local']
show me all homeworks i submitted	'business communication homework 1', 'spanish homework 1', 'us history homework 1', 'business communication homework 4', 'business communication homework 5', 'spanish homework 3', 'business communication homework 6', 'us history homework 2'	['question_type_global', 'question_two_hop_statement']
what assignments do I have to do for [spanish]?	'spanish project 1'	['question_type_global', 'question_two_hop_statement']
list projects that are due on [May 13]	'spanish project 1'	['question_type_global', 'question_two_hop_statement']
How many points did I get on [business communication homework 5]	44	['question_type_local']
which homeworks are due after [June 20]?	'business communication homework 6'	['question_type_global', 'question_two_hop_statement']
What courses is [Vivienne] teaching?	'business communication'	['question_type_local']
which projects did I submit late?	'business communication project 1', 'business communication project 2', 'us history project 2'	['question_type_global', 'question_two_hop_statement']
who are the instructors to whom i submitted any late projects?	'Vivienne', 'Emmie'	['question_type_global', 'question_three_hop_statement']
list all homeworks for [Milagros]	'spanish homework 1', 'spanish homework 2', 'spanish homework 3'	['question_type_global', 'question_three_hop_statement']
List all assignments for [us history]	'us history project 1', 'us history project 2', 'us history homework 1', 'us history homework 2'	['question_type_local']
what are the assignments that i submitted for [us history]	'us history project 1', 'us history project 2', 'us history homework 1', 'us history homework 2'	['question_type_global', 'question_two_hop_statement']
how many points did I receive on [spanish project 1]?	93	['question_type_local']
what homeworks do I have to do for [spanish]?	'spanish homework 1', 'spanish homework 2', 'spanish homework 3'	['question_type_global', 'question_two_hop_statement']
what courses did i have late projects for?	'business communication', 'us history'	['question_type_global', 'question_two_hop_statement']
which courses did I submit late homeworks for?	'business communication'	['question_type_global', 'question_two_hop_statement']
what are the assignments that i submitted for [Emmie]	'us history project 1', 'us history project 2', 'us history homework 1', 'us history homework 2'	['question_type_global', 'question_three_hop_statement']
who are the instructors to whom i submitted late homeworks?	'Vivienne'	['question_type_global', 'question_three_hop_statement']
what projects did i submit for [Vivienne]?	'business communication project 1', 'business communication project 2', 'business communication project 3', 'business communication project 4'	['question_type_global', 'question_three_hop_statement']
list the professors in the [math] department	'Vivienne', 'Emmie'	['question_type_global', 'question_two_hop_statement']
list all homeworks that i submitted	'business communication homework 1', 'spanish homework 1', 'us history homework 1', 'business communication homework 4', 'business communication homework 5', 'spanish homework 3', 'business communication homework 6', 'us history homework 2'	['question_type_global', 'question_two_hop_statement']
what projects did i submit for [us history]?	'us history project 1', 'us history project 2'	['question_type_global', 'question_two_hop_statement']
what are the assignments that i submitted for [Milagros]	'spanish homework 1', 'spanish project 1', 'spanish homework 3'	['question_type_global', 'question_three_hop_statement']
When is [business communication project 4] due?	'June 13'	['question_type_local']
which assignments are due on [June 03]?	'business communication project 3'	['question_type_global', 'question_two_hop_statement']
list all homeworks that i submitted late	'business communication homework 1', 'business communication homework 5'	['question_type_global', 'question_two_hop_statement']
show me all projects i submitted	'business communication project 1', 'us history project 1', 'business communication project 2', 'business communication project 3', 'us history project 2', 'spanish project 1', 'business communication project 4'	['question_type_global', 'question_two_hop_statement']
what assignments did i submit for [business communication]?	'business communication project 1', 'business communication homework 1', 'business communication project 2', 'business communication project 3', 'business communication project 4', 'business communication homework 4', 'business communication homework 5', 'business communication homework 6'	['question_type_global', 'question_two_hop_statement']
what are the courses for which i submitted late assignments?	'business communication', 'us history'	['question_type_global', 'question_two_hop_statement']
What courses is [Vivienne] teaching?	'business communication'	['question_type_local']
what are the projects that i submitted?	'business communication project 1', 'us history project 1', 'business communication project 2', 'business communication project 3', 'us history project 2', 'spanish project 1', 'business communication project 4'	['question_type_global', 'question_two_hop_statement']
show all professors	'Vivienne', 'Lucio', 'Emmie', 'Milagros', 'Britney'	['question_type_global', 'question_single_statement']
When is [spanish project 1] due?	'May 13'	['question_type_local']
list all homeworks for [spanish]	'spanish homework 1', 'spanish homework 2', 'spanish homework 3'	['question_type_global', 'question_two_hop_statement']
what projects do I have to do for [Milagros]?	'spanish project 1'	['question_type_global', 'question_three_hop_statement']
show me all homeworks i submitted	'business communication homework 1', 'spanish homework 1', 'us history homework 1', 'business communication homework 4', 'business communication homework 5', 'spanish homework 3', 'business communication homework 6', 'us history homework 2'	['question_type_global', 'question_two_hop_statement']
which homeworks did I submit for [us history]?	'us history homework 1', 'us history homework 2'	['question_type_global', 'question_two_hop_statement']
which projects are due after [May 18]?	'business communication project 3', 'us history project 2', 'business communication project 4', 'business communication project 5'	['question_type_global', 'question_two_hop_statement']
what are all the assignments due for [us history]?	'us history project 1', 'us history project 2'	['question_type_global', 'question_two_hop_statement']
how many points is [spanish homework 1]?	54	['question_type_local']
who did I submit homeworks late to	'Vivienne'	['question_type_global', 'question_three_hop_statement']
what are the late homeworks that i submitted?	'business communication homework 1', 'business communication homework 5'	['question_type_global', 'question_two_hop_statement']
what projects do I have to do for [Emmie]?	'us history project 1', 'us history project 2'	['question_type_global', 'question_three_hop_statement']
[business communication] has a new [business communication homework 8] out
Show me all homeworks due for [spanish]	'spanish homework 1', 'spanish homework 2', 'spanish homework 3'	['question_type_local']
what are the late assignments that i submitted	'business communication project 1', 'business communication homework 1', 'business communication project 2', 'us history project 2', 'business communication homework 5'	['question_type_global', 'question_two_hop_statement']
what courses did i have late homeworks for?	'business communication'	['question_type_global', 'question_two_hop_statement']
show me all the late assignments that i submitted	'business communication project 1', 'business communication homework 1', 'business communication project 2', 'us history project 2', 'business communication homework 5'	['question_type_global', 'question_two_hop_statement']
