create a [professor] named [Tom]
[he]'s office is [G969]
[that person] is affiliated with the [animal science] department
change [that person]'s department to [electrical engineering]
create a [professor] named [Eun]
[Eun] is in [G969]
which professors are in the [None] department?	'Eun'	['question_type_global', 'question_two_hop_statement']
[this professor] is affiliated with the [electrical engineering] department
What office is [Tom] in?	'G969'	['question_type_local']
create a [professor] named [Hanna]
[Hanna]'s department is [applied physics]
[this person]'s office is [SP 098]
create a [professor] named [Lucio]
[he] is in [G969]
What is [Tom]'s office?	'G969'	['question_type_local']
[this person]'s department is [electrical engineering]
What department is [Eun] affiliated with?	'electrical engineering'	['question_type_local']
change [that person]'s department to [neuroscience]
What is [Tom]'s department?	'electrical engineering'	['question_type_local']
show all professors	'Tom', 'Eun', 'Hanna', 'Lucio'	['question_type_global', 'question_single_statement']
change [this professor]'s department to [electrical engineering]
Which department is [Eun] in?	'electrical engineering'	['question_type_local']
What office is [Lucio] in?	'G969'	['question_type_local']
What is [Eun]'s office?	'G969'	['question_type_local']
[this person]'s department is now [applied physics]
I am taking a course called [spanish]
I am taking a [sociology] course
[Hanna] is the instructor for [sociology]
What is [this professor]'s department?	'applied physics'	['question_type_local']
What office is [Eun] in?	'G969'	['question_type_local']
What is [Eun]'s department?	'electrical engineering'	['question_type_local']
What office is [she] in?	'SP 098'	['question_type_local']
there is new [sociology homework 1] for [that course]
[this assignment] is worth [33] points
[sociology homework 1] is about [k means]
I submitted [sociology homework 1] late and received 32 points
what are the assignments that i submitted for [sociology]	'sociology homework 1'	['question_type_global', 'question_two_hop_statement']
[sociology] has a new [sociology project 1] out
[spanish] has a new [spanish homework 1] released
[sociology project 1] is about [unsupervised learning]
I submitted [that project]
create a [professor] named [Gabrielle]
[sociology project 1] is due on [May 31]
[that assignment] is worth [79] points
there is a [professor] named [Lucy]
[she] is in [SP 098]
[this professor]'s department is [applied physics]
list all homeworks for [Hanna]	'sociology homework 1'	['question_type_global', 'question_three_hop_statement']
list all assignments	'sociology homework 1', 'sociology project 1', 'spanish homework 1'	['question_type_global', 'question_single_statement']
[sociology] has a new [sociology homework 2] out
The topic of [this assignment] is [kernels]
What department is [Lucy] affiliated with?	'applied physics'	['question_type_local']
list all projects for [Hanna]	'sociology project 1'	['question_type_global', 'question_three_hop_statement']
who are the instructors to whom i submitted late homeworks?	'Hanna'	['question_type_global', 'question_three_hop_statement']
show me all late homeworks i submitted for [Hanna]	'sociology homework 1'	['question_type_global', 'question_three_hop_statement']
show me all assignments i submitted	'sociology homework 1', 'sociology project 1'	['question_type_global', 'question_two_hop_statement']
[sociology homework 1] is due on [June 01]
What are the assignments for [sociology]?	'sociology homework 1', 'sociology project 1', 'sociology homework 2'	['question_type_local']
list assignments that are due on [May 31]	'sociology project 1'	['question_type_global', 'question_two_hop_statement']
How many points is [sociology project 1] worth?	79	['question_type_local']
The deadline of [sociology homework 1] moved to [May 31]
what courses did i have late homeworks for?	'sociology'	['question_type_global', 'question_two_hop_statement']
What are the homeworks for [sociology]?	'sociology homework 1', 'sociology homework 2'	['question_type_local']
list all homeworks for [sociology]	'sociology homework 1', 'sociology homework 2'	['question_type_global', 'question_two_hop_statement']
list all the professors	'Tom', 'Eun', 'Hanna', 'Lucio', 'Gabrielle', 'Lucy'	['question_type_global', 'question_single_statement']
What is [Eun]'s office?	'G969'	['question_type_local']
show me all projects i submitted for [Hanna]	'sociology project 1'	['question_type_global', 'question_three_hop_statement']
[spanish homework 2] is released for [spanish]
[spanish homework 2] is [48] points
[this homework] is due on [June 07]
which courses did I submit late homeworks for?	'sociology'	['question_type_global', 'question_two_hop_statement']
what projects do I have to do?	'sociology project 1'	['question_type_global', 'question_single_statement']
I submitted [sociology homework 2] on time
list all homeworks that i submitted late	'sociology homework 1'	['question_type_global', 'question_two_hop_statement']
what assignments did i submit late for [sociology]?	'sociology homework 1'	['question_type_global', 'question_two_hop_statement']
what are the projects that i submitted?	'sociology project 1'	['question_type_global', 'question_two_hop_statement']
which homeworks are due before [June 01]?	'sociology homework 1'	['question_type_global', 'question_two_hop_statement']
I am taking a [business communication] course
[that assignment] is due on [June 11]
who are the professors affiliated with [None]?	'Gabrielle'	['question_type_global', 'question_two_hop_statement']
which assignments are due on [May 31]?	'sociology homework 1', 'sociology project 1'	['question_type_global', 'question_two_hop_statement']
[sociology project 2] is out for [sociology]
list all assignments that i submitted late for [sociology]	'sociology homework 1'	['question_type_global', 'question_two_hop_statement']
who are the instructors to whom i submitted any late assignments?	'Hanna'	['question_type_global', 'question_three_hop_statement']
show me all projects i submitted for [Hanna]	'sociology project 1'	['question_type_global', 'question_three_hop_statement']
[that homework] is worth [61] points
what assignments did i submit late?	'sociology homework 1'	['question_type_global', 'question_two_hop_statement']
show me all courses for which i submitted at least one late assignment	'sociology'	['question_type_global', 'question_two_hop_statement']
[that project] is [15] points
The topic of [this project] is [Genetics]
The topic of [spanish homework 2] is [deep learning]
I submitted [that homework] on time and received 48 points
The deadline of [this assignment] moved to [June 04]
The deadline of [this assignment] moved to [June 07]
list all assignments	'sociology homework 1', 'sociology project 1', 'spanish homework 1', 'sociology homework 2', 'spanish homework 2', 'sociology project 2'	['question_type_global', 'question_single_statement']
what are the homeworks that i submitted for [Hanna]	'sociology homework 1', 'sociology homework 2'	['question_type_global', 'question_three_hop_statement']
which homeworks are due before [June 09]?	'sociology homework 1', 'spanish homework 2'	['question_type_global', 'question_two_hop_statement']
which professors are in the [None] department?	'Gabrielle'	['question_type_global', 'question_two_hop_statement']
[Gabrielle] is affiliated with the [electrical engineering] department
[she]'s office is [SP 098]
I am taking a course called [math]
What is [Hanna]'s office?	'SP 098'	['question_type_local']
who are the instructors to whom i submitted late homeworks?	'Hanna'	['question_type_global', 'question_three_hop_statement']
[spanish project 1] is released for [spanish]
[that course] is taught by [Lucy]
How many points is [sociology project 1] worth?	79	['question_type_local']
what are all the projects due?	'sociology project 1', 'sociology project 2', 'spanish project 1'	['question_type_global', 'question_single_statement']
How much is [sociology project 1] worth?	79	['question_type_local']
which assignments are due on [June 07]?	'spanish homework 2'	['question_type_global', 'question_two_hop_statement']
list all projects that i submitted	'sociology project 1'	['question_type_global', 'question_two_hop_statement']
there is new [spanish project 2] for [spanish]
[spanish project 2] is worth [42] points
I submitted [that assignment] and received 36 points
who are the professors?	'Tom', 'Eun', 'Hanna', 'Lucio', 'Gabrielle', 'Lucy'	['question_type_global', 'question_single_statement']
which projects did I submit for [spanish]?	'spanish project 2'	['question_type_global', 'question_two_hop_statement']
How many points did I get on [spanish homework 2]	48	['question_type_local']
The deadline of [spanish project 2] is [June 17]
list all homeworks that i submitted late	'sociology homework 1'	['question_type_global', 'question_two_hop_statement']
What office is [Lucio] in?	'G969'	['question_type_local']
what are the late assignments that i submitted	'sociology homework 1'	['question_type_global', 'question_two_hop_statement']
what assignments do I have to do?	'sociology homework 1', 'sociology project 1', 'spanish homework 1', 'sociology homework 2', 'spanish homework 2', 'sociology project 2', 'spanish project 1', 'spanish project 2'	['question_type_global', 'question_single_statement']
List all assignments for [spanish]	'spanish homework 1', 'spanish homework 2', 'spanish project 1', 'spanish project 2'	['question_type_local']
what are the assignments that i submitted for [sociology]	'sociology homework 1', 'sociology project 1', 'sociology homework 2'	['question_type_global', 'question_two_hop_statement']
what homeworks do I have to do?	'sociology homework 1', 'spanish homework 1', 'sociology homework 2', 'spanish homework 2'	['question_type_global', 'question_single_statement']
what assignments did i submit for [sociology]?	'sociology homework 1', 'sociology project 1', 'sociology homework 2'	['question_type_global', 'question_two_hop_statement']
which assignments did I submit for [Hanna]?	'sociology homework 1', 'sociology project 1', 'sociology homework 2'	['question_type_global', 'question_three_hop_statement']
list all assignments that i submitted late	'sociology homework 1'	['question_type_global', 'question_two_hop_statement']
Show me all assignments due for [sociology]	'sociology homework 1', 'sociology project 1', 'sociology homework 2', 'sociology project 2'	['question_type_local']
what are the projects that i submitted?	'sociology project 1', 'spanish project 2'	['question_type_global', 'question_two_hop_statement']
which projects are due on [June 17]?	'spanish project 2'	['question_type_global', 'question_two_hop_statement']
What office is [Lucio] in?	'G969'	['question_type_local']
show me all the late assignments that i submitted	'sociology homework 1'	['question_type_global', 'question_two_hop_statement']
list all homeworks that i submitted	'sociology homework 1', 'sociology homework 2', 'spanish homework 2'	['question_type_global', 'question_two_hop_statement']
[Milagros] is a [professor]
the affiliation of [that person] is [electrical engineering]
What is the topic of [sociology project 2]?	'Genetics'	['question_type_local']
what assignments did i submit late?	'sociology homework 1'	['question_type_global', 'question_two_hop_statement']
which projects are due before [June 06]?	'sociology project 1'	['question_type_global', 'question_two_hop_statement']
list all projects	'sociology project 1', 'sociology project 2', 'spanish project 1', 'spanish project 2'	['question_type_global', 'question_single_statement']
which assignments are due after [June 09]?	'sociology homework 2', 'spanish project 2'	['question_type_global', 'question_two_hop_statement']
[that professor]'s office is [G969]
what did I get on [spanish homework 2]?	48	['question_type_local']
list all homeworks	'sociology homework 1', 'spanish homework 1', 'sociology homework 2', 'spanish homework 2'	['question_type_global', 'question_single_statement']
which homeworks are due before [June 12]?	'sociology homework 1', 'sociology homework 2', 'spanish homework 2'	['question_type_global', 'question_two_hop_statement']
change [Milagros]'s department to [applied physics]
show all professors	'Tom', 'Eun', 'Hanna', 'Lucio', 'Gabrielle', 'Lucy', 'Milagros'	['question_type_global', 'question_single_statement']
How much is [sociology project 1] worth?	79	['question_type_local']
show me all late homeworks i submitted	'sociology homework 1'	['question_type_global', 'question_two_hop_statement']
who are the professors affiliated with [applied physics]?	'Hanna', 'Lucio', 'Lucy', 'Milagros'	['question_type_global', 'question_two_hop_statement']
how many points is [sociology homework 2]?	61	['question_type_local']
which assignments are due before [June 06]?	'sociology homework 1', 'sociology project 1'	['question_type_global', 'question_two_hop_statement']
which homeworks are due on [June 07]?	'spanish homework 2'	['question_type_global', 'question_two_hop_statement']
which assignments are due on [June 11]?	'sociology homework 2'	['question_type_global', 'question_two_hop_statement']
How much is [spanish project 2] worth?	42	['question_type_local']
what are all the homeworks due?	'sociology homework 1', 'spanish homework 1', 'sociology homework 2', 'spanish homework 2'	['question_type_global', 'question_single_statement']
what assignments do I have to do for [Hanna]?	'sociology homework 1', 'sociology project 1', 'sociology homework 2', 'sociology project 2'	['question_type_global', 'question_three_hop_statement']
what did I get on [sociology homework 1]?	32	['question_type_local']
which projects are due before [June 02]?	'sociology project 1'	['question_type_global', 'question_two_hop_statement']
what assignments did i submit late?	'sociology homework 1'	['question_type_global', 'question_two_hop_statement']
what projects do I have to do?	'sociology project 1', 'sociology project 2', 'spanish project 1', 'spanish project 2'	['question_type_global', 'question_single_statement']
what are all the homeworks due for [Hanna]?	'sociology homework 1', 'sociology homework 2'	['question_type_global', 'question_three_hop_statement']
which projects are due before [June 07]?	'sociology project 1'	['question_type_global', 'question_two_hop_statement']
Which professor is teaching [math]?	'Lucy'	['question_type_local']
which projects are due before [June 18]?	'sociology project 1', 'spanish project 2'	['question_type_global', 'question_two_hop_statement']
which professors are in the [applied physics] department?	'Hanna', 'Lucio', 'Lucy', 'Milagros'	['question_type_global', 'question_two_hop_statement']
which assignments did I submit for [spanish]?	'spanish homework 2', 'spanish project 2'	['question_type_global', 'question_two_hop_statement']
which assignments did I submit late?	'sociology homework 1'	['question_type_global', 'question_two_hop_statement']
list all assignments for [Hanna]	'sociology homework 1', 'sociology project 1', 'sociology homework 2', 'sociology project 2'	['question_type_global', 'question_three_hop_statement']
which assignments are due on [June 07]?	'spanish homework 2'	['question_type_global', 'question_two_hop_statement']
on which assignments did I get full credit?	'spanish homework 2'	['question_type_global', 'question_three_hop_statement']
what are the projects that i submitted for [spanish]	'spanish project 2'	['question_type_global', 'question_two_hop_statement']
how many points did I receive on [spanish project 2]?	36	['question_type_local']
what are all the homeworks due?	'sociology homework 1', 'spanish homework 1', 'sociology homework 2', 'spanish homework 2'	['question_type_global', 'question_single_statement']
list all assignments for [sociology]	'sociology project 1', 'sociology project 2'	['question_type_global', 'question_two_hop_statement']
which projects are due on [June 17]?	'spanish project 2'	['question_type_global', 'question_two_hop_statement']
[she]'s department is now [neuroscience]
How many points is [spanish homework 2] worth?	48	['question_type_local']
show me all homeworks i submitted for [Hanna]	'sociology homework 1', 'sociology homework 2'	['question_type_global', 'question_three_hop_statement']
which homeworks did I submit?	'sociology homework 1', 'sociology homework 2', 'spanish homework 2'	['question_type_global', 'question_two_hop_statement']
what courses did i have late homeworks for?	'sociology'	['question_type_global', 'question_two_hop_statement']
[sociology] has a new [sociology project 3] released
what are all the assignments due for [Hanna]?	'sociology homework 1', 'sociology project 1', 'sociology homework 2', 'sociology project 2', 'sociology project 3'	['question_type_global', 'question_three_hop_statement']
what are the late homeworks that i submitted?	'sociology homework 1'	['question_type_global', 'question_two_hop_statement']
what assignments did i submit?	'sociology homework 1', 'sociology project 1', 'sociology homework 2', 'spanish homework 2', 'spanish project 2'	['question_type_global', 'question_two_hop_statement']
what projects did i submit for [Hanna]?	'sociology project 1'	['question_type_global', 'question_three_hop_statement']
[spanish homework 3] is released for [spanish]
I submitted [this project]
What is [Tom]'s office?	'G969'	['question_type_local']
what assignments did i submit late?	'sociology homework 1'	['question_type_global', 'question_two_hop_statement']
[this homework] is due on [June 20]
how much did I get on [spanish project 2]?	36	['question_type_local']
show me all assignments i submitted for [spanish]	'spanish homework 2', 'spanish project 2'	['question_type_global', 'question_two_hop_statement']
which assignments are due on [June 17]?	'spanish project 2'	['question_type_global', 'question_two_hop_statement']
[this project] is due on [June 26]
[sociology project 3] is worth [49] points
who are the professors?	'Tom', 'Eun', 'Hanna', 'Lucio', 'Gabrielle', 'Lucy', 'Milagros'	['question_type_global', 'question_single_statement']
which assignments are due before [June 17]?	'sociology homework 1', 'sociology project 1', 'sociology homework 2', 'spanish homework 2'	['question_type_global', 'question_two_hop_statement']
show me all assignments that i submitted for [Hanna]	'sociology homework 1', 'sociology project 1', 'sociology homework 2', 'sociology project 3'	['question_type_global', 'question_three_hop_statement']
What courses is [Hanna] teaching?	'sociology'	['question_type_local']
Show me all assignments due for [spanish]	'spanish homework 1', 'spanish homework 2', 'spanish project 1', 'spanish project 2', 'spanish homework 3'	['question_type_local']
list all assignments	'sociology homework 1', 'sociology project 1', 'spanish homework 1', 'sociology homework 2', 'spanish homework 2', 'sociology project 2', 'spanish project 1', 'spanish project 2', 'sociology project 3', 'spanish homework 3'	['question_type_global', 'question_single_statement']
what courses did i have late assignments for?	'sociology'	['question_type_global', 'question_two_hop_statement']
which homeworks are due on [June 07]?	'spanish homework 2'	['question_type_global', 'question_two_hop_statement']
what homeworks did i submit late for [Hanna]?	'sociology homework 1'	['question_type_global', 'question_three_hop_statement']
list all assignments that i submitted late	'sociology homework 1'	['question_type_global', 'question_two_hop_statement']
[sociology] has a new [sociology project 4] released
Which department is [Tom] in?	'electrical engineering'	['question_type_local']
list all homeworks	'sociology homework 1', 'spanish homework 1', 'sociology homework 2', 'spanish homework 2', 'spanish homework 3'	['question_type_global', 'question_single_statement']
I submitted [sociology project 4] on time
[that assignment] is worth [98] points
When is the deadline of [sociology project 1]?	'May 31'	['question_type_local']
what assignments did i submit?	'sociology homework 1', 'sociology project 1', 'sociology homework 2', 'spanish homework 2', 'spanish project 2', 'sociology project 3', 'sociology project 4'	['question_type_global', 'question_two_hop_statement']
show me all assignments that i submitted for [Hanna]	'sociology homework 1', 'sociology project 1', 'sociology homework 2', 'sociology project 3', 'sociology project 4'	['question_type_global', 'question_three_hop_statement']
what are all the assignments due for [sociology]?	'sociology project 1', 'sociology project 2', 'sociology project 3', 'sociology project 4'	['question_type_global', 'question_two_hop_statement']
[business communication] has a new [business communication project 1] released
[spanish homework 4] is out for [spanish]
The deadline of [that project] is [June 02]
which assignments are due after [June 11]?	'spanish project 2', 'sociology project 3', 'spanish homework 3'	['question_type_global', 'question_two_hop_statement']
which homeworks did I submit for [sociology]?	'sociology homework 1', 'sociology homework 2'	['question_type_global', 'question_two_hop_statement']
list the professors in the [neuroscience] department	'Milagros'	['question_type_global', 'question_two_hop_statement']
The deadline of [sociology project 3] moved to [June 27]
[business communication project 1] is [71] points
which projects did I submit?	'sociology project 1', 'spanish project 2', 'sociology project 3', 'sociology project 4'	['question_type_global', 'question_two_hop_statement']
list all assignments that i submitted for [Hanna]	'sociology homework 1', 'sociology project 1', 'sociology homework 2', 'sociology project 3', 'sociology project 4'	['question_type_global', 'question_three_hop_statement']
which assignments are due after [June 04]?	'sociology homework 2', 'spanish homework 2', 'spanish project 2', 'sociology project 3', 'spanish homework 3'	['question_type_global', 'question_two_hop_statement']
show me all courses for which i submitted at least one late homework	'sociology'	['question_type_global', 'question_two_hop_statement']
list all assignments that i submitted for [sociology]	'sociology homework 1', 'sociology project 1', 'sociology homework 2', 'sociology project 3', 'sociology project 4'	['question_type_global', 'question_two_hop_statement']
[business communication] is taught by [Eun]
how many points did I receive on [spanish homework 2]?	48	['question_type_local']
what are the late homeworks that i submitted for [Hanna]	'sociology homework 1'	['question_type_global', 'question_three_hop_statement']
change [Lucy]'s department to [neuroscience]
how many points is [sociology project 3]?	49	['question_type_local']
which assignments are due before [June 05]?	'sociology homework 1', 'sociology project 1', 'business communication project 1'	['question_type_global', 'question_two_hop_statement']
which assignments are due after [June 20]?	'sociology project 3'	['question_type_global', 'question_two_hop_statement']
what homeworks do I have to do for [spanish]?	'spanish homework 1', 'spanish homework 2', 'spanish homework 3', 'spanish homework 4'	['question_type_global', 'question_two_hop_statement']
show me all late homeworks i submitted for [sociology]	'sociology homework 1'	['question_type_global', 'question_two_hop_statement']
list all homeworks	'sociology homework 1', 'spanish homework 1', 'sociology homework 2', 'spanish homework 2', 'spanish homework 3', 'spanish homework 4'	['question_type_global', 'question_single_statement']
what are the late assignments that i submitted	'sociology homework 1'	['question_type_global', 'question_two_hop_statement']
what are the assignments that i submitted for [sociology]	'sociology homework 1', 'sociology project 1', 'sociology homework 2', 'sociology project 3', 'sociology project 4'	['question_type_global', 'question_two_hop_statement']
Which department is [Lucy] in?	'neuroscience'	['question_type_local']
which homeworks did I submit for [spanish]?	'spanish homework 2'	['question_type_global', 'question_two_hop_statement']
which assignments did I submit?	'sociology homework 1', 'sociology project 1', 'sociology homework 2', 'spanish homework 2', 'spanish project 2', 'sociology project 3', 'sociology project 4'	['question_type_global', 'question_two_hop_statement']
what courses did i have late homeworks for?	'sociology'	['question_type_global', 'question_two_hop_statement']
The deadline of [sociology homework 2] moved to [June 08]
list all projects for [spanish]	'spanish project 1', 'spanish project 2'	['question_type_global', 'question_two_hop_statement']
which homeworks are due after [June 11]?	'spanish homework 3'	['question_type_global', 'question_two_hop_statement']
there is new [spanish project 3] for [spanish]
[this project] is [29] points
I submitted [spanish project 3] late and received 29 points
The deadline of [that assignment] is [July 05]
list all assignments that i submitted late	'sociology homework 1', 'spanish project 3'	['question_type_global', 'question_two_hop_statement']
which assignments did I submit for [Hanna]?	'sociology homework 1', 'sociology project 1', 'sociology homework 2', 'sociology project 3', 'sociology project 4'	['question_type_global', 'question_three_hop_statement']
Which department is [Eun] in?	'electrical engineering'	['question_type_local']
who did I submit assignments late to	'Hanna'	['question_type_global', 'question_three_hop_statement']
[sociology project 4] is due on [July 15]
what are the homeworks that i submitted for [sociology]	'sociology homework 1', 'sociology homework 2'	['question_type_global', 'question_two_hop_statement']
show me all courses for which i submitted at least one late project	'spanish'	['question_type_global', 'question_two_hop_statement']
which projects are due after [June 07]?	'spanish project 2', 'sociology project 3', 'sociology project 4', 'spanish project 3'	['question_type_global', 'question_two_hop_statement']
what are all the assignments due for [Hanna]?	'sociology homework 1', 'sociology project 1', 'sociology homework 2', 'sociology project 2', 'sociology project 3', 'sociology project 4'	['question_type_global', 'question_three_hop_statement']
how much did I get on [spanish project 3]?	29	['question_type_local']
what are the late projects that i submitted for [spanish]	'spanish project 3'	['question_type_global', 'question_two_hop_statement']
[business communication homework 1] is released for [business communication]
there is new [business communication project 2] for [business communication]
I submitted [that homework] on time
[that homework] is [30] points
[business communication homework 1] is due on [June 05]
which homeworks are due after [June 10]?	'spanish homework 3'	['question_type_global', 'question_two_hop_statement']
what did I get on [sociology homework 1]?	32	['question_type_local']
what assignments did i submit for [Hanna]?	'sociology homework 1', 'sociology project 1', 'sociology homework 2', 'sociology project 3', 'sociology project 4'	['question_type_global', 'question_three_hop_statement']
How many points is [spanish project 3] worth?	29	['question_type_local']
list all assignments	'sociology homework 1', 'sociology project 1', 'spanish homework 1', 'sociology homework 2', 'spanish homework 2', 'sociology project 2', 'spanish project 1', 'spanish project 2', 'sociology project 3', 'spanish homework 3', 'sociology project 4', 'business communication project 1', 'spanish homework 4', 'spanish project 3', 'business communication homework 1', 'business communication project 2'	['question_type_global', 'question_single_statement']
which courses did I submit late projects for?	'spanish'	['question_type_global', 'question_two_hop_statement']
which projects are due after [July 04]?	'sociology project 4', 'spanish project 3'	['question_type_global', 'question_two_hop_statement']
there is a new [project] for [business communication]
how many points did I receive on [sociology homework 1]?	32	['question_type_local']
which homeworks are due after [June 02]?	'sociology homework 2', 'spanish homework 2', 'spanish homework 3', 'business communication homework 1'	['question_type_global', 'question_two_hop_statement']
which projects are due after [June 06]?	'spanish project 2', 'sociology project 3', 'sociology project 4', 'spanish project 3'	['question_type_global', 'question_two_hop_statement']
list all projects for [Hanna]	'sociology project 1', 'sociology project 2', 'sociology project 3', 'sociology project 4'	['question_type_global', 'question_three_hop_statement']
which assignments are due after [June 18]?	'sociology project 3', 'spanish homework 3', 'sociology project 4', 'spanish project 3'	['question_type_global', 'question_two_hop_statement']
How many points did I get on [spanish project 2]	36	['question_type_local']
show me the assignments due on [July 15]	'sociology project 4'	['question_type_global', 'question_two_hop_statement']
what are the late homeworks that i submitted?	'sociology homework 1'	['question_type_global', 'question_two_hop_statement']
list all homeworks	'sociology homework 1', 'spanish homework 1', 'sociology homework 2', 'spanish homework 2', 'spanish homework 3', 'spanish homework 4', 'business communication homework 1'	['question_type_global', 'question_single_statement']
which homeworks did I submit late?	'sociology homework 1'	['question_type_global', 'question_two_hop_statement']
which assignments did I submit for [Hanna]?	'sociology homework 1', 'sociology project 1', 'sociology homework 2', 'sociology project 3', 'sociology project 4'	['question_type_global', 'question_three_hop_statement']
How many points is [sociology homework 2] worth?	61	['question_type_local']
show me all the late projects that i submitted	'spanish project 3'	['question_type_global', 'question_two_hop_statement']
list all homeworks that i submitted late	'sociology homework 1'	['question_type_global', 'question_two_hop_statement']
How much is [sociology project 4] worth?	98	['question_type_local']
list all homeworks for [business communication]	'business communication homework 1'	['question_type_global', 'question_two_hop_statement']
what are the homeworks that i submitted?	'sociology homework 1', 'sociology homework 2', 'spanish homework 2', 'business communication homework 1'	['question_type_global', 'question_two_hop_statement']
[spanish] is taught by [Milagros]
[spanish homework 1] is worth [12] points
The deadline of [spanish homework 1] is [June 01]
[spanish homework 5] is out for [spanish]
[spanish homework 5] is worth [66] points
list all assignments	'sociology homework 1', 'sociology project 1', 'spanish homework 1', 'sociology homework 2', 'spanish homework 2', 'sociology project 2', 'spanish project 1', 'spanish project 2', 'sociology project 3', 'spanish homework 3', 'sociology project 4', 'business communication project 1', 'spanish homework 4', 'spanish project 3', 'business communication homework 1', 'business communication project 2', 'business communication project 3', 'spanish homework 5'	['question_type_global', 'question_single_statement']
what did I get on [spanish project 3]?	29	['question_type_local']
which courses did I submit late homeworks for?	'sociology'	['question_type_global', 'question_two_hop_statement']
[this homework] is due on [August 02]
When is the deadline of [sociology homework 1]?	'May 31'	['question_type_local']
list all homeworks for [spanish]	'spanish homework 1', 'spanish homework 2', 'spanish homework 3', 'spanish homework 4', 'spanish homework 5'	['question_type_global', 'question_two_hop_statement']
which projects did I submit for [spanish]?	'spanish project 2', 'spanish project 3'	['question_type_global', 'question_two_hop_statement']
who are the instructors to whom i submitted any late assignments?	'Hanna', 'Milagros'	['question_type_global', 'question_three_hop_statement']
What courses is [Hanna] teaching?	'sociology'	['question_type_local']
show me the assignments due on [June 20]	'spanish homework 3'	['question_type_global', 'question_two_hop_statement']
list all projects	'sociology project 1', 'sociology project 2', 'spanish project 1', 'spanish project 2', 'sociology project 3', 'sociology project 4', 'business communication project 1', 'spanish project 3', 'business communication project 2', 'business communication project 3'	['question_type_global', 'question_single_statement']
show me the assignments due on [June 05]	'business communication homework 1'	['question_type_global', 'question_two_hop_statement']
which assignments are due after [May 31]?	'spanish homework 1', 'sociology homework 2', 'spanish homework 2', 'spanish project 2', 'sociology project 3', 'spanish homework 3', 'sociology project 4', 'business communication project 1', 'spanish project 3', 'business communication homework 1', 'spanish homework 5'	['question_type_global', 'question_two_hop_statement']
which assignments are due before [June 02]?	'sociology homework 1', 'sociology project 1', 'spanish homework 1'	['question_type_global', 'question_two_hop_statement']
[spanish] has a new [spanish homework 6] released
I submitted [spanish homework 5] and received 53 points
list all homeworks that i submitted for [Hanna]	'sociology homework 1', 'sociology homework 2'	['question_type_global', 'question_three_hop_statement']
list all homeworks for [sociology]	'sociology homework 1', 'sociology homework 2'	['question_type_global', 'question_two_hop_statement']
what are all the homeworks due for [Hanna]?	'sociology homework 1', 'sociology homework 2'	['question_type_global', 'question_three_hop_statement']
