I am taking a [economics] course
I am taking a [statistics] course
create a [professor] named [Gabrielle]
[that course] is taught by [that professor]
[Lucio] is a [professor]
the affiliation of [she] is [neuroscience]
[Casey] is a [professor]
[Casey] is affiliated with the [electrical engineering] department
Who is teaching [statistics]?	'Gabrielle'	['question_type_local']
there is a [professor] named [Andy]
the affiliation of [Andy] is [neuroscience]
there is new [economics homework 1] for [economics]
[economics homework 1] is on [The Environment]
I submitted [economics homework 1] late
[that homework] is due on [June 10]
[economics homework 1] is worth [10] points
list all homeworks that i submitted for [economics]	'economics homework 1'	['question_type_global', 'question_two_hop_statement']
show me all homeworks i submitted	'economics homework 1'	['question_type_global', 'question_two_hop_statement']
which homeworks did I submit late?	'economics homework 1'	['question_type_global', 'question_two_hop_statement']
what are the courses for which i submitted late assignments?	'economics'	['question_type_global', 'question_two_hop_statement']
What are the assignments for [economics]?	'economics homework 1'	['question_type_local']
list all assignments that i submitted late	'economics homework 1'	['question_type_global', 'question_two_hop_statement']
there is a [professor] named [William]
[that professor]'s department is [electrical engineering]
What courses is [Gabrielle] teaching?	'statistics'	['question_type_local']
list assignments that are due on [June 10]	'economics homework 1'	['question_type_global', 'question_two_hop_statement']
create a [professor] named [Charlott]
change [William]'s department to [computer science]
the affiliation of [she] is [psychology]
which assignments did I submit late?	'economics homework 1'	['question_type_global', 'question_two_hop_statement']
what assignments do I have to do?	'economics homework 1'	['question_type_global', 'question_single_statement']
there is a new [project] for [statistics]
change [Casey]'s department to [computer science]
there is a [professor] named [Isaiah]
create a [professor] named [Stephine]
[she]'s department is [psychology]
what are all the projects due for [statistics]?	'statistics project 1'	['question_type_global', 'question_two_hop_statement']
what assignments did i submit late?	'economics homework 1'	['question_type_global', 'question_two_hop_statement']
what are all the homeworks due?	'economics homework 1'	['question_type_global', 'question_single_statement']
what assignments do I have to do for [statistics]?	'statistics project 1'	['question_type_global', 'question_two_hop_statement']
show me all late assignments i submitted for [economics]	'economics homework 1'	['question_type_global', 'question_two_hop_statement']
what assignments do I have to do for [Gabrielle]?	'statistics project 1'	['question_type_global', 'question_three_hop_statement']
[Charlott] teaches [economics]
List all homeworks for [that class]	'economics homework 1'	['question_type_local']
who are the professors?	'Gabrielle', 'Lucio', 'Casey', 'Andy', 'William', 'Charlott', 'Isaiah', 'Stephine'	['question_type_global', 'question_single_statement']
list all assignments for [Charlott]	'economics homework 1'	['question_type_global', 'question_three_hop_statement']
create a [professor] named [Tereasa]
the affiliation of [Tereasa] is [computer science]
which homeworks did I submit?	'economics homework 1'	['question_type_global', 'question_two_hop_statement']
which assignments are due before [June 12]?	'economics homework 1'	['question_type_global', 'question_two_hop_statement']
[economics] has a new [economics homework 2] released
I submitted [that assignment] late
What is [Tereasa]'s department?	'computer science'	['question_type_local']
list all projects	'statistics project 1'	['question_type_global', 'question_single_statement']
what assignments do I have to do for [Charlott]?	'economics homework 1', 'economics homework 2'	['question_type_global', 'question_three_hop_statement']
[that assignment] is due on [June 21]
which homeworks did I submit late?	'economics homework 1', 'economics homework 2'	['question_type_global', 'question_two_hop_statement']
which homeworks are due after [June 20]?	'economics homework 2'	['question_type_global', 'question_two_hop_statement']
which assignments did I submit late for [economics]?	'economics homework 1', 'economics homework 2'	['question_type_global', 'question_two_hop_statement']
show me all homeworks i submitted	'economics homework 1', 'economics homework 2'	['question_type_global', 'question_two_hop_statement']
What courses is [Gabrielle] teaching?	'statistics'	['question_type_local']
which professors did I submit late assignments for?	'Charlott'	['question_type_global', 'question_three_hop_statement']
list all projects	'statistics project 1'	['question_type_global', 'question_single_statement']
show all professors	'Gabrielle', 'Lucio', 'Casey', 'Andy', 'William', 'Charlott', 'Isaiah', 'Stephine', 'Tereasa'	['question_type_global', 'question_single_statement']
there is a new [project] for [statistics]
[this project] is about [Plants]
[this assignment] is worth [28] points
I submitted [statistics project 2] on time and received 22 points
what assignments did i submit for [economics]?	'economics homework 1', 'economics homework 2'	['question_type_global', 'question_two_hop_statement']
what are the assignments that i submitted for [statistics]	'statistics project 2'	['question_type_global', 'question_two_hop_statement']
show me all homeworks i submitted	'economics homework 1', 'economics homework 2'	['question_type_global', 'question_two_hop_statement']
[this project] is due on [June 25]
what are all the assignments due?	'economics homework 1', 'statistics project 1', 'economics homework 2', 'statistics project 2'	['question_type_global', 'question_single_statement']
what assignments do I have to do?	'economics homework 1', 'statistics project 1', 'economics homework 2', 'statistics project 2'	['question_type_global', 'question_single_statement']
which assignments are due after [June 08]?	'economics homework 1', 'economics homework 2', 'statistics project 2'	['question_type_global', 'question_two_hop_statement']
I am taking a [business communication] course
What is [William]'s department?	'computer science'	['question_type_local']
[Casey] is the instructor for [that class]
How many points did I get on [statistics project 2]	22	['question_type_local']
who did I submit assignments late to	'Charlott'	['question_type_global', 'question_three_hop_statement']
list all assignments that i submitted	'economics homework 1', 'economics homework 2', 'statistics project 2'	['question_type_global', 'question_two_hop_statement']
Show me all assignments due for [statistics]	'statistics project 1', 'statistics project 2'	['question_type_local']
which assignments are due before [June 20]?	'economics homework 1'	['question_type_global', 'question_two_hop_statement']
list homeworks that are due on [June 10]	'economics homework 1'	['question_type_global', 'question_two_hop_statement']
Which department is [Casey] in?	'computer science'	['question_type_local']
show me all late homeworks i submitted for [economics]	'economics homework 1', 'economics homework 2'	['question_type_global', 'question_two_hop_statement']
show me the assignments due on [June 10]	'economics homework 1'	['question_type_global', 'question_two_hop_statement']
what are the late homeworks that i submitted?	'economics homework 1', 'economics homework 2'	['question_type_global', 'question_two_hop_statement']
which courses did I submit late assignments for?	'economics'	['question_type_global', 'question_two_hop_statement']
[business communication homework 1] is released for [business communication]
what are the homeworks that i submitted?	'economics homework 1', 'economics homework 2'	['question_type_global', 'question_two_hop_statement']
which assignments are due after [June 22]?	'statistics project 2'	['question_type_global', 'question_two_hop_statement']
there is a new [homework] for [statistics]
[business communication homework 1] is on [Molds & Fungi]
[business communication homework 1] is due on [June 15]
[this assignment] is [21] points
I submitted [that homework] and received 21 points
what are the assignments that i submitted for [Gabrielle]	'statistics project 2'	['question_type_global', 'question_three_hop_statement']
what projects do I have to do?	'statistics project 1', 'statistics project 2'	['question_type_global', 'question_single_statement']
List all assignments for [statistics]	'statistics project 1', 'statistics project 2', 'statistics homework 1'	['question_type_local']
what instructors did i have late homeworks for?	'Charlott'	['question_type_global', 'question_three_hop_statement']
who are the professors?	'Gabrielle', 'Lucio', 'Casey', 'Andy', 'William', 'Charlott', 'Isaiah', 'Stephine', 'Tereasa'	['question_type_global', 'question_single_statement']
what are the projects that i submitted?	'statistics project 2'	['question_type_global', 'question_two_hop_statement']
which homeworks are due before [June 22]?	'economics homework 1', 'economics homework 2', 'business communication homework 1'	['question_type_global', 'question_two_hop_statement']
show me all homeworks i submitted	'economics homework 1', 'economics homework 2', 'business communication homework 1'	['question_type_global', 'question_two_hop_statement']
What are the assignments for [statistics]?	'statistics project 1', 'statistics project 2', 'statistics homework 1'	['question_type_local']
who did I submit assignments late to	'Charlott'	['question_type_global', 'question_three_hop_statement']
List all assignments for [business communication]	'business communication homework 1'	['question_type_local']
on which assignments did I get full credit?	'business communication homework 1'	['question_type_global', 'question_three_hop_statement']
what are all the homeworks due for [Casey]?	'business communication homework 1'	['question_type_global', 'question_three_hop_statement']
[statistics] has a new [statistics homework 2] released
I submitted [statistics homework 2] late
list all assignments that i submitted late	'economics homework 1', 'economics homework 2', 'statistics homework 2'	['question_type_global', 'question_two_hop_statement']
what homeworks did i submit for [Casey]?	'business communication homework 1'	['question_type_global', 'question_three_hop_statement']
[this assignment] is due on [June 27]
[that homework] is on [graphical models]
[Casey]'s department is now [neuroscience]
what are the assignments that i submitted for [business communication]	'business communication homework 1'	['question_type_global', 'question_two_hop_statement']
which assignments are due on [June 10]?	'economics homework 1'	['question_type_global', 'question_two_hop_statement']
what are the homeworks that i submitted for [business communication]	'business communication homework 1'	['question_type_global', 'question_two_hop_statement']
there is new [business communication project 1] for [business communication]
The topic of [business communication project 1] is [expectation maximization]
What is the topic of [statistics homework 2]?	'graphical models'	['question_type_local']
I submitted [this assignment] late
The deadline of [business communication project 1] is [June 15]
[that project] is worth [20] points
list all homeworks that i submitted	'economics homework 1', 'economics homework 2', 'business communication homework 1', 'statistics homework 2'	['question_type_global', 'question_two_hop_statement']
show me all courses for which i submitted at least one late project	'business communication'	['question_type_global', 'question_two_hop_statement']
The deadline of [that assignment] moved to [June 18]
What is [Stephine]'s department?	'psychology'	['question_type_local']
list all projects for [Gabrielle]	'statistics project 1', 'statistics project 2'	['question_type_global', 'question_three_hop_statement']
show me all homeworks i submitted	'economics homework 1', 'economics homework 2', 'business communication homework 1', 'statistics homework 2'	['question_type_global', 'question_two_hop_statement']
on which assignments did I get full credit?	'business communication homework 1'	['question_type_global', 'question_three_hop_statement']
which assignments did I submit late for [economics]?	'economics homework 1', 'economics homework 2'	['question_type_global', 'question_two_hop_statement']
what are the courses for which i submitted late assignments?	'economics', 'statistics', 'business communication'	['question_type_global', 'question_two_hop_statement']
The deadline of [this project] moved to [June 17]
which projects are due before [June 27]?	'statistics project 2', 'business communication project 1'	['question_type_global', 'question_two_hop_statement']
what homeworks did i submit late for [statistics]?	'statistics homework 2'	['question_type_global', 'question_two_hop_statement']
what homeworks did i submit for [Casey]?	'business communication homework 1'	['question_type_global', 'question_three_hop_statement']
there is a new [project] for [business communication]
I submitted [business communication project 2]
[that project] is on [hidden markov models]
[that project] is [20] points
When is [economics homework 2] due?	'June 21'	['question_type_local']
which assignments are due before [June 18]?	'economics homework 1', 'business communication homework 1', 'business communication project 1'	['question_type_global', 'question_two_hop_statement']
what projects did i submit late?	'business communication project 1'	['question_type_global', 'question_two_hop_statement']
The deadline of [that assignment] is [June 29]
what are the homeworks that i submitted?	'economics homework 1', 'economics homework 2', 'business communication homework 1', 'statistics homework 2'	['question_type_global', 'question_two_hop_statement']
how many points did I receive on [statistics project 2]?	22	['question_type_local']
show me all the late projects that i submitted	'business communication project 1'	['question_type_global', 'question_two_hop_statement']
what are the courses for which i submitted late homeworks?	'economics', 'statistics'	['question_type_global', 'question_two_hop_statement']
which projects did I submit late?	'business communication project 1'	['question_type_global', 'question_two_hop_statement']
How much is [statistics project 2] worth?	28	['question_type_local']
show me all assignments i submitted for [statistics]	'statistics project 2', 'statistics homework 2'	['question_type_global', 'question_two_hop_statement']
which assignments are due after [June 15]?	'economics homework 2', 'statistics project 2', 'statistics homework 2', 'business communication project 1', 'business communication project 2'	['question_type_global', 'question_two_hop_statement']
what are the assignments that i submitted?	'economics homework 1', 'economics homework 2', 'statistics project 2', 'business communication homework 1', 'statistics homework 2', 'business communication project 1', 'business communication project 2'	['question_type_global', 'question_two_hop_statement']
list all homeworks that i submitted late for [economics]	'economics homework 1', 'economics homework 2'	['question_type_global', 'question_two_hop_statement']
which homeworks did I submit late?	'economics homework 1', 'economics homework 2', 'statistics homework 2'	['question_type_global', 'question_two_hop_statement']
which projects are due before [June 27]?	'statistics project 2', 'business communication project 1'	['question_type_global', 'question_two_hop_statement']
who are the professors?	'Gabrielle', 'Lucio', 'Casey', 'Andy', 'William', 'Charlott', 'Isaiah', 'Stephine', 'Tereasa'	['question_type_global', 'question_single_statement']
which professors did I submit late projects for?	'Casey'	['question_type_global', 'question_three_hop_statement']
list the professors in the [computer science] department	'William', 'Tereasa'	['question_type_global', 'question_two_hop_statement']
which assignments are due after [June 26]?	'statistics homework 2', 'business communication project 2'	['question_type_global', 'question_two_hop_statement']
[economics homework 2] is worth [26] points
list all homeworks that i submitted late	'economics homework 1', 'economics homework 2', 'statistics homework 2'	['question_type_global', 'question_two_hop_statement']
What is [Andy]'s department?	'neuroscience'	['question_type_local']
which assignments are due before [June 18]?	'economics homework 1', 'business communication homework 1', 'business communication project 1'	['question_type_global', 'question_two_hop_statement']
what are the projects that i submitted for [business communication]	'business communication project 1', 'business communication project 2'	['question_type_global', 'question_two_hop_statement']
there is new [economics homework 3] for [economics]
[economics homework 3] is due on [June 24]
I submitted [that homework] late
[that assignment] is about [neural networks]
which homeworks did I submit for [Gabrielle]?	'statistics homework 2'	['question_type_global', 'question_three_hop_statement']
on which assignments did I get full credit?	'business communication homework 1'	['question_type_global', 'question_three_hop_statement']
what projects did i submit late?	'business communication project 1'	['question_type_global', 'question_two_hop_statement']
list all homeworks that i submitted late	'economics homework 1', 'economics homework 2', 'statistics homework 2', 'economics homework 3'	['question_type_global', 'question_two_hop_statement']
what homeworks do I have to do?	'economics homework 1', 'economics homework 2', 'business communication homework 1', 'statistics homework 1', 'statistics homework 2', 'economics homework 3'	['question_type_global', 'question_single_statement']
show all professors	'Gabrielle', 'Lucio', 'Casey', 'Andy', 'William', 'Charlott', 'Isaiah', 'Stephine', 'Tereasa'	['question_type_global', 'question_single_statement']
[statistics project 3] is released for [statistics]
list all assignments for [Charlott]	'economics homework 1', 'economics homework 2', 'economics homework 3'	['question_type_global', 'question_three_hop_statement']
list all homeworks for [economics]	'economics homework 1', 'economics homework 2', 'economics homework 3'	['question_type_global', 'question_two_hop_statement']
which homeworks are due before [June 21]?	'economics homework 1', 'business communication homework 1'	['question_type_global', 'question_two_hop_statement']
what are the projects that i submitted?	'statistics project 2', 'business communication project 1', 'business communication project 2'	['question_type_global', 'question_two_hop_statement']
what assignments did i submit late for [business communication]?	'business communication project 1'	['question_type_global', 'question_two_hop_statement']
there is a new [project] for [economics]
I submitted [statistics project 3] on time
[statistics project 3] is due on [July 03]
[that project] is worth [88] points
[that assignment] is about [k means]
When is [economics homework 3] due?	'June 24'	['question_type_local']
what are the courses for which i submitted late projects?	'business communication'	['question_type_global', 'question_two_hop_statement']
list all homeworks that i submitted for [Gabrielle]	'statistics homework 2'	['question_type_global', 'question_three_hop_statement']
which homeworks are due before [June 23]?	'economics homework 1', 'economics homework 2', 'business communication homework 1'	['question_type_global', 'question_two_hop_statement']
what are all the projects due for [Charlott]?	'economics project 1'	['question_type_global', 'question_three_hop_statement']
what are all the projects due for [statistics]?	'statistics project 1', 'statistics project 2', 'statistics project 3'	['question_type_global', 'question_two_hop_statement']
What is [Gabrielle]'s department?	'neuroscience'	['question_type_local']
which assignments are due before [June 28]?	'economics homework 1', 'economics homework 2', 'statistics project 2', 'business communication homework 1', 'statistics homework 2', 'business communication project 1', 'economics homework 3'	['question_type_global', 'question_two_hop_statement']
list all assignments that i submitted late for [economics]	'economics homework 1', 'economics homework 2', 'economics homework 3'	['question_type_global', 'question_two_hop_statement']
Which department is [Andy] in?	'neuroscience'	['question_type_local']
on which assignments did I get full credit?	'business communication homework 1'	['question_type_global', 'question_three_hop_statement']
what assignments do I have to do for [Gabrielle]?	'statistics project 1', 'statistics project 2', 'statistics homework 1', 'statistics homework 2', 'statistics project 3'	['question_type_global', 'question_three_hop_statement']
which assignments are due on [June 27]?	'statistics homework 2'	['question_type_global', 'question_two_hop_statement']
list the professors in the [computer science] department	'William', 'Tereasa'	['question_type_global', 'question_two_hop_statement']
show me all homeworks i submitted for [business communication]	'business communication homework 1'	['question_type_global', 'question_two_hop_statement']
how much did I get on [business communication homework 1]?	21	['question_type_local']
which projects did I submit late?	'business communication project 1'	['question_type_global', 'question_two_hop_statement']
What courses is [Gabrielle] teaching?	'statistics'	['question_type_local']
which assignments did I submit for [statistics]?	'statistics project 2', 'statistics homework 2', 'statistics project 3'	['question_type_global', 'question_two_hop_statement']
[economics homework 3] is [32] points
list all assignments that i submitted late for [Casey]	'business communication project 1'	['question_type_global', 'question_three_hop_statement']
which homeworks did I submit late?	'economics homework 1', 'economics homework 2', 'statistics homework 2', 'economics homework 3'	['question_type_global', 'question_two_hop_statement']
list all projects for [business communication]	'business communication project 1', 'business communication project 2'	['question_type_global', 'question_two_hop_statement']
what are all the homeworks due?	'economics homework 1', 'economics homework 2', 'business communication homework 1', 'statistics homework 1', 'statistics homework 2', 'economics homework 3'	['question_type_global', 'question_single_statement']
list all projects that i submitted late for [business communication]	'business communication project 1'	['question_type_global', 'question_two_hop_statement']
what are the late homeworks that i submitted?	'economics homework 1', 'economics homework 2', 'statistics homework 2', 'economics homework 3'	['question_type_global', 'question_two_hop_statement']
which projects did I submit for [statistics]?	'statistics project 2', 'statistics project 3'	['question_type_global', 'question_two_hop_statement']
list all projects	'statistics project 1', 'statistics project 2', 'business communication project 1', 'business communication project 2', 'statistics project 3', 'economics project 1'	['question_type_global', 'question_single_statement']
what homeworks do I have to do?	'economics homework 1', 'economics homework 2', 'business communication homework 1', 'statistics homework 1', 'statistics homework 2', 'economics homework 3'	['question_type_global', 'question_single_statement']
which professors did I submit late homeworks for?	'Gabrielle', 'Charlott'	['question_type_global', 'question_three_hop_statement']
what homeworks did i submit late?	'economics homework 1', 'economics homework 2', 'statistics homework 2', 'economics homework 3'	['question_type_global', 'question_two_hop_statement']
When is [economics homework 1] due?	'June 10'	['question_type_local']
list all homeworks for [business communication]	'business communication homework 1'	['question_type_global', 'question_two_hop_statement']
[statistics project 4] is released for [statistics]
I submitted [that project] on time
how many points is [business communication project 2]?	20	['question_type_local']
what are the late assignments that i submitted for [Gabrielle]	'statistics homework 2'	['question_type_global', 'question_three_hop_statement']
show me all projects i submitted	'statistics project 2', 'business communication project 1', 'business communication project 2', 'statistics project 3', 'statistics project 4'	['question_type_global', 'question_two_hop_statement']
[William]'s department is now [electrical engineering]
what are all the assignments due for [economics]?	'economics project 1'	['question_type_global', 'question_two_hop_statement']
what are the late assignments that i submitted for [statistics]	'statistics homework 2'	['question_type_global', 'question_two_hop_statement']
which assignments did I submit for [business communication]?	'business communication homework 1', 'business communication project 1', 'business communication project 2'	['question_type_global', 'question_two_hop_statement']
which professors did I submit late assignments for?	'Gabrielle', 'Casey', 'Charlott'	['question_type_global', 'question_three_hop_statement']
what are the projects that i submitted for [statistics]	'statistics project 2', 'statistics project 3', 'statistics project 4'	['question_type_global', 'question_two_hop_statement']
which professors did I submit late homeworks for?	'Gabrielle', 'Charlott'	['question_type_global', 'question_three_hop_statement']
which homeworks are due after [June 23]?	'statistics homework 2', 'economics homework 3'	['question_type_global', 'question_two_hop_statement']
When is the deadline of [business communication project 1]?	'June 17'	['question_type_local']
what homeworks do I have to do for [business communication]?	'business communication homework 1'	['question_type_global', 'question_two_hop_statement']
show me all assignments i submitted for [business communication]	'business communication homework 1', 'business communication project 1', 'business communication project 2'	['question_type_global', 'question_two_hop_statement']
list all assignments that i submitted late	'economics homework 1', 'economics homework 2', 'statistics homework 2', 'business communication project 1', 'economics homework 3'	['question_type_global', 'question_two_hop_statement']
what assignments do I have to do?	'economics homework 1', 'statistics project 1', 'economics homework 2', 'statistics project 2', 'business communication homework 1', 'statistics homework 1', 'statistics homework 2', 'business communication project 1', 'business communication project 2', 'economics homework 3', 'statistics project 3', 'economics project 1', 'statistics project 4'	['question_type_global', 'question_single_statement']
[economics project 2] is released for [economics]
[this project] is [82] points
I submitted [that assignment] and received 82 points
How many points is [economics homework 1] worth?	10	['question_type_local']
what homeworks did i submit for [Casey]?	'business communication homework 1'	['question_type_global', 'question_three_hop_statement']
which courses did I submit late homeworks for?	'economics', 'statistics'	['question_type_global', 'question_two_hop_statement']
I submitted [statistics project 1] on time
[statistics project 1] is due on [June 16]
The topic of [that project] is [The Senses]
[that assignment] is [79] points
show me all courses for which i submitted at least one late assignment	'economics', 'statistics', 'business communication'	['question_type_global', 'question_two_hop_statement']
which assignments did I submit?	'economics homework 1', 'statistics project 1', 'economics homework 2', 'statistics project 2', 'business communication homework 1', 'statistics homework 2', 'business communication project 1', 'business communication project 2', 'economics homework 3', 'statistics project 3', 'statistics project 4', 'economics project 2'	['question_type_global', 'question_two_hop_statement']
which projects did I submit for [statistics]?	'statistics project 1', 'statistics project 2', 'statistics project 3', 'statistics project 4'	['question_type_global', 'question_two_hop_statement']
which projects are due after [June 09]?	'statistics project 1', 'statistics project 2', 'business communication project 1', 'business communication project 2', 'statistics project 3'	['question_type_global', 'question_two_hop_statement']
When is [business communication project 2] due?	'June 29'	['question_type_local']
list all assignments that i submitted late for [economics]	'economics homework 1', 'economics homework 2', 'economics homework 3'	['question_type_global', 'question_two_hop_statement']
what projects did i submit for [Charlott]?	'economics project 2'	['question_type_global', 'question_three_hop_statement']
[economics homework 4] is released for [economics]
How many points did I get on [business communication homework 1]	21	['question_type_local']
list all projects that i submitted	'statistics project 1', 'statistics project 2', 'business communication project 1', 'business communication project 2', 'statistics project 3', 'statistics project 4', 'economics project 2'	['question_type_global', 'question_two_hop_statement']
which projects are due on [June 29]?	'business communication project 2'	['question_type_global', 'question_two_hop_statement']
how many points did I receive on [statistics project 2]?	22	['question_type_local']
show me all courses for which i submitted at least one late project	'business communication'	['question_type_global', 'question_two_hop_statement']
what instructors did i have late projects for?	'Casey'	['question_type_global', 'question_three_hop_statement']
show me all homeworks i submitted	'economics homework 1', 'economics homework 2', 'business communication homework 1', 'statistics homework 2', 'economics homework 3'	['question_type_global', 'question_two_hop_statement']
what are the late homeworks that i submitted for [Charlott]	'economics homework 1', 'economics homework 2', 'economics homework 3'	['question_type_global', 'question_three_hop_statement']
list all homeworks that i submitted for [business communication]	'business communication homework 1'	['question_type_global', 'question_two_hop_statement']
which projects did I submit?	'statistics project 1', 'statistics project 2', 'business communication project 1', 'business communication project 2', 'statistics project 3', 'statistics project 4', 'economics project 2'	['question_type_global', 'question_two_hop_statement']
What courses is [Casey] teaching?	'business communication'	['question_type_local']
show me the homeworks due on [June 15]	'business communication homework 1'	['question_type_global', 'question_two_hop_statement']
what assignments did i submit late for [economics]?	'economics homework 1', 'economics homework 2', 'economics homework 3'	['question_type_global', 'question_two_hop_statement']
what are all the projects due for [business communication]?	'business communication project 1', 'business communication project 2'	['question_type_global', 'question_two_hop_statement']
what homeworks did i submit late for [statistics]?	'statistics homework 2'	['question_type_global', 'question_two_hop_statement']
which homeworks are due on [June 27]?	'statistics homework 2'	['question_type_global', 'question_two_hop_statement']
how many points is [statistics project 2]?	28	['question_type_local']
list all the professors	'Gabrielle', 'Lucio', 'Casey', 'Andy', 'William', 'Charlott', 'Isaiah', 'Stephine', 'Tereasa'	['question_type_global', 'question_single_statement']
[economics project 3] is released for [economics]
[this project] is [84] points
how many points did I receive on [economics project 2]?	82	['question_type_local']
who did I submit assignments late to	'Gabrielle', 'Casey', 'Charlott'	['question_type_global', 'question_three_hop_statement']
what are the late assignments that i submitted for [Gabrielle]	'statistics homework 2'	['question_type_global', 'question_three_hop_statement']
list all assignments that i submitted late	'economics homework 1', 'economics homework 2', 'statistics homework 2', 'business communication project 1', 'economics homework 3'	['question_type_global', 'question_two_hop_statement']
list all projects that i submitted for [business communication]	'business communication project 1', 'business communication project 2'	['question_type_global', 'question_two_hop_statement']
I submitted [this assignment] and received 84 points
what projects do I have to do?	'statistics project 1', 'statistics project 2', 'business communication project 1', 'business communication project 2', 'statistics project 3', 'economics project 1', 'statistics project 4', 'economics project 2', 'economics project 3'	['question_type_global', 'question_single_statement']
which projects did I submit late?	'business communication project 1'	['question_type_global', 'question_two_hop_statement']
there is new [statistics project 5] for [statistics]
I submitted [statistics project 5]
[statistics project 5] is due on [August 12]
[business communication project 1] is now due on [June 20]
What courses is [Charlott] teaching?	'economics'	['question_type_local']
which projects are due before [June 20]?	'statistics project 1'	['question_type_global', 'question_two_hop_statement']
which projects did I submit for [Gabrielle]?	'statistics project 1', 'statistics project 2', 'statistics project 3', 'statistics project 4', 'statistics project 5'	['question_type_global', 'question_three_hop_statement']
which courses did I submit late homeworks for?	'economics', 'statistics'	['question_type_global', 'question_two_hop_statement']
what projects did i submit?	'statistics project 1', 'statistics project 2', 'business communication project 1', 'business communication project 2', 'statistics project 3', 'statistics project 4', 'economics project 2', 'economics project 3', 'statistics project 5'	['question_type_global', 'question_two_hop_statement']
show me all late homeworks i submitted	'economics homework 1', 'economics homework 2', 'statistics homework 2', 'economics homework 3'	['question_type_global', 'question_two_hop_statement']
[statistics project 4] is worth [72] points
The deadline of [statistics project 4] is [July 25]
list assignments that are due on [June 29]	'business communication project 2'	['question_type_global', 'question_two_hop_statement']
Which professor is teaching [business communication]?	'Casey'	['question_type_local']
what are all the projects due for [statistics]?	'statistics project 1', 'statistics project 2', 'statistics project 3', 'statistics project 4', 'statistics project 5'	['question_type_global', 'question_two_hop_statement']
there is new [economics project 4] for [economics]
[economics project 4] is due on [July 09]
[economics project 4] is worth [31] points
what instructors did i have late projects for?	'Casey'	['question_type_global', 'question_three_hop_statement']
show me all homeworks i submitted for [statistics]	'statistics homework 2'	['question_type_global', 'question_two_hop_statement']
[statistics] has a new [statistics homework 3] released
I submitted [this project] and received 31 points
What courses is [Charlott] teaching?	'economics'	['question_type_local']
which homeworks did I submit late?	'economics homework 1', 'economics homework 2', 'statistics homework 2', 'economics homework 3'	['question_type_global', 'question_two_hop_statement']
list all assignments that i submitted for [statistics]	'statistics project 1', 'statistics project 2', 'statistics homework 2', 'statistics project 3', 'statistics project 4', 'statistics project 5'	['question_type_global', 'question_two_hop_statement']
[statistics homework 4] is out for [statistics]
[this homework] is worth [76] points
I submitted [that homework] on time and received 76 points
The deadline of [that assignment] is [July 29]
