I am taking a course called [religion]
there is a [professor] named [Roslyn]
[that person] is in [194]
[Roslyn]'s email is [Roslyn@nh.edu]
What office is [that person] in?	'194'	['question_type_local']
there is a new [homework] for [religion]
[this homework] is on [k means]
The deadline of [this assignment] is [May 01]
What is [this homework] on?	'k means'	['question_type_local']
[Roslyn] is the instructor for [religion]
Show me all homeworks due for [this course]	'religion homework 1'	['question_type_local']
What are the assignments for [religion]?	'religion homework 1'	['question_type_local']
What is the topic of [religion homework 1]?	'k means'	['question_type_local']
what assignments do I have to do?	'religion homework 1'	['question_type_global', 'question_single_statement']
[religion homework 1] is worth [73] points
I submitted [this homework] and received 20 points
What is [Roslyn]'s email	'Roslyn@nh.edu'	['question_type_local']
what did I get on [this assignment]?	20	['question_type_local']
Which professor is teaching [religion]?	'Roslyn'	['question_type_local']
I am taking a course called [accounting]
how many points is [religion homework 1]?	73	['question_type_local']
I am taking a course called [philosophy]
[Bob] is a [professor]
[Bob] is the instructor for [that course]
there is new [religion project 1] for [religion]
[this project] is due on [May 05]
[that project] is about [bayesian models]
[Francoise] is a [professor]
[he]'s email is [Francoise@cornell.edu]
which assignments are due before [May 02]?	'religion homework 1'	['question_type_global', 'question_two_hop_statement']
which projects are due before [May 07]?	'religion project 1'	['question_type_global', 'question_two_hop_statement']
[this professor] is in [194]
What office is [this professor] in?	'194'	['question_type_local']
list all projects for [Roslyn]	'religion project 1'	['question_type_global', 'question_three_hop_statement']
who are the professors?	'Roslyn', 'Bob', 'Francoise'	['question_type_global', 'question_single_statement']
[Bob]'s email is [Bob@gmail.com]
[Bob] is in [P267]
List all assignments for [religion]	'religion homework 1', 'religion project 1'	['question_type_local']
What courses is [Roslyn] teaching?	'religion'	['question_type_local']
what homeworks do I have to do for [Roslyn]?	'religion homework 1'	['question_type_global', 'question_three_hop_statement']
list all the professors	'Roslyn', 'Bob', 'Francoise'	['question_type_global', 'question_single_statement']
[philosophy project 1] is out for [philosophy]
[that assignment] is about [Genetics]
[this project] is worth [61] points
[philosophy project 1] is due on [May 03]
I submitted [this project] and received 61 points
[this assignment] is now due on [May 01]
What is [Bob]'s email	'Bob@gmail.com'	['question_type_local']
[accounting project 1] is released for [accounting]
what are the projects that i submitted for [philosophy]	'philosophy project 1'	['question_type_global', 'question_two_hop_statement']
which homeworks did I submit for [Roslyn]?	'religion homework 1'	['question_type_global', 'question_three_hop_statement']
which projects are due after [May 03]?	'religion project 1'	['question_type_global', 'question_two_hop_statement']
there is a new [project] for [religion]
I submitted [religion project 2] late
The deadline of [this project] is [May 08]
The topic of [religion project 2] is [graphical models]
When is [that project] due?	'May 08'	['question_type_local']
show me all late projects i submitted for [religion]	'religion project 2'	['question_type_global', 'question_two_hop_statement']
which projects are due before [May 11]?	'religion project 1', 'philosophy project 1', 'religion project 2'	['question_type_global', 'question_two_hop_statement']
show me all assignments that i submitted for [Bob]	'philosophy project 1'	['question_type_global', 'question_three_hop_statement']
[this assignment] is worth [60] points
[Zenaida] is a [professor]
what assignments did i submit late?	'religion project 2'	['question_type_global', 'question_two_hop_statement']
what assignments do I have to do for [philosophy]?	'philosophy project 1'	['question_type_global', 'question_two_hop_statement']
there is a new [project] for [accounting]
[that professor]'s email is [Zenaida@cornell.edu]
[Zenaida] is in [194]
what projects did i submit late?	'religion project 2'	['question_type_global', 'question_two_hop_statement']
what homeworks did i submit for [religion]?	'religion homework 1'	['question_type_global', 'question_two_hop_statement']
I submitted [religion project 1] on time
create a [professor] named [Stephine]
The deadline of [that assignment] moved to [May 02]
[Stephine]'s email is [Stephine@chk.ru]
[this project] is [18] points
how much did I get on [philosophy project 1]?	61	['question_type_local']
which projects did I submit late for [religion]?	'religion project 2'	['question_type_global', 'question_two_hop_statement']
[that person]'s office is [194]
what assignments did i submit late for [Roslyn]?	'religion project 2'	['question_type_global', 'question_three_hop_statement']
what are the late assignments that i submitted	'religion project 2'	['question_type_global', 'question_two_hop_statement']
what assignments did i submit for [Bob]?	'philosophy project 1'	['question_type_global', 'question_three_hop_statement']
create a [professor] named [Ashly]
[Ashly]'s email is [Ashly@gmail.com]
[this professor]'s office is [194]
which projects are due after [April 29]?	'religion project 1', 'philosophy project 1', 'religion project 2'	['question_type_global', 'question_two_hop_statement']
[philosophy] has a new [philosophy project 2] out
[philosophy project 2] is on [Cells]
What are the assignments for [accounting]?	'accounting project 1', 'accounting project 2'	['question_type_local']
show all professors	'Roslyn', 'Bob', 'Francoise', 'Zenaida', 'Stephine', 'Ashly'	['question_type_global', 'question_single_statement']
which assignments did I submit late?	'religion project 2'	['question_type_global', 'question_two_hop_statement']
which homeworks are due after [April 29]?	'religion homework 1'	['question_type_global', 'question_two_hop_statement']
[philosophy project 2] is due on [May 12]
What is the topic of [philosophy project 1]?	'Genetics'	['question_type_local']
list homeworks that are due on [May 01]	'religion homework 1'	['question_type_global', 'question_two_hop_statement']
What is [Ashly]'s office?	'194'	['question_type_local']
which assignments did I submit late for [Roslyn]?	'religion project 2'	['question_type_global', 'question_three_hop_statement']
list projects that are due on [May 12]	'philosophy project 2'	['question_type_global', 'question_two_hop_statement']
[philosophy project 2] is worth [30] points
I submitted [that assignment] late and received 17 points
how many points is [religion project 2]?	60	['question_type_local']
what assignments do I have to do for [Roslyn]?	'religion homework 1', 'religion project 1', 'religion project 2'	['question_type_global', 'question_three_hop_statement']
which assignments are due on [May 01]?	'religion homework 1', 'philosophy project 1'	['question_type_global', 'question_two_hop_statement']
what are the projects that i submitted?	'religion project 1', 'philosophy project 1', 'religion project 2', 'philosophy project 2'	['question_type_global', 'question_two_hop_statement']
[accounting] has a new [accounting homework 1] out
[religion project 1] is now due on [May 02]
What is [philosophy project 2] on?	'Cells'	['question_type_local']
which projects are due before [May 03]?	'religion project 1', 'philosophy project 1'	['question_type_global', 'question_two_hop_statement']
which homeworks are due before [May 15]?	'religion homework 1'	['question_type_global', 'question_two_hop_statement']
what homeworks do I have to do for [accounting]?	'accounting homework 1'	['question_type_global', 'question_two_hop_statement']
what projects did i submit?	'religion project 1', 'philosophy project 1', 'religion project 2', 'philosophy project 2'	['question_type_global', 'question_two_hop_statement']
[that homework] is due on [May 05]
I submitted [this homework] late
[that homework] is on [cold war]
How many points did I get on [religion homework 1]	20	['question_type_local']
who did I submit projects late to	'Roslyn', 'Bob'	['question_type_global', 'question_three_hop_statement']
what projects do I have to do for [Roslyn]?	'religion project 1', 'religion project 2'	['question_type_global', 'question_three_hop_statement']
show me all projects i submitted	'religion project 1', 'philosophy project 1', 'religion project 2', 'philosophy project 2'	['question_type_global', 'question_two_hop_statement']
what projects did i submit late?	'religion project 2', 'philosophy project 2'	['question_type_global', 'question_two_hop_statement']
which assignments are due after [April 30]?	'religion homework 1', 'religion project 1', 'philosophy project 1', 'religion project 2', 'philosophy project 2', 'accounting homework 1'	['question_type_global', 'question_two_hop_statement']
[that homework] is [47] points
which projects are due on [May 02]?	'religion project 1'	['question_type_global', 'question_two_hop_statement']
list all projects that i submitted late	'religion project 2', 'philosophy project 2'	['question_type_global', 'question_two_hop_statement']
which projects did I submit?	'religion project 1', 'philosophy project 1', 'religion project 2', 'philosophy project 2'	['question_type_global', 'question_two_hop_statement']
which assignments did I submit late?	'religion project 2', 'philosophy project 2', 'accounting homework 1'	['question_type_global', 'question_two_hop_statement']
what are the courses for which I submitted projects late	'religion', 'philosophy'	['question_type_global', 'question_two_hop_statement']
list all homeworks	'religion homework 1', 'accounting homework 1'	['question_type_global', 'question_single_statement']
what are all the assignments due for [religion]?	'religion project 1', 'religion project 2'	['question_type_global', 'question_two_hop_statement']
what assignments did i submit late?	'religion project 2', 'philosophy project 2', 'accounting homework 1'	['question_type_global', 'question_two_hop_statement']
how many points did I receive on [philosophy project 2]?	17	['question_type_local']
what are the late assignments that i submitted	'religion project 2', 'philosophy project 2', 'accounting homework 1'	['question_type_global', 'question_two_hop_statement']
what are all the projects due?	'religion project 1', 'philosophy project 1', 'accounting project 1', 'religion project 2', 'accounting project 2', 'philosophy project 2'	['question_type_global', 'question_single_statement']
create a [professor] named [Angelita]
[this professor] is in [778]
[this professor]'s email is [Angelita@harvard.edu]
list homeworks that are due on [May 05]	'accounting homework 1'	['question_type_global', 'question_two_hop_statement']
what are the late homeworks that i submitted for [accounting]	'accounting homework 1'	['question_type_global', 'question_two_hop_statement']
[philosophy] has a new [philosophy homework 1] out
[this assignment] is due on [May 02]
What is the topic of [religion project 2]?	'graphical models'	['question_type_local']
what projects did i submit late?	'religion project 2', 'philosophy project 2'	['question_type_global', 'question_two_hop_statement']
what did I get on [philosophy project 2]?	17	['question_type_local']
[this assignment] is [58] points
I submitted [this homework] on time and received 58 points
which homeworks are due before [May 05]?	'religion homework 1', 'philosophy homework 1'	['question_type_global', 'question_two_hop_statement']
which assignments are due after [May 04]?	'religion project 2', 'philosophy project 2', 'accounting homework 1'	['question_type_global', 'question_two_hop_statement']
what are all the projects due?	'religion project 1', 'philosophy project 1', 'accounting project 1', 'religion project 2', 'accounting project 2', 'philosophy project 2'	['question_type_global', 'question_single_statement']
[this assignment] is on [The Environment]
When is [philosophy project 2] due?	'May 12'	['question_type_local']
which projects did I submit late?	'religion project 2', 'philosophy project 2'	['question_type_global', 'question_two_hop_statement']
list all projects	'religion project 1', 'philosophy project 1', 'accounting project 1', 'religion project 2', 'accounting project 2', 'philosophy project 2'	['question_type_global', 'question_single_statement']
show me all the late projects that i submitted	'religion project 2', 'philosophy project 2'	['question_type_global', 'question_two_hop_statement']
[accounting project 3] is released for [accounting]
what homeworks did i submit late?	'accounting homework 1'	['question_type_global', 'question_two_hop_statement']
what are all the homeworks due?	'religion homework 1', 'accounting homework 1', 'philosophy homework 1'	['question_type_global', 'question_single_statement']
I submitted [this project] late
The deadline of [this project] is [May 27]
what homeworks do I have to do for [religion]?	'religion homework 1'	['question_type_global', 'question_two_hop_statement']
When is [religion project 1] due?	'May 02'	['question_type_local']
what homeworks do I have to do for [philosophy]?	'philosophy homework 1'	['question_type_global', 'question_two_hop_statement']
show me the assignments due on [May 01]	'religion homework 1', 'philosophy project 1'	['question_type_global', 'question_two_hop_statement']
there is a new [project] for [accounting]
The deadline of [accounting project 4] is [June 03]
[that project] is [37] points
I submitted [this project] on time and received 4 points
What is the topic of [philosophy project 1]?	'Genetics'	['question_type_local']
who are the instructors to whom i submitted any late projects?	'Roslyn', 'Bob'	['question_type_global', 'question_three_hop_statement']
What is [Zenaida]'s email	'Zenaida@cornell.edu'	['question_type_local']
what assignments did i submit for [accounting]?	'accounting homework 1', 'accounting project 3', 'accounting project 4'	['question_type_global', 'question_two_hop_statement']
there is new [accounting project 5] for [accounting]
When is the deadline of [religion project 1]?	'May 02'	['question_type_local']
list all assignments that i submitted late for [Bob]	'philosophy project 2'	['question_type_global', 'question_three_hop_statement']
list all homeworks that i submitted for [Bob]	'philosophy homework 1'	['question_type_global', 'question_three_hop_statement']
show all professors	'Roslyn', 'Bob', 'Francoise', 'Zenaida', 'Stephine', 'Ashly', 'Angelita'	['question_type_global', 'question_single_statement']
[religion project 3] is released for [religion]
I submitted [accounting project 5]
I submitted [religion project 3]
[religion project 3] is due on [June 05]
[this project] is [77] points
How many points is [philosophy project 2] worth?	30	['question_type_local']
what are the late projects that i submitted?	'religion project 2', 'philosophy project 2', 'accounting project 3'	['question_type_global', 'question_two_hop_statement']
What is [religion project 2] on?	'graphical models'	['question_type_local']
list all assignments that i submitted late for [religion]	'religion project 2'	['question_type_global', 'question_two_hop_statement']
[accounting homework 2] is released for [accounting]
I submitted [that homework] late
What is [Ashly]'s email	'Ashly@gmail.com'	['question_type_local']
what projects did i submit?	'religion project 1', 'philosophy project 1', 'religion project 2', 'philosophy project 2', 'accounting project 3', 'accounting project 4', 'accounting project 5', 'religion project 3'	['question_type_global', 'question_two_hop_statement']
what are all the assignments due?	'religion homework 1', 'religion project 1', 'philosophy project 1', 'accounting project 1', 'religion project 2', 'accounting project 2', 'philosophy project 2', 'accounting homework 1', 'philosophy homework 1', 'accounting project 3', 'accounting project 4', 'accounting project 5', 'religion project 3', 'accounting homework 2'	['question_type_global', 'question_single_statement']
list all projects for [Roslyn]	'religion project 1', 'religion project 2', 'religion project 3'	['question_type_global', 'question_three_hop_statement']
What office is [Roslyn] in?	'194'	['question_type_local']
list all homeworks that i submitted	'religion homework 1', 'accounting homework 1', 'philosophy homework 1', 'accounting homework 2'	['question_type_global', 'question_two_hop_statement']
what are the late assignments that i submitted for [philosophy]	'philosophy project 2'	['question_type_global', 'question_two_hop_statement']
what projects do I have to do?	'religion project 1', 'philosophy project 1', 'accounting project 1', 'religion project 2', 'accounting project 2', 'philosophy project 2', 'accounting project 3', 'accounting project 4', 'accounting project 5', 'religion project 3'	['question_type_global', 'question_single_statement']
list all projects for [accounting]	'accounting project 1', 'accounting project 2', 'accounting project 3', 'accounting project 4', 'accounting project 5'	['question_type_global', 'question_two_hop_statement']
which courses did I submit late projects for?	'religion', 'accounting', 'philosophy'	['question_type_global', 'question_two_hop_statement']
[that assignment] is due on [May 16]
[that assignment] is [82] points
What is [Ashly]'s office?	'194'	['question_type_local']
show me the projects due on [May 08]	'religion project 2'	['question_type_global', 'question_two_hop_statement']
which homeworks are due before [May 24]?	'religion homework 1', 'accounting homework 1', 'philosophy homework 1', 'accounting homework 2'	['question_type_global', 'question_two_hop_statement']
[philosophy] has a new [philosophy homework 2] released
I submitted [philosophy homework 2]
[that homework] is [34] points
Who is the instructor for [religion]?	'Roslyn'	['question_type_local']
which courses did I submit late homeworks for?	'accounting'	['question_type_global', 'question_two_hop_statement']
which projects are due after [May 28]?	'accounting project 4', 'religion project 3'	['question_type_global', 'question_two_hop_statement']
list all assignments for [Roslyn]	'religion homework 1', 'religion project 1', 'religion project 2', 'religion project 3'	['question_type_global', 'question_three_hop_statement']
[this homework] is due on [May 22]
What is [Francoise]'s email	'Francoise@cornell.edu'	['question_type_local']
what are the late projects that i submitted?	'religion project 2', 'philosophy project 2', 'accounting project 3'	['question_type_global', 'question_two_hop_statement']
[religion] has a new [religion project 4] out
What are the assignments for [accounting]?	'accounting project 1', 'accounting project 2', 'accounting homework 1', 'accounting project 3', 'accounting project 4', 'accounting project 5', 'accounting homework 2'	['question_type_local']
show me all projects i submitted	'religion project 1', 'philosophy project 1', 'religion project 2', 'philosophy project 2', 'accounting project 3', 'accounting project 4', 'accounting project 5', 'religion project 3'	['question_type_global', 'question_two_hop_statement']
[philosophy homework 3] is released for [philosophy]
I submitted [that project] late
[religion project 4] is due on [May 26]
what are all the homeworks due?	'religion homework 1', 'accounting homework 1', 'philosophy homework 1', 'accounting homework 2', 'philosophy homework 2', 'philosophy homework 3'	['question_type_global', 'question_single_statement']
list all assignments that i submitted for [Roslyn]	'religion homework 1', 'religion project 1', 'religion project 2', 'religion project 3', 'religion project 4'	['question_type_global', 'question_three_hop_statement']
which projects did I submit late?	'religion project 2', 'philosophy project 2', 'accounting project 3', 'religion project 4'	['question_type_global', 'question_two_hop_statement']
show me the homeworks due on [May 01]	'religion homework 1'	['question_type_global', 'question_two_hop_statement']
who did I submit assignments late to	'Roslyn', 'Bob'	['question_type_global', 'question_three_hop_statement']
[this assignment] is worth [44] points
what did I get on [accounting project 4]?	4	['question_type_local']
list assignments that are due on [June 05]	'religion project 3'	['question_type_global', 'question_two_hop_statement']
what homeworks do I have to do for [Roslyn]?	'religion homework 1'	['question_type_global', 'question_three_hop_statement']
[this project] is now due on [May 28]
there is a [professor] named [Loyd]
[Loyd]'s email is [Loyd@yahoo.com]
[this professor] is in [P267]
How much is [philosophy project 2] worth?	30	['question_type_local']
show me all the late assignments that i submitted	'religion project 2', 'philosophy project 2', 'accounting homework 1', 'accounting project 3', 'accounting homework 2', 'religion project 4'	['question_type_global', 'question_two_hop_statement']
what are the courses for which i submitted late homeworks?	'accounting'	['question_type_global', 'question_two_hop_statement']
what assignments do I have to do for [Bob]?	'philosophy project 1', 'philosophy project 2', 'philosophy homework 1', 'philosophy homework 2', 'philosophy homework 3'	['question_type_global', 'question_three_hop_statement']
what assignments did i submit late for [Bob]?	'philosophy project 2'	['question_type_global', 'question_three_hop_statement']
what instructors did i have late projects for?	'Roslyn', 'Bob'	['question_type_global', 'question_three_hop_statement']
[philosophy homework 4] is out for [philosophy]
[this assignment] is [71] points
What are the assignments for [philosophy]?	'philosophy project 1', 'philosophy project 2', 'philosophy homework 1', 'philosophy homework 2', 'philosophy homework 3', 'philosophy homework 4'	['question_type_local']
which courses did I submit late assignments for?	'religion', 'accounting', 'philosophy'	['question_type_global', 'question_two_hop_statement']
what assignments do I have to do for [Roslyn]?	'religion homework 1', 'religion project 1', 'religion project 2', 'religion project 3', 'religion project 4'	['question_type_global', 'question_three_hop_statement']
list all assignments	'religion homework 1', 'religion project 1', 'philosophy project 1', 'accounting project 1', 'religion project 2', 'accounting project 2', 'philosophy project 2', 'accounting homework 1', 'philosophy homework 1', 'accounting project 3', 'accounting project 4', 'accounting project 5', 'religion project 3', 'accounting homework 2', 'philosophy homework 2', 'religion project 4', 'philosophy homework 3', 'philosophy homework 4'	['question_type_global', 'question_single_statement']
list all homeworks	'religion homework 1', 'accounting homework 1', 'philosophy homework 1', 'accounting homework 2', 'philosophy homework 2', 'philosophy homework 3', 'philosophy homework 4'	['question_type_global', 'question_single_statement']
list all projects	'religion project 1', 'philosophy project 1', 'accounting project 1', 'religion project 2', 'accounting project 2', 'philosophy project 2', 'accounting project 3', 'accounting project 4', 'accounting project 5', 'religion project 3', 'religion project 4'	['question_type_global', 'question_single_statement']
show me the assignments due on [May 16]	'accounting homework 2'	['question_type_global', 'question_two_hop_statement']
I submitted [this assignment] and received 57 points
What is [Bob]'s email	'Bob@gmail.com'	['question_type_local']
list all homeworks that i submitted	'religion homework 1', 'accounting homework 1', 'philosophy homework 1', 'accounting homework 2', 'philosophy homework 2', 'philosophy homework 4'	['question_type_global', 'question_two_hop_statement']
what are the assignments that i submitted for [religion]	'religion homework 1', 'religion project 1', 'religion project 2', 'religion project 3', 'religion project 4'	['question_type_global', 'question_two_hop_statement']
what projects do I have to do?	'religion project 1', 'philosophy project 1', 'accounting project 1', 'religion project 2', 'accounting project 2', 'philosophy project 2', 'accounting project 3', 'accounting project 4', 'accounting project 5', 'religion project 3', 'religion project 4'	['question_type_global', 'question_single_statement']
list all projects that i submitted late for [Bob]	'philosophy project 2'	['question_type_global', 'question_three_hop_statement']
show me the assignments due on [June 05]	'religion project 3'	['question_type_global', 'question_two_hop_statement']
The deadline of [philosophy homework 4] is [May 22]
