I am taking a [calculus] course
I am taking a [english composition] course
there is a [professor] named [Hanna]
[that person] is in [4358]
What office is [Hanna] in?	'4358'	['question_type_local']
[english composition] has a new [english composition project 1] out
there is a [professor] named [Albertha]
[this person] is in [4358]
[this professor] is the instructor for [english composition]
there is new [calculus homework 1] for [calculus]
[this assignment] is about [introduction]
[calculus homework 1] is [82] points
there is a new [project] for [calculus]
[that project] is worth [13] points
[Danita] is a [professor]
[this assignment] is about [decision trees]
[calculus project 1] is due on [December 23]
I submitted [calculus project 1] late and received 9 points
show me all the late projects that i submitted	'calculus project 1'	['question_type_global', 'question_two_hop_statement']
which projects did I submit late?	'calculus project 1'	['question_type_global', 'question_two_hop_statement']
which assignments are due before [December 26]?	'calculus project 1'	['question_type_global', 'question_two_hop_statement']
[Genevive] is a [professor]
list all the professors	'Hanna', 'Albertha', 'Danita', 'Genevive'	['question_type_global', 'question_single_statement']
How many points did I get on [that project]	9	['question_type_local']
list all assignments for [calculus]	'calculus project 1'	['question_type_global', 'question_two_hop_statement']
I am taking a [government] course
[that person] is in [577]
what projects do I have to do?	'english composition project 1', 'calculus project 1'	['question_type_global', 'question_single_statement']
[Hanna] teaches [that course]
[Yoshiko] is a [professor]
how much did I get on [calculus project 1]?	9	['question_type_local']
show me all late assignments i submitted for [calculus]	'calculus project 1'	['question_type_global', 'question_two_hop_statement']
there is a new [homework] for [government]
[Yoshiko] is in [4358]
what did I get on [calculus project 1]?	9	['question_type_local']
what are the courses for which I submitted projects late	'calculus'	['question_type_global', 'question_two_hop_statement']
[government homework 1] is due on [December 29]
[this assignment] is about [Cloning]
which homeworks are due before [December 31]?	'government homework 1'	['question_type_global', 'question_two_hop_statement']
What courses is [Albertha] teaching?	'english composition'	['question_type_local']
I submitted [that assignment]
list all assignments	'english composition project 1', 'calculus homework 1', 'calculus project 1', 'government homework 1'	['question_type_global', 'question_single_statement']
what are the courses for which I submitted assignments late	'calculus'	['question_type_global', 'question_two_hop_statement']
show all professors	'Hanna', 'Albertha', 'Danita', 'Genevive', 'Yoshiko'	['question_type_global', 'question_single_statement']
[government homework 1] is [66] points
When is [that homework] due?	'December 29'	['question_type_local']
which assignments are due after [December 28]?	'government homework 1'	['question_type_global', 'question_two_hop_statement']
what are the late assignments that i submitted	'calculus project 1'	['question_type_global', 'question_two_hop_statement']
What are the assignments for [calculus]?	'calculus homework 1', 'calculus project 1'	['question_type_local']
what are all the assignments due?	'english composition project 1', 'calculus homework 1', 'calculus project 1', 'government homework 1'	['question_type_global', 'question_single_statement']
what are all the homeworks due for [Hanna]?	'government homework 1'	['question_type_global', 'question_three_hop_statement']
which homeworks are due after [December 24]?	'government homework 1'	['question_type_global', 'question_two_hop_statement']
[english composition homework 1] is released for [english composition]
what projects do I have to do for [calculus]?	'calculus project 1'	['question_type_global', 'question_two_hop_statement']
List all assignments for [government]	'government homework 1'	['question_type_local']
what projects do I have to do for [english composition]?	'english composition project 1'	['question_type_global', 'question_two_hop_statement']
what assignments do I have to do for [Albertha]?	'english composition project 1', 'english composition homework 1'	['question_type_global', 'question_three_hop_statement']
list all projects that i submitted	'calculus project 1'	['question_type_global', 'question_two_hop_statement']
The deadline of [english composition homework 1] is [December 29]
there is a new [project] for [calculus]
The topic of [that project] is [Cells]
[that project] is worth [26] points
how much did I get on [calculus project 1]?	9	['question_type_local']
[government project 1] is released for [government]
I submitted [government project 1]
[this assignment] is on [Evolution]
The deadline of [government project 1] is [December 30]
[calculus] has a new [calculus homework 2] out
[that project] is worth [49] points
The deadline of [english composition project 1] is [December 28]
The topic of [english composition project 1] is [svm]
[this project] is [23] points
When is [english composition homework 1] due?	'December 29'	['question_type_local']
which homeworks are due on [December 29]?	'government homework 1', 'english composition homework 1'	['question_type_global', 'question_two_hop_statement']
which projects are due before [December 26]?	'calculus project 1'	['question_type_global', 'question_two_hop_statement']
I submitted [english composition project 1] and received 23 points
When is the deadline of [government project 1]?	'December 30'	['question_type_local']
what projects did i submit for [english composition]?	'english composition project 1'	['question_type_global', 'question_two_hop_statement']
list all projects	'english composition project 1', 'calculus project 1', 'calculus project 2', 'government project 1'	['question_type_global', 'question_single_statement']
list all assignments that i submitted for [Hanna]	'government homework 1', 'government project 1'	['question_type_global', 'question_three_hop_statement']
what are all the projects due?	'english composition project 1', 'calculus project 1', 'calculus project 2', 'government project 1'	['question_type_global', 'question_single_statement']
what are the assignments that i submitted for [Albertha]	'english composition project 1'	['question_type_global', 'question_three_hop_statement']
[government homework 2] is out for [government]
[that homework] is worth [16] points
The topic of [that homework] is [reinforcement learning]
[calculus project 3] is out for [calculus]
[that project] is worth [92] points
I submitted [this project] late and received 92 points
The topic of [that project] is [supervised learning]
I submitted [english composition homework 1] on time
[this homework] is worth [33] points
How many points is [government project 1] worth?	49	['question_type_local']
what assignments did i submit?	'english composition project 1', 'calculus project 1', 'government homework 1', 'english composition homework 1', 'government project 1', 'calculus project 3'	['question_type_global', 'question_two_hop_statement']
[this assignment] is about [expectation maximization]
What is [government homework 2] on?	'reinforcement learning'	['question_type_local']
list all assignments	'english composition project 1', 'calculus homework 1', 'calculus project 1', 'government homework 1', 'english composition homework 1', 'calculus project 2', 'government project 1', 'calculus homework 2', 'government homework 2', 'calculus project 3'	['question_type_global', 'question_single_statement']
what projects did i submit?	'english composition project 1', 'calculus project 1', 'government project 1', 'calculus project 3'	['question_type_global', 'question_two_hop_statement']
which projects are due on [December 30]?	'government project 1'	['question_type_global', 'question_two_hop_statement']
there is new [english composition homework 2] for [english composition]
which projects are due before [December 30]?	'english composition project 1', 'calculus project 1'	['question_type_global', 'question_two_hop_statement']
The topic of [english composition homework 2] is [k means]
I submitted [this homework] late
[that homework] is [39] points
[that assignment] is due on [January 13]
What is [calculus homework 1] on?	'introduction'	['question_type_local']
list all projects for [government]	'government project 1'	['question_type_global', 'question_two_hop_statement']
what are the late assignments that i submitted	'calculus project 1', 'calculus project 3', 'english composition homework 2'	['question_type_global', 'question_two_hop_statement']
who are the professors?	'Hanna', 'Albertha', 'Danita', 'Genevive', 'Yoshiko'	['question_type_global', 'question_single_statement']
what homeworks do I have to do?	'calculus homework 1', 'government homework 1', 'english composition homework 1', 'calculus homework 2', 'government homework 2', 'english composition homework 2'	['question_type_global', 'question_single_statement']
What is [government homework 1] on?	'Cloning'	['question_type_local']
what assignments do I have to do?	'english composition project 1', 'calculus homework 1', 'calculus project 1', 'government homework 1', 'english composition homework 1', 'calculus project 2', 'government project 1', 'calculus homework 2', 'government homework 2', 'calculus project 3', 'english composition homework 2'	['question_type_global', 'question_single_statement']
which professors did I submit late assignments for?	'Albertha'	['question_type_global', 'question_three_hop_statement']
list all homeworks that i submitted late for [Albertha]	'english composition homework 2'	['question_type_global', 'question_three_hop_statement']
What is [english composition homework 1] on?	'expectation maximization'	['question_type_local']
what are the late projects that i submitted?	'calculus project 1', 'calculus project 3'	['question_type_global', 'question_two_hop_statement']
list all projects that i submitted late	'calculus project 1', 'calculus project 3'	['question_type_global', 'question_two_hop_statement']
on which assignments did I get full credit?	'english composition project 1', 'calculus project 3'	['question_type_global', 'question_three_hop_statement']
show me all the late projects that i submitted	'calculus project 1', 'calculus project 3'	['question_type_global', 'question_two_hop_statement']
When is the deadline of [calculus project 1]?	'December 23'	['question_type_local']
which professors did I submit late homeworks for?	'Albertha'	['question_type_global', 'question_three_hop_statement']
what assignments did i submit for [government]?	'government homework 1', 'government project 1'	['question_type_global', 'question_two_hop_statement']
which courses did I submit late homeworks for?	'english composition'	['question_type_global', 'question_two_hop_statement']
what are the assignments that i submitted?	'english composition project 1', 'calculus project 1', 'government homework 1', 'english composition homework 1', 'government project 1', 'calculus project 3', 'english composition homework 2'	['question_type_global', 'question_two_hop_statement']
I submitted [government homework 2] on time and received 16 points
show me all assignments that i submitted for [Albertha]	'english composition project 1', 'english composition homework 1', 'english composition homework 2'	['question_type_global', 'question_three_hop_statement']
[government homework 2] is due on [January 13]
there is new [government homework 3] for [government]
What is [calculus project 1] on?	'decision trees'	['question_type_local']
list all projects that i submitted	'english composition project 1', 'calculus project 1', 'government project 1', 'calculus project 3'	['question_type_global', 'question_two_hop_statement']
The deadline of [government homework 3] is [January 09]
What is [calculus project 2] on?	'Cells'	['question_type_local']
what projects did i submit late?	'calculus project 1', 'calculus project 3'	['question_type_global', 'question_two_hop_statement']
what instructors did i have late assignments for?	'Albertha'	['question_type_global', 'question_three_hop_statement']
which homeworks did I submit for [government]?	'government homework 1', 'government homework 2'	['question_type_global', 'question_two_hop_statement']
which projects are due before [January 02]?	'english composition project 1', 'calculus project 1', 'government project 1'	['question_type_global', 'question_two_hop_statement']
what are all the assignments due for [Hanna]?	'government homework 1', 'government project 1', 'government homework 2', 'government homework 3'	['question_type_global', 'question_three_hop_statement']
which projects are due before [January 12]?	'english composition project 1', 'calculus project 1', 'government project 1'	['question_type_global', 'question_two_hop_statement']
what homeworks do I have to do for [english composition]?	'english composition homework 1', 'english composition homework 2'	['question_type_global', 'question_two_hop_statement']
what courses did i have late projects for?	'calculus'	['question_type_global', 'question_two_hop_statement']
I submitted [that homework]
[english composition homework 3] is released for [english composition]
The deadline of [english composition homework 3] is [January 21]
what are the courses for which i submitted late assignments?	'calculus', 'english composition'	['question_type_global', 'question_two_hop_statement']
[this homework] is worth [68] points
I submitted [this homework] and received 56 points
what did I get on [government homework 2]?	16	['question_type_local']
show me all projects i submitted	'english composition project 1', 'calculus project 1', 'government project 1', 'calculus project 3'	['question_type_global', 'question_two_hop_statement']
[english composition homework 4] is out for [english composition]
what are the projects that i submitted?	'english composition project 1', 'calculus project 1', 'government project 1', 'calculus project 3'	['question_type_global', 'question_two_hop_statement']
what are the homeworks that i submitted?	'government homework 1', 'english composition homework 1', 'government homework 2', 'english composition homework 2', 'government homework 3', 'english composition homework 3'	['question_type_global', 'question_two_hop_statement']
list homeworks that are due on [December 29]	'government homework 1', 'english composition homework 1'	['question_type_global', 'question_two_hop_statement']
I submitted [english composition homework 4]
The deadline of [this assignment] is [January 29]
what did I get on [english composition project 1]?	23	['question_type_local']
what instructors did i have late assignments for?	'Albertha'	['question_type_global', 'question_three_hop_statement']
list all homeworks that i submitted late	'english composition homework 2'	['question_type_global', 'question_two_hop_statement']
who are the professors?	'Hanna', 'Albertha', 'Danita', 'Genevive', 'Yoshiko'	['question_type_global', 'question_single_statement']
[this homework] is [59] points
which projects did I submit for [english composition]?	'english composition project 1'	['question_type_global', 'question_two_hop_statement']
show me all the late projects that i submitted	'calculus project 1', 'calculus project 3'	['question_type_global', 'question_two_hop_statement']
what assignments do I have to do?	'english composition project 1', 'calculus homework 1', 'calculus project 1', 'government homework 1', 'english composition homework 1', 'calculus project 2', 'government project 1', 'calculus homework 2', 'government homework 2', 'calculus project 3', 'english composition homework 2', 'government homework 3', 'english composition homework 3', 'english composition homework 4'	['question_type_global', 'question_single_statement']
what assignments did i submit late?	'calculus project 1', 'calculus project 3', 'english composition homework 2'	['question_type_global', 'question_two_hop_statement']
[calculus project 4] is released for [calculus]
The deadline of [that project] is [February 02]
[this assignment] is worth [91] points
I submitted [calculus project 4] and received 91 points
When is the deadline of [government homework 3]?	'January 09'	['question_type_local']
what are all the projects due for [government]?	'government project 1'	['question_type_global', 'question_two_hop_statement']
what are all the assignments due for [Hanna]?	'government homework 1', 'government project 1', 'government homework 2', 'government homework 3'	['question_type_global', 'question_three_hop_statement']
[that project] is now due on [January 31]
[english composition project 2] is released for [english composition]
how much did I get on [calculus project 3]?	92	['question_type_local']
which projects are due after [January 30]?	'calculus project 4'	['question_type_global', 'question_two_hop_statement']
[english composition project 2] is worth [79] points
I submitted [that assignment] on time and received 3 points
list all homeworks that i submitted late	'english composition homework 2'	['question_type_global', 'question_two_hop_statement']
what assignments do I have to do for [Hanna]?	'government homework 1', 'government project 1', 'government homework 2', 'government homework 3'	['question_type_global', 'question_three_hop_statement']
what assignments do I have to do?	'english composition project 1', 'calculus homework 1', 'calculus project 1', 'government homework 1', 'english composition homework 1', 'calculus project 2', 'government project 1', 'calculus homework 2', 'government homework 2', 'calculus project 3', 'english composition homework 2', 'government homework 3', 'english composition homework 3', 'english composition homework 4', 'calculus project 4', 'english composition project 2'	['question_type_global', 'question_single_statement']
[that project] is due on [December 30]
List all homeworks for [calculus]	'calculus homework 1', 'calculus homework 2'	['question_type_local']
what are all the homeworks due for [calculus]?	'calculus homework 1', 'calculus homework 2'	['question_type_global', 'question_two_hop_statement']
list all assignments for [Hanna]	'government homework 1', 'government project 1', 'government homework 2', 'government homework 3'	['question_type_global', 'question_three_hop_statement']
what are all the homeworks due?	'calculus homework 1', 'government homework 1', 'english composition homework 1', 'calculus homework 2', 'government homework 2', 'english composition homework 2', 'government homework 3', 'english composition homework 3', 'english composition homework 4'	['question_type_global', 'question_single_statement']
show me the assignments due on [December 28]	'english composition project 1'	['question_type_global', 'question_two_hop_statement']
show me all late homeworks i submitted for [english composition]	'english composition homework 2'	['question_type_global', 'question_two_hop_statement']
which assignments are due after [January 21]?	'english composition homework 4', 'calculus project 4'	['question_type_global', 'question_two_hop_statement']
show me all the late projects that i submitted	'calculus project 1', 'calculus project 3'	['question_type_global', 'question_two_hop_statement']
[government] has a new [government project 2] out
I submitted [government project 2]
[this project] is due on [January 09]
How many points did I get on [calculus project 3]	92	['question_type_local']
show me all homeworks i submitted for [Albertha]	'english composition homework 1', 'english composition homework 2', 'english composition homework 3', 'english composition homework 4'	['question_type_global', 'question_three_hop_statement']
list all homeworks	'calculus homework 1', 'government homework 1', 'english composition homework 1', 'calculus homework 2', 'government homework 2', 'english composition homework 2', 'government homework 3', 'english composition homework 3', 'english composition homework 4'	['question_type_global', 'question_single_statement']
which homeworks are due on [December 29]?	'government homework 1', 'english composition homework 1'	['question_type_global', 'question_two_hop_statement']
[this project] is worth [40] points
show me all the late assignments that i submitted	'calculus project 1', 'calculus project 3', 'english composition homework 2'	['question_type_global', 'question_two_hop_statement']
which projects did I submit for [Hanna]?	'government project 1', 'government project 2'	['question_type_global', 'question_three_hop_statement']
What is the topic of [english composition project 1]?	'svm'	['question_type_local']
what assignments do I have to do?	'english composition project 1', 'calculus homework 1', 'calculus project 1', 'government homework 1', 'english composition homework 1', 'calculus project 2', 'government project 1', 'calculus homework 2', 'government homework 2', 'calculus project 3', 'english composition homework 2', 'government homework 3', 'english composition homework 3', 'english composition homework 4', 'calculus project 4', 'english composition project 2', 'government project 2'	['question_type_global', 'question_single_statement']
show me all assignments that i submitted for [Albertha]	'english composition project 1', 'english composition homework 1', 'english composition homework 2', 'english composition homework 3', 'english composition homework 4', 'english composition project 2'	['question_type_global', 'question_three_hop_statement']
[government homework 3] is worth [23] points
[government homework 4] is released for [government]
I submitted [government homework 4] late
[that assignment] is due on [February 02]
[this assignment] is worth [46] points
which homeworks are due before [January 23]?	'government homework 1', 'english composition homework 1', 'government homework 2', 'english composition homework 2', 'government homework 3', 'english composition homework 3'	['question_type_global', 'question_two_hop_statement']
which professors did I submit late homeworks for?	'Hanna', 'Albertha'	['question_type_global', 'question_three_hop_statement']
what instructors did i have late assignments for?	'Hanna', 'Albertha'	['question_type_global', 'question_three_hop_statement']
List all homeworks for [government]	'government homework 1', 'government homework 2', 'government homework 3', 'government homework 4'	['question_type_local']
what assignments do I have to do for [Hanna]?	'government homework 1', 'government project 1', 'government homework 2', 'government homework 3', 'government project 2', 'government homework 4'	['question_type_global', 'question_three_hop_statement']
list all homeworks that i submitted late	'english composition homework 2', 'government homework 4'	['question_type_global', 'question_two_hop_statement']
show me the projects due on [December 28]	'english composition project 1'	['question_type_global', 'question_two_hop_statement']
list all projects for [Albertha]	'english composition project 1', 'english composition project 2'	['question_type_global', 'question_three_hop_statement']
list all projects for [government]	'government project 1', 'government project 2'	['question_type_global', 'question_two_hop_statement']
When is [english composition project 1] due?	'December 28'	['question_type_local']
which projects did I submit?	'english composition project 1', 'calculus project 1', 'government project 1', 'calculus project 3', 'calculus project 4', 'english composition project 2', 'government project 2'	['question_type_global', 'question_two_hop_statement']
list all projects that i submitted for [Albertha]	'english composition project 1', 'english composition project 2'	['question_type_global', 'question_three_hop_statement']
what are the courses for which I submitted homeworks late	'english composition', 'government'	['question_type_global', 'question_two_hop_statement']
What is [Hanna]'s office?	'4358'	['question_type_local']
what homeworks did i submit?	'government homework 1', 'english composition homework 1', 'government homework 2', 'english composition homework 2', 'government homework 3', 'english composition homework 3', 'english composition homework 4', 'government homework 4'	['question_type_global', 'question_two_hop_statement']
what assignments did i submit?	'english composition project 1', 'calculus project 1', 'government homework 1', 'english composition homework 1', 'government project 1', 'government homework 2', 'calculus project 3', 'english composition homework 2', 'government homework 3', 'english composition homework 3', 'english composition homework 4', 'calculus project 4', 'english composition project 2', 'government project 2', 'government homework 4'	['question_type_global', 'question_two_hop_statement']
which assignments did I submit late for [english composition]?	'english composition homework 2'	['question_type_global', 'question_two_hop_statement']
what homeworks did i submit late?	'english composition homework 2', 'government homework 4'	['question_type_global', 'question_two_hop_statement']
which homeworks are due before [January 28]?	'government homework 1', 'english composition homework 1', 'government homework 2', 'english composition homework 2', 'government homework 3', 'english composition homework 3'	['question_type_global', 'question_two_hop_statement']
list all assignments for [Albertha]	'english composition project 1', 'english composition homework 1', 'english composition homework 2', 'english composition homework 3', 'english composition homework 4', 'english composition project 2'	['question_type_global', 'question_three_hop_statement']
what projects did i submit for [Hanna]?	'government project 1', 'government project 2'	['question_type_global', 'question_three_hop_statement']
[government homework 5] is out for [government]
[government homework 5] is [67] points
[that assignment] is due on [January 20]
What is [Genevive]'s office?	'577'	['question_type_local']
show me all courses for which i submitted at least one late assignment	'calculus', 'english composition', 'government'	['question_type_global', 'question_two_hop_statement']
how many points is [government project 2]?	40	['question_type_local']
what are the courses for which i submitted late projects?	'calculus'	['question_type_global', 'question_two_hop_statement']
what are the homeworks that i submitted for [Hanna]	'government homework 1', 'government homework 2', 'government homework 3', 'government homework 4'	['question_type_global', 'question_three_hop_statement']
which homeworks are due after [January 16]?	'english composition homework 3', 'english composition homework 4', 'government homework 4', 'government homework 5'	['question_type_global', 'question_two_hop_statement']
which assignments did I submit late for [Hanna]?	'government homework 4'	['question_type_global', 'question_three_hop_statement']
show me all the late assignments that i submitted	'calculus project 1', 'calculus project 3', 'english composition homework 2', 'government homework 4'	['question_type_global', 'question_two_hop_statement']
list all assignments that i submitted late for [Hanna]	'government homework 4'	['question_type_global', 'question_three_hop_statement']
[english composition] has a new [english composition homework 5] released
[english composition homework 5] is [60] points
[calculus] is taught by [Genevive]
When is [government homework 5] due?	'January 20'	['question_type_local']
show me all late assignments i submitted for [government]	'government homework 4'	['question_type_global', 'question_two_hop_statement']
what courses did i have late projects for?	'calculus'	['question_type_global', 'question_two_hop_statement']
what projects do I have to do for [Albertha]?	'english composition project 1', 'english composition project 2'	['question_type_global', 'question_three_hop_statement']
How many points did I get on [calculus project 4]	91	['question_type_local']
what are the late assignments that i submitted	'calculus project 1', 'calculus project 3', 'english composition homework 2', 'government homework 4'	['question_type_global', 'question_two_hop_statement']
what are all the projects due for [Hanna]?	'government project 1', 'government project 2'	['question_type_global', 'question_three_hop_statement']
which projects are due after [December 29]?	'government project 1', 'calculus project 4', 'english composition project 2', 'government project 2'	['question_type_global', 'question_two_hop_statement']
which projects did I submit?	'english composition project 1', 'calculus project 1', 'government project 1', 'calculus project 3', 'calculus project 4', 'english composition project 2', 'government project 2'	['question_type_global', 'question_two_hop_statement']
what are the projects that i submitted for [Hanna]	'government project 1', 'government project 2'	['question_type_global', 'question_three_hop_statement']
what projects did i submit for [Albertha]?	'english composition project 1', 'english composition project 2'	['question_type_global', 'question_three_hop_statement']
show me all projects i submitted for [Genevive]	'calculus project 1', 'calculus project 3', 'calculus project 4'	['question_type_global', 'question_three_hop_statement']
which homeworks did I submit?	'government homework 1', 'english composition homework 1', 'government homework 2', 'english composition homework 2', 'government homework 3', 'english composition homework 3', 'english composition homework 4', 'government homework 4'	['question_type_global', 'question_two_hop_statement']
what projects did i submit for [english composition]?	'english composition project 1', 'english composition project 2'	['question_type_global', 'question_two_hop_statement']
what are the homeworks that i submitted for [government]	'government homework 1', 'government homework 2', 'government homework 3', 'government homework 4'	['question_type_global', 'question_two_hop_statement']
what homeworks did i submit late for [government]?	'government homework 4'	['question_type_global', 'question_two_hop_statement']
[calculus project 5] is out for [this course]
[that assignment] is worth [74] points
I submitted [this assignment] on time and received 74 points
[calculus project 5] is due on [January 25]
show me all courses for which i submitted at least one late project	'calculus'	['question_type_global', 'question_two_hop_statement']
what are the projects that i submitted?	'english composition project 1', 'calculus project 1', 'government project 1', 'calculus project 3', 'calculus project 4', 'english composition project 2', 'government project 2', 'calculus project 5'	['question_type_global', 'question_two_hop_statement']
what are the courses for which i submitted late homeworks?	'english composition', 'government'	['question_type_global', 'question_two_hop_statement']
When is [this project] due?	'January 25'	['question_type_local']
list projects that are due on [January 09]	'government project 2'	['question_type_global', 'question_two_hop_statement']
what are the assignments that i submitted?	'english composition project 1', 'calculus project 1', 'government homework 1', 'english composition homework 1', 'government project 1', 'government homework 2', 'calculus project 3', 'english composition homework 2', 'government homework 3', 'english composition homework 3', 'english composition homework 4', 'calculus project 4', 'english composition project 2', 'government project 2', 'government homework 4', 'calculus project 5'	['question_type_global', 'question_two_hop_statement']
what projects do I have to do for [english composition]?	'english composition project 1', 'english composition project 2'	['question_type_global', 'question_two_hop_statement']
which assignments did I submit late for [calculus]?	'calculus project 1', 'calculus project 3'	['question_type_global', 'question_two_hop_statement']
show me all assignments i submitted	'english composition project 1', 'calculus project 1', 'government homework 1', 'english composition homework 1', 'government project 1', 'government homework 2', 'calculus project 3', 'english composition homework 2', 'government homework 3', 'english composition homework 3', 'english composition homework 4', 'calculus project 4', 'english composition project 2', 'government project 2', 'government homework 4', 'calculus project 5'	['question_type_global', 'question_two_hop_statement']
What is the topic of [government homework 1]?	'Cloning'	['question_type_local']
which projects did I submit for [Hanna]?	'government project 1', 'government project 2'	['question_type_global', 'question_three_hop_statement']
[english composition] has a new [english composition project 3] released
[english composition project 3] is worth [28] points
[this assignment] is due on [January 21]
list all homeworks that i submitted late	'english composition homework 2', 'government homework 4'	['question_type_global', 'question_two_hop_statement']
which homeworks are due after [January 12]?	'government homework 2', 'english composition homework 2', 'english composition homework 3', 'english composition homework 4', 'government homework 4', 'government homework 5'	['question_type_global', 'question_two_hop_statement']
which projects are due after [January 21]?	'calculus project 4', 'calculus project 5'	['question_type_global', 'question_two_hop_statement']
