create a [professor] named [Willis]
[that professor]'s department is [psychology]
[he] is in [026]
I am taking a [algebra] course
[that professor] teaches [that class]
[Jack] is a [professor]
Which department is [Willis] in?	'psychology'	['question_type_local']
who are the professors?	'Willis', 'Jack'	['question_type_global', 'question_single_statement']
the affiliation of [Jack] is [physics]
[this person]'s office is [310]
Which department is [that professor] in?	'physics'	['question_type_local']
there is a new [homework] for [algebra]
I submitted [this assignment]
[that assignment] is worth [60] points
[algebra project 1] is out for [algebra]
The topic of [this project] is [unsupervised learning]
I submitted [this assignment]
Show me all assignments due for [algebra]	'algebra homework 1', 'algebra project 1'	['question_type_local']
What is [this assignment] on?	'unsupervised learning'	['question_type_local']
list all projects for [Willis]	'algebra project 1'	['question_type_global', 'question_three_hop_statement']
list all assignments	'algebra homework 1', 'algebra project 1'	['question_type_global', 'question_single_statement']
list all assignments that i submitted	'algebra homework 1', 'algebra project 1'	['question_type_global', 'question_two_hop_statement']
which projects did I submit?	'algebra project 1'	['question_type_global', 'question_two_hop_statement']
[algebra project 1] is worth [11] points
what are all the homeworks due for [Willis]?	'algebra homework 1'	['question_type_global', 'question_three_hop_statement']
what assignments do I have to do for [algebra]?	'algebra project 1'	['question_type_global', 'question_two_hop_statement']
what projects do I have to do?	'algebra project 1'	['question_type_global', 'question_single_statement']
[this project] is due on [March 12]
What are the homeworks for [algebra]?	'algebra homework 1'	['question_type_local']
what homeworks did i submit for [algebra]?	'algebra homework 1'	['question_type_global', 'question_two_hop_statement']
create a [professor] named [Hanna]
the affiliation of [this professor] is [applied physics]
[that person]'s office is [026]
list all the professors	'Willis', 'Jack', 'Hanna'	['question_type_global', 'question_single_statement']
what are all the assignments due for [algebra]?	'algebra project 1'	['question_type_global', 'question_two_hop_statement']
who are the professors affiliated with [physics]?	'Jack'	['question_type_global', 'question_two_hop_statement']
list all homeworks that i submitted for [algebra]	'algebra homework 1'	['question_type_global', 'question_two_hop_statement']
show all professors	'Willis', 'Jack', 'Hanna'	['question_type_global', 'question_single_statement']
there is a new [homework] for [algebra]
The topic of [this assignment] is [vc dimension]
show me all projects i submitted	'algebra project 1'	['question_type_global', 'question_two_hop_statement']
what assignments did i submit?	'algebra homework 1', 'algebra project 1'	['question_type_global', 'question_two_hop_statement']
list the professors in the [physics] department	'Jack'	['question_type_global', 'question_two_hop_statement']
what homeworks do I have to do?	'algebra homework 1', 'algebra homework 2'	['question_type_global', 'question_single_statement']
[algebra homework 2] is due on [March 16]
[that assignment] is worth [59] points
I submitted [this homework] and received 39 points
Show me all assignments due for [algebra]	'algebra homework 1', 'algebra project 1', 'algebra homework 2'	['question_type_local']
what are all the assignments due?	'algebra homework 1', 'algebra project 1', 'algebra homework 2'	['question_type_global', 'question_single_statement']
what are all the projects due for [Willis]?	'algebra project 1'	['question_type_global', 'question_three_hop_statement']
list all homeworks	'algebra homework 1', 'algebra homework 2'	['question_type_global', 'question_single_statement']
which projects are due before [March 13]?	'algebra project 1'	['question_type_global', 'question_two_hop_statement']
When is [that assignment] due?	'March 16'	['question_type_local']
list all homeworks for [algebra]	'algebra homework 1', 'algebra homework 2'	['question_type_global', 'question_two_hop_statement']
list all projects for [algebra]	'algebra project 1'	['question_type_global', 'question_two_hop_statement']
What is [Willis]'s office?	'026'	['question_type_local']
list all projects	'algebra project 1'	['question_type_global', 'question_single_statement']
What is the topic of [algebra project 1]?	'unsupervised learning'	['question_type_local']
list all assignments for [algebra]	'algebra project 1'	['question_type_global', 'question_two_hop_statement']
there is a new [homework] for [algebra]
which homeworks are due on [March 16]?	'algebra homework 2'	['question_type_global', 'question_two_hop_statement']
what are all the homeworks due for [Willis]?	'algebra homework 1', 'algebra homework 2', 'algebra homework 3'	['question_type_global', 'question_three_hop_statement']
what are the assignments that i submitted for [Willis]	'algebra homework 1', 'algebra project 1', 'algebra homework 2'	['question_type_global', 'question_three_hop_statement']
show me all homeworks i submitted for [Willis]	'algebra homework 1', 'algebra homework 2'	['question_type_global', 'question_three_hop_statement']
list all assignments that i submitted	'algebra homework 1', 'algebra project 1', 'algebra homework 2'	['question_type_global', 'question_two_hop_statement']
show all professors	'Willis', 'Jack', 'Hanna'	['question_type_global', 'question_single_statement']
How much is [algebra homework 2] worth?	59	['question_type_local']
what projects did i submit?	'algebra project 1'	['question_type_global', 'question_two_hop_statement']
which projects are due before [March 15]?	'algebra project 1'	['question_type_global', 'question_two_hop_statement']
list assignments that are due on [March 12]	'algebra project 1'	['question_type_global', 'question_two_hop_statement']
list all assignments for [algebra]	'algebra project 1'	['question_type_global', 'question_two_hop_statement']
I am taking a [statistics] course
The topic of [this homework] is [grammar induction]
I submitted [algebra homework 3]
list all projects that i submitted	'algebra project 1'	['question_type_global', 'question_two_hop_statement']
which assignments are due after [March 15]?	'algebra homework 2'	['question_type_global', 'question_two_hop_statement']
which professors are in the [physics] department?	'Jack'	['question_type_global', 'question_two_hop_statement']
[statistics project 1] is released for [statistics]
[that project] is due on [March 11]
[that assignment] is on [expectation maximization]
[statistics project 1] is [35] points
create a [professor] named [Peggy]
[this professor]'s office is [026]
how many points is [algebra homework 1]?	60	['question_type_local']
what are the homeworks that i submitted?	'algebra homework 1', 'algebra homework 2', 'algebra homework 3'	['question_type_global', 'question_two_hop_statement']
which assignments are due after [March 14]?	'algebra homework 2'	['question_type_global', 'question_two_hop_statement']
I am taking a [english] course
[Hanna] is the instructor for [english]
how much did I get on [algebra homework 2]?	39	['question_type_local']
When is [algebra project 1] due?	'March 12'	['question_type_local']
show me the assignments due on [March 16]	'algebra homework 2'	['question_type_global', 'question_two_hop_statement']
what are all the homeworks due?	'algebra homework 1', 'algebra homework 2', 'algebra homework 3'	['question_type_global', 'question_single_statement']
show me the homeworks due on [March 16]	'algebra homework 2'	['question_type_global', 'question_two_hop_statement']
which projects are due on [March 11]?	'statistics project 1'	['question_type_global', 'question_two_hop_statement']
list assignments that are due on [March 11]	'statistics project 1'	['question_type_global', 'question_two_hop_statement']
[statistics project 2] is released for [statistics]
change [Hanna]'s department to [physics]
I submitted [statistics project 2]
[statistics project 2] is [21] points
how many points is [algebra homework 2]?	59	['question_type_local']
what are all the assignments due?	'algebra homework 1', 'algebra project 1', 'algebra homework 2', 'algebra homework 3', 'statistics project 1', 'statistics project 2'	['question_type_global', 'question_single_statement']
[statistics] has a new [statistics homework 1] released
[this homework] is worth [28] points
The deadline of [that assignment] is [March 12]
I submitted [that assignment] late and received 21 points
How many points is [algebra homework 1] worth?	60	['question_type_local']
list all homeworks for [Willis]	'algebra homework 1', 'algebra homework 2', 'algebra homework 3'	['question_type_global', 'question_three_hop_statement']
what are the projects that i submitted?	'algebra project 1', 'statistics project 2'	['question_type_global', 'question_two_hop_statement']
what projects do I have to do for [statistics]?	'statistics project 1', 'statistics project 2'	['question_type_global', 'question_two_hop_statement']
what homeworks do I have to do?	'algebra homework 1', 'algebra homework 2', 'algebra homework 3', 'statistics homework 1'	['question_type_global', 'question_single_statement']
[this assignment] is about [decision trees]
What are the assignments for [statistics]?	'statistics project 1', 'statistics project 2', 'statistics homework 1'	['question_type_local']
show me the homeworks due on [March 12]	'statistics homework 1'	['question_type_global', 'question_two_hop_statement']
which homeworks did I submit late?	'statistics homework 1'	['question_type_global', 'question_two_hop_statement']
what are all the homeworks due for [Willis]?	'algebra homework 1', 'algebra homework 2', 'algebra homework 3'	['question_type_global', 'question_three_hop_statement']
there is new [algebra homework 4] for [algebra]
I submitted [algebra homework 4] late
[algebra homework 4] is worth [18] points
[statistics project 2] is due on [March 28]
create a [professor] named [Kristeen]
[algebra] has a new [algebra project 2] released
The deadline of [this project] is [March 22]
[that assignment] is worth [83] points
[algebra project 2] is on [clustering]
what assignments do I have to do?	'algebra homework 1', 'algebra project 1', 'algebra homework 2', 'algebra homework 3', 'statistics project 1', 'statistics project 2', 'statistics homework 1', 'algebra homework 4', 'algebra project 2'	['question_type_global', 'question_single_statement']
what are the courses for which I submitted assignments late	'algebra', 'statistics'	['question_type_global', 'question_two_hop_statement']
what are the projects that i submitted for [Willis]	'algebra project 1'	['question_type_global', 'question_three_hop_statement']
what assignments did i submit?	'algebra homework 1', 'algebra project 1', 'algebra homework 2', 'algebra homework 3', 'statistics project 2', 'statistics homework 1', 'algebra homework 4'	['question_type_global', 'question_two_hop_statement']
Show me all assignments due for [algebra]	'algebra homework 1', 'algebra project 1', 'algebra homework 2', 'algebra homework 3', 'algebra homework 4', 'algebra project 2'	['question_type_local']
who are the professors?	'Willis', 'Jack', 'Hanna', 'Peggy', 'Kristeen'	['question_type_global', 'question_single_statement']
list all projects	'algebra project 1', 'statistics project 1', 'statistics project 2', 'algebra project 2'	['question_type_global', 'question_single_statement']
what instructors did i have late assignments for?	'Willis'	['question_type_global', 'question_three_hop_statement']
there is a new [homework] for [english]
[this homework] is worth [53] points
The deadline of [english homework 1] is [March 07]
List all assignments for [statistics]	'statistics project 1', 'statistics project 2', 'statistics homework 1'	['question_type_local']
which assignments are due before [March 29]?	'algebra project 1', 'algebra homework 2', 'statistics project 1', 'statistics project 2', 'statistics homework 1', 'algebra project 2', 'english homework 1'	['question_type_global', 'question_two_hop_statement']
show me all late homeworks i submitted	'statistics homework 1', 'algebra homework 4'	['question_type_global', 'question_two_hop_statement']
[this assignment] is on [nearest neighbor algorithm]
I submitted [that assignment] and received 42 points
When is [algebra homework 2] due?	'March 16'	['question_type_local']
which projects are due on [March 12]?	'algebra project 1'	['question_type_global', 'question_two_hop_statement']
which assignments are due after [March 19]?	'statistics project 2', 'algebra project 2'	['question_type_global', 'question_two_hop_statement']
which projects are due before [March 28]?	'algebra project 1', 'statistics project 1', 'algebra project 2'	['question_type_global', 'question_two_hop_statement']
what assignments did i submit for [english]?	'english homework 1'	['question_type_global', 'question_two_hop_statement']
list all homeworks for [statistics]	'statistics homework 1'	['question_type_global', 'question_two_hop_statement']
what homeworks did i submit for [statistics]?	'statistics homework 1'	['question_type_global', 'question_two_hop_statement']
which assignments did I submit for [english]?	'english homework 1'	['question_type_global', 'question_two_hop_statement']
When is [algebra project 2] due?	'March 22'	['question_type_local']
which professors did I submit late assignments for?	'Willis'	['question_type_global', 'question_three_hop_statement']
which projects are due after [March 22]?	'statistics project 2'	['question_type_global', 'question_two_hop_statement']
which assignments did I submit?	'algebra homework 1', 'algebra project 1', 'algebra homework 2', 'algebra homework 3', 'statistics project 2', 'statistics homework 1', 'algebra homework 4', 'english homework 1'	['question_type_global', 'question_two_hop_statement']
How many points is [algebra project 1] worth?	11	['question_type_local']
list the professors in the [None] department	'Peggy', 'Kristeen'	['question_type_global', 'question_two_hop_statement']
what are the late homeworks that i submitted?	'statistics homework 1', 'algebra homework 4'	['question_type_global', 'question_two_hop_statement']
How many points did I get on [this assignment]	42	['question_type_local']
what are the projects that i submitted?	'algebra project 1', 'statistics project 2'	['question_type_global', 'question_two_hop_statement']
show me all late assignments i submitted for [Willis]	'algebra homework 4'	['question_type_global', 'question_three_hop_statement']
list all assignments that i submitted	'algebra homework 1', 'algebra project 1', 'algebra homework 2', 'algebra homework 3', 'statistics project 2', 'statistics homework 1', 'algebra homework 4', 'english homework 1'	['question_type_global', 'question_two_hop_statement']
what courses did i have late homeworks for?	'algebra', 'statistics'	['question_type_global', 'question_two_hop_statement']
list the professors in the [psychology] department	'Willis'	['question_type_global', 'question_two_hop_statement']
What department is [Hanna] affiliated with?	'physics'	['question_type_local']
list all homeworks for [Hanna]	'english homework 1'	['question_type_global', 'question_three_hop_statement']
what projects did i submit for [algebra]?	'algebra project 1'	['question_type_global', 'question_two_hop_statement']
list all assignments for [statistics]	'statistics project 1', 'statistics project 2'	['question_type_global', 'question_two_hop_statement']
which homeworks are due after [March 04]?	'algebra homework 2', 'statistics homework 1', 'english homework 1'	['question_type_global', 'question_two_hop_statement']
What office is [Jack] in?	'310'	['question_type_local']
show me all courses for which i submitted at least one late homework	'algebra', 'statistics'	['question_type_global', 'question_two_hop_statement']
what are the late assignments that i submitted	'statistics homework 1', 'algebra homework 4'	['question_type_global', 'question_two_hop_statement']
which assignments are due before [March 21]?	'algebra project 1', 'algebra homework 2', 'statistics project 1', 'statistics homework 1', 'english homework 1'	['question_type_global', 'question_two_hop_statement']
list all homeworks	'algebra homework 1', 'algebra homework 2', 'algebra homework 3', 'statistics homework 1', 'algebra homework 4', 'english homework 1'	['question_type_global', 'question_single_statement']
which projects did I submit?	'algebra project 1', 'statistics project 2'	['question_type_global', 'question_two_hop_statement']
[algebra] has a new [algebra homework 5] out
[algebra homework 5] is due on [May 09]
I submitted [algebra homework 5] late
[that homework] is about [svm]
[that assignment] is [51] points
I am taking a [accounting] course
I submitted [algebra project 2] on time and received 55 points
[Kristeen] is the instructor for [that course]
When is [statistics project 2] due?	'March 28'	['question_type_local']
list homeworks that are due on [March 12]	'statistics homework 1'	['question_type_global', 'question_two_hop_statement']
what assignments did i submit late?	'statistics homework 1', 'algebra homework 4', 'algebra homework 5'	['question_type_global', 'question_two_hop_statement']
what courses did i have late homeworks for?	'algebra', 'statistics'	['question_type_global', 'question_two_hop_statement']
[this person] is affiliated with the [english] department
[this professor]'s office is [310]
there is new [accounting homework 1] for [accounting]
What department is [Willis] affiliated with?	'psychology'	['question_type_local']
which projects are due before [March 30]?	'algebra project 1', 'statistics project 1', 'statistics project 2', 'algebra project 2'	['question_type_global', 'question_two_hop_statement']
which projects are due before [March 15]?	'algebra project 1', 'statistics project 1'	['question_type_global', 'question_two_hop_statement']
create a [professor] named [Cyndi]
I submitted [accounting homework 1]
[this assignment] is due on [March 11]
What is the topic of [algebra project 2]?	'clustering'	['question_type_local']
show me all projects i submitted for [algebra]	'algebra project 1', 'algebra project 2'	['question_type_global', 'question_two_hop_statement']
which assignments did I submit for [algebra]?	'algebra homework 1', 'algebra project 1', 'algebra homework 2', 'algebra homework 3', 'algebra homework 4', 'algebra project 2', 'algebra homework 5'	['question_type_global', 'question_two_hop_statement']
what are the courses for which i submitted late homeworks?	'algebra', 'statistics'	['question_type_global', 'question_two_hop_statement']
[accounting homework 1] is worth [69] points
The deadline of [statistics homework 1] moved to [March 12]
what assignments do I have to do?	'algebra homework 1', 'algebra project 1', 'algebra homework 2', 'algebra homework 3', 'statistics project 1', 'statistics project 2', 'statistics homework 1', 'algebra homework 4', 'algebra project 2', 'english homework 1', 'algebra homework 5', 'accounting homework 1'	['question_type_global', 'question_single_statement']
what projects do I have to do for [Willis]?	'algebra project 1', 'algebra project 2'	['question_type_global', 'question_three_hop_statement']
change [Hanna]'s department to [applied physics]
which assignments are due after [March 19]?	'statistics project 2', 'algebra project 2', 'algebra homework 5'	['question_type_global', 'question_two_hop_statement']
what homeworks did i submit late?	'statistics homework 1', 'algebra homework 4', 'algebra homework 5'	['question_type_global', 'question_two_hop_statement']
show me the assignments due on [March 16]	'algebra homework 2'	['question_type_global', 'question_two_hop_statement']
list all homeworks that i submitted for [Willis]	'algebra homework 1', 'algebra homework 2', 'algebra homework 3', 'algebra homework 4', 'algebra homework 5'	['question_type_global', 'question_three_hop_statement']
there is new [statistics homework 2] for [statistics]
[this assignment] is worth [83] points
how many points is [algebra homework 4]?	18	['question_type_local']
what are all the assignments due for [Willis]?	'algebra homework 1', 'algebra project 1', 'algebra homework 2', 'algebra homework 3', 'algebra homework 4', 'algebra project 2', 'algebra homework 5'	['question_type_global', 'question_three_hop_statement']
which assignments are due on [March 11]?	'statistics project 1', 'accounting homework 1'	['question_type_global', 'question_two_hop_statement']
[statistics homework 2] is due on [March 22]
I submitted [this assignment] and received 83 points
how much did I get on [this assignment]?	83	['question_type_local']
who are the instructors to whom i submitted any late assignments?	'Willis'	['question_type_global', 'question_three_hop_statement']
on which assignments did I get full credit?	'statistics homework 2'	['question_type_global', 'question_three_hop_statement']
which homeworks are due before [March 16]?	'statistics homework 1', 'english homework 1', 'accounting homework 1'	['question_type_global', 'question_two_hop_statement']
What is the topic of [algebra project 1]?	'unsupervised learning'	['question_type_local']
what are the courses for which i submitted late homeworks?	'algebra', 'statistics'	['question_type_global', 'question_two_hop_statement']
there is a new [project] for [accounting]
I submitted [that project] late
The deadline of [this project] is [March 07]
How much is [algebra project 1] worth?	11	['question_type_local']
which homeworks are due after [March 20]?	'algebra homework 5', 'statistics homework 2'	['question_type_global', 'question_two_hop_statement']
list all homeworks that i submitted	'algebra homework 1', 'algebra homework 2', 'algebra homework 3', 'statistics homework 1', 'algebra homework 4', 'english homework 1', 'algebra homework 5', 'accounting homework 1', 'statistics homework 2'	['question_type_global', 'question_two_hop_statement']
what homeworks do I have to do for [english]?	'english homework 1'	['question_type_global', 'question_two_hop_statement']
what assignments did i submit for [english]?	'english homework 1'	['question_type_global', 'question_two_hop_statement']
what homeworks do I have to do for [Hanna]?	'english homework 1'	['question_type_global', 'question_three_hop_statement']
on which assignments did I get full credit?	'statistics homework 2'	['question_type_global', 'question_three_hop_statement']
[that project] is worth [46] points
what are all the projects due for [algebra]?	'algebra project 1', 'algebra project 2'	['question_type_global', 'question_two_hop_statement']
[english] has a new [english project 1] released
how many points did I receive on [algebra project 2]?	55	['question_type_local']
list projects that are due on [March 28]	'statistics project 2'	['question_type_global', 'question_two_hop_statement']
which homeworks are due after [March 26]?	'algebra homework 5'	['question_type_global', 'question_two_hop_statement']
there is a new [homework] for [algebra]
I submitted [english project 1] late
I submitted [this homework]
[this homework] is due on [May 17]
List all assignments for [english]	'english homework 1', 'english project 1'	['question_type_local']
which projects did I submit late?	'accounting project 1', 'english project 1'	['question_type_global', 'question_two_hop_statement']
what are all the homeworks due for [Hanna]?	'english homework 1'	['question_type_global', 'question_three_hop_statement']
[that homework] is now due on [May 14]
Who is the instructor for [english]?	'Hanna'	['question_type_local']
show me all homeworks i submitted for [Hanna]	'english homework 1'	['question_type_global', 'question_three_hop_statement']
which homeworks did I submit for [Kristeen]?	'accounting homework 1'	['question_type_global', 'question_three_hop_statement']
what are the courses for which i submitted late assignments?	'algebra', 'statistics', 'english', 'accounting'	['question_type_global', 'question_two_hop_statement']
which projects are due before [May 10]?	'algebra project 1', 'statistics project 1', 'statistics project 2', 'algebra project 2', 'accounting project 1'	['question_type_global', 'question_two_hop_statement']
there is a new [homework] for [algebra]
[algebra homework 6] is [80] points
What department is [Kristeen] affiliated with?	'english'	['question_type_local']
what projects do I have to do?	'algebra project 1', 'statistics project 1', 'statistics project 2', 'algebra project 2', 'accounting project 1', 'english project 1'	['question_type_global', 'question_single_statement']
which homeworks are due after [March 11]?	'algebra homework 2', 'statistics homework 1', 'algebra homework 5', 'statistics homework 2', 'algebra homework 6'	['question_type_global', 'question_two_hop_statement']
show me all homeworks i submitted	'algebra homework 1', 'algebra homework 2', 'algebra homework 3', 'statistics homework 1', 'algebra homework 4', 'english homework 1', 'algebra homework 5', 'accounting homework 1', 'statistics homework 2', 'algebra homework 6'	['question_type_global', 'question_two_hop_statement']
[statistics project 3] is out for [statistics]
[english homework 2] is out for [english]
[that project] is [48] points
[this project] is due on [April 02]
what are all the projects due for [english]?	'english project 1'	['question_type_global', 'question_two_hop_statement']
Which department is [Kristeen] in?	'english'	['question_type_local']
list all homeworks for [Hanna]	'english homework 1', 'english homework 2'	['question_type_global', 'question_three_hop_statement']
I submitted [that assignment] and received 44 points
I submitted [algebra homework 7] late
[algebra homework 7] is worth [98] points
What office is [Jack] in?	'310'	['question_type_local']
what are the courses for which i submitted late projects?	'english', 'accounting'	['question_type_global', 'question_two_hop_statement']
what homeworks do I have to do?	'algebra homework 1', 'algebra homework 2', 'algebra homework 3', 'statistics homework 1', 'algebra homework 4', 'english homework 1', 'algebra homework 5', 'accounting homework 1', 'statistics homework 2', 'algebra homework 6', 'algebra homework 7', 'english homework 2'	['question_type_global', 'question_single_statement']
on which assignments did I get full credit?	'statistics homework 2'	['question_type_global', 'question_three_hop_statement']
how much did I get on [algebra project 2]?	55	['question_type_local']
which assignments did I submit late for [accounting]?	'accounting project 1'	['question_type_global', 'question_two_hop_statement']
which homeworks are due after [March 18]?	'algebra homework 5', 'statistics homework 2', 'algebra homework 6'	['question_type_global', 'question_two_hop_statement']
which projects are due after [March 28]?	'statistics project 3'	['question_type_global', 'question_two_hop_statement']
list all homeworks	'algebra homework 1', 'algebra homework 2', 'algebra homework 3', 'statistics homework 1', 'algebra homework 4', 'english homework 1', 'algebra homework 5', 'accounting homework 1', 'statistics homework 2', 'algebra homework 6', 'algebra homework 7', 'english homework 2'	['question_type_global', 'question_single_statement']
[that homework] is due on [April 18]
