create a [professor] named [Tawnya]
[this person]'s office is [788]
[that person]'s email is [Tawnya@gmail.com]
What is [that person]'s email	'Tawnya@gmail.com'	['question_type_local']
I am taking a course called [us history]
[that course] has a new [us history homework 1] out
[that assignment] is on [k means]
I submitted [this homework] on time
I am taking a [economics] course
[this homework] is worth [15] points
[that homework] is due on [April 03]
Show me all assignments due for [us history]	'us history homework 1'	['question_type_local']
list all homeworks that i submitted	'us history homework 1'	['question_type_global', 'question_two_hop_statement']
which homeworks are due on [April 03]?	'us history homework 1'	['question_type_global', 'question_two_hop_statement']
List all homeworks for [us history]	'us history homework 1'	['question_type_local']
[Tawnya] teaches [us history]
What office is [she] in?	'788'	['question_type_local']
what homeworks did i submit for [Tawnya]?	'us history homework 1'	['question_type_global', 'question_three_hop_statement']
When is the deadline of [us history homework 1]?	'April 03'	['question_type_local']
What is the topic of [us history homework 1]?	'k means'	['question_type_local']
list all assignments that i submitted	'us history homework 1'	['question_type_global', 'question_two_hop_statement']
there is a [professor] named [Albertha]
What courses is [Tawnya] teaching?	'us history'	['question_type_local']
show all professors	'Tawnya', 'Albertha'	['question_type_global', 'question_single_statement']
what assignments did i submit?	'us history homework 1'	['question_type_global', 'question_two_hop_statement']
there is a new [homework] for [economics]
[that professor]'s office is [322]
[this professor]'s email is [Albertha@yahoo.com]
I am taking a [algebra] course
What is [us history homework 1] on?	'k means'	['question_type_local']
[this course] is taught by [she]
[economics] has a new [economics project 1] released
The deadline of [this project] is [March 30]
[that project] is worth [72] points
[economics homework 1] is due on [March 31]
[that homework] is on [Animals]
I submitted [this assignment]
there is a new [homework] for [economics]
[economics homework 1] is worth [41] points
What office is [Albertha] in?	'322'	['question_type_local']
what are all the projects due?	'economics project 1'	['question_type_global', 'question_single_statement']
[economics project 1] is about [bayesian models]
What is [Tawnya]'s office?	'788'	['question_type_local']
which homeworks are due after [March 29]?	'us history homework 1', 'economics homework 1'	['question_type_global', 'question_two_hop_statement']
I submitted [economics homework 2] on time
[that homework] is [33] points
The topic of [economics homework 2] is [Molds & Fungi]
The deadline of [economics homework 2] is [April 17]
there is a new [project] for [us history]
create a [professor] named [Cyndi]
[this person]'s office is [788]
[Cyndi]'s email is [Cyndi@harvard.edu]
which assignments are due after [March 30]?	'us history homework 1', 'economics homework 1', 'economics homework 2'	['question_type_global', 'question_two_hop_statement']
list all projects for [Tawnya]	'us history project 1'	['question_type_global', 'question_three_hop_statement']
What is the topic of [economics homework 2]?	'Molds & Fungi'	['question_type_local']
What office is [Tawnya] in?	'788'	['question_type_local']
which homeworks are due before [April 18]?	'us history homework 1', 'economics homework 1', 'economics homework 2'	['question_type_global', 'question_two_hop_statement']
show me the projects due on [March 30]	'economics project 1'	['question_type_global', 'question_two_hop_statement']
What is the topic of [us history homework 1]?	'k means'	['question_type_local']
which projects are due before [April 17]?	'economics project 1'	['question_type_global', 'question_two_hop_statement']
show all professors	'Tawnya', 'Albertha', 'Cyndi'	['question_type_global', 'question_single_statement']
which homeworks are due after [April 01]?	'us history homework 1', 'economics homework 2'	['question_type_global', 'question_two_hop_statement']
[economics project 2] is out for [economics]
What is [Tawnya]'s office?	'788'	['question_type_local']
show me all assignments i submitted	'us history homework 1', 'economics homework 1', 'economics homework 2'	['question_type_global', 'question_two_hop_statement']
[Casey] is a [professor]
[that project] is worth [75] points
list all the professors	'Tawnya', 'Albertha', 'Cyndi', 'Casey'	['question_type_global', 'question_single_statement']
[this professor]'s email is [Casey@cmu.edu]
[that professor]'s office is [788]
When is [us history homework 1] due?	'April 03'	['question_type_local']
which assignments are due before [April 02]?	'economics homework 1', 'economics project 1'	['question_type_global', 'question_two_hop_statement']
what assignments do I have to do for [Tawnya]?	'us history homework 1', 'us history project 1'	['question_type_global', 'question_three_hop_statement']
list assignments that are due on [April 17]	'economics homework 2'	['question_type_global', 'question_two_hop_statement']
I am taking a [chemistry] course
[economics project 2] is on [expectation maximization]
What office is [Albertha] in?	'322'	['question_type_local']
which projects are due before [April 16]?	'economics project 1'	['question_type_global', 'question_two_hop_statement']
list assignments that are due on [April 03]	'us history homework 1'	['question_type_global', 'question_two_hop_statement']
I submitted [that assignment] and received 39 points
The deadline of [this project] is [April 15]
create a [professor] named [Zenaida]
Who is teaching [algebra]?	'Albertha'	['question_type_local']
what are all the projects due for [us history]?	'us history project 1'	['question_type_global', 'question_two_hop_statement']
show me the projects due on [April 15]	'economics project 2'	['question_type_global', 'question_two_hop_statement']
there is a new [project] for [economics]
[that person]'s office is [788]
[Zenaida]'s email is [Zenaida@yahoo.com]
What is [Casey]'s office?	'788'	['question_type_local']
which projects are due before [April 01]?	'economics project 1'	['question_type_global', 'question_two_hop_statement']
what homeworks did i submit for [Tawnya]?	'us history homework 1'	['question_type_global', 'question_three_hop_statement']
How much is [economics project 1] worth?	72	['question_type_local']
which assignments are due after [April 01]?	'us history homework 1', 'economics homework 2', 'economics project 2'	['question_type_global', 'question_two_hop_statement']
[economics homework 3] is out for [economics]
When is the deadline of [us history homework 1]?	'April 03'	['question_type_local']
which homeworks did I submit?	'us history homework 1', 'economics homework 1', 'economics homework 2'	['question_type_global', 'question_two_hop_statement']
I am taking a course called [religion]
[religion] is taught by [Casey]
Who is the instructor for [us history]?	'Tawnya'	['question_type_local']
list all assignments	'us history homework 1', 'economics homework 1', 'economics project 1', 'economics homework 2', 'us history project 1', 'economics project 2', 'economics project 3', 'economics homework 3'	['question_type_global', 'question_single_statement']
list projects that are due on [March 30]	'economics project 1'	['question_type_global', 'question_two_hop_statement']
which projects are due before [April 16]?	'economics project 1', 'economics project 2'	['question_type_global', 'question_two_hop_statement']
who are the professors?	'Tawnya', 'Albertha', 'Cyndi', 'Casey', 'Zenaida'	['question_type_global', 'question_single_statement']
[Will] is a [professor]
[Will] is in [788]
[this person]'s email is [Will@cmu.edu]
[Hanna] is a [professor]
[she]'s office is [322]
[this professor]'s email is [Hanna@cmu.edu]
[religion] has a new [religion homework 1] released
[this assignment] is due on [April 03]
[us history] has a new [us history homework 2] released
I submitted [religion homework 1]
[religion homework 1] is on [unsupervised learning]
how many points is [us history homework 1]?	15	['question_type_local']
list all homeworks for [religion]	'religion homework 1'	['question_type_global', 'question_two_hop_statement']
Show me all assignments due for [religion]	'religion homework 1'	['question_type_local']
which assignments are due after [April 02]?	'us history homework 1', 'economics homework 2', 'economics project 2', 'religion homework 1'	['question_type_global', 'question_two_hop_statement']
[this assignment] is worth [30] points
which homeworks are due on [April 17]?	'economics homework 2'	['question_type_global', 'question_two_hop_statement']
show me the assignments due on [March 30]	'economics project 1'	['question_type_global', 'question_two_hop_statement']
list all projects	'economics project 1', 'us history project 1', 'economics project 2', 'economics project 3'	['question_type_global', 'question_single_statement']
Who is the instructor for [us history]?	'Tawnya'	['question_type_local']
[Gia] is a [professor]
how many points is [economics homework 2]?	33	['question_type_local']
what homeworks do I have to do?	'us history homework 1', 'economics homework 1', 'economics homework 2', 'economics homework 3', 'religion homework 1', 'us history homework 2'	['question_type_global', 'question_single_statement']
[Gia]'s email is [Gia@yale.edu]
[this person] is in [329]
list all assignments that i submitted for [us history]	'us history homework 1'	['question_type_global', 'question_two_hop_statement']
show me all homeworks i submitted for [Casey]	'religion homework 1'	['question_type_global', 'question_three_hop_statement']
show me all projects i submitted	'economics project 2'	['question_type_global', 'question_two_hop_statement']
How much is [economics project 1] worth?	72	['question_type_local']
which projects are due on [March 30]?	'economics project 1'	['question_type_global', 'question_two_hop_statement']
What is [economics homework 2] on?	'Molds & Fungi'	['question_type_local']
show me all homeworks i submitted for [Tawnya]	'us history homework 1'	['question_type_global', 'question_three_hop_statement']
what assignments did i submit for [economics]?	'economics homework 1', 'economics homework 2', 'economics project 2'	['question_type_global', 'question_two_hop_statement']
there is a new [project] for [chemistry]
[that project] is worth [70] points
What courses is [Albertha] teaching?	'algebra'	['question_type_local']
list all assignments	'us history homework 1', 'economics homework 1', 'economics project 1', 'economics homework 2', 'us history project 1', 'economics project 2', 'economics project 3', 'economics homework 3', 'religion homework 1', 'us history homework 2', 'chemistry project 1'	['question_type_global', 'question_single_statement']
The deadline of [chemistry project 1] is [March 30]
[that project] is about [kernels]
Show me all assignments due for [economics]	'economics homework 1', 'economics project 1', 'economics homework 2', 'economics project 2', 'economics project 3', 'economics homework 3'	['question_type_local']
list all projects for [us history]	'us history project 1'	['question_type_global', 'question_two_hop_statement']
How many points is [economics project 1] worth?	72	['question_type_local']
which projects did I submit?	'economics project 2'	['question_type_global', 'question_two_hop_statement']
which assignments did I submit for [Casey]?	'religion homework 1'	['question_type_global', 'question_three_hop_statement']
how much did I get on [economics project 2]?	39	['question_type_local']
which homeworks are due after [April 02]?	'us history homework 1', 'economics homework 2', 'religion homework 1'	['question_type_global', 'question_two_hop_statement']
which projects are due after [April 01]?	'economics project 2'	['question_type_global', 'question_two_hop_statement']
there is new [us history project 2] for [us history]
[us history project 2] is about [deep learning]
[this assignment] is worth [48] points
I submitted [us history project 2] and received 48 points
Which professor is teaching [religion]?	'Casey'	['question_type_local']
which assignments are due before [April 02]?	'economics homework 1', 'economics project 1', 'chemistry project 1'	['question_type_global', 'question_two_hop_statement']
[that project] is due on [April 09]
show me all projects i submitted for [economics]	'economics project 2'	['question_type_global', 'question_two_hop_statement']
what are all the projects due?	'economics project 1', 'us history project 1', 'economics project 2', 'economics project 3', 'chemistry project 1', 'us history project 2'	['question_type_global', 'question_single_statement']
on which assignments did I get full credit?	'us history project 2'	['question_type_global', 'question_three_hop_statement']
Show me all homeworks due for [economics]	'economics homework 1', 'economics homework 2', 'economics homework 3'	['question_type_local']
which homeworks are due after [April 02]?	'us history homework 1', 'economics homework 2', 'religion homework 1'	['question_type_global', 'question_two_hop_statement']
How much is [religion homework 1] worth?	30	['question_type_local']
there is a new [project] for [economics]
[economics project 4] is worth [13] points
how many points did I receive on [us history project 2]?	48	['question_type_local']
show me all homeworks i submitted for [religion]	'religion homework 1'	['question_type_global', 'question_two_hop_statement']
The topic of [economics project 4] is [clustering]
When is the deadline of [chemistry project 1]?	'March 30'	['question_type_local']
list homeworks that are due on [March 31]	'economics homework 1'	['question_type_global', 'question_two_hop_statement']
which assignments did I submit?	'us history homework 1', 'economics homework 1', 'economics homework 2', 'economics project 2', 'religion homework 1', 'us history project 2'	['question_type_global', 'question_two_hop_statement']
list all homeworks	'us history homework 1', 'economics homework 1', 'economics homework 2', 'economics homework 3', 'religion homework 1', 'us history homework 2'	['question_type_global', 'question_single_statement']
[us history] has a new [us history homework 3] released
I submitted [that project] on time and received 3 points
what projects do I have to do for [us history]?	'us history project 1', 'us history project 2'	['question_type_global', 'question_two_hop_statement']
The deadline of [that project] is [May 01]
list all projects for [economics]	'economics project 1', 'economics project 2', 'economics project 3', 'economics project 4'	['question_type_global', 'question_two_hop_statement']
which projects are due on [April 15]?	'economics project 2'	['question_type_global', 'question_two_hop_statement']
How much is [economics project 2] worth?	75	['question_type_local']
list homeworks that are due on [April 03]	'us history homework 1', 'religion homework 1'	['question_type_global', 'question_two_hop_statement']
list all assignments for [Tawnya]	'us history homework 1', 'us history project 1', 'us history homework 2', 'us history project 2', 'us history homework 3'	['question_type_global', 'question_three_hop_statement']
[religion homework 2] is released for [religion]
The topic of [this homework] is [Cloning]
What is [Hanna]'s email	'Hanna@cmu.edu'	['question_type_local']
what projects did i submit?	'economics project 2', 'us history project 2', 'economics project 4'	['question_type_global', 'question_two_hop_statement']
list assignments that are due on [April 09]	'us history project 2'	['question_type_global', 'question_two_hop_statement']
[religion] has a new [religion project 1] out
The deadline of [this homework] is [April 07]
[this homework] is [71] points
I submitted [religion homework 2] on time and received 59 points
What is the topic of [economics project 2]?	'expectation maximization'	['question_type_local']
which homeworks are due before [May 02]?	'us history homework 1', 'economics homework 1', 'economics homework 2', 'religion homework 1', 'religion homework 2'	['question_type_global', 'question_two_hop_statement']
What office is [Will] in?	'788'	['question_type_local']
which projects are due after [April 03]?	'economics project 2', 'us history project 2', 'economics project 4'	['question_type_global', 'question_two_hop_statement']
how many points did I receive on [economics project 2]?	39	['question_type_local']
which projects did I submit?	'economics project 2', 'us history project 2', 'economics project 4'	['question_type_global', 'question_two_hop_statement']
what projects do I have to do for [chemistry]?	'chemistry project 1'	['question_type_global', 'question_two_hop_statement']
what assignments did i submit for [Tawnya]?	'us history homework 1', 'us history project 2'	['question_type_global', 'question_three_hop_statement']
what assignments do I have to do?	'us history homework 1', 'economics homework 1', 'economics project 1', 'economics homework 2', 'us history project 1', 'economics project 2', 'economics project 3', 'economics homework 3', 'religion homework 1', 'us history homework 2', 'chemistry project 1', 'us history project 2', 'economics project 4', 'us history homework 3', 'religion homework 2', 'religion project 1'	['question_type_global', 'question_single_statement']
show me the homeworks due on [March 31]	'economics homework 1'	['question_type_global', 'question_two_hop_statement']
what are the homeworks that i submitted?	'us history homework 1', 'economics homework 1', 'economics homework 2', 'religion homework 1', 'religion homework 2'	['question_type_global', 'question_two_hop_statement']
what did I get on [us history project 2]?	48	['question_type_local']
list all assignments	'us history homework 1', 'economics homework 1', 'economics project 1', 'economics homework 2', 'us history project 1', 'economics project 2', 'economics project 3', 'economics homework 3', 'religion homework 1', 'us history homework 2', 'chemistry project 1', 'us history project 2', 'economics project 4', 'us history homework 3', 'religion homework 2', 'religion project 1'	['question_type_global', 'question_single_statement']
How many points is [us history project 2] worth?	48	['question_type_local']
list all assignments for [economics]	'economics project 1', 'economics project 2', 'economics project 3', 'economics project 4'	['question_type_global', 'question_two_hop_statement']
what projects do I have to do for [Casey]?	'religion project 1'	['question_type_global', 'question_three_hop_statement']
What is [Cyndi]'s email	'Cyndi@harvard.edu'	['question_type_local']
show me all assignments i submitted	'us history homework 1', 'economics homework 1', 'economics homework 2', 'economics project 2', 'religion homework 1', 'us history project 2', 'economics project 4', 'religion homework 2'	['question_type_global', 'question_two_hop_statement']
What is [Casey]'s office?	'788'	['question_type_local']
What is [Zenaida]'s office?	'788'	['question_type_local']
The deadline of [that assignment] moved to [April 10]
[economics] is taught by [Will]
show me all homeworks i submitted for [Will]	'economics homework 1', 'economics homework 2'	['question_type_global', 'question_three_hop_statement']
[chemistry project 2] is released for [chemistry]
How much is [economics project 2] worth?	75	['question_type_local']
what homeworks do I have to do for [us history]?	'us history homework 1', 'us history homework 2', 'us history homework 3'	['question_type_global', 'question_two_hop_statement']
When is [us history project 2] due?	'April 09'	['question_type_local']
which projects are due after [April 07]?	'economics project 2', 'us history project 2', 'economics project 4'	['question_type_global', 'question_two_hop_statement']
who are the professors?	'Tawnya', 'Albertha', 'Cyndi', 'Casey', 'Zenaida', 'Will', 'Hanna', 'Gia'	['question_type_global', 'question_single_statement']
When is the deadline of [economics project 1]?	'March 30'	['question_type_local']
what projects do I have to do?	'economics project 1', 'us history project 1', 'economics project 2', 'economics project 3', 'chemistry project 1', 'us history project 2', 'economics project 4', 'religion project 1', 'chemistry project 2'	['question_type_global', 'question_single_statement']
list projects that are due on [May 01]	'economics project 4'	['question_type_global', 'question_two_hop_statement']
[economics] has a new [economics project 5] out
The deadline of [economics project 5] is [May 16]
I submitted [that assignment] on time
[that project] is [26] points
Who is teaching [algebra]?	'Albertha'	['question_type_local']
show me all projects i submitted for [Will]	'economics project 2', 'economics project 4', 'economics project 5'	['question_type_global', 'question_three_hop_statement']
what homeworks did i submit for [religion]?	'religion homework 1', 'religion homework 2'	['question_type_global', 'question_two_hop_statement']
What office is [Hanna] in?	'322'	['question_type_local']
what homeworks do I have to do for [Casey]?	'religion homework 1', 'religion homework 2'	['question_type_global', 'question_three_hop_statement']
what assignments do I have to do for [economics]?	'economics project 1', 'economics project 2', 'economics project 3', 'economics project 4', 'economics project 5'	['question_type_global', 'question_two_hop_statement']
How much is [chemistry project 1] worth?	70	['question_type_local']
how many points is [religion homework 1]?	30	['question_type_local']
list all projects for [Will]	'economics project 1', 'economics project 2', 'economics project 3', 'economics project 4', 'economics project 5'	['question_type_global', 'question_three_hop_statement']
I submitted [chemistry project 2] on time
[chemistry project 2] is [42] points
[chemistry] has a new [chemistry project 3] out
which homeworks did I submit for [economics]?	'economics homework 1', 'economics homework 2'	['question_type_global', 'question_two_hop_statement']
I submitted [chemistry project 3] late
The deadline of [that project] is [April 15]
[that project] is worth [43] points
[algebra project 1] is out for [algebra]
I submitted [algebra project 1]
[that assignment] is worth [56] points
[that assignment] is due on [March 30]
what did I get on [religion homework 2]?	59	['question_type_local']
what projects did i submit late for [chemistry]?	'chemistry project 3'	['question_type_global', 'question_two_hop_statement']
which projects are due before [May 15]?	'economics project 1', 'economics project 2', 'chemistry project 1', 'us history project 2', 'economics project 4', 'chemistry project 3', 'algebra project 1'	['question_type_global', 'question_two_hop_statement']
which projects are due before [April 13]?	'economics project 1', 'chemistry project 1', 'us history project 2', 'algebra project 1'	['question_type_global', 'question_two_hop_statement']
