[Emmie] is a [professor]
[that person] is affiliated with the [psychology] department
[Emmie]'s email is [Emmie@yahoo.com]
I am taking a course called [government]
[government] is taught by [Emmie]
list the professors in the [psychology] department	'Emmie'	['question_type_global', 'question_two_hop_statement']
[that person]'s department is now [biomedical engineering]
What is [that professor]'s department?	'biomedical engineering'	['question_type_local']
[government] has a new [government project 1] released
what projects do I have to do?	'government project 1'	['question_type_global', 'question_single_statement']
I submitted [government project 1] on time
List all assignments for [government]	'government project 1'	['question_type_local']
show me all projects i submitted for [Emmie]	'government project 1'	['question_type_global', 'question_three_hop_statement']
what projects did i submit for [Emmie]?	'government project 1'	['question_type_global', 'question_three_hop_statement']
[this assignment] is on [decision trees]
[that assignment] is worth [83] points
The deadline of [this project] is [February 15]
What department is [Emmie] affiliated with?	'biomedical engineering'	['question_type_local']
what assignments did i submit?	'government project 1'	['question_type_global', 'question_two_hop_statement']
What courses is [Emmie] teaching?	'government'	['question_type_local']
what assignments do I have to do for [Emmie]?	'government project 1'	['question_type_global', 'question_three_hop_statement']
List all assignments for [government]	'government project 1'	['question_type_local']
I am taking a course called [math]
Which professor is teaching [government]?	'Emmie'	['question_type_local']
which projects are due after [February 12]?	'government project 1'	['question_type_global', 'question_two_hop_statement']
When is [government project 1] due?	'February 15'	['question_type_local']
list all projects for [Emmie]	'government project 1'	['question_type_global', 'question_three_hop_statement']
create a [professor] named [Lucy]
[that professor] is affiliated with the [neuroscience] department
Which department is [Emmie] in?	'biomedical engineering'	['question_type_local']
I am taking a [history] course
[this person]'s email is [Lucy@cmu.edu]
list all assignments	'government project 1'	['question_type_global', 'question_single_statement']
show me all assignments that i submitted for [Emmie]	'government project 1'	['question_type_global', 'question_three_hop_statement']
[Lucy] teaches [history]
[that class] has a new [history project 1] out
[this project] is about [Molds & Fungi]
[this assignment] is worth [98] points
list all assignments that i submitted	'government project 1'	['question_type_global', 'question_two_hop_statement']
show me all assignments i submitted for [government]	'government project 1'	['question_type_global', 'question_two_hop_statement']
I submitted [that assignment] on time and received 98 points
[history project 1] is due on [February 16]
What is the topic of [government project 1]?	'decision trees'	['question_type_local']
what projects do I have to do?	'government project 1', 'history project 1'	['question_type_global', 'question_single_statement']
I am taking a [english] course
When is the deadline of [government project 1]?	'February 15'	['question_type_local']
there is a [professor] named [Kristeen]
the affiliation of [that person] is [neuroscience]
[Kristeen]'s email is [Kristeen@yahoo.com]
[english homework 1] is out for [english]
Which professor is teaching [history]?	'Lucy'	['question_type_local']
which professors are in the [biomedical engineering] department?	'Emmie'	['question_type_global', 'question_two_hop_statement']
list projects that are due on [February 16]	'history project 1'	['question_type_global', 'question_two_hop_statement']
who are the professors?	'Emmie', 'Lucy', 'Kristeen'	['question_type_global', 'question_single_statement']
The topic of [this assignment] is [Cells]
[that homework] is due on [February 15]
[english homework 1] is worth [55] points
What are the assignments for [government]?	'government project 1'	['question_type_local']
what assignments did i submit?	'government project 1', 'history project 1'	['question_type_global', 'question_two_hop_statement']
what projects do I have to do?	'government project 1', 'history project 1'	['question_type_global', 'question_single_statement']
[Kristeen]'s department is now [biomedical engineering]
Who is the instructor for [government]?	'Emmie'	['question_type_local']
list projects that are due on [February 15]	'government project 1'	['question_type_global', 'question_two_hop_statement']
[math homework 1] is released for [math]
[math homework 1] is worth [27] points
[this assignment] is about [svm]
I submitted [math homework 1] and received 9 points
what are the assignments that i submitted?	'government project 1', 'history project 1', 'math homework 1'	['question_type_global', 'question_two_hop_statement']
[government project 2] is out for [government]
How many points did I get on [history project 1]	98	['question_type_local']
which homeworks are due after [February 13]?	'english homework 1'	['question_type_global', 'question_two_hop_statement']
The deadline of [government project 2] is [February 23]
The deadline of [math homework 1] is [February 12]
What are the assignments for [math]?	'math homework 1'	['question_type_local']
list all homeworks that i submitted	'math homework 1'	['question_type_global', 'question_two_hop_statement']
list all assignments that i submitted for [Emmie]	'government project 1'	['question_type_global', 'question_three_hop_statement']
show me all projects i submitted	'government project 1', 'history project 1'	['question_type_global', 'question_two_hop_statement']
[math project 1] is out for [math]
how many points is [history project 1]?	98	['question_type_local']
What is [math homework 1] on?	'svm'	['question_type_local']
which projects did I submit for [government]?	'government project 1'	['question_type_global', 'question_two_hop_statement']
List all assignments for [math]	'math homework 1', 'math project 1'	['question_type_local']
which assignments did I submit?	'government project 1', 'history project 1', 'math homework 1'	['question_type_global', 'question_two_hop_statement']
what did I get on [math homework 1]?	9	['question_type_local']
which projects are due after [February 18]?	'government project 2'	['question_type_global', 'question_two_hop_statement']
what are all the homeworks due for [math]?	'math homework 1'	['question_type_global', 'question_two_hop_statement']
list assignments that are due on [February 16]	'history project 1'	['question_type_global', 'question_two_hop_statement']
what are the assignments that i submitted for [Lucy]	'history project 1'	['question_type_global', 'question_three_hop_statement']
[english homework 2] is out for [english]
[that homework] is [39] points
I submitted [that homework] late and received 39 points
[this assignment] is due on [February 17]
[english homework 2] is on [The Senses]
What is [Emmie]'s email	'Emmie@yahoo.com'	['question_type_local']
what are all the projects due for [math]?	'math project 1'	['question_type_global', 'question_two_hop_statement']
what are all the assignments due?	'government project 1', 'history project 1', 'english homework 1', 'math homework 1', 'government project 2', 'math project 1', 'english homework 2'	['question_type_global', 'question_single_statement']
show me all courses for which i submitted at least one late homework	'english'	['question_type_global', 'question_two_hop_statement']
which projects are due before [February 19]?	'government project 1', 'history project 1'	['question_type_global', 'question_two_hop_statement']
How many points did I get on [english homework 2]	39	['question_type_local']
what are all the assignments due for [Lucy]?	'history project 1'	['question_type_global', 'question_three_hop_statement']
[that homework] is now due on [February 18]
how many points did I receive on [math homework 1]?	9	['question_type_local']
there is a new [homework] for [history]
The deadline of [history homework 1] is [February 13]
I submitted [history homework 1]
list homeworks that are due on [February 15]	'english homework 1'	['question_type_global', 'question_two_hop_statement']
what are all the homeworks due for [Lucy]?	'history homework 1'	['question_type_global', 'question_three_hop_statement']
[history homework 2] is out for [history]
I submitted [history homework 2] late
The deadline of [that assignment] is [February 23]
[that homework] is worth [92] points
When is the deadline of [math homework 1]?	'February 12'	['question_type_local']
what homeworks did i submit late?	'english homework 2', 'history homework 2'	['question_type_global', 'question_two_hop_statement']
What is [Emmie]'s department?	'biomedical engineering'	['question_type_local']
which assignments did I submit?	'government project 1', 'history project 1', 'math homework 1', 'english homework 2', 'history homework 1', 'history homework 2'	['question_type_global', 'question_two_hop_statement']
who are the professors affiliated with [neuroscience]?	'Lucy'	['question_type_global', 'question_two_hop_statement']
show me all late assignments i submitted for [Lucy]	'history homework 2'	['question_type_global', 'question_three_hop_statement']
[history homework 2] is on [Plants]
there is new [english homework 3] for [english]
[english homework 3] is on [Viruses & other Microbes]
[that homework] is [13] points
I submitted [english homework 3] on time and received 10 points
[that assignment] is due on [February 24]
How many points is [government project 1] worth?	83	['question_type_local']
which professors did I submit late homeworks for?	'Lucy'	['question_type_global', 'question_three_hop_statement']
list all homeworks that i submitted for [Lucy]	'history homework 1', 'history homework 2'	['question_type_global', 'question_three_hop_statement']
which assignments are due after [February 10]?	'government project 1', 'history project 1', 'english homework 1', 'math homework 1', 'government project 2', 'english homework 2', 'history homework 1', 'history homework 2', 'english homework 3'	['question_type_global', 'question_two_hop_statement']
When is [english homework 1] due?	'February 15'	['question_type_local']
what are all the assignments due?	'government project 1', 'history project 1', 'english homework 1', 'math homework 1', 'government project 2', 'math project 1', 'english homework 2', 'history homework 1', 'history homework 2', 'english homework 3'	['question_type_global', 'question_single_statement']
what are the courses for which I submitted assignments late	'history', 'english'	['question_type_global', 'question_two_hop_statement']
list all homeworks that i submitted for [history]	'history homework 1', 'history homework 2'	['question_type_global', 'question_two_hop_statement']
[math project 2] is out for [math]
How many points did I get on [math homework 1]	9	['question_type_local']
which projects did I submit for [government]?	'government project 1'	['question_type_global', 'question_two_hop_statement']
list all projects	'government project 1', 'history project 1', 'government project 2', 'math project 1', 'math project 2'	['question_type_global', 'question_single_statement']
list all projects for [Emmie]	'government project 1', 'government project 2'	['question_type_global', 'question_three_hop_statement']
[english project 1] is out for [english]
[english project 1] is about [supervised learning]
I submitted [english project 1] late
What is [this project] on?	'supervised learning'	['question_type_local']
what are the projects that i submitted for [government]	'government project 1'	['question_type_global', 'question_two_hop_statement']
show me all the late assignments that i submitted	'english homework 2', 'history homework 2', 'english project 1'	['question_type_global', 'question_two_hop_statement']
what assignments did i submit for [Emmie]?	'government project 1'	['question_type_global', 'question_three_hop_statement']
The deadline of [this assignment] is [February 15]
What are the assignments for [math]?	'math homework 1', 'math project 1', 'math project 2'	['question_type_local']
which homeworks are due after [February 21]?	'history homework 2', 'english homework 3'	['question_type_global', 'question_two_hop_statement']
[english project 1] is worth [28] points
what projects did i submit?	'government project 1', 'history project 1', 'english project 1'	['question_type_global', 'question_two_hop_statement']
what are the courses for which i submitted late homeworks?	'history', 'english'	['question_type_global', 'question_two_hop_statement']
what homeworks do I have to do for [Lucy]?	'history homework 1', 'history homework 2'	['question_type_global', 'question_three_hop_statement']
list all projects	'government project 1', 'history project 1', 'government project 2', 'math project 1', 'math project 2', 'english project 1'	['question_type_global', 'question_single_statement']
show me all courses for which i submitted at least one late assignment	'history', 'english'	['question_type_global', 'question_two_hop_statement']
which homeworks are due before [February 16]?	'english homework 1', 'math homework 1', 'history homework 1'	['question_type_global', 'question_two_hop_statement']
list all homeworks that i submitted late for [Lucy]	'history homework 2'	['question_type_global', 'question_three_hop_statement']
list all homeworks that i submitted late	'english homework 2', 'history homework 2'	['question_type_global', 'question_two_hop_statement']
what projects did i submit for [government]?	'government project 1'	['question_type_global', 'question_two_hop_statement']
which assignments are due on [February 16]?	'history project 1'	['question_type_global', 'question_two_hop_statement']
what assignments do I have to do for [history]?	'history project 1'	['question_type_global', 'question_two_hop_statement']
what are the late assignments that i submitted for [history]	'history homework 2'	['question_type_global', 'question_two_hop_statement']
[math project 3] is released for [math]
[math project 3] is [88] points
I submitted [this project] on time and received 62 points
[math project 3] is on [bayesian models]
The deadline of [that assignment] is [March 05]
List all assignments for [government]	'government project 1', 'government project 2'	['question_type_local']
which homeworks are due before [February 16]?	'english homework 1', 'math homework 1', 'history homework 1'	['question_type_global', 'question_two_hop_statement']
what projects do I have to do?	'government project 1', 'history project 1', 'government project 2', 'math project 1', 'math project 2', 'english project 1', 'math project 3'	['question_type_global', 'question_single_statement']
what projects did i submit late?	'english project 1'	['question_type_global', 'question_two_hop_statement']
there is a new [homework] for [history]
[history homework 3] is about [Cloning]
How many points is [english homework 3] worth?	13	['question_type_local']
which assignments did I submit late?	'english homework 2', 'history homework 2', 'english project 1'	['question_type_global', 'question_two_hop_statement']
show me all the late projects that i submitted	'english project 1'	['question_type_global', 'question_two_hop_statement']
which homeworks are due after [February 15]?	'english homework 2', 'history homework 2', 'english homework 3'	['question_type_global', 'question_two_hop_statement']
create a [professor] named [Genevive]
I submitted [history homework 3]
[this homework] is due on [February 27]
When is [english homework 3] due?	'February 24'	['question_type_local']
what are the late assignments that i submitted	'english homework 2', 'history homework 2', 'english project 1'	['question_type_global', 'question_two_hop_statement']
which assignments are due before [February 18]?	'government project 1', 'history project 1', 'english homework 1', 'math homework 1', 'history homework 1', 'english project 1'	['question_type_global', 'question_two_hop_statement']
which assignments are due before [February 15]?	'math homework 1', 'history homework 1'	['question_type_global', 'question_two_hop_statement']
there is a new [homework] for [government]
[government homework 1] is [85] points
I submitted [government homework 1] late and received 82 points
which assignments are due after [February 26]?	'math project 3', 'history homework 3'	['question_type_global', 'question_two_hop_statement']
which assignments are due before [February 14]?	'math homework 1', 'history homework 1'	['question_type_global', 'question_two_hop_statement']
I submitted [math project 1]
[this project] is due on [February 15]
[that project] is worth [16] points
how many points did I receive on [history project 1]?	98	['question_type_local']
what homeworks did i submit?	'math homework 1', 'english homework 2', 'history homework 1', 'history homework 2', 'english homework 3', 'history homework 3', 'government homework 1'	['question_type_global', 'question_two_hop_statement']
there is a new [project] for [history]
I submitted [history project 2] late
[history project 2] is due on [March 01]
[history project 2] is worth [87] points
what did I get on [math homework 1]?	9	['question_type_local']
show me all assignments i submitted for [math]	'math homework 1', 'math project 1', 'math project 3'	['question_type_global', 'question_two_hop_statement']
How much is [math homework 1] worth?	27	['question_type_local']
which projects did I submit late?	'english project 1', 'history project 2'	['question_type_global', 'question_two_hop_statement']
what are the late projects that i submitted?	'english project 1', 'history project 2'	['question_type_global', 'question_two_hop_statement']
list all assignments that i submitted for [Emmie]	'government project 1', 'government homework 1'	['question_type_global', 'question_three_hop_statement']
which assignments did I submit late for [Emmie]?	'government homework 1'	['question_type_global', 'question_three_hop_statement']
When is the deadline of [english homework 1]?	'February 15'	['question_type_local']
what homeworks did i submit late for [history]?	'history homework 2'	['question_type_global', 'question_two_hop_statement']
which projects are due before [February 22]?	'government project 1', 'history project 1', 'math project 1', 'english project 1'	['question_type_global', 'question_two_hop_statement']
which assignments are due before [February 14]?	'math homework 1', 'history homework 1'	['question_type_global', 'question_two_hop_statement']
list all homeworks that i submitted late for [Emmie]	'government homework 1'	['question_type_global', 'question_three_hop_statement']
which courses did I submit late assignments for?	'government', 'history', 'english'	['question_type_global', 'question_two_hop_statement']
what are all the projects due for [history]?	'history project 1', 'history project 2'	['question_type_global', 'question_two_hop_statement']
which assignments did I submit late for [Emmie]?	'government homework 1'	['question_type_global', 'question_three_hop_statement']
show all professors	'Emmie', 'Lucy', 'Kristeen', 'Genevive'	['question_type_global', 'question_single_statement']
what courses did i have late assignments for?	'government', 'history', 'english'	['question_type_global', 'question_two_hop_statement']
which professors did I submit late projects for?	'Lucy'	['question_type_global', 'question_three_hop_statement']
what homeworks did i submit late for [Lucy]?	'history homework 2'	['question_type_global', 'question_three_hop_statement']
who are the instructors to whom i submitted any late assignments?	'Emmie', 'Lucy'	['question_type_global', 'question_three_hop_statement']
What department is [Lucy] affiliated with?	'neuroscience'	['question_type_local']
which assignments are due after [March 02]?	'math project 3'	['question_type_global', 'question_two_hop_statement']
How many points did I get on [history project 1]	98	['question_type_local']
list homeworks that are due on [February 18]	'english homework 2'	['question_type_global', 'question_two_hop_statement']
which homeworks are due before [February 13]?	'math homework 1'	['question_type_global', 'question_two_hop_statement']
what courses did i have late projects for?	'history', 'english'	['question_type_global', 'question_two_hop_statement']
[history project 3] is released for [history]
[history project 3] is worth [59] points
[history project 3] is due on [March 17]
I submitted [history project 3] on time and received 59 points
[this assignment] is now due on [March 18]
how many points did I receive on [government homework 1]?	82	['question_type_local']
which projects are due before [March 08]?	'government project 1', 'history project 1', 'government project 2', 'math project 1', 'english project 1', 'math project 3', 'history project 2'	['question_type_global', 'question_two_hop_statement']
list all homeworks that i submitted late for [english]	'english homework 2'	['question_type_global', 'question_two_hop_statement']
what assignments do I have to do for [history]?	'history project 1', 'history project 2', 'history project 3'	['question_type_global', 'question_two_hop_statement']
What is the topic of [math homework 1]?	'svm'	['question_type_local']
what are the late assignments that i submitted for [history]	'history homework 2', 'history project 2'	['question_type_global', 'question_two_hop_statement']
which homeworks are due on [February 23]?	'history homework 2'	['question_type_global', 'question_two_hop_statement']
which professors are in the [None] department?	'Genevive'	['question_type_global', 'question_two_hop_statement']
What is [Lucy]'s department?	'neuroscience'	['question_type_local']
which homeworks did I submit for [Lucy]?	'history homework 1', 'history homework 2', 'history homework 3'	['question_type_global', 'question_three_hop_statement']
list all assignments that i submitted for [government]	'government project 1', 'government homework 1'	['question_type_global', 'question_two_hop_statement']
what are the courses for which i submitted late assignments?	'government', 'history', 'english'	['question_type_global', 'question_two_hop_statement']
which assignments are due after [February 17]?	'government project 2', 'english homework 2', 'history homework 2', 'english homework 3', 'math project 3', 'history homework 3', 'history project 2', 'history project 3'	['question_type_global', 'question_two_hop_statement']
What is [english project 1] on?	'supervised learning'	['question_type_local']
what are the late projects that i submitted?	'english project 1', 'history project 2'	['question_type_global', 'question_two_hop_statement']
show me all the late assignments that i submitted	'english homework 2', 'history homework 2', 'english project 1', 'government homework 1', 'history project 2'	['question_type_global', 'question_two_hop_statement']
[government homework 2] is released for [government]
What is [history homework 3] on?	'Cloning'	['question_type_local']
what homeworks do I have to do for [math]?	'math homework 1'	['question_type_global', 'question_two_hop_statement']
list all assignments that i submitted late	'english homework 2', 'history homework 2', 'english project 1', 'government homework 1', 'history project 2'	['question_type_global', 'question_two_hop_statement']
[math] is taught by [Genevive]
List all assignments for [history]	'history project 1', 'history homework 1', 'history homework 2', 'history homework 3', 'history project 2', 'history project 3'	['question_type_local']
what are the late homeworks that i submitted?	'english homework 2', 'history homework 2', 'government homework 1'	['question_type_global', 'question_two_hop_statement']
how much did I get on [english homework 2]?	39	['question_type_local']
show me all homeworks i submitted for [Lucy]	'history homework 1', 'history homework 2', 'history homework 3'	['question_type_global', 'question_three_hop_statement']
How many points did I get on [math project 3]	62	['question_type_local']
which projects are due after [February 20]?	'government project 2', 'math project 3', 'history project 2', 'history project 3'	['question_type_global', 'question_two_hop_statement']
what assignments do I have to do for [history]?	'history project 1', 'history project 2', 'history project 3'	['question_type_global', 'question_two_hop_statement']
[history project 4] is released for [history]
What is the topic of [math homework 1]?	'svm'	['question_type_local']
what are all the assignments due for [Genevive]?	'math homework 1', 'math project 1', 'math project 2', 'math project 3'	['question_type_global', 'question_three_hop_statement']
[that person]'s email is [Genevive@nh.edu]
What is [english project 1] on?	'supervised learning'	['question_type_local']
which assignments did I submit late for [english]?	'english homework 2', 'english project 1'	['question_type_global', 'question_two_hop_statement']
show me all late projects i submitted for [history]	'history project 2'	['question_type_global', 'question_two_hop_statement']
list all projects that i submitted late	'english project 1', 'history project 2'	['question_type_global', 'question_two_hop_statement']
I submitted [english homework 1] late and received 55 points
When is the deadline of [history homework 1]?	'February 13'	['question_type_local']
which assignments are due on [February 18]?	'english homework 2'	['question_type_global', 'question_two_hop_statement']
what are all the assignments due?	'government project 1', 'history project 1', 'english homework 1', 'math homework 1', 'government project 2', 'math project 1', 'english homework 2', 'history homework 1', 'history homework 2', 'english homework 3', 'math project 2', 'english project 1', 'math project 3', 'history homework 3', 'government homework 1', 'history project 2', 'history project 3', 'government homework 2', 'history project 4'	['question_type_global', 'question_single_statement']
the affiliation of [Genevive] is [mechanical engineering]
which homeworks did I submit for [english]?	'english homework 1', 'english homework 2', 'english homework 3'	['question_type_global', 'question_two_hop_statement']
which courses did I submit late projects for?	'history', 'english'	['question_type_global', 'question_two_hop_statement']
What is [english project 1] on?	'supervised learning'	['question_type_local']
what are all the projects due?	'government project 1', 'history project 1', 'government project 2', 'math project 1', 'math project 2', 'english project 1', 'math project 3', 'history project 2', 'history project 3', 'history project 4'	['question_type_global', 'question_single_statement']
what assignments did i submit?	'government project 1', 'history project 1', 'english homework 1', 'math homework 1', 'math project 1', 'english homework 2', 'history homework 1', 'history homework 2', 'english homework 3', 'english project 1', 'math project 3', 'history homework 3', 'government homework 1', 'history project 2', 'history project 3'	['question_type_global', 'question_two_hop_statement']
what are the courses for which i submitted late assignments?	'government', 'history', 'english'	['question_type_global', 'question_two_hop_statement']
list all homeworks that i submitted for [history]	'history homework 1', 'history homework 2', 'history homework 3'	['question_type_global', 'question_two_hop_statement']
on which assignments did I get full credit?	'history project 1', 'english homework 1', 'english homework 2', 'history project 3'	['question_type_global', 'question_three_hop_statement']
show me all homeworks i submitted for [Lucy]	'history homework 1', 'history homework 2', 'history homework 3'	['question_type_global', 'question_three_hop_statement']
list all assignments that i submitted for [Emmie]	'government project 1', 'government homework 1'	['question_type_global', 'question_three_hop_statement']
[Genevive]'s department is now [psychology]
what did I get on [math homework 1]?	9	['question_type_local']
what are the late assignments that i submitted	'english homework 1', 'english homework 2', 'history homework 2', 'english project 1', 'government homework 1', 'history project 2'	['question_type_global', 'question_two_hop_statement']
who are the instructors to whom i submitted any late projects?	'Lucy'	['question_type_global', 'question_three_hop_statement']
[that person]'s department is now [mechanical engineering]
What is [english project 1] on?	'supervised learning'	['question_type_local']
list all assignments for [math]	'math project 1', 'math project 2', 'math project 3'	['question_type_global', 'question_two_hop_statement']
which homeworks did I submit late?	'english homework 1', 'english homework 2', 'history homework 2', 'government homework 1'	['question_type_global', 'question_two_hop_statement']
show me all the late assignments that i submitted	'english homework 1', 'english homework 2', 'history homework 2', 'english project 1', 'government homework 1', 'history project 2'	['question_type_global', 'question_two_hop_statement']
list all homeworks for [math]	'math homework 1'	['question_type_global', 'question_two_hop_statement']
show me all the late projects that i submitted	'english project 1', 'history project 2'	['question_type_global', 'question_two_hop_statement']
there is new [government project 3] for [government]
[that assignment] is [49] points
When is [english homework 2] due?	'February 18'	['question_type_local']
what are all the assignments due?	'government project 1', 'history project 1', 'english homework 1', 'math homework 1', 'government project 2', 'math project 1', 'english homework 2', 'history homework 1', 'history homework 2', 'english homework 3', 'math project 2', 'english project 1', 'math project 3', 'history homework 3', 'government homework 1', 'history project 2', 'history project 3', 'government homework 2', 'history project 4', 'government project 3'	['question_type_global', 'question_single_statement']
The deadline of [government project 3] is [March 05]
