I am taking a [english] course
[Andrew] is a [professor]
[he] is the instructor for [this course]
What courses is [this person] teaching?	'english'	['question_type_local']
[this professor]'s office is [026]
show all professors	'Andrew'	['question_type_global', 'question_single_statement']
[Hanna] is a [professor]
[Emmie] is a [professor]
[Hanna]'s office is [NSH802]
[english homework 1] is out for [english]
I am taking a [philosophy] course
[english homework 1] is due on [February 01]
[Emmie] teaches [philosophy]
[she]'s office is [1812]
which homeworks are due after [January 29]?	'english homework 1'	['question_type_global', 'question_two_hop_statement']
When is [english homework 1] due?	'February 01'	['question_type_local']
[english homework 1] is [15] points
List all homeworks for [english]	'english homework 1'	['question_type_local']
what assignments do I have to do?	'english homework 1'	['question_type_global', 'question_single_statement']
Which professor is teaching [philosophy]?	'Emmie'	['question_type_local']
[english] has a new [english homework 2] out
I submitted [english homework 1] and received 15 points
[english homework 1] is on [Genetics]
How many points is [that assignment] worth?	15	['question_type_local']
list all assignments for [Andrew]	'english homework 1', 'english homework 2'	['question_type_global', 'question_three_hop_statement']
How much is [english homework 1] worth?	15	['question_type_local']
what are the assignments that i submitted for [english]	'english homework 1'	['question_type_global', 'question_two_hop_statement']
What office is [Andrew] in?	'026'	['question_type_local']
there is a new [homework] for [english]
[english homework 3] is due on [March 04]
When is the deadline of [english homework 1]?	'February 01'	['question_type_local']
[that homework] is about [hidden markov models]
[this homework] is worth [98] points
When is [english homework 1] due?	'February 01'	['question_type_local']
which assignments did I submit for [Andrew]?	'english homework 1'	['question_type_global', 'question_three_hop_statement']
which homeworks are due on [March 04]?	'english homework 3'	['question_type_global', 'question_two_hop_statement']
I submitted [this assignment] on time and received 54 points
there is new [english project 1] for [english]
[that project] is worth [26] points
[that assignment] is on [vc dimension]
I submitted [that assignment] and received 16 points
The deadline of [this assignment] is [January 28]
What courses is [Emmie] teaching?	'philosophy'	['question_type_local']
which assignments are due before [January 30]?	'english project 1'	['question_type_global', 'question_two_hop_statement']
list all projects for [english]	'english project 1'	['question_type_global', 'question_two_hop_statement']
show me all projects i submitted for [english]	'english project 1'	['question_type_global', 'question_two_hop_statement']
[philosophy] has a new [philosophy project 1] released
[philosophy project 1] is about [Viruses & other Microbes]
[this project] is worth [75] points
[this assignment] is due on [January 28]
When is the deadline of [english homework 1]?	'February 01'	['question_type_local']
on which assignments did I get full credit?	'english homework 1'	['question_type_global', 'question_three_hop_statement']
I am taking a [statistics] course
I submitted [that project] and received 71 points
[William] is a [professor]
[William] is in [NSH802]
which homeworks are due after [January 25]?	'english homework 1', 'english homework 3'	['question_type_global', 'question_two_hop_statement']
[philosophy homework 1] is out for [philosophy]
[this assignment] is on [svm]
I submitted [that homework]
[that assignment] is [97] points
what are the projects that i submitted for [english]	'english project 1'	['question_type_global', 'question_two_hop_statement']
what assignments do I have to do for [Andrew]?	'english homework 1', 'english homework 2', 'english homework 3', 'english project 1'	['question_type_global', 'question_three_hop_statement']
[english] has a new [english homework 4] released
List all assignments for [english]	'english homework 1', 'english homework 2', 'english homework 3', 'english project 1', 'english homework 4'	['question_type_local']
list all homeworks for [english]	'english homework 1', 'english homework 2', 'english homework 3', 'english homework 4'	['question_type_global', 'question_two_hop_statement']
[english homework 4] is on [kernels]
The deadline of [this homework] is [March 02]
I am taking a [calculus] course
[Hanna] is the instructor for [calculus]
what projects did i submit?	'english project 1', 'philosophy project 1'	['question_type_global', 'question_two_hop_statement']
show me all assignments i submitted for [english]	'english homework 1', 'english homework 3', 'english project 1'	['question_type_global', 'question_two_hop_statement']
what did I get on [english homework 3]?	54	['question_type_local']
[english homework 4] is worth [10] points
how many points did I receive on [philosophy project 1]?	71	['question_type_local']
which homeworks did I submit?	'english homework 1', 'english homework 3', 'philosophy homework 1'	['question_type_global', 'question_two_hop_statement']
there is a new [project] for [english]
[this project] is due on [February 12]
[that project] is about [nearest neighbor algorithm]
which homeworks are due before [March 02]?	'english homework 1'	['question_type_global', 'question_two_hop_statement']
which projects are due after [January 25]?	'english project 1', 'philosophy project 1', 'english project 2'	['question_type_global', 'question_two_hop_statement']
[Tereasa] is a [professor]
on which assignments did I get full credit?	'english homework 1'	['question_type_global', 'question_three_hop_statement']
who are the professors?	'Andrew', 'Hanna', 'Emmie', 'William', 'Tereasa'	['question_type_global', 'question_single_statement']
what are all the homeworks due?	'english homework 1', 'english homework 2', 'english homework 3', 'philosophy homework 1', 'english homework 4'	['question_type_global', 'question_single_statement']
what are all the assignments due?	'english homework 1', 'english homework 2', 'english homework 3', 'english project 1', 'philosophy project 1', 'philosophy homework 1', 'english homework 4', 'english project 2'	['question_type_global', 'question_single_statement']
[calculus] has a new [calculus homework 1] out
[that homework] is about [grammar induction]
I submitted [calculus homework 1]
[that assignment] is worth [29] points
When is [english homework 3] due?	'March 04'	['question_type_local']
what are all the assignments due for [english]?	'english project 1', 'english project 2'	['question_type_global', 'question_two_hop_statement']
create a [professor] named [Luanna]
[Luanna] is in [1812]
What courses is [Andrew] teaching?	'english'	['question_type_local']
on which assignments did I get full credit?	'english homework 1'	['question_type_global', 'question_three_hop_statement']
what projects do I have to do for [philosophy]?	'philosophy project 1'	['question_type_global', 'question_two_hop_statement']
What are the assignments for [calculus]?	'calculus homework 1'	['question_type_local']
what are all the projects due for [Andrew]?	'english project 1', 'english project 2'	['question_type_global', 'question_three_hop_statement']
which projects are due before [March 03]?	'english project 1', 'philosophy project 1', 'english project 2'	['question_type_global', 'question_two_hop_statement']
which projects did I submit for [Emmie]?	'philosophy project 1'	['question_type_global', 'question_three_hop_statement']
what are all the projects due?	'english project 1', 'philosophy project 1', 'english project 2'	['question_type_global', 'question_single_statement']
list all assignments that i submitted for [Emmie]	'philosophy project 1', 'philosophy homework 1'	['question_type_global', 'question_three_hop_statement']
what are the projects that i submitted?	'english project 1', 'philosophy project 1'	['question_type_global', 'question_two_hop_statement']
[english project 2] is worth [69] points
I submitted [this project] and received 20 points
When is the deadline of [philosophy project 1]?	'January 28'	['question_type_local']
on which assignments did I get full credit?	'english homework 1'	['question_type_global', 'question_three_hop_statement']
which assignments are due after [February 28]?	'english homework 3', 'english homework 4'	['question_type_global', 'question_two_hop_statement']
which homeworks did I submit for [calculus]?	'calculus homework 1'	['question_type_global', 'question_two_hop_statement']
The deadline of [english homework 3] moved to [March 02]
[that homework] is now due on [March 02]
What is [Emmie]'s office?	'1812'	['question_type_local']
what homeworks did i submit for [Hanna]?	'calculus homework 1'	['question_type_global', 'question_three_hop_statement']
list all projects that i submitted	'english project 1', 'philosophy project 1', 'english project 2'	['question_type_global', 'question_two_hop_statement']
[statistics] has a new [statistics homework 1] out
I submitted [statistics homework 1] on time
[that homework] is due on [January 28]
[Ashly] is a [professor]
[this professor] is in [1812]
what did I get on [english homework 3]?	54	['question_type_local']
which assignments are due after [February 13]?	'english homework 3', 'english homework 4'	['question_type_global', 'question_two_hop_statement']
what are all the homeworks due for [Emmie]?	'philosophy homework 1'	['question_type_global', 'question_three_hop_statement']
list all homeworks for [statistics]	'statistics homework 1'	['question_type_global', 'question_two_hop_statement']
How many points is [english homework 3] worth?	98	['question_type_local']
show all professors	'Andrew', 'Hanna', 'Emmie', 'William', 'Tereasa', 'Luanna', 'Ashly'	['question_type_global', 'question_single_statement']
Who is teaching [english]?	'Andrew'	['question_type_local']
what are the projects that i submitted?	'english project 1', 'philosophy project 1', 'english project 2'	['question_type_global', 'question_two_hop_statement']
what did I get on [english homework 3]?	54	['question_type_local']
list all projects	'english project 1', 'philosophy project 1', 'english project 2'	['question_type_global', 'question_single_statement']
[statistics homework 1] is [36] points
create a [professor] named [Cecil]
[that person]'s office is [1812]
List all homeworks for [statistics]	'statistics homework 1'	['question_type_local']
what are all the projects due for [philosophy]?	'philosophy project 1'	['question_type_global', 'question_two_hop_statement']
there is new [english homework 5] for [english]
what assignments do I have to do?	'english homework 1', 'english homework 2', 'english homework 3', 'english project 1', 'philosophy project 1', 'philosophy homework 1', 'english homework 4', 'english project 2', 'calculus homework 1', 'statistics homework 1', 'english homework 5'	['question_type_global', 'question_single_statement']
what are all the assignments due?	'english homework 1', 'english homework 2', 'english homework 3', 'english project 1', 'philosophy project 1', 'philosophy homework 1', 'english homework 4', 'english project 2', 'calculus homework 1', 'statistics homework 1', 'english homework 5'	['question_type_global', 'question_single_statement']
[english homework 6] is out for [english]
[english homework 6] is [21] points
which homeworks are due after [February 12]?	'english homework 3', 'english homework 4'	['question_type_global', 'question_two_hop_statement']
what are all the projects due for [Emmie]?	'philosophy project 1'	['question_type_global', 'question_three_hop_statement']
what homeworks did i submit for [english]?	'english homework 1', 'english homework 3'	['question_type_global', 'question_two_hop_statement']
[english homework 6] is on [The Environment]
[Roslyn] is a [professor]
I submitted [that homework] on time and received 21 points
[english homework 5] is [61] points
How many points did I get on [english homework 6]	21	['question_type_local']
which projects are due on [January 28]?	'english project 1', 'philosophy project 1'	['question_type_global', 'question_two_hop_statement']
Show me all assignments due for [calculus]	'calculus homework 1'	['question_type_local']
list all the professors	'Andrew', 'Hanna', 'Emmie', 'William', 'Tereasa', 'Luanna', 'Ashly', 'Cecil', 'Roslyn'	['question_type_global', 'question_single_statement']
which assignments are due before [March 01]?	'english homework 1', 'english project 1', 'philosophy project 1', 'english project 2', 'statistics homework 1'	['question_type_global', 'question_two_hop_statement']
which homeworks are due before [February 09]?	'english homework 1', 'statistics homework 1'	['question_type_global', 'question_two_hop_statement']
which projects are due after [January 31]?	'english project 2'	['question_type_global', 'question_two_hop_statement']
I submitted [english homework 5] late and received 61 points
The deadline of [this assignment] is [February 25]
[Ashly] is the instructor for [statistics]
what instructors did i have late assignments for?	'Andrew'	['question_type_global', 'question_three_hop_statement']
which homeworks are due after [January 29]?	'english homework 1', 'english homework 3', 'english homework 4', 'english homework 5'	['question_type_global', 'question_two_hop_statement']
which projects are due before [February 25]?	'english project 1', 'philosophy project 1', 'english project 2'	['question_type_global', 'question_two_hop_statement']
[calculus homework 2] is released for [calculus]
How much is [english homework 5] worth?	61	['question_type_local']
[calculus homework 2] is due on [February 18]
[this assignment] is [68] points
When is [english homework 4] due?	'March 02'	['question_type_local']
which professors did I submit late homeworks for?	'Andrew'	['question_type_global', 'question_three_hop_statement']
what assignments did i submit for [Ashly]?	'statistics homework 1'	['question_type_global', 'question_three_hop_statement']
which assignments are due after [January 26]?	'english homework 1', 'english homework 3', 'english project 1', 'philosophy project 1', 'english homework 4', 'english project 2', 'statistics homework 1', 'english homework 5', 'calculus homework 2'	['question_type_global', 'question_two_hop_statement']
which assignments did I submit late?	'english homework 5'	['question_type_global', 'question_two_hop_statement']
what are the late homeworks that i submitted?	'english homework 5'	['question_type_global', 'question_two_hop_statement']
how many points did I receive on [english homework 1]?	15	['question_type_local']
show me all homeworks i submitted for [philosophy]	'philosophy homework 1'	['question_type_global', 'question_two_hop_statement']
list all homeworks that i submitted for [Emmie]	'philosophy homework 1'	['question_type_global', 'question_three_hop_statement']
I submitted [calculus homework 2] and received 68 points
The topic of [this assignment] is [k means]
which courses did I submit late homeworks for?	'english'	['question_type_global', 'question_two_hop_statement']
The deadline of [calculus homework 1] is [January 31]
show all professors	'Andrew', 'Hanna', 'Emmie', 'William', 'Tereasa', 'Luanna', 'Ashly', 'Cecil', 'Roslyn'	['question_type_global', 'question_single_statement']
which homeworks did I submit?	'english homework 1', 'english homework 3', 'philosophy homework 1', 'calculus homework 1', 'statistics homework 1', 'english homework 5', 'english homework 6', 'calculus homework 2'	['question_type_global', 'question_two_hop_statement']
show me all the late assignments that i submitted	'english homework 5'	['question_type_global', 'question_two_hop_statement']
what homeworks do I have to do?	'english homework 1', 'english homework 2', 'english homework 3', 'philosophy homework 1', 'english homework 4', 'calculus homework 1', 'statistics homework 1', 'english homework 5', 'english homework 6', 'calculus homework 2'	['question_type_global', 'question_single_statement']
what instructors did i have late assignments for?	'Andrew'	['question_type_global', 'question_three_hop_statement']
which assignments are due on [January 31]?	'calculus homework 1'	['question_type_global', 'question_two_hop_statement']
The deadline of [calculus homework 2] moved to [February 20]
What is [Luanna]'s office?	'1812'	['question_type_local']
list all homeworks that i submitted for [statistics]	'statistics homework 1'	['question_type_global', 'question_two_hop_statement']
show me the homeworks due on [February 20]	'calculus homework 2'	['question_type_global', 'question_two_hop_statement']
[statistics project 1] is released for [statistics]
I submitted [that project]
[this project] is worth [83] points
What is the topic of [english homework 6]?	'The Environment'	['question_type_local']
show me all projects i submitted for [Ashly]	'statistics project 1'	['question_type_global', 'question_three_hop_statement']
what are the courses for which i submitted late homeworks?	'english'	['question_type_global', 'question_two_hop_statement']
there is new [english homework 7] for [english]
I submitted [english homework 7]
The deadline of [english homework 7] is [April 15]
how many points is [english project 1]?	26	['question_type_local']
what assignments did i submit late?	'english homework 5'	['question_type_global', 'question_two_hop_statement']
which assignments are due before [February 28]?	'english homework 1', 'english project 1', 'philosophy project 1', 'english project 2', 'calculus homework 1', 'statistics homework 1', 'english homework 5', 'calculus homework 2'	['question_type_global', 'question_two_hop_statement']
[english homework 7] is worth [13] points
there is a [professor] named [Rachele]
what are all the assignments due?	'english homework 1', 'english homework 2', 'english homework 3', 'english project 1', 'philosophy project 1', 'philosophy homework 1', 'english homework 4', 'english project 2', 'calculus homework 1', 'statistics homework 1', 'english homework 5', 'english homework 6', 'calculus homework 2', 'statistics project 1', 'english homework 7'	['question_type_global', 'question_single_statement']
[Rachele] is in [026]
The deadline of [statistics project 1] is [February 01]
which homeworks are due after [April 12]?	'english homework 7'	['question_type_global', 'question_two_hop_statement']
which projects did I submit for [Ashly]?	'statistics project 1'	['question_type_global', 'question_three_hop_statement']
how much did I get on [english homework 5]?	61	['question_type_local']
list all the professors	'Andrew', 'Hanna', 'Emmie', 'William', 'Tereasa', 'Luanna', 'Ashly', 'Cecil', 'Roslyn', 'Rachele'	['question_type_global', 'question_single_statement']
list all assignments that i submitted for [english]	'english homework 1', 'english homework 3', 'english project 1', 'english project 2', 'english homework 5', 'english homework 6', 'english homework 7'	['question_type_global', 'question_two_hop_statement']
which projects are due on [February 01]?	'statistics project 1'	['question_type_global', 'question_two_hop_statement']
What is [philosophy homework 1] on?	'svm'	['question_type_local']
what projects did i submit?	'english project 1', 'philosophy project 1', 'english project 2', 'statistics project 1'	['question_type_global', 'question_two_hop_statement']
what assignments did i submit?	'english homework 1', 'english homework 3', 'english project 1', 'philosophy project 1', 'philosophy homework 1', 'english project 2', 'calculus homework 1', 'statistics homework 1', 'english homework 5', 'english homework 6', 'calculus homework 2', 'statistics project 1', 'english homework 7'	['question_type_global', 'question_two_hop_statement']
I submitted [english homework 4] and received 10 points
When is the deadline of [calculus homework 2]?	'February 20'	['question_type_local']
who are the professors?	'Andrew', 'Hanna', 'Emmie', 'William', 'Tereasa', 'Luanna', 'Ashly', 'Cecil', 'Roslyn', 'Rachele'	['question_type_global', 'question_single_statement']
what are all the projects due for [Ashly]?	'statistics project 1'	['question_type_global', 'question_three_hop_statement']
list homeworks that are due on [April 15]	'english homework 7'	['question_type_global', 'question_two_hop_statement']
which assignments are due on [February 20]?	'calculus homework 2'	['question_type_global', 'question_two_hop_statement']
there is a new [homework] for [philosophy]
what are the late assignments that i submitted	'english homework 5'	['question_type_global', 'question_two_hop_statement']
which assignments are due before [January 29]?	'english project 1', 'philosophy project 1', 'statistics homework 1'	['question_type_global', 'question_two_hop_statement']
[philosophy homework 2] is due on [February 18]
[that homework] is worth [35] points
what assignments do I have to do for [english]?	'english project 1', 'english project 2'	['question_type_global', 'question_two_hop_statement']
which assignments are due before [April 18]?	'english homework 1', 'english homework 3', 'english project 1', 'philosophy project 1', 'english homework 4', 'english project 2', 'calculus homework 1', 'statistics homework 1', 'english homework 5', 'calculus homework 2', 'statistics project 1', 'english homework 7', 'philosophy homework 2'	['question_type_global', 'question_two_hop_statement']
What office is [Hanna] in?	'NSH802'	['question_type_local']
which courses did I submit late homeworks for?	'english'	['question_type_global', 'question_two_hop_statement']
which assignments did I submit for [Emmie]?	'philosophy project 1', 'philosophy homework 1'	['question_type_global', 'question_three_hop_statement']
list all projects that i submitted for [Emmie]	'philosophy project 1'	['question_type_global', 'question_three_hop_statement']
[calculus homework 3] is out for [calculus]
[calculus homework 3] is due on [February 14]
What courses is [Ashly] teaching?	'statistics'	['question_type_local']
list all homeworks that i submitted late	'english homework 5'	['question_type_global', 'question_two_hop_statement']
I submitted [that assignment]
What courses is [Andrew] teaching?	'english'	['question_type_local']
which homeworks are due before [February 28]?	'english homework 1', 'calculus homework 1', 'statistics homework 1', 'english homework 5', 'calculus homework 2', 'philosophy homework 2', 'calculus homework 3'	['question_type_global', 'question_two_hop_statement']
which courses did I submit late homeworks for?	'english'	['question_type_global', 'question_two_hop_statement']
