I am taking a course called [government]
[government project 1] is out for [government]
I submitted [this project]
[this project] is [63] points
[that assignment] is on [svm]
Show me all assignments due for [government]	'government project 1'	['question_type_local']
The deadline of [government project 1] is [January 27]
I am taking a course called [french]
When is the deadline of [that project]?	'January 27'	['question_type_local']
When is [that project] due?	'January 27'	['question_type_local']
what are the projects that i submitted?	'government project 1'	['question_type_global', 'question_two_hop_statement']
show me all assignments i submitted	'government project 1'	['question_type_global', 'question_two_hop_statement']
[that course] has a new [french project 1] released
which assignments did I submit for [government]?	'government project 1'	['question_type_global', 'question_two_hop_statement']
list all assignments	'government project 1', 'french project 1'	['question_type_global', 'question_single_statement']
[government] has a new [government project 2] released
I submitted [government project 2]
The topic of [this project] is [neural networks]
How much is [government project 1] worth?	63	['question_type_local']
there is a [professor] named [Lucio]
[Lucio]'s office is [1300]
[this professor]'s email is [Lucio@harvard.edu]
[this professor] is affiliated with the [english] department
I am taking a [business communication] course
[that person] teaches [business communication]
Show me all assignments due for [government]	'government project 1', 'government project 2'	['question_type_local']
what are the assignments that i submitted?	'government project 1', 'government project 2'	['question_type_global', 'question_two_hop_statement']
list projects that are due on [January 27]	'government project 1'	['question_type_global', 'question_two_hop_statement']
[french] has a new [french project 2] out
[french project 1] is due on [January 29]
[french project 1] is [33] points
[government project 2] is [75] points
what assignments do I have to do for [french]?	'french project 1', 'french project 2'	['question_type_global', 'question_two_hop_statement']
what are all the projects due?	'government project 1', 'french project 1', 'government project 2', 'french project 2'	['question_type_global', 'question_single_statement']
What is the topic of [government project 1]?	'svm'	['question_type_local']
list all assignments	'government project 1', 'french project 1', 'government project 2', 'french project 2'	['question_type_global', 'question_single_statement']
[government project 2] is due on [February 07]
which projects are due before [February 07]?	'government project 1', 'french project 1'	['question_type_global', 'question_two_hop_statement']
there is a [professor] named [Gia]
[that person]'s office is [310]
What office is [Gia] in?	'310'	['question_type_local']
show me the assignments due on [January 29]	'french project 1'	['question_type_global', 'question_two_hop_statement']
the affiliation of [this professor] is [english]
[this person]'s email is [Gia@harvard.edu]
create a [professor] named [Bob]
[he]'s email is [Bob@gmail.com]
what are the assignments that i submitted?	'government project 1', 'government project 2'	['question_type_global', 'question_two_hop_statement']
[this professor] is in [303]
[Charlott] is a [professor]
[she]'s department is [applied physics]
[this person]'s email is [Charlott@cmu.edu]
which professors are in the [applied physics] department?	'Charlott'	['question_type_global', 'question_two_hop_statement']
what assignments did i submit?	'government project 1', 'government project 2'	['question_type_global', 'question_two_hop_statement']
[this person] is in [303]
Who is the instructor for [business communication]?	'Lucio'	['question_type_local']
which projects are due after [January 24]?	'government project 1', 'french project 1', 'government project 2'	['question_type_global', 'question_two_hop_statement']
which assignments are due after [January 28]?	'french project 1', 'government project 2'	['question_type_global', 'question_two_hop_statement']
How many points is [french project 1] worth?	33	['question_type_local']
who are the professors affiliated with [None]?	'Bob'	['question_type_global', 'question_two_hop_statement']
How much is [government project 2] worth?	75	['question_type_local']
create a [professor] named [Cecil]
What is [Bob]'s office?	'303'	['question_type_local']
the affiliation of [he] is [applied physics]
[Cecil]'s email is [Cecil@gmail.com]
[this person] is in [1300]
which assignments are due before [January 31]?	'government project 1', 'french project 1'	['question_type_global', 'question_two_hop_statement']
Which department is [Charlott] in?	'applied physics'	['question_type_local']
[that person]'s department is now [physics]
[french project 1] is about [unsupervised learning]
How much is [government project 1] worth?	63	['question_type_local']
list the professors in the [None] department	'Bob'	['question_type_global', 'question_two_hop_statement']
show me all assignments i submitted	'government project 1', 'government project 2'	['question_type_global', 'question_two_hop_statement']
[french] has a new [french homework 1] out
[french homework 1] is [73] points
[that homework] is due on [January 31]
I submitted [that homework] on time and received 73 points
[french homework 2] is released for [french]
[french homework 2] is about [Genetics]
I submitted [french homework 2] late
When is the deadline of [government project 1]?	'January 27'	['question_type_local']
what are all the projects due for [french]?	'french project 1', 'french project 2'	['question_type_global', 'question_two_hop_statement']
show me all assignments i submitted for [government]	'government project 1', 'government project 2'	['question_type_global', 'question_two_hop_statement']
which assignments are due before [February 10]?	'government project 1', 'french project 1', 'government project 2', 'french homework 1'	['question_type_global', 'question_two_hop_statement']
there is new [french project 3] for [french]
[french homework 2] is [10] points
which assignments are due before [February 01]?	'government project 1', 'french project 1', 'french homework 1'	['question_type_global', 'question_two_hop_statement']
[that project] is due on [February 14]
there is a [professor] named [Kristeen]
[this person] is in [303]
[she] is affiliated with the [applied physics] department
[Kristeen]'s email is [Kristeen@yandex.com]
change [she]'s department to [english]
What are the assignments for [french]?	'french project 1', 'french project 2', 'french homework 1', 'french homework 2', 'french project 3'	['question_type_local']
show me all late homeworks i submitted	'french homework 2'	['question_type_global', 'question_two_hop_statement']
list the professors in the [None] department	'Bob'	['question_type_global', 'question_two_hop_statement']
which homeworks are due after [January 27]?	'french homework 1'	['question_type_global', 'question_two_hop_statement']
What is [Lucio]'s department?	'english'	['question_type_local']
what are all the projects due for [french]?	'french project 1', 'french project 2', 'french project 3'	['question_type_global', 'question_two_hop_statement']
[government homework 1] is out for [government]
When is [french homework 1] due?	'January 31'	['question_type_local']
what are the assignments that i submitted for [french]	'french homework 1', 'french homework 2'	['question_type_global', 'question_two_hop_statement']
what are the late assignments that i submitted for [french]	'french homework 2'	['question_type_global', 'question_two_hop_statement']
what homeworks did i submit?	'french homework 1', 'french homework 2'	['question_type_global', 'question_two_hop_statement']
[government homework 1] is due on [January 30]
[that assignment] is about [grammar induction]
[this homework] is [76] points
I submitted [government homework 1] on time and received 76 points
how much did I get on [french homework 1]?	73	['question_type_local']
list all homeworks	'french homework 1', 'french homework 2', 'government homework 1'	['question_type_global', 'question_single_statement']
show me all homeworks i submitted	'french homework 1', 'french homework 2', 'government homework 1'	['question_type_global', 'question_two_hop_statement']
[government] has a new [government project 3] out
I submitted [government project 3] late
The deadline of [that assignment] is [February 11]
[government project 3] is about [reinforcement learning]
[business communication] has a new [business communication project 1] out
[government project 3] is worth [39] points
When is the deadline of [government project 2]?	'February 07'	['question_type_local']
which assignments are due on [February 14]?	'french project 3'	['question_type_global', 'question_two_hop_statement']
which projects are due before [February 02]?	'government project 1', 'french project 1'	['question_type_global', 'question_two_hop_statement']
which assignments are due after [January 31]?	'government project 2', 'french project 3', 'government project 3'	['question_type_global', 'question_two_hop_statement']
[business communication project 1] is worth [83] points
[business communication project 1] is due on [January 27]
there is new [business communication project 2] for [business communication]
The topic of [business communication project 2] is [The Environment]
The deadline of [this assignment] is [February 15]
what are all the homeworks due for [french]?	'french homework 1', 'french homework 2'	['question_type_global', 'question_two_hop_statement']
what are the late homeworks that i submitted?	'french homework 2'	['question_type_global', 'question_two_hop_statement']
which homeworks are due after [January 27]?	'french homework 1', 'government homework 1'	['question_type_global', 'question_two_hop_statement']
[that project] is worth [15] points
I submitted [business communication project 2] and received 15 points
What office is [Cecil] in?	'1300'	['question_type_local']
what projects do I have to do for [Lucio]?	'business communication project 1', 'business communication project 2'	['question_type_global', 'question_three_hop_statement']
what are the late assignments that i submitted	'french homework 2', 'government project 3'	['question_type_global', 'question_two_hop_statement']
list all projects that i submitted	'government project 1', 'government project 2', 'government project 3', 'business communication project 2'	['question_type_global', 'question_two_hop_statement']
what are all the projects due for [government]?	'government project 1', 'government project 2', 'government project 3'	['question_type_global', 'question_two_hop_statement']
what are the courses for which I submitted assignments late	'government', 'french'	['question_type_global', 'question_two_hop_statement']
show me all courses for which i submitted at least one late project	'government'	['question_type_global', 'question_two_hop_statement']
[business communication] has a new [business communication project 3] out
[William] is a [professor]
[this professor]'s email is [William@cmu.edu]
[this person]'s department is [physics]
[that person]'s office is [3851]
When is [business communication project 1] due?	'January 27'	['question_type_local']
list all homeworks for [french]	'french homework 1', 'french homework 2'	['question_type_global', 'question_two_hop_statement']
list all projects for [business communication]	'business communication project 1', 'business communication project 2', 'business communication project 3'	['question_type_global', 'question_two_hop_statement']
show me all assignments that i submitted for [Lucio]	'business communication project 2'	['question_type_global', 'question_three_hop_statement']
which courses did I submit late assignments for?	'government', 'french'	['question_type_global', 'question_two_hop_statement']
What is [business communication project 2] on?	'The Environment'	['question_type_local']
what courses did i have late homeworks for?	'french'	['question_type_global', 'question_two_hop_statement']
list all projects that i submitted for [Lucio]	'business communication project 2'	['question_type_global', 'question_three_hop_statement']
which assignments are due after [January 31]?	'government project 2', 'french project 3', 'government project 3', 'business communication project 2'	['question_type_global', 'question_two_hop_statement']
[government] has a new [government homework 2] out
[this homework] is [99] points
What is [Bob]'s email	'Bob@gmail.com'	['question_type_local']
what are the late projects that i submitted?	'government project 3'	['question_type_global', 'question_two_hop_statement']
which projects did I submit late?	'government project 3'	['question_type_global', 'question_two_hop_statement']
what projects do I have to do for [business communication]?	'business communication project 1', 'business communication project 2', 'business communication project 3'	['question_type_global', 'question_two_hop_statement']
[this assignment] is due on [February 05]
[french] has a new [french project 4] out
I submitted [that homework] on time and received 83 points
How many points is [business communication project 1] worth?	83	['question_type_local']
which projects are due on [February 14]?	'french project 3'	['question_type_global', 'question_two_hop_statement']
The deadline of [french project 4] is [February 27]
[that project] is [14] points
[this assignment] is now due on [February 27]
When is [french project 1] due?	'January 29'	['question_type_local']
list all homeworks that i submitted late	'french homework 2'	['question_type_global', 'question_two_hop_statement']
what are all the homeworks due for [french]?	'french homework 1', 'french homework 2'	['question_type_global', 'question_two_hop_statement']
what did I get on [french homework 1]?	73	['question_type_local']
list all assignments	'government project 1', 'french project 1', 'government project 2', 'french project 2', 'french homework 1', 'french homework 2', 'french project 3', 'government homework 1', 'government project 3', 'business communication project 1', 'business communication project 2', 'business communication project 3', 'government homework 2', 'french project 4'	['question_type_global', 'question_single_statement']
The deadline of [that assignment] moved to [March 02]
I submitted [this project] on time and received 14 points
which projects did I submit late for [government]?	'government project 3'	['question_type_global', 'question_two_hop_statement']
show me all courses for which i submitted at least one late homework	'french'	['question_type_global', 'question_two_hop_statement']
who are the professors affiliated with [physics]?	'Cecil', 'William'	['question_type_global', 'question_two_hop_statement']
what are the late assignments that i submitted	'french homework 2', 'government project 3'	['question_type_global', 'question_two_hop_statement']
What is [Charlott]'s office?	'303'	['question_type_local']
show all professors	'Lucio', 'Gia', 'Bob', 'Charlott', 'Cecil', 'Kristeen', 'William'	['question_type_global', 'question_single_statement']
What is the topic of [government project 1]?	'svm'	['question_type_local']
what are the courses for which i submitted late assignments?	'government', 'french'	['question_type_global', 'question_two_hop_statement']
what did I get on [government homework 1]?	76	['question_type_local']
which homeworks are due before [February 13]?	'french homework 1', 'government homework 1', 'government homework 2'	['question_type_global', 'question_two_hop_statement']
which assignments are due before [January 28]?	'government project 1', 'business communication project 1'	['question_type_global', 'question_two_hop_statement']
what are the courses for which i submitted late projects?	'government'	['question_type_global', 'question_two_hop_statement']
What department is [William] affiliated with?	'physics'	['question_type_local']
which homeworks did I submit late?	'french homework 2'	['question_type_global', 'question_two_hop_statement']
What office is [William] in?	'3851'	['question_type_local']
which courses did I submit late homeworks for?	'french'	['question_type_global', 'question_two_hop_statement']
list assignments that are due on [January 29]	'french project 1'	['question_type_global', 'question_two_hop_statement']
what are the late homeworks that i submitted?	'french homework 2'	['question_type_global', 'question_two_hop_statement']
which courses did I submit late assignments for?	'government', 'french'	['question_type_global', 'question_two_hop_statement']
What is [Bob]'s email	'Bob@gmail.com'	['question_type_local']
what projects do I have to do for [business communication]?	'business communication project 1', 'business communication project 2', 'business communication project 3'	['question_type_global', 'question_two_hop_statement']
what are all the projects due for [Lucio]?	'business communication project 1', 'business communication project 2', 'business communication project 3'	['question_type_global', 'question_three_hop_statement']
[government] has a new [government project 4] out
[government project 4] is worth [85] points
The deadline of [that project] is [March 15]
I submitted [that project] on time and received 85 points
How many points did I get on [this assignment]	85	['question_type_local']
what homeworks did i submit late?	'french homework 2'	['question_type_global', 'question_two_hop_statement']
list assignments that are due on [January 27]	'government project 1', 'business communication project 1'	['question_type_global', 'question_two_hop_statement']
When is the deadline of [government project 1]?	'January 27'	['question_type_local']
which courses did I submit late assignments for?	'government', 'french'	['question_type_global', 'question_two_hop_statement']
what assignments do I have to do?	'government project 1', 'french project 1', 'government project 2', 'french project 2', 'french homework 1', 'french homework 2', 'french project 3', 'government homework 1', 'government project 3', 'business communication project 1', 'business communication project 2', 'business communication project 3', 'government homework 2', 'french project 4', 'government project 4'	['question_type_global', 'question_single_statement']
what assignments did i submit?	'government project 1', 'government project 2', 'french homework 1', 'french homework 2', 'government homework 1', 'government project 3', 'business communication project 2', 'government homework 2', 'french project 4', 'government project 4'	['question_type_global', 'question_two_hop_statement']
list homeworks that are due on [January 31]	'french homework 1'	['question_type_global', 'question_two_hop_statement']
show me all the late assignments that i submitted	'french homework 2', 'government project 3'	['question_type_global', 'question_two_hop_statement']
which assignments did I submit for [Lucio]?	'business communication project 2'	['question_type_global', 'question_three_hop_statement']
What courses is [Lucio] teaching?	'business communication'	['question_type_local']
what assignments did i submit late?	'french homework 2', 'government project 3'	['question_type_global', 'question_two_hop_statement']
what are the courses for which I submitted projects late	'government'	['question_type_global', 'question_two_hop_statement']
on which assignments did I get full credit?	'french homework 1', 'government homework 1', 'business communication project 2', 'french project 4', 'government project 4'	['question_type_global', 'question_three_hop_statement']
what are the late homeworks that i submitted?	'french homework 2'	['question_type_global', 'question_two_hop_statement']
what projects did i submit for [government]?	'government project 1', 'government project 2', 'government project 3', 'government project 4'	['question_type_global', 'question_two_hop_statement']
which homeworks are due before [February 16]?	'french homework 1', 'government homework 1', 'government homework 2'	['question_type_global', 'question_two_hop_statement']
When is the deadline of [government project 1]?	'January 27'	['question_type_local']
list projects that are due on [February 15]	'business communication project 2'	['question_type_global', 'question_two_hop_statement']
what homeworks did i submit late?	'french homework 2'	['question_type_global', 'question_two_hop_statement']
what are the assignments that i submitted for [business communication]	'business communication project 2'	['question_type_global', 'question_two_hop_statement']
list all assignments that i submitted for [business communication]	'business communication project 2'	['question_type_global', 'question_two_hop_statement']
which assignments did I submit late for [french]?	'french homework 2'	['question_type_global', 'question_two_hop_statement']
what projects did i submit for [Lucio]?	'business communication project 2'	['question_type_global', 'question_three_hop_statement']
what projects did i submit?	'government project 1', 'government project 2', 'government project 3', 'business communication project 2', 'french project 4', 'government project 4'	['question_type_global', 'question_two_hop_statement']
[french] has a new [french project 5] out
I submitted [french project 5] on time
[this assignment] is worth [18] points
The deadline of [french project 5] is [February 27]
what did I get on [government project 4]?	85	['question_type_local']
show me all late assignments i submitted for [french]	'french homework 2'	['question_type_global', 'question_two_hop_statement']
on which assignments did I get full credit?	'french homework 1', 'government homework 1', 'business communication project 2', 'french project 4', 'government project 4'	['question_type_global', 'question_three_hop_statement']
which assignments are due before [February 16]?	'government project 1', 'french project 1', 'government project 2', 'french homework 1', 'french project 3', 'government homework 1', 'government project 3', 'business communication project 1', 'business communication project 2', 'government homework 2'	['question_type_global', 'question_two_hop_statement']
there is a new [homework] for [french]
what projects do I have to do?	'government project 1', 'french project 1', 'government project 2', 'french project 2', 'french project 3', 'government project 3', 'business communication project 1', 'business communication project 2', 'business communication project 3', 'french project 4', 'government project 4', 'french project 5'	['question_type_global', 'question_single_statement']
what are all the projects due?	'government project 1', 'french project 1', 'government project 2', 'french project 2', 'french project 3', 'government project 3', 'business communication project 1', 'business communication project 2', 'business communication project 3', 'french project 4', 'government project 4', 'french project 5'	['question_type_global', 'question_single_statement']
I submitted [french project 1] and received 9 points
[that homework] is [44] points
I submitted [that homework] on time and received 32 points
When is the deadline of [french project 1]?	'January 29'	['question_type_local']
show me the assignments due on [February 14]	'french project 3'	['question_type_global', 'question_two_hop_statement']
list all assignments for [Lucio]	'business communication project 1', 'business communication project 2', 'business communication project 3'	['question_type_global', 'question_three_hop_statement']
what are the courses for which i submitted late projects?	'government'	['question_type_global', 'question_two_hop_statement']
list assignments that are due on [January 27]	'government project 1', 'business communication project 1'	['question_type_global', 'question_two_hop_statement']
show me all the late projects that i submitted	'government project 3'	['question_type_global', 'question_two_hop_statement']
what projects did i submit for [Lucio]?	'business communication project 2'	['question_type_global', 'question_three_hop_statement']
what assignments do I have to do?	'government project 1', 'french project 1', 'government project 2', 'french project 2', 'french homework 1', 'french homework 2', 'french project 3', 'government homework 1', 'government project 3', 'business communication project 1', 'business communication project 2', 'business communication project 3', 'government homework 2', 'french project 4', 'government project 4', 'french project 5', 'french homework 3'	['question_type_global', 'question_single_statement']
When is [government homework 2] due?	'February 05'	['question_type_local']
what are the late homeworks that i submitted?	'french homework 2'	['question_type_global', 'question_two_hop_statement']
[this homework] is due on [March 01]
