I am taking a [history] course
[Angelita] is a [professor]
[this person] is affiliated with the [psychology] department
[Angelita] is in [3851]
[this professor]'s email is [Angelita@yale.edu]
show all professors	'Angelita'	['question_type_global', 'question_single_statement']
What office is [that professor] in?	'3851'	['question_type_local']
[history] is taught by [this professor]
What office is [that person] in?	'3851'	['question_type_local']
What department is [that person] affiliated with?	'psychology'	['question_type_local']
I am taking a course called [religion]
there is new [religion project 1] for [religion]
what are all the projects due?	'religion project 1'	['question_type_global', 'question_single_statement']
[this course] has a new [religion project 2] released
[religion project 1] is about [cold war]
What courses is [Angelita] teaching?	'history'	['question_type_local']
[religion project 2] is worth [37] points
I submitted [religion project 2] late and received 27 points
[that assignment] is due on [June 26]
Which professor is teaching [history]?	'Angelita'	['question_type_local']
list assignments that are due on [June 26]	'religion project 2'	['question_type_global', 'question_two_hop_statement']
who are the professors affiliated with [psychology]?	'Angelita'	['question_type_global', 'question_two_hop_statement']
[Hiram] is a [professor]
[that project] is on [supervised learning]
What is the topic of [religion project 2]?	'supervised learning'	['question_type_local']
show me all late assignments i submitted for [religion]	'religion project 2'	['question_type_global', 'question_two_hop_statement']
list projects that are due on [June 26]	'religion project 2'	['question_type_global', 'question_two_hop_statement']
there is a [professor] named [Will]
How many points did I get on [this project]	27	['question_type_local']
what are all the assignments due?	'religion project 1', 'religion project 2'	['question_type_global', 'question_single_statement']
who are the professors?	'Angelita', 'Hiram', 'Will'	['question_type_global', 'question_single_statement']
show me the assignments due on [June 26]	'religion project 2'	['question_type_global', 'question_two_hop_statement']
[he]'s email is [Will@yale.edu]
what assignments did i submit late for [religion]?	'religion project 2'	['question_type_global', 'question_two_hop_statement']
[religion homework 1] is released for [religion]
[this assignment] is due on [June 15]
What is the topic of [religion project 1]?	'cold war'	['question_type_local']
what are the late assignments that i submitted	'religion project 2'	['question_type_global', 'question_two_hop_statement']
show me the assignments due on [June 15]	'religion homework 1'	['question_type_global', 'question_two_hop_statement']
which assignments are due on [June 26]?	'religion project 2'	['question_type_global', 'question_two_hop_statement']
I submitted [this assignment] on time
[that assignment] is [80] points
The deadline of [religion project 1] is [June 14]
I submitted [religion project 1] late
what are the assignments that i submitted?	'religion project 1', 'religion project 2', 'religion homework 1'	['question_type_global', 'question_two_hop_statement']
show me all courses for which i submitted at least one late project	'religion'	['question_type_global', 'question_two_hop_statement']
who are the professors?	'Angelita', 'Hiram', 'Will'	['question_type_global', 'question_single_statement']
[this project] is [79] points
[Lucy] is a [professor]
[history project 1] is released for [history]
[she]'s email is [Lucy@chk.ru]
[that professor] is in [3851]
the affiliation of [she] is [applied physics]
The topic of [religion homework 1] is [unsupervised learning]
List all assignments for [religion]	'religion project 1', 'religion project 2', 'religion homework 1'	['question_type_local']
list all projects	'religion project 1', 'religion project 2', 'history project 1'	['question_type_global', 'question_single_statement']
what assignments did i submit?	'religion project 1', 'religion project 2', 'religion homework 1'	['question_type_global', 'question_two_hop_statement']
what projects do I have to do for [history]?	'history project 1'	['question_type_global', 'question_two_hop_statement']
List all assignments for [history]	'history project 1'	['question_type_local']
what projects did i submit for [religion]?	'religion project 1', 'religion project 2'	['question_type_global', 'question_two_hop_statement']
which professors are in the [psychology] department?	'Angelita'	['question_type_global', 'question_two_hop_statement']
What is the topic of [religion project 2]?	'supervised learning'	['question_type_local']
which assignments did I submit?	'religion project 1', 'religion project 2', 'religion homework 1'	['question_type_global', 'question_two_hop_statement']
which assignments are due before [June 24]?	'religion project 1', 'religion homework 1'	['question_type_global', 'question_two_hop_statement']
what are the homeworks that i submitted for [religion]	'religion homework 1'	['question_type_global', 'question_two_hop_statement']
What is [Angelita]'s department?	'psychology'	['question_type_local']
which projects are due before [June 16]?	'religion project 1'	['question_type_global', 'question_two_hop_statement']
what assignments did i submit?	'religion project 1', 'religion project 2', 'religion homework 1'	['question_type_global', 'question_two_hop_statement']
what projects do I have to do?	'religion project 1', 'religion project 2', 'history project 1'	['question_type_global', 'question_single_statement']
what did I get on [religion project 2]?	27	['question_type_local']
what are all the assignments due?	'religion project 1', 'religion project 2', 'religion homework 1', 'history project 1'	['question_type_global', 'question_single_statement']
which homeworks are due after [June 14]?	'religion homework 1'	['question_type_global', 'question_two_hop_statement']
How many points did I get on [religion project 2]	27	['question_type_local']
show me all late assignments i submitted for [religion]	'religion project 1', 'religion project 2'	['question_type_global', 'question_two_hop_statement']
what projects did i submit late?	'religion project 1', 'religion project 2'	['question_type_global', 'question_two_hop_statement']
what homeworks did i submit for [religion]?	'religion homework 1'	['question_type_global', 'question_two_hop_statement']
[Will] is the instructor for [religion]
I am taking a course called [sociology]
[he] is in [788]
the affiliation of [this professor] is [applied physics]
how much did I get on [religion project 2]?	27	['question_type_local']
what projects did i submit for [religion]?	'religion project 1', 'religion project 2'	['question_type_global', 'question_two_hop_statement']
list all assignments that i submitted	'religion project 1', 'religion project 2', 'religion homework 1'	['question_type_global', 'question_two_hop_statement']
show me all the late assignments that i submitted	'religion project 1', 'religion project 2'	['question_type_global', 'question_two_hop_statement']
there is a [professor] named [Eun]
what did I get on [religion project 2]?	27	['question_type_local']
who did I submit assignments late to	'Will'	['question_type_global', 'question_three_hop_statement']
who are the instructors to whom i submitted any late projects?	'Will'	['question_type_global', 'question_three_hop_statement']
show me all projects i submitted	'religion project 1', 'religion project 2'	['question_type_global', 'question_two_hop_statement']
[she]'s office is [156]
the affiliation of [Eun] is [psychology]
[that professor]'s email is [Eun@chk.ru]
What is [Lucy]'s office?	'3851'	['question_type_local']
which assignments are due after [June 18]?	'religion project 2'	['question_type_global', 'question_two_hop_statement']
list all assignments for [history]	'history project 1'	['question_type_global', 'question_two_hop_statement']
what are the late projects that i submitted?	'religion project 1', 'religion project 2'	['question_type_global', 'question_two_hop_statement']
who are the instructors to whom i submitted any late assignments?	'Will'	['question_type_global', 'question_three_hop_statement']
What is [that person]'s email	'Eun@chk.ru'	['question_type_local']
list all projects that i submitted late for [Will]	'religion project 1', 'religion project 2'	['question_type_global', 'question_three_hop_statement']
what assignments did i submit late for [religion]?	'religion project 1', 'religion project 2'	['question_type_global', 'question_two_hop_statement']
what projects do I have to do?	'religion project 1', 'religion project 2', 'history project 1'	['question_type_global', 'question_single_statement']
Which professor is teaching [history]?	'Angelita'	['question_type_local']
who did I submit assignments late to	'Will'	['question_type_global', 'question_three_hop_statement']
I am taking a [government] course
What is [Will]'s department?	'applied physics'	['question_type_local']
what are all the homeworks due?	'religion homework 1'	['question_type_global', 'question_single_statement']
[sociology project 1] is released for [sociology]
[Eun] is the instructor for [government]
List all assignments for [history]	'history project 1'	['question_type_local']
what are all the projects due?	'religion project 1', 'religion project 2', 'history project 1', 'sociology project 1'	['question_type_global', 'question_single_statement']
show me all the late projects that i submitted	'religion project 1', 'religion project 2'	['question_type_global', 'question_two_hop_statement']
list all projects	'religion project 1', 'religion project 2', 'history project 1', 'sociology project 1'	['question_type_global', 'question_single_statement']
[that person]'s department is now [applied physics]
How much is [religion homework 1] worth?	80	['question_type_local']
list all the professors	'Angelita', 'Hiram', 'Will', 'Lucy', 'Eun'	['question_type_global', 'question_single_statement']
[sociology] has a new [sociology homework 1] released
[this assignment] is about [introduction]
I submitted [this assignment] late
[that homework] is due on [June 16]
[sociology homework 1] is worth [16] points
which assignments are due on [June 14]?	'religion project 1'	['question_type_global', 'question_two_hop_statement']
what homeworks did i submit?	'religion homework 1', 'sociology homework 1'	['question_type_global', 'question_two_hop_statement']
List all assignments for [sociology]	'sociology project 1', 'sociology homework 1'	['question_type_local']
show me all the late projects that i submitted	'religion project 1', 'religion project 2'	['question_type_global', 'question_two_hop_statement']
What office is [Angelita] in?	'3851'	['question_type_local']
[government] has a new [government homework 1] released
Show me all homeworks due for [government]	'government homework 1'	['question_type_local']
which professors did I submit late assignments for?	'Will'	['question_type_global', 'question_three_hop_statement']
what are the late assignments that i submitted	'religion project 1', 'religion project 2', 'sociology homework 1'	['question_type_global', 'question_two_hop_statement']
[Michael] is a [professor]
[this person]'s email is [Michael@harvard.edu]
[this professor] is in [3851]
[that professor] is affiliated with the [neuroscience] department
What courses is [Will] teaching?	'religion'	['question_type_local']
show me all late assignments i submitted for [Will]	'religion project 1', 'religion project 2'	['question_type_global', 'question_three_hop_statement']
what homeworks did i submit for [Will]?	'religion homework 1'	['question_type_global', 'question_three_hop_statement']
which homeworks did I submit late?	'sociology homework 1'	['question_type_global', 'question_two_hop_statement']
What are the assignments for [history]?	'history project 1'	['question_type_local']
what are all the homeworks due for [government]?	'government homework 1'	['question_type_global', 'question_two_hop_statement']
[sociology] has a new [sociology project 2] out
When is the deadline of [religion project 2]?	'June 26'	['question_type_local']
list projects that are due on [June 14]	'religion project 1'	['question_type_global', 'question_two_hop_statement']
show me the assignments due on [June 15]	'religion homework 1'	['question_type_global', 'question_two_hop_statement']
who are the professors?	'Angelita', 'Hiram', 'Will', 'Lucy', 'Eun', 'Michael'	['question_type_global', 'question_single_statement']
who are the professors affiliated with [psychology]?	'Angelita'	['question_type_global', 'question_two_hop_statement']
which homeworks are due after [June 15]?	'sociology homework 1'	['question_type_global', 'question_two_hop_statement']
list all homeworks for [government]	'government homework 1'	['question_type_global', 'question_two_hop_statement']
list all assignments that i submitted late	'religion project 1', 'religion project 2', 'sociology homework 1'	['question_type_global', 'question_two_hop_statement']
what are the late projects that i submitted for [Will]	'religion project 1', 'religion project 2'	['question_type_global', 'question_three_hop_statement']
I submitted [this project]
[that assignment] is worth [17] points
[sociology project 2] is due on [June 16]
there is new [history project 2] for [history]
The topic of [sociology project 2] is [Plants]
The deadline of [history project 2] is [June 20]
[history project 2] is worth [34] points
What is [sociology project 2] on?	'Plants'	['question_type_local']
show me the homeworks due on [June 15]	'religion homework 1'	['question_type_global', 'question_two_hop_statement']
What department is [Will] affiliated with?	'applied physics'	['question_type_local']
what are the late assignments that i submitted	'religion project 1', 'religion project 2', 'sociology homework 1'	['question_type_global', 'question_two_hop_statement']
which homeworks are due before [June 18]?	'religion homework 1', 'sociology homework 1'	['question_type_global', 'question_two_hop_statement']
list all assignments that i submitted late for [Will]	'religion project 1', 'religion project 2'	['question_type_global', 'question_three_hop_statement']
[history project 3] is out for [history]
[history project 2] is about [Molds & Fungi]
I submitted [history project 2] late and received 1 points
what did I get on [religion project 2]?	27	['question_type_local']
list all projects for [history]	'history project 1', 'history project 2', 'history project 3'	['question_type_global', 'question_two_hop_statement']
[sociology homework 2] is released for [sociology]
[sociology homework 2] is [57] points
The topic of [sociology homework 2] is [Cells]
[that assignment] is due on [June 18]
there is a new [project] for [government]
[government project 1] is due on [June 15]
[this assignment] is [36] points
I submitted [this project] and received 32 points
What office is [Will] in?	'788'	['question_type_local']
what are the assignments that i submitted?	'religion project 1', 'religion project 2', 'religion homework 1', 'sociology homework 1', 'sociology project 2', 'history project 2', 'government project 1'	['question_type_global', 'question_two_hop_statement']
which assignments did I submit late?	'religion project 1', 'religion project 2', 'sociology homework 1', 'history project 2'	['question_type_global', 'question_two_hop_statement']
The topic of [this project] is [svm]
[history homework 1] is released for [history]
When is [this project] due?	'June 15'	['question_type_local']
[history homework 2] is out for [history]
The topic of [history homework 2] is [The Senses]
I submitted [that assignment] on time
[William] is a [professor]
the affiliation of [this professor] is [english]
[this person] is in [788]
[this person]'s email is [William@cornell.edu]
how many points is [sociology homework 1]?	16	['question_type_local']
list assignments that are due on [June 14]	'religion project 1'	['question_type_global', 'question_two_hop_statement']
list all projects that i submitted late	'religion project 1', 'religion project 2', 'history project 2'	['question_type_global', 'question_two_hop_statement']
which homeworks are due after [June 16]?	'sociology homework 2'	['question_type_global', 'question_two_hop_statement']
there is new [government homework 2] for [government]
The deadline of [that homework] is [June 28]
show me all late assignments i submitted for [Will]	'religion project 1', 'religion project 2'	['question_type_global', 'question_three_hop_statement']
what are the late projects that i submitted?	'religion project 1', 'religion project 2', 'history project 2'	['question_type_global', 'question_two_hop_statement']
which assignments are due after [June 14]?	'religion project 2', 'religion homework 1', 'sociology homework 1', 'sociology project 2', 'history project 2', 'sociology homework 2', 'government project 1', 'government homework 2'	['question_type_global', 'question_two_hop_statement']
what are the projects that i submitted?	'religion project 1', 'religion project 2', 'sociology project 2', 'history project 2', 'government project 1'	['question_type_global', 'question_two_hop_statement']
what instructors did i have late projects for?	'Angelita', 'Will'	['question_type_global', 'question_three_hop_statement']
[that assignment] is [33] points
What department is [William] affiliated with?	'english'	['question_type_local']
what are the courses for which I submitted assignments late	'history', 'religion', 'sociology'	['question_type_global', 'question_two_hop_statement']
which professors did I submit late assignments for?	'Angelita', 'Will'	['question_type_global', 'question_three_hop_statement']
which homeworks did I submit?	'religion homework 1', 'sociology homework 1', 'history homework 2'	['question_type_global', 'question_two_hop_statement']
I submitted [that homework] and received 33 points
how much did I get on [history project 2]?	1	['question_type_local']
list all projects for [Will]	'religion project 1', 'religion project 2'	['question_type_global', 'question_three_hop_statement']
what projects did i submit late for [Will]?	'religion project 1', 'religion project 2'	['question_type_global', 'question_three_hop_statement']
list all homeworks for [Eun]	'government homework 1', 'government homework 2'	['question_type_global', 'question_three_hop_statement']
what are all the projects due for [sociology]?	'sociology project 1', 'sociology project 2'	['question_type_global', 'question_two_hop_statement']
what instructors did i have late assignments for?	'Angelita', 'Will'	['question_type_global', 'question_three_hop_statement']
How many points did I get on [religion project 2]	27	['question_type_local']
what are the late assignments that i submitted for [Will]	'religion project 1', 'religion project 2'	['question_type_global', 'question_three_hop_statement']
what are the late homeworks that i submitted?	'sociology homework 1'	['question_type_global', 'question_two_hop_statement']
there is a [professor] named [Tereasa]
The deadline of [government homework 2] moved to [July 01]
What office is [William] in?	'788'	['question_type_local']
show me all homeworks i submitted	'religion homework 1', 'sociology homework 1', 'history homework 2', 'government homework 2'	['question_type_global', 'question_two_hop_statement']
list all projects that i submitted late for [Angelita]	'history project 2'	['question_type_global', 'question_three_hop_statement']
[that professor]'s email is [Tereasa@cornell.edu]
[that person] is in [156]
[that professor]'s department is [applied physics]
how many points is [sociology homework 1]?	16	['question_type_local']
show me all assignments i submitted for [history]	'history project 2', 'history homework 2'	['question_type_global', 'question_two_hop_statement']
which projects are due after [June 12]?	'religion project 1', 'religion project 2', 'sociology project 2', 'history project 2', 'government project 1'	['question_type_global', 'question_two_hop_statement']
what are the homeworks that i submitted for [Will]	'religion homework 1'	['question_type_global', 'question_three_hop_statement']
what are the homeworks that i submitted for [Angelita]	'history homework 2'	['question_type_global', 'question_three_hop_statement']
how many points is [religion project 2]?	37	['question_type_local']
what homeworks did i submit late?	'sociology homework 1'	['question_type_global', 'question_two_hop_statement']
what are the courses for which I submitted assignments late	'history', 'religion', 'sociology'	['question_type_global', 'question_two_hop_statement']
what projects did i submit late for [history]?	'history project 2'	['question_type_global', 'question_two_hop_statement']
What is [Angelita]'s department?	'psychology'	['question_type_local']
which homeworks did I submit late for [sociology]?	'sociology homework 1'	['question_type_global', 'question_two_hop_statement']
what assignments do I have to do for [religion]?	'religion project 1', 'religion project 2'	['question_type_global', 'question_two_hop_statement']
show me all homeworks i submitted	'religion homework 1', 'sociology homework 1', 'history homework 2', 'government homework 2'	['question_type_global', 'question_two_hop_statement']
How many points is [government project 1] worth?	36	['question_type_local']
what are the courses for which I submitted assignments late	'history', 'religion', 'sociology'	['question_type_global', 'question_two_hop_statement']
which projects did I submit late for [Will]?	'religion project 1', 'religion project 2'	['question_type_global', 'question_three_hop_statement']
what are all the homeworks due for [Will]?	'religion homework 1'	['question_type_global', 'question_three_hop_statement']
what projects do I have to do?	'religion project 1', 'religion project 2', 'history project 1', 'sociology project 1', 'sociology project 2', 'history project 2', 'history project 3', 'government project 1'	['question_type_global', 'question_single_statement']
What is [Eun]'s office?	'156'	['question_type_local']
what homeworks do I have to do for [government]?	'government homework 1', 'government homework 2'	['question_type_global', 'question_two_hop_statement']
which assignments did I submit?	'religion project 1', 'religion project 2', 'religion homework 1', 'sociology homework 1', 'sociology project 2', 'history project 2', 'government project 1', 'history homework 2', 'government homework 2'	['question_type_global', 'question_two_hop_statement']
The deadline of [sociology project 2] moved to [June 19]
What is [sociology homework 1] on?	'introduction'	['question_type_local']
what assignments do I have to do?	'religion project 1', 'religion project 2', 'religion homework 1', 'history project 1', 'sociology project 1', 'sociology homework 1', 'government homework 1', 'sociology project 2', 'history project 2', 'history project 3', 'sociology homework 2', 'government project 1', 'history homework 1', 'history homework 2', 'government homework 2'	['question_type_global', 'question_single_statement']
list all assignments that i submitted	'religion project 1', 'religion project 2', 'religion homework 1', 'sociology homework 1', 'sociology project 2', 'history project 2', 'government project 1', 'history homework 2', 'government homework 2'	['question_type_global', 'question_two_hop_statement']
list all assignments that i submitted for [religion]	'religion project 1', 'religion project 2', 'religion homework 1'	['question_type_global', 'question_two_hop_statement']
which homeworks are due before [June 27]?	'religion homework 1', 'sociology homework 1', 'sociology homework 2'	['question_type_global', 'question_two_hop_statement']
what assignments do I have to do for [Angelita]?	'history project 1', 'history project 2', 'history project 3', 'history homework 1', 'history homework 2'	['question_type_global', 'question_three_hop_statement']
which projects did I submit late?	'religion project 1', 'religion project 2', 'history project 2'	['question_type_global', 'question_two_hop_statement']
[Kristeen] is a [professor]
When is [sociology homework 2] due?	'June 18'	['question_type_local']
who did I submit projects late to	'Angelita', 'Will'	['question_type_global', 'question_three_hop_statement']
what are the courses for which I submitted projects late	'history', 'religion'	['question_type_global', 'question_two_hop_statement']
show me all homeworks i submitted	'religion homework 1', 'sociology homework 1', 'history homework 2', 'government homework 2'	['question_type_global', 'question_two_hop_statement']
list all projects	'religion project 1', 'religion project 2', 'history project 1', 'sociology project 1', 'sociology project 2', 'history project 2', 'history project 3', 'government project 1'	['question_type_global', 'question_single_statement']
[history] has a new [history project 4] out
[this project] is [56] points
how many points did I receive on [history project 2]?	1	['question_type_local']
what are the projects that i submitted for [sociology]	'sociology project 2'	['question_type_global', 'question_two_hop_statement']
what are the projects that i submitted?	'religion project 1', 'religion project 2', 'sociology project 2', 'history project 2', 'government project 1'	['question_type_global', 'question_two_hop_statement']
what are all the projects due for [Angelita]?	'history project 1', 'history project 2', 'history project 3', 'history project 4'	['question_type_global', 'question_three_hop_statement']
I submitted [that project] and received 56 points
what did I get on [government project 1]?	32	['question_type_local']
which assignments are due after [June 19]?	'religion project 2', 'history project 2', 'government homework 2'	['question_type_global', 'question_two_hop_statement']
show me all the late projects that i submitted	'religion project 1', 'religion project 2', 'history project 2'	['question_type_global', 'question_two_hop_statement']
[that project] is due on [July 16]
What department is [Lucy] affiliated with?	'applied physics'	['question_type_local']
what assignments do I have to do?	'religion project 1', 'religion project 2', 'religion homework 1', 'history project 1', 'sociology project 1', 'sociology homework 1', 'government homework 1', 'sociology project 2', 'history project 2', 'history project 3', 'sociology homework 2', 'government project 1', 'history homework 1', 'history homework 2', 'government homework 2', 'history project 4'	['question_type_global', 'question_single_statement']
[Kristeen]'s office is [156]
[Kristeen]'s email is [Kristeen@chk.ru]
what did I get on [religion project 2]?	27	['question_type_local']
what are the assignments that i submitted for [religion]	'religion project 1', 'religion project 2', 'religion homework 1'	['question_type_global', 'question_two_hop_statement']
which assignments are due after [June 18]?	'religion project 2', 'sociology project 2', 'history project 2', 'government homework 2', 'history project 4'	['question_type_global', 'question_two_hop_statement']
what are the assignments that i submitted for [history]	'history project 2', 'history homework 2', 'history project 4'	['question_type_global', 'question_two_hop_statement']
[that person]'s department is [neuroscience]
what homeworks do I have to do for [history]?	'history homework 1', 'history homework 2'	['question_type_global', 'question_two_hop_statement']
list all the professors	'Angelita', 'Hiram', 'Will', 'Lucy', 'Eun', 'Michael', 'William', 'Tereasa', 'Kristeen'	['question_type_global', 'question_single_statement']
which professors did I submit late projects for?	'Angelita', 'Will'	['question_type_global', 'question_three_hop_statement']
list all assignments that i submitted late	'religion project 1', 'religion project 2', 'sociology homework 1', 'history project 2'	['question_type_global', 'question_two_hop_statement']
[she]'s department is now [english]
What office is [Kristeen] in?	'156'	['question_type_local']
show me all projects i submitted for [Will]	'religion project 1', 'religion project 2'	['question_type_global', 'question_three_hop_statement']
what are all the homeworks due for [Will]?	'religion homework 1'	['question_type_global', 'question_three_hop_statement']
which homeworks did I submit?	'religion homework 1', 'sociology homework 1', 'history homework 2', 'government homework 2'	['question_type_global', 'question_two_hop_statement']
which courses did I submit late projects for?	'history', 'religion'	['question_type_global', 'question_two_hop_statement']
What office is [Tereasa] in?	'156'	['question_type_local']
show me all assignments i submitted for [sociology]	'sociology homework 1', 'sociology project 2'	['question_type_global', 'question_two_hop_statement']
When is [sociology project 2] due?	'June 19'	['question_type_local']
show me all late homeworks i submitted	'sociology homework 1'	['question_type_global', 'question_two_hop_statement']
How much is [government homework 2] worth?	33	['question_type_local']
list all assignments that i submitted late	'religion project 1', 'religion project 2', 'sociology homework 1', 'history project 2'	['question_type_global', 'question_two_hop_statement']
list the professors in the [applied physics] department	'Will', 'Lucy', 'Eun', 'Tereasa'	['question_type_global', 'question_two_hop_statement']
What is the topic of [sociology project 2]?	'Plants'	['question_type_local']
show me all late assignments i submitted for [history]	'history project 2'	['question_type_global', 'question_two_hop_statement']
what are the late assignments that i submitted	'religion project 1', 'religion project 2', 'sociology homework 1', 'history project 2'	['question_type_global', 'question_two_hop_statement']
which assignments did I submit late?	'religion project 1', 'religion project 2', 'sociology homework 1', 'history project 2'	['question_type_global', 'question_two_hop_statement']
how many points is [history project 4]?	56	['question_type_local']
show me all courses for which i submitted at least one late project	'history', 'religion'	['question_type_global', 'question_two_hop_statement']
who did I submit assignments late to	'Angelita', 'Will'	['question_type_global', 'question_three_hop_statement']
how many points is [government project 1]?	36	['question_type_local']
which assignments did I submit for [Eun]?	'government project 1', 'government homework 2'	['question_type_global', 'question_three_hop_statement']
list all assignments for [Will]	'religion project 1', 'religion project 2', 'religion homework 1'	['question_type_global', 'question_three_hop_statement']
which homeworks did I submit for [history]?	'history homework 2'	['question_type_global', 'question_two_hop_statement']
How much is [religion project 2] worth?	37	['question_type_local']
what assignments do I have to do for [government]?	'government project 1'	['question_type_global', 'question_two_hop_statement']
what courses did i have late homeworks for?	'sociology'	['question_type_global', 'question_two_hop_statement']
what are the courses for which i submitted late homeworks?	'sociology'	['question_type_global', 'question_two_hop_statement']
which homeworks are due on [June 18]?	'sociology homework 2'	['question_type_global', 'question_two_hop_statement']
what instructors did i have late assignments for?	'Angelita', 'Will'	['question_type_global', 'question_three_hop_statement']
list all homeworks that i submitted	'religion homework 1', 'sociology homework 1', 'history homework 2', 'government homework 2'	['question_type_global', 'question_two_hop_statement']
who are the instructors to whom i submitted any late assignments?	'Angelita', 'Will'	['question_type_global', 'question_three_hop_statement']
show me the projects due on [June 20]	'history project 2'	['question_type_global', 'question_two_hop_statement']
How much is [religion homework 1] worth?	80	['question_type_local']
show me all projects i submitted for [sociology]	'sociology project 2'	['question_type_global', 'question_two_hop_statement']
what projects do I have to do for [history]?	'history project 1', 'history project 2', 'history project 3', 'history project 4'	['question_type_global', 'question_two_hop_statement']
list assignments that are due on [June 26]	'religion project 2'	['question_type_global', 'question_two_hop_statement']
[sociology project 3] is out for [sociology]
which homeworks are due before [June 19]?	'religion homework 1', 'sociology homework 1', 'sociology homework 2'	['question_type_global', 'question_two_hop_statement']
what homeworks did i submit for [Will]?	'religion homework 1'	['question_type_global', 'question_three_hop_statement']
what assignments did i submit for [Eun]?	'government project 1', 'government homework 2'	['question_type_global', 'question_three_hop_statement']
which projects did I submit late for [Angelita]?	'history project 2'	['question_type_global', 'question_three_hop_statement']
