I am taking a course called [government]
create a [professor] named [Cecil]
[this professor]'s email is [Cecil@yale.edu]
the affiliation of [Cecil] is [english]
[government homework 1] is out for [government]
The topic of [that homework] is [deep learning]
[that homework] is worth [14] points
The deadline of [this assignment] is [March 20]
[government project 1] is released for [government]
[that project] is worth [22] points
What is [government homework 1] on?	'deep learning'	['question_type_local']
what assignments do I have to do?	'government homework 1', 'government project 1'	['question_type_global', 'question_single_statement']
I submitted [government project 1] on time and received 13 points
[government project 1] is due on [March 16]
how many points did I receive on [that assignment]?	13	['question_type_local']
list all projects for [government]	'government project 1'	['question_type_global', 'question_two_hop_statement']
[government] is taught by [Cecil]
which assignments are due on [March 20]?	'government homework 1'	['question_type_global', 'question_two_hop_statement']
which assignments did I submit?	'government project 1'	['question_type_global', 'question_two_hop_statement']
show me the assignments due on [March 16]	'government project 1'	['question_type_global', 'question_two_hop_statement']
What is the topic of [government homework 1]?	'deep learning'	['question_type_local']
there is a [professor] named [Genevive]
[she] is affiliated with the [english] department
[Genevive]'s email is [Genevive@msn.com]
I am taking a [statistics] course
[Genevive] is the instructor for [statistics]
I am taking a [microbiology] course
what homeworks do I have to do?	'government homework 1'	['question_type_global', 'question_single_statement']
which assignments did I submit for [Cecil]?	'government project 1'	['question_type_global', 'question_three_hop_statement']
I submitted [government homework 1] late and received 14 points
what projects do I have to do?	'government project 1'	['question_type_global', 'question_single_statement']
show me the assignments due on [March 20]	'government homework 1'	['question_type_global', 'question_two_hop_statement']
who are the professors affiliated with [english]?	'Cecil', 'Genevive'	['question_type_global', 'question_two_hop_statement']
[government homework 1] is now due on [March 18]
What is [Genevive]'s email	'Genevive@msn.com'	['question_type_local']
what are all the projects due for [Cecil]?	'government project 1'	['question_type_global', 'question_three_hop_statement']
which assignments are due on [March 18]?	'government homework 1'	['question_type_global', 'question_two_hop_statement']
what assignments did i submit?	'government homework 1', 'government project 1'	['question_type_global', 'question_two_hop_statement']
What is [this homework] on?	'deep learning'	['question_type_local']
list homeworks that are due on [March 18]	'government homework 1'	['question_type_global', 'question_two_hop_statement']
I am taking a [english composition] course
How many points did I get on [that homework]	14	['question_type_local']
What is [Genevive]'s email	'Genevive@msn.com'	['question_type_local']
show me all late homeworks i submitted	'government homework 1'	['question_type_global', 'question_two_hop_statement']
list all projects for [government]	'government project 1'	['question_type_global', 'question_two_hop_statement']
which homeworks did I submit for [Cecil]?	'government homework 1'	['question_type_global', 'question_three_hop_statement']
which projects are due before [March 21]?	'government project 1'	['question_type_global', 'question_two_hop_statement']
What is [government homework 1] on?	'deep learning'	['question_type_local']
what are all the projects due for [Cecil]?	'government project 1'	['question_type_global', 'question_three_hop_statement']
which homeworks did I submit?	'government homework 1'	['question_type_global', 'question_two_hop_statement']
what are the courses for which I submitted assignments late	'government'	['question_type_global', 'question_two_hop_statement']
How many points is [that assignment] worth?	14	['question_type_local']
what are all the homeworks due?	'government homework 1'	['question_type_global', 'question_single_statement']
which assignments did I submit late?	'government homework 1'	['question_type_global', 'question_two_hop_statement']
What courses is [Genevive] teaching?	'statistics'	['question_type_local']
what homeworks did i submit late?	'government homework 1'	['question_type_global', 'question_two_hop_statement']
change [Genevive]'s department to [applied physics]
Who is the instructor for [statistics]?	'Genevive'	['question_type_local']
which homeworks are due before [March 21]?	'government homework 1'	['question_type_global', 'question_two_hop_statement']
there is new [statistics homework 1] for [statistics]
[this homework] is worth [86] points
what assignments did i submit late for [Cecil]?	'government homework 1'	['question_type_global', 'question_three_hop_statement']
list all projects for [Cecil]	'government project 1'	['question_type_global', 'question_three_hop_statement']
there is a new [homework] for [statistics]
The deadline of [statistics homework 2] is [March 29]
I submitted [this homework]
The topic of [statistics homework 2] is [decision trees]
how many points did I receive on [government homework 1]?	14	['question_type_local']
show me all late homeworks i submitted for [government]	'government homework 1'	['question_type_global', 'question_two_hop_statement']
on which assignments did I get full credit?	'government homework 1'	['question_type_global', 'question_three_hop_statement']
[government] has a new [government homework 2] released
I submitted [government homework 2] on time
[that homework] is [19] points
[government homework 2] is on [supervised learning]
[this assignment] is due on [April 04]
what assignments do I have to do for [government]?	'government project 1'	['question_type_global', 'question_two_hop_statement']
list all homeworks	'government homework 1', 'statistics homework 1', 'statistics homework 2', 'government homework 2'	['question_type_global', 'question_single_statement']
what are the courses for which I submitted assignments late	'government'	['question_type_global', 'question_two_hop_statement']
there is a [professor] named [Lorilee]
[that person]'s email is [Lorilee@yandex.com]
[Lorilee] is affiliated with the [applied physics] department
list assignments that are due on [April 04]	'government homework 2'	['question_type_global', 'question_two_hop_statement']
[this professor]'s department is now [mechanical engineering]
what assignments do I have to do?	'government homework 1', 'government project 1', 'statistics homework 1', 'statistics homework 2', 'government homework 2'	['question_type_global', 'question_single_statement']
there is a [professor] named [Luanna]
[Luanna]'s department is [applied physics]
[Luanna]'s email is [Luanna@yandex.com]
create a [professor] named [Milagros]
the affiliation of [Milagros] is [english]
[Milagros]'s email is [Milagros@nh.edu]
The topic of [government project 1] is [logistic regression]
how many points did I receive on [government homework 1]?	14	['question_type_local']
list all homeworks that i submitted	'government homework 1', 'statistics homework 2', 'government homework 2'	['question_type_global', 'question_two_hop_statement']
what courses did i have late assignments for?	'government'	['question_type_global', 'question_two_hop_statement']
how many points is [statistics homework 1]?	86	['question_type_local']
list all assignments for [Genevive]	'statistics homework 1', 'statistics homework 2'	['question_type_global', 'question_three_hop_statement']
which professors did I submit late homeworks for?	'Cecil'	['question_type_global', 'question_three_hop_statement']
what are the homeworks that i submitted for [Genevive]	'statistics homework 2'	['question_type_global', 'question_three_hop_statement']
what are the projects that i submitted?	'government project 1'	['question_type_global', 'question_two_hop_statement']
which projects did I submit?	'government project 1'	['question_type_global', 'question_two_hop_statement']
who did I submit assignments late to	'Cecil'	['question_type_global', 'question_three_hop_statement']
how many points did I receive on [government project 1]?	13	['question_type_local']
list assignments that are due on [April 04]	'government homework 2'	['question_type_global', 'question_two_hop_statement']
what are the assignments that i submitted?	'government homework 1', 'government project 1', 'statistics homework 2', 'government homework 2'	['question_type_global', 'question_two_hop_statement']
who are the professors?	'Cecil', 'Genevive', 'Lorilee', 'Luanna', 'Milagros'	['question_type_global', 'question_single_statement']
[statistics] has a new [statistics homework 3] out
[this homework] is due on [April 18]
The topic of [that assignment] is [cold war]
I submitted [statistics homework 3]
[that assignment] is worth [35] points
show me all homeworks i submitted for [Genevive]	'statistics homework 2', 'statistics homework 3'	['question_type_global', 'question_three_hop_statement']
who are the professors affiliated with [applied physics]?	'Genevive', 'Luanna'	['question_type_global', 'question_two_hop_statement']
list all homeworks for [Genevive]	'statistics homework 1', 'statistics homework 2', 'statistics homework 3'	['question_type_global', 'question_three_hop_statement']
[Luanna] is the instructor for [english composition]
there is new [government project 2] for [government]
what homeworks did i submit for [government]?	'government homework 1', 'government homework 2'	['question_type_global', 'question_two_hop_statement']
what are the late homeworks that i submitted?	'government homework 1'	['question_type_global', 'question_two_hop_statement']
what are all the projects due?	'government project 1', 'government project 2'	['question_type_global', 'question_single_statement']
there is a new [project] for [microbiology]
The topic of [microbiology project 1] is [Plants]
I submitted [that assignment]
[that project] is [57] points
Show me all homeworks due for [government]	'government homework 1', 'government homework 2'	['question_type_local']
what assignments do I have to do for [microbiology]?	'microbiology project 1'	['question_type_global', 'question_two_hop_statement']
list all assignments that i submitted late	'government homework 1'	['question_type_global', 'question_two_hop_statement']
list all homeworks that i submitted late	'government homework 1'	['question_type_global', 'question_two_hop_statement']
create a [professor] named [Andrew]
[that project] is due on [March 14]
there is new [english composition homework 1] for [english composition]
The topic of [english composition homework 1] is [clustering]
show me the assignments due on [April 04]	'government homework 2'	['question_type_global', 'question_two_hop_statement']
[english composition] has a new [english composition project 1] out
[english composition project 1] is about [The Environment]
I submitted [this assignment]
[this project] is worth [24] points
show me all assignments i submitted for [statistics]	'statistics homework 2', 'statistics homework 3'	['question_type_global', 'question_two_hop_statement']
what are all the projects due for [Luanna]?	'english composition project 1'	['question_type_global', 'question_three_hop_statement']
[that assignment] is due on [March 21]
What is [Milagros]'s email	'Milagros@nh.edu'	['question_type_local']
which projects are due after [March 15]?	'government project 1', 'english composition project 1'	['question_type_global', 'question_two_hop_statement']
[government] has a new [government project 3] released
[government project 3] is due on [April 09]
I submitted [government project 3] late
What is [english composition homework 1] on?	'clustering'	['question_type_local']
list all assignments	'government homework 1', 'government project 1', 'statistics homework 1', 'statistics homework 2', 'government homework 2', 'statistics homework 3', 'government project 2', 'microbiology project 1', 'english composition homework 1', 'english composition project 1', 'government project 3'	['question_type_global', 'question_single_statement']
which projects are due after [March 14]?	'government project 1', 'english composition project 1', 'government project 3'	['question_type_global', 'question_two_hop_statement']
show me all late homeworks i submitted	'government homework 1'	['question_type_global', 'question_two_hop_statement']
The topic of [that assignment] is [suffrage movement]
The deadline of [that project] moved to [April 12]
there is a [professor] named [Francoise]
[that project] is worth [76] points
[this professor]'s department is [applied physics]
there is a [professor] named [Rey]
[Francoise]'s email is [Francoise@cornell.edu]
list all homeworks that i submitted for [statistics]	'statistics homework 2', 'statistics homework 3'	['question_type_global', 'question_two_hop_statement']
what are all the projects due?	'government project 1', 'government project 2', 'microbiology project 1', 'english composition project 1', 'government project 3'	['question_type_global', 'question_single_statement']
list all projects for [microbiology]	'microbiology project 1'	['question_type_global', 'question_two_hop_statement']
[microbiology homework 1] is released for [microbiology]
[statistics homework 1] is due on [March 19]
When is the deadline of [government homework 2]?	'April 04'	['question_type_local']
what are the assignments that i submitted?	'government homework 1', 'government project 1', 'statistics homework 2', 'government homework 2', 'statistics homework 3', 'microbiology project 1', 'english composition project 1', 'government project 3'	['question_type_global', 'question_two_hop_statement']
what homeworks did i submit for [Genevive]?	'statistics homework 2', 'statistics homework 3'	['question_type_global', 'question_three_hop_statement']
there is a [professor] named [Lucy]
[this professor] is affiliated with the [mechanical engineering] department
What is [statistics homework 2] on?	'decision trees'	['question_type_local']
list all assignments that i submitted late for [Cecil]	'government homework 1', 'government project 3'	['question_type_global', 'question_three_hop_statement']
what are the projects that i submitted?	'government project 1', 'microbiology project 1', 'english composition project 1', 'government project 3'	['question_type_global', 'question_two_hop_statement']
which assignments are due before [April 21]?	'government homework 1', 'government project 1', 'statistics homework 1', 'statistics homework 2', 'government homework 2', 'statistics homework 3', 'microbiology project 1', 'english composition project 1', 'government project 3'	['question_type_global', 'question_two_hop_statement']
show me all late homeworks i submitted	'government homework 1'	['question_type_global', 'question_two_hop_statement']
When is [government homework 1] due?	'March 18'	['question_type_local']
what are all the projects due for [government]?	'government project 1', 'government project 2', 'government project 3'	['question_type_global', 'question_two_hop_statement']
[english composition homework 2] is released for [english composition]
[Lucy]'s email is [Lucy@cmu.edu]
What department is [Lucy] affiliated with?	'mechanical engineering'	['question_type_local']
what assignments did i submit late?	'government homework 1', 'government project 3'	['question_type_global', 'question_two_hop_statement']
what assignments did i submit?	'government homework 1', 'government project 1', 'statistics homework 2', 'government homework 2', 'statistics homework 3', 'microbiology project 1', 'english composition project 1', 'government project 3'	['question_type_global', 'question_two_hop_statement']
which assignments are due before [April 03]?	'government homework 1', 'government project 1', 'statistics homework 1', 'statistics homework 2', 'microbiology project 1', 'english composition project 1'	['question_type_global', 'question_two_hop_statement']
show me all the late assignments that i submitted	'government homework 1', 'government project 3'	['question_type_global', 'question_two_hop_statement']
which assignments are due after [March 18]?	'statistics homework 1', 'statistics homework 2', 'government homework 2', 'statistics homework 3', 'english composition project 1', 'government project 3'	['question_type_global', 'question_two_hop_statement']
[that assignment] is [81] points
what homeworks do I have to do?	'government homework 1', 'statistics homework 1', 'statistics homework 2', 'government homework 2', 'statistics homework 3', 'english composition homework 1', 'microbiology homework 1', 'english composition homework 2'	['question_type_global', 'question_single_statement']
what are the courses for which I submitted assignments late	'government'	['question_type_global', 'question_two_hop_statement']
which assignments did I submit late?	'government homework 1', 'government project 3'	['question_type_global', 'question_two_hop_statement']
change [this person]'s department to [applied physics]
What is the topic of [microbiology project 1]?	'Plants'	['question_type_local']
list all the professors	'Cecil', 'Genevive', 'Lorilee', 'Luanna', 'Milagros', 'Andrew', 'Francoise', 'Rey', 'Lucy'	['question_type_global', 'question_single_statement']
what homeworks did i submit late?	'government homework 1'	['question_type_global', 'question_two_hop_statement']
[this assignment] is due on [April 02]
I submitted [english composition homework 2] and received 24 points
what courses did i have late assignments for?	'government'	['question_type_global', 'question_two_hop_statement']
show me all the late assignments that i submitted	'government homework 1', 'government project 3'	['question_type_global', 'question_two_hop_statement']
list all projects	'government project 1', 'government project 2', 'microbiology project 1', 'english composition project 1', 'government project 3'	['question_type_global', 'question_single_statement']
What courses is [Genevive] teaching?	'statistics'	['question_type_local']
[microbiology project 1] is now due on [March 15]
there is new [microbiology homework 2] for [microbiology]
The deadline of [microbiology homework 2] is [March 23]
[microbiology homework 2] is [35] points
I submitted [this homework] late and received 29 points
how many points did I receive on [government project 1]?	13	['question_type_local']
which homeworks did I submit late?	'government homework 1', 'microbiology homework 2'	['question_type_global', 'question_two_hop_statement']
show all professors	'Cecil', 'Genevive', 'Lorilee', 'Luanna', 'Milagros', 'Andrew', 'Francoise', 'Rey', 'Lucy'	['question_type_global', 'question_single_statement']
list all assignments that i submitted late for [Cecil]	'government homework 1', 'government project 3'	['question_type_global', 'question_three_hop_statement']
what projects do I have to do for [government]?	'government project 1', 'government project 2', 'government project 3'	['question_type_global', 'question_two_hop_statement']
What is [government homework 2] on?	'supervised learning'	['question_type_local']
list homeworks that are due on [April 02]	'english composition homework 2'	['question_type_global', 'question_two_hop_statement']
what courses did i have late projects for?	'government'	['question_type_global', 'question_two_hop_statement']
who did I submit homeworks late to	'Cecil'	['question_type_global', 'question_three_hop_statement']
What is the topic of [statistics homework 2]?	'decision trees'	['question_type_local']
show me all courses for which i submitted at least one late homework	'government', 'microbiology'	['question_type_global', 'question_two_hop_statement']
what are all the projects due?	'government project 1', 'government project 2', 'microbiology project 1', 'english composition project 1', 'government project 3'	['question_type_global', 'question_single_statement']
what projects did i submit late for [Cecil]?	'government project 3'	['question_type_global', 'question_three_hop_statement']
show me all late homeworks i submitted for [Cecil]	'government homework 1'	['question_type_global', 'question_three_hop_statement']
list all homeworks that i submitted for [microbiology]	'microbiology homework 2'	['question_type_global', 'question_two_hop_statement']
How much is [english composition homework 2] worth?	81	['question_type_local']
what projects do I have to do for [government]?	'government project 1', 'government project 2', 'government project 3'	['question_type_global', 'question_two_hop_statement']
What is [Genevive]'s email	'Genevive@msn.com'	['question_type_local']
who are the professors affiliated with [mechanical engineering]?	'Lorilee'	['question_type_global', 'question_two_hop_statement']
what homeworks do I have to do for [microbiology]?	'microbiology homework 1', 'microbiology homework 2'	['question_type_global', 'question_two_hop_statement']
which projects are due after [March 19]?	'english composition project 1', 'government project 3'	['question_type_global', 'question_two_hop_statement']
What is [english composition homework 1] on?	'clustering'	['question_type_local']
which courses did I submit late assignments for?	'government', 'microbiology'	['question_type_global', 'question_two_hop_statement']
list all projects that i submitted late	'government project 3'	['question_type_global', 'question_two_hop_statement']
show me all the late assignments that i submitted	'government homework 1', 'government project 3', 'microbiology homework 2'	['question_type_global', 'question_two_hop_statement']
who are the professors affiliated with [applied physics]?	'Genevive', 'Luanna', 'Francoise', 'Lucy'	['question_type_global', 'question_two_hop_statement']
which homeworks are due on [April 04]?	'government homework 2'	['question_type_global', 'question_two_hop_statement']
what are the courses for which I submitted assignments late	'government', 'microbiology'	['question_type_global', 'question_two_hop_statement']
which homeworks did I submit for [statistics]?	'statistics homework 2', 'statistics homework 3'	['question_type_global', 'question_two_hop_statement']
show me the projects due on [March 15]	'microbiology project 1'	['question_type_global', 'question_two_hop_statement']
which homeworks did I submit late for [Cecil]?	'government homework 1'	['question_type_global', 'question_three_hop_statement']
what assignments do I have to do for [Luanna]?	'english composition homework 1', 'english composition project 1', 'english composition homework 2'	['question_type_global', 'question_three_hop_statement']
What is the topic of [english composition homework 1]?	'clustering'	['question_type_local']
list all homeworks	'government homework 1', 'statistics homework 1', 'statistics homework 2', 'government homework 2', 'statistics homework 3', 'english composition homework 1', 'microbiology homework 1', 'english composition homework 2', 'microbiology homework 2'	['question_type_global', 'question_single_statement']
What department is [Francoise] affiliated with?	'applied physics'	['question_type_local']
list the professors in the [None] department	'Andrew', 'Rey'	['question_type_global', 'question_two_hop_statement']
which assignments are due before [April 15]?	'government homework 1', 'government project 1', 'statistics homework 1', 'statistics homework 2', 'government homework 2', 'microbiology project 1', 'english composition project 1', 'government project 3', 'english composition homework 2', 'microbiology homework 2'	['question_type_global', 'question_two_hop_statement']
What is [Lorilee]'s email	'Lorilee@yandex.com'	['question_type_local']
what projects did i submit late for [Cecil]?	'government project 3'	['question_type_global', 'question_three_hop_statement']
what assignments did i submit for [microbiology]?	'microbiology project 1', 'microbiology homework 2'	['question_type_global', 'question_two_hop_statement']
How much is [statistics homework 3] worth?	35	['question_type_local']
list all assignments	'government homework 1', 'government project 1', 'statistics homework 1', 'statistics homework 2', 'government homework 2', 'statistics homework 3', 'government project 2', 'microbiology project 1', 'english composition homework 1', 'english composition project 1', 'government project 3', 'microbiology homework 1', 'english composition homework 2', 'microbiology homework 2'	['question_type_global', 'question_single_statement']
show me all the late projects that i submitted	'government project 3'	['question_type_global', 'question_two_hop_statement']
which homeworks did I submit?	'government homework 1', 'statistics homework 2', 'government homework 2', 'statistics homework 3', 'english composition homework 2', 'microbiology homework 2'	['question_type_global', 'question_two_hop_statement']
which homeworks are due on [April 02]?	'english composition homework 2'	['question_type_global', 'question_two_hop_statement']
what courses did i have late homeworks for?	'government', 'microbiology'	['question_type_global', 'question_two_hop_statement']
show me all courses for which i submitted at least one late project	'government'	['question_type_global', 'question_two_hop_statement']
which assignments are due before [March 31]?	'government homework 1', 'government project 1', 'statistics homework 1', 'statistics homework 2', 'microbiology project 1', 'english composition project 1', 'microbiology homework 2'	['question_type_global', 'question_two_hop_statement']
what assignments do I have to do for [Genevive]?	'statistics homework 1', 'statistics homework 2', 'statistics homework 3'	['question_type_global', 'question_three_hop_statement']
list all assignments that i submitted for [microbiology]	'microbiology project 1', 'microbiology homework 2'	['question_type_global', 'question_two_hop_statement']
show me all homeworks i submitted	'government homework 1', 'statistics homework 2', 'government homework 2', 'statistics homework 3', 'english composition homework 2', 'microbiology homework 2'	['question_type_global', 'question_two_hop_statement']
which assignments did I submit late for [microbiology]?	'microbiology homework 2'	['question_type_global', 'question_two_hop_statement']
which homeworks did I submit for [microbiology]?	'microbiology homework 2'	['question_type_global', 'question_two_hop_statement']
which courses did I submit late homeworks for?	'government', 'microbiology'	['question_type_global', 'question_two_hop_statement']
which projects did I submit late?	'government project 3'	['question_type_global', 'question_two_hop_statement']
What department is [Cecil] affiliated with?	'english'	['question_type_local']
what are the homeworks that i submitted?	'government homework 1', 'statistics homework 2', 'government homework 2', 'statistics homework 3', 'english composition homework 2', 'microbiology homework 2'	['question_type_global', 'question_two_hop_statement']
[government] has a new [government project 4] out
What is the topic of [statistics homework 3]?	'cold war'	['question_type_local']
what are the courses for which i submitted late assignments?	'government', 'microbiology'	['question_type_global', 'question_two_hop_statement']
which assignments did I submit late?	'government homework 1', 'government project 3', 'microbiology homework 2'	['question_type_global', 'question_two_hop_statement']
[that project] is worth [69] points
What is [Milagros]'s email	'Milagros@nh.edu'	['question_type_local']
which homeworks are due before [March 21]?	'government homework 1', 'statistics homework 1'	['question_type_global', 'question_two_hop_statement']
what are all the projects due for [government]?	'government project 1', 'government project 2', 'government project 3', 'government project 4'	['question_type_global', 'question_two_hop_statement']
who did I submit projects late to	'Cecil'	['question_type_global', 'question_three_hop_statement']
[statistics homework 4] is released for [statistics]
I submitted [that homework]
[this assignment] is [11] points
How many points is [statistics homework 3] worth?	35	['question_type_local']
list all homeworks that i submitted	'government homework 1', 'statistics homework 2', 'government homework 2', 'statistics homework 3', 'english composition homework 2', 'microbiology homework 2', 'statistics homework 4'	['question_type_global', 'question_two_hop_statement']
show me all courses for which i submitted at least one late homework	'government', 'microbiology'	['question_type_global', 'question_two_hop_statement']
what homeworks do I have to do for [Cecil]?	'government homework 1', 'government homework 2'	['question_type_global', 'question_three_hop_statement']
who are the instructors to whom i submitted any late projects?	'Cecil'	['question_type_global', 'question_three_hop_statement']
I submitted [statistics homework 1] and received 63 points
how much did I get on [statistics homework 1]?	63	['question_type_local']
which professors did I submit late assignments for?	'Cecil'	['question_type_global', 'question_three_hop_statement']
who did I submit assignments late to	'Cecil'	['question_type_global', 'question_three_hop_statement']
show me all assignments that i submitted for [Genevive]	'statistics homework 1', 'statistics homework 2', 'statistics homework 3', 'statistics homework 4'	['question_type_global', 'question_three_hop_statement']
which assignments are due on [April 02]?	'english composition homework 2'	['question_type_global', 'question_two_hop_statement']
which courses did I submit late assignments for?	'government', 'microbiology'	['question_type_global', 'question_two_hop_statement']
list all projects that i submitted late	'government project 3'	['question_type_global', 'question_two_hop_statement']
How many points did I get on [government homework 1]	14	['question_type_local']
show me all the late projects that i submitted	'government project 3'	['question_type_global', 'question_two_hop_statement']
show me all late projects i submitted for [Cecil]	'government project 3'	['question_type_global', 'question_three_hop_statement']
[statistics homework 4] is due on [April 20]
list all homeworks for [statistics]	'statistics homework 1', 'statistics homework 2', 'statistics homework 3', 'statistics homework 4'	['question_type_global', 'question_two_hop_statement']
who are the professors?	'Cecil', 'Genevive', 'Lorilee', 'Luanna', 'Milagros', 'Andrew', 'Francoise', 'Rey', 'Lucy'	['question_type_global', 'question_single_statement']
Which professor is teaching [statistics]?	'Genevive'	['question_type_local']
show me all projects i submitted	'government project 1', 'microbiology project 1', 'english composition project 1', 'government project 3'	['question_type_global', 'question_two_hop_statement']
list all homeworks that i submitted for [Genevive]	'statistics homework 1', 'statistics homework 2', 'statistics homework 3', 'statistics homework 4'	['question_type_global', 'question_three_hop_statement']
[statistics] has a new [statistics project 1] out
The deadline of [statistics project 1] is [March 19]
[this assignment] is worth [46] points
